bitnami/jasperreports/Chart.yaml, bitnami/jasperreports/templates/deployment.yaml
=> [bitnami/jasperreports] Use custom probes if given

bitnami/external-dns/Chart.yaml, bitnami/external-dns/templates/deployment.yaml
=> [bitnami/external-dns] Use custom probes if given

bitnami/mariadb/Chart.yaml, bitnami/mariadb/templates/primary/statefulset.yaml, bitnami/mariadb/templates/secondary/statefulset.yaml
=> [bitnami/mariadb] Use custom probes if given

bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/templates/deployment.yaml
=> [bitnami/sonarqube] Use custom probes if given

bitnami/solr/Chart.yaml, bitnami/solr/templates/metrics-deployment.yaml, bitnami/solr/templates/statefulset.yaml
=> [bitnami/solr] Use custom probes if given

bitnami/phpbb/Chart.yaml, bitnami/phpbb/templates/deployment.yaml
=> [bitnami/phpbb] Use custom probes if given

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kafka/templates/statefulset.yaml, bitnami/kafka/values.yaml
Allow addition of labels to volume claim template in the StatefulSet.
Signed-off-by: Milan Sladky <milan.sladky@sentinelone.com>
Allow addition of labels to volume claim template in the StatefulSet.
=> [bitnami/kafka] Add labels to volume claim template

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/README.md, bitnami/rabbitmq/templates/_helpers.tpl
There are no mentions of `bitnami/` when it's related to the Helm repo in the README. They are replaced by a generic `my-repo`
Readme instructions can be followed regardless of the repository used to deploy the Helm charts
=> [bitnami/rabbitmq] Generic README instructions related to the repo

bitnami/mariadb-galera/Chart.yaml, bitnami/mariadb-galera/README.md, bitnami/mariadb-galera/templates/NOTES.txt, bitnami/mariadb-galera/templates/_helpers.tpl
There are no mentions of `bitnami/` when it's related to the Helm repo in the README. They are replaced by a generic `my-repo`
Readme instructions can be followed regardless of the repository used to deploy the Helm charts
=> [bitnami/mariadb-galera] Generic README instructions related to the repo

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/README.md, bitnami/postgresql-ha/templates/_helpers.tpl
There are no mentions of `bitnami/` when it's related to the Helm repo in the README. They are replaced by a generic `my-repo`
Readme instructions can be followed regardless of the repository used to deploy the Helm charts
=> [bitnami/postgresql-ha] Generic README instructions related to the repo

bitnami/contour/Chart.yaml
We always appreciate the initial contribution of @Cellebyte at https://github.com/bitnami/charts/pull/2069
On websites like [ArtifactHUB](https://artifacthub.io/packages/helm/bitnami/contour), the current maintainers are showed
=> [bitnami/contour] Update maintainers

bitnami/metallb/Chart.yaml
We always appreciate the initial contribution of @Cellebyte at https://github.com/bitnami/charts/pull/2068
On websites like [ArtifactHUB](https://artifacthub.io/packages/helm/bitnami/metallb), the current maintainers are showed
=> [bitnami/metallb] Update maintainers

bitnami/postgresql/Chart.yaml
We always appreciate the initial contribution of @desaintmartin when migrating this Helm chart from Helm stable
On websites like [ArtifactHUB](https://artifacthub.io/packages/helm/bitnami/postgresql), the current maintainers are showed
=> [bitnami/postgresql] Update maintainers

bitnami/redis/Chart.yaml
We always appreciate the initial contribution of @desaintmartin when migrating this Helm chart from Helm stable
On websites like [ArtifactHUB](https://artifacthub.io/packages/helm/bitnami/redis), the current maintainers are showed
=> [bitnami/redis] Update maintainers

bitnami/redmine/Chart.yaml, bitnami/redmine/templates/deployment.yaml
=> [bitnami/redmine] Use custom probes if given

bitnami/grafana-operator/Chart.yaml
We always appreciate the initial contribution of @Cellebyte at https://github.com/bitnami/charts/pull/3287
On websites like [ArtifactHUB](https://artifacthub.io/packages/helm/bitnami/grafana-operator), the current maintainers are showed
=> [bitnami/grafana-operator] Update maintainers

bitnami/redis/Chart.yaml, bitnami/redis/templates/sentinel/statefulset.yaml
Fixed typo that causes chart failed to render using DH param in TLS options.
Chart installation will no longer fails when setting DH param file in TLS options.
- fixes #11863
=> [bitnami/redis] Fixed typo that causes chart failed to render using DH param in TLS options.

.vib/redis/vib-publish.json
Fixes typo introduced in https://github.com/bitnami/charts/pull/12797 related to goss's vars file that is currently making the related Redis' publish pipeline fail. See: https://github.com/bitnami/charts/commit/7f3f7f7cd84b510f08ddddac1e395e36b2903812
Fixes Redis' publish workflow.
N/A
=> [bitnami/redis] Fix typo in publish pipeline definition

bitnami/grafana-loki/Chart.yaml, bitnami/grafana-loki/templates/table-manager/deployment.yaml
fixes a hardcoded path for the config in grafana-loki table-manager component
Changes to `.Values.loki.dataDir` will be used in table-manager as well
none
- mentioned in #12833
i was not able to test this, as i never deployed helm charts directly from the forked bitnami chart repo
=> [bitnami/grafana-loki]  fixed hardcoded table manager configpath

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/templates/_helpers.tpl
bitnami/jupyterhub 2.0.0
Set `hub.config.CryptKeeper.keys` and `hub.config.JupyterHub.cookie_secret` in `hub.configuration`. E.g:
```yaml
hub:
config:
CryptKeeper:
keys: XXXXXXXXXXXXXXXXXXX
JupyterHub:
cookie_secret: YYYYYYYYYYYYYYY
```
The provided values are not used in the hub secret, instead a random value is generated (or value in existing secret if available)
The template function `hasKey` doesn't support test of nested keys.
=> [bitnami/jupyterhub] Fix test existence nested key

bitnami/mysql/Chart.yaml, bitnami/mysql/README.md, bitnami/mysql/templates/primary/svc-headless.yaml, bitnami/mysql/templates/secondary/svc-headless.yaml, bitnami/mysql/values.yaml
Adds the ability to annotate the headless services. This is useful for a specific use case around externaldns for us.
More flexibility, in our case to add an externaldns annotation.
N/A
N/A
=> [bitnami/mysql] Add custom annotations to headless services

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/repo-server/metrics-svc.yaml
There is a bug in the current version of the chart:
repo-server/metrics-svc.yaml  references a non existing value which leads to nil pointer exception. 
``` "argo-cd/templates/repo-server/metrics-svc.yaml" at <.Values.service.annotations>: nil pointer evaluating interface {}.annotations``` 
We fixed this by simple replacing the wrong reference with the correct value:
```Values.service.annotations``` -> ```Values.repo-server.metrics.service.annotations```
No errors anymore when enabling metrics 
No
=> [bitnami/argo-cd] Fix wrong value reference

.github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline.yml
As described in the [documentation](https://github.com/vmware-labs/vmware-image-builder-action#action-input-parameters), the VMware Image Builder action accepts several parameters as inputs to customize its execution. These parameters are not meant to be defined at pipeline-level though, as they are inputs of the action.
This PR introduces logic to allow to define, per asset, this configuration by creating a file under `.vib/ASSET/vib-action.config`. It also adds initial support to recognize the `verification-mode` one.
Assets can define specific configurations to launch the VIB action, such as the `verification-mode`.
None, backward compatibility is maintained.
NA.
Tested in [joancafom-serial](https://github.com/joancafom/charts/actions/runs/3242108696/jobs/5314926901) and …
=> [bitnami/*] Allow VIB action configuration per asset

bitnami/dokuwiki/Chart.yaml, bitnami/dokuwiki/templates/deployment.yaml
=> [bitnami/dokuwiki] Use custom probes if given

bitnami/mariadb-galera/Chart.yaml, bitnami/mariadb-galera/templates/statefulset.yaml
=> [bitnami/mariadb-galera] Use custom probes if given

bitnami/oauth2-proxy/Chart.yaml, bitnami/oauth2-proxy/templates/deployment.yaml
=> [bitnami/oauth2-proxy] Use custom probes if given

bitnami/pytorch/Chart.yaml, bitnami/pytorch/templates/deployment.yaml, bitnami/pytorch/templates/statefulset.yaml
=> [bitnami/pytorch] Use custom probes if given

.vib/parse/vib-publish.json
There is a typo in the endpoint which is blocking releases due to the following error:
```
health-check( 07156f31-f051-4668-9d90-62523ca722bb ). Error:  The pipeline contains the following invalid fields: $.phases.verify.actions[0].params.port is required but it is missing (The field can be injected from the output attribute $.endpoints[?(@.name == 'lb-parse-dasboard-http-dashboard')].port of a previous 'deployment' action. Are {endpoint: lb-parse-dasboard-http-dashboard} valid values?). $.phases.verify.actions[0].params.host is required but it is missing (The field can be injected from the output attribute $.endpoints[?(@.name == 'lb-parse-dasboard-http-dashboard')].host of a previous 'deployment' action. Are {endpoint: lb-parse-dasboard-http-dashboard} valid values?)
```
See …
=> [bitnami/parse] Fix typo in the health-check endpoint blocking publishing

bitnami/parse/Chart.yaml
A typo in the CD pipeline prevented the chart from publishing in the index. After fixing the issue in https://github.com/bitnami/charts/pull/12976, this PR manually forces a new version of the chart to be created, uploaded, and listed in the index.
The index is updated with a new asset version, which includes all the changes in the GitHub repo.
None
NA
Related to https://github.com/bitnami/charts/pull/12976
=> [bitnami/parse] Force chart publishing

.github/workflows/cd-pipeline.yml
> **Notify unsuccessful CD run**
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: slackapi/slack-github-action
Taking a look at the version used for `slackapi/slack-github-action`:
```console
$ ag 'slackapi/slack-github-action' .github
.github/workflows/cd-pipeline.yml
243:        uses: slackapi/slack-github-action@v1.19.0
```
According to the above warning, we should bump the `slackapi/slack-github-action` version to `v1.23.0` everywhere in order to use the latest …
=> Bump slackapi/slack-github-action version from v1.19.0 to v1.23.0

.github/workflows/clossing-issues.yml, .github/workflows/stale.yml
> **Stale**
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/stale
Taking a look at the version used for `actions/stale`:
```console
$ ag 'actions/stale' charts/.github vms/.github containers/.github
charts/.github/workflows/stale.yml
15:      - uses: actions/stale@v4
26:      - uses: actions/stale@v4
charts/.github/workflows/clossing-issues.yml
13:      - uses: actions/stale@v4
vms/.github/workflows/stale.yml
10:      - uses: actions/stale@v3 …
```
=> Bump actions/stale version to v5

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/README.md, bitnami/rabbitmq/templates/ingress.yaml, bitnami/rabbitmq/templates/tls-secrets.yaml, bitnami/rabbitmq/values.yaml
Support ingress.existingSecret for rabbitmq
- fixes #
=> [bitnami/rabbitmq] Support ingress.existingSecret for Rabbitmq

.github/workflows/generate-chart-readme.yml
> **update-readme-metadata**
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/cache, actions/cache
Taking a look at the version used for `actions/cache`, currently, there is a mix of `v2` and `v3`:
```
$ ag 'actions/cache' charts/.github vms/.github containers/.github
charts/.github/workflows/generate-chart-readme.yml
24:        uses: actions/cache@v2
```
According to the above warning, we should bump the `actions/cache` version to `v3` everywhere in order to use …
=> Bump actions/cache version to v3

.github/workflows/ci-pipeline.yml
> **Reviewal for automated PRs**
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: reitermarkus/automerge, hmarr/auto-approve-action
Taking a look at the version used for `hmarr/auto-approve-action`:
```console
$ ag 'hmarr/auto-approve-action' charts/.github vms/.github containers/.github
charts/.github/workflows/ci-pipeline.yml
146:        uses: hmarr/auto-approve-action@v2.4.0
containers/.github/workflows/ci-pipeline.yml
178:        uses: …
```
=> Bump hmarr/auto-approve-action version to v3.0.0

bitnami/common/Chart.yaml, bitnami/common/templates/_secrets.tpl
Add quotes to password values when using `lookup`.
Helm release revisions >1 will keep quotes in secret values so checksum are consistent.
None known.
- fixes helm/helm#11144
- fixes #10985
Tested with a chart depending on `bitnami/rabbitmq` in version 10.1.14 (including `bitnami/common` in version 1.16.1).
First release revision contains the quotes in secrets (eg. `<release>-rabbitmq`) because the `lookup` is not done on first revision (the secret does not exist yet).
When creating a second revision, the quotes are gone because the secret value is fetch by `lookup` which return no quote as `kubectl` does.
Before this PR:
```bash
diff <(helm -n rabbitmq get manifest rabbitmq-test --revision 1) <(helm -n rabbitmq get manifest rabbitmq-test --revision 2)
```
```diff
<   rabbitmq-password: …
```
=> [bitnami/common] quote secret value when lookup

.github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline-extra-thanos.yml, .github/workflows/ci-pipeline.yml
This is a temporary workaround in order to solve an internal networking issue that is producing some actions to fail due to
```
Substituting variable VIB_ENV_TARGET_PLATFORM in parse/vib-publish.json
Warning: Environment variable VIB_ENV_ALTERNATIVE_TARGET_PLATFORM is set but is not used within pipeline parse/vib-publish.json
Substituting variable VIB_ENV_S3_URL in parse/vib-publish.json
Substituting variable VIB_ENV_S3_USERNAME in parse/vib-publish.json
Substituting variable VIB_ENV_S3_PASSWORD in parse/vib-publish.json
The pipeline has been validated successfully.
Request to /v1/pipelines failed. Retry: 0. Waiting 5000
Request to /v1/pipelines failed. Retry: 1. Waiting 10000
Request to /v1/pipelines failed. Retry: 2. Waiting 15000
Error: Could not execute operation. Retried 3 times.
```
=> Increase retry-count from 3 (default) to 6 in VIB action

.github/workflows/comments.yml, .github/workflows/moving-cards.yml, .github/workflows/sync-teams.yml, .github/workflows/triage.yml
> **label-card**
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: xom9ikk/dotenv, andymckay/labeler
Taking a look at the version used for `xom9ikk/dotenv`:
```console
$ ag 'xom9ikk/dotenv' charts/.github vms/.github containers/.github
charts/.github/workflows/triage.yml
23:        uses: xom9ikk/dotenv@v1.0.2
charts/.github/workflows/sync-teams.yml
19:        uses: xom9ikk/dotenv@v1.0.2
charts/.github/workflows/comments.yml
17:        uses: xom9ikk/dotenv@v1.0.2 …
```
=> Bump xom9ikk/dotenv version to v2

.github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline.yml
>*Get modified charts*
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: actions/github-script
Taking a look at the version used for `actions/github-script`, currently there is a mix of `v3` and `v6`:
```console
$ ag 'uses: actions/github-script' */.github
charts/.github/workflows/ci-pipeline.yml
78:        uses: actions/github-script@v3
charts/.github/workflows/cd-pipeline.yml
131:        uses: actions/github-script@v3
charts/.github/workflows/assign-asset-label.yml
35: …
```
=> Bump actions/github-script version to v6

bitnami/kafka/README.md
Added description on how to set `ssl.client.auth=required` in Kafka configuration. This is necessary for those that might need to use Kafka ACLs. This change is related with https://github.com/bitnami/charts/issues/12577
Signed-off-by: arasic <rasic.alis@gmail.com>
Updated README.md file only - Added extra docs on how to set `set ssl.client.auth=required` in Kafka configuration. This is necessary for those that might need to use Kafka ACLs.
Having the necessary documentation will make the life easier for future developers so that they do not have to look in the templates/code about the logic behind. This option is necessary for those that will need to use Kafka ACLs (AclAuthorizer).
Not aware of any.
This PR is related with Issue #12577
None.
=> [bitnami/kafka] Added description on how to set ssl.client.auth=required in Kafka configuration

.vib/postgresql-ha/vib-publish.json
The publish pipeline for `bitnami/postgresql-ha` is failing because the endpoint used in the health-check action was not updated in https://github.com/bitnami/charts/pull/12713.
The publish pipeline succeeds hereon.
None
Failed publish action: https://github.com/bitnami/charts/actions/runs/3295703998/jobs/5434524413
=> [bitnami/postgresql-ha] Fix typo in CD health-check endpoint

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kafka/templates/kafka-provisioning.yaml, bitnami/kafka/values.yaml
Added `nodeSelector` to the provisioning job. This matches the `statefulset` and `kafka-metrics-deployments` YAML.
The chart user can control on which nodes the batch pods are scheduled. For example at the moment on a mixed Linux/Windows cluster the provisioning job can end up on Windows nodes incorrectly.
None
- fixes #
The provisioning batch does not include support for `podAffinity`, `podAntiAffinity` or `nodeAffinity`.
=> [bitnami/kafka] Add nodeSelector to Kafka provisioning

bitnami/redis/Chart.yaml, bitnami/redis/templates/tls-secret.yaml
Signed-off-by: Celia Garcia Marquez <gcelia@vmware.com>
Fix redis-master-api-svc-local missing in auto generated cert altnames.
- fixes #12172
=> [bitnami/redis] Fix redis master.api.svc.cluster.local missing

bitnami/metallb/Chart.yaml, bitnami/metallb/templates/_helpers.tpl
Fixes the service account name when disabling it.
- fixes #
=> [bitnami/metallb] Fix service account name handling

template/CHART_NAME/templates/deployment.yaml
In values.yaml, autoscaling is nested under %%MAIN_OBJECT_BLOCK%%.
Signed-off-by: Brad Solomon <81818815+brsolomon-deloitte@users.noreply.github.com>
=> [bitnami/template] Fix autoscaling reference in template chart deployment

bitnami/kong/Chart.yaml, bitnami/kong/templates/ingress-controller-rbac.yaml
This change adds missing persmissions on ingressclassparameterses.
Issue: https://github.com/bitnami/charts/issues/13005
=> [bitnami/kong] Adds missing get/list/watch permissions for ingressclassparameterses

bitnami/common/Chart.yaml, bitnami/common/templates/_ingress.tpl
`kubernetes.io/tls-acme` should be an acceptable Ingress annotation to trigger creation of the IngressTLS array. Many clusters run cert-manager with a default issuer configured for [fully automated TLS](https://cert-manager.io/docs/usage/ingress/#optional-configuration). This PR addresses that in the `_ingress.tpl` template of the bitnami/common Chart.
Clusters admins / operators no longer need to tie their deployments to specific certificate issuers. In many cases this is already defined in the cluster's cert-manager deployment (if present).
This change does not interfere with previous deployments so there are no known limitations. The only possible drawback would be if `kubernetes.io/tls-acme` is defined without a desire for a IngressTLS array - perhaps when set to `false`, however, …
=> [bitnami/common] kubernetes.io/tls-acme Ingress annotation triggers IngressTLS array

bitnami/kong/Chart.yaml, bitnami/kong/templates/ingress-controller-rbac.yaml
This PR updates the RBACs to match the [upstream ones](https://github.com/Kong/charts/blob/aa8ac50d5d8e97493175ccf257c2dc86a8198668/charts/kong/templates/controller-rbac-resources.yaml).
Kong Ingress Controller pod does not enter a constant `CrashLoopBackOff` state by being unable to list the new CRDs.
None
NA
CRDs were updated in https://github.com/bitnami/charts/pull/12978, but we missed updating RBACs as well.
=> [bitnami/kong] Sync upstream RBAC

.github/workflows/sync-chart-index.yaml, bitnami/index.html
We should serve a simple `index.html` file from the root of the Helm repository instead of the whole `index.yaml` file.
This will serve two purposes:
- Help end users configure Bitnami's Helm repository.
- Reduce the traffic for non-helm requests (helm CLI always asks for `index.yaml` specifically).
None that I can think of, since all current features will be kept.
None.
N/A
=> Serve minimal index.html file at the root of the Helm repository

bitnami/node/Chart.lock, bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/node/templates/NOTES.txt, bitnami/node/values.yaml
The Node.js helm chart will be deprecated
=> [bitnami/node] Deprecate NodeJS Helm chart

bitnami/sealed-secrets/Chart.yaml, bitnami/sealed-secrets/README.md, bitnami/sealed-secrets/values.yaml
This aligns the sealed-secrets pod with the [pod security standards](https://kubernetes.io/docs/concepts/security/pod-security-standards/#restricted)
Sealed secrets will pass the restricted baseline validation
We're running with these settings, and nothing appears to be broken
=> [bitnami/sealed-secrets] fix: Align sealed-secrets security context to the pod security standards

bitnami/common/Chart.yaml, bitnami/common/templates/_secrets.tpl
This PR adds a new common function, that depends on the Helm `lookup` function.
This function searches for a key in an existing secret, otherwise sets a default value.
This function can be used to prevent regenerating secrets when upgrading, for example, for autogenerated certs.
Currently, we do not have a method to lookup for a value in an existing secret, and it could be used, for example, in cases like this:
```diff
-  ca.crt: {{ $ca.Cert | b64enc | quote }}
-  tls.crt: {{ $crt.Cert | b64enc | quote }}
-  tls.key: {{ $crt.Key | b64enc | quote }}
+  ca.crt: {{ include "common.secrets.lookup" (dict "secret" $secretName "key" "ca.crt" "defaultValue" $ca.Cert "context" $) }}
+  tls.crt: {{ include "common.secrets.lookup" (dict "secret" …
```
=> [bitnami/common] Add new function 'common.secrets.lookup'

.github/workflows/assign-asset-label.yml, .github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline.yml, .github/workflows/moving-cards.yml, .github/workflows/srp-report.yml, .github/workflows/triage.yml
The `set-output` command is deprecated and will be disabled soon. Here we upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Code is up to date and warnings disappear from action runs.
Execution examples:
* https://github.com/fmulero/charts/actions/runs/3330002252
* https://github.com/fmulero/charts/actions/runs/3330893295
=> [bitnami/charts] Use Environment Files instead of set-output

.github/workflows/moving-cards.yml
Use compact output in jq to retrieve the assignee list in order to avoid multiline output.
In #13158 the set-output command was change to use the output file. [Multiline outputs](https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings) has to be adapted
None
Errors in actions like: https://github.com/bitnami/charts/actions/runs/3338362010/jobs/5525932191
Follow up #13158
=> [bitnami/charts] Compact output for assignee list

.github/workflows/clossing-issues.yml, .github/workflows/stale.yml
The `set-output` command is deprecated and will be disabled soon. Here we upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/. In #13158 we covered the main part but we missed the `actions/stale`because we weren't using the [latest version](https://github.com/actions/stale/releases/tag/v6.0.1) which fixes it.
Code is up to date and warnings disappear from action runs.
=> [bitnami/charts] Upgrading actions/stale version to remove set-output usage

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/secret-external-db.yaml
Fixes the following error on deployment:
```
STDERR:
Error: UPGRADE FAILED: execution error at (keycloak/templates/secret-external-db.yaml:16:18):
PASSWORDS ERROR: The secret "keycloak-dev-externaldb" does not contain the key "password"
```
How to reproduce:
1. install the Keycloak chart v11.0.0 for the first time - it works
2. re-install the same chart: it fails with the error above because this time the secret exists but the key name is wrong.
Signed-off-by: Stefano Zaninetta <stefano.zaninetta@nagra.com>
=> [bitnami/keycloak] Fix reference to external db secret password key

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/statefulset.yaml
Removes additional `-}}` which was causing rendering issues.
- fixes #13206
=> [bitnami/keycloak] Fix SPI truststore env

.github/workflows/ci-pipeline.yml
> *Reviewal for automated PRs*
> Node.js 12 actions are deprecated. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/. Please update the following actions to use Node.js 16: reitermarkus/automerge, hmarr/auto-approve-action
{quote}
Taking a look at the version used for `reitermarkus/automerge`:
```console
$ ag 'reitermarkus/automerge' charts/.github vms/.github containers/.github
charts/.github/workflows/ci-pipeline.yml
136:        uses: reitermarkus/automerge@v2.1.2
containers/.github/workflows/ci-pipeline.yml
170:        uses: reitermarkus/automerge@v2.1.2
``` …
=> Bump reitermarkus/automerge version

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/query/deployment.yaml
Signed-off-by: Boris Kreitchman <bkreitch@gmail.com>
A container using a ConfigMap as a subPath volume mount does not receive ConfigMap updates, so currently Query doesn't see the changes to servicediscovery.yml. This PR removes subPath and mounts volume on a directory to allow ConfigMap updates and automatic reloads.
Allows automatic reloads of Query servicediscovery.yml
- fixes #
=> [bitnami/thanos] Remove subPath from servicediscovery.yml

bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md, bitnami/keycloak/templates/configmap-env-vars.yaml, bitnami/keycloak/templates/headless-service.yaml, bitnami/keycloak/templates/statefulset.yaml, bitnami/keycloak/values.yaml
Add the possibility to use cache stacks beside the default 'kubernetes' one as well as additional ports used by those stacks.
The change allows the chart to be used in environments where infinispan discovery and communication does not work according to the standard kubernetes stack. This is the case, for example, in the context of the istio service mesh or even when a remote infinispan cluster is configured as cache store. Then additional port mappings and adjustments to the stack are required.
See https://www.keycloak.org/server/caching for caching-options supported out-of-the-box by keycloak.
None, as only optional parameters are added.
=> [bitnami/keycloak] Add support for custom infinispan/jgroups cache stacks (e.g. istio)

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/redis-statefulset.yaml, bitnami/redis-cluster/templates/scripts-configmap.yaml, bitnami/redis-cluster/templates/update-cluster.yaml
The name of the environment variables in the container are:
- [REDIS_PORT_NUMBER](https://github.com/bitnami/containers/blob/512680642767755f31c5552b8048a49be14ab9f7/bitnami/redis/7.0/debian-11/rootfs/opt/bitnami/scripts/redis-env.sh#L32)
- [REDIS_TLS_PORT_NUMBER](https://github.com/bitnami/containers/blob/512680642767755f31c5552b8048a49be14ab9f7/bitnami/redis/7.0/debian-11/rootfs/opt/bitnami/scripts/redis-env.sh#L45)
- fixes #13270
=> [bitnami/redis-cluster] Fix port number enviroment variables name

bitnami/tomcat/Chart.yaml, bitnami/tomcat/templates/NOTES.txt, bitnami/tomcat/templates/secrets.yaml
Signed-off-by: Daniel Haß <danielhass@users.noreply.github.com>
https://github.com/bitnami/charts/issues/12296 https://github.com/bitnami/charts/issues/13048
Removing the enforced check of the `tomcatPassword` value on subsequent upgrades and moving the secret generation from an in chart conditional to the commons `common.secrets.passwords.manage` function.
From my understanding this enforcement of the `tomcatPassword` being set on subsequent upgrades is not necessary as the password is stored properly inside a Kubernetes Secret that is evaluated automatically on every container startup.
- fixes #13048
- fixes #12296
=> [bitnami/tomcat] Removed enforcement of tomcatPassword variable on upgrades

bitnami/postgresql/Chart.yaml, bitnami/postgresql/README.md, bitnami/postgresql/templates/primary/svc-headless.yaml, bitnami/postgresql/templates/read/svc-headless.yaml, bitnami/postgresql/values.yaml
Similar to https://github.com/bitnami/charts/pull/12295 this adds the ability to annotate the headless services. This is useful for a specific use case around externaldns for us.
More flexibility, in our case to add an externaldns annotation.
N/A
N/A
=> [bitnami/postgresql] Annotations for headless service

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/_helpers.tpl, bitnami/thanos/templates/serviceaccount.yaml
The template/serviceaccount file sets its name value using the _helpers.tlp file just like the other assets and not the common fullname value.
The format is the same as the other assets and the value is really being set with the value indicated
In addition, the logic of assigning the value of the serviceAccount.name variable in the _helpers.tlp file has been modified so that, when the value of serviceAccount.name in the values.yaml is set, it uses that value instead of the default value. .
- Fixes https://github.com/bitnami/charts/issues/12954
=> [bitnami/thanos] Modified logic for serviceAccount name in Thanos

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/README.md, bitnami/elasticsearch/templates/metrics/deployment.yaml, bitnami/elasticsearch/values.yaml
Signed-off-by: Anton Patsev <patsev.anton@gmail.com>
Fix failed metrics pod in elasticsearch when deploying elasticsearch
Fixed bug https://github.com/bitnami/charts/issues/12957
Limitations: run metrics after running core pods elasticsearch
- fixes #12957
- continues https://github.com/bitnami/charts/pull/12959
=> [bitnami/elasticsearch] Fix failed metrics pod in elasticsearch when deploy ES

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/configmap-env-vars.yaml
Bugfix. Chart uses the wrong value for its SPI truststore file.
Bugfix
%
%
%
=> [bitnami/keycloak] Use correct value for SPI truststore file

bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/crds/crd-rabbitmq-cluster.yaml, bitnami/rabbitmq-cluster-operator/crds/crds-messaging-topology-operator.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/clusterrole.yaml
Signed-off-by: David van der Spek <vanderspek.david@gmail.com>
This PR updates the CRDs for the RabbitMQ Cluster Operator and RabbitMQ Messaging Topology Operator.
The CRDs have changed since they were last synced so they should be updated.
The CRDs for the RabbitMQ Messaging Topology Operator were generated for `v1.9.0`. The current image is for `v1.8.0`, so a new image for the correct version should be built.
If the RabbitMQ Messaging Topology Operator is updated to `v1.9.0`, the RBAC needs to be updated for a new CRD type. This RBAC update is included in this PR.
- fixes #
=> [bitnami/rabbitmq-cluster-operator] update the rabbitmq operator CRDs

bitnami/opencart/Chart.yaml, bitnami/opencart/templates/deployment.yaml
Allows using an existing secret for opencart password and SMTP password. 
Signed-off-by: Ricardo Herrera <rickhl@outlook.com>
Fixes a bug where using an `existingSecret` for opencart password and/or SMTP password does not result in the secret being used.
Allow `existingSecrets` to be used for opencart password and SMTP password.
None.
None
No
=> [bitnami/opencart] Use templated values for opencart secret name

bitnami/postgresql/README.md
Fix the PostgreSQL Helm Chart security config for OpenShift. Since the major version 11 of the helm chart, the mentioned config is no longer working on OpenShift.
The PostgreSQL Helm Chart will have an appropriate documentation for OpenShift again. 
Not known.
- fixes #
Example of how it is executed on OpenShift:
```yaml
spec:
containers:
- name: postgresql
...
securityContext:
allowPrivilegeEscalation: false
capabilities:
drop:
- ALL
runAsNonRoot: true
runAsUser: 1000990000
...
initContainers:
- command:
...
name: copy-certs
securityContext:
allowPrivilegeEscalation: false
capabilities:
drop:
- ALL
runAsNonRoot: true
runAsUser: 1000990000
...
securityContext:
fsGroup: 1000990000
seLinuxOptions:
level: s0:c31,c25
seccompProfile:
type: RuntimeDefault
```
=> [bitnami/postgresql] Update OpenShift specifc security settings

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/templates/deployment.yaml
The proper argument name is `--zap-log-level` (see https://github.com/grafana-operator/grafana-operator/blob/955daa6abb9b6efe85d921a783eeffd51853fae4/documentation/deploy_grafana.md?plain=1#L87)
=> [bitnami/grafana-operator] Fix wrong argument name for parameter `zapLevel`

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/_helpers.tpl, bitnami/thanos/templates/bucketweb/deployment.yaml, bitnami/thanos/templates/bucketweb/serviceaccount.yaml, bitnami/thanos/templates/compactor/deployment.yaml, bitnami/thanos/templates/compactor/serviceaccount.yaml, bitnami/thanos/templates/query-frontend/deployment.yaml, bitnami/thanos/templates/query-frontend/psp-clusterrolebinding.yaml, bitnami/thanos/templates/query-frontend/serviceaccount.yaml, bitnami/thanos/templates/query/deployment.yaml, bitnami/thanos/templates/query/psp-clusterrolebinding.yaml, bitnami/thanos/templates/query/serviceaccount.yaml, bitnami/thanos/templates/receive-distributor/deployment.yaml, bitnami/thanos/templates/receive-distributor/serviceaccount.yaml, bitnami/thanos/templates/receive/serviceaccount.yaml, bitnami/thanos/templates/receive/statefulset.yaml, bitnami/thanos/templates/ruler/serviceaccount.yaml, bitnami/thanos/templates/ruler/statefulset.yaml, bitnami/thanos/templates/serviceaccount.yaml, bitnami/thanos/templates/storegateway/serviceaccount.yaml, bitnami/thanos/templates/storegateway/statefulset-sharded.yaml, bitnami/thanos/templates/storegateway/statefulset.yaml
The template/serviceaccount file sets its name value using the _helpers.tlp file just like the other assets and not the common fullname value.
The format is the same as the other assets and the value is really being set with the value indicated.
- Fixes https://github.com/bitnami/charts/issues/13378
=> [bitnami/thanos] Fix serviceAccount name logic for Thanos

.github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline-extra-thanos.yml, .github/workflows/ci-pipeline.yml
In this PR we are using a specific version for the [VIB action](https://github.com/marketplace/actions/vmware-image-builder) in order to avoid breaking changes when using the latest code
=> Use 0.4.7 as pinned version for vib action

bitnami/mysql/Chart.yaml, bitnami/mysql/README.md, bitnami/mysql/templates/primary/statefulset.yaml, bitnami/mysql/templates/secondary/statefulset.yaml, bitnami/mysql/values.yaml
MySQL chart, in some scenarios with a more controlled Volume, we may need to use a custom path for it.
This will provide a new parameter to the MySQL helm chart to use a custom subPath for persistence volume
- fixes #
=> [bitnami/mysql] Added support for MySQL volume subPath

bitnami/spark/Chart.yaml, bitnami/spark/templates/statefulset-master.yaml, bitnami/spark/templates/statefulset-worker.yaml
Changed the mount path of shared-certs volume in Apache Spark chart.
Successful deployment when SSL is enabled for Apache Spark. This change allows Spark to find the certificates in default location where it search them.
https://github.com/bitnami/charts/issues/13290 issue.
=> [bitnami/spark]  Fixed the mount path of shared-certs volume

bitnami/sealed-secrets/Chart.yaml, bitnami/sealed-secrets/README.md, bitnami/sealed-secrets/values.yaml
Signed-off-by: Alfredo Garcia <algarcia@vmware.com>
Fixes the Sealed Secrets chart readme links
Links to the Bitnami Sealed Secrets documentation are not correct in the `README` file; this PR modifies the links to the appropriate URL. 
None.
=> [bitnami/sealed-secrets] Fixes the Sealed Secrets chart readme links

bitnami/redis/Chart.yaml, bitnami/redis/README.md, bitnami/redis/templates/master/application.yaml, bitnami/redis/templates/replicas/statefulset.yaml, bitnami/redis/templates/sentinel/statefulset.yaml, bitnami/redis/values.yaml
Add support for subPathExpr field to construct subPath directory names.
subPathExpr field can be used to construct subPath directory name based on environment variables
- fixes #
=> [bitnami/redis] Add support for volume subPathExpr

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/statefulset.yaml
Signed-off-by: Cyril Jouve <jv.cyril@gmail.com>
see #13428
- drop removed options in java11
- replace deprecated options by "new" ones
- fixes #13428
- fixes #13071 
tested with:
``` yaml
metrics:
jmx:
enabled: true
resources:
limits: 1Gi
``` 
=>
```
VM settings:
Max. Heap Size (Estimated): 989.88M
Using VM: OpenJDK 64-Bit Server VM
```
=> [bitnami/kafka] fix memory opts for jmx-exporter

bitnami/tomcat/Chart.yaml, bitnami/tomcat/templates/_pod.tpl
Signed-off-by: Cyril Jouve <jv.cyril@gmail.com>
see https://github.com/bitnami/charts/issues/
* drop removed options in java11
* replace deprecated options by "new" ones
- related to #13428 and #13445
=> [bitnami/tomcat] fix memory opts for jmx-exporter

bitnami/solr/Chart.yaml, bitnami/solr/README.md, bitnami/solr/templates/pdb.yaml, bitnami/solr/values.yaml
Add PodDisruptionBudget for chart `solr`.
We have a setup with three solr pods. When upgrading our cluster (GKE) we sometimes experience prolonged startup times of the solr pods cause of conditions we can't influence. Sometimes these are so severe, that all three pods are down at the same time, rendering solr unfunctional.
With this PodDisruptionBudget I added, one can guarantee that at least some pods are available (`minAvailable`) or at most some pods are unavailable (`maxUnavailable`).
There are no known drawbacks.
n/a
n/a
=> [bitnami/solr] Add PodDisruptionBudget

bitnami/cert-manager/Chart.yaml, bitnami/cert-manager/README.md, bitnami/cert-manager/templates/_helpers.tpl, bitnami/cert-manager/values.yaml
Following the upstream nomenclature, all the occurrences of _Cert Manager_ were replaced by _cert-manager_.
Related to https://github.com/bitnami/containers/pull/13324
=> [bitnami/cert-manager] Rename Cert Manager to cert-manager

.github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline-extra-thanos.yml, .github/workflows/ci-pipeline.yml
This version should include changes from the following PR:
* https://github.com/vmware-labs/vmware-image-builder-action/pull/104
**Changelog**:
* Timeouts are now 120s
* There is a new info log line that will print on slow requests (>60s)
* Removed the stack from the trace on retries and almost reverted to the simpler format that we had before plus a couple of additional pieces of info.
=> Use 0.4.11 as pinned version for vib action

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/serviceaccount.yaml
Fixes an issue with the serviceaccount.yaml template introduced in #13312, where the helper 'thanos.serviceAccountName' is missing its arguments.
We could either use `component=""` or revert back to `common.names.fullname`.
The benefits of using `component=""` is that the ServiceAccount name can be created using the name `.Values.serviceAccount.name`.
- fixes #13466
=> [bitnami/thanos] Fix issue with serviceAccount.create

bitnami/fluentd/Chart.yaml, bitnami/fluentd/values.yaml
Signed-off-by: Petrus.Z <silencly07@gmail.com>
Fix extraEnvVars typo in comments of the values.yaml file.
Make values.yaml more clear.
=> [bitnami/fluentd] fix extraEnvVars typo in values.yaml

bitnami/redis/Chart.yaml, bitnami/redis/templates/_helpers.tpl
The `auth.existingSecret` parameter can now include Helm templating.
This allows users of the chart to derive the name of the secret from other variables, like the release name.
It could cause backwards incompatibility if existing users used characters in their secret name that could be misinterpreted as Helm templating syntax, but I don't think there are any such characters that would have previously referred to a valid secret name.
- Fixes #13503
N/A
=> [bitnami/redis] Allow auth.existingSecret to be templated

bitnami/nats/Chart.yaml, bitnami/nats/README.md, bitnami/nats/templates/_helpers.tpl, bitnami/nats/templates/statefulset.yaml, bitnami/nats/values.yaml
This PR adds support for [NATS JetStream](https://docs.nats.io/nats-concepts/jetstream)
Users can deploy a NATS cluster with JetStream enabled.
None
N/A
N/A
=> [bitnami/nats] Add support for JetStream

bitnami/solr/Chart.yaml, bitnami/solr/templates/pdb.yaml
In #13463 I added a PDB for `solr`. Turns out, the provided `common.labels.matchLabels` are not sufficient: The `solr-exporter` uses the same set. They are only distinguishable by the label `app.kubernetes.io/component`. Values are `solr` or `exporter` of which we need to match `solr`.
This PR adds the label directly in template pdb.yaml. I'm not sure if this is the right way, so feel free to criticize.
PDB can distinguish between `solr` and `solr-exporter`.
There are no known drawbacks.
n/a
n/a
=> [bitnami/solr] Add "app.kubernetes.io/component: solr" to matchLabels

bitnami/mariadb/Chart.yaml, bitnami/mariadb/README.md, bitnami/mariadb/templates/primary/statefulset.yaml, bitnami/mariadb/templates/secondary/statefulset.yaml, bitnami/mariadb/values.yaml
Adding support for RuntimeClass into MariaDB helm chart
It allows the MariaDB workload to run on FireCracker, CloudHypervisor, Sysbox, gVisor...etc
=> [bitnami/mariadb]: Add support for RuntimeClass

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/README.md, bitnami/redis-cluster/templates/configmap.yaml, bitnami/redis-cluster/templates/redis-statefulset.yaml, bitnami/redis-cluster/values.yaml
* Adds support to disable persistence (uses emptyDir instead of a PVC). This is required if one wants to use Redis with in-memory data only. It makes sense to disable AOF and RDB persistence in the config in that case.
```
appendonly no
save ""
```
* Adds support to supply a custom Redis configuration, e.g. to support an older version of Redis. With the current setup the config is hard-coded and not backwards compatible, so the current chart version can't be used with an older version or Redis.
Adds additional features already covered, e.g. in the bitnami/redis chart. Does not change the default behavior and the changes are fully backwards compatible.
Additional complexity
- fixes #4484
- fixes #13409
=> [bitnami/redis-cluster] add support to disable persistence and add custom config

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/README.md, bitnami/kube-prometheus/templates/prometheus-operator/deployment.yaml, bitnami/kube-prometheus/values.yaml
Support specifying the namespaces that the prometheus-operator watches.
Chart can co-exists with 'Openshift Monitoring' (or presumably multiple operator-versions in a single cluster)
None known 
- fixes #13525
First time PR here - hope I got this right. I will be AFK for a couple of weeks from the end of the week - so I haven't died if we don't get this in before then.
=> [bitnami/kube-prometheus] Support prometheus-operator namespace allowlist. (#13525)

bitnami/mysql/Chart.yaml, bitnami/mysql/README.md, bitnami/mysql/templates/primary/statefulset.yaml, bitnami/mysql/templates/secondary/statefulset.yaml, bitnami/mysql/values.yaml
Adding support for RuntimeClass into MySQL helm chart
It allows the MySQL workload to run on FireCracker, CloudHypervisor, Sysbox, gVisor...etc
=> [bitnami/mysql]: Add support for RuntimeClass

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/common-scripts-cm.yaml
Adds support for envvars usage inside `tls.extraDnsNames`.
- fixes #13519
=> [bitnami/mongodb] Add support for envvars in tls.extraDnsNames

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/templates/_helpers.tpl, bitnami/postgresql-ha/templates/pgpool/deployment.yaml, bitnami/postgresql-ha/templates/postgresql/statefulset.yaml, bitnami/postgresql-ha/templates/serviceaccount.yaml
creating dedicated helper for postgresql-ha to comply to the existing values.yaml
comply to the existing values.yaml
none
- fixes #](https://github.com/bitnami/charts/issues/13629)
=> [bitnami/postgresql-ha]  create serviceAccountName helper

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/coordinating/hpa.yaml
[bitnami/elasticsearch] fix wrong apiversion for statefulset
=> [bitnami/elasticsearch] fix wrong apiversion for statefulset

bitnami/wavefront-hpa-adapter/Chart.yaml, bitnami/wavefront-hpa-adapter/templates/custom-metrics-apiserver-auth-delegator-cluster-role-binding.yaml, bitnami/wavefront-hpa-adapter/templates/custom-metrics-apiserver-resource-reader-cluster-role-binding.yaml, bitnami/wavefront-hpa-adapter/templates/hpa-custom-metrics-cluster-role-binding.yaml, bitnami/wavefront-hpa-adapter/templates/hpa-external-metrics-cluster-role-binding.yaml
[bitnami/wavefront-hpa-adapter] fix apiversion hardcode ClusterRoleBinding
=> [bitnami/wavefront-hpa-adapter] fix apiversion hardcode ClusterRoleBinding

bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/clusterrole.yaml
[bitnami/rabbitmq-cluster-operator] RabbitMQ messaging topology operator allow edit secrets in clusterrole (bitnami#13497)
Since [messaging-topology-operator/user_controller.go](https://github.com/rabbitmq/messaging-topology-operator/blob/main/controllers/user_controller.go#L57) introduce autogenerated user password when it's empty in predefined secret, the operator has to be able to update this secret.
Successful User reconciliation with updated secret.
=> [bitnami/rabbitmq-cluster-operator] RabbitMQ messaging topology operator allow edit secrets in clusterrole (bitnami#13497)

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/templates/postgresql/metrics-service.yaml, bitnami/postgresql-ha/templates/postgresql/servicemonitor.yaml
Added / updated the condition for annotations rendering in the following files:
- `bitnami/postgresql-ha/templates/postgresql/metrics-service.yaml`
- `bitnami/postgresql-ha/templates/postgresql/servicemonitor.yaml`
When enabling the metrics in the `postgresql-ha` value file, helm now do not complain with rendering chart.
- fixes https://github.com/bitnami/charts/issues/13373
=>  [bitnami/postgresql-ha]: fixes helm chart rendering when enabling metrics

bitnami/common/Chart.yaml, bitnami/common/templates/_affinities.tpl
Signed-off-by: Kazimieras <kazimieras@omnisend.com>
Fix topology key assignment. Could not assign from app chart as string, required nested dict.
Simplified `default` assignment
Fix
None as this functions is not adopted in other charts
In app chart it was desired to have this topology config:
```
topologyKey: topology.kubernetes.io/zone
```
but current implementation worked only with:
```
topologyKey: 
topologyKey: topology.kubernetes.io/zone
```
=> [bitnami/common] fix common topology key affinity function

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml, bitnami/mongodb-sharded/templates/mongos/mongos-dep-sts.yaml
Fix rendering topologySpreadConstraints in mongodb-sharded.
=> [bitnami/mongodb-sharded] fix rendering topologySpreadConstraints

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/alert-rule/absent_rules.yml, bitnami/thanos/templates/alert-rule/compaction.yml, bitnami/thanos/templates/alert-rule/query.yml, bitnami/thanos/templates/alert-rule/receive.yml, bitnami/thanos/templates/alert-rule/replicate.yml, bitnami/thanos/templates/alert-rule/ruler.yml, bitnami/thanos/templates/alert-rule/sidecar.yml, bitnami/thanos/templates/alert-rule/store_gateway.yml
When setting `prometheusRule.enabled: true` in chart verstion 11.6.1 those CRDs resources fail with: 
> Helm upgrade failed: error while running post render on files: may not add resource with an already registered id
Issue is that it wants to create all of `PrometheusRule` resources with the same name in the same namespace.
This will add suffix referring to components that rules are for which will set different names to all those resources.
Maybe some better logic instead of hardcoding these. Though it should be ok since its related to this specific chart and should not clash with other resources of the same kind.
None that I know off.
=> [bitnami/thanos] update PrometheusRule names to be unique

bitnami/contour/Chart.yaml, bitnami/contour/templates/contour/rbac.yaml
Adds missing RBAC that allows Contour to watch [Gateway API ReferenceGrants](https://gateway-api.sigs.k8s.io/api-types/referencegrant/).
This change follows what was done in upstream Contour for 1.23 release (1.23 is the app version for latest Contour Helm chart from this repo) https://github.com/projectcontour/contour/commit/c74c33a84f16c6a3818967c0c0232ec2e90061c0
Users will be able to use this Helm chart to install Contour v1.23 for use with Gateway API in ['static'](https://projectcontour.io/guides/gateway-api/#:~:text=Option%20%231%3A%20Statically%20provisioned) mode.
#11722 
To reproduce the bug:
```bash
// Apply Gateway API CRDs
kubectl apply -f https://github.com/kubernetes-sigs/gateway-api/releases/download/v0.5.1/experimental-install.yaml
// install Contour in 'static' mode
cat …
```
=> [bitnami/contour] adds missing RBAC to watch Gateway API ReferenceGrants

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kafka/templates/svc-external-access.yaml, bitnami/kafka/templates/svc-headless.yaml, bitnami/kafka/values.yaml
Signed-off-by: David Ballano <dfernandez@demonware.net>
lets you chose if you want to keep the endpoints under headless and external service services when pods are not ready yet.
this is closer to what kafka behaviour should be.
Once you have enabled the setting you could modify the readiness prod or prestop/prestart hooks in order to slow down rolling restart for example.
there is no drawbacks, this is how bitnamis zookeeper chart works by default..
- fixes https://github.com/bitnami/charts/issues/13129
N/A
=> [bitnami/kafka] Adding publishNotReadyAddresses to kafka services headless and external.

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/templates/NOTES.txt, bitnami/postgresql-ha/templates/pgpool/deployment.yaml, bitnami/postgresql-ha/templates/postgresql/secrets.yaml, bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
Align postgresql and postgresql-ha secrets
with this change, the postgresql and postgresql-ha Helm charts can be switch to each other without changing the application mount point
none
- Fixes https://github.com/bitnami/charts/issues/13660
=> [bitnami/postgresql-ha] Align postgresql and postgresql-ha secrets

.github/workflows/cd-pipeline.yml, .vib/kubeapps/cypress/cypress.json, .vib/kubeapps/cypress/cypress/fixtures/releases.json, .vib/kubeapps/cypress/cypress/integration/kubeapps_spec.js, .vib/kubeapps/cypress/cypress/support/commands.js, .vib/kubeapps/cypress/cypress/support/index.js, .vib/kubeapps/cypress/cypress/support/utils.js, .vib/kubeapps/goss/goss.yaml, .vib/kubeapps/goss/vars.yaml, .vib/kubeapps/vib-publish.json, .vib/kubeapps/vib-verify.json
The main objective of this PR is to publish our Bitnami Kubeapps Helm Chart using VMware Image Builder. In order to do that, several changes are included:
- Increasing the existing test coverage of the asset by adding Goss tests.
NA
Tested in https://github.com/joancafom/charts/pull/99
=> [bitnami/kubeapps] Add tests and publishing using VIB

bitnami/geode/Chart.yaml, bitnami/geode/README.md, bitnami/geode/templates/NOTES.txt
The bitnami/geode chart will be deprecated and won't receive new updates.
=> [bitnami/geode] Mark chart as deprecated

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
First determine if this charts will create the secret (a.k.a no `postgresql.existingSecret` is defined, using [ `postgresql-ha.postgresqlCreateSecret`](https://github.com/bitnami/charts/blob/main/bitnami/postgresql-ha/templates/_helpers.tpl#L304)), if so it will use the new `password` envFrom key. In case there is a custom secret provided it will lookup the secret and ONLY if it has a `postgres-password` key this will be used. Otherwise it will default to the new `password` key.
Backward compatibility with users that provide an existing secret with the old `postgres-password` key. Otherwise this lead to create container errors.
None, default to the new `password` key.
- Fixes #13800
=> [bitnami/postgresql-ha] backwards compat postgres-password

bitnami/redis/Chart.yaml, bitnami/redis/values.yaml
Enable to set up **updateStrategy.type: Recreate**  for redis chart. For this, drop conflicting **rollingUpdate** stanza.
Before this change, it is impossible to set up **updateStrategy.type: Recreate** in values.yaml, because it already contains **updateStrategy.rollingUpdate: {}**, so deployment/statefulset manifests isn't valid with both stanzas.
Chart users will able to use Recreate strategy to avoid chart updating troubles with RWO-volumes (**Multi-Attach error**).
Those who use rollingUpdate strategy and want to fine-tune it, still can add **updateStrategy.rollingUpdate** stanza in values.yaml, chart defaults it **not** changed.
None.
- fixes #
=> [bitnami/redis] Enable to set up Recreate updateStrategy when "kind: Deployment"

bitnami/nginx/Chart.yaml, bitnami/nginx/templates/deployment.yaml
Similar to #7970 which fixes the apache chart initial clone `CrashLoopBackOff` of the init container.
The initial clone doesn't fail, resulting in a clean and functional deployment.
n.a.
- fixes #13626 
-
=> [bitnami/nginx] Fix git clone on restart #13626

bitnami/solr/Chart.yaml, bitnami/solr/README.md, bitnami/solr/templates/statefulset.yaml, bitnami/solr/values.yaml
Added subPath and subPathExpr properties to persistence parameters.
See also https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#volumes-1
It's now possible to use these parameters during installation.
None I can think of.
Signed-off-by: mgmgwi <guido.wischrop@mgm-tp.com>
=> [bitnami/solr]  Add subPath and subPathExpr

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/svc.yaml
Exposed external port in Kafka SVC
Ability to connect to the broker from outside via SVC on external port and gain access to all nodes from one endpoint.
=>  [bitnami/kafka] Expose external port in SVC for ClusterIP

bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/README.md, bitnami/sonarqube/values.yaml
As in https://docs.sonarqube.org/latest/setup-and-upgrade/deploy-on-kubernetes/deploy-sonarqube-on-kubernetes/#helm-chart-specifics stated, the persistency is only used for elasticsearch to speed up the index generation and not really needed. As with the defaults set as is, a container restart or scaling is not possible at all.
- fixes #13865
=> [bitnami/sonarqube] Fix sonarqube to scale to more than one running pod

bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/README.md, bitnami/sonarqube/values.yaml
Fixed changing postgresql.persistence.enabled to true (the previous value). This bug was introduced at https://github.com/bitnami/charts/pull/14032 but it didn't reach the Helm registry, see https://github.com/bitnami/charts/pull/14032#issuecomment-1359505726
- fixes #13865
=> [bitnami/sonarqube] Undo postgresql persistence enabled value

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/README.md, bitnami/clickhouse/values.yaml
Signed-off-by: lusson <lusson@foxmail.com>
zookeeper cluster replica is 2 will cause cluster split brain, zookeeper cluster least replica is 3.
zookeeper cluster No split-brain
no
- fixes #13954
no
=> [clickhouse] update clickhouse zk cluster replica to 3

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/_helpers.tpl
This PR fixes a bug where the exporter won't connect with MongoDB if a different port is used.
The mongodb-exporter URI hardcoded MongoDB port to 27017, but the MongoDB port may vary depending of the value `containerPorts.mongodb`.
- fixes #13951
nything else that's important and relevant to your pull request, mention that information here.-->
=> [bitnami/mongodb] Set dynamic port on mongodb-exporter uri

bitnami/jaeger/Chart.lock, bitnami/jaeger/Chart.yaml
It seems there is an issue when working with OCI registries and the definition order of the subcharts.
While the issue is solved in the Helm CLI, we are reordering the dependencies.
None
- #9297
=> [bitnami/jaeger] Reorder chart dependencies

bitnami/mastodon/Chart.yaml, bitnami/mastodon/templates/externalelasticsearch-secret.yaml, bitnami/mastodon/templates/externalredis-secret.yaml, bitnami/mastodon/templates/externals3-secret.yaml
Version **0.1.1** of the mastodon helm chart is using the `include "common.names.namespace"` directive in several templates. The `include` function requires the current context argument to be passed. Some templates (such as `externals3-secret.yaml`, `externalredis-secret.yaml`, etc. ) are missing the current context argument, hence chart installation fails when enabling external components such as **S3**, **Redis**, etc.
Signed-off-by: Cristian Marius Tiutiu <v-ctiutiu@digitalocean.com>
The Helm chart installation doesn't fail when enabling external components such as **S3**, **Redis**, etc.
Fixes the installation breakage introduced in version **0.1.1** of the chart.
=> [bitnami/mastodon]: Fix chart installation issues

bitnami/consul/Chart.yaml, bitnami/consul/templates/NOTES.txt, bitnami/consul/templates/ingress.yaml, bitnami/consul/templates/tls-secrets.yaml
The change is adding an additional tpl call before using the configured `.Values.ingress.hostname` parameter.
Currently, you have to provide dedicated _values.yaml_ files for the deployment of a consul where the ingress URL only differs with a small part connected with the deployed namespace: 
e.g. having the namespaces "product-dev" and "product-test" you currently need different _values.yaml_ to prevent a clash in the used ingress URLs.
- _values.dev.yaml_ including
```yaml
consul:
ingress:
enabled: true
hostname: some-consul-url-for-product-dev.org
```
- and a _values.test.yaml_ including
```yaml
consul:
ingress:
enabled: true
hostname: some-consul-url-for-product-test.org
```
With the additional tpl call, one can have one _values.yaml_ which includes the namespace used during …
=> [bitnami/consul] Support templating for ingress urls

bitnami/harbor/Chart.yaml, bitnami/harbor/README.md, bitnami/harbor/values.yaml
Version 16.0.1 of this chart introduced support for Redis sentinel. This added references to some `redis.sentinel.*` variables without providing default values for them in the values.yaml file. If the user does not supply these values then the chart installation fails.
This PR provides the defaults matching the default values used in the bitnami/redis chart so that the error does not happen.
Signed-off-by: Jim Barber <jim.barber@healthengine.com.au>
Fixes the installation of the harbor chart when the user doesn't supply any `redis.sentinel.*` variables because they are not using it.
Fixes the installation breakage introduced in version 16.0.1 of the chart.
- fixes #14054
=> [bitnami/harbor]: Fix chart installation

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/_helpers.tpl
The `auth.database` parameter can now include Helm templating.
This allows users of the chart to derive the name of the database from other variables, like the release name.
N/A
- fixes #14165
N/A
=> [bitnami/postgresql] allow auth.database to be templated

bitnami/memcached/README.md
It seems extremely likely that this line is a typo, based on:
* investigation in [this SO question](https://stackoverflow.com/questions/75001357/different-name-required-to-override-value-in-helm-subchart/75002389)
* the fact that [the PR where this line was introduced](https://github.com/bitnami/charts/pull/8668) updated the actual `Chart.yaml` to
[6.0.0](https://github.com/bitnami/charts/pull/8668/commits/4ed25c0b776ee688d20fddb67f7d63c5356aa5ff)
* the fact that [5.0.0 is referenced twice in this file](https://github.com/bitnami/charts/blob/main/bitnami/memcached/README.md?plain=1#L330-L348)
Signed-off-by: Jack Jackson <scubbojj@gmail.com>
=> [bitnami/memcached] Correct typo in README.md

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/coordinating/svc-headless.yaml, bitnami/elasticsearch/templates/data/svc-headless.yaml, bitnami/elasticsearch/templates/ingest/svc-headless.yaml, bitnami/elasticsearch/templates/master/svc-headless.yaml
Ever since https://github.com/bitnami/charts/pull/12349 was introduced, the chart is no longer upgradeable. The chart throws errors 
```
upgrade.go:434: [debug] warning: Upgrade "elasticsearch" failed: 
cannot patch "elasticsearch-coordinating-hl" with kind Service: Service "elasticsearch-coordinating-hl" is invalid: spec.clusterIP: Invalid value: "": field is immutable 
&& 
cannot patch "elasticsearch-data-hl" with kind Service: Service "elasticsearch-data-hl" is invalid: spec.clusterIP: Invalid value: "": field is immutable 
&& 
cannot patch "elasticsearch-ingest-hl" with kind Service: Service "elasticsearch-ingest-hl" is invalid: spec.clusterIP: Invalid value: "": field is immutable 
&& 
cannot patch "elasticsearch-master-hl" with kind Service: Service "elasticsearch-master-hl" is …
```
=> [bitnami/elasticsearch] Resolve immutable field error due to empty string clusterIP being set

.vib/sealed-secrets/vib-verify.json, bitnami/sealed-secrets/Chart.yaml, bitnami/sealed-secrets/templates/service.yaml
Signed-off-by: Mateusz Drab <mateuszd@outlook.com>
Add port name in service ports spec.
Resolves an issue with servicemonitor not working due to a reference to the port name which was missing in the service:
```yaml
spec:                                                                                                                            
endpoints:
- port: {{ .Values.service.ports.name }}
```
Fixes servicemonitor
N/A
N/A
=> [bitnami/sealed-secrets] add port name to sealed secrets service

bitnami/pinniped/Chart.yaml, bitnami/pinniped/README.md, bitnami/pinniped/templates/NOTES.txt, bitnami/pinniped/templates/supervisor/service-api.yaml, bitnami/pinniped/templates/supervisor/service.yaml, bitnami/pinniped/values.yaml
One single configuration is in parallel for two services. This PR separates them so that the can be configured separately. 
Fixes #13875
=> [bitnami/pinniped] Separate service configuration for supervisor api and aggregator server

.github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline-extra-thanos.yml, .github/workflows/ci-pipeline.yml
Reverts the use of `main` as the version for the `vmware-image-builder-action` to hotfix the current issue blocking the CD pipeline. 
The publishing issue comes from a refactor done in `v0.4.19` of the action that renames some files used in the pipelines' logic. An adaptation of our CI/CD to the latest version will be addressed in a follow-up PR.
=> Use fixed version for vib action

bitnami/gitea/Chart.yaml
=> [bitnami/gitea] Bump version chart to force new publish

.github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline-extra-thanos.yml, .github/workflows/ci-pipeline.yml
The name of the file from which the metadata is obtained for the publishing process was updated to the new naming, as per the new version v0.4.19 of the VIB Action in https://github.com/vmware-labs/vmware-image-builder-action/pull/110
The publishing workflow works again with the latest published version if the VIB Action.
None.
NA.
Follow-up of https://github.com/bitnami/charts/pull/14285
=> [bitnami/*] Update publishing workflow to VIB Action v0.4.19

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/NOTES.txt, bitnami/kafka/templates/statefulset.yaml
Ports in listener config are hard coded. This change uses the ports configured in `containerPorts` for the predefined listeners.
Little fixes in NOTES.txt to avoid blank lines in consumer and producer examples.
Users wouldn't need to set the `listeners` value to change the listener ports.
- fixes #13868
=> [bitnami/kafka] Remove hardcoded ports from listeners

bitnami/haproxy-intel/Chart.yaml, bitnami/wordpress-intel/Chart.yaml, bitnami/wordpress-intel/README.md, bitnami/wordpress-intel/templates/NOTES.txt
Deprecate the bitnami/wordpress-intel Helm chart
=> [bitnami/wordpress-intel] Deprecate Helm chart

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/README.md, bitnami/grafana-operator/crds/grafanas.integreatly.org.yaml, bitnami/grafana-operator/templates/grafana.yaml, bitnami/grafana-operator/values.yaml
Reverts #14181 and #14103
The value `grafana.initContainers` is not supported by the upstream grafana-operator, therefore can't be added to the chart.
- relates to https://github.com/bitnami/charts/issues/14104
=> [bitnami/grafana-operator] Revert #14181 and #14103

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/README.md, bitnami/zookeeper/templates/statefulset.yaml, bitnami/zookeeper/templates/svc-headless.yaml, bitnami/zookeeper/values.yaml
A new configuration parameter `service.headless.name` now allows to override the default name given to the headless service.
Signed-off-by: Fabien Marchand <fabien.marchand@intersec.com>
- fixes #
=> [bitnami/zookeeper] Configure headless service name

bitnami/etcd/Chart.yaml, bitnami/etcd/templates/statefulset.yaml
Won't render jwt secret volume for etcd StatefulSet when the auth token is disabled.
```yaml
- name: etcd-jwt-token
mountPath: /opt/bitnami/etcd/certs/token/
readOnly: true
volumes:
- name: etcd-jwt-token
secret:
secretName: dashbase-etcd-server-jwt-token
defaultMode: 256
```
can disable etcd auth completed. related: https://github.com/bitnami/charts/issues/14249
- fixes #14273.
=> [bitnami/etcd] Fix an issue where the etcd chart renders the jwt volume when the auth is disable

.vib/fluentd/goss/goss.yaml
Fluentd tests were failing after a cluster's update. The permissions configuration is different in the new version
```
duration: 0,
name: "File /var/lib/docker/containers mode",
location: "goss",
message: "ERRORS: [File: /var/lib/docker/containers: mode: doesn't match, expect: ["0701"] found: ["0710"]] FAILURES: [File: /var/lib/docker/containers: mode: doesn't match, expect: ["0701"] found: ["0710"]] ",
test_id: "8cfbff4e",
status: "FAILED"
```
Tests will succeed
None
- related to errors found in https://github.com/bitnami/charts/pull/14328
- [NA] Variables are documented in the …
=> [bitnami/fluentd] Update tests after cluster update

bitnami/minio/Chart.yaml, bitnami/minio/templates/NOTES.txt, bitnami/minio/templates/_helpers.tpl
- In minio chart's NOTES.txt file, the validation of password has been changed to check for existing password in minio secret instead of a combination of Values which do not cover all the scenarios
- No errors during upgrade when auto-created secret already exists. 
- fixes #14069
=> [bitnami/minio]: Check for existing password only in minio NOTES.txt for validation

bitnami/kubeapps/Chart.yaml, bitnami/kubeapps/templates/kubeappsapis/deployment.yaml
Signed-off-by: Kevin DiMichel <kdimiche@gmail.com>
While using the kubeapps chart with these values:
* `postgresql.enabled` to `false`
* `externalDatabase.host` to a cloud managed postgresql database
* `externalDatabase.port` to `"5432"`
the deployment template for `kubeapps-internal-kubeappsapis` constructs the value for `ASSET_SYNCER_DB_URL` including a `-hl`.  With this value, the KubeApps Catalog displays an error:
> An error occurred while fetching the catalog: Unable to fetch chart categories: dial tcp: lookup <KUBEAPPS_POSTGRESQL_HOST>-hl on 10.0.0.10:53: no such host.
This can be worked around via a Helm postrenderer Kustomize patch, but it better that the chart supports it.
Extends the functionality to allow the use of an external postgresql database.
None. It only applies when …
=> [bitnami/kubeapps] wrap ASSET_SYNCER_DB_URL in conditional with no mutation when using externalDatabase

bitnami/mariadb/Chart.yaml, bitnami/mariadb/templates/_helpers.tpl
I noticed that `initdbScriptsConfigMap` and `auth.existingSecret` don't allow us to use template strings. I don't see a reason why this shouldn't be allowed, so this change will apply Helm's `tpl` function to both of them.
The same setup is already used for `primary.existingConfigmap` and `secondary.existingConfigmap`.
This will allow us to configure the following, which currently causes an error:
```yaml
auth:
database: my-database
username: my-user
existingSecret: "{{ .Release.Name }}-mariadb-secret"
initdbScriptsConfigMap: "{{ .Release.Name }}-mariadb-init-config"
```
Without this change we would be unable to e.g. include the release name in the secret or config map.
No known drawbacks.
Not reported yet.
\-
=> [bitnami/mariadb] Allow templates for initdbScriptsConfigMap and auth.existingSecret

bitnami/redis/Chart.yaml, bitnami/redis/README.md, bitnami/redis/templates/master/application.yaml, bitnami/redis/templates/replicas/statefulset.yaml, bitnami/redis/templates/sentinel/statefulset.yaml, bitnami/redis/values.yaml
Signed-off-by: André Bauer <andre.bauer@staffbase.com>
* add probes for metrics container
* startupProbe, livenessProbe & readinessProbe can be defined for metrics container
* default is disabled so current behaviour is not changed
* bumped version to 17.6.0 because there is a pr for 17.5.0 already: https://github.com/bitnami/charts/pull/14399
- fixes #
=> [bitnami/redis] add probes for metrics container

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/templates/controller-service.yaml
Fix rendering of CIDR block list for loadBalancerSourceRanges
Signed-off-by: Samuel Boynton <samlingx@gmail.com>
This change passes the user-supplied values for `loadBalancerSourceRanges` through `toYaml` and indents them properly in order to correctly render a list in the final manifest.
Supplying a list of CIDR blocks in `.Values.service.loadBalancerSourceRanges` will render correctly in the final manifest.
There should be no negative effects from this change.
- fixes #14439
=> [bitnami/nginx-ingress-controller] Fix rendering of CIDR block list for loadBalancerSourceRanges

template/CHART_NAME/templates/pdb.yaml
The PodDisruptionBudget (PDB) template can now be generated alongside the HorizontalPodAutoscaling (HPA) template without illogically setting ".Values.replicaCount" to a value greater than 1.
PDB and HPA are both fairly generic API resources which can both be applied to a large number of applications, so it makes sense for the templates to assume that a chart may want to deploy both/one-of/neither of these resources.
Templates are more flexible
If a user only wants a PDB in their chart, and not a HPA, the PDB template requires additional modification.
- fixes #14407
I looked through the current Bitnami charts and didn't see any charts this would fix, but if the Kafka chart and the Zookeeper chart want to add a HorizontalPodAutoscaler template in the future then they should be sure to …
=> [bitnami/template] PodDisruptionBudget template now works alongside autoscaling

bitnami/redis/Chart.yaml, bitnami/redis/templates/master/application.yaml, bitnami/redis/templates/replicas/statefulset.yaml, bitnami/redis/templates/sentinel/statefulset.yaml
PR #14420 added probes for the metrics container. However, the new Helm values are only included for the `startupProbe`, but not for the `livenessProbe` and `readinessProbe`, i.e. those have always k8s default values.
Actually use the defnied values for the probes
None
- fixes #14420
=> [bitnami/redis] Fix missing Helm value rendering for metrics container probes

bitnami/wordpress/Chart.yaml, bitnami/wordpress/templates/ingress.yaml
Fixed a problem that made `Values.ingress.tlsWwwPrefix` or `nginx.ingress.kubernetes.io/from-to-www-redirect` break the ingress creation
Change made for the wordpress chart and especially for the ingress part.
The ingress section wasn't working when setting `Values.ingress.tlsWwwPrefix` to `true` or when setting `nginx.ingress.kubernetes.io/from-to-www-redirect` in the ingress annotation
Make the ingress resource deployable when enabling `Values.ingress.tlsWwwPrefix` to `true` or when setting `nginx.ingress.kubernetes.io/from-to-www-redirect` in the ingress annotation.
I think not applicable
N/A
Nothing else
=> [bitnami/wordpress] fix: Wordpress ingress bad indentation

bitnami/keycloak/README.md
I was able to run KC with a MSSQL 2019 and the bitnami Keycloak chart, so decided to add this to the documentation. 
Proposed works because KeyCloak gives preferences to the environment compared to the statements in the configuration file. I think it could be useful for other chart users.
Signed-off-by: Alex Samorukov <samm@net-art.cz>
Update Keycloak chart readme to document possible use of MSSQL as an external DB
=> bitnami/keycloak: Document possible use of MSSQL as an external DB

bitnami/minio/Chart.yaml, bitnami/minio/templates/_helpers.tpl, bitnami/minio/templates/api-ingress.yaml, bitnami/minio/templates/ingress.yaml
Signed-off-by: Remy Trompier <remy.trompier@gmail.com>
Use template to define ingress hosts.
This change allow a root chart to override host thanks to template usage.
Previous version allow only to set ingress hosts via the values file, but not programmatically in a parent chart.
=> [bitnami/minio] Allow templates override for ingress hosts

.vib/mastodon/cypress/cypress.json, .vib/mastodon/vib-publish.json, .vib/mastodon/vib-verify.json, bitnami/mastodon/Chart.yaml, bitnami/mastodon/README.md, bitnami/mastodon/values.yaml
Starting version 4.0.2-debian-11-r14 (https://github.com/bitnami/containers/pull/19154/files) of the `bitnami/mastodon` image, the email domain `example.com` is no longer supported, as Mastodon blocks it by default.
It is necessary to change the Mastodon admin email, otherwise deploying the chart using default values will fail.
Chart deployment using default values won't fail
None known.
- related to #14485
=> [bitnami/mastodon] Update default Admin email

bitnami/wordpress/Chart.yaml, bitnami/wordpress/templates/ingress.yaml
Fixes generation of www domain in wordpress ingress.
Currently it is not rendering.
Ingress will have a www domain if needed.
Not rendering chart if tls is used.
=> [bitnami/wordpress] fix: wordpress ingress tls www domain

bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md, bitnami/mongodb/values.yaml
Increase  `timeoutSeconds` for livenesProbe and readinessProbe after detecting several cases where they are very small.
Avoid issues when enabling the metrics with default values.
None.
- fixes #14515 and #12717
=> [bitnami/mongodb] Increase timeout for probes

bitnami/wordpress/Chart.yaml, bitnami/wordpress/templates/NOTES.txt
The instructions given in the `NOTES.txt` file for the `wordpress` chart were incorrect. They contained a non-existent `--include` flag for the `kubectl` command. Trying to create a release from this chart prints the following message:
```
...
To access your WordPress site from outside the cluster follow the steps below:
1. Get the WordPress URL by running these commands:
NOTE: It may take a few minutes for the LoadBalancer IP to be available.
Watch the status with: 'kubectl get svc --namespace wordpress -w my-blog-wordpress'
export SERVICE_IP=$(kubectl get svc --namespace wordpress my-blog-wordpress --include "{{ range (index .status.loadBalancer.ingress 0) }}{{ . }}{{ end }}")
echo "WordPress URL: http://$SERVICE_IP/"
echo "WordPress Admin URL: http://$SERVICE_IP/admin"
...
```
Running …
=> [bitnami/wordpress] Fix `kubectl` flag in `NOTES.txt`

bitnami/matomo/Chart.yaml, bitnami/matomo/templates/deployment.yaml, bitnami/matomo/templates/postinit-configmap.yaml
Signed-off-by: Christian Kraus <christian@kraus.work>
When providing a `customPostInitScripts` value, the chart would only add a `volumeMount` to the deployment but not actually set up the ConfigMap and the volume. Thus, trying to use a post init script would result in an error regarding the missing volume.
I have copied the missing configuration from the dokuwiki chart.
`customPostInitScripts` setting now works as intended.
None.
=> [bitnami/matomo] Fix mounting of post init scripts

bitnami/argo-workflows/Chart.yaml, bitnami/argo-workflows/templates/server/tls-secrets.yaml
=> [bitnami/argo-workflows] Don't regenerate self-signed certs on upgrade

bitnami/aspnet-core/Chart.yaml, bitnami/aspnet-core/templates/tls-secret.yaml
=> [bitnami/aspnet-core] Don't regenerate self-signed certs on upgrade

bitnami/discourse/Chart.yaml, bitnami/discourse/templates/tls-secrets.yaml
=> [bitnami/discourse] Don't regenerate self-signed certs on upgrade

bitnami/external-dns/Chart.yaml, bitnami/external-dns/templates/tls-secret.yaml
=> [bitnami/external-dns] Don't regenerate self-signed certs on upgrade

bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/tls-certs.yaml
=> [bitnami/fluentd] Don't regenerate self-signed certs on upgrade

bitnami/jasperreports/Chart.yaml, bitnami/jasperreports/templates/tls-secrets.yaml
=> [bitnami/jasperreports] Don't regenerate self-signed certs on upgrade

bitnami/kong/Chart.yaml, bitnami/kong/templates/tls-secrets.yaml
=> [bitnami/kong] Don't regenerate self-signed certs on upgrade

.vib/ejbca/cypress/cypress/integration/ejbca_spec.js, .vib/ejbca/goss/goss-wait.yaml, .vib/ejbca/vib-publish.json, .vib/ejbca/vib-verify.json
This PR should increase the stability of VIB tests for EJBCA, introducing new timeouts when necessary.
This will avoid having to trigger the tests multiple times due to false positives.
Tests may take a little bit longer to run.
None
Tested in https://github.com/joancafom/charts/pull/105 with 4 successful ✅ in a row.
=> [bitnami/ejbca] Increase tests stability

template/CHART_NAME/templates/tls-secret.yaml
Don't recreate self-signed certificates on when upgrading a chart.
=> [bitnami/template] Don't regenerate self-signed certs on upgrade

bitnami/wordpress/Chart.yaml, bitnami/wordpress/templates/tls-secrets.yaml
=> [bitnami/wordpress] Don't regenerate self-signed certs on upgrade

bitnami/wildfly/Chart.yaml, bitnami/wildfly/templates/tls-secrets.yaml
=> [bitnami/wildfly] Don't regenerate self-signed certs on upgrade

bitnami/tomcat/Chart.yaml, bitnami/tomcat/templates/tls-secrets.yaml
=> [bitnami/tomcat] Don't regenerate self-signed certs on upgrade

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/bucketweb/tls-secrets.yaml, bitnami/thanos/templates/compactor/tls-secrets.yaml, bitnami/thanos/templates/http-certs-secret.yaml, bitnami/thanos/templates/query-frontend/tls-secrets.yaml, bitnami/thanos/templates/query/grpc-client-tls-secrets.yaml, bitnami/thanos/templates/query/grpc-server-tls-secrets.yaml, bitnami/thanos/templates/query/tls-secrets-grpc.yaml, bitnami/thanos/templates/query/tls-secrets.yaml, bitnami/thanos/templates/receive/grpc-server-tls-secrets.yaml, bitnami/thanos/templates/receive/tls-secrets.yaml, bitnami/thanos/templates/ruler/tls-secrets.yaml, bitnami/thanos/templates/storegateway/grpc-server-tls-secrets.yaml, bitnami/thanos/templates/storegateway/tls-secrets.yaml
=> [bitnami/thanos] Don't regenerate self-signed certs on upgrade

bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/templates/server/tls-secret.yaml
=> [bitnami/spring-cloud-dataflow] Don't regenerate self-signed certs on upgrade

bitnami/spark/Chart.yaml, bitnami/spark/templates/tls-secrets.yaml
=> [bitnami/spark] Don't regenerate self-signed certs on upgrade

bitnami/solr/Chart.yaml, bitnami/solr/templates/ingress-tls-secrets.yaml, bitnami/solr/templates/tls-secrets.yaml
=> [bitnami/solr] Don't regenerate self-signed certs on upgrade

bitnami/schema-registry/Chart.yaml, bitnami/schema-registry/templates/tls-secret.yaml
=> [bitnami/schema-registry] Don't regenerate self-signed certs on upgrade

bitnami/redmine/Chart.yaml, bitnami/redmine/templates/tls-secrets.yaml
=> [bitnami/redmine] Don't regenerate self-signed certs on upgrade

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/tls-secret.yaml
=> [bitnami/redis-cluster] Don't regenerate self-signed certs on upgrade

bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/validating-webhook-configuration.yaml
=> [bitnami/rabbitmq-cluster-operator] Don't regenerate self-signed certs on upgrade

bitnami/pinniped/Chart.yaml, bitnami/pinniped/templates/supervisor/tls-secret.yaml
=> [bitnami/pinniped] Don't regenerate self-signed certs on upgrade

bitnami/osclass/Chart.yaml, bitnami/osclass/templates/tls-secrets.yaml
=> [bitnami/osclass] Don't regenerate self-signed certs on upgrade

bitnami/oauth2-proxy/Chart.yaml, bitnami/oauth2-proxy/templates/tls-secrets.yaml
=> [bitnami/oauth2-proxy] Don't regenerate self-signed certs on upgrade

bitnami/nginx/Chart.yaml, bitnami/nginx/templates/tls-secrets.yaml
=> [bitnami/nginx] Don't regenerate self-signed certs on upgrade

bitnami/nats/Chart.yaml, bitnami/nats/templates/tls-secret.yaml
=> [bitnami/nats] Don't regenerate self-signed certs on upgrade

bitnami/minio/Chart.yaml, bitnami/minio/templates/tls-secrets.yaml
=> [bitnami/minio] Don't regenerate self-signed certs on upgrade

bitnami/mediawiki/Chart.yaml, bitnami/mediawiki/templates/tls-secrets.yaml
=> [bitnami/mediawiki] Don't regenerate self-signed certs on upgrade

bitnami/mariadb-galera/Chart.yaml, bitnami/mariadb-galera/templates/tls-secrets.yaml
=> [bitnami/mariadb-galera] Don't regenerate self-signed certs on upgrade

bitnami/magento/Chart.yaml, bitnami/magento/templates/tls-secrets.yaml
=> [bitnami/magento] Don't regenerate self-signed certs on upgrade

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/tls-secrets.yaml
=> [bitnami/kafka] Don't regenerate self-signed certs on upgrade

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/templates/proxy/tls-secret.yaml
=> [bitnami/jupyterhub] Don't regenerate self-signed certs on upgrade

bitnami/contour/Chart.yaml, bitnami/contour/templates/default-backend/tls-secrets.yaml
=> [bitnami/contour] Don't regenerate self-signed certs on upgrade

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/web/tls-secrets.yaml
Don't recreate airflow certificates on when upgrading the chart.
=> [bitnami/airflow] Don't regenerate self-signed certs on upgrade

bitnami/jenkins/Chart.yaml, bitnami/jenkins/templates/tls-secret.yaml
=> [bitnami/jenkins] Don't regenerate self-signed certs on upgrade

bitnami/logstash/Chart.yaml, bitnami/logstash/templates/tls-secret.yaml
=> [bitnami/logstash] Don't regenerate self-signed certs on upgrade

bitnami/odoo/Chart.yaml, bitnami/odoo/templates/tls-secrets.yaml
=> [bitnami/odoo] Don't regenerate self-signed certs on upgrade

bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/templates/tls-secret.yaml
=> [bitnami/sonarqube] Don't regenerate self-signed certs on upgrade

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/templates/tls-secrets.yaml
=> [bitnami/zookeeper] Don't regenerate self-signed certs on upgrade

bitnami/ghost/Chart.yaml, bitnami/ghost/templates/tls-secrets.yaml
=> [bitnami/ghost] Don't regenerate self-signed certs on upgrade

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/templates/alertmanager/tls-secrets.yaml, bitnami/kube-prometheus/templates/prometheus/tls-secrets.yaml
=> [bitnami/kube-prometheus] Don't regenerate self-signed certs on upgrade

bitnami/sealed-secrets/Chart.yaml, bitnami/sealed-secrets/templates/tls-secret.yaml
=> [bitnami/sealed-secrets] Don't regenerate self-signed certs on upgrade

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/tls-secrets.yaml
=> [bitnami/postgresql] Don't regenerate self-signed certs on upgrade

bitnami/matomo/Chart.yaml, bitnami/matomo/templates/tls-secrets.yaml
=> [bitnami/matomo] Don't regenerate self-signed certs on upgrade

bitnami/kiam/Chart.yaml, bitnami/kiam/templates/_helpers.tpl
=> [bitnami/kiam] Don't regenerate self-signed certs on upgrade

bitnami/dokuwiki/Chart.yaml, bitnami/dokuwiki/templates/tls-secrets.yaml
=> [bitnami/dokuwiki] Don't regenerate self-signed certs on upgrade

bitnami/grafana-loki/Chart.yaml, bitnami/grafana-loki/templates/gateway/tls-secret.yaml
=> [bitnami/grafana-loki] Don't regenerate self-signed certs on upgrade

bitnami/apache/Chart.yaml, bitnami/apache/templates/tls-secrets.yaml
=> [bitnami/apache] Don't regenerate self-signed certs on upgrade

bitnami/appsmith/Chart.yaml, bitnami/appsmith/templates/client/tls-secret.yaml
=> [bitnami/appsmith] Don't regenerate self-signed certs on upgrade

bitnami/concourse/Chart.yaml, bitnami/concourse/templates/web/tls-secrets.yaml
=> [bitnami/concourse] Don't regenerate self-signed certs on upgrade

bitnami/cassandra/Chart.yaml, bitnami/cassandra/templates/_helpers.tpl, bitnami/cassandra/templates/tls-secret.yaml
=> [bitnami/cassandra] Don't regenerate self-signed certs on upgrade

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/templates/ingress-tls-secrets.yaml, bitnami/clickhouse/templates/tls-secret.yaml
=> [bitnami/clickhouse] Don't regenerate self-signed certs on upgrade

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/README.md, bitnami/postgresql-ha/templates/pgpool/service.yaml, bitnami/postgresql-ha/templates/postgresql/service.yaml, bitnami/postgresql-ha/values.yaml
Add `pgpool.annotations` and `postgresql.annotations` to the chart values.
It allows Pgpool and PostgreSQL service annotations to be separately configurable. As the pgpool service can be set to `LoadBalancer`, it may need a different set of annotations than postgresql service that is always `ClusterIP`.
None, the change is backward compatible. The original `service.annotations` still behaves as before and affects both postgresql and pgpool services, although it should be discouraged to use, especially on AWS with ALB ingress controller, because it may lead to unintentional public exposure of the 5432 port.
- fixes #14523
=> [bitnami/postgresql-ha] Service annotations (#14523)

bitnami/kibana/Chart.yaml, bitnami/kibana/templates/tls-secret.yaml
=> [bitnami/kibana] Don't regenerate self-signed certs on upgrade

bitnami/redis/Chart.yaml, bitnami/redis/README.md, bitnami/redis/templates/scripts-configmap.yaml, bitnami/redis/values.yaml
This change allows you use IPs instead of hostnames when configuring the different nodes in the deployment
This solves the tilt mode issue reported [here](https://github.com/bitnami/charts/issues/9689)
None from the tests I performed
- Launched a new deployment with the useHostnames parameter set to false
- Removed a secondary node and confirmed everything worked as expected
- Removed a primary node and confirmed everything worked as expected. A new primary was selected
- fixes https://github.com/bitnami/charts/issues/9689
=> [bitnami/redis] Allow option to disable hostnames usage when configuring nodes

bitnami/gitea/Chart.yaml, bitnami/gitea/templates/tls-secrets.yaml
=> [bitnami/gitea] Don't regenerate self-signed certs on upgrade

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/ingress/tls-secret.yaml, bitnami/harbor/templates/internal/internal-crt-secret.yaml, bitnami/harbor/templates/nginx/tls-secret.yaml, bitnami/harbor/templates/notary/notary-secret.yaml
=> [bitnami/harbor] Don't regenerate self-signed certs on upgrade

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/tls-secret.yaml
=> [bitnami/keycloak] Don't regenerate self-signed certs on upgrade

bitnami/kiam/Chart.yaml, bitnami/kiam/templates/_helpers.tpl, bitnami/kiam/templates/agent/agent-secret.yaml, bitnami/kiam/templates/server/server-secret.yaml
Fixes an issue with Kiam certificates introduced in https://github.com/bitnami/charts/pull/14631
=> [bitnami/kiam] Hotfix kiam certificates

bitnami/phpmyadmin/Chart.yaml, bitnami/phpmyadmin/templates/tls-secrets.yaml
=> [bitnami/phpmyadmin] Don't regenerate self-signed certs on upgrade

.vib/kubeapps/goss/goss.yaml, bitnami/kubeapps/Chart.yaml, bitnami/kubeapps/templates/tls-secrets.yaml
=> [bitnami/kubeapps] Don't regenerate self-signed certs on upgrade

bitnami/common/Chart.yaml, bitnami/common/templates/_images.tpl
Corrected example use of "common.images.image" template.
Change from `... "global" $` to `..."global" .Values.global"`.
Less confusion when using the template and leaning against the docs.
That it will start to actually work for some people who might have used the current example.
=> [bitnami/common] chore: Correct common.images.image global in example

.vib/kube-prometheus/cypress/cypress/integration/kube_prometheus_spec.js
Fix syntax error in kube-prometheus tests.
=> [bitnami/kube-prometheus] Fix test syntax error

bitnami/redis/Chart.yaml, bitnami/redis/templates/master/service.yaml, bitnami/redis/templates/replicas/service.yaml, bitnami/redis/templates/sentinel/service.yaml
Signed-off-by: Samuel Linclau <samuel@linclau.fr>
Updates the templates for the 3 main Services to properly propagate the `loadBalancerSourceRanges` values
This PR fixes the invalid propagation of the loadBalancerSourceRange values, which are interpreted as strings instead of arrays, and causing this error
```shell
$ helm upgrade --set-json 'redis.master.service.loadBalancerSourceRanges=["10.1.2.0/24","10.3.4.0/24"]' (...)
Error: UPGRADE FAILED: cannot patch "redis-master" with kind Service: Service "redis-master" is invalid: spec.LoadBalancerSourceRanges: Invalid value: "[10.1.2.0/24 10.3.4.0/24]": must be a list of IP ranges. For example, 10.240.0.0/24,10.250.0.0/24
```
Here are some manual tests that I made:
- BEFORE the change (invalid yaml array):
```shell
$ helm template --set …
```
=> [bitnami/redis] fix wrong propagation of loadBalancerSourceRanges

.vib/tensorflow-resnet/goss/goss.yaml
Goss looks for the information in the /proc/net/tcp and /proc/net/tcp6 files. The Tensorflow's service works properly in all platforms (for both IPv4 and IPv6). However, the /proc/net/tcp doesn't reflect that information. Removing the protocol (optional) makes goss confirm that there is something working on that port
Tests pass in all platforms
None
There were some platforms in which these tests were failing.
=> [bitnami/tensorflow-resnet] Remove protocol from Tensorflow's goss tests

.vib/tensorflow-resnet/goss/goss.yaml
In https://github.com/bitnami/charts/pull/14773, I erroneously tested the solution in EKS and the changes didn't fixed the tests in that platform. With the current PR, I moved the port tests to addr ones to solve the issues when testing that cluster. This way we can confirm in a different way that the service is listening in the expected ports
```
bitnami ~/projects/charts/.vib/tensorflow-resnet/goss (update-tf-goss-tests) $ goss -g goss.yaml --vars vars.yaml render >  bla.yaml
bitnami ~/projects/charts/.vib/tensorflow-resnet/goss (update-tf-goss-tests) $ k cp bla.yaml jota-tr-tensorflow-resnet-89cb67b87-4fjvx:/tmp/
Defaulted container "tensorflow-serving" out of: tensorflow-serving, seed (init)
bitnami …
```
=> [bitnami/tensorflow-resnet] Move port tests to addr ones

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/nginx/deployment.yaml
Remove extra annotations key when nginx.podAnnotations is defined
Allow using nginx.podAnnotations 
N/A
N/A
- [ X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)
=> [bitnami/harbor] fix nginx custom pod annotations

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/storegateway/hpa-sharded.yaml
The original fix for hardcoded apiversion https://github.com/bitnami/charts/pull/13542 used the wrong context in the range statement which results in a template error.
No more template error and people can use sharded HPAs for the storagegateway
=> [bitnami/thanos] fix context for statefulset

bitnami/thanos/Chart.yaml, bitnami/thanos/README.md, bitnami/thanos/templates/storegateway/statefulset-sharded.yaml
Signed-off-by: Yuval Almog <yuval.almog@riskified.com>
It is now possible to specify different requests and resources for each StatefulSet storegateway container, with the default values being storegateway.resources.requests and storegateway.resources.limits.
Example for specifying resources per partition: 
```
timePartitioning:
- min: ""
max: -6w
resources: #this will change the StatefulSet storegateway container resources just for this partition 
requests:
cpu: 10m
memory: 100Mi
limits:
cpu: 20m
memory: 100Mi
- min: -6w
max: -2w
- min: -2w
max: ""
```
The current implementation of timeaPrtitioning creates all Statefulsets with the same requests and limits, thus forcing the user to set the resources to be as high as the most resource intensive partition. 
As a result of this change, the …
=> [bitnami/thanos] Add Support for timePartitioning resource management

.vib/kong/cypress/cypress.json, .vib/kong/cypress/cypress/integration/kong_spec.js, .vib/kong/vib-publish.json, .vib/kong/vib-verify.json, bitnami/kong/Chart.yaml, bitnami/kong/README.md, bitnami/kong/templates/_helpers.tpl, bitnami/kong/templates/declarative-config-configmap.yaml, bitnami/kong/templates/dep-ds.yaml, bitnami/kong/templates/migrate-job.yaml, bitnami/kong/values.yaml
This PR adds support for not using any database in the Kong chart. This is useful for cases where you want to add a declarative configuration.
This PR also changes the init scripts so they can be evaluated as templates (this is important for cases where you use kong as a subchart
- fixes #
=> [bitnami/kong] feat: :sparkles: Add support for db-less and declarative configuration

bitnami/nginx/Chart.yaml, bitnami/nginx/templates/svc.yaml
This is the same change as https://github.com/bitnami/charts/pull/14455 but for the nginx chart.
- fixes #14834
=> [bitnami/nginx] Fix rendering of CIDR block list for loadBalancerSourceRanges

bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md, bitnami/keycloak/templates/serviceaccount.yaml, bitnami/keycloak/values.yaml
Signed-off-by: Arend Lapere <arend.lapere@gmail.com>
The reason for this PR is that, as I'm injecting secrets via a CSI provider, I need to federate my serviceaccount using Workload Identity. In AKS this is done by passing an annotation with my clientId and a label stating it to use aks workload identity. The latter is not yet supported and I would have to create a service account outside this chart to support 
This PR adds the configuration of extraLabels to serviceAccount configuration block. This allows to add extra labels on top of the ones already there (hence the reason I named it extraLabels and not just labels)
We don't need to create a service account outside of our helm chart. It's more integrated this way.
None that I can see as it is optionally to add labels but they don't …
=> [bitnami/keycloak] Support extraLabels for serviceAccount

bitnami/drupal/Chart.yaml, bitnami/drupal/README.md, bitnami/drupal/values.yaml
Signed-off-by: Mathges <geslinmariecurie@gmail.com>
`resources:` values on `values.yaml` don't have default `resources.requests` values anymore
Users will now be able to fully specify `resources.requests`
- fixes #14739
=> [bitnami/drupal] Remove specified resources on values.yaml

bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/validating-webhook-configuration.yaml
Fixes a bug introduced in #14654, where the `ca.crt` will stop being regenerated in every release.
I missed the references to `$ca.cert` in caBundle, causing it to change to the new CA although the deployment reused the previous CA cert.
- fixes #14908
=> [rabbitmq-cluster-operator] Fix issue with caBundle not using existing CA certificate

bitnami/ejbca/Chart.yaml, bitnami/ejbca/README.md, bitnami/ejbca/values.yaml
Signed-off-by: Mathges <geslinmariecurie@gmail.com>
`resources: values` on `values.yaml` don't have default `resources.requests` values anymore
Users will now be able to fully specify `resources.requests`
- fixes #14739
=> replaced specified values by empty ones on resources

bitnami/redis/Chart.yaml, bitnami/redis/templates/master/application.yaml
The `metrics.command` key was well documented but not implemented in bitnami/redis.
The problem is solved.
- fixes #
=> [bitnami/redis] Fix missing metrics.command key

bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md, bitnami/wordpress/values.yaml
Currently, the wordpress helm chart specifies the following in the values.yaml
```
updateStrategy:
type: RollingUpdate
rollingUpdate: {}
```
When you use the wordpress helm chart as a subchart of another helm chart, there is no way to overwrite the `updateStrategy.rollingUpdate` property to remove it. This causes problems as soon as you want to use the `Recreate` update strategy. Then helm throws the following error:
```
Deployment.apps "my-app-wordpress" is invalid: spec.strategy.rollingUpdate: Forbidden: may not be specified when strategy `type` is 'Recreate'
```
To fix, this, I align the values.yaml with that of other bitnami helm charts like Kibana: https://github.com/andreas-eberle/charts/blob/main/bitnami/kibana/values.yaml#L104
With this change, it becomes possible to use the …
=> [bitnami/wordpress] Remove updateStrategy.rollingUpdate: {} from wordpress chart to allow using Recreate update strategy

bitnami/mastodon/Chart.yaml, bitnami/mastodon/README.md, bitnami/mastodon/templates/_helpers.tpl, bitnami/mastodon/templates/sidekiq/deployment.yaml, bitnami/mastodon/templates/smtp-secret.yaml, bitnami/mastodon/templates/streaming/deployment.yaml, bitnami/mastodon/templates/web/deployment.yaml, bitnami/mastodon/values.yaml
- Add `LOCAL_DOMAIN` environment variable, and emphasize that `WEB_DOMAIN` is an *optional* configuration which should be considered carefully before using
- Add `LOCAL_HTTPS` environment variable to allow successful federation with other Mastodon instances
- Add SMTP configuration to enable sending emails
- Add `RAILS_ENV` and `NODE_ENV` environment variables to the default config
- Fix Redis auth being disabled unless `externalRedis.password` is set. Auth now enabled by *either* `externalRedis.password` or `externalRedis.existingSecret`
- Add `DEFAULT_LOCALE` environment variable
Mastodon installs without `LOCAL_DOMAIN` set show each user's account as "@user@localhost:3000", and are unable to properly federate with other servers. This change fixes that problem by allowing the user to …
=> [bitnami/mastodon] Add SMTP config, LOCAL_DOMAIN, LOCAL_HTTPS, DEFAULT_LOCALE, and other useful and/or required environment variables

.vib/appsmith/cypress/cypress/integration/appsmith_spec.js, bitnami/appsmith/Chart.yaml
The Appsmith functional test can be streamlined by reducing the number of steps required to create a project. Instead of clicking on "New project" the test now creates a new project by directly forking a template. This modification will not impact the test's intended purpose and fixes issues with popup overlays.
- fixes #
=> [bitnami/appsmith] Fix Appsmith Cypress tests

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/README.md, bitnami/grafana-operator/templates/grafana.yaml, bitnami/grafana-operator/values.yaml
Adding support for existingVolume to be with Grafana. Details are already in issue #14796
data persistence outside grafana-operator helm release 
- fixes #14796
=> [bitnami/grafana-operator] - Adding support for existing volume provisioned outside the chart

bitnami/metallb/Chart.yaml
Bumps chart version to trigger the chart publish, fixing missing bump at https://github.com/bitnami/charts/pull/15083
=> [bitnami/metallb] Bump chart release to trigger publishing

bitnami/contour/Chart.yaml, bitnami/contour/README.md, bitnami/contour/templates/contour/deployment.yaml, bitnami/contour/values.yaml
This PR adds a new contour.logFormat parameter in the values.yaml file. 
Changing the logFormat to json is a frequent operation to make contour work well with log aggregation tools like Cloud Logging or Datadog. Those expect structured json logs. 
With the current chart one must provide `--log-format=json` in the `contour.extraArgs` section which is cumbersome and unintuitive for such a frequent operation. Additionally, one must match the contour documentation with the chart documentation to find the parameter in the first place.
Given that the accesslog-format for envoy is prominently highlighted in the documentation, I believe that the log-format should also be a first-class configuration parameter.
This change opens a second way to configure the same thing, because the logFormat could …
=> [bitnami/contour] add contour.logFormat configuration

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/values.yaml
Fixing extraArgs comment as https://github.com/bitnami/charts/blob/10d0f62b55ca3aceae38c955916366799053d01a/bitnami/mongodb/values.yaml#L1920
=> [bitnami/mongodb-sharded] fixing doc comment

bitnami/common/Chart.yaml, bitnami/common/templates/_images.tpl
This function is modified in order to allow empty registry name.
This allows companies which have a a default proxy to the registries, not to set the registry in every field.
This changes have been tested in rabbitmq operator bitnami chart.
This function is modified in order to allow empty registry name.
Currently, this is not possible because it generates an image name like this: /reponame:tag
This allows companies which have a default proxy to the registries, not to set the registry in every field.
=> [bitnami/common] Allow empty registry name

bitnami/redis/Chart.yaml, bitnami/redis/README.md, bitnami/redis/templates/master/application.yaml, bitnami/redis/templates/master/pvc.yaml, bitnami/redis/templates/replicas/statefulset.yaml, bitnami/redis/templates/sentinel/statefulset.yaml, bitnami/redis/values.yaml
=> [bitnami/redis] add PVC labels

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/README.md, bitnami/clickhouse/templates/statefulset.yaml, bitnami/clickhouse/values.yaml
=> [bitnami/clickhouse] add PVC labels

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/README.md, bitnami/rabbitmq/templates/statefulset.yaml, bitnami/rabbitmq/values.yaml
=> [bitnami/rabbitmq] add PVC labels

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kafka/templates/_helpers.tpl, bitnami/kafka/templates/scripts-configmap.yaml, bitnami/kafka/templates/statefulset.yaml, bitnami/kafka/templates/svc-headless.yaml, bitnami/kafka/values.yaml
Signed-off-by: Danil Kuchukov <danil.kuchukov@outlook.com>
This PR implements Kraft mode of Kafka (without Zookeeper). 
It is a pretty important feature of Kafka and the current chart does not support it.
I tested it with Zookeeper and without it, but it would be great if other people help with testing for backward compatibility.
- Currently, bitnami docker image of Kafka does not support sasl_tls and sasl modes with Kraft mode. It hangs on "Creating zookeeper users" even when Kraft mode is enabled. I know what must be fixed and plan to create a PR next week.
- Scaling is not supported. It is known issue when using Kraft. To fix that we need to delete __cluster_metadata/quorum-state file before scaling. I'm not sure how to do that better. We can do it either with helm hooks or …
=> [bitnami/kafka] Kafka Kraft implementation

bitnami/memcached/Chart.yaml, bitnami/memcached/README.md, bitnami/memcached/templates/statefulset.yaml, bitnami/memcached/values.yaml
=> [bitnami/memcached] add PVC labels

bitnami/etcd/Chart.yaml, bitnami/etcd/README.md, bitnami/etcd/templates/statefulset.yaml, bitnami/etcd/values.yaml
=> [bitnami/etcd] add PVC labels

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/secrets.yaml
Execute credentials search and all the `ServiceBinding` logic when auth is enabled. 
Users can upgrade charts when authentication is not enabled. Please see how to reproduce the issue in #15311
- fixes #15311
The issue was introduced in #14910
=> [bitnami/mongodb] Fix chart upgrade when auth.enable=false

bitnami/minio/Chart.yaml, bitnami/minio/README.md, bitnami/minio/values.yaml
Replace default value for 'networkPolicy.extraFromClauses' from object to array.
- fixes #15314
=> [bitnami/minio] Change value 'networkPolicy.extraFromClauses' from object to array

bitnami/cassandra/Chart.yaml, bitnami/cassandra/README.md, bitnami/cassandra/templates/headless-svc.yaml, bitnami/cassandra/values.yaml
=> [bitnami/cassandra] Add support for service.headless.annotations

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/README.md, bitnami/clickhouse/templates/service-headless.yaml, bitnami/clickhouse/values.yaml
=> [bitnami/clickhouse] Add support for service.headless.annotations

bitnami/consul/Chart.yaml, bitnami/consul/README.md, bitnami/consul/templates/consul-headless-service.yaml, bitnami/consul/values.yaml
=> [bitnami/consul] Add support for service.headless.annotations

bitnami/spark/Chart.yaml, bitnami/spark/README.md, bitnami/spark/templates/headless-svc.yaml, bitnami/spark/values.yaml
=> [bitnami/spark] Add support for service.headless.annotations

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/README.md, bitnami/mongodb-sharded/templates/headless-service.yaml, bitnami/mongodb-sharded/values.yaml
=> [bitnami/mongodb-sharded] Add support for service.headless.annotations

bitnami/etcd/Chart.yaml, bitnami/etcd/README.md, bitnami/etcd/templates/svc-headless.yaml, bitnami/etcd/values.yaml
=> [bitnami/etcd] Add support for service.headless.annotations

bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md, bitnami/keycloak/templates/headless-service.yaml, bitnami/keycloak/values.yaml
=> [bitnami/keycloak] Add support for service.headless.annotations

bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md, bitnami/mongodb/templates/arbiter/headless-svc.yaml, bitnami/mongodb/templates/hidden/headless-svc.yaml, bitnami/mongodb/templates/replicaset/headless-svc.yaml, bitnami/mongodb/values.yaml
=> [bitnami/mongodb] Add support for service.headless.annotations

bitnami/pytorch/Chart.yaml, bitnami/pytorch/README.md, bitnami/pytorch/templates/headless-svc.yaml, bitnami/pytorch/values.yaml
=> [bitnami/pytorch] Add support for service.headless.annotations

bitnami/schema-registry/Chart.yaml, bitnami/schema-registry/README.md, bitnami/schema-registry/templates/headless-service.yaml, bitnami/schema-registry/values.yaml
=> [bitnami/schema-registry] Add support for service.headless.annotations

bitnami/solr/Chart.yaml, bitnami/solr/README.md, bitnami/solr/templates/svc-headless.yaml, bitnami/solr/values.yaml
=> [bitnami/solr] Add support for service.headless.annotations

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/scripts-configmap.yaml
Change signal to [SIGTERM](https://www.gnu.org/software/libc/manual/html_node/Termination-Signals.html) on probes
> The SIGTERM signal is a generic signal used to cause program termination. Unlike SIGKILL, this signal can be blocked, handled, and ignored. It is the normal way to politely ask a program to terminate.
>
> The shell command kill generates SIGTERM by default. 
It is the same changes like we recently did for the redis #15057
Using `SIGTERM` instead of the `SIGQUIT` on probes will remove unnecessary coredumps.
Probably nothing and in the case of the issue, `redis-cli` will generate a proper coredump.
Similar to the #15055
=> [bitnami/redis-cluster] Use SIGTERM on timeout for probes

bitnami/contour/Chart.yaml, bitnami/contour/templates/contour/deployment.yaml, bitnami/contour/templates/envoy/daemonset.yaml, bitnami/contour/templates/envoy/deployment.yaml
This change removes the rigor from the securityContext settings and just allows to set everything you need (or what company policies dictate is needed).
This is a non-breaking change as the values already provide with safe defaults + default fields to use. It is just adding the ability to set the remainder of fields.
The runtime chart can be compliant with whatever policy is set or needed.
The limitation is that, before the fields that make sense are only used, in the new case, one would need to prevent entering garbage fields. This is only true to some extent, as some of the securitycontext configs already copied the entire value over verbatim.
- fixes #15392
=> [bitnami/contour] Support all securitycontext fields

bitnami/redis/Chart.yaml, bitnami/redis/templates/master/application.yaml, bitnami/redis/templates/replicas/statefulset.yaml, bitnami/redis/templates/sentinel/statefulset.yaml
The `minReadySeconds` Helm values have a kubernetes version constraint `>=1.25` since MR #13783. While `minReadySeconds` for `StatefulSet` is stable since 1.25, it has been in beta state since 1.23 (see https://github.com/kubernetes/website/pull/30435), which means that it is available on k8s >=1.23 by default unless specifically disabled.
Change the version constraint to `>=1.23-0` to make the feature available on older k8s clusters. (The `-0` includes pre-releases and follows the general pattern used in Bitnami Helm charts)
- `minReadySeconds` is available on clusters running older k8s versions
- If the `minReadySeconds` feature gate is explicitly disabled on a cluster running k8s 1.23 or 1.24 _and_ minReadySeconds is explicitly set to a value greater than 0 in the chart, the resulting …
=> [bitnami/redis] minReadySeconds feature only requires k8s >=1.23

bitnami/redis/Chart.yaml, bitnami/redis/templates/_helpers.tpl
After syncing my fork, it closes the old PR #15118 (my fault). This one replaced it.
This PR replaces the hardcoded default secret key used to compute the checksum with the defined function.
Allow to use custom secret key name.
None
=> [bitnami/redis] Use definition instead of hardcoded key

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/applicationset/servicemonitor.yaml
Fixes a typo error on service monitor name.
=> [bitnami/argo-cd] Fix typo applicationSet name on ServiceMonitor

bitnami/grafana-mimir/Chart.yaml, bitnami/grafana-mimir/templates/gateway/configmap-http.yaml
Amend gateway configuration for alertmanager.
Bugfix
None
- fixes #15369
=> [bitnami/grafana-mimir] Fix wrong gateway configuration when alertmanager.enabled=true

.vib/grafana-tempo/ginkgo/grafana_tempo_test.go, .vib/grafana-tempo/ginkgo/integration_suite_test.go
Adapts Ginkgo tests to allow for the usage of hosts in the services LB. This is necessary for the tests to succeed in AWS-based clusters.
Improves test compatibility.
Changes tested in fork: https://github.com/FraPazGal/charts/pull/145
=> [bitnami/grafana-tempo] Adapt ginkgo tests for non-GKE

.vib/nginx-ingress-controller/ginkgo/integration_suite_test.go, .vib/nginx-ingress-controller/ginkgo/nginx_ingress_controller_test.go
Adapts Ginkgo tests to allow for the usage of hosts in the services LB. This is necessary for the tests to succeed in AWS-based clusters.
Improves test compatibility.
Changes tested in fork: https://github.com/FraPazGal/charts/pull/146
=> [bitnami/nginx-ingress-controller] Adapt ginkgo tests for non-GKE

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md
This major version updates the Kafka subchart to its newest major.
- Related to #14943
=> [bitnami/spring-cloud-dataflow] bump kafka dependency

bitnami/schema-registry/Chart.lock, bitnami/schema-registry/Chart.yaml, bitnami/schema-registry/README.md
This major version updates the Kafka subchart to its newest major.
- Related to #14943
=> [bitnami/schema-registry] bump kafka dependency

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/README.md, bitnami/rabbitmq/templates/statefulset.yaml, bitnami/rabbitmq/values.yaml
Enables adding annotations to the StatefulSet object.
The limitation of the existing commonAnnotations is that it adds the annotations to all the k8s objects. This feature allows adding annotations to the StatefulSet object only, which is needed in some cases.
None
=> [bitnami/rabbitmq] Add support for StatefulSet annotations

bitnami/kafka/README.md
Docs/Readme clarification
Less wasted time on invalid configuration
None (docs addition)
#13624 (see comments)
The example/default turns out to be a valid ID but that is entirely not obvious from looking at it (without knowing the required format).
- [ x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [x ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)
=> [bitnami/kafka] kraft.clusterId format docs

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/service-metrics.yaml, bitnami/influxdb/templates/servicemonitor.yaml
The influxdb chart creates a servicemonitor which targets both the influxdb service and the metrics service.
I changed the `app.kubernetes.io/component` label to influxdb-metrics on the metrics service and adjusted the servicemonitor to differentiate between them.
Metrics targets are not discovered twice per instance
- fixes [#15630](https://github.com/bitnami/charts/issues/15630)
=> [bitnami/influxdb] fix servicemonitor and service labels

bitnami/mysql/Chart.yaml, bitnami/mysql/README.md, bitnami/mysql/templates/primary/statefulset.yaml, bitnami/mysql/templates/secondary/statefulset.yaml, bitnami/mysql/values.yaml
Add `containerSecurityContext` for metrics container.
Allow users configure the `securityContext` for metrics container.
None indentified
- Related to #15552
=> [bitnami/mysql] metrics containerSecurityContext

.vib/contour-operator/runtime-parameters.yaml, .vib/kubeapps/runtime-parameters.yaml, .vib/logstash/runtime-parameters.yaml, .vib/oauth2-proxy/runtime-parameters.yaml, .vib/pinniped/runtime-parameters.yaml, .vib/thanos/runtime-parameters.yaml, .vib/wildfly/runtime-parameters.yaml
A follow-up of #15510, this PRs fixes quoting issues in `runtime-parameters.yaml` files when a configuration block or k8s templating is used.
The migration from the old base64 string to the `.yaml` file removed the double quotes of the strings. This is not an issue for standard strings in yaml, but can create issues for complex configuration blocks or k8s templates.
Fixes faulty code
Additional assets may be impacted by the `"` removal.
=> [bitnami/*] Fix quoting for runtime-params k8s templates and injected configs

bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md, bitnami/keycloak/templates/keycloak-config-cli-job.yaml, bitnami/keycloak/values.yaml
* Added the value `keycloakConfigCli.nodeSelector` this functionality was missing.
* Added [Automatic Cleanup for Finished Jobs](https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/), this is configured with two values;
* `keycloakConfigCli.cleanupAfterFinished.enabled` which enables or disabled the addition of the `.spec.ttlSecondsAfterFinished` field.
* `keycloakConfigCli.cleanupAfterFinished.seconds` which sets the value of the `.spec.ttlSecondsAfterFinished` field.
* The keycloak-config-cli job can now run on clusters that use both Linux and Windows (or any other supported OS).
* Jobs can now be cleaned up if so desired.
=> [bitnami/keycloak] Added nodeSelector and option to automatic cleanup finished jobs to the keycloak-config-cli job

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/common-scripts-cm.yaml
- change in MongoDB Chart the alternate DNS entry from static to clusterDomain variable
- if not using cluster.local as default Cluster Domain, the created MongoDB Cert is still valid
=> [bitnami/mongodb] Change static DNS entry to clusterDomain variable

.github/workflows/assign-asset-label.yml, .github/workflows/ci-pipeline.yml, .github/workflows/move-closed-issues.yml, .github/workflows/moving-cards.yml, .github/workflows/triage.yml
Modify workflows involved in automated PRs to reduce the number of requests to the GitHub API. With these changes we remove 10 API requests for each automated PR.
Take advantage of the latest changes in the labeler action. We are mainly interested on https://github.com/fmulero/labeler/pull/3.
Reduce errors due to the API rate limit. Also, the workflows involving the labeler action will fail clearly if API rate limit is reached and the user can retry the actions failed.
* Related to: https://github.com/bitnami/containers/pull/28187
* Related to: https://github.com/bitnami/containers/pull/27835
=> [bitnami/charts] Reduce GitHub API requests

bitnami/minio/Chart.yaml, bitnami/minio/templates/provisioning-job.yaml
Fix minio policy provisioning error:
```
Incorrect command. Please use 'mc admin policy attach'
```
- fixes #15675
=> [bitnami/minio] Fix minio policy to version minio:2023.3.20 

.github/workflows/ci-pipeline.yml
Use Main Catalog Testing CSP org for testing workflows.
Split production and testing workflows.
To diagnose broken pipelines we could need to change our Organization in CSP or use the artifacts attached to workflow execution.
=> [bitnami/charts] Use Main Catalog Testing CSP Org for GitHub testing pipelines

.github/workflows/moving-cards.yml
* Upgrade [auto-assign-issue](https://github.com/pozil/auto-assign-issue) action dependency.
* Set flag `allowSelfAssign=false`.
* Remove condition to avoid PRs created by bitnami-bot
* PRs 'From Bitnami' shouldn't be assigned to the author.
* PRs in build-maintenance will be automatically assigned
=> [bitnami/charts] Prevent card self assignment

bitnami/minio/Chart.yaml
Bumb version of chart for resolve issue #15718.
It is as written by @justusbunsi. Auto merge bumb version before accepting pull request and ci pipeline does not release a fixed version of helm chart.
- Bumb version for release new helm chart version
Final fix issue #15718
- fixes #15718
=> [bitnami/minio] Bumb version of chart for resolve issue #15718.

bitnami/cert-manager/Chart.yaml, bitnami/cert-manager/templates/webhook/service.yaml
Removes condition to only deploy the webhook service if metrics are enabled. 
The service is also needed by the controller and thus only deploying it when metrics are enabled will break a deployment where metrics are disabled by the user.
The deployment also works when `.Values.metrics.enabled` is set to `false`
None that I am aware of
Possible fix for:
- cert-manager/cert-manager#3195
- cert-manager/cert-manager#4999
These issues are mentioned in the troubleshooting docs of cert-manager
https://cert-manager.io/docs/troubleshooting/webhook/#error-service-cert-managercert-manager-webhook-not-found
=> [bitnami/cert-manager] Remove condition from cert-manager webhook service

bitnami/metallb/Chart.yaml, bitnami/metallb/templates/controller/crds.yaml
Fix for issue #15745 and extends to fix to version 0.13.9
L2Advertisements were missing "interfaces" parameters. This finding lead me to believe that the crds.yaml was not updated.
The comment shows 0.13.4 whereas the chart references 0.13.9 images.
Not only does this fix the L2Advertisement issue but it adds all crds features left out between 0.13.4 (current crds.yaml in chart) and the 0.13.9 version, which this chart claims to be.
The benefit of having a metallb version with all intended features, instead of the newest chart with inaccessible settings/features.
None that come to mind
- fixes #15745 
- fixes metallb up to version 0.13.9
PLEASE UPDATE THE CRDS.YAML ON EACH VERSION UPDATE!!!
Copied crds.yaml from metallb into this project keeping bitnami specific modifications.
Diffs …
=> [bitnami/metallb] crds.yaml update to 0.13.9 (#15745 fix)

bitnami/cassandra/Chart.yaml
Version bump, there was an overlap between  #15803 and #15814
Release changes from #15803
None
- fixes https://github.com/bitnami/charts/actions/runs/4572409717/jobs/8071628518
=> [bitnami/cassandra] Version bump

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/statefulset.yaml
Make setting the `RABBITMQ_FEATURE_FLAGS` variable conditional on content in  `featureFlags`
When no value specified the flags will be set as per RabbitMQ version defaults
None
Currently `RABBITMQ_FEATURE_FLAGS` is always set and when the value is empty, this causes some flags (that should be active by default for a version) to be disabled by RabbitMQ eg. `stream_queue`
=> [bitnami/rabbitmq] Empty RABBITMQ_FEATURE_FLAGS variable causes some flags to be disabled

bitnami/external-dns/Chart.yaml, bitnami/external-dns/templates/clusterrole.yaml
With these recently merged PRs in upstream:
https://github.com/kubernetes-sigs/external-dns/pull/3503 - RBAC added upstream in `external-dns` helm chart.
https://github.com/kubernetes-sigs/external-dns/pull/3162 - code changes in `external-dns`.
we now need to add the same RBAC to this chart to be able to configure `external-dns` to list F5 `VirtualServer` objects in the cluster.
We'll be able to configure the `--source=f5-virtualserver` flag which instructs `external-dns` to list all `VirtualServer` objects in the cluster, these objects will be used as a source to create DNS records in the given provider.
=> [bitnami/external-dns] Add RBAC to support F5 VirtualServer external-dns source

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/application-controller/clusterrole.yaml, bitnami/argo-cd/templates/application-controller/clusterrolebinding.yaml, bitnami/argo-cd/templates/server/clusterrole.yaml, bitnami/argo-cd/templates/server/clusterrolebinding.yaml
Remove namespace field for cluster wide resources
N/A
N/A
N/A
N/A
=> [bitnami/argo-cd] fix remove namespace field for cluster wide resources

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/_helpers.tpl
Update the `redis` username to `default` in harbor configuration according to redis ACL [documentation](https://redis.io/docs/management/security/acl/):
> new connections are already authenticated with a "default" user (this is the default configuration)
Users can set a password for redis.
N/A
- fixes #13473
Checked if other charts are affected, but the redis username is only being defined in harbor chart.
=> [bitnami/harbor] Update redis default user

.github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline.yml
Use `v0` tag for vmware-image-build-acion
We can keep using the latest released version (instead of main branch) and revert if needed to a fixed version easily.
Currently, some of the [automated PRs are failing](https://github.com/bitnami/charts/pulls/bitnami-bot) due to recent changes in main branch.
=> [bitnami/charts] Use tag v0 for vmware-image-build-acion

.github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline.yml
Don't set runtime-parameters.yaml file when it doesn't exist.
Prevent pipeline failures because the file doesnt exist.
- Releated to #15855
=> [bitnami/charts] Allow empty runtime-parameters

.github/workflows/cd-pipeline.yml
Amend charts path in CD pipeline.
Fix broken pipelines
None
- Related to this failure: https://github.com/bitnami/charts/actions/runs/4610178340/attempts/2
Follow up: #15960
=> [bitnami/charts] Fix charts path in CD pipeline

bitnami/metallb/Chart.yaml, bitnami/metallb/README.md, bitnami/metallb/templates/crds.yaml, bitnami/metallb/values.yaml
Add a flag to skip CRD install in te metallb chart, for example if CRDs are managed externally.
Allows management of CRDs by other resources than helm or before this chart gets applied.
none
none
none
=> [bitnami/metallb] add option to skip CRD install

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/ingress/core-ingress.yaml
Change ingress portal_path to the last path to support ingress ALB load balancer.
The problem is the same at [issue](https://github.com/goharbor/harbor-helm/issues/485) at harbor official helm chart and fixed [here](https://github.com/goharbor/harbor-helm/commit/3036f2bf4f7f3b6e679805073c8fe43cdb67f7da5).
Can use harbor throught AWS ALB ingress controller
=> [bitnami/harbor] Update ingress portal path to the last

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/notifications/servicemonitor.yaml
Fix the wrong variable name `argo-cd.notifications` to `argocd.notifications` 
- fixes #15820 
(bug1)
=> [bitnami/argo-cd] Fix argocd.notifications helper reference

bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/forwarder-clusterrole.yaml
Fixing the `resourceNames` attribute to use the correct name of PSP without `namespace`. Currently the value assigned to `resourceNames` uses the PSP name with `namespace` which is wrong.
PSP resource name [created here](https://github.com/bitnami/charts/blob/main/bitnami/fluentd/templates/forwarder-psp.yaml#L6) is without namespace. So need to reference with same name in the ClusterRole under the attribute `resourceNames`
Below is the error while performing the upgrade of fluentd-forwader helm chart with PSP enabled due to the wrong reference of PSP name in ClusterRole
`Error creating: pods "<name>-fluentd-" is forbidden: PodSecurityPolicy: unable to admit pod: [spec.securityContext.fsGroup: Invalid value: []int64{0}: group 0 must be in the ranges: [{1 65535}] spec.volumes[3]: Invalid …
=> [bitnami/fluentd] Fix `resourceNames` attribute in `ClusterRole` to use correct name of PSP

bitnami/metallb/Chart.yaml, bitnami/metallb/README.md, bitnami/metallb/templates/rbac.yaml, bitnami/metallb/templates/speaker/daemonset.yaml, bitnami/metallb/templates/speaker/psp.yaml, bitnami/metallb/templates/speaker/rbac.yaml, bitnami/metallb/templates/speaker/secret.yaml, bitnami/metallb/templates/speaker/service.yaml, bitnami/metallb/templates/speaker/serviceaccount.yaml, bitnami/metallb/templates/speaker/servicemonitor.yaml, bitnami/metallb/values.yaml
Provide an option for disabling BGP speakers. Some CNIs (most prominent being calico) do not need speakers and Metallb recommends disabling speakers when working with calico installation.
Reference: https://metallb.universe.tf/configuration/calico/#the-easy-way
Clusters using Calico can disable metallb speakers and save resources
None
- fixes #8742
=> [bitnami/metallb] Provide a flag for disabling BGP speakers

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/statefulset.yaml
This PR removes the "explicit" mount of `externalDatabase.existingSecret` in the Keycloak container, due to the fact that it's already provided as `KEYCLOAK_DATABASE_PASSWORD`.
See https://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/statefulset.yaml#L118 and https://github.com/bitnami/charts/blob/main/bitnami/keycloak/templates/_helpers.tpl#L163 for the details on how `KEYCLOAK_DATABASE_PASSWORD` gets populated.
This code change avoids having *two* environment variables with a similar purpose being generated, as in:
```yaml
containers:
- name: keycloak
env:
- name: KEYCLOAK_DATABASE_PASSWORD
valueFrom:
secretKeyRef:
key: password
name: database-credentials
envFrom:
- secretRef:
name: database-credentials
```
With the following values:
```yaml
externalDatabase:
... …
```
=> [bitnami/keycloak] Drop unnecessary secret mount in Keycloak container

bitnami/mariadb/Chart.yaml, bitnami/mariadb/README.md, bitnami/mariadb/values.yaml
The value `networkPolicy.egressRules.customRules ` causes the failures reported in #15821 by changing its dictionary type to array in this PR #15638. Therefore, we have to revert the changes again.
=> [bitnami/mariadb] Fix customRules type

bitnami/matomo/Chart.yaml, bitnami/matomo/README.md, bitnami/matomo/values.yaml
The proviced readiness and liveness probes don't work because matomo responses with redirects to https and port 443 on its base path. As documented [in the matomo faq](https://matomo.org/faq/how-to/faq_20278/) health checks can point to `/matomo.php`. 
This has been discussed in this [issue](https://github.com/bitnami/charts/issues/15793).
Out of the box, the probes won't work right now with the bitnami chart. With this change, the probes will work again.
Can't think of any.
- fixes #15793
=> [bitnami/matomo] Fix probe paths

bitnami/etcd/Chart.yaml, bitnami/etcd/README.md, bitnami/etcd/templates/cronjob.yaml, bitnami/etcd/values.yaml
bitnami/etcd: Add ability to dynamically specify snapshot directory.
This allows multiple clusters to leverage the same snapshotting PVC.
Can't think of any, the variable will default to the current value (/snapshots).
N/A
Testing:
```
pit:~/brad # kubectl logs -n services cray-bos-bitnami-etcd-snapshotter-28020465-q67ds
etcd 15:45:06.17 DEBUG ==> Using endpoint cray-bos-bitnami-etcd-0.cray-bos-bitnami-etcd-headless.services.svc.cluster.local:2379
cray-bos-bitnami-etcd-0.cray-bos-bitnami-etcd-headless.services.svc.cluster.local:2379 is healthy: successfully committed proposal: took = 50.561429ms
etcd 15:45:06.27 INFO  ==> Snapshotting the keyspace
{"level":"info","ts":"2023-04-11T15:45:06.303Z","caller":"snapshot/v3_snapshot.go:65","msg":"created temporary db …
```
=> [bitnami/etcd] Add support for dynamic snapshot dir in snapshotter cronjob

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/kafka-provisioning.yaml
When using PEM certs, CA and client certs are reversed in provisioning job, resulting in failure in cert validation.
Provisioning works properly when using PEM certs.
N/A
- fixes #13688
=> [bitnami/kafka] fix reversed certs in provisioning when using PEM certs

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/kafka-provisioning.yaml, bitnami/kafka/values.yaml
When using bundle CA in provisioning job container it complains "unable to find valid certification path". Details are described in the issue referenced below.
This fix changes the reference to the cert files to keystore and truststore locations, instead of inline them in the provisioning client config file. With this fix, the bundle CA can work without issue. Furthermore, anyway, we bind the cert files through a k8s secret, inlining the certs in config file doesn't make the system safer.
Provisioning of topics works with bundle CA.
- fixes #16031
=> [bitnami/kafka] Fix provisioning with bundle CA

bitnami/opencart/Chart.lock, bitnami/opencart/Chart.yaml, bitnami/opencart/README.md
=> [bitnami/opencart] Upgrade MariaDB to version 10.11

bitnami/wordpress/Chart.lock, bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md
=> [bitnami/wordpress] Upgrade MariaDB to version 10.11

bitnami/moodle/Chart.lock, bitnami/moodle/Chart.yaml, bitnami/moodle/README.md
=> [bitnami/moodle] Upgrade MariaDB to version 10.11

bitnami/drupal/Chart.lock, bitnami/drupal/Chart.yaml, bitnami/drupal/README.md
=> [bitnami/drupal] Upgrade MariaDB to version 10.11

bitnami/phpmyadmin/Chart.lock, bitnami/phpmyadmin/Chart.yaml, bitnami/phpmyadmin/README.md
=> [bitnami/phpmyadmin] Upgrade MariaDB to version 10.11

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md
=> [bitnami/spring-cloud-dataflow] Upgrade MariaDB to version 10.11

bitnami/matomo/Chart.lock, bitnami/matomo/Chart.yaml, bitnami/matomo/README.md
=> [bitnami/matomo] Upgrade MariaDB to version 10.11

bitnami/joomla/Chart.lock, bitnami/joomla/Chart.yaml, bitnami/joomla/README.md
=> [bitnami/joomla] Upgrade MariaDB to version 10.11

bitnami/mediawiki/Chart.lock, bitnami/mediawiki/Chart.yaml, bitnami/mediawiki/README.md
=> [bitnami/mediawiki] Upgrade MariaDB to version 10.11

bitnami/prestashop/Chart.lock, bitnami/prestashop/Chart.yaml, bitnami/prestashop/README.md
=> [bitnami/prestashop] Upgrade MariaDB to version 10.11

bitnami/jasperreports/Chart.lock, bitnami/jasperreports/Chart.yaml, bitnami/jasperreports/README.md
=> [bitnami/jasperreports] Upgrade MariaDB to version 10.11

bitnami/magento/Chart.lock, bitnami/magento/Chart.yaml, bitnami/magento/README.md
=> [bitnami/magento] Upgrade MariaDB to version 10.11

bitnami/suitecrm/Chart.lock, bitnami/suitecrm/Chart.yaml, bitnami/suitecrm/README.md
=> [bitnami/suitecrm] Upgrade MariaDB to version 10.11

bitnami/ejbca/Chart.lock, bitnami/ejbca/Chart.yaml, bitnami/ejbca/README.md
=> [bitnami/ejbca] Upgrade MariaDB to version 10.11

bitnami/osclass/Chart.lock, bitnami/osclass/Chart.yaml, bitnami/osclass/README.md
=> [bitnami/osclass] Upgrade MariaDB to version 10.11

bitnami/redmine/Chart.lock, bitnami/redmine/Chart.yaml, bitnami/redmine/README.md
=> [bitnami/redmine] Upgrade MariaDB to version 10.11

bitnami/redis/Chart.yaml, bitnami/redis/templates/replicas/hpa.yaml
Change the order of the HPA metrics to avoid ArgoCD incorrectly reporting OutOfSync
Any tool that runs `diff` between the current HPA resource and the new version before deploying, will see no difference that hasn't been intentionally made.
In my current production deployment, I'm using `16.13.2`. Is it possible to backport this change to a `16.13.x` version of the chart?
- fixes #16198
=> redis chart: sort alphabetically hpa metrics, fixes #16198

bitnami/apache/Chart.lock, bitnami/apache/Chart.yaml, bitnami/clickhouse/Chart.lock, bitnami/clickhouse/Chart.yaml, bitnami/grafana-mimir/Chart.lock, bitnami/grafana-mimir/Chart.yaml, bitnami/mariadb-galera/Chart.lock, bitnami/mariadb-galera/Chart.yaml, bitnami/mariadb/Chart.lock, bitnami/mariadb/Chart.yaml, bitnami/minio/Chart.lock, bitnami/minio/Chart.yaml, bitnami/postgresql-ha/Chart.lock, bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql/Chart.lock, bitnami/postgresql/Chart.yaml, bitnami/tomcat/Chart.lock, bitnami/tomcat/Chart.yaml, bitnami/zookeeper/Chart.lock, bitnami/zookeeper/Chart.yaml
Once applied changes from https://github.com/bitnami/charts/pull/15998, in some cases, our internal test & release pipeline reverts them by mistake (i.e https://github.com/bitnami/charts/pull/16150). The aim of this PR is to undo that undesired revert.
Changes were done by running
```bash
for chart in apache clickhouse grafana-mimir mariadb-galera mariadb minio postgresql-ha postgresql tomcat zookeeper; do
cd $chart || exit
sed -i '' -e 's@https://charts.bitnami.com/bitnami@oci://registry-1.docker.io/bitnamicharts@g' Chart.yaml
rm -rf charts Chart.lock
helm dep update --debug && cd ..
done
```
where the list of charts was previously obtained with
```bash
ag 'charts.bitnami.com' -l | grep 'Chart.*'
```
=> [bitnami/several] Revert changes done by mistake in Chart.yaml repo

bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md, bitnami/keycloak/templates/_helpers.tpl, bitnami/keycloak/templates/ingress.yaml, bitnami/keycloak/templates/servicemonitor.yaml, bitnami/keycloak/values.yaml
When `httpRelativePath` is set, keycloak listens on that path. If a user sets `httpRelativePath` they (optionally) need to match the same in `ingress.path` and must (if they use metrics) match the same path on `metrics.serviceMonitor.endpoints[]`.
This change automates setting these manually when setting `httpRelativePath` and improves user experience.
Improves user experience. No need to remember to set 4 values (`httpRelativePath`, `ingress.path`, and 2 elements of `metrics.serviceMonitor.endpoints`) when you really only want to set 1 (`httpRelativePath`).
None.
=> [bitnami/keycloak] Use `httpRelativePath` for ingress path and service monitor endpoints

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/NOTES.txt, bitnami/argo-cd/templates/_helpers.tpl, bitnami/argo-cd/templates/application-controller/deployment.yaml, bitnami/argo-cd/templates/repo-server/deployment.yaml, bitnami/argo-cd/templates/server/deployment.yaml
- Add helper for the redis image for compatibility with the rest of container image references.
- Include redis image in `argocd.imagePullSecrets`.
- Check redis image with `common.warnings.rollingTag`.
=> [bitnami/argo-cd] Add helper for the redis image

bitnami/discourse/Chart.yaml, bitnami/discourse/README.md, bitnami/discourse/templates/deployment.yaml, bitnami/discourse/values.yaml
Adds a new feature 'discourse.plugins' to the bitnami/discourse chart.
This feature allows users to install plugins during the container initialization, by running `rake plugin:install --repo=...` before the discourse initialization begins.
- supersedes #16009
Tested locally using the following values:
```
discourse:
plugins:
- https://github.com/discourse/discourse-oauth2-basic
```
The Oauth plugin showing in the /admin/plugins page:
=> [bitnami/discourse] Add feature discourse.plugins

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/templates/statefulset.yaml
The command used in `volumePermissions` init container was specified as string instead of a list of strings. This may have resulted in errors reported by Helm:
```
Error: UPGRADE FAILED: error validating "": error validating data: ValidationError(StatefulSet.spec.template.spec.initContainers[0].command): invalid type for io.k8s.api.core.v1.Container.command: got "string", expected "array"
```
Also, this chart appears to have an unused `.Values.volumePermissions.containerSecurityContext` knob and unconditionally uses the main container's securityContext for `volumePermissions` init container instead. This breaks the startup in some cases, e.g. when we require root privileges in order to set up file permissions properly. This PR makes `volumePermissions` honor the securityContext specified …
=> [bitnami/clickhouse] Fix volumePermissions's command syntax and security context

bitnami/nginx/Chart.yaml, bitnami/nginx/README.md, bitnami/nginx/templates/deployment.yaml, bitnami/nginx/values.yaml
I had problems that hpa did not work together with GitClone
Added resources to Sync-Container in deployment.
In my Test-Environment i was able to use hpa and GitClone together
Replaces #16185
=> [bitnami/nginx] Add resources for Add resources to Git-Sync. Otherwise hpa did not work

bitnami/common/Chart.yaml, bitnami/common/README.md
Fix a minor typo in README.md to force the publishing via GitHub.
N/A
N/A
N/A
=> [bitnami/common] Fix typo in README.md to test chart publishing from GitHub

bitnami/mariadb/Chart.yaml, bitnami/mariadb/templates/_helpers.tpl, bitnami/mariadb/templates/secrets.yaml
Currently, when the user does execute `helm upgrade` helm always tries to find a `mariadb-password` secret key even if it does not exist and prints the error:
```
PASSWORDS ERROR: The secret "mariadb" does not contain the key "mariadb-password"
```
This change aims to avoid that error.
Also, when the `serviceBindings.enabled=true` now it will check if `auth.forcePassword=true` in case the user is forced to provide a password.
Users can `helm upgrade` without having to set up a password.
N/A
- fixes #15093
=> [bitnami/mariadb] Fix mariadb upgrade

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/scripts-configmap.yaml
The environmental variable `KAFKA_CFG_CONTROLLER_QUORUM_VOTERS` is always overwritten when `KAFKA_CFG_PROCESS_ROLES` includes `controller`; see [line](https://github.com/bitnami/charts/blob/483fcc8527b6005f31b16a963e28ebd837d09cbb/bitnami/kafka/templates/scripts-configmap.yaml#L110). This should only be overwritten when `KAFKA_CFG_CONTROLLER_QUORUM_VOTERS` is not set.
This PR resolve this  issue #16261 by  adding a  `-z "${KAFKA_CFG_CONTROLLER_QUORUM_VOTERS}"` to the logic gating the overwrite.
Resolves the issue.
None, but I might be wrong.
- fixes #16261
=> [bitnami/kafka] Fix logic to prevent overwriting voter variable

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/core/core-cm-envvars.yaml
Add jfrog-artifactory as a permitted proxy cache to enable integration to Artifactory.
https://github.com/goharbor/harbor/blob/0a3509f8a76ad0e6fa418e057816939f4eb2fe66/make/photon/prepare/templates/core/env.jinja#L42
Integration to Artifactory
n/a
=> [bitnami/harbor] Add jfrog-artifactory as permitted proxy cache

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/keycloak-config-cli-job.yaml, bitnami/keycloak/values.yaml
The user cannot set keycloakConfigCli parameters on `values.yaml` because `keycloak-config-cli` pod container is crashing:
```
$ kubectl get po -n keycloak -w
NAME                                 READY   STATUS    RESTARTS   AGE
keycloak-0                           0/1     Running   0          68s
keycloak-keycloak-config-cli-cnsrr   0/1     Error     0          17s
keycloak-keycloak-config-cli-lgm9j   0/1     Error     0          67s
keycloak-postgresql-0                1/1     Running   0          68s
$ kubectl logs -n keycloak keycloak-keycloak-config-cli-cnsrr
Error: Unable to access jarfile /opt/bitnami/keycloak-config-cli/keycloak-config-cli-21.1.1.jar
```
To skip the error, the chart should avoid trying to match the chart version in the jarfile name.
```
$ docker run -it --name …
```
=> [bitnami/keycloak] Fix keycloakConfigCli

.github/workflows/comments.yml
Amend conditions in `comments.yaml` workflow to manage any comment from users. 
The order in the conditions were also changed to be more readable.
Comments on issues or pull request without any label were being ignored. This problem was affecting mainly to issues created before these workflows were deployed.
Example of [issue](https://github.com/bitnami/charts/issues/2610) not managed properly by the [workflow](https://github.com/bitnami/charts/actions/runs/4902857831)
=> [bitnami/charts] Fix comments workflow to manage any comment from users

bitnami/grafana-loki/Chart.yaml, bitnami/grafana-loki/templates/ingester/statefulset.yaml, bitnami/grafana-loki/templates/querier/statefulset.yaml
Specify apiVersion and kind on volumeClaimTemplates in order to that ArgoCD can recognise them as matching the original manifest.
Deployments of the chat using ArgoCD will look a lot nicer in ArgoCD (they won't look as if there is a problem).
None known.
- fixes #16048
Equivalent to https://github.com/bitnami/charts/pull/15816 for grafana-loki.
=> [bitnami/grafana-loki] apiVersion and kind on volumeClaimTemplates

bitnami/oauth2-proxy/Chart.yaml, bitnami/oauth2-proxy/templates/_helpers.tpl
Update template helpers to resolve redis master node name in case one uses nameOverride for a subchart through values.yaml 
* Enables granular control over resource naming.
* Enables consuming more than one proxy as a subchart (through subcharts aliases) in case the app is governed by various IDPs. 
Not that I can think of.
Not that I'm aware of.
N/A
=> [bitnami/oauth2-proxy] Allow name override of redis subchart

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/_helpers.tpl
`auth.existingSecret` may include Helm templating.
Allows users to use template functions when defining an existing/external secret.
No known drawbacks.
- fixes #16563 
N/A
=> [bitnami/mongodb-sharded] allow mongodb to template existing secret

bitnami/kubeapps/Chart.yaml, bitnami/kubeapps/templates/kubeappsapis/deployment.yaml
Switches the readiness and liveness probes to use grpc_health_probe (until our minimum k8s version supports this natively) rather than the http get which depends on the gRPC-Gateway which we don't otherwise use.
Also fixes the Chart.home attribute which had been accidentally (I think?) switched to "https://bitnami.com" along with all the other charts (which don't have their own bitnami/vmware home pages) in #16546 .
Readiness and liveness checks are using the actual endpoint which is used by the app.
More useful homepage for chart.
- fixes #
- [N/A] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
=> [bitnami/kubeapps] Switch Readiness check to grpc. Fix home URL

bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md, bitnami/mongodb/templates/_helpers.tpl, bitnami/mongodb/templates/hidden/statefulset.yaml, bitnami/mongodb/templates/replicaset/statefulset.yaml, bitnami/mongodb/templates/standalone/dep-sts.yaml, bitnami/mongodb/values.yaml
This PR refers to https://github.com/bitnami/charts/issues/15982
It replaces the hardcoded "--collect-all" with configurable values. All collector options available from mongodb-exporter are now represented by values.
This change also affects the default behaviour of metrics. It no longer defaults to "--collect-all" - instead, by default only diagnosticData and replicasetStatus are enabled (and compatible mode). In my tests, this should be enough to allow the published grafana dashboards (on grafana.com) to work the same as they do with --collect all.
Reason for the change is outlined in the above issue: "--collect-all" is very CPU intensive and collects megabytes of metric data (bloating prometheus in the process) that go mostly unused.
- fine grained and easily accessible control over …
=> [bitnami/mongodb] Handle mongodb-exporter arguments with chart values

bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/templates/deployment.yaml
Generate an `initContainers` section in `deployment.yaml` template even if caCerts is the only initContainer to be run.
Enable using custom ca certificates even if no other initContainer should be run.
None
- fixes #16619
None
=> [bitnami/sonarqube] Enable initContainers section in deployment.yaml for caCerts

bitnami/grafana-tempo/Chart.lock, bitnami/grafana-tempo/Chart.yaml, bitnami/grafana-tempo/README.md, bitnami/grafana-tempo/values.yaml
When the chart is installed the pods of the compactor were restarted, so I'm increasing a little this time to avoid this behavior.
```
$ kubectl get po -w
NAME                                              READY   STATUS    RESTARTS      AGE
grafana-tempo-compactor-6d498df67-bb82q           0/1     Running   1 (48s ago)   2m10s
grafana-tempo-compactor-6d498df67-xbpkd           0/1     Running   1 (37s ago)   2m10s
grafana-tempo-distributor-64bf7b5db-4s7l5         1/1     Running   0             2m10s
grafana-tempo-ingester-0                          1/1     Running   0             2m10s
grafana-tempo-memcached-7d58dc68f8-vzjhc          1/1     Running   0             2m10s
grafana-tempo-metrics-generator-c59bc59bb-zp9nt   1/1     Running   0             2m10s …
```
=> [bitnami/grafana-tempo] Avoid compactor restart

bitnami/supabase/Chart.lock, bitnami/supabase/Chart.yaml, bitnami/supabase/templates/studio/ingress.yaml
Fix Ingress to point to supabase-studio service.
Fix Ingress resource.
N/A
- fixes #16151
=> [bitnami/supabase] Fix ingress to point to correct svc

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/templates/scripts-configmap.yaml
Use the variable HOSTNAME instead of HOST when logging the Zookeeper hostname while trying to generate a server id
Properly log the Hostname when the bash script fails
None - bugfix
=> [bitnami/zookeeper] Bugfix: Use the correct variable for logging Zookeeper hostname

bitnami/redis/Chart.yaml, bitnami/redis/templates/master/application.yaml, bitnami/redis/templates/replicas/statefulset.yaml
Use proper indentation level when adding additional labels to PVC for both Redis master and replicas.
Fixes redis Helm template when used with labels.
Advertised functionality actually works
None known.
- fixes #16677 
Tested manually since there is no test automation that I could find.
=> [bitnami/redis] Fix PVC labeling for bitnami/redis Helm chart

bitnami/etcd/Chart.yaml, bitnami/etcd/templates/svc.yaml
Fix the issue [[bitnami/etcd] `service.clusterIP` only works when `service.type` is `ClusterIP`](https://github.com/bitnami/charts/issues/16325).
Assuming that service-cidr is `10.16.0.0/16`, now we can specify `clusterIP` when `service.type` is not `ClusterIP`.
```shell
cd bitnami/etcd
helm dependency build
helm install etcd . \
--namespace test \
--create-namespace \
--set auth.rbac.create=false \
--set service.type=NodePort \
--set service.clusterIP=10.16.23.79
```
- fixes #16325
Only charts [bitnami/etcd], [bitnami/redis], [bitnami/redis-cluster] have changed.
=> [bitnami/etcd] Fix `service.clusterIP` only works when `service.type` is `ClusterIP`

bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md, bitnami/mongodb/templates/hidden/statefulset.yaml, bitnami/mongodb/templates/replicaset/statefulset.yaml, bitnami/mongodb/templates/standalone/dep-sts.yaml, bitnami/mongodb/values.yaml
Adding the ability to mount extra volumes to the metrics container
This will grant greater customisation of the metrics container, such as providing additional scripts, binaries or (in my use case) a TLS certificate whilst having `tls.enabled: false`
This level of customisation might be excessive for the metrics sidecar / lead to more complexity with other work arounds.
- fixes #
=> [bitnami/mongodb] Adding extraVolumeMounts to the Metrics container

bitnami/external-dns/Chart.yaml, bitnami/external-dns/templates/clusterrole.yaml
This change adds missing permissions required for gateway api.
To be able to manage dns records for gateway api resources, external-dns will use these newly added required permissions.
None.
- fixes https://github.com/bitnami/charts/issues/16589
N/A
- [X ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)
=> [bitnami/external-dns] add missing clusterrole permissions for gateway api

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/primary/statefulset.yaml, bitnami/postgresql/templates/read/statefulset.yaml
Mount extended configuration over the mountPath for the data volume.
Extended configuration will be applied when the data volumen is mounted in a different folder than `/bitnamI/postgresql`
This approach could hide existing configuration files in the persisted volume, under the `{{ .Values.primary.persistence.mountPath }}/conf` folder.
- #16623
=> [bitnami/postgresql] Fix mountPath for extendedConfiguration

bitnami/contour/Chart.yaml, bitnami/contour/templates/contour/rbac.yaml
Newer versions of Contour watch for this resource and do not reconcile other Gateway API resources if the CRD is missing or RBAC doesn't allow access.
=> [bitnami/contour] add grpcroutes to RBAC

bitnami/prometheus/Chart.yaml, bitnami/prometheus/templates/alertmanager/statefulset.yaml, bitnami/prometheus/values.yaml
Use FQDN for `cluster.peer` configuration in alertmanager.
Fix name resolution issues in some environments.
=> [bitnami/prometheus] Use FQDN for cluster.peers in alertmanager

bitnami/kube-prometheus/README.md
When upgrading a chart is common to receive errors related to #15636. This is a helm limitation explained in the [Helm documentation](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations/). This PR adds this warning information.
- fixes #15636
=> [bitnami/kube-prometheus] Add chart upgrading notes related to CRDs

bitnami/moodle/Chart.yaml, bitnami/moodle/templates/svc.yaml, template/CHART_NAME/templates/service.yaml
This change fixes the problem related to issue #16149 and any other when the service is ClusterIP type and the container listening port is not the standard HTTP port (e.g. moodle server running as a non-privileged user on 8080).
With this fix, the service target port gets configured with the value specified on `containerPorts.http` and the container service can be reached by the ingress.
=> [bitnami/moodle] Bugfix: container port different from http

.github/workflows/assign-asset-label.yml
Change `assign-asset-label.yaml` workflow to listen for `pull_request_target` events to avoid issues with pull requests created from forks.
Assign labels in PRs created from forked repositories.
- Related to: https://github.com/bitnami/charts/actions/runs/5116736686/jobs/9203138024
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
=> [bitnami/charts] Fix bug in assign-asset-label workflow

.github/workflows/pr-reviews.yml
Change `pr-reviews.yaml` workflow to listen for `pull_request_target` events to avoid issues with pull requests created from forks.
Allow moving cards in PRs created from forked repositories.
- Related to: https://github.com/bitnami/charts/actions/runs/5141142920
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
=> [bitnami/charts] Fix issue moving cards from forks

bitnami/minio/Chart.yaml, bitnami/minio/templates/NOTES.txt, bitnami/minio/templates/_helpers.tpl
**I removed the check for the root-password `NOTES.txt`.**
The problem with the current implementation is a [known](https://github.com/helm/helm-www/issues/635) and [documented](https://github.com/helm/helm-www/blob/main/content/en/docs/chart_template_guide/functions_and_pipelines.md#using-the-lookup-function) behaviour:
> Keep in mind that Helm is not supposed to contact the Kubernetes API Server during a `helm template` or a `helm install|upgrade|delete|rollback --dry-run`, so the lookup function will return an empty list (i.e. dict) in such a case.
This (currently) makes the condition in `NOTES.txt` fail in all cases when using one of the aforementioned `helm` commands. I took a step back and thought about a case were the password could be not set/empty, but I couldn't really find one. …
=> [bitnami/minio] remove unnecessary password conditions in NOTES.txt

bitnami/wavefront/Chart.yaml, bitnami/wavefront/README.md, bitnami/wavefront/templates/NOTES.txt
Wavefront helm chart will be deprecated since the upstream project has been discontinued and no new features.
=> [bitnami/wavefront] Mark wavefront helm chart as deprecated

bitnami/vault/Chart.yaml, bitnami/vault/templates/server/statefulset.yaml
Removing a duplicated `env:` key in `server/statefulset.yaml` template which causes vault installation to fail when using
fluxcd-2.0.0-rc.5:
```
vault     	        	False    	False	Helm install failed: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 73: mapping key "env" already defined at line 72
```
bitnami/vault helm chart will be possible to install using fluxcd
Not aware of any.
N/A
I have tested this change by building a new helm chart and successfully been able to install it using fluxcd-2.0.0-rc.5 in a k3s cluster.
=> [bitnami/vault] Fix: fluxcd fails to install vault

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/compactor/service.yaml, bitnami/thanos/templates/compactor/servicemonitor.yaml
Don't create a `Service` or `ServiceMonitor` for the compactor when the compactor is configured to run as a cronjob
When enabling the compactor as a cronjob, there's no need to delete the Service & ServiceMonitor via a kustomize patch
N/A
#16742
=> [bitnami/thanos]: conditionals for compactor cronjob

bitnami/vault/Chart.yaml, bitnami/vault/values.yaml
Fix a bug in default value of `vault` charts, which cause error when vault csiProvider  enabled
=> [bitnami/vault] fix: break when using vault csiProvider

.vib/grafana-tempo/goss/goss.yaml, .vib/grafana-tempo/runtime-parameters.yaml
At testing time, add external client to the deployment to generate traces and verify that the ingestion of data is working properly. Based on https://grafana.com/docs/tempo/latest/getting-started/docker-example/ and https://github.com/grafana/tempo/blob/3e70bb9/example/docker-compose/distributed/docker-compose.yaml.
Improved test battery.
Additional points of unreliability in the tests.
=> [bitnami/grafana-tempo] Add external client to generate traces

bitnami/etcd/Chart.yaml, bitnami/etcd/README.md, bitnami/etcd/templates/pdb.yaml, bitnami/etcd/templates/statefulset.yaml
Hi,
We found an issue, that the `PodDisruptionBudget` is not working as desired, as it currently takes  `Jobs` created by the `Cronjob` (if `disasterRecovery.enabled=true`) into consideration:
```
$ k describe poddisruptionbudgets.policy -n sandbox-profile-0-n5c8h
Name:           sandbox-profile-0-n5c8h-etcd
Namespace:      sandbox-profile-0-n5c8h
Min available:  51%
Selector:       app.kubernetes.io/instance=sandbox-profile-0-n5c8h-etcd,app.kubernetes.io/name=etcd
Status:
Allowed disruptions:  0
Current:              3
Desired:              2
Total:                3
Events:
Type     Reason                           Age              From               Message
----     ------                           ----             ----               -------
Normal   NoPods                           18m …
```
=> [bitnami/etcd] Fix label selector for pdb

.github/workflows/moving-cards.yml
Keep cards on [Build Maintenance column](https://github.com/bitnami/charts/projects/4#column-19174507) unassigned.
Avoid noise.
None
=> [bitnami/charts] Avoid assignment of cards in Build Maintenance column

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
- Fixing reference to MONGODB_ROOT_USERNAME
- Use mongodb root user when getting current primary
The MongoDB root username is customisable in the values.yaml file. This value was not used in all parts of the chart. 
This PR addresses a typo made when implementing that fix.
Correctly uses the MONGODB_ROOT_USER environment variable 
n/a
PR where `$` error was introduced
- https://github.com/bitnami/charts/pull/16849#pullrequestreview-1478956290
PR where `root` username was returned to current primary command: 
- https://github.com/bitnami/charts/pull/16853
=> [MongoDB] Respecting the MONGODB_ROOT_USER environment variable

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/secrets.yaml
I am using rabbitmq as dependency.
Upon debugging my chart template using the `helm template [CHART] --debug` command, I noticed that the secrets YAML file generated an empty line between rabbitmq-password and rabbitmq-erlang-cookie.
This change removes any trailing whitespace between rabbitmq-password and rabbitmq-erlang-cookie.
By removing the empty line, the generated secrets YAML file will have a cleaner and more consistent structure.
None
N/A
=> [bitnami/rabbitmq] removed empty line added between password and cookie secret

bitnami/redis/Chart.yaml, bitnami/redis/templates/master/application.yaml, bitnami/redis/templates/replicas/statefulset.yaml, bitnami/redis/templates/sentinel/statefulset.yaml
Add the `automountServiceAccountToken` to redis `master`, `replica` and `sentinel`.
Allow a user to influence the `automountServiceAccountToken` setting for `PodSpec`s.
A user having a custom `ServiceAccount` configured but explicitly having `automountServiceAccountToken` set to `false` might inadvertently rely on the current behavior of auto-mounting. I would argue, that the intent of `automountServiceAccountToken: false` is to not mount the token, making this a bug.
- fixes #17174 
-
=> [bitnami/redis] Add automountServiceAccountToken in pod specs

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/templates/pgpool/deployment.yaml
Added missing quotes around PGPOOL_DISABLE_LOAD_BALANCE_ON_WRITE value. The missing `| quote` filter would render an invalid deployment manifest when `pgpool.loadBalancingOnWrite` was set to `off` because YAML interprets `off` as `false` when unquoted.
Allows users to correctly configure load balancing in pgPool for reads from the PostgreSQL servers without also load balancing writes to the pool, should they choose to do so.
N/A
I personally encountered this bug just recently, but I haven't filed an issue for it. Quite frankly, the fix took less time than creating the issue would, so here we are.
N/A
=> [bitnami/postgresql-ha] pgPool Load Balanced Write Bugfix

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/statefulset.yaml
Fixes issue where the key KAFKA_ENABLE_KRAFT is set twice if `.Values.kraft.enabled` is false. When deploying with ArgoCD this causes a `ComparisonError failures due to duplicate keys` ([issue](https://github.com/argoproj/argo-cd/issues/4071)) which blocks deployment.
=> [bitnami/kafka] Remove KAFKA_ENABLE_KRAFT duplicated keys

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/primary/statefulset.yaml
This is a simple cosmetic change in order to make my life a bit easier while working with the `PostgreSQL` chart and `ArgoCD`. I use the code-snippet below to deploy PostgreSQL via [`kustomize`](https://kustomize.io/), which produces a manifest referencing the `PersistentVolumeClaim` in the short form, without the `apiVersion` and `kind` (see the right side of the image below the code-snippet). 
The issue, is that the verbose reference is added once I apply it to my Cluster (left side of the image). This results in `ArgoCD` thinking there is a diff, where in actuality, they are equal. Now this can be solved by me adding a patch which adds the verbose reference, but I don't want to have unnecessary complexity for something I think is kind of silly. 
**Config**
```yaml
apiVersion: …
```
=> [bitnami/PostgreSQL] Update statefulset to inlcude verbose PVC reference

bitnami/wavefront-prometheus-storage-adapter/Chart.yaml, bitnami/wavefront-prometheus-storage-adapter/README.md, bitnami/wavefront-prometheus-storage-adapter/templates/NOTES.txt
Wavefront Prometheus Adapter helm chart will be deprecated since the upstream project has been discontinued and no new features.
=> [bitnami/wavefront-prometheus-storage-adapter] Mark Wavefront Prometheus Adapter helm chart as deprecated

bitnami/thanos/Chart.yaml, bitnami/thanos/README.md, bitnami/thanos/templates/compactor/pvc.yaml, bitnami/thanos/values.yaml
This change will add the possibility to add labels to the PVC of the Thanos Compactor
It is possible to add labels to the PVC. Before this only the common labels were added to the PVC. One use-case would be to add the `label_excluded_from_alerts=true` label to the PVC, which is used by kube-prometheus to ignore certain PVCs.
I cannot think of drawbacks.
=> [bitnami/thanos] Add labels for Thanos Compactor PVC

bitnami/kube-state-metrics/Chart.yaml, bitnami/kube-state-metrics/values.yaml
Adding an example section for `extraArgs` in values.yaml
This section will help new people use this argument as people new to Helm may find this one difficult to use.
None, As this change is added as a comment only so no drawbacks
- fixes # N/A
N/A
=> [bitnami/kube-state-metrics] Added example section for "extraArgs" section to help use argument in correct way

bitnami/metallb/Chart.yaml, bitnami/metallb/templates/controller/rbac.yaml, bitnami/metallb/templates/speaker/rbac.yaml
=> [bitnami/metallb] Remove namespace field for cluster wide resources

bitnami/external-dns/Chart.yaml, bitnami/external-dns/templates/clusterrole.yaml, bitnami/external-dns/templates/clusterrolebinding.yaml, bitnami/external-dns/templates/psp-clusterrole.yaml, bitnami/external-dns/templates/psp-clusterrolebinding.yaml
=> [bitnami/external-dns] Remove namespace field for cluster wide resources

bitnami/fluent-bit/Chart.yaml, bitnami/fluent-bit/templates/clusterrole.yaml, bitnami/fluent-bit/templates/clusterrolebinding.yaml
=> [bitnami/fluent-bit] Remove namespace field for cluster wide resources

bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/forwarder-clusterrole.yaml, bitnami/fluentd/templates/forwarder-clusterrolebinding.yaml
=> [bitnami/fluentd] Remove namespace field for cluster wide resources

bitnami/flux/Chart.yaml, bitnami/flux/templates/helm-controller/clusterroles.yaml, bitnami/flux/templates/image-automation-controller/clusterroles.yaml, bitnami/flux/templates/image-reflector-controller/clusterroles.yaml, bitnami/flux/templates/kustomize-controller/clusterroles.yaml, bitnami/flux/templates/notification-controller/clusterroles.yaml, bitnami/flux/templates/source-controller/clusterroles.yaml
=> [bitnami/flux] Remove namespace field for cluster wide resources

bitnami/kiam/Chart.yaml, bitnami/kiam/templates/agent/agent-psp-clusterrole.yaml, bitnami/kiam/templates/agent/agent-psp-clusterrolebinding.yaml, bitnami/kiam/templates/server/server-psp-clusterrole.yaml, bitnami/kiam/templates/server/server-psp-clusterrolebinding.yaml, bitnami/kiam/templates/server/server-read-clusterrole.yaml, bitnami/kiam/templates/server/server-read-clusterrolebinding.yaml, bitnami/kiam/templates/server/server-write-clusterrole.yaml, bitnami/kiam/templates/server/server-write-clusterrolebinding.yaml
=> [bitnami/kiam] Remove namespace field for cluster wide resources

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/templates/alertmanager/psp-clusterrole.yaml, bitnami/kube-prometheus/templates/alertmanager/psp-clusterrolebinding.yaml, bitnami/kube-prometheus/templates/prometheus-operator/clusterrole.yaml, bitnami/kube-prometheus/templates/prometheus-operator/clusterrolebinding.yaml, bitnami/kube-prometheus/templates/prometheus-operator/psp-clusterrole.yaml, bitnami/kube-prometheus/templates/prometheus-operator/psp-clusterrolebinding.yaml, bitnami/kube-prometheus/templates/prometheus/clusterrole.yaml, bitnami/kube-prometheus/templates/prometheus/clusterrolebinding.yaml, bitnami/kube-prometheus/templates/prometheus/psp-clusterrole.yaml, bitnami/kube-prometheus/templates/prometheus/psp-clusterrolebinding.yaml
=> [bitnami/kube-prometheus] Remove namespace field for cluster wide resources

bitnami/kube-state-metrics/Chart.yaml, bitnami/kube-state-metrics/templates/clusterrole.yaml, bitnami/kube-state-metrics/templates/clusterrolebinding.yaml, bitnami/kube-state-metrics/templates/psp-clusterrole.yaml, bitnami/kube-state-metrics/templates/psp-clusterrolebinding.yaml
=> [bitnami/kube-state-metrics] Remove namespace field for cluster wide resources

bitnami/kubernetes-event-exporter/Chart.yaml, bitnami/kubernetes-event-exporter/templates/clusterrole.yaml, bitnami/kubernetes-event-exporter/templates/rbac.yaml
=> [bitnami/kubernetes-event-exporter] Remove namespace field for cluster wide resources

bitnami/multus-cni/Chart.yaml, bitnami/multus-cni/templates/clusterrole.yaml, bitnami/multus-cni/templates/clusterrolebinding.yaml
=> [bitnami/multus-cni] Remove namespace field for cluster wide resources

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/templates/clusterrole.yaml, bitnami/nginx-ingress-controller/templates/clusterrolebinding.yaml
=> [bitnami/nginx-ingress-controller] Remove namespace field for cluster wide resources

bitnami/node-exporter/Chart.yaml, bitnami/node-exporter/templates/psp-clusterrole.yaml, bitnami/node-exporter/templates/psp-clusterrolebinding.yaml
=> [bitnami/node-exporter] Remove namespace field for cluster wide resources

bitnami/sealed-secrets/Chart.yaml, bitnami/sealed-secrets/templates/clusterrole.yaml, bitnami/sealed-secrets/templates/clusterrolebinding.yaml, bitnami/sealed-secrets/templates/psp-clusterrole.yaml, bitnami/sealed-secrets/templates/psp-clusterrolebinding.yaml
=> [bitnami/sealed-secrets] Remove namespace field for cluster wide resources

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/query-frontend/psp-clusterrole.yaml, bitnami/thanos/templates/query-frontend/psp-clusterrolebinding.yaml, bitnami/thanos/templates/query/psp-clusterrole.yaml, bitnami/thanos/templates/query/psp-clusterrolebinding.yaml
=> [bitnami/thanos] Remove namespace field for cluster wide resources

bitnami/whereabouts/Chart.yaml, bitnami/whereabouts/templates/clusterrole.yaml, bitnami/whereabouts/templates/clusterrolebinding.yaml
=> [bitnami/whereabouts] Remove namespace field for cluster wide resources

bitnami/argo-workflows/Chart.yaml, bitnami/argo-workflows/templates/controller/aggregate-cluster-roles.yaml, bitnami/argo-workflows/templates/controller/clusterrolebinding.yaml, bitnami/argo-workflows/templates/controller/controller-cluster-roles.yaml, bitnami/argo-workflows/templates/server/cluster-role.yaml, bitnami/argo-workflows/templates/server/clusterrolebinding.yaml
=> [bitnami/argo-workflows] Remove namespace field for cluster wide resources

bitnami/concourse/Chart.yaml, bitnami/concourse/templates/web/role.yaml, bitnami/concourse/templates/worker/role.yaml
=> [bitnami/concourse] Remove namespace field for cluster wide resources

.vib/wavefront-hpa-adapter/runtime-parameters.yaml, bitnami/wavefront-hpa-adapter/Chart.yaml, bitnami/wavefront-hpa-adapter/README.md, bitnami/wavefront-hpa-adapter/templates/NOTES.txt
Add deprecation notice to deprecate Wavefront HPA Adapter.
=> [bitnami/wavefront-hpa-adapter] Add deprecation notice

.vib/fluentd/vib-publish.json, .vib/fluentd/vib-verify.json, .vib/redis/vib-publish.json, .vib/redis/vib-verify.json
There is a wrong type in a variable in, at least, the [GitHub _vib-verify.json_ file](https://github.com/bitnami/charts/blob/main/.vib/redis/vib-verify.json) for the Redis chart. In particular, `worker_nodes_instance_count` is expected to be an Integer, instead of a String
=> worker_nodes_instance_count should be integer instead of string

bitnami/cert-manager/Chart.yaml, bitnami/cert-manager/templates/cainjector/rbac.yaml
The ClusterRoleBinding for cainjector template was using the wrong helper and so the subjects ServiceAccount was not right especially when you use a custom ServiceAccount name.
It will let you use a different ServiceAccount for cainjector than cert-manager-cainjector in the cert-manager Helm Chart.
There is no drawbacks.
=> [bitnami/cert-manager] fix wrong ServiceAccount used for cainjector ClusterRoleBinding

bitnami/grafana-loki/Chart.yaml, bitnami/grafana-loki/README.md, bitnami/grafana-loki/templates/compactor/deployment.yaml, bitnami/grafana-loki/templates/distributor/deployment.yaml, bitnami/grafana-loki/templates/gateway/deployment.yaml, bitnami/grafana-loki/templates/index-gateway/statefulset.yaml, bitnami/grafana-loki/templates/ingester/statefulset.yaml, bitnami/grafana-loki/templates/promtail/daemonset.yaml, bitnami/grafana-loki/templates/querier/statefulset.yaml, bitnami/grafana-loki/templates/query-frontend/deployment.yaml, bitnami/grafana-loki/templates/query-scheduler/deployment.yaml, bitnami/grafana-loki/templates/ruler/statefulset.yaml, bitnami/grafana-loki/templates/table-manager/deployment.yaml, bitnami/grafana-loki/values.yaml
This PR is related to #16890
This change aims to give the ability to provide extra arguments to all containers managed by this Helm chart
As explained in #16890, in order to add extra arguments, we must inspect containers default args and then repeat them in the YAML value file before adding extra arguments
With `extraArgs` value, we'll be able for any container to set additional arguments, eg. `-config.expand-env=true`
N/A
- fixes #16890 
This change has been tested by rendering the Helm chart with `extraArgs` values and multiple scenarii
For every testcase, following command was used (only values.yaml differs) : 
```bash
helm template . \
-f values.yaml \
| yq -r '. | select (((.kind == "Deployment") or (.kind == "StatefulSet") or (.kind == "DaemonSet")) 
and ((.metadata.name | …
```
=> [bitnami/grafana-loki] Add the ability to set extra args for all containers

bitnami/thanos/README.md
Indented the "ruler" config in the YAML file to fix errors when copy-pasting the config. This is just a cosmetic change to the README file and example.
=> [bitnami/thanos] Fix ruler config in README example

bitnami/spark/Chart.yaml, bitnami/spark/README.md, bitnami/spark/templates/statefulset-master.yaml, bitnami/spark/templates/statefulset-worker.yaml, bitnami/spark/values.yaml
I just added the ability to mount volumes (PVC) to master and worker nodes
I we run Kubernetes nodes with HDD, Spark would be very slow. So, if we mount PVC which could be premium SSD on Azure or gp3 on AWS, Spark can have much better performance.
There is not drawbacks
- fixes #17283
=> [bitnami/spark] Add extraVolumeClaimTemplates in master and worker StatefulSets

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/README.md, bitnami/clickhouse/templates/_helpers.tpl, bitnami/clickhouse/templates/configmap-users-extra.yaml, bitnami/clickhouse/templates/statefulset.yaml, bitnami/clickhouse/values.yaml
As shards need to set specific configuration over some user (default for example), there is no way to indicate that custom config from the chart. This PR takes the same approach the `extra` config map (or custom extra config) the chart uses today.
Shards and custom configs for users are now supported
- fixes #13541
This PR does not require changes on the bitnami clickhouse image, as the image already handles files written under the `users.d` folder. More info: [link to code](https://github.com/bitnami/containers/blob/cc3d2cdfe72ce58e788ba78fb627679632b1e088/bitnami/clickhouse/23/debian-11/rootfs/opt/bitnami/scripts/libclickhouse.sh#L89-L90C6)
=> [bitnami/clickhouse] allow to set custom configuration for users folder

bitnami/common/Chart.yaml, bitnami/common/templates/_secrets.tpl
Adds two changes to the 'secrets' helpers group.
* Adds the variable `failOnNew`for "common.secrets.passwords.manage", which avoids a failure if the secrets exist but the key that is being searched does not exist. Default behavior stays as it currently is.
* Makes defaultValue optional on "common.secrets.lookup", if not set and lookup actions returns nothing, the helper will return nothing too.
=> [bitnami/common] Update common.secrets.passwords.manage and common.secrets.lookup

.vib/redis/vib-publish.json, .vib/redis/vib-verify.json
We're finding some issues when testing the Redis Helm chart using `worker_nodes_instance_count: 1`; without this option, everything is working as expected
Just for the records, this parameter was introduced at https://github.com/bitnami/charts/pull/13021
=> [bitnami/redis] Remove worker nodes setting from VIB tests

bitnami/grafana-mimir/Chart.yaml, bitnami/grafana-mimir/templates/_helpers.tpl
Correctly return the existing secret name in grafana-mimir.gateway.secretName when gateway.auth.existingSecret is set.
Allows pre-existing secrets to be used for gateway authentication.
None
- fixes #17468
=> [bitnami/grafana-mimir] Fix helm error when gateway.auth.existingSecret is set

.github/workflows/license-headers.yml
Use `pull_request_target` instead of `pull_request` to allow changes in forked pull requests with licenses issues.
Report license issues in forked pull requests.
- https://github.com/bitnami/charts/actions/runs/5450309954/jobs/9915432045
According to the [documentation](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token), the maximum access for pull requests from public forked repositories is 'read' for all the APIs. We have to move to `pull_request_target` if we want to add comments/reviews in the pull request.
[Containers PR](https://github.com/bitnami/containers/pull/39864)
=> [bitnami/charts] Fix permissions in license-headers workflow

bitnami/postgresql/Chart.lock, bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/_helpers.tpl, bitnami/postgresql/templates/secrets.yaml
This PR fixes an issue where the values `global.postgresql.auth.postgresPassword` and `auth.postgresPassword` were being ignored and therefore a random password was being generated.
The issue affects versions from 12.6.0 to 12.6.3.
- fixes https://github.com/bitnami/charts/issues/17490
=> [bitnami/postgresql] Fix postgres random password generation

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/read/statefulset.yaml
This PR fixes failed rendering of the templates when using `architecture: replication`  and `metrics.extraEnvVars`. The issue was caused by an invalid indentation used. 
Setting `metrics.extraEnvVars` now works properly.
=> [bitnami/postgresql] Fix invalid indentation for replica metrics extraEnvVars

bitnami/oauth2-proxy/Chart.yaml, bitnami/oauth2-proxy/README.md, bitnami/oauth2-proxy/templates/deployment.yaml, bitnami/oauth2-proxy/values.yaml
Signed-off-by: omer nitzan <omer2500@gmail.com>
The --google-group flag on oauth2proxy may be given multiple times depends of how many groups you have.
so i converted the variable name to groups(because its already nested inside google property) and made it of type list and not string.
Will give the option to pass multiple google groups without the need to add it as extra args
None its how oauth2-proxy working
- fixes #
=> [bitnami/oauth2-proxy] make google-group as list instead of string

bitnami/apisix/Chart.lock, bitnami/apisix/Chart.yaml
There is an issue when working with OCI registries and the definition order of the subcharts.
While the issue is solved in the Helm CLI, we are reordering the dependencies.
None
- #9299
=> [bitnami/apisix] Reorder chart dependencies

bitnami/redis/Chart.yaml, bitnami/redis/templates/secret.yaml
For service binds, when using unauthenticated redis, don't include `@` symbol.
service bind works as expected.
I'm not sure there are any...
- fixes #
=> [bitnami/redis] don't include `@` for unauthenticated URI

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/ingress-tls-secrets.yaml, bitnami/rabbitmq/templates/statefulset.yaml, bitnami/rabbitmq/templates/tls-secrets.yaml
1) Moved the ingress tls secrets to a new file (aligned  with how it is done in bitnami/elasticsearch)
2) `tls-secret` now only contains the secret for rabbitmq certs
3) Added checksum tag to the `tls-secret` file  to restart the pods if there are changes to it
If the certs are changed in the secret it will automatically restart the pods
None
- [ x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ x] All commits …
=> [bitnami/rabbitmq] Updating the tls certs through values.yaml not restarting the pods

bitnami/mxnet/Chart.yaml, bitnami/mxnet/README.md, bitnami/mxnet/templates/distributed/scheduler/deployment.yaml, bitnami/mxnet/templates/distributed/server/statefulset.yaml, bitnami/mxnet/templates/distributed/worker/statefulset.yaml, bitnami/mxnet/templates/standalone/deployment.yaml, bitnami/mxnet/values.yaml
Use `bash` instead of `sh` in order to match the command syntax, which is not POSIX-compliant. This lead to errors in which the script is not correctly executed, like:
```console
$ k logs mxnet-55f44dbdff-lpchn -f -c git-clone-repository
+ [[ -f /opt/bitnami/scripts/git/entrypoint.sh ]]
/bin/sh: 2: [[: not found
+ git clone https://github.com/apache/incubator-mxnet.git --branch v1.2.0 /app
Cloning into '/app'...
```
The git container is initialized properly:
```console
$ k logs  mxnet-55f44dbdff-lpchn -f -c git-clone-repository
+ [[ -f /opt/bitnami/scripts/git/entrypoint.sh ]]
+ source /opt/bitnami/scripts/git/entrypoint.sh
++ set -o errexit
++ set -o nounset
++ set -o pipefail
+++ id -u
++ getent passwd 1002
++ '[' -e /opt/bitnami/common/lib/libnss_wrapper.so ']'
++ export …
```
=> [bitnami/mxnet] Fix git init container

bitnami/kube-prometheus/Chart.yaml
Follow-up of https://github.com/bitnami/charts/pull/17707.
The Helm chart version needs to be bumped again because some other change also bumped the version and the commit when the https://github.com/bitnami/charts/pull/17707 was merged didn't: https://github.com/bitnami/charts/commit/dfc44e255a84b3f7cb0bf0953c3bdb111c8fd977
=> [bitnami/kube-prometheus] Bump Helm chart version

.github/workflows/generate-chart-readme.yml
This PR renames the GH action used to run readme generator that's part of the CI/CD since it's currently marked as part of the support GH actions.
Actions to properly reflect the stage they belong to.
N/A
N/A
N/A
=> chore: Rename GH action used to run readme generator

bitnami/pinniped/Chart.yaml
Follow-up of https://github.com/bitnami/charts/pull/17737.
The Helm chart version needs to be bumped again because some other change also bumped the version and the commit when the https://github.com/bitnami/charts/pull/17737 was merged.
=> [bitnami/pinniped] Bump Helm chart version

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/templates/grafana.yaml
Fixes  the `host` value in `ingress.rules` to generate correct Ingress spec.
Correct ingress spec rendered.
N/A
Should fix #17554
N/A
=> [bitnami/grafana-operator] fix host for ingress.rules if ingress is enabled

.github/workflows/vib-files-validator.yml
This PR adds a new GH workflow to validate VIB pipeline files by ensuring the **_verify_** phases are identical on both `vib-verify.json` & `vib-publish.json`. As it's explained in [testing guidelines](https://github.com/bitnami/charts/blob/main/TESTING.md#vib-verifyjson-vs-vib-publishjson):
> _it was decided that the verification process should be identical in both cases_
Ensure no discrepancies are introduced by mistake.
None
N/A
N/A
=> chore: New GH workflow to validate VIB pipeline files

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/templates/grafana.yaml
This PR ensures we properly set the image pull secrets required for pulling Grafana images when indicated at `grafana.image.pullSecrets` parameter.
Operator to be compatible with using private images.
None
N/A
It also fixes an indentation issue with affinity
=> [bitnami/grafana-operator] Add missing image pull secrets for Grafana deployment

bitnami/redis/Chart.yaml, bitnami/redis/README.md, bitnami/redis/values.yaml
Enhance security controls for redis pods
Greater compliance with kubernetes pod security best practices
Users doing custom things may need to adjust their settings.
- fixes #
https://kubernetes.io/docs/concepts/security/pod-security-standards/
=> [bitnami/redis] Try to seed redis with pss-restricted

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/templates/statefulset.yaml
Idea originated from stale PR: https://github.com/bitnami/charts/pull/17333.
Set a label that allows identifying the shard the pod belongs to. Similar to what we are doing in [bitnami/mongodb-sharded](https://github.com/bitnami/charts/blob/a8eb95ec6a71e695157a56c3d60122c8e3844b5e/bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml#L40).
Identify pods for affinity/anti-affinity policies.
n/a
n/a
n/a
=> [bitnami/clickhouse] Add shard label to pods

bitnami/pinniped/Chart.yaml, bitnami/pinniped/templates/concierge/service-proxy.yaml, bitnami/pinniped/templates/supervisor/service-api.yaml, bitnami/pinniped/templates/supervisor/service.yaml
This is just a propagation of [this](https://github.com/bitnami/charts/issues/17450) fix but for `pinniped`
Allows to provide multiple elements to primary.service.loadBalancerSourceRanges.
None
=> [bitnami/pinniped] Allow array for loadBalancerSourceRanges

bitnami/solr/Chart.yaml, bitnami/solr/templates/scripts-configmap.yaml
This PR fixes issues in the initContainer script for the solr helm chart. By adding the noprompt option, the keytool command is able to successfully complete even if the container is being resumed and the certificate is already added to the keystore, instead of erroring out and expecting interactive user input.
With this change, solr statefulset pods will be able to successfully startup even if the init script has been executed on the filesystem before.
=> [bitnami/solr] Add noprompt to init certs command to avoid crash on resume

bitnami/mariadb-galera/Chart.yaml, bitnami/mariadb-galera/templates/statefulset.yaml
[mysqld_exporter 0.15.0](https://github.com/prometheus/mysqld_exporter/releases/tag/v0.15.0) introduced a breaking change in how credentials and target hostname is passed on to the exporter:
> The exporter no longer supports the monolithic DATA_SOURCE_NAME environment variable.
To configure connections to MySQL you can either use a my.cnf style config file or command line arguments.
>
> For example:
>
>```
>export MYSQLD_EXPORTER_PASSWORD=secret
>mysqld_exporter --mysqld.address=localhost:3306 --mysqld.username=exporter
>```
This PR adds this variable and arguments to the exporter container.
Metrics container works with mysqld_exporter versions 0.15.0+
Metrics container stops working with mysqld_exporter versions lower than 0.15.0
- fixes #17994
-
=> [bitnami/mariadb-galera] Pass credentials correctly to mysqld_exporter 0.15.x

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/README.md, bitnami/clickhouse/templates/statefulset.yaml, bitnami/clickhouse/values.yaml
Adds support for using an existing PVC in the clickhouse chart 
Let's you use a custom PVC for clickhouse
Might only support single replica situations
- fixes #17893
=> [bitnami/clickhouse]  Add support for persistence.existingClaim

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/secrets.yaml
Fixes an issue where the `system-user-password` password was created only if metrics/provisioning was enabled.
This makes sense in the Kafka chart, but other applications use this secret key to access a single password instead of the comma-separated list of passwords, as it is the case of Milvus.
Unblocks Milvus update.
- fixes #18186
=> [bitnami/kafka] Always create system-user if client SASL enabled

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/_helpers.tpl, bitnami/rabbitmq/templates/ingress.yaml
Fixes an issue where RabbitMQ deployment would fail when Ingress is enabled using existingSecret
- fixes #18005
=> [bitnami/rabbitmq] Fix issue with ingress.existingSecret

bitnami/mariadb/Chart.yaml, bitnami/mariadb/templates/primary/statefulset.yaml, bitnami/mariadb/templates/secondary/statefulset.yaml
Change arguments passed to mysqld_exporter as from 0.15.0 it doesn't use DATA_SOURCE_NAME anymore, there it crashloop without this change.
mariadb won't crashloop if metrics are enabled.
mysql don't crashloop if metrics are enabled.
- fixes #17994
Initial PR: #17962
=> [bitnami/mariadb] Fix mysql_exporter arguments for 0.15.0

bitnami/mysql/Chart.yaml, bitnami/mysql/templates/primary/statefulset.yaml, bitnami/mysql/templates/secondary/statefulset.yaml
Change arguments passed to mysqld_exporter as from 0.15.0 it doesn't use DATA_SOURCE_NAME anymore, there it crashloop without this change.
mysql don't crashloop if metrics are enabled.
Not tested on older version of the image.
- relates to #17994
Initial PR: #17962
=> [bitnami/mysql] Fix mysql_exporter arguments for 0.15.0

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/NOTES.txt
Use `regexMatch` instead of `regexFind`, becuase we expect `boolean`
Fixes a bug with enabling `externalAccess`
none
- fixes #18196
=> [bitnami/kafka] externalAccess bugfix Use regexMatch instead of regexFind

bitnami/redis/Chart.yaml, bitnami/redis/templates/scripts-configmap.yaml
Signed-off-by: Xinyu Luo <1349694179@qq.com>
Add retry mechanism for getting master info from redis svc when start redis node/sentinel
Can integrate istio proxy, fix the issue that connect redis svc failed before istio sidecar container initialize ready
If istio-proxy container take more than 2 seconds to be ready, then the fix should be invalid.
- fixes #https://github.com/bitnami/charts/issues/18195
=> [bitnami/redis] retry when get master info failed

bitnami/haproxy/Chart.yaml, bitnami/haproxy/templates/deployment.yaml
This change modifies the HAProxy chart's Deployment.yaml to conditionally set replicaCount based on whether autoscaling is enabled. This change allows the Horizontal Pod Autoscaler (HPA) to properly control the number of replicas when autoscaling is enabled and falls back to use the value from replicaCount when autoscaling is not enabled.
This fix allows users of the HAProxy chart to properly use Kubernetes HPA with the chart. This resolves an issue where the `replicaCount` setting in values.yaml would override the HPA's replica count, preventing proper autoscaling.
As this change is adding a condition to the setting of replicaCount, it should not introduce any drawbacks unless there is a dependency on the replicaCount field being explicitly set in the Deployment even when autoscaling is …
=> fix: allow HPA to manage replicas when autoscaling is enabled

bitnami/etcd/Chart.yaml, bitnami/etcd/templates/statefulset.yaml
Title is self explanatory
Removes a non existing service url from the advertised address list
fixes https://github.com/bitnami/charts/issues/18209
=> [bitnami/etcd] only add the service to advertised addresses when it is enabled

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/templates/pgpool/deployment.yaml, bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
Adds resources section to TLS initContainers for postgresql and pgpool templates
Optionally add resources to TLS initContainers
None
N/A
N/A
=> [bitnami/postgresql-ha] Add resources to tls init containers

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/provisioning/job.yaml
This PR updates default provisioning job `client.properties` location to a writable directory.
Provisioning works with default hardening config (`readOnlyRootFilesystem`)
N/A
- fixes #18191
=> [bitnami/kafka] Provisioning job to use a writable folder for client.properties;

.vib/kubernetes-event-exporter/goss/goss.yaml
=> [bitnami/kubernetes-event-exporter] Skip check-no-capabilities test when securityContext disabled

.vib/nats/goss/goss.yaml
Fixes an issue with NATS goss tests, where tests would fail in Openshift as the variable '$running_user' will not match the real running user, causing the tests to fail.
=> [bitnami/nats] Fix issue with goss tests 'running_user'

.vib/metallb/goss/goss.yaml
=> [bitnami/metallb] Skip check-no-capabilities test when securityContext disabled

.vib/spring-cloud-dataflow/goss/goss.yaml
Removes the 'runAsUser' test from Spring Cloud Dataflow goss tests as it is not compatible with all platforms.
When deployed in platforms such as Openshift that does not use 'securityContext' the goss tests will fail.
=> [bitnami/spring-cloud-dataflow] Remove 'runAsUser' goss test

bitnami/prometheus/Chart.yaml, bitnami/prometheus/templates/alertmanager/ingress.yaml, bitnami/prometheus/templates/server/ingress.yaml, bitnami/prometheus/templates/server/service.yaml
Prometheus Chart
Changed Alertmanager an Server Ingress to match with there Services
Ingresses should now be usable
Not Known
none
none
=> bitnami/prometheus: Changes Ingress backend to match services

bitnami/cert-manager/Chart.yaml, bitnami/cert-manager/templates/controller/rbac.yaml
This change adds `patch` verb to the cluster role for issues and clusterissuers. This has been causing the following error in our logs
> cert-manager/clusterissuers: re-queuing item due to error processing" err="clusterissuers.cert-manager.io \"letsencrypt\" is forbidden: User \"system:serviceaccount:cert-manager:cert-manager-controller\" cannot patch resource \"clusterissuers/status\" in API group \"cert-manager.io\" at the cluster scope" key="letsencrypt
Issuer status will get updated
- fixes #
This change has already been made on the [official helm chart](https://github.com/cert-manager/cert-manager/commit/3e23b6fd8a7a4f1200e53f4f17e5496e11813d90)
=> [bitnami/cert-manager] Add patch permission to cert-manager controller for issuers and clusterissuers

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/templates/statefulset.yaml
This PR ensures we don't use labels which values are likely to change (e.g. `helm.sh/chart`) on `volumeClaimTemplates.metadata.labels` since it's forbidden to update this field.
We stop breaking backwards compatibility on every single release.
None
- fixes #18215
Before:
```yaml
(...)
volumeClaimTemplates:
- metadata:
name: data
annotations:
labels:
app.kubernetes.io/name: clickhouse
helm.sh/chart: clickhouse-3.6.3
app.kubernetes.io/instance: clickhouse
app.kubernetes.io/component: clickhouse
(...)  
```
After:
```yaml
(...)
volumeClaimTemplates:
- metadata:
name: data
annotations:
labels:
app.kubernetes.io/name: clickhouse
app.kubernetes.io/instance: clickhouse
app.kubernetes.io/component: clickhouse
(...)  
```
=> [bitnami/clickhouse]: Use inmutable labels on claim templates

.vib/vault/goss/goss.yaml
=> [bitnami/vault] Skip check-no-capabilities test when securityContext disabled

.vib/opensearch/goss/goss.yaml, .vib/opensearch/runtime-parameters.yaml
=> [bitnami/opensearch] Skip check-no-capabilities test when securityContext disabled

bitnami/schema-registry/Chart.yaml, bitnami/schema-registry/templates/statefulset.yaml
This PR address a bug when having `kafka.enabled.false` and using an external Kafka instance. With the current logic, you need to set `kafka.broker.replicaCount=1` and `kafka.kraft.enabled=false` to avoid templating errors.
Fixes bug
None
- fixes #18237
=> [bitnami/schema-registry] Fix sts when using externalKafka

bitnami/schema-registry/Chart.yaml, bitnami/schema-registry/templates/statefulset.yaml
The .Values.auth.tls.jksSecret parameter was not used at all in the schema-registry chart when we have references in the README and values files. 
Allow mounting the TLS certs when required
None as this doesn't modify the default configuration
- fixes https://github.com/bitnami/charts/issues/15771
I rendered the templates and the volume appeared in the statefulset.yaml file.
=> [bitnami/schema-registry] Allow mounting the .Values.auth.tls.jksSecret secret in the certs folder

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/README.md, bitnami/argo-cd/templates/applicationset/deployment.yaml, bitnami/argo-cd/templates/rbac-cm.yaml, bitnami/argo-cd/values.yaml
Besides the `gpg-keys` and `tls-certs` configmaps, there is also a `rbac` configmap for role-based authentication configuration.
Configure rbac as part of the chart.
None
See also:
* https://argo-cd.readthedocs.io/en/stable/operator-manual/rbac/
* https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-rbac-cm.yaml
=> [bitnami/argo-cd] Provide configmap for rbac configuration

bitnami/pinniped/Chart.yaml, bitnami/pinniped/templates/supervisor/ingress.yaml
This PR fixes a bug introduced at https://github.com/bitnami/charts/pull/18406 on ingress annotations.
Proper rendering of ingress manifest.
None
- fixes #18790
N/A
=> [bitnami/pinniped]: fix ingress annotations

bitnami/kafka/Chart.lock, bitnami/kafka/Chart.yaml, bitnami/kafka/README.md
This major version updates the Zookeeper subchart to its newest major.
=> [bitnami/kafka] Zookeeper chart update

bitnami/solr/Chart.lock, bitnami/solr/Chart.yaml, bitnami/solr/README.md
This major version updates the Zookeeper subchart to its newest major.
=> [bitnami/solr] Zookeeper chart update

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/values.yaml
set remote_servers auth by default as [documented](https://clickhouse.com/docs/en/engines/table-engines/special/distributed#distributed-clusters):
> user – Name of the user for connecting to a remote server. Default value is the default user. This user must have access to  connect to the specified server. Access is configured in the users.xml file. For more information, see the section [Access > rights](https://clickhouse.com/docs/en/operations/access-rights).
> password – The password for connecting to a remote server (not masked). Default value: empty string.
using [from_env](https://clickhouse.com/docs/en/operations/configuration-files).
the fix from #13541 require an override to `usersExtraOverrides` to make replicated tables work, this change make it so that it works by default.
- …
=> [bitnami/clickhouse] set remote_servers auth by default

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/servicemonitor.yaml
Fix of values path issue introduced in https://github.com/bitnami/charts/pull/18416
Installation of the chart with `metrics.enabled` set to true currently fails because it's looking for annotations at `serviceMonitor.annotations` unless I add a value like this at the top level of my values file:
```
serviceMonitor:
annotations: {}
```
Bugfix
- fixes #
=> [bitnami/rabbitmq] fix path to serviceMonitor annotations value

.vib/kube-prometheus/goss/goss.yaml
=> [bitnami/kube-prometheus] Skip check-no-capabilities test when securityContext disabled

.vib/argo-cd/goss/goss.yaml
=> [bitnami/argo-cd] Skip check-no-capabilities test when securityContext disabled

.vib/mastodon/goss/goss.yaml
=> [bitnami/mastodon] Skip check-no-capabilities test when securityContext disabled

.vib/milvus/goss/goss.yaml
=> [bitnami/milvus] Skip check-no-capabilities test when securityContext disabled

.vib/apisix/goss/goss.yaml
=> [bitnami/apisix] Skip check-no-capabilities test when securityContext disabled

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/metrics/jmx-svc.yaml
Current selector labels of **`jmx-exporter`** service are not up-to-date, so prometheus metrics services discovery cannot scrape metrics from **`jmx-exporter`** container
Prometheus will able to discovery metrics from jmx-exporter (if enable).
=> [bitnami/kafka] Change selector labels of kafka JMX metrics exporter

bitnami/milvus/Chart.lock, bitnami/milvus/Chart.yaml, bitnami/milvus/README.md
Updates Kafka subchart after its new major #18805
=> [bitnami/milvus] Update Kafka subchart 25.0.0

bitnami/schema-registry/Chart.lock, bitnami/schema-registry/Chart.yaml, bitnami/schema-registry/README.md
Updates Kafka subchart after its new major #18805
=> [bitnami/schema-registry] Update Kafka subchart 25.0.0

bitnami/grafana-operator/Chart.yaml
As reported by @BernhardGruen, we did not properly bumped the chart version at https://github.com/bitnami/charts/pull/18305. This PR fixes this error.
Grafana Operator chart is released with the correct versioning.
None
N/A
N/A
=> [Grafana Operator]: Bump minor version

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/broker/pdb.yaml, bitnami/kafka/templates/broker/statefulset.yaml, bitnami/kafka/templates/broker/svc-external-access.yaml, bitnami/kafka/templates/broker/svc-headless.yaml
This PR fixes an issue introduced at https://github.com/bitnami/charts/pull/18609 since the podLabels values reference for brokers wasn't correct.
Proper broker templates rendering.
None
- fixes #18843
N/A
=> [bitnami/kafka] broker pod labels

bitnami/sealed-secrets/Chart.yaml, bitnami/sealed-secrets/templates/deployment.yaml
This PR fixes an issue introduced at https://github.com/bitnami/charts/pull/18439 since there's a missing dot in `.Values.podAnnotations`.
None
- fixes #18851
N/A
=> [bitnami/sealed-secrest] missing dot

bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/templates/cluster-operator/servicemonitor.yaml
Fixes a bug in rabbitmq-cluster-operator chart template for service monitor object.
Bug is fixed.
None
- fixes #18847
=> [bitnami/rabbitmq-cluster-operator] Bugfix for servicemonitor.yaml template

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md, bitnami/spring-cloud-dataflow/templates/scripts-configmap.yaml
Updates Kafka subchart after its new major #18805
=> [bitnami/spring-cloud-dataflow] Update Kafka subchart 25.0.0

bitnami/kubeapps/Chart.lock, bitnami/kubeapps/Chart.yaml, bitnami/kubeapps/README.md
=> [bitnami/kubeapps] Update Redis' subchart

bitnami/matomo/Chart.yaml, bitnami/matomo/README.md, bitnami/matomo/templates/deployment.yaml, bitnami/matomo/values.yaml
The changes adds the option to set three environment variables relating to mail configuration:
```
MATOMO_SMTP_AUTH
MATOMO_NOREPLY_ADDRESS
MATOMO_NOREPLY_NAME
```
The values can now be set in the chart by setting the following values respectively:
```
smtpAuth
noreplyAddress
noreplyName
```
It allows the configuration of these variables without having to use a workaround.
None
- fixes #18740
=> [bitnami/matomo] Expand configuration with smtpAuth and noreply values

bitnami/supabase/Chart.yaml, bitnami/supabase/templates/studio/ingress.yaml
This PR fixes a but introduced at https://github.com/bitnami/charts/pull/18751 on the Studio ingress annotations.
Users can properly customize studio ingress annotations.
None
- fixes #18921
N/A
=> [bitnami/supabse]: fix studio ingress annotations

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/broker/statefulset.yaml, bitnami/kafka/templates/controller-eligible/statefulset.yaml, bitnami/kafka/templates/metrics/deployment.yaml
Pods were using incorrect labels for the affinity and anti-affinity presets. The labels did not correctly identify their peer pods, leading to faulty behaviour.
The affinity and anti-affinity presets work as intended.
None
- fixes #18794
NA
=> [bitnami/kafka] Fix pod affinity labels

bitnami/kubernetes-event-exporter/Chart.yaml, bitnami/kubernetes-event-exporter/README.md, bitnami/kubernetes-event-exporter/templates/vpa.yaml, bitnami/kubernetes-event-exporter/values.yaml
Adds support for Vertical Pod Autoscaler to automatically adjust cpu/memory requests/limits based on the actual usage without user intervention.
Improve cluster resource utilization.
=> [bitnami/kubernetes-event-exporter] add vpa support

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/templates/grafana.yaml
This PR ensures we use the correct chart value for rendering the ingress annotations to use for Grafana.
Users can set custom ingress annotations for Grafana.
None
- fixes #18249
N/A
=> [bitnami/grafana-operator]: fix ingress annotations

.vib/flux/runtime-parameters.yaml, bitnami/flux/Chart.yaml
This PR modifies the `HelmRelease` extraDeploy to disable `podSecurityContext/containerSecurityContext` for the `bitnami/dokuwiki` chart. This is done to support internal OpenShift testing and does not change the testing env in any way. 
> Note: Given the `runtime-parameters.yaml` complexity, modifying the runtimes here instead of internally is preferred.
None to GH repo usage
None
None
Successful execution [here](https://github.com/bitnami/charts/actions/runs/6040096071/job/16390381897?pr=18963).
=> [bitnami/flux] Update runtime-params to support Openshift

bitnami/redis/Chart.yaml, bitnami/redis/templates/secret-svcbind.yaml
Redis URI format should be like "redis://user:secret@localhost:6379/0?foo=bar&qux=baz"
The "userinfo" part should be "user:secret".
Since user part is empty, the uri will have to leave a colon then concatenate with the secret.
ref: https://www.iana.org/assignments/uri-schemes/prov/redis
Change uri format to match the RFC so that other applications follows the RFC can connect to redis service by the uri directly.
=> [bitnami/redis] expose service binding with correct uri

bitnami/logstash/Chart.yaml, bitnami/logstash/templates/NOTES.txt
Add namespace under the kubectl port-forward logstash chart
When you deploy the Logstash helm chart, the `port-forward` in the notes does not take into consideration the namespace the chart has been deployed.
This is the current output:
```bash
Logstash can be accessed through following DNS names from within your cluster:
Logstash: logstash.logstash.svc.cluster.local
To access Logstash from outside the cluster execute the following commands:
export SERVICE_PORT=$(kubectl get --namespace logstash -o jsonpath="{.spec.ports[0].port}" services logstash)
kubectl port-forward svc/logstash ${SERVICE_PORT}:${SERVICE_PORT} &
echo "http://127.0.0.1:$/{SERVICE_PORT}"
```
Expected output with namespace consideration:
```bash
Logstash can be accessed through following DNS names from within your …
```
=> [bitnami/logstash] fix: add namespace under the kubectl port-forward logstash chart

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/keycloak-config-cli-job.yaml
With the version 16.0.3 of the chart, the templating of the metadata.name field of templates/keycloak-config-cli-job.yaml is incorrect:
```yaml
apiVersion: batch/v1
kind: Job
metadata:
name: common.names.fullname-keycloak-config-cli
```
The common.names.fullname value is not templated.
The name is correctly templated: 
```yaml
apiVersion: batch/v1
kind: Job
metadata:
name: release-name-keycloak-keycloak-config-cli
```
With a truncate to 63 characters if we use a name too long, for example:
```yaml
{{- if .Values.keycloakConfigCli.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
name: {{ printf "%s-keycloak-config-cli-keycloak-config-cli-keycloak-config-cli-keycloak-config-cli" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
```
We get a truncated string:
```yaml …
```
=> [bitnami/keycloak] fix on metadata templating for keycloakConfigCliJob

bitnami/concourse/Chart.lock, bitnami/concourse/Chart.yaml, bitnami/concourse/templates/web/deployment.yaml, bitnami/concourse/templates/web/gateway-service.yaml, bitnami/concourse/templates/web/ingress.yaml, bitnami/concourse/templates/web/service-account.yaml, bitnami/concourse/templates/web/service.yaml, bitnami/concourse/templates/worker/deployment.yaml, bitnami/concourse/templates/worker/poddisruptionbudget.yaml, bitnami/concourse/templates/worker/service-account.yaml, bitnami/concourse/templates/worker/service.yaml, bitnami/concourse/templates/worker/statefulset.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/concourse]: Use merge helper

bitnami/sealed-secrets/Chart.lock, bitnami/sealed-secrets/Chart.yaml, bitnami/sealed-secrets/templates/deployment.yaml, bitnami/sealed-secrets/templates/ingress.yaml, bitnami/sealed-secrets/templates/networkpolicy.yaml, bitnami/sealed-secrets/templates/service.yaml, bitnami/sealed-secrets/templates/serviceaccount.yaml, bitnami/sealed-secrets/templates/servicemonitor.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/sealed-secrets]: Use merge helper

bitnami/wildfly/Chart.yaml, bitnami/wildfly/templates/deployment.yaml, bitnami/wildfly/templates/ingress.yaml, bitnami/wildfly/templates/management-ingress.yaml, bitnami/wildfly/templates/pvc.yaml, bitnami/wildfly/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/wildfly]: Use merge helper

bitnami/kiam/Chart.lock, bitnami/kiam/Chart.yaml, bitnami/kiam/templates/agent/agent-daemonset.yaml, bitnami/kiam/templates/agent/agent-service-account.yaml, bitnami/kiam/templates/agent/agent-service.yaml, bitnami/kiam/templates/agent/agent-servicemonitor.yaml, bitnami/kiam/templates/server/server-daemonset.yaml, bitnami/kiam/templates/server/server-deployment.yaml, bitnami/kiam/templates/server/server-service-account.yaml, bitnami/kiam/templates/server/server-service.yaml, bitnami/kiam/templates/server/server-servicemonitor.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/kiam]: Use merge helper

bitnami/deepspeed/Chart.lock, bitnami/deepspeed/Chart.yaml, bitnami/deepspeed/templates/client/client-dep-job.yaml, bitnami/deepspeed/templates/client/networkpolicy.yaml, bitnami/deepspeed/templates/client/pvc.yaml, bitnami/deepspeed/templates/client/service-account.yaml, bitnami/deepspeed/templates/worker/networkpolicy.yaml, bitnami/deepspeed/templates/worker/service-account.yaml, bitnami/deepspeed/templates/worker/worker-headless-svc.yaml, bitnami/deepspeed/templates/worker/worker-service.yaml, bitnami/deepspeed/templates/worker/worker-statefulset.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/deepspeed]: Use merge helper

bitnami/nginx-ingress-controller/Chart.lock, bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/templates/controller-daemonset.yaml, bitnami/nginx-ingress-controller/templates/controller-deployment.yaml, bitnami/nginx-ingress-controller/templates/controller-metrics-service.yaml, bitnami/nginx-ingress-controller/templates/controller-poddisruptionbudget.yaml, bitnami/nginx-ingress-controller/templates/controller-service.yaml, bitnami/nginx-ingress-controller/templates/controller-servicemonitor.yaml, bitnami/nginx-ingress-controller/templates/default-backend-deployment.yaml, bitnami/nginx-ingress-controller/templates/default-backend-poddisruptionbudget.yaml, bitnami/nginx-ingress-controller/templates/default-backend-service.yaml, bitnami/nginx-ingress-controller/templates/serviceaccount.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/nginx-ingress-controller]: Use merge helper

bitnami/vault/Chart.lock, bitnami/vault/Chart.yaml, bitnami/vault/templates/csi-provider/daemonset.yaml, bitnami/vault/templates/csi-provider/service-account.yaml, bitnami/vault/templates/injector/deployment.yaml, bitnami/vault/templates/injector/pdb.yaml, bitnami/vault/templates/injector/service-account.yaml, bitnami/vault/templates/injector/service.yaml, bitnami/vault/templates/server/active-service.yaml, bitnami/vault/templates/server/ingress.yaml, bitnami/vault/templates/server/pdb.yaml, bitnami/vault/templates/server/service-account.yaml, bitnami/vault/templates/server/service-headless.yaml, bitnami/vault/templates/server/service.yaml, bitnami/vault/templates/server/servicemonitor.yaml, bitnami/vault/templates/server/statefulset.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/vault]: Use merge helper

bitnami/aspnet-core/Chart.lock, bitnami/aspnet-core/Chart.yaml, bitnami/aspnet-core/templates/deployment.yaml, bitnami/aspnet-core/templates/health-ingress.yaml, bitnami/aspnet-core/templates/ingress.yaml, bitnami/aspnet-core/templates/pdb.yaml, bitnami/aspnet-core/templates/serviceaccount.yaml, bitnami/aspnet-core/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/aspnet-core]: Use merge helper

bitnami/grafana-tempo/Chart.yaml, bitnami/grafana-tempo/templates/compactor/servicemonitor.yaml, bitnami/grafana-tempo/templates/distributor/servicemonitor.yaml, bitnami/grafana-tempo/templates/ingester/servicemonitor.yaml, bitnami/grafana-tempo/templates/metrics-generator/servicemonitor.yaml, bitnami/grafana-tempo/templates/querier/servicemonitor.yaml, bitnami/grafana-tempo/templates/query-frontend/servicemonitor.yaml, bitnami/grafana-tempo/templates/vulture/servicemonitor.yaml
Fixes an indent issue introduced in the PR https://github.com/bitnami/charts/pull/18509 which prevents servicemonitors being deployed for Grafana Tempo
N/A
None
N/A
Issue only occurs if `metrics.serviceMonitor.enabled: true`
=> [bitnami/grafana-tempo] Fixed incorrect indent in servicemonitor labels

bitnami/discourse/Chart.lock, bitnami/discourse/Chart.yaml, bitnami/discourse/templates/deployment.yaml, bitnami/discourse/templates/ingress.yaml, bitnami/discourse/templates/networkpolicy-backend-ingress.yaml, bitnami/discourse/templates/networkpolicy-ingress.yaml, bitnami/discourse/templates/pvc.yaml, bitnami/discourse/templates/service.yaml, bitnami/discourse/templates/serviceaccount.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/discourse]: Use merge helper

bitnami/drupal/Chart.lock, bitnami/drupal/Chart.yaml, bitnami/drupal/templates/deployment.yaml, bitnami/drupal/templates/ingress.yaml, bitnami/drupal/templates/metrics-svc.yaml, bitnami/drupal/templates/networkpolicy-backend-ingress.yaml, bitnami/drupal/templates/networkpolicy-ingress.yaml, bitnami/drupal/templates/pvc.yaml, bitnami/drupal/templates/serviceaccount.yaml, bitnami/drupal/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/drupal]: Use merge helper

bitnami/flink/Chart.lock, bitnami/flink/Chart.yaml, bitnami/flink/templates/jobmanager/deployment.yaml, bitnami/flink/templates/jobmanager/service.yml, bitnami/flink/templates/jobmanager/serviceaccount.yaml, bitnami/flink/templates/taskmanager/deployment.yaml, bitnami/flink/templates/taskmanager/service.yml, bitnami/flink/templates/taskmanager/serviceaccount.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/flink]: Use merge helper

bitnami/grafana/Chart.lock, bitnami/grafana/Chart.yaml, bitnami/grafana/templates/deployment.yaml, bitnami/grafana/templates/image-renderer-deployment.yaml, bitnami/grafana/templates/image-renderer-service.yaml, bitnami/grafana/templates/image-renderer-servicemonitor.yaml, bitnami/grafana/templates/ingress.yaml, bitnami/grafana/templates/pvc.yaml, bitnami/grafana/templates/service.yaml, bitnami/grafana/templates/serviceaccount.yaml, bitnami/grafana/templates/servicemonitor.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/grafana]: Use merge helper

bitnami/moodle/Chart.lock, bitnami/moodle/Chart.yaml, bitnami/moodle/templates/deployment.yaml, bitnami/moodle/templates/ingress.yaml, bitnami/moodle/templates/metrics-svc.yaml, bitnami/moodle/templates/networkpolicy-backend-ingress.yaml, bitnami/moodle/templates/networkpolicy-ingress.yaml, bitnami/moodle/templates/pvc.yaml, bitnami/moodle/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/moodle]: Use merge helper

bitnami/mxnet/Chart.lock, bitnami/mxnet/Chart.yaml, bitnami/mxnet/templates/distributed/scheduler/deployment.yaml, bitnami/mxnet/templates/distributed/scheduler/service.yaml, bitnami/mxnet/templates/distributed/server/statefulset.yaml, bitnami/mxnet/templates/distributed/worker/statefulset.yaml, bitnami/mxnet/templates/pvc.yaml, bitnami/mxnet/templates/standalone/deployment.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/mxnet]: Use merge helper

bitnami/postgresql/Chart.lock, bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/backup/cronjob.yaml, bitnami/postgresql/templates/backup/pvc.yaml, bitnami/postgresql/templates/primary/metrics-svc.yaml, bitnami/postgresql/templates/primary/networkpolicy.yaml, bitnami/postgresql/templates/primary/servicemonitor.yaml, bitnami/postgresql/templates/primary/statefulset.yaml, bitnami/postgresql/templates/primary/svc-headless.yaml, bitnami/postgresql/templates/primary/svc.yaml, bitnami/postgresql/templates/prometheusrule.yaml, bitnami/postgresql/templates/read/metrics-svc.yaml, bitnami/postgresql/templates/read/networkpolicy.yaml, bitnami/postgresql/templates/read/servicemonitor.yaml, bitnami/postgresql/templates/read/statefulset.yaml, bitnami/postgresql/templates/read/svc-headless.yaml, bitnami/postgresql/templates/read/svc.yaml, bitnami/postgresql/templates/serviceaccount.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/postgresql]: Use merge helper

bitnami/redis/Chart.lock, bitnami/redis/Chart.yaml, bitnami/redis/templates/headless-svc.yaml, bitnami/redis/templates/master/application.yaml, bitnami/redis/templates/master/pvc.yaml, bitnami/redis/templates/master/service.yaml, bitnami/redis/templates/master/serviceaccount.yaml, bitnami/redis/templates/metrics-svc.yaml, bitnami/redis/templates/replicas/service.yaml, bitnami/redis/templates/replicas/serviceaccount.yaml, bitnami/redis/templates/replicas/statefulset.yaml, bitnami/redis/templates/sentinel/node-services.yaml, bitnami/redis/templates/sentinel/service.yaml, bitnami/redis/templates/sentinel/statefulset.yaml, bitnami/redis/templates/serviceaccount.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/redis]: Use merge helper

bitnami/suitecrm/Chart.lock, bitnami/suitecrm/Chart.yaml, bitnami/suitecrm/templates/deployment.yaml, bitnami/suitecrm/templates/ingress.yaml, bitnami/suitecrm/templates/metrics-svc.yaml, bitnami/suitecrm/templates/networkpolicy-backend-ingress.yaml, bitnami/suitecrm/templates/networkpolicy-ingress.yaml, bitnami/suitecrm/templates/pvc.yaml, bitnami/suitecrm/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/suitecrm]: Use merge helper

bitnami/tensorflow-resnet/Chart.lock, bitnami/tensorflow-resnet/Chart.yaml, bitnami/tensorflow-resnet/templates/deployment.yaml, bitnami/tensorflow-resnet/templates/service.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/tensorflow-resnet]: Use merge helper

bitnami/contour/Chart.lock, bitnami/contour/Chart.yaml, bitnami/contour/templates/certgen/serviceaccount.yaml, bitnami/contour/templates/contour/deployment.yaml, bitnami/contour/templates/contour/service.yaml, bitnami/contour/templates/contour/serviceaccount.yaml, bitnami/contour/templates/contour/servicemonitor.yaml, bitnami/contour/templates/default-backend/deployment.yaml, bitnami/contour/templates/default-backend/ingress.yaml, bitnami/contour/templates/default-backend/poddisruptionbudget.yaml, bitnami/contour/templates/default-backend/service.yaml, bitnami/contour/templates/envoy/daemonset.yaml, bitnami/contour/templates/envoy/deployment.yaml, bitnami/contour/templates/envoy/service.yaml, bitnami/contour/templates/envoy/serviceaccount.yaml, bitnami/contour/templates/envoy/servicemonitor.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/contour]: Use merge helper

.vib/nginx-ingress-controller/ginkgo/integration_suite_test.go, .vib/nginx-ingress-controller/ginkgo/nginx_ingress_controller_test.go, .vib/nginx-ingress-controller/runtime-parameters.yaml, .vib/nginx-ingress-controller/vib-publish.json, .vib/nginx-ingress-controller/vib-verify.json, bitnami/nginx-ingress-controller/Chart.yaml
This PR replaces the [kuard image](https://github.com/kubernetes-up-and-running/kuard) used as demo web app for NGINX Ingress Controller ginkgo tests. Instead, we'll use Bitnami Dokuwiki since it's compatible with multi-arch environments.
VIB tests pass on different arch clusters.
None
N/A
N/A
=> [bitnami/nginx-ingress-controller] Replace kuard with dokuwiki

bitnami/solr/Chart.lock, bitnami/solr/Chart.yaml, bitnami/solr/templates/ingress.yaml, bitnami/solr/templates/metrics-deployment.yaml, bitnami/solr/templates/metrics-svc.yaml, bitnami/solr/templates/pdb.yaml, bitnami/solr/templates/service-account.yaml, bitnami/solr/templates/statefulset.yaml, bitnami/solr/templates/svc-headless.yaml, bitnami/solr/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/solr]: Use merge helper

bitnami/rabbitmq-cluster-operator/Chart.lock, bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/templates/cluster-operator/deployment.yaml, bitnami/rabbitmq-cluster-operator/templates/cluster-operator/metrics-service.yaml, bitnami/rabbitmq-cluster-operator/templates/cluster-operator/service-account.yaml, bitnami/rabbitmq-cluster-operator/templates/cluster-operator/servicemonitor.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/deployment.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/metrics-service.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/service-account.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/servicemonitor.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/webhook-service.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/rabbitmq-cluster-operator]: Use merge helper

bitnami/mongodb-sharded/Chart.lock, bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/config-server/config-server-poddisruptionbudget.yaml, bitnami/mongodb-sharded/templates/config-server/config-server-podmonitor.yaml, bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml, bitnami/mongodb-sharded/templates/headless-service.yaml, bitnami/mongodb-sharded/templates/mongos/mongos-dep-sts.yaml, bitnami/mongodb-sharded/templates/mongos/mongos-poddisruptionbudget.yaml, bitnami/mongodb-sharded/templates/mongos/mongos-podmonitor.yaml, bitnami/mongodb-sharded/templates/mongos/mongos-service-per-replica.yaml, bitnami/mongodb-sharded/templates/mongos/mongos-service.yaml, bitnami/mongodb-sharded/templates/serviceaccount.yaml, bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml, bitnami/mongodb-sharded/templates/shard/shard-data-poddisruptionbudget.yaml, bitnami/mongodb-sharded/templates/shard/shard-data-podmonitor.yaml, bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/mongodb-sharded]: Use merge helper

bitnami/kong/Chart.lock, bitnami/kong/Chart.yaml, bitnami/kong/templates/dep-ds.yaml, bitnami/kong/templates/ingress-controller-serviceaccount.yaml, bitnami/kong/templates/ingress.yaml, bitnami/kong/templates/metrics-service.yaml, bitnami/kong/templates/migrate-job.yaml, bitnami/kong/templates/pdb.yaml, bitnami/kong/templates/service.yaml, bitnami/kong/templates/servicemonitor.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/kong]: Use merge helper

.vib/clickhouse/ginkgo/clickhouse_suite_test.go, bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/README.md, bitnami/clickhouse/values.yaml
Set zookeeper 3.8 image because there is an incompatibility with Zookeeper 3.9.x, see: https://github.com/ClickHouse/ClickHouse/issues/53749
=> [bitnami/clickhouse] Set Zookeeper 3.8.x as subchart

bitnami/wordpress/Chart.lock, bitnami/wordpress/Chart.yaml, bitnami/wordpress/templates/deployment.yaml, bitnami/wordpress/templates/ingress.yaml, bitnami/wordpress/templates/metrics-svc.yaml, bitnami/wordpress/templates/networkpolicy-backend-ingress.yaml, bitnami/wordpress/templates/networkpolicy-ingress.yaml, bitnami/wordpress/templates/pdb.yaml, bitnami/wordpress/templates/pvc.yaml, bitnami/wordpress/templates/serviceaccount.yaml, bitnami/wordpress/templates/servicemonitor.yaml, bitnami/wordpress/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/wordpress]: Use merge helper

bitnami/spark/Chart.lock, bitnami/spark/Chart.yaml, bitnami/spark/templates/headless-svc.yaml, bitnami/spark/templates/ingress.yaml, bitnami/spark/templates/serviceaccount.yaml, bitnami/spark/templates/statefulset-master.yaml, bitnami/spark/templates/statefulset-worker.yaml, bitnami/spark/templates/svc-master.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/spark]: Use merge helper

bitnami/nginx/Chart.lock, bitnami/nginx/Chart.yaml, bitnami/nginx/templates/deployment.yaml, bitnami/nginx/templates/health-ingress.yaml, bitnami/nginx/templates/ingress.yaml, bitnami/nginx/templates/pdb.yaml, bitnami/nginx/templates/serviceaccount.yaml, bitnami/nginx/templates/servicemonitor.yaml, bitnami/nginx/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/nginx]: Use merge helper

bitnami/mariadb-galera/Chart.lock, bitnami/mariadb-galera/Chart.yaml, bitnami/mariadb-galera/templates/headless-svc.yaml, bitnami/mariadb-galera/templates/metrics-svc.yaml, bitnami/mariadb-galera/templates/pdb.yaml, bitnami/mariadb-galera/templates/serviceaccount.yaml, bitnami/mariadb-galera/templates/servicemonitor.yaml, bitnami/mariadb-galera/templates/statefulset.yaml, bitnami/mariadb-galera/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/mariadb-galera]: Use merge helper

bitnami/consul/Chart.lock, bitnami/consul/Chart.yaml, bitnami/consul/templates/consul-headless-service.yaml, bitnami/consul/templates/ingress.yaml, bitnami/consul/templates/metrics-svc.yaml, bitnami/consul/templates/pdb.yaml, bitnami/consul/templates/service.yaml, bitnami/consul/templates/servicemonitor.yaml, bitnami/consul/templates/statefulset.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/consul]: Use merge helper

.vib/mariadb-galera/ginkgo/mariadb_suite_test.go, bitnami/mariadb/Chart.lock, bitnami/mariadb/Chart.yaml, bitnami/mariadb/templates/primary/networkpolicy-ingress.yaml, bitnami/mariadb/templates/primary/pdb.yaml, bitnami/mariadb/templates/primary/statefulset.yaml, bitnami/mariadb/templates/primary/svc.yaml, bitnami/mariadb/templates/secondary/networkpolicy-ingress.yaml, bitnami/mariadb/templates/secondary/pdb.yaml, bitnami/mariadb/templates/secondary/statefulset.yaml, bitnami/mariadb/templates/secondary/svc.yaml, bitnami/mariadb/templates/serviceaccount.yaml, bitnami/mariadb/templates/servicemonitor.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/mariadb]: Use merge helper

bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/templates/deployment.yaml, bitnami/sonarqube/templates/ingress.yaml, bitnami/sonarqube/templates/jmx-metrics-svc.yaml, bitnami/sonarqube/templates/jmx-servicemonitor.yaml, bitnami/sonarqube/templates/pvc.yaml, bitnami/sonarqube/templates/service-account.yaml, bitnami/sonarqube/templates/service.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/sonarqube]: Use merge helper

bitnami/parse/Chart.yaml, bitnami/parse/templates/dashboard-deployment.yaml, bitnami/parse/templates/dashboard-svc.yaml, bitnami/parse/templates/ingress.yaml, bitnami/parse/templates/pvc.yaml, bitnami/parse/templates/server-deployment.yaml, bitnami/parse/templates/server-svc.yaml, bitnami/parse/templates/service-account.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/parse]: Use merge helper

bitnami/gitea/Chart.lock, bitnami/gitea/Chart.yaml, bitnami/gitea/templates/deployment.yaml, bitnami/gitea/templates/ingress.yaml, bitnami/gitea/templates/pvc.yaml, bitnami/gitea/templates/service-account.yaml, bitnami/gitea/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/gitea]: Use merge helper

bitnami/matomo/Chart.lock, bitnami/matomo/Chart.yaml, bitnami/matomo/templates/deployment.yaml, bitnami/matomo/templates/ingress.yaml, bitnami/matomo/templates/networkpolicy-backend-ingress.yaml, bitnami/matomo/templates/networkpolicy-ingress.yaml, bitnami/matomo/templates/pvc.yaml, bitnami/matomo/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/matomo]: Use merge helper

bitnami/mediawiki/Chart.lock, bitnami/mediawiki/Chart.yaml, bitnami/mediawiki/templates/deployment.yaml, bitnami/mediawiki/templates/ingress.yaml, bitnami/mediawiki/templates/mediawiki-pvc.yaml, bitnami/mediawiki/templates/metrics-svc.yaml, bitnami/mediawiki/templates/networkpolicy-backend-ingress.yaml, bitnami/mediawiki/templates/networkpolicy-ingress.yaml, bitnami/mediawiki/templates/servicemonitor.yaml, bitnami/mediawiki/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/mediawiki]: Use merge helper

bitnami/mongodb/Chart.lock, bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/arbiter/headless-svc.yaml, bitnami/mongodb/templates/arbiter/pdb.yaml, bitnami/mongodb/templates/arbiter/statefulset.yaml, bitnami/mongodb/templates/hidden/external-access-svc.yaml, bitnami/mongodb/templates/hidden/headless-svc.yaml, bitnami/mongodb/templates/hidden/pdb.yaml, bitnami/mongodb/templates/hidden/statefulset.yaml, bitnami/mongodb/templates/metrics-svc.yaml, bitnami/mongodb/templates/replicaset/external-access-svc.yaml, bitnami/mongodb/templates/replicaset/headless-svc.yaml, bitnami/mongodb/templates/replicaset/pdb.yaml, bitnami/mongodb/templates/replicaset/statefulset.yaml, bitnami/mongodb/templates/replicaset/svc.yaml, bitnami/mongodb/templates/serviceaccount.yaml, bitnami/mongodb/templates/servicemonitor.yaml, bitnami/mongodb/templates/standalone/dep-sts.yaml, bitnami/mongodb/templates/standalone/pvc.yaml, bitnami/mongodb/templates/standalone/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/mongodb]: Use merge helper

bitnami/multus-cni/Chart.lock, bitnami/multus-cni/Chart.yaml, bitnami/multus-cni/templates/daemonset.yaml, bitnami/multus-cni/templates/service-account.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/multus-cni]: Use merge helper

bitnami/argo-workflows/Chart.lock, bitnami/argo-workflows/Chart.yaml, bitnami/argo-workflows/templates/controller/deployment.yaml, bitnami/argo-workflows/templates/controller/pdb.yaml, bitnami/argo-workflows/templates/controller/service-account.yaml, bitnami/argo-workflows/templates/controller/service.yaml, bitnami/argo-workflows/templates/controller/workflow-serviceaccount.yaml, bitnami/argo-workflows/templates/server/deployment.yaml, bitnami/argo-workflows/templates/server/ingress.yaml, bitnami/argo-workflows/templates/server/pdb.yaml, bitnami/argo-workflows/templates/server/service-account.yaml, bitnami/argo-workflows/templates/server/service.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/argo-workflows]: Use merge helper

bitnami/whereabouts/Chart.lock, bitnami/whereabouts/Chart.yaml, bitnami/whereabouts/templates/daemonset.yaml, bitnami/whereabouts/templates/service-account.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/whereabouts]: Use merge helper

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/templates/prometheus-proxy/deployment.yaml, bitnami/spring-cloud-dataflow/templates/prometheus-proxy/pdb.yaml, bitnami/spring-cloud-dataflow/templates/prometheus-proxy/service.yaml, bitnami/spring-cloud-dataflow/templates/prometheus-proxy/servicemonitor-metrics.yaml, bitnami/spring-cloud-dataflow/templates/server/deployment.yaml, bitnami/spring-cloud-dataflow/templates/server/ingress.yaml, bitnami/spring-cloud-dataflow/templates/server/pdb.yaml, bitnami/spring-cloud-dataflow/templates/server/service.yaml, bitnami/spring-cloud-dataflow/templates/serviceaccount.yaml, bitnami/spring-cloud-dataflow/templates/skipper/deployment.yaml, bitnami/spring-cloud-dataflow/templates/skipper/pdb.yaml, bitnami/spring-cloud-dataflow/templates/skipper/service.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/spring-cloud-dataflow]: Use merge helper

bitnami/redmine/Chart.lock, bitnami/redmine/Chart.yaml, bitnami/redmine/templates/cronjob.yaml, bitnami/redmine/templates/deployment.yaml, bitnami/redmine/templates/ingress.yaml, bitnami/redmine/templates/networkpolicy-backend-ingress.yaml, bitnami/redmine/templates/networkpolicy-ingress.yaml, bitnami/redmine/templates/pdb.yaml, bitnami/redmine/templates/pvc.yaml, bitnami/redmine/templates/serviceaccount.yaml, bitnami/redmine/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/redmine]: Use merge helper

bitnami/phpbb/Chart.lock, bitnami/phpbb/Chart.yaml, bitnami/phpbb/templates/deployment.yaml, bitnami/phpbb/templates/ingress.yaml, bitnami/phpbb/templates/networkpolicy-backend-ingress.yaml, bitnami/phpbb/templates/networkpolicy-ingress.yaml, bitnami/phpbb/templates/phpbb-pvc.yaml, bitnami/phpbb/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/phpbb]: Use merge helper

bitnami/osclass/Chart.lock, bitnami/osclass/Chart.yaml, bitnami/osclass/templates/deployment.yaml, bitnami/osclass/templates/ingress.yaml, bitnami/osclass/templates/metrics-svc.yaml, bitnami/osclass/templates/networkpolicy-backend-ingress.yaml, bitnami/osclass/templates/networkpolicy-ingress.yaml, bitnami/osclass/templates/osclass-pvc.yaml, bitnami/osclass/templates/pdb.yaml, bitnami/osclass/templates/servicemonitor.yaml, bitnami/osclass/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/osclass]: Use merge helper

bitnami/kube-state-metrics/Chart.lock, bitnami/kube-state-metrics/Chart.yaml, bitnami/kube-state-metrics/templates/deployment.yaml, bitnami/kube-state-metrics/templates/service.yaml, bitnami/kube-state-metrics/templates/serviceaccount.yaml, bitnami/kube-state-metrics/templates/servicemonitor.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/kube-state-metrics]: Use merge helper

bitnami/haproxy/Chart.lock, bitnami/haproxy/Chart.yaml, bitnami/haproxy/templates/deployment.yaml, bitnami/haproxy/templates/pdb.yaml, bitnami/haproxy/templates/service-account.yaml, bitnami/haproxy/templates/service.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/haproxy]: Use merge helper

bitnami/jupyterhub/Chart.lock, bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/templates/hub/deployment.yaml, bitnami/jupyterhub/templates/hub/networkpolicy.yaml, bitnami/jupyterhub/templates/hub/pdb.yaml, bitnami/jupyterhub/templates/hub/service-account.yaml, bitnami/jupyterhub/templates/hub/service.yaml, bitnami/jupyterhub/templates/hub/servicemonitor.yaml, bitnami/jupyterhub/templates/image-puller/daemonset.yaml, bitnami/jupyterhub/templates/proxy/deployment.yaml, bitnami/jupyterhub/templates/proxy/ingress.yaml, bitnami/jupyterhub/templates/proxy/networkpolicy.yaml, bitnami/jupyterhub/templates/proxy/pdb.yaml, bitnami/jupyterhub/templates/proxy/service-account.yaml, bitnami/jupyterhub/templates/proxy/service-api.yaml, bitnami/jupyterhub/templates/proxy/service-metrics.yaml, bitnami/jupyterhub/templates/proxy/service-public.yaml, bitnami/jupyterhub/templates/proxy/servicemonitor.yaml, bitnami/jupyterhub/templates/singleuser/networkpolicy.yaml, bitnami/jupyterhub/templates/singleuser/service-account.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/jupyterhub]: Use merge helper

bitnami/opencart/Chart.lock, bitnami/opencart/Chart.yaml, bitnami/opencart/templates/deployment.yaml, bitnami/opencart/templates/ingress.yaml, bitnami/opencart/templates/networkpolicy-backend-ingress.yaml, bitnami/opencart/templates/networkpolicy-ingress.yaml, bitnami/opencart/templates/pvc.yaml, bitnami/opencart/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/opencart]: Use merge helper

bitnami/kubeapps/Chart.lock, bitnami/kubeapps/Chart.yaml, bitnami/kubeapps/templates/apprepository/deployment.yaml, bitnami/kubeapps/templates/apprepository/serviceaccount.yaml, bitnami/kubeapps/templates/dashboard/deployment.yaml, bitnami/kubeapps/templates/dashboard/service.yaml, bitnami/kubeapps/templates/frontend/deployment.yaml, bitnami/kubeapps/templates/frontend/service.yaml, bitnami/kubeapps/templates/ingress-api.yaml, bitnami/kubeapps/templates/ingress.yaml, bitnami/kubeapps/templates/kubeappsapis/deployment.yaml, bitnami/kubeapps/templates/kubeappsapis/service.yaml, bitnami/kubeapps/templates/kubeappsapis/serviceaccount.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/kubeapps]: Use merge helper

bitnami/tomcat/Chart.lock, bitnami/tomcat/Chart.yaml, bitnami/tomcat/templates/_pod.tpl, bitnami/tomcat/templates/deployment.yaml, bitnami/tomcat/templates/ingress.yaml, bitnami/tomcat/templates/networkpolicy.yaml, bitnami/tomcat/templates/podmonitor.yaml, bitnami/tomcat/templates/statefulset.yaml, bitnami/tomcat/templates/svc-headless.yaml, bitnami/tomcat/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/tomcat]: Use merge helper

.vib/contour/runtime-parameters.yaml
This PR fixes the `values.yaml` used to install Contour chart since we're setting the same container port for both HTTP & HTTPS .
Testing Contour with a reasonable configuration.
None
N/A
N/A
=> [bitnami/contour]: VIB test envoy's container port

bitnami/pytorch/Chart.lock, bitnami/pytorch/Chart.yaml, bitnami/pytorch/templates/deployment.yaml, bitnami/pytorch/templates/headless-svc.yaml, bitnami/pytorch/templates/pvc.yaml, bitnami/pytorch/templates/service.yaml, bitnami/pytorch/templates/statefulset.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/pytorch]: Use merge helper

bitnami/pinniped/Chart.lock, bitnami/pinniped/Chart.yaml, bitnami/pinniped/templates/concierge/deployment.yaml, bitnami/pinniped/templates/concierge/impersonation-proxy-service-account.yaml, bitnami/pinniped/templates/concierge/kube-cert-agent-service-account.yaml, bitnami/pinniped/templates/concierge/service-account.yaml, bitnami/pinniped/templates/concierge/service-api.yaml, bitnami/pinniped/templates/concierge/service-proxy.yaml, bitnami/pinniped/templates/supervisor/deployment.yaml, bitnami/pinniped/templates/supervisor/ingress.yaml, bitnami/pinniped/templates/supervisor/service-account.yaml, bitnami/pinniped/templates/supervisor/service-api.yaml, bitnami/pinniped/templates/supervisor/service.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/pinniped]: Use merge helper

bitnami/rabbitmq/Chart.lock, bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/ingress.yaml, bitnami/rabbitmq/templates/networkpolicy.yaml, bitnami/rabbitmq/templates/pdb.yaml, bitnami/rabbitmq/templates/serviceaccount.yaml, bitnami/rabbitmq/templates/servicemonitor.yaml, bitnami/rabbitmq/templates/statefulset.yaml, bitnami/rabbitmq/templates/svc-headless.yaml, bitnami/rabbitmq/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/rabbitmq]: Use merge helper

bitnami/fluentd/Chart.lock, bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/aggregator-hpa.yaml, bitnami/fluentd/templates/aggregator-statefulset.yaml, bitnami/fluentd/templates/aggregator-svc-headless.yaml, bitnami/fluentd/templates/aggregator-svc.yaml, bitnami/fluentd/templates/forwarder-daemonset.yaml, bitnami/fluentd/templates/forwarder-svc.yaml, bitnami/fluentd/templates/ingress.yaml, bitnami/fluentd/templates/metrics-svc.yaml, bitnami/fluentd/templates/serviceaccount.yaml, bitnami/fluentd/templates/servicemonitor.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/fluentd]: Use merge helper

bitnami/apache/Chart.lock, bitnami/apache/Chart.yaml, bitnami/apache/templates/deployment.yaml, bitnami/apache/templates/ingress.yaml, bitnami/apache/templates/metrics-svc.yaml, bitnami/apache/templates/pdb.yaml, bitnami/apache/templates/prometheusrules.yaml, bitnami/apache/templates/servicemonitor.yaml, bitnami/apache/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/apache]: Use merge helper

.vib/contour/goss/goss.yaml, bitnami/contour/Chart.yaml
This PR fixes a typo in contour goss tests since we're accessing to Envoy UI using http protocol but https port.
Fix test suite.
None
N/A
N/A
=> [bitnami/contour]: Fix typo in goss tests

bitnami/ghost/Chart.lock, bitnami/ghost/Chart.yaml, bitnami/ghost/templates/deployment.yaml, bitnami/ghost/templates/ingress.yaml, bitnami/ghost/templates/networkpolicy-backend-ingress.yaml, bitnami/ghost/templates/networkpolicy-ingress.yaml, bitnami/ghost/templates/pvc.yaml, bitnami/ghost/templates/service-account.yaml, bitnami/ghost/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/ghost]: Use merge helper

.vib/zookeeper/ginkgo/zookeeper_suite_test.go, bitnami/zookeeper/Chart.lock, bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/templates/metrics-svc.yaml, bitnami/zookeeper/templates/networkpolicy.yaml, bitnami/zookeeper/templates/pdb.yaml, bitnami/zookeeper/templates/serviceaccount.yaml, bitnami/zookeeper/templates/statefulset.yaml, bitnami/zookeeper/templates/svc-headless.yaml, bitnami/zookeeper/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/zookeeper]: Use merge helper

bitnami/dokuwiki/Chart.lock, bitnami/dokuwiki/Chart.yaml, bitnami/dokuwiki/templates/deployment.yaml, bitnami/dokuwiki/templates/dokuwiki-pvc.yaml, bitnami/dokuwiki/templates/ingress.yaml, bitnami/dokuwiki/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/dokuwiki]: Use merge helper

bitnami/common/Chart.yaml, bitnami/common/templates/_labels.tpl
This PR attempts to fix an incompatibility introduced at #18154 due to the use of "new line" characters on some `dict` instructions. [This limitation](https://github.com/golang/go/issues/29770) that was fixed in `go1.16` affects Helm < 3.6 versions.
Users can use any Helm 3.2.0+ version with `bitnami/common`.
None
- fixes #19011
N/A
=> [bitnami/common]: Compatiblity with Helm 3.2.0+

bitnami/postgresql-ha/Chart.lock, bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/templates/networkpolicy-egress.yaml, bitnami/postgresql-ha/templates/networkpolicy-ingress.yaml, bitnami/postgresql-ha/templates/pgpool/deployment.yaml, bitnami/postgresql-ha/templates/pgpool/pdb.yaml, bitnami/postgresql-ha/templates/pgpool/service.yaml, bitnami/postgresql-ha/templates/postgresql/metrics-service.yaml, bitnami/postgresql-ha/templates/postgresql/pdb.yaml, bitnami/postgresql-ha/templates/postgresql/service-headless.yaml, bitnami/postgresql-ha/templates/postgresql/service-witness.yaml, bitnami/postgresql-ha/templates/postgresql/service.yaml, bitnami/postgresql-ha/templates/postgresql/servicemonitor.yaml, bitnami/postgresql-ha/templates/postgresql/statefulset.yaml, bitnami/postgresql-ha/templates/postgresql/witness-statefulset.yaml, bitnami/postgresql-ha/templates/serviceaccount.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/postgresql-ha]: Use merge helper

bitnami/supabase/Chart.lock, bitnami/supabase/Chart.yaml, bitnami/supabase/templates/auth/deployment.yaml, bitnami/supabase/templates/auth/service.yaml, bitnami/supabase/templates/jwt-init-job.yaml, bitnami/supabase/templates/meta/deployment.yaml, bitnami/supabase/templates/meta/service.yaml, bitnami/supabase/templates/realtime/deployment.yaml, bitnami/supabase/templates/realtime/service.yaml, bitnami/supabase/templates/rest/deployment.yaml, bitnami/supabase/templates/rest/service.yaml, bitnami/supabase/templates/service-account.yaml, bitnami/supabase/templates/storage/deployment.yaml, bitnami/supabase/templates/storage/pvc.yaml, bitnami/supabase/templates/storage/service.yaml, bitnami/supabase/templates/studio/deployment.yaml, bitnami/supabase/templates/studio/ingress.yaml, bitnami/supabase/templates/studio/service.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/supabase]: Use merge helper

bitnami/phpmyadmin/Chart.lock, bitnami/phpmyadmin/Chart.yaml, bitnami/phpmyadmin/templates/deployment.yaml, bitnami/phpmyadmin/templates/ingress.yaml, bitnami/phpmyadmin/templates/metrics-svc.yaml, bitnami/phpmyadmin/templates/networkpolicy-backend-ingress.yaml, bitnami/phpmyadmin/templates/networkpolicy-ingress.yaml, bitnami/phpmyadmin/templates/service.yaml, bitnami/phpmyadmin/templates/serviceaccount.yaml, bitnami/phpmyadmin/templates/servicemonitor.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/phpmyadmin]: Use merge helper

bitnami/magento/Chart.lock, bitnami/magento/Chart.yaml, bitnami/magento/templates/deployment.yaml, bitnami/magento/templates/ingress.yaml, bitnami/magento/templates/metrics-svc.yaml, bitnami/magento/templates/networkpolicy-backend-ingress.yaml, bitnami/magento/templates/networkpolicy-ingress.yaml, bitnami/magento/templates/pv.yaml, bitnami/magento/templates/pvc.yaml, bitnami/magento/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/magento]: Use merge helper

bitnami/joomla/Chart.lock, bitnami/joomla/Chart.yaml, bitnami/joomla/templates/deployment.yaml, bitnami/joomla/templates/ingress.yaml, bitnami/joomla/templates/joomla-pvc.yaml, bitnami/joomla/templates/networkpolicy-backend-ingress.yaml, bitnami/joomla/templates/networkpolicy-ingress.yaml, bitnami/joomla/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/joomla]: Use merge helper

bitnami/jenkins/Chart.lock, bitnami/jenkins/Chart.yaml, bitnami/jenkins/templates/agent-listener-svc.yaml, bitnami/jenkins/templates/controller-svc.yaml, bitnami/jenkins/templates/deployment.yaml, bitnami/jenkins/templates/ingress.yaml, bitnami/jenkins/templates/pvc.yaml, bitnami/jenkins/templates/serviceaccount.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/jenkins]: Use merge helper

bitnami/harbor/Chart.lock, bitnami/harbor/Chart.yaml, bitnami/harbor/templates/core/core-dpl.yaml, bitnami/harbor/templates/core/core-svc.yaml, bitnami/harbor/templates/exporter/exporter-dpl.yaml, bitnami/harbor/templates/exporter/exporter-svc.yaml, bitnami/harbor/templates/ingress/core-ingress.yaml, bitnami/harbor/templates/ingress/notary-ingress.yaml, bitnami/harbor/templates/jobservice/jobservice-dpl.yaml, bitnami/harbor/templates/jobservice/jobservice-pvc.yaml, bitnami/harbor/templates/jobservice/jobservice-scandata-pvc.yaml, bitnami/harbor/templates/jobservice/jobservice-svc.yaml, bitnami/harbor/templates/metrics/metrics-svcmonitor.yaml, bitnami/harbor/templates/nginx/deployment.yaml, bitnami/harbor/templates/nginx/service.yaml, bitnami/harbor/templates/notary/notary-server.yaml, bitnami/harbor/templates/notary/notary-signer.yaml, bitnami/harbor/templates/notary/notary-svc.yaml, bitnami/harbor/templates/portal/portal-dpl.yaml, bitnami/harbor/templates/portal/portal-svc.yaml, bitnami/harbor/templates/registry/registry-dpl.yaml, bitnami/harbor/templates/registry/registry-pvc.yaml, bitnami/harbor/templates/registry/registry-svc.yaml, bitnami/harbor/templates/trivy/trivy-sts.yaml, bitnami/harbor/templates/trivy/trivy-svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/harbor]: Use merge helper

bitnami/cert-manager/Chart.lock, bitnami/cert-manager/Chart.yaml, bitnami/cert-manager/templates/cainjector/deployment.yaml, bitnami/cert-manager/templates/cainjector/serviceaccount.yaml, bitnami/cert-manager/templates/controller/deployment.yaml, bitnami/cert-manager/templates/controller/service.yaml, bitnami/cert-manager/templates/controller/serviceaccount.yaml, bitnami/cert-manager/templates/controller/servicemonitor.yaml, bitnami/cert-manager/templates/webhook/deployment.yaml, bitnami/cert-manager/templates/webhook/service.yaml, bitnami/cert-manager/templates/webhook/serviceaccount.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/cert-manager]: Use merge helper

bitnami/apisix/Chart.lock, bitnami/apisix/Chart.yaml, bitnami/apisix/templates/control-plane/dep-ds.yaml, bitnami/apisix/templates/control-plane/ingress.yaml, bitnami/apisix/templates/control-plane/pdb.yaml, bitnami/apisix/templates/control-plane/service-account.yaml, bitnami/apisix/templates/control-plane/service.yaml, bitnami/apisix/templates/control-plane/servicemonitor.yaml, bitnami/apisix/templates/control-plane/vpa.yaml, bitnami/apisix/templates/dashboard/deployment.yaml, bitnami/apisix/templates/dashboard/ingress.yaml, bitnami/apisix/templates/dashboard/pdb.yaml, bitnami/apisix/templates/dashboard/service-account.yaml, bitnami/apisix/templates/dashboard/service.yaml, bitnami/apisix/templates/dashboard/vpa.yaml, bitnami/apisix/templates/data-plane/dep-ds.yaml, bitnami/apisix/templates/data-plane/ingress.yaml, bitnami/apisix/templates/data-plane/pdb.yaml, bitnami/apisix/templates/data-plane/service-account.yaml, bitnami/apisix/templates/data-plane/service.yaml, bitnami/apisix/templates/data-plane/servicemonitor.yaml, bitnami/apisix/templates/data-plane/vpa.yaml, bitnami/apisix/templates/ingress-controller/deployment.yaml, bitnami/apisix/templates/ingress-controller/ingress.yaml, bitnami/apisix/templates/ingress-controller/pdb.yaml, bitnami/apisix/templates/ingress-controller/service-account.yaml, bitnami/apisix/templates/ingress-controller/service.yaml, bitnami/apisix/templates/ingress-controller/servicemonitor.yaml, bitnami/apisix/templates/ingress-controller/vpa.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/apisix]: Use merge helper

bitnami/node-exporter/Chart.lock, bitnami/node-exporter/Chart.yaml, bitnami/node-exporter/templates/daemonset.yaml, bitnami/node-exporter/templates/service.yaml, bitnami/node-exporter/templates/serviceaccount.yaml, bitnami/node-exporter/templates/servicemonitor.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/node-exporter]: Use merge helper

bitnami/metrics-server/Chart.lock, bitnami/metrics-server/Chart.yaml, bitnami/metrics-server/templates/deployment.yaml, bitnami/metrics-server/templates/pdb.yaml, bitnami/metrics-server/templates/serviceaccount.yaml, bitnami/metrics-server/templates/svc.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/metrics-server]: Use merge helper

bitnami/mysql/Chart.lock, bitnami/mysql/Chart.yaml, bitnami/mysql/templates/metrics-svc.yaml, bitnami/mysql/templates/primary/pdb.yaml, bitnami/mysql/templates/primary/statefulset.yaml, bitnami/mysql/templates/primary/svc-headless.yaml, bitnami/mysql/templates/primary/svc.yaml, bitnami/mysql/templates/secondary/pdb.yaml, bitnami/mysql/templates/secondary/statefulset.yaml, bitnami/mysql/templates/secondary/svc-headless.yaml, bitnami/mysql/templates/secondary/svc.yaml, bitnami/mysql/templates/serviceaccount.yaml, bitnami/mysql/templates/servicemonitor.yaml
```yaml
podLabels:
foo: "bar"
```
```yaml
podLabels: |
```
None
N/A
N/A
=> [bitnami/mysql]: Use merge helper

bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/_helpers.tpl, bitnami/fluentd/templates/aggregator-statefulset.yaml, bitnami/fluentd/templates/forwarder-daemonset.yaml
This change fixes some missing functions to use initScript correctly.
- fixes #18377
=> [bitnami/fluentd] Fix some functions for using initScripts

bitnami/common/Chart.yaml, bitnami/common/templates/_images.tpl
This PR adds a new helper to `bitnami/common` that returns an image version.
This helper can be useful for setting the `app.kubernetes.io/version` label, for instance:
```yaml
app.kubernetes.io/version: {{ include "common.images.version" ( dict "imageRoot" .Values.image "chart" .Chart ) | quote }}
```
None
N/A
N/A
=> [bitnami/common] New helper to return image version

bitnami/magento/Chart.yaml, bitnami/magento/README.md, bitnami/magento/templates/_helpers.tpl, bitnami/magento/values.yaml
It uses ports 80 and 443 as default ports for the service. It also adds the use of `magentoHost`.
Fix usage with ingress.
N/A
- fixes #19231
N/A
=> [bitnami/magento] Fix magentoHost when using Ingress #19262

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/README.md, bitnami/redis-cluster/templates/update-cluster.yaml, bitnami/redis-cluster/values.yaml
Ability to setup other Helm hook rather than hard coded one.
On ArgoCD side, a hard coded `"helm.sh/hook": post-upgrade` hook is equivalent to `argocd.argoproj.io/hook: PostSync`, which means, hook will be launched only when ArgoCD application is fully synced.
But it never does as new added node runs in standalone mode and as the default `readinessProbe` is [checking for cluster info](https://github.com/bitnami/charts/blob/main/bitnami/redis-cluster/templates/scripts-configmap.yaml#L52-L77) it will always fail.
Ability to setup other Helm hook would help to launch the script on ArgoCD side.
N/A
- fixes https://github.com/bitnami/charts/issues/18924
N/A
=> [bitnami/redis-cluster] Allow set Helm/ArgoCD hook for updateJob

.vib/grafana-mimir/vib-publish.json, .vib/grafana-mimir/vib-verify.json
This PR increments the cluster size to use for testing Grafana Mimir to M4 (same used for Grafana Tempo) given the big amount of pods this chart deploys by default.
Improve tests reliability
None
N/A
N/A
=> [grafana-mimir] Increment cluster size for testing Grafana Mimir in VIB

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/backup/cronjob.yaml
This will enable backups with `auth: {enabled: false}`
=> [bitnami/mongodb] enable backup with auth: {enabled: false}

bitnami/mastodon/Chart.yaml, bitnami/mastodon/templates/apache-configmap.yaml
The change removes a duplicated `VirtualHost` entry in the Apache config map and adds the `ProxyPreserveHost on` option
Removing the duplicated `VirtualHost` entry from the config map removes an "Unrecognized VirtualHost VirtualHost" error in the Apache pod logs.
Enabling `ProxyPreserveHost` allows Mastodon federation functionalities to work properly when behind Apache. According to the [documentation](https://docs.joinmastodon.org/spec/security/#http), Mastodon requires a signature based partially on the `Host` header. That signature then gets deciphered upon receiving. However, if Apache overwrites the host header (the default behavior), the deciphered signature does not match the source one and incoming federation operations throw a `401 unauthorized` error in Apache logs.
None that …
=> [bitnami/mastodon] Add `ProxyPreserveHost on` and remove duplicated `VirtualHost` in apache-configmap.yaml

.vib/mongodb-sharded/ginkgo/mongodb_suite_test.go, bitnami/mongodb-sharded/Chart.yaml
In slow platforms the ginkgo tests are failing when performing scale down and scale up. This PR fixes it.
- fixes #
=> [bitnami/mongodb-sharded] test: :white_check_mark: Bump timeouts

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/_helpers.tpl
Fixes #19285
Adds back in a missing newline which causes invalid YAML when serviceMonitor selector labels are specified.
Valid YAML when the setting is used.
I have tested with an without the `selector` configured and the output looks good.
#19285
=> [bitnami/thanos] Fix line break issue with serviceMonitor selector labels

bitnami/airflow/Chart.lock, bitnami/airflow/Chart.yaml, bitnami/airflow/templates/metrics/deployment.yaml, bitnami/airflow/templates/metrics/service.yaml, bitnami/airflow/templates/metrics/servicemonitor.yaml, bitnami/airflow/templates/scheduler/deployment.yaml, bitnami/airflow/templates/scheduler/poddisruptionbudget.yaml, bitnami/airflow/templates/scheduler/service-headless.yaml, bitnami/airflow/templates/web/deployment.yaml, bitnami/airflow/templates/web/poddisruptionbudget.yaml, bitnami/airflow/templates/web/service.yaml, bitnami/airflow/templates/worker/horizontalpodautoscaler.yaml, bitnami/airflow/templates/worker/poddisruptionbudget.yaml, bitnami/airflow/templates/worker/service-headless.yaml, bitnami/airflow/templates/worker/statefulset.yaml
=> [bitnami/airflow] Use different app.kubernetes.io/version label on subcomponents

bitnami/argo-cd/Chart.lock, bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/dex/deployment.yaml, bitnami/argo-cd/templates/dex/metrics-svc.yaml, bitnami/argo-cd/templates/dex/role.yaml, bitnami/argo-cd/templates/dex/rolebinding.yaml, bitnami/argo-cd/templates/dex/service-account.yaml, bitnami/argo-cd/templates/dex/service.yaml, bitnami/argo-cd/templates/dex/servicemonitor.yaml
=> [bitnami/argo-cd] Use different app.kubernetes.io/version label on subcomponents

bitnami/cert-manager/Chart.lock, bitnami/cert-manager/Chart.yaml, bitnami/cert-manager/templates/cainjector/deployment.yaml, bitnami/cert-manager/templates/cainjector/rbac.yaml, bitnami/cert-manager/templates/cainjector/serviceaccount.yaml, bitnami/cert-manager/templates/controller/deployment.yaml, bitnami/cert-manager/templates/controller/rbac.yaml, bitnami/cert-manager/templates/controller/service.yaml, bitnami/cert-manager/templates/controller/serviceaccount.yaml, bitnami/cert-manager/templates/controller/servicemonitor.yaml, bitnami/cert-manager/templates/webhook/deployment.yaml, bitnami/cert-manager/templates/webhook/mutating-webhook.yaml, bitnami/cert-manager/templates/webhook/rbac.yaml, bitnami/cert-manager/templates/webhook/service.yaml, bitnami/cert-manager/templates/webhook/serviceaccount.yaml, bitnami/cert-manager/templates/webhook/validating-webhook.yaml
=> [bitnami/cert-manager] Use different app.kubernetes.io/version label on subcomponents

bitnami/contour/Chart.lock, bitnami/contour/Chart.yaml, bitnami/contour/templates/certgen/job.yaml, bitnami/contour/templates/certgen/rbac.yaml, bitnami/contour/templates/certgen/serviceaccount.yaml, bitnami/contour/templates/contour/configmap.yaml, bitnami/contour/templates/contour/deployment.yaml, bitnami/contour/templates/contour/ingressclass.yaml, bitnami/contour/templates/contour/rbac.yaml, bitnami/contour/templates/contour/service.yaml, bitnami/contour/templates/contour/serviceaccount.yaml, bitnami/contour/templates/contour/servicemonitor.yaml, bitnami/contour/templates/default-backend/deployment.yaml, bitnami/contour/templates/default-backend/ingress.yaml, bitnami/contour/templates/default-backend/poddisruptionbudget.yaml, bitnami/contour/templates/default-backend/service.yaml, bitnami/contour/templates/default-backend/tls-secrets.yaml, bitnami/contour/templates/envoy/daemonset.yaml, bitnami/contour/templates/envoy/deployment.yaml, bitnami/contour/templates/envoy/hpa.yaml, bitnami/contour/templates/envoy/prometheusrule.yaml, bitnami/contour/templates/envoy/service.yaml, bitnami/contour/templates/envoy/serviceaccount.yaml, bitnami/contour/templates/envoy/servicemonitor.yaml
=> [bitnami/contour] Use different app.kubernetes.io/version label on subcomponents

bitnami/metallb/Chart.lock, bitnami/metallb/Chart.yaml, bitnami/metallb/templates/speaker/daemonset.yaml, bitnami/metallb/templates/speaker/psp.yaml, bitnami/metallb/templates/speaker/rbac.yaml, bitnami/metallb/templates/speaker/secret.yaml, bitnami/metallb/templates/speaker/service.yaml, bitnami/metallb/templates/speaker/serviceaccount.yaml, bitnami/metallb/templates/speaker/servicemonitor.yaml
=> [bitnami/metallb] Use different app.kubernetes.io/version label on subcomponents

bitnami/milvus/Chart.lock, bitnami/milvus/Chart.yaml, bitnami/milvus/templates/attu/deployment.yaml, bitnami/milvus/templates/attu/hpa.yaml, bitnami/milvus/templates/attu/ingress-tls-secret.yaml, bitnami/milvus/templates/attu/ingress.yaml, bitnami/milvus/templates/attu/networkpolicy.yaml, bitnami/milvus/templates/attu/pdb.yaml, bitnami/milvus/templates/attu/service-account.yaml, bitnami/milvus/templates/attu/service.yaml, bitnami/milvus/templates/attu/vpa.yaml, bitnami/milvus/templates/init-job.yaml
=> [bitnami/milvus] Use different app.kubernetes.io/version label on subcomponents

bitnami/grafana/Chart.lock, bitnami/grafana/Chart.yaml, bitnami/grafana/README.md, bitnami/grafana/templates/service.yaml, bitnami/grafana/values.yaml
`loadBalancerClass` is introduced since Kubernetes 1.24 to allow specify the LB provider.
This PR adds the support to set `loadBalancerClass` in grafana helm chart.
Allow to set `loadBalancerClass` in grafana chart
- fixes #19316
=> [bitnami/grafana] Allow loadBalancerClass in grafana service

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/templates/default-backend-configmap.yaml, bitnami/nginx-ingress-controller/templates/default-backend-deployment.yaml, bitnami/nginx-ingress-controller/templates/default-backend-poddisruptionbudget.yaml, bitnami/nginx-ingress-controller/templates/default-backend-service.yaml
=> [bitnami/nginx-ingress-controller] Use different app.kubernetes.io/version label on subcomponents

bitnami/apisix/Chart.lock, bitnami/apisix/Chart.yaml, bitnami/apisix/templates/dashboard/configmap.yaml, bitnami/apisix/templates/dashboard/deployment.yaml, bitnami/apisix/templates/dashboard/extra-configmap.yaml, bitnami/apisix/templates/dashboard/hpa.yaml, bitnami/apisix/templates/dashboard/ingress-tls-secret.yaml, bitnami/apisix/templates/dashboard/ingress.yaml, bitnami/apisix/templates/dashboard/pdb.yaml, bitnami/apisix/templates/dashboard/secret.yaml, bitnami/apisix/templates/dashboard/service-account.yaml, bitnami/apisix/templates/dashboard/service.yaml, bitnami/apisix/templates/dashboard/vpa.yaml, bitnami/apisix/templates/ingress-controller/clusterrolebinding.yaml, bitnami/apisix/templates/ingress-controller/clusterroles.yaml, bitnami/apisix/templates/ingress-controller/configmap.yaml, bitnami/apisix/templates/ingress-controller/deployment.yaml, bitnami/apisix/templates/ingress-controller/extra-configmap.yaml, bitnami/apisix/templates/ingress-controller/hpa.yaml, bitnami/apisix/templates/ingress-controller/ingress-tls-secret.yaml, bitnami/apisix/templates/ingress-controller/ingress.yaml, bitnami/apisix/templates/ingress-controller/pdb.yaml, bitnami/apisix/templates/ingress-controller/service-account.yaml, bitnami/apisix/templates/ingress-controller/service.yaml, bitnami/apisix/templates/ingress-controller/servicemonitor.yaml, bitnami/apisix/templates/ingress-controller/vpa.yaml
=> [bitnami/apisix] Use different app.kubernetes.io/version label on subcomponents

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/README.md, bitnami/kube-prometheus/templates/exporters/core-dns/servicemonitor.yaml, bitnami/kube-prometheus/templates/exporters/kube-apiserver/servicemonitor.yaml, bitnami/kube-prometheus/templates/exporters/kube-controller-manager/servicemonitor.yaml, bitnami/kube-prometheus/templates/exporters/kube-proxy/servicemonitor.yaml, bitnami/kube-prometheus/templates/exporters/kube-scheduler/servicemonitor.yaml, bitnami/kube-prometheus/templates/exporters/kubelet/servicemonitor.yaml, bitnami/kube-prometheus/templates/prometheus/servicemonitor.yaml, bitnami/kube-prometheus/values.yaml
This is a follow-up of sorts to #18413: when setting the *global* sample limit, one might also need to set higher sample limits for some service monitors.
More control over the amount of data collected.
None.
None.
Related PRs: #19299, #19323, #19322
=> [bitnami/kube-prometheus] Allow setting ServiceMonitors' sampleLimit for Prometheus and other components

bitnami/argo-workflows/Chart.lock, bitnami/argo-workflows/Chart.yaml, bitnami/argo-workflows/templates/controller/aggregate-cluster-roles.yaml, bitnami/argo-workflows/templates/controller/clusterrolebinding.yaml, bitnami/argo-workflows/templates/controller/controller-cluster-roles.yaml, bitnami/argo-workflows/templates/controller/database-secret.yaml, bitnami/argo-workflows/templates/controller/deployment.yaml, bitnami/argo-workflows/templates/controller/pdb.yaml, bitnami/argo-workflows/templates/controller/service-account.yaml, bitnami/argo-workflows/templates/controller/service.yaml, bitnami/argo-workflows/templates/controller/servicemonitor.yaml, bitnami/argo-workflows/templates/controller/workflow-role.yaml, bitnami/argo-workflows/templates/controller/workflow-rolebinding.yaml, bitnami/argo-workflows/templates/controller/workflow-serviceaccount.yaml, bitnami/argo-workflows/templates/server/cluster-role.yaml, bitnami/argo-workflows/templates/server/clusterrolebinding.yaml, bitnami/argo-workflows/templates/server/deployment.yaml, bitnami/argo-workflows/templates/server/ingress.yaml, bitnami/argo-workflows/templates/server/pdb.yaml, bitnami/argo-workflows/templates/server/service-account.yaml, bitnami/argo-workflows/templates/server/service.yaml, bitnami/argo-workflows/templates/server/tls-secrets.yaml
=> [bitnami/argo-workflows] Use different app.kubernetes.io/version label on subcomponents

bitnami/jupyterhub/Chart.lock, bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/templates/proxy/deployment.yaml, bitnami/jupyterhub/templates/proxy/ingress.yaml, bitnami/jupyterhub/templates/proxy/networkpolicy.yaml, bitnami/jupyterhub/templates/proxy/pdb.yaml, bitnami/jupyterhub/templates/proxy/service-account.yaml, bitnami/jupyterhub/templates/proxy/service-api.yaml, bitnami/jupyterhub/templates/proxy/service-metrics.yaml, bitnami/jupyterhub/templates/proxy/service-public.yaml, bitnami/jupyterhub/templates/proxy/servicemonitor.yaml, bitnami/jupyterhub/templates/proxy/tls-secret.yaml
=> [bitnami/jupyterhub] Use different app.kubernetes.io/version label on subcomponents

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/README.md, bitnami/clickhouse/templates/service-external-access.yaml, bitnami/clickhouse/values.yaml
Current logic is not assigning correctly pod annotations for external access to each shard-replica. In order to assign a DNS address to each loadbalancer for external access, if we have a cluster with 3 shards and 2 replicas per shard, we need to assign 6 annotations. Currently this process is not possible as they are not being assigned in the correct order. 
Now you can assign annotations in the correct order
- fixes #
=> [bitnami/clickhouse] Fix clickhouse external access annotation assignment 

bitnami/grafana-tempo/Chart.lock, bitnami/grafana-tempo/Chart.yaml, bitnami/grafana-tempo/templates/query-frontend/deployment.yaml, bitnami/grafana-tempo/templates/query-frontend/headless-service.yaml, bitnami/grafana-tempo/templates/query-frontend/query-configmap.yaml, bitnami/grafana-tempo/templates/query-frontend/service.yaml, bitnami/grafana-tempo/templates/query-frontend/servicemonitor.yaml, bitnami/grafana-tempo/templates/vulture/deployment.yaml, bitnami/grafana-tempo/templates/vulture/service.yaml, bitnami/grafana-tempo/templates/vulture/servicemonitor.yaml
=> [bitnami/grafana-tempo] Use different app.kubernetes.io/version label on subcomponents

bitnami/postgresql-ha/Chart.lock, bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/templates/pgpool/configmap.yaml, bitnami/postgresql-ha/templates/pgpool/custom-users-secrets.yaml, bitnami/postgresql-ha/templates/pgpool/deployment.yaml, bitnami/postgresql-ha/templates/pgpool/initdb-scripts-configmap.yaml, bitnami/postgresql-ha/templates/pgpool/pdb.yaml, bitnami/postgresql-ha/templates/pgpool/secrets.yaml, bitnami/postgresql-ha/templates/pgpool/service.yaml
=> [bitnami/postgresql-ha] Use different app.kubernetes.io/version label on subcomponents

bitnami/vault/Chart.lock, bitnami/vault/Chart.yaml, bitnami/vault/templates/csi-provider/clusterrole.yaml, bitnami/vault/templates/csi-provider/configmap.yaml, bitnami/vault/templates/csi-provider/daemonset.yaml, bitnami/vault/templates/csi-provider/role.yaml, bitnami/vault/templates/csi-provider/rolebinding.yaml, bitnami/vault/templates/csi-provider/service-account.yaml, bitnami/vault/templates/injector/clusterrolebinding.yaml, bitnami/vault/templates/injector/clusterroles.yaml, bitnami/vault/templates/injector/deployment.yaml, bitnami/vault/templates/injector/hpa.yaml, bitnami/vault/templates/injector/mutating-webhook.yaml, bitnami/vault/templates/injector/pdb.yaml, bitnami/vault/templates/injector/role.yaml, bitnami/vault/templates/injector/rolebinding.yaml, bitnami/vault/templates/injector/service-account.yaml, bitnami/vault/templates/injector/service.yaml
=> [bitnami/vault] Use different app.kubernetes.io/version label on subcomponents

bitnami/rabbitmq-cluster-operator/Chart.lock, bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/certificate.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/clusterrole.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/clusterrolebinding.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/deployment.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/metrics-service.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/role.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/rolebinding.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/service-account.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/servicemonitor.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/validating-webhook-configuration.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/webhook-service.yaml
=> [bitnami/rabbitmq-cluster-operator] Use different app.kubernetes.io/version label on subcomponents

bitnami/parse/Chart.yaml, bitnami/parse/templates/dashboard-deployment.yaml, bitnami/parse/templates/dashboard-svc.yaml
=> [bitnami/parse] Use different app.kubernetes.io/version label on subcomponents

bitnami/nginx/Chart.lock, bitnami/nginx/Chart.yaml, bitnami/nginx/README.md, bitnami/nginx/templates/deployment.yaml, bitnami/nginx/values.yaml
Add `cloneStaticSiteFromGit.extraEnvVarsSecret` value
Allow to use credentials as secret mounted as variables to clone the content of a private repository by using a token instead of a ssh key.
With this, we can use cloneStaticSiteFromGit.repository: "https://oauth2:${token}@github.com/example/test.git" by pickup the token from a secret.
None
=> [bitnami/nginx] add `cloneStaticSiteFromGit.extraEnvVarsSecret`

bitnami/prometheus/Chart.lock, bitnami/prometheus/Chart.yaml, bitnami/prometheus/templates/alertmanager/configmap.yaml, bitnami/prometheus/templates/alertmanager/ingress.yaml, bitnami/prometheus/templates/alertmanager/pdb.yaml, bitnami/prometheus/templates/alertmanager/service-account.yaml, bitnami/prometheus/templates/alertmanager/service-headless.yaml, bitnami/prometheus/templates/alertmanager/service.yaml, bitnami/prometheus/templates/alertmanager/statefulset.yaml
=> [bitnami/prometheus] Use different app.kubernetes.io/version label on subcomponents

bitnami/minio/Chart.yaml, bitnami/minio/templates/api-ingress.yaml, bitnami/minio/templates/ingress.yaml
This PR fixes a bug introduced at #19074 that prevents enabling TLS on Ingress due to an issue with annotations.
Users can use custom enable Ingress with TLS & using custom annotations.
N/A
- fixes #19392
N/A
=> [bitnami/minio]: Fix ingress TLS configuration

bitnami/common/Chart.yaml, bitnami/common/templates/_utils.tpl
The pattern to rollout workloads on config change, described in [helm docs](https://helm.sh/docs/howto/charts_tips_and_tricks/#automatically-roll-deployments), has the issue that it will trigger a reload of the pods when the chart version change, even it the pod template and configmap data are not changed.
This happens because the version of the chart is included in "helm.sh/chart" in metadata.labels (printf "%s-%s" .Chart.Name .Chart.Version) of the configmap and the checksum is done on the whole file.
This new macro calculates the checksum by omitting metadata.
- fixes #18376
=> [bitnami/common] new macro to checksum config resources

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/templates/controller-metrics-service.yaml
Revert this [change](https://github.com/bitnami/charts/pull/18359/files#diff-2e6d2d8189cc2446f17464c22c015ce3ff429b6e51f799db529d532fa51f34d8R14)). 
`ServiceMonitor` matches with the `Service`
N/A
- fixes #19129
=> [bitnami/nginx-ingress-controller] Revert metrics service component label

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/backup/cronjob.yaml
The changes will consider the values passed of ImagePullSecrets and ImagePullPolicy to be passed to backup-cronjob. 
You can pull images from private Repositories and adjust the pull-Strategy.
Users who do not want the values to be passed to the cronjob might have issues. To solve this you might want to make these values configurable for each type of deployment.
However I don't think that there are users who do not want this to happen.
- fixes #19488
=> bitnami/postgresql  Added ImagePullSecrets and ImagePullPolicy to be passed through to backup-cronjob

bitnami/appsmith/Chart.yaml, bitnami/appsmith/templates/_helpers.tpl
Currently, the Appsmith helper template references the MongoDB secret.  This updates the helper template to reference the external Redis secret in the deployment yaml.
- fixes 19474
=> [bitnami/appsmith] - Bug 19474 - Updated reference to external redis secret

.vib/grafana-tempo/goss/goss.yaml, .vib/grafana-tempo/runtime-parameters.yaml
Removes the section of the runtime-parameters and tests that depend on third-party image.
- reverts #17019
=> [bitnami/grafana-tempo] Remove extraDeploy from runtime-parameters (Revert #17019)

.vib/prometheus/runtime-parameters.yaml
- Removes `volumePermissions.enabled=true` from the testing params as it isn't checked by any test and generated incompatibilities with OpenShift
- Uses `server.service.sessionAffinity=None` as `ClientIP` is not compatible con AWS clusters. Moreover, this config is not relevant in the current testing env.
Testing params support AWS clusters
None
N/A
=> [bitnami/prometheus] Adapt runtime-params for non-GKE testing

.vib/elasticsearch/ginkgo/elasticsearch_suite_test.go, bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/README.md, bitnami/elasticsearch/templates/NOTES.txt, bitnami/elasticsearch/templates/_helpers.tpl, bitnami/elasticsearch/templates/master/statefulset.yaml
This PR adds the option to deploy a single-node cluster that assumes all the roles. The following inputs should be provided:
```yaml
master:
masterOnly: false
replicaCount: 1
data:
replicaCount: 0
coordinating:
replicaCount: 0
ingest:
replicaCount: 0
```
The single-node cluster will be configured with [single-node discovery](https://www.elastic.co/guide/en/elasticsearch/reference/current/bootstrap-checks.html#single-node-discovery) in that case.
- Cover more use cases.
- Scaling the replicas up requires reloading the configuration in the existing node. A warning was added in the `NOTES.txt`.
- Originated in #18996, thank you @fabiocastagnino!
=> [bitnami/elasticsearch] Add support for single-node

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/README.md
This PR bumps the chart version in a major since the application has a new major version (6.x.x -> 7.x.x). The major version bump should have been done at https://github.com/bitnami/charts/pull/19575 but it was released as a patch version by mistake
=> [bitnami/mongodb-sharded] Bump major version not bumped at #19575

bitnami/redis/Chart.yaml, bitnami/redis/templates/sentinel/statefulset.yaml
The `redis` chart is missing `kind` & `apiVersion` on one of the statefulsets (others are ok). This causes a unwanted diff in ArgoCD etc.
Fixes the diff so applications will show as in sync
- fixes #
=> [bitnami/redis] add kind & apiVersion for pvc template in statefulset

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/README.md
This PR bumps the chart version in a major since the application has a new major version (15.x.x -> 16.x.x). The major version bump should have been done at https://github.com/bitnami/charts/pull/19590 but it was released as a patch version by mistake
- Closes https://github.com/bitnami/charts/issues/19596
- Relates https://github.com/bitnami/charts/pull/19591
=> [bitnami/postgresql-ha] Bump major version not bumped at #19590

.vib/matomo/runtime-parameters.yaml
Increase `initialDelaySeconds` for testing.
In my local environment, first Matomo intialization takes around 20 seconds after waiting for the database, taking in total around 50 seconds. During the initialization process (20 seconds), the path `/matomo.php` is ready and returning 200 codes, so the container is exposed in the service but it's not fully operative and current cypress tests can fail sporadically. This problem is even worse if the tests are preformed in small platforms.
N/A
At the moment Matomo doesn't provide a better way to check if the [service is ready](https://matomo.org/faq/how-to/faq_20278/) or not. Even if we try to reach `/index.php` and the application is not fully initialized, the application will return a 200 status code.
=> [bitnami/charts] Increase initialDelaySeconds for testing environments

bitnami/nginx-ingress-controller/Chart.lock, bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/templates/podsecuritypolicy.yaml
=> [bitnami/nginx-ingress-controller] Use common capabilities for PSP

bitnami/fluentd/Chart.lock, bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/forwarder-clusterrole.yaml, bitnami/fluentd/templates/forwarder-psp.yaml
=> [bitnami/fluentd] Use common capabilities for PSP

bitnami/mongodb/Chart.lock, bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/psp.yaml, bitnami/mongodb/templates/role.yaml
=> [bitnami/mongodb] Use common capabilities for PSP

bitnami/postgresql/Chart.lock, bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/psp.yaml, bitnami/postgresql/templates/role.yaml
=> [bitnami/postgresql] Use common capabilities for PSP

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/README.md, bitnami/nginx-ingress-controller/templates/controller-service.yaml, bitnami/nginx-ingress-controller/values.yaml
This pull request adds support for setting ipFamilyPolicy and ipFamilies in nginx-ingress-controller's service spec
Allows users of this chart to enable dual stack or use IPv6 for the Kubernetes Service.
None
I'm not sure about my documentation, please help me out here since it's the first time contributing to this project
=> [bitnami/nginx-ingress-controller] Add Service spec: ipFamilyPolicy and ipFamilies

bitnami/appsmith/Chart.yaml
Adds missing Chart version bump in https://github.com/bitnami/charts/pull/19476
The chart is published
None
- NA
NA
=> [bitnami/appsmith] Bump Chart.yaml version

bitnami/metallb/Chart.lock, bitnami/metallb/Chart.yaml, bitnami/metallb/templates/controller/psp.yaml, bitnami/metallb/templates/controller/rbac.yaml, bitnami/metallb/templates/speaker/psp.yaml, bitnami/metallb/templates/speaker/rbac.yaml
=> [bitnami/metallb] Use common capabilities for PSP

bitnami/influxdb/Chart.lock, bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/psp-role.yaml, bitnami/influxdb/templates/psp-rolebinding.yaml, bitnami/influxdb/templates/psp.yaml
=> [bitnami/influxdb] Use common capabilities for PSP

bitnami/redis-cluster/Chart.lock, bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/psp.yaml, bitnami/redis-cluster/templates/redis-role.yaml
=> [bitnami/redis-cluster] Use common capabilities for PSP

bitnami/thanos/Chart.lock, bitnami/thanos/Chart.yaml, bitnami/thanos/templates/query-frontend/psp-clusterrole.yaml, bitnami/thanos/templates/query-frontend/psp-clusterrolebinding.yaml, bitnami/thanos/templates/query-frontend/psp.yaml, bitnami/thanos/templates/query/psp-clusterrole.yaml, bitnami/thanos/templates/query/psp-clusterrolebinding.yaml, bitnami/thanos/templates/query/psp.yaml
=> [bitnami/thanos] Use common capabilities for PSP

bitnami/opensearch/Chart.yaml, bitnami/opensearch/templates/coordinating/statefulset.yaml, bitnami/opensearch/templates/data/statefulset.yaml, bitnami/opensearch/templates/ingest/statefulset.yaml, bitnami/opensearch/templates/master/statefulset.yaml
Modify opensearch liveness probe to not rely on `/cluster/health` API call.
This change aims to improve chart stability by avoiding restarts if API endpoint is not reachable, and instead uses the rest-api port listening.
This change should help avoid restarts during the cluster bootstrap stage and reduce the number of accidental restarts due to other causes.
Change in the default livenessProbe behavior.
=> [bitnami/opensearch] Modify liveness probes

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/coordinating/statefulset.yaml, bitnami/elasticsearch/templates/data/statefulset.yaml, bitnami/elasticsearch/templates/ingest/statefulset.yaml, bitnami/elasticsearch/templates/master/statefulset.yaml
Modify elasticsearch liveness probe to not rely on `/cluster/health` API call.
This change aims to improve chart stability by avoiding restarts if API endpoint is not reachable, and instead uses the rest-api port listening.
This change should help avoid restarts during the cluster bootstrap stage and reduce the number of accidental restarts due to other causes.
Change in the default livenessProbe behavior.
=> [bitnami/elasticsearch] Modify liveness probes

bitnami/flink/Chart.yaml, bitnami/flink/templates/_helpers.tpl, bitnami/flink/templates/jobmanager/deployment.yaml, bitnami/flink/templates/taskmanager/deployment.yaml
As reported in #19302, the chart was unable to pull images from private registries and/or use extra volumes. This PR addresses theses issues.
Both image pull secrets and extra volume features can be used, as originally intended.
None
- fixes #19302
None
=> [bitnami/flink] Fix pullSecrets and extraVolumeMounts

bitnami/pinniped/Chart.yaml, bitnami/pinniped/values.yaml
Adds pullSecrets for kubeCertAgent image.
Upstream ref: https://github.com/vmware-tanzu/pinniped/blob/78cb86215b83994a0950d57dd9ed08d06234009d/deploy/concierge/deployment.yaml#L93C24-L95
Tested locally:
```
$ helm install test bitnami/pinniped -f .vib/pinniped/runtime-parameters.yaml --dry-run --set "global.imagePullSecrets[0]=testing"
...
data:
pinniped.yaml: |-
discovery:
url: null
api:
servingCertificate:
durationSeconds: 2592000
renewBeforeSeconds: 2160000
apiGroupSuffix: pinniped.dev
aggregatedAPIServerPort: 10250
impersonationProxyServerPort: 8444
names:
servingCertificateSecret: test-pinniped-concierge-default-api-tls-serving-certificate
credentialIssuer: test-pinniped-concierge
apiService: test-pinniped-concierge-default-api
impersonationLoadBalancerService: …
```
=> [bitnami/pinniped] Add kubeCertAgent imagePullSecrets

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/README.md, bitnami/rabbitmq/templates/statefulset.yaml, bitnami/rabbitmq/values.yaml
This pull request adds support for `enableServiceLinks` parameter on Rabbitmq Helm chart.
- Reduce startup time for pods that run in a shared namespace with many services.
- None. Param has default value of `true`, which is standard k8s behaviour.
=> bitnami/rabbitmq Add support for enableServiceLinks on rabbitmq chart

bitnami/pinniped/Chart.yaml, bitnami/pinniped/templates/_helpers.tpl, bitnami/pinniped/values.yaml
Fixes an issue introduced at https://github.com/bitnami/charts/pull/19688
The pinniped.yaml config format does not match the Kubernetes spec format:
Wrong, using K8s format:
```
kubeCertAgent:
namePrefix: test-pinniped-concierge-kube-cert-agent-
image: docker.io/bitnami/pinniped:0.26.0-debian-11-r0  
imagePullSecrets:
- name: testing
```
Correct:
```
kubeCertAgent:
namePrefix: test-pinniped-concierge-kube-cert-agent-
image: docker.io/bitnami/pinniped:0.26.0-debian-11-r0  
imagePullSecrets:
- testing
```
=> [bitnami/pinniped] Fix issue with kubeCertAgent pullSecrets

bitnami/common/Chart.yaml, bitnami/common/templates/_labels.tpl
pass correct context (`.context` instead of `.`) inside common.labels.standard.
- fixes #
=> [bitnami/common] render labels correctly when they contain templates

bitnami/pinniped/Chart.yaml
=> [bitnami/pinniped] Bump chart version (missing in #19733)

bitnami/appsmith/Chart.yaml, bitnami/appsmith/README.md, bitnami/appsmith/templates/_helpers.tpl, bitnami/appsmith/templates/backend/deployment.yaml, bitnami/appsmith/values.yaml
Currently on an install with default values, when storage persistence is set for the backend deployment apps try to save the local git repo under /data which does not exist.  This change will add functionality to set the APPSMITH_GIT_ROOT environment variable for the backend deployment in a way that does not disrupt current deployments.  This environment variable sets the destination of the local git repository data when the app is connected to a git repository.
This makes it a bit more obvious that this "gotcha" exists and offers a way to get this set "automagically" without disrupting current installs.
Since the default value for this is empty, folks will probably not set this until they run into the snag in their current deployment.  I just can't think of a good way to easily do this …
=> [bitnami/appsmith] Create options for local git repo data on persistent storage

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/README.md, bitnami/redis-cluster/templates/svc-cluster-external-access.yaml, bitnami/redis-cluster/values.yaml
With theses changes, the user can optionally disable the Service.spec.loadBalancerIP for external access. Alternatively, the user can specify an annotation name with `cluster.externalAccess.service.loadBalancerIPAnnotation` to use service annotations for fixed IPs.
This MR only ist for external access service. The same should be done for metrics-svc and redis-svc. I will file separate issues for that
Provide migration path for the deprecation of `Service.spec.loadBalancerIP`
- fixes #19535
=> [bitnami/redis-cluster] feat: optionally disable Service.spec.loadBalancerIP for external access

.github/workflows/ci-pipeline.yml, .github/workflows/retry-failed-releases.yml
Right now, our triage for failed PRs include retrying the `VIB Verify` workflow a couple of times to avoid any transient errors. This is a time-consuming manual process that should be automated.
Improved triage workflow
None
- fixes #
=> [bitnami/*] Add CI retriability for release PRs

.vib/kibana/cypress/cypress.json
Increasing timeout for Kibana Cypress test as it is currently failing on GKE.
=> [bitnami/kibana] Increase Kibana Cypress test timeout

.vib/keycloak/cypress/cypress.json
Increasing timeout for Keycloak Cypress test as it is currently failing on GKE.
=> [bitnami/keycloak] Increase Keycloak Cypress test timeout

bitnami/keycloak/README.md, bitnami/keycloak/values.yaml
Remove reference to a non-existing param in README (it should be `keycloakConfigCli.configuration` instead of `keycloakConfigCli.config`).
It has been removed instead of updated because the same information is explicitly mention in the following paragraph.
README shows correct information
None
- fixes #19819
None
=> [bitnami/keycloak] Remove reference to missing param in README

bitnami/matomo/Chart.yaml, bitnami/matomo/README.md, bitnami/matomo/templates/cronjob.yaml, bitnami/matomo/values.yaml
Fix the wrong indention of the `extraVolumes` inside the new cronjob. It's a regression of
- #18754
I've also fixed the heading for the cronjob parameters to not be included inside the network policy parameter table
Chart now works with extra volumes
none
none
=> [bitnami/matomo] fix wrong indent of extra volumes inside cronjobs

bitnami/airflow/Chart.yaml, bitnami/airflow/README.md, bitnami/airflow/values.yaml
Bumps airflow-worker image revision to an updated versions that now includes `git` by default.
DAGs expecting a git repo to be cloned can clone the repo successfully.
Not expected.
- fixes #13984
=> [bitnami/airflow] Update airflow-worker image including git

.vib/clickhouse/goss/goss.yaml, .vib/concourse/goss/worker/goss.yaml, .vib/mariadb/goss/goss.yaml, .vib/mysql/goss/goss.yaml, .vib/postgresql/goss/goss.yaml
In this new version, the output is expected as a string instead of as an integer
Without quotes:
```console
$ goss --gossfile .vib/clickhouse/goss/goss.yaml --vars .vib/clickhouse/runtime-parameters.yaml render
...
check-cluster-status:
stdout:
- 4
create-database-in-cluster:
stdout:
- 23
```
Quoting the value:
```console
$ goss --gossfile .vib/clickhouse/goss/goss.yaml --vars .vib/clickhouse/runtime-parameters.yaml render
...
check-cluster-status:
stdout:
- "4"
create-database-in-cluster:
stdout:
- "23"
```
=> Adapt some tests to Goss 4

.vib/clickhouse/goss/goss.yaml, .vib/consul/goss/goss.yaml, .vib/discourse/goss/goss.yaml, .vib/etcd/goss/goss.yaml, .vib/influxdb/goss/goss.yaml, .vib/jupyterhub/goss/goss.yaml, .vib/kafka/goss/goss.yaml, .vib/logstash/goss/goss.yaml, .vib/mariadb-galera/goss/goss.yaml, .vib/memcached/goss/goss.yaml, .vib/mongodb-sharded/goss/goss.yaml, .vib/mongodb/goss/goss.yaml, .vib/nginx-ingress-controller/goss/goss.yaml, .vib/odoo/goss/goss.yaml, .vib/postgresql-ha/goss/repmgr/goss.yaml, .vib/prometheus/goss/goss.yaml, .vib/rabbitmq/goss/goss.yaml, .vib/redis/goss/goss.yaml, .vib/solr/goss/goss.yaml, .vib/spring-cloud-dataflow/goss/goss.yaml, .vib/wordpress/goss/goss.yaml, .vib/zookeeper/goss/goss.yaml
This is a follow-up of https://github.com/bitnami/charts/pull/20305. Since any integer in `contents:` and `stdout:` is expected to be treated as a string, we opted for quoting any variable or hardcoded value except regexps so we don't need to care about the type.
=> Quote everything inside stdout/contents except regexp

bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/README.md, bitnami/rabbitmq-cluster-operator/templates/cluster-operator/metrics-service.yaml, bitnami/rabbitmq-cluster-operator/templates/cluster-operator/podmonitor.yaml, bitnami/rabbitmq-cluster-operator/templates/cluster-operator/servicemonitor.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/metrics-service.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/podmonitor.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/servicemonitor.yaml, bitnami/rabbitmq-cluster-operator/values.yaml
Adding PodMonitor support for rabbitmq-cluster-operator
**Benefits**
Removing the need for ClusterIP service that solely exist for gathering metrics
=> [bitnami/rabbitmq-cluster-operator] - Add support for PodMonitor

.vib/common-tests/ginkgo-utils/k8s.go
Currently, the scale function was incorrectly not running the update command because it was checking the Status.Replicas field. However, this was not enough because sometimes the Status field was not properly updated when scaling down. We now check that both Replicas and AvailableReplicas are set to `count` in order to ignore the update function.
- fixes #
=> [bitnami/*] test: :white_check_mark: Fix race condition in ginkgo utils

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/templates/grafana.yaml
Fixes a mistake in the grafana CR which broke serviceAccount configuration.
Makes additional `grafana.serviceAccount` configuration work as expected again.
=> [bitnami/grafana-operator]: fix grafana.serviceAccount

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/query/pdb.yaml
In 065a7279 we added new labels but did not remove the old ones. This means if you have labels and the pod disruption budget you can't deploy.
Removes the duplicate labels on the pdb
We can helm install again
=> [bitnami/thanos] Fix dup common labels in the query pdb
