bitnami/charts

bitnami/schema-registry/Chart.lock
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/templates/_helpers.tpl
bitnami/schema-registry/templates/external-kafka-secrets.yaml
bitnami/schema-registry/templates/statefulset.yaml
bitnami/schema-registry/values.yaml

Updates Kafka subchart after its new major #17507

[bitnami/schema-registry] Update Kafka subchart 24.0.0

---

.vib/pytorch/goss/goss.yaml
.vib/pytorch/goss/testfiles/README.md
.vib/pytorch/goss/testfiles/polynomial_tensor.py
.vib/pytorch/runtime-parameters.yaml
bitnami/pytorch/Chart.yaml

Some tests do not work in air-gapped environments. We will store the polynomial_tensor.py file in our repo to run it when needed.
We are modifying the tests to make them work in all environments. This way we can verify that the solution works as expected. If the solution doesn't work in that environment, tests will not be changed and support for that env will be removed.

[bitnami/pytorch] Adapt Pytorch tests to Air-gapped environments 

---

bitnami/common/Chart.yaml
bitnami/common/templates/_labels.tpl

Adds the recommended label app.kubernetes.io/version to the Common chart
app.kubernetes.io/version is a recommended label and allows you to query objects in k8s based on the app version. Also good for telemetry data also.
I suppose if people wish to hid the app version currently deployed this will not allow for that but I suppose a bigger PR could be made to allow this to be turned on and off.
- fixes NONE

[bitnami/common] Add app.kubernetes.io/version based on AppVersion

---

bitnami/common/Chart.yaml
bitnami/common/templates/_labels.tpl

Delete app Kubernetes version field
Reverts https://github.com/bitnami/charts/pull/18194

[bitnami/common] Delete app kubernetes version field

---

bitnami/kafka/Chart.yaml
bitnami/kafka/templates/provisioning/job.yaml

Fix issues enabling provisioning and topics.
Provisioning job is created. 
N/A
- fixes #18191

[bitnami/kafka] Fix Kafka provisoning

---

.github/workflows/license-headers.yml

This PR excludes the license check for files that contain `/crds/` in their path. It was designed so it is extensible to other path patters.
- fixes #

[bitnami/*] chore: :construction_worker: Exclude license check in CRDs

---

.licenserc.yaml

[bitnami/*] chore: :construction_worker: Disable CRD check in license linter

---

bitnami/contour/Chart.yaml
bitnami/contour/README.md
bitnami/contour/templates/envoy/service.yaml
bitnami/contour/values.yaml

my task is to create a service with the load balancer type ipv6 only, for this you need to specify ipFamilies
IPv6 only service in dualstak custer
- fixes #

[bitnami/contour] add ipFamilies to contour envoy service.yaml

---

bitnami/flux/Chart.yaml
bitnami/flux/crds/helm-controller/helm.toolkit.fluxcd.io_helmreleases.yaml
bitnami/flux/crds/image-automation-controller/image.toolkit.fluxcd.io_imageupdateautomations.yaml
bitnami/flux/crds/image-reflector-controller/image.toolkit.fluxcd.io_imagepolicies.yaml
bitnami/flux/crds/image-reflector-controller/image.toolkit.fluxcd.io_imagerepositories.yaml
bitnami/flux/crds/kustomize-controller/kustomize.toolkit.fluxcd.io_kustomizations.yaml
bitnami/flux/crds/notification-controller/notification.toolkit.fluxcd.io_alerts.yaml
bitnami/flux/crds/notification-controller/notification.toolkit.fluxcd.io_providers.yaml
bitnami/flux/crds/notification-controller/notification.toolkit.fluxcd.io_receivers.yaml
bitnami/flux/crds/source-controller/source.toolkit.fluxcd.io_buckets.yaml
bitnami/flux/crds/source-controller/source.toolkit.fluxcd.io_gitrepositories.yaml
bitnami/flux/crds/source-controller/source.toolkit.fluxcd.io_helmcharts.yaml
bitnami/flux/crds/source-controller/source.toolkit.fluxcd.io_helmrepositories.yaml
bitnami/flux/crds/source-controller/source.toolkit.fluxcd.io_ocirepositories.yaml

[bitnami/flux] chore: :page_facing_up: Remove license from CRDs

---

bitnami/apisix/Chart.yaml
bitnami/apisix/crds/ApisixGlobalRule.yaml
bitnami/apisix/crds/customresourcedefinitions.yaml

[bitnami/apisix] chore: :page_facing_up: Remove license from CRDs

---

bitnami/multus-cni/Chart.yaml
bitnami/multus-cni/crds/network-attachment-definitions.yaml

[bitnami/multus-cni] chore: :page_facing_up: Remove license from CRDs

---

bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/crds/crd-rabbitmq-cluster.yaml
bitnami/rabbitmq-cluster-operator/crds/crds-messaging-topology-operator.yaml

[bitnami/rabbitmq-cluster-operator] chore: :page_facing_up: Remove license from CRDs

---

bitnami/pinniped/Chart.yaml
bitnami/pinniped/crds/concierge-crds.yaml
bitnami/pinniped/crds/supervisor.crds.yaml

[bitnami/pinniped] chore: :page_facing_up: Remove license from CRDs

---

bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/templates/crds/crd-certificaterequests.yaml
bitnami/cert-manager/templates/crds/crd-certificates.yaml
bitnami/cert-manager/templates/crds/crd-challenges.yaml
bitnami/cert-manager/templates/crds/crd-clusterissuers.yaml
bitnami/cert-manager/templates/crds/crd-issuers.yaml
bitnami/cert-manager/templates/crds/crd-orders.yaml

[bitnami/cert-manager] chore: :page_facing_up: Remove license from CRDs

---

bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/crds/argoproj.io_clusterworkflowtemplates.yaml
bitnami/argo-workflows/crds/argoproj.io_cronworkflows.yaml
bitnami/argo-workflows/crds/argoproj.io_eventbus.yaml
bitnami/argo-workflows/crds/argoproj.io_eventsources.yaml
bitnami/argo-workflows/crds/argoproj.io_sensors.yaml
bitnami/argo-workflows/crds/argoproj.io_workflowartifactgctasks.yaml
bitnami/argo-workflows/crds/argoproj.io_workfloweventbindings.yaml
bitnami/argo-workflows/crds/argoproj.io_workflows.yaml
bitnami/argo-workflows/crds/argoproj.io_workflowtaskresults.yaml
bitnami/argo-workflows/crds/argoproj.io_workflowtasksets.yaml
bitnami/argo-workflows/crds/argoproj.io_workflowtemplates.yaml

[bitnami/argo-workflows] chore: :page_facing_up: Remove license from CRDs

---

bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/crds/grafanadashboards.integreatly.org.yaml
bitnami/grafana-operator/crds/grafanadatasources.integreatly.org.yaml
bitnami/grafana-operator/crds/grafanafolders.integreatly.org.yaml
bitnami/grafana-operator/crds/grafanas.integreatly.org.yaml

[bitnami/grafana-operator] chore: :page_facing_up: Remove license from CRDs

---

bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/crds/crd.yaml

[bitnami/external-dns] chore: :page_facing_up: Remove license in CRDs

---

bitnami/contour/Chart.yaml
bitnami/contour/templates/crds/contourconfiguration.yaml
bitnami/contour/templates/crds/contourdeployments.yaml
bitnami/contour/templates/crds/extensionservices.yaml
bitnami/contour/templates/crds/httpproxies.yaml
bitnami/contour/templates/crds/tlscertificatedeligations.yaml

[bitnami/contour] chore: :page_facing_up: Remove license in CRDs

---

bitnami/metallb/Chart.yaml
bitnami/metallb/templates/crds/crds.yaml

[bitnami/metallb] chore: :page_facing_up: Remove license in CRDs

---

bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/hack/update_crds.sh

[bitnami/kube-prometheus] chore: :wrench: Update hack script to remove copyright addition

---

bitnami/matomo/Chart.yaml
bitnami/matomo/templates/externaldb-secrets.yaml

Fixes #18027.
See #18027.
None.
- fixes #18027

[bitnami/matomo] Do not create Secret when an external DB Secret is provided (#18027)

---

bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/templates/_helpers.tpl
bitnami/deepspeed/templates/client/client-dep-job.yaml
bitnami/deepspeed/templates/worker/worker-statefulset.yaml

This broadens the compatibility of the chart with flavors with other ssh versions (which do not have the `/etc/ssh/sshd_config.d` or `/etc/ssh/ssh_config.d` folders).
- fixes #

[bitnami/deepspeed] feat: :sparkles: Allow older versions of ssh

---

.vib/deepspeed/runtime-parameters.yaml
bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/README.md
bitnami/deepspeed/templates/_helpers.tpl
bitnami/deepspeed/templates/client/client-dep-job.yaml
bitnami/deepspeed/templates/worker/worker-statefulset.yaml
bitnami/deepspeed/values.yaml

[bitnami/deepspeed] fix: :bug: Add context to init container

---

bitnami/contour/Chart.yaml
bitnami/contour/templates/envoy/daemonset.yaml
bitnami/contour/templates/envoy/deployment.yaml

Use envoy resources for the envoy initContainers
- fixes #18365

[bitnami/contour] Use envoy resources for envoy daemonset and deployment initContainers

---

bitnami/mysql/Chart.yaml
bitnami/mysql/README.md
bitnami/mysql/templates/_helpers.tpl
bitnami/mysql/templates/primary/startdb-configmap.yaml
bitnami/mysql/templates/primary/statefulset.yaml
bitnami/mysql/templates/secondary/statefulset.yaml
bitnami/mysql/values.yaml

Added capability of specifying startdb scripts using helm values.
This change allows users to specify startdb scripts which would run every time the container starts. A possible usecase could be that the users can run specific checks on every container restarts and perform some actions accordingly.
Users needs to be carefully specify these scripts since they would run on every container restart.
- fixes #17718

[bitnami/mysql] Update to mysql chart to have startdb script

---

bitnami/contour/Chart.yaml
bitnami/contour/README.md
bitnami/contour/templates/envoy/hpa.yaml
bitnami/contour/values.yaml

Possibity to control scaleUp andscaleDown of Contour Envoy proxy.

[bitnami/contour] Added suport for behavior on Envoy HPA

---

bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/templates/client/client-dep-job.yaml
bitnami/deepspeed/templates/worker/worker-statefulset.yaml

This PR sets the HOME environment variable to `/home/deepspeed` so users can launch commands without relying on the nss_wrapper entrypoint. 
- fixes #

[bitnami/deepspeed] fix: :bug: Set HOME to /home/deepspeed

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/backup/cronjob.yaml

Correctly check for the annotations to be used
Correct use of annotations on Jobs
- fixes #
Noted in https://github.com/bitnami/charts/pull/17852#discussion_r1297325693

[bitnami/postgresql] fix annotation typo

---

.vib/aspnet-core/goss/goss.yaml

Some of the current GOSS tests related to permissions are dependant to the K8s cluster used to test the chart. This PR adapt those tests to work on OpenShift.  
Tests now work on OpenShift
None
N/A

[bitnami/aspnet-core] Adapt GOSS test to support OpenShift testing

---

.vib/haproxy/runtime-parameters.yaml
bitnami/haproxy/Chart.yaml

We are using a `NGINX@1.22` container as a sidecar, which doesn't have an ARM version. This is making or internal tests in ARM fail. Updated sidecar to the latest version.
Testing deployment works in ARM k8s clusters.
None
N/A

[bitnami/haproxy] Update runtime-parameters for ARM support

---

bitnami/redis/README.md

Update upgrading notes.
Explain the changes for the new major of Redis, and notify about an issue in the release process for the previous one.
N/A
N/A
N/A

[bitnami/redis] Update upgrading notes for version 18.x.x

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/pvc.yaml

obey what is documented in values.yaml and README.md related to persistence.selector for pvc
- fixes #18795

[bitnami/wordpress] add missing persistence.selector values if defined

---

bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md

Update Redis' subchart, and notify about an issue in the release process with the previous version of this subchart.
N/A
N/A
N/A

[bitnami/mastodon] Update Redis' subchart

---

bitnami/harbor/Chart.lock
bitnami/harbor/Chart.yaml
bitnami/harbor/README.md

[bitnami/harbor] Update Redis' subchart

---

bitnami/airflow/Chart.lock
bitnami/airflow/Chart.yaml
bitnami/airflow/README.md

[bitnami/airflow] Update Redis' subchart

---

bitnami/appsmith/Chart.lock
bitnami/appsmith/Chart.yaml
bitnami/appsmith/README.md

[bitnami/appsmith] Update Redis' subchart

---

bitnami/oauth2-proxy/Chart.lock
bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md

[bitnami/oauth2-proxy] Update Redis' subchart

---

bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml
bitnami/discourse/README.md

[bitnami/discourse] Update Redis' subchart

---

bitnami/argo-cd/Chart.lock
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/README.md

[bitnami/argo-cd] Update Redis' subchart

---

bitnami/kafka/README.md

Fix the order from the upgrading section

[bitnami/kafka] Fix typo

---

bitnami/argo-cd/README.md

Users to understand the right way to install a Config Management Plugin using Bitnami ArgoCD chart.
None
N/A
N/A

[bitnami/argo-cd] Document how to install a Config Management Plugin

---

bitnami/contour/Chart.yaml
bitnami/contour/README.md
bitnami/contour/templates/envoy/daemonset.yaml
bitnami/contour/templates/envoy/deployment.yaml
bitnami/contour/values.yaml

Renames `envoy.containerSecurityContextEnvoyInit` as `envoy.initConfig.containerSecurityContext` to be aligned with the rest of the catalog.

[bitnami/contour] Rename envoy.containerSecurityContextEnvoyInit as envoy.initConfig.containerSecurityContext

---

bitnami/redis-cluster/README.md

Update upgrading notes.
Explain the changes for the new major of Redis, and notify about an issue in the release process for the previous one.
N/A
N/A
N/A

[bitnami/redis-cluster] Update upgrading notes

---

bitnami/common/Chart.yaml
bitnami/common/templates/_tplvalues.tpl
template/CHART_NAME/templates/daemonset.yaml
template/CHART_NAME/templates/deployment.yaml
template/CHART_NAME/templates/ingress.yaml
template/CHART_NAME/templates/pdb.yaml
template/CHART_NAME/templates/pvc.yaml
template/CHART_NAME/templates/service-account.yaml
template/CHART_NAME/templates/service.yaml
template/CHART_NAME/templates/servicemonitor.yaml
template/CHART_NAME/templates/statefulset.yaml

new macro to merge a list of values with rendering 
support for fixing #18888
after this is integrated, all charts will be fixed by applying diffs like this one for labels  :
```diff
-{{- $podLabels := merge .Values.master.podLabels .Values.commonLabels }} 
+{{- $podLabels := include "common.tplvalues.merge" (dict "values" .Values.master.podLabels .Values.commonLabels "context" .) | fromYaml }} 
selector:
matchLabels: {{- include "common.labels.matchLabels" ( dict "customLabels" $podLabels "context" $ ) | nindent 6 }}
```
and annotations
```diff
-  {{- $annotations := merge .Values.master.service.annotations .Values.commonAnnotations }}
+  {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.master.service.annotations .Values.commonAnnotations ) "context" . …
```

[bitnami/common] new macro to merge a list of values with rendering 

---

.vib/fluentd/goss/goss.yaml

Increase the timeout for the fluentd forward-aggregator test

[bitnami/fluentd] Fix fluentd timeout for the forward-aggregator test

---

.vib/postgresql-ha/ginkgo/postgresql_suite_test.go
.vib/postgresql/ginkgo/postgresql_suite_test.go

[bitnami/postgresql,postgresql-ha] test: :wrench: Bump ginkgo timeouts

---

.vib/fluentd/goss/goss.yaml

Improve reliability for the fluentd verification test

[bitnami/fluentd] Improve reliability test for fluentd forward-aggregator test

---

bitnami/clickhouse/Chart.lock
bitnami/clickhouse/Chart.yaml

This PR updates the dependencies of the chart.

[bitnami/clickhouse] Update dependencies

---

.vib/mongodb-sharded/vib-action.config
bitnami/mongodb-sharded/Chart.yaml

In order to ensure more test stability, this PR changes the verification to serial as the number of deployments is high.
- fixes #

[bitnami/mongodb-sharded] test: :construction_worker: Set serial verification

---

template/CHART_NAME/templates/daemonset.yaml
template/CHART_NAME/templates/deployment.yaml
template/CHART_NAME/templates/ingress.yaml
template/CHART_NAME/templates/pdb.yaml
template/CHART_NAME/templates/pvc.yaml
template/CHART_NAME/templates/service-account.yaml
template/CHART_NAME/templates/service.yaml
template/CHART_NAME/templates/servicemonitor.yaml
template/CHART_NAME/templates/statefulset.yaml

fix a typo in templates/CHART_NAME
- fixes #
- [] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title

[template] typofix

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/secrets.yaml

Fix the usage of global secret keys for the passwords
- fixes #19202

[bitnami/postgresql] Fix global secretkeys usage

---

bitnami/matomo/Chart.yaml
bitnami/matomo/templates/deployment.yaml

Currently it's removing the required newline, so this will fix the rendering:
```yaml
- name: MATOMO_WEBSITE_NAME
value: "example"
- name: MATOMO_WEBSITE_HOST
value: "https://example.org"- name: MATOMO_SMTP_AUTH
value: "Login"
- name: MATOMO_SMTP_HOST
value: "smtp.example.org"
```
After this change it does render correctly:
```yaml
- name: MATOMO_WEBSITE_NAME
value: "example"
- name: MATOMO_WEBSITE_HOST
value: "https://example.org"
- name: MATOMO_SMTP_AUTH
value: "Login"
- name: MATOMO_SMTP_HOST
value: "smtp.example.org"
```
We can set `smtpAuth`.
none
none

[bitnami/matomo] wrong smtpAuth rendering

---

bitnami/apisix/README.md
bitnami/appsmith/README.md
bitnami/argo-cd/README.md
bitnami/aspnet-core/README.md
bitnami/clickhouse/README.md
bitnami/concourse/README.md
bitnami/consul/README.md
bitnami/discourse/README.md
bitnami/flux/README.md
bitnami/gitea/README.md
bitnami/jupyterhub/README.md
bitnami/kubeapps/README.md
bitnami/magento/README.md
bitnami/mastodon/README.md
bitnami/matomo/README.md
bitnami/milvus/README.md
bitnami/multus-cni/README.md
bitnami/oauth2-proxy/README.md
bitnami/osclass/README.md
bitnami/phpmyadmin/README.md
bitnami/pinniped/README.md
bitnami/schema-registry/README.md
bitnami/spring-cloud-dataflow/README.md
bitnami/supabase/README.md
bitnami/vault/README.md
bitnami/whereabouts/README.md
bitnami/wordpress/README.md

This PR is performing two changes across all the charts: 1) renaming from Kubeapps.com to Kubeapps.dev; 2) using the same wording in the ingress section.
Up-to-date and more uniform docs.
N/A
N/A
N/A

[bitnami/*] Update readme files

---

bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/templates/rbac-clustescope.yaml

Fix error if specify route.spec.host
```
2023-09-13T13:01:09Z	ERROR	GrafanaReconciler	reconciler error in stage	{"controller": "grafana", "controllerGroup": "grafana.integreatly.org", "controllerKind": "Grafana", "Grafana": {"name":"grafana-openshift","namespace":"test"}, "namespace": "test", "name": "grafana-openshift", "reconcileID": "aa772ba9-dbe2-4fa1-8be4-53ba727b34fe", "stage": "ingress", "error": "Route.route.openshift.io \"grafana-openshift-route\" is invalid: spec.host: Forbidden: you do not have permission to set the host field of the route"}
```
- fixes #

[bitnami/grafana-operator] Update rbac-clustescope.yaml

---

bitnami/parse/Chart.lock
bitnami/parse/Chart.yaml
bitnami/parse/README.md

Update the MongoDB subchart to the latest major.
Use the latest MongoDB.
N/A
- fixes #

[bitnami/parse] Update MongoDB subchart

---

bitnami/clickhouse/Chart.yaml
bitnami/clickhouse/templates/statefulset.yaml

Syntax error (too many "}") in statefulset.yaml.
Resolve issue #19496

[bitnami/clickhouse] Remove syntax error in statefulset.yaml. Resolve #19496

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/postinit-configmap.yaml

Without the start / for the chmod command the path would be relative to the current directory where this is executed.
By adding a / at the begging of the line we remove any path ambiguity, similar to line 24 in the same script.
By adding a / at the begging of the line we remove any path ambiguity, similar to line 24 in the same script.
None
- fixes NA

[bitnami/wordpress] Fixing proper path for permission revocation

---

bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/crds/crd-alertmanagerconfigs.yaml
bitnami/kube-prometheus/crds/crd-alertmanagers.yaml
bitnami/kube-prometheus/crds/crd-podmonitors.yaml
bitnami/kube-prometheus/crds/crd-probes.yaml
bitnami/kube-prometheus/crds/crd-prometheusagents.yaml
bitnami/kube-prometheus/crds/crd-prometheuses.yaml
bitnami/kube-prometheus/crds/crd-prometheusrules.yaml
bitnami/kube-prometheus/crds/crd-scrapeconfigs.yaml
bitnami/kube-prometheus/crds/crd-servicemonitors.yaml
bitnami/kube-prometheus/crds/crd-thanosrulers.yaml

Update the CRDs used by kube-prometheus to be in sync with the operator version. I suppose that they were not updated with the last operator update.
CRDs and operator versions are in sync.
None.
No issues opened afaik.

[bitnami/kube-prometheus] Update CRDs to be in sync with the operator version

---

bitnami/common/Chart.yaml
bitnami/common/templates/_labels.tpl

don't set app.kubernetes.io/version if appVersion is unset in Chart.yaml
appVersion is an optional field in Chart.yaml, so instead of setting the app.kubernetes.io/version to empty string, don't set the label at all.
- fixes #17201

[bitnami/common] allow for empty appVersion

---

bitnami/postgresql/README.md

Simply updating the README after the release
- fixes #

[bitnami/postgresql] Update README after major release

---

bitnami/supabase/Chart.lock
bitnami/supabase/Chart.yaml
bitnami/supabase/README.md

This PR updates the Chart's dependencies

[bitnami/supabase] Update dependencies

---

bitnami/gitea/Chart.lock
bitnami/gitea/Chart.yaml
bitnami/gitea/README.md

This PR updates the Chart's dependencies

[bitnami/gitea] Update dependencies

---

bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md

This PR updates the Chart's dependencies

[bitnami/mastodon] Update dependencies

---

.vib/matomo/runtime-parameters.yaml
bitnami/matomo/Chart.yaml

Disable cronjobs for testing.
Avoid timeouts during deployment. It seems CP is waiting for the scheduled job execution.
Pipeline triggered with these changes: https://github.com/bitnami/charts/actions/runs/6392946368/job/17351232133?pr=19692

[bitnami/matomo] Disable cronjobs for testing

---

bitnami/apache/Chart.lock
bitnami/apache/Chart.yaml

[bitnami/apache] update bitnami/common

---

bitnami/consul/Chart.lock
bitnami/consul/Chart.yaml

[bitnami/consul] update bitnami/common

---

bitnami/aspnet-core/Chart.lock
bitnami/aspnet-core/Chart.yaml

[bitnami/aspnet-core] update bitnami/common

---

bitnami/cert-manager/Chart.lock
bitnami/cert-manager/Chart.yaml

[bitnami/cert-manager] update bitnami/common

---

bitnami/contour/Chart.lock
bitnami/contour/Chart.yaml

[bitnami/contour] update bitnami/common

---

bitnami/deepspeed/Chart.lock
bitnami/deepspeed/Chart.yaml

[bitnami/deepspeed] update bitnami/common

---

bitnami/etcd/Chart.lock
bitnami/etcd/Chart.yaml

[bitnami/etcd] update bitnami/common

---

bitnami/cassandra/Chart.lock
bitnami/cassandra/Chart.yaml

[bitnami/cassandra] update bitnami/common

---

TESTING.md

Update TESTING.md to align with the recent changes in the verification strategy.
Documentation is up-to-date.
None
- Related to #19845
NA

[bitnami/*] Update TESTING.md with new approach

---

.vib/concourse/goss/web/goss.yaml

Skip test if platform is in an air-gapped environment
We can verify other functionalities of the application when skipping the failing tests
None
We dropped support to some solutions in air-gapped environment due to specific issues of the environment. We want to update the tests to be able to verify the solutions there as well

[bitnami/concourse] Skip test if platform is air-gapped

---

.vib/flux/goss/goss-wait.yaml
.vib/flux/goss/goss.yaml
.vib/flux/runtime-parameters.yaml

Skip test if platform is in an air-gapped environment
We can verify other functionalities of the application when skipping the failing tests
None
We dropped support to some solutions in air-gapped environment due to specific issues of the environment. We want to update the tests to be able to verify the solutions there as well

[bitnami/flux] Skip tests if platform is air-gapped

---

bitnami/phpbb/Chart.lock
bitnami/phpbb/Chart.yaml

[bitnami/phpbb] Update MariaDB to 14.x.x

---

bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md

[bitnami/spring-cloud-dataflow] Update MariaDB to 14.x.x

---

bitnami/phpbb/Chart.yaml
bitnami/phpbb/README.md

Update the major and readme.md

[bitnami/phpbb] Update major

---

bitnami/mediawiki/Chart.lock
bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/README.md

[bitnami/mediawiki] Update MariaDB to 14.x.x

---

bitnami/osclass/Chart.lock
bitnami/osclass/Chart.yaml
bitnami/osclass/README.md

[bitnami/osclass] Update MariaDB to 14.x.x

---

bitnami/supabase/Chart.lock
bitnami/supabase/Chart.yaml
bitnami/supabase/README.md

This PR updates the Chart's dependencies (Kong)
- fixes #

[bitnami/supabase] Update Kong subchart

---

bitnami/prestashop/Chart.lock
bitnami/prestashop/Chart.yaml
bitnami/prestashop/README.md

[bitnami/prestashop] Update MariaDB to 14.x.x

---

bitnami/suitecrm/Chart.lock
bitnami/suitecrm/Chart.yaml
bitnami/suitecrm/README.md

[bitnami/suitcrm] Update MariaDB to 14.x.x

---

bitnami/ejbca/Chart.lock
bitnami/ejbca/Chart.yaml
bitnami/ejbca/README.md

[bitnami/ejbca] Update MariaDB to 14.x.x

---

bitnami/magento/Chart.lock
bitnami/magento/Chart.yaml
bitnami/magento/README.md

[bitnami/magento] Update MariaDB to 14.x.x

---

bitnami/jasperreports/Chart.lock
bitnami/jasperreports/Chart.yaml
bitnami/jasperreports/README.md

[bitnami/jasperreports] Update MariaDB to 14.x.x

---

bitnami/drupal/Chart.lock
bitnami/drupal/Chart.yaml
bitnami/drupal/README.md

[bitnami/drupal] Update MariaDB to 14.x.x

---

bitnami/phpmyadmin/Chart.lock
bitnami/phpmyadmin/Chart.yaml
bitnami/phpmyadmin/README.md

[bitnami/phpmyadmin] Update MariaDB to 14.x.x

---

bitnami/joomla/Chart.lock
bitnami/joomla/Chart.yaml
bitnami/joomla/README.md

[bitnami/joomla] Update MariaDB to 14.x.x

---

bitnami/opencart/Chart.lock
bitnami/opencart/Chart.yaml
bitnami/opencart/README.md

[bitnami/opencart] Update MariaDB to 14.x.x

---

bitnami/mariadb/README.md

[bitnami/mariadb] Update README.md

---

bitnami/moodle/Chart.lock
bitnami/moodle/Chart.yaml
bitnami/moodle/README.md

[bitnami/moodle] Update MariaDB to 14.x.x

---

bitnami/redmine/Chart.lock
bitnami/redmine/Chart.yaml
bitnami/redmine/README.md

[bitnami/redmine] Update MariaDB to 14.x.x

---

.vib/zookeeper/vib-verify.json

[bitnami/zookeeper] Disable ginkgo tests temporarily

---

.vib/apisix/goss/goss.yaml

Fixing Apisix goss test 
- fixes #

[bitnami/apisix] Fix Apisix goss test

---

bitnami/fluentd/Chart.lock
bitnami/fluentd/Chart.yaml

[bitnami/fluentd] update bitnami/common

---

bitnami/fluent-bit/Chart.lock
bitnami/fluent-bit/Chart.yaml

[bitnami/fluent-bit] update bitnami/common

---

bitnami/spark/Chart.lock
bitnami/spark/Chart.yaml

[bitnami/spark] update bitnami/common

---

bitnami/grafana-mimir/Chart.yaml
bitnami/grafana-mimir/values.yaml

Correct alertmanager external_url in grafana mimir configuration.
Copy of #18884
- fixes #

[bitnami/grafana-mimir] Fix alertmanager external url

---

.vib/mlflow/vib-publish.json
.vib/mlflow/vib-verify.json

[bitnami/mlflow] chore: :construction_worker: Update vib-publish.json

---

.vib/pinniped/ginkgo/integration_suite_test.go
.vib/pinniped/ginkgo/pinniped_test.go
.vib/pinniped/ginkgo/scripts/pinniped-auth.sh
bitnami/pinniped/Chart.yaml

[bitnami/pinniped] test: :white_check_mark: Update to use pinniped-cli

---

.vib/nats/goss/goss.yaml
.vib/nats/goss/testfiles/README.md
.vib/nats/goss/testfiles/downloadCLI.sh
bitnami/nats/Chart.yaml

[bitnami/nats] test: :fire: Remove CLI goss tests

---

.vib/pinniped/ginkgo/scripts/pinniped-auth.sh
bitnami/pinniped/Chart.yaml

[bitnami/pinniped] test: :white_check_mark: Use internal API server

---

.github/workflows/retry-failed-releases.yml

Fixes a typo on the POST API URL to avoid current `404` [errors](https://github.com/bitnami/charts/actions/runs/6482224207/job/17601314275). 
The PR now includes some additional improvements:
- Removed an unnecessary usage of the GitHub token for a public API call. 
- Parametrised the `$MAX_RUNS_ATTEMPS` and `$MAX_RETRY_SLOTS` variables.
- The "List workflow runs" query is now limited to runs launched by the `bitnami-bot` in the last 3 days.
- Increased the number of results from the "List workflow runs" query to the maximum of `100` per page.
- Increased workflow's verbose.
These changes we'll allow us to avoid retrieving unnecessary or obsolete info and will make it harder to reach the pagination limit of 100 results.
This leaves untreated the corner case of a catalog-wide error in VIB …

[bitnami/*] Improve logic for retries workflow

---

bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md

[bitnami/spring-cloud-dataflow] Update kafka to 26.x.x

---

bitnami/common/Chart.yaml
bitnami/common/templates/_capabilities.tpl

As discussed on https://github.com/bitnami/charts/pull/19428, I noticed a typo in the new Pod Security Standard objects. This PR corrects the typo.
Using the new function will be typed correctly.
Nothing that I can think of
- Does not relate to any issue

[bitnami/common]: Address admission configuration typo 

---

.github/workflows/retry-failed-releases.yml

[bitnami/*] Fix rerun_url parsing for the retries workflow

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/hidden/headless-svc.yaml

When enabling the following in my yaml configuration for the mongodb chart
```yaml
hidden:
enabled: true
```
I get the following error 
```
Error: INSTALLATION FAILED: YAML parse error on mongodb/templates/hidden/headless-svc.yaml: error converting YAML to JSON: yaml: line 26: mapping values are not allowed in this context
```
Able to correctly setup the Bitnami MongoDb instance with a hidden replica set member
None
- fixes #

[bitnami/mongodb] whitespace preventing YAML from being parsed

---

bitnami/common/README.md

This change is a continuation of https://github.com/bitnami/charts/pull/19835. We couldn't merge this change before due to technical issues
Remove pending references to the registry and the repository
None

[bitnami/common] Standardize documentation

---

template/CHART_NAME/values.yaml

After applying some standardization changes in the values.yaml file and README.md files of all the Bitnami charts, this PR updates the template file we use when creating new solutions
https://github.com/bitnami/charts/pull/19835
https://github.com/bitnami/charts/pull/19841
Template file is updated with the latest changes
None

[templates] Update values file with the latest standardizations

---

.github/workflows/.env

Set correct ID for the Solved column  in the support dashboard.
Fix errors in the [Delete solved cards action](https://github.com/bitnami/charts/actions/workflows/delete-solved-cards.yml)
None.

[bitnami/*] Fix Solve column id

---

bitnami/pytorch/README.md

Fix a small typo in the README file
It improves the documentation
None

[bitnami/pytorch] Fix typo in the README file

---

bitnami/keycloak/README.md

Updated documentation on how to import/export realms with users. This is especially useful in a development context.
Better usability of the image. Would have helped me finding the right information right out of the gates.
Documentation on broken behaviour due to keycloak bug might get out of date. https://github.com/keycloak/keycloak/issues/23970)
- complements [Bitnami / Keycloak] Automatic Keycloak realm import not working https://github.com/bitnami/charts/issues/5178
- complements [bitnami/keycloak] Better support for importing realms https://github.com/bitnami/containers/issues/1046

[bitnami/keycloak] Documentation regarding importing and exporting a keycloak realm

---

bitnami/mysql/Chart.yaml
bitnami/mysql/README.md
bitnami/mysql/values.schema.json
bitnami/mysql/values.yaml

[bitnami/mysql] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/appsmith/Chart.yaml
bitnami/appsmith/README.md
bitnami/appsmith/values.yaml

[bitnami/appsmith] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/apache/Chart.yaml
bitnami/apache/README.md
bitnami/apache/values.yaml

[bitnami/apache] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/haproxy/Chart.yaml
bitnami/haproxy/README.md
bitnami/haproxy/values.yaml

[bitnami/haproxy] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/contour/Chart.yaml
bitnami/contour/templates/crds/httpproxies.yaml

Update httpproxies CRD from the upstream project
allows to use regex route conditions
- fixes #20112

[bitnami/contour] Update httpproxies CRD

---

bitnami/milvus/Chart.lock
bitnami/milvus/Chart.yaml
bitnami/milvus/README.md
bitnami/milvus/values.yaml

[bitnami/milvus] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/joomla/Chart.lock
bitnami/joomla/Chart.yaml
bitnami/joomla/README.md
bitnami/joomla/templates/deployment.yaml
bitnami/joomla/values.yaml

[bitnami/joomla] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/grafana-tempo/Chart.yaml
bitnami/grafana-tempo/README.md
bitnami/grafana-tempo/values.yaml

[bitnami/grafana-tempo] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/grafana-mimir/Chart.yaml
bitnami/grafana-mimir/README.md
bitnami/grafana-mimir/values.yaml

[bitnami/grafana-mimir] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/README.md
bitnami/mongodb/values.yaml

[bitnami/mongodb] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/gitea/Chart.yaml
bitnami/gitea/README.md
bitnami/gitea/values.yaml

[bitnami/gitea] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/flink/Chart.yaml
bitnami/flink/README.md
bitnami/flink/values.yaml

[bitnami/flink] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/drupal/Chart.lock
bitnami/drupal/Chart.yaml
bitnami/drupal/README.md
bitnami/drupal/values.yaml

[bitnami/drupal] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/dokuwiki/Chart.yaml
bitnami/dokuwiki/README.md
bitnami/dokuwiki/templates/deployment.yaml
bitnami/dokuwiki/values.yaml

[bitnami/dokuwiki] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/suitecrm/Chart.lock
bitnami/suitecrm/Chart.yaml
bitnami/suitecrm/README.md
bitnami/suitecrm/values.yaml

[bitnami/suitecrm] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/sonarqube/Chart.lock
bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/README.md
bitnami/sonarqube/values.yaml

[bitnami/sonarqube] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/consul/Chart.yaml
bitnami/consul/README.md
bitnami/consul/values.yaml

[bitnami/consul] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/values.yaml

[bitnami/schema-registry] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/run/dep-job.yaml

When using the following parameters I got an error rendering the yaml:
```
run:
enabled: true
useJob: false
extraEnvVars:
- MLFLOW_TRACKING_URI: http://192.168.49.102/
- MLFLOW_TRACKING_USERNAME: mluser
- MLFLOW_TRACKING_PASSWORD: testpwd
source:
type: "git"
git:
repository: "https://github.com/mlflow/mlflow.git"
launchCommand: "python train.py"
```
Error:
```
Error: template: mlflow/templates/run/dep-job.yaml:91:12: executing "mlflow/templates/run/dep-job.yaml" at <include "mlflow.v0.git.cloneInitContainer" .Values.run>: error calling include: template: mlflow/templates/_helpers.tpl:636:29: executing "mlflow.v0.git.cloneInitContainer" at <.Values.gitImage.pullPolicy>: nil pointer evaluating interface {}.gitImage
```

[bitnami/mlflow] Fix error when using git image

---

bitnami/prestashop/Chart.lock
bitnami/prestashop/Chart.yaml
bitnami/prestashop/README.md
bitnami/prestashop/values.yaml

[bitnami/prestashop] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md
bitnami/wordpress/values.yaml

[bitnami/wordpress] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/wildfly/Chart.yaml
bitnami/wildfly/README.md
bitnami/wildfly/values.yaml

[bitnami/wildfly] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/pytorch/Chart.yaml
bitnami/pytorch/README.md
bitnami/pytorch/values.yaml

[bitnami/pytorch] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/pinniped/Chart.lock
bitnami/pinniped/Chart.yaml
bitnami/pinniped/README.md
bitnami/pinniped/values.yaml

[bitnami/pinniped] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/phpmyadmin/Chart.lock
bitnami/phpmyadmin/Chart.yaml
bitnami/phpmyadmin/README.md
bitnami/phpmyadmin/values.yaml

[bitnami/phpmyadmin] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/opencart/Chart.lock
bitnami/opencart/Chart.yaml
bitnami/opencart/README.md
bitnami/opencart/values.yaml

[bitnami/opencart] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/mediawiki/Chart.lock
bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/README.md
bitnami/mediawiki/values.yaml

[bitnami/mediawiki] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/kong/Chart.yaml
bitnami/kong/README.md
bitnami/kong/values.yaml

[bitnami/kong] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/README.md
bitnami/deepspeed/values.yaml

[bitnami/deepspeed] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/moodle/Chart.lock
bitnami/moodle/Chart.yaml
bitnami/moodle/README.md
bitnami/moodle/values.yaml

[bitnami/moodle] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/magento/Chart.lock
bitnami/magento/Chart.yaml
bitnami/magento/README.md
bitnami/magento/values.yaml

[bitnami/magento] feat: :sparkles: Add support for PSA restricted policy

---

.vib/postgresql-ha/vib-verify.json

PostgreSQL HA tests were really unstable when using a S4 cluster
Tests will be more stable
None
I [tested the changes in my own fork](https://github.com/jotamartos/charts/actions/runs/6786120892/job/18445930207?pr=19) and tests succeeded every time

[bitnami/postgresql-ha] Make ginkgo tests more stable

---

.vib/kubeapps/cypress/cypress.json
.vib/kubeapps/cypress/cypress/integration/kubeapps_spec.js
.vib/kubeapps/cypress/cypress/support/commands.js
.vib/kubeapps/vib-verify.json
bitnami/kubeapps/Chart.yaml

Updates Kubeapps' Cypress tests to look for a new string in its README. This broke after the changes at https://github.com/bitnami/charts/pull/19835, where the string the tests were looking for disappeared.
Tests work
None
Testing passed at https://github.com/bitnami/charts/actions/runs/6788894024

[bitnami/kubeapps] Update Cypress tests

---

.github/dependabot.yml
.github/workflows/assign-asset-label.yml
.github/workflows/cd-pipeline.yml
.github/workflows/ci-pipeline.yml
.github/workflows/clossing-issues.yml
.github/workflows/comments.yml
.github/workflows/delete-solved-cards.yml
.github/workflows/generate-chart-readme.yml
.github/workflows/license-headers.yml
.github/workflows/markdown-linter.yml
.github/workflows/move-closed-issues.yml
.github/workflows/moving-cards.yml
.github/workflows/pr-reviews.yml
.github/workflows/retry-failed-releases.yml
.github/workflows/srp-report.yml
.github/workflows/stale.yml
.github/workflows/sync-teams.yml
.github/workflows/triage.yml

* Use SHA reference for GitHub actions (`vmware-labs/vmware-image-builder-action` is an exception).
* Avoid the use of github context substitution in scripts to prevent script injections.
* Remove third-party actions that can be easily implemented with actions or scripts provided by GitHub.
* `aws-cli` installation and configuration is removed, this step is no needed in `ubuntu-latest`
* Include dependabot rules to update periodically the actions.
* Keep updated the actions.
Apply GitHub best practices, reduce attack surface and risks related to the use of third party actions.
Some actions has been updated to its latest major version. These actions are:
* apache/skywalking-eyes/header
* pozil/auto-assign-issue
* actions/stale
Due to that we could face some issues in the execution of the …

[bitnami/charts] GitHub actions hardening

---

.github/workflows/ci-pipeline.yml

Comment with `bitnami-bot` user to trigger support workflows.
Avoid missing PR in support dashboard.
None

Use bitnami-bot to comment on failing pipelines

---

bitnami/sealed-secrets/Chart.yaml
bitnami/sealed-secrets/crds/sealed-secrets.yaml

Update sealed-secrets crd from upstream repository
https://github.com/bitnami-labs/sealed-secrets/pull/1217 
- fixes  #20667

Sealed secrets crd update

---

template/CHART_NAME/README.md

This PR ...
- adds the information regarding TAC (bitnami.com/enterprise) in the charts' template
- updates the links to be https, # or img
- uses the REGISTRY_NAME/REPOSITORY_NAME placeholders
- adds the note regarding those placeholders
- [Na] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)

[template] Update template file with the latest changes

---

bitnami/milvus/Chart.yaml
bitnami/milvus/README.md
bitnami/milvus/templates/attu/deployment.yaml
bitnami/milvus/templates/data-coordinator/deployment.yaml
bitnami/milvus/templates/data-node/deployment.yaml
bitnami/milvus/templates/index-coordinator/deployment.yaml
bitnami/milvus/templates/index-node/deployment.yaml
bitnami/milvus/templates/proxy/deployment.yaml
bitnami/milvus/templates/query-coordinator/deployment.yaml
bitnami/milvus/templates/query-node/deployment.yaml
bitnami/milvus/templates/root-coordinator/deployment.yaml
bitnami/milvus/values.schema.json
bitnami/milvus/values.yaml

[bitnami/milvus] Fixup milvus & externalS3 couldn't be deployed in the same namespace (bitnami#20396)

---

bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/templates/deployment.yaml

This allows the grafana-operator to watch a restricted set of namespaces without locking it down to its own namespace.
This fixes the configuration bug identified in https://github.com/bitnami/charts/issues/20960.
Users will be able to deploy a grafana-operator that watches a restricted set of namespaces.
None.
- fixes #20960

[bitnami/grafana-operator] Fix namespace restriction bug (#20960)

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
bitnami/argo-workflows/README.md
bitnami/clickhouse/README.md
bitnami/concourse/README.md
bitnami/grafana-loki/README.md
bitnami/grafana-mimir/README.md
bitnami/milvus/README.md
bitnami/oauth2-proxy/README.md
bitnami/pinniped/README.md
bitnami/redis/README.md
template/CHART_NAME/README.md

This project was recently transferred from the [bitnami-labs](https://github.com/bitnami-labs) organization to the regular [bitnami](https://github.com/bitnami) one

Update readme-generator links

---

bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/crds/crds-messaging-topology-operator.yaml

[bitnami/rabbitmq-cluster-operator] refresh messaging-topology-operator crds

---

bitnami/matomo/Chart.yaml
bitnami/matomo/templates/cronjob.yaml

The `taskScheduler` cron job uses wrong `suspend` value, so it can't be suspended seperately.
Allow the `taskScheduler` cronjob to be suspended by the documented value `cronjobs.taskScheduler.suspend`.
`taskScheduler` cronjob is no longer suspended by the `cronjobs.archive.suspend` value.
none

[bitnami/matomo] taskScheduler cronjob uses wrong suspend value

---

bitnami/milvus/Chart.yaml
bitnami/milvus/templates/NOTES.txt

Fix some typos with the instructions to obtain Milvus services included in NOTES.txt

[bitnami/milvus] Fix Milvus notes

---

template/CHART_NAME/templates/daemonset.yaml
template/CHART_NAME/templates/deployment.yaml
template/CHART_NAME/templates/statefulset.yaml
template/CHART_NAME/values.yaml
template/README.md

Allow to specify annotations for specific controllers (e.g. daemonset, deployment, statefulset)
There is no possibility to add annotations only for specific daemonset/deployment/statefulset.
My proposal is introduce such entities as deploymentAnnotations, statefulsetAnnotations and daemonsetAnnotations, as for now we can only apply annotations to daemonset/deployment/statefulset globally, by the means of .Values.commonAnnotations.
For example: when one wants to use [stakater/Reloader](https://github.com/stakater/Reloader) to reload daemonset/deployment/statefulset on secret/configmap change, one must add specific annotation to the entity one wants to manage as such.
- fixes #20983

[bitnami/template] allow specific annotations for controllers

---

bitnami/minio/Chart.yaml

Just bumping it again for https://github.com/bitnami/charts/pull/21032 as it was not correctly detected by github.
N/A
N/A
N/A
N/A

[bitnami/minio] Bump minio chart for 21032 PR

---

bitnami/matomo/Chart.yaml

Bumped the version of the chart.

Bumped the chart

---

bitnami/sealed-secrets/Chart.yaml
bitnami/sealed-secrets/templates/deployment.yaml

Unquote the key-prefix argument so the controller start
The controller will start again
- fixes #21355

[bitnami/sealed-secrets] do not double quote the secret name

---

.vib/cassandra/ginkgo/cassandra_suite_test.go
.vib/clickhouse/ginkgo/clickhouse_suite_test.go
.vib/consul/ginkgo/consul_suite_test.go
.vib/elasticsearch/ginkgo/elasticsearch_suite_test.go
.vib/etcd/ginkgo/etcd_suite_test.go
.vib/influxdb/ginkgo/influxdb_suite_test.go
.vib/kafka/ginkgo/kafka_suite_test.go
.vib/mariadb-galera/ginkgo/mariadb_suite_test.go
.vib/mariadb/ginkgo/mariadb_suite_test.go
.vib/minio/ginkgo/minio_suite_test.go
.vib/mongodb-sharded/ginkgo/mongodb_suite_test.go
.vib/mongodb/ginkgo/mongodb_suite_test.go
.vib/mysql/ginkgo/mysql_suite_test.go
.vib/nats/ginkgo/nats_suite_test.go
.vib/opensearch/ginkgo/opensearch_suite_test.go
.vib/postgresql-ha/ginkgo/postgresql_suite_test.go
.vib/postgresql/ginkgo/postgresql_suite_test.go
.vib/rabbitmq/ginkgo/rabbitmq_suite_test.go
.vib/redis-cluster/ginkgo/redis_suite_test.go
.vib/redis/ginkgo/redis_suite_test.go
.vib/solr/ginkgo/solr_suite_test.go
.vib/zookeeper/ginkgo/zookeeper_suite_test.go

This PR adapts the ginkgo tests to be run in a PSA restricted environment.
Result:
```
Ran 1 of 1 Specs in 39.269 seconds
SUCCESS! -- 1 Passed | 0 Failed | 0 Pending | 0 Skipped
PASS
```
- fixes #

[bitnami/*] test: :white_check_mark: Support restricted PSA

---

.vib/flux/runtime-parameters.yaml
.vib/oauth2-proxy/runtime-parameters.yaml
.vib/pinniped/runtime-parameters.yaml

[bitnami/pinniped, oauth2-proxy, flux] test: :white_check_mark: Fix runtime-parameters for PSA restricted mode

---

.vib/argo-cd/cypress/cypress/fixtures/applications.json
.vib/jaeger/runtime-parameters.yaml

[bitnami/argo-cd, jaeger] test: :white_check_mark: Make tests compatible with PSA restricted

---

.github/workflows/ci-pipeline.yml

Log chart info CI pipelines
Log information about the chart that can be easily used from other integrations.
None
Execution example: https://github.com/fmulero/charts/actions/runs/7196782267

[bitnami/*] Log chart info in CI pipeline

---

bitnami/milvus/Chart.yaml
bitnami/milvus/README.md
bitnami/milvus/templates/_helpers.tpl
bitnami/milvus/templates/init-job.yaml
bitnami/milvus/templates/proxy/deployment.yaml
bitnami/milvus/values.schema.json
bitnami/milvus/values.yaml

[bitnami/milvus] Fix milvus server cannot startup with SSL (#19838)

---

bitnami/nginx/Chart.yaml
bitnami/nginx/values.schema.json

Add Security Context properties to `values.schema.json`
These parameters can be customized directly during installation when using tools that consume this metadata. For instance, Kubeapps.
None
NA
NA

[bitnami/nginx] Add securityContext to values schema

---

bitnami/phpbb/Chart.lock
bitnami/phpbb/Chart.yaml
bitnami/phpbb/README.md

[bitnami/phpbb] Upgrade MariaDB 11.2

---

bitnami/magento/Chart.lock
bitnami/magento/Chart.yaml
bitnami/magento/README.md

[bitnami/magento] Upgrade MariaDB 11.2

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/backup/cronjob.yaml

Correct the incorrect use of `securityContext`.
Cronjob no longer reports schema error
None
- fixes #

[bitnami/mongodb] Pod security context doesn't apply to cronjobs

---

.vib/kong/runtime-parameters.yaml

Set `securityContext` in the  `nginx-vib-tests` deployment used for testing.
We can run tests in environments with PSA enabled.
None
None

[bitnami/kong] Configure securityContext in test deploy

---

.vib/apisix/runtime-parameters.yaml

Add `securityContext` to the `nginx` deployment used for testing.
We can ran tests on clusters with PSA enabled.
None.
[vib execution](https://github.com/bitnami/charts/actions/runs/7337954202/job/19979686329?pr=21767)

[bitnami/apisix] Add securityContext to test deployment

---

.vib/flink/runtime-parameters.yaml

Add `securityContext` to the `nginx` deployment used for testing.
We can ran tests on clusters with PSA enabled.
None.
[vib execution](https://github.com/bitnami/charts/actions/runs/7340156005/job/19985687214?pr=21775)

[bitnami/flink] Add securityContext to test job

---

bitnami/tensorflow-resnet/Chart.yaml
bitnami/tensorflow-resnet/templates/deployment.yaml

Add security context to 'seed' container.
This change allows running the chart on PSA-Restricted environments.
None.

[bitnami/tensorflow-resnet] Add security context to 'seed' container

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/sentinel/node-services.yaml

Fix wrong context reference in `bitnami/redis/templates/sentinel/node-services.yaml`
Redis can be installed using a `NodePort` sentinel service.
None
- fixes #21619

[bitnami/redis] Use correct context to retrieve node ports for sentinel service

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/README.md
bitnami/mongodb/templates/standalone/dep-sts.yaml
bitnami/mongodb/values.yaml

[bitnami/mongodb] Added possibility to configure persistence volume name and claim name

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/configmap-env-vars.yaml

This is to fix a spelling error in an environment variable. The original variable name KC_LOG_LEVEL has a spelling mistake, which may prevent the correct setting of Keycloak's log level. By correcting the variable name to the correct KEYCLOAK_LOG_LEVEL, we can ensure that the environment variable can work properly and set Keycloak's log level correctly.
- fixes #21885

[bitnami/keycloak] Fix the spelling error of KC_LOG_LEVEL, correct it to the correct KEYCLOAK_LOG_LEVEL

---

.vib/redmine/goss/goss.yaml
bitnami/redmine/Chart.yaml
bitnami/redmine/README.md
bitnami/redmine/values.yaml

[bitnami/redmine] feat: :sparkles: Add seccompProfile to containerSecurityContext

---

bitnami/whereabouts/Chart.yaml
bitnami/whereabouts/README.md
bitnami/whereabouts/values.yaml

[bitnami/whereabouts] feat: :sparkles: Add seccompProfile to containerSecurityContext

---

.vib/odoo/goss/goss.yaml
bitnami/odoo/Chart.yaml
bitnami/odoo/README.md
bitnami/odoo/values.yaml

[bitnami/odoo] feat: :sparkles: Add seccompProfile to containerSecurityContext

---

bitnami/multus-cni/Chart.yaml
bitnami/multus-cni/README.md
bitnami/multus-cni/values.yaml

[bitnami/multus-cni] feat: :sparkles: Add seccompProfile to containerSecurityContext

---

.vib/discourse/goss/goss.yaml
bitnami/discourse/Chart.yaml
bitnami/discourse/README.md
bitnami/discourse/values.yaml

[bitnami/discourse] feat: :sparkles: Add seccompProfile to containerSecurityContext

---

bitnami/gitea/Chart.yaml
bitnami/gitea/README.md
bitnami/gitea/values.yaml

[bitnami/gitea] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/appsmith/Chart.yaml
bitnami/appsmith/README.md
bitnami/appsmith/values.yaml

[bitnami/appsmith] fix: :lock: Do not mount service account token

---

bitnami/airflow/Chart.yaml
bitnami/airflow/README.md
bitnami/airflow/values.yaml

This PR sets the service account creation to true. As RBAC is not enabled by default, the automount of the service account token is set to false.
- fixes #

[bitnami/airflow] fix: :lock: Do not use the default service account

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/README.md
bitnami/cassandra/values.yaml

[bitnami/cassandra] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/spark/Chart.yaml
bitnami/spark/README.md
bitnami/spark/values.yaml

[bitnami/spark] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/haproxy/Chart.yaml
bitnami/haproxy/README.md
bitnami/haproxy/values.yaml

[bitnami/haproxy] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/supabase/Chart.yaml
bitnami/supabase/README.md
bitnami/supabase/templates/_helpers.tpl
bitnami/supabase/templates/jwt-init-job.yaml
bitnami/supabase/values.yaml

[bitnami/supabase] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/values.yaml

[bitnami/schema-registry] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/mysql/Chart.yaml
bitnami/mysql/README.md
bitnami/mysql/values.yaml

[bitnami/mysql] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/drupal/Chart.yaml
bitnami/drupal/README.md
bitnami/drupal/values.yaml

[bitnami/drupal] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/solr/Chart.yaml
bitnami/solr/README.md
bitnami/solr/values.yaml

[bitnami/solr] fix: :lock: Do not use the default service account

---

bitnami/clickhouse/Chart.yaml
bitnami/clickhouse/README.md
bitnami/clickhouse/values.yaml

[bitnami/clickhouse] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/README.md
bitnami/aspnet-core/values.yaml

[bitnami/aspnet-core] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/parse/Chart.yaml
bitnami/parse/README.md
bitnami/parse/values.yaml

[bitnami/parse] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md
bitnami/oauth2-proxy/values.yaml

[bitnami/oauth2-proxy] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/README.md
bitnami/argo-workflows/values.yaml

This PR sets the service account creation to true to avoid using the default service account (which could pose a security issue)
- fixes #

[bitnami/argo-workflows] fix: :lock: Do not use the default service account

---

bitnami/milvus/Chart.yaml
bitnami/milvus/README.md
bitnami/milvus/values.yaml

[bitnami/milvus] fix: :lock: Do not use the default service account

---

bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/README.md
bitnami/sonarqube/values.yaml

[bitnami/sonarqube] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/README.md
bitnami/jupyterhub/values.yaml

[bitnami/jupyterhub] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/README.md
bitnami/grafana-loki/values.yaml

[bitnami/grafana-loki] fix: :lock: Do not use the default service account

---

bitnami/fluent-bit/Chart.yaml
bitnami/fluent-bit/templates/hpa.yaml

[bitnami/fluent-bit] Fix HPA API version template usage

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/README.md
bitnami/mongodb/templates/hidden/statefulset.yaml
bitnami/mongodb/templates/replicaset/statefulset.yaml
bitnami/mongodb/values.yaml

[bitnami/mongodb] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/apisix/Chart.yaml
bitnami/apisix/README.md
bitnami/apisix/values.yaml

[bitnami/apisix] fix: :lock: Do not mount service account token unless necessary

---

.vib/deepspeed/runtime-parameters.yaml
bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/README.md
bitnami/deepspeed/values.yaml

This PR sets the service account creation to true to avoid using the default service account (which could pose a security issue)
- fixes #

[bitnami/deepspeed] fix: :lock: Do not use the default service account

---

bitnami/apisix/Chart.yaml
bitnami/apisix/README.md
bitnami/apisix/templates/NOTES.txt
bitnami/apisix/templates/ingress-controller/clusterroles.yaml
bitnami/apisix/templates/ingress-controller/secret-namespaced-rbac.yaml
bitnami/apisix/values.yaml

The following PR allows limiting the namespaces that the application can check for secrets. By default, it is using a ClusterRole, which has security implications that should be taken into account by operators.
The default value is to allow secrets to in all namespaces so we don't break upgrades.
- fixes #

[bitnami/apisix] feat: :lock: Allow limit access to secrets by namespace

---

.vib/flux/runtime-parameters.yaml
bitnami/flux/Chart.yaml
bitnami/flux/templates/crds/notification-controller/notification.toolkit.fluxcd.io_alerts.yaml
bitnami/flux/templates/crds/notification-controller/notification.toolkit.fluxcd.io_providers.yaml

Currently the notification controller is failing after a short period with the following error:
```
failed to get API group resources: unable to retrieve the complete list of server APIs: notification.toolkit.fluxcd.io/v1beta3: the server could not find the requested resource
```
Updating the crds for notification providers and notification alerts to `v1beta3` fixes this.
The upstream API version of the notification controller is v1beta3:
https://github.com/fluxcd/website/commit/a740f4d96186bd823a2a2bcbe3bf6a0ea7bb0b74

[bitnami/flux] Update Flux notification api version

---

bitnami/kong/Chart.yaml
bitnami/kong/crds/custom-resource-definitions.yaml

[bitnami/kong] Update CRDs and add source header

---

bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/crds/grafanadashboards.integreatly.org.yaml
bitnami/grafana-operator/crds/grafanadatasources.integreatly.org.yaml
bitnami/grafana-operator/crds/grafanafolders.integreatly.org.yaml
bitnami/grafana-operator/crds/grafanas.integreatly.org.yaml

[bitnami/grafana-operator] Update CRDs and add source header

---

bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/crds/crd.yaml

[bitnami/external-dns] Update CRDs and add source header

---

bitnami/kuberay/Chart.yaml
bitnami/kuberay/crds/ray.io_rayclusters.yaml
bitnami/kuberay/crds/ray.io_rayjobs.yaml
bitnami/kuberay/crds/ray.io_rayservices.yaml

[bitnami/kuberay] Update CRDs and add source header

---

bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/templates/hub/configmap.yaml
bitnami/jupyterhub/values.yaml

This PR updates the kubespawner script of Jupyterhub so the single user instances now contain the proper securityContext sections to be compatible with PSA restricted.
Security enhancement
- fixes #

[bitnami/jupyterhub] feat: :lock: Add compatibility with PSA restricted

---

bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/templates/controller/workflow-role.yaml
bitnami/argo-workflows/templates/controller/workflow-rolebinding.yaml

Fix bug in workflows role and rolebinding templates whereas the workflowNamespaces value was not respected and prevented instantiation for said templates in target namespaces.
- fixes #

[bitnami/argo-workflows] bugfix: Fix argo workflows namespaces roles and rolebindings

---

bitnami/apisix/Chart.yaml
bitnami/apisix/README.md
bitnami/apisix/values.yaml

This PR enables the liveness probe, which was disabled for no reason
- fixes #

[bitnami/apisix] fix: :bug: Enable liveness probe

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/health-ingress.yaml
bitnami/nginx/templates/ingress.yaml

Fix Helm templating error.
Helm Chart bitnami/nginx can be installed with `ingress.extraHosts` set.
- fixes #22474

[bitnami/nginx]: Fix template scope for .Values

---

bitnami/whereabouts/Chart.yaml
bitnami/whereabouts/README.md
bitnami/whereabouts/templates/networkpolicy.yaml
bitnami/whereabouts/values.yaml

[bitnami/whereabouts] feat: :lock: Enable networkPolicy

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/deployment.yaml

Add condition before initContainers to remove empty `initContainers:` block when `cloneStaticSiteFromGit.enabled: false`
Default kyverno rules will pass when `cloneStaticSiteFromGit.enabled: false` is set, other it will apply rules to the empty `initContainers:` block.
Future templated initContainers have to be added to `or` statement.
- fixes #

[bitnami/nginx]: Add contitional to initContainers block

---

.gitmodules

Remove charts-docs submodule as it's now deprecated. Related to this previous PR
https://github.com/bitnami/charts/pull/22203

[docs] Remove charts-docs submodule

---

bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/README.md
bitnami/mediawiki/values.yaml

Add metrics.serviceMonitor.jobLabel parameter to values.yaml.
If metrics.enabled=true is set, fluxcd will fail checking the HelmRelease state:
```
mediawiki               mediawiki                       18.2.0          True            False   Could not determine release state: unable to determine cluster state: ServiceMonitor/mediawiki/mediawiki dry-run failed (Invalid): ServiceMonitor.monitoring.coreos.com "mediawiki" is invalid: spec.jobLabel: Invalid value: "null": spec.jobLabel in body must be of type string: "null"
```
By setting jobLabel default to an empty string, the problem is solved.
Not that I'm aware of.

[bitnami/mediawiki] Add param metrics.serviceMonitor.jobLabel

---

bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/templates/_helpers.tpl
bitnami/schema-registry/templates/networkpolicy.yaml
bitnami/schema-registry/values.yaml

[bitnami/schema-registry] feat: :lock: Enable networkPolicy

---

bitnami/tomcat/Chart.yaml
bitnami/tomcat/templates/_pod.tpl

Fixes the tomcat http configuration.
The user is able to configure the container port by using `containerPorts.http`

[bitnami/tomcat] Fix http port configuration

---

bitnami/phpmyadmin/Chart.yaml
bitnami/phpmyadmin/README.md
bitnami/phpmyadmin/templates/deployment.yaml
bitnami/phpmyadmin/values.yaml

Allows to set number of replicas. Fixes #22816.

[bitnami/phpmyadmin]: add number of replicas

---

bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/crds/crd.yaml

[bitnami/external-dns] Update CRDs and add headers for automatic update

---

bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/crds/messaging-topology-operator/rabbitmq.com_bindings.yaml
bitnami/rabbitmq-cluster-operator/crds/messaging-topology-operator/rabbitmq.com_exchanges.yaml
bitnami/rabbitmq-cluster-operator/crds/messaging-topology-operator/rabbitmq.com_federations.yaml
bitnami/rabbitmq-cluster-operator/crds/messaging-topology-operator/rabbitmq.com_permissions.yaml
bitnami/rabbitmq-cluster-operator/crds/messaging-topology-operator/rabbitmq.com_policies.yaml
bitnami/rabbitmq-cluster-operator/crds/messaging-topology-operator/rabbitmq.com_queues.yaml
bitnami/rabbitmq-cluster-operator/crds/messaging-topology-operator/rabbitmq.com_schemareplications.yaml
bitnami/rabbitmq-cluster-operator/crds/messaging-topology-operator/rabbitmq.com_shovels.yaml
bitnami/rabbitmq-cluster-operator/crds/messaging-topology-operator/rabbitmq.com_superstreams.yaml
bitnami/rabbitmq-cluster-operator/crds/messaging-topology-operator/rabbitmq.com_topicpermissions.yaml
bitnami/rabbitmq-cluster-operator/crds/messaging-topology-operator/rabbitmq.com_users.yaml
bitnami/rabbitmq-cluster-operator/crds/messaging-topology-operator/rabbitmq.com_vhosts.yaml
bitnami/rabbitmq-cluster-operator/crds/rabbitmq-cluster/rabbitmq.com_rabbitmqclusters.yaml

[bitnami/rabbitmq-cluster-operator] Update CRDs and add headers for automatic update

---

bitnami/kong/Chart.yaml
bitnami/kong/crds/custom-resource-definitions.yaml

[bitnami/kong] Update CRDs and add headers for automatic update

---

bitnami/contour/Chart.yaml
bitnami/contour/templates/crds/contour-crds.yaml

[bitnami/contour] Update CRDs and add headers for automatic update

---

bitnami/supabase/Chart.yaml
bitnami/supabase/README.md
bitnami/supabase/templates/auth/networkpolicy.yaml
bitnami/supabase/templates/meta/networkpolicy.yaml
bitnami/supabase/templates/realtime/networkpolicy.yaml
bitnami/supabase/templates/rest/networkpolicy.yaml
bitnami/supabase/templates/storage/networkpolicy.yaml
bitnami/supabase/templates/studio/networkpolicy.yaml
bitnami/supabase/values.yaml

[bitnami/supabase] fix: :bug: Add allowExternalEgress to avoid breaking istio

---

bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/README.md
bitnami/sonarqube/values.yaml

A comment in the values.yaml mentions that possible values for the update strategy of the deployment are ```RollingUpdate``` and ```OnDelete```.
Using  ```OnDelete``` leads to invalid manifests though:
```
spec.strategy: Unsupported value: apps.DeploymentStrategy{Type:"OnDelete", RollingUpdate:(*apps.RollingUpdateDeployment)(nil)}: supported values: "Recreate", "RollingUpdate"
```
This fix just corrects the comment in values.yaml to show ```RollingUpdate``` and ```Recreate``` as possible options.
Correct docs ;)
None
None
None

[bitnami/sonarqube] Fix updateStrategy.type option comment in default values

---

bitnami/whereabouts/Chart.yaml
bitnami/whereabouts/README.md
bitnami/whereabouts/templates/networkpolicy.yaml
bitnami/whereabouts/values.yaml

[bitnami/whereabouts] fix: :bug: Add allowExternalEgress to avoid breaking istio

---

bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/templates/networkpolicy.yaml
bitnami/schema-registry/values.yaml

[bitnami/schema-registry] fix: :bug: Add allowExternalEgress to avoid breaking istio

---

bitnami/nginx-ingress-controller/Chart.yaml
bitnami/nginx-ingress-controller/README.md
bitnami/nginx-ingress-controller/templates/controller-networkpolicy.yaml
bitnami/nginx-ingress-controller/templates/default-backend-networkpolicy.yaml
bitnami/nginx-ingress-controller/values.yaml

[bitnami/nginx-ingress-controller] fix: :bug: Add allowExternalEgress to avoid breaking istio

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/backup/cronjob.yaml

mongodb backup cronjob will now respect the `global.imagePullSecrets` and `image.pullPolicy`settings
backup job will be able to launch if a private image repository requiring authentication is used
None
- fixes #23021

[bitnami/mongodb] backup cronjob respects global.imagePullSecrets and image.pullPolicy

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/networkpolicy.yaml

This PR sets the https value for network policy conditional as this is not set by default.
- fixes https://github.com/bitnami/charts/issues/23058

[bitnami/nginx] fix: :bug: Use conditional value for https in networkpolicy

---

bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/_helpers.tpl

Adds the possibility to use templating on existingSecret variable on redis-cluster charts.
It will allow more flexibility when specifying the variable existingSecret
- #22549

[bitnami/redis-cluster] feat: Allow templating on existingSecret param

---

bitnami/moodle/Chart.yaml

Bump moodle chart version.
Release changes from #23283. The chart version in that PR was overlapped with the PR #23113 and those changes were not released.
None
Changes described on #23283 were not released.

[bitnami/moodle] Bump chart version

---

.github/workflows/ci-pipeline.yml

Use CSP_API_TOKEN in CI pipelines
Use same token in CI and CD wokflows.
@bitnami/charts-support  should be aware of this change to know what organization we are using for our tests.

[bitnami/charts] CSP_API_TOKEN for CI pipelines

---

bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/README.md
bitnami/aspnet-core/values.yaml

This PR adds support for aspnet-core baseline security context. We need to enable one kernel capability (NET_BIND_SERVICE) in order to allow it.
- fixes #

[bitnami/aspnet-core] feat: :lock: Allow running in PSA baseline mode

---

bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
bitnami/postgresql-ha/templates/postgresql/witness-statefulset.yaml

Applies same fix from #15816 to postgresql-ha chart.
- Fixes same issue as described in #15526 for postgresql-ha

 [bitnami/postgresql-ha] Fix: Add missing version, kind to volumeClaimTemplates

---

bitnami/common/Chart.yaml
bitnami/common/templates/_resources.tpl

Security checklists also require the `ephemeral-storage` section to be set.  This is used for emptyDir volumes that do not have `medium: Memory`. In this sense, these should not be very high (except for charts where we download datasets like tensorflow-resent or clone git repos like deepspeed).  Then, it could be used by applications that write temporary data or logs that we have not detected.
We've set a very low request value (50Mi) and then increased a bit based on the instance size. However, we should not expect the ephemeral-storage to be highly consumed, otherwise we should check the application logic.
- fixes #

[bitnami/common] feat: :sparkles: Add ephemeral-storage to resources preset

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/templates/svc.yaml
bitnami/rabbitmq/values.yaml

Allow specifying loadBalancerClass on service.
This will allow using different loadbalancers for different services.
Should not affect anyone not using this configuration.
- fixes #

[bitnami/rabbitmq] Allow specifying service loadBalancerClass

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/statefulset.yaml

This PR removes the empty-dir volume from the if statement that was preventing the volume mounting
- fixes https://github.com/bitnami/charts/issues/23905

[bitnami/mongodb] fix: :bug: Add missing empty-dir in arbiter

---

.vib/argo-workflows/cypress/cypress/fixtures/workflow-template.json
bitnami/argo-workflows/Chart.yaml

Updates the template used for the testing. This should allow running the test in more restricted environments.
- fixes #
Test passed in this [job](https://github.com/bitnami/charts/actions/runs/8098011353/job/22130440650)

Draft: [CONTENT-7704] Update argocd workflow template

---

bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/values.yaml

Fix executor securitycontext config generation
- fixes #

[bitnami/argo-workflows] Fix executor securitycontext

---

bitnami/jenkins/Chart.yaml
bitnami/jenkins/templates/_helpers.tpl
bitnami/jenkins/templates/casc-cm.yaml

This PR fixes an issue with Jenkins resources in the agent, as it was causing a null pointer exception.
- fixes https://github.com/bitnami/charts/issues/23945

[bitnami/jenkins] fix: :bug: Allow empty resources in jenkins agent

---

.vib/nats/ginkgo/nats_test.go

Tests continued failing in some platforms. We are now checking that a key/value is added to the database and increasing the delay before deleting the pods.
Make the tests stable in some platforms
None
- related to https://github.com/bitnami/charts/pull/23952

[bitnami/nats] Improve Ginkgo tests to make tests more stable

---

bitnami/ejbca/Chart.lock
bitnami/ejbca/Chart.yaml
bitnami/ejbca/README.md

Bump dependencies to the latest major of MariaDB
None

[bitnami/ejbca] Update dependencies

---

.vib/argo-workflows/cypress/cypress/e2e/argo_workflows.cy.js

Adds a delay before starting the testing to let the deployment to be ready.
- fixes #

[bitnami/argo-workflows] Adds a delay before starting the test

---

bitnami/fluent-bit/Chart.yaml
bitnami/fluent-bit/values.yaml

- add `Parsers_File` parameters for fluent-bit service
- `Parsers_File /opt/bitnami/fluent-bit/conf/parsers.conf`
- `Parsers_File /opt/bitnami/fluent-bit/conf/custom_parsers.conf`
- bump version
Without that changes fluent-bit ignores parsers and cannot use default(`parsers.conf`) or custom parsers(`custom_parsers.conf`) at all.
So, with that fix, fluent-bit can use parsers.
None.
None.
Example: <https://github.com/fluent/helm-charts/blob/e6aef88910eb9494198d8f3d1805f501aafadf3a/charts/fluent-bit/values.yaml#L358>

[bitnami/fluent-bit] feat: add missing parser files definitions

---

.vib/argo-workflows/cypress/cypress/e2e/argo_workflows.cy.js

[bitnami/argcd-workflow] Bumps cypress start delay

---

bitnami/contour/Chart.yaml
bitnami/contour/templates/envoy/daemonset.yaml
bitnami/contour/templates/envoy/deployment.yaml

This PR adds missing if/else sections in the resources block, which was causing volumeMounts to fail.
- fixes https://github.com/bitnami/charts/issues/24026 https://github.com/bitnami/charts/issues/24026

[bitnami/contour] fix: :bug: Add missing if/end statement to resources section

---

.vib/argo-workflows/cypress/cypress/e2e/argo_workflows.cy.js

This change is for debugging purposes only. Once the issue if fixed it will be returned to normal values or even deleted.
- fixes #

[bitnami/argo-worflows] Increase timeout to debug cypress test

---

.vib/argo-workflows/cypress/cypress/e2e/argo_workflows.cy.js

[bitnami/argo-workflows] Restore delay to a normal value

---

.vib/argo-workflows/cypress/cypress/e2e/argo_workflows.cy.js

[bitnami/argcd-workflow] Moves delay to the end

---

.vib/argo-workflows/cypress/cypress/e2e/argo_workflows.cy.js

[bitnami/argo-workflows] Removes long delay in testing

---

.vib/argo-workflows/cypress/cypress/e2e/argo_workflows.cy.js

[bitnami/argo-workflows] Adds delay in testing

---

.vib/argo-workflows/cypress/cypress/e2e/argo_workflows.cy.js

[bitnami/argo-workflow] Increase delay

---

bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/application-controller/servicemonitor.yaml
bitnami/argo-cd/templates/applicationset/servicemonitor.yaml
bitnami/argo-cd/templates/dex/servicemonitor.yaml
bitnami/argo-cd/templates/notifications/servicemonitor.yaml
bitnami/argo-cd/templates/repo-server/servicemonitor.yaml
bitnami/argo-cd/templates/server/servicemonitor.yaml

See https://github.com/bitnami/charts/pull/24020
- fixes #

 [bitnami/argo-cd] fix: add missing brackets

---

bitnami/rabbitmq/README.md

This PR updates the README.md notes for version 12.10.0, where network policies are enabled by default.
- fixes https://github.com/bitnami/charts/issues/24181

[bitnami/rabbitmq] docs: :memo: Add upgrade notes for 12.10.0

---

bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml
bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml

See https://github.com/bitnami/charts/pull/24020
- fixes #

[bitnami/mongodb-sharded] fix: correct indention

---

bitnami/kuberay/Chart.yaml
bitnami/kuberay/templates/operator/networkpolicy.yaml

See https://github.com/bitnami/charts/pull/24020
- fixes #

[bitnami/kuberay] fix: correct indention

---

bitnami/redis/README.md

Fix some typos in README.md
None
None
None
None

[bitnami/redis] Fix (r) and reg typos in README.md

---

bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/cronjob-backup.yaml

Adding the imagePullSecrets to the backup CronJob.
Private docker repositories can be used.
Backup with private docker repositories not possible.
- fixes #24449

[bitnami/influxdb] add imagePullSecrets to backup

---

bitnami/redis/Chart.yaml
bitnami/redis/values.yaml

fix #24499
use `@skip` readme-genetator-for-helm annotations to hide the previous options
- fixes #24499

[bitnami/redis] handling of deprecated relabellings

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/statefulset.yaml

This PR mounts an empty-dir in /bitnami/mongodb in arbiter nodes. Even though they don't have persistence the application writes in that directory.
- fixes https://github.com/bitnami/containers/issues/63885

[bitnami/mongodb] fix: :bug: Mount emptyDir in /bitnami/mongodb in arbiter node

---

bitnami/grafana/Chart.yaml
bitnami/grafana/templates/deployment.yaml

This PR adds an emptyDir in /bitnami/grafana, which is necessary for allowing running init scripts.
- fixes https://github.com/bitnami/charts/issues/24473

[bitnami/grafana] fix: :bug: Mount emptyDir in /bitnami/grafana to allow init scripts

---

bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/templates/controller/deployment.yaml
bitnami/argo-workflows/templates/server/deployment.yaml

Add app.kubernetes.io/part-of: argo-workflows labels to the controller and server pod template
The networkpolicies will work again.
- fixes #24534

[bitnami/argo-workflows] Add app.kubernetes.io/part-of label to pod template

---

bitnami/mastodon/Chart.yaml
bitnami/mastodon/templates/sidekiq/deployment.yaml

Sidekiq jobs fail because the ruby impl looking for temporary directories checks for the sticky bit if the directory is world-writable. This fails with directory backed emptyDir volumes on k8s. 
This change simply sets the backend for the emptyDir mounted to /tmp in the sidekiq pod to be memory-based rather than filesystem based.
Some interesting links:
- https://github.com/kubernetes/kubernetes/issues/110835
- https://shivering-isles.com/2023/09/about-read-only-containers-ruby-and-emptydir
Fixes failing sidekiq jobs.
None that I could identify, except maybe for slightly higher RAM consumption.
- N/A

[bitnami/mastodon] Fix Sidekiq jobs failing (temp directory detection)

---

bitnami/deepspeed/values.yaml
bitnami/kong/values.yaml
bitnami/logstash/values.yaml
bitnami/mariadb-galera/values.yaml
bitnami/mariadb/values.yaml
bitnami/mastodon/values.yaml
bitnami/memcached/values.yaml
bitnami/metallb/values.yaml
bitnami/metrics-server/values.yaml
bitnami/milvus/values.yaml
bitnami/minio/values.yaml
bitnami/mlflow/values.yaml
bitnami/mysql/values.yaml
bitnami/nats/values.yaml
bitnami/odoo/values.yaml
bitnami/opensearch/values.yaml
bitnami/redis-cluster/values.yaml

Fix issue in comments mentioning Keycloak instead of the specific chart.
The version in the values.yaml wasn't bumped on purpose since those changes only affect comments. A new release won't be cut but the changes can be merged.

[bitnami/several] Fix comment mentioning Keycloak

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/serviceaccount.yaml

Updates the created ServiceAccount to take into consideration if the user has configured the `auth.existingSecret` value. Use this value if so, otherwise use the value of the generated secret.
Correctly links to the secret when one is specified.
- fixes #24740
Is giving the ServiceAccount access to the secret even needed?

[bitnami/mongodb] Fix invalid secret pointer in MongoDB ServiceAccount

---

bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/templates/prometheus-operator/clusterrole.yaml

Add missing cluster roles
No more warnings and the operator can now publish kubernetes events
none
- fixes #24680

[bitnami/kube-prometheus] Add missing cluster roles

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/deployment.yaml

This PR adds a missing load of libfs.sh library for checking if the logs folder is empty
- fixes #

[bitnami/wordpress] fix: :bug: Load missing libfs.sh library in init container

---

template/CHART_NAME/templates/daemonset.yaml
template/CHART_NAME/templates/deployment.yaml
template/CHART_NAME/templates/networkpolicy.yaml
template/CHART_NAME/templates/statefulset.yaml
template/CHART_NAME/values.yaml

This PR adds to the chart template the security improvements, openshift adaptations & resource presets that were introduced in the catalog by @javsalgar 
New charts can be created using the template and they'll have:
- Better compliance with NSA and MITRE security checklists
- Improved compatibility with Openshift
None
None
N/A

chore: Add security improvements, openshift & resource presets to chart template

---

bitnami/phpbb/Chart.lock
bitnami/phpbb/Chart.yaml
bitnami/phpbb/README.md

Update MariaDB chart to version 18.0.0 (app version 11.3).
Use the latest MariaDB version.
- fixes #

[bitnami/phpbb] Update MariaDB to branch 11.3

---

bitnami/phpmyadmin/Chart.lock
bitnami/phpmyadmin/Chart.yaml
bitnami/phpmyadmin/README.md

Update MariaDB chart to version 18.0.0 (app version 11.3).
Use the latest MariaDB version.
- fixes #

[bitnami/phpmyadmin] Update MariaDB to branch 11.3

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/data/statefulset.yaml
bitnami/elasticsearch/templates/ingest/statefulset.yaml
bitnami/elasticsearch/templates/master/statefulset.yaml

This PR removes an unnecessary / in the `cp` operation in the copy-default-plugins init container
- fixes #

[bitnami/elasticsearch] fix: :bug: Remove / from copy-default-plugins

---

bitnami/ejbca/Chart.lock
bitnami/ejbca/Chart.yaml
bitnami/ejbca/README.md

Update MariaDB chart to version 18.0.0 (app version 11.3).
Use the latest MariaDB version.
- fixes #

[bitnami/ejbca] Update MariaDB to branch 11.3

---

bitnami/wordpress/Chart.lock
bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md

Update MariaDB chart to version 18.0.0 (app version 11.3).
Use the latest MariaDB version.
- fixes #

[bitnami/wordpress] Update MariaDB to branch 11.3

---

.vib/aspnet-core/goss/goss.yaml
.vib/aspnet-core/runtime-parameters.yaml
bitnami/aspnet-core/Chart.lock
bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/README.md
bitnami/aspnet-core/templates/NOTES.txt
bitnami/aspnet-core/templates/_helpers.tpl
bitnami/aspnet-core/templates/deployment.yaml
bitnami/aspnet-core/templates/health-ingress.yaml
bitnami/aspnet-core/templates/hpa.yaml
bitnami/aspnet-core/templates/ingress.yaml
bitnami/aspnet-core/templates/networkpolicy.yaml
bitnami/aspnet-core/templates/pdb.yaml
bitnami/aspnet-core/templates/serviceaccount.yaml
bitnami/aspnet-core/templates/svc.yaml
bitnami/aspnet-core/values.yaml

This major bump changes the following security defaults:
- `runAsUser` is changed from `0` to `1001`
- `runAsGroup` is changed from `0` to `1001`
- `readOnlyRootFilesystem` is set to `true`
- `resourcesPreset` is changed from `none` to the minimum size working in our test suites (NOTE: `resourcesPreset` is not meant for production usage, but `resources` adapted to your use case).
- `global.compatibility.openshift.adaptSecurityContext` is changed from `disabled` to `auto`.
- Network policies have been added
- Better compliance with NSA and MITRE security checklists
- Improved compatibility with Openshift
This could potentially break any customization or init scripts used in your deployment. If this is the case, …

[bitnami/aspnet-core] feat!: :lock: :boom: Improve security defaults

---

bitnami/kafka/Chart.yaml
bitnami/kafka/templates/networkpolicy.yaml

This PR adds a missing controller port in the networkpolicy
- fixes #

[bitnami/kafka] fix: :bug: Add missing controller port in networkpolicy

---

bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/templates/ruler/networkpolicy.yaml

Default chart configuration results in no ruler created, but a NetworkPolicy is created pointing to a non-existent pod.  This PR will update the NetworkPolicy to only be created if the ruler is enabled _and_ the NetworkPolicy is enabled.
No dangling NetworkPolicy will be created by a default install.
None noted
- fixes #

[bitnami/grafana-loki] Don't create NetworkPolicy for ruler if ruler is disabled

---

bitnami/consul/Chart.yaml
bitnami/consul/README.md
bitnami/consul/templates/consul-headless-service.yaml
bitnami/consul/templates/statefulset.yaml
bitnami/consul/values.yaml

This PR adds to the deployment spec the ports that were missing, such as the  WAN port. It also allows the customization of these values.
n/a
- fixes #

[bitnami/consul] fix: :bug: :lock: Expose missing ports in deployment spec

---

bitnami/rabbitmq/README.md

Add the upgrade notes for version 14.0.0 (appVersion 3.13.x).

[bitnami/rabbitmq] Add upgrade notes for version 3.13.x

---

bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md

This PR updates rabbitmq subchart to version 14.0.0 (appVersion 3.13.x).
- fixes #

[bitnami/spring-cloud-dataflow] Bump rabbitmq subchart

---

bitnami/solr/README.md

- fixes #
- [-] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.

[bitnami/solr] Adds note to solr chart for the HDFS module removal

---

bitnami/airflow/Chart.lock
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/_helpers.tpl

The change fixes a wrong call made by the helpers function to `renderSecurityContext` with `$`, that is `nil`. It has been changed to `.context`.
NA
- fixes #24568

[bitnami/airflow] Fix nil pointer evaluating when using dags.existingConfigmap"

---

bitnami/jenkins/Chart.yaml
bitnami/jenkins/templates/networkpolicy.yaml

If `agent.enabled = true`, add the agentListener port to the networkPolicy ingress.
I'm using `agent.enabled = true` to get the port 50000 enabled on the Jenkins controller container and getting the
agent-listener service created. But since port 50000 is not added to the network policy ingress, no inbound agents
can connect to the controller.
I have earlier solved it by adding an extra network policy ingress ports:
```
networkPolicy:
extraIngress:
- ports:
- port: 50000
```
but perhaps it can be added to the networkpolicy.yaml template to be done automatically when agent is enabled.
Port 50000 will have same network policy rules as port 8080/8443. Perhaps this is not a wanted position.

[bitnami/jenkins] Add agentListener port to networkPolicy ingress

---

bitnami/mariadb/Chart.yaml
bitnami/mariadb/templates/primary/statefulset.yaml
bitnami/mariadb/templates/secondary/statefulset.yaml

This PR adds the preserve-symlinks init container, in order to ensure that logs are written to stdout/stderr
- fixes #

[bitnami/mariadb] fix: :bug: Add symlinks to stdout/stderr

---

bitnami/solr/Chart.yaml

Continuation of this previous PR
https://github.com/bitnami/charts/pull/25076/files
There was a release in the same period of time and the version was not bumped correctly 
https://github.com/bitnami/charts/pull/25118/files
Changes are released

[bitnami/solr] fix: add missing metrics port to networkpolicy (cont)

---

bitnami/airflow/Chart.yaml
bitnami/airflow/templates/_git_helpers.tpl

The git repository didn't have permissions to edit the /etc/ssh folder so the initialization failed
Initialization works and repo can be cloned 
- fixes https://github.com/bitnami/charts/issues/24935

[bitnami/airflow] Fix clone of initial repositories

---

bitnami/elasticsearch/README.md

This tag was removed accidentally in https://github.com/bitnami/charts/pull/24303

[bitnami/elasticsearch] Recover Upgrading tag in the README

---

bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md

Updates dependencies of the chart to the latest new major versions.

[bitnami/mastodon] Update dependencies of the chart

---

bitnami/magento/Chart.lock
bitnami/magento/Chart.yaml
bitnami/magento/README.md

Updates dependencies of the chart to the latest new major versions.

[bitnami/magento] Update dependencies of the chart

---

bitnami/consul/Chart.yaml

Bump chart version to force a new release.
Fix error on previous release
None
- fixes https://github.com/bitnami/charts/actions/runs/8799380377/job/24150050695

[bitnami/consul] Bump consul version to force release

---

bitnami/supabase/Chart.yaml
bitnami/supabase/templates/realtime/deployment.yaml

Set the missing environment variables for postgres configuration in supabase-realtime
- fixes #25104

[bitnami/supabase] Fixes realtime externaldb configuration

---

bitnami/minio/Chart.yaml
bitnami/minio/templates/tls-secrets.yaml

This PR fixes an incorrect context in the tls-secret.yaml file. As the section is inside `range`, the context needs to be changed to `$` rather than `.`.
- fixes #

[bitnami/minio] fix: :bug: Set correct context in tls-secret

---

.github/workflows/license-headers.yml
bitnami/kafka/templates/broker/hpa.yaml
bitnami/kafka/templates/broker/vpa.yaml
bitnami/kafka/templates/controller-eligible/hpa.yaml
bitnami/kafka/templates/controller-eligible/vpa.yaml
bitnami/metallb/templates/speaker/configmap.yaml
bitnami/metallb/templates/speaker/service-frr.yaml
bitnami/metallb/templates/speaker/servicemonitor-frr.yaml
bitnami/moodle/templates/hpa.yaml

Update license headers on some manifests that were missing the update..
None
None
N/A
N/A

[bitnami/*] Fix license headers

---

.vib/janusgraph/goss/goss.yaml
.vib/janusgraph/vib-publish.json
bitnami/janusgraph/Chart.yaml
bitnami/janusgraph/templates/configmap.yaml
bitnami/janusgraph/templates/deployment.yaml
bitnami/janusgraph/templates/extra-list.yaml
bitnami/janusgraph/templates/hpa.yaml
bitnami/janusgraph/templates/metrics/configmap.yaml
bitnami/janusgraph/templates/metrics/service.yaml
bitnami/janusgraph/templates/metrics/servicemonitor.yaml
bitnami/janusgraph/templates/networkpolicy.yaml
bitnami/janusgraph/templates/pdb.yaml
bitnami/janusgraph/templates/pvc.yaml
bitnami/janusgraph/templates/service-account.yaml
bitnami/janusgraph/templates/service.yaml
bitnami/janusgraph/templates/vpa.yaml
bitnami/janusgraph/values.yaml

Adds `authn.role` in vib-publish.json

[bitnami/janusgraph] Add vib-publish role

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/storegateway/statefulset-sharded.yaml

- Corrects the storegateway args to use updated indexCache and bucketCache paths to match the previously updated volume mounts
- Note: bringing storegateway statefulset-sharded to parity with the currently working storegateway statefulset configs
- Corrected support for indexCache & bucketCache with sharded storegateways
- N/A

[bitnami/thanos] correct storegateway statefulset-sharded cache config args

---

bitnami/metallb/Chart.yaml
bitnami/metallb/templates/speaker/daemonset.yaml

The FRR mode was not working proper due to missing configuration environment variables in the speaker. Also FRR user needed to be change so config reload could be triggered.
- fixes #

[bitnami/metallb] Fixes for FRR mode

---

bitnami/vault/Chart.yaml
bitnami/vault/README.md
bitnami/vault/templates/server/statefulset.yaml
bitnami/vault/values.yaml

Added support for vault Oracle plugin
Additional mount path and volume claim template is added for vault oracle plugin support
- The Oracle database plugin is not bundled in the core Vault code tree and can be found at its own git repository here: [hashicorp/vault-plugin-database-oracle](https://github.com/hashicorp/vault-plugin-database-oracle)
- When vault oracle plugin is registered ,vault internally writes into a directory "/tmp" for which an external persistenance storage volume is needed.
- vault oracle plugin is not supported by vault opensource edition, so this will help to enable oracle database secret engine for dynamic secrets engine.
N/A
NA
- This change only works with  custom image with plugin binary installed.
- For linux/amd64, pre-built binaries can be found at [the …

[bitnami/vault]  Add support for vault oracle plugin persistence storage 

---

.vib/mlflow/goss/goss.yaml

Increase timeout for `http` tests.
Tests succeed in all platforms.
Not expected

[bitnami/mlflow] Set timeout for Goss http tests

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/deployment.yaml

Fix [[bitnami/nginx] deployment fail because of OpenShift restricted-v2](https://github.com/bitnami/charts/issues/25425#top) 
Deployment to OpenShit with restricted-v2 policy will not fail because of initContainer with missing podSecurityContext
None AFAIK.
- fixes #

[bitnami/nginx] deployment fail because of OpenShift restricted-v2 issue 25425

---

bitnami/clickhouse/README.md

If using Clickhouse keeper instead of Zookeeper, Zookeeper settings should be ignore.
https://github.com/bitnami/charts/blob/0f95fcf8900f8e4a884b884df5cdc1767946dc15/bitnami/clickhouse/values.yaml#L338-L348
N/A
N/A
N/A
N/A

[bitnami/clickhouse] Correct description of keeper section

---

bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/templates/controller/pdb.yaml
bitnami/argo-workflows/templates/server/pdb.yaml

[bitnami/argo-workflows] PDB review

---

.github/workflows/archive-full-index.yml
.github/workflows/sync-chart-index.yml

Undo workflow movement done in https://github.com/bitnami/charts/pull/25712
Workflows continue working as expected
Workflows didn't run when there was a change in the index branch 

Undo workflow movement in #25712

---

bitnami/apache/Chart.yaml
bitnami/apache/templates/pdb.yaml

[bitnami/apache] PDB review

---

.github/workflows/archive-full-index.yml

Moving these changes to production 
https://github.com/bitnami/charts/pull/25712
https://github.com/bitnami/charts/pull/25883
Repo size is reduced
None AFAIK
- [Na] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.

Reduce archive-full-index branch size by squashing all commits

---

.github/workflows/archive-full-index.yml

Fixing git-related issues after applying this other PR
https://github.com/bitnami/charts/pull/25889
- fixes https://github.com/bitnami/charts/pull/25889

Move git config lines to the beginning of the archive-full-index action

---

.github/workflows/cd-pipeline.yml

Moving these changes to production 
https://github.com/bitnami/charts/pull/25712
Repo size is reduced
None AFAIK
- [Na] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.

Reduce index branch size by squashing all commits

---

.github/workflows/archive-full-index.yml

This logic helps us avoid issues when pushing a shorter file to the index branch
Only files with more data will be pushed
Related to this other PR https://github.com/bitnami/charts/pull/25889

Avoid pushing a shorter index.yaml file to the archive-full-index branch

---

bitnami/apache/Chart.yaml
bitnami/apache/templates/pdb.yaml

Reverts #25862
Remove unnecessary conditions.
- reverts #25862

[bitnami/apache] Reverts #25862

---

.github/workflows/cd-pipeline.yml

This logic helps us avoid issues when pushing a non-valid file to the index branch
Only valid files will be pushed
Related to this other PR https://github.com/bitnami/charts/pull/25913

Add temporary index.yaml file to helm to confirm it's a valid file

---

bitnami/etcd/Chart.yaml
bitnami/etcd/templates/pdb.yaml

This reverts #25896
Conditions added in that PR are not needed.
- reverts #25896

[bitnami/etcd] Revert #25896

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/_helpers.tpl

Fixes the rendering of: `mongodb.initContainer.volumePermissions`
- fixes #25682

[bitnami/mongodb] Fix volumePermissions rendering

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/pdb.yaml

Reverts #25867
- Reverts #25867

[bitnami/apache] Reverts #25867

---

bitnami/grafana/README.md

Mention the changes introduced here: https://github.com/bitnami/charts/pull/26137
Continuation of https://github.com/bitnami/charts/pull/26137

[bitnami/grafana] Update README with the latest major version

---

.github/workflows/ci-pipeline.yml

[bitnami/*] ci: :construction_worker: Allow updating changelog when using a fork

---

bitnami/deepspeed/CHANGELOG.md
bitnami/deepspeed/Chart.lock
bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/templates/NOTES.txt

[bitnami/deepspeed] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/discourse/CHANGELOG.md
bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml
bitnami/discourse/templates/NOTES.txt

[bitnami/discourse] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/fluentd/CHANGELOG.md
bitnami/fluentd/Chart.lock
bitnami/fluentd/Chart.yaml
bitnami/fluentd/templates/NOTES.txt

[bitnami/fluentd] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/gitea/CHANGELOG.md
bitnami/gitea/Chart.lock
bitnami/gitea/Chart.yaml
bitnami/gitea/templates/NOTES.txt

[bitnami/gitea] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/grafana-mimir/CHANGELOG.md
bitnami/grafana-mimir/Chart.lock
bitnami/grafana-mimir/Chart.yaml
bitnami/grafana-mimir/templates/NOTES.txt

[bitnami/grafana-mimir] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/grafana-tempo/CHANGELOG.md
bitnami/grafana-tempo/Chart.lock
bitnami/grafana-tempo/Chart.yaml
bitnami/grafana-tempo/templates/NOTES.txt

[bitnami/grafana-tempo] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/kong/CHANGELOG.md
bitnami/kong/Chart.lock
bitnami/kong/Chart.yaml
bitnami/kong/templates/NOTES.txt

[bitnami/kong] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml
bitnami/mastodon/templates/NOTES.txt

[bitnami/mastodon] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/nats/CHANGELOG.md
bitnami/nats/Chart.lock
bitnami/nats/Chart.yaml
bitnami/nats/templates/NOTES.txt

[bitnami/nats] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/prometheus/CHANGELOG.md
bitnami/prometheus/Chart.lock
bitnami/prometheus/Chart.yaml
bitnami/prometheus/templates/NOTES.txt

[bitnami/prometheus] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/supabase/CHANGELOG.md
bitnami/supabase/Chart.lock
bitnami/supabase/Chart.yaml
bitnami/supabase/templates/NOTES.txt

[bitnami/supabase] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/wildfly/CHANGELOG.md
bitnami/wildfly/Chart.lock
bitnami/wildfly/Chart.yaml
bitnami/wildfly/templates/NOTES.txt

[bitnami/wildfly] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/whereabouts/CHANGELOG.md
bitnami/whereabouts/Chart.lock
bitnami/whereabouts/Chart.yaml
bitnami/whereabouts/templates/NOTES.txt

[bitnami/whereabouts] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/tensorflow-resnet/CHANGELOG.md
bitnami/tensorflow-resnet/Chart.lock
bitnami/tensorflow-resnet/Chart.yaml
bitnami/tensorflow-resnet/templates/NOTES.txt

[bitnami/tensorflow-resnet] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/templates/NOTES.txt

[bitnami/spring-cloud-dataflow] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/sonarqube/CHANGELOG.md
bitnami/sonarqube/Chart.lock
bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/templates/NOTES.txt

[bitnami/sonarqube] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/solr/CHANGELOG.md
bitnami/solr/Chart.lock
bitnami/solr/Chart.yaml
bitnami/solr/templates/NOTES.txt

[bitnami/solr] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/sealed-secrets/CHANGELOG.md
bitnami/sealed-secrets/Chart.lock
bitnami/sealed-secrets/Chart.yaml
bitnami/sealed-secrets/templates/NOTES.txt

[bitnami/sealed-secrets] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/redmine/CHANGELOG.md
bitnami/redmine/Chart.lock
bitnami/redmine/Chart.yaml
bitnami/redmine/templates/NOTES.txt

[bitnami/redmine] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/redis-cluster/CHANGELOG.md
bitnami/redis-cluster/Chart.lock
bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/NOTES.txt

[bitnami/redis-cluster] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/rabbitmq-cluster-operator/CHANGELOG.md
bitnami/rabbitmq-cluster-operator/Chart.lock
bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/templates/NOTES.txt

[bitnami/rabbitmq-cluster-operator] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/prestashop/CHANGELOG.md
bitnami/prestashop/Chart.lock
bitnami/prestashop/Chart.yaml
bitnami/prestashop/templates/NOTES.txt

[bitnami/prestashop] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/postgresql-ha/CHANGELOG.md
bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/templates/NOTES.txt

[bitnami/postgresql-ha] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/pinniped/CHANGELOG.md
bitnami/pinniped/Chart.lock
bitnami/pinniped/Chart.yaml
bitnami/pinniped/templates/NOTES.txt

[bitnami/pinniped] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/phpmyadmin/CHANGELOG.md
bitnami/phpmyadmin/Chart.lock
bitnami/phpmyadmin/Chart.yaml
bitnami/phpmyadmin/templates/NOTES.txt

[bitnami/phpmyadmin] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/phpbb/CHANGELOG.md
bitnami/phpbb/Chart.lock
bitnami/phpbb/Chart.yaml
bitnami/phpbb/templates/NOTES.txt

[bitnami/phpbb] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/parse/CHANGELOG.md
bitnami/parse/Chart.lock
bitnami/parse/Chart.yaml
bitnami/parse/templates/NOTES.txt

[bitnami/parse] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/opensearch/CHANGELOG.md
bitnami/opensearch/Chart.yaml
bitnami/opensearch/templates/NOTES.txt

[bitnami/opensearch] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/opencart/CHANGELOG.md
bitnami/opencart/Chart.lock
bitnami/opencart/Chart.yaml
bitnami/opencart/templates/NOTES.txt

[bitnami/opencart] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/odoo/CHANGELOG.md
bitnami/odoo/Chart.lock
bitnami/odoo/Chart.yaml
bitnami/odoo/templates/NOTES.txt

[bitnami/odoo] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/oauth2-proxy/CHANGELOG.md
bitnami/oauth2-proxy/Chart.lock
bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/templates/NOTES.txt

[bitnami/oauth2-proxy] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/node-exporter/CHANGELOG.md
bitnami/node-exporter/Chart.yaml
bitnami/node-exporter/templates/NOTES.txt

[bitnami/node-exporter] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/nginx-ingress-controller/CHANGELOG.md
bitnami/nginx-ingress-controller/Chart.lock
bitnami/nginx-ingress-controller/Chart.yaml
bitnami/nginx-ingress-controller/templates/NOTES.txt

[bitnami/nginx-ingress-controller] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/nginx/CHANGELOG.md
bitnami/nginx/Chart.lock
bitnami/nginx/Chart.yaml
bitnami/nginx/templates/NOTES.txt

[bitnami/nginx] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/multus-cni/CHANGELOG.md
bitnami/multus-cni/Chart.lock
bitnami/multus-cni/Chart.yaml
bitnami/multus-cni/templates/NOTES.txt

[bitnami/multus-cni] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/moodle/CHANGELOG.md
bitnami/moodle/Chart.lock
bitnami/moodle/Chart.yaml
bitnami/moodle/templates/NOTES.txt

[bitnami/moodle] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/mongodb-sharded/CHANGELOG.md
bitnami/mongodb-sharded/Chart.lock
bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/NOTES.txt

[bitnami/mongodb-sharded] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.lock
bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/NOTES.txt

[bitnami/mongodb] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.lock
bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/NOTES.txt

[bitnami/mlflow] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/minio/CHANGELOG.md
bitnami/minio/Chart.lock
bitnami/minio/Chart.yaml
bitnami/minio/templates/NOTES.txt

[bitnami/minio] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/metrics-server/CHANGELOG.md
bitnami/metrics-server/Chart.lock
bitnami/metrics-server/Chart.yaml
bitnami/metrics-server/templates/NOTES.txt

[bitnami/metrics-server] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/memcached/CHANGELOG.md
bitnami/memcached/Chart.lock
bitnami/memcached/Chart.yaml
bitnami/memcached/templates/NOTES.txt

[bitnami/memcached] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/matomo/CHANGELOG.md
bitnami/matomo/Chart.lock
bitnami/matomo/Chart.yaml
bitnami/matomo/templates/NOTES.txt

[bitnami/matomo] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/mariadb/CHANGELOG.md
bitnami/mariadb/Chart.lock
bitnami/mariadb/Chart.yaml
bitnami/mariadb/templates/NOTES.txt

[bitnami/mariadb] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/magento/CHANGELOG.md
bitnami/magento/Chart.lock
bitnami/magento/Chart.yaml
bitnami/magento/templates/NOTES.txt

[bitnami/magento] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/logstash/CHANGELOG.md
bitnami/logstash/Chart.lock
bitnami/logstash/Chart.yaml
bitnami/logstash/templates/NOTES.txt

[bitnami/logstash] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/kuberay/CHANGELOG.md
bitnami/kuberay/Chart.lock
bitnami/kuberay/Chart.yaml
bitnami/kuberay/templates/NOTES.txt

[bitnami/kuberay] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/kubeapps/CHANGELOG.md
bitnami/kubeapps/Chart.lock
bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/templates/NOTES.txt

[bitnami/kubeapps] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/kube-state-metrics/CHANGELOG.md
bitnami/kube-state-metrics/Chart.lock
bitnami/kube-state-metrics/Chart.yaml
bitnami/kube-state-metrics/templates/NOTES.txt

[bitnami/kube-state-metrics] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/kibana/CHANGELOG.md
bitnami/kibana/Chart.lock
bitnami/kibana/Chart.yaml
bitnami/kibana/templates/NOTES.txt

[bitnami/kibana] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/kiam/CHANGELOG.md
bitnami/kiam/Chart.lock
bitnami/kiam/Chart.yaml
bitnami/kiam/templates/NOTES.txt

[bitnami/kiam] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.lock
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/NOTES.txt

[bitnami/keycloak] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/jupyterhub/CHANGELOG.md
bitnami/jupyterhub/Chart.lock
bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/templates/NOTES.txt

[bitnami/jupyterhub] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/jenkins/CHANGELOG.md
bitnami/jenkins/Chart.lock
bitnami/jenkins/Chart.yaml
bitnami/jenkins/templates/NOTES.txt

[bitnami/jenkins] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/influxdb/CHANGELOG.md
bitnami/influxdb/Chart.lock
bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/NOTES.txt

[bitnami/influxdb] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.lock
bitnami/harbor/Chart.yaml
bitnami/harbor/templates/NOTES.txt

[bitnami/harbor] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/grafana-operator/CHANGELOG.md
bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/templates/NOTES.txt

[bitnami/grafana-operator] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/grafana-loki/CHANGELOG.md
bitnami/grafana-loki/Chart.lock
bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/templates/NOTES.txt

[bitnami/grafana-loki] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/grafana/CHANGELOG.md
bitnami/grafana/Chart.lock
bitnami/grafana/Chart.yaml
bitnami/grafana/templates/NOTES.txt

[bitnami/grafana] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/ghost/CHANGELOG.md
bitnami/ghost/Chart.lock
bitnami/ghost/Chart.yaml
bitnami/ghost/templates/NOTES.txt

[bitnami/ghost] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/fluent-bit/CHANGELOG.md
bitnami/fluent-bit/Chart.yaml
bitnami/fluent-bit/templates/NOTES.txt

[bitnami/fluent-bit] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/external-dns/CHANGELOG.md
bitnami/external-dns/Chart.lock
bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/NOTES.txt

[bitnami/external-dns] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/elasticsearch/CHANGELOG.md
bitnami/elasticsearch/Chart.lock
bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/NOTES.txt

[bitnami/elasticsearch] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/ejbca/CHANGELOG.md
bitnami/ejbca/Chart.lock
bitnami/ejbca/Chart.yaml
bitnami/ejbca/templates/NOTES.txt

[bitnami/ejbca] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/drupal/CHANGELOG.md
bitnami/drupal/Chart.lock
bitnami/drupal/Chart.yaml
bitnami/drupal/templates/NOTES.txt

[bitnami/drupal] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/dokuwiki/CHANGELOG.md
bitnami/dokuwiki/Chart.lock
bitnami/dokuwiki/Chart.yaml
bitnami/dokuwiki/templates/NOTES.txt

[bitnami/dokuwiki] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/contour/CHANGELOG.md
bitnami/contour/Chart.lock
bitnami/contour/Chart.yaml
bitnami/contour/templates/NOTES.txt

[bitnami/contour] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/consul/CHANGELOG.md
bitnami/consul/Chart.lock
bitnami/consul/Chart.yaml
bitnami/consul/templates/NOTES.txt

[bitnami/consul] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/concourse/CHANGELOG.md
bitnami/concourse/Chart.lock
bitnami/concourse/Chart.yaml
bitnami/concourse/templates/NOTES.txt

[bitnami/concourse] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/clickhouse/CHANGELOG.md
bitnami/clickhouse/Chart.lock
bitnami/clickhouse/Chart.yaml
bitnami/clickhouse/templates/NOTES.txt

[bitnami/clickhouse] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/cert-manager/CHANGELOG.md
bitnami/cert-manager/Chart.lock
bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/templates/NOTES.txt

[bitnami/cert-manager] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/cassandra/CHANGELOG.md
bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/NOTES.txt

[bitnami/cassandra] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/aspnet-core/CHANGELOG.md
bitnami/aspnet-core/Chart.lock
bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/templates/NOTES.txt

[bitnami/aspnet-core] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/argo-workflows/CHANGELOG.md
bitnami/argo-workflows/Chart.lock
bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/templates/NOTES.txt

[bitnami/argo-workflows] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/appsmith/CHANGELOG.md
bitnami/appsmith/Chart.lock
bitnami/appsmith/Chart.yaml
bitnami/appsmith/templates/NOTES.txt

[bitnami/appsmith] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/wordpress/CHANGELOG.md
bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/NOTES.txt

[bitnami/wordpress] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/kubernetes-event-exporter/CHANGELOG.md
bitnami/kubernetes-event-exporter/Chart.lock
bitnami/kubernetes-event-exporter/Chart.yaml
bitnami/kubernetes-event-exporter/templates/NOTES.txt

[bitnami/kubernetes-event-exporter] feat: :sparkles: :lock: Add warning when original images are replaced

---

.github/workflows/ci-pipeline.yml

Some of the changelog commit links were broken because the conventional-changelogs-cli tool uses short sha's instead of long sha. For some reason, Github links with short sha do not work for all commits. This PR changes all changelog links to use the long sha instead, which is proved to always work.
- fixes #

[bitnami/*] ci: :construction_worker: Fix broken commit links in changelogs

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/_helpers.tpl

Allow templating for config map scripts
for instance: 
```yaml
mongodb:
initdbScriptsConfigMap: '{{ include "common.names.fullname" $ }}-configmap'
```
- fixes #25966

[bitnami/mongodb] Allow templating for initdbScriptsConfigMap

---

bitnami/argo-workflows/CHANGELOG.md
bitnami/argo-workflows/Chart.lock
bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/templates/server/deployment.yaml

[bitnami/argo-workflows] Use different liveness/readiness probes

---

template/CHART_NAME/templates/NOTES.txt

[bitnami/template] feat: :sparkles: :lock: Include modified images check

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/NOTES.txt

… 
This PR fixes a regression introduced in https://github.com/bitnami/charts/pull/26182 where it was checking a non-existent image. It was accidentally merged even though it did not pass the verification
- fixes #

[bitnami/argo-cd] fix: :bug: :ambulance: Remove non-existent image in replacedImages check

---

.vib/jupyterhub/cypress/cypress/e2e/jupyterhub.cy.js

Includes all the steps for each of the tests in one session.
This helps when handling xsrf situations.
- fixes #

[bitnami/jupyterhub] Fixes jupyterhub testing

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.yaml
bitnami/etcd/templates/statefulset.yaml

Add `scheme` to the liveness probe to support it when TLS is enabled
- fixes #
- ~[ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)~

[bitnami/etcd] Fix livenessProbe for ETCD with TLS

---

bitnami/milvus/CHANGELOG.md
bitnami/milvus/Chart.lock
bitnami/milvus/Chart.yaml
bitnami/milvus/README.md

Update dependencies after a subchart major change
- fixes #

[bitnami/milvus] Update dependencies

---

bitnami/ghost/CHANGELOG.md
bitnami/ghost/Chart.lock
bitnami/ghost/Chart.yaml
bitnami/ghost/README.md

Updates mysql dependency to 11.0.0
- fixes #

[bitnami/ghost] Update dependencies

---

.vib/seaweedfs/ginkgo/seaweedfs_suite_test.go

Remove security context configuration from the testing job to allow it to run on Openshift.

[bitnami/seaweedfs] Fix tests

---

.vib/kubeapps/cypress/cypress/e2e/kubeapps.cy.js
.vib/kubeapps/cypress/cypress/fixtures/releases.json

I changed the test to click on one of cards the appears at the beginning (apache) instead of using the search. 
For the search to work needs to end the indexing and this takes a while when using the Bitnami catalog.
- fixes #

[bitnami/kubeapps] Change the kubeapps test to apache

---

bitnami/janusgraph/CHANGELOG.md
bitnami/janusgraph/Chart.yaml

Adds the chart repository to the sources list of the janusgraph chart.
Allows tools (e.g. Renovate) to discover the new Changelogs
- fixes #

[bitnami/janusgraph] Add chart source URL to sources list

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.yaml

Adds the chart repository to the sources list of the mlflow chart.
Allows tools (e.g. Renovate) to discover the new Changelogs
- fixes #

[bitnami/mlflow] Add chart source URL to sources list

---

.vib/seaweedfs/ginkgo/seaweedfs_suite_test.go

Reverts bitnami/charts#26400 due to fails in the testing.
- fixes #

[bitnami/seaweedfs] Revert Fix tests 

---

bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.yaml

Adds the chart repository to the sources list of the seaweeds chart.
Allows tools (e.g. Renovate) to discover the new Changelogs
- fixes #

[bitnami/seaweedfs] Add chart source URL to sources list

---

bitnami/influxdb/README.md

Describes how to trigger the data migration process from InfluxDB 1.x into 2.x.

[bitnami/influxdb] Update docs

---

template/CHART_NAME/templates/daemonset.yaml
template/CHART_NAME/templates/deployment.yaml
template/CHART_NAME/templates/hpa.yaml
template/CHART_NAME/templates/networkpolicy.yaml
template/CHART_NAME/templates/pdb.yaml
template/CHART_NAME/templates/statefulset.yaml
template/CHART_NAME/templates/vpa.yaml
template/CHART_NAME/values.yaml

This PR updates the chart template with missing common parameters that we recently added to new charts.
New charts don't miss common parameters
None
N/A
N/A

chore: update template with missing common parameters

---

bitnami/wordpress/CHANGELOG.md
bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/deployment.yaml

Fix typo in deployment.yaml template. 
None that I'm aware of.
- fixes #26133

[bitnami/wordpress] Fix issue #26133

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/NOTES.txt

Signed-off-by: Thatcher Peskens <thatcher@t2studio.nl>
removes the run.source.git string from image changed security warning in notes.txt
This string would always cause an "image changed warning" to be triggered because this git thing is not a path to an image.
n.a.
- fixes #26471

[bitnami/mlflow] fix always image warning

---

bitnami/apache/CHANGELOG.md
bitnami/apache/Chart.yaml

[bitnami/apache] Bump chart version

---

bitnami/aspnet-core/CHANGELOG.md
bitnami/aspnet-core/Chart.yaml

[bitnami/aspnet-core] Bump chart version

---

bitnami/cassandra/CHANGELOG.md
bitnami/cassandra/Chart.yaml

[bitnami/cassandra] Bump chart version

---

bitnami/cert-manager/CHANGELOG.md
bitnami/cert-manager/Chart.yaml

[bitnami/cert-manager] Bump chart version

---

bitnami/consul/CHANGELOG.md
bitnami/consul/Chart.yaml

[bitnami/consul] Bump chart version

---

bitnami/contour/CHANGELOG.md
bitnami/contour/Chart.yaml

[bitnami/contour] Bump chart version

---

bitnami/deepspeed/CHANGELOG.md
bitnami/deepspeed/Chart.yaml

[bitnami/deepspeed] Bump chart version

---

bitnami/dokuwiki/CHANGELOG.md
bitnami/dokuwiki/Chart.yaml

[bitnami/dokuwiki] Bump chart version

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.yaml

[bitnami/etcd] Bump chart version

---

bitnami/external-dns/CHANGELOG.md
bitnami/external-dns/Chart.yaml

[bitnami/external-dns] Bump chart version

---

bitnami/flink/CHANGELOG.md
bitnami/flink/Chart.yaml

[bitnami/flink] Bump chart version

---

bitnami/fluent-bit/CHANGELOG.md
bitnami/fluent-bit/Chart.yaml

[bitnami/fluent-bit] Bump chart version

---

bitnami/flux/CHANGELOG.md
bitnami/flux/Chart.yaml

[bitnami/flux] Bump chart version

---

bitnami/grafana/CHANGELOG.md
bitnami/grafana/Chart.yaml

[bitnami/grafana] Bump chart version

---

bitnami/grafana-operator/CHANGELOG.md
bitnami/grafana-operator/Chart.yaml

[bitnami/grafana-operator] Bump chart version

---

bitnami/haproxy/CHANGELOG.md
bitnami/haproxy/Chart.yaml

[bitnami/haproxy] Bump chart version

---

bitnami/influxdb/CHANGELOG.md
bitnami/influxdb/Chart.yaml

[bitnami/influxdb] Bump chart version

---

bitnami/jenkins/CHANGELOG.md
bitnami/jenkins/Chart.yaml

[bitnami/jenkins] Bump chart version

---

bitnami/kiam/CHANGELOG.md
bitnami/kiam/Chart.yaml

[bitnami/kiam] Bump chart version

---

bitnami/kibana/CHANGELOG.md
bitnami/kibana/Chart.yaml

[bitnami/kibana] Bump chart version

---

bitnami/kube-state-metrics/CHANGELOG.md
bitnami/kube-state-metrics/Chart.yaml

[bitnami/kube-state-metrics] Bump chart version

---

bitnami/kuberay/CHANGELOG.md
bitnami/kuberay/Chart.yaml

[bitnami/kuberay] Bump chart version

---

bitnami/kubernetes-event-exporter/CHANGELOG.md
bitnami/kubernetes-event-exporter/Chart.yaml

[bitnami/kubernetes-event-exporter] Bump chart version

---

bitnami/logstash/CHANGELOG.md
bitnami/logstash/Chart.yaml

[bitnami/logstash] Bump chart version

---

bitnami/mariadb/CHANGELOG.md
bitnami/mariadb/Chart.yaml

[bitnami/mariadb] Bump chart version

---

bitnami/mariadb-galera/CHANGELOG.md
bitnami/mariadb-galera/Chart.yaml

[bitnami/mariadb-galera] Bump chart version

---

bitnami/memcached/CHANGELOG.md
bitnami/memcached/Chart.yaml

[bitnami/memcached] Bump chart version

---

bitnami/metallb/CHANGELOG.md
bitnami/metallb/Chart.yaml

[bitnami/metallb] Bump chart version

---

bitnami/metrics-server/CHANGELOG.md
bitnami/metrics-server/Chart.yaml

[bitnami/metrics-server] Bump chart version

---

bitnami/minio/CHANGELOG.md
bitnami/minio/Chart.yaml

[bitnami/minio] Bump chart version

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.yaml

[bitnami/mongodb] Bump chart version

---

bitnami/mongodb-sharded/CHANGELOG.md
bitnami/mongodb-sharded/Chart.yaml

[bitnami/mongodb-sharded] Bump chart version

---

bitnami/multus-cni/CHANGELOG.md
bitnami/multus-cni/Chart.yaml

[bitnami/multus-cni] Bump chart version

---

bitnami/mysql/CHANGELOG.md
bitnami/mysql/Chart.yaml

[bitnami/mysql] Bump chart version

---

bitnami/nats/CHANGELOG.md
bitnami/nats/Chart.yaml

[bitnami/nats] Bump chart version

---

bitnami/nginx/CHANGELOG.md
bitnami/nginx/Chart.yaml

[bitnami/nginx] Bump chart version

---

bitnami/nginx-ingress-controller/CHANGELOG.md
bitnami/nginx-ingress-controller/Chart.yaml

[bitnami/nginx-ingress-controller] Bump chart version

---

bitnami/node-exporter/CHANGELOG.md
bitnami/node-exporter/Chart.yaml

[bitnami/node-exporter] Bump chart version

---

bitnami/opensearch/CHANGELOG.md
bitnami/opensearch/Chart.yaml

[bitnami/opensearch] Bump chart version

---

bitnami/pinniped/CHANGELOG.md
bitnami/pinniped/Chart.yaml

[bitnami/pinniped] Bump chart version

---

bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.yaml

[bitnami/postgresql] Bump chart version

---

bitnami/prometheus/CHANGELOG.md
bitnami/prometheus/Chart.yaml

[bitnami/prometheus] Bump chart version

---

bitnami/pytorch/CHANGELOG.md
bitnami/pytorch/Chart.yaml

[bitnami/pytorch] Bump chart version

---

bitnami/rabbitmq/CHANGELOG.md
bitnami/rabbitmq/Chart.yaml

[bitnami/rabbitmq] Bump chart version

---

bitnami/rabbitmq-cluster-operator/CHANGELOG.md
bitnami/rabbitmq-cluster-operator/Chart.yaml

[bitnami/rabbitmq-cluster-operator] Bump chart version

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml

[bitnami/redis] Bump chart version

---

bitnami/redis-cluster/CHANGELOG.md
bitnami/redis-cluster/Chart.yaml

[bitnami/redis-cluster] Bump chart version

---

bitnami/spark/CHANGELOG.md
bitnami/spark/Chart.yaml

[bitnami/spark] Bump chart version

---

bitnami/tensorflow-resnet/CHANGELOG.md
bitnami/tensorflow-resnet/Chart.yaml

[bitnami/tensorflow-resnet] Bump chart version

---

bitnami/tomcat/CHANGELOG.md
bitnami/tomcat/Chart.yaml

[bitnami/tomcat] Bump chart version

---

bitnami/vault/CHANGELOG.md
bitnami/vault/Chart.yaml

[bitnami/vault] Bump chart version

---

bitnami/whereabouts/CHANGELOG.md
bitnami/whereabouts/Chart.yaml

[bitnami/whereabouts] Bump chart version

---

bitnami/zookeeper/CHANGELOG.md
bitnami/zookeeper/Chart.yaml

[bitnami/zookeeper] Bump chart version

---

bitnami/phpbb/CHANGELOG.md
bitnami/phpbb/Chart.yaml
bitnami/phpbb/templates/deployment.yaml

Fix typo in deployment.yaml template file.
Fix typo.
None.
N/A
N/A

[bitnami/phpbb] Fix typo in deployment.yaml template

---

bitnami/drupal/CHANGELOG.md
bitnami/drupal/Chart.yaml
bitnami/drupal/templates/deployment.yaml

Fix typo in deployment.yaml template.
Fix typo.
None.
N/A
N/A

[bitnami/drupal] Fix typo in deployment.yaml template

---

bitnami/nessie/CHANGELOG.md
bitnami/nessie/Chart.yaml
bitnami/nessie/README.md

This PR sets the correct metadata `app-name` in the README.md. This avoids incorrect autogenerated PRs like this one https://github.com/bitnami/charts/pull/26683
- fixes #

[bitnami/nessie] fix: :bug: Set correct README.md metadata

---

bitnami/opencart/CHANGELOG.md
bitnami/opencart/Chart.yaml
bitnami/opencart/templates/deployment.yaml

Fix typo in deployment.yaml template.
Fix typo.
None.
N/A
N/A

[bitnami/opencart] Fix typo in deployment.yaml template

---

bitnami/wordpress/Chart.yaml

[bitnami/wordpress] Bump chart version

---

bitnami/valkey/CHANGELOG.md
bitnami/valkey/Chart.yaml

[bitnami/valkey] Bump chart version

---

bitnami/thanos/CHANGELOG.md
bitnami/thanos/Chart.yaml

[bitnami/thanos] Bump chart version

---

bitnami/supabase/CHANGELOG.md
bitnami/supabase/Chart.yaml

[bitnami/supabase] Bump chart version

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.yaml

[bitnami/spring-cloud-dataflow] Bump chart version

---

bitnami/sonarqube/Chart.yaml

[bitnami/sonarqube] Bump chart version

---

bitnami/solr/Chart.yaml

[bitnami/solr] Bump chart version

---

bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.yaml

[bitnami/seaweedfs] Bump chart version

---

bitnami/scylladb/CHANGELOG.md
bitnami/scylladb/Chart.yaml

[bitnami/scylladb] Bump chart version

---

bitnami/redmine/Chart.yaml

[bitnami/redmine] Bump chart version

---

bitnami/kube-prometheus/Chart.yaml

[bitnami/kube-prometheus] Bump chart version

---

bitnami/phpmyadmin/CHANGELOG.md
bitnami/phpmyadmin/Chart.yaml

[bitnami/phpmyadmin] Bump chart version

---

bitnami/phpbb/CHANGELOG.md
bitnami/phpbb/Chart.yaml

[bitnami/phpbb] Bump chart version

---

bitnami/opencart/CHANGELOG.md
bitnami/opencart/Chart.yaml

[bitnami/opencart] Bump chart version

---

bitnami/odoo/CHANGELOG.md
bitnami/odoo/Chart.yaml

[bitnami/odoo] Bump chart version

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.yaml

[bitnami/mlflow] Bump chart version

---

bitnami/milvus/CHANGELOG.md
bitnami/milvus/Chart.yaml

[bitnami/milvus] Bump chart version

---

bitnami/mediawiki/CHANGELOG.md
bitnami/mediawiki/Chart.yaml

[bitnami/mediawiki] Bump chart version

---

bitnami/matomo/CHANGELOG.md
bitnami/matomo/Chart.yaml

[bitnami/matomo] Bump chart version

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.yaml

[bitnami/mastodon] Bump chart version

---

bitnami/magento/CHANGELOG.md
bitnami/magento/Chart.yaml

[bitnami/magento] Bump chart version

---

bitnami/kubeapps/CHANGELOG.md
bitnami/kubeapps/Chart.yaml

[bitnami/kubeapps] Bump chart version

---

bitnami/kong/CHANGELOG.md
bitnami/kong/Chart.yaml

[bitnami/kong] Bump chart version

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml

[bitnami/keycloak] Bump chart version

---

bitnami/kafka/CHANGELOG.md
bitnami/kafka/Chart.yaml

[bitnami/kafka] Bump chart version

---

bitnami/jupyterhub/CHANGELOG.md
bitnami/jupyterhub/Chart.yaml

[bitnami/jupyterhub] Bump chart version

---

bitnami/janusgraph/CHANGELOG.md
bitnami/janusgraph/Chart.yaml

[bitnami/janusgraph] Bump chart version

---

bitnami/jaeger/CHANGELOG.md
bitnami/jaeger/Chart.yaml

[bitnami/jaeger] Bump chart version

---

bitnami/grafana-tempo/CHANGELOG.md
bitnami/grafana-tempo/Chart.yaml

[bitnami/grafana-tempo] Bump chart version

---

bitnami/grafana-mimir/CHANGELOG.md
bitnami/grafana-mimir/Chart.yaml

[bitnami/grafana-mimir] Bump chart version

---

bitnami/gitea/CHANGELOG.md
bitnami/gitea/Chart.yaml

[bitnami/gitea] Bump chart version

---

bitnami/ghost/CHANGELOG.md
bitnami/ghost/Chart.yaml

[bitnami/ghost] Bump chart version

---

bitnami/elasticsearch/CHANGELOG.md
bitnami/elasticsearch/Chart.yaml

[bitnami/elasticsearch] Bump chart version

---

bitnami/discourse/CHANGELOG.md
bitnami/discourse/Chart.yaml

[bitnami/discourse] Bump chart version

---

bitnami/concourse/CHANGELOG.md
bitnami/concourse/Chart.yaml

[bitnami/concourse] Bump chart version

---

bitnami/clickhouse/CHANGELOG.md
bitnami/clickhouse/Chart.yaml

[bitnami/clickhouse] Bump chart version

---

bitnami/argo-workflows/CHANGELOG.md
bitnami/argo-workflows/Chart.yaml

[bitnami/argo-workflows] Bump chart version

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml

[bitnami/argo-cd] Bump chart version

---

bitnami/appsmith/CHANGELOG.md
bitnami/appsmith/Chart.yaml

[bitnami/appsmith] Bump chart version

---

bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.yaml

[bitnami/apisix] Bump chart version

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml

[bitnami/airflow] Bump chart version

---

.vib/jupyterhub/cypress/cypress.config.js
.vib/jupyterhub/cypress/cypress/e2e/jupyterhub.cy.js
.vib/jupyterhub/cypress/cypress/support/commands.js

Improves jupyterhub's testing instability.
- fixes #

[bitnami/jupyterhub] Improve jupyter hub testing instability

---

bitnami/prestashop/CHANGELOG.md
bitnami/prestashop/Chart.lock
bitnami/prestashop/Chart.yaml

[bitnami/prestashop] Bump chart version

---

bitnami/parse/CHANGELOG.md
bitnami/parse/Chart.lock
bitnami/parse/Chart.yaml

[bitnami/parse] Bump chart version

---

bitnami/oauth2-proxy/CHANGELOG.md
bitnami/oauth2-proxy/Chart.yaml

[bitnami/oauth2-proxy] Bump chart version

---

bitnami/joomla/CHANGELOG.md
bitnami/joomla/Chart.lock
bitnami/joomla/Chart.yaml

[bitnami/joomla] Bump chart version

---

bitnami/ejbca/CHANGELOG.md
bitnami/ejbca/Chart.lock
bitnami/ejbca/Chart.yaml

[bitnami/ejbca] Bump chart version

---

bitnami/drupal/CHANGELOG.md
bitnami/drupal/Chart.lock
bitnami/drupal/Chart.yaml

[bitnami/drupal] Bump chart version

---

bitnami/grafana-operator/CHANGELOG.md
bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/crds/grafanacontactpoints.integreatly.org.yaml

Updates source url for grafanacontactpoints.integreatly.org.yaml
- fixes https://github.com/bitnami/charts/issues/26499
Check the issue for more information

[bitnami/grafana-operator] Update content of grafanacontactpoints.integreatly.org.yaml

---

.vib/kibana/cypress/cypress/e2e/kibana.cy.js
bitnami/kibana/CHANGELOG.md
bitnami/kibana/Chart.yaml

Fix Cypress test to skip the welcome page.
Test get fixed.
N/A
- fixes #
- ~[ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)~

[bitnami/kibana] Fix cypress test to skip welcome page

---

bitnami/postgresql-ha/README.md

Clarify the upgrading steps. It would help users like in #26452
- fixes #

[bitnami/postgresql-ha] Clarify postgresql-ha upgrading

---

.vib/mlflow/goss/goss.yaml

Increase runs/search timeout
In some platforms, that test is taking more than 10s
None

[bitnami/mlflow] Increase runs/search timeout

---

bitnami/apisix/README.md

[bitnami/apisix] Fix typo Mastodon -> APISIX

---

bitnami/nessie/CHANGELOG.md
bitnami/nessie/Chart.yaml
bitnami/nessie/templates/hpa.yaml
bitnami/nessie/templates/vpa.yaml

This PR fixes an issue with the HPA and VPA api helpers, which were missing the proper context.
- fixes #

[bitnami/nessie] fix: :bug: Set correct context in HPA and VPA api helper

---

bitnami/nessie/README.md

This PR improves the Nessie documentation adding how to enable tracing.
- fixes #

[bitnami/nessie] docs: :memo: Add tracing documentation

---

bitnami/dremio/CHANGELOG.md
bitnami/dremio/Chart.yaml
bitnami/dremio/templates/coordinator/networkpolicy.yaml
bitnami/dremio/templates/executor/networkpolicy.yaml
bitnami/dremio/templates/master-coordinator/networkpolicy.yaml

This PR adds a missing port for the Dremio metrics endpoint when metrics.enabled=true.
- fixes #

[bitnami/dremio] fix: :bug: Add missing metrics ports in networkpolicy

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.lock
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/worker/statefulset.yaml

source command doesn't work properly with sh. Changing it to "." to avoid liveness probe issues
Error is never shown
```
Warning  Unhealthy  61s (x3 over 101s)      kubelet            Liveness probe failed: sh: 1: source: not found
```
- fixes https://github.com/bitnami/charts/issues/27196

[bitnami/airflow] liveness probe fail on worker pod

---

.vib/appsmith/cypress/cypress.config.js
.vib/appsmith/cypress/cypress/support/commands.js
bitnami/appsmith/CHANGELOG.md
bitnami/appsmith/Chart.yaml

Increase number of retries to make tests more stable
Tests were randomly failing in some platforms
None

[bitnami/appsmith] Increase test retries for Appsmith

---

.vib/magento/cypress/cypress/support/utils.js
bitnami/magento/CHANGELOG.md
bitnami/magento/Chart.yaml

Tests were failing for some flavors. Unifying tests to avoid future issues.
We test the same in all platforms

[bitnami/magento] Improve tests for Magento

---

bitnami/schema-registry/CHANGELOG.md
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/templates/service.yaml
bitnami/schema-registry/values.yaml

This PR add the possibility to add custom labels to the service.
It adds a possibility that did not exists before

[bitnami/schema-registry] Add labels to service

---

bitnami/matomo/CHANGELOG.md
bitnami/matomo/Chart.yaml
bitnami/matomo/templates/_helpers.tpl

Fix an indentation typo when using `customCAs` parameter.
Allow the usage of customCAs
N/A
- fixes #27879

[bitnami/matomo] Fix customCAs usage

---

.vib/gitea/goss/goss-wait.yaml
.vib/gitea/vib-verify.json
bitnami/gitea/CHANGELOG.md
bitnami/gitea/Chart.yaml

Goss tests were accessing the node so quickly and processes were not still available. This change allows the processes to initialize properly and accept connections
Tests will be more stable
None

[bitnami/gitea] Include goss-wait test to improve test results

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.lock
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/application-controller/_pod.tpl

Fix an indentation when using `imagePullSecrets`.
Allow using `imagePullSecrets`.
N/A
- fixes #

[bitnami/argo-cd] Fix issue when using imagePullSecrets

---

.github/workflows/cd-pipeline.yml

Fixes var name in `sed` command

[github-actions] Fix CD pipeline typo

---

.github/workflows/cd-pipeline.yml

Reverts https://github.com/bitnami/charts/pull/27979 and https://github.com/bitnami/charts/pull/28117

[github-actions] Reverts OCI index

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.lock
bitnami/mlflow/Chart.yaml

Updates the bitnami/mlflow dependencies to use the latest minio version

[bitnami/mlflow] Update deps

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/cluster-configs.yaml

Bugfix <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
bitnami/argo-cd/templates/cluster-configs.yaml
Bugfix by adding clusterCredentials to the values.yaml file as shown below, the <.Release.Namespace>: nil pointer evaluating interface {}.Namespace error will not occur.
```yaml
config:
clusterCredentials:
- name: <CLUSTER_NAME> # Ex. my-cluster
server: <CLUSTER_URL OR IP> # Ex. https://10.10.10.10:6443
config:
bearerToken: <TOKEN>
tlsClientConfig:
insecure: false
caData: <CA_DATA>
```
Maybe nothing else.
- fixes #28440

[bitnami/argo-cd] Bugfix cluster-config.yaml nil pointer evaluating interface {}.XXX

---

bitnami/kibana/CHANGELOG.md
bitnami/kibana/Chart.yaml
bitnami/kibana/templates/configmap.yaml
bitnami/kibana/values.yaml

This change maps a configuration item in server.publicBaseURL to the Kibana config file (server.publicBaseUrl). See https://www.elastic.co/guide/en/kibana/8.14/settings.html#server-publicBaseUrl
Kibana throws an annoying pop-up on each initial load asking you to set this variable. I'm sure it probably also provides a security benefit, but i'm primarily annoyed with the pop up :) 
There's no real drawbacks and arguably this could be added as a parameter in "extraConfiguration", however given Kibana is pushing this as an issue in the UI, it feels more appropriate to be an explicit configuration option IMO 
None

[bitnami/kibana] add publicBaseUrl param

---

bitnami/joomla/CHANGELOG.md
bitnami/joomla/Chart.yaml
bitnami/joomla/README.md
bitnami/joomla/templates/NOTES.txt

Add deprecation notice for Joomla!

[bitnami/joomla] Add deprecation notice

---

bitnami/dokuwiki/CHANGELOG.md
bitnami/dokuwiki/Chart.yaml
bitnami/dokuwiki/README.md
bitnami/dokuwiki/templates/NOTES.txt

Add deprecation notice for Dokuwiki.

[bitnami/dokuwiki] Add deprecation notice

---

bitnami/opencart/CHANGELOG.md
bitnami/opencart/Chart.yaml
bitnami/opencart/README.md
bitnami/opencart/templates/NOTES.txt

Add deprecation notice for OpenCart.

[bitnami/opencart] chore: :memo: :wastebasket: Add deprecation notice

---

bitnami/kafka/README.md

Add missing Kafka Upgrade Notes for latest version.

[bitnami/kafka] Upgrade notes

---

bitnami/phpbb/CHANGELOG.md
bitnami/phpbb/Chart.yaml
bitnami/phpbb/README.md
bitnami/phpbb/templates/NOTES.txt

Add deprecation notice for phpBB.

[bitnami/phpbb] Add deprecation notice

---

bitnami/mediawiki/CHANGELOG.md
bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/README.md
bitnami/mediawiki/templates/NOTES.txt

Add deprecation notice for MediaWiki.

[bitnami/mediawiki] Add deprecation notice

---

bitnami/fluentd/README.md

update READMD.md, becase extraEnv are renamed to extraEnvVars,so update docs.
- fixes #

[bitnami/fluentd]  update README.md

---

bitnami/chainloop/CHANGELOG.md
bitnami/chainloop/Chart.yaml
bitnami/chainloop/README.md

Adds missing TL;DR section in the README.md

[bitnami/chainloop] Add TL;DR

---

bitnami/redis/README.md

Update README after latest major update

[bitnami/redis] Update README after major update

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.lock
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/README.md

Update dependencies to the latest Bitnami Redis major update

[bitnami/argo-cd] Update dependencies

---

bitnami/oauth2-proxy/CHANGELOG.md
bitnami/oauth2-proxy/Chart.lock
bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md

Update dependencies to the latest Bitnami Redis major update

[bitnami/oauth2-proxy] Update dependencies

---

bitnami/appsmith/CHANGELOG.md
bitnami/appsmith/Chart.lock
bitnami/appsmith/Chart.yaml
bitnami/appsmith/README.md

Update dependencies to the latest Bitnami Redis major update

[bitnami/appsmith] Update dependencies

---

bitnami/pinniped/CHANGELOG.md
bitnami/pinniped/Chart.lock
bitnami/pinniped/Chart.yaml

This PR bumps the common subchart dependency, to include the latest changes
- fixes #

[bitnami/pinniped] chore: :arrow_up: Bump common subchart

---

bitnami/postgresql-ha/README.md

Fix some spelling/grammatical errors, and replace the outdated master/slave terminology with primary/replica.

 [bitnami/postgresql-ha] README tweaks

---

template/CHART_NAME/values.yaml

This PR updates the template according to the new standard introduced at #24863
None
None
N/A

bugfix: update template

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/_helpers.tpl

This changes adds a resources section to the Load DAGs init container.
This makes the chart compatible with clusters that mandate that every container has resources defined.
None.
- fixes #28952

[bitnami/airflow] add resources to loaddags initcontainer try 2

---

bitnami/supabase/CHANGELOG.md
bitnami/supabase/Chart.yaml
bitnami/supabase/README.md
bitnami/supabase/templates/NOTES.txt

Add deprecation notice for Supabase.

[bitnami/supabase] Add deprecation notice

---

bitnami/elasticsearch/CHANGELOG.md
bitnami/elasticsearch/Chart.yaml

Bump elasticsearch version to force a new release.
Previous changes were not properly released for all platforms.
None
- fixes #

[bitnami/elasticsearch]fix: Bump version

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/values.schema.json

Update `values.schema.json` for the Redis helm chart
Allows generating `RedisValues` object so it can be used in the cdk8s project. [cdk8s doc](https://cdk8s.io/docs/latest/cli/import/#values-schema)
- fixes #

[bitnami/redis] update values.schema.json

---

.vib/zipkin/vib-action.config
bitnami/zipkin/CHANGELOG.md
bitnami/zipkin/Chart.yaml

This PR moves the verification to serial, as some platforms cannot handle to cassandra instances
- fixes #

[bitnami/zipkin] test: :white_check_mark: Move verification to serial

---

bitnami/grafana-mimir/CHANGELOG.md
bitnami/grafana-mimir/Chart.yaml
bitnami/grafana-mimir/templates/gateway/secret.yaml

 [bitnami/grafana-mimir] removing quotes from gw secrets #29214

---

bitnami/zookeeper/CHANGELOG.md
bitnami/zookeeper/Chart.yaml
bitnami/zookeeper/templates/statefulset.yaml

[bitnami/zookeeper] fix: add apiVersion and kind to volumeClaimTemplates

---

bitnami/prometheus/CHANGELOG.md
bitnami/prometheus/Chart.yaml
bitnami/prometheus/templates/alertmanager/statefulset.yaml

[bitnami/prometheus] fix: add apiVersion and kind to volumeClaimTemplates

---

bitnami/keydb/CHANGELOG.md
bitnami/keydb/Chart.yaml
bitnami/keydb/templates/master/networkpolicy.yaml
bitnami/keydb/templates/replica/networkpolicy.yaml

Adds metrics port to the network policy of master and replica nodes.
Alleviates the need to add the metrics port manually into the additional ports for the network policy.
None

[bitnami/keydb] Adds metrics port to NetworkPolicy

---

bitnami/zipkin/CHANGELOG.md
bitnami/zipkin/Chart.lock
bitnami/zipkin/Chart.yaml
bitnami/zipkin/README.md

Upgrade Cassandra to 12.x.x (appVersion 5.0.0)
- Use the latest stable version of Cassandra.
- N/A
https://cassandra.apache.org/doc/latest/cassandra/new/index.html

[bitnami/zipkin] Upgrade Cassandra to 12.x.x (appVersion 5.0.0)

---

bitnami/mariadb/README.md

fix a typo. The correct value name is `resourcesPreset`
- fixes a typo in README.md

[bitnami/mariadb] Update README.md (typo fix)

---

bitnami/mariadb-galera/README.md

fix a typo.
- fixes a typo in README.md

[bitnami/mariadb-galera] Update README.md (typo fix)

---

bitnami/valkey/CHANGELOG.md
bitnami/valkey/Chart.yaml
bitnami/valkey/values.yaml

A link is a 404.
See https://github.com/valkey-io/valkey-doc/pull/81

[bitnami/valkey] Fix 404 in docs link

---

bitnami/pytorch/CHANGELOG.md
bitnami/pytorch/Chart.yaml
bitnami/pytorch/templates/statefulset.yaml

[bitnami/pytorch] fix: add apiVersion and kind to volumeClaimTemplates

---

bitnami/solr/CHANGELOG.md
bitnami/solr/Chart.yaml
bitnami/solr/templates/statefulset.yaml

[bitnami/solr] fix: add apiVersion and kind to volumeClaimTemplates

---

bitnami/tomcat/CHANGELOG.md
bitnami/tomcat/Chart.yaml
bitnami/tomcat/templates/statefulset.yaml

[bitnami/tomcat] fix: add apiVersion and kind to volumeClaimTemplates

---

bitnami/redis-cluster/CHANGELOG.md
bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/redis-statefulset.yaml

[bitnami/redis-cluster] fix: add apiVersion and kind to volumeClaimTemplates

---

bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.yaml
bitnami/seaweedfs/templates/master/statefulset.yaml
bitnami/seaweedfs/templates/volume/statefulset.yaml

[bitnami/seaweedfs] fix: add apiVersion and kind to volumeClaimTemplates

---

bitnami/neo4j/CHANGELOG.md
bitnami/neo4j/Chart.yaml
bitnami/neo4j/templates/statefulset.yaml

[bitnami/neo4j] fix: add apiVersion and kind to volumeClaimTemplates

---

bitnami/elasticsearch/CHANGELOG.md
bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/data/statefulset.yaml
bitnami/elasticsearch/templates/master/statefulset.yaml

[bitnami/elasticsearch] fix: add apiVersion and kind to volumeClaimTemplates

---

bitnami/janusgraph/CHANGELOG.md
bitnami/janusgraph/Chart.lock
bitnami/janusgraph/Chart.yaml
bitnami/janusgraph/README.md
bitnami/janusgraph/values.yaml

Update Cassandra's chart to version 12

[bitnami/janusgraph] Update version of Cassandra's chart

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.lock
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/statefulset.yaml

Mount path was not correctly set
Scripts can work with the directory now
- fixes https://github.com/bitnami/charts/issues/29194

[bitnami/keycloak] Fix app-volume-dir mount path

---

bitnami/kube-prometheus/README.md

Fixes typo `configuratios` -> `configurations`
- fixes #

[bitnami/kube-prometheus] Fix typo in README.md

---

bitnami/grafana-operator/README.md

Removes duplicated text in the README's **Differences between the Bitnami Grafana chart and the Bitnami Grafana Operator chart** section. The text from the bullet points for each option is repeated under their respective diagrams without providing additional information or context.
Also fixes a typo in the **Resource requests and limits** section: `resourcePreset` -> `resourcesPreset` which is the argument name.
- fixes #

[bitnami/grafana-operator] Remove duplicated text in README.md

---

bitnami/magento/CHANGELOG.md
bitnami/magento/Chart.yaml
bitnami/magento/README.md
bitnami/magento/templates/NOTES.txt

Adds a deprecation notice for the Magento Helm chart.

[bitnami/magento] Add deprecation note

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md

This PR bumps Spring Cloud Dataflow to a new major, as the RabbitMQ dependency was bumped to version 4.x.x
- fixes #

[bitnami/spring-cloud-dataflow] feat!: :arrow_up: :boom: Bump RabbitMQ to 4.x.x

---

bitnami/odoo/CHANGELOG.md
bitnami/odoo/Chart.lock
bitnami/odoo/Chart.yaml
bitnami/odoo/README.md

[bitnami/odoo] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/sonarqube/CHANGELOG.md
bitnami/sonarqube/Chart.lock
bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/README.md

[bitnami/sonarqube] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.lock
bitnami/seaweedfs/Chart.yaml
bitnami/seaweedfs/README.md

[bitnami/seaweedfs] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/redmine/CHANGELOG.md
bitnami/redmine/Chart.lock
bitnami/redmine/Chart.yaml
bitnami/redmine/README.md

[bitnami/redmine] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.lock
bitnami/mlflow/Chart.yaml
bitnami/mlflow/README.md

[bitnami/mlflow] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.lock
bitnami/airflow/Chart.yaml
bitnami/airflow/README.md

[bitnami/airflow] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/chainloop/CHANGELOG.md
bitnami/chainloop/Chart.lock
bitnami/chainloop/Chart.yaml
bitnami/chainloop/README.md

[bitnami/chainloop] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.lock
bitnami/harbor/Chart.yaml
bitnami/harbor/README.md

[bitnami/harbor] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/kubeapps/CHANGELOG.md
bitnami/kubeapps/Chart.lock
bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/README.md

[bitnami/kubeapps] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/kong/CHANGELOG.md
bitnami/kong/Chart.lock
bitnami/kong/Chart.yaml
bitnami/kong/README.md

[bitnami/kong] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.lock
bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md

[bitnami/keycloak] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/jupyterhub/CHANGELOG.md
bitnami/jupyterhub/Chart.lock
bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/README.md

[bitnami/jupyterhub] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/nessie/CHANGELOG.md
bitnami/nessie/Chart.lock
bitnami/nessie/Chart.yaml
bitnami/nessie/README.md

[bitnami/nessie] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/mongodb-sharded/README.md
bitnami/mongodb/README.md

Updates README information on how to upgrade into 16.0.0

[bitnami/mongodb] Update README

---

bitnami/minio/CHANGELOG.md
bitnami/minio/Chart.yaml
bitnami/minio/README.md
bitnami/minio/templates/distributed/statefulset.yaml
bitnami/minio/values.yaml

Support custom selector for persistent volumes on distributed mode
Allow more fine grained persistent volume selection
none
- none

[bitnami/minio] Support selector for `volumeClaimTemplates`

---

template/CHART_NAME/templates/secret.yaml

Use `common.secrets.passwords.manage` right from the template to streamline future charts on how they handle password.
As this is on the template, this is purely a suggestion.

[bitnami/template] Use common password manager for password secret template

---

bitnami/consul/CHANGELOG.md
bitnami/consul/Chart.yaml
bitnami/consul/templates/configmap.yaml

Fixes #29955
This Changes fixes the wrong Rendering of the COnsul configmap.yaml (config.json)
Rendering of the Configmap is correct for config.json
no limitations
- fixes #29955

[bitnami/consul] Change Configmap Template

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/templates/server/deployment.yaml

This PR adds a missing emptyDir at /.m2 which was causing the application import to fail
- fixes #

[bitnami/spring-cloud-dataflow] fix: :bug: Add missing /.m2 emptyDir

---

bitnami/grafana-loki/CHANGELOG.md
bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/templates/ruler/pdb.yaml

If ruler is disabled, PDB should not get created.
Similar conditional as on other components' PDB template
PDB is not created if ruler is disabled.
None noted
- fixes #

[bitnami/grafana-loki] Fix conditional on ruler PDB creation

---

bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/read/statefulset.yaml

When `architecture: replication` as well as `metrics.enabled: true` and `metrics.collectors.postmaster: true` are set (any collector works here, postmaster used as example) this change makes the read replicas metrics containers start with the relevant collector args.
Consistent behavior when enabling metrics collectors in replication mode.
- fixes #30125

[bitnami/postgresql] metrics.collectors applies to read replicas

---

bitnami/mysql/CHANGELOG.md
bitnami/mysql/Chart.yaml
bitnami/mysql/templates/_helpers.tpl

Remove the unused, undocumented, un-namespaced `getValueFromSecret` local helper for the following charts:
* https://github.com/bitnami/charts/pull/29962
* https://github.com/bitnami/charts/pull/29440
Promote the use of common helpers `common.secrets.passwords.manage`, properly defined.
Should also help to reduce errors/mismatches around secret lookups.

[bitnami/mysql] Drop unused `getValueFromSecret` local helper

---

bitnami/airflow/README.md

This PR adds a "Prometheus metrics" section with more details on the Prometheus integration in the chart.
n/a
- fixes #

[bitnami/airflow] docs: :memo: Add "Prometheus metrics" section

---

bitnami/mastodon/README.md
bitnami/prometheus/README.md

There are no code changes.  I've corrected some cut-and-paste issues with README.md for mastodon and prometheus
* Fix example snippet for installing Grafana and Prometheus
* Fix incorrect reference to Redis in External elasticsearch support README.md
Better documentation.
- [X ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [ X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

[bitnami/mastodon][bitnami/prometheus] Fix README.md files typos

---

bitnami/kube-prometheus/CHANGELOG.md
bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/charts/kube-prometheus-crds/values.yaml

Add _values.yaml_ since it is required by CI/CD tools and processes.

[bitnami/kube-prometheus] Add dummy values.yaml to CRDs subchart

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md

This PR bumps the MariaDB subchart to version 20.x.x, in order to continue having automated updates without issues.
- fixes #

[bitnami/spring-cloud-dataflow] chore!: :arrow_up: :boom: Bump MariaDB subchart to 20

---

bitnami/milvus/README.md

This PR adds a section for updating credentials. 
Documentation improved
n/a
- fixes #

[bitnami/milvus] docs: :memo: Add "Update credentials" section

---

bitnami/kafka/README.md

Add upgrade notes for version 31.0.0
- fixes #

[bitnami/kafka] Add upgrade notes for version 31.0.0

---

.vib/apisix/cypress/cypress/fixtures/service.json
.vib/kong/cypress/cypress/fixtures/services.json
.vib/matomo/cypress/cypress/fixtures/websites.json

[bitnami/apisix, kong, matomo] test: :white_check_mark: Replace bitnami endpoints with google

---

bitnami/common/Chart.yaml

Follow up https://github.com/bitnami/charts/pull/30625 syncing appVersion with version

[bitnami/common] Fix appVersion

---

bitnami/mariadb/CHANGELOG.md
bitnami/mariadb/Chart.yaml
bitnami/mariadb/templates/primary/statefulset.yaml
bitnami/mariadb/templates/secondary/statefulset.yaml

This PR adds a missing `s` in the tls mountPath in the MariaDB chart.
TLS works
n/a
- fixes #

[bitnami/mariadb] fix: :bug: Set correct TLS mountPath

---

bitnami/influxdb/README.md
bitnami/janusgraph/README.md
bitnami/jupyterhub/README.md
bitnami/kafka/README.md
bitnami/keycloak/README.md
bitnami/keydb/README.md
bitnami/kiam/README.md
bitnami/kibana/README.md
bitnami/kong/README.md
bitnami/kuberay/README.md
bitnami/kubernetes-event-exporter/README.md

This PR adds a "Prometheus metrics" section with more details on the Prometheus integration in the chart.
n/a
- fixes #

[bitnami/*] docs: :memo: Add "Prometheus metrics" (batch 3)

---

bitnami/nats/README.md
bitnami/nessie/README.md
bitnami/nginx-ingress-controller/README.md
bitnami/nginx/README.md
bitnami/opensearch/README.md
bitnami/phpmyadmin/README.md
bitnami/postgresql-ha/README.md
bitnami/postgresql/README.md
bitnami/rabbitmq-cluster-operator/README.md
bitnami/rabbitmq/README.md
bitnami/redis-cluster/README.md
bitnami/redis/README.md

This PR adds a "Prometheus metrics" section with more details on the Prometheus integration in the chart.
n/a
- fixes #

[bitnami/*] docs: :memo: Add "Prometheus metrics" (batch 5)

---

bitnami/mariadb-galera/README.md
bitnami/mariadb/README.md
bitnami/minio/README.md
bitnami/mlflow/README.md
bitnami/mysql/README.md
bitnami/scylladb/README.md
bitnami/sealed-secrets/README.md
bitnami/seaweedfs/README.md
bitnami/solr/README.md
bitnami/sonarqube/README.md
bitnami/spark/README.md
bitnami/spring-cloud-dataflow/README.md
bitnami/tensorflow-resnet/README.md
bitnami/thanos/README.md
bitnami/tomcat/README.md
bitnami/valkey-cluster/README.md
bitnami/valkey/README.md
bitnami/vault/README.md
bitnami/wordpress/README.md
bitnami/zipkin/README.md
bitnami/zookeeper/README.md

This PR adds a "Prometheus metrics" section with more details on the Prometheus integration in the chart.
n/a
- fixes #

[bitnami/*] docs: :memo: Add "Prometheus metrics" (batch 6)

---

bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.lock
bitnami/apisix/Chart.yaml
bitnami/apisix/README.md
bitnami/apisix/templates/dashboard/secret.yaml

This PR changes the dashboard secret allow overriding via values.yaml. Additionally, it provides a documentation section in the README.md
n/a
- fixes #

[bitnami/apisix] feat: :sparkles: :memo: Allow password update via values.yaml

---

bitnami/dremio/CHANGELOG.md
bitnami/dremio/Chart.yaml
bitnami/dremio/values.yaml

This PR renames an auto-generated documentation section to avoid issues with the "Markdown Linter" and error "Same headings"
- fixes #

[bitnami/dremio] chore: :bulb: :memo: :rotating_light: Rename prometheus "@section" to avoid linter problems

---

bitnami/airflow/README.md
bitnami/appsmith/README.md
bitnami/cassandra/README.md
bitnami/clickhouse/README.md
bitnami/concourse/README.md
bitnami/discourse/README.md
bitnami/drupal/README.md
bitnami/ejbca/README.md
bitnami/elasticsearch/README.md
bitnami/etcd/README.md

This PR adds a "Update credentials" section with more details on how to change the credentials in the charts.
n/a
- fixes #

[bitnami/*] docs: :memo: Add "Update Credentials" (batch 1)

---

bitnami/ghost/README.md
bitnami/gitea/README.md
bitnami/grafana/README.md
bitnami/influxdb/README.md
bitnami/jenkins/README.md
bitnami/jupyterhub/README.md
bitnami/kafka/README.md
bitnami/keycloak/README.md
bitnami/kibana/README.md
bitnami/mariadb-galera/README.md
bitnami/mastodon/README.md
bitnami/matomo/README.md
bitnami/memcached/README.md
bitnami/minio/README.md

This PR adds a "Update credentials" section with more details on how to change the credentials in the charts.
n/a
- fixes #

[bitnami/*] docs: :memo: Add "Update Credentials" (batch 2)

---

bitnami/valkey/CHANGELOG.md
bitnami/valkey/Chart.lock
bitnami/valkey/Chart.yaml
bitnami/valkey/README.md
bitnami/valkey/templates/secret.yaml

This PR changes the dashboard secret allow overriding via values.yaml. Additionally, it provides a documentation section in the README.md
n/a
- fixes #

[bitnami/valkey] feat: :sparkles: :memo: Allow password update via values.yaml

---

bitnami/keydb/CHANGELOG.md
bitnami/keydb/Chart.lock
bitnami/keydb/Chart.yaml
bitnami/keydb/README.md
bitnami/keydb/templates/secret.yaml

This PR changes the dashboard secret allow overriding via values.yaml. Additionally, it provides a documentation section in the README.md
n/a
- fixes #

[bitnami/keydb] feat: :sparkles: :memo: Allow password update via values.yaml

---

template/CHART_NAME/templates/NOTES.txt
template/CHART_NAME/values.yaml

Implemented thanks to [those changes](https://github.com/bitnami/charts/pull/30851) in btinami/common.

[bitnami/template] Detect non-standard images

---

bitnami/jaeger/CHANGELOG.md
bitnami/jaeger/Chart.yaml
bitnami/jaeger/templates/NOTES.txt

Fix issue introduced at https://github.com/bitnami/charts/pull/30881

[bitnami/jaeger] Fix typo in NOTES.txt

---

.vib/wildfly/goss/goss.yaml

Skip test because is using an forbidden algorithm type on an specific OS.
Chart release

[bitnami/wildfly] Skip test on specific OS_FLAVOR

---

.vib/wildfly/goss/goss.yaml
bitnami/wildfly/CHANGELOG.md
bitnami/wildfly/Chart.yaml

Bump patch version
Use new test changes.

[bitnami/wildfly] Bump patch version to apply .vib tests changes

---

bitnami/postgresql-ha/README.md

I found a typo in the documentation.
Better readability
Maybe introduced another typo.
_none_
_none_

[bitnami/postgresql-ha] Fix typo in documentation

---

bitnami/mariadb-galera/README.md

Update documentation related to sidecar containers (formerly known as extracontainers), see https://github.com/bitnami/charts/pull/10422
- Fixes https://github.com/bitnami/charts/issues/31181

[bitnami/mariadb-galera] Update sidecar containers doc in README.md

---

.github/workflows/gchat-notification.yml
.github/workflows/index-monitor.yml

Adds the new workflow 'index-monitor.yml'.
This new workflow will be executed in a schedule every 10 minutes and will be in charge of checking the integrity of the index.yaml file available at 
These changes aim to prevent the recent index failures, which we suspect may be related to the upload of the index.yaml available at 'http://charts.bitnami.com/bitnami/index.yaml'.
If consistent failures are detected (failed 3 times in a row), notifies the error and triggers a new index upload to immediately amend the issues.
The workflow consists of 2 checks:
- The integrity check will verify the index.yaml available in the  'index' branch matches the one available at 'http://charts.bitnami.com/bitnami/index.yaml'.
- The validation check will test that the commands `helm repo add` and `helm repo …

[github-actions] Add index-monitor action

---

.vib/prometheus/goss/goss.yaml
bitnami/prometheus/CHANGELOG.md
bitnami/prometheus/Chart.yaml

Remove GOSS duplicated command

[bitnami/prometheus] Remove GOSS duplicated command

---

bitnami/grafana-mimir/CHANGELOG.md
bitnami/grafana-mimir/Chart.lock
bitnami/grafana-mimir/Chart.yaml

Bump MinIO subchart.
Keep our charts up to date.
None

[bitnami/grafana-mimir] feature(minio): Bump MinIO subchart

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.lock
bitnami/mlflow/Chart.yaml

Bump MinIO subchart.
Keep our charts up to date.
None

[bitnami/mlflow] feature(minio): Bump MinIO subchart

---

bitnami/thanos/CHANGELOG.md
bitnami/thanos/Chart.lock
bitnami/thanos/Chart.yaml

Bump MinIO subchart.
Keep our charts up to date.
None

[bitnami/thanos] feature(minio): Bump MinIO subchart

---

.github/workflows/sync-chart-cloudflare-index.yml

Updates the gchat-notification workflow location

[index] Update gchat-notification workflow

---

bitnami/nginx/README.md

Minor clarification in `README.md` file.

[bitnami/nginx] Update README.md

---

bitnami/cert-manager/CHANGELOG.md
bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/templates/cainjector/rbac.yaml
bitnami/cert-manager/templates/controller/rbac.yaml

Updated the RBAC permissions for cert-manager controller and cainjector to align as much with the upstream.
- https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/templates/cainjector-rbac.yaml
- https://github.com/cert-manager/cert-manager/blob/master/deploy/charts/cert-manager/templates/rbac.yaml
Able to use Server Side Apply feature
- fixes #31724

[bitnami/cert-manager] Updated cert-manager RBAC

---

.github/workflows/archive-full-index.yml

Update dependencies of the archive-full-index workflow.

[index] Update archive-full-index workflow dependencies

---

bitnami/chainloop/CHANGELOG.md
bitnami/chainloop/Chart.lock
bitnami/chainloop/Chart.yaml

[bitnami/chainloop] Update deps

---

bitnami/cloudnative-pg/CHANGELOG.md
bitnami/cloudnative-pg/Chart.yaml
bitnami/cloudnative-pg/templates/_helpers.tpl

This PR fixes the pull secret calculation for the PULL_SECRET_NAME variable, which was missing the `name` parameter
- fixes #

[bitnami/cloudnative-pg] fix: :bug: Set proper pull secret name

---

.vib/cloudnative-pg/runtime-parameters.yaml
bitnami/cloudnative-pg/CHANGELOG.md
bitnami/cloudnative-pg/Chart.yaml
bitnami/cloudnative-pg/templates/deployment.yaml

[bitnami/cloudnative-pg] test: :white_check_mark: Add imagePullSecrets to the cluster

---

bitnami/valkey/CHANGELOG.md
bitnami/valkey/Chart.yaml
bitnami/valkey/templates/_helpers.tpl

Specifically: updates the formatting of .Values.tls.existingSecret to properly format variables such as "{{ .Release.Name }}-valkey-tls"
updates the formatting of .Values.tls.existingSecret to properly format variables such as "{{ .Release.Name }}-valkey-tls"
Allows for proper formatting of variables for tls.existingSecret
None. This aligns the formatting with the Valkey-Cluster chart.
none
- [x ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)

[bitnami]/valkey update _helpers.tpl to be in line with Valkey-Cluster.

---

bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.yaml
bitnami/harbor/templates/core/core-dpl.yaml

Remove unused psc mount in harbor core deployment
Mount caused issues during microshift deployment and has no benifits
Mount has no benfit so should have no drawbacks
- resolves #32265
Mount is unused has been confirmed by goharbor maintainer here: https://github.com/goharbor/harbor/issues/21706

[bitnami/harbor] removed /etc/core/token mount since it's unused

---

bitnami/pytorch/CHANGELOG.md
bitnami/pytorch/Chart.yaml

It's needed to apply changes in tests (https://github.com/bitnami/charts/pull/32403)

[bitnami/pytorch] Update Chart.yaml

---

.github/workflows/cd-pipeline.yml
.github/workflows/ci-pipeline.yml
.github/workflows/index-update.yml

@bitnami-bot email has been changed

Update bitnami bot email

---

.vib/cert-manager/ginkgo/go.mod
.vib/contour/ginkgo/go.mod
.vib/kubernetes-event-exporter/ginkgo/go.mod
.vib/metallb/ginkgo/go.mod
.vib/nginx-ingress-controller/ginkgo/go.mod
.vib/pinniped/ginkgo/go.mod
.vib/sealed-secrets/ginkgo/go.mod

Follow up https://github.com/bitnami/charts/pull/32662

Upgrade Go version in Ginkgo tests

---

.vib/minio-operator/goss/goss.yaml

This PR adds the --insecure flag in the minio client command, as in some platforms there is an issue with the certificate verification
- fixes #

[bitnami/minio-operator] test: :white_check_mark: Add --insecure flag

---

.vib/superset/runtime-parameters.yaml

Use small resourcesPreset for PostgreSQL

[bitnami/superset] Use small resourcesPreset for PostgreSQL

---

bitnami/milvus/CHANGELOG.md
bitnami/milvus/Chart.lock
bitnami/milvus/Chart.yaml
bitnami/milvus/README.md

This PR fixes a typo in #32701
Use the correct version of MinIO

[bitnami/milvus] Update minio chart

---

.vib/superset/goss/goss.yaml
.vib/superset/runtime-parameters.yaml

Revert superset resource preset for postgresql

[bitnami/superset] Revert superset resource preset for postgresql

---

.vib/dremio/goss/goss.yaml
.vib/dremio/runtime-parameters.yaml

Fix goss tests with Photon-5 chart

Dremio photon 5

---

bitnami/jupyterhub/CHANGELOG.md
bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/README.md
bitnami/jupyterhub/templates/hub/configmap.yaml

Updates `jupyterhub_config.py` and `z2jh.py` references.
Not expected.

[bitnami/jupyterhub] Update jupyterhub_config.py and z2hj.py

---

bitnami/influxdb/CHANGELOG.md
bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/servicemonitor.yaml

Fixes a templating issue introduced in https://github.com/bitnami/charts/pull/32985
The chart will render correctly instead of error
N/A
- fixes #32939 (again)
N/A

[bitnami/influxdb] fix invalid template syntax

---

bitnami/influxdb/CHANGELOG.md
bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/configmap-backup.yaml

[bitnami/influxdb] Fix backup functionality, closes bitnami#33038

---

bitnami/grafana-operator/CHANGELOG.md
bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/templates/grafana.yaml

Don't override labels of resources managed by `grafana-operator`.
The operator already handles it. See [`SetInheritedLabels`](https://github.com/grafana/grafana-operator/blob/3b5208de816c7e1caa866d2fa9165c1c12e9540a/controllers/model/utils.go#L39).

[bitnami/grafana-operator] don't add common labels to Grafana resources

---

bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/update-password/job.yaml

Values.passwordUpdateJob.annotations didn't seem to be working as expected, so i updated to merge those annotations.
AS-IS
TO-BE
- fixes #

 [bitnami/postgresql] Fix annotations not applied to passwordUpdateJob

---

bitnami/influxdb/CHANGELOG.md
bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/configmap-backup.yaml

- fixes #33110 
- related #33038

 [bitnami/influxdb] Fix backup functionality, closes bitnami#33110

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/_helpers.tpl

Allow tpl of external database + external user

[bitnami/keycloak] Allow tpl of external database + external user

---

bitnami/mysql/README.md
bitnami/spring-cloud-dataflow/README.md

Update MySQL docs. Also, fix a typo in spring-cloud-dataflow README.md

[bitnami/mysql] Update MySQL docs

---

bitnami/ghost/CHANGELOG.md
bitnami/ghost/Chart.lock
bitnami/ghost/Chart.yaml
bitnami/ghost/README.md

Update MySQL subchart to version 9.3
Use the latest MySQL
N/A
- fixes #

[bitnami/ghost] Update MySQL subchart

---

bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.yaml
bitnami/harbor/templates/_helpers.tpl

This change fixes a typo in the environment variable for enabling tracing in the Harbor Helm Chart and quotes the `tracing.attributes` object using single quotes to avoid a YAML error.
Tracing is enabled correctly.
- fixes #33679 
The YAML error was also discovered and fixed at https://github.com/goharbor/harbor-helm/issues/1556.  The environment variable for enabling tracing is also at https://github.com/goharbor/harbor-helm/blob/ac65d7b4d6dd5f42b0e1521be2c488bc1663b1c4/templates/_helpers.tpl#L545.

[bitnami/harbor] update tracing environment variables and escaping

---

bitnami/argo-cd/README.md
bitnami/clickhouse/README.md
bitnami/kafka/README.md
bitnami/kube-prometheus/README.md
bitnami/minio/README.md
bitnami/mongodb/README.md
bitnami/nginx/README.md
bitnami/postgresql/README.md
bitnami/rabbitmq/README.md
bitnami/redis/README.md

Add CNAB link for charts on Azure MP

[bitnami/*] Add CNAB link for charts on Azure MP

---

bitnami/grafana/CHANGELOG.md
bitnami/grafana/Chart.yaml
bitnami/grafana/templates/prometheusrules.yaml
bitnami/grafana/templates/servicemonitor.yaml

wrap include with parenthesis to isolate it.
- fixes #33623

[bitnami/grafana] fix metrics namespace include

---

bitnami/argo-cd/README.md
bitnami/clickhouse/README.md
bitnami/kafka/README.md
bitnami/kube-prometheus/README.md
bitnami/minio/README.md
bitnami/mongodb/README.md
bitnami/nginx/README.md
bitnami/postgresql/README.md
bitnami/rabbitmq/README.md
bitnami/redis/README.md

Update CNAB tip to properly show link on DockerHub

[bitnami/*] Update CNAB tip

---

bitnami/milvus/CHANGELOG.md
bitnami/milvus/Chart.lock
bitnami/milvus/Chart.yaml
bitnami/milvus/README.md

Update ETCD to major 12
Use the latest version of ETCD subchart
N/A
https://github.com/bitnami/charts/tree/main/bitnami/etcd#to-1100

[bitnami/milvus] Update ETCD subchart

---

bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.yaml
bitnami/harbor/templates/_helpers.tpl

Check if trivy is enabled in `harbor.validateValues.externalRedis` validation helper.
We don't need to add  a dummy value for `externalRedis.trivy.host` when trivy is disabled.
None

[bitnami/harbor]fix(validateValues.externalRedis): Check if trivy is enabled

---

.vib/grafana-alloy/goss/goss.yaml

[bitnami/grafana-alloy] Adapt tests for Openshift

---

template/CHART_NAME/templates/NOTES.txt
template/CHART_NAME/templates/_helpers.tpl
template/CHART_NAME/templates/_init_containers.tpl
template/CHART_NAME/templates/daemonset.yaml
template/CHART_NAME/templates/deployment.yaml
template/CHART_NAME/templates/networkpolicy.yaml
template/CHART_NAME/templates/statefulset.yaml
template/CHART_NAME/values.yaml

This PR updates the chart template with some of the the latest standards we incorporated in the catalog such as:
- Usage of "defaultInitContainers"
- Usage of `_init_containers.tpl` for helpers related to init-containers
- Usage of `common.warnings.resources` in NOTES
- Simplification on chart parameters' descriptions

feat: update chart template with some of the latest standards

---

template/CHART_NAME/templates/clusterrolebinding.yaml
template/CHART_NAME/templates/networkpolicy.yaml
template/CHART_NAME/templates/pvc.yaml
template/CHART_NAME/templates/role.yaml

Minor change but align all template to have apiVersion on the first element (or Kind to second...)
help when diff template

[template] move apiVersion on first element (or kind to second)

---

bitnami/rabbitmq/CHANGELOG.md
bitnami/rabbitmq/Chart.lock
bitnami/rabbitmq/Chart.yaml

[bitnami/rabbitmq] Update dependencies

---

bitnami/nginx/CHANGELOG.md
bitnami/nginx/Chart.lock
bitnami/nginx/Chart.yaml

[bitnami/nginx] Update dependencies

---

bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.lock
bitnami/postgresql/Chart.yaml

[bitnami/postgresql] Update dependencies

---

.github/workflows/cd-pipeline.yml

Update VIB public URL

---

template/CHART_NAME/values.yaml

Fix values.yaml template about ExisitingConfigMap settings default value

[bitnami/template] Add missing quote for existingConfigmap settings

---

bitnami/redis/README.md

This change updates the Redis documentation to include instructions on how to load modules (RediSearch, RedisBloom, RedisJSON, RedisTimeSeries) in Redis Open Source 8+.
This update provides clear and specific guidance for users on configuring Redis 8+ to load necessary modules, improving the user experience and reducing potential setup issues.
There are no known drawbacks to this change, as it is purely a documentation update.

[bitnami/redis] Add Redis Open Source 8 Load Modules Docs

---

bitnami/ghost/CHANGELOG.md
bitnami/ghost/Chart.lock
bitnami/ghost/Chart.yaml
bitnami/ghost/README.md

Upgrade MySQL subchart to 14
Use the latest version of MySQL
N/A

[bitnami/ghost] Upgrade MySQL subchart to 14

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.yaml
bitnami/etcd/README.md
bitnami/etcd/templates/preupgrade-hook-job.yaml
bitnami/etcd/values.yaml

Implement optional preUpgrade behavior change delivered
by bitnami/containers#82434 to etcd container.
Signed-off-by: Robert Moucha <robert.moucha@gooddata.com>
- fixes #

[bitnami/etcd] feat: introduce preUpgrade job delay

---

bitnami/external-dns/CHANGELOG.md
bitnami/external-dns/Chart.lock
bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/_helpers.tpl

This PR removes hardcoded references to the image repository in the chart templates.

[bitnami/external-dns] Remove hardcoded references to image repository

---

bitnami/vault/CHANGELOG.md
bitnami/vault/Chart.yaml
bitnami/vault/README.md
bitnami/vault/templates/server/roles.yaml
bitnami/vault/values.yaml

This change allows users to modify or extend the Roles created by `server.rbac`.
Iin the current version of the Chart modifying the server RBAC rules is only possible by disabling RBAC and manually creating Roles and RoleBindings. With the changes made in this PR Users can just adjust or extend the `server.rbac.leaderElection.rules` or `server.rbac.discovery.rules` to their needs.
- fixes #27314

[bitnami/vault] Add ability to modify or extend the vault sever RBAC roles

---

bitnami/minio/CHANGELOG.md
bitnami/minio/Chart.yaml
bitnami/minio/values.yaml

This PR fix the broken documentation link to minio server configuration
- fixes #

[bitnami/minio]: fix broken provisioning config link

---

bitnami/telegraf/README.md

Add README for Telegraf BSI chart

[bitnami/telegraf] Add Telegraf README.md

---

bitnami/telegraf/README.md

Update naming to Telegraf (TM)

[bitnami/telegraf] Update naming to Telegraf (TM)

---

.github/workflows/index-monitor.yml
.github/workflows/index-update.yml

Recover actions related to the index.yaml wrongly removed at https://github.com/bitnami/charts/pull/36274

Recover actions related to index

---

bitnami/postgresql/README.md

Change dry-run option to use 'client' in kubectl command since --dry-run is deprecated.
- fixes #

[bitnami/postgresql]Update kubectl command for creating secrets
