bitnami/schema-registry/Chart.lock
bitnami/schema-registry/Chart.yaml

The chart version was downgraded by mistake at https://github.com/bitnami/charts/pull/20074, this PR returned the Helm chart to the 16.x.x branch and updated the dependencies
15.0.1 ✅ -> 15.0.2 ✅ -> 16.0.0 ✅ -> 15.1.0 🔴 -> **16.1.0** ✅

[bitnami/schema-registry] Bump chart version and update deps

---

bitnami/milvus/Chart.yaml
bitnami/milvus/README.md
bitnami/milvus/values.yaml

Set all the default values for externalEtcd.
The chart start using an external ETCD.
N/A
- fixes #20397

[bitnami/milvus] Fix externalEtcd settings

---

bitnami/solr/Chart.yaml
bitnami/solr/README.md
bitnami/solr/templates/statefulset.yaml
bitnami/solr/values.yaml

This pull request adds support for `enableServiceLinks` parameter on Solr Helm chart.
- Reduce startup time for pods that run in a shared namespace with many services.
- None. Param has default value of `true`, which is standard k8s behaviour.

[bitnami/solr] Add support for enableServiceLinks on solr chart

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/configmap.yaml

This is a bugfix for the issue #20255 (i.e. arbiter's configuration file cannot be customised).
MongoDB Arbiter `configmap.yaml` is correctly generated when custom configuration is provided.
n/a
- fixes #20255
n/a

[bitnami/mongodb] Fixed mongodb arbiter configmap

---

bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/tracking/externals3-secret.yaml
bitnami/mlflow/values.yaml

External s3 secret name and link to it at deployment must be the same.
Typo at readme, redis is not exist at this chart.
- fixes #

[bitnami/mlflow] Fix external s3 secret support and typo's

---

bitnami/kafka/README.md

Update a typo where `externalAccess.controller.*` was listed twice instead of `externalAccess.controller.*` and `externalAccess.broker.*`.
Be explicit about the fact that either condition mentioned is sufficient for controller pods to configure externalAccess.
Validated by reading
`bitnami/kafka/templates/controller-eligible/svc-external-access.yaml` and
`bitnami/kafka/templates/broker/svc-external-access.yaml`.
No code changes.
Clarity of README. 
None

[bitnami/kafka] Update README's upgrade 24.0.0 notes (#17029)

---

bitnami/jasperreports/Chart.lock
bitnami/jasperreports/Chart.yaml
bitnami/jasperreports/README.md
bitnami/jasperreports/values.yaml

[bitnami/jasperreports] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/jaeger/Chart.yaml
bitnami/jaeger/README.md
bitnami/jaeger/templates/_helpers.tpl
bitnami/jaeger/templates/agent/deployment.yaml
bitnami/jaeger/templates/collector/deployment.yaml
bitnami/jaeger/templates/migrate-job.yaml
bitnami/jaeger/templates/query/deployment.yaml
bitnami/jaeger/values.yaml

[bitnami/jaeger] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/mxnet/Chart.yaml
bitnami/mxnet/README.md
bitnami/mxnet/values.yaml

[bitnami/mxnet] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/ejbca/Chart.lock
bitnami/ejbca/Chart.yaml
bitnami/ejbca/README.md
bitnami/ejbca/values.yaml

[bitnami/ejbca] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/README.md
bitnami/cassandra/values.yaml

[bitnami/cassandra] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/kafka/Chart.yaml
bitnami/kafka/values.yaml

Docs are specifying the opposite of the actual implementation:
```
{{- define "kafka.validateValues.zookeeperMissingBrokers" -}}
{{- if and (or .Values.zookeeper.enabled .Values.externalZookeeper.servers) (le (int .Values.broker.replicaCount) 0)}}
kafka: Zookeeper mode - No Kafka brokers configured
Zookeper mode has been enabled, but no Kafka brokers nodes have been configured
```

[bitnami/kafka]: clarify docs

---

bitnami/whereabouts/Chart.yaml
bitnami/whereabouts/templates/service-account.yaml

Use `common.names.namespace` instead of `.Release.Namespace` to define the namespace for the service account so it matches Daemonset. This prevents Service Account and Daemonset from ending up in different namespaces when a namespace override is used.
Service Accounts will be created in the correct namespace, daemonset will get the required RBAC
None that I'm aware of
- Fixes #20597

[bitnami/whereabouts] Fix service account namespace to match daemonset.

---

bitnami/multus-cni/Chart.yaml
bitnami/multus-cni/templates/service-account.yaml

Use `common.names.namespace` instead of `.Release.Namespace` to define a namespace for a service account so it matches Daemonset. This prevents Service Account and  Daemonset from ending up in different namespaces when a namespace override is used.
Service Accounts will be created in the correct namespace, daemonset will get the required RBAC
None that I'm aware of
- Fixes #20597

bitnami/multus Fix service account namespace to match daemonset.

---

bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/tracking/externaldb-secret.yaml

See https://github.com/bitnami/charts/issues/20581
The name of the external-dbs secret manifest should have the name defined in helpers and used by other manifests.
Fixes deployment with external DBs
N/A
- Fixes https://github.com/bitnami/charts/issues/20581

[bitnami/mlflow] Issue 20581 - fix external DB secret template name

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/templates/metrics-service.yaml
bitnami/keycloak/values.yaml

add extraPorts to the metrics service, so that vm metrics can be moved away from the default port to the admin port (9000), by this the metrics are not exposed to the otherwise public port.
- fixes #

[bitnami/keycloak] fix: add extraPorts to metrics service

---

bitnami/mysql/Chart.yaml
bitnami/mysql/values.yaml

In the mysql configuration section in values.yaml there is a reference to .Values.auth.defaultAuthPlugin which does not exist. The correct name is .Values.auth.defaultAuthenticationPlugin
Setting .Values.auth.defaultAuthenticationPlugin actually works.
Users which has compensated for the error by using a undocumented variable might need to adjust their configuration
- fixes #20574

[bitnami/mysql] Fix reference to defaultAuthenticationPlugin

---

bitnami/oauth2-proxy/Chart.lock
bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md
bitnami/oauth2-proxy/values.yaml

[bitnami/oauth2-proxy] feat: :sparkles: Add support for PSA restricted policy

---

bitnami/gitea/Chart.yaml
bitnami/gitea/README.md
bitnami/gitea/templates/deployment.yaml
bitnami/gitea/values.yaml

Remove the ability to increase the number of replicas. Running Gitea in HA mode is a experimental feature, as described in their [official documentation](https://gitea.com/gitea/helm-chart/src/branch/main/docs/ha-setup.md), and requires a management system for cache, session and queueing.
Removed support for `replicaCount > 1` deployments, which will result in failure.
None, deployments with `replicaCount > 1` should already fail.
- relates to #19834
An internal issue has been created in order to evaluate implementing the necessary changes for the chart to be HA-compatible.

[bitnami/gitea] Remove HA support

---

.vib/kubernetes-event-exporter/ginkgo/kubernetes_event_exporter.go

Increase the timeout for the test that checks whether a pod was created.
In some clusters, the pod may take more time to start. This makes tests more resilient by incrementing the timeout to a reasonable range (1 minute).
None
NA
NA

[bitnami/kubernetes-event-exporter] Increase ginkgo tests timeouts

---

bitnami/apisix/Chart.yaml
bitnami/apisix/values.yaml

add missing etcd config for data-plane
when etcd config missing, data-plane will use default etcd  http://127.0.0.1:2379, cause `etcd get: has no healthy etcd endpoint available` error
- fixes #

[bitnami/apisix] fix: add missing etcd config for data-plane

---

bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/run/service-account.yaml
bitnami/mlflow/templates/tracking/ingress.yaml
bitnami/mlflow/templates/tracking/service-account.yaml
bitnami/mlflow/templates/tracking/service.yaml

Closes https://github.com/bitnami/charts/issues/20660
This changes address all instances in mlflow chart templates where annotations are incorrectly merged as 
```
{{- $annotations := include "common.tplvalues.merge" (dict "values" .Values.run.serviceAccount.annotations .Values.commonAnnotations "context" .) | fromYaml }}
```
Annotations can be specified via values and can be successfully merged with `commonAnnotations`
20660

[bitnami/mlflow] fix  issue 20660 'error unmarshaling JSON: while decoding JSON:...' when merging annotations

---

bitnami/mxnet/Chart.yaml
bitnami/mxnet/README.md
bitnami/mxnet/templates/NOTES.txt

Apache MXNet helm chart will be deprecated since the upstream project has been [discontinued](https://mxnet.apache.org/versions/1.9.1/).

[bitnami/mxnet] Mark MXNet chart as deprecated

---

bitnami/metallb/Chart.yaml
bitnami/metallb/templates/controller/deployment.yaml
bitnami/metallb/templates/speaker/daemonset.yaml

The MetalLB chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%
See also #20662 for same change in CertManager.

[bitnami/metallb] Replace deprecated pull secret partial

---

bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/templates/_helpers.tpl

The CertManager chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%
See also #20661 for same change in MetalLB.

[bitnami/cert-manager] Replace deprecated pull secret partial

---

template/CHART_NAME/templates/_helpers.tpl

The chart template still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%
See also the following PRs for same similar changes:
* #20661 MetalLB
* #20662 CertManager
* #20665 MongoDB
* #20666 Redis

[template] Replace deprecated pull secret partial

---

bitnami/minio/Chart.yaml
bitnami/minio/README.md
bitnami/minio/templates/servicemonitor.yaml
bitnami/minio/values.yaml

This enables the use of multiple paths for ServiceMonitor as MinIO exposes different metrics at different endpoints.
Now it's possible to add multiple paths (`/minio/v2/metrics/cluster`, `/minio/v2/metrics/node` , ...) for the ServiceMonitor
Also this deprecates `metrics.serviceMonitor.path` by replacing `metrics.serviceMonitor.paths`, but it still supports `metrics.serviceMonitor.path` field for backward compatibility.
- fixes #19573
Nothing specific

[bitnami/minio] feat: Support multiple paths for metrics (fixes #19573)

---

.github/workflows/retry-failed-releases.yml

Github doesn't support the use of an envvar as a parameter for another envvar in the same `env` scope. To avoid this and maintain the hardening, we'll hardcode the `WORKFLOW_ID` env to avoid issues when creating the `env.WORKFLOW_RUNS_URL` one.
The workflow works as expected
N/A

[bitnami/*] Fix env issue for retry workflow

---

bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/templates/deployment.yaml

The keys `namespaceScope` and `watchNamespace` are inside `operator` section but they are being referenced from root in the deployment template

[bitnami/grafana-operator]  Fix namespace reference

---

bitnami/matomo/Chart.yaml
bitnami/matomo/templates/cronjob.yaml

`extraVolumeMounts` on the archive cron job has wrong indention
`extraVolumeMounts` are usable with cron jobs
none
- fixes #20922

[bitnami/matomo] fix wrong indent of extraVolumeMounts in cron job

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/templates/statefulset.yaml
bitnami/rabbitmq/values.yaml

Supports PVC retention policy for rabbitmq statefulsets
Make use of persistentVolumeClaimRetentionPolicy to Delete or Retain the PVCs/PVs whenever the statefulset gets deleted or scaled down.
Nil
https://github.com/bitnami/charts/issues/13917

[bitnami/rabbitmq] Add Persistent Volume Claim Retention Policy to Rabbitmq Statefulsets  

---

bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/templates/master/application.yaml
bitnami/redis/templates/replicas/application.yaml
bitnami/redis/values.schema.json
bitnami/redis/values.yaml

With this change it is possible to define master as the DaemonSet kind (defaults to StatefulSet) similar to how the master can already be defined as a Deployment.
master:
kind: DaemonSet
Defining master as a DaemonSet has the advantage of being able to run directly on nodes so that applications can connect directly to a master running on the same node using file sockets. The master can be configured to expose the file socket like so
```yaml
commonConfiguration: |
unixsocket /host-tmp/redis.socket
unixsocketperm 775
master:
kind: DaemonSet
extraVolumes:
- name: host-tmp
hostPath:
path: /tmp
type: Directory
extraVolumeMounts:
- mountPath: /host-tmp
name: host-tmp
```
the client app can then mount the socket and connect directly to the replica instead of going through TCP connections. In …

[bitnami/redis] Implementing an option to define masters as DaemonSets

---

bitnami/jaeger/Chart.yaml
bitnami/jaeger/README.md
bitnami/jaeger/templates/_helpers.tpl
bitnami/jaeger/templates/agent/deployment.yaml
bitnami/jaeger/templates/collector/deployment.yaml
bitnami/jaeger/templates/collector/service.yml
bitnami/jaeger/templates/migrate-job.yaml
bitnami/jaeger/templates/query/deployment.yaml
bitnami/jaeger/values.yaml

- fix missing imagePullSecrets in templates
- expose missing otlp receiver ports in jaeger collector
-  https://www.jaegertracing.io/docs/1.50/deployment/#collector ports 4317 and 4318 are now exposed 
- images can be pulled from private registry
- jaeger can receive traces using otlp protocol
- this fixes #20318 
- [X ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ X] All commits signed off and in agreement of …

[bitnami/jaeger] Chart missing imagePullSecrets and otlp ports

---

bitnami/etcd/Chart.yaml
bitnami/etcd/README.md
bitnami/etcd/templates/cronjob.yaml
bitnami/etcd/values.yaml

It allows adding extra labels only to pods created by snapshot cronjob. In the same way that labels are added to pods created by statefulset, it is a good a idea to be able to add labels to pods created by snapshot cronjob.
Ability to add extra labels to pods created by snapshot cronjob.
None as far as I know
- fixes #20972

[bitnami/etcd] Add variable to add extra labels only for snapshot cronjob pods

---

bitnami/contour/Chart.yaml
bitnami/contour/templates/envoy/daemonset.yaml
bitnami/contour/templates/envoy/deployment.yaml

Follow-up of #20492 to fix backwards compatibility.
When `.Values.envoy.useHostPort=false`, the backwards compatibility still works.
None
None
Follow-up of  #20492

[bitnami/contour] Fix useHostPort backwards compatibility

---

bitnami/mariadb/Chart.yaml
bitnami/mariadb/templates/servicemonitor.yaml

Chart has `metrics.serviceMonitor.namespace` value, but doesn't use it in templates. Moreover template for ServiceMonitor uses `metrics.prometheusRule.namespace` for namespace field instead of `metrics.serviceMonitor.namespace`.
Ability to set namespace for ServiceMonitor regardless of PrometheusRule.
None.
None.
The bug appeared with https://github.com/bitnami/charts/commit/ccb27d3cb70a4ccc645032fcb14e809da8ef1e80

[bitnami/mariadb] Fix ServiceMonitor namespace value reference

---

bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md
bitnami/mastodon/values.yaml

This replaces all instances of JupyterHub with Mastodon.
This makes the comments in the values.yaml and the README docs more clear. I believe this was just a copy paste cleanup issue. No biggie.
none that I can think of
no issues that I see immediately
let me know if you'd like me to remove the Chart.yaml version bump

[bitnami/mastodon] replace all instances of JupyterHub with Mastodon in values.yaml

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/README.md
bitnami/postgresql/templates/primary/statefulset.yaml
bitnami/postgresql/values.yaml

add a new option to configure collectors of postgres exporter
allows to switch collectors on/off
for example, to disable wal collector for #20247 or enable collectors that are disabled by default
- fixes #

[bitnami/postgresql] value to configure posgres_exporter collectors

---

bitnami/mastodon/Chart.yaml
bitnami/mastodon/templates/tootctlMediaManagement/cronjob.yaml

Fixes an error preventing the tootctlMediaManagement job from running due to a hard coded configmap name used in the cronjob template.
The container can initialize, run, and complete successfully.
None
- fixes #21110
No changes were needed to README.md as this was bug fix for an issue introduced in https://github.com/bitnami/charts/commit/10711912ed2c3ab5840f1c8196de1ea413deeccd
- [ X] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [ X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] …

[bitnami/mastodon] Fix tootctl media management volume mount

---

bitnami/milvus/Chart.yaml
bitnami/milvus/templates/init-job.yaml

Fix typo using initJob.extraVolumes/extraVolumeMounts

[bitnami/milvus] Fix initJob.extraVolumes

---

bitnami/etcd/Chart.yaml
bitnami/etcd/README.md
bitnami/etcd/values.yaml

Fix the type for the podlabels.
Otherwise it would result in error, when using the chart.
```bash
helm template etcd . --dependency-update --set disasterRecovery.enabled=true
Error: template: etcd/templates/cronjob.yaml:7:71: executing "etcd/templates/cronjob.yaml" at <.Values.disasterRecovery.cronjob.podLabels>: wrong type for value; expected map[string]interface {}; got []interface {}
```
Be able to use the chart without setting extra podLabels for the disasterRecovery cronjob.

[bitnami/etcd] Fix podLabels for disasterRecovery cronjob

---

bitnami/matomo/Chart.yaml
bitnami/matomo/README.md
bitnami/matomo/templates/_helpers.tpl
bitnami/matomo/templates/cronjob.yaml
bitnami/matomo/values.yaml

This version deprecates `cronjobs.enabled` value in favor of `cronjobs.taskScheduler.enabled` and `cronjobs.archive.enabled` values.
We can install each cronjob separately.
- fixes #20567

[bitnami/matomo] Deprecates 'cronjobs.enabled'

---

bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/_helpers.tpl

Force integer conversion in serviceMonitor port.
Fix issue reported in #20668
None
- fixes #20668

[bitnami/mlflow] Fix faulty type conversion in serviceMonitor

---

.github/workflows/ci-pipeline.yml

* Reduce exposure of the `CSP_API_TOKEN` secret.
* Reduce verbosity in the errors reported by `get-chart` step.
* Use GitHub API instead of custom scripts to retrieve modified files in a PR.
Avoid possible injections and reduce the exposure of the secrets.
Malicious user could retrieve `CSP_API_TOKEN` using js scripts in its PR.
Thanks Benoit for sharing this issue.

[charts/*] Hardening CI workflow

---

template/CHART_NAME/templates/service.yaml

The template allows for container and service ports, that are not equal. But the created service is only taking the service port into consideration.
In case the container and service ports are different the target port of the service should be set to the container port.
Template will work, when both ports are set differently.
None, that I know of.
%
https://kubernetes.io/docs/concepts/services-networking/service/#field-spec-ports

[template] add support for non-equal service and container ports

---

.github/workflows/cd-pipeline.yml

Reduce CSP_API_TOKEN exposure.
Token is accesible only by the required job, other jobs doesn't have information about that token.
- Related to https://github.com/bitnami/charts/pull/21265

[bitnami/charts] Reduce CSP_API_TOKEN exposure

---

bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/templates/ingress.yaml

Use `common.ingress` helpers to generate ingress `extraHosts` section
use common.ingress helpers to generate extraHosts entries
Fixes compatibility with ingress syntax
- fixes #21221

[bitname/schema-registry] fix extraHosts entry

---

template/CHART_NAME/templates/daemonset.yaml
template/CHART_NAME/templates/deployment.yaml
template/CHART_NAME/templates/ingress.yaml
template/CHART_NAME/templates/pdb.yaml
template/CHART_NAME/templates/pvc.yaml
template/CHART_NAME/templates/service-account.yaml
template/CHART_NAME/templates/service.yaml
template/CHART_NAME/templates/servicemonitor.yaml
template/CHART_NAME/templates/statefulset.yaml

In #18889 the usage of a new partial was introduced to merge objects together. Unfortunately in the change the parameters were not given correctly to the partial.
_bugfix_
%
%
%

[template] Fix usage of common.tplvalues.merge partial

---

bitnami/suitecrm/Chart.yaml
bitnami/suitecrm/README.md
bitnami/suitecrm/templates/NOTES.txt

SuiteCRM helm chart will be deprecated. 
The latest branch of SuiteCRM 8 has a bug that makes it incompatible with the chart deployment.

[bitnami/suitecrm] Mark SuiteCRM helm chart as deprecated

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
bitnami/mongodb/values.yaml

The modifications allow for more granular control of replica set member settings, such as priority levels, directly through Helm values.
This makes it easier to manage and tune the replica set according to specific requirements and scenarios directly from the Helm chart, without needing manual interventions post-deployment.
The modifications allow for more granular control of replica set member settings, such as priority levels, directly through Helm values.
- fixes https://github.com/bitnami/charts/issues/21291

[bitnami/mongodb]  feat: add node configuration

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/_helpers.tpl
bitnami/mongodb/templates/replicaset/scripts-configmap.yaml

The first issue was resolved in the exporter, specifically within the "_helpers.tpl" file, where the TLS parameters were not being set correctly.
For the second issue, it was identified in the replicaSetConfigurationSettings configuration file, which failed to operate properly with TLS settings. The script intended to manage these settings was unable to execute the configurations as expected, leading to operational discrepancies in replicaSetConfigurationSettings.configuration.

[bitnami/mongodb] fix: metric and reolicaset script issues with tls and mtls

---

bitnami/metrics-server/Chart.yaml
bitnami/metrics-server/templates/_helpers.tpl

The Metrics Server chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/metrics-server] Replace deprecated pull secret partial

---

bitnami/minio/Chart.yaml
bitnami/minio/templates/_helpers.tpl

The MinIO chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/minio] Replace deprecated pull secret partial

---

bitnami/node-exporter/Chart.yaml
bitnami/node-exporter/templates/_helpers.tpl

The node-exporter chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/node-exporter] Replace deprecated pull secret partial

---

bitnami/fluent-bit/Chart.yaml
bitnami/fluent-bit/templates/_helpers.tpl

The FluentBit chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/fluent-bit] Replace deprecated pull secret partial

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/_helpers.tpl

The Elasticsearch chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/elasticsearch] Replace deprecated pull secret partial

---

bitnami/grafana/Chart.yaml
bitnami/grafana/templates/_helpers.tpl

The Grafana chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/grafana] Replace deprecated pull secret partial

---

bitnami/jaeger/Chart.yaml
bitnami/jaeger/templates/_helpers.tpl

The Jaeger chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/jaeger] Replace deprecated pull secret partial

---

bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/templates/_helpers.tpl

The Grafana-Loki chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/grafana-loki] Replace deprecated pull secret partial

---

bitnami/opensearch/Chart.yaml
bitnami/opensearch/templates/_helpers.tpl

The OpenSearch chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/opensearch] Replace deprecated pull secret partial

---

bitnami/logstash/Chart.yaml
bitnami/logstash/templates/_helpers.tpl

The Logstash chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/logstash] Replace deprecated pull secret partial

---

bitnami/kube-state-metrics/Chart.yaml
bitnami/kube-state-metrics/templates/_helpers.tpl

The Kube-State-Metrics chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/kube-state-metrics] Replace deprecated pull secret partial

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/_helpers.tpl

The Nginx chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/nginx] Replace deprecated pull secret partial

---

bitnami/prometheus/Chart.yaml
bitnami/prometheus/templates/_helpers.tpl

The Prometheus chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/prometheus] Replace deprecated pull secret partial

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/_helpers.tpl

The RabbitMQ chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/rabbitmq] Replace deprecated pull secret partial

---

bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/templates/_helpers.tpl

The SonarQube chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/sonarqube] Replace deprecated pull secret partial

---

bitnami/vault/Chart.yaml
bitnami/vault/templates/_helpers.tpl

The Vault chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/vault] Replace deprecated pull secret partial

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/_helpers.tpl

The PostgreSQL chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/postgresql] Replace deprecated pull secret partial

---

bitnami/solr/Chart.yaml
bitnami/solr/templates/statefulset.yaml

Solr: Remove double-defined Probes parameters
Avoid duplicated content

[bitnami/solr] chore: Remove double-defined Probes parameters

---

bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/run/dep-job.yaml
bitnami/mlflow/templates/tracking/deployment.yaml

- fix run.initContainers render
- better formatting of imagePullSecrets
Make it possible to use initContainers with the run component.
N/A
No issue created yet.
N/A

[bitnami/mlflow] Fix run.initContainers render

---

bitnami/zookeeper/Chart.yaml
bitnami/zookeeper/templates/statefulset.yaml

With the YAML 1.2 spec octals must be prefixed with `0o` and not `0`. Parsers implementing the latest spec run into issues.
This commit makes the Zookeeper script mount compliant with YAML 1.2.
None at the moment
See background discussion here: https://github.com/dtolnay/serde-yaml/pull/225

[bitnami/zookeeper] Make Zookeeper DefaultMode YAML 1.2 Compliant

---

bitnami/kafka/Chart.yaml
bitnami/kafka/templates/broker/statefulset.yaml
bitnami/kafka/templates/controller-eligible/statefulset.yaml

With the YAML 1.2 spec octals must be prefixed with `0o` and not `0`. Parsers implementing the latest spec run into issues. 
This commit makes the Kafka script mounts compliant with YAML 1.2.
None at the moment.
See background discussion here: dtolnay/serde-yaml#225

[bitnami/kafka] Make Kafka DefaultMode YAML 1.2 Compliant

---

bitnami/mysql/Chart.yaml
bitnami/mysql/README.md
bitnami/mysql/templates/primary/statefulset.yaml
bitnami/mysql/templates/secondary/statefulset.yaml
bitnami/mysql/values.yaml

Allow to specify a persistentVolumeClaimRetentionPolicy in both the primary and secondary StatefulSet.
This allows for automatic cleanup of PVCs after deletion, etc. An example use case of this is for highly dynamic test environments, where cleaning up the PVCs after deletion of the helm chart is preferred.
None, it needs to be enabled, and the defaults are the same as Kubernetes specifies if it is not defined. 
None.
This is implemented following the same pattern as the postgresql helm chart.

[bitnami/mysql] Allow to set a persistentVolumeClaimRetentionPolicy

---

bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/templates/_helpers.tpl

The PostgreSQL HA chart still uses the deprecated `common.images.pullSecrets` partial to render pull secrets. It was replaced with the recommended replacement `common.images.renderPullSecrets`.
%
%

[bitnami/postgresql-ha] Replace deprecated pull secret partial

---

bitnami/discourse/Chart.yaml
bitnami/discourse/README.md
bitnami/discourse/templates/deployment.yaml
bitnami/discourse/values.yaml

This PR add support for removing "plugins" from the data to persist so the installed plugins are updated based on the `discourse.plugins` parameters.
Easier for users to skip persisting plugins so they're updated on every container restart. 
None
- fixes https://github.com/bitnami/charts/issues/21320
N/A

[bitnami/discourse] Add support for skipping to persist plugins

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/deployment.yaml

This PR ensures we omit `wp-config.php` from the default data to persist (specified via `WORDPRESS_DATA_TO_PERSIST` environment variable) when it's mounted as a read-only file from a secret.
Fixes the workflow below:
```bash
helm install wordpress oci://registry-1.docker.io/bitnamicharts/wordpress
kubectl cp "$(kubectl get pod -o jsonpath='{.items[0].metadata.name}' -l app.kubernetes.io/name=wordpress)":/bitnami/wordpress/wp-config.php wp-config.php
kubectl create secret generic wordpress-config --from-file=wp-config.php
helm upgrade wordpress oci://registry-1.docker.io/bitnamicharts/wordpress --set existingWordPressConfigurationSecret=wordpress-config --set wordpressSkipInstall=true
```
None
- fixes https://github.com/bitnami/charts/issues/20880
Default value for …

[bitnami/wordpress] Omit wp-config.php from data to persist if provided via secret

---

bitnami/matomo/Chart.yaml
bitnami/matomo/README.md
bitnami/matomo/templates/cronjob.yaml
bitnami/matomo/values.yaml

Allows to configure affinity for CronJobs.
Some k8s environments have limitations when attaching volume to more than one pod, eg. when using `rook-ceph` as storage driver you are not able to mount volume to pods assigned to different nodes: https://github.com/rook/rook/issues/4699
Allowing to configure CronJob pods affinity helps to resolve this issue by placing CronJob pods on the same node as Matomo pod.
No known drawbacks.
- workaround for [#20568](https://github.com/bitnami/charts/issues/20568)

[bitnami/matomo] Allow configuring CronJob pods affinity

---

bitnami/opensearch/Chart.yaml
bitnami/opensearch/templates/_helpers.tpl

In #21287 I introduced a way to configure the keys of the TLS secrets.
I was working a lot with ExternalSecrets operator at that time. And somehow after testing I changed the key from `existingSecret` to `externalSecret` in the helper.
Bugfix
None
None
Related PRs:
* #21287

[bitnami/opensearch] fix: Use correct key for existing TLS secrets

---

bitnami/common/Chart.yaml
bitnami/common/templates/_secrets.tpl

Adding two parameters to allow more specific usage of `common.secrets.passwords.manage`:
- **`skipB64enc`**: option to disable return already be converted to base64 encoded string
- **`skipQuote`**: option to disable return already wrapped with quotes
This will allow to further use the secret in other ways when the helper is used.
For example this will allow to use secret templating with [`stringData`](https://kubernetes.io/docs/concepts/configuration/secret/#basic-authentication-secret) instead of `data`:
```yaml
{{- $resName := "foo" }}
{{- $resKey := "bar" }}
kind: Secret
apiVersion: v1
metadata:
name: {{ $resName }}
type: Opaque
stringData: # stringData instead of data
{{ $resKey }}: {{ include "common.secrets.passwords.manage" (dict
"secret" $resName
"key" $resKey
"providedValues" …
```

[bitnami/common] add params skipB64enc and skipQuote to common.secrets.passwords.manage

---

template/CHART_NAME/templates/service.yaml

[bitnami/template]  service.yaml syntax error
Should there be lint before push possibly? For example there could be two normalization steps before template linting:
- `.%%MAIN_OBJECT_BLOCK%%.` can be stripped
- `app.kubernetes.io/component: %%COMPONENT_NAME%%` removed

[bitnami/template] Update service.yaml

---

.github/workflows/cd-pipeline.yml

Reverts bitnami/charts#21612
There are several errors related to the above changes:
* https://github.com/bitnami/charts/actions/runs/7262227519/job/19785026092
* https://github.com/bitnami/charts/actions/runs/7261433171/job/19786370007

Revert "Bump actions/download-artifact from 3.0.2 to 4.0.0"

---

bitnami/common/Chart.yaml
bitnami/common/templates/_secrets.tpl

Fix a minor typo introduced in #21595, that makes MariaDB fails when using `replication`.

[bitnami/common] Fix typo with new line in common.secrets.passwords.manage

---

bitnami/ejbca/Chart.lock
bitnami/ejbca/Chart.yaml
bitnami/ejbca/README.md

[bitnami/ejbca] Upgrade MariaDB 11.2

---

bitnami/jasperreports/Chart.lock
bitnami/jasperreports/Chart.yaml
bitnami/jasperreports/README.md

[bitnami/jasperreports] Upgrade MariaDB 11.2

---

bitnami/joomla/Chart.lock
bitnami/joomla/Chart.yaml
bitnami/joomla/README.md

[bitnami/joomla] Upgrade MariaDB 11.2

---

bitnami/matomo/Chart.lock
bitnami/matomo/Chart.yaml
bitnami/matomo/README.md

[bitnami/matomo] Upgrade MariaDB 11.2

---

bitnami/wordpress/Chart.lock
bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md

[bitnami/wordpress] Upgrade MariaDB 11.2

---

bitnami/opencart/Chart.lock
bitnami/opencart/Chart.yaml
bitnami/opencart/README.md

[bitnami/opencart] Upgrade MariaDB 11.2

---

bitnami/osclass/Chart.lock
bitnami/osclass/Chart.yaml
bitnami/osclass/README.md

[bitnami/osclass] Upgrade MariaDB 11.2

---

bitnami/redmine/Chart.lock
bitnami/redmine/Chart.yaml
bitnami/redmine/README.md

[bitnami/redmine] Upgrade MariaDB 11.2

---

bitnami/drupal/Chart.lock
bitnami/drupal/Chart.yaml
bitnami/drupal/README.md

[bitnami/drupal] Upgrade MariaDB 11.2

---

bitnami/prestashop/Chart.lock
bitnami/prestashop/Chart.yaml
bitnami/prestashop/README.md

[bitnami/prestashop] Upgrade MariaDB 11.2

---

bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml

[bitnami/spring-cloud-dataflow] Upgrade MariaDB 11.2

---

bitnami/phpmyadmin/Chart.lock
bitnami/phpmyadmin/Chart.yaml
bitnami/phpmyadmin/README.md

[bitnami/phpmyadmin] Upgrade MariaDB 11.2

---

bitnami/mediawiki/Chart.lock
bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/README.md

[bitnami/mediawiki] Upgrade MariaDB 11.2

---

bitnami/moodle/Chart.lock
bitnami/moodle/Chart.yaml
bitnami/moodle/README.md

[bitnami/moodle] Upgrade MariaDB 11.2

---

bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md
bitnami/spring-cloud-dataflow/templates/server/deployment.yaml
bitnami/spring-cloud-dataflow/templates/skipper/deployment.yaml
bitnami/spring-cloud-dataflow/values.schema.json
bitnami/spring-cloud-dataflow/values.yaml

Add securityContext to init containers.
Chart can be deployed on clusters with PSA enabled.
None.

[bitnami/scdf] Add securityContext to init containers

---

bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md

Update the Apache subchart to version 10.x.x.

[bitnami/mastodon] Update apache subchart

---

.vib/pinniped/runtime-parameters.yaml

Create secrets and certificates using a name based on the deployment name.
We can run tests using any name. With previous configuration tests only worked if the deployment is called `pinniped`.
None

[bitnami/pinniped] Fix pinniped supervisor references

---

bitnami/fluentd/Chart.yaml
bitnami/fluentd/templates/aggregator-statefulset.yaml
bitnami/fluentd/templates/forwarder-daemonset.yaml

Use the `common.tplvalues.render` partial to render volume and volume mount configs.
Volume and volume mount config can be templated.
None
None
None

[bitnami/fluentd] Render extra volumes and volume mounts

---

.vib/pinniped/ginkgo/scripts/pinniped-auth.sh
.vib/pinniped/runtime-parameters.yaml

Configure `ImpersonationProxy` mode to run tests on clusters with PSA enabled.
Be able to run tests on PSA clusters.
None, this change affects to our tests.
With the default configuration (Token Credential Request API), concierge pods try to create a deployment whose pods need to run in the same node as the `kube-controller-manager` and they have to share particular volumes. So, by design, this configuration won't work on clusters with PSA unless pinniped is deployed in the `kube-system` namespace.
[vib execution](https://github.com/bitnami/charts/actions/runs/7347139444/job/20003059268?pr=21782)

[bitnami/pinniped] Configure impersonationProxy mode to run tests on clusters with PSA enabled

---

.vib/kafka/runtime-parameters.yaml

Enable explicitly in the `runtime-parameters.yaml` file the security context for the autoDiscovery pods.
For some of our internal tests this config has to be set.
None
[vib execution](https://github.com/bitnami/charts/actions/runs/7411422626/job/20165928475?pr=21853)

[bitnami/kafka] Enable securityContext for autoDiscovery pods

---

bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/templates/grafana.yaml

Re-fixes #18249. Applies the labels from `.Values.grafana.labels` to the service and deployment.

[bitnami/grafana-operator] Fix grafana labels on deployment and service

---

.vib/spring-cloud-dataflow/runtime-parameters.yaml

Enable explicitly in the `runtime-parameters.yaml` file the security context for the waitForBackends containers.
For some of our internal tests this config has to be set.
None
[vib execution](https://github.com/bitnami/charts/actions/runs/7447891385/job/20261088333?pr=21884)

[bitnami/spring-cloud-dataflow] Enable securityContext for initContainers

---

bitnami/fluentd/Chart.yaml
bitnami/fluentd/templates/aggregator-statefulset.yaml
bitnami/fluentd/templates/forwarder-daemonset.yaml

When using the `extraGems` key from #21768 with an empty list of extra init containers, the rendered list of init containers on both the aggregator and the forwarder are not valid
Bugfix
None
Is affected by #21768
%

[bitnami/fluentd] bugfix: render additional init containers only if not empty

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/values.yaml

Fix the rendering of parameter `vm_memory_high_watermark` depending if it is `absolute` or `relative`
- fixes #21981

[bitnami/rabbitmq] Fix rendering of vm_memory_high_watermark param

---

bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md
bitnami/mastodon/values.yaml

[bitnami/mastodon] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/jaeger/Chart.yaml
bitnami/jaeger/README.md
bitnami/jaeger/values.yaml

[bitnami/jaeger] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/ghost/Chart.yaml
bitnami/ghost/README.md
bitnami/ghost/values.yaml

[bitnami/ghost] fix: :lock: Do not automount the service account token unless necessary

---

bitnami/zookeeper/Chart.yaml
bitnami/zookeeper/README.md
bitnami/zookeeper/values.yaml

[bitnami/zookeeper] fix: :lock: Do not use the default service account

---

bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/README.md
bitnami/postgresql-ha/values.yaml

[bitnami/postgresql-ha] fix: :lock: Do not use the default service account

---

bitnami/etcd/Chart.yaml
bitnami/etcd/README.md
bitnami/etcd/values.yaml

[bitnami/etcd] fix: :lock: Do not use the default service account

---

bitnami/discourse/Chart.yaml
bitnami/discourse/README.md
bitnami/discourse/values.yaml

This PR creates the service accoutn and disables the automount of the service account token for those components that have no RBAC rules. It This is to comply with Kubernetes security checklists.
- fixes #

[bitnami/discourse] fix: :lock: Do not use the default service account

---

bitnami/mlflow/Chart.yaml
bitnami/mlflow/README.md
bitnami/mlflow/values.yaml

[bitnami/mlflow] fix: :lock: Do not use the default service account

---

bitnami/nginx/Chart.yaml
bitnami/nginx/README.md
bitnami/nginx/values.yaml

[bitnami/nginx] fix: :lock: Do not use the default service account

---

.vib/redis/goss/goss.yaml
.vib/redis/runtime-parameters.yaml
bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/values.yaml

[bitnami/redis] fix: :lock: Do not use the default service account

---

bitnami/supabase/Chart.yaml
bitnami/supabase/values.yaml

Update the supabase-storage image and set the default value for DB_INSTALL_ROLES variable to false, since those roles are created by supabase-postgres.
Use the latest available version for supabase-storage.
N/A
N/A
[Related change](https://github.com/supabase/storage/pull/409)

[bitnami/supabase] Update supabase storage image

---

bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/README.md
bitnami/sonarqube/values.yaml

[bitnami/sonarqube] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/flink/Chart.yaml
bitnami/flink/README.md
bitnami/flink/values.yaml

[bitnami/flink] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/etcd/Chart.yaml
bitnami/etcd/README.md
bitnami/etcd/values.yaml

[bitnami/etcd] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/drupal/Chart.yaml
bitnami/drupal/README.md
bitnami/drupal/values.yaml

[bitnami/drupal] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md
bitnami/wordpress/values.yaml

[bitnami/wordpress] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/whereabouts/Chart.yaml
bitnami/whereabouts/README.md
bitnami/whereabouts/values.yaml

[bitnami/whereabouts] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/kong/Chart.yaml
bitnami/kong/README.md
bitnami/kong/values.yaml

[bitnami/kong] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/README.md
bitnami/grafana-loki/values.yaml

[bitnami/grafana-loki] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/gitea/Chart.yaml
bitnami/gitea/README.md
bitnami/gitea/values.yaml

[bitnami/gitea] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/README.md
bitnami/deepspeed/values.yaml

[bitnami/deepspeed] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/redmine/Chart.yaml
bitnami/redmine/README.md
bitnami/redmine/values.yaml

[bitnami/redmine] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/moodle/Chart.yaml
bitnami/moodle/README.md
bitnami/moodle/values.yaml

[bitnami/moodle] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/milvus/Chart.yaml
bitnami/milvus/README.md
bitnami/milvus/values.yaml

[bitnami/milvus] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/magento/Chart.yaml
bitnami/magento/README.md
bitnami/magento/values.yaml

[bitnami/magento] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/fluent-bit/Chart.yaml
bitnami/fluent-bit/README.md
bitnami/fluent-bit/values.yaml

[bitnami/fluent-bit] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md
bitnami/mastodon/values.yaml

[bitnami/mastodon] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/values.yaml

[bitnami/rabbitmq] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/prestashop/Chart.yaml
bitnami/prestashop/README.md
bitnami/prestashop/values.yaml

[bitnami/prestashop] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/multus-cni/Chart.yaml
bitnami/multus-cni/README.md
bitnami/multus-cni/values.yaml

[bitnami/multus-cni] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/matomo/Chart.yaml
bitnami/matomo/README.md
bitnami/matomo/values.yaml

[bitnami/matomo] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/consul/Chart.yaml
bitnami/consul/README.md
bitnami/consul/values.yaml

[bitnami/consul] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/README.md
bitnami/cassandra/values.yaml

[bitnami/cassandra] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/opencart/Chart.yaml
bitnami/opencart/README.md
bitnami/opencart/values.yaml

[bitnami/opencart] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/nginx/Chart.yaml
bitnami/nginx/README.md
bitnami/nginx/values.yaml

[bitnami/nginx] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/ejbca/Chart.yaml
bitnami/ejbca/README.md
bitnami/ejbca/values.yaml

[bitnami/ejbca] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/appsmith/Chart.yaml
bitnami/appsmith/README.md
bitnami/appsmith/values.yaml

[bitnami/appsmith] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/haproxy/Chart.yaml
bitnami/haproxy/README.md
bitnami/haproxy/values.yaml

[bitnami/haproxy] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/grafana-tempo/Chart.yaml
bitnami/grafana-tempo/README.md
bitnami/grafana-tempo/values.yaml

[bitnami/grafana-tempo] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/dokuwiki/Chart.yaml
bitnami/dokuwiki/README.md
bitnami/dokuwiki/values.yaml

[bitnami/dokuwiki] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/spark/Chart.yaml
bitnami/spark/README.md
bitnami/spark/values.yaml

[bitnami/spark] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/nats/Chart.yaml
bitnami/nats/README.md
bitnami/nats/values.yaml

[bitnami/nats] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/discourse/Chart.yaml
bitnami/discourse/README.md
bitnami/discourse/values.yaml

[bitnami/discourse] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/values.yaml

[bitnami/schema-registry] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/values.yaml

[bitnami/redis] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md
bitnami/oauth2-proxy/values.yaml

[bitnami/oauth2-proxy] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/jenkins/Chart.yaml
bitnami/jenkins/README.md
bitnami/jenkins/values.yaml

[bitnami/jenkins] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/jaeger/Chart.yaml
bitnami/jaeger/README.md
bitnami/jaeger/values.yaml

[bitnami/jaeger] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/README.md
bitnami/cert-manager/templates/NOTES.txt
bitnami/cert-manager/templates/cainjector/rbac.yaml
bitnami/cert-manager/templates/cainjector/secret-namespaced-rbac.yaml
bitnami/cert-manager/templates/controller/rbac.yaml
bitnami/cert-manager/templates/controller/secret-namespaced-rbac.yaml
bitnami/cert-manager/values.yaml

The following PR allows limiting the namespaces that the application can check for secrets. By default, it is using a ClusterRole, which has security implications that should be taken into account by operators.
The default value is to allow secrets to in all namespaces so we don't break upgrades.
- fixes #

[bitnami/cert-manager] feat: :lock: Allow limit access to secrets by namespace

---

bitnami/pytorch/Chart.yaml
bitnami/pytorch/README.md
bitnami/pytorch/values.yaml

[bitnami/pytorch] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/odoo/Chart.yaml
bitnami/odoo/README.md
bitnami/odoo/values.yaml

[bitnami/odoo] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/joomla/Chart.yaml
bitnami/joomla/README.md
bitnami/joomla/values.yaml

[bitnami/joomla] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/jasperreports/Chart.yaml
bitnami/jasperreports/README.md
bitnami/jasperreports/values.yaml

[bitnami/jasperreports] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/ghost/Chart.yaml
bitnami/ghost/README.md
bitnami/ghost/values.yaml

[bitnami/ghost] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/README.md
bitnami/aspnet-core/values.yaml

[bitnami/aspnet-core] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/README.md
bitnami/argo-cd/values.yaml

[bitnami/argo-cd] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/deployment.yaml
bitnami/nginx/templates/health-ingress.yaml
bitnami/nginx/templates/ingress.yaml
bitnami/nginx/templates/svc.yaml

This change will disable the `http` port if `containerPorts.http` is empty.
When using `NodePort` and `http` is not used, it will still occupy a port on the node, even if unused.
If `containerPorts.http` is not set, and the default `readinessProbe` is used, the pod will never reach readiness.
Useful if using only the `https` port.
My specific use-case: I have another application using a defined node port. On installation the nginx-chart is installed first, causing a random node port being assigned to `http`, with a chance of being the same as the defined port for the other application.

[bitnami/nginx] feat: disable http port if containerPorts.http is empty

---

bitnami/nginx/Chart.yaml

bitnami/nginx chart version  was overlapped on these PRs:
* #21567
* #20934
Changes on  #20934 were not released. This new version will force it.
None
- https://github.com/bitnami/charts/actions/runs/7555911541/job/20571855096

[bitnami/nginx] Bump nginx version

---

bitnami/wildfly/Chart.yaml
bitnami/wildfly/README.md
bitnami/wildfly/values.yaml

[bitnami/wildfly] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/README.md
bitnami/mongodb/values.yaml

[bitnami/mongodb] fix: :lock: Improve podSecurityContext and containerSecurityContext with essential security fields

---

.vib/argo-cd/runtime-parameters.yaml

Fixes typo `all` -> `ALL` in Argo CD runtime parameters, affecting TKG deployment.

[bitnami/argo-cd] Fix typo in runtime-parameters.yaml

---

.github/workflows/ci-pipeline.yml

Fixes issue where $source_url is not set if {version} placeholder is not in the URL.
URLs not including {version} placeholder may be intentional in case of upstream not being versioned, and we would like to pull the latest version in case of release event.

github-actions: Fix issue when {version} placeholder not present

---

bitnami/opensearch/Chart.yaml
bitnami/opensearch/templates/coordinating/networkpolicy.yaml
bitnami/opensearch/templates/dashboards/networkpolicy.yaml
bitnami/opensearch/templates/data/networkpolicy.yaml
bitnami/opensearch/templates/ingest/networkpolicy.yaml
bitnami/opensearch/templates/master/networkpolicy.yaml

- The label `app.kubernetes.io/part-of: opensearch` is not added to the pods, so network policy fails to apply.
- Allow access to other opensearch pods when network policy is enabled and default ingress is blocked. This is now the same behavior as on `redis` and `redis-cluster`.
Buildin network policies work as expected.
none
none

[bitnami/opensearch] fix network policy ingress

---

bitnami/spark/Chart.yaml
bitnami/spark/README.md
bitnami/spark/templates/statefulset-master.yaml
bitnami/spark/templates/statefulset-worker.yaml
bitnami/spark/values.yaml

[bitnami/spark] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/templates/statefulset.yaml
bitnami/rabbitmq/values.yaml

[bitnami/rabbitmq] fix: :lock: Move service-account token auto-mount to pod declaration

---

.vib/nginx-ingress-controller/goss/goss.yaml
.vib/nginx-ingress-controller/runtime-parameters.yaml
bitnami/nginx-ingress-controller/Chart.yaml
bitnami/nginx-ingress-controller/README.md
bitnami/nginx-ingress-controller/templates/controller-daemonset.yaml
bitnami/nginx-ingress-controller/templates/controller-deployment.yaml
bitnami/nginx-ingress-controller/templates/default-backend-deployment.yaml
bitnami/nginx-ingress-controller/values.yaml

[bitnami/nginx-ingress-controller] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/nginx/Chart.yaml
bitnami/nginx/README.md
bitnami/nginx/templates/deployment.yaml
bitnami/nginx/values.yaml

[bitnami/nginx] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/mysql/Chart.yaml
bitnami/mysql/README.md
bitnami/mysql/templates/primary/statefulset.yaml
bitnami/mysql/templates/secondary/statefulset.yaml
bitnami/mysql/values.yaml

[bitnami/mysql] fix: :lock: Move service-account token auto-mount to pod declaration

---

.vib/milvus/goss/goss.yaml
.vib/milvus/runtime-parameters.yaml
bitnami/milvus/Chart.yaml
bitnami/milvus/README.md
bitnami/milvus/templates/attu/deployment.yaml
bitnami/milvus/templates/data-coordinator/deployment.yaml
bitnami/milvus/templates/data-node/deployment.yaml
bitnami/milvus/templates/index-coordinator/deployment.yaml
bitnami/milvus/templates/index-node/deployment.yaml
bitnami/milvus/templates/init-job.yaml
bitnami/milvus/templates/proxy/deployment.yaml
bitnami/milvus/templates/query-coordinator/deployment.yaml
bitnami/milvus/templates/query-node/deployment.yaml
bitnami/milvus/templates/root-coordinator/deployment.yaml
bitnami/milvus/values.yaml

[bitnami/milvus] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/mariadb/Chart.yaml
bitnami/mariadb/README.md
bitnami/mariadb/templates/primary/statefulset.yaml
bitnami/mariadb/templates/secondary/statefulset.yaml
bitnami/mariadb/values.yaml

[bitnami/mariadb] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/kiam/Chart.yaml
bitnami/kiam/README.md
bitnami/kiam/templates/agent/agent-daemonset.yaml
bitnami/kiam/templates/server/server-daemonset.yaml
bitnami/kiam/templates/server/server-deployment.yaml
bitnami/kiam/values.yaml

[bitnami/kiam] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/grafana-mimir/Chart.yaml
bitnami/grafana-mimir/README.md
bitnami/grafana-mimir/templates/alertmanager/statefulset.yaml
bitnami/grafana-mimir/templates/compactor/statefulset.yaml
bitnami/grafana-mimir/templates/distributor/deployment.yaml
bitnami/grafana-mimir/templates/gateway/deployment.yaml
bitnami/grafana-mimir/templates/ingester/statefulset.yaml
bitnami/grafana-mimir/templates/overrides-exporter/deployment.yaml
bitnami/grafana-mimir/templates/querier/deployment.yaml
bitnami/grafana-mimir/templates/query-frontend/deployment.yaml
bitnami/grafana-mimir/templates/query-scheduler/deployment.yaml
bitnami/grafana-mimir/templates/ruler/deployment.yaml
bitnami/grafana-mimir/templates/store-gateway/statefulset.yaml
bitnami/grafana-mimir/values.yaml

[bitnami/grafana-mimir] fix: :lock: Move service-account token auto-mount to pod declaration

---

.vib/fluent-bit/goss/goss.yaml
.vib/fluent-bit/runtime-parameters.yaml
bitnami/fluent-bit/Chart.yaml
bitnami/fluent-bit/README.md
bitnami/fluent-bit/templates/daemonset.yaml
bitnami/fluent-bit/templates/deployment.yaml
bitnami/fluent-bit/values.yaml

[bitnami/fluent-bit] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/etcd/Chart.yaml
bitnami/etcd/README.md
bitnami/etcd/templates/statefulset.yaml
bitnami/etcd/values.yaml

[bitnami/etcd] fix: :lock: Move service-account token auto-mount to pod declaration

---

.vib/deepspeed/goss/goss.yaml
.vib/deepspeed/runtime-parameters.yaml
bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/README.md
bitnami/deepspeed/templates/client/client-dep-job.yaml
bitnami/deepspeed/templates/worker/worker-statefulset.yaml
bitnami/deepspeed/values.yaml

[bitnami/deepspeed] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/tomcat/Chart.yaml
bitnami/tomcat/README.md
bitnami/tomcat/templates/_helpers.tpl
bitnami/tomcat/templates/_pod.tpl
bitnami/tomcat/templates/serviceaccount.yaml
bitnami/tomcat/values.yaml

[bitnami/tomcat] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/README.md
bitnami/cert-manager/templates/controller/networkpolicy.yaml
bitnami/cert-manager/templates/webhook/networkpolicy.yaml
bitnami/cert-manager/values.yaml

Add Network Policies templates
Allow the users to configure Ingress/Egress Network Policies
- [ X ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ X ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [ X ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ X ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)

[bitnami/cert-manager] Add Network Policies

---

bitnami/multus-cni/Chart.yaml
bitnami/multus-cni/README.md
bitnami/multus-cni/templates/daemonset.yaml
bitnami/multus-cni/values.yaml

[bitnami/multus-cni] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/jenkins/Chart.yaml
bitnami/jenkins/README.md
bitnami/jenkins/templates/deployment.yaml
bitnami/jenkins/values.yaml

[bitnami/jenkins] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/whereabouts/Chart.yaml
bitnami/whereabouts/README.md
bitnami/whereabouts/values.yaml

This PR enables the readiness probe, which was disabled for no reason.
The chart will use the already implemented probe.
None.
NA.
NA.

[bitnami/whereabouts] Enable readinessProbe by default

---

.github/workflows/ci-pipeline.yml

Remove exception to use GITHUB_TOKEN when action actor is 'bitnami-bot'.

[github-actions] update-pr: Use BITNAMI_BOT_TOKEN instead of GITHUB_TOKEN when pushing changes

---

bitnami/moodle/Chart.yaml
bitnami/moodle/README.md
bitnami/moodle/templates/_helpers.tpl
bitnami/moodle/templates/deployment.yaml
bitnami/moodle/templates/serviceaccount.yaml
bitnami/moodle/values.yaml

[bitnami/moodle] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/wildfly/Chart.yaml
bitnami/wildfly/README.md
bitnami/wildfly/templates/deployment.yaml
bitnami/wildfly/values.yaml

[bitnami/wildfly] fix: :lock: Move service-account token auto-mount to pod declaration

---

.vib/oauth2-proxy/goss/goss.yaml
.vib/oauth2-proxy/runtime-parameters.yaml
bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md
bitnami/oauth2-proxy/templates/deployment.yaml
bitnami/oauth2-proxy/values.yaml

[bitnami/oauth2-proxy] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/matomo/Chart.yaml
bitnami/matomo/README.md
bitnami/matomo/templates/deployment.yaml
bitnami/matomo/values.yaml

[bitnami/matomo] fix: :lock: Move service-account token auto-mount to pod declaration

---

.vib/mastodon/goss/goss.yaml
.vib/mastodon/runtime-parameters.yaml
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md
bitnami/mastodon/templates/init-job/init-job.yaml
bitnami/mastodon/templates/sidekiq/deployment.yaml
bitnami/mastodon/templates/streaming/deployment.yaml
bitnami/mastodon/templates/web/deployment.yaml
bitnami/mastodon/values.yaml

[bitnami/mastodon] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/joomla/Chart.yaml
bitnami/joomla/README.md
bitnami/joomla/templates/_helpers.tpl
bitnami/joomla/templates/deployment.yaml
bitnami/joomla/templates/serviceaccount.yaml
bitnami/joomla/values.yaml

[bitnami/joomla] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/supabase/Chart.yaml
bitnami/supabase/templates/studio/deployment.yaml
bitnami/supabase/templates/studio/service.yaml

The svc on supabase-studio was not able to reach the port in the containers.

[bitnam/supabase] Fix supabase studio svc

---

bitnami/jasperreports/Chart.yaml
bitnami/jasperreports/README.md
bitnami/jasperreports/templates/_helpers.tpl
bitnami/jasperreports/templates/deployment.yaml
bitnami/jasperreports/templates/serviceaccount.yaml
bitnami/jasperreports/values.yaml

[bitnami/jasperreports] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/ejbca/Chart.yaml
bitnami/ejbca/README.md
bitnami/ejbca/templates/_helpers.tpl
bitnami/ejbca/templates/deployment.yaml
bitnami/ejbca/templates/serviceaccount.yaml
bitnami/ejbca/values.yaml

[bitnami/ejbca] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/dokuwiki/Chart.yaml
bitnami/dokuwiki/README.md
bitnami/dokuwiki/templates/_helpers.tpl
bitnami/dokuwiki/templates/deployment.yaml
bitnami/dokuwiki/templates/serviceaccount.yaml
bitnami/dokuwiki/values.yaml

[bitnami/dokuwiki] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/consul/Chart.yaml
bitnami/consul/README.md
bitnami/consul/templates/_helpers.tpl
bitnami/consul/templates/serviceaccount.yaml
bitnami/consul/templates/statefulset.yaml
bitnami/consul/values.yaml

[bitnami/consul] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/README.md
bitnami/grafana-loki/templates/compactor/deployment.yaml
bitnami/grafana-loki/templates/distributor/deployment.yaml
bitnami/grafana-loki/templates/gateway/deployment.yaml
bitnami/grafana-loki/templates/index-gateway/statefulset.yaml
bitnami/grafana-loki/templates/ingester/statefulset.yaml
bitnami/grafana-loki/templates/promtail/daemonset.yaml
bitnami/grafana-loki/templates/querier/statefulset.yaml
bitnami/grafana-loki/templates/query-frontend/deployment.yaml
bitnami/grafana-loki/templates/query-scheduler/deployment.yaml
bitnami/grafana-loki/templates/ruler/statefulset.yaml
bitnami/grafana-loki/templates/table-manager/deployment.yaml
bitnami/grafana-loki/values.yaml

[bitnami/grafana-loki] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/grafana/Chart.yaml
bitnami/grafana/README.md
bitnami/grafana/templates/deployment.yaml
bitnami/grafana/values.yaml

[bitnami/grafana] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/opencart/Chart.yaml
bitnami/opencart/README.md
bitnami/opencart/templates/_helpers.tpl
bitnami/opencart/templates/deployment.yaml
bitnami/opencart/templates/serviceaccount.yaml
bitnami/opencart/values.yaml

[bitnami/opencart] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/magento/templates/serviceaccount.yaml
bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/README.md
bitnami/mediawiki/templates/_helpers.tpl
bitnami/mediawiki/templates/deployment.yaml
bitnami/mediawiki/templates/serviceaccount.yaml
bitnami/mediawiki/values.yaml

[bitnami/mediawiki] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/pytorch/Chart.yaml
bitnami/pytorch/README.md
bitnami/pytorch/templates/_helpers.tpl
bitnami/pytorch/templates/deployment.yaml
bitnami/pytorch/templates/serviceaccount.yaml
bitnami/pytorch/templates/statefulset.yaml
bitnami/pytorch/values.yaml

[bitnami/pytorch] fix: :lock: Move service-account token auto-mount to pod declaration

---

bitnami/supabase/Chart.yaml
bitnami/supabase/templates/studio/service.yaml
bitnami/supabase/values.yaml

- Updates the studio container image to the latest one that has the redirection fixed.
- Fix studio service target port
- fixes #20914

[bitnami/studio] Updates container image version + fix studio svc target port

---

bitnami/wildfly/Chart.yaml
bitnami/wildfly/README.md
bitnami/wildfly/values.yaml

[bitnami/wildfly] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/values.yaml

[bitnami/schema-registry] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/pytorch/Chart.yaml
bitnami/pytorch/README.md
bitnami/pytorch/values.yaml

[bitnami/pytorch] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/pinniped/Chart.yaml
bitnami/pinniped/README.md
bitnami/pinniped/values.yaml

[bitnami/pinniped] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/README.md
bitnami/mediawiki/values.yaml

[bitnami/mediawiki] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/jenkins/Chart.yaml
bitnami/jenkins/README.md
bitnami/jenkins/values.yaml

[bitnami/jenkins] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/opencart/Chart.yaml
bitnami/opencart/README.md
bitnami/opencart/values.yaml

[bitnami/opencart] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/haproxy/Chart.yaml
bitnami/haproxy/README.md
bitnami/haproxy/values.yaml

[bitnami/haproxy] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/grafana-mimir/Chart.yaml
bitnami/grafana-mimir/README.md
bitnami/grafana-mimir/values.yaml

[bitnami/grafana-mimir] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/README.md
bitnami/grafana-loki/values.yaml

[bitnami/grafana-loki] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/grafana/Chart.yaml
bitnami/grafana/README.md
bitnami/grafana/values.yaml

[bitnami/grafana] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/flink/Chart.yaml
bitnami/flink/README.md
bitnami/flink/values.yaml

[bitnami/flink] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/etcd/Chart.yaml
bitnami/etcd/README.md
bitnami/etcd/values.yaml

[bitnami/etcd] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/drupal/Chart.yaml
bitnami/drupal/README.md
bitnami/drupal/values.yaml

[bitnami/drupal] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/README.md
bitnami/deepspeed/values.yaml

[bitnami/deepspeed] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/README.md
bitnami/argo-cd/values.yaml

[bitnami/argo-cd] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/apache/Chart.yaml
bitnami/apache/README.md
bitnami/apache/values.yaml

[bitnami/apache] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/moodle/Chart.yaml
bitnami/moodle/README.md
bitnami/moodle/values.yaml

[bitnami/moodle] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/clickhouse/Chart.yaml
bitnami/clickhouse/README.md
bitnami/clickhouse/templates/networkpolicy.yaml
bitnami/clickhouse/values.yaml

 [bitnami/clickhouse] feat: 🔒 Enable networkPolicy 

---

bitnami/dokuwiki/Chart.yaml
bitnami/dokuwiki/README.md
bitnami/dokuwiki/values.yaml

[bitnami/dokuwiki] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md
bitnami/wordpress/values.yaml

[bitnami/wordpress] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/redmine/Chart.yaml
bitnami/redmine/README.md
bitnami/redmine/values.yaml

[bitnami/redmine] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/prestashop/Chart.yaml
bitnami/prestashop/README.md
bitnami/prestashop/values.yaml

[bitnami/prestashop] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md
bitnami/oauth2-proxy/values.yaml

[bitnami/oauth2-proxy] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/nginx/Chart.yaml
bitnami/nginx/README.md
bitnami/nginx/values.yaml

[bitnami/nginx] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/mysql/Chart.yaml
bitnami/mysql/README.md
bitnami/mysql/values.yaml

[bitnami/mysql] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/README.md
bitnami/mongodb/values.yaml

[bitnami/mongodb] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/matomo/Chart.yaml
bitnami/matomo/README.md
bitnami/matomo/values.yaml

[bitnami/matomo] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md
bitnami/mastodon/values.yaml

[bitnami/mastodon] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/jasperreports/Chart.yaml
bitnami/jasperreports/README.md
bitnami/jasperreports/values.yaml

[bitnami/jasperreports] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/gitea/Chart.yaml
bitnami/gitea/README.md
bitnami/gitea/values.yaml

[bitnami/gitea] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/discourse/Chart.yaml
bitnami/discourse/README.md
bitnami/discourse/values.yaml

[bitnami/discourse] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/README.md
bitnami/cert-manager/values.yaml

[bitnami/cert-manager] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/README.md
bitnami/aspnet-core/values.yaml

[bitnami/aspnet-core] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/appsmith/Chart.yaml
bitnami/appsmith/README.md
bitnami/appsmith/values.yaml

[bitnami/appsmith] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/vault/Chart.yaml
bitnami/vault/README.md
bitnami/vault/templates/csi-provider/networkpolicy.yaml
bitnami/vault/templates/injector/networkpolicy.yaml
bitnami/vault/templates/server/networkpolicy.yaml
bitnami/vault/values.yaml

[bitnami/vault] feat: :lock: Enable networkPolicy

---

bitnami/spark/Chart.yaml
bitnami/spark/README.md
bitnami/spark/values.yaml

[bitnami/spark] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/phpmyadmin/Chart.yaml
bitnami/phpmyadmin/README.md
bitnami/phpmyadmin/values.yaml

[bitnami/phpmyadmin] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/jaeger/Chart.yaml
bitnami/jaeger/README.md
bitnami/jaeger/values.yaml

[bitnami/jaeger] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/consul/Chart.yaml
bitnami/consul/README.md
bitnami/consul/values.yaml

[bitnami/consul] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/README.md
bitnami/cassandra/values.yaml

[bitnami/cassandra] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/odoo/Chart.yaml
bitnami/odoo/templates/_helpers.tpl

The deployment cannot find the secret with external database password and fails to start.
This change makes consistent definition between the secret for the external database password with the deployment secret definition.
The pod will start without errors
Unknown
- fixes #14741
I tried to run the CI action on my side, but It didn't work, and I don't know if it's because of some specifications for the project itself.

[bitnami/odoo] Fix secret name for external database password

---

bitnami/odoo/Chart.yaml
bitnami/odoo/README.md
bitnami/odoo/values.yaml

[bitnami/odoo] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/milvus/Chart.yaml
bitnami/milvus/README.md
bitnami/milvus/values.yaml

[bitnami/milvus] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/magento/Chart.yaml
bitnami/magento/README.md
bitnami/magento/values.yaml

[bitnami/magento] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/fluent-bit/Chart.yaml
bitnami/fluent-bit/README.md
bitnami/fluent-bit/values.yaml

[bitnami/fluent-bit] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/ejbca/Chart.yaml
bitnami/ejbca/README.md
bitnami/ejbca/values.yaml

[bitnami/ejbca] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/kafka/Chart.yaml
bitnami/kafka/templates/broker/statefulset.yaml
bitnami/kafka/templates/controller-eligible/statefulset.yaml

Applies same fix from https://github.com/bitnami/charts/pull/15816 to kafka chart.
- fixes same issue as described in https://github.com/bitnami/charts/issues/15526 for kafka
Only impact is a rolling restart of the deployment due to the helm chart version change.

[bitnami/kafka] Add missing version, kind to volumeClaimTemplates

---

bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/templates/alertmanager/alertmanager.yaml
bitnami/kube-prometheus/templates/prometheus/prometheus.yaml

When neither annotations nor labels are given for the `volumeClaimTemplate`s xof the Prometheus or Alertmanager custom resource, the metadata block of that resource renders to `null`, which is not valid and fails a deployment.
So in case there is neither an annotation nor a label given, just don't render the metadata block at all.
Bugfix
None
None

[bitnami/kube-prometheus] Omit empty metadata blocks in volume claim templates of Prometheus and Alertmanager

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/values.yaml

[bitnami/rabbitmq] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/nats/Chart.yaml
bitnami/nats/README.md
bitnami/nats/values.yaml

[bitnami/nats] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/multus-cni/Chart.yaml
bitnami/multus-cni/README.md
bitnami/multus-cni/values.yaml

[bitnami/multus-cni] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/joomla/Chart.yaml
bitnami/joomla/README.md
bitnami/joomla/values.yaml

[bitnami/joomla] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/ghost/Chart.yaml
bitnami/ghost/README.md
bitnami/ghost/values.yaml

[bitnami/ghost] fix: :bug: Set seLinuxOptions to null for Openshift compatibility

---

bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/README.md
bitnami/sonarqube/templates/NOTES.txt
bitnami/sonarqube/templates/deployment.yaml
bitnami/sonarqube/templates/externaldb-secret.yaml
bitnami/sonarqube/templates/ingress.yaml
bitnami/sonarqube/templates/install_plugins.yaml
bitnami/sonarqube/templates/jmx-configmap.yaml
bitnami/sonarqube/templates/jmx-metrics-svc.yaml
bitnami/sonarqube/templates/jmx-servicemonitor.yaml
bitnami/sonarqube/templates/networkpolicy.yaml
bitnami/sonarqube/templates/pvc.yaml
bitnami/sonarqube/templates/secret.yaml
bitnami/sonarqube/templates/service-account.yaml
bitnami/sonarqube/templates/service.yaml
bitnami/sonarqube/templates/tls-secret.yaml
bitnami/sonarqube/values.yaml

[bitnami/sonarqube] feat: :lock: Enable networkPolicy

---

bitnami/mlflow/Chart.yaml
bitnami/mlflow/README.md
bitnami/mlflow/templates/tracking/deployment.yaml
bitnami/mlflow/templates/tracking/externals3-secret.yaml
bitnami/mlflow/values.schema.json
bitnami/mlflow/values.yaml

This patch introduces a new value `externalS3.useCredentialsInSecret` that lets users opt out of setting AWS credentials for connecting to S3 using a kubernetes secret.
When this value is set to `true` (the default), the chart behaves in the exact same way as before, creating and/or referencing a secret for setting the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` variables.
When this value is set to `false`, `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` are not set and no secret is created and/or referenced.
Previously, enabling external S3 meant that the chart was setting the `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` environment variables with values from a kubernetes secret. However, users may want to use other means of providing these credentials, e.g. on EKS, where it's …

[bitnami/mlflow] feat: 🔒 make S3 secret optional

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/values.yaml

This PR disables the memoryHighWatermark feature in RabbitMQ by default. It was accidentally enabled in this other PR
https://github.com/bitnami/charts/pull/22203/files#diff-4196e2902de7c60cf9b84763119ec51216bf72ff7ec6917e94e3feaadb1b7dd3
Chart keeps unchanged
None
- fixes this unexpected change
https://github.com/bitnami/charts/pull/22203/files#diff-4196e2902de7c60cf9b84763119ec51216bf72ff7ec6917e94e3feaadb1b7dd3

[bitnami/rabbitmq] Disable memoryHighWatermark by default in RabbitMQ

---

bitnami/grafana/Chart.yaml
bitnami/grafana/templates/deployment.yaml

In the Grafana chart some re sources, that are mounted to the container, allow for templated names. Others don't.
This change enables templating for all resources.
Streamlining. All resources  work the same.
None
None
None

[bitnami/grafana] Enable templating of all volumes and volumeMounts

---

bitnami/fluentd/Chart.yaml
bitnami/fluentd/templates/aggregator-statefulset.yaml
bitnami/fluentd/templates/forwarder-daemonset.yaml

Put extra env vars through `common.tplvalues.render` helper, before rendering to containers.
Templating of extra env vars possible.
None
None
None

[bitnami/fluentd] Allow templating of extra env vars

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/storegateway/statefulset-sharded.yaml

Fixing the way we retreive the revisionHistoryLimit from the Values for thanos storegateway
Fixes the chart
None
- fixes #

[bitnami/thanos] Fix revisionHistoryLimit for thanos storegateway

---

bitnami/memcached/Chart.yaml
bitnami/memcached/templates/statefulset.yaml

Removes the value for `replicas` in the Statefulset, if autoscaling is enabled.
Prevents a livelock with ArgoCD (possibly other gitops clients..) which terminates the pods created by the HPA, if the Statefulset has another specified value.
- compliments #8408 (it highlighted that replicas are set on the statefulset when autoscaling is enabled, but didn't fix it.)
- fixex #22743 created as documentation for the unfinished business of #8390.

[bitnami/memcached] CHANGE remove replicas in statefulset if autoscaling + HA #22743

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/master/serviceaccount.yaml

Since 18.8.3 (https://github.com/bitnami/charts/pull/22716) no service account is created with architecture set to standalone.
In this case the serviceaccount and application condition didn't match for master (instead the condition for replicas was used for the master service account).
- fixes #22746

[bitnami/redis]: Fix standalone redis missing service account

---

.vib/kubernetes-event-exporter/ginkgo/integration_suite_test.go

Include `securityContext` config in test pods created by ginkgo.
These changes allow running ginkgo tests on clusters with PSA enabled.
None
[vib execution](https://github.com/bitnami/charts/actions/runs/7696596394/job/20971772449?pr=22828)

[bitnami/kubernetes-event-exporter] Set security context in ginkgo tests

---

.vib/haproxy/runtime-parameters.yaml

This PR adapts the `securityContext` of the testing NGINX pod with the same config introduced in https://github.com/bitnami/charts/commit/b17d6aeceb48ce6686b60ced1861753d9ea4596e
The chart tests work in a TKG cluster
None

[bitnami/haproxy] Fix securityContext for testing env

---

bitnami/opensearch/Chart.yaml
bitnami/opensearch/templates/_helpers.tpl

Put secret names through `common.tplvalues.render` helper, before rendering to containers.
Templating of extra env vars possible.
None
None
None

[bitnami/opensearch] Allow templating of secret names

---

.vib/flux/runtime-parameters.yaml

This PR, in addition to https://github.com/mdhont/podinfo/pull/1, should fix Flux testing deployment in TKG.

[bitnami/flux] Fix flux tests, do not disable dokuwiki securityContexts

---

bitnami/pinniped/Chart.yaml
bitnami/pinniped/README.md
bitnami/pinniped/templates/concierge/networkpolicy.yaml
bitnami/pinniped/templates/supervisor/networkpolicy.yaml
bitnami/pinniped/values.yaml

[bitnami/pinniped] feat: :lock: Enable networkPolicy

---

bitnami/nginx-ingress-controller/Chart.yaml
bitnami/nginx-ingress-controller/README.md
bitnami/nginx-ingress-controller/templates/controller-networkpolicy.yaml
bitnami/nginx-ingress-controller/templates/default-backend-networkpolicy.yaml
bitnami/nginx-ingress-controller/values.yaml

[bitnami/nginx-ingress-controller] feat: :lock: Enable networkPolicy

---

bitnami/pytorch/Chart.yaml
bitnami/pytorch/README.md
bitnami/pytorch/templates/networkpolicy.yaml
bitnami/pytorch/values.yaml

[bitnami/pytorch] feat: :lock: Enable networkPolicy

---

bitnami/jupyterhub/Chart.yaml

When https://github.com/bitnami/charts/pull/22735 was merged the version bump collided with another bump (https://github.com/bitnami/charts/pull/22799), so at this moment the CD job is failing. This PR bumps the chart version so the changes included in the previously mentioned PR will be released.

[bitnami/jupyterhub] Bump chart version

---

.github/workflows/ci-pipeline.yml

Adds several enhancements to the automatic CRDs update workflow to increase its coverage.
The new features are:
- `# Conditional` - Adds a conditional {{if}}/{{end}} to the downloaded upstream CRD
- `# VersionOf` - Name of a subcomponent, its version will be used for CRD tracking instead of the main component version
- `# UseKustomize` - If set to true, uses Kustomize to render the CRDs
- `# RequiresFilter` - If set to true, uses yq to filter resources having 'kind: CustomResourceDefinition', useful when using 'install.yaml' file as upstream source 
Increase automatic CRD coverage from 7 out of 16, to 15 out of 16. 
The only exception is `cert-manager`, since upstream uses templating that needs to be manually modified.
- Base feature (Source + Version)
- bitnami/argo-cd
- …

github-actions: Enhancements for automatic CRDs update feature

---

bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/networkpolicy.yaml
bitnami/redis-cluster/templates/redis-statefulset.yaml

- Changes "contanierPorts" to "containerPorts" on `redis-cluster` templates.
- `serviceMonitors` resources fixed
- fixes typo on `redis-cluster` helm chart templates

[bitnami/redis-cluster] Small typo fix on redis-cluster templates

---

bitnami/zookeeper/Chart.yaml
bitnami/zookeeper/README.md
bitnami/zookeeper/templates/networkpolicy.yaml
bitnami/zookeeper/values.yaml

[bitnami/zookeeper] fix: :bug: Add allowExternalEgress to avoid breaking istio

---

bitnami/spark/Chart.yaml
bitnami/spark/README.md
bitnami/spark/templates/networkpolicy-master.yaml
bitnami/spark/templates/networkpolicy-worker.yaml
bitnami/spark/values.yaml

[bitnami/spark] fix: :bug: Add allowExternalEgress to avoid breaking istio

---

.vib/redis/goss/goss.yaml

Adds single quotes to Redis auth to avoid issues in systems with Bash history substitution enabled

[bitnami/redis] Add single quotes in goss test to avoid history search substitution

---

bitnami/mysql/Chart.yaml
bitnami/mysql/README.md
bitnami/mysql/templates/networkpolicy.yaml
bitnami/mysql/templates/primary/statefulset.yaml
bitnami/mysql/templates/secondary/statefulset.yaml
bitnami/mysql/values.yaml

[bitnami/mysql] feat: :lock: Enable networkPolicy

---

bitnami/memcached/Chart.yaml
bitnami/memcached/README.md
bitnami/memcached/templates/networkpolicy.yaml
bitnami/memcached/values.yaml

[bitnami/memcached] feat: :lock: Enable networkPolicy

---

bitnami/jaeger/Chart.yaml
bitnami/jaeger/README.md
bitnami/jaeger/templates/agent/networkpolicy.yaml
bitnami/jaeger/templates/collector/networkpolicy.yaml
bitnami/jaeger/templates/migrate-networkpolicy.yaml
bitnami/jaeger/templates/query/networkpolicy.yaml
bitnami/jaeger/values.yaml

[bitnami/jaeger] feat: :lock: Enable networkPolicy

---

bitnami/kong/Chart.yaml
bitnami/kong/README.md
bitnami/kong/templates/migrate-job-networkpolicy.yaml
bitnami/kong/templates/networkpolicy.yaml
bitnami/kong/values.yaml

[bitnami/kong] feat: :lock: Enable networkPolicy

---

bitnami/flink/Chart.yaml
bitnami/flink/README.md
bitnami/flink/templates/jobmanager/networkpolicy.yaml
bitnami/flink/templates/taskmanager/networkpolicy.yaml
bitnami/flink/values.yaml

[bitnami/flink] feat: :lock: Enable networkPolicy

---

bitnami/moodle/Chart.yaml
bitnami/moodle/templates/_helpers.tpl
bitnami/moodle/templates/deployment.yaml

[bitnami/moodle] : fix the usage of `existingSecret` like other helm chart 
bitnami standard
.
- fixes #23214
.
- [ x] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)

[bitnami/moodle] fix MOODLE_PASSWORD with existingSecrets

---

bitnami/consul/Chart.yaml
bitnami/consul/README.md
bitnami/consul/templates/networkpolicy.yaml
bitnami/consul/values.yaml

[bitnami/consul] feat: :lock: Enable networkPolicy

---

bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/values.yaml

Follow up of https://github.com/bitnami/charts/pull/22515, this PR fixes the chart installation in Openshift clusters.With the current logic, the pods launched by jupyterhub will use the default securityContext, which hardcodes the user to `1001`. This (and other) policy is invalid in Openshift and will result in a pod deployment failure.
The chart installs successfully in Openshift
None

[bitnami/jupyterhub] Fix securityContext in Openshift clusters

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/README.md
bitnami/cassandra/templates/NOTES.txt
bitnami/cassandra/templates/_helpers.tpl
bitnami/cassandra/templates/cassandra-secret.yaml
bitnami/cassandra/templates/headless-svc.yaml
bitnami/cassandra/templates/metrics-configmap.yaml
bitnami/cassandra/templates/networkpolicy.yaml
bitnami/cassandra/templates/pdb.yaml
bitnami/cassandra/templates/service.yaml
bitnami/cassandra/templates/serviceaccount.yaml
bitnami/cassandra/templates/servicemonitor.yaml
bitnami/cassandra/templates/statefulset.yaml
bitnami/cassandra/templates/tls-secret.yaml
bitnami/cassandra/values.yaml

[bitnami/cassandra] feat: :lock: Enable networkPolicy

---

bitnami/fluent-bit/Chart.yaml
bitnami/fluent-bit/README.md
bitnami/fluent-bit/templates/networkpolicy.yaml
bitnami/fluent-bit/values.yaml

[bitnami/fluent-bit] feat: :lock: Enable networkPolicy

---

bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/README.md
bitnami/argo-workflows/templates/controller/networkpolicy.yaml
bitnami/argo-workflows/templates/server/networkpolicy.yaml
bitnami/argo-workflows/values.yaml

[bitnami/argo-workflows] feat: :lock: Enable networkPolicy

---

bitnami/matomo/Chart.yaml
bitnami/matomo/templates/cronjob.yaml

I tried to use custom certificates (using [`certificates`](https://github.com/bitnami/charts/tree/main/bitnami/matomo#certificate-injection-parameters) and I found a bug. Secret with certificate is correctly mounted on application container, but not on `CronJob` ones.
After reviewing chart code I found out that that in `CronJob` there is `volume` for custom certificates, but `volumeMounts` are missing.
I have deployed chart after changes and everything worked.
Code should be backwards compatible.
- fixes #23211.

[bitnami/matomo] Bugfix: missing volumeMounts for custom certificates in CronJob

---

.vib/discourse/runtime-parameters.yaml
bitnami/jasperreports/Chart.yaml

[bitnami/jasperreports] Mark JasperReports chart as deprecated

---

bitnami/common/Chart.yaml
bitnami/common/templates/_resources.tpl
bitnami/common/templates/_warnings.tpl

This PR adds support for a future improvement in our charts: resource presets. Currently, Bitnami charts do not set the `resources` object by default. While it is true that this is a task of the operator to adapt the resources to their use case, we do not explicitly mention in our documentation that a deployment without resources is not recommended for production. 
The PR adds a helper for defining the resources based on a set of presets (nano, micro, small...), which will be configured in our charts by default to the smallest size that works in our testing. This value will be called `resourcesPreset` , and will be superseded if the user sets the already existing `resources` value. Additionally, we will add warnings explaining …

[bitnami/common] feat: :sparkles: Add support for resource presets

---

bitnami/apisix/Chart.yaml
bitnami/apisix/README.md
bitnami/apisix/templates/control-plane/networkpolicy.yaml
bitnami/apisix/templates/dashboard/networkpolicy.yaml
bitnami/apisix/templates/data-plane/networkpolicy.yaml
bitnami/apisix/templates/ingress-controller/networkpolicy.yaml
bitnami/apisix/values.yaml

[bitnami/apisix] feat: :lock: Enable networkPolicy

---

bitnami/osclass/Chart.yaml
bitnami/osclass/README.md
bitnami/osclass/templates/NOTES.txt

Osclass helm chart will be deprecated.

[bitnami/osclass] Mark Osclass chart as deprecated

---

bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/networkpolicy.yaml

This adds the rabbitmq port 15672 to the network policy for the topology operator allowing it to access the rabbitmq api for performing changes.
This will allow the topology operator to create resources within the rabbitmq cluster again, otherwise connections would time out when creating users, permissions, etc. 
```json
{
"level": "error",
"ts": "2024-02-14T10:09:18Z",
"msg": "Reconciler error",
"controller": "user",
"controllerGroup": "rabbitmq.com",
"controllerKind": "User",
"User": {
"name": "hello-world-example",
"namespace": "default"
},
"namespace": "default",
"name": "hello-world-example",
"reconcileID": "d8a36e0e-88c9-4240-8054-7fa358e00cbc",
"error": "Put \"http://hello-world.default.svc:15672/api/users/AFu_qP-3iogUYqq1QpjI0ck9-IOqUpgv\": dial tcp 10.43.168.83:15672: i/o …
```

[bitnami/rabbitmq-cluster-operator] fix: 🐛 Add RabbitMQ port to NetworkPolicy for Topology Operator

---

bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/templates/skipper/networkpolicy.yaml

This PR fixes disabling the creation of networkPolicy when we set `networkPolicy.enabled` to `false`.
In my case I want to deploy Spring Cloud Skipper and not create a networkPolicy.
I noticed that when I have (by default) skipper.enabled set to true then by default a networkPolicy is created.
When You add networkPolicy.enabled false, then the networkPolicy is still being created because of the bug in networkpolicy template.
I was using SpringCloudDataFlow HelmChart in 2 versions:
- 23.1.4
- 26.5.3
In both cases the results were the same.
It should be possible to disable creation of networkPolicy.

[bitnami/spring-cloud-dataflow] Fixing disabling skipper networkPolicy creation

---

bitnami/kafka/Chart.yaml
bitnami/kafka/README.md
bitnami/kafka/templates/provisioning/job.yaml
bitnami/kafka/values.yaml

This PR adds the option `provisioning.useHelmHooks` to allow disabling the helm hooks for the provisioning job. By default they will be enabled as before.
Disabling the hooks in combination with setting `provisioning.waitForKafka` to `true` (default value) there still won't be any failure with backoff happening.
* Allows to use `--wait` or even `--atomic` when trying to install the chart with provisioning.
* Allows to use helm's chart tester tool for `ct install` tests (the tool depends on the `--wait` flag).
* The job (and pod) will not be automatically removed (when disabling helm hooks)
Not having this option blocks us completely from using chart tester running on an umbrella chart with kafka as a dependency. In that umbrella chart there are init containers which wait until provisioned …

[bitnami/kafka] Add useHelmHooks value to allow install with --wait

---

bitnami/tomcat/Chart.yaml
bitnami/tomcat/README.md
bitnami/tomcat/templates/_helpers.tpl
bitnami/tomcat/templates/_pod.tpl
bitnami/tomcat/templates/secrets.yaml
bitnami/tomcat/values.yaml

Add existing secret management
Be able to use an existing kubernetes secret to set the tomcat password
No drawback identified
No applicable issue
Tested locally to prevent any regression

[bitnami/tomcat] Add existing secret management

---

bitnami/supabase/Chart.yaml
bitnami/supabase/templates/studio/ingress.yaml

This uses the correct port name of Supabase Studio service in  the Ingress of the Supabase Studio.
Studio Ingress works again
None
- fixes #20914

[bitnami/supabase] use correct servicePort name for studio ingress

---

bitnami/mariadb-galera/Chart.yaml
bitnami/mariadb-galera/templates/statefulset.yaml

This PR refactors all the readonlyrootfs emptydirs to one
- fixes #

[bitnami/mariadb-galera] chore: :recycle: Move all emptydirs to one

---

bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml
bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml

Applies same fix from https://github.com/bitnami/charts/pull/15816 to mongodb-sharded chart.
Fixes same issue as described in https://github.com/bitnami/charts/issues/15526 for mongodb-sharded

[bitnami/mongodb-sharded] Fix: Add missing version, kind to volumeClaimTemplates

---

bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/deployment.yaml

This fixes a subPath that was falsely declared to be a mountPath in the influxdb deployment. The duplicate mountPath caused problems with deployments that checked the correctness of the yaml.
The chart version was increased by a patch version to 5.17.1.
Automated deployments will not reject the update due to invalid yaml.
None, known.
- Fixes #23861

[bitnami/influxdb] Remove duplicate mountpath in influxdb deployment

---

bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/values.yaml

- fixes a bug where when setting global.imageRegistry some images were still using docker.io
global.imageRegistry will be respected in all images, preventing application not starting up due to imagePullbackOff. 
None
I encountered this issue when deployed the helm chart in environment with a private registry, and got this error when the server got launched.

[bitnami/jupyterhub] Fix global image registry not being respected in jupyterhub configuration

---

bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/templates/postgresql/witness-statefulset.yaml

in postgres-ha witness-statefullset init-chmod-data securityContext contains "enabled: true" which is not allowed.
aligned it to the securityContext from postgres init-chmod-data where the enabled field is omited from the securityContext
does not fail in k8 1.29.x
- fixes #

[bitnami/postgres-ha]: strict decoding error: unknown field "spec.template.spec.initContainers[0].securityContext.enabled"

---

.vib/nats/ginkgo/nats_test.go

Delaying the removal of pods during the tests to allow the application sync the data and make them more stable
This other PR will succeed with the changes 
https://github.com/bitnami/charts/pull/23810
None
- fixes https://github.com/bitnami/charts/pull/23810
Pods are removed quickly and changes are not synced

[bitnami/nats] Give the application some time to sync the data during the tests

---

bitnami/keycloak/Chart.lock
bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md

This PR updates the bundled bitnami/postgresql subchart to its new major (see https://github.com/bitnami/charts/pull/22750), bumping the keycloak version in a major as well

[bitnami/keycloak] Update bundled PostgreSQL

---

bitnami/harbor/Chart.lock
bitnami/harbor/Chart.yaml
bitnami/harbor/README.md

This PR updates the bundled bitnami/postgresql subchart to its new major (see https://github.com/bitnami/charts/pull/22750), bumping the harbor version in a major as well

[bitnami/harbor] Update bundled PostgreSQL

---

bitnami/redmine/Chart.lock
bitnami/redmine/Chart.yaml
bitnami/redmine/README.md

This PR updates the bundled bitnami/postgresql and bitnami/mariadb subcharts to the new major (see https://github.com/bitnami/charts/pull/22750 and https://github.com/bitnami/charts/pull/23054), bumping the redmine version in a major as well

[bitnami/redmine] Update bundled PostgreSQL and MariaDB

---

bitnami/wordpress/Chart.lock
bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md

This PR updates the bundled bitnami/mariadb subchart to the new major (see https://github.com/bitnami/charts/pull/23054), bumping the wordpress version in a major as well

[bitnami/wordpress] Update bundled MariaDB

---

bitnami/milvus/Chart.lock
bitnami/milvus/Chart.yaml
bitnami/milvus/README.md

This PR updates the bundled bitnami/mariadb subchart to the new major (see https://github.com/bitnami/charts/pull/22058), bumping the milvus version in a major as well

[bitnami/milvus] Update bundled MinIO

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/headless-svc.yaml

Similar to https://github.com/bitnami/charts/issues/15526, this removes the empty annotations entry on the headless service (set by the helm chart) so that instead it is contemplated with the conditionals.
This causes annotations that are set outside of the chart (like Google's automatic `cloud.google.com/neg`) to constantly be OutOfSync in ArgoCD:
ArgoCD will no longer try to remove automatic annotations set outside of the helm chart.

[bitnami/redis] Fix ordering of annotations

---

bitnami/airflow/Chart.lock
bitnami/airflow/Chart.yaml
bitnami/airflow/README.md

This PR updates the bundled bitnami/postgresql subchart to its new major (see https://github.com/bitnami/charts/pull/22750), bumping the airflow version in a major as well

[bitnami/airflow] Update bundled PostgreSQL

---

bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/templates/cluster-operator/networkpolicy.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/networkpolicy.yaml

This change fixes the network policies templates, which reference an incorrect metrics port (when `metrics.enabled` is true). This affects both the cluster and messaging topology operators.
- fixes #23427

[bitnami/rabbitmq-cluster-operator] fix: correct network policy port for metrics

---

bitnami/jupyterhub/Chart.lock
bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/README.md

This PR updates the bundled bitnami/postgresql subchart to its new major (see https://github.com/bitnami/charts/pull/22750), bumping the jupyterhub version in a major as well

[bitnami/jupyterhub] Update bundled PostgreSQL

---

bitnami/common/Chart.yaml
bitnami/common/templates/_compatibility.tpl

This PR adds the `_compatibility.tpl` file, where we can define helpers for making our charts compatible with more platforms out of the box.
The idea would be having a section in values.yaml called `compatibility`, having different flags for platforms.
For example, right now our charts in Openshift fail in the `restricted-v1` SCC with the following error:
```
Warning  FailedCreate  13d (x17 over 13d)      replicaset-controller  Error creating: pods "apisix-ingress-controller-d58bf646c-" is forbidden: unable to validate against any security context constraint: [provider "anyuid": Forbidden: not usable by user or serviceaccount, provider restricted-v2: .spec.securityContext.fsGroup: Invalid value: []int64{1001}: 1001 is not an …
```

[bitnami/common] feat: :sparkles: :lock: Add compatibility support for securityContext in Openshift restricted-v1 SCC

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/coordinating/statefulset.yaml
bitnami/elasticsearch/templates/data/statefulset.yaml
bitnami/elasticsearch/templates/ingest/statefulset.yaml
bitnami/elasticsearch/templates/master/statefulset.yaml

This PR fixes an issue with `extraRoles` and `ELASTICSEARCH_NODE_ROLES`. The value is not properly rendered (note the square brackets in the extra role):
```shell
$ helm template . --set 'master.extraRoles[0]=remote_cluster_client' | grep -B1 remote_cluster_client
- name: ELASTICSEARCH_NODE_ROLES
value: "master,[remote_cluster_client]"
```
- fixes #23562
Tested with:
```shell
$ helm template . | grep -A1 ELASTICSEARCH_NODE_ROLES
- name: ELASTICSEARCH_NODE_ROLES
value: ""
--
- name: ELASTICSEARCH_NODE_ROLES
value: "data"
--
- name: ELASTICSEARCH_NODE_ROLES
value: "ingest"
--
- name: ELASTICSEARCH_NODE_ROLES
value: "master"
```
```shell
$ helm template . --set 'master.extraRoles[0]=remote_cluster_client' --set 'data.extraRoles[0]=remote_cluster_client' --set …
```

[bitnami/elasticsearch] Fix values for ELASTICSEARCH_NODE_ROLES

---

bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/templates/promtail/daemonset.yaml

Remove the label `loki-gossip-member: "true"` from Promtail pods
This label `loki-gossip-member: "true"` is used as a pod selector by the `gossip-ring-headless-service`. By removing it from the Promtail pods specification,  the service will no longer try to forward traffic to promtail pods (instead of loki pods).
- fixes #23939

[bitnami/grafana-loki] Remove the label `Loki-gossip-member: "true"` from Promtail pods

---

bitnami/elasticsearch/Chart.yaml

Follow-up of #23845. The version was not actually bumped on `main`; the conflict was auto-resolved silently.

[bitnami/elasticsearch] Bump chart version again

---

bitnami/grafana/Chart.yaml
bitnami/grafana/templates/deployment.yaml

This PR fixes the mount point of the providers to allow conflicts when building the empty-dir based conf folder (which is necessary for readonlyrootfs support)
- fixes https://github.com/bitnami/charts/issues/24042

[bitnami/grafana] fix: :bug: Change mount-point of providers to conf.default

---

bitnami/clickhouse/Chart.lock
bitnami/clickhouse/Chart.yaml
bitnami/clickhouse/README.md
bitnami/clickhouse/templates/statefulset.yaml
bitnami/clickhouse/values.yaml

[bitnami/clickhouse] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/redis/Chart.lock
bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/templates/master/application.yaml
bitnami/redis/templates/replicas/application.yaml
bitnami/redis/templates/sentinel/statefulset.yaml
bitnami/redis/values.yaml

[bitnami/redis] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/spark/Chart.lock
bitnami/spark/Chart.yaml
bitnami/spark/README.md
bitnami/spark/templates/statefulset-master.yaml
bitnami/spark/templates/statefulset-worker.yaml
bitnami/spark/values.yaml

[bitnami/spark] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/memcached/Chart.lock
bitnami/memcached/Chart.yaml
bitnami/memcached/README.md
bitnami/memcached/templates/deployment.yaml
bitnami/memcached/templates/statefulset.yaml
bitnami/memcached/values.yaml

[bitnami/memcached] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/keycloak/Chart.lock
bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/templates/keycloak-config-cli-job.yaml
bitnami/keycloak/templates/statefulset.yaml
bitnami/keycloak/values.yaml

[bitnami/keycloak] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/flux/Chart.lock
bitnami/flux/Chart.yaml
bitnami/flux/README.md
bitnami/flux/templates/helm-controller/deployment.yaml
bitnami/flux/templates/image-automation-controller/deployment.yaml
bitnami/flux/templates/image-reflector-controller/deployment.yaml
bitnami/flux/templates/kustomize-controller/deployment.yaml
bitnami/flux/templates/notification-controller/deployment.yaml
bitnami/flux/templates/source-controller/deployment.yaml
bitnami/flux/values.yaml

[bitnami/flux] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/mariadb/Chart.lock
bitnami/mariadb/Chart.yaml
bitnami/mariadb/README.md
bitnami/mariadb/templates/primary/statefulset.yaml
bitnami/mariadb/templates/secondary/statefulset.yaml
bitnami/mariadb/values.yaml

[bitnami/mariadb] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/zookeeper/Chart.lock
bitnami/zookeeper/Chart.yaml
bitnami/zookeeper/README.md
bitnami/zookeeper/templates/statefulset.yaml
bitnami/zookeeper/values.yaml

[bitnami/zookeeper] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/whereabouts/Chart.lock
bitnami/whereabouts/Chart.yaml
bitnami/whereabouts/README.md
bitnami/whereabouts/templates/daemonset.yaml
bitnami/whereabouts/values.yaml

[bitnami/whereabouts] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/vault/Chart.lock
bitnami/vault/Chart.yaml
bitnami/vault/README.md
bitnami/vault/templates/csi-provider/daemonset.yaml
bitnami/vault/templates/injector/deployment.yaml
bitnami/vault/templates/server/statefulset.yaml
bitnami/vault/values.yaml

[bitnami/vault] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/tensorflow-resnet/Chart.lock
bitnami/tensorflow-resnet/Chart.yaml
bitnami/tensorflow-resnet/README.md
bitnami/tensorflow-resnet/templates/deployment.yaml
bitnami/tensorflow-resnet/values.yaml

[bitnami/tensorflow-resnet] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/redmine/Chart.yaml
bitnami/redmine/README.md
bitnami/redmine/templates/cronjob.yaml
bitnami/redmine/templates/deployment.yaml
bitnami/redmine/values.yaml

[bitnami/redmine] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/pytorch/Chart.lock
bitnami/pytorch/Chart.yaml
bitnami/pytorch/README.md
bitnami/pytorch/templates/_helpers.tpl
bitnami/pytorch/templates/deployment.yaml
bitnami/pytorch/templates/statefulset.yaml
bitnami/pytorch/values.yaml

[bitnami/pytorch] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/mysql/Chart.lock
bitnami/mysql/Chart.yaml
bitnami/mysql/README.md
bitnami/mysql/templates/primary/statefulset.yaml
bitnami/mysql/templates/secondary/statefulset.yaml
bitnami/mysql/values.yaml

[bitnami/mysql] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/moodle/Chart.lock
bitnami/moodle/Chart.yaml
bitnami/moodle/README.md
bitnami/moodle/templates/deployment.yaml
bitnami/moodle/values.yaml

[bitnami/moodle] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/matomo/Chart.lock
bitnami/matomo/Chart.yaml
bitnami/matomo/README.md
bitnami/matomo/templates/cronjob.yaml
bitnami/matomo/templates/deployment.yaml
bitnami/matomo/values.yaml

[bitnami/matomo] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/kiam/Chart.lock
bitnami/kiam/Chart.yaml
bitnami/kiam/README.md
bitnami/kiam/templates/agent/agent-daemonset.yaml
bitnami/kiam/templates/server/server-daemonset.yaml
bitnami/kiam/templates/server/server-deployment.yaml
bitnami/kiam/values.yaml

[bitnami/kiam] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/jupyterhub/Chart.lock
bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/README.md
bitnami/jupyterhub/templates/hub/deployment.yaml
bitnami/jupyterhub/templates/image-puller/daemonset.yaml
bitnami/jupyterhub/templates/proxy/deployment.yaml
bitnami/jupyterhub/values.yaml

[bitnami/jupyterhub] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/influxdb/Chart.lock
bitnami/influxdb/Chart.yaml
bitnami/influxdb/README.md
bitnami/influxdb/templates/cronjob-backup.yaml
bitnami/influxdb/templates/deployment.yaml
bitnami/influxdb/values.yaml

[bitnami/influxdb] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/grafana-tempo/Chart.lock
bitnami/grafana-tempo/Chart.yaml
bitnami/grafana-tempo/README.md
bitnami/grafana-tempo/templates/compactor/deployment.yaml
bitnami/grafana-tempo/templates/distributor/deployment.yaml
bitnami/grafana-tempo/templates/ingester/statefulset.yaml
bitnami/grafana-tempo/templates/metrics-generator/deployment.yaml
bitnami/grafana-tempo/templates/querier/deployment.yaml
bitnami/grafana-tempo/templates/query-frontend/deployment.yaml
bitnami/grafana-tempo/templates/vulture/deployment.yaml
bitnami/grafana-tempo/values.yaml

[bitnami/grafana-tempo] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/fluentd/Chart.lock
bitnami/fluentd/Chart.yaml
bitnami/fluentd/README.md
bitnami/fluentd/templates/aggregator-statefulset.yaml
bitnami/fluentd/templates/forwarder-daemonset.yaml
bitnami/fluentd/values.yaml

[bitnami/fluentd] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/contour/Chart.lock
bitnami/contour/Chart.yaml
bitnami/contour/README.md
bitnami/contour/templates/certgen/job.yaml
bitnami/contour/templates/contour/deployment.yaml
bitnami/contour/templates/default-backend/deployment.yaml
bitnami/contour/templates/envoy/daemonset.yaml
bitnami/contour/templates/envoy/deployment.yaml
bitnami/contour/values.yaml

[bitnami/contour] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/external-dns/Chart.lock
bitnami/external-dns/Chart.yaml
bitnami/external-dns/README.md
bitnami/external-dns/templates/dep-ds.yaml
bitnami/external-dns/values.yaml

[bitnami/external-dns] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/kong/Chart.lock
bitnami/kong/Chart.yaml
bitnami/kong/README.md
bitnami/kong/templates/dep-ds.yaml
bitnami/kong/templates/migrate-job.yaml
bitnami/kong/values.yaml

[bitnami/kong] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/cassandra/Chart.lock
bitnami/cassandra/Chart.yaml
bitnami/cassandra/README.md
bitnami/cassandra/templates/statefulset.yaml
bitnami/cassandra/values.yaml

[bitnami/cassandra] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/solr/Chart.lock
bitnami/solr/Chart.yaml
bitnami/solr/README.md
bitnami/solr/templates/metrics-deployment.yaml
bitnami/solr/templates/statefulset.yaml
bitnami/solr/values.yaml

[bitnami/solr] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/prometheus/Chart.lock
bitnami/prometheus/Chart.yaml
bitnami/prometheus/README.md
bitnami/prometheus/templates/alertmanager/statefulset.yaml
bitnami/prometheus/templates/server/deployment.yaml
bitnami/prometheus/values.yaml

[bitnami/prometheus] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/node-exporter/Chart.lock
bitnami/node-exporter/Chart.yaml
bitnami/node-exporter/README.md
bitnami/node-exporter/templates/daemonset.yaml
bitnami/node-exporter/values.yaml

[bitnami/node-exporter] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/minio/Chart.yaml
bitnami/minio/README.md
bitnami/minio/templates/distributed/statefulset.yaml
bitnami/minio/templates/provisioning-job.yaml
bitnami/minio/templates/standalone/deployment.yaml
bitnami/minio/values.yaml

[bitnami/minio] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/appsmith/Chart.lock
bitnami/appsmith/Chart.yaml
bitnami/appsmith/README.md
bitnami/appsmith/templates/_helpers.tpl
bitnami/appsmith/templates/backend/deployment.yaml
bitnami/appsmith/templates/client/deployment.yaml
bitnami/appsmith/templates/rts/deployment.yaml
bitnami/appsmith/values.yaml

[bitnami/appsmith] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/dokuwiki/Chart.lock
bitnami/dokuwiki/Chart.yaml
bitnami/dokuwiki/README.md
bitnami/dokuwiki/templates/deployment.yaml
bitnami/dokuwiki/values.yaml

[bitnami/dokuwiki] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/airflow/Chart.lock
bitnami/airflow/Chart.yaml
bitnami/airflow/README.md
bitnami/airflow/templates/_git_helpers.tpl
bitnami/airflow/templates/_helpers.tpl
bitnami/airflow/templates/config/configmap.yaml
bitnami/airflow/templates/metrics/deployment.yaml
bitnami/airflow/templates/scheduler/deployment.yaml
bitnami/airflow/templates/web/deployment.yaml
bitnami/airflow/templates/worker/statefulset.yaml
bitnami/airflow/values.yaml

[bitnami/airflow] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/argo-cd/Chart.lock
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/README.md
bitnami/argo-cd/templates/application-controller/deployment.yaml
bitnami/argo-cd/templates/applicationset/deployment.yaml
bitnami/argo-cd/templates/dex/deployment.yaml
bitnami/argo-cd/templates/notifications/bots/slack/deployment.yaml
bitnami/argo-cd/templates/notifications/deployment.yaml
bitnami/argo-cd/templates/repo-server/deployment.yaml
bitnami/argo-cd/templates/server/deployment.yaml
bitnami/argo-cd/values.yaml

[bitnami/argo-cd] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/argo-workflows/Chart.lock
bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/README.md
bitnami/argo-workflows/templates/controller/deployment.yaml
bitnami/argo-workflows/templates/server/deployment.yaml
bitnami/argo-workflows/values.yaml

[bitnami/argo-workflows] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/cert-manager/Chart.lock
bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/README.md
bitnami/cert-manager/templates/cainjector/deployment.yaml
bitnami/cert-manager/templates/controller/deployment.yaml
bitnami/cert-manager/templates/webhook/deployment.yaml
bitnami/cert-manager/values.yaml

[bitnami/cert-manager] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/concourse/Chart.lock
bitnami/concourse/Chart.yaml
bitnami/concourse/README.md
bitnami/concourse/templates/web/deployment.yaml
bitnami/concourse/templates/worker/deployment.yaml
bitnami/concourse/templates/worker/statefulset.yaml
bitnami/concourse/values.yaml

[bitnami/concourse] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/consul/Chart.lock
bitnami/consul/Chart.yaml
bitnami/consul/README.md
bitnami/consul/templates/statefulset.yaml
bitnami/consul/values.yaml

[bitnami/consul] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/ejbca/Chart.lock
bitnami/ejbca/Chart.yaml
bitnami/ejbca/README.md
bitnami/ejbca/templates/deployment.yaml
bitnami/ejbca/values.yaml

[bitnami/ejbca] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/fluent-bit/Chart.lock
bitnami/fluent-bit/Chart.yaml
bitnami/fluent-bit/README.md
bitnami/fluent-bit/templates/daemonset.yaml
bitnami/fluent-bit/templates/deployment.yaml
bitnami/fluent-bit/values.yaml

[bitnami/fluent-bit] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/ghost/Chart.lock
bitnami/ghost/Chart.yaml
bitnami/ghost/README.md
bitnami/ghost/templates/deployment.yaml
bitnami/ghost/values.yaml

[bitnami/ghost] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/haproxy/Chart.lock
bitnami/haproxy/Chart.yaml
bitnami/haproxy/README.md
bitnami/haproxy/templates/deployment.yaml
bitnami/haproxy/values.yaml

[bitnami/haproxy] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/kuberay/Chart.lock
bitnami/kuberay/Chart.yaml
bitnami/kuberay/README.md
bitnami/kuberay/templates/apiserver/deployment.yaml
bitnami/kuberay/templates/cluster/raycluster.yaml
bitnami/kuberay/templates/operator/deployment.yaml
bitnami/kuberay/values.yaml

[bitnami/kuberay] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/mongodb-sharded/Chart.lock
bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/README.md
bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml
bitnami/mongodb-sharded/templates/mongos/mongos-dep-sts.yaml
bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml
bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
bitnami/mongodb-sharded/values.yaml

[bitnami/mongodb-sharded] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/multus-cni/Chart.lock
bitnami/multus-cni/Chart.yaml
bitnami/multus-cni/README.md
bitnami/multus-cni/templates/daemonset.yaml
bitnami/multus-cni/values.yaml

[bitnami/multus-cni] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/oauth2-proxy/Chart.lock
bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md
bitnami/oauth2-proxy/templates/deployment.yaml
bitnami/oauth2-proxy/values.yaml

[bitnami/oauth2-proxy] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/odoo/Chart.yaml
bitnami/odoo/README.md
bitnami/odoo/templates/deployment.yaml
bitnami/odoo/values.yaml

[bitnami/odoo] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/opencart/Chart.lock
bitnami/opencart/Chart.yaml
bitnami/opencart/README.md
bitnami/opencart/templates/deployment.yaml
bitnami/opencart/values.yaml

[bitnami/opencart] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/phpbb/Chart.lock
bitnami/phpbb/Chart.yaml
bitnami/phpbb/README.md
bitnami/phpbb/templates/deployment.yaml
bitnami/phpbb/values.yaml

[bitnami/phpbb] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/pinniped/Chart.lock
bitnami/pinniped/Chart.yaml
bitnami/pinniped/README.md
bitnami/pinniped/templates/concierge/deployment.yaml
bitnami/pinniped/templates/supervisor/deployment.yaml
bitnami/pinniped/values.yaml

[bitnami/pinniped] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/prestashop/Chart.lock
bitnami/prestashop/Chart.yaml
bitnami/prestashop/README.md
bitnami/prestashop/templates/deployment.yaml
bitnami/prestashop/values.yaml

[bitnami/prestashop] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/rabbitmq-cluster-operator/Chart.lock
bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/README.md
bitnami/rabbitmq-cluster-operator/templates/cluster-operator/deployment.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/deployment.yaml
bitnami/rabbitmq-cluster-operator/values.yaml

[bitnami/rabbitmq-cluster-operator] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/redis-cluster/Chart.lock
bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/README.md
bitnami/redis-cluster/templates/redis-statefulset.yaml
bitnami/redis-cluster/templates/update-cluster.yaml
bitnami/redis-cluster/values.yaml

[bitnami/redis-cluster] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/schema-registry/Chart.lock
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/templates/statefulset.yaml
bitnami/schema-registry/values.yaml

[bitnami/schema-registry] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/tomcat/Chart.lock
bitnami/tomcat/Chart.yaml
bitnami/tomcat/README.md
bitnami/tomcat/templates/_pod.tpl
bitnami/tomcat/values.yaml

[bitnami/tomcat] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/wildfly/Chart.lock
bitnami/wildfly/Chart.yaml
bitnami/wildfly/README.md
bitnami/wildfly/templates/deployment.yaml
bitnami/wildfly/values.yaml

[bitnami/wildfly] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/thanos/Chart.lock
bitnami/thanos/Chart.yaml
bitnami/thanos/README.md
bitnami/thanos/templates/bucketweb/deployment.yaml
bitnami/thanos/templates/compactor/_pod-template.tpl
bitnami/thanos/templates/query-frontend/deployment.yaml
bitnami/thanos/templates/query/deployment.yaml
bitnami/thanos/templates/receive-distributor/deployment.yaml
bitnami/thanos/templates/receive/statefulset.yaml
bitnami/thanos/templates/ruler/statefulset.yaml
bitnami/thanos/templates/storegateway/statefulset-sharded.yaml
bitnami/thanos/templates/storegateway/statefulset.yaml
bitnami/thanos/values.yaml

[bitnami/thanos] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml
bitnami/discourse/README.md
bitnami/discourse/templates/deployment.yaml
bitnami/discourse/values.yaml

[bitnami/discourse] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/etcd/Chart.lock
bitnami/etcd/Chart.yaml
bitnami/etcd/README.md
bitnami/etcd/templates/cronjob.yaml
bitnami/etcd/templates/statefulset.yaml
bitnami/etcd/values.yaml

[bitnami/etcd] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/kube-state-metrics/Chart.lock
bitnami/kube-state-metrics/Chart.yaml
bitnami/kube-state-metrics/README.md
bitnami/kube-state-metrics/templates/deployment.yaml
bitnami/kube-state-metrics/values.yaml

[bitnami/kube-state-metrics] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/kubeapps/Chart.lock
bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/README.md
bitnami/kubeapps/templates/apprepository/apprepositories.yaml
bitnami/kubeapps/templates/apprepository/deployment.yaml
bitnami/kubeapps/templates/dashboard/deployment.yaml
bitnami/kubeapps/templates/frontend/deployment.yaml
bitnami/kubeapps/templates/kubeappsapis/deployment.yaml
bitnami/kubeapps/values.yaml

[bitnami/kubeapps] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/kubernetes-event-exporter/Chart.lock
bitnami/kubernetes-event-exporter/Chart.yaml
bitnami/kubernetes-event-exporter/README.md
bitnami/kubernetes-event-exporter/templates/deployment.yaml
bitnami/kubernetes-event-exporter/values.yaml

[bitnami/kubernetes-event-exporter] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/magento/Chart.lock
bitnami/magento/Chart.yaml
bitnami/magento/README.md
bitnami/magento/templates/deployment.yaml
bitnami/magento/values.yaml

[bitnami/magento] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/mariadb-galera/Chart.lock
bitnami/mariadb-galera/Chart.yaml
bitnami/mariadb-galera/README.md
bitnami/mariadb-galera/templates/statefulset.yaml
bitnami/mariadb-galera/values.yaml

[bitnami/mariadb-galera] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md
bitnami/mastodon/templates/_helpers.tpl
bitnami/mastodon/templates/init-job/init-job.yaml
bitnami/mastodon/templates/sidekiq/deployment.yaml
bitnami/mastodon/templates/streaming/deployment.yaml
bitnami/mastodon/templates/web/deployment.yaml
bitnami/mastodon/values.yaml

[bitnami/mastodon] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/mediawiki/Chart.lock
bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/README.md
bitnami/mediawiki/templates/deployment.yaml
bitnami/mediawiki/values.yaml

[bitnami/mediawiki] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/metallb/Chart.lock
bitnami/metallb/Chart.yaml
bitnami/metallb/README.md
bitnami/metallb/templates/controller/deployment.yaml
bitnami/metallb/templates/speaker/daemonset.yaml
bitnami/metallb/values.yaml

[bitnami/metallb] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/metrics-server/Chart.lock
bitnami/metrics-server/Chart.yaml
bitnami/metrics-server/README.md
bitnami/metrics-server/templates/deployment.yaml
bitnami/metrics-server/values.yaml

[bitnami/metrics-server] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/sonarqube/Chart.lock
bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/README.md
bitnami/sonarqube/templates/deployment.yaml
bitnami/sonarqube/values.yaml

[bitnami/sonarqube] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/apisix/Chart.lock
bitnami/apisix/Chart.yaml
bitnami/apisix/README.md
bitnami/apisix/templates/_helpers.tpl
bitnami/apisix/templates/control-plane/dep-ds.yaml
bitnami/apisix/templates/dashboard/deployment.yaml
bitnami/apisix/templates/data-plane/dep-ds.yaml
bitnami/apisix/templates/ingress-controller/deployment.yaml
bitnami/apisix/values.yaml

[bitnami/apisix] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/deepspeed/Chart.lock
bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/README.md
bitnami/deepspeed/templates/_helpers.tpl
bitnami/deepspeed/templates/client/client-dep-job.yaml
bitnami/deepspeed/templates/worker/worker-statefulset.yaml
bitnami/deepspeed/values.yaml

[bitnami/deepspeed] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/kafka/Chart.lock
bitnami/kafka/Chart.yaml
bitnami/kafka/README.md
bitnami/kafka/templates/_helpers.tpl
bitnami/kafka/templates/broker/statefulset.yaml
bitnami/kafka/templates/controller-eligible/statefulset.yaml
bitnami/kafka/templates/metrics/deployment.yaml
bitnami/kafka/templates/provisioning/job.yaml
bitnami/kafka/values.yaml

[bitnami/kafka] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/opensearch/Chart.lock
bitnami/opensearch/Chart.yaml
bitnami/opensearch/README.md
bitnami/opensearch/templates/_helpers.tpl
bitnami/opensearch/templates/coordinating/statefulset.yaml
bitnami/opensearch/templates/dashboards/deployment.yaml
bitnami/opensearch/templates/data/statefulset.yaml
bitnami/opensearch/templates/ingest/statefulset.yaml
bitnami/opensearch/templates/master/statefulset.yaml
bitnami/opensearch/values.yaml

[bitnami/opensearch] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/jaeger/Chart.lock
bitnami/jaeger/Chart.yaml
bitnami/jaeger/README.md
bitnami/jaeger/templates/_helpers.tpl
bitnami/jaeger/templates/agent/deployment.yaml
bitnami/jaeger/templates/collector/deployment.yaml
bitnami/jaeger/templates/migrate-job.yaml
bitnami/jaeger/templates/query/deployment.yaml
bitnami/jaeger/values.yaml

[bitnami/jaeger] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/grafana-loki/Chart.lock
bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/README.md
bitnami/grafana-loki/templates/compactor/deployment.yaml
bitnami/grafana-loki/templates/distributor/deployment.yaml
bitnami/grafana-loki/templates/gateway/deployment.yaml
bitnami/grafana-loki/templates/index-gateway/statefulset.yaml
bitnami/grafana-loki/templates/ingester/statefulset.yaml
bitnami/grafana-loki/templates/promtail/daemonset.yaml
bitnami/grafana-loki/templates/querier/statefulset.yaml
bitnami/grafana-loki/templates/query-frontend/deployment.yaml
bitnami/grafana-loki/templates/query-scheduler/deployment.yaml
bitnami/grafana-loki/templates/ruler/statefulset.yaml
bitnami/grafana-loki/templates/table-manager/deployment.yaml
bitnami/grafana-loki/values.yaml

[bitnami/grafana-loki] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/nginx/Chart.lock
bitnami/nginx/Chart.yaml
bitnami/nginx/README.md
bitnami/nginx/templates/deployment.yaml
bitnami/nginx/values.yaml

[bitnami/nginx] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/joomla/Chart.lock
bitnami/joomla/Chart.yaml
bitnami/joomla/README.md
bitnami/joomla/templates/deployment.yaml
bitnami/joomla/values.yaml

[bitnami/joomla] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/flink/Chart.lock
bitnami/flink/Chart.yaml
bitnami/flink/README.md
bitnami/flink/templates/jobmanager/deployment.yaml
bitnami/flink/templates/taskmanager/statefulset.yaml
bitnami/flink/values.yaml

[bitnami/flink] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/milvus/Chart.lock
bitnami/milvus/Chart.yaml
bitnami/milvus/README.md
bitnami/milvus/templates/_helpers.tpl
bitnami/milvus/templates/attu/deployment.yaml
bitnami/milvus/templates/data-coordinator/deployment.yaml
bitnami/milvus/templates/data-node/deployment.yaml
bitnami/milvus/templates/index-coordinator/deployment.yaml
bitnami/milvus/templates/index-node/deployment.yaml
bitnami/milvus/templates/init-job.yaml
bitnami/milvus/templates/proxy/deployment.yaml
bitnami/milvus/templates/query-coordinator/deployment.yaml
bitnami/milvus/templates/query-node/deployment.yaml
bitnami/milvus/templates/root-coordinator/deployment.yaml
bitnami/milvus/values.yaml

[bitnami/milvus] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

bitnami/aspnet-core/Chart.lock
bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/README.md
bitnami/aspnet-core/templates/deployment.yaml
bitnami/aspnet-core/values.yaml

[bitnami/aspnet-core] feat: :sparkles: :lock: Add automatic adaptation for Openshift restricted-v2 SCC

---

.vib/flux/runtime-parameters.yaml

In #21589 we modified the `podinfo` repo used, which was configured to use the secContext necessary for our tests to run in non-Openshift cluster. 
After creating a custom `openshift` branch in the used repo, this PR adapts the `extraDeploy` params to support Openshift as a testing platform. This required changes both in `bitnami/flux` and `bitnami/dokuwiki` repos.
The runtime parameters can now be used in an Openshift testing deployment.
None

[bitnami/flux] Update runtime-params to support Openshift testing

---

bitnami/common/Chart.yaml
bitnami/common/templates/_compatibility.tpl

This PR removes empty seLinuxOptions in Openshift environments, as this is causing problems when performing validation.
Initially, we set it to `null` to workaround this incompatibility with this was causing problems in non-openshift environments. This new adapter should fix the issue.
- fixes https://github.com/bitnami/charts/issues/24159

[bitnami/common] feat: :sparkles: Remove empty seLinuxOptions in adapted Openshift rendered security context

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/NOTES.txt
bitnami/redis/templates/secret.yaml

This MR fixes the wrong usage of the variable `.Values.auth.usePasswordFiles`, in the generation of the secret. This typo was introduced in https://github.com/bitnami/charts/pull/23886
If clause for the generation of the secret is properly parsed. Also, the NOTES.txt now contains accurate information.
N/A
N/A
N/A

[bitnami/redis] Fix typo in usePasswordFiles variable name

---

bitnami/argo-workflows/Chart.lock
bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/README.md

This PR updates the bundled bitnami/postgresql subchart to its new major (see https://github.com/bitnami/charts/pull/22750), bumping the jupyterhub version in a major as well

[bitnami/argo-workflows] Update bundled PostgreSQL

---

bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/templates/headless-service.yaml

This PR adds the `metadata.namespace` value to the `template/headless-service.yaml` to align with the other templates within the chart.
Improves consistency and compatibility with ArgoCD
- fixes #24263

[bitnami/schema-registry] Add missing namespace metadata to headless-service.yaml

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/scripts-configmap.yaml

Fix sentinel prestop scripts, by using the correct environment variable for port. Without TLS, environment variable is named ```REDIS_SENTINEL_PORT```. With TLS, it's named ```REDIS_SENTINEL_TLS_PORT_NUMBER```.
Because ```REDIS_SENTINEL_PORT``` doesn't exist when TLS is enabled, the resulting command looks like this:
```redis-cli -h redis-sentinel.redis.svc.cluster.local -p '' --tls --cert /opt/bitnami/redis/certs/tls.crt --key /opt/bitnami/redis/certs/tls.key --cacert /opt/bitnami/redis/certs/ca.crt sentinel get-master-addr-by-name mymaster```
And since no port is defined (```-p ''```), it fails (with a timeout), and the container is killed before any error log appears.
Sentinel prestop scripts are fixed, and failover is triggered as expected.

[bitnami/redis] Fix sentinel prestop scripts using wrong port when TLS is enabled

---

bitnami/redis-cluster/Chart.lock
bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/redis-statefulset.yaml

Use `resourcesPreset` where missing.
- #24281

[bitnami/redis-cluster] fix: use resource presets

---

bitnami/vault/Chart.lock
bitnami/vault/Chart.yaml
bitnami/vault/templates/server/statefulset.yaml

Add an if clause to the resources of the volumePermissions init container.
- #24276

[bitnami/vault] fix: volumePermissions resources

---

bitnami/vault/Chart.yaml
bitnami/vault/templates/csi-provider/networkpolicy.yaml
bitnami/vault/templates/csi-provider/service-account.yaml
bitnami/vault/templates/injector/hpa.yaml
bitnami/vault/templates/injector/networkpolicy.yaml
bitnami/vault/templates/injector/pdb.yaml
bitnami/vault/templates/injector/service-account.yaml

Some auxiliary resources like service accounts and network policies are still created when using the default values (where CSI Provider and injector are not deployed). With this change, those resources will only be created when actually needed.
* Unused resources will not be deployed.
* There may be a corner case (not identified) when the CSI Provider and injector are deployed without those auxiliary resources.
None

[bitnami/vault] fix: don't create unused CSI Provider or injector resources

---

bitnami/spark/Chart.lock
bitnami/spark/Chart.yaml
bitnami/spark/templates/statefulset-master.yaml
bitnami/spark/templates/statefulset-worker.yaml

Mount an `emptyDir` volume to Spark's work directory to allow read only root filesystems.
- #24278

[bitnami/spark] fix: work directory permissions

---

bitnami/argo-cd/Chart.lock
bitnami/argo-cd/Chart.yaml

This PR update ArgoCD chart deps to use latest version of Redis.
None
None
N/A

[bitnami/argo-cd] Update chart deps

---

bitnami/kubeapps/Chart.lock
bitnami/kubeapps/Chart.yaml

This PR update Kubeapps chart deps to use latest version of Redis.
None
None
N/A

[bitnami/kubeapps] Update chart deps

---

bitnami/oauth2-proxy/Chart.lock
bitnami/oauth2-proxy/Chart.yaml

This PR update OAuth2Proxy chart deps to use latest version of Redis.
None
None
N/A

[bitnami/oauth2-proxy] Update chart deps

---

bitnami/harbor/Chart.lock
bitnami/harbor/Chart.yaml

This PR update Harbor chart deps to use latest version of Redis.
None
None
N/A

[bitnami/harbor] Update chart deps

---

bitnami/airflow/Chart.lock
bitnami/airflow/Chart.yaml

This PR update Airflow chart deps to use latest version of Redis.
None
None
N/A

[bitnami/airflow] Update chart deps

---

bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml

This PR update Discourse chart deps to use latest version of Redis.
None
None
N/A

[bitnami/discourse] Update chart deps

---

bitnami/appsmith/Chart.lock
bitnami/appsmith/Chart.yaml

This PR update AppSmith chart deps to use latest version of Redis.
None
None
N/A

[bitnami/appsmith] Update chart deps

---

bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml

This PR update Mastodon chart deps to use latest version of Redis.
None
None
N/A

[bitnami/mastodon] Update chart deps

---

bitnami/matomo/Chart.yaml
bitnami/matomo/templates/cronjob.yaml
bitnami/matomo/values.yaml

Follow-up of https://github.com/bitnami/charts/pull/23903 to fix backwards compatibility.
When `.Values.cronjobs.archive.resources` is not specified, the backwards compatibility still works.
None
- Follow-up of https://github.com/bitnami/charts/pull/23903

[bitnami/matomo] Fix cronjobs.archive.resources backwards compatibility

---

bitnami/thanos/Chart.lock
bitnami/thanos/Chart.yaml
bitnami/thanos/README.md

This PR updates the bundled bitnami/minio subchart to the new major (see https://github.com/bitnami/charts/pull/22058), bumping the Thanos version in a major as well

[bitnami/thanos] Update bundled MinIO

---

bitnami/kong/Chart.yaml
bitnami/kong/templates/migrate-job.yaml

corrects indentation of optionally provided `extraVolumes` in the migration job template.
allows the chart to successfully render when providing extra volumes.
n/a
note that the chart only fails to render if you use a database (e.g. `database: postgresql` in values.yaml)

[bitnami/kong] fix: extra volumes indentation for migrate-job.yaml

---

bitnami/mlflow/Chart.yaml
bitnami/mlflow/values.schema.json

Removes the `string` constraint for extraIngress and extraEgress network policy values.
Before this change, I was unable to use either `extraIngress` or `extraEgress` as I was getting this error:
```
Invalid type. Expected: string, given: object
```
Allows for usage of `extraIngress` or `extraEgress`
N/A
* Fixes #24049
* Reverts some changes originally implemented in #23555

[bitnami/mlflow] Remove string constraint from NetworkPolicy extraIngress/extraEgress

---

.vib/matomo/runtime-parameters.yaml
bitnami/matomo/Chart.lock
bitnami/matomo/Chart.yaml
bitnami/matomo/README.md
bitnami/matomo/templates/cronjob.yaml
bitnami/matomo/values.yaml

I wanted to be able to have separate config for the cronjobs compared to the matomo deployment.
So I extracted persistent volume and resources config.
I also added `podSecurityContext` and `extraEnvVars` for both cronjobs
One major benefit is that you can now disable persistence for the cronjobs since they were unable to be scheduled if you had persistence on matomo and `ReadWriteOnce` volumes.
And otherwise this adds more ability to setup the cronjobs a bit differently than the matomo deployment to match the needs of the cluster.
There's a bit more config now which might be perceived as complex. But I think that the benefits overcomes the drawbacks.
- fixes #
This will cause some disruption of the config where some config were moved from one place to another so I opted to bump a minor …

[bitnami/matomo] Separate config for cronjobs

---

bitnami/minio/Chart.yaml
bitnami/minio/templates/distributed/statefulset.yaml
bitnami/minio/templates/standalone/deployment.yaml

Fixes an issue where MinIO API port wouldn't be changed when setting `containerPorts.api`, causing the Probes and service to fail.
- fixes #23953

[bitnami/minio] Fix issue when setting containerPorts.api

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/backup/networkpolicy.yaml

This change modifies the `bitnami/postgres` chart to not include backup network policies when backups aren't enabled.
This will prevent unnecessary network policies from being applied when they aren't needed, which could potentially improve performance and reduce confusion.
None identified. This change should only affect situations where backups aren't enabled.
N/A

[bitnami/postgres] don't include backup netpol when backup aren't enabled

---

bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/templates/cluster-operator/aggregate-cluster-roles.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/aggregate-cluster-roles.yaml

This change adds aggregate cluster roles for `admin`, `edit` and `view` built-in roles, so that operated resources can be managed by processess or individuals carrying those roles on the namespace.
The rationale is that operated resources are in the same security group with standard namespaced resources, such as `Deployments`, and most users would expect to be able to view and manage them freely on namespaces they have access to.
This improves out-of-the-box experience for users utilizing RBAC on the cluster and using non-admin kubeconfigs.
For example, without this change, even `kubectl get all` on a namespace will produce error messages for anyone with a `view` role.
Some may not desire this behavior (though I cannot come up with a scenario).
n/a

[bitnami/rabbitmq-cluster-operator] Add aggregate cluster roles

---

bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/dep-ds.yaml

Fixes flag boolean flag `--pihole-tls-skip-verify`.
- fixes #24529

[bitnami/external-dns] Fix boolean flag --pihole-tls-skip-verify

---

bitnami/apisix/Chart.yaml
bitnami/apisix/templates/data-plane/dep-ds.yaml
bitnami/apisix/templates/tls-secret.yaml

Honor the property `controlPlane.tls.enabled` to generate or not the Secret **apisix-control-plane-tls**.
Honor the property `dataPlane.tls.enabled` when is set to false to don't mount the certificates on the data-plane.  
Allows disable the tls on control-plane and data-plane. 
None IMO
- fixes #24594

[bitnami/apisix] Fix disable tls on controlPlane and dataPlane

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/_helpers.tpl
bitnami/thanos/templates/bucketweb/deployment.yaml
bitnami/thanos/templates/compactor/_pod-template.tpl
bitnami/thanos/templates/receive-distributor/deployment.yaml
bitnami/thanos/templates/receive/statefulset.yaml
bitnami/thanos/templates/ruler/statefulset.yaml
bitnami/thanos/templates/storegateway/statefulset-sharded.yaml
bitnami/thanos/templates/storegateway/statefulset.yaml

Do not render `checksum/objstore-configuration` annotation if `existingObjstoreSecret` is set, plus move `indexCacheConfig` and `bucketCacheConfig` checksum generation from `objstore-configuration` to `storegateway-configuration` as they only used by storage gateway, and other components of thanos should not be redeployed when they are changed.
Get working deployment when existingObjstoreSecret is set
None
- fixes #24536

[bitnami/thanos] Fix thanos objstoreConfig and storegatewayConfigMap

---

bitnami/common/Chart.yaml
bitnami/common/templates/_resources.tpl

Our testing platforms use instances of 2 CPU and 6 GB of memory in the nodes. This is causing that some CPU-MEM intensive solutions are not being deployed. As the resource presets are meant for testing purposes, this PR reduces the request section in these presets.
- fixes #

[bitnami/common] chore: :wrench: Relax preset resource requests xlarge and 2xlarge instances

---

bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/templates/controller/deployment.yaml

Removed duplicate part-of key from controller deployment template. Was causing chart to fail.

[Bitnami/Argo-Workflow] Fix duplicate part-of key

---

bitnami/kibana/Chart.yaml
bitnami/kibana/templates/deployment.yaml

The kibana chart includes a mechanism to adapt the `securityContext` when used on OpenShift. This mechanism was used only for the main container, but not for the initContainer. According to K8S's behavior, the `securityContext` of the initContainer is also applied to the main container. As a result, when passing secrets to the container, kibana fails to open the file due to permissions. The fix applies the same mechanism for the initContainer.
Without this change, kibana is unable to access the provided certificates. The chart offers a workaround of disabling the `securityContext` altogether. But, I believe it's less desiarable.
Don't know any
- fixes #24762
- [X ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only …

bitnami/kibana - Adapt the securityContext also for the init container

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/serviceaccount.yaml

Updates the created ServiceAccount to take into consideration if the user has configured the `auth.existingPasswordSecret`value. Use this value if so, otherwise use the value of the generated secret.
Correctly links to the secret when one is specified.
- fixes #24738
Is giving the ServiceAccount access to the secret even needed?

[bitnami/rabbitmq] Fix invalid secret pointer in RabbitMQ ServiceAccount

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/_helpers.tpl
bitnami/thanos/templates/query/deployment.yaml

Use `https://` prefix for ruler alert URL when `queryFrontend.ingress.tls` is set to `true`. 
Compute a valid URL based on ingress configuration.
This bugfix might break some configurations in some edge cases.  
- fixes #

[bitnami/thanos] fix: use https for queryURL when ingress is tls

---

bitnami/nats/Chart.yaml
bitnami/nats/templates/deployment.yaml

By probing the `/healthz` endpoint instead of `/` on the Nats monitoring port, the pods only become ready once they are in fact ok, instead of right away after startup. This improves restarts where for instance Jetstream needs to recover first. 
Restarts only progress once Nats pods are actually ready instead of once Nats has started up and starts listening on the monitoring port
Deployments that used to rollout a restart quite quick may take longer to progress.
- fixes #24360

[bitnami/nats] Fix readiness probe endpoint (#24360)

---

.vib/grafana-mimir/goss/goss.yaml

Increase timeout as the command takes 80s to run in Openshift:
```
2024-04-03T10:24:14Z [TRACE] SUCCESS: Command => check-mimirtool (exit-status 0 0) [79.81]
```

[bitnami/grafana-mimir] Increase test timeout

---

bitnami/grafana/Chart.yaml
bitnami/grafana/templates/serviceaccount.yaml

Updates the created ServiceAccount to take into consideration if the user has configured the `admin.existingSecret` value.  Use this value if so, otherwise use the value of the generated secret.
Correctly links to the secret when one is specified.
- fixes #24736
Is giving the ServiceAccount access to the secret even needed?

[bitnami/grafana] Fix invalid secret pointer in Grafana ServiceAccount

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/deployment.yaml

This PR fixes an issue when using a custom configmap with htaccess. It needs to create a writable folder in the prepare-base-dir init container to avoid making the vhosts folder read-only, causing errors like follows:
```
wordpress-699688968d-fbzw2 wordpress cp: cannot create regular file '/opt/bitnami/apache/conf/./vhosts/00_status-vhost.conf': Permission denied
wordpress-699688968d-fbzw2 wordpress cp: cannot create regular file '/opt/bitnami/apache/conf/./vhosts/wordpress-https-vhost.conf': Permission denied      
wordpress-699688968d-fbzw2 wordpress cp: cannot create regular file '/opt/bitnami/apache/conf/./vhosts/wordpress-vhost.conf': Permission denied
```
Fixes regression with the use of custom htaccess files.
n/a
- fixes …

[bitnami/wordpress] fix: :bug: Create htaccess folder when using custom configmap

---

bitnami/solr/Chart.yaml
bitnami/solr/templates/prometheusrule.yaml
bitnami/solr/templates/servicemonitor.yaml

https://github.com/bitnami/charts/pull/22725 introduced a templating issue for servicemonitor.yaml and prometheusrule.yaml, the parentheses were forgotten. 
The error was:
` wrong number of args for include: want 2 got 0`
The issue happens only when setting metrics.serviceMonitor.enabled: true or metrics.prometheusRule.enabled: true, that is probably why the issue remained undetected since 8.6.0
Bugfix :)

[bitnami/solr] fix: add missing parentheses

---

bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/templates/deployment.yaml

Remove a duplicated ports definition in template/deployment.yaml. This caused an error when using
fluxcd-2.2.3:
```
testwiki                        False           False   Helm install failed for release test/testwiki with chart mediawiki@20.0.0: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 161: mapping key "ports" already defined at line 160  
``` 
Fixes deployment problem when using fluxcd-2.2.3.
None that I am aware of.
I have tested the patch with fluxcd-2.2.3. Problem is gone when the extra ports is removed.

[bitnami/mediawiki] Fix a deploy issue with fluxcd-2.2.3

---

bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/README.md
bitnami/grafana-loki/templates/index-gateway/statefulset.yaml
bitnami/grafana-loki/values.yaml

This PR adds Helm values to the `bitnami/grafana-loki` chart to allow setting persistence parameters for the index gateway component. The [index gateway service](https://grafana.com/docs/loki/next/get-started/components/#index-gateway) downloads TSDB or BoltDB index files from object storage and is [recommended](https://grafana.com/docs/loki/latest/operations/storage/boltdb-shipper/#index-gateway) to be deployed as a StatefulSet with persistent storage. The official `grafana/loki-distributed` chart currently [allows](https://github.com/grafana/helm-charts/blob/a50f643c5df38a21af9548608617b9dbefc72759/charts/loki-distributed/templates/index-gateway/statefulset-index-gateway.yaml) to do that.
As per above, allows setting persistence parameters for the index gateway component of Grafana …

[bitnami/grafana-loki] Persistence parameters for Index Gateway

---

bitnami/matomo/Chart.yaml
bitnami/matomo/templates/deployment.yaml

Properly set expected resources for metrics container.
Currently you get a duplicate `resources` key because of the wron conditions.
using `resources` key works out of the box.
none
none

[bitnami/matomo]: wrong resources condition for metrics

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/scripts-configmap.yaml
bitnami/redis/templates/sentinel/statefulset.yaml

When containers crash or get killed and are restarted, their respective start script will run. Moreover, we can't rely on them being started in an ordered manner (for example, see #24380 or #8878). The following changes improve how we handle such a situation:
- `start-sentinel.sh`: If persistent config was enabled, restart did not work correctly on replica nodes. The script terminated with an error.
Fix this by relying on the information from the config file if no sentinel is reachable.
- `start-sentinel.sh`: Hide incomplete Sentinel config files
Creating the new config file at startup was done in place. This may lead to an incomplete config file if an error occurs or the startup script is killed. Improve this by preparing the config file using a different name (`prepare-sentinel.conf`) …

[bitnami/redis] Improve restart behavior in sentinel mode

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/deployment.yaml

Preserve the default PHP config from container build, in particular, activate the memcached extension: [link](https://github.com/bitnami/containers/blob/26cd3f32780387f8cb275fa544bbd7824d0198b1/bitnami/wordpress/6/debian-12/rootfs/opt/bitnami/scripts/wordpress/postunpack.sh#L57).
- fixes #24605
- related to #24537
`/wp-admin/plugins.php`:
```
$ grep memcached /opt/bitnami/php/etc/php.ini
;extension = memcached
```
```
$ grep memcached /opt/bitnami/php/etc/php.ini
extension = memcached
```
---

[bitnami/wordpress] Preserve default PHP config from container build

---

bitnami/prometheus/Chart.yaml
bitnami/prometheus/templates/alertmanager/networkpolicy.yaml

If AlertManager is disabled, a NetworkPolicy shouldn't be created for it pointing to a non-existent pod.
This PR will update the NetworkPolicy to only be created if the AlertManager is enabled _and_ the NetworkPolicy is enabled.
No dangling NetworkPolicy will be created.
None noted
- fixes #
You can very easily disable the NetworkPolicy by setting `alertmanager.networkPolicy.enabled=false` but I think this shouldn't be necessary when the AlertManager is disabled.

[bitnami/prometheus] Don't create NetworkPolicy for AlertManager if AlertManager is disabled

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/deployment.yaml

In deployment.yaml file, it seems that the ternary used by probes is incorrect since the use of the value ```tls.enabled``` done by commit e3d035dfe226568e07b40b6f561d591199e2706f. When we deactivate the TLS, the deployment could not start because a connection attempt is done in HTTPS and not HTTP.
Fix issue when TLS is disabled.
HTTPS doesn't work as intended, I didn't test this kind of configuration
-
-

[bitnami/nginx] fix: correct ternary when tls is enabled

---

bitnami/apisix/Chart.yaml
bitnami/apisix/templates/control-plane/dep-ds.yaml
bitnami/apisix/templates/data-plane/dep-ds.yaml

Currently, the http-metrics port was shown in the ports: section regardless metrics.enabled was set to true or not. This PR adds an if statement to show the port only when strictly necessary.
n/a
- fixes #

[bitnami/apisix] fix: :bug: :lock: Do not expose http-metrics unless metrics.enabled=true

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/service.yaml
bitnami/cassandra/templates/statefulset.yaml

This PR hides the tls port when internode encryption is disabled. This makes the container ports and the deployment ports definition to be consistent. This PR also exposes the service metrics port only when metrics.enabled=true
n/a
- fixes #

[bitnami/cassandra] fix: :bug: :lock: Do not expose tls internode port unless encryption is set

---

bitnami/clickhouse/Chart.yaml
bitnami/clickhouse/templates/service-headless.yaml
bitnami/clickhouse/templates/statefulset.yaml

This PR adds a `shard` label to the clickhouse statefulsets, so we ensure that each compute unit has its own set of labels.
Better security in the chart
- fixes #

[bitnami/clickhouse] fix: :bug: :lock: Add shard label to avoid Compute Unit collision

---

.vib/flink/runtime-parameters.yaml
bitnami/flink/Chart.yaml

Fixes tests on top of Openshift by setting the correct security settings on `extraDeploy` objects. Adds a new `emptyDir` volume so the k8s job object can write the `/tmp/ready` file.
Flink can be properly tested on Openshift environments.
Not expected

[bitnami/flink] Update extraDeploy for Openshift tests

---

bitnami/ejbca/Chart.lock
bitnami/ejbca/Chart.yaml
bitnami/ejbca/templates/deployment.yaml

This PR adds to the deployment spec the ports that were missing, such as the ajp port. These ports are currently hardcoded in the container logic (as they add no value to the application)
n/a
- fixes #

[bitnami/ejbca] fix: :bug: :lock: Expose missing ports in deployment spec

---

bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/application-controller/prometheus-rule.yaml
bitnami/argo-cd/templates/application-controller/servicemonitor.yaml
bitnami/argo-cd/templates/applicationset/servicemonitor.yaml
bitnami/argo-cd/templates/dex/servicemonitor.yaml
bitnami/argo-cd/templates/notifications/servicemonitor.yaml
bitnami/argo-cd/templates/repo-server/servicemonitor.yaml
bitnami/argo-cd/templates/server/servicemonitor.yaml

Enabling the metrics and serviceMonitor for one of the services lead to an helm error, becaus of an invalid statement. Fixing the statement by adding missing brackets.
ServiceMonitor can be enabled again
None
None

[bitnami/argo-cd]: fixing creation of service monitors

---

.vib/phpmyadmin/cypress/cypress.config.js

Remove reference to a transient testing machine and replace it by `localhost`.
The tests can be run locally without any change.
None
NA

[bitnami/phpmyadmin] Use localhost in tests template

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/bucketweb/ingress.yaml
bitnami/thanos/templates/compactor/ingress.yaml
bitnami/thanos/templates/query-frontend/ingress.yaml
bitnami/thanos/templates/query/ingress.yaml
bitnami/thanos/templates/ruler/ingress.yaml
bitnami/thanos/templates/storegateway/ingress.yaml

When some Thanos component is disabled and Ingress of this component is enabled, the Ingress component should not be rendered.
E.g. In general values file (same for multiple instances) I will create a general configuration of component bucketweb. Then in values file for each instance I will just enable or disable this bucketweb component.
```yaml
bucketweb:
enabled: false
ingress:
enabled: true
```
```yaml
bucketweb:
enabled: true
```
```yaml
bucketweb:
enabled: false
```
Values applied in way `helm install thanos bitnami/thanos -f values.general.yaml -f values.cluster-N.yaml`
It will reduce the necessary configuration for multiple instances of the same Chart using different values ​​files from general to specific.
N/A
N/A
N/A

[bitnami/thanos] Enable Ingress only when component is enabled

---

.vib/cassandra/runtime-parameters.yaml

Set Java VM memory settings for testing.
This prevents the automatic computation of these settings, which was causing an internal issue if the size of the cluster is greater than the expected.
NA
NA
NA

[bitnami/cassandra] Set Java VM memory in testing

---

bitnami/kafka/Chart.yaml
bitnami/kafka/templates/scripts-configmap.yaml

Fixes #25132 
Matching on `"` at the end for the `password-placeholder` ensures that only `password-placeholder-1` is matched and not `password-placeholder-10`, `password-placeholder-11`, etc.

[bitnami/kafka] :lady_beetle: Fix password replace for >10 users

---

.vib/cassandra/runtime-parameters.yaml
bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/NOTES.txt
bitnami/cassandra/templates/_helpers.tpl
bitnami/cassandra/templates/statefulset.yaml

Right now, the Cassandra chart is crashing in several platforms since we enabled resources presets. This is because how the JVM Max Heap Size and New Heap Size are being calculated. Up until now, the container is using the host physical memory instead of the one set in the `resources` section. 
Example in minikube:
```
kubectl get pods -o=jsonpath='{range .items[*]}{"\n"}{.metadata.name}{":\t"}{.spec.containers[*].resources}'               
cassandra-0:    {"limits":{"cpu":"1500m","ephemeral-storage":"1Gi","memory":"3Gi"},"requests":{"cpu":"1","ephemeral-storage":"50Mi","memory":"2Gi"}}
```
The limit is set to 3Gi, but if we enter the container and launch `free`, we see the following:
```
I have no name!@cassandra-0:/$ free -h …
```

[bitnami/cassandra] fix: :bug: Honor memory limits in jvm heap sizes

---

bitnami/airflow/Chart.yaml
bitnami/airflow/templates/_helpers.tpl

From versions 15 up to 18 in airflow-exporter Deployment, when using default PostgreSQL password and without existing secret chart installation fails, because secret name is not passed to the values
```yaml
- name: AIRFLOW_PROMETHEUS_DATABASE_PASSWORD
valueFrom:
secretKeyRef:
name: 
key: password
```
Fixing error
None

[bitnami/airflow] Fixing error with default PostgreSQL password

---

bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/templates/networkpolicy.yaml

This PR adds the necessary section in grafana-operator networkPolicy to allow egress traffic when `allowExternalEgress: true`. This may have been overlooked when adding the networkPolicy section.
- fixes https://github.com/bitnami/charts/issues/25150

[bitnami/grafana-operator] fix: :bug: Honor allowExternalEgress in networkPolicy

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/statefulset.yaml
bitnami/rabbitmq/values.yaml

This PR adds to the deployment spec the ports that were missing, such as the metrics port. Right now we were enclosing it in an if/else statement, but our container logic always enables the prometheus plugin, so it should always be documented in the ports section:
https://github.com/bitnami/containers/blob/main/bitnami/rabbitmq/3.13/debian-12/rootfs/opt/bitnami/scripts/librabbitmq.sh#L555
n/a
- fixes #

[bitnami/rabbitmq] fix: :bug: :lock: Expose missing ports in deployment spec

---

bitnami/kube-state-metrics/Chart.yaml
bitnami/kube-state-metrics/templates/deployment.yaml

This PR adds to the deployment spec the ports that were missing, such as the telemetry port. Right now it was conditional but the port is always open, as seen in the upstream Dockerfile
https://github.com/kubernetes/kube-state-metrics/blob/9e855147a20f2539b0b8c3ea1aa7cd761c104797/Dockerfile#L17
n/a
- fixes #

[bitnami/kube-state-metrics] fix: :bug: :lock: Expose missing ports in deployment spec

---

bitnami/keycloak/Chart.lock
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/headless-service.yaml
bitnami/keycloak/templates/statefulset.yaml

This PR adds to the deployment spec the ports that were missing, such as the discovery port. It also changes the headless service to not use the service ports but the container ports instead.
n/a
- fixes #

[bitnami/keycloak] fix: :bug: :lock: Expose missing ports in deployment spec and fix headless service

---

bitnami/solr/Chart.yaml
bitnami/solr/templates/networkpolicy.yaml

In the networkpolicy, the port for the metrics was forgotten, blocking the retrieval of the metrics by Prometheus.
Getting metrics again :)

[bitnami/solr] fix: add missing metrics port to networkpolicy

---

bitnami/airflow/Chart.yaml

Bump chart version because it was overlapped in 2 different PRs.
Release changes from #25138
None

[bitnami/airflow] Version bump to realese #25138

---

.vib/concourse/goss/web/goss.yaml

Increase create-pipeline-trigger-job test timeouts
That test takes longer than expected in some environments. We need to increase the time expected.
None

[bitnami/concourse] Increase goss create-pipeline-trigger-job test timeouts

---

bitnami/flink/Chart.yaml
bitnami/flink/templates/taskmanager/statefulset.yaml

This PR ensures the `taskmanager.data.port` property is properly configured based on the container port chosen in the values.
Before:
```yaml
taskmanager.bind-host: 0.0.0.0
taskmanager.host: flink-taskmanager-0.flink-taskmanager-headless.default.svc.cluster.local
taskmanager.rpc.port: 6122
```
After:
```yaml
taskmanager.bind-host: 0.0.0.0
taskmanager.data.port: 6121
taskmanager.host: flink-taskmanager-0.flink-taskmanager-headless.default.svc.cluster.local
taskmanager.rpc.port: 6122
```
Configuration aligned with chart values.
None
It might help with https://github.com/bitnami/charts/issues/24784#event-12337147216
N/A

[bitnami/flink] Ensure data port is set in configuration

---

bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
bitnami/postgresql-ha/templates/postgresql/witness-statefulset.yaml

The PostgreSQL logs are not shown to STDOUT. The RW `emptyDir` for postgresql logs is not needed:
```console
$ docker run --rm --entrypoint /bin/bash bitnami/postgresql -c 'ls -l /opt/bitnami/postgresql/logs'
total 0
lrwxrwxrwx 1 root root 11 Feb 21 13:27 postgresql.log -> /dev/stdout
```
* There might be other PostgreSQL log files, depending on specific user configs.
- fixes #24700

[bitnami/postgresql-ha] Remove RW emptyDir for postgresql logs

---

bitnami/postgresql-ha/Chart.yaml

#25207 conflicted with #25165 and the resulting commit to `main` c3b1082 did not bump the chart version.

[bitnami/postgresql-ha] Bump chart version

---

bitnami/node-exporter/Chart.yaml
bitnami/node-exporter/README.md
bitnami/node-exporter/templates/NOTES.txt
bitnami/node-exporter/templates/_helpers.tpl
bitnami/node-exporter/templates/deployment.yaml
bitnami/node-exporter/values.yaml

This PR will add support of deploying Node Exporter as `Deployment` instead of `Daemonset`
There are some situation in which you have to deploy a single pod of Node Exporter. For example you want to disable all default collectors and only enable textfile collector so a sidecar container can update textfiles in a shared volume and Node Exporter will read and expose them to prometheus.
In this scenario you don't need to use `hostNetwork`, `hostPid` and have access to `/proc` and `/sys`. So this PR also introduce another variable named `isolatedDeployment` that is `true` by default and will only affect `Deployment` mode that takes care of this requirement.

[bitnami/node-exporter] Add deployment support

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/servicemonitor.yaml

Fix typo
Chart can be installed wiith serviceMonitor enabled.
None
- fixes #23408

[bitnami/cassandra] Fix ServiceMonitor namespace

---

bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/templates/skipper/configmap.yaml
bitnami/spring-cloud-dataflow/templates/skipper/externaldb-secret.yaml

This change was made to fix a discovered issue from the values documentation mentioning that `externalDatabase.existingPasswordSecret` and `externalDatabase.existingPasswordKey` is deprecated in favor of using `existingSecret` and `existingSecretPasswordKey` within `dataflow` and `skipper`. When changing to the expected way but having skipper disabled, the skipper `externaldb-secret.yaml` is still included and fails to base64 encode the password since it is empty. The best solution was not to include the file at all. I applied the same logic to skippers `configmap.yaml` since it is not used when enabled.
This change fixes an issue when disabling skipper and mariadb but not including a password for the skipper database. The following is a bare minimum values.yaml that would break before …

[bitnami/spring-cloud-dataflow] Remove Skipper ConfigMap and Secrets when Skipper is disabled

---

bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/templates/webhook/networkpolicy.yaml

Add default ingress port to networkpolicy.
- Fixing liniting error of network policy: `/spec/ingress/0/ports/0/port' does not validate with https://raw.githubusercontent.com/yannh/kubernetes-json-schema/master/master-standalone/networkpolicy-networking-v1.json#/properties/spec/properties/ingress/items/properties/ports/items/properties/port/oneOf`
- Can be evaluated with `helm template . | kubeconform`
- More similar to cainjector and controller networkpolicy
None
None

[bitnami/cert-manager] fix: webhook networkpolicy

---

bitnami/minio/Chart.yaml
bitnami/minio/templates/distributed/statefulset.yaml

Fixes permissions issue when using multiple drives per node:
```
/opt/bitnami/scripts/libminio.sh: line 364: /bitnami/minio/data/.root_user: Permission denied
```
- fixes #24998

[bitnami/minio] Permission denied at startup with multiple drives per node

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/statefulset.yaml

Due to the new security defaults introduced at #24336, it's no longer possible to install custom plugins using the `communityPlugins` parameter since users face permissions issues due to the read-only filesystem.
This PR introduces an init-container to workaround this limitation by copying the default plugins (the ones included in the image) to an empty-dir, and mounting that empty-dir with the default plugins in the main container where it's possible to perform write actions.
Installing custom plugins doesn't require reverting security defaults.
None
- fixes https://github.com/bitnami/charts/issues/24592
None

[bitnami/rabbitmq]: Fix custom plugins installation

---

bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/application-controller/networkpolicy.yaml

Fix small bug in the application-controller NetworkPolicy implemented in #23359. One ingress port is null, the parameter was removed as part of #25043.
```console
$ helm template oci://registry-1.docker.io/bitnamicharts/argo-cd --version 6.0.10 -s templates/application-controller/networkpolicy.yaml | grep port
- ports:
- port:
- port: 8082
```

[bitnami/argo-cd] Remove null port in application-controller NetworkPolicy

---

bitnami/consul/Chart.yaml
bitnami/consul/templates/tls-secrets.yaml

Fix condition for creation tls-secrets if existingSecret is specified - Don't create tls-secret
Don't create not needed secret.
None
None
None

[bitnami/consul] Fix condition for creation tls-secrets if existingSecret is specified

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/podmonitor.yaml

PR #23859 seems to break additionalEndpoints in pod-monitor, this PR aims to fix it by changing the var scope to handle Helm range properly
- fixes #

[bitnami/redis] Fix relabelling var scope in pod-monitor

---

.github/workflows/sync-chart-index.yaml

Change AWS accounts and assume roles to publish the helm charts in the index branch.
Restrict the use of these credentials and only request the permissions needed.
None

Use AWS role to publish index.yaml file in S3

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/NOTES.txt
bitnami/mongodb/templates/_helpers.tpl
bitnami/mongodb/templates/networkpolicy.yaml

Tune validations keeping in mind the auto-discovery function. Little fix in network policies to allow traffic to the K8S API server.
Keep it clean and promote auto-discovery function.
None

[bitnami/mongodb] Fix validations and Autodiscovery

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/statefulset.yaml

Adds an 'else' to the .Values.enableDefaultInitContainers allowing for initContainers to still be specified, even if the default initContainers are disabled.
It is understood that folks sometimes want to specify initContainers and that is good, so we should still allow initContainers to be specified, even if someone decides to disable the default initContainers (needed to run 3rd party images).
None come to mind.  It's a pretty small change with big benefit.
- fixes #24544
I'm not a pro at helm chart template files, so please check my work.  Suggestions welcome!
Been awhile since I commited a change... if something else is needed just let me know.

[bitnami/keycloak] add else when '.Values.enableDefaultInitContainers: false', otherwise all initContainers are disabled

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/primary/statefulset.yaml
bitnami/postgresql/templates/read/statefulset.yaml

The PostgreSQL logs are not shown to STDOUT. The RW `emptyDir` for postgresql logs is not needed:
```console
$ docker run --rm --entrypoint /bin/bash bitnami/postgresql -c 'ls -l /opt/bitnami/postgresql/logs'
total 0
lrwxrwxrwx 1 root root 11 Feb 21 13:27 postgresql.log -> /dev/stdout
```
* There might be other PostgreSQL log files, depending on specific user configs.
- related to #24700

[bitnami/postgresql] Remove RW emptyDir for postgresql logs

---

bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/servicemonitor.yaml

Fix typo in `servicemonitor.yaml` template, when this values are set:
```yaml
#[...]
metrics:
enabled: true
serviceMonitor:
enabled: true
relabelings:
- action: replace
sourceLabels:
- "__meta_kubernetes_pod_label_app"
targetLabel: instance
#[...]
```
The code runs without breaking
None
None
None

[bitnami/influxdb] Fix typo in servicemonitor template

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/statefulset.yaml

Replace KC_HOSTNAME_ADMIN by KC_HOSTNAME_ADMIN_URL to include the scheme (http or https) and add KC_HOSTNAME_URL for the frontend to function correctly. These variable allow the front to function correctly if we have the tls option enabled. Before this commit the front was always attempting to load some resources over http while it may be exposed in https.
Keycloak admin ingress works if tls/https is configured
If some users defined `KC_HOSTNAME` or `KC_HOSTNAME_URL` in extraEnv it could prevent keycloak to start, I reduced the risk by adding this variable only if the ingress is not enabled though

[bitnami/keycloak]: add url env vars to fix admin ingress access

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/templates/role.yaml
bitnami/rabbitmq/values.yaml

Add `rbac.rules` value
Allow users to set additional rules to the rabbitmq role.
None
- fixes #25387

[bitnami/rabbitmq] Add rbac.rules

---

bitnami/janusgraph/Chart.yaml
bitnami/janusgraph/templates/_helpers.tpl
bitnami/janusgraph/templates/networkpolicy.yaml

Fixes issue with JanusGraph network policy missing the metrics ingress port.

[bitnami/janusgraph] Add metrics port in networkPolicy ingress

---

.vib/jaeger/runtime-parameters.yaml

Reverts #21894
Instead of using the custom image `davidbhlm/example-hotrod`, which only added `USER 1001` to the `jaegertracing/example-hotrod` image, uses the default image but adds `runAsUser` when the environment is not OpenShift.
Additionally, uses the image version matching the current Jaeger release.
- Fixes issues when testing ARM
- No need to manually update the image version

[bitnami/jaeger] Rollback runtime-parameters to use jaegertracing/example-hotrod

---

bitnami/node-exporter/Chart.yaml
bitnami/node-exporter/README.md
bitnami/node-exporter/templates/psp.yaml
bitnami/node-exporter/values.yaml

This change introduces a specific dynamic annotation in the PodSecurityPolicy for the node-exporter Helm chart, specifically to resolve an issue with the seccomp profile settings. By allowing these values to be configurable:
```
seccomp.security.alpha.kubernetes.io/defaultProfileName: runtime/default
seccomp.security.alpha.kubernetes.io/allowedProfileNames: runtime/default
```
we enable users to specify the required seccomp profiles, thus enhancing the chart's adaptability to different security requirements and Kubernetes cluster configurations.
- Increased Compatibility: The update ensures that the node-exporter can be deployed in environments with strict PodSecurityPolicies that enforce seccomp profiles, thereby expanding the chart's usability.
- Security Compliance: Users can align the …

[bitnami/node-exporter] Update PSP annotation to dynamic value

---

.github/workflows/ci-pipeline.yml

This PR improves our CI GH actions to ensure we don't include unprintable characters on `values.yaml` files.

CI: Add GH action to ensure no unprintable characters

---

bitnami/contour/Chart.yaml
bitnami/contour/templates/envoy/deployment.yaml

This fixes bitnami/contour envoy deployment spec when `envoy.kind: deployment` is set. Currently the deployment will fail due to `Readiness probe errored: strconv.Atoi: parsing "http-shutdown": invalid syntax`. The shutdown-manager container liveness and readiness probes were switched to use a named port which does not exist in the container spec. This adds the port using the existing values defined for --serve-port on the shutdown-manager.
Fixes chart deployment failure when `envoy.kind: deployment` is set.
None, this fixes the deployment using the same values that already exist and were previously set before the switch to a named port.
- fixes #25507 
none

[bitnami/contour] Adding missing named port for shutdown-manager container

---

bitnami/kafka/Chart.yaml
bitnami/kafka/templates/metrics/deployment.yaml

Before this change, default liveness- and readiness probes for kafka-exporter polled /metrics, which causes high CPU usage and frequent events about timeouts (because the default probe timeout is 1s and the amount of data gathered and transferred for no reason sometimes took more on my cluster).
Changing this to /healthz makes this probe stable again and CPU usage decreases significantly (on my test cluster).
The /healthz endpoint is not documented (or I couldn't find it) but it is used in the original author's [own helm chart](https://github.com/danielqsj/kafka_exporter/blob/2e60c05d09b934c477e86426c36a59b2e40a90c1/charts/kafka-exporter/templates/deployment.yaml#L98C1-L98C29) for both liveness and readiness.
- less timeouts and unnecessary restarts
- less CPU cycles wasted
- the actual …

[bitnami/kafka] change probe path for kafka-exporter to /healthz

---

bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/crds/grafanacontactpoints.integreatly.org.yaml
bitnami/grafana-operator/templates/rbac-clustescope.yaml
bitnami/grafana-operator/templates/rbac-namespace.yaml

- Add missing CRD for GrafanaContactPoints
- Add missing RBAC for GrafanaContactPoints
- Bump Chart.yaml
- Add correct license header for Chart.yaml
The new version of Grafana-Operator will not fail.
*none*
- fixes #25514

[bitnami/grafana-operator] Add missing CRD: GrafanaContactPoints

---

bitnami/memcached/Chart.yaml
bitnami/memcached/templates/networkpolicy.yaml

Fixes configuring memcached `networkPolicy.extraEgress`
`networkPolicy.extraEgress` works
If someone is relying on the erroneous values
- fixes #

[bitnami/memcached] Fix memcached network policy extraEgress

---

bitnami/etcd/Chart.yaml
bitnami/etcd/templates/NOTES.txt

The notes didn't take into account if the user was providing an existing secret.
The client works properly now
- fixes https://github.com/bitnami/charts/issues/25525

[bitnami/etcd] Properly get ROOT_PASSWORD when providing an existing secret

---

bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/deployment.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/webhook-service.yaml

rabbitmq-cluster-operator: rename http-webhook port to https-webhook
You are able to deploy RabbitmqCluster CRDs in a k8s cluster with Istio enabled.
none
Didn't find any.
Istio does magic based on the name of the port and expects http traffic on http-<name> ports, not https. This results in a "connection reset by peer" when trying to deploy a RabbitmqCluster resource, when it tries to invoke the message topology operator's webhook.
And the webhook is actually https traffic, not http.

bitnami/rabbitmq-cluster-operator: rename http-webhook port to https-webhook

---

bitnami/haproxy/Chart.yaml
bitnami/haproxy/README.md
bitnami/haproxy/templates/service.yaml
bitnami/haproxy/values.yaml

Allows to set externalIPs on haproxy service.
Allows to expose service with [ExternalIPs](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips) 
Fixes https://github.com/bitnami/charts/issues/25564

[bitnami/haproxy] Add externalIPs (#25564)

---

bitnami/mariadb-galera/Chart.yaml
bitnami/mariadb-galera/templates/statefulset.yaml

Fixes an issue where legacy `securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}` would be used instead of the new helper `common.compatibility.renderSecurityContext`, causing issues in Openshift deployments

[bitnami/mariadb-galera] Use renderSecurityContext in initContainer

---

bitnami/dokuwiki/Chart.yaml
bitnami/dokuwiki/templates/deployment.yaml

The php-var-dir needs to be pre-populated in the emptyDir volume to avoid issues in PHP session management.
- fixes #25540

[bitnami/dokuwiki] Fix php session mgmt

---

bitnami/metallb/Chart.yaml
bitnami/metallb/templates/speaker/rbac.yaml

Typo fix in RBAC for the speaker component.
- fixes #25577

[bitnami/metallb] Typo fix in speaker RBAC

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/templates/hpa.yaml
bitnami/keycloak/values.yaml

This PR adds the ability to configure the `behavior` of the `HorizontalPodAutoscaler` of the Keycloak StatefulSet with new parameter block `autoscaling.behavior` 
ref: https://kubernetes.io/docs/tasks/run-application/horizontal-pod-autoscale/#configurable-scaling-behavior
This allows us to set policies that control how the autoscaler scales up/down the pods e.g., the keycloak pods can be scaled by X units or percent of current pods during a `periodSeconds` window. 
`stabilizationWindowSeconds` can be set to set the duration which past recommendations should be considered while scaling
`selectPolicy` - The priority of policies that the autoscaler will apply when scaling up/down. Can be `Max`, `Min`, `Disabled`
Keycloak pods are stateful due to the embedded Infinispan cache that requires …

[bitnami/keycloak] Add HPA Behavior when scaling up and down

---

bitnami/opensearch/Chart.yaml
bitnami/opensearch/templates/_helpers.tpl

Fix typo to make the chart work when `dashboards.persistence.enabled` is true
Allow `dashboards.persistence.enabled` usage
N/A
- fixes #25690
~- [ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)~

[bitnami/opensearch] Fix dashboards persistence

---

.github/workflows/archive-full-index.yaml
.github/workflows/cd-pipeline.yml
.github/workflows/sync-chart-index.yaml

These changes squash all commits in the branch every time the job is executed
Repo size is reduced
None AFAIK
Related to https://github.com/bitnami/charts/pull/25730
- [Na] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.

Reduce index branch size by squashing all commits

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/pdb.yaml

[bitnami/cassandra] PDB review

---

bitnami/mariadb/Chart.yaml
bitnami/mariadb/templates/primary/statefulset.yaml
bitnami/mariadb/templates/secondary/statefulset.yaml

[bitnami/mariadb] Use different liveness/readiness probes

---

bitnami/prometheus/Chart.yaml
bitnami/prometheus/templates/NOTES.txt

Updated prometheus server local cluster address, as it pointed to the wrong service name.
The post install message generates this cluster url: prometheus.prometheus.svc.cluster.local
However, the url is wrong, as it uses the `common.names.fullname` template instead of the `prometheus.server.fullname`.
Using the correct template, the generated cluster url is: **prometheus-server.prometheus.svc.cluster.local**.
For reference, also the alert manager and thanos internal url are generated in a similar way:
- template "prometheus.alertmanager.fullname"
- template "prometheus.thanos-sidecar.fullname"
The cluster url for the prometheus-server service is now correct.

[bitnami/prometheus] Updated prometheus server local cluster address

---

bitnami/kafka/Chart.yaml
bitnami/kafka/templates/scripts-configmap.yaml

Use non-printable delimiter to avoid sed errors with delimiter symbols in passwords
Fixes sed string to be correct with passwords that use / symbols (standard sed delimiter symbol)
No sed errors in case of using / symbols in passwords
- fixes #25500

bitnami/kafka Fix for sed in kafka-init.sh

---

bitnami/mysql/Chart.yaml
bitnami/mysql/templates/primary/statefulset.yaml
bitnami/mysql/templates/secondary/statefulset.yaml

[bitnami/mysql] Use different liveness/readiness probes

---

bitnami/etcd/Chart.yaml
bitnami/etcd/templates/pdb.yaml

[bitnami/etcd] PDB review

---

template/CHART_NAME/templates/pdb.yaml

Remove replicaCount and autoscaling conditions from the PodDisruptionBudget template.
Users with just one pod in their deployments or replicasets can enable Pod disruption budget feature. There is no real restriction to enforce users to create a deployment or replicasets with two or more pods if they want to enable the PDBs.
None
* https://github.com/bitnami/charts/pull/14433

[bitnami/template] PodDisruptionBudget template more permissive

---

template/CHART_NAME/templates/statefulset.yaml

Fixing error in template. This last `{{- end }}` doesn't have anything to close
Make the template more usable (I'm trying to automate generating charts from the template).
None
None
None

[bitnami/template] Remove unneeded `{{- end }}`

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/coordinating/statefulset.yaml
bitnami/elasticsearch/templates/data/statefulset.yaml
bitnami/elasticsearch/templates/ingest/statefulset.yaml
bitnami/elasticsearch/templates/master/statefulset.yaml

Fixed the securityContexts for some initContainers, so that it runs on openshift.
Right now one has to manually disable the securityContext for all statefulsets like following to be able to run it on openshift:
```
coordinating.containerSecurityContext.enabled: false
master.containerSecurityContext.enabled: false
data.containerSecurityContext.enabled: false
ingest.containerSecurityContext.enabled: false
```
no workaround necessary, less values to be configured and more straightforward to deploy
none
- fixes #25860
none
(no vars changed)

[bitnami/elasticsearch] fixed secContext for initContainer for openshift

---

bitnami/wordpress/Chart.lock
bitnami/wordpress/Chart.yaml
bitnami/wordpress/values.yaml

[bitnami/wordpress] Use different liveness/readiness probes

---

bitnami/joomla/Chart.lock
bitnami/joomla/Chart.yaml
bitnami/joomla/templates/deployment.yaml

[bitnami/joomla] Use different liveness/readiness probes

---

bitnami/phpbb/Chart.yaml
bitnami/phpbb/templates/deployment.yaml

[bitnami/phpbb] Use different liveness/readiness probes

---

bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/README.md
bitnami/grafana-loki/templates/compactor/networkpolicy.yaml
bitnami/grafana-loki/templates/distributor/networkpolicy.yaml
bitnami/grafana-loki/templates/gateway/networkpolicy.yaml
bitnami/grafana-loki/templates/index-gateway/networkpolicy.yaml
bitnami/grafana-loki/templates/ingester/networkpolicy.yaml
bitnami/grafana-loki/templates/promtail/networkpolicy.yaml
bitnami/grafana-loki/templates/querier/networkpolicy.yaml
bitnami/grafana-loki/templates/query-frontend/networkpolicy.yaml
bitnami/grafana-loki/templates/query-scheduler/networkpolicy.yaml
bitnami/grafana-loki/templates/ruler/networkpolicy.yaml
bitnami/grafana-loki/templates/table-manager/networkpolicy.yaml
bitnami/grafana-loki/values.yaml

Apply the same changes made in PR #25519 to the Loki chart
Review network policy features to allow users cover their needs without forcing specific labels.
Users can restrict access to their deployments in a cleaner way, without leaving open doors to specific labeled pods.
None

[bitnami/grafana-loki] Network policy review

---

bitnami/ghost/Chart.lock
bitnami/ghost/Chart.yaml
bitnami/ghost/templates/deployment.yaml

[bitnami/ghost] Use different liveness/readiness probes

---

bitnami/haproxy/Chart.yaml
bitnami/haproxy/README.md
bitnami/haproxy/templates/deployment.yaml
bitnami/haproxy/values.yaml

Allow to set enableServiceLinks on haproxy, true by default.
Some users need to set enableServiceLinks=false
- fixes #25851

[bitnami/haproxy] Add enableServiceLinks (#25851)

---

bitnami/etcd/README.md

It should be `auth.rbac.create` not `auth.rbac.enabled` since https://github.com/bitnami/charts/commit/c3f6f9a4a6f5f81038a33245e198557ba4b19024

[bitnami/etcd] Fix inconsistent between readme and code for etcd

---

bitnami/grafana-mimir/Chart.yaml
bitnami/grafana-mimir/templates/alertmanager/pdb.yaml
bitnami/grafana-mimir/templates/compactor/pdb.yaml
bitnami/grafana-mimir/templates/distributor/pdb.yaml
bitnami/grafana-mimir/templates/gateway/pdb.yaml
bitnami/grafana-mimir/templates/ingester/pdb.yaml
bitnami/grafana-mimir/templates/overrides-exporter/pdb.yaml
bitnami/grafana-mimir/templates/querier/pdb.yaml
bitnami/grafana-mimir/templates/query-frontend/pdb.yaml
bitnami/grafana-mimir/templates/query-scheduler/pdb.yaml
bitnami/grafana-mimir/templates/ruler/pdb.yaml
bitnami/grafana-mimir/templates/store-gateway/pdb.yaml

[bitnami/grafana-mimir] PDB review

---

bitnami/redmine/Chart.lock
bitnami/redmine/Chart.yaml
bitnami/redmine/README.md
bitnami/redmine/templates/deployment.yaml
bitnami/redmine/values.yaml

[bitnami/redmine] Use different liveness/readiness probes

---

bitnami/memcached/Chart.yaml
bitnami/memcached/README.md
bitnami/memcached/templates/networkpolicy.yaml
bitnami/memcached/values.yaml

Apply the same changes made in PR #25519 to the Memcached chart
Review network policy features to allow users cover their needs without forcing specific labels.
Users can restrict access to their deployments in a cleaner way, without leaving open doors to specific labeled pods.
None

[bitnami/memcached] Network policy review

---

bitnami/etcd/Chart.yaml
bitnami/etcd/templates/statefulset.yaml

[bitnami/etcd] Use different liveness/readiness probes

---

bitnami/jenkins/Chart.yaml
bitnami/jenkins/templates/deployment.yaml

[bitnami/jenkins] Use different liveness/readiness probes

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/deployment.yaml

[bitnami/nginx] Use different liveness/readiness probes

---

bitnami/sonarqube/Chart.lock
bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/templates/deployment.yaml

[bitnami/sonarqube] Use different liveness/readiness probes

---

bitnami/fluent-bit/Chart.yaml
bitnami/fluent-bit/templates/daemonset.yaml
bitnami/fluent-bit/templates/deployment.yaml

[bitnami/fluent-bit] Use different liveness/readiness probes

---

bitnami/tomcat/Chart.yaml
bitnami/tomcat/templates/_pod.tpl

[bitnami/tomcat] Use different liveness/readiness probes

---

bitnami/keycloak/README.md

- There's no `auth.managementPassword` value in the templates
- `keycloakConfigCli.configuration` receives an object that has keys matching `*.json` to work
- `keycloakConfigCli.enabled` needs to be set to `true`
- add a newline at `EOF`
- fixes #

[bitnami/keycloak] Update README.md

---

bitnami/dokuwiki/Chart.yaml
bitnami/dokuwiki/templates/deployment.yaml

[bitnami/dokuwiki] Use different liveness/readiness probes

---

bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/templates/deployment.yaml

[bitnami/aspnet-core] Use different liveness/readiness probes

---

bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml
bitnami/discourse/templates/deployment.yaml

[bitnami/discourse] Use different liveness/readiness probes

---

bitnami/common/Chart.yaml
bitnami/common/templates/_warnings.tpl

This PR adds a common warning function to be used in NOTES.txt: `common.warnings.modifiedImages`. This one checks if the Bitnami shipped images are being replaced by images different from the ones set in Chart.Annotations (the ones that have been verified and tested). We want to warn users of the potential risks of this action.
Example of usage in the matomo chart:
```
{{- include "common.warnings.modifiedImages" (dict "images" (list .Values.image .Values.metrics.image .Values.volumePermissions.image .Values.certificates.image) "context" $) }}
```
If we change one of the images, we see the following warning:
```
SECURITY WARNING: Original containers have been substituted. This Helm chart was designed, tested, and validated on …
```

[bitnami/common] feat: :sparkles: Show warning when original images are replaced

---

bitnami/kibana/Chart.yaml
bitnami/kibana/templates/deployment.yaml

[bitnami/kibana] Use different liveness/readiness probes

---

bitnami/logstash/Chart.yaml
bitnami/logstash/templates/sts.yaml

[bitnami/logstash] Use different liveness/readiness probes

---

bitnami/parse/Chart.lock
bitnami/parse/Chart.yaml
bitnami/parse/templates/dashboard-deployment.yaml
bitnami/parse/templates/server-deployment.yaml

[bitnami/parse] Use different liveness/readiness probes

---

bitnami/opensearch/Chart.yaml
bitnami/opensearch/templates/dashboards/deployment.yaml

[bitnami/opensearch] Use different liveness/readiness probes

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/metrics/deployment.yaml

[bitnami/elasticsearch] Use different liveness/readiness probes

---

bitnami/wildfly/Chart.yaml
bitnami/wildfly/values.yaml

[bitnami/wildfly] Use different liveness/readiness probes

---

bitnami/spark/Chart.yaml
bitnami/spark/templates/statefulset-master.yaml
bitnami/spark/templates/statefulset-worker.yaml

[bitnami/spark] Use different liveness/readiness probes

---

bitnami/kafka/Chart.lock
bitnami/kafka/Chart.yaml
bitnami/kafka/templates/broker/statefulset.yaml
bitnami/kafka/templates/controller-eligible/statefulset.yaml
bitnami/kafka/templates/metrics/deployment.yaml

[bitnami/kafka] Use different liveness/readiness probes

---

bitnami/kong/Chart.lock
bitnami/kong/Chart.yaml
bitnami/kong/templates/dep-ds.yaml

[bitnami/kong] Use different liveness/readiness probes

---

bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/templates/client/client-dep-job.yaml
bitnami/deepspeed/templates/worker/worker-statefulset.yaml

[bitnami/deepspeed] Use different liveness/readiness probes

---

bitnami/nats/CHANGELOG.md
bitnami/nats/Chart.yaml
bitnami/nats/README.md
bitnami/nats/values.yaml

[bitnami/nats] PDB review

---

bitnami/node-exporter/CHANGELOG.md
bitnami/node-exporter/Chart.lock
bitnami/node-exporter/Chart.yaml
bitnami/node-exporter/templates/daemonset.yaml
bitnami/node-exporter/templates/deployment.yaml

[bitnami/node-exporter] Use different liveness/readiness probes

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.lock
bitnami/etcd/Chart.yaml
bitnami/etcd/templates/NOTES.txt

[bitnami/etcd] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.lock
bitnami/redis/Chart.yaml
bitnami/redis/templates/NOTES.txt

[bitnami/redis] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/pytorch/CHANGELOG.md
bitnami/pytorch/Chart.yaml
bitnami/pytorch/templates/NOTES.txt

[bitnami/pytorch] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/spark/CHANGELOG.md
bitnami/spark/Chart.lock
bitnami/spark/Chart.yaml
bitnami/spark/templates/NOTES.txt

[bitnami/spark] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/NOTES.txt

[bitnami/postgresql] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/zookeeper/CHANGELOG.md
bitnami/zookeeper/Chart.lock
bitnami/zookeeper/Chart.yaml
bitnami/zookeeper/templates/NOTES.txt

[bitnami/zookeeper] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/vault/CHANGELOG.md
bitnami/vault/Chart.yaml
bitnami/vault/templates/NOTES.txt

[bitnami/vault] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/tomcat/CHANGELOG.md
bitnami/tomcat/Chart.lock
bitnami/tomcat/Chart.yaml
bitnami/tomcat/templates/NOTES.txt

[bitnami/tomcat] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/thanos/CHANGELOG.md
bitnami/thanos/Chart.lock
bitnami/thanos/Chart.yaml
bitnami/thanos/templates/NOTES.txt

[bitnami/thanos] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.lock
bitnami/seaweedfs/Chart.yaml
bitnami/seaweedfs/templates/NOTES.txt

[bitnami/seaweedfs] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/rabbitmq/CHANGELOG.md
bitnami/rabbitmq/Chart.lock
bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/NOTES.txt

[bitnami/rabbitmq] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/mysql/CHANGELOG.md
bitnami/mysql/Chart.lock
bitnami/mysql/Chart.yaml
bitnami/mysql/templates/NOTES.txt

[bitnami/mysql] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/milvus/CHANGELOG.md
bitnami/milvus/Chart.lock
bitnami/milvus/Chart.yaml
bitnami/milvus/templates/NOTES.txt

[bitnami/milvus] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/metallb/CHANGELOG.md
bitnami/metallb/Chart.lock
bitnami/metallb/Chart.yaml
bitnami/metallb/templates/NOTES.txt

[bitnami/metallb] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/kafka/CHANGELOG.md
bitnami/kafka/Chart.lock
bitnami/kafka/Chart.yaml
bitnami/kafka/templates/NOTES.txt

[bitnami/kafka] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/joomla/CHANGELOG.md
bitnami/joomla/Chart.lock
bitnami/joomla/Chart.yaml
bitnami/joomla/templates/NOTES.txt

[bitnami/joomla] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/janusgraph/CHANGELOG.md
bitnami/janusgraph/Chart.lock
bitnami/janusgraph/Chart.yaml
bitnami/janusgraph/templates/NOTES.txt

[bitnami/janusgraph] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/jaeger/CHANGELOG.md
bitnami/jaeger/Chart.lock
bitnami/jaeger/Chart.yaml
bitnami/jaeger/templates/NOTES.txt

[bitnami/jaeger] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/NOTES.txt

[bitnami/argo-cd] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.lock
bitnami/apisix/Chart.yaml
bitnami/apisix/templates/NOTES.txt

[bitnami/apisix] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/airflow/Chart.lock
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/NOTES.txt
bitnami/apache/Chart.lock
bitnami/apache/Chart.yaml
bitnami/apache/templates/NOTES.txt

[bitnami/apache] feat: :sparkles: :lock: Add warning when original images are replaced

---

bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.yaml
bitnami/seaweedfs/templates/filer/statefulset.yaml
bitnami/seaweedfs/templates/master/statefulset.yaml
bitnami/seaweedfs/templates/s3/deployment.yaml
bitnami/seaweedfs/templates/volume/statefulset.yaml
bitnami/seaweedfs/templates/webadv/deployment.yaml

Use the `renderSecurityContext` helper to render the `podSecurityContext`. 
It works with the `auto` compatibility parameter for Openshift.

[bitnami/seaweedfs] fix: adapt pod security context to openshift

---

bitnami/deepspeed/CHANGELOG.md
bitnami/deepspeed/Chart.lock
bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/templates/client/client-dep-job.yaml

[bitnami/deepspeed] Use different liveness/readiness probes (part 2)

---

bitnami/oauth2-proxy/CHANGELOG.md
bitnami/oauth2-proxy/Chart.lock
bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/templates/deployment.yaml

[bitnami/oauth2-proxy] Use different liveness/readiness probes

---

bitnami/kube-state-metrics/CHANGELOG.md
bitnami/kube-state-metrics/Chart.yaml
bitnami/kube-state-metrics/templates/deployment.yaml

[bitnami/kube-state-metrics-probes] Use different liveness/readiness probes

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.lock
bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/statefulset.yaml
bitnami/mongodb/templates/hidden/statefulset.yaml
bitnami/mongodb/templates/replicaset/statefulset.yaml
bitnami/mongodb/templates/standalone/dep-sts.yaml

[bitnami/mongodb] Use different liveness/readiness probes

---

bitnami/schema-registry/CHANGELOG.md
bitnami/schema-registry/Chart.lock
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/templates/statefulset.yaml

[bitnami/schema-registry] Use different liveness/readiness probes

---

bitnami/metallb/CHANGELOG.md
bitnami/metallb/Chart.lock
bitnami/metallb/Chart.yaml
bitnami/metallb/templates/controller/deployment.yaml
bitnami/metallb/templates/speaker/daemonset.yaml

[bitnami/metallb] Use different liveness/readiness probes

---

bitnami/jaeger/CHANGELOG.md
bitnami/jaeger/Chart.lock
bitnami/jaeger/Chart.yaml
bitnami/jaeger/templates/agent/deployment.yaml
bitnami/jaeger/templates/collector/deployment.yaml
bitnami/jaeger/templates/query/deployment.yaml

[bitnami/jaeger] Use different liveness/readiness probes

---

bitnami/sealed-secrets/CHANGELOG.md
bitnami/sealed-secrets/Chart.lock
bitnami/sealed-secrets/Chart.yaml
bitnami/sealed-secrets/templates/deployment.yaml

[bitnami/sealed-secrets] Use different liveness/readiness probes

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/templates/prometheus-proxy/deployment.yaml
bitnami/spring-cloud-dataflow/templates/server/deployment.yaml
bitnami/spring-cloud-dataflow/templates/skipper/deployment.yaml

[bitnami/spring-cloud-dataflow] Use different liveness/readiness probes

---

bitnami/kubeapps/CHANGELOG.md
bitnami/kubeapps/Chart.lock
bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/templates/dashboard/deployment.yaml
bitnami/kubeapps/templates/frontend/deployment.yaml
bitnami/kubeapps/templates/kubeappsapis/deployment.yaml

[bitnami/kubeapps] Use different liveness/readiness probes

---

bitnami/mongodb-sharded/CHANGELOG.md
bitnami/mongodb-sharded/Chart.lock
bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml
bitnami/mongodb-sharded/templates/mongos/mongos-dep-sts.yaml
bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml
bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml

[bitnami/mongodb-sharded] Use different liveness/readiness probes

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md
bitnami/mastodon/templates/sidekiq/deployment.yaml
bitnami/mastodon/templates/streaming/deployment.yaml
bitnami/mastodon/templates/web/deployment.yaml
bitnami/mastodon/values.yaml

[bitnami/mastodon] Use different liveness/readiness probes

---

bitnami/solr/CHANGELOG.md
bitnami/solr/Chart.lock
bitnami/solr/Chart.yaml
bitnami/solr/templates/metrics-deployment.yaml
bitnami/solr/templates/statefulset.yaml

[bitnami/solr] Use different liveness/readiness probes

---

bitnami/memcached/CHANGELOG.md
bitnami/memcached/Chart.lock
bitnami/memcached/Chart.yaml
bitnami/memcached/templates/deployment.yaml
bitnami/memcached/templates/statefulset.yaml

[bitnami/memcached] Use different liveness/readiness probes

---

bitnami/kuberay/CHANGELOG.md
bitnami/kuberay/Chart.lock
bitnami/kuberay/Chart.yaml
bitnami/kuberay/templates/apiserver/deployment.yaml
bitnami/kuberay/templates/operator/deployment.yaml

[bitnami/kuberay] Use different liveness/readiness probes

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.lock
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/statefulset.yaml

[bitnami/keycloak] Use different liveness/readiness probes

---

bitnami/contour/CHANGELOG.md
bitnami/contour/Chart.yaml
bitnami/contour/templates/contour/deployment.yaml
bitnami/contour/templates/default-backend/deployment.yaml
bitnami/contour/templates/envoy/daemonset.yaml
bitnami/contour/templates/envoy/deployment.yaml

[bitnami/contour] Use different liveness/readiness probes

---

bitnami/fluentd/CHANGELOG.md
bitnami/fluentd/Chart.yaml
bitnami/fluentd/templates/aggregator-statefulset.yaml
bitnami/fluentd/templates/forwarder-daemonset.yaml

[bitnami/fluentd] Use different liveness/readiness probes

---

bitnami/influxdb/CHANGELOG.md
bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/deployment.yaml

[bitnami/influxdb] Use different liveness/readiness probes

---

bitnami/grafana-loki/CHANGELOG.md
bitnami/grafana-loki/Chart.lock
bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/templates/compactor/deployment.yaml
bitnami/grafana-loki/templates/distributor/deployment.yaml
bitnami/grafana-loki/templates/gateway/deployment.yaml
bitnami/grafana-loki/templates/index-gateway/statefulset.yaml
bitnami/grafana-loki/templates/ingester/statefulset.yaml
bitnami/grafana-loki/templates/promtail/daemonset.yaml
bitnami/grafana-loki/templates/querier/statefulset.yaml
bitnami/grafana-loki/templates/query-frontend/deployment.yaml
bitnami/grafana-loki/templates/query-scheduler/deployment.yaml
bitnami/grafana-loki/templates/ruler/statefulset.yaml
bitnami/grafana-loki/templates/table-manager/deployment.yaml

[bitnami/grafana-loki] Use different liveness/readiness probes

---

bitnami/grafana-mimir/CHANGELOG.md
bitnami/grafana-mimir/Chart.lock
bitnami/grafana-mimir/Chart.yaml
bitnami/grafana-mimir/templates/alertmanager/statefulset.yaml
bitnami/grafana-mimir/templates/compactor/statefulset.yaml
bitnami/grafana-mimir/templates/distributor/deployment.yaml
bitnami/grafana-mimir/templates/gateway/deployment.yaml
bitnami/grafana-mimir/templates/ingester/statefulset.yaml
bitnami/grafana-mimir/templates/overrides-exporter/deployment.yaml
bitnami/grafana-mimir/templates/querier/deployment.yaml
bitnami/grafana-mimir/templates/query-frontend/deployment.yaml
bitnami/grafana-mimir/templates/query-scheduler/deployment.yaml
bitnami/grafana-mimir/templates/ruler/deployment.yaml
bitnami/grafana-mimir/templates/store-gateway/statefulset.yaml

[bitnami/grafana-mimir] Use different liveness/readiness probes

---

bitnami/concourse/CHANGELOG.md
bitnami/concourse/Chart.lock
bitnami/concourse/Chart.yaml
bitnami/concourse/templates/web/deployment.yaml
bitnami/concourse/templates/worker/deployment.yaml
bitnami/concourse/templates/worker/statefulset.yaml

[bitnami/concourse] Use different liveness/readiness probes

---

bitnami/jupyterhub/CHANGELOG.md
bitnami/jupyterhub/Chart.lock
bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/templates/hub/deployment.yaml
bitnami/jupyterhub/templates/proxy/deployment.yaml

[bitnami/jupyterhub] Use different liveness/readiness probes

---

bitnami/flink/CHANGELOG.md
bitnami/flink/Chart.yaml
bitnami/flink/templates/jobmanager/deployment.yaml
bitnami/flink/templates/taskmanager/statefulset.yaml

[bitnami/flink] Use different liveness/readiness probes

---

bitnami/janusgraph/CHANGELOG.md
bitnami/janusgraph/Chart.yaml
bitnami/janusgraph/templates/deployment.yaml

[bitnami/janusgraph] Use different liveness/readiness probes

---

bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.lock
bitnami/apisix/Chart.yaml
bitnami/apisix/templates/control-plane/dep-ds.yaml
bitnami/apisix/templates/dashboard/deployment.yaml
bitnami/apisix/templates/data-plane/dep-ds.yaml
bitnami/apisix/templates/ingress-controller/deployment.yaml

[bitnami/apisix] Use different liveness/readiness probes

---

bitnami/pinniped/CHANGELOG.md
bitnami/pinniped/Chart.yaml
bitnami/pinniped/templates/concierge/deployment.yaml
bitnami/pinniped/templates/supervisor/deployment.yaml

[bitnami/pinniped] Use different liveness/readiness probes

---

bitnami/nats/CHANGELOG.md
bitnami/nats/Chart.yaml
bitnami/nats/templates/statefulset.yaml

[bitnami/nats] Use different liveness/readiness probes

---

bitnami/kiam/CHANGELOG.md
bitnami/kiam/Chart.yaml
bitnami/kiam/templates/agent/agent-daemonset.yaml
bitnami/kiam/templates/server/server-daemonset.yaml
bitnami/kiam/templates/server/server-deployment.yaml

[bitnami/kiam] Use different liveness/readiness probes

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/templates/skipper/configmap.yaml

Wrong variables definition in the skipper's ConfigMap. The variables are sensitive to 'release-name' provided with Heml installation command. This fix issue reported with ticket [[issues/26169](https://github.com/bitnami/charts/issues/26169)].
This fix the definition of following application variables, declared with wrong values.
- SPRING_CLOUD_STREAM_KAFKA_BINDER_BROKERS 
- SPRING_CLOUD_STREAM_KAFKA_BINDER_ZK_NODES
Fixes https://github.com/bitnami/charts/issues/26169
With this fix is possible to install Spring-Cloud-Dataflow using Helm 'release-name' that contain dash char ('-').

[bitnami/spring-cloud-dataflow] Fix variables definition sensitive to Helm 'release-name'

---

bitnami/redmine/CHANGELOG.md
bitnami/redmine/Chart.yaml
bitnami/redmine/README.md
bitnami/redmine/templates/pdb.yaml
bitnami/redmine/values.yaml

[bitnami/redmine] Enable PodDisruptionBudgets

---

bitnami/nginx/CHANGELOG.md
bitnami/nginx/Chart.yaml
bitnami/nginx/templates/deployment.yaml

This PR fixes a bug introduced at https://github.com/bitnami/charts/pull/26362 by applying the change below:
```diff
readinessProbe:
failureThreshold: 3
initialDelaySeconds: 5
-           path: /
periodSeconds: 5
successThreshold: 1
timeoutSeconds: 3
httpGet:
path: /
port: http
```
Probes are correct.
None
None
N/A

[bitnami/nginx] Fix readiness probe

---

bitnami/appsmith/CHANGELOG.md
bitnami/appsmith/Chart.lock
bitnami/appsmith/Chart.yaml
bitnami/appsmith/templates/backend/deployment.yaml
bitnami/appsmith/templates/client/deployment.yaml
bitnami/appsmith/templates/rts/deployment.yaml

[bitnami/appsmith] Use different liveness/readiness probes

---

bitnami/rabbitmq-cluster-operator/CHANGELOG.md
bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/templates/cluster-operator/deployment.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/deployment.yaml

[bitnami/rabbitmq-cluster-operator] Use different liveness/readiness probes

---

bitnami/tensorflow-resnet/CHANGELOG.md
bitnami/tensorflow-resnet/Chart.yaml
bitnami/tensorflow-resnet/templates/deployment.yaml

[bitnami/tensorflow-resnet] Use different liveness/readiness probes

---

bitnami/grafana-operator/CHANGELOG.md
bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/templates/grafana.yaml

[bitnami/grafana-operator] Use different liveness/readiness probes
