bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.lock
bitnami/harbor/Chart.yaml
bitnami/harbor/templates/core/core-dpl.yaml
bitnami/harbor/templates/exporter/exporter-dpl.yaml
bitnami/harbor/templates/jobservice/jobservice-dpl.yaml
bitnami/harbor/templates/nginx/deployment.yaml
bitnami/harbor/templates/portal/portal-dpl.yaml
bitnami/harbor/templates/registry/registry-dpl.yaml

[bitnami/harbor] Use different liveness/readiness probes

---

bitnami/external-dns/CHANGELOG.md
bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/dep-ds.yaml

[bitnami/external-dns] Use different liveness/readiness probes

---

bitnami/nginx-ingress-controller/CHANGELOG.md
bitnami/nginx-ingress-controller/Chart.yaml
bitnami/nginx-ingress-controller/templates/controller-deployment.yaml

[bitnami/nginx-ingress-controller] Use different liveness/readiness pending probe

---

bitnami/postgresql-ha/CHANGELOG.md
bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/templates/postgresql/statefulset.yaml

It fixes an issue introduced in #26388.
Fix metrics livenessProbe.
- fixes #26396
- ~[ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)~

[bitnami/postgresql-ha] Fix livenessProbe for metrics

---

bitnami/oauth2-proxy/CHANGELOG.md
bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md
bitnami/oauth2-proxy/templates/_helpers.tpl
bitnami/oauth2-proxy/values.yaml

This patch adds the field "externalRedis.databaseIndex" to the `oauth2-proxy` chart. This field controls the index of the Redis database when using an existing instance, and defaults to `0` (the current implicit behavior).
This allows this chart to be used with an existing Redis instance used by other services without risk of key collision or similar undesired behavior, including deploying multiple instances of this chart against a single Redis instance.
None known
- fixes https://github.com/bitnami/charts/issues/25529

[bitnami/oauth2-proxy] Add field externalRedis.databaseIndex

---

bitnami/clickhouse/Chart.lock
bitnami/clickhouse/Chart.yaml
bitnami/clickhouse/README.md
bitnami/clickhouse/templates/pdb.yaml
bitnami/clickhouse/values.yaml
template/CHART_NAME/templates/pdb.yaml
template/CHART_NAME/values.yaml

[bitnami/clickhouse] Enable PodDisruptionBudgets

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/notifications/bots/slack/deployment.yaml
bitnami/argo-cd/templates/notifications/deployment.yaml

Fix typo in tcpSocket probe where port was missing.
Deployment works with `--set notifications.enabled=true`.
N/A
- fixes #26405
- ~[ ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)~

[bitnami/argo-cd] Define port for notifications probes

---

bitnami/prometheus/CHANGELOG.md
bitnami/prometheus/Chart.yaml

Adds the chart repository to the sources list of the prometheus chart.
Allows tools (e.g. Renovate) to discover the new Changelogs (which are awesome BTW).
None noted
- fixes #
It does not look like many/any other charts have other URLs in their sources list.  Would you like the other 3 removed from this chart?

[bitnami/prometheus] Add chart source URL to sources list

---

bitnami/apache/CHANGELOG.md
bitnami/apache/Chart.yaml
bitnami/apache/templates/deployment.yaml

Fixes an issue with apache, where deployment will fail when htdocs are mounted.
```
apache 09:12:49.11 INFO  ==> ** Starting Apache setup **
apache 09:12:49.22 INFO  ==> Mounting application files from '/app'
rm: cannot remove '/opt/bitnami/apache/htdocs/index.html': Read-only file system
```
This issue is caused by [this section](https://github.com/bitnami/containers/blob/553a1efd8556e38d226a19dd2d2535cf9b08e756/bitnami/apache/2.4/debian-12/rootfs/opt/bitnami/scripts/apache/setup.sh#L76-L80) of the image logic:
```
if ! is_dir_empty "/app"; then
info "Mounting application files from '/app'"
rm -rf "$APACHE_HTDOCS_DIR"
ln -sf "/app" "$APACHE_HTDOCS_DIR"
fi
```
Mounting the htdocs at `/app` will attempt to remove `/opt/bitnami/apache/htdocs`, causing the above permission error.
This PR …

[bitnami/apache] Fix htdocs with readOnlyRootFilesystem

---

bitnami/sonarqube/CHANGELOG.md
bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/README.md
bitnami/sonarqube/templates/pdb.yaml
bitnami/sonarqube/values.yaml

[bitnami/sonarqube] Enable PodDisruptionBudgets

---

bitnami/fluentd/CHANGELOG.md
bitnami/fluentd/Chart.yaml
bitnami/fluentd/templates/NOTES.txt

This chart has the option to define different images for aggregator and forwarder via aggregator.image and forwarder.image. As these sections are optional, it was causing a false positive in the `common.warnings.modifiedImages` helper. This PR checks if these optional images are configured before passing them as parameters to the helper
- fixes #

[bitnami/fluentd] fix: :bug: Only check replaced images when set

---

bitnami/discourse/CHANGELOG.md
bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml
bitnami/discourse/README.md
bitnami/discourse/templates/pdb.yaml
bitnami/discourse/values.yaml

[bitnami/discourse] Enable PodDisruptionBudgets

---

bitnami/deepspeed/CHANGELOG.md
bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/README.md
bitnami/deepspeed/templates/client/pdb.yaml
bitnami/deepspeed/templates/worker/pdb.yaml
bitnami/deepspeed/values.yaml

[bitnami/deepspeed] Enable PodDisruptionBudgets

---

bitnami/valkey/CHANGELOG.md
bitnami/valkey/Chart.yaml
bitnami/valkey/templates/secret.yaml

This PR ensures the `global.valkey.password` is taken into account and it takes precedence over `auth.password`
The `global.valkey.password` parameter works as expected.
None
- fixes #26372
N/A

[bitnami/valkey] take global.valkey.password into account

---

template/CHART_NAME/templates/pdb.yaml
template/CHART_NAME/values.yaml

Enabled PodDisruptionBudget by default and little fixes in PDB configuration to allow users set PDB values in an easier way.
Users can set any of the PDB values without unsetting the other.
None
- [N/A] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.

[bitnami/template] Update PDB defintion in our scaffolding template

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/config/configmap.yaml

- Fix config generation and volume mounts
- Bump chart version
Airfow properly initializes configuration in a volume that is accessible by the initContainer
Not that I can see
- fixes [25367](https://github.com/bitnami/charts/issues/25367)
- Based on contribution from the amazing @[MarijnMB](https://github.com/MarijnMB)

[bitnami/airflow] Fix Airflow k8s config generation in the initContainer and filesystem writability

---

bitnami/mongodb-sharded/CHANGELOG.md
bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/mongos/mongos-dep-sts.yaml

Fixes the mongos deployment/statefulset liveness probe
- fixes #26360

[bitnami/mongodb-sharded] Fix mongos livenessProbe

---

bitnami/redis-cluster/CHANGELOG.md
bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/redis-statefulset.yaml

Add templating to sts' podAnnotations values.
values can contain helm template.
None that I know of.

[bitnami/redis-cluster] Template podAnnotation values

---

.vib/seaweedfs/ginkgo/seaweedfs_suite_test.go
.vib/seaweedfs/ginkgo/seaweedfs_test.go

Add `runAsUser` and `fsGroup` to the testing jobs based on the values from the main pod.
Testing jobs can run on Openshift.

[bitnami/seaweedfs] Fix tests

---

.vib/kubeapps/cypress/cypress/e2e/kubeapps.cy.js
.vib/kubeapps/cypress/cypress/fixtures/releases.json
.vib/kubeapps/runtime-parameters.yaml

Filter the charts synced by the apprepository job and use `nginx` for testing.
Reduce the load in the testing infrastructure and use `nginx` because it allows us to set `securityContext`s in the deploy.
None
Several PRs are blocked due to this failure.
* #26505
* #26573
* #26488
This is a [succeeded execution](https://github.com/bitnami/charts/actions/runs/9352171884/job/25739875791?pr=26605)
- [N/A] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [N/A] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)

[bitnami/kubeapps] Use nginx for testing

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.yaml
bitnami/mongodb/values.yaml

This PR removes Unicode characters from the values.yaml which isn't compatible with certain automation tools.
Before:
```console
$ perl -ne 'print "$. $_" if m/[\x80-\xFF]/' bitnami/mongodb/values.yaml
962     ##
$ encguess bitnami/mongodb/values.yaml
bitnami/mongodb/values.yaml	UTF-8
$ uchardet bitnami/mongodb/values.yaml
UTF-8
```
After:
```console
$ perl -ne 'print "$. $_" if m/[\x80-\xFF]/' bitnami/mongodb/values.yaml
$ encguess bitnami/mongodb/values.yaml
bitnami/mongodb/values.yaml	US-ASCII
$ uchardet bitnami/mongodb/values.yaml
ASCII
```
⚠️ It seems the check implemented at https://github.com/bitnami/charts/pull/25542 is not enough

[bitnami/mongodb] Remove UTF-8 chars

---

bitnami/phpmyadmin/CHANGELOG.md
bitnami/phpmyadmin/Chart.yaml
bitnami/phpmyadmin/templates/deployment.yaml

Fix typo in deployment.yaml template file.
Fix typo.
None.
N/A
N/A

[bitnami/phpmyadmin] Fix typo in deployment.yaml template

---

.vib/jupyterhub/cypress/cypress/support/commands.js

Increase the timeout of what is expected after login because some platforms seems to be lagging.
- fixes #

[bitnami/jupyterjub] Increase the timeout in login test

---

bitnami/mediawiki/CHANGELOG.md
bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/templates/deployment.yaml

Fix typo in deployment.yaml template file.
Fix typo.
None.
N/A
N/A

[bitnami/mediawiki] Fix typo in deployment.yaml template

---

bitnami/dokuwiki/CHANGELOG.md
bitnami/dokuwiki/Chart.yaml
bitnami/dokuwiki/templates/deployment.yaml

Fix typo in deployment.yaml template.
Fix typo.
None.
N/A
N/A

[bitnami/dokuwiki] Fix typo in deployment.yaml template

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_capabilities.tpl

This PR ensures we return the latest known apiVersion for a given K8s object if `common.capabilities.kubeVersion` is unable to obtain the `kubeVersion` (e.g. using `helm template` with both `global.kubeVersion` and `kubeVersion` values unset).
We should assume the latest kubernetes version as the target when it's undefined.
Users using `helm template` (or ArgoCD and other CD tools that use helm templating engine under the hood) that aren't setting  `global.kubeVersion` nor `kubeVersion` may experience a change in their K8s objects' apiVersion.
None
N/A

[bitnami/common] Capabilities to return latest apiVersion if kubeVersion is undefined

---

bitnami/memcached/CHANGELOG.md
bitnami/memcached/Chart.yaml
bitnami/memcached/README.md
bitnami/memcached/templates/pdb.yaml
bitnami/memcached/values.yaml

Little fixes in PDB configuration to keep it aligned with current templates.
None

[bitnami/memcached] Align PodDisruptionBudgets with templates

---

bitnami/apache/CHANGELOG.md
bitnami/apache/Chart.yaml
bitnami/apache/README.md
bitnami/apache/templates/pdb.yaml
bitnami/apache/values.yaml

[bitnami/apache] Enable PodDisruptionBudgets

---

.vib/mlflow/goss/goss.yaml
bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/tracking/pdb.yaml

Fix tests definition, adding a final dash to avoid entries with the same name.
Clean legacy code from the PDB.
mlflow can pass the tests again.
None

[bitnami/mlflow] Fix tests definition and remove legacy code from PDBs

---

bitnami/rabbitmq/README.md

Explain the problem and a widely used solution
instead of recommending force booting nodes.
These practices are generally used by existing
RabbitMQ K8S Cluster Operators but this PR
intentionally does not recommend any of them.
References https://github.com/bitnami/charts/issues/25698,  https://github.com/bitnami/charts/issues/16081, https://github.com/bitnami/charts/pull/25916.

[bitnami/rabbitmq] RabbitMQ: explain how to safely avoid a deployment deadlock

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_compatibility.tpl

This PR improves `common.compatibility.renderSecurityContext` helper by ensuring that disregarded fields are omitted when running a container in privileged mode.
Simplify (when possible) rendered container security contexts.
None
None
N/A

[bitnami/common] improve renderSecurityContext

---

.github/workflows/cd-pipeline.yml

Upload `vmware-chart-debian-x64.json` and `bitnami-chart-debian-x64.json` files after updating the chart index file.
Keep released charts properly tracked.
None

[CI/CD] Upload promotion files after vib-publish

---

.github/workflows/cd-pipeline.yml

Remove registry information (`doker.io`) from containers list.
Iterate recursively over all Chart.yaml file in dependencies.
Keep same format as previous files.
Ensure we don't miss any image in the container list.
None

[CI/CD] Remove registry from container list

---

bitnami/janusgraph/CHANGELOG.md
bitnami/janusgraph/Chart.yaml
bitnami/janusgraph/templates/_helpers.tpl

This PR fixes an issue resolving the storage password secretName when the release name is not "janusgraph".
- fixes #26354

[bitnami/janusgraph] Fix storage password secretName helper function

---

bitnami/thanos/CHANGELOG.md
bitnami/thanos/Chart.yaml
bitnami/thanos/templates/storegateway/statefulset-sharded.yaml

Make the sharded storegateway cache config mount condition use the root ($), not local dot (.) context. This bug was introduced in #26490 (but did not get caught by linting).
Rendering the chart with a sharded storegateway no longer fails.
N/A
Follow-up to #26490
N/A

 [bitnami/thanos] Fix sharded storegateway cache configs (again)

---

.github/workflows/ci-pipeline.yml

This PR fixes a security issue in the Changelog action. Currently, expanding the ${{github.pr.title}} in the bash script allowed running commands, for example, when adding backticks to the PR title. We now use the Github API to fetch the title to avoid any unwanted usage of the PR title for malicious reasons.
- fixes #

[bitnami/*] ci: :construction_worker: :lock: Remove template expansion in changelog action

---

bitnami/schema-registry/CHANGELOG.md
bitnami/schema-registry/Chart.lock
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/templates/_helpers.tpl
bitnami/schema-registry/templates/statefulset.yaml

Use `nindent` instead of `indent` after rendering imagePullSecrets.
Avoid issues with latest `common` chart release.
None
- Related to #26882

[bitnami/schema-registry] Render imagePullSecrets

---

bitnami/milvus/CHANGELOG.md
bitnami/milvus/Chart.yaml
bitnami/milvus/README.md
bitnami/milvus/templates/externals3-secret.yaml
bitnami/milvus/values.yaml

Fix Milvus connection with S3 when using externalS3 model
Fix bug and increase usability
NA
- fixes #27139

[bitnami/milvus] Fix milvus externalS3 config, address minor typos

---

bitnami/jaeger/CHANGELOG.md
bitnami/jaeger/Chart.yaml
bitnami/jaeger/templates/_helpers.tpl

This change updates the query for  `check_cassandra_keyspace_schema` on all Jaeger deployments (`jaeger-agent, jaeger-collector and jaeger-query`).
If there are many rows in the trace table, the query may time out. The updated query checks the existence of the keyspace `${CASSANDRA_KEYSPACE}`
- fixes #27071

[bitnami/jaeger] Update query for check_cassandra_keyspace_schema

---

bitnami/milvus/CHANGELOG.md
bitnami/milvus/Chart.yaml
bitnami/milvus/templates/_helpers.tpl
bitnami/milvus/templates/externalkafka-tls-password-secret.yaml

Fixes the Milvus chart to not expose the externalKafka.tls.keyPassword in the init-container.
- Relates #26118
Pod root-coordinator no longer exposes the password in its init-container command:
```
...
yq e -i '.kafka.ssl.enabled = true' /bitnami/milvus/rendered-conf/pre-render-config_01.yaml
yq e -i '.kafka.ssl.tlsCert = "/opt/bitnami/milvus/configs/cert/kafka/client/tls.crt"' /bitnami/milvus/rendered-conf/pre-render-config_01.yaml
yq e -i '.kafka.ssl.tlsKey = "/opt/bitnami/milvus/configs/cert/kafka/client/tls.key"' /bitnami/milvus/rendered-conf/pre-render-config_01.yaml
yq e -i '.kafka.ssl.tlsCaCert = "/opt/bitnami/milvus/configs/cert/kafka/client/ca.crt"' /bitnami/milvus/rendered-conf/pre-render-config_01.yaml
yq e -i '.kafka.ssl.tlsKeyPassword = "{{ MILVUS_KAFKA_TLS_KEY_PASSWORD }}"' …
```

[bitnami/milvus] Do not expose externalKafka.tls.keyPassword

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_resources.tpl

This PR relaxes the xlarge and 2xlarge resources requests to acommodate the testing of big Java applications like Dremio.
NOTE: resourcesPreset is not meant for production so the change should not be considered breaking.
Better testing of some solutions.
n/a

[bitnami/common] chore: :wrench: Relax large and xlarge presets resource requests

---

bitnami/thanos/CHANGELOG.md
bitnami/thanos/Chart.yaml
bitnami/thanos/templates/receive/service-headless.yaml
bitnami/thanos/templates/receive/service.yaml

As of 15.7.5, both receive and receive-distributor pods are scrapped by the receive servicemonitor, and when mode is standalone receive pods are scrapped twice. 
To fix this : 
* when "receive.mode: dual-stack", change "app.kubernetes.io/component" label of the thanos-receive service (which is selecting receive-distributor pods in this mode) from receive to "receive-distributor" to make it scrapped by the "receive-distributor" servicemonitor correctly
* only add "prometheus-operator/monitor: true" label to thanos-receive-headless service to avoid having thanos-receive pods scrapped twice when "receive.mode: standalone"
Targets will be configurable by the correct serviceMonitor, and in standalone mode receive pods will not be scrapped twice.
Change labels of the receive service between …

[bitnami/thanos] fix thanos dual-stack receive monitoring

---

bitnami/rabbitmq-cluster-operator/CHANGELOG.md
bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/validating-webhook-configuration.yaml

This closes https://github.com/bitnami/charts/issues/27143
Webhook configuration for the TopicPermission controller in "RabbitMQ-cluster-operator" Messaging Topology Operator is missing, this PR is adding it
TopicPermission controller will now work properly
None
- fixes https://github.com/bitnami/charts/issues/27143

[bitnami/rabbitmq-cluster-operator] Adding TopicPermission webhook missing configuration in Topology Operator

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/statefulset.yaml

Uses HTTPS for admin host url when using proxy=edge.
Fixes the issue to make admin console accessible, otherwise we get `redirect_uri` incorrect error.
N/A
- fixes #27315

[bitnami/keycloak] fix Keycloak HTTP schema for edge proxy mode

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/_helpers.tpl
bitnami/mongodb/templates/hidden/statefulset.yaml
bitnami/mongodb/templates/replicaset/statefulset.yaml
bitnami/mongodb/templates/standalone/dep-sts.yaml

Recovers the symlink to /dev/stdout. This way, you can access the server's logs using `k logs pod`
```
mongodb 13:59:57.17 INFO  ==> ** Starting MongoDB **
{"t":{"$date":"2024-06-24T13:59:57.216Z"},"s":"I",  "c":"CONTROL",  "id":5760901, "ctx":"main","msg":"Applied --setParameter options","attr":{"serverParameters":{"enableLocalhostAuthBypass":{"default":true,"value":false}}}}
{"t":{"$date":"2024-06-24T13:59:57.217+00:00"},"s":"I",  "c":"CONTROL",  "id":20698,   "ctx":"main","msg":"***** SERVER RESTARTED *****"}
{"t":{"$date":"2024-06-24T13:59:57.220+00:00"},"s":"I",  "c":"NETWORK",  "id":4915701, "ctx":"main","msg":"Initialized wire specification","attr":{"spec":{"incomingExternalClient":{"minWireVersion":0,"maxWireVersion":21},"incomingInternalClient":{"minWireVersion":0,"maxWireVersion" …
```

[bitnami/mongodb] Recover logging to stdout

---

bitnami/opensearch/CHANGELOG.md
bitnami/opensearch/Chart.yaml
bitnami/opensearch/templates/data/statefulset.yaml
bitnami/opensearch/templates/master/statefulset.yaml

Fix templating indentation for opensearch volume claim annotations. Broken as of https://github.com/bitnami/charts/commit/3bf4682123d860a11100ec60fb3d2fc9fbfb1144
Reopening auto-closed PR.
- fixes #

[bitnami/opensearch] Fix opensearch annotation templating indentation

---

bitnami/kafka/CHANGELOG.md
bitnami/kafka/Chart.yaml
bitnami/kafka/templates/controller-eligible/statefulset.yaml

During testing migration to kraft mode I recognized that the controller needs also a VolumeMount to the kafka_jaas.conf file to be able to properly connect to Zookeeper.
You can now migrate an external sasl authenticated zookeeper.
None
- fixes #27581
None

[bitnami/kafka] fix: Mount kafka_jaas.conf in controller statefulset for kraft migration

---

bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/primary/statefulset.yaml
bitnami/postgresql/templates/read/statefulset.yaml

Currently there is no option to monitor all databases with postgres exporter without mentioning the databases names and creating them in the init scripts. (.Values.auth.database). Postgres Exporter does let this feature work if you dont mention any databases in the URI and that is why i think the required statement is not correct so i removed it.

postgres exporter monitor all databases

---

bitnami/supabase/CHANGELOG.md
bitnami/supabase/Chart.yaml
bitnami/supabase/templates/auth/networkpolicy.yaml
bitnami/supabase/templates/auth/service.yaml
bitnami/supabase/templates/meta/networkpolicy.yaml
bitnami/supabase/templates/meta/service.yaml
bitnami/supabase/templates/realtime/networkpolicy.yaml
bitnami/supabase/templates/realtime/secret.yaml
bitnami/supabase/templates/realtime/service.yaml
bitnami/supabase/templates/rest/networkpolicy.yaml
bitnami/supabase/templates/rest/service.yaml
bitnami/supabase/templates/storage/networkpolicy.yaml
bitnami/supabase/templates/storage/pvc.yaml
bitnami/supabase/templates/storage/service.yaml
bitnami/supabase/templates/studio/ingress.yaml
bitnami/supabase/templates/studio/networkpolicy.yaml
bitnami/supabase/templates/studio/service.yaml
bitnami/supabase/templates/studio/tls-secret.yaml

Skip rendering resources like network policies, services, secrets or even pvc for components 
(auth, meta, realtime, rest, storage, studio) which are disabled.
Resolves: #27540
Add condition for a supabase component (auth, meta, realtime, rest, storage, studio) to be enabled, prior to rendering ayn resource for it.
No dangling and unused resources in Kubernetes.
I believe there are none 
- fixes #27540

[bitnami/supabase] Do not render any resources for disabled components

---

bitnami/neo4j/CHANGELOG.md
bitnami/neo4j/Chart.yaml
bitnami/neo4j/README.md

This PR sets the correct metadata app-name in the README.md. This avoids incorrect autogenerated PRs like this one https://github.com/bitnami/charts/pull/27757

[bitnami/neo4j] Update README appname

---

bitnami/apache/CHANGELOG.md
bitnami/apache/Chart.yaml
bitnami/apache/templates/deployment.yaml

Use common.compatibility.renderSecurityContext template to render containerSecurityContext values in container specs.
Consistency with other Bitnami charts, and presumably the intended behavior.
It may be possible that a user relies on the current (incorrect) default behavior in a OpenShift environment - which would be to set `securityContext.runAsUser: 1001` and `securityContext.runAsGroup: 0` in the container specs (excepting the main `apache` container).  In this case, the default setting `global.compatibility.openshift.adaptSecurityContext: auto` would likely remove the securityContext config for container specs.  If in fact the user wants the pre-commit behavior, they can set global.compatibility.openshift.adaptSecurityContext to `disabled`. 
- fixes #27633

[bitnami/apache] Uses `common.compatibility.renderSecurityContext` template to render `containerSecurityContext` values in container specs

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/applicationset/networkpolicy.yaml
bitnami/argo-cd/templates/applicationset/pdb.yaml
bitnami/argo-cd/templates/applicationset/role.yaml
bitnami/argo-cd/templates/dex/pdb.yaml
bitnami/argo-cd/templates/notifications/pdb.yaml
bitnami/argo-cd/templates/repo-server/pdb.yaml
bitnami/argo-cd/templates/server/pdb.yaml

PodDisruptionBudgets and NetworkPolicies of the ArgoCD applications are only rendered when the corresponding application is enabled.
PDBs have been created as part of #26419.  NetworkPolicies as part of #23359.
No unnecessary resources in the cluster.
None
None
%

[bitnami/argo-cd] Render PDBs and NetworkPolicies only if apps are enabled as well

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/templates/NOTES.txt
bitnami/keycloak/templates/statefulset.yaml
bitnami/keycloak/values.yaml

The admin realm of Keycloak is fixed in this chart to 'master'. In an interest to allow users of this chart to not use this term, if the chart allowed for changing the admin realm name as a built-in, this would make supporting this easier.
This PR was based on values overrides that are possible with the existing Keycloak chart.
Enables the admin realm to be able to be named differently.  This allows for the use of a name other than 'master'.
This also has security improvements (allowing for use of a non-standard name).
Not currently able to verify the serviceMonitor portion.
- expected to address #27816
N/A

bitnami/keycloak Diversity: Allow Keycloak admin realm to be changed/configurable

---

bitnami/grafana-tempo/CHANGELOG.md
bitnami/grafana-tempo/Chart.yaml
bitnami/grafana-tempo/values.yaml

In tempo configuration the ports of gossip-ring and grpc aren't correctly bind. 
Include values for grpc and gossip-ring ports in tempo configuration. 
None
None

[bitnami/grafana-tempo] Fix: bind correctly containerPorts (grpc and gossip-ring ports)

---

bitnami/discourse/CHANGELOG.md
bitnami/discourse/Chart.yaml
bitnami/discourse/templates/deployment.yaml

Liveness probe for the sidekiq container has been spitting out errors by default due to the "pgreg" typo. I also made the livenessProbe command consistent with the rest of the probes while I'm at it.
There would be no need to use custom livenessProbe to avoid the errors.
None
Haven't posted an issue regarding this as it is a simple fix

[bitnami/discourse] Fix pgrep on livenessProbe typo

---

.github/workflows/ci-pipeline.yml

Improves the kubescape action in the CI pipeline by implementing these changes:
- Fixes an issue when the Kubescape report returns an integer, for example `100%`.
- Allows manually bypassing the score check. Useful when a new feature slightly decreases the score and it can not be avoided.
- Skip score check for automated PRs, to avoid issues with score changes caused by subchart updates.

[github-ci] Kubescape action improvements

---

bitnami/rabbitmq/CHANGELOG.md
bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/templates/svc-headless.yaml
bitnami/rabbitmq/values.yaml

Fixes an issue with RabbitMQ headless service.
Due to the changes introduced at https://github.com/bitnami/charts/pull/26136, there could be issues when nodePort service is used and `service.extraPorts` includes `nodePort` settings, which are not valid in ClusterIP services.
Because of this, the headless extraPorts need to be provided in a separated value, which I created as `extraPortsHeadless`.
Allows using NodePort services with `extraPorts`.
Headless ports won't be automatically mapped to service ports.
This is not necessarily bad, since it provides granular control on which ports want to be exposed in the headless and which in the service.
- fixes #27460

[bitnami/rabbitmq] Replace extraPorts with extraPortsHeadless in headless service

---

bitnami/supabase/CHANGELOG.md
bitnami/supabase/Chart.lock
bitnami/supabase/Chart.yaml
bitnami/supabase/templates/storage/deployment.yaml
bitnami/supabase/values.yaml

This PR bumps the version of supabase-storage to 1.6.8, together with the kong and postgresql subcharts. 
- fixes #

[bitnami/supabase] chore: :arrow_up: Update supabase-storage to 1.6.8

---

bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.yaml
bitnami/apisix/templates/control-plane/ingress.yaml

This PR makes a correction in the control plane ingress template. 
Previously, the backend service port name set in the control plane ingress manifest, e.g. `http-admin`, did not match the service port name as set in the control plane service, e.g. `http-admin-api`, and as a result, access to the control plane through ingress always resulted in error 503. The affected port name in the ingress manifest has now been corrected.
The change will make connections to the control plane's Admin API through an ingress succeed.
None
- fixes #27729
None

[bitnami/apisix] Correct service port name in control plane ingress

---

.vib/zookeeper/vib-verify.json

POC to reenable the kubescape VIB action using the bitnami/zookeeper chart.

[bitnami/zookeeper] Reenable VIB kubescape action

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/statefulset.yaml

#25386 added usage of `KC_HOSTNAME_ADMIN_URL` and `KC_HOSTNAME_URL`; however, the implementation has many issues. One such issue (dealing with `edge` proxy mode) was fixed earlier in #27436; another issue is documented in #25963. This PR is resolving yet another issue. Per [v1 docs](https://www.keycloak.org/server/hostname-deprecated), `KC_HOSTNAME_URL` and `KC_HOSTNAME_ADMIN_URL` are independent environment variables. Since the chart makes two separate ingresses (one public and one admin), these variables should be defined independently based on the ingress values. Without this, in the proxy edge mode, Keycloak is returning Kubernetes internal DNS when calling `.well-known/openid-configuration` from within the same cluster using internal services since `KC_HOSTNAME_URL` is not defined.
* …

[bitnami/keycloak] fix conditions for KC_HOSTNAME_URL

---

bitnami/zookeeper/CHANGELOG.md
bitnami/zookeeper/Chart.yaml

Bump patch version to run the POC introduced at https://github.com/bitnami/charts/pull/27881

[bitnami/zookeeper] Bump patch version

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_resources.tpl

Sonarqube is failing due to the usage of the resources being higher than the limits 
```
Warning  Evicted              9m38s  kubelet            Pod ephemeral local storage usage exceeds the total limit of containers 1Gi.
```
Increase limits in volume usage
None
- would fix this other PR https://github.com/bitnami/charts/pull/27731

[bitnami/common] Increase ephemeral-storage default limits

---

bitnami/joomla/CHANGELOG.md
bitnami/joomla/Chart.lock
bitnami/joomla/Chart.yaml
bitnami/joomla/README.md

[bitnami/joomla] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/opencart/CHANGELOG.md
bitnami/opencart/Chart.lock
bitnami/opencart/Chart.yaml
bitnami/opencart/README.md

[bitnami/opencart] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/phpmyadmin/CHANGELOG.md
bitnami/phpmyadmin/Chart.lock
bitnami/phpmyadmin/Chart.yaml
bitnami/phpmyadmin/README.md

[bitnami/phpmyadmin] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/phpbb/CHANGELOG.md
bitnami/phpbb/Chart.lock
bitnami/phpbb/Chart.yaml
bitnami/phpbb/README.md

[bitnami/phpbb] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/drupal/CHANGELOG.md
bitnami/drupal/Chart.lock
bitnami/drupal/Chart.yaml
bitnami/drupal/README.md

[bitnami/drupal] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/mediawiki/CHANGELOG.md
bitnami/mediawiki/Chart.lock
bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/README.md

[bitnami/mediawiki] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.lock
bitnami/seaweedfs/Chart.yaml
bitnami/seaweedfs/README.md

[bitnami/seaweedfs] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/redmine/CHANGELOG.md
bitnami/redmine/Chart.lock
bitnami/redmine/Chart.yaml
bitnami/redmine/README.md

[bitnami/redmine] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/prestashop/CHANGELOG.md
bitnami/prestashop/Chart.lock
bitnami/prestashop/Chart.yaml
bitnami/prestashop/README.md

[bitnami/prestashop] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/magento/CHANGELOG.md
bitnami/magento/Chart.lock
bitnami/magento/Chart.yaml
bitnami/magento/README.md

[bitnami/magento] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/moodle/CHANGELOG.md
bitnami/moodle/Chart.lock
bitnami/moodle/Chart.yaml
bitnami/moodle/README.md

[bitnami/moodle] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/wordpress/CHANGELOG.md
bitnami/wordpress/Chart.lock
bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md

[bitnami/wordpress] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.yaml
bitnami/harbor/templates/portal/portal-dpl.yaml

Remove duplicated security context in templates/portal/portal-dpl.yaml since this causes deployments of harbor-22.0.2 using fluxcd v2.3.0 to fail with:
```
harbor  22.0.1          False           False   Helm upgrade failed for release harbor/harbor with chart harbor@22.0.2: error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 78: mapping key "securityContext" already defined at line 60        
```
Harbor can be deployed using fluxcd v2.3.0.
None.
N/A
I have tested this patch in fluxcd with successful result:
```
NAME    REVISION        SUSPENDED       READY   MESSAGE                                                                        
harbor  22.0.3          False           True    Helm upgrade succeeded for release harbor/harbor.v102 …
```

[bitnami/harbor] Remove duplicated security context

---

.github/workflows/ci-pipeline.yml

Fixes an issue with the kubescape score check in the CI pipeline.
The issue is that both VIB and the 'get-score' step generate different scores using the 'same' sources.
The main difference is that VIB uses `helm pull oci://...`, while the `get-score` step uses the `main branch + helm dep update`.
This results in VIB having subcharts uncompressed, while `get-score` step has compressed subcharts `.tgz` files.
This causes both reports to differ, resulting in slightly different scores in those charts that have subcharts.
Tested at https://github.com/migruiz4/charts/pull/21

[github-actions] kubescape score: untar subcharts for score match

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/_helpers.tpl

Signed-off-by: Oliver Ni <oliverni@berkeley.edu>
`automountServiceAccountToken` is a field on Pod spec, not the container spec
Currently, this breaks the template
- fixes #26596

[bitnami/mongodb] Fix autoDiscovery initContainer template

---

.github/workflows/ci-pipeline.yml

Fixes an issue with the 'chart-score' step in the CI pipeline that affects the common chart.
It omits the untar step when there are no sub-charts.

[github-action] Fix kubescape score step for common chart

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md

[bitnami/spring-cloud-dataflow] chore!: :arrow_up: :boom: Update mariadb to 11.4

---

bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.yaml
bitnami/apisix/templates/_helpers.tpl

The wait container in the control plane pod now supports untrusted certificates when checking availability of etcd using custom/auto-generated TLS certificates by skipping certificate verification.
Since certificates are not being verified, i.e. they are being just accepted regardless of their issuers, authenticity and integrity of the connection might be impacted. The insecure option is being used only if `etcd.auth.client.useAutoTLS` has been set, though.
- fixes #27924

[bitnami/apisix] wait container: support self-generated certificates at etcd

---

bitnami/matomo/CHANGELOG.md
bitnami/matomo/Chart.lock
bitnami/matomo/Chart.yaml
bitnami/matomo/templates/_helpers.tpl
bitnami/matomo/templates/cronjob.yaml
bitnami/matomo/templates/deployment.yaml

Remove wrong `initContainers[0].imagePullSecrets` references
N/A
- #27879

[bitnami/matomo] Fix wrong initContainers[0].imagePullSecrets value

---

bitnami/metallb/CHANGELOG.md
bitnami/metallb/Chart.lock
bitnami/metallb/Chart.yaml

This PR deprecates _global.storageClass_ in favor of _global.defaultStorageClass_ given it's more convenient for this parameter to behave as a fallback instead of taking precedence over more specific values.
This PR shouldn't be merged until the changes in the common helpers at this [PR](https://github.com/bitnami/charts/pull/24863) are merged and published.

[bitnami/metallb] Global StorageClass as default value

---

bitnami/nginx/CHANGELOG.md
bitnami/nginx/Chart.lock
bitnami/nginx/Chart.yaml

This PR deprecates _global.storageClass_ in favor of _global.defaultStorageClass_ given it's more convenient for this parameter to behave as a fallback instead of taking precedence over more specific values.
This PR shouldn't be merged until the changes in the common helpers at this [PR](https://github.com/bitnami/charts/pull/24863) are merged and published.

[bitnami/nginx] Global StorageClass as default value

---

.github/workflows/cd-pipeline.yml

This PR updates the CD pipeline to use the OCI URL in the index.yaml for new charts.

[github-actions] CD pipeline: Use OCI url in index.yaml

---

bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.yaml
bitnami/harbor/templates/registry/registry-cm.yaml

This removes the DB setting from the registry config if you are running with redis sentinel
The current config does not allow setting an DB with sentinel enabled, as this happens
`[harbor-registry-7f6579568-slz9t] time="2024-07-15T13:41:40.380848854Z" level=error msg="redis: error connecting: ERR unknown command 'SELECT', with args beginning with: '2' " go.version=go1.22.5 instance.id=779d36f5-ca6e-431a-bbc1-e0e4f481b7d3 redis.connect.duration=2.407059ms service=registry version=v2.8.3`
Removing the DBkey fixes redis caching for the registry
none
- fixes #

[bitnami/harbor] Dont set redis DB if Sentinel is enabled

---

bitnami/jupyterhub/CHANGELOG.md
bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/templates/_helpers.tpl

This PR follows up https://github.com/bitnami/charts/pull/28037 given there was a reference to `global.storageClass` that we didn't take into account.

[bitnami/jupyterhub] Fix for jupyterhub.storage.class helper

---

bitnami/cassandra/CHANGELOG.md
bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/_helpers.tpl

This PR follows up https://github.com/bitnami/charts/pull/28002 given there was a reference to `global.storageClass` that we didn't take into account.

[bitnami/cassandra] Fix for cassandra.commitstorage.class helper

---

bitnami/minio/CHANGELOG.md
bitnami/minio/Chart.yaml
bitnami/minio/templates/provisioning-job.yaml

This fixes an error in the provisioning job, where the `mc admin service restart` command requires a TTY-enabled console to work.
Provisioning job works again. :)
Not sure if these flags are backwards compatible with previous MinIO versions. Is this desired?
- fixes #27898
The `--json` flag seems to disable the required TTY feature. The `--wait` flag is for sanity. It looked like the provisioning already continues even when the restart is still in progress.
An alternative approach would've been adding `tty: true` to the container. However, this massively slowed down the provisioning script and caused my `helm upgrade` command to time out.

[bitnami/minio] Fix provisioning in non-tty environment

---

bitnami/cilium/CHANGELOG.md
bitnami/cilium/Chart.yaml
bitnami/cilium/templates/hubble-ui/deployment.yaml
bitnami/cilium/templates/tls-secret.yaml

This PR fixes the TLS cert use on Hubble Relay pods for the client to connect with Hubble server via TLS.
N/A

[bitnami/cilium] Fix TLS cert for Hubble Relay

---

bitnami/mariadb-galera/CHANGELOG.md
bitnami/mariadb-galera/Chart.yaml
bitnami/mariadb-galera/templates/_helpers.tpl
bitnami/mariadb-galera/templates/statefulset.yaml

Allows template in value of keys `existingSecret` and `extraVolumes` which usually contains references to configMaps and that usually has release name as part of the name.
By prefixing configMaps with release name dynamically, we will avoid conflicts when multiple releases are installed in same cluster.
None.
- fixes #27914

[bitnami/mariadb-galera] allow template in existingSecret and extraVolumes

---

bitnami/vault/CHANGELOG.md
bitnami/vault/Chart.yaml
bitnami/vault/templates/server/statefulset.yaml

Current chart tries to mount data volume even if persistence is disabled.
Adds a conditional to add a volumeMount for data. 
This is useful when we are running with `vault.server.command: ["vault", "server", "-dev"]` to install vault on dev mode only.
N/A
N/A
N/A

[bitnami/vault] Only mount data volume if persistence is enabled

---

bitnami/mysql/CHANGELOG.md
bitnami/mysql/Chart.yaml
bitnami/mysql/templates/networkpolicy.yaml

The main goal of this change is to simplify the template and remove duplications that may happen in the NetworkPolicy even when you are in standalone mode.
resource.
The main benefit is to fix two bugs:
* Remove duplicated ports in the ingress and egress NetworkPolicy
* The secondary instance has a bug using the `mysql` port instead of `mysqlx` port.
N/A
N/A
It's possible to compare the current and new version in the [Helm Playground](https://helm-playground.com/#t=KYcwTsDOkFwFAAIkIMQIIIBtMHsDuCAJgHaQISQ6YCuALgJY7GLIC0CADjmLbC8m07daMBAFYAzPwHIOYHLRwBjKqICqAEQAK0gey49Rk3TLkLlqhABUAwjoFob1MBGK0EANWBhIjZnqEePhlBAxEEAG8IhAA6DwBDGigYuXoAW3iwAE8YlTd4%2BmJvLWFIGLSsyABHTAQAXzqTJH1hUSjYhKSyyGA8wkycvNoCorASoPLKmvrGkKj2egAzDsTqZNSM7JjgYniAI0xgAFksgGUARQAZAA0ZpoQWw0jouNX1sHSB3KZhwuLSybVTAADzucwi7B2hDB …

[bitnami/mysql]: Remove duplicated ports in the network policies

---

bitnami/valkey-cluster/CHANGELOG.md
bitnami/valkey-cluster/Chart.yaml
bitnami/valkey-cluster/templates/svc-cluster-external-access.yaml

Changes the loop which generates pod names to not throw errors when templating with `externalAccess` enabled. Matches the method used in the Redis-Cluster chart here: https://github.com/bitnami/charts/blob/51eeb01d38beed95f3cbb0f2e538cb5fe09bb42c/bitnami/redis-cluster/templates/svc-cluster-external-access.yaml#L17C8-L17C62
Unblocks enabling external-access
- Resolves: https://github.com/bitnami/charts/issues/28162

[bitanami/valkey-cluster] fix name generation loop in the external access template

---

bitnami/solr/CHANGELOG.md
bitnami/solr/Chart.yaml
bitnami/solr/templates/statefulset.yaml

* When using a volume permission change container, change permissions of the Solr data directory, as well as its content.
* Bump patch version. Now 9.3.8
Make the initialization container change the owner of the data directory itself. Otherwise, Solr will not be able to create files in it and will get stuck in a crash loop. The same chown is being done on the zookeeper data directory, but it seems it is forgotten on Solr.
With this change, the permission system works. Otherwise, the chart fails to deploy on restricted settings. For example, if you use Talos and host path volumes, the existing init container fails.
None.
None

[bitnami/solr] Change permissions of the Solr data directory

---

bitnami/cilium/CHANGELOG.md
bitnami/cilium/Chart.yaml
bitnami/cilium/templates/agent/daemonset.yaml

Some system binaries (e.g. `update-alternatives`) use the `/var/log` directory to write some log files. We need to add write permissions to this directory then.
None
N/A
N/A

[bitnami/cilium] Compatible with read-only fs

---

bitnami/metallb/CHANGELOG.md
bitnami/metallb/Chart.yaml
bitnami/metallb/templates/speaker/daemonset.yaml

Remove duplicated keys that cause applying with flux to fail when frr is enabled
Fixes usage by tools that reject duplicate keys (such as flux):
```
2024-07-20T22:40:36.520Z error HelmRelease/metallb.metallb-system - Reconciler error error while running post render on files: map[string]interface {}(nil): yaml: unmarshal errors:
line 183: mapping key "imagePullPolicy" already defined at line 173
line 213: mapping key "resources" already defined at line 204
line 264: mapping key "securityContext" already defined at line 254
```
None. The same values were defined a few lines above the removed ones.

[bitnami/metallb] Remove duplicate keys

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/_helpers.tpl

This is a fixup for the auth database URI generation. The previous commit PR #25965
did not apply the dialect template / config to the uri of the auth database.
Fixes: #25965
Fixes: #25964
Signed-off-by: Christian Rohmann <christian.rohmann@inovex.de>

[bitnami/mlflow] feat: Fixup to allow database dialects to be configured (#25965)

---

bitnami/cilium/CHANGELOG.md
bitnami/cilium/Chart.yaml
bitnami/cilium/templates/agent/_init_containers.tpl
bitnami/cilium/templates/agent/daemonset.yaml

Follows up https://github.com/bitnami/charts/pull/28223 ensuring other directories that require write access are writable.
None
N/A
N/A

[bitnami/cilium] Compatible with read-only fs - part ii

---

bitnami/milvus/CHANGELOG.md
bitnami/milvus/Chart.yaml
bitnami/milvus/templates/attu/deployment.yaml

This PR adds a fix for future attu versions, which need to fully write in the .cache folder.
- fixes #

[bitnami/milvus] fix: :bug: Set cache directory fully writable in attu

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/configmap-env-vars.yaml

(Hopefully) Fixes issues mentioned in https://github.com/bitnami/charts/pull/27890
Even though `forwarded|xforwarded` is mentioned in the docs (https://www.keycloak.org/docs/latest/upgrading/index.html#deprecated-proxy-option) it is not valid and does not pass variable validation inside the container.
This PR changes it so proxy headers will now default to `xforwarded` when legacy `proxy` value is used.

[bitnami/keycloak] Fix invalid value of proxy headers when legacy proxy is used

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/templates/statefulset.yaml
bitnami/keycloak/values.yaml

Adds new options ingress.controller and adminIngress.controller to support ingress controllers such as GCE and APISIX, which require * to be appended in the ingress.path, such that the * suffix is not added into KC_HOSTNAME_ADMIN_URL and KC_HOSTNAME_URL in case the controller type is set as gce (default is default)
The specification of ingress.controller is inspired from the bitnami/harbor helm chart
Allow users to deploy with Ingress controllers such as GCE and APISIX and not break Admin UI functionality
NA
- fixes #28357
NA

[bitnami/keycloak] Allow support for gce based ingress controllers

---

bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.yaml
bitnami/seaweedfs/templates/s3/deployment.yaml

Seaweedfs S3 API allows enabling credential based access through [JSON file](https://github.com/seaweedfs/seaweedfs/wiki/Amazon-S3-API#static-configuration), which can be mounted as file from the secret named `.Values.s3.auth.existingSecret`. The Chart is using `subPath` to only select the key with the JSON configuration value from the Secret, the name of the key can be provided by passing `.Values.s3.auth.existingSecretConfigKey`. value.
```yaml
- mountPath: /auth
readOnly: true
{{- if .Values.s3.auth.existingSecret }}
name: auth
subPath: {{ default "config.json" .Values.s3.auth.existingSecretConfigKey }}
{{- else }}
name: empty-dir
subPath: auth-dir
{{- end }}
```
The problem is that the Secret file gets mounted at `/auth` path, and because of the `subPath` it mounts the JSON config to …

[bitnami/seaweedfs] Fix mounting the S3 auth config.json from secret

---

.vib/cassandra/ginkgo/cassandra_test.go
bitnami/cassandra/CHANGELOG.md
bitnami/cassandra/Chart.yaml

This PR improves Ginkgo tests reliability for Cassandra chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/cassandra] Improve Ginkgo test

---

bitnami/kafka/CHANGELOG.md
bitnami/kafka/Chart.yaml
bitnami/kafka/templates/_helpers.tpl

Changed kafka chart _helpers.tpl
Added extraListeners to kafka.listeners the same way it is done in kafka.advertisedListeners
Allow to use extraListeners without manually overriding them.
None, as without it kafka doesn`t start.
Exception in thread "main" java.lang.IllegalArgumentException: requirement failed: advertised.listeners listener names must be equal to or a subset of the ones defined in listeners. Found CLIENT,INTERNAL,CLUSTER,EXTERNAL. The valid options based on the current configuration are CLIENT,INTERNAL,EXTERNAL,CONTROLLER
- fixes #21747
- fixes #21746

bitnami/kafka Add extraListeners to kafka.listeners in _helpers.tpl

---

bitnami/matomo/CHANGELOG.md
bitnami/matomo/Chart.yaml
bitnami/matomo/values.yaml

Remove wrong dokuwiki reference.

[bitnami/matomo] Remove dokuwiki reference

---

bitnami/logstash/CHANGELOG.md
bitnami/logstash/Chart.yaml
bitnami/logstash/templates/networkpolicy.yaml

This PR fixes a regression introduced in https://github.com/bitnami/charts/pull/27763. There were missing ports in the network policy definition. 
- fixes #

[bitnami/logstash] fix: :bug: Add missing ports in networkpolicy

---

bitnami/kafka/README.md
bitnami/schema-registry/CHANGELOG.md
bitnami/schema-registry/Chart.lock
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md

This major updates the Kafka subchart to its newest major, 30.0.0
None
None
N/A

[bitnami/schema-registry] Update chart dependency (kafka)

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_secrets.tpl

This changes the handling of non-existing secrets that should be generated so they will be generated if `failOnNew` is `true`.
This allows the user to add new secrets to a managed secret without having to specify it and letting this chart generate it.
Not that I can think of.
Non that I created, but we sometimes do https://github.com/teutonet/teutonet-helm-charts/blob/main/charts/base-cluster/templates/monitoring/kube-prometheus-stack/oauth-proxy-secret.yaml?plain=1#L14C204-L14C356 to work around this problem.

[bitnami/common] Allow handling of new secrets after initial installation

---

bitnami/milvus/CHANGELOG.md
bitnami/milvus/Chart.lock
bitnami/milvus/Chart.yaml
bitnami/milvus/README.md
bitnami/milvus/values.yaml

This major updates the Kafka subchart to its newest major, 30.0.0
None
None
N/A

[bitnami/milvus] Update chart dependency (kafka)

---

.vib/flux/goss/goss.yaml
.vib/flux/runtime-parameters.yaml
bitnami/flux/CHANGELOG.md
bitnami/flux/Chart.yaml

Change the testing deployment from dokuwiki (deprected) to NGINX

[bitnami/flux] Use nginx instead of dokuwiki for testing

---

bitnami/wordpress/CHANGELOG.md
bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md
bitnami/wordpress/templates/deployment.yaml
bitnami/wordpress/values.yaml

As discussed here https://github.com/bitnami/charts/issues/25174 and implemented in the container here https://github.com/bitnami/containers/pull/67399
This change makes it possible to adjust the sender email and the sender name in the smtp config.
It is backwards compatible because it uses the previous environment variables if none are specified.
- fixes #25174

[bitnami/wordpress] Add the possibility to set `smtpFromEmail` and `smtpFromName`

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/statefulset.yaml

This PR improves the ini-container we use to preserve original container data on writable dirs. As pointed out by @ @JBKoerber at https://github.com/bitnami/charts/pull/24939, the current chart was overwriting data available in the Keycloak data directory.
None
None
N/A

[bitnami/keycloak] Preserve data on writable dirs

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/templates/configmap-env-vars.yaml
bitnami/keycloak/templates/statefulset.yaml
bitnami/keycloak/values.yaml

Use [Hostname v2](https://www.keycloak.org/docs/latest/upgrading/index.html#new-hostname-options) options as v1 options are not used by default.
Use updated configurations in alignment with upstream Keycloak project.
Enabling hostname-strict when hostname is more secure, but may cause issues for some users.
- fixes #28586
This has be merged after the image is updated, see https://github.com/bitnami/containers/pull/70466.

[bitnami/keycloak] use hostname v2 options

---

bitnami/mysql/CHANGELOG.md
bitnami/mysql/Chart.yaml
bitnami/mysql/templates/secrets.yaml

Adds database to service binding secret when root user is used.
Allows the service binding secret to contain the database without also needing to set a custom user.
None
Fixes #28627

[bitnami/mysql] Include database in service binding secret when using root user

---

bitnami/schema-registry/README.md

Fix typo in schema-registry README:  envVars -> extraEnvVars

[btinami/schema-registry] Fix typo in README: envVars -> extraEnvVars.

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_images.tpl

Implemented changes requested in #23536 by updating the `common.images.image` helper to set the image tag to `chart.AppVersion` if no tag is set.
It also replicates the behavior of `common.images.version` introduced in #19223, which returns the chart appVersion by default.
Allows chart maintainers to define a single source of truth for image versions in a chart.
Align behavior for `common.images.version` and `common.images.image` helpers.
Update the helper definition with a new `chart` argument. The impact should be limited or zero as the parameter is not mandatory to make this change backward compatible.
- fixes #23536 (Closed as stale)
N/A

[bitnami/common] Fallback to chart appVersion in common.images.image

---

bitnami/pinniped/CHANGELOG.md
bitnami/pinniped/Chart.yaml
bitnami/pinniped/templates/supervisor/rbac.yaml

This PR syncs missing RBAC sections in the supervisor ClusterRole

[bitnami/pinniped] fix: :bug: Add missing rbac resources

---

.vib/redis-cluster/ginkgo/redis_suite_test.go
.vib/redis-cluster/ginkgo/redis_test.go
bitnami/redis-cluster/CHANGELOG.md
bitnami/redis-cluster/Chart.yaml

Perform rolling update instead of scaling down and up the STS. 
The test is a little bit faster and we get some seconds extra to avoid the volume clean up performed in some environments.
None
Similar changes:
* #28598
* #28813

[bitnami/redis-cluster] fix: Use rollout restart in ginkgo tests

---

.vib/redis/ginkgo/redis_suite_test.go
.vib/redis/ginkgo/redis_test.go
bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml

Perform rolling update instead of scaling down and up the STS. 
The test is a little bit faster and we get some seconds extra to avoid the volume clean up performed in some environments.
None
Similar changes:
*  #28598
* https://github.com/bitnami/charts/pull/28814

[bitnami/redis] fix: Use rollout restart in ginkgo tests

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/configmap-env-vars.yaml
bitnami/keycloak/templates/statefulset.yaml

Moves the definition of hostname variables (`KEYCLOAK_HOSTNAME_ADMIN` and `KEYCLOAK_HOSTNAME`) to the config map instead of defining them directly on statefulset. This allows them to be manually overridden using `extraEnvVars` Helm value.
In certain scenarios, the generated path is not correct. For example, when using Regex path matching. This allows the override without creating additional Helm values.
With great power comes great responsibility. Users can provide invalid values in the override.
- fixes #28590
This is an alternative solution to #28523.

[bitnami/keycloak] move hostname variables to config map to allow override

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md

Update dependencies to the latest Bitnami Redis major update

[bitnami/mastodon] Update dependencies

---

bitnami/nginx/CHANGELOG.md
bitnami/nginx/Chart.yaml
bitnami/nginx/templates/deployment.yaml

This modification allows the Bitnami nginx Helm chart to support non-Bitnami nginx images by conditionally executing an initContainer based on the readOnlyRootFilesystem setting. The initContainer is necessary for handling logs via Bitnami-specific scripts, which non-Bitnami images lack. By adding a conditional check, users can deploy with alternative nginx images without encountering errors related to missing Bitnami-specific scripts.
Allows users to use any nginx image, not just those provided by Bitnami.
None
None
This change does not affect the primary operation of nginx within the Helm chart but instead broadens the potential user base by accommodating more image options. It is particularly useful for users who may be operating in environments where Bitnami images are not ideal or …

[bitnami/nginx] Support for Non-Bitnami Nginx Images in nginx Helm Chart

---

bitnami/apache/CHANGELOG.md
bitnami/apache/Chart.yaml
bitnami/apache/templates/deployment.yaml

* `bitnami/git` container crashes running the `entrypoint.sh` when it attempts to create a ssh key on the readonly file system.  Issue introduced with the changes to add a security context in https://github.com/bitnami/charts/commit/6b0889197e33f20b93f84fee9e6917634f358efc.
* Added a `/etc/ssh` volume mount to `git-clone-repository` and `git-repo-syncer` so it doesn't fail writing SSH keys to the readonly file system.
* Added a `securityContext` to `git-clone-repository`. Previously the repo is cloned as root, then the syncer fails unable to overwrite files created by root.
No CrashLoopBackOff when using cloneHtdocsFromGit
None
- fixes #28845
Tested with:
```
helm install my-apache . \
--set-string cloneHtdocsFromGit.repository=https://github.com/russau/static-site.git \
--set-string …
```

[bitnami/apache] fix CrashLoopBackOff when using cloneHtdocsFromGit

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/applicationset/role.yaml

Add missing verbs (list, watch) to the ApplicationSet controller's role.
The new verbs are required since a recent update. Not granting them in the role results in errors in the ApplicationSet controller's logs, e.g.
(without `list`)
```
W0816 22:58:18.236433       1 reflector.go:539] pkg/mod/k8s.io/client-go@v0.29.6/tools/cache/reflector.go:229: failed to list *v1alpha1.AppProject: appprojects.argoproj.io is forbidden: User "system:serviceaccount:argocd:argocd-argo-cd-applicationset-controller" cannot list resource "appprojects" in API group "argoproj.io" in the namespace "argocd"
```
(without `watch`)
```
E0816 23:20:09.253511       1 reflector.go:147] pkg/mod/k8s.io/client-go@v0.29.6/tools/cache/reflector.go:229: Failed to watch *v1alpha1.AppProject: unknown (get …
```

[bitnami/argo-cd] Add missing verbs to ApplicationSet role

---

bitnami/valkey-cluster/CHANGELOG.md
bitnami/valkey-cluster/Chart.yaml
bitnami/valkey-cluster/templates/valkey-statefulset.yaml

`redis_exporter` does not adapt the env-vars to the `VALKEY_` format.
https://github.com/oliver006/redis_exporter?tab=readme-ov-file#command-line-flags
- fixes #28564

[bitnami/valkey-cluster] Fix env-vars for metrics container

---

.vib/kibana/cypress/cypress/e2e/kibana.cy.js
bitnami/kibana/CHANGELOG.md
bitnami/kibana/Chart.yaml

Increase wait for DOM content in Cypress test/
Reduce failures for different scenarios that require more time to load.
N/A
Test fails on AKS with Photon OS 5.0 distro.

[bitnami/kibana] Increase wait for DOM content in Cypress test

---

.vib/argo-cd/cypress/cypress/e2e/argo_cd.cy.js
bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml

Added a test change to the Argo CD Cypress tests to address an issue where the UI was not loading fast enough on some platforms, leading to an error when attempting to click on an element.
This change improves the reliability of the Cypress tests.
The error encountered was: 
```
'FAILURES: [Timed out retrying after 30050ms: `cy.click()` failed because this element: `<span class="applications-list__title" aria-expanded="false">all-new...</span>` is being covered by another element: `<div class="white-box">...</div>` Fix this problem, or use {force: true} to disable error checking. <https://on.cypress.io/element-cannot-be-interacted-with>
```

[bitnami/argo-cd] test: :white_check_mark: Improve resilience of cypress test

---

.vib/mongodb-sharded/ginkgo/mongodb_suite_test.go
.vib/mongodb-sharded/ginkgo/mongodb_test.go
bitnami/mongodb-sharded/CHANGELOG.md
bitnami/mongodb-sharded/Chart.yaml

Updates the ginkgo tests to use rollout restart instead of replica scale up/down

[bitnami/mongodb-sharded]Ginkgo tests: Use rollout instead of scale down

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.yaml
bitnami/mlflow/README.md
bitnami/mlflow/values.yaml

AWS S3 HTTP endpoints are always regional, with `s3.amazonaws.com` defaulting to us-east-1. To avoid issues or confusion when using buckets from other regions, we should encourage including region code in the host.
Avoid potential issues with buckets in AWS S3 regions other than us-east-1.
None.
- fixes https://github.com/bitnami/charts/issues/23959

[bitnami/mlflow] Update externalS3.host example

---

bitnami/wordpress/CHANGELOG.md
bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/deployment.yaml

The php-var-dir needs to be pre-populated in the emptyDir volume to avoid issues in PHP session management.
Same fix as https://github.com/bitnami/charts/pull/25697 but for wordpress

[bitnami/wordpress] Fix php session mgmt

---

bitnami/jupyterhub/CHANGELOG.md
bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/README.md
bitnami/jupyterhub/templates/hub/deployment.yaml

When using fluxCD or argoCD `and` using an external postgres instances, the postgres image is lost in translation and causes the following error.
```
Helm install failed for release my_namespace/jupyterhub with chart jupyterhub@7.2.14: template: jupyterhub/templates/hub/deployment.yaml:82:20: executing "jupyterhub/templates/hub/deployment.yaml" at <include "common.images.image" (dict "imageRoot" .Values.postgresql.image "global" .Values.global)>: error calling include: template: jupyterhub/charts/common/templates/_images.tpl:12:39: executing "common.images.image" at <.imageRoot.registry>: can't evaluate field registry in type interface {}
``` 
This creates a catchall so that the deploy user/manifest can still lint the postgres image to the init container and deploy successfully. 
fluxCD …

[bitnami/juypterhub] postgres image missing when postgres is disabled (fluxCD/argoCD)

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/templates/_helpers.tpl
bitnami/keycloak/values.yaml

Currently, a different database user secret key cannot be used in Keycloak, even if it can be changed in the PostgreSQL sub-chart.
The following does not affect Keycloak because the key is hard-coded in Keycloak:
```yaml
keycloak:
postgresql:
auth:
secretKeys:
userPasswordKey: "password-user"
```
Hence, the database user's secret key should be set to the one used in PostgreSQL (and fallback to `password`).
Allow to customize the database user secret key which is important if the user uses an existing secret.
No behavior change.
- fixes #
None.

[bitnami/keycloak] Use database user secret key from PostgreSQL chart

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/statefulset.yaml

This change adds an emptyDir volume mount to the `/bitnami` folder in the Keycloak deployment. This is necessary for the init scripts to work properly.
- Ensures that the init scripts have the necessary permissions and storage to function correctly.
- Improves the overall stability and reliability of the Keycloak deployment.
- Slight increase in resource usage due to the additional volume mount.
- fixes #15930

[bitnami/keycloak] fix: :bug: Add emptyDir at /bitnami to allow init scripts

---

bitnami/mariadb/CHANGELOG.md
bitnami/mariadb/Chart.yaml
bitnami/mariadb/templates/primary/statefulset.yaml
bitnami/mariadb/templates/secondary/statefulset.yaml

This fixes deprecation warnings in startup/liveness/readiness probes.
The `mysqladmin` command emits a deprecation warning, this is the first line of output, and this is the line that gets included in k8s events when a probe fails.  This obscures the actual error.
Before:
```
0s    Warning    Unhealthy    pod/mariadb-0    Readiness probe failed: mysqladmin: Deprecated program name. It will be removed in a future release, use '/opt/bitnami/mariadb/bin/mariadb-admin' instead...
```
After:
```
0s    Warning    Unhealthy    pod/mariadb-0    Readiness probe failed: mariadb-admin: connect to server at 'localhost' failed...
```
If people override the container image/version tag with something much older, it may not work.
Fixes #29016
Besides this, there's another deprecation message in the …

[bitnami/mariadb] Fix deprecation warnings in checks

---

bitnami/jupyterhub/CHANGELOG.md
bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/values.yaml

Fix idents for extra volumes and extra volume mounts in the values of Jupyterhub.
The Singleuser deployment with configured extra volumes will be successful.
- fixes #24458

[bitnami/jupyterhub] Fix indents of singleuser extra volumes & mounts for #24458

---

.vib/rabbitmq/ginkgo/rabbitmq_test.go
bitnami/rabbitmq/CHANGELOG.md
bitnami/rabbitmq/Chart.yaml

This PR improves Ginkgo tests reliability for RabbitMQ chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/rabbitmq] Improve Ginkgo test

---

bitnami/cilium/CHANGELOG.md
bitnami/cilium/Chart.yaml
bitnami/cilium/templates/_helpers.tpl
bitnami/cilium/templates/hubble-ui/rbac.yaml

This change updates the Hubble UI ClusterRole objects in the bitnami/cilium chart to use the fullname.namespace helper. This fix prevents collisions when deploying the chart multiple times in different namespaces.
- Allows multiple deployments of the cilium chart in different namespaces without ClusterRole conflicts

[bitnami/cilium] fix: :bug: Use namespace to avoid collisions in hubble UI RBAC objects

---

.vib/valkey-cluster/ginkgo/valkey_test.go
bitnami/valkey-cluster/CHANGELOG.md
bitnami/valkey-cluster/Chart.yaml

This PR modifies the ginkgo tests for the valkey-cluster chart to improve reliability. Specifically, it changes the "scale to 0 and back to n replicas" operation, which was used to ensure persistence, to a restart operation. This change addresses reliability issues encountered in some cloud environments where scaling to 0 caused problems with PVCs and occasionally led to race conditions.
- Improved test reliability across different cloud environments
- Reduced likelihood of PVC-related issues during testing
- Minimized occurrence of race conditions
- Maintained ability to verify persistence logic without compromising stability
- The restart operation may not cover all edge cases that the scale to 0 operation did, although it should be sufficient for verifying persistence in most scenarios

[bitnami/valkey-cluster] test: :white_check_mark: Improve ginkgo tests reliability

---

.vib/keydb/goss/goss.yaml
bitnami/keydb/CHANGELOG.md
bitnami/keydb/Chart.yaml

Goss tests are executed inside the `keydb-master-0` pod and, we're implicitly testing that `keydb-master` service works as expected (otherwise Replica pods won't be able to sync data from the master).
Therefore, we can simplify Goss tests and use `127.0.0.1` to run `keydb-cli` commands that target the master.
Simplify CI tests
None
None
N/A

[bitnami/keydb] ci: simplify goss tests

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/_helpers.tpl

If the containerSecurityContext is enabled, it adds securityContext to the initContainer dns-check which is missing
The initContainer has securityContext like the log-dir initContainer.

[bitnami/mongodb] add securityContext via helper to initContainter dns-check

---

.vib/cilium/goss/goss-wait.yaml
.vib/cilium/vib-verify.json
bitnami/cilium/CHANGELOG.md
bitnami/cilium/Chart.yaml

This PR improves the test resiliency of the bitnami/cilium chart by addressing DNS resolution issues encountered on some platforms. The change adds a wait mechanism in the goss tests to ensure that all necessary services are ready before proceeding with DNS resolution checks.
1. Increased reliability of the test suite, particularly on platforms where services may take longer to become fully operational.
2. Reduction in false negative test results caused by premature DNS resolution attempts.

[bitnami/cilium] test: :white_check_mark: Improve resiliency of goss test

---

.vib/cilium/goss/goss-wait.yaml
bitnami/cilium/CHANGELOG.md
bitnami/cilium/Chart.yaml

This change adds a waiting time to the goss test to address issues we've been experiencing with goss testing and some endpoints. The modification introduces a delay before checking the endpoints, allowing more time for services to fully initialize.

[bitnami/cilium] test: :white_check_mark: Add a wait before goss test

---

bitnami/cassandra/README.md

Fixed the typo and changed to "dynamically".

[bitnami/cassandra] Update readme to fix typo

---

bitnami/kafka/README.md

Update kafka readme with new externalAccess services architecture
LoadBalancers will be created correctly

[bitnami/kafka] update readme with new architecture for externalAccess services

---

.vib/postgresql-ha/ginkgo/postgresql_test.go
bitnami/postgresql-ha/CHANGELOG.md
bitnami/postgresql-ha/Chart.yaml

This PR modifies the ginkgo tests for the postgresql-ha chart to improve reliability. Specifically, it changes the "scale to 0 and back to n replicas" operation, which was used to ensure persistence, to a restart operation. This change addresses reliability issues encountered in some cloud environments where scaling to 0 caused problems with PVCs and occasionally led to race conditions.
- Improved test reliability across different cloud environments
- Reduced likelihood of PVC-related issues during testing
- Minimized occurrence of race conditions
- Maintained ability to verify persistence logic without compromising stability
- The restart operation may not cover all edge cases that the scale to 0 operation did, although it should be sufficient for verifying persistence in most scenarios

[bitnami/postgresql-ha] test: :white_check_mark: Improve ginkgo test reliability

---

bitnami/cassandra/CHANGELOG.md
bitnami/cassandra/Chart.yaml
bitnami/cassandra/README.md
bitnami/cassandra/templates/initdb-configmap.yaml
bitnami/cassandra/templates/statefulset.yaml
bitnami/cassandra/values.yaml

This pull request introduces a new feature to the bitnami/cassandra chart, allowing users to set init scripts directly in the `values.yaml` file. Previously, init scripts could only be set using configmaps or secrets. This change aligns with the functionality available in other charts, such as bitnami/mariadb and bitnami/mariadb-galera.
Users will have a more straightforward method for setting init scripts, improving ease of use and consistency across Bitnami charts.
n/a

[bitnami/cassandra] feat: :sparkles: Allow setting initdb scripts in values

---

.vib/cassandra/ginkgo/cassandra_test.go
bitnami/cassandra/CHANGELOG.md
bitnami/cassandra/Chart.yaml

This pull request improves the resiliency of the tests in the bitnami/cassandra chart. The restart sequence for instances will now proceed from instance N-1 to 0, allowing for checks to be performed in the reverse order, ensuring a more robust verification process.

[bitnami/cassandra] test: :white_check_mark: Improve ginkgo testing reliability

---

bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.yaml
bitnami/apisix/values.yaml

The `multi-auth` plugin that was added to APISIX in the 3.8.0 release is not available in the plugins list even though the APISIX version that is being used in 3.10.0 and I could see the plugin by shelling into the container.
https://apisix.apache.org/docs/apisix/next/plugins/multi-auth/

[bitnami/apisix] Added multi-auth plugin to the plugins list

---

bitnami/elasticsearch/CHANGELOG.md
bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/coordinating/statefulset.yaml
bitnami/elasticsearch/templates/data/statefulset.yaml
bitnami/elasticsearch/templates/ingest/statefulset.yaml
bitnami/elasticsearch/templates/master/statefulset.yaml

Signed-off-by: Karel Vanden Houte <karel.vandenhoute@outlook.com>
Resolves the bug where you can not have sysctlImage disabled, but do want to copy tls certs
None
- fixes #29187

[bitnami/elasticsearch:21.3.10] Unable to copy tls certificates when sysctlImage is disabled 

---

.vib/clickhouse/ginkgo/clickhouse_suite_test.go
.vib/clickhouse/ginkgo/clickhouse_test.go
bitnami/clickhouse/CHANGELOG.md
bitnami/clickhouse/Chart.yaml

This PR improves Ginkgo tests reliability for Clickhouse chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/clickhouse] Improve Ginkgo test

---

.vib/cilium/runtime-parameters.yaml
bitnami/cilium/CHANGELOG.md
bitnami/cilium/Chart.yaml
bitnami/cilium/templates/NOTES.txt

This PR introduces a K8s job for VIB testing that rollout restarts Cilium sub-components deployments after Cilium agents are ready.
It also adds a note in NOTES.txt warning users about unmanaged pods.
Ensure Cilium sub-components aren't assigned IPs from the pre-configured CNI.
None
None
N/A

[bitnami/cilium] Rollout restart Cilium sub-components for better VIB reliability

---

bitnami/clickhouse/CHANGELOG.md
bitnami/clickhouse/Chart.yaml
bitnami/clickhouse/templates/statefulset.yaml

ArgoCD says that the VolumeClaimTemplate is missing the kind and apiVersion and tries to add it. Since this is never addressed in the actual app (ArgoCD is set to automatically "fix" itself), the issue repeats over and over.
ArgoCD will not try to constantly "fix" the application to be in sync. No need to workaround with strategicMergePatches
None found, fully compatible.

[bitnami/clickhouse] fix: Add missing version, kind to volumeClaimTemplates

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/values.yaml

Just make the comments clearer about what keys are required for the password of jks truststore and keystore.
Also, remove the contradicting comment about `usePem` stating that it will search for `keycloak.crt` and  `keycloak.key` while in reality it uses `tls.key` and `tls.crt`.
Document the right behaviour.

[bitnami/keycloak] Specify which keys must the secret have for jks in values.yaml comments

---

bitnami/mongodb-sharded/CHANGELOG.md
bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/_helpers.tpl

The namespace part of primaryhost in configsvr is modified to use `common.names.namespace`.
When installing helm, we can set a consistent namespace by simply setting the override namespace without passing a separate namespace argument. Therefore, mongodb-sharded charts become easier to use as subcharts.
N/A
- fixes #29142

[bitnami/mongodb-sharded] Changed to use namespaceOverride value when defining primaryhost in configsvr

---

bitnami/rabbitmq/CHANGELOG.md
bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/statefulset.yaml

This mirrors the use of `common.tplvalues.render` on `resources` values, like is done in many other Bitnami charts,
Users can provide templated strings to render for `resources` values.
None noted
- fixes #

[bitnami/rabbitmq] Allow rendering resources values

---

bitnami/logstash/CHANGELOG.md
bitnami/logstash/Chart.yaml
bitnami/logstash/templates/networkpolicy.yaml

Fixes the missing protocol in computed NetworkPolicy for logstash.
We can now open ports on UDP protocol.
I don't see any.
- fixes #29129 
None

[bitnami/logstash] fix #29129 missing protocol in networkPolicy

---

bitnami/memcached/CHANGELOG.md
bitnami/memcached/Chart.yaml
bitnami/memcached/templates/deployment.yaml
bitnami/memcached/templates/statefulset.yaml

This mirrors the use of `common.tplvalues.render` on `resources` values, like is done in many other Bitnami charts,
Users can provide templated strings to render for `resources` values.
None noted
- fixes #

[bitnami/memcached] Allow rendering resources values

---

bitnami/nginx/CHANGELOG.md
bitnami/nginx/Chart.yaml
bitnami/nginx/templates/prometheusrules.yaml

This change removes a conflicting label from the prometheusrules template. Two labels with the key 'app.kubernetes.io/component' existed. This is not possible, and caused issues with FluxCD. This change removes the first label 'app.kubernetes.io/component=nginx' as it was overwritten with 'app.kubernetes.io/component=metrics' during manual installs anyways.
This chart can be deployed by FluxCD
None
- fixes #

[bitnami/nginx] Release 18.1.12 - bugfix prometheusrules label collision

---

bitnami/grafana-tempo/CHANGELOG.md
bitnami/grafana-tempo/Chart.yaml
bitnami/grafana-tempo/templates/compactor/deployment.yaml
bitnami/grafana-tempo/templates/distributor/deployment.yaml
bitnami/grafana-tempo/templates/ingester/statefulset.yaml
bitnami/grafana-tempo/templates/metrics-generator/deployment.yaml
bitnami/grafana-tempo/templates/querier/deployment.yaml
bitnami/grafana-tempo/templates/query-frontend/deployment.yaml
bitnami/grafana-tempo/templates/vulture/deployment.yaml

This mirrors the use of `common.tplvalues.render` on `resources` values, like is done in many other Bitnami charts,
Users can provide templated strings to render for `resources` values.
None noted
- fixes #

[bitnami/grafana-tempo] Allow rendering resources values

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/statefulset.yaml
bitnami/mongodb/templates/backup/cronjob.yaml
bitnami/mongodb/templates/hidden/statefulset.yaml
bitnami/mongodb/templates/replicaset/statefulset.yaml
bitnami/mongodb/templates/standalone/dep-sts.yaml

This mirrors the use of `common.tplvalues.render` on `resources` values, like is done in many other Bitnami charts,
Users can provide templated strings to render for `resources` values.
None noted
- fixes #

[bitnami/mongodb] Allow rendering resources values

---

bitnami/nats/CHANGELOG.md
bitnami/nats/Chart.yaml
bitnami/nats/README.md
bitnami/nats/templates/statefulset.yaml
bitnami/nats/values.yaml

Added the `PersistentVolumeRetentionPolicy` to the NATS Statefulset so that PVCs can be configured to automatically be cleaned up when scaling or deleting the NATS Statefulset.
Disabled and set to Retain by default.
PVCs can be configured to automatically be deleted (retained by default) when scaling or deleting the statefulset.
None, disabled by default as in other charts (`bitnami/redis`, `bitnami/postgresql`, for example)
None

[bitnami/nats] Add `PersistentVolumeRetentionPolicy`

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_compatibility.tpl
template/CHART_NAME/values.yaml

Adding new `global.compatibility.omitEmptySeLinuxOption` option to conditionally remove empty/falsy `seLinuxOptions`property.
- fixes #28934

[bitnami/common] Add option to remove empty seLinuxOptions from securityContext in non OpenShift environment

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/applicationset/deployment.yaml

No functional change. Remove (illegal) duplicate yaml key
Tools such as kustomize (relying on kyaml) will no longer crash like this:
```
❯ kubectl kustomize --enable-helm .
error: map[string]interface {}(nil): yaml: unmarshal errors:
line 19: mapping key "selector" already defined at line 18
```
I'm not too familiar with helm's syntax, I _hope_ this is correct (`$podLabels` just gets assigned, doesn't matter where)
possible drawback: I missed something obvious and this is wrong
n/a - didn't bother creating an issue for such a trivial fix
This is a regression from https://github.com/bitnami/charts/pull/18458, [here](https://github.com/bitnami/charts/pull/18458/files#diff-4a98e2a629963611f398c32ddeb6de161be4e4444ba9c2da413510c93acf8ff5)
I assume this was just a mass-edit copy pasting mishap

[bitnami/argo-cd] Fix duplicate `selector:` in applicationset deployment

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/templates/_helpers.tpl

Switch to the common helper `common.secrets.passwords.manage` for managing the password instead of the local undocumented helper.
* Streamline with the other charts
* Use a documented helper
* Benefit from the common helper features
The custom helper was introduced by https://github.com/bitnami/charts/pull/8486

[bitnami/redis] Use common password manager to handle password

---

bitnami/external-dns/CHANGELOG.md
bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/_helpers.tpl

This resolves an issue when using workload identity with the external-dns oci provider. When `oci.useWorkloadIdentity` is true, the secret is needed to configure the oci provider as such, but secret generation depends on the field `oci.privateKeyFingerprint` being set even though it's not used.
I've updated the conditions to use either `oci.useWorkloadIdentity` or `oci.privateKeyFingerprint` to determine if the secret should be generated or not.
- Fixes an issue where `oci.privateKeyFingerprint` must be specified even when it's not needed.
None

[bitnami/external-dns] Fixed oci workload identity secret creation

---

bitnami/nats/CHANGELOG.md
bitnami/nats/Chart.yaml
bitnami/nats/values.yaml

* Only enable Clustering if `replicaCount > 1`
* Allows single replica Jetstream to work as expected
Allows you to run NATS with Jetstream enabled in a single replica
- fixes #29378

[bitnami/nats] Fix single replica Jetstream

---

.vib/nats/ginkgo/nats_test.go
bitnami/nats/CHANGELOG.md
bitnami/nats/Chart.yaml

This PR improves Ginkgo tests reliability for NATS chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/nats] Improve Ginkgo tests

---

.vib/consul/ginkgo/consul_test.go
bitnami/consul/CHANGELOG.md
bitnami/consul/Chart.yaml

This PR improves Ginkgo tests reliability for Consul chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/consul] test: :white_check_mark: Improve reliability of ginkgo tests

---

.vib/elasticsearch/ginkgo/elasticsearch_test.go
bitnami/elasticsearch/CHANGELOG.md
bitnami/elasticsearch/Chart.yaml

This PR improves Ginkgo tests reliability for Elasticsearch chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/elasticsearch] test: :white_check_mark: Improve reliability of ginkgo tests

---

.vib/kafka/ginkgo/kafka_test.go
bitnami/kafka/CHANGELOG.md
bitnami/kafka/Chart.yaml

This PR improves Ginkgo tests reliability for Kafka chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/kafka] test: :white_check_mark: Improve reliability of ginkgo tests

---

.vib/mariadb/ginkgo/mariadb_test.go
bitnami/mariadb/CHANGELOG.md
bitnami/mariadb/Chart.yaml

This PR improves Ginkgo tests reliability for MariaDB chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/mariadb] test: :white_check_mark: Improve reliability of ginkgo tests

---

.vib/mysql/ginkgo/mysql_test.go
bitnami/mysql/CHANGELOG.md
bitnami/mysql/Chart.yaml

This PR improves Ginkgo tests reliability for MySQL chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/mysql] test: :white_check_mark: Improve reliability of ginkgo tests

---

.vib/seaweedfs/ginkgo/seaweedfs_test.go
bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.yaml

This PR improves Ginkgo tests reliability for SeaweedFS chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/seaweedfs] test: :white_check_mark: Improve reliability of ginkgo tests

---

.vib/etcd/ginkgo/etcd_test.go
bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.yaml

This PR improves Ginkgo tests reliability for etcd chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/etcd] test: :white_check_mark: Improve reliability of ginkgo tests

---

.vib/postgresql/ginkgo/postgresql_test.go
bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.yaml

This PR improves Ginkgo tests reliability for PostgreSQL chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/postgresql] test: :white_check_mark: Improve reliability of ginkgo tests

---

.vib/opensearch/ginkgo/opensearch_test.go
bitnami/opensearch/CHANGELOG.md
bitnami/opensearch/Chart.yaml

This PR improves Ginkgo tests reliability for Opensearch chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/opensearch] test: :white_check_mark: Improve reliability of ginkgo tests

---

.vib/solr/ginkgo/solr_suite_test.go
.vib/solr/ginkgo/solr_test.go
bitnami/solr/CHANGELOG.md
bitnami/solr/Chart.yaml

This PR improves Ginkgo tests reliability for Solr chart by replacing scaling down to 0 and up to the original number of replicas by running a "rollout restart" on the statefulset pods.
N/A

[bitnami/solr] test: :white_check_mark: Improve reliability of ginkgo tests

---

bitnami/minio/CHANGELOG.md
bitnami/minio/Chart.yaml
bitnami/minio/templates/provisioning-job.yaml

This PR adds an extra wait because of an issue starting with this version https://github.com/bitnami/charts/pull/28118. It seems that the `--wait` and `--json` commands are not honored at the same time, causing a deployment issue in apps that have minio like grafana-mimir or mastodon. We add an extra wait to ensure that the restart finishes successfully.
- fixes #

[bitnami/minio] fix: :bug: Add sleep to avoid race condition in provisioning

---

bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.yaml
bitnami/harbor/templates/registry/registry-secret.yaml

`REGISTRY_HTTP_SECRET` value should be base64 encoded when taken from an existing secret
The chart does not generate an invalid secret definition when `registry.existingSecret` value is specified.
The should be none.
- fixes #29372
None

[bitnami/harbor] Fix REGISTRY_HTTP_SECRET encoding when declared on an existing secret

---

bitnami/opensearch/README.md

This change replaces the links to open.co with links to opensearch.org.
The links in the documentation works.
The content of the pages may have changed, so these new pages are my best guess for the intended content.
- fixes #29547
Apparently there was a missing trailing newline in the README and my editor added it automatically. I think this is better, but just tell me if I should remove it since it does not technically belong to this PR!

[bitnami/opensearch] Replace links to open.co with opensearch.org

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/templates/servicemonitor.yaml
bitnami/redis/values.yaml

When setting the additionalEndpoints option for ServiceMonitor (to scrape metrics of the sentinel container) the generated chart is invalid.
To reproduce do the following in the `bitnami/redis` folder on main:
2. in `values.yaml` enable metrics ie set `metrics.enabled` to `true`
3. in `values.yaml` enable serviceMonitor ie set `metrics.serviceMonitor.enabled` to `true`
4. uncomment the example under `metrics.serviceMonitor.additionalEndpoints` (also delete the `[]` after `additionalEndpoints:` itself)
5. run `helm template . -f values.yaml --debug` and you get the error below:
```
install.go:222: [debug] Original chart version: ""
install.go:239: [debug] CHART PATH: /Users/user1/git/charts/bitnami/redis
Error: template: redis/templates/servicemonitor.yaml:48:29: executing …
```

[bitnami/redis] - fix additionalEndpoints in servicemonitor

---

bitnami/valkey-cluster/CHANGELOG.md
bitnami/valkey-cluster/Chart.yaml
bitnami/valkey-cluster/templates/valkey-statefulset.yaml

change the scheme used to form the metrics target url
this makes metrics work, as redis_exporter does not support valkeys/valkey scheme

[bitnami/valkey-cluster] the redis_url for redis_exporter should use rediss/redis scheme, not valkeys/valkey.

---

bitnami/opensearch/CHANGELOG.md
bitnami/opensearch/Chart.yaml
bitnami/opensearch/templates/_helpers.tpl

This PR follows up https://github.com/bitnami/charts/pull/29586 allowing the init-container to be executed as a non-root user.
The chart can be installed in restrictive environment such as Openshift where only non-root containers are allowed
None
None
N/A

[bitnami/opensearch] Plugin installation as non-root user

---

bitnami/argo-workflows/CHANGELOG.md
bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/templates/controller/workflow-role.yaml

Updates the workflow `Role` to use the recommended CRDs in the workflow RBAC as per: https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/
When deploying the chart I noticed warnings in the `wait` container of the tasks:
```level=warning msg="failed to patch task result, falling back to legacy/insecure pod patch, see https://argo-workflows.readthedocs.io/en/release-3.5/workflow-rbac/" error="[workflowtaskresults.argoproj.io](http://workflowtaskresults.argoproj.io/) is forbidden: User \"system:serviceaccount:argo:argo-test-argo-workflows-workflows\" cannot create resource \"workflowtaskresults\" in API group \"[argoproj.io](http://argoproj.io/)\" in the namespace \"argo\"```
Minimal `values.yaml`:
```yaml
workflows:
serviceAccount:
create: true
automountServiceAccountToken: …
```

[bitnami/argo-workflows] Update Workflow RBAC to Use Recommended `workflowtaskresults` CRD

---

bitnami/mongodb-sharded/CHANGELOG.md
bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml
bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml

This PR modifies how the `datadir` volume is created and mounted when `persistence.enabled` parameter is set to false within statefulset manifests for both config server and shard server. It also removes some bad lines of code.
Persistence can now be disabled for both config server and shard server without resulting in a YAML parse error.
- fixes #29127 
Disabling persistence can be useful when the default configuration to be set doesn't fit your cluster.
- [X ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [X ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)
- [X ] Title …

[bitnami/mongodb-sharded] Fix uncapacity to disable persistence

---

bitnami/drupal/CHANGELOG.md
bitnami/drupal/Chart.yaml
bitnami/drupal/templates/ingress.yaml

This should fix the issue mentioned in https://github.com/bitnami/charts/issues/29190, which impacts the nginx, wordpress and drupal charts.
It should now be possible to use an ingress.hostname value of www.example.com and set the nginx.ingress.kubernetes.io/from-to-www-redirect annotation, without a TLS host for www.www.example.com being added.

[bitnami/drupal] templates/ingress.yaml: fix wrong www.www tls name

---

bitnami/spark/CHANGELOG.md
bitnami/spark/Chart.yaml
bitnami/spark/templates/networkpolicy-worker.yaml

Fix wrong application of `extraIngress` configuration value from master to workers in Spark chart.
- fixes #

[bitnami/spark] Fix extraEgress being applied from master instead of worker

---

bitnami/nginx/CHANGELOG.md
bitnami/nginx/Chart.yaml
bitnami/nginx/templates/ingress.yaml

This should fix the issue mentioned in #29190, which impacts the **nginx**, **wordpress** and **drupal** charts.
It should now be possible to use an ingress.hostname value of [www.example.com](http://www.example.com/) and set the nginx.ingress.kubernetes.io/from-to-www-redirect annotation, without a TLS host for [www.www.example.com](http://www.www.example.com/) being added.

[bitnami/nginx] templates/ingress.yaml: fix wrong www.www tls name

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_tplvalues.tpl

Adding a new helper to the Bitnami common chart. This helper uses the sprig function [mergeOverwrite](https://masterminds.github.io/sprig/dicts.html#mergeoverwrite-mustmergeoverwrite) to merge multiple dictionaries into one.
* merging two or more dicts with precedence consistent with [mergeOverwrite](https://masterminds.github.io/sprig/dicts.html#mergeoverwrite-mustmergeoverwrite)
* precedence "from **right to left**"
* fixes issues, where it is not possible to overwrite "truthy" values with "falsy" values, even when the "falsy" values should have precedence according to the docs
* for more see #29566 and https://github.com/Masterminds/sprig/issues/134
None
- needed for #27628 
- fixes #29566 
- Masterminds/sprig issue for reference https://github.com/Masterminds/sprig/issues/134
%

[bitnami/common] Add common.tplvalues.merge-overwrite helper

---

bitnami/gitea/CHANGELOG.md
bitnami/gitea/Chart.lock
bitnami/gitea/Chart.yaml
bitnami/gitea/README.md

[bitnami/gitea] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/discourse/CHANGELOG.md
bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml
bitnami/discourse/README.md

[bitnami/discourse] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md

[bitnami/mastodon] feat!: :arrow_up: :boom: Bump PostgreSQL to 17.x

---

.github/workflows/ci-pipeline.yml

Adds a new step to the CI pipeline that checks the chart does not include hardcoded images in its templates.
The goal of this feature is to avoid accidentally merging charts that have containers defined directly in the manifests instead of using the values.yaml.
The action searches for any `image:` key in the `${CHART}/templates` folder and checks it is formatted as `image: {{ ... }}`.
Images formatted as plain text will cause the workflow to fail, e.g. `image: foo/bar`

[actions] CI pipeline: Check hardcoded images

---

bitnami/grafana-operator/CHANGELOG.md
bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/values.yaml

Provided default samples didn't work.
Fixes envFrom examples.
Allowing Grafana deployment to consume the environment from preprovisioned secrets/configmaps.
N/A
N/A
N/A

[bitnami/grafana-operator] Fixed envFrom examples

---

bitnami/thanos/CHANGELOG.md
bitnami/thanos/Chart.yaml
bitnami/thanos/templates/receive/statefulset.yaml
bitnami/thanos/templates/ruler/statefulset.yaml
bitnami/thanos/templates/storegateway/statefulset.yaml

Reverts #29673
Fixes #29749
Although the fix is correct, modifying the Statefulset immutable fields is problematic and should not have been included in a patch release.
Reverting the change so users do not have to face issues while upgrading, we may include this in the next thanos major.

[bitnami/thanos] Revert #29673

---

bitnami/kubernetes-event-exporter/CHANGELOG.md
bitnami/kubernetes-event-exporter/Chart.yaml
bitnami/kubernetes-event-exporter/templates/rbac-leader-election.yaml

This PR adds the `metadata.namespace` value to the leader election `RoleBinding` to align with the other resources deployed by this chart.
In addition to aligning better with the other resources. This fixes integration with ArgoCD, which requires an explicit namespace to be specific on all namespaced resources.
N/A
Roughly identical MR I put up earlier for bitnami/schema-registry https://github.com/bitnami/charts/pull/24284

[bitnami/kubernetes-event-exporter] Add  to leader election RoleBinding

---

bitnami/contour/CHANGELOG.md
bitnami/contour/Chart.yaml
bitnami/contour/templates/default-backend/deployment.yaml

The default backend's deployment.yaml currently contains the following code:
```yaml
{{- if .Values.defaultBackend.extraVolumeMounts }}
volumeMounts: {{- include "common.tplvalues.render" ( dict "value" .Values.contour.extraVolumeMounts "context" $ ) | nindent 12 }}
{{- end }}
```
Note that the if condition uses the correct variable (`defaultBackend.extraVolumeMounts`) whereas the render call uses the incorrect one (`contour.extraVolumeMounts`). This looks like a simple copy and paste mistake.
The default backends' volumes get rendered correctly.

[bitnami/contour]: Fix invalid extraVolumeMounts

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/_helpers.tpl

Since a [change](https://github.com/mFranz82/charts/commit/8d231f86e78a6ad07b5f588a0eedebf7c21d0f9b) made 3 month before the templating fails if using ` redis.enabled=false `
```
Error: 
execution error at (argo-cd/templates/server/deployment.yaml:100:50): 
If the redis dependency is disabled you need to add an external redis host
```
The error is triggered at this point in Notes.txt
```
{{- if $message -}}
{{-   printf "\nVALUES VALIDATION:\n%s" $message | fail -}}
{{- end -}}
```
And occurs because the validation function could never be successful:
```
{{/*
Validate external Redis config
*/}}
{{- define "argocd.validateValues.externalRedis" -}}
{{- if not .Values.redis.enabled -}}
Argo CD: If the redis dependency is disabled you need to add an external redis port
{{- end -}}
{{- end -}} …
```

[bitnami/argo-cd] fix: provide a functional validation function for validation

---

bitnami/mariadb/CHANGELOG.md
bitnami/mariadb/Chart.yaml
bitnami/mariadb/values.yaml
bitnami/mysql/Chart.yaml

- the change adds an entry `binlog_expire_logs_seconds=2592000` to the `primary.configuration` and `secondary.configuration` properties of values.yaml file
- this change will clean up binary logs older than 30 days, which currently does not happen (as discussed in #21886)
- old binary log files will not fill up the storage anymore
- binary log files, which are older than 30 days and are still needed, could get deleted
- fixes #21886

[bitnami/mariadb] add default binlog expiry configuration of 30 days

---

bitnami/wildfly/CHANGELOG.md
bitnami/wildfly/Chart.yaml
bitnami/wildfly/templates/management-ingress.yaml

Change "persistence" reference annotations to "mgmtIngress"
During the merge for management ingress annotations, they wrong takes annotations by "persistence" component instead "mgmtIngress".
Now the "mgmtIngress" component has right annonations.
- fixes #29787

[bitnami/wildfly] fix annotations merging for management ingress

---

bitnami/jenkins/CHANGELOG.md
bitnami/jenkins/Chart.yaml
bitnami/jenkins/templates/_helpers.tpl
bitnami/jenkins/templates/deployment.yaml
bitnami/jenkins/templates/init-hook-scripts-configmap.yaml
bitnami/jenkins/templates/init-script-configmap.yaml

Because not existing template about initScripts, initHookScripts 
So add init-scripts-configmap, init-hook-scripts-configmap
Now we can use values initScripts, initScriptCM, initScriptSecret, initHookScripts, initHookScriptCM, initHookScriptSecret
Nothing
- fixes #

[bitnami/jenkins] Fix: InitScripts, InitHookScripts

---

.github/workflows/ci-pipeline.yml

Fixes an issue with the hardcoded images check, where it would fail with the `bitnami/common` chart because it detects some empty image string.
Additionally fixes the regex by removing the `^` character that was added during code review.
At first I thought it was a good idea to prevent false positives, but in fact it may be used to bypass the test as it would fail to detect syntax as:
```
- image: test
```
Fixes issue with the CI pipeline affecting the `common` chart.
None known.
- This issue was affecting PR #29479

[github-actions] Fix issue with hardcoded-images check

---

bitnami/nginx/CHANGELOG.md
bitnami/nginx/Chart.yaml
bitnami/nginx/templates/NOTES.txt

When this verification was added (https://github.com/bitnami/charts/pull/26253/files), one of the images was added twice and using the wrong path, see https://github.com/bitnami/charts/pull/26253/files#diff-c1f6a431b1044866e4a53647d8ad582071b14f7424a968be5deed26d6edfed8eR74.
This is causing the following error given that this unexisting image is interpreted as a container substitution:
```
⚠ SECURITY WARNING: Original containers have been substituted. This Helm chart was designed, tested, and validated on multiple platforms using a specific set of Bitnami and Tanzu Application Catalog containers. Substituting other containers is likely to cause degraded security and performance, broken chart features, and missing environment variables.
Substituted images detected:
- %!s(<nil>)/:%!s(<nil>) …
```

[bitnami/nginx] Remove duplicated (and wrong) image in verification

---

bitnami/sealed-secrets/CHANGELOG.md
bitnami/sealed-secrets/Chart.yaml
bitnami/sealed-secrets/templates/role.yaml
bitnami/sealed-secrets/templates/rolebinding.yaml

Currently the sealed-secret chart fails to render with the following minimal values:
```yaml
additionalNamespaces: ["test"]
rbac:
clusterRole: false
namespacedRoles: true
```
This configuration causes namespaced roles to be created for every entry in `additionalNamespaces`. Within the definition of the namespaced roles some `include`s are called using `.` instead of `$`. Since this is happening within a `range` `.` does not reference the root context anymore.
The error message produced:
`Error: template: sealed-secrets/templates/rolebinding.yaml:55:24: executing "sealed-secrets/templates/rolebinding.yaml" at <include "sealed-secrets.namespacedRoleName" .>: error calling include: template: sealed-secrets/templates/_helpers.tpl:46:14: executing "sealed-secrets.namespacedRoleName" at …

[bitnami/sealed-secrets] Fix combination of additionalNamespaces, rbac.clusterRole=false and rbac.namespacedRoles=true

---

bitnami/discourse/CHANGELOG.md
bitnami/discourse/Chart.yaml
bitnami/discourse/templates/deployment.yaml

Fixes the mount path to use on the "install-plugins" init-container, so plugins are copied to the right folder.
This bug was introduced by myself at https://github.com/bitnami/charts/pull/29568 as reported by @netdata-be and @notz
Plugins' installation works as expected.
None
- fixes https://github.com/bitnami/charts/issues/29169
N/A

[bitnami/discourse]: (bugfix) fix mount path on install-plugins init-container

---

bitnami/rabbitmq/CHANGELOG.md
bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/_helpers.tpl
bitnami/rabbitmq/templates/secrets.yaml
bitnami/rabbitmq/values.yaml

Switch to the common helpers `common.secrets.passwords.manage` & `common.secrets.lookup` for managing the password instead of the local undocumented helper.
* Streamline with the other charts
* Use documented helpers
* Benefit from the common helpers features and maintenance

[bitnami/rabbitmq] Use common password/secrets manager to handle credentials

---

bitnami/grafana-loki/CHANGELOG.md
bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/values.yaml

Loki default configuration failed to start.
field embedded_cache not found in type cache.Config
The official configuration has written the wrong parameters before.
Fixed after v3.2.x version.
[cache_config](https://grafana.com/docs/loki/v3.2.x/configure/#cache_config)
relevant issues [issues](https://github.com/grafana/loki/issues/6915#issuecomment-1369488273)
Run successfully after modification.

[grafana-loki] Fix loki config results_cache type embedded-cache

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/templates/scripts-configmap.yaml

Fix `preExecCmds` to work as array.
Allow to use `preExecCmds` parameter.
N/A
- fixes #29893

[bitnami/redis] Fix preExecCmds parameter

---

bitnami/apache/CHANGELOG.md
bitnami/apache/Chart.yaml
bitnami/apache/templates/NOTES.txt

Removes wrong entries from the `common.warnings.modifiedImages` helper list.
Fixes issues with image checking.
None known.
- related to #29871

[bitnami/apache] Remove wrong entries from image verification

---

bitnami/pytorch/CHANGELOG.md
bitnami/pytorch/Chart.yaml
bitnami/pytorch/templates/NOTES.txt

Removes wrong entries from the `common.warnings.modifiedImages` helper list.
Fixes issues with image checking.
None known.
- related to #29871

[bitnami/pytorch] Remove wrong entries from image verification

---

bitnami/aspnet-core/CHANGELOG.md
bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/templates/NOTES.txt

Removes wrong entries from the `common.warnings.modifiedImages` helper list.
Fixes issues with image checking.
None known.
- related to #29871

[bitnami/aspnet-core] Remove wrong entries from image verification

---

bitnami/contour/CHANGELOG.md
bitnami/contour/Chart.yaml
bitnami/contour/templates/default-backend/deployment.yaml

The defaultBackend currently indents volumes to the same level as an individual container (8), however, it actually needs to be one level further up (6).
Currently, we have 
```
containers:
- name: default-backend
<snip>
{{- if .Values.defaultBackend.sidecars }}
{{- include "common.tplvalues.render" ( dict "value" .Values.defaultBackend.sidecars "context" $) | nindent 8 }}
{{- end }}
{{- if .Values.defaultBackend.extraVolumes }}
volumes: {{- include "common.tplvalues.render" ( dict "value" .Values.defaultBackend.extraVolumes "context" $ ) | nindent 8 }}
{{- end }}
```
... note that volumes is on the same indent level as an individual container. It should actually be one level up. This change does just that. I unfortunately missed this when upstreaming the original fix in …

[bitnami/contour]: Fix invalid volume indentation

---

bitnami/discourse/CHANGELOG.md
bitnami/discourse/Chart.yaml
bitnami/discourse/templates/deployment.yaml

When installing discourse behind a firewall, the "install-plugins" init-container cannot download the plugins without the proxy-settings defined in “discourse.extraEnvVars”:
```
discourse:
extraEnvVars:
- name: http_proxy
value: http://my.proxy
- name: https_proxy
value: http://my.proxy
- name: no_proxy
value: '.svc,.svc.cluster.local'
```
The "install-plugins" init-container can download the plugins.
See: https://github.com/bitnami/charts/pull/29986

[bitnami/discourse] include discourse.extraEnvVars in the "install-plugins" init-container

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.yaml
bitnami/etcd/templates/cronjob-defrag.yaml

The change fixes bitnami/etcd `defrag.cronjob.podLabels` bug, which breaks labels indentation.
Correct pod labels indentation.
None.
- fixes #30049

[bitnami/etcd]: Fix podLabels bug

---

.vib/solr/ginkgo/solr_suite_test.go
bitnami/solr/CHANGELOG.md
bitnami/solr/Chart.yaml

* Increase default timeout for ginkgo tests.
* Add TimeToLive parameter to created jobs.
Avoid timeout errors that we are facing in some test environments.
None
https://kubernetes.io/docs/concepts/workloads/controllers/ttlafterfinished/
- [] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)

[bitnami/solr] chore: Increase ginkgo test timeout

---

bitnami/external-dns/CHANGELOG.md
bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/_helpers.tpl

This fixes a bug where the secret containing the pihole secret was not created when the password value was set.

[bitnami/external-dns] fix: secret not getting created when pihole password value is set

---

bitnami/rabbitmq/CHANGELOG.md
bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/_helpers.tpl
bitnami/rabbitmq/values.yaml

I get an `You enabled configuring memory high watermark using a relative limit.` error when I remove the memory limit and set
```yaml
memoryHighWatermark:
enabled: true
type: absolute
value: 40Gi
```
That's because the chart validation does not check if the type is actually `relative` before looking for a memory limit.
I can set an absolute high watermark without memory limit specified.
None afaik.

[bitnami/rabbitmq] Allow missing memory limit when memoryHighWatermark is absolute

---

.vib/deepspeed/runtime-parameters.yaml
bitnami/deepspeed/CHANGELOG.md
bitnami/deepspeed/Chart.yaml

Increase client resources by default.
Some tests were failing randomly because client pods were being killed because the were running out of memory. OOMKilled (error 137)
None
- Fix random OOMKilled pods detected on tests.

[bitnami/deepspeed] chore: increase client memory

---

bitnami/kube-prometheus/CHANGELOG.md
bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/templates/prometheus/prometheus.yaml

Helm will render a valid spec for the thanos-sidecar if `prometheus.thanos.extraEnvVarsCM` and `prometheus.thanos.extraEnvVarsSecret` are not set.
- fixes https://github.com/bitnami/charts/issues/29799

[bitnami/kube-prometheus] Fix spec for thanos sidecar if no extraEnv is provided

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/_helpers.tpl

Use `common.tplvalues.render` to render resources of log dir, volume permissions and auto discovery init container as it's done for workload manifest statefulset or deployment.
This will allow us to be consistent on render of `.Values.resources` on every manifest.
None noted
- fixes #

[bitnami/mongodb] Fix render values of resources on init container

---

bitnami/kibana/CHANGELOG.md
bitnami/kibana/Chart.yaml
bitnami/kibana/templates/configmap.yaml
bitnami/kibana/values.yaml

This change defaults the host value to 0.0.0.0 instead of `::` in the configmap because unless folks have ipv6 enabled, :: causes Kibana to fail on startup. 
The majority of the world is using IPV4 and this is a more sane default. If needed, folks can update for ipv6 compatability manually. 
If you're using ipv6 without any ipv4 fallback, this change may be breaking (unlikely scenario) 
- fixes #17375

[bitnami/kibana] set base host to 0.0.0.0

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/_init_containers_sidecars.tpl
bitnami/airflow/templates/scheduler/deployment.yaml
bitnami/airflow/templates/web/deployment.yaml
bitnami/airflow/templates/worker/statefulset.yaml
bitnami/airflow/values.yaml

This PR splits the logic to load DAGs and plugins into different init containers and sidecars. Then, it ensure that only the ones related to plugins are used for Airflow Web server
The goal is simple: ensure we don't load/sync DAGs on this component given it doesn't need them.
None
None
N/A

[bitnami/airflow] Split init containers

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.yaml
bitnami/mastodon/templates/init-job/init-job-configmap.yaml

The version 9.0.0 bitnami/mastodon introduced a regression where the admin account is allows created.  This is fine for a new installs but needs to be set to false on upgrades.  Prior to Chart version 9.0.0 the creation of the admin account was controlled by .Values.initJob.createAdmin set as a boolean.  In version 9.0.0 this was moved to .Values.initJob.migrateAndCreateAdmin.createAdmin but configmap template referenced .Values.initJob.migrateAndCreateAdmin.  As a result https://github.com/bitnami/charts/blob/356941ddb5c6ebbd08867aae2b07dfa21ff0e394/bitnami/mastodon/templates/init-job/init-job-configmap.yaml#L51 was always inserted to the ConfigMap generated for init-job.  This means on upgrade when an admin account already exists init-job fails and the helm chart upgrade fails.
The …

[bitnami/mastodon] Mastodon initjob always tries to create admin on upgrade

---

bitnami/minio/CHANGELOG.md
bitnami/minio/Chart.yaml
bitnami/minio/templates/_helpers.tpl

The "Option to use a secret" introduced in `14.7.0` also brought a small bug with it: The [check if the secret should be created](https://github.com/bitnami/charts/blob/minio/14.8.0/bitnami/minio/templates/secrets.yaml#L6) expects a boolean, but ["include" always returns a string ](https://github.com/helm/helm/issues/11231). Because it is not used directly (only in the [minio.createSecret](https://github.com/bitnami/charts/blob/minio/14.8.0/bitnami/minio/templates/_helpers.tpl#L95) template), even setting `auth.useSecret` to `false` will result in the string "false". This string is then interpreted as / casted to a boolean in the corresponding `if`-clause, where it always is translated to `true` because it is not empty. (If you set `auth.useSecret` to an empty string, the secret will not …

[bitnami/minio] fix secret creation check

---

.github/workflows/ci-pipeline.yml

Add a step to the CI pipeline that checks the chart image warning list content is correct.
Helps avoiding accidents when adding new images to the chart.
It has issues with variables, which is the case of fluentd, which is a special case:
https://github.com/bitnami/charts/blob/005e0d696004dd972915f290b7caffb2bc332400/bitnami/fluentd/templates/NOTES.txt#L57-L64

[github-actions] Add test to check images warning list

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/config/configmap.yaml

This PR fixes a bug introduced at https://github.com/bitnami/charts/pull/30155 given we didn't update accordingly the Pod Templates.
Users can use the `KubernetesExecutor` executor.
None
- fixes https://github.com/bitnami/charts/issues/30210
N/A

[bitnami/airflow] bugfix: pod template

---

bitnami/contour/CHANGELOG.md
bitnami/contour/Chart.yaml
bitnami/contour/README.md
bitnami/contour/templates/crds/gateway-api-crds.yaml
bitnami/contour/values.yaml

This adds the ability to deploy the Gateway API CRDs with the Contour chart. It's disabled by default so the default behavior of the chart doesn't change.
This ensures that the Gateway API CRDs deployed in your cluster follows the versions supported in the deployed Contour version.
I don't see any.

[bitnami/contour] Add Gateway API CRDs

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.yaml
bitnami/etcd/templates/cronjob-defrag.yaml

Dear maintainers,
Fix volume indentation for defrag cronjob. Volume should have the path `jobTemplate.spec.template.spec.volumes` not `jobTemplate.spec.template.volumes`

[bitnami/etcd]: Fix volume indentation for defrag cronjob

---

.github/workflows/cd-pipeline.yml
.github/workflows/ci-pipeline.yml

In https://github.com/bitnami/charts/pull/30142 we are moving the kube-prometheus CRDs to a subchart. This is causing issues with the Github actions as it is incorrectly detecting more than one chart bump. In this PR we are changing the logic to only take into account the Chart.yaml files under the paths `bitnami/*/Chart.yaml`
- fixes #

[bitnami/*] ci: :construction_worker: Update get-chart to ignore local subcharts

---

bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.lock
bitnami/seaweedfs/Chart.yaml
bitnami/seaweedfs/templates/filer/statefulset.yaml
bitnami/seaweedfs/templates/master/statefulset.yaml
bitnami/seaweedfs/templates/s3/deployment.yaml
bitnami/seaweedfs/templates/security-configmap.yaml
bitnami/seaweedfs/templates/volume/statefulset.yaml
bitnami/seaweedfs/templates/webadv/deployment.yaml

This PR ensures we always mount the `security.toml` file at SeaweedFS components regardless security enhancements are enabled or not. When `security.enabled=false` we mount a dummy file like the one below:
```toml
[cors.allowed_origins]
values = "*"
```
Avoids the warning below on SeaweedFS components' logs which leads users to confusion:
```console
I1106 05:53:12.968388 config.go:53 Reading : Config File "security" Not Found in "[/opt/bitnami/seaweedfs /opt/bitnami/seaweedfs/.seaweedfs /usr/local/etc/seaweedfs /etc/seaweedfs]"
```
None
None
N/A

[bitnami/seaweedfs] Mount security.toml regardless security enhancements are enabled

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_secrets.tpl

This PR adds a new parameter `honorProvidedValues` to `common.secrets.manage`. This is to allow changing the value of a password secret using what is set in values.yaml. This is to allow the proper functionality of a future password update feature explored here https://github.com/bitnami/charts/tree/feat/mariadb-poc-update-password.
It is set to false by default to not break existing chart functionality
Users can change the password secret via helm values
Users need to know that, depending on the solution, they may need to manually change the credentials in the app. 
- fixes #

[bitnami/common] feat: :sparkles: Add honorProvidedValues in common.secrets.manage

---

bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.yaml
bitnami/seaweedfs/README.md
bitnami/seaweedfs/templates/volume/statefulset.yaml
bitnami/seaweedfs/values.yaml

This PR adds support for configuring the max. number of volume for each disk mounted on SeaweedFS Volume server.
Number of volumes can be properly customized, see:
- https://github.com/seaweedfs/seaweedfs/wiki/FAQ#how-many-volumes-do-i-need
None
None
N/A

[bitnami/seaweedfs] Support configuring max number of volumes per disk

---

bitnami/cilium/CHANGELOG.md
bitnami/cilium/Chart.yaml
bitnami/cilium/templates/hubble-relay/configmap.yaml

This change allows the usage of a different cluster-name for hubble-relay configmap. Also set  `tls-hubble-client-cert-file` `tls-hubble-client-key-file` to use the client certificate.
* Allows setting cluster-name to a value different from 'default'.
* Use the expected certificates
N/A
- Related #30264
Upstream logic
https://github.com/cilium/cilium/blob/3a988cd59c83355891f4d61815baf260caf6bf1f/install/kubernetes/cilium/templates/hubble-relay/configmap.yaml#L36-L38
https://github.com/cilium/cilium/blob/3a988cd59c83355891f4d61815baf260caf6bf1f/install/kubernetes/cilium/templates/_extensions.tpl#L20-L38

[bitnami/cilium] Fix typos with clusterName and certificates

---

.github/workflows/cd-pipeline.yml

Revert "Bump actions/download-artifact from 3.0.2 to 4.1.8"

---

bitnami/nats/CHANGELOG.md
bitnami/nats/Chart.yaml
bitnami/nats/README.md
bitnami/nats/templates/headless-svc.yaml
bitnami/nats/values.yaml

* Add the `publishNotReadyAddresses` config to NATS Headless Service
* Default to `false` (existing behavior)
Allow operators to specify `service.headless.publishNotReadyAddresses=true` if desired.
- fixes #30392

[bitnami/nats] Expose `publishNotReadyAddresses` on headless service

---

.github/workflows/cd-pipeline.yml

This PR adds an additional job to the CD pipeline workflow.
This additional step will update the `deprecated-index` branch in preparation for the index.yaml migration to OCI https://github.com/bitnami/charts/pull/30402
**IMPORTANT NOTES:** 
- We will keep `.tgz` releases for 3 months after this change, where the legacy index using `.tgz` will be published into the 'deprecated-index' branch.  
- **After the deprecation period ends** the branch will be permanently removed and new releases of the charts will only be available through the OCI repository.

[github-actions] Add support for legacy .tgz index branch

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/templates/NOTES.txt
bitnami/keycloak/templates/metrics-service.yaml
bitnami/keycloak/templates/servicemonitor.yaml
bitnami/keycloak/values.yaml

Fixes metrics collection by:
* adding the possibility to overwrite the ```port``` for each serviceMonitor's endpoint
* adding ```scheme``` and ```tlsConfig``` support to serviceMonitor
* adding all required ports to ```keycloak-metrics``` service
As explained in #28975, a recent update changed ```/metrics``` to be exposed through the management port (9000). However, the realms' metrics (```/realms/<realm>/metrics```) are still exposed through the http (8080), or https (8443) ports.
This causes 2 issues:
* Metrics service only expose the 9000 port, and the service monitor has both ```/metrics``` and ```/realms/master/metrics``` endpoints configured in default values. The latter fails as it's not exposed on the management port, and http port isn't present in the service (nor serviceMonitor) …

[bitnami/keycloak] Fix metrics ports and servicemonitor

---

bitnami/milvus/CHANGELOG.md
bitnami/milvus/Chart.lock
bitnami/milvus/Chart.yaml
bitnami/milvus/README.md

Update kafka subchar to version 31.0.0 (appVersion 3.9.0).
Use the latest stable version of Kafka subchart.
N/A
https://downloads.apache.org/kafka/3.9.0/RELEASE_NOTES.html

[bitnami/milvus] Update kafka subchart to 31.0.0

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md

Update kafka subchar to version 31.0.0 (appVersion 3.9.0).
Use the latest stable version of Kafka subchart.
N/A
https://downloads.apache.org/kafka/3.9.0/RELEASE_NOTES.html

[bitnami/spring-cloud-dataflow] Update kafka subchart to 31.0.0

---

bitnami/schema-registry/CHANGELOG.md
bitnami/schema-registry/Chart.lock
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md

Update kafka subchar to version 31.0.0 (appVersion 3.9.0).
Use the latest stable version of Kafka subchart.
N/A
https://downloads.apache.org/kafka/3.9.0/RELEASE_NOTES.html

[bitnami/schema-registry] Update kafka subchart to 31.0.0

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/repo-server/pdb.yaml

Fix the label selector for the repo-server Deployment ("kubernetes.io/component: repo-server") used by the corresponding PDB (was: "kubernetes.io/component: repoServer").
The PDB is satisfied.
None.
- fixes #30228 
A better fix might be to put all component labels into values (or named templates) and using them where applicable.
Also, the component labels are a bit inconsistent right now: The application-set has "applicationSet", but the repo-server has "repo-server". But changing that would require a major release.

[bitnami/argo-cd] Fix repo-server PDB label selector

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/templates/_helpers.tpl

This PR adds the `honorProvidedValues` option to `common.secrets.manage`, so users can update the redis password using  the `auth.password` value.
Redis already supports updating the password (as it is set via redis.conf), so we do not need a password update job like in MariaDB, PostgreSQL or MySQL
n/a
- fixes #

[bitnami/redis] feat: :sparkles: Allow updating credentials via values.yaml

---

.github/workflows/cd-pipeline.yml
.github/workflows/index-update.yml
.github/workflows/push-tag.yml

This PR updates the current CD pipeline introducing several changes:
- `push-tag` job has been migrated into an independent workflow
- Removed slack notification
- New `index-update` workflow will pull information from the OCI registry and update the `index.yaml`.
- `push-promotion` has been moved into the new 'index-update' workflow
- `update-index` replaced with `update-deprecated-index`. Which updates the branch `deprecated-index` instead of `index`.
**IMPORTANT NOTES:** 
- We will keep `.tgz` releases for 3 months after this change, where the legacy index using `.tgz` will be published into the 'deprecated-index' branch.  
- **After the deprecation period ends** the branch will be permanently removed and new releases of the charts will only be available through the OCI repository.

[github-actions] Update index.yaml to use OCI charts references

---

.vib/airflow/goss/goss.yaml
.vib/airflow/runtime-parameters.yaml
bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml

This PR improves Goss testing for Airflow and fixes an issue on chart metadata.
Better test suite
None
None
N/A
- [] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami/readme-generator-for-helm)

[bitnami/airflow] Improve Goss tests

---

.vib/airflow/goss/goss.yaml
.vib/airflow/runtime-parameters.yaml
bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/README.md
bitnami/airflow/templates/config/configmap-pod-template.yaml
bitnami/airflow/templates/config/configmap.yaml
bitnami/airflow/values.yaml

This PR adds support for extending the default Airflow configuration. 
Currently it's possible to overwrite the whole Airflow configuration via the configuration chart parameter. However, it's not possible to extend it so only certain configuration sections are overwritten or extended.
Values must be adapted before upgrading given `configuration` now expects YAML format.
- fixes #30442
It also fixes an issue related to sync dags/plugins sidecar containers that shouldn't be included as part of the Pod Template when using the KubernetesExecutor given pods.

[bitnami/airflow] Add support for extending default configuration

---

bitnami/discourse/README.md
bitnami/keycloak/values.yaml
bitnami/postgresql-ha/README.md
bitnami/postgresql-ha/values.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/values.yaml
bitnami/sealed-secrets/values.yaml

This PR fixes a few copy-paste typos with wrong references to Airflow
Accurate docs
None
None
N/A

[bitnami/*] docs: fix copy-paste typos with wrong references to Airflow

---

bitnami/janusgraph/CHANGELOG.md
bitnami/janusgraph/Chart.yaml
bitnami/janusgraph/README.md
bitnami/janusgraph/templates/NOTES.txt
bitnami/janusgraph/values.yaml

This PR removes the subchart image from the values.yaml
The image tag will automatically use the version defined in the subchart.
None known

[bitnami/janusgraph] Remove subchart image from values.yaml

---

bitnami/clickhouse/CHANGELOG.md
bitnami/clickhouse/Chart.yaml
bitnami/clickhouse/README.md
bitnami/clickhouse/templates/NOTES.txt
bitnami/clickhouse/values.yaml

This PR removes the subchart image from the values.yaml
The image tag will automatically use the version defined in the subchart.
None known

[bitnami/clickhouse] Remove subchart image from values.yaml

---

bitnami/rabbitmq/CHANGELOG.md
bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/templates/secrets.yaml
bitnami/rabbitmq/templates/statefulset.yaml
bitnami/rabbitmq/values.yaml

This PR allows updating passwords in the RabbitMQ chart. In order to not break existing deployments, this must be set using `auth.updatePassword=true`. In future majors, once this is mature enough, we could consider enabling it by default.
It also adds a documentation section in the README.md file.
Unexpected corner cases 
- fixes #

[bitnami/rabbitmq] feat: :sparkles: Allow password updates

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_capabilities.tpl

This PR fixes the `common.capabilities.vpa.apiVersion` helper that is returning `v2` and `v2betaX` API versions based on the K8s version when it should be returning `v1` and `v1betaX` instead, see:
- https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#compatibility
- https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#notice-on-deprecation-of-v1beta2-version-0130
- https://github.com/kubernetes/autoscaler/tree/master/vertical-pod-autoscaler#notice-on-removal-of-v1beta1-version-050
VPA objects are compatible with Vertical Pod Autoscaler.
None
Reported at https://github.com/bitnami/charts/issues/30583
N/A

[bitnami/common] Fix VPA apiVersion

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml

This PR bumps `bitnami/common` patch version given it wasn't properly bumped on a previous contribution.
None
None
None
N/A

[bitnami/common]: bump patch version

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/_init_containers_sidecars.tpl
bitnami/airflow/templates/setup-db-job.yaml

This PR ensures the `extraVolumeMounts` and `extraVolumes` parameters are considered also for the setup-db k8s job and the wait-for-db init container.
Users that use a external database with TLS encryption enabled setting a custom SQL connection string via the `externalDatabase.sqlConnection` parameters might need to use `extraVolumeMounts` and `extraVolumes` parameters to mount the TLS client certs. If that't the case, it's needed to mount them on setup-db k8s job and the wait-for-db init container too.
None
None
N/A

[bitnami/airflow] bugfix: extra volume/mounts should apply to setup-db job and wait-for-db init-container

---

bitnami/influxdb/CHANGELOG.md
bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/configmap-backup.yaml

gsutil depends on python 3.11 which is not availlable on newer gcloud sdk images. Also, google now recommends using gcloud storage (which does support newer python versions).
This change updates the gcloud upload script for the influxdb backup so that it replaces the deprecated gsutil with the corresponding gcloud storage invocation.
On the current bitnami/google-cloud-sdk image (used by the influxdb backup to upload the backup to google), gsutil fails as it requires python 3.11 to be present on the image, which was replaced by 3.12 on the release 489r1. Using `gcloud storage` instead of `gsutil` the invocation works with the python version supported by gcloud.
gcloud storage rsync was added on gcloud 437 (current release is 502), an older version of gcloud will fail.

[bitnam/influxdb] gcloud backups, replace gsutil

---

bitnami/milvus/CHANGELOG.md
bitnami/milvus/Chart.lock
bitnami/milvus/Chart.yaml

This PR update Milvus chart deps to use latest common version. This latest version comes with fixes for the VPA api version.
VPA API version is correct.
None
- fixes #https://github.com/bitnami/charts/issues/30583
N/A

[bitnami/milvus] feat: update chart deps

---

bitnami/janusgraph/CHANGELOG.md
bitnami/janusgraph/Chart.yaml
bitnami/janusgraph/README.md
bitnami/janusgraph/values.yaml

This PR renames an auto-generated documentation section to avoid issues with the "Markdown Linter" and error "Same headings"
- fixes #

[bitnami/janusgraph] chore: :bulb: :memo: :rotating_light: Rename prometheus "@section" to avoid linter problems

---

bitnami/sealed-secrets/CHANGELOG.md
bitnami/sealed-secrets/Chart.yaml
bitnami/sealed-secrets/templates/pdb.yaml

Currently the PodDisruptionBudget in the sealed-secret chart is deployed to the release namespace. This however, is not necessarily the namespace the rest of the sealed-secrets manifests are deployed to (i.e. due to `.Values.namespaceOverride` being set).
That leads to a violated PodDisruptionBudget in the release namespace, as the pods it references are deployed to a different namespace.
This PR updates the namespace field in the PDB to have the same value as for example the deployment it references:
Setting `.Values.namespaceOverride` no longer breaks the PDB.

[bitnami/sealed-secrets] Fix namespace in PodDisruptionBudget

---

bitnami/rabbitmq-cluster-operator/CHANGELOG.md
bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/pdb.yaml

Fixes issue #30364 where PodDisruptionBudget for msg topology operator is created even though it is set to be disabled
- fixes #30364

[bitnami/rabbitmq-cluster-operator] Fix msg topology operator PodDisruptionBudget

---

bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/read/statefulset.yaml

When `auth.username` is not set and `metrics.enabled: true`, it still looks up `auth.password` for metrics user, leading to `CreateContainerConfigError` on replication mode.
As the default value of `DATA_SOURCE_USER` is `postgres`, its value must be `auth.postgresPassword` if `auth.username` is not set.
Resolve error when creating replica postgresql pod with metrics enabled.
#30680

[bitnami/postgresql] use adminPassword for metrics user when custom user is not set

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/triggerer/hpa.yaml
bitnami/airflow/templates/worker/hpa.yaml
bitnami/airflow/templates/worker/vpa.yaml

https://github.com/bitnami/charts/issues/30834
Fixes the typo preventing HPA to function for Airflow Worker and Triggerer.
HPA can find the target `StatefulSet` and manage scaling.
- Fixes https://github.com/bitnami/charts/issues/30834

[bitnami/airflow] bugfix: Fix Airflow HPA, VPA for Worker and Triggerer typo (#30834)

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/tracking/deployment.yaml

Currently when you set useCredentialsInSecret it will require all secrets to be set, but this doesn't make sense since you only want 1 out of the 3 (connection_String, access_key or client_secret) to be set. This PR adds a conditional check if they key is provided in the values.yaml otherwise the env secret is not defined.

fix: azure secrets

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_errors.tpl

This PR adds verification to detect non-standard images in Bitnami Helm charts.

[bitnami/common] New helper to detect non-standard images

---

bitnami/external-dns/CHANGELOG.md
bitnami/external-dns/Chart.lock
bitnami/external-dns/Chart.yaml
bitnami/external-dns/README.md
bitnami/external-dns/templates/NOTES.txt
bitnami/external-dns/values.yaml

Implemented thanks to [those changes](https://github.com/bitnami/charts/pull/30851) in btinami/common.

[bitnami/external-dns] Detect non-standard images

---

bitnami/jaeger/CHANGELOG.md
bitnami/jaeger/Chart.lock
bitnami/jaeger/Chart.yaml
bitnami/jaeger/README.md
bitnami/jaeger/templates/NOTES.txt
bitnami/jaeger/values.yaml

Implemented thanks to [those changes](https://github.com/bitnami/charts/pull/30851) in btinami/common.

[bitnami/jaeger] Detect non-standard images

---

bitnami/metallb/CHANGELOG.md
bitnami/metallb/Chart.lock
bitnami/metallb/Chart.yaml
bitnami/metallb/README.md
bitnami/metallb/templates/NOTES.txt

Implemented thanks to [those changes](https://github.com/bitnami/charts/pull/30851) in btinami/common.

[bitnami/metallb] Detect non-standard images

---

bitnami/kube-state-metrics/CHANGELOG.md
bitnami/kube-state-metrics/Chart.yaml
bitnami/kube-state-metrics/templates/NOTES.txt

Fix typo introduced at https://github.com/bitnami/charts/pull/30913

[bitnami/kube-state-metrics] Fix typo in NOTES.txt

---

bitnami/redis/README.md

The proper value key is 'usePasswordFiles', with a final `s`

Redis Readme: fix typo in value key name

---

template/CHART_NAME/templates/hpa.yaml

This fixes the context passed to `common.capabilities.hpa.apiVersion` in hpa.yaml, and replace `.Values.worker.autoscaling.hpa.targetMemory` by `.Values.%%MAIN_OBJECT_BLOCK%%.autoscaling.hpa.targetMemory` in the same file.
- fixes #30713

[bitnami/template] fix(template): hpa context and path to hpa settings

---

bitnami/scylladb/CHANGELOG.md
bitnami/scylladb/Chart.yaml
bitnami/scylladb/README.md
bitnami/scylladb/templates/statefulset.yaml
bitnami/scylladb/values.yaml

Fix existingConfiguration parameter for scylladb
Allow setting a custom configuration file
N/A
- fixes #30803

[bitnami/scylladb] Fix existingConfiguration parameter for scylladb

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/metrics/networkpolicy.yaml

The pull request (#30459) that added StatsD for metrics specifies the wrong protocol. Interaction occurs over UDP, but TCP is being set (as the protocol is not explicitly defined). As a result, only StatsD's internal metrics are being collected, while Airflow metrics are absent. A workaround until this fix is to disable the Network Policy for metrics.
The collection of Airflow metrics is working again.
I didn’t find any issues, but I encountered this problem myself and also found [this comment](https://github.com/bitnami/charts/pull/30459#issuecomment-2536322196).

[bitnami/airflow] Fix wrong protocol for metrics network policy

---

.vib/zookeeper/runtime-parameters.yaml
bitnami/zookeeper/CHANGELOG.md
bitnami/zookeeper/Chart.yaml

Fix tests to release our charts.

[bitnami/zookeeper] Increase resources to avoid OOMKilled reason executing tests

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/templates/master/application.yaml
bitnami/redis/templates/replicas/application.yaml
bitnami/redis/values.yaml

Enables annotation to just resources (StatefulSet) that creates master and replicas
`.commonAnnotations` do annotate all the resources which is not always optimal. Some examples is when you plan to use applicaztions like [skupper](https://skupper.io/index.html) when annotate Services may cause many issues.
None

[bitname/redis] Add support for master and replicas resources to be annotated

---

bitnami/dremio/CHANGELOG.md
bitnami/dremio/Chart.yaml
bitnami/dremio/templates/coordinator/statefulset.yaml
bitnami/dremio/templates/executor/statefulset.yaml
bitnami/dremio/templates/master-coordinator/statefulset.yaml
bitnami/dremio/values.yaml

Upgrade jmx-exporter image
Keep chart updated.
None
File name for the java application was changed: https://github.com/prometheus/jmx_exporter/releases/tag/1.1.0

[birtnami/dremio] chore(jmx-exporter): Upgrade image and change args

---

bitnami/tomcat/CHANGELOG.md
bitnami/tomcat/Chart.yaml
bitnami/tomcat/templates/_pod.tpl
bitnami/tomcat/values.yaml

Upgrade jmx-exporter image
Keep chart updated.
None
File name for the java application was changed: https://github.com/prometheus/jmx_exporter/releases/tag/1.1.0

[bitnami/tomcat] chore(jmx-exporter): Upgrade image and change args

---

.vib/nessie/runtime-parameters.yaml
bitnami/nessie/CHANGELOG.md
bitnami/nessie/Chart.yaml

Set explicitly a long postgresql password in `runtime-parameters.yaml` file.
Default postgresql password has 10 characters (80 bits). This length is not enough for some test scenarios. 
None

[bitnami/nessie]fix(runtime-parameters.yaml): Set long postgresql password

---

bitnami/jenkins/CHANGELOG.md
bitnami/jenkins/Chart.yaml
bitnami/jenkins/templates/deployment.yaml

Use `name` instead of `secretName` for projected volume when using `initHookScriptsSecret`.
Allos using `initHookScriptsSecret`
N/A
- fixes #31167
```
Each projected volume source is listed in the spec under sources. The parameters are nearly the same with two exceptions:
For secrets, the secretName field has been changed to name to be consistent with ConfigMap naming.
The defaultMode can only be specified at the projected level and not for each volume source. However, as illustrated above, you can explicitly set the mode for each individual projection.
```
https://kubernetes.io/docs/concepts/storage/projected-volumes/#example-configuration-secrets-nondefault-permission-mode

[bitnami/jenkins] Fix initHookScriptsSecret

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.yaml
bitnami/mastodon/templates/web/deployment.yaml

Avoid `mkdir` error when restarting if the directory already exists.
Allow restarting web deployment correctly.
N/A
- fixes #31025

[bitnami/mastodon] Avoid mkdir issue when restarting

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_capabilities.tpl

- Add "common.capabilities.job.apiVersion" template
- Encapsulate job API version string logic
It's related to https://github.com/bitnami/charts/pull/31161 and https://github.com/bitnami/containers/pull/75906

[bitnami/common] Add "common.capabilities.job.apiVersion" template

---

bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/primary/statefulset.yaml
bitnami/postgresql/templates/read/statefulset.yaml

This PR reverts the changes introduced at https://github.com/juan131/charts/commit/b0d2c2e53c9033d3827597c561931fbb331eb99b given they add a conflict with storage class name.
None
- fixes https://github.com/bitnami/charts/issues/31140
N/A

Revert "[bitnami/postgresql] Add Storage Class Configuration to Templates (#30858)"

---

bitnami/rabbitmq/CHANGELOG.md
bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/networkpolicy.yaml

Removes a undefined `rts` key from `networkpolicy.yaml`
Currently, modifying the `.Values.extraEgress` fails chart rendering as the template is looking for an `rts` key, which is neither specified in the documentation of the `.Values` nor present _anywhere_ else in the chart for reference points as to how to use it.
The error produced when `.Values.extraEgress` is defined:
```
Helm upgrade failed: template: rabbitmq/templates/networkpolicy.yaml:47:64: executing "rabbitmq/templates/networkpolicy.yaml" at <.Values.rts.networkPolicy.extraEgress>: nil pointer evaluating interface {}.networkPolicy
```
The work around is to define both `.Values.extraEgress`  and `.Values.rts.extraEgress` to pass the initial feature flag and enable the block render
By removing the undefined `rts` key, the …

[bitnami/rabbitmq] remove undefined rts key from network policy template

---

bitnami/moodle/CHANGELOG.md
bitnami/moodle/Chart.yaml
bitnami/moodle/README.md
bitnami/moodle/templates/_helpers.tpl
bitnami/moodle/templates/deployment.yaml
bitnami/moodle/values.yaml

Defining imagePullSecrets on container level is against spec (https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#containers). They have to be defined on pod level, which is already covered.
Being able to deploy without error with `certificates.customCAs` defined.
None as `imagePullSecrets` on pod level are already covered.
- fixes #31199

[bitnami/moodle] #31199 Fix invalid imagePullSecrets on container level

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/templates/configmap-env-vars.yaml
bitnami/keycloak/templates/headless-service-ispn.yaml
bitnami/keycloak/templates/statefulset.yaml
bitnami/keycloak/values.yaml

Add possibility to version bind the ispn discovery. The new config property is `.cache.useHeadlessServiceWithAppVersion`. This solution is inspired by: https://github.com/keycloak/keycloak/discussions/21067#discussioncomment-8855429 
Added a config property `.cache.useHeadlessServiceWithAppVersion`. When this is set to `false` (default) the behavior stays the same as before and the Keycloak ISPN Cache will continue to use the default headless service for discovery. 
If the value is set to true:
- New headless service "`(include "common.names.fullname" .)-headless-ispn-(replace "." "-" .Chart.AppVersion)`"  is created that contains an additional selector for `app.kubernetes.io/app-version: {{ .Chart.AppVersion }}`. This headless service will only discover for keycloak pods that are running …

[bitnami/keycloak] add option to use dedicated version bound headless service for jgroups discovery

---

bitnami/postgresql-ha/CHANGELOG.md
bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/templates/pgpool/deployment.yaml
bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
bitnami/postgresql-ha/templates/postgresql/witness-statefulset.yaml

setting ServiceAccount also when is not created by the bitnami chart
service account can be create externally (like every other services like [redis](https://github.com/bitnami/charts/blob/main/bitnami/redis/templates/sentinel/statefulset.yaml#L71) or [mongo](https://github.com/bitnami/charts/blob/main/bitnami/mongodb/templates/replicaset/statefulset.yaml#L55))
- fixes #

[bitnami/postgresql-ha] setting ServiceAccount also when is not created by the bitnami chart

---

.vib/pinniped/runtime-parameters.yaml
bitnami/pinniped/CHANGELOG.md
bitnami/pinniped/Chart.yaml

We use the Bitnami OpenLDAP container for our integration test suite. This PR removes some env. vars that we're setting and were deprecated.
The setup is aligned with latest changes in OpenLDAP container.
None
None
N/A

[bitnami/pinniped] bugfix: remove deprecated vars to configure OpenLDAP on VIB

---

bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/update-password/job.yaml

Fix missing dot in include statement for passwordUpdate job template
```
Error: template: idp/charts/keycloak/charts/postgresql/templates/update-password/job.yaml:60:37: 
executing "idp/charts/keycloak/charts/postgresql/templates/update-password/job.yaml" 
at <include>: wrong number of args for include: want 2 got 1
```
- fixes # Bug of rendering of paswordUpdate job
Chart has been rendered locally (as a subchart of keycloak) and the issue appears fixed
```yaml
apiVersion: batch/v1
kind: Job
metadata:
name: idp-postgresql-password-update
namespace: "idp"
labels:
app.kubernetes.io/instance: idp
app.kubernetes.io/name: postgresql
app.kubernetes.io/version: 17.2.0
helm.sh/chart: postgresql-16.4.2
app.kubernetes.io/part-of: postgresql …
```

bitnami/postgresql Fix missing dot in include statement for passwordUpdate job template

---

.github/workflows/gchat-notification.yml

Add flags `--fail`, `-s` and `-o` to the notifications workflow.

[actions] Skip output in Gchat notification

---

bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.yaml
bitnami/apisix/templates/_helpers.tpl
bitnami/apisix/templates/control-plane/dep-ds.yaml
bitnami/apisix/templates/data-plane/dep-ds.yaml

This PR changes the APISIX init containers so os-shell is used instead of apisix. This helps to remove useless go-tools in the bitnami/apisix image.
Reduce bitnami/apisix image size
n/a
- fixes #

[bitnami/apisix] feat: :recycle: Use os-shell for config generation

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/configmap-env-vars.yaml

Dear Bitnami Team, 
with this PR I want to address an issue, where in the values.yml file the option proxy is set to "passthrough".
Our ArgoCD is not very happy with the ConfigMap. See:
As you can see, the value is just empty. I assume it should be "". So I made a little tiny change.
With my change:
Now it's valid yaml. 
I did not add any documentation, as it is not changing the expected behavior.
Added quotes for ConfigMap, that contains "KEYCLOAK_PROXY_HEADERS"
For us ArgoCD wasn't happy with the following data(helm template)
`KEYCLOAK_PROXY_HEADERS:`
It will now be:
`KEYCLOAK_PROXY_HEADERS: ""`
There should not be a drawback. It just fixes a problem that is present since at least 22.2.6
None
none

[bitnami/keycloak] Fix quotes for handling KC_PROXY_HEADER when options is set to passthrough

---

bitnami/clickhouse/CHANGELOG.md
bitnami/clickhouse/Chart.yaml
bitnami/clickhouse/templates/scripts-configmap.yaml
bitnami/clickhouse/values.yaml

This PR is re-open of #31168 (see https://github.com/bitnami/charts/pull/31168#issuecomment-2567439700)
The current clickhouse helm chart don't support ipv6 only cluster.
By default clickhouse bind localhost on ipv4 and ipv6 (see https://github.com/ClickHouse/ClickHouse/blob/master/programs/server/config.xml#L253).
The bitnami container override this behaviors and bind to any ipv4 by passing `-- --listen_host=0.0.0.0` to `clickhouse-server` via the `CMD` (see https://github.com/bitnami/containers/blob/main/bitnami/clickhouse/24/debian-12/Dockerfile#L60).
this is easily override to listen on ivp6 by changing the container command to `/opt/bitnami/scripts/clickhouse/run.sh -- --listen_host="::"`.
The helm chart use an hard coded script as it's entry with no possibility to pass/override …

 [bitnami/clickhouse] Fix: bind ipv6 and ipv4 by default 

---

bitnami/minio/CHANGELOG.md
bitnami/minio/Chart.yaml
bitnami/minio/templates/provisioning-job.yaml

This PR changes the Minio provisioning job so we can remove `wait-for-port` in the bitnami/minio image.
Smaller bitnami/minio image
n/a
- fixes #

[bitnami/minio] chore: :recycle: Do not use wait-for-port in minio image

---

bitnami/thanos/CHANGELOG.md
bitnami/thanos/Chart.yaml
bitnami/thanos/templates/storegateway/hpa-sharded.yaml

Fixes bug in helm chart template. When using Thanos Storegateway and HPA, an error appears due. This PR corrects the template.
Error message
`Error: template: thanos/templates/storegateway/hpa-sharded.yaml:19:30: executing "thanos/templates/storegateway/hpa-sharded.yaml" at <$shards>: wrong type for value; expected int; got int64`
Use --debug flag to render out invalid YAML`
No more template errors :) 
None
- fixes https://github.com/bitnami/charts/issues/31059

[bitnami/thanos] Fix Helm Template Error For Storegateway and HPA

---

bitnami/jaeger/CHANGELOG.md
bitnami/jaeger/Chart.yaml
bitnami/jaeger/templates/migrate-job.yaml

Date: Sa Jan 4 20:42 2028 +01:00
- Fixes https://github.com/bitnami/charts/issues/31207
Signed-off-by: Marco Fuykschot <marcof@titaniumit.nl>
namespace of the migration-job is now using the include common.names.namespace
**Benefits**
namespaceOverride is consistent again
**Checklist**
(https://github.com/bitnami/readme-generator-for-helm)
See other pr (rename of branch only)

 [bitnami/jaeger] Migration job not using namespace overwrite 31207

---

bitnami/zipkin/CHANGELOG.md
bitnami/zipkin/Chart.yaml
bitnami/zipkin/templates/_helpers.tpl
bitnami/zipkin/templates/configmap.yaml

This is needed because it will later be combined with the port in the configmap.
Removed the quote from the host value so it can be combined in configmap with the port.
Now it is possible to use external database.
None
None
Nothing.

bitnami/zipkin Remove quote for the host

---

.github/workflows/sync-chart-cloudflare-index.yml

Fixes an issue with the '.github/workflows/sync-chart-cloudflare-index.yml' when called from the 'main' branch, by specifying the checkout branch 'index' (by default, it uses the current branch).
This allows the workflow to be called from other branches, not only 'index' branch.
None known.
- fixes issues with monitor workflow: https://github.com/bitnami/charts/actions/runs/12902662888

[Index] Add 'ref: index' to index upload workflow checkout

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/_init_containers_sidecars.tpl

When using configmap-based DAGs, the directory being copied to `/dags/external` fails to correctly copy the dags from the configmap folder if the directory does not exist. This creates the directory first.
- fixes #31224

[bitnami/airflow] Fix missing directory in Airflow configmap-based dag

---

bitnami/cilium/CHANGELOG.md
bitnami/cilium/Chart.lock
bitnami/cilium/Chart.yaml
bitnami/cilium/README.md

Update ETCD to major 11
Use the latest version of ETCD subchart
Regarding ETCD, upgrading of any kind including increasing replica count must be done with helm upgrade exclusively.
https://github.com/bitnami/charts/tree/main/bitnami/etcd#to-1100

[bitnami/cilium] Update ETCD to major 11

---

.vib/apisix/goss/goss.yaml
bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.lock
bitnami/apisix/Chart.yaml
bitnami/apisix/README.md

Update ETCD to major 11
Use the latest version of ETCD subchart
Regarding ETCD, upgrading of any kind including increasing replica count must be done with helm upgrade exclusively.
https://github.com/bitnami/charts/tree/main/bitnami/etcd#to-1100

[bitnami/apisix] Update ETCD to major 11

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.yaml
bitnami/etcd/templates/preupgrade-hook-job.yaml

It will help fix the issue reported on below issue.
https://github.com/bitnami/charts/issues/31517
1. 1st change is related to addition of securityContext for fsgroup so that there wont be any permission denied error for reading tls certificates
2. Change for ETCD Endpoint to user ClientPort(2379) instead of PeerPort(2380) as peer port is only meant for members. This will fix error "EOF" while running endpoint list.
PreUpgrade Job will succeed without any issues.
No drawbacks.
- fixes https://github.com/bitnami/charts/issues/31517

[bitnami/etcd] fix for PreUpgrade Job Issue

---

bitnami/nats/CHANGELOG.md
bitnami/nats/Chart.yaml
bitnami/nats/values.yaml

This improves the generated nats-server.conf file, to include all the routes to each pod, rather than the current single route that points to the general service.
This will prevent improper routing of messages in a cluster.
n/a
- fixes #30124
n/a

[bitnami/nats] Improve NATS routes configuration

---

.github/workflows/ci-pipeline.yml

This PR adapts the "Look for hardcoded images" job on "CI Pipeline" workflow so we skip looking for hardcoded images on 
NOTES.txt files.
We usually include instructions to create "client pods" on the notes and, when using images for the clients not included in the chart (e.g. using a `bitnami/golang:latest` to compile some Go example app and use it as a client) it's useful to use hardcoded images with rolling tags.

ci: Skip hardcoded images check on NOTES.txt files

---

bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.yaml
bitnami/harbor/values.yaml

If you use an existingEnvVarsSecret, the documentation implies that everything will work as long as you change postgres-password and HARBOR_DATABASE_PASSWORD. However, you must also change the postgresql.auth.existingSecret to point at the same secret because the postgresql chart doesn't automatically inherit the secrets/variables.
Documentation only.  Added clarity to an issue that had me confused as to why things weren't working as documented until I dug into it deeper.
Should prevent confusion in the future and save people some time.
None
N/A
N/A

[bitnami/harbor] Clarify usage of custom POSTGRESQL_PASSWORD

---

bitnami/redis-cluster/CHANGELOG.md
bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/svc-cluster-external-access.yaml

Addresses redis-cluster chart not working with external access enabled.
This is a simple one-line change where the wrong scope was being passed to "common.names.namespace" from svc-cluster-external-access.yaml but was only impacted when external access was enabled. With this change I was able to install using the chart as expected.
Allows the chart to be used to install redis-cluster with external access
None I can see or think off
N/A

[bitnami/redis-cluster] Address chart not working with external access enabled

---

bitnami/keydb/CHANGELOG.md
bitnami/keydb/Chart.yaml
bitnami/keydb/templates/master/statefulset.yaml
bitnami/keydb/templates/replica/statefulset.yaml

This change fixes the commands of `volume-permissions` initContainers.
There are no default values set for `.Values.master.persistence.path`, `.Values.replica.persistence.path` in `values.yaml`, so the command have been updated to use `*.mountPath`.
Also, the `-r` argument for `xargs` added.
Init container starts to work when `.Values.volumePermissions.enabled: true`
Maybe it is worth to consider the further parameterization of initContainer `command` in helm values.
N/A

[bitnami/keydb] fix: Update "volume-permissions" initContainers command

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_compatibility.tpl

There are some cases where we want to include `seLinuxOptions` with `privileged` containers.
Being able to use `seLinuxOptions` with `privileged`.
We use the `spc_t` on our minio deployment since it contains billions of small files. Without this, Openshift is unable to start the pods in a timely manner.
Adding the `spc_t` is a [Redhat recommendation](https://access.redhat.com/solutions/6221251) and it needs to be there even if the pods are privileged.
None
- fixes #31278 
Partial-Revert of 5f0bdde77cf05afa20cb4a800090748a8d102d02

[bitnami/common] Removing seLinuxOptions from omission

---

TESTING.md

This pull request fixes a minor typo in the `TESTING.md` file:  
- Corrected "accross" to "across" to improve clarity and accuracy.

Fix typo TESTING.md

---

bitnami/nginx-ingress-controller/CHANGELOG.md
bitnami/nginx-ingress-controller/Chart.yaml
bitnami/nginx-ingress-controller/templates/controller-daemonset.yaml
bitnami/nginx-ingress-controller/templates/controller-deployment.yaml

This PR adds the `--enable-metrics` command line argument when `metrics.enabled` is set to true in the chart
This will add many basic metric outputs to the prometheus exporter
None that I can think of
- fixes #31603

[bitnami/nginx-ingress-controller] Add --enable-metrics command line argument

---

bitnami/superset/CHANGELOG.md
bitnami/superset/Chart.yaml
bitnami/superset/README.md

Fixes typo in Apache superset README.md and Chart.yaml

[bitnami/superset] Fix README.md app-name typo

---

.vib/airflow/runtime-parameters.yaml

This PR improves the runtime parameters for Airflow by ensuring we test a different UID/GID for Airflow components.
Other Airflow components are tested for flexibility on switching the UID/GID.
None
None
N/A

[bitnami/airflow] ci: improve runtime parameters

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml

Bump MinIO subchart.
Keep our charts up to date.
None

[bitnami/mastodon] feature(minio): Bump MinIO subchart

---

bitnami/superset/CHANGELOG.md
bitnami/superset/Chart.lock
bitnami/superset/Chart.yaml

[bitnami/superset] Update subcharts

---

bitnami/clickhouse/README.md
bitnami/moodle/README.md

kube-lego is deprecated, see https://github.com/jetstack/kube-lego

[bitnami/clickhouse][bitnami/moodle] Remove references to deprecated kube-lego

---

bitnami/kube-prometheus/CHANGELOG.md
bitnami/kube-prometheus/Chart.lock
bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/README.md

Update kube-state-metric subchart to 5.0.0
Use the latest version of the subchart
- fixes #

[kube-prometheus] Update kube-state-metric subchart to 5.0.0

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/templates/configmap.yaml
bitnami/redis/templates/scripts-configmap.yaml
bitnami/redis/values.schema.json
bitnami/redis/values.yaml

This PR introduces support for Redis ACL (`aclfile`) in the Redis Helm chart. It includes the following enhancements:
- An option to enable/disable ACL support (`auth.acl.enabled`, default: `false`).
- Configuration for ACL users (`auth.acl.users`), including username, password, and permissions for commands, keys, and Pub/Sub channels.
- Adds support for Redis ACL system, enabling fine-grained access control for commands, keys, and channels.
- Enhances security by restricting connections based on user-defined ACL rules.
- Improves flexibility with customizable user configurations and permissions.
- None identified.
When `auth.acl.enabled` is set to `true`, the `default` user will be automatically created in the aclfile with a SHA-256 hash of the password from `global.auth.password`, …

[bitnami/redis] Redis ACL support to the Bitnami Redis Helm Chart

---

bitnami/cert-manager/CHANGELOG.md
bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/templates/controller/rbac.yaml

This PR adds a missing RBAC permission for `controller-certificates` ClusterRole.
[Server-Side Apply](https://cert-manager.io/docs/devops-tips/scaling-cert-manager/#enable-server-side-apply) can be enabled.
None
- https://github.com/bitnami/charts/issues/31724
N/A

[bitnami/cert-manager] Update rules for controller-certificates ClusterRole

---

bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/primary/statefulset.yaml

This PR applies the same changes from #30720 to the primary statefulset.
Resolve error when creating primary postgresql pod with metrics enabled.
#30680

[bitnami/postgresql] use adminPassword for metrics user when custom user is not set on primary

---

.github/workflows/cd-pipeline.yml
.github/workflows/index-monitor.yml
.github/workflows/index-update.yml
.github/workflows/push-tag.yml
.github/workflows/retry-failed-releases.yml

Check repository ownership to avoid running scheduled or CD workflows in forked repositories.
Skip unnecessary executions and failures in forks.
None

chore(workflows): Avoid running scheduled workflows in forked repositories

---

bitnami/seaweedfs/README.md

Signed-off-by: Tom Crasset <25140344+tcrasset@users.noreply.github.com>

[bitnami/seaweedfs]: correct typo in README

---

.github/workflows/index-monitor.yml

Skip notifications on index-monitor workflow when running on forked repositories.
Avoid unnecessary executions and failures.
None
Follow up: #31863

[bitnami/charts] chore(workflows): Avoid running workflows in forked repositories

---

bitnami/thanos/CHANGELOG.md
bitnami/thanos/Chart.lock
bitnami/thanos/Chart.yaml
bitnami/thanos/templates/bucketweb/deployment.yaml
bitnami/thanos/templates/compactor/_pod-template.tpl
bitnami/thanos/templates/query-frontend/deployment.yaml
bitnami/thanos/templates/query/deployment.yaml
bitnami/thanos/templates/receive-distributor/deployment.yaml
bitnami/thanos/templates/receive/statefulset.yaml
bitnami/thanos/templates/ruler/statefulset.yaml
bitnami/thanos/templates/storegateway/statefulset-sharded.yaml
bitnami/thanos/templates/storegateway/statefulset.yaml

Add common annotations to pod templates
The added annotation also appears in the deployed pods
N/A
- fixes #31602

[bitnami/thanos] Add common annotations to pod templates

---

bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.yaml
bitnami/harbor/templates/_helpers.tpl

Add tpl to the externalURL to allow templating the dns hostname to your harbor deployment easily.
My team deploys harbor on a number of clusters. We inject the name of our clusters into the our applications deployed by helm using a variable ".Values.global.clusterName" (we use an argocd applicationset to do so) and wanted to use it for templating the .Values.externalURL variable without needing to fork and maintain another instance of the harbor helm. 
People who might not want the externalURL value to be templated will need to maneuver this change in order to leave {{ }} inside the externalURL value
No applicable issues
- fixes #

[bitnami/harbor] Added tpl to externalURL

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_capabilities.tpl

This PR adds a helper to check if a specific API version is supported. The helper allows running this check without relying on the `.Capabilities.APIVersions` built-in object but chart values instead (if defined).
Users can define the Kubernetes API versions using a parameter such as the one below:
```yaml
##
apiVersions: []
```
Use conditional like the one below in their templates:
```yaml
{{- if include "common.capabilities.apiVersions.has" ( dict "version" "batch/v1" "context" . ) }}
foo: bar
{{- end }}
```
Then, render templates (`helm template [NAME] [CHART]`) and obtain sth like this:
```yaml
$ helm template [NAME] [CHART] -s templates/xxx.yaml
Error: could not find template templates/xxx.yaml in chart
$ helm template [NAME] [CHART] --set apiVersions[0]="batch/v1" -s …
```

[bitnami/common] Add helper to check API versions

---

.github/workflows/ci-pipeline.yml

We need to escape curly braces (`{{` and `}}`) used on Prometheus rules' descriptions. Follows up https://github.com/bitnami/charts/pull/31991
Avoid parsing errors on Prometheus rules manifests.
N/A
None
N/A

ci: escape curly braces on kube-prometheus rules automated generation

---

bitnami/fluent-bit/CHANGELOG.md
bitnami/fluent-bit/Chart.lock
bitnami/fluent-bit/Chart.yaml
bitnami/fluent-bit/README.md
bitnami/fluent-bit/templates/vpa.yaml
bitnami/fluent-bit/values.yaml

[bitnami/fluent-bit] feat: use new helper for checking API versions

---

bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.lock
bitnami/apisix/Chart.yaml
bitnami/apisix/README.md
bitnami/apisix/templates/control-plane/vpa.yaml
bitnami/apisix/templates/dashboard/vpa.yaml
bitnami/apisix/templates/data-plane/vpa.yaml
bitnami/apisix/templates/ingress-controller/vpa.yaml
bitnami/apisix/values.yaml

[bitnami/apisix] feat: use new helper for checking API versions

---

bitnami/scylladb/CHANGELOG.md
bitnami/scylladb/Chart.yaml
bitnami/scylladb/README.md
bitnami/scylladb/templates/vpa.yaml
bitnami/scylladb/values.yaml

[bitnami/scylladb] feat: use new helper for checking API versions

---

template/CHART_NAME/templates/vpa.yaml
template/CHART_NAME/values.yaml

Update template replacing references to ".Capabilities.APIVersions.Has" with the new common helper added at #31969
None
None
N/A

feat: update chart template to use new helper for checking API versions

---

bitnami/keydb/CHANGELOG.md
bitnami/keydb/Chart.yaml
bitnami/keydb/README.md
bitnami/keydb/templates/master/vpa.yaml
bitnami/keydb/templates/replica/vpa.yaml
bitnami/keydb/values.yaml

[bitnami/keydb] feat: use new helper for checking API versions

---

bitnami/kong/CHANGELOG.md
bitnami/kong/Chart.yaml
bitnami/kong/README.md
bitnami/kong/templates/ingress-controller-rbac.yaml
bitnami/kong/values.yaml

[bitnami/kong] feat: use new helper for checking API versions

---

bitnami/kafka/CHANGELOG.md
bitnami/kafka/Chart.yaml
bitnami/kafka/README.md
bitnami/kafka/templates/broker/vpa.yaml
bitnami/kafka/templates/controller-eligible/vpa.yaml
bitnami/kafka/values.yaml

[bitnami/kafka] feat: use new helper for checking API versions

---

bitnami/kuberay/CHANGELOG.md
bitnami/kuberay/Chart.yaml
bitnami/kuberay/README.md
bitnami/kuberay/templates/apiserver/vpa.yaml
bitnami/kuberay/templates/operator/vpa.yaml
bitnami/kuberay/values.yaml

[bitnami/kuberay] feat: use new helper for checking API versions

---

bitnami/metrics-server/CHANGELOG.md
bitnami/metrics-server/Chart.yaml
bitnami/metrics-server/README.md
bitnami/metrics-server/templates/NOTES.txt
bitnami/metrics-server/values.yaml

[bitnami/metrics-server] feat: use new helper for checking API versions

---

bitnami/milvus/CHANGELOG.md
bitnami/milvus/Chart.yaml
bitnami/milvus/README.md
bitnami/milvus/templates/attu/vpa.yaml
bitnami/milvus/templates/data-coordinator/vpa.yaml
bitnami/milvus/templates/data-node/vpa.yaml
bitnami/milvus/templates/index-coordinator/vpa.yaml
bitnami/milvus/templates/index-node/vpa.yaml
bitnami/milvus/templates/proxy/vpa.yaml
bitnami/milvus/templates/query-coordinator/vpa.yaml
bitnami/milvus/templates/query-node/vpa.yaml
bitnami/milvus/templates/root-coordinator/vpa.yaml
bitnami/milvus/values.yaml

[bitnami/milvus] feat: use new helper for checking API versions

---

bitnami/neo4j/CHANGELOG.md
bitnami/neo4j/Chart.yaml
bitnami/neo4j/README.md
bitnami/neo4j/templates/vpa.yaml
bitnami/neo4j/values.yaml

[bitnami/neo4j] feat: use new helper for checking API versions

---

bitnami/opensearch/CHANGELOG.md
bitnami/opensearch/Chart.lock
bitnami/opensearch/Chart.yaml
bitnami/opensearch/README.md
bitnami/opensearch/templates/coordinating/vpa.yaml
bitnami/opensearch/templates/dashboards/vpa.yaml
bitnami/opensearch/templates/data/vpa.yaml
bitnami/opensearch/templates/ingest/vpa.yaml
bitnami/opensearch/templates/master/vpa.yaml
bitnami/opensearch/values.yaml

[bitnami/opensearch] feat: use new helper for checking API versions

---

bitnami/dremio/CHANGELOG.md
bitnami/dremio/Chart.yaml
bitnami/dremio/README.md
bitnami/dremio/templates/coordinator/vpa.yaml
bitnami/dremio/templates/executor/vpa.yaml
bitnami/dremio/templates/master-coordinator/vpa.yaml
bitnami/dremio/values.yaml

[bitnami/dremio] feat: use new helper for checking API versions

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.lock
bitnami/airflow/Chart.yaml
bitnami/airflow/README.md
bitnami/airflow/templates/dag-processor/vpa.yaml
bitnami/airflow/templates/scheduler/vpa.yaml
bitnami/airflow/templates/triggerer/vpa.yaml
bitnami/airflow/templates/web/vpa.yaml
bitnami/airflow/templates/worker/vpa.yaml
bitnami/airflow/values.yaml

None
- fixes https://github.com/bitnami/charts/issues/31815#issuecomment-2669027842
N/A

[bitnami/airflow] feat: use new helper for checking API versions

---

bitnami/chainloop/CHANGELOG.md
bitnami/chainloop/Chart.lock
bitnami/chainloop/Chart.yaml
bitnami/chainloop/README.md
bitnami/chainloop/templates/cas/vpa.yaml
bitnami/chainloop/templates/controlplane/vpa.yaml
bitnami/chainloop/values.yaml

[bitnami/chainloop] feat: use new helper for checking API versions

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.lock
bitnami/mlflow/Chart.yaml
bitnami/mlflow/README.md
bitnami/mlflow/templates/tracking/vpa.yaml
bitnami/mlflow/values.yaml

[bitnami/mlflow] feat: use new helper for checking API versions

---

.vib/kubernetes-event-exporter/ginkgo/integration_suite_test.go
.vib/kubernetes-event-exporter/ginkgo/kubernetes_event_exporter.go
bitnami/kubernetes-event-exporter/CHANGELOG.md
bitnami/kubernetes-event-exporter/Chart.lock
bitnami/kubernetes-event-exporter/Chart.yaml
bitnami/kubernetes-event-exporter/README.md
bitnami/kubernetes-event-exporter/templates/vpa.yaml
bitnami/kubernetes-event-exporter/values.yaml

[bitnami/kubernetes-event-exporter] feat: use new helper for checking API versions

---

bitnami/superset/CHANGELOG.md
bitnami/superset/Chart.lock
bitnami/superset/Chart.yaml
bitnami/superset/README.md
bitnami/superset/templates/flower/vpa.yaml
bitnami/superset/templates/web/vpa.yaml
bitnami/superset/templates/worker/vpa.yaml
bitnami/superset/values.yaml

[bitnami/superset] feat: use new helper for checking API versions

---

bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.yaml
bitnami/apisix/README.md
bitnami/apisix/templates/_helpers.tpl
bitnami/apisix/templates/control-plane/dep-ds.yaml
bitnami/apisix/templates/dashboard/deployment.yaml
bitnami/apisix/templates/data-plane/dep-ds.yaml
bitnami/apisix/templates/ingress-controller/deployment.yaml
bitnami/apisix/values.yaml

Adds support for `usePasswordFiles` and enables it by default.
Variables are renamed with the `_FILE` suffix and point to the mounted secret file.
None
None
N/A

[bitnami/apisix] Add support for `usePasswordFiles`

---

.vib/argo-cd/cypress/cypress/e2e/argo_cd.cy.js
bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/README.md
bitnami/argo-cd/templates/application-controller/_pod.tpl
bitnami/argo-cd/templates/repo-server/deployment.yaml
bitnami/argo-cd/templates/server/deployment.yaml
bitnami/argo-cd/values.yaml

Adds support for `usePasswordFiles` and enables it by default.
Variables are renamed with the `_FILE` suffix and point to the mounted secret file.
None
None
N/A

[bitnami/argo-cd] Add support for `usePasswordFiles`

---

bitnami/valkey/CHANGELOG.md
bitnami/valkey/Chart.yaml
bitnami/valkey/README.md
bitnami/valkey/templates/primary/application.yaml
bitnami/valkey/templates/replicas/application.yaml
bitnami/valkey/templates/sentinel/statefulset.yaml
bitnami/valkey/values.yaml

[bitnami/valkey] Set `usePasswordFiles=true` by default

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/templates/configmap.yaml
bitnami/redis/values.yaml

As described in #31952 , the redis helm chart does not support acl-based authentication for Sentinel Mode. This PR uses the configured users to enable this; clients can then authenticate both to redis and to sentinel with the same user credentials.
Introduces changes to the configmap containing the `sentinel.conf`, in order to enable ACL authentication to the sentinel nodes.
Make it easier for clients to authenticate and connect both to redis and sentinel. Previously, clients needed to provide credentials for redis (6379) as well as for sentinel (26379) separately (either the default user´s password, or turning off the authentication on sentinel).
With the change, clients can now use the same credentials to authenticate both to redis and sentinel, taken from the configured users in the …

[bitnami/redis] Add ACL Authentication for Sentinel Nodes

---

bitnami/valkey/CHANGELOG.md
bitnami/valkey/Chart.yaml
bitnami/valkey/templates/primary/application.yaml
bitnami/valkey/templates/replicas/application.yaml
bitnami/valkey/templates/sentinel/statefulset.yaml

Add missing check of `auth.enabled` value before `auth.usePasswordFiles`
Makes chart behave as expected with disabled auth and disable mounting password secrets when they does not exists
None
- fixes #32154

[bitnami/valkey] Check is auth.enabled before auth.usePasswordFiles

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/README.md
bitnami/airflow/templates/_helpers.tpl
bitnami/airflow/templates/_init_containers_sidecars.tpl
bitnami/airflow/templates/config/configmap-pod-template.yaml
bitnami/airflow/templates/dag-processor/deployment.yaml
bitnami/airflow/templates/scheduler/deployment.yaml
bitnami/airflow/templates/setup-db-job.yaml
bitnami/airflow/templates/triggerer/statefulset.yaml
bitnami/airflow/templates/web/deployment.yaml
bitnami/airflow/templates/worker/statefulset.yaml
bitnami/airflow/values.yaml

Adds support for `usePasswordFiles` and enables it by default.
Variables are renamed with the `_FILE` suffix and point to the mounted secret file.
None
None
N/A

[bitnami/airflow] Add support for `usePasswordFiles`

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/templates/NOTES.txt
bitnami/redis/templates/master/application.yaml

These changes limit all effects of `auth.usePasswordFiles` unless `auth.enabled` is also true.
This fixes a Pod scheduling issue for users that want to install the chart with auth disabled. Even with `auth.enabled: false`, the chart rendered with a `redis-password` volume mount that referenced a `redis-password` secret which doesn't exist when auth is disabled.
Here's a rendering diff with `auth.enabled: false` after these changes:
```diff
@@ -421,8 +421,6 @@
mountPath: /opt/bitnami/scripts/start-scripts
- name: health
mountPath: /health
-            - name: redis-password
-              mountPath: /opt/bitnami/redis/secrets/
- name: redis-data
mountPath: /data
- name: config
@@ -442,13 +440,6 @@
configMap:
name: redis-health
defaultMode: 0755
-        - name: redis-password
-
- …
```

[bitnami/redis]: only use auth.usePasswordFiles if auth.enabled is set

---

.vib/airflow/goss/goss.yaml
.vib/airflow/runtime-parameters.yaml
bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/dag-processor/deployment.yaml
bitnami/airflow/templates/scheduler/deployment.yaml
bitnami/airflow/templates/triggerer/statefulset.yaml
bitnami/airflow/values.yaml

This PR introduces timeout on readiness, liveness & startup probes' commands used on Triggerer, Scheduler and Dag Processor. This helps saving memory if these commands hang.
It also removes loading examples from "runtime parameters" given it's making tests very slow due to the big amount of DAGS to process.
Avoid probes causing an increase of memory usage due to periodical and concurrent executions that hang.
None
None
N/A

[bitnami/airflow] feat: timeouts for probes

---

bitnami/keydb/CHANGELOG.md
bitnami/keydb/Chart.yaml
bitnami/keydb/templates/servicemonitor.yaml

The KeyDB service port name did not match the expected port name in the ServiceMonitor configuration.  
This mismatch prevented Prometheus from discovering and scraping KeyDB metrics.  
This change updates the service port name to ensure consistency, allowing proper metric collection.
- Enables Prometheus (Prometheus Operator) to correctly scrape KeyDB metrics.  
- Fixes the mismatch between the Service and ServiceMonitor configurations.  
- No known drawbacks.  
- Fixes
- This change does not introduce breaking changes.  
- No additional configuration is required.

fix: change svc target port in servicemonitor

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.yaml
bitnami/etcd/templates/statefulset.yaml

Liveness probes should use the health check script when TLS client-to-server authentication is enabled given we don't ship `curl` nor `wget` in the container and it's not possible to customize the K8s native "httpGet" to include certificates.
Default liveness probes don't fail when setting `auth.client.secureTransport` to `true`.
None
Reported at [#78362](https://github.com/bitnami/containers/issues/78362)
N/A

[bitnami/etcd] bugfix: probes to use healthcheck when TLS client-to-server authentication

---

bitnami/valkey/CHANGELOG.md
bitnami/valkey/Chart.yaml
bitnami/valkey/templates/primary/application.yaml
bitnami/valkey/templates/replicas/application.yaml
bitnami/valkey/templates/sentinel/statefulset.yaml

Fixes issue when `usePasswordFile=true` and metrics are enabled.

[bitnami/valkey] Fix usePasswordFile typo in metrics container

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/templates/master/application.yaml
bitnami/redis/templates/replicas/application.yaml
bitnami/redis/templates/sentinel/statefulset.yaml

This is a followup of https://github.com/bitnami/charts/pull/32208 (also reported here https://github.com/bitnami/charts/issues/32218) to disable usage of usePasswordFiles not only in master, but also replicas and sentinel
Deployments using replicas and sentinel don't crash with the error mentioned in #32218
None that I'm aware
- fixes #32218
- could be related to #32252
This is a pure copy&pase PR, I don't have the infrastructure to generate/test Helm Charts

[bitnami/redis] Disable all usages of usePasswordFiles if auth.enabled is unset

---

bitnami/mysql/CHANGELOG.md
bitnami/mysql/Chart.yaml
bitnami/mysql/templates/networkpolicy.yaml

This PR fixes an issue with the `networkpolicy.yaml` template that causes the following error to be raised when `networkPolicy.allowExternalEgress` is set to `false`:
> Error: template: mysql/templates/networkpolicy.yaml:50:64: executing "mysql/templates/networkpolicy.yaml" at <.Values.rts.networkPolicy.extraEgress>: nil pointer evaluating interface {}.networkPolicy
Setting the `networkPolicy.allowExternal` variable as `true` or `false` did not stop the error from occurring.
Chart can be deployed successfully.
None known.
N/A
Values used:
```YAML
networkPolicy:
enabled: true
allowExternal: true
allowExternalEgress: false
extraIngress:
- ports:
- port: 3306
- port: 9104
from:
- podSelector:
matchLabels:
app.kubernetes.io/name: example
- podSelector:
matchLabels:
app.kubernetes.io/part-of: …
```

[bitnami/mysql] Fix network policy extraEgress bug

---

bitnami/wordpress/CHANGELOG.md
bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/networkpolicy.yaml

This PR fixes an issue discovered while enabling metrics on WordPress. 
Metrics were no present in Prometheus, experiencing a connection refused issue.
Connection issue cause by the `networkPolicy` specification. Per default, only 'frontend' ports are enabled (8080, 8443).
However, when we activate metrics scraping with Prometheus, it also takes the 'metrics port' (default 9117) to be enabled
:+1: 'metrics port' (9117) is allowed per default when metrics are enabled.
:-1: Instead of using `extraIngress` entry in the `values.yaml` file
```yaml
[...]
networkPolicy:
extraIngress:
- ports:
- port: 9117
```
None seen
N/A

[bitnami/wordpress] fix network policy when metrics enabled

---

bitnami/valkey/CHANGELOG.md
bitnami/valkey/Chart.yaml
bitnami/valkey/templates/sentinel/statefulset.yaml

Exactly as #29678, but for Valkey
Before this change, ArgoCD kept on complaining about the application not being in sync:
This is due to the fact that the Valkey Sentinel StatefulSet is missing the `apiVersion` and `kind` on the `sentinel-data` volume specification, exactly as #29678.
No more sync issues in ArgoCD
None
N/A
N/A

[bitnami/valkey]: add apiVersion and kind to sentinel statefulset

---

bitnami/keydb/CHANGELOG.md
bitnami/keydb/Chart.yaml
bitnami/keydb/templates/master/statefulset.yaml
bitnami/keydb/templates/replica/statefulset.yaml

Do not mount secret if auth is disabled.
Regression of #32108
No need to set `auth.usePasswordFiles=false` when `auth.enabled=false`
none
- #32353

[bitnami/keydb] only use password files if auth is enabled

---

bitnami/keydb/CHANGELOG.md
bitnami/keydb/Chart.yaml
bitnami/keydb/templates/master/statefulset.yaml
bitnami/keydb/templates/replica/statefulset.yaml

Implements #32215 for the bitnami/keydb chart.

[bitnami/keydb] Fix issue when using custom password secret key

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/secret-external-db.yaml

Update namespace value in `secret-external-db.yaml` template to use the namespace value from common helper, and not use the Release namespace.
This will allow to use the value from `namespaceOverride` if needed, instead of always adding the secret in the "default" namespace. This also follows the value in rest of templates in the same chart.
N/A
N/A
N/A

[bitnami/keycloak] Update secret-external-db namespace to use common helper value

---

.vib/pytorch/goss/goss.yaml

Increase timeout in pytorch goss tests since it's taking ~15 secs in some platforms, so it's safer to give it more margin to succeed.

Increase timeout in pytorch goss tests

---

bitnami/pytorch/CHANGELOG.md
bitnami/pytorch/Chart.yaml

It's needed to bump the chart version to apply the following changes in the tests: https://github.com/bitnami/charts/pull/32398

[bitnami/pytorch] Bump version to apply test changes

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/statefulset.yaml
bitnami/mongodb/templates/hidden/statefulset.yaml
bitnami/mongodb/templates/replicaset/statefulset.yaml

Updates the `dns-check` init container conditional to not include `.Values.externalAccess.service.domain`.
The value `externalAccess.service.domain` didn't interfere in any way with the `dns-check` init container, which led us to two possible scenarios:
- When `externalAccess.service.publicNames` is set, the dns-check will ensure that indeed the pod is able to resolve the DNS.
- When `externalAccess.service.publicNames` is **NOT** set, but `externalAccess.service.domain` is, the `dns-check` will perform a check on the pod's FQDN, e.g. `mongodb-0.svc.mongodb-hl.my-ns.cluster.local`.
This second scenario doesn't really make sense, because the headless service is configured with `publishNotReadyAddresses=true`, and performing a DNS check on a headless service is unnecessary.
Simplifies the …

[bitnami/mongodb] Update dns-check init container condition

---

bitnami/valkey/CHANGELOG.md
bitnami/valkey/Chart.yaml
bitnami/valkey/templates/primary/application.yaml
bitnami/valkey/templates/replicas/application.yaml
bitnami/valkey/templates/sentinel/statefulset.yaml

Implements #32215 for the bitnami/valkey chart.

[bitnami/valkey] Fix issue when using custom password secret key

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.yaml
bitnami/etcd/templates/NOTES.txt
bitnami/etcd/templates/_helpers.tpl
bitnami/etcd/templates/cronjob-snapshotter.yaml
bitnami/etcd/templates/preupgrade-hook-job.yaml

This PR ensures we add the `--insecure-skip-tls-verify` flag to etcdctl command when self-signed certs (with no CA provided) are used.
pre-upgrade hook works if self-signed certs with no CA are used.
None
- fixes #https://github.com/bitnami/containers/issues/78362
N/A

[bitnami/etcd] bugfix: skip TLS verification with self-signed certs

---

bitnami/redis-cluster/CHANGELOG.md
bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/_helpers.tpl
bitnami/redis-cluster/templates/redis-statefulset.yaml

Fixes an issue when, in the values yaml, the yes/no value for `redis.useAOFPersistence` is provided without quotes.
If provided without quotes, YAML will interpret yes/no as true/false, and when `{{ .Values.redis.useAOFPersistence | quote }}` is interpreted, it will print "true"/"false" instead of the expected "yes"/"no".
The new helper makes the chart tolerant to using both string and boolean values for `redis.useAOFPersistence`.
Avoid issues when users accidentally use the value `useAOFPersistence` without quotes and yaml interprets it as boolean.
None known.
- fixes #31883
https://www.bram.us/2022/01/11/yaml-the-norway-problem/

[bitnami/redis-cluster] Use ternary yes/no for useAOFPersistence

---

.vib/kubernetes-event-exporter/ginkgo/kubernetes_event_exporter.go
bitnami/kubernetes-event-exporter/CHANGELOG.md
bitnami/kubernetes-event-exporter/Chart.yaml

Depending on the K8s platform, the kubernetes event will display a different message to state the container was created. This PR makes the regexp more flexible.
CI works on different K8s platforms.
None
None
N/A

[bitnami/kubernetes-event-exporter] ci: more flexible regexp on Ginkgo tests

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/repo-server/deployment.yaml
bitnami/argo-cd/templates/server/deployment.yaml

Fixes the name of the *_FILE environment names in the server and repo-server deployments.
None known.
- fixes #32444

[bitnami/argo-cd] Fix redis password not read when using passwordFiles

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md
bitnami/spring-cloud-dataflow/templates/skipper/externaldb-secret.yaml

the documented `externalDatabase.skipper.password` will now be accepted by the chart and take precedence over `externalDatabase.password`.
implementation will reflect the documentation
none, ensured the change is backwards compatible by falling back to `externalDatabase.password` if `externalDatabase.skipper.password`is empty
N/A
N/A

[bitnami/spring-cloud-dataflow] fix incorrect application of externalDatabase.skipper.password value

---

bitnami/rabbitmq/CHANGELOG.md
bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/templates/svc-headless.yaml
bitnami/rabbitmq/values.yaml

Hello !
Add trafficDistribution feature on svc-headless of RabbitMQ. 
This feature is available since k8s v1.31.
Take advantage of the new feature trafficDistribution.
cf. https://kubernetes.io/docs/concepts/services-networking/service/#traffic-distribution
Normally, no drawbacks.

[bitnami/rabbitmq] allow to configure trafficDistribution

---

bitnami/grafana-operator/README.md

Fixes: #32494 
This pull request contains update of link to Grafana's Dashboards documentation. The previous one seems to be outdated.
The most up to date links to docs.
N/A
N/A
N/A

[bitnami/grafana-operator] Fix link to grafana-operator dashboards documentation

---

bitnami/cassandra/CHANGELOG.md
bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/statefulset.yaml

On 'init-certs' init-container, don't attempt overwriting read only ssl certs when they already exist (from previous runs of the init-container) 
Avoids an issue where the cassandra pod is stuck in a init:crashLoopBackoff because the previously copied certs cannot be overwritten.
If the certs exist from some process other than the init-container, they may not be overwritten correctly from the configured k8s secret.
- fixes #32369 
This will fix the 12.X.X version of the cassandra charts, which by default use cassandra 5.0.x.  Are the charts intended to be backwards compatible for cassandra 4.1?  If not, is there a way to patch the 11.X version of the cassandra charts?

[bitnami/cassandra] bugfix #32369

---

.vib/kong/vib-action.config
bitnami/kong/CHANGELOG.md
bitnami/kong/Chart.yaml
bitnami/kong/templates/ingress-controller-rbac.yaml

Concat namespace to `ClusterRole` and `ClusterRoleBinding` name.
It allows several kong releases in the same cluster.
Names for `ClusterRole` and `ClusterRoleBinding` resources will change. Users who deploy the chart from the `helm template` result,  could see 2  cluster roles linked to the Kong `ServiceAccount`.
With this change we don't need to test the chart in serial mode.

[bitnami/kong] chore(ClusterRole): Concat namespace in ClusterRole name

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/setup-db-job.yaml

Fixes bug due to indentation on the airflow chart setupDBJob.yaml template. 
Allows chart user to override setupDBJob resources to custom needs.
N/A
- fixes #32581 
- Simple one liner change. 
-

bitnami/airflow  Fix indentation error when providing setupDBJob.resources in values

---

bitnami/schema-registry/CHANGELOG.md
bitnami/schema-registry/Chart.lock
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/templates/statefulset.yaml
bitnami/schema-registry/values.yaml

This PR bumps the chart major version given we bumped the major version in one of the chart dependencies: Kafka. Find more information below:
- https://github.com/bitnami/charts/tree/main/bitnami/kafka#to-3200
Keep the chart up-to-date with latest deps changes.
None
None
N/A

[bitnami/schema-registry] feat: bump major due to major bump on Kafka dep

---

bitnami/kafka/CHANGELOG.md
bitnami/kafka/Chart.yaml
bitnami/kafka/templates/secrets.yaml

This PR fixes an important upgrading bug due to an issue on secret lookup with the keys.
Upgrading from `32.y.z` versions work
None
- fixes https://github.com/bitnami/charts/issues/32620
N/A

[bitnami/kafka] bugfix: upgrade issue due to secret lookup

---

bitnami/kafka/CHANGELOG.md
bitnami/kafka/Chart.yaml
bitnami/kafka/templates/broker/statefulset.yaml
bitnami/kafka/templates/controller-eligible/statefulset.yaml

This PR relaxes the conditions under SASL secret must be mounted as volume on Kafka pods.
Fix statefulset(s) when using PLAIN as SASL mechanism.
None
None
N/A

[bitnami/kakfa] bugfix: relax conditions under SASL secret must be mounted as volume

---

bitnami/dremio/CHANGELOG.md
bitnami/dremio/Chart.lock
bitnami/dremio/Chart.yaml
bitnami/dremio/README.md

Bumps a major version updating the Minio subchart version to 16.x.x

[bitnami/dremio] Bump MinIO major version 16.x.x

---

bitnami/grafana-mimir/CHANGELOG.md
bitnami/grafana-mimir/Chart.lock
bitnami/grafana-mimir/Chart.yaml
bitnami/grafana-mimir/README.md

Bumps a major version updating the Minio subchart version to 16.x.x

[bitnami/grafana-mimir] Bump MinIO major version 16.x.x

---

bitnami/kafka/README.md

In the mongoDB Kafka Connector sink example of the "Deploying extra resources" section,
- corrected two paths in the `CMD` of the Dockerfile
- updated hostname and port of the example `bootstrap.servers` configuration.
The line 
```Dockerfile
CMD /opt/bitnami/kafka/bin/connect-standalone.sh /opt/bitnami/kafka/config/connect-standalone.properties /opt/bitnami/kafka/config/mongo.properties
```
points `connect-standalone.sh` to the configuration files that are by default in the docker image. This means that if a user of the chart builds this Dockerfile, the configurations that are made in the ConfigMap are not used since those configurations are mounted on a different path. This also means that by default the pod does not manage to connect to the controller since the default hostname is …

bitnami/kafka Adjust parameters in example of section "Deploying extra resources" in README 

---

bitnami/external-dns/CHANGELOG.md
bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/clusterrole.yaml

This PR adds missing RBAC to the `external-dns` chart.
The change in this PR reflects the following upstream change: https://github.com/kubernetes-sigs/external-dns/pull/5066
Support for TransportServer as a `Source` in `external-dns` where added in `0.16.0` of `external-dns`.
We'll be able to configure the `--source=f5-transportserver` flag which instructs `external-dns` to list all `TransportServer` objects in the cluster, these objects will be used as a source to create DNS records in the given provider.

[bitnami/external-dns] Add RBAC to support F5 TransportServer source

---

bitnami/wildfly/CHANGELOG.md
bitnami/wildfly/Chart.yaml
bitnami/wildfly/README.md
bitnami/wildfly/templates/deployment.yaml
bitnami/wildfly/values.yaml

[bitnami/wildfly] Set `usePasswordFiles=true` by default

---

bitnami/moodle/CHANGELOG.md
bitnami/moodle/Chart.yaml
bitnami/moodle/README.md
bitnami/moodle/templates/deployment.yaml
bitnami/moodle/values.yaml

[bitnami/moodle] Set `usePasswordFiles=true` by default

---

bitnami/tomcat/CHANGELOG.md
bitnami/tomcat/Chart.yaml
bitnami/tomcat/README.md
bitnami/tomcat/templates/_pod.tpl
bitnami/tomcat/values.yaml

[bitnami/tomcat] Set `usePasswordFiles=true` by default

---

bitnami/redmine/CHANGELOG.md
bitnami/redmine/Chart.yaml
bitnami/redmine/README.md
bitnami/redmine/templates/cronjob.yaml
bitnami/redmine/templates/deployment.yaml
bitnami/redmine/templates/mail-receiver-configmap.yaml
bitnami/redmine/values.yaml

[bitnami/redmine] Set `usePasswordFiles=true` by default

---

bitnami/scylladb/CHANGELOG.md
bitnami/scylladb/Chart.yaml
bitnami/scylladb/README.md
bitnami/scylladb/templates/statefulset.yaml
bitnami/scylladb/values.yaml

[bitnami/scylladb] Set `usePasswordFiles=true` by default

---

bitnami/wordpress/CHANGELOG.md
bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md
bitnami/wordpress/templates/deployment.yaml
bitnami/wordpress/values.yaml

[bitnami/wordpress] Set `usePasswordFiles=true` by default

---

bitnami/opensearch/CHANGELOG.md
bitnami/opensearch/Chart.yaml
bitnami/opensearch/README.md
bitnami/opensearch/templates/_helpers.tpl
bitnami/opensearch/templates/coordinating/statefulset.yaml
bitnami/opensearch/templates/dashboards/deployment.yaml
bitnami/opensearch/templates/data/statefulset.yaml
bitnami/opensearch/templates/ingest/statefulset.yaml
bitnami/opensearch/templates/master/statefulset.yaml
bitnami/opensearch/values.yaml

[bitnami/opensearch] Set `usePasswordFiles=true` by default

---

bitnami/schema-registry/CHANGELOG.md
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/templates/statefulset.yaml
bitnami/schema-registry/values.yaml

[bitnami/schema-registry] Set `usePasswordFiles=true` by default

---

bitnami/kibana/CHANGELOG.md
bitnami/kibana/Chart.yaml
bitnami/kibana/README.md
bitnami/kibana/templates/deployment.yaml
bitnami/kibana/values.yaml

[bitnami/kibana] Set `usePasswordFiles=true` by default

---

bitnami/solr/CHANGELOG.md
bitnami/solr/Chart.yaml
bitnami/solr/README.md
bitnami/solr/templates/metrics-deployment.yaml
bitnami/solr/templates/scripts-configmap.yaml
bitnami/solr/templates/statefulset.yaml
bitnami/solr/values.yaml

[bitnami/solr] Set `usePasswordFiles=true` by default

---

bitnami/discourse/CHANGELOG.md
bitnami/discourse/Chart.yaml
bitnami/discourse/templates/deployment.yaml

This allows the initContainer `install-plugins` to use environment variables set via ConfigMap or Secret. 
Sometimes you need to install discourse plugins from private github repositories and you can do so normally by passing your github personal access token in the url of this plugin repo like this: 
`https://${GITHUBPAT}@github.com/myprivateorg/discourseplugin`
That definitely something you'd want to pass as a secret.
Maybe by using `.Values.discourse.extraEnvVarsCM` and `.Values.discourse.extraEnvVarsSecret` we are passing unnecessary env vars but I also don't see the harm. We could also add `Values.install-plugins.*`  instead.

[bitnami/discourse] Support envFrom in `install-plugins`

---

bitnami/zookeeper/CHANGELOG.md
bitnami/zookeeper/Chart.yaml
bitnami/zookeeper/README.md
bitnami/zookeeper/templates/statefulset.yaml
bitnami/zookeeper/values.yaml

[bitnami/zookeeper] Set `usePasswordFiles=true` by default

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/_helpers.tpl
bitnami/keycloak/templates/secret-external-db.yaml

[bitnami/keycloak] The secret name of the externaldb is inherited by the .Release.Name and not by the (include "common.names.fullname" .) function.

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.yaml
bitnami/mongodb/README.md
bitnami/mongodb/templates/arbiter/statefulset.yaml
bitnami/mongodb/templates/backup/cronjob.yaml
bitnami/mongodb/templates/hidden/statefulset.yaml
bitnami/mongodb/templates/replicaset/statefulset.yaml
bitnami/mongodb/templates/standalone/dep-sts.yaml
bitnami/mongodb/templates/update-password/job.yaml
bitnami/mongodb/values.yaml

[bitnami/mongodb] Set `usePasswordFiles=true` by default

---

bitnami/external-dns/CHANGELOG.md
bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/deployment.yaml

This change will prevent setting EXTERNAL_DNS_RFC2136_TSIG_SECRET variable from a secret when `.Values.provider` is not set to `rfc2136`.
Prevent accidental misconfiguration. Especially when using chart as a downstream library.
none
- fixes #
I have a use case where I am using this helm chart as a dependency and allow for configuring two providers. To allow for easy debugging, I am preconfiguring this helm chart and setting `rfc2136.secretName` (secret is generated via other means and name is static). However when I want to use other provider (via `.Values.provider`), the `EXTERNAL_DNS_RFC2136_TSIG_SECRET` is still included in the Deployment object, which I would consider a bug.

bitnami/external-dns: do not set EXTERNAL_DNS_RFC2136_TSIG_SECRET when rfc2136 provider is not used

---

bitnami/matomo/CHANGELOG.md
bitnami/matomo/Chart.yaml
bitnami/matomo/templates/deployment.yaml
bitnami/matomo/templates/pdb.yaml

That label is required, so that the pod disruption budget only matches pods of the deployment and not the cronjobs.
You no longer see `Failed to calculate the number of expected pods: jobs.batch does not implement the scale subresource` warning.
none known
- fixes #29884

[bitnami/matomo] Add missing `app.kubernetes.io/component` label to deployment and pdb

---

bitnami/minio/CHANGELOG.md
bitnami/minio/Chart.yaml
bitnami/minio/templates/distributed/statefulset.yaml
bitnami/minio/templates/provisioning-job.yaml
bitnami/minio/templates/standalone/deployment.yaml

Fixes an issue when using values `auth.rootPasswordSecretKey` or `auth.rootUserSecretKey`.
None known.
- fixes #32850

[bitnami/minio] Fix issue when using custom secret keys

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.yaml
bitnami/etcd/templates/statefulset.yaml

fix livenessprobe when metrics.useSeparateEndpoint is set.
Force to listen on metrics port instead of client port.
Allow livenessProbe to succeed when metrics.useSeparateEndpoint is set.
- fixes #

[bitnami/etcd] fix livenessprobe when metrics.useSeparateEndpoint is set

---

bitnami/schema-registry/CHANGELOG.md
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/templates/hpa.yaml

The HPA is currently looking for a deployment. But the schema-registry is managed by a statefulset. We so update the reference to the good kind
HPA will work well
None
- Fixes https://github.com/bitnami/charts/issues/32869

Update HPA with statefulset as reference instead of deployment

---

bitnami/influxdb/CHANGELOG.md
bitnami/influxdb/Chart.yaml
bitnami/influxdb/README.md
bitnami/influxdb/templates/NOTES.txt
bitnami/influxdb/templates/configmap-backup.yaml
bitnami/influxdb/templates/servicemonitor.yaml
bitnami/influxdb/values.yaml

This PR replaces references to `.Release.Namespace` using our common helper `common.names.namespace`
Target namespace can be overwritten via the `namespaceOverride` chart parameter.
None
- fixes #32939
N/A

[bitnami/influxdb] bugfix: replace references to .Release.Namespace

---

bitnami/matomo/CHANGELOG.md
bitnami/matomo/Chart.yaml
bitnami/matomo/templates/cronjob.yaml

Added matomo-secrets volume to matomo-archive cronjob.
Deployable archive cronjob
-
- fixes #32884
-

[bitnami/matomo] Adds matomo-secrets volume to matomo-archive cronjob

---

bitnami/redis-cluster/CHANGELOG.md
bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/redis-statefulset.yaml

When the `existingSecret` value is not defined, the chart adds the checksum annotation to the StatefulSet resource. However, we would like the opposite behavior.
Not really a "Benefit," just cleaning up the resource annotation.
RAS
- fixes #

 [bitnami/redis-cluster] fix: Do not generate secret checksum when is not existing

---

bitnami/solr/README.md
bitnami/solr/values.yaml
bitnami/zookeeper/values.yaml

There are some typos in Solr and Zookeeper mentioning Geode.
There is no need to update the chart version or separate the changes into different PRs since the modifications only impact comments.

Fix typo mentioning Geode in Solr and Zookeeper

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/statefulset.yaml

This PR adds a `db-` prefix on projected database secret keys to avoid collisions with the Keycloak password secret key.
Avoid collisions to overwrite passwords.
None
Reported by @olav-st at https://github.com/bitnami/charts/pull/32594
N/A

[bitnami/keycloak] bugfix: add prefix on projected db secret keys

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/templates/_helpers.tpl
bitnami/redis/templates/configmap.yaml
bitnami/redis/values.yaml

- Introduced auth.acl.userSecret for specifying the secret containing user credentials.
- Added helper function common.secrets.get to fetch user credentials from a Secret.
- Updated Redis ACL user configuration to prioritize secrets over plain-text passwords.
- Ensured backward compatibility by falling back to .password when no secret is found.
- Allows passwords to be managed in Kubernetes secrets instead of being hardcoded in `values.yaml`.
- None. The change is backward compatible, and previous users can continue using the chart without any issues.

[bitnami/redis] Support retrieving Redis ACL user passwords from Kubernetes Secrets 

---

.vib/clickhouse-operator/goss/goss.yaml
.vib/clickhouse-operator/runtime-parameters.yaml
bitnami/clickhouse-operator/CHANGELOG.md
bitnami/clickhouse-operator/Chart.yaml
bitnami/clickhouse-operator/README.md

This PR extends the example we have in the README so it doesn't deploy a simple ClickHouse Installation but one that uses a ClickHouse Keeper Installation.
It also simplifies the runtime parameter setup by removing some extra properties that aren't required.
Users understand how to create ClickHouse Keeper Installations.
None
None
N/A

[bitnami/clickhouse-operator] docs: improve examples on READMEs

---

bitnami/matomo/CHANGELOG.md
bitnami/matomo/Chart.yaml
bitnami/matomo/templates/cronjob.yaml

fix mount path for matomo-secrets volume on cronjobs
Archive job works with password files.
none known
- regression of #32363
- fixes #32884
- closes #32924

[bitnami/matomo] fix mount path for `matomo-secrets` volume on cronjobs

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/templates/scripts-configmap.yaml

Since #32190, using Redis Sentinel means the Redis Sentinels will not announce their hostnames anymore. This is because the `sentinel announce-ip` configuration is only included when `.Values.sentinel.externalAccess.enabled` is set to `true`.
Before #32190, `sentinel announce-ip` was always included with the sentinel configuration, unless it was already included within the custom configuration that can be set through `.Values.sentinel.configuration`.
This change ensures that the old behaviour is restored. As long as `sentinel announce-ip` is not set manually as part of `.Values.sentinel.configuration`, it is always included to ensure that sentinels announce their hostnames to eachother. When external access is enabled, the configuration is changed slightly in correspondence with #32190, …

[bitnami/redis] fix 32573 - Always announce hostname independent of external service configuration

---

bitnami/clickhouse/CHANGELOG.md
bitnami/clickhouse/Chart.yaml
bitnami/clickhouse/templates/service.yaml
bitnami/clickhouse/templates/servicemonitor.yaml

This PR fixes the value for `prometheus.io/scrape` label which should be a string.
Metrics integration works as expected.
None
- fixes #33058
- fixes #33057
N/A

[bitnami/clickhouse] bugfix: prometheus.io/scrape label

---

bitnami/postgresql-ha/CHANGELOG.md
bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/templates/postgresql/statefulset.yaml

Updates `POSTGRES_POSTGRES_PASSWORD` condition that is now preventing to add a custom user during initialization with the next sample values:
```yaml
postgresql:
username: user1
password: 123456
```
- fixes https://github.com/bitnami/charts/issues/25671

[bitnami/postgresql-ha] Update POSTGRES_POSTGRES_PASSWORD condition

---

bitnami/grafana/CHANGELOG.md
bitnami/grafana/Chart.yaml
bitnami/grafana/README.md
bitnami/grafana/templates/configmap.yaml
bitnami/grafana/templates/dashboard-provider.yaml
bitnami/grafana/templates/datasources-secret.yaml
bitnami/grafana/templates/deployment.yaml
bitnami/grafana/templates/ingress.yaml
bitnami/grafana/templates/ldap-secret.yaml
bitnami/grafana/templates/prometheusrules.yaml
bitnami/grafana/templates/pvc.yaml
bitnami/grafana/templates/secret.yaml
bitnami/grafana/templates/service.yaml
bitnami/grafana/templates/serviceaccount.yaml
bitnami/grafana/templates/servicemonitor.yaml
bitnami/grafana/templates/smtp-secret.yaml
bitnami/grafana/templates/tls-secret.yaml
bitnami/grafana/values.yaml

Use the common namespaceOverride options
deploy the chart in custom namespaces

[bitnami/grafana] fixed namespaceOverride options

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/templates/master/application.yaml
bitnami/redis/templates/replicas/application.yaml
bitnami/redis/templates/sentinel/statefulset.yaml
bitnami/redis/values.yaml

This PR disables the use of emptyDirs when readOnlyRootFS is disabled. This helps reducing the host filesystem exhaustion in certain use cases.
Remove unnecessary mounts when not applicable
n/a
- fixes #

[bitnami/redis] feat: :sparkles: Disable empty-dirs when readOnlyRootFS is disabled

---

bitnami/logstash/CHANGELOG.md
bitnami/logstash/Chart.yaml
bitnami/logstash/templates/headless-svc.yaml
bitnami/logstash/templates/networkpolicy.yaml

The change includes ports from the `.service.extraPorts` values to the headless service and fixes the invalid handling of the `.extraContainerPorts` values in the generated NetworkPolicy
The headless service gets more usable and the NetworkPolicy no longer errors when a additional container port is defined
None
- fixes #33054

[bitnami/logstash] Fix headless service does not include extra ports

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/statefulset.yaml

Fixes the External DB Secret Keys in the Keycloak Statefulset projected secret volume.
Instead of the DB Host, Port, Username, and DB all being the same (the DB Host), they now are the correct values.
Host == host
Port == port
Username == username
DB == DB
None
Reported by @rblaine95 in #33004
Fixes https://github.com/bitnami/charts/issues/33106
N/A

[bitnami/keycloak] Fix Keycloak external DB secret keys

---

bitnami/cassandra/CHANGELOG.md
bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/statefulset.yaml

Remove path in readinessProbe for the metrics container. Metrics are exposed directly in the root path, there is nothing exposed in `/metrics`
ReadinessProbe work as expected by default.
None

[bitnami/cassandra]fix(readinessProbe): Remove path for metrics readinessProbe

---

.vib/rabbitmq/goss/goss.yaml

Increase the `rabbitmqctl-replication-check` goss test timeout, especially for platforms as OpenShift.

[bitnami/rabbitmq] Increase goss test timeout

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md

This PR bumps the chart major version, given we bumped the major version in one of the chart dependencies: RabbitMQ. 
Keep the chart up-to-date with the latest deps changes.
None
None
N/A

[bitnami/spring-cloud-dataflow] Update RabbitMQ to major 16

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/_helpers.tpl

Fix syntax (parameter order) for flaskServerSecretKey in template
Fix in template for the `flaskServerSecretKey` definition, that makes it first look for a configured value before falling back to the default (hard-coded) value.
The template definition for `flaskServerSecretKey` works as expected, and doesn't always take the default value.
None (what I can see).
- Fixes #33234

Fix syntax (parameter order) for flaskServerSecretKey in template

---

bitnami/redis-cluster/CHANGELOG.md
bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/redis-statefulset.yaml
bitnami/redis-cluster/templates/scripts-configmap.yaml

This change replaces the default shell from /bin/sh to /bin/bash in scripts executed by the container.
Using /bin/bash allows for more reliable process management and advanced signal handling. This change is aimed at mitigating issues related to defunct (zombie) processes observed in certain server environments.
fixes:
- https://github.com/bitnami/charts/issues/9654
- https://github.com/bitnami/charts/issues/8475
- https://github.com/bitnami/charts/issues/5328
- https://github.com/bitnami/charts/issues/2441

[bitnami/redis-cluster] Switch shell from /bin/sh to /bin/bash to improve process handling

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_secrets.tpl

[bitnami/common] Allows tpl in provided passwords "common.secrets.passwords.manage"

---

bitnami/elasticsearch/CHANGELOG.md
bitnami/elasticsearch/Chart.lock
bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/README.md

Upgrade the kibana subchart to match version 9.x

[bitnami/elasticsearch] Update kibana subchart

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md

Upgrade the elasticsearch subchart to its latest version 22.x.x.
This new version upgrades Elasticsearch from version 8.x to 9.x

[bitnami/mastodon] major: Upgrade elasticsearch subchart to 22.x.x (ES 9.x)

---

bitnami/cloudnative-pg/CHANGELOG.md
bitnami/cloudnative-pg/Chart.yaml
bitnami/cloudnative-pg/templates/role.yaml
bitnami/cloudnative-pg/templates/rolebinding.yaml

- https://github.com/bitnami/charts/issues/33080

[bitnami/cloudnative-pg] fix use Values failed in range method

---

.vib/airflow/cypress/cypress/e2e/airflow.cy.js

Increases the wait value from 3 seconds to 10 seconds to validate the DAG execution has been scheduled.

[bitnami/airflow] Update Cypress test

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/NOTES.txt
bitnami/airflow/templates/web/ingress.yaml

Fix `airflow-web` service references in Ingress resource. This error is related to the `23.0.0` major release. 
- fixes #33302

[bitnami/airflow] Fix svc name for Ingress backend

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_capabilities.tpl
bitnami/common/templates/_ingress.tpl

This PR removes the APIs we deprecated a year a half ago when forcing the Kubernetes version to 1.23
More readable code
Potentially breaking the installations of those that were not complying with the pre-requisites
- fixes #

[bitnami/common] chore: :recycle: Remove deprecated APIs (<1.23.0)

---

bitnami/chainloop/CHANGELOG.md
bitnami/chainloop/Chart.lock
bitnami/chainloop/Chart.yaml
bitnami/chainloop/README.md
bitnami/chainloop/templates/cas/hpa.yaml
bitnami/chainloop/templates/controlplane/hpa.yaml

This PR bumps the required k8s version to 1.23 and removes unnecessary YAML
- fixes #

[bitnami/chainloop] chore!: :recycle: :boom: :arrow_up: Bump k8s requirements to 1.23

---

bitnami/appsmith/CHANGELOG.md
bitnami/appsmith/Chart.lock
bitnami/appsmith/Chart.yaml
bitnami/appsmith/templates/client/ingress.yaml

[bitnami/appsmith] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/consul/CHANGELOG.md
bitnami/consul/Chart.lock
bitnami/consul/Chart.yaml
bitnami/consul/templates/ingress.yaml

[bitnami/consul] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/kiam/CHANGELOG.md
bitnami/kiam/Chart.lock
bitnami/kiam/Chart.yaml

[bitnami/kiam] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/influxdb/CHANGELOG.md
bitnami/influxdb/Chart.lock
bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/ingress.yaml

[bitnami/influxdb] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/kube-arangodb/CHANGELOG.md
bitnami/kube-arangodb/Chart.lock
bitnami/kube-arangodb/Chart.yaml
bitnami/kube-arangodb/templates/hpa.yaml
bitnami/kube-arangodb/templates/ingress.yaml

[bitnami/kube-arangodb] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/kong/CHANGELOG.md
bitnami/kong/Chart.lock
bitnami/kong/Chart.yaml
bitnami/kong/templates/ingress.yaml

[bitnami/kong] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/kubernetes-event-exporter/CHANGELOG.md
bitnami/kubernetes-event-exporter/Chart.lock
bitnami/kubernetes-event-exporter/Chart.yaml

[bitnami/kubernetes-event-exporter] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/memcached/CHANGELOG.md
bitnami/memcached/Chart.lock
bitnami/memcached/Chart.yaml
bitnami/memcached/templates/hpa.yaml

[bitnami/memcached] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/mysql/CHANGELOG.md
bitnami/mysql/Chart.lock
bitnami/mysql/Chart.yaml

[bitnami/mysql] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/mongodb-sharded/CHANGELOG.md
bitnami/mongodb-sharded/Chart.lock
bitnami/mongodb-sharded/Chart.yaml

[bitnami/mongodb-sharded] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/zipkin/CHANGELOG.md
bitnami/zipkin/Chart.lock
bitnami/zipkin/Chart.yaml
bitnami/zipkin/templates/hpa.yaml
bitnami/zipkin/templates/ingress.yaml

[bitnami/zipkin] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/wildfly/CHANGELOG.md
bitnami/wildfly/Chart.lock
bitnami/wildfly/Chart.yaml
bitnami/wildfly/templates/ingress.yaml
bitnami/wildfly/templates/management-ingress.yaml

[bitnami/wildfly] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/zookeeper/CHANGELOG.md
bitnami/zookeeper/Chart.lock
bitnami/zookeeper/Chart.yaml

[bitnami/zookeeper] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/wordpress/CHANGELOG.md
bitnami/wordpress/Chart.lock
bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/hpa.yaml
bitnami/wordpress/templates/ingress-secondary.yaml
bitnami/wordpress/templates/ingress.yaml

[bitnami/wordpress] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/whereabouts/CHANGELOG.md
bitnami/whereabouts/Chart.lock
bitnami/whereabouts/Chart.yaml

[bitnami/whereabouts] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/valkey/CHANGELOG.md
bitnami/valkey/Chart.lock
bitnami/valkey/Chart.yaml
bitnami/valkey/templates/_helpers.tpl
bitnami/valkey/templates/primary/application.yaml
bitnami/valkey/templates/primary/service.yaml
bitnami/valkey/templates/replicas/application.yaml
bitnami/valkey/templates/replicas/hpa.yaml
bitnami/valkey/templates/replicas/service.yaml
bitnami/valkey/templates/role.yaml
bitnami/valkey/templates/sentinel/hpa.yaml
bitnami/valkey/templates/sentinel/statefulset.yaml

[bitnami/valkey] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/templates/prometheus-proxy/hpa.yaml
bitnami/spring-cloud-dataflow/templates/server/hpa.yaml
bitnami/spring-cloud-dataflow/templates/server/ingress.yaml
bitnami/spring-cloud-dataflow/templates/skipper/hpa.yaml

[bitnami/spring-cloud-dataflow] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/thanos/CHANGELOG.md
bitnami/thanos/Chart.lock
bitnami/thanos/Chart.yaml
bitnami/thanos/templates/bucketweb/hpa.yaml
bitnami/thanos/templates/bucketweb/ingress.yaml
bitnami/thanos/templates/compactor/ingress.yaml
bitnami/thanos/templates/query-frontend/hpa.yaml
bitnami/thanos/templates/query-frontend/ingress.yaml
bitnami/thanos/templates/query/hpa.yaml
bitnami/thanos/templates/query/ingress-grpc.yaml
bitnami/thanos/templates/query/ingress.yaml
bitnami/thanos/templates/receive-distributor/hpa.yaml
bitnami/thanos/templates/receive/hpa.yaml
bitnami/thanos/templates/receive/ingress.yaml
bitnami/thanos/templates/receive/statefulset.yaml
bitnami/thanos/templates/ruler/hpa.yaml
bitnami/thanos/templates/ruler/ingress.yaml
bitnami/thanos/templates/ruler/statefulset.yaml
bitnami/thanos/templates/storegateway/hpa-sharded.yaml
bitnami/thanos/templates/storegateway/hpa.yaml
bitnami/thanos/templates/storegateway/ingress-grpc.yaml
bitnami/thanos/templates/storegateway/ingress.yaml
bitnami/thanos/templates/storegateway/statefulset-sharded.yaml
bitnami/thanos/templates/storegateway/statefulset.yaml

[bitnami/thanos] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/spark/CHANGELOG.md
bitnami/spark/Chart.lock
bitnami/spark/Chart.yaml
bitnami/spark/templates/hpa-worker.yaml
bitnami/spark/templates/ingress.yaml

[bitnami/spark] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.lock
bitnami/seaweedfs/Chart.yaml
bitnami/seaweedfs/templates/filer/hpa.yaml
bitnami/seaweedfs/templates/filer/ingress.yaml
bitnami/seaweedfs/templates/master/hpa.yaml
bitnami/seaweedfs/templates/master/ingress.yaml
bitnami/seaweedfs/templates/s3/hpa.yaml
bitnami/seaweedfs/templates/s3/ingress.yaml
bitnami/seaweedfs/templates/volume/hpa.yaml
bitnami/seaweedfs/templates/volume/ingress.yaml
bitnami/seaweedfs/templates/webadv/hpa.yaml
bitnami/seaweedfs/templates/webadv/ingress.yaml

[bitnami/seaweedfs] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/sealed-secrets/CHANGELOG.md
bitnami/sealed-secrets/Chart.lock
bitnami/sealed-secrets/Chart.yaml
bitnami/sealed-secrets/templates/_helpers.tpl
bitnami/sealed-secrets/templates/ingress.yaml
bitnami/sealed-secrets/templates/psp.yaml

[bitnami/sealed-secrets] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/rabbitmq-cluster-operator/CHANGELOG.md
bitnami/rabbitmq-cluster-operator/Chart.lock
bitnami/rabbitmq-cluster-operator/Chart.yaml

[bitnami/rabbitmq-cluster-operator] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/neo4j/CHANGELOG.md
bitnami/neo4j/Chart.lock
bitnami/neo4j/Chart.yaml
bitnami/neo4j/templates/ingress.yaml

[bitnami/neo4j] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/nessie/CHANGELOG.md
bitnami/nessie/Chart.lock
bitnami/nessie/Chart.yaml
bitnami/nessie/templates/hpa.yaml
bitnami/nessie/templates/ingress.yaml

[bitnami/nessie] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/nginx/CHANGELOG.md
bitnami/nginx/Chart.lock
bitnami/nginx/Chart.yaml
bitnami/nginx/templates/health-ingress.yaml
bitnami/nginx/templates/hpa.yaml
bitnami/nginx/templates/ingress.yaml

[bitnami/nginx] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

.vib/superset/goss/goss.yaml
bitnami/superset/CHANGELOG.md
bitnami/superset/Chart.yaml
bitnami/superset/templates/_helpers.tpl
bitnami/superset/templates/init/init-job.yaml
bitnami/superset/templates/web/deployment.yaml

The init job is taking too long due to 429 HTTP errors when the value `loadExamples` is set. Examples database is downloaded from github making several requests. The initialization process could take about 5 min.
Superset web pods will start once the examples are completely loaded without errors or retries.
None

[bitnami/superset] fix(wait-for-examples): Support 429 errors in examples load

---

bitnami/moodle/CHANGELOG.md
bitnami/moodle/Chart.lock
bitnami/moodle/Chart.yaml
bitnami/moodle/templates/hpa.yaml
bitnami/moodle/templates/ingress.yaml

[bitnami/moodle] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.lock
bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/tracking/hpa.yaml
bitnami/mlflow/templates/tracking/ingress.yaml

[bitnami/mlflow] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/metrics-server/CHANGELOG.md
bitnami/metrics-server/Chart.lock
bitnami/metrics-server/Chart.yaml

[bitnami/metrics-server] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/multus-cni/CHANGELOG.md
bitnami/multus-cni/Chart.lock
bitnami/multus-cni/Chart.yaml

[bitnami/multus-cni] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/node-exporter/CHANGELOG.md
bitnami/node-exporter/Chart.lock
bitnami/node-exporter/Chart.yaml

[bitnami/node-exporter] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/odoo/CHANGELOG.md
bitnami/odoo/Chart.lock
bitnami/odoo/Chart.yaml
bitnami/odoo/templates/hpa.yaml
bitnami/odoo/templates/ingress.yaml

[bitnami/odoo] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/oauth2-proxy/CHANGELOG.md
bitnami/oauth2-proxy/Chart.lock
bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/templates/ingress.yaml

[bitnami/oauth2-proxy] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/kuberay/CHANGELOG.md
bitnami/kuberay/Chart.lock
bitnami/kuberay/Chart.yaml
bitnami/kuberay/templates/apiserver/hpa.yaml
bitnami/kuberay/templates/apiserver/ingress.yaml
bitnami/kuberay/templates/operator/hpa.yaml
bitnami/kuberay/templates/operator/ingress.yaml

[bitnami/kuberay] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/logstash/CHANGELOG.md
bitnami/logstash/Chart.lock
bitnami/logstash/Chart.yaml
bitnami/logstash/templates/ingress.yaml

[bitnami/logstash] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/mariadb/CHANGELOG.md
bitnami/mariadb/Chart.lock
bitnami/mariadb/Chart.yaml

[bitnami/mariadb] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml

[bitnami/mastodon] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/metallb/CHANGELOG.md
bitnami/metallb/Chart.lock
bitnami/metallb/Chart.yaml

[bitnami/metallb] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.lock
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/admin-ingress.yaml
bitnami/keycloak/templates/hpa.yaml
bitnami/keycloak/templates/ingress.yaml
bitnami/keycloak/templates/statefulset.yaml

[bitnami/keycloak] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/keydb/CHANGELOG.md
bitnami/keydb/Chart.lock
bitnami/keydb/Chart.yaml
bitnami/keydb/templates/replica/hpa.yaml

[bitnami/keydb] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/kube-prometheus/CHANGELOG.md
bitnami/kube-prometheus/Chart.lock
bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/templates/alertmanager/ingress.yaml
bitnami/kube-prometheus/templates/prometheus/ingress.yaml
bitnami/kube-prometheus/templates/prometheus/thanos-ingress.yaml

[bitnami/kube-prometheus] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/kibana/CHANGELOG.md
bitnami/kibana/Chart.lock
bitnami/kibana/Chart.yaml
bitnami/kibana/templates/ingress.yaml

[bitnami/kibana] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/kube-state-metrics/CHANGELOG.md
bitnami/kube-state-metrics/Chart.lock
bitnami/kube-state-metrics/Chart.yaml

[bitnami/kube-state-metrics] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/kubeapps/CHANGELOG.md
bitnami/kubeapps/Chart.lock
bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/templates/ingress-api.yaml
bitnami/kubeapps/templates/ingress.yaml

[bitnami/kubeapps] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/jupyterhub/CHANGELOG.md
bitnami/jupyterhub/Chart.lock
bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/templates/proxy/ingress.yaml

[bitnami/jupyterhub] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/kafka/CHANGELOG.md
bitnami/kafka/Chart.lock
bitnami/kafka/Chart.yaml
bitnami/kafka/templates/broker/hpa.yaml
bitnami/kafka/templates/controller-eligible/hpa.yaml

[bitnami/kafka] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/jenkins/CHANGELOG.md
bitnami/jenkins/Chart.lock
bitnami/jenkins/Chart.yaml
bitnami/jenkins/templates/ingress.yaml

[bitnami/jenkins] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.lock
bitnami/harbor/Chart.yaml
bitnami/harbor/templates/ingress/core-ingress.yaml

[bitnami/harbor] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/janusgraph/CHANGELOG.md
bitnami/janusgraph/Chart.lock
bitnami/janusgraph/Chart.yaml
bitnami/janusgraph/templates/hpa.yaml

[bitnami/janusgraph] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/parse/CHANGELOG.md
bitnami/parse/Chart.lock
bitnami/parse/Chart.yaml
bitnami/parse/templates/ingress.yaml

[bitnami/parse] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/haproxy/CHANGELOG.md
bitnami/haproxy/Chart.lock
bitnami/haproxy/Chart.yaml
bitnami/haproxy/templates/hpa.yaml
bitnami/haproxy/templates/ingress.yaml

[bitnami/haproxy] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/grafana-tempo/CHANGELOG.md
bitnami/grafana-tempo/Chart.lock
bitnami/grafana-tempo/Chart.yaml

[bitnami/grafana-tempo] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/grafana-loki/CHANGELOG.md
bitnami/grafana-loki/Chart.lock
bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/templates/gateway/ingress.yaml

[bitnami/grafana-loki] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/grafana-mimir/CHANGELOG.md
bitnami/grafana-mimir/Chart.lock
bitnami/grafana-mimir/Chart.yaml
bitnami/grafana-mimir/templates/gateway/ingress.yaml

[bitnami/grafana-mimir] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/pinniped/CHANGELOG.md
bitnami/pinniped/Chart.lock
bitnami/pinniped/Chart.yaml
bitnami/pinniped/templates/supervisor/ingress.yaml

[bitnami/pinniped] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/gitlab-runner/CHANGELOG.md
bitnami/gitlab-runner/Chart.yaml
bitnami/gitlab-runner/templates/hpa.yaml
bitnami/gitlab-runner/templates/session-server-ingress.yaml

[bitnami/gitlab-runner] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/gitea/CHANGELOG.md
bitnami/gitea/Chart.lock
bitnami/gitea/Chart.yaml
bitnami/gitea/templates/ingress.yaml

[bitnami/gitea] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/ghost/CHANGELOG.md
bitnami/ghost/Chart.lock
bitnami/ghost/Chart.yaml
bitnami/ghost/templates/ingress.yaml

[bitnami/ghost] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/flux/CHANGELOG.md
bitnami/flux/Chart.lock
bitnami/flux/Chart.yaml

[bitnami/flux] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/flink/CHANGELOG.md
bitnami/flink/Chart.lock
bitnami/flink/Chart.yaml

[bitnami/flink] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/envoy-gateway/CHANGELOG.md
bitnami/envoy-gateway/Chart.lock
bitnami/envoy-gateway/Chart.yaml
bitnami/envoy-gateway/templates/hpa.yaml

[bitnami/envoy-gateway] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/elasticsearch/CHANGELOG.md
bitnami/elasticsearch/Chart.lock
bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/coordinating/hpa.yaml
bitnami/elasticsearch/templates/data/hpa.yaml
bitnami/elasticsearch/templates/ingest/hpa.yaml
bitnami/elasticsearch/templates/ingest/ingress.yaml
bitnami/elasticsearch/templates/ingress.yaml
bitnami/elasticsearch/templates/master/hpa.yaml

[bitnami/elasticsearch] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/discourse/CHANGELOG.md
bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml
bitnami/discourse/templates/ingress.yaml

[bitnami/discourse] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/external-dns/CHANGELOG.md
bitnami/external-dns/Chart.lock
bitnami/external-dns/Chart.yaml

[bitnami/external-dns] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/dremio/CHANGELOG.md
bitnami/dremio/Chart.lock
bitnami/dremio/Chart.yaml
bitnami/dremio/templates/coordinator/hpa.yaml
bitnami/dremio/templates/executor/hpa.yaml
bitnami/dremio/templates/ingress.yaml
bitnami/dremio/templates/master-coordinator/hpa.yaml

[bitnami/dremio] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/concourse/CHANGELOG.md
bitnami/concourse/Chart.lock
bitnami/concourse/Chart.yaml
bitnami/concourse/templates/web/ingress.yaml

[bitnami/concourse] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/cloudnative-pg/CHANGELOG.md
bitnami/cloudnative-pg/Chart.lock
bitnami/cloudnative-pg/Chart.yaml
bitnami/cloudnative-pg/templates/hpa.yaml

[bitnami/cloudnative-pg] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/clickhouse-operator/CHANGELOG.md
bitnami/clickhouse-operator/Chart.lock
bitnami/clickhouse-operator/Chart.yaml
bitnami/clickhouse-operator/templates/hpa.yaml

[bitnami/clickhouse-operator] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/aspnet-core/CHANGELOG.md
bitnami/aspnet-core/Chart.lock
bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/templates/health-ingress.yaml
bitnami/aspnet-core/templates/hpa.yaml
bitnami/aspnet-core/templates/ingress.yaml

[bitnami/aspnet-core] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/cassandra/CHANGELOG.md
bitnami/cassandra/Chart.lock
bitnami/cassandra/Chart.yaml

[bitnami/cassandra] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/cadvisor/CHANGELOG.md
bitnami/cadvisor/Chart.lock
bitnami/cadvisor/Chart.yaml
bitnami/cadvisor/templates/ingress.yaml

[bitnami/cadvisor] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/argo-workflows/CHANGELOG.md
bitnami/argo-workflows/Chart.lock
bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/templates/server/ingress.yaml

[bitnami/argo-workflows] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.lock
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/applicationset/ingress-webhook.yaml
bitnami/argo-cd/templates/repo-server/hpa.yaml
bitnami/argo-cd/templates/server/hpa.yaml
bitnami/argo-cd/templates/server/ingress-grcp.yaml
bitnami/argo-cd/templates/server/ingress.yaml

[bitnami/argo-cd] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/apache/CHANGELOG.md
bitnami/apache/Chart.lock
bitnami/apache/Chart.yaml
bitnami/apache/templates/hpa.yaml
bitnami/apache/templates/ingress.yaml

[bitnami/apache] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.lock
bitnami/apisix/Chart.yaml
bitnami/apisix/templates/control-plane/hpa.yaml
bitnami/apisix/templates/control-plane/ingress.yaml
bitnami/apisix/templates/dashboard/hpa.yaml
bitnami/apisix/templates/dashboard/ingress.yaml
bitnami/apisix/templates/data-plane/hpa.yaml
bitnami/apisix/templates/data-plane/ingress.yaml
bitnami/apisix/templates/ingress-controller/hpa.yaml
bitnami/apisix/templates/ingress-controller/ingress.yaml

[bitnami/apisix] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/cert-manager/CHANGELOG.md
bitnami/cert-manager/Chart.lock
bitnami/cert-manager/Chart.yaml

[bitnami/cert-manager] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/cilium/CHANGELOG.md
bitnami/cilium/Chart.lock
bitnami/cilium/Chart.yaml
bitnami/cilium/templates/hubble-relay/hpa.yaml
bitnami/cilium/templates/hubble-ui/hpa.yaml
bitnami/cilium/templates/hubble-ui/ingress.yaml
bitnami/cilium/templates/operator/hpa.yaml

[bitnami/cilium] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/templates/podmonitor.yaml

The PodMonitor template was mistakenly checking for
```
.Values.metrics.serviceMonitor.podTargetLabels
```
instead of
```
.Values.metrics.podMonitor.podTargetLabels
```
As a result, any podTargetLabels defined under metrics.podMonitor were ignored.

[bitnami/redis] fix pod-monitor podTargetLabels conditional 

---

bitnami/minio/CHANGELOG.md
bitnami/minio/Chart.lock
bitnami/minio/Chart.yaml
bitnami/minio/templates/api-ingress.yaml
bitnami/minio/templates/ingress.yaml

[bitnami/minio] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/valkey-cluster/CHANGELOG.md
bitnami/valkey-cluster/Chart.lock
bitnami/valkey-cluster/Chart.yaml
bitnami/valkey-cluster/templates/_helpers.tpl
bitnami/valkey-cluster/templates/networkpolicy.yaml

[bitnami/valkey-cluster] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/solr/CHANGELOG.md
bitnami/solr/Chart.yaml
bitnami/solr/README.md
bitnami/solr/templates/statefulset.yaml
bitnami/solr/values.yaml

Add the persistentvolumeclaim retention on solr statefulset. The other bitnami charters have this configuration.
This chode change permit to delete or not pvc when the sts is scale or deleted.
The others bitnami charts have this configuration.

[bitnami/solr] Add persistentvolumeclaim retention on solr statefulset

---

bitnami/victoriametrics/CHANGELOG.md
bitnami/victoriametrics/Chart.lock
bitnami/victoriametrics/Chart.yaml
bitnami/victoriametrics/templates/vmagent/hpa.yaml
bitnami/victoriametrics/templates/vmalert/hpa.yaml
bitnami/victoriametrics/templates/vmauth/hpa.yaml
bitnami/victoriametrics/templates/vmauth/ingress.yaml
bitnami/victoriametrics/templates/vminsert/hpa.yaml
bitnami/victoriametrics/templates/vminsert/ingress.yaml
bitnami/victoriametrics/templates/vmselect/hpa.yaml
bitnami/victoriametrics/templates/vmselect/ingress.yaml
bitnami/victoriametrics/templates/vmstorage/hpa.yaml

[bitnami/victoriametrics] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/ejbca/CHANGELOG.md
bitnami/ejbca/Chart.lock
bitnami/ejbca/Chart.yaml
bitnami/ejbca/templates/_helpers.tpl
bitnami/ejbca/templates/ingress.yaml

[bitnami/ejbca] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/jaeger/CHANGELOG.md
bitnami/jaeger/Chart.lock
bitnami/jaeger/Chart.yaml

[bitnami/jaeger] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/vault/CHANGELOG.md
bitnami/vault/Chart.lock
bitnami/vault/Chart.yaml
bitnami/vault/templates/injector/hpa.yaml
bitnami/vault/templates/server/ingress.yaml

[bitnami/vault] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/tensorflow-resnet/CHANGELOG.md
bitnami/tensorflow-resnet/Chart.lock
bitnami/tensorflow-resnet/Chart.yaml

[bitnami/tensorflow-resnet] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/fluentd/CHANGELOG.md
bitnami/fluentd/Chart.lock
bitnami/fluentd/Chart.yaml
bitnami/fluentd/templates/ingress.yaml

[bitnami/fluentd] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.lock
bitnami/etcd/Chart.yaml

[bitnami/etcd] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

bitnami/matomo/CHANGELOG.md
bitnami/matomo/Chart.lock
bitnami/matomo/Chart.yaml
bitnami/matomo/templates/ingress.yaml

[bitnami/matomo] chore: :recycle: :arrow_up: Update common and remove k8s < 1.23 references

---

template/CHART_NAME/templates/hpa.yaml
template/CHART_NAME/templates/ingress.yaml

This PR updates the templates to not contain references to unsupported k8s versions

[bitnami/template] chore: :recycle: Remove deprecated APIs (<1.23.0)

---

bitnami/argo-cd/CHANGELOG.md
bitnami/argo-cd/Chart.lock
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/README.md

[bitnami/argo-cd] feat!: :arrow_up: :boom: Bump Redis(R) to 8.0

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_ingress.tpl

Follow up of https://github.com/bitnami/charts/pull/33320/. We remove these two helpers as they are not being used anymore.
Cleaner code
n/a

[bitnami/common] chore: :recycle: Remove unused helpers

---

bitnami/discourse/CHANGELOG.md
bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml
bitnami/discourse/README.md

[bitnami/discourse] feat!: :arrow_up: :boom: Bump Redis(R) to 8.0

---

bitnami/kubeapps/CHANGELOG.md
bitnami/kubeapps/Chart.lock
bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/README.md

[bitnami/kubeapps] feat!: :arrow_up: :boom: Bump Redis(R) to 8.0

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md

[bitnami/mastodon] feat!: :arrow_up: :boom: Bump Redis(R) to 8.0

---

bitnami/oauth2-proxy/CHANGELOG.md
bitnami/oauth2-proxy/Chart.lock
bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md

[bitnami/oauth2-proxy] feat!: :arrow_up: :boom: Bump Redis(R) to 8.0

---

bitnami/superset/CHANGELOG.md
bitnami/superset/Chart.lock
bitnami/superset/Chart.yaml
bitnami/superset/README.md

[bitnami/superset] feat!: :arrow_up: :boom: Bump Redis(R) to 8.0

---

bitnami/appsmith/CHANGELOG.md
bitnami/appsmith/Chart.lock
bitnami/appsmith/Chart.yaml
bitnami/appsmith/README.md

[bitnami/appsmith] feat!: :arrow_up: :boom: Bump Redis(R) to 8.0

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.lock
bitnami/airflow/Chart.yaml
bitnami/airflow/README.md

[bitnami/airflow] feat!: :arrow_up: :boom: Bump Redis(R) to 8.0

---

.vib/postgresql-ha/ginkgo/postgresql_suite_test.go
.vib/postgresql-ha/vib-verify.json
bitnami/postgresql-ha/CHANGELOG.md
bitnami/postgresql-ha/Chart.yaml

This PR attempt to improve stability on Ginkgo tests by increasing timeout for operations such as scaling up/down PostgreSQL replicas.
More stable CI
None
None
N/A

[bitnami/postgresql-ha] ci: improve stability on Ginkgo tests

---

bitnami/kubeapps/CHANGELOG.md
bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/README.md
bitnami/kubeapps/templates/NOTES.txt

The upstream project has been discontinued (see notice at https://github.com/vmware-tanzu/kubeapps?tab=readme-ov-file#-kubeapps), therefore, this Helm chart will be deprecated as well.

[bitnami/kubeapps] Deprecate Helm chart

---

bitnami/jupyterhub/CHANGELOG.md
bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/templates/hub/deployment.yaml

Use of `hub.initContainers` in the JupyterHub chart is no longer dependent on `postgresql.enabled` being true. 
Can use init containers and an external PostgreSQL instance.
None
- fixes #33524
None

[bitnami/jupyterhub] Init containers can be used with external PostgreSQL

---

bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/NOTES.txt
bitnami/postgresql/templates/_helpers.tpl
bitnami/postgresql/templates/prometheusrule.yaml
bitnami/postgresql/templates/psp.yaml
bitnami/postgresql/templates/role.yaml
bitnami/postgresql/templates/rolebinding.yaml
bitnami/postgresql/templates/secrets.yaml
bitnami/postgresql/templates/tls-secrets.yaml
bitnami/postgresql/templates/update-password/job.yaml
bitnami/postgresql/templates/update-password/new-secret.yaml
bitnami/postgresql/templates/update-password/previous-secret.yaml
bitnami/postgresql/values.yaml

Added new function that returns a global chart name while giving priority for the .Values.global.postgresql.fullnameOverride value.
Changed every occurance of "common.names.fullname" to that new function as suggested in previous PR by @juan131 
I have accidentally deleted the last PR source branch and the PR has been deleted automatically so i have created a new one.
Thanks Everyone.

[bitnami/postgresql] Support for global postgresql fullnameOverride

---

bitnami/postgresql-ha/CHANGELOG.md
bitnami/postgresql-ha/README.md

This PR adds a note on 16.0.0 notes and Changelog warning users about the security issue addressed on this version.

[bitnami-postgresql-ha] docs: document security fix on 16.0.0

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/templates/configmap.yaml

Allow grabbing sentinel acl configuration from `auth.acl.userSecret`
Sentinel acl is in sync with redis acl
I'm not sure what the correct way of handling users without passwords would be, so I'm keeping the previous behavior of just excluding users without a password.
This may be wrong, but at least it's _less wrong_ than before.
- extends #32434 which introduced this feature for non-sentinel acl configuration.
<details>
<summary>test values excerpt</summary>
```yaml
auth:
acl:
enabled: true
sentinel: true
users:
- username: alice
commands: +@all
- username: bob
commands: +@all
- username: hasnopass
commands: +@all
- username: passinvalues
password: asd
commands: +@all
userSecret: acl-secret
```
</details>
<details>
<summary>resulting `users.acl` in `configuration` configmap</summary> …

[bitnami/redis] Allow grabbing sentinel acl configuration from userSecret

---

bitnami/grafana/CHANGELOG.md
bitnami/grafana/Chart.yaml
bitnami/grafana/templates/deployment.yaml

When using grafana dashboard configMap feature (.Values.dashboardsConfigMaps) and mapping multiple dashboards to the same configMapName, the deployment will fail becaues the templating will try to mount same volume twice or more, We have to make the .spec.template.spec.volumes Uniq.

[bitnami/grafana] Grafana uniq dashboard volumes

---

.vib/clickhouse-operator/runtime-parameters.yaml
bitnami/clickhouse-operator/CHANGELOG.md
bitnami/clickhouse-operator/Chart.yaml
bitnami/clickhouse-operator/values.yaml

This PR removes a hack we included on runtime parameters to make Keeper image compatible with the Operator by modifying mount points for custom configuration. With the latest Keeper image, this hack is no longer required.
Hacks not required on read-only-fs environments.
None
None
N/A

[clickhouse-operator] ci: remove hack on runtime parameters

---

bitnami/grafana-loki/CHANGELOG.md
bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/templates/NOTES.txt
bitnami/grafana-loki/templates/compactor/deployment.yaml

Two occurances of .Values.loki.dataDir that are using the default value /bitnami/grafana-loki instead of substitution of the value.

[bitnami/grafana-loki] dataDir value substitution instead of static config

---

bitnami/kafka/CHANGELOG.md
bitnami/kafka/Chart.yaml
bitnami/kafka/README.md
bitnami/kafka/templates/_helpers.tpl
bitnami/kafka/templates/broker/configmap.yaml
bitnami/kafka/templates/controller-eligible/configmap.yaml

Controller was failing to start when separating brokers and controller due to the configuration 
```
diff --git a/bitnami/kafka/values.yaml b/bitnami/kafka/values.yaml
index accc647aed..4ef074ec86 100644
--- a/bitnami/kafka/values.yaml
+++ b/bitnami/kafka/values.yaml
@@ -113,7 +113,7 @@ image:
pullSecrets: []
##
-  debug: false
+  debug: true
@@ -671,7 +671,7 @@ controller:
replicaCount: 3
##
-  controllerOnly: false
+  controllerOnly: true
##
quorumBootstrapServers: ""
@@ -1134,7 +1134,7 @@ controller:
broker:
##
-  replicaCount: 0
+  replicaCount: 3
```
```
➜  kafka git:(main) k logs -p kafka-controller-2
Defaulted container "kafka" out of: kafka, prepare-config (init)
kafka 08:02:06.51 INFO  ==> 
kafka 08:02:06.51 INFO  ==> Welcome to the Bitnami kafka container
kafka 08:02:06.51 INFO …
```

[bitnami/kafka][bitnami/charts/issues/32851] Update controller and broker configuration when enabling controller.controllerOnly

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.yaml
bitnami/etcd/README.md
bitnami/etcd/templates/NOTES.txt
bitnami/etcd/templates/_helpers.tpl
bitnami/etcd/templates/configmap.yaml
bitnami/etcd/templates/cronjob-defrag.yaml
bitnami/etcd/templates/cronjob-snapshotter.yaml
bitnami/etcd/templates/networkpolicy.yaml
bitnami/etcd/templates/podmonitor.yaml
bitnami/etcd/templates/preupgrade-hook-job.yaml
bitnami/etcd/templates/prometheusrule.yaml
bitnami/etcd/templates/secrets.yaml
bitnami/etcd/templates/serviceaccount.yaml
bitnami/etcd/templates/snapshot-pvc.yaml
bitnami/etcd/templates/statefulset.yaml
bitnami/etcd/templates/svc-headless.yaml
bitnami/etcd/templates/svc.yaml
bitnami/etcd/templates/token-secrets.yaml
bitnami/etcd/values.yaml

This patch replaces `.Release.Namespace` by `common.names.namespace` that supports overriding namespace by `Values.namespaceOverride`.
It enables deploying the chart in a custom namespace.
N/A. (The fix is backward-compatible because `common.names.namespace` defaults to `.Release.Namespace` if `Values.namespaceOverride` is not provided.)
N/A. (Searched for namespaceOverride, etcd and no related issues found.)
> Please run any tests or examples that can exercise your modified code
Installed the new chart on a k8s cluster with or without namespaceOverride, verified that both works, 
* With namespaceOverride
```console
$ helm dependency build bitnami/etcd
$ kubectl create namespace etcd-system
$ helm upgrade --install etcd-release bitnami/etcd --values test-values.yaml --set …
```

[bitnami/etcd] Allow release namespace to be overridden

---

bitnami/postgresql-ha/CHANGELOG.md
bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/templates/_helpers.tpl
bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
bitnami/postgresql-ha/templates/postgresql/witness-statefulset.yaml

This PR ensures we properly set `POSTGRES_POSTGRES_PASSWORD` when using a custom user/db, regardless the password for 'postgres' user is consumed from an existing secret or not. 
The workflow below works:
```
kubectl create secret generic pgpool --from-literal=admin-password=adminPassword --from-literal=sr-check-password=srCheckPassword
kubectl create secret generic postgresql --from-literal=postgres-password=postgresPassword --from-literal=password=password --from-literal=repmgr-password=repmgrPassword
helm install my-release oci://registry-1.docker.io/bitnamicharts/postgresql-ha --set global.postgresql.existingSecret=postgresql --set global.pgpool.existingSecret=pgpool --set postgresql.database=test --set postgresql.username=test
```
None
- fixes #25671
N/A

[bitnami/postgresql-ha] bugfix: missing password for 'postgres' user when using custom user/db

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_names.tpl

This PR fixes an issue in the `bitnami/common` Helm chart templates where the release name could violate DNS naming conventions.  
The fix sanitizes the release name generation logic in `_names.tpl` to ensure it complies with DNS label standards, preventing deployment errors caused by invalid resource names.
- Ensures Helm release names conform to DNS naming specifications.  
- Prevents deployment failures related to invalid resource names.  
- Improves overall chart stability and compatibility with Kubernetes naming requirements.
- No known drawbacks. This change is backward compatible and does not affect existing functionality aside from improving name validation.
- 
Tested locally with various release names to confirm resource names are valid and deployments succeed.
```ruby
"A-B" => …
```

[bitnami/common] Prevent release name from breaking DNS naming specification

---

bitnami/influxdb/CHANGELOG.md
bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/create-admin-token-job.yaml
bitnami/influxdb/templates/delete-admin-token-job.yaml

In some very restrictive environments, we need to allow write permissions in `/tmp` when using read-only fs on the K8s jobs that make use of `kubectl`
Stability
None
None
N/A

[bitnami/influxdb] bugfix: address limitations with read-only restrictive environments

---

bitnami/dremio/CHANGELOG.md
bitnami/dremio/Chart.yaml
bitnami/dremio/templates/ingress.yaml

Make the ingress expose the correct port to the UI
Make the ingress work by default
Maybe it should be a variable ?
Port name is defined here : https://github.com/bitnami/charts/blob/788718d0999fa2ebb8953eb604e3df5226f7c84c/bitnami/dremio/templates/service.yaml#L40C13-L40C21
Chart.yml version was bumped two minor versions, to be compatible with #33752

[bitnami/dremio] fix: ingress to wrong port

---

.github/workflows/retry-failed-releases.yml

* According to the [documentation](https://docs.github.com/en/rest/actions/workflow-runs?apiVersion=2022-11-28#list-workflow-runs-for-a-workflow) `author` is not a valid query parameter.
* Title for automated releases has been changed. Some examples:
* #33948
* #33924
Automated releases can be retried again automatically.
None

fix(retry-failed-releases): Find releases with new format

---

bitnami/spring-cloud-dataflow/CHANGELOG.md
bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md
bitnami/spring-cloud-dataflow/templates/NOTES.txt

Those applications are not being maintained upstream, see https://spring.io/blog/2025/04/21/spring-cloud-data-flow-commercial:
> Today we're announcing that going forward *we will not be maintaining Spring Cloud Data Flow, Spring Cloud Deployer, or Spring Statemachine as open-source projects*. Spring Cloud Data Flow 2.11.x, Spring Cloud Deployer 2.9.x, and Spring Statemachine 4.0.x will be the last open-source lines and any future releases will only be made available to Tanzu Spring customers. This change has no impact on the rest of the open-source Spring portfolio or the support obligations of the currently available OSS versions for existing users.
Related to https://github.com/bitnami/charts/issues/33797

Deprecate Spring Cloud

---

bitnami/kuberay/CHANGELOG.md
bitnami/kuberay/Chart.yaml
bitnami/kuberay/templates/cluster/raycluster.yaml

Fix the indentation of `nodeAffinity` element in `workerGroupSpecs`.
This chart does not work unless setting `cluster.enabled: false`
None
- fixes #33887

fix(kuberay): wrong indentation in nodeAffinity element

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/statefulset.yaml
bitnami/mongodb/templates/backup/cronjob.yaml
bitnami/mongodb/templates/hidden/statefulset.yaml

The generate-tls-certs initContainer in the backup CronJob will now apply the securityContext set in `tls.securityContext` the same way it does when used as an initContainer for the StatefulSet.  
Backup CronJob can successfully deploy to systems using restricted PSS
None
- fixes #33802

[bitnami/mongodb] generate-tls-certs init container should respect tls securityContext

---

bitnami/harbor/CHANGELOG.md
bitnami/harbor/Chart.yaml
bitnami/harbor/templates/exporter/exporter-dpl.yaml

This PR amends the ConfigMap & Secret references used on Harbor exporter to load env. variables.
Address bug introduced at https://github.com/bitnami/charts/commit/fd3d9a6bfeb495dc46e17ac29923646c51c67ca6#diff-647397203d5eb5fb06c525555d02e53926a7cd8d0e9adadc05228e9f290be6a9R132-R140
None
- fixes #34099
N/A

[bitnami/harbor] bugfix: amend ConfigMap & Secret references

---

bitnami/schema-registry/CHANGELOG.md
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/values.yaml

Duplicate @param comments caused certain parameters to appear twice in the generated README.md, leading to visual clutter and confusion.
This change removes those redundant comments to improve documentation clarity.

[bitnami/schema-registry] Remove duplicate @param entries from chart

---

bitnami/thanos/CHANGELOG.md
bitnami/thanos/Chart.yaml
bitnami/thanos/README.md
bitnami/thanos/values.yaml

This PR disable MinIO Console by default given it's not required when using MinIO as a storage backend for the application.
Only deploy required components by default, reducing resource consumption and improving security by not exposing the MinIO Console.
None
None
N/A

[bitnami/thanos] Disable MinIO Console

---

bitnami/dremio/CHANGELOG.md
bitnami/dremio/Chart.yaml
bitnami/dremio/README.md
bitnami/dremio/values.yaml

This PR disable MinIO Console by default given it's not required when using MinIO as a storage backend for the application.
Only deploy required components by default, reducing resource consumption and improving security by not exposing the MinIO Console.
None
None
N/A

[bitnami/dremio] Disable MinIO Console

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md
bitnami/mastodon/values.yaml

This PR disable MinIO Console by default given it's not required when using MinIO as a storage backend for the application.
Only deploy required components by default, reducing resource consumption and improving security by not exposing the MinIO Console.
None
None
N/A

[bitnami/mastodon] Disable MinIO Console

---

bitnami/postgresql/README.md

Update the values paths for some of the keys in the documentation. It should be `passwordUpdateJob` not `passwordUpdate.job`. There was also a comma where there should have been a period.
Correct documentation
None
None
None

[bitnami/postgresql] Fix incorrect value paths in password update job documentation

---

bitnami/grafana-alloy/CHANGELOG.md
bitnami/grafana-alloy/Chart.yaml
bitnami/grafana-alloy/README.md
bitnami/grafana-alloy/templates/configmap.yaml
bitnami/grafana-alloy/values.yaml

Avoid creating a ConfigMap for Alloy configuration if one already exists. It also changes the default service type to ClusterIP as it is usual in our charts.
Avoid extra resources to be created
N/A

[bitnami/grafana-alloy] Avoid ConfigMap creation if existing one

---

bitnami/common/CHANGELOG.md
bitnami/common/Chart.yaml
bitnami/common/templates/_capabilities.tpl

This helper shouldn't receive a "context" parameter given it adds no value. As we can see, other similar functions don't receive it either:
```yaml
{{/*
Return the appropriate apiVersion for AdmissionConfiguration.
*/}}
{{- define "common.capabilities.admissionConfiguration.apiVersion" -}}
{{- $kubeVersion := include "common.capabilities.kubeVersion" . -}}
{{- if and (not (empty $kubeVersion)) (semverCompare "<1.25-0" $kubeVersion) -}}
{{- print "apiserver.config.k8s.io/v1beta1" -}}
{{- else -}}
{{- print "apiserver.config.k8s.io/v1" -}}
{{- end -}}
{{- end -}}
{{/*
Return the appropriate apiVersion for PodSecurityConfiguration.
*/}}
{{- define "common.capabilities.podSecurityConfiguration.apiVersion" -}}
{{- $kubeVersion := include "common.capabilities.kubeVersion" . -}}
{{- if and (not …
```

[bitnami/common] bugfix: common.capabilities.vpa.apiVersion context

---

bitnami/victoriametrics/CHANGELOG.md
bitnami/victoriametrics/Chart.lock
bitnami/victoriametrics/Chart.yaml
bitnami/victoriametrics/templates/vmagent/vpa.yaml
bitnami/victoriametrics/templates/vmalert/vpa.yaml
bitnami/victoriametrics/templates/vmauth/vpa.yaml
bitnami/victoriametrics/templates/vminsert/vpa.yaml
bitnami/victoriametrics/templates/vmselect/vpa.yaml
bitnami/victoriametrics/templates/vmstorage/vpa.yaml

Follows up https://github.com/bitnami/charts/pull/34372 ensuring the usage of `common.capabilities.vpa.apiVersion` is properly adapted according to latest standard. 
Simplify usage.
None
None
N/A

[bitnami/victoriametrics] bugfix: common.capabilities.vpa.apiVersion context

---

bitnami/dremio/CHANGELOG.md
bitnami/dremio/Chart.lock
bitnami/dremio/Chart.yaml
bitnami/dremio/templates/coordinator/vpa.yaml
bitnami/dremio/templates/executor/vpa.yaml
bitnami/dremio/templates/master-coordinator/vpa.yaml

Follows up https://github.com/bitnami/charts/pull/34372 ensuring the usage of `common.capabilities.vpa.apiVersion` is properly adapted according to latest standard. 
Simplify usage.
None
None
N/A

[bitnami/dremio] bugfix: common.capabilities.vpa.apiVersion context

---

.github/workflows/ci-pipeline.yml
.github/workflows/retry-failed-releases.yml

Insert the comment in automated PRs with pipeline errors when maximun number of attempts is reached
Avoid the removal of the `auto-merge` label in the first retry. That label is removed once the comment is added.
None
[Several PRs are freezed](https://github.com/bitnami/charts/pulls?q=is%3Apr+is%3Aopen+label%3Areview-required) after the first retry

fix(ci-pipeline): Add comment with errors only when MAX_RUNS_ATTEMPTS is reached

---

bitnami/grafana/CHANGELOG.md
bitnami/grafana/Chart.yaml
bitnami/grafana/templates/deployment.yaml
bitnami/grafana/templates/serviceaccount.yaml

Minimal changes were made to the Grafana subchart involving the rendering of `{{ .Values.datasources.secretName }}` to both the `deployment.yaml` and the `serviceaccount.yaml`. These changes more closely align with the rest of the chart's capabilities involving templated rendering of value file attributes.
This change is backwards compatible while providing a more customized way of setting the DataSource's secret name in the chart. The templated rendering should still keep the functionality of previous implementation, while providing more needed customization.
This change would allow me to deploy a secret name based on some variables in the chart, instead of the current approach, which only accepts a hardcoded non-templated value.
In all honesty, I don't think this causes any drawbacks. …

[bitnami/grafana] Templated Rendering of Grafana Datasource SecretName

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/_helpers.tpl

Configures the right section for the `secret_key` configuration setting depending on Airflow's major version. Addresses the next initialization warning:
```
DeprecationWarning: The secret_key option in [webserver] has been moved to the secret_key option in [api] - the old setting has been used, but please update your config.
```

[bitnami/airflow] Configure correct section for api/web secret_key

---

bitnami/nessie/CHANGELOG.md
bitnami/nessie/Chart.yaml
bitnami/nessie/templates/service-management.yaml
bitnami/nessie/templates/servicemonitor.yaml

Amend labels in `serviceMonitor` object and nessie-management service.
Promethues integration works as expected.
None
- fixes #34110

[bitnami/nessie]fix(serviceMonitor): Amend selector

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.lock
bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/tracking/auth-secret.yaml

Create flask-server-secret-key when upgrading if it does not exists
Allows upgrading from version prior to 2.5.1 
N/A
- fixes #34156
Change [added to auth-secret.yaml template in version 2.5.1](https://github.com/bitnami/charts/commit/955396401facdf2dfc3fb203c0435411cc38004a#diff-5a0a775cec0600396479fd9399f9cf38d755c7141dca468ab8d5f3eea4f69215R22)

[bitnami/mlflow] Create flask-server-secret-key when upgrading

---

bitnami/moodle/CHANGELOG.md
bitnami/moodle/Chart.lock
bitnami/moodle/Chart.yaml
bitnami/moodle/README.md

[bitnami/moodle] Upgrade MariaDB 11.8

---

bitnami/redmine/CHANGELOG.md
bitnami/redmine/Chart.lock
bitnami/redmine/Chart.yaml
bitnami/redmine/README.md

[bitnami/redmine] Upgrade MariaDB 11.8

---

bitnami/drupal/CHANGELOG.md
bitnami/drupal/Chart.lock
bitnami/drupal/Chart.yaml
bitnami/drupal/README.md

[bitnami/drupal] Upgrade MariaDB 11.8

---

bitnami/phpmyadmin/CHANGELOG.md
bitnami/phpmyadmin/Chart.lock
bitnami/phpmyadmin/Chart.yaml
bitnami/phpmyadmin/README.md

[bitnami/phpmyadmin] Upgrade MariaDB 11.8

---

bitnami/seaweedfs/CHANGELOG.md
bitnami/seaweedfs/Chart.lock
bitnami/seaweedfs/Chart.yaml
bitnami/seaweedfs/README.md

[bitnami/seaweedfs] Upgrade MariaDB 11.8

---

bitnami/ejbca/CHANGELOG.md
bitnami/ejbca/Chart.lock
bitnami/ejbca/Chart.yaml
bitnami/ejbca/README.md

[bitnami/ejbca] Upgrade MariaDB 11.8

---

bitnami/valkey/CHANGELOG.md
bitnami/valkey/Chart.yaml
bitnami/valkey/templates/primary/pdb.yaml

Fixes a bug in the Helm template condition that prevents the PodDisruptionBudget (PDB) from being rendered when using the `standalone` architecture.
The condition incorrectly references `.Values.primary.count`, which is not defined in the `values.yaml`. It has been updated to use `.Values.primary.replicaCount`, which is the correct and documented field for specifying the number of primary replicas.
Ensures that the PDB is rendered as expected when `primary.pdb.create` is `true` and `primary.replicaCount > 0`.
If any users were unknowingly relying on `primary.count` (despite it not being documented), their configuration might stop working. However, this is unlikely and would indicate misalignment with the intended values schema.

[bitnami/valkey] Fix key on condition to create PodDisruptionBudget

---

bitnami/keydb/CHANGELOG.md
bitnami/keydb/Chart.yaml
bitnami/keydb/templates/replica/hpa.yaml

Fix capitalization in KeyDB replica HPA template where `kind: Statefulset` incorrectly uses lowercase 's' instead of the correct `kind: StatefulSet` with uppercase 'S'. This causes the HPA controller to fail with the error:
"the HPA controller was unable to get the target's current scale: no matches for kind "Statefulset" in group "apps""
The change is a simple one-character correction to ensure proper capitalization.
- Fixes HPA functionality for KeyDB replicas
- Prevents error messages in cluster logs
- Enables proper autoscaling for KeyDB replica pods
- Improves user experience by ensuring out-of-the-box functionality works as expected
None. This is a straightforward fix that corrects a typo in the resource kind name.
- fixes #XXXX 
The Kubernetes API is case-sensitive for resource …

 [bitnami/keydb] Fix StatefulSet capitalization in replica HPA

---

bitnami/etcd/CHANGELOG.md
bitnami/etcd/Chart.yaml
bitnami/etcd/templates/cronjob-defrag.yaml

Fix the protocol selected in the defragmentation cronjob template.
The cronjob no longer fails when etcd is configured to use https for peer communication but http for client communication.
None.
None.
Currently the template is selecting the client port but the peer protocol.

[bitnami/etcd] Fix protocol selection in defrag job

---

bitnami/kafka/CHANGELOG.md
bitnami/kafka/Chart.yaml
bitnami/kafka/templates/_helpers.tpl

This PR fixes a rendering bug in the Kafka Helm chart's _helpers.tpl where the use of {{- end -}} inside the kafka.extraListeners.containerPorts helper caused Helm to trim all newlines between loop iterations, resulting in invalid YAML under container.ports.
Users of the Kafka Helm chart will be able to configure and use extra listeners.
None
- fixes [34731](https://github.com/bitnami/charts/issues/34731)
**Example of the Bug**
Given this input:
```yaml
listeners:
extraListeners:
- name: sasl_plaintext
containerPort: 9095
- name: ssl
containerPort: 9096
```
The following invalid YAML is rendered:
```yaml
ports:
- name: sasl_plaintext
containerPort: 9095- name: ssl
containerPort: 9096
```
This causes helm to fail with:
Error: YAML parse error on …

[bitnami/kafka] fix: Correct extraListeners rendering to avoid malformed YAML

---

bitnami/deepspeed/CHANGELOG.md
bitnami/deepspeed/Chart.yaml
bitnami/deepspeed/templates/client/client-dep-job.yaml

Replaced "values" with "value" in the call to common.tplvalues.render, as this helper expects a single value (e.g. a list, string, or map) under the key "value", along with a "context", like so:
```
dict "value" .Values.somePath "context" $
```
The previous usage incorrectly passed "values", which is not supported by `common.tplvalues.render`.

[bitnami/deepspeed] Wrong input expected by the helper function

---

bitnami/kuberay/CHANGELOG.md
bitnami/kuberay/Chart.yaml
bitnami/kuberay/README.md
bitnami/kuberay/values.yaml

Update `operator.metrics.serviceMonitor.honorLabels` from `false` to `true`
To keep in sync with upstream's defaults
None
- fixes #34792

[bitnami/kuberay]  Update `operator.metrics.serviceMonitor.honorLabels` to keep in sync with upstream chart

---

bitnami/nginx/CHANGELOG.md
bitnami/nginx/Chart.yaml
bitnami/nginx/templates/prometheusrules.yaml

- fix the syntax of the prometheusRules template
- chart fixed
- helm template error 
```bash
Error: YAML parse error on nginx/templates/prometheusrules.yaml: error converting YAML to JSON: yaml: line 18: could not find expected ':'
helm.go:92: 2025-07-04 14:38:28.307659 +0200 CEST m=+0.169137667 [debug] error converting YAML to JSON: yaml: line 18: could not find expected ':'
YAML parse error on nginx/templates/prometheusrules.yaml
```

fix prometheusRules syntax

---

.vib/fluent-bit/vib-verify.json
bitnami/fluent-bit/CHANGELOG.md
bitnami/fluent-bit/Chart.yaml

Removes the duplicated 'healthcheck' test.
Both the service and the containerPort connectivity are tested in the goss tests, so it is unnecessary to also run the "healthcheck" action, saving some extra resources.

[bitnami/fluent-bit] Remove healthcheck VIB test

---

bitnami/gitlab-runner/CHANGELOG.md
bitnami/gitlab-runner/Chart.yaml
bitnami/gitlab-runner/templates/_helpers.tpl
bitnami/gitlab-runner/values.yaml

This PR adds support for custom image pull secrets on runners.
Users can use private container images for runners.
None
None
N/A

[bitnami/gitlab-runner] feat: add support for custom image_pull_secrets

---

.vib/kube-state-metrics/goss/goss.yaml
.vib/kube-state-metrics/runtime-parameters.yaml
.vib/kube-state-metrics/vib-verify.json
bitnami/kube-state-metrics/CHANGELOG.md
bitnami/kube-state-metrics/Chart.yaml

Similar to https://github.com/bitnami/charts/pull/34819, this PR removes the usage of `health-check` on VIB verify given it adds no value. We're already given that:
- `health-check` is very limited we can't configure the sub-path to use as target. Also, it accepts a wide range of status code responses are valid (`>= 200 && <= 499`).
- We're testing the same service endpoint on Goss with more precision.
Simplify tests.
None
None
N/A

[bitnami/kube-state-metrics] ci: VIB verify

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.yaml
bitnami/mlflow/templates/tracking/auth-secret.yaml

MLFlow was failing to deploy due to password's length
```
mlflow.exceptions.MlflowException: Password must be a string longer than 12 characters.
```
After the change, I deployed the solution either using the auto-generated password and a custom password and everything worked as expected 
```diff
diff --git a/bitnami/mlflow/values.yaml b/bitnami/mlflow/values.yaml
index 0508e705c0..f715f06e99 100644
--- a/bitnami/mlflow/values.yaml
+++ b/bitnami/mlflow/values.yaml
@@ -273,7 +273,7 @@ tracking:
auth:
enabled: true
username: user
-    password: ""
+    password: "123456789876"
flaskServerSecretKey: ""
existingSecret: ""
existingSecretUserKey: ""
```
```console
$ k logs mlflow-tracking-XXXXXX
...
[2025-07-16 07:20:05 +0000] [21] [INFO] Starting gunicorn 23.0.0
[2025-07-16 07:20:05 +0000] …
```

[bitnami/charts/issues/35055] Increase lenght of auto-generated password for MLFlow

---

bitnami/nessie/CHANGELOG.md
bitnami/nessie/Chart.lock
bitnami/nessie/Chart.yaml
bitnami/nessie/README.md
bitnami/nessie/templates/_helpers.tpl
bitnami/nessie/templates/configmap.yaml
bitnami/nessie/templates/deployment.yaml

This PR reverts some changes applied in #34376, once the dependencies have been updated. Using specific database env vars is the preferred way.
Use the recommended configuration
N/A (it only would fail with version 0.104.2)
- fixes #

[bitnami/nessie] Recover quarkus specific environment variables

---

bitnami/dremio/CHANGELOG.md
bitnami/dremio/Chart.yaml
bitnami/dremio/templates/coordinator/statefulset.yaml
bitnami/dremio/templates/executor/statefulset.yaml
bitnami/dremio/templates/externals3-secret.yaml
bitnami/dremio/templates/master-coordinator/statefulset.yaml

This PR fixes the conditions used to identify whether resources to interact with S3 (or S3-compatible) storage system are required
Installation works when installing Dremio using `--set dremio.distStorageType=other`
None
None
N/A

[bitnami/dremio] bugfix: conditions to disable S3 storage

---

bitnami/wordpress/CHANGELOG.md
bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/deployment.yaml

Move wordpress password files mountpath from `/opt/bitnami/wordpress/secrets/` to `/secrets`

[bitnami/wordpress] Update passwordFile secret mountPath

---

bitnami/thanos/CHANGELOG.md
bitnami/thanos/Chart.yaml
bitnami/thanos/templates/storegateway/statefulset-sharded.yaml

Fixes [#35002](https://github.com/bitnami/charts/issues/35002). Currently helm chart fails to render using storewaygay sharded and commonLabels
- fixes #35002

[bitnami/thanos] Fix commonLabels on sharded storegateway

---

bitnami/kafka/CHANGELOG.md
bitnami/kafka/Chart.yaml
bitnami/kafka/templates/provisioning/job.yaml

Fix typo in provisioning job to avoid rendering `provisioning.initContainers` twice.
Provisioned initContainers are rendered properly.
None

[bitnami/kafka]fix(provisioning): Fix typo in initContainers

---

bitnami/apisix/CHANGELOG.md
bitnami/apisix/Chart.yaml
bitnami/apisix/templates/_helpers.tpl

Installation was failing when following the documentation
https://github.com/bitnami/charts/issues/35218
Installation works 
```
➜  apisix git:(bitnami/charts/issues/35218) k get pods 
NAME                                 READY   STATUS    RESTARTS   AGE
apisix-data-plane-77986f5f99-mhrb6   1/1     Running   0          2m50s
redis-node-0                         2/2     Running   0          79m
```
None
- fixes https://github.com/bitnami/charts/issues/35218

[bitnami/charts/issues/35218] Share context with apisix.etcd.authEnabled function

---

bitnami/airflow/CHANGELOG.md
bitnami/airflow/Chart.yaml
bitnami/airflow/templates/_helpers.tpl

fix `AIRFLOW__API_AUTH__JWT_SECRET_CMD `env
`AIRFLOW__API_AUTH__JWT_SECRET_CMD` used twice - one time correct and another is wrong
now `AIRFLOW__API_AUTH__JWT_SECRET_CMD` and `AIRFLOW__API_AUTH__JWT_SECRET` will be correct

[bitnami/airflow] fix AIRFLOW__API_AUTH__JWT_SECRET

---

bitnami/mongodb/CHANGELOG.md
bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/statefulset.yaml
bitnami/mongodb/templates/backup/cronjob.yaml
bitnami/mongodb/templates/hidden/statefulset.yaml
bitnami/mongodb/templates/replicaset/statefulset.yaml
bitnami/mongodb/templates/standalone/dep-sts.yaml

This PR replaces the `0o` octal notation with `0###` to unify this chart with the rest of the catalog.

[bitnami/mongodb] Replace `0o` octal notation with `0###`

---

bitnami/redmine/CHANGELOG.md
bitnami/redmine/Chart.lock
bitnami/redmine/Chart.yaml
bitnami/redmine/templates/ingress.yaml

This PR removes references to deprecated helpers that were removed at https://github.com/bitnami/charts/pull/33496
- Fixes https://github.com/bitnami/charts/issues/35394

[bitnami/redmine] Remove references to deprecated helpers

---

bitnami/kube-prometheus/Chart.yaml

At https://github.com/bitnami/charts/pull/35410, the chart version was wrongly lowered from `11.3.0` to `11.2.18` instead of `11.3.1`, which should be the proper version.

[bitnami/kube-prometheus] Bump chart version

---

bitnami/apache/CHANGELOG.md
bitnami/apache/Chart.yaml
bitnami/apache/templates/NOTES.txt
bitnami/apache/templates/_helpers.tpl

This PR removes hardcoded references to the image repository in the chart templates.

[bitnami/apache] Remove hardcoded references to image repository

---

bitnami/postgresql/CHANGELOG.md
bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/_helpers.tpl

This PR removes hardcoded references to the image repository in the chart templates.
- fixes #35552

[bitnami/postgresql] Remove hardcoded references to image repository

---

bitnami/superset/CHANGELOG.md
bitnami/superset/Chart.lock
bitnami/superset/Chart.yaml
bitnami/superset/README.md

Upgrade to Redis subchart 22 (app version 8.2).
Use the latest version of Redis subchart

[bitnami/superset] Upgrade to Redis subchart 22

---

bitnami/mastodon/CHANGELOG.md
bitnami/mastodon/Chart.lock
bitnami/mastodon/Chart.yaml
bitnami/mastodon/README.md

Upgrade to Redis subchart 22 (app version 8.2).
Use the latest version of Redis subchart

[bitnami/mastodon] Upgrade to Redis subchart 22

---

bitnami/appsmith/CHANGELOG.md
bitnami/appsmith/Chart.lock
bitnami/appsmith/Chart.yaml
bitnami/appsmith/README.md

Upgrade to Redis subchart 22 (app version 8.2).
Use the latest version of Redis subchart

[bitnami/appsmith] Upgrade to Redis subchart 22

---

bitnami/tensorflow-resnet/CHANGELOG.md
bitnami/tensorflow-resnet/Chart.lock
bitnami/tensorflow-resnet/Chart.yaml
bitnami/tensorflow-resnet/templates/deployment.yaml

This PR updates the download URL used to download the `resnet-50` model. More info at https://www.kaggle.com/models/tensorflow/resnet-50/tensorFlow2/classification/1?tfhub-redirect=true
The `resnet-50` model can be properly downloaded.
None
None
N/A

[bitnami/tensorflow-resnet] bugfix: update model download url

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/_helpers.tpl

This PR fixes the validation we use to ensure that, when production is enabled, TLS or proxy headers are also set.
Validation works as expected.
None
- fixes #35749
N/A

[bitnami/keycloak] bugfix: validation when production is enabled

---

bitnami/schema-registry/CHANGELOG.md
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/templates/_helpers.tpl
bitnami/schema-registry/templates/statefulset.yaml

This PR resolves an issue where the chart's templating logic incorrectly requires a JKS secret when using SASL_SSL with SCRAM authentication.
In environments like AWS MSK, SCRAM authentication uses TLS for encryption but does not require mutual TLS (mTLS) for client authentication. The original chart logic, however, assumes that any protocol containing "SSL" necessitates JKS files, causing the deployment to fail.
This change modifies the templating to only require a JKS secret when mutual TLS is explicitly enabled, allowing users to configure SASL_SSL for SCRAM-based environments without providing an unnecessary secret.
jks value changed optional condition
- fixes #35731

[bitnami/schema-registry] Fix Schema Registry with SCRAM-SHA-512 and external MSK fails due to mandatory jksSecret

---

bitnami/cassandra/CHANGELOG.md
bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/_helpers.tpl

The Cassandra init script currently uses the .Release.Name value when constructing the headless service DNS name. This causes service name mismatches when a fullnameOverride or a nameOverride is set (such as when deploying Cassandra as a subchart).
The change updates the script to use the correct full release name from include "common.names.fullname" . along with .Release.Namespace and .Values.clusterDomain, ensuring that the generated headless service name matches the actual Kubernetes service name.
1. Prevents random authentication failures when connecting to Cassandra from non-seed (secondary) nodes in multi-replica deployments.
2. Improves reliability and stability of Cassandra connections in Kubernetes clusters.
3. Makes the Helm chart more robust when used as a subchart in larger …

[bitnami/cassandra] Authentication failures when connecting to Cassandra from non-seed (secondary) nodes in multi-replica deployments.  

---

bitnami/redis/CHANGELOG.md
bitnami/redis/Chart.yaml
bitnami/redis/templates/scripts-configmap.yaml

Fix Redis configuration when enabling sentinel and one replica. Issue is described here https://github.com/bitnami/charts/issues/35435.
Chart is now initialized properly 
```
➜  redis git:(bitnami/charts/issues/35435) git diff values.yaml
diff --git a/bitnami/redis/values.yaml b/bitnami/redis/values.yaml
index 017ee3652a..0f6e08ad55 100644
--- a/bitnami/redis/values.yaml
+++ b/bitnami/redis/values.yaml
@@ -682,7 +682,7 @@ replica:
kind: StatefulSet
##
-  replicaCount: 3
+  replicaCount: 1
revisionHistoryLimit: 10
@@ -1172,7 +1172,7 @@ sentinel:
##
-  enabled: false
+  enabled: true
➜  redis git:(bitnami/charts/issues/35435) k logs pod/redis-node-0                                                                                   
Defaulted container "redis" out of: redis, sentinel …
```

[bitnami/charts/issues/35435] Fix Redis configuration when using sentinel and 1 replica

---

bitnami/mlflow/CHANGELOG.md
bitnami/mlflow/Chart.yaml
bitnami/mlflow/README.md
bitnami/mlflow/templates/tracking/deployment.yaml
bitnami/mlflow/values.schema.json
bitnami/mlflow/values.yaml

This change introduces a new feature to configure the /tmp volume as a generic ephemeral volume, which is backed by a PersistentVolumeClaim (PVC).
Better Resource Management: Administrators can now manage the storage for /tmp using standard Kubernetes storage mechanisms. This allows for applying storage quotas, using specific performance tiers via StorageClass, and isolating /tmp storage from the node's ephemeral disk.
Increased Flexibility: Users can customize the storage characteristics for /tmp by defining their own volumeClaimTemplate, specifying properties like storage size (resources.requests.storage), accessModes, and storageClassName.
- fixes #36283

[bitnami/mlflow] Add support for generic ephemeral volume

---

.github/workflows/ci-pipeline.yml

Use bitnami-bot user to commit changes on forked repositories.
We can update the changelog in forked repositories
None
- Pushes done by this workflow on forked repositories are currently failing.

fix(ci-workflow): Allow changelog commits on forked repositories

---

bitnami/keycloak/CHANGELOG.md
bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/ingress-tls-secret.yaml

Correct the indentation of the `metadata.name` field from 1 space to 2 spaces.
- fixes #36244
---
Literally just #36281 but from my personal github to allow edits by maintainers.

[bitnami/keycloak] Fix indentation in ingress TLS secret template

---

.github/actions/get-chart/action.yaml
.github/workflows/ci-update.yml
.github/workflows/ci-verify.yml

Split CI wokflows:
* get-chart action: Common logic to get modifed charts.
* CI update: With access to secrets to commit changes on forkerd repositories with new changelog entries.
* CI verify: Run linter and kubescape.
Keep a minimal verification on charts.
None
NOTE: Current validation is failing because the action is not landed.
Execution examples:
* Everything OK:  https://github.com/bitnami/charts/actions/runs/18215280799/job/51863146741
* Linter KO: https://github.com/bitnami/charts/actions/runs/18215374615/job/51863438022
* Kubescape KO: https://github.com/bitnami/charts/actions/runs/18216050758/job/51865415556

Split CI workflow and add more verification steps
