- bitnami/rabbitmq/Chart.lock
- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/README.md
- bitnami/rabbitmq/templates/ingress.yaml
- bitnami/rabbitmq/values-production.yaml
- bitnami/rabbitmq/values.yaml
**Benefits**
n/a
**Checklist**
> [bitnami/rabbitmq] Adapt ingress to k8s 1.20

- bitnami/nginx/Chart.yaml
- bitnami/nginx/README.md
- bitnami/nginx/templates/health-ingress.yaml
- bitnami/nginx/templates/ingress.yaml
- bitnami/nginx/values.yaml
**Benefits**
n/a
**Checklist**
> [bitnami/nginx] Adapt ingress rules to k8s 1.20

- bitnami/common/Chart.yaml
- bitnami/common/README.md
- bitnami/common/templates/_secrets.tpl
The `_secrets.tpl` template had a wrong reference in it which broke the usage of the template `common.secrets.passwords.manage`. Fixing the reference to be `common.capabilities.supportsHelmVersion` fixed the issue with the template function.
**Benefits**
```json
null
```
- fixes #5033 now properly.
**Checklist** 
> [bitnami/common] fix wrong include reference

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/templates/secrets.yaml
.Values used in non-root scope, so from 8.6.4 you can't install chart due to variable scope problems
Fix scope problems https://github.com/bitnami/charts/pull/4960
https://github.com/bitnami/charts/pull/4960
```
fatal: [node1]: FAILED! => {"changed": false, "command": "/usr/local/bin/helm --namespace=rabbitmq --version=8.7.0 upgrade -i --reset-values --create-namespace -f=/tmp/tmp5s1azey8.yml rabbitmq bitnami/rabbitmq", "msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: UPGRADE FAILED: template: rabbitmq/templates/statefulset.yaml:30:28: executing \"rabbitmq/templates/statefulset.yaml\" at <include (print $.Template.BasePath \"/secrets.yaml\") .>: error calling include: template: …
```
> [bitnami/rabbitmq] Fix critical rabbitmq helm scope bug

- bitnami/mariadb/Chart.yaml
- bitnami/mariadb/templates/extra-list.yaml
- bitnami/mariadb/values-production.yaml
- bitnami/mariadb/values.yaml
add missing extraDeploy to mariadb
**Checklist** 
> [bitnami/mariadb] add missing extraDeploy

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/scripts-configmap.yaml
**Benefits**
Put back ID variable as expected to fix bug from PR #4683 that cause serious Regression when need to Upgrade from the Helm Chart version >= 12.4.0. This is for the fix of #4947 
No
#4947 
**Checklist**
> bitnami/kafka Fix Upgrade regression from PR #4683

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/ci/ingress-wildcard-values.yaml
- bitnami/wordpress/templates/ingress.yaml
- bitnami/wordpress/templates/tls-secrets.yaml
Quote the hostnames to be able to use wildcard domains
- fixes #5079
**Checklist**
> [bitnami/wordpress] Fix issue with wildcard domains

- bitnami/harbor/Chart.yaml
- bitnami/harbor/templates/chartmuseum/chartmuseum-dpl.yaml
- bitnami/harbor/templates/clair/clair-dpl.yaml
- bitnami/harbor/templates/core/core-dpl.yaml
- bitnami/harbor/templates/jobservice/jobservice-dpl.yaml
- bitnami/harbor/templates/nginx/deployment.yaml
- bitnami/harbor/templates/notary/notary-server.yaml
- bitnami/harbor/templates/notary/notary-signer.yaml
- bitnami/harbor/templates/portal/portal-dpl.yaml
- bitnami/harbor/templates/registry/registry-dpl.yaml
Fix indentation issue with extraVolumes templates
- fixes #5054
**Checklist**
> [bitnami/harbor] Fix indentantion when adding extraVolumes

- bitnami/redmine/Chart.yaml
- bitnami/redmine/README.md
- bitnami/redmine/values.yaml
On [this PR](https://github.com/bitnami/charts/pull/4159) (major version) we modified the default pod/container security context so it treats Redmine container as a "non-root" container. This is a common practice on Bitnami containers, **but Redmine hasn't adopted it yet**. Therefore, we should ensure that, by default, the `runAsUser` and `fsGroup` are set to `0` (root user)
**Benefits**
SecurityContext properly configured
None
- fixes https://github.com/bitnami/charts/issues/5038
**Checklist**
> [bitnami/redmine] Fix Pod/Container SecurityContext(s)

- bitnami/fluentd/Chart.yaml
- bitnami/fluentd/templates/ingress.yaml
This change removes the quotes around the $serviceName variable
which currently prevents interpolation.
Remove the quotes surrounding a variable.
**Benefits**
Enables the ability to use the ingress for fluentd-aggregator
#5077 
**Checklist**
> [bitnami/fluentd] 5077: Fluentd typo in ingress template

- bitnami/nginx/Chart.yaml
- bitnami/nginx/README.md
- bitnami/nginx/templates/deployment.yaml
- bitnami/nginx/values.yaml
Add extraInitContainers parameters
**Benefits**
Put python static into nginx.
I could not build nginx image with static because python collect static script requere database, But I don't want to create any shared volumes with python app.
Run `python manage.py collectstatic` in initcontainer of nginx is ideal scenario. 
**Checklist**
> [bitnami/nginx] add extraInitContainers

- bitnami/harbor/Chart.yaml
- bitnami/harbor/templates/chartmuseum/chartmuseum-cm-envvars.yaml
- bitnami/harbor/templates/registry/registry-cm.yaml
This adds a few additional if statements into variables that are normally populated for 99.9% of use cases, we just happen to fall into that 0.1% where this would be very beneficial for us.
**Benefits**
We bring in certain variables -- specifically the AWS REGION and AWS Bucket name through `extraEnvVars` options in the chart.  Currently we have a `ytt` overlay that strips these values out of the config maps and secrets, and would like to work towards deprecating any modifications we make to the Bitnami chart in favor of incorporating those hooks directly into the chart.
In almost every use case these values are already populated, and in the default values file they have default values, so this should not impact any current chart users. …
> [bitnami/harbor] Incorporate more IF statements for absent variables to handle unique use cases.

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/README.md
- bitnami/mongodb/templates/_helpers.tpl
- bitnami/mongodb/templates/psp.yaml
- bitnami/mongodb/templates/role.yaml
- bitnami/mongodb/values.yaml
This PR adds the ability for a user to use PSP with MongoDB chart.
**Benefits**
For users that have PSP enabled in their clusters, they also need to have a PSP resource for Pods that use volumes. Without it, the user will see errors and permission related messages.
The implementation in this PR, is pretty flexible and can allow a user to create PSP resource best for their environment.
By default the PSP creation is disabled. So by default, not changes should be seen by the user. However, if PSP is created, then an understanding of how PSP work would be required.
N/A
Without this PR, using this chart in clusters that have PSP would require manual creation of the PSP and also updating the …
> [bitnami/mongodb] Enable psp for mongodb

- bitnami/common/Chart.yaml
- bitnami/common/templates/_secrets.tpl
Removed the check on the `common.secrets.passwords.manage` helper implemented in #5018 to ensure that the used helm version was below 3.3 (the target was to avoid a version `>3.1` but helm source code made impossible to check anything below 3.3). As the minimum Helm version in our charts has been bumped to Helm 3.1 #5091, this check is no longer necessary.
**Benefits**
Users using versions 3.1.x-3.2.x will have a smoother password management experience.
**Checklist** 
> [bitnami/common] Remove helm version checker from secret helper

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/templates/ingress.yaml
In the ingress route, the target port is hard-coded and change the service port name disables the ingress route.
As an example the following value changes the service port name for the manager port:
```yml
service:
managerPortName: stats
```
Then because of the hard-coded value in the ingress route it will be disabled.
> [bitnami/rabbitmq]: use managerPortName in ingress target port

- bitnami/apache/Chart.yaml
- bitnami/apache/README.md
- bitnami/apache/ci/ct-values.yaml
- bitnami/apache/templates/NOTES.txt
- bitnami/apache/templates/_helpers.tpl
- bitnami/apache/templates/configmap-vhosts.yaml
- bitnami/apache/templates/configmap.yaml
- bitnami/apache/templates/deployment.yaml
- bitnami/apache/templates/ingress.yaml
- bitnami/apache/templates/svc.yaml
- bitnami/apache/values.yaml
This PR adds support to hostAliases to cover cases like https://github.com/bitnami/charts/issues/3427. If accepted, I will work on moving it to Redmine. We also changed some of the helpers so it uses the common functions.
**Benefits**
None known 
**Checklist** 
> [bitnami/apache] Add hostAliases support

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/README.md
- bitnami/postgresql-ha/files/README.md
- bitnami/postgresql-ha/files/conf.d/README.md
- bitnami/postgresql-ha/files/docker-entrypoint-initdb.d/README.md
- bitnami/postgresql-ha/files/pgpool-entrypoint-initdb.d/README.md
- bitnami/postgresql-ha/templates/pgpool/configmap.yaml
- bitnami/postgresql-ha/templates/pgpool/deployment.yaml
- bitnami/postgresql-ha/templates/pgpool/initdb-scripts-configmap.yaml
- bitnami/postgresql-ha/templates/postgresql/configmap.yaml
- bitnami/postgresql-ha/templates/postgresql/extended-configmap.yaml
- bitnami/postgresql-ha/templates/postgresql/initdb-scripts-configmap.yaml
- bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
- bitnami/postgresql-ha/values.yaml
This PR:
- Removes support to load configuration and init scripts from `files/` directory
- Treats `postgresql.configuration` & `postgresql.extendedConf` parameters as plain configuration (instead of doing weird `camelCase` to `sneak_case` transformation). 
**Benefits**
Avoid confusion and have a most intuitive approach for loading custom configuration & scripts.
Users can no longer load their configuration from the `files/` directory.
- fixes https://github.com/bitnami/charts/issues/5075
Adding custom configuration files or initialization scripts by placing them under the "files" directory is very confusing for users since they do not usually …
> [bitnami/postgresql-ha] Remove support to load conf/scripts from 'files/' directory

- bitnami/consul/Chart.yaml
- bitnami/consul/README.md
- bitnami/consul/templates/statefulset.yaml
- bitnami/consul/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/consul] Add hostAliases

- bitnami/kong/Chart.yaml
Wrong url for the png
**Checklist**
> [bitnami/kong] Fix png url

- bitnami/redis/Chart.yaml
- bitnami/redis/README.md
Update redis README.md for the usage of metrics.extraArgs when redis tls is enabled
**Benefits**
User will know how to configure parameters of redis.metrics so that the metrics data can be retrived when redis TLS is enable.d
N/A
The change is an implementation of issue [#4585](https://github.com/bitnami/charts/issues/4585).
The change only applies to the README.md for the bitnami/redis chart.
**Checklist**
> [bitnami/redis] update redis README.md for the usage of metrics.extraArgs when redis tls is enabled

- bitnami/discourse/Chart.yaml
- bitnami/discourse/README.md
- bitnami/discourse/templates/deployment.yaml
- bitnami/discourse/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/discourse] Add hostAliases

- bitnami/dokuwiki/Chart.yaml
- bitnami/dokuwiki/README.md
- bitnami/dokuwiki/templates/deployment.yaml
- bitnami/dokuwiki/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/dokuwiki] Add hostAliases

- bitnami/drupal/Chart.yaml
- bitnami/drupal/README.md
- bitnami/drupal/templates/deployment.yaml
- bitnami/drupal/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/drupal] Add hostAliases

- bitnami/redis/Chart.yaml
- bitnami/redis/README.md
authored-by: Dong, Hujun Hujun.Dong@IGT.com
Description of the change
Update redis README.md for the usage of metrics.extraArgs when redis tls is enabled.
Fix a typo in the readme.md file. 
Benefits
User will know how to configure parameters of redis.metrics so that the metrics data can be retrived when redis TLS is enable.d
Possible drawbacks
Fixes #5228
Applicable issues
The change is an implementation of issue #5228.
Additional information
The change applies to the README.md for the bitnami/redis.
**Checklist** 
> fix a typo in the readme.md file for usage of redis metrics extraarge when enable tls

- bitnami/magento/Chart.yaml
- bitnami/magento/README.md
- bitnami/magento/templates/ingress.yaml
- bitnami/magento/values.yaml
In short, bitnami/magento is not compatible with k8s 1.20. I am simply following @javsalgar template for making the ingress compatible.
This PR updates the common library with the changes from #4859.
Depending on the Kubernetes version it will generate the proper Ingress object
It allows forcing a Kubernetes version so it is compatible with GitOps approaches
**Benefits**
n/a
**Checklist**
> [bitnami/magento] Adapt ingress to k8s 1.20

- bitnami/kiam/Chart.yaml
- bitnami/kiam/README.md
- bitnami/kiam/templates/agent/agent-daemonset.yaml
- bitnami/kiam/templates/server/server-daemonset.yaml
- bitnami/kiam/templates/server/server-deployment.yaml
- bitnami/kiam/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/kiam] Add hostAliases

- bitnami/jenkins/Chart.yaml
- bitnami/jenkins/README.md
- bitnami/jenkins/templates/deployment.yaml
- bitnami/jenkins/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/jenkins] Add hostAliases

- bitnami/grafana/Chart.yaml
- bitnami/grafana/README.md
- bitnami/grafana/templates/deployment.yaml
- bitnami/grafana/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/grafana] Add hostAliases

- bitnami/jasperreports/Chart.yaml
- bitnami/jasperreports/README.md
- bitnami/jasperreports/templates/deployment.yaml
- bitnami/jasperreports/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/jasperreports] Add hostAliases

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/templates/secrets.yaml
Change the helper used to build the secret name
**Benefits**
It will permit us to use larger release names
N/A
N/A
N/A
**Checklist**
> [bitnami/keycloak] fix: error with secret when release name too long

- bitnami/kubernetes-event-exporter/Chart.yaml
- bitnami/kubernetes-event-exporter/README.md
- bitnami/kubernetes-event-exporter/templates/deployment.yaml
- bitnami/kubernetes-event-exporter/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/kubernetes-event-exporter] Add hostAliases

- bitnami/memcached/Chart.yaml
- bitnami/memcached/README.md
- bitnami/memcached/templates/deployment.yaml
- bitnami/memcached/templates/statefulset.yaml
- bitnami/memcached/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/memcached] Add hostAlias

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/README.md
- bitnami/mongodb/templates/arbiter/statefulset.yaml
- bitnami/mongodb/templates/replicaset/statefulset.yaml
- bitnami/mongodb/templates/standalone/dep-sts.yaml
- bitnami/mongodb/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/mongodb] Add hostAliases

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/README.md
- bitnami/grafana-operator/templates/deployment.yaml
- bitnami/grafana-operator/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/grafana-operator] Add hostAliases

- bitnami/mediawiki/Chart.yaml
- bitnami/mediawiki/README.md
- bitnami/mediawiki/templates/deployment.yaml
- bitnami/mediawiki/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/mediawiki] Add hostAliases

- bitnami/opencart/Chart.yaml
- bitnami/opencart/README.md
- bitnami/opencart/templates/deployment.yaml
- bitnami/opencart/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/opencart] Add hostAliases

- bitnami/external-dns/Chart.yaml
- bitnami/external-dns/README.md
- bitnami/external-dns/templates/deployment.yaml
- bitnami/external-dns/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/external-dns] Add hostAliases

- bitnami/nats/Chart.yaml
- bitnami/nats/README.md
- bitnami/nats/templates/deployment.yaml
- bitnami/nats/templates/statefulset.yaml
- bitnami/nats/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/nats] Add hostAlias

- bitnami/orangehrm/Chart.yaml
- bitnami/orangehrm/README.md
- bitnami/orangehrm/templates/deployment.yaml
- bitnami/orangehrm/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/orangehrm] Add hostAliases

- bitnami/owncloud/Chart.yaml
- bitnami/owncloud/README.md
- bitnami/owncloud/templates/deployment.yaml
- bitnami/owncloud/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/owncloud] Add hostAliases

- bitnami/magento/Chart.yaml
- bitnami/magento/README.md
- bitnami/magento/templates/deployment.yaml
- bitnami/magento/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/magento] Add hostAlias

- bitnami/joomla/Chart.yaml
- bitnami/joomla/README.md
- bitnami/joomla/templates/deployment.yaml
- bitnami/joomla/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/joomla] Add hostAliases

- bitnami/kubewatch/Chart.yaml
- bitnami/kubewatch/README.md
- bitnami/kubewatch/templates/deployment.yaml
- bitnami/kubewatch/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/kubewatch] Add hostAliases

- bitnami/phpmyadmin/Chart.yaml
- bitnami/phpmyadmin/README.md
- bitnami/phpmyadmin/templates/deployment.yaml
- bitnami/phpmyadmin/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/phpmyadmin] Add hostAliases

- bitnami/node/README.md
Just fixes the default value of the `extraEnvVars` variable in the readme
**Benefits**
People don't get confused when they read the README instead of the values.yml
N/A
N/A
> [bitnami/node] fix invalid default var value in readme

- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/README.md
- bitnami/redis-cluster/templates/init-cluster.yaml
- bitnami/redis-cluster/templates/redis-statefulset.yaml
- bitnami/redis-cluster/templates/update-cluster.yaml
- bitnami/redis-cluster/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/redis-cluster] Add hostAliases

- bitnami/prestashop/Chart.yaml
- bitnami/prestashop/README.md
- bitnami/prestashop/templates/deployment.yaml
- bitnami/prestashop/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/prestashop] Add hostAliases

- bitnami/testlink/Chart.yaml
- bitnami/testlink/README.md
- bitnami/testlink/templates/deployment.yaml
- bitnami/testlink/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/testink] Add hostAliases

- bitnami/tomcat/Chart.yaml
- bitnami/tomcat/README.md
- bitnami/tomcat/templates/deployment.yaml
- bitnami/tomcat/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/tomcat] Add hostAliases

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/README.md
- bitnami/zookeeper/templates/statefulset.yaml
- bitnami/zookeeper/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/zookeeper] Add hostAliases

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/README.md
- bitnami/wordpress/templates/deployment.yaml
- bitnami/wordpress/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/wordpress] Add hostAliases

- bitnami/wavefront/Chart.yaml
- bitnami/wavefront/README.md
- bitnami/wavefront/templates/collector-daemonset.yaml
- bitnami/wavefront/templates/collector-deployment.yaml
- bitnami/wavefront/templates/proxy-deployment.yaml
- bitnami/wavefront/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/wavefront] Add hostAliases

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/secrets-ca.yaml
Removing a hook that isn't actually required.
**Benefits**
Will allow gitops operations
N/A
N/A
N/A
**Checklist**
> [bitnami/mongodb] fix: remove unnecesary hook

- bitnami/postgresql/Chart.yaml
- bitnami/postgresql/templates/configmap.yaml
- bitnami/postgresql/templates/extended-config-configmap.yaml
- bitnami/postgresql/templates/initialization-configmap.yaml
- bitnami/postgresql/templates/metrics-configmap.yaml
- bitnami/postgresql/templates/metrics-svc.yaml
- bitnami/postgresql/templates/networkpolicy.yaml
- bitnami/postgresql/templates/podsecuritypolicy.yaml
- bitnami/postgresql/templates/role.yaml
- bitnami/postgresql/templates/rolebinding.yaml
- bitnami/postgresql/templates/secrets.yaml
- bitnami/postgresql/templates/serviceaccount.yaml
- bitnami/postgresql/templates/statefulset-readreplicas.yaml
- bitnami/postgresql/templates/statefulset.yaml
- bitnami/postgresql/templates/svc-headless.yaml
- bitnami/postgresql/templates/svc-read.yaml
- bitnami/postgresql/templates/svc.yaml
This PR adds support for explicitly adding a namespace field in resources. when `helm template`  command is run to generate YAML files, it does not add the namespace field which results in resources getting created in the default namespace.
**Benefits**
Add namespace field in manifests generated from `helm template`
None known
> [bitnami/Postgresql] Add explicit namespace field on resources

- bitnami/airflow/Chart.yaml
- bitnami/airflow/README.md
- bitnami/airflow/templates/_helpers.tpl
- bitnami/airflow/templates/config/secret-external-redis.yaml
Add a condition to not use Redis when the executor is `KubernetesExecutor`
**Benefits**
We can use `KubernetesExecutor`
N/A
- fixes #5179
N/A
**Checklist**
> [bitnami/airflow] fix: not to use redis when KubernetesExecutor

- bitnami/nginx/Chart.yaml
- bitnami/nginx/values.yaml
Swap podSecurityContext and containerSecurityContext parameters in values.yaml 
**Benefits**
- fixes #5327 
**Checklist** 
> [bitnami/nginx] Fix swapped securityContext parameters #5327

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/templates/NOTES.txt
- Add condition before checking password must be provided.
**Benefits**
- We can use the existing secrets feature. 
N/A
- fixes a bug introduced by #5189
N/A
**Checklist**
> [bitnami/keycloak] fix: considere existing secret when validating passwords

- bitnami/suitecrm/Chart.yaml
- bitnami/suitecrm/README.md
- bitnami/suitecrm/templates/deployment.yaml
- bitnami/suitecrm/values.yaml
**Benefits**
None known 
**Checklist** 
> [bitnami/suitecrm] Add hostAliases

- bitnami/grafana/Chart.yaml
- bitnami/grafana/templates/deployment.yaml
I believe this was accidentally changed in #4965.
**Checklist**
> [bitnami/grafana] Remove '-envvars' suffix from deployment

- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/templates/metrics-deploy.yaml
In order to slightly improve the performance of the metrics gathering (in the end all the nodes are queries because we set the --es.all flag in elasticserach exporter), we were using the coordinating only nodes as the metrics target for elasticsearch_exporter. It is possible to deploy the chart without coordinating nodes and that was causing issues with the exporter. In this PR we set the master node as fallback in case there are no coordinating nodes available. I considered using a service that points for all the nodes but that caused issues in the past because of incompatibilities with istio (reason why we removed the headless service). 
**Benefits**
Metrics available even though we don't deploy coordinating only nodes.
None known …
> [bitnami/elasticsearch] Change metrics endpoint when no coordinating nodes are used

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/README.md
- bitnami/keycloak/values.yaml
There was a reference to `postgresql.existingSecret` in the README's `postgresql.postgresqlPassword` description but it was not documented nor present in `values.yaml`. 
Also, fixed a reported typo saying `Discourse`.
**Benefits**
- fixes #5237
**Checklist** 
> Keycloak missing postgresql parameters

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/statefulset.yaml
This is needed for the dataplatform Helm Chart where we need to point the externalZookeepers to the Zookeeper subchart, that will not be the Zookeeper included in Kafka.
Link to dataplatform PR: https://github.com/bitnami/charts/pull/5216
**Benefits**
- fixes #
**Checklist** 
> [bitnami/kafka] Add posibility to templatize externalZookeepers

- bitnami/metallb/Chart.yaml
- bitnami/metallb/templates/speaker/secret.yaml
- Remove unnecessary hooks
**Benefits**
- Will allow gitops operations
N/A
N/A
N/A
**Checklist**
> [bitnami/metallb] fix: remove unnecessary hooks

- bitnami/common/Chart.yaml
- bitnami/common/templates/_affinities.tpl
- bitnami/common/templates/_utils.tpl
The change adds quotes around the Kubernetes namespace's name when it is used in a template.
**Benefits**
The added quotes remove any ambiguity about the value's type. This has no effect if the namespace's name is obviously a string (eg. `qwerty`) but is necessary to avoid errors when the name is ambiguous (eg. `12345`).
None that I see.
- fixes #5361
**Checklist**
> [bitnami/common] add quotes around namespace name

- bitnami/grafana/Chart.yaml
- bitnami/grafana/README.md
- bitnami/grafana/templates/deployment.yaml
- bitnami/grafana/values.yaml
Adds priority class name as an option for the deployment.
**Benefits**
Grafana can be proiritzed scheduled or evicted earlier or later compared to other pods in a cluster.
None
None
**Checklist** 
> [bitnami/grafana] Add priority class name

- bitnami/nginx/Chart.yaml
- bitnami/nginx/templates/tls-secrets.yaml
Small changes that fix the scope issue of the Nginx Chart,
where the top level variables `.Values` need to be referenced by `$.Values` 
because it's inside  a loop over the `secrets` list/
> [bitnami/nginx] fixes #4394, implements same fix as #3891

- bitnami/metallb/Chart.yaml
- bitnami/metallb/README.md
- bitnami/metallb/templates/speaker/daemonset.yaml
- bitnami/metallb/values.yaml
Adds support for user specifying initContainers to run before the speaker starts. We have needed this to work around:
https://github.com/metallb/metallb/issues/277
https://github.com/metallb/metallb/issues/277
**Checklist**
> [bitnami/metallb] Add initcontainer support to the speaker

- bitnami/mysql/Chart.yaml
- bitnami/mysql/README.md
- bitnami/mysql/values.yaml
The PR fixes the `*.pdb.enabled` parameters. The templates are using `enabled` but values and readme specify `create`.
https://github.com/bitnami/charts/blob/782282306b2ff68131bb4cbcff7f7f68cf4af0d4/bitnami/mysql/templates/primary/pdb.yaml#L1
https://github.com/bitnami/charts/blob/782282306b2ff68131bb4cbcff7f7f68cf4af0d4/bitnami/mysql/templates/secondary/pdb.yaml#L1
- fixes #5398
**Checklist**
> [bitnami/mysql] Fix *.pdb.enabled parameters

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/_helpers.tpl
- bitnami/kafka/templates/kafka-metrics-deployment.yaml
This change provides two separate helper templates returning `true` if the client connections to Kafka and the inter broker communication connections are encrypted with TLS (i.e. are using tls or mtls).
The new `(include "kafka.client.tlsEncryption" .)` helper template is used in kafka metric exporter deployment to decide if tls command line options should be applied.
**Benefits**
If the kafka release is configured so that both or neither client connections and inter broker connections are using TLS, the metric exporter deployment works as intended.
However, in case when client connections are configured not to use encryption, but broker connections are, the output of `(include "kafka.tlsEncryption" .)` still evaluates to `true`, which results in metric …
> [bitnami/kafka] Separate tls encryption helpers

- bitnami/kube-prometheus/Chart.yaml
- bitnami/kube-prometheus/templates/alertmanager/ingress.yaml
Fix regression introduced by #5338.
Current workaround is to have a definition of `prometheus.ingress.extraTls` in your `values.yaml`.
**Benefits**
Allow extra TLS definition for Alertmanager and minor fix for `extraTls` block.
- fixes #
**Checklist** 
> [bitnami/kube-prometheus] Fix alertmanager ingress extraTls

- bitnami/memcached/Chart.yaml
- bitnami/memcached/README.md
- bitnami/memcached/templates/deployment.yaml
- bitnami/memcached/templates/statefulset.yaml
- bitnami/memcached/values.yaml
Move portName into the values.yaml to let the user override it.
**Benefits**
Compatibility with istio.
- fixes #
**Checklist** 
> [bitnami/memcached] Add support for portName

- bitnami/harbor/Chart.yaml
- bitnami/harbor/templates/core/core-dpl.yaml
Fix what I think is just a typo in the handling of logic when disabling the startupProbe.  Without this fix, even setting the probe to disabled keeps the probe in place
**Benefits**
This allows for the chart to be used on older kubernetes versions, such as those shipped with Openshift 3.x
None
Tested this locally and everything seemed to work as expected
**Checklist** 
> [bitnami/harbor] Fix incorrect logic when disabling startupProbe

- bitnami/thanos/Chart.yaml
- bitnami/thanos/README.md
- bitnami/thanos/templates/receive/configmap.yaml
- bitnami/thanos/templates/receive/service.yaml
- bitnami/thanos/templates/receive/statefulset.yaml
- bitnami/thanos/values.yaml
Thanos Receive fixes
- hashring config now rendered
- `extraFlags` is now being utilized
- missing remote write port was added to the service
**Benefits**
Thanos Receive is now usable
There are still unimplemented/missing parts for Thanos Receive
**Checklist**
> bitnami/thanos - Thanos Receive fixes

- bitnami/rabbitmq/README.md
This PR adds a section to cover cluster recovery from complete shutdown.
**Checklist**
> [bitnami/rabbitmq] Add section to cover cluster recovery

- bitnami/spring-cloud-dataflow/Chart.yaml
- bitnami/spring-cloud-dataflow/templates/skipper/deployment.yaml
This PR fixes skipper `extraVolumes` and `extraVolumeMounts`, which are improperly pointing at the server section.
**Benefits**
Skipper volumes work as expected.
N/A
N/A
**Checklist** 
> [bitnami/spring-cloud-dataflow] Fix skipper volume references

- bitnami/minio/Chart.yaml
- bitnami/minio/templates/NOTES.txt
NOTES.txt erroneously uses `template "minio.name"` instead of `include "common.names.fullname"`, which causes rendering to fail. This PR fixes it.
**Benefits**
Fixes uses of the chart with network policies enabled and external access disabled.
- fixes #
**Checklist** 
> [bitnami/minio] Fix rendering of NOTES.txt

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/query/deployment.yaml
Add a default dns discovery entry in _query_ for _receive_ service 
**Benefits**
_Receive_ In-memory chunks can be queried 
**Checklist** 
> [bitnami/thanos] Add receive to query dns discovery

- bitnami/discourse/Chart.yaml
- bitnami/discourse/README.md
- bitnami/discourse/templates/pvc.yaml
- bitnami/discourse/values.yaml
This change adds a selector to the PCV so that user can use label matching to select the PV
Also updated the accessMode to ReadWriteMany as it being used by discourse and sidekiq  pods.
**Benefits**
User can target the right PV in a kube that has many PVs
If the user does not have a storage provider that supports ReadWriteMany, they will need to create two PVC, one for discourse and one for sidekiq
- fixes #5454
**Checklist** 
- [ X ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ X ] Variables are documented in the README.md
- [ X ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
:warning: Keep in mind that if you want to make changes …
> [bitnami/charts/discourse] Add selector option to pvc

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/templates/NOTES.txt
Notes were using the wrong logic to obtain the secret name to show the password.
- Previous logic:
```console
$ helm install keycloak bitnami/keycloak
NAME: keycloak
LAST DEPLOYED: Fri Feb 12 08:31:09 2021
NAMESPACE: default
STATUS: deployed
REVISION: 1
TEST SUITE: None
NOTES:
** Please be patient while the chart is being deployed **
Keycloak can be accessed through the following DNS name from within your cluster:
keycloak.default.svc.cluster.local (port 80)
To access Keycloak from outside the cluster execute the following commands:
1. Get the Keycloak URL by running these commands:
NOTE: It may take a few minutes for the LoadBalancer IP to be available.
You can watch its status by running 'kubectl get --namespace default svc -w keycloak'
export …
```
> [bitnami/keycloak] Fix password notes reading the secret

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/query/deployment.yaml
- bitnami/thanos/templates/query/tls-server-secret.yaml
Restore TLS client config in a modular way as implemented in PR https://github.com/bitnami/charts/pull/3989 (issue https://github.com/bitnami/charts/issues/3988).
**Benefits**
As explained on #3988 this would enable the usage of multiple ingresses as target stores if they are all under the same CA.
It does not break compatibility as the user is still able to specify all CA, Cert and Key for its TLS client. This only makes it so it is modular enough for the user to only pass the information needed to its use-case.
- fixes #5437
**Checklist*
> [bitnami/thanos] fix query TLS client in a modular way (#5437)

- bitnami/postgresql/Chart.yaml
- bitnami/postgresql/templates/_helpers.tpl
This update aims to fix the issue that `prometheus rules` are unable to get deployed because `{{ template postgresql.name}}` was not defined anywhere in the template. 
**Benefits**
prometheus rules can be deployed 
N/A
- fixes #
https://github.com/bitnami/charts/blob/ac99170769e58207b3d7122361ef736bf96e1812/bitnami/postgresql/templates/prometheusrule.yaml#L20
This is the original reference of the template variable.
**Checklist** 
> [bitnami/postgresql] update prometheus rules name

- bitnami/mysql/Chart.yaml
- bitnami/mysql/README.md
- bitnami/mysql/templates/primary/svc.yaml
- bitnami/mysql/templates/secondary/svc.yaml
- bitnami/mysql/values.yaml
PR adds an option to configure `externalTrafficPolicy` to service type `LoadBalancer` in mysql chart to preserve Client IP. Additionally, while running MySQL on Azure AKS cluster with an internal  LoadBalancer and default `externalTrafficPolicy`: `Cluster`, mysql instance gets health probes from AKS LoadBalancer and drops them as aborted connections, this fills up error logs and reserves unnecessary connections in mysql. Setting `externalTrafficPolicy`: `Local` eliminates this issue. 
**Benefits**
* `externalTrafficPolicy` is configurable to preserve `ClientIP`
* avoid issues with internal load balancers on AKS clusters 
not known 
no 
no 
**Checklist**
> bitnami/mysql: add `externalTrafficPolicy` to service type `LoadBalancer`

- bitnami/kafka/Chart.yaml
- bitnami/kafka/README.md
- bitnami/kafka/templates/scripts-configmap.yaml
- bitnami/kafka/templates/statefulset.yaml
- bitnami/kafka/values.yaml
Flexible JKS configuration. 
In my company we are using cert-manager to automate certificate management. The cert-manager creates a secret, which is completely different, than the one forced by the kafka-helm-chart. 
We need to be able to change the default JKS secret and key mappings.
**Benefits**
This is helpful for anyone who is using already some kind of cert-management or even using a different scheme for creating the certs.
Don't see any
> [bitnami/kafka] Flexible tls config

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/bucketweb/ingress.yaml
- bitnami/thanos/templates/query-frontend/ingress.yaml
- bitnami/thanos/templates/query/ingress-grpc.yaml
- bitnami/thanos/templates/query/ingress.yaml
- bitnami/thanos/templates/receive/ingress.yaml
When using extraHosts on any ingress, you get the error:
```
Error: template: thanos/templates/query-frontend/ingress.yaml:34:96: executing "thanos/templates/query-frontend/ingress.yaml" at <include "common.names.fullname" .>: error calling include: template: thanos/charts/common/templates/_names.tpl:22:14: executing "common.names.fullname" at <.Values.fullnameOverride>: nil pointer evaluating interface {}.fullnameOverride
```
This PR will fix the usage of extraHosts variable on Thanos.
**Checklist** 
> [bitnami/thanos] Fix extraHosts fullnameOverride nil pointer

- bitnami/ghost/Chart.yaml
- bitnami/ghost/README.md
- bitnami/ghost/templates/svc.yaml
- bitnami/ghost/values.yaml
The change adds a possibility to use `loadBalancerSourceRanges` for the service definition.
**Benefits**
So, anyone is able to define `loadBalancerSourceRanges` from `values.yaml`
-
-
-
**Checklist**
> [bitnami/ghost] add "loadBalancerSourceRanges"

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/README.md
- bitnami/rabbitmq/templates/svc-headless.yaml
- bitnami/rabbitmq/values.yaml
Add support for annotations of Headless service for Rabbitmq chart 
**Benefits**
Allows to customise the behaviour of the headless service for Rabbitmq separately from the main service
Nothing known
- fixes #
**Checklist** 
- [X ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
> [bitnami/rabbitmq] Add support for annotations on Rabbitmq Headless service

- bitnami/apache/Chart.yaml
- bitnami/apache/README.md
- bitnami/apache/templates/deployment.yaml
- bitnami/apache/templates/extra-list.yaml
- bitnami/apache/values.yaml
New version of tomcat chart proposes a flexible way to add extra objects in the chart and extra initContainers & sidecars in the pod. In a use case of mine, I need this as well in apache, so I propose to port the same mechanism from tomcat chart to apache.
**Benefits**
Align to latest practices
None
**Checklist** 
> [bitnami/apache] Add extra-list.yaml & extra initContainers & sidecars

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/README.md
- bitnami/zookeeper/templates/extra-list.yaml
- bitnami/zookeeper/values.yaml
New version of tomcat chart proposes a flexible way to add extra objects in the chart. In a use case of mine, I need this as well in zookeeper, so I propose to port the same mechanism from tomcat chart to zookeeper.
There are some refactors we could do in zookeeper to make it align with latest practices in tomcat chart, theses will be for next PRs to come.  
**Benefits**
Align to latest practices
None
**Checklist** 
> [bitnami/zookeeper] Add extra-list.yaml

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
Readiness and Liveness probe were failing because of using `PGPASSWORD=$(<$POSTGRES_PASSWORD_FILE)` in an `sh` command.
This PR changes the Readiness and Liveness from `sh -c` to `bash -ec` which supports the Syntax.
An alternative solution would be using `cat` to set PGPASSWORD:
```
PGPASSWORD=$(cat $POSTGRES_PASSWORD_FILE)
```
For more information please check https://stackoverflow.com/questions/7427262/how-to-read-a-file-into-a-variable-in-shell
Testing outcome:
```sh
#Current command
> kubectl exec -it miruiz-postgresql-postgresql-ha-postgresql-0 -- sh -c 'export POSTGRES_PASSWORD_FILE=/opt/bitnami/postgresql/secrets/postgresql-password; PGPASSWORD=$(<$POSTGRES_PASSWORD_FILE); echo $PGPASSWORD'
```
```bash
#Using sh and cat
> kubectl exec -it …
```
> [bitnami/postgresql-ha] Fix usePasswordFile readiness and liveness Probe

- bitnami/solr/Chart.yaml
- bitnami/solr/values.yaml
`livenessProbe.successThreshold` is limited to 1 and cannot be a different value, or an error will be thrown (i.e. see #5537).
References: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
> `successThreshold`: Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness and startup Probes. Minimum value is 1.
**Benefits**
- fixes #5537
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is …
> [bitnami/solr] Fix successThreshold for exporters

- bitnami/solr/Chart.yaml
- bitnami/solr/templates/statefulset.yaml
The current `StatefulSet` has a duplicate `initContainers` definition.
This results in errors such as:
```sh
create Pod welp-solr-0 in StatefulSet welp-solr failed error: Pod "welp-solr-0" is invalid: spec.initContainers[1].name: Duplicate value: "load-solr-config"
```
**Benefits**
We can add `initContainers` without error
- fixes #
**Checklist** 
> [bitnami/solr] Remove extra initContainers entry

- bitnami/mariadb-galera/Chart.yaml
- bitnami/mariadb-galera/templates/statefulset.yaml
Use root path for metrics health probes.
**Benefits**
Using `/metrics` as a health check incurs load on the DB.
Some error states might not be catched by this endpoint.
- fixes #
We had a case where a DB under high load didn't respond to health checks because they took longer than the 1s timeout. This led to unnecessary restarts of the metrics sidecar.
**Checklist** 
> [bitnami/mariadb-galera] Use root path for metrics health probes

- bitnami/external-dns/Chart.yaml
- bitnami/external-dns/templates/clusterrole.yaml
- bitnami/external-dns/templates/role.yaml
This adds rbac rules in anticipation of gloo support being merged in https://github.com/kubernetes-sigs/external-dns/pull/1693
**Checklist**
> [bitnami/external-dns] add gloo-proxy rbac rules

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/statefulset.yaml
The combination of Zookeeper-Auth with jaas and client/interbroker with mTLS is not possible at this moment 
**Benefits**
Fix the problem from the description
- fixes #5523
**Checklist**
> [bitnami/kafka] Fix Zookeeper with SASL-auth in combination with client/interbroker mTLS

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/receive/statefulset.yaml
**Benefits**
- fixes #5549
**Checklist** 
> [bitnami/thanos] Fixing weird behavior when helm library is used from flux and terraform

- bitnami/external-dns/Chart.yaml
- bitnami/external-dns/templates/clusterrole.yaml
- bitnami/external-dns/templates/role.yaml
Add cluster/role rules for recently added Ambassador support to external-dns. 
**Benefits**
Support for functionality in external-dns
See 
https://github.com/kubernetes-sigs/external-dns/pull/1642
https://github.com/kubernetes-sigs/external-dns/issues/1965
**Checklist**
> [bitnami/external-dns] Ambassador RBAC Rules

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/NOTES.txt
- bitnami/kafka/templates/scripts-configmap.yaml
- bitnami/kafka/templates/statefulset.yaml
- bitnami/kafka/values.yaml
Thanks to [this contribution](https://github.com/bitnami/bitnami-docker-kafka/pull/142), now it's possible to use the environment variable **KAFKA_CFG_TLS_CLIENT_AUTH** to decide whether to set `ssl.client.auth` to `none`, `requested` or `required`.
This setting (`ssl.client.auth`) should only be set to `required` when `mtls` is set at `auth.clientProtocol`. This PR fixes this, and improves the NOTES to provide precise instructions to connect to the cluster using a client depending on the chosen protocol.
**Benefits**
`mTLS` and `tls` authentication  protocols are properly differentiated.
None
- fixes https://github.com/bitnami/charts/issues/3755
**Checklist**
> [bitnami/kafka] Only set ssl.client.auth to required when mTLS is used

- bitnami/common/Chart.yaml
- bitnami/common/README.md
- bitnami/common/templates/_capabilities.tpl
There are two main removed API versions included in Kubernetes v1.22 (see https://kubernetes.io/docs/reference/using-api/deprecation-guide/):
- CRDs: `apiextensions.k8s.io/v1beta1` removed in favor of `apiextensions.k8s.io/v1` (was deprecated in v1.19). **It requires several changes in the manifests.**
- RBAC: `rbac.authorization.k8s.io/v1beta1` removed in favor of `rbac.authorization.k8s.io/v1` (was deprecated in v1.17, see https://pkg.go.dev/k8s.io/api/rbac/v1beta1).
This PR adds new macros to `bitnami/common` to distinguish between versions: 
**Benefits**
Compatibility with different K8s versions.
None
- fixes https://github.com/bitnami/charts/issues/5577 …
> [bitnami/common] Add RBAC/CRD apiVersion support for versions 1.22+

- bitnami/kafka/Chart.yaml
- bitnami/kafka/README.md
- bitnami/kafka/templates/statefulset.yaml
- bitnami/kafka/values.yaml
Fix for `long` value for `log.flush.scheduler.interval.ms`. See #5578
**Checklist**
> [bitnami/kafka] Fix `long` value for `log.flush.scheduler.interval.ms`

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/redis-master-statefulset.yaml
- bitnami/redis/templates/redis-node-statefulset.yaml
mount /tmp as emptyDir. 
Default image (bitnami redis) uses heredoc as seen [here](https://github.com/bitnami/bitnami-docker-redis/blob/master/6.0/debian-10/rootfs/opt/bitnami/scripts/redis/run.sh#L23). 
heredoc creates a temp file in the `/tmp` directory. Thus, `/tmp` has to be exempted implicitly in order to support read only root filesystem.
**Benefits**
Support read only root filesystem. 
- fixes #5600
**Checklist** 
> [bitnami/redis] mount /tmp as emptyDir

- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/templates/poddisruptionbudget.yaml
Adds a condition to the PDB selector to not match the initJob pod.
**Benefits**
PodDisruptionBudget will not match the initJob.
- fixes #5526
Before the change:
```
> kubectl get pods
NAME                                                     READY   STATUS      RESTARTS   AGE
redis-cluster-0                                   1/1     Running     0          53s
redis-cluster-1                                   1/1     Running     0          53s
redis-cluster-2                                   1/1     Running     0          52s
redis-cluster-3                                   1/1     Running     0          52s
redis-cluster-4                                   1/1     Running     0 …
```
> [bitnami/redis-cluster] Fix podDisruptionBudget matching initJob

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/README.md
- bitnami/rabbitmq/templates/statefulset.yaml
- bitnami/rabbitmq/values.yaml
This change enhances the chart to support `Topology Spread Constraints` for assignment pods spread across your cluster among failure-domains such as regions, zones, nodes, and other user-defined topology domains. This can help to achieve high availability as well as efficient resource utilization.
**Benefits**
Users have an optional to use `Topology Spread Constraints`
None
- fixes #
**Checklist** 
> [bitnami/rabbitmq] Added Topology Spread Constraints for pod assignment

- bitnami/harbor/Chart.yaml
- bitnami/harbor/templates/ingress/ingress.yaml
- bitnami/harbor/templates/notary/notary-secret.yaml
When installing the chart relying on self-signed certificates generated by Helm, we find issues like the on below in the Notary Server container:
```
x509: certificate relies on legacy Common Name field, use SANs or temporarily enable Common Name matching with GODEBUG=x509ignoreCN=0
```
Based on the solution proposed at https://github.com/helm/helm/issues/9046, I'm adding alternate domains to avoid this issue.
**Benefits**
No issues with self-signed certificates once these are configured to be trusted.
None
Related to https://github.com/bitnami/charts/issues/5551
It also removes a duplicated TLS section in Ingress rules:
- Before
```console
$ …
```
> [bitnami/harbor] Configure alternate domains for Notary Signer self-signed certificates

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/README.md
- bitnami/grafana-operator/templates/extra-list.yaml
- bitnami/grafana-operator/values.yaml
This PR provides a mechanism to define extra objects to be deployed using `helm install/upgrade` commands.
It also improves the README.md.
**Benefits**
Better UX.
None
N/A
N/A
**Checklist**
> [bitnami/grafana-operator] Provide mechanism to define extra objects

- bitnami/kube-prometheus/Chart.yaml
- bitnami/kube-prometheus/templates/_helpers.tpl
Add possibility to pull images prometheusConfigReload Image without giving specific registry in Values.yaml file but by setting default registry on host. See #5582 
**Benefits**
We can use non default prometheusConfigReload if we omit `.Values.operator.prometheusConfigReloader.image.registry`
We cannot use default behavior for prometheusConfigReload by omitting `.Values.operator.prometheusConfigReloader.image.registry`, we need to omit imageName or imageTag.
- fixes #5584 
None
**Checklist**
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This …
> [bitnami/kube-prometheus] Add possibility to pull images without giving registry name

- bitnami/external-dns/Chart.yaml
- bitnami/external-dns/templates/deployment.yaml
- bitnami/external-dns/templates/service.yaml
- bitnami/external-dns/templates/serviceaccount.yaml
The deployment, service, and serviceaccount resources were missing
metadata.namespace which limited options for installing the chart to a
specific namespace. Now the namespace is specified for all resources and
using the --namespace command with helm install isn't required anymore,
which is helpful when using tools like Argocd or Grafana Tanka.
Specifies namespace to create deployment, service, and serviceaccount resources in
**Benefits**
Chart compatability with argocd is fixed
None
#5017 
Without this change trying to use the chart in Argocd results in missing namespace errors for the deployment, service, and serviceaccount. 
This change has been tested on a 1.16 cluster
**Checklist** …
> [bitnami/external-dns] Allow release to specify namespace for install

- bitnami/mariadb-galera/Chart.yaml
- bitnami/mariadb-galera/templates/statefulset.yaml
* Don't use the chart as pod label
**Benefits**
Otherwise this will cause a pod restart on every release, even if the pod didn't change.
- fixes #
**Checklist** 
> [bitnami/mariadb-galera] Fix pod labels

- bitnami/kube-prometheus/Chart.yaml
- bitnami/kube-prometheus/crds/crd-alertmanager-config.yaml
- bitnami/kube-prometheus/crds/crd-alertmanager.yaml
- bitnami/kube-prometheus/crds/crd-podmonitor.yaml
- bitnami/kube-prometheus/crds/crd-probes.yaml
- bitnami/kube-prometheus/crds/crd-prometheus.yaml
- bitnami/kube-prometheus/crds/crd-prometheusrules.yaml
- bitnami/kube-prometheus/crds/crd-servicemonitor.yaml
- bitnami/kube-prometheus/crds/crd-thanosrulers.yaml
Update crds to prometheus-operator 0.46.0
**Benefits**
Add relabelingConfigs to ProbeTargetStaticConfig (provided by 0.46.0)
None
https://github.com/prometheus-operator/prometheus-operator/releases/tag/v0.46.0
None
**Checklist**
> [bitnami/kube-prometheus] Update crds kube prometheus

- bitnami/postgresql/Chart.yaml
- bitnami/postgresql/templates/secrets.yaml
- bitnami/postgresql/templates/statefulset-readreplicas.yaml
When only using the "postgres" user, the secret gets updated every helm upgrade with a
random string. When using with argocd (and maybe other gitops tools) there are always
changes until you put a dummy value into postgresqlPostgresPassword.
Use the same conditional as in statefulset.yaml:
~~~
{{- if not (eq (include "postgresql.username" .) "postgres")  }}
- name: POSTGRES_POSTGRES_PASSWORD
valueFrom:
secretKeyRef:
name: {{ template "postgresql.secretName" . }}
key: postgresql-postgres-password
{{- end }}
{{- end }}
~~~
**Benefits**
Accomplish idempotency when only using the "postgres" user.
`-`
`-`
`-`
**Checklist** 
:warning: Keep in mind that if you want to make changes to the …
> [bitnami/postgresql] Don't put postgresql-postgres-password in secret when not needed

- bitnami/wildfly/Chart.lock
- bitnami/wildfly/Chart.yaml
- bitnami/wildfly/templates/deployment.yaml
Adds replicaCount value to deployment.yaml template file.
**Benefits**
- fixes #5666
**Checklist** 
> [bitnami/wildfly]: replicaSet missing from deployment.yaml

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/README.md
- bitnami/mongodb/templates/_helpers.tpl
- bitnami/mongodb/templates/hidden/configmap.yml
- bitnami/mongodb/templates/hidden/external-access-svc.yaml
- bitnami/mongodb/templates/hidden/headless-svc.yaml
- bitnami/mongodb/templates/hidden/pdb.yaml
- bitnami/mongodb/templates/hidden/statefulset.yaml
- bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
- bitnami/mongodb/values.yaml
Added Hidden replica node support
**Benefits**
These nodes can be used for several things like - 
- Analytical Queries
- Backup
Backwards compatibile, so no obvious issues beyond the minor increase in complexity
- fixes #4051
**Checklist** 
> [bitnami/mongodb] Added hidden node support

- bitnami/nginx/Chart.yaml
- bitnami/nginx/README.md
- bitnami/nginx/templates/_helpers.tpl
- bitnami/nginx/templates/deployment.yaml
- bitnami/nginx/templates/serviceaccount.yaml
- bitnami/nginx/values.yaml
Add the ability to create and name a service account for the nginx Deployment. This is based on how the `nginx-ingress-controller` configures the service account.
**Benefits**
This is a common feature across a lot of Bitnami charts, which allows setting `serviceAccount.create` and `serviceAccount.name` values to configure creating a new service account for nginx and what the name should be.
None
None
**Checklist** 
> [bitnami/nginx] Add service account to nginx chart

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/README.md
- bitnami/postgresql-ha/values.yaml
Improve explanation about initdbScripts (both in README and comments in the values.yaml), focusing on the different StatefulSets where it can be applied and the supported extensions.
**Checklist**
> [bitnami/postgresql-ha] Improve explanation about initdbScripts

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/hidden/external-access-svc.yaml
- Fix portName variable for hidden node external service
https://github.com/bitnami/charts/pull/5505
**Checklist** 
> [bitnami/mongodb] Fix portname variable refrence

- bitnami/nginx/Chart.yaml
- bitnami/nginx/README.md
- bitnami/nginx/templates/deployment.yaml
- bitnami/nginx/values.yaml
Add ability to set environment variables in the containers that clone static site from git via `cloneStaticSiteFromGit.extraEnvVars`. 
**Benefits**
This is helpful configuring git via environment variables (see https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables). For example, cloning a private git repository via ssh with something like:
```yaml
cloneStaticSiteFromGit:
extraEnvVars:
- name: GIT_SSH_COMMAND
value: ssh -i /path/to/ssh/key
```
None
None
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a …
> [bitnami/nginx] Add support for defining env vars in `cloneStaticSiteFromGit` containers

- bitnami/cassandra/Chart.yaml
- bitnami/cassandra/templates/statefulset.yaml
If you use HOST NETWORK then the Password Seeder wont work. Because the if condition checks the HOSTNAME.
Therefore added a new ENV POD_NAME (metadata.name) instead of HOSTNAME.
**Benefits**
- fixes #
**Checklist** 
> [bitnami/cassandra] Password Seeder fix for HOST Networking

- bitnami/kubewatch/Chart.yaml
- bitnami/kubewatch/templates/clusterrole.yaml
Add `events` to the "" api groups, as well as alphabetically sort the list.
**Benefits**
- fixes https://github.com/bitnami/charts/issues/5410
I'm not aware of any limitations this causes
Testing was done locally: 
```
$ helm dependency build kubewatch
$ helm package kubewatch
$ helm upgrade -i kubewatch ~/sources/charts-1/bitnami/kubewatch-3.1.3.tgz -f ~/tmp/kubewatch.yaml
```
Where the values file was something like this:
```
rbac:
create: true
slack:
enabled: false
image:
registry: 'myregistry.io'
repository: 'kubewatch'
tag: '1.0.0'
pullSecrets:
- myPullSecret
```
I've manually verified in the kubewatch pod logs that the error isn't showing up.
**Checklist**
> [bitnami/kubewatch] Add events to empty api groups

- bitnami/influxdb/Chart.yaml
- bitnami/influxdb/templates/ingress.yaml
```
$ helm template --set-string architecture=high-availability --set-string ingress.enabled=true . --debug -s templates/ingress.yaml
```
The ingress.yaml template is not well indented when rendered with the parameters above.
- fixes #5691
**Checklist**
> [bitnami/influxdb] Fix typo in ingress.yaml

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/README.md
- bitnami/mongodb/templates/_helpers.tpl
- bitnami/mongodb/templates/replicaset/external-access-svc.yaml
- bitnami/mongodb/templates/replicaset/svc.yaml
- bitnami/mongodb/values.yaml
Allow to set externalAccess.service.type to ClusterIP.
**Benefits**
Allow to expose mongodb through reverse proxies (ingress-nginx for example).
- fixes #5683
**Checklist**
> [bitnami/mongodb] Add support for externalAccess.service.type=ClusterIP

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
chmods lock folder
**Benefits**
If the lockfolder has invalid permissions the container cannot start, so this makes the:
```
volumePermissions:
enabled: true
```
Option actually work.
lockfolder is more permissive?
**Checklist** 
- [ x ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ x ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
> bitnami/postgresql-ha - Init container does not chmod lock folder

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/replicaset/statefulset.yaml
- bitnami/mongodb/templates/standalone/dep-sts.yaml
Fix issue #5698 : avoid create duplicate env variable MONGODB_EXTRA_FLAGS when tls.enabled= true **and** extraFlags is set.
**Benefits**
This allows to have correct values in MONGODB_EXTRA_FLAGS and fix chart upgrade removing some values randomly.
N/A
- fixes #5698 
N/A
**Checklist** 
> [bitnami/mongodb] Fix duplicate env variable MONGODB_EXTRA_FLAGS (#5698)

- bitnami/kubewatch/Chart.yaml
- bitnami/kubewatch/templates/clusterrole.yaml
Adding configmaps, nodes and secrets to RBAC "" API group.
**Benefits**
When running with a custom image, we get permission errors, as you can see in the attached issue.
There's still a missing resource (clusterrole), but that's for another api group which I couldn't figure how to add. 
- fixes https://github.com/bitnami/charts/issues/5730
Testing was done using the following values.yaml file: 
```
rbac:
create: true
slack:
enabled: false
image:
registry: 'myregistry.io'
repository: 'kubewatch'
tag: '1.0.0'
pullSecrets:
- myPullSecret
resourcesToWatch:
clusterrole: false  # cluster role
configmap: true     # configmap
deployment: true    # deployment
ds: true            # daemon set
ing: …
```
> [bitnami/kubewatch] Add missing resources to rbac api group

- bitnami/airflow/Chart.yaml
- bitnami/airflow/templates/config/configmap.yaml
Adds the environment variables `AIRFLOW_WEBSERVER_HOST` and `AIRFLOW_WEBSERVER_PORT_NUMBER`, that was preventing the KubernetesExecutor to work.
None known.
- fixes #5569
**Checklist**
> [bitnami/airflow] Fix Kubernetes Executor initContainer

- bitnami/jasperreports/Chart.yaml
- bitnami/jasperreports/templates/_helpers.tpl
Currently the externaldb secret is not referenced correctly:
https://github.com/bitnami/charts/blob/master/bitnami/jasperreports/templates/externaldb-secrets.yaml#L5
```
name: {{ printf "%s-externaldb" (include "common.names.fullname" .) }}
```
but in https://github.com/bitnami/charts/blob/master/bitnami/jasperreports/templates/_helpers.tpl#L80
```
{{- else -}}
{{- printf "%s-%s" .Release.Name "externaldb" -}}
{{- end -}}
```
**Checklist**
> [bitnami/jasperserver] fix secrets name reference if externaldb is used

- bitnami/cassandra/Chart.yaml
- bitnami/cassandra/README.md
- bitnami/cassandra/templates/_helpers.tpl
- bitnami/cassandra/templates/serviceaccount.yaml
- bitnami/cassandra/templates/statefulset.yaml
- bitnami/cassandra/values.yaml
Create a service account by default to be used by the statefulset
**Benefits**
This allows users of the helm chart to create RBAC resources as needed for their cluster by linking them to the service account that is created.
No known limitations
None
Moving forward, any users of this helm chart who may have created RBAC resources for the default service account to run cassandra in their cluster will instead need to link them to the service account that is created by the chart.
**Checklist**
> [bitnami/cassandra] Add default service account

- bitnami/harbor/Chart.lock
- bitnami/harbor/Chart.yaml
- bitnami/harbor/README.md
- bitnami/harbor/templates/NOTES.txt
- bitnami/harbor/templates/core/core-cm-envvars.yaml
- bitnami/harbor/templates/core/core-secret-envvars.yaml
- bitnami/harbor/values.yaml
- Updates the Harbor components to `2.2.0`.
- Adapts Clair component that has been deprecated. We will keep the option to deploy the service and add it manually as an additional interrogation service.
If users are configuring Clair with Habor, they will need to add it again.
**Checklist**
> [bitnami/harbor] Update Harbor 2.2.0 and adapt Clair component

- bitnami/mariadb-galera/Chart.yaml
Why  do you use in keyword percona, but this chart install mariadb software?
> [bitnami/mariadb-galera] Remove percona keyword from mariadb-galera

- bitnami/kafka/Chart.yaml
- bitnami/kafka/README.md
- bitnami/kafka/templates/statefulset.yaml
- bitnami/kafka/values.yaml
The serviceAccountName is always included on the statefulset
**Benefits**
This fixes a bug where users could not specify an existing service account name to use via the following values:
```yaml
serviceAccount:
create: false
name: useThisName
```
No known limitations
No applicable issues
This change brings the kafka chart in line with other bitnami charts with respect to specifying the service account, like the following:
https://github.com/bitnami/charts/blob/master/bitnami/cassandra/templates/statefulset.yaml#L47
https://github.com/bitnami/charts/blob/master/bitnami/zookeeper/templates/statefulset.yaml#L46
**Checklist**
> [bitnami/kafka] Always include serviceAccountName on statefulset

- bitnami/dokuwiki/Chart.yaml
- bitnami/dokuwiki/templates/deployment.yaml
> [bitnami/dokuwiki] fix: align scrape_uri port to apache

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/templates/_helpers.tpl
Use `mariadb.auth.existingSecret` when the user provides it. Right now the chart is ignoring that parameter.
- fixes #5774
**Checklist**
> [bitnami/wordpress] Use mariadb.auth.existingSecret

- bitnami/etcd/Chart.yaml
- bitnami/etcd/templates/svc.yaml
It seems recent refactor broke it.
**Checklist**
> [bitnami/etcd] Service: Fix clientPortNameOverride and peerPortNameOverride

- bitnami/aspnet-core/Chart.yaml
- bitnami/aspnet-core/README.md
- bitnami/aspnet-core/values.yaml
Currently, this Helm Chart is not working because the branch name in the cloned repository has changed from `master` to `main`, see https://github.com/dotnet/AspNetCore.Docs/pull/21737.
This PR updates the default value to `main`.
**Checklist**
> [bitnami/aspnet-core] Change default repo branch from master to main

- bitnami/elasticsearch/Chart.lock
- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/templates/NOTES.txt
- bitnami/elasticsearch/values.yaml
Improve documentation (installation notes and _values.yaml_ comments) regarding custom parameters and kernel settings.
**Benefits**
With the changes in the bitnami/elasticsearch image users should be able to deploy ES in a non-privileged cluster without modifying the kernel settings but using some specific parameters in the ES config file (_elasticsearch.yml_) via the `config:` block present in the _values.yaml_
- fixes #5641
Pending changes in the container image ⚠️ 
**Checklist**
> [bitnami/es] Improve notes and values regarding custom params and kernel settings

- bitnami/solr/Chart.yaml
- bitnami/solr/templates/NOTES.txt
- bitnami/solr/templates/exporter-deployment.yaml
Fixes the default flags passed to the exporter since the one used for Zookeeper was wrong. The `"solr.zookeeper.host"` marco already includes the Zookeeper port, so it's not necessary to append it again. 
**Benefits**
Users can properly expose metrics.
None
- fixes https://github.com/bitnami/charts/issues/5789
**Checklist**
> [bitnami/solr] Fix exporter's flag to connect to Zookeeper

- bitnami/solr/Chart.yaml
- bitnami/solr/templates/NOTES.txt
Fixes the installation instructions to access the metrics exporter.
**Benefits**
Improve UX
None
Reported at https://github.com/bitnami/charts/issues/5789
**Checklist**
> [bitnami/solr] Fix NOTES.txt

- bitnami/kibana/Chart.yaml
- bitnami/kibana/templates/_helpers.tpl
- bitnami/kibana/templates/tests/test-connection.yaml
Fixes the "test-connection" chart test by substituting `minideb` with `bitnami-shell` and `wget` with `curl`
**Benefits**
You can run `helm test RELEASE_NAME` and it works.
None
- fixes https://github.com/bitnami/charts/issues/5801
N/A
**Checklist**
> [bitnami/kibana] Fix helm test

- bitnami/spring-cloud-dataflow/Chart.lock
- bitnami/spring-cloud-dataflow/Chart.yaml
- bitnami/spring-cloud-dataflow/README.md
- bitnami/spring-cloud-dataflow/templates/prometheus-proxy/deployment.yaml
- bitnami/spring-cloud-dataflow/templates/prometheus-proxy/hpa.yaml
- bitnami/spring-cloud-dataflow/templates/prometheus-proxy/pdb.yaml
- bitnami/spring-cloud-dataflow/templates/prometheus-proxy/servicemonitor-metrics.yaml
- bitnami/spring-cloud-dataflow/values.yaml
- Added Prometheus Rsocket Proxy deployment replica count
- Extra labels for ServiceMonitor, in case [Prometheus](https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#prometheusspec) is configured with serviceMonitorSelector
- PDB / HPA for Prometheus Rsocket Proxy
- Fix duplicate namespace in ServiceMonitor
**Benefits**
- Allow the ServiceMonitor to be picked up by Prometheus configured with serviceMonitorSelector
- Allow HA / autoscaling of Prometheus Rsocket Proxy
ServiceMonitor won't be picked up by Prometheus if specific label is required.
Prometheus Rsocket Proxy has no option to be deployed in HA
**Checklist** 
:warning: Keep in mind that if …
> [bitnami/spring-cloud-dataflow] Add more options for Pometheus Proxy

- bitnami/contour/Chart.yaml
- bitnami/contour/README.md
- bitnami/contour/templates/envoy/daemonset.yaml
- bitnami/contour/values.yaml
Adds the feature `envoy.extraArgs`
None known.
- fixes #5799
**Checklist**
> [bitnami/contour] Envoy extraArgs

- bitnami/nginx-ingress-controller/Chart.yaml
- bitnami/nginx-ingress-controller/README.md
- bitnami/nginx-ingress-controller/templates/controller-service.yaml
Allow users to enable or disable http/https with an empty service port, just by leaving the port number blank.
The kubernetes/ingress-nginx already allows this by using two flags enableHttp and enableHttps
https://github.com/kubernetes/ingress-nginx/blob/master/charts/ingress-nginx/values.yaml#L370
**Benefits**
Turn on and off http/https as you like
None
**Checklist** 
> [bitnami/nginx-ingress-controller] Allow users to enable or disable http/https service port

- bitnami/etcd/Chart.yaml
- bitnami/etcd/templates/statefulset.yaml
Signed-off-by: Gorka Maiztegi <gmaiztegi@reviewpro.com>
As the retention is a number, the value must be quoted to put it in the environment variables. 
**Benefits**
Bug fix, see the description.
Haven't seen any.
None.
**Checklist**
> [bitnami/etcd] Quote retention env variable values

- bitnami/spring-cloud-dataflow/Chart.yaml
- bitnami/spring-cloud-dataflow/templates/NOTES.txt
Signed-off-by: Bruno Jost <bruno.jost@bedag.ch>
fixes the bug: [[bitnami/spring-cloud-dataflow] make upgrade possible without rabbitmq deployed](https://github.com/bitnami/charts/issues/5781)
**Benefits**
Allow to do 'helm upgrade', even when there is no rabbitmq deployed.
- fixes #5781 
**Checklist** 
- [X ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
> [bitnami/spring-cloud-dataflow]: rabbitmq passwordErrors only if rabbitmq is used (#5781)

- bitnami/elasticsearch/Chart.lock
- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/values.yaml
Update elasticsearch dependencies in order for it to use the last kibana version.
**Benefits**
Elasticsearch uses the last version of kibana.
- help fixing #5810
**Checklist**
> [bitnami/elasticsearch] Update dependencies (#5810)

- bitnami/harbor/Chart.yaml
- bitnami/harbor/templates/core/core-cm-envvars.yaml
Enhance the proxy cache to support Google Container Registry(GCR), Elastic Container Registry(ECR), Azure Container Registry(Azure), Quay.io.
> [bitnami/harbor] add permitted registry types for harbor 2.2

- bitnami/contour/Chart.yaml
- bitnami/contour/templates/contour/rbac.yaml
The original change in contour happened here: https://github.com/projectcontour/contour/pull/3266/files
I have very limited experience with helm charts, and this is the first time I've heard of RBAC so please review this PR accordingly.
Added  `incgressclasses` to RBAC.
**Benefits**
This chart is broken otherwise.
**Checklist**
> [bitnami/contour] Add ingressclasses to RBAC

- bitnami/minio/Chart.yaml
- bitnami/minio/README.md
- bitnami/minio/templates/NOTES.txt
- bitnami/minio/templates/_helpers.tpl
- bitnami/minio/templates/distributed/statefulset.yaml
- bitnami/minio/templates/gateway/deployment.yaml
- bitnami/minio/templates/secrets.yaml
- bitnami/minio/templates/standalone/deployment.yaml
- bitnami/minio/values.yaml
As described at MinIO Gateway for Azure docs: 
- https://docs.min.io/docs/minio-gateway-for-azure
It's possible to use custom  access/secret keys to provide users access the MinIO UI instead of reusing Azure credentials. This is a safer setup.
**Benefits**
Security
None
N/A
Change suggested by @maxisam 
**Checklist**
> [bitnami/minio] MinIO Gateway for Azure: Use custom access/secret keys instead of reusing Azure credentials

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/README.md
- bitnami/keycloak/templates/configmap-env-vars.yaml
- bitnami/keycloak/templates/secrets.yaml
- bitnami/keycloak/templates/statefulset.yaml
- bitnami/keycloak/values.yaml
Add the possibility to specify an existing secret for the external database configuration.
**Benefits**
The current release of the chart _only_ supports externally setting the password. In my belief using an external database almost always means that creation of database and installing of the keycloak chart are separate workflows. The operator creating the database will store the credentials to the database in one location. Therefore splitting it up like in the current release of the chart is some overhead work.
Complexity of the chart of course. Other than that none, since the chart will keep its backwards compatibility.
#5834 
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps …
> [bitname/keycloak] Support existingSecret for externalDatabase use

- bitnami/nats/Chart.yaml
- bitnami/nats/templates/NOTES.txt
- bitnami/nats/templates/configmap.yaml
- bitnami/nats/values.yaml
Signed-off-by: joancafom <jcarmona@vmware.com>
When the configuration file for nats holds strings starting with numeric values, the server is unable to parse the information and the pod fails to start:
```
$ helm install --set clusterAuth.password=1234test alpha bitnami/nats
$ kubectl get pods
NAME           READY   STATUS   RESTARTS   AGE
alpha-nats-0   0/1     Error    0          2s
$ kubectl logs alpha-nats-0
nats-server: Parse error on line 29: 'Expected a map value terminator "," or a map terminator "}", but got 'e' instead.'
```
This is an error we have faced in the upcoming version of the application `2.2.0`, but does not seem to fail with the current one. However, this is a known issue and the recommended way of storing such values in the …
> [bitnami/nats] fix: Quote string values in config file

- bitnami/influxdb/Chart.yaml
- bitnami/influxdb/README.md
- bitnami/influxdb/templates/service-collectd.yaml
- bitnami/influxdb/values.yaml
Add collectd as an additional service to influxdb chart. If you enable
this service, you must speciy the collectd listener port (default 25826)
along with corresponding configuration in influxdb.conf to enable collectd
listener.
InfluxDb is often used with collected listeners (to allow collectd service to push data to influx). Bitnami chart can be used to specify influxdb.conf with collectd section - however there is no option to specify the udp port (25826) to be exposed.
**Benefits**
InfluxDB can now ingest logs/data from collectd.
Not that I know of
I have only tested this on my local k8 setup with metallb. I have no way to test on any other setup
**Checklist** 
- [X ] Variables are …
> bitnami/influxdb: Adding collectd listener option

- bitnami/memcached/Chart.yaml
- bitnami/memcached/README.md
- bitnami/memcached/templates/_helpers.tpl
- bitnami/memcached/templates/deployment.yaml
- bitnami/memcached/templates/serviceaccount.yaml
- bitnami/memcached/values.yaml
Add service account to memcached charts 
fixes #5811
**Benefits**
This is part of the best practices and is also a compliance thing for many of the certifications such as Fedramp.
- fixes #5811
**dry-run output**
```
NAME: my-memcache
LAST DEPLOYED: Fri Mar 19 10:54:03 2021
NAMESPACE: mahesh
STATUS: pending-install
REVISION: 1
TEST SUITE: None
HOOKS:
MANIFEST:
---
apiVersion: v1
kind: ServiceAccount
metadata:
name: my-memcache-memcached
namespace: mahesh
labels:
app.kubernetes.io/name: memcached
helm.sh/chart: memcached-5.7.0
app.kubernetes.io/instance: my-memcache
---
apiVersion: v1
kind: Service
metadata:
name: my-memcache-memcached
namespace: mahesh
labels: …
```
> [bitnami/memcached] add support for memcached to use its own SA

- bitnami/external-dns/Chart.yaml
- bitnami/external-dns/templates/_helpers.tpl
- bitnami/external-dns/templates/deployment.yaml
- bitnami/external-dns/templates/role.yaml
- bitnami/external-dns/templates/rolebindings.yaml
Sets the `namespace` parameter to the deployed namespace when a cluster role is not created.
**Benefits**
Chart will deploy successfully when `rbac.clusterRole=false` & `sources=[ingress]` which previously required manually setting the namespace parameter also.
None - defaults should be used in all other parameter combinations
- fixes #4446
**Checklist** 
> [bitnami/external-dns] Set namespace variable when not creating cluster role

- bitnami/kafka/README.md
Fixed the problem #5649: extraDeploy doesn't render with example in documentation
I resolved the problem #5649 changing the format of the value of the *.Values.extraDeploy*.  
In particolar I use a Yaml list of multi-line string. So using the `-` as _block sequence entry indicator_ for each K8s resources I want to deploy, followed by `|` to say that the element of the list is a multi-line string.
I also had to correct some `nindent `value reducing them.
**Benefits**
In this way it works for me!
PR encouraged by @marcosbc
> Update README.md - Fixed #5649

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/templates/grafana.yaml
This change allows `global.imagePullSecrets` to be templated into the grafana deployment so when pulling the image from a private registry using `imageRegistry` the pull does not fail due to authentication.
**Benefits**
This allows `global.imagePullSecrets` to work as described in the readme and prevents deployments from failing when using `global.imageRegistry`
- fixes #5762 
**Checklist** 
> [bitnami/grafana-operator] Add image pull secrets to grafana template

- bitnami/minio/Chart.yaml
- bitnami/minio/README.md
- bitnami/minio/templates/servicemonitor.yaml
- bitnami/minio/values.yaml
As explained at the [MinIO docs](https://docs.min.io/docs/how-to-monitor-minio-using-prometheus.html), the recommended endpoint to scrap metrics from is `/minio/v2/metrics/cluster`.
The chart is currently using an equivalent legacy endpoint, that will be deprecated at some point.
**Benefits**
- Flexibility
None
N/A
N/A
**Checklist**
> [bitnami/minio] Use v2 endpoint to scrap metrics and make it customizable

- bitnami/airflow/Chart.yaml
- bitnami/airflow/README.md
- bitnami/airflow/templates/_git_helpers.tpl
- bitnami/airflow/values.yaml
Apply securityContext and add resources on git init & sidecar containers
**Benefits**
Ability to install the chart on constrained k8s cluster (no root images, explicit container resources)
None
None
None
**Checklist** 
- [ X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
> [bitnami/airflow] Apply securityContext & add resources on git containers

- bitnami/solr/Chart.yaml
- bitnami/solr/templates/statefulset.yaml
Fixes a typo in the command of the initcontainer for the statefulset 
Fixes a 
**Benefits**
- fixes #5885
**Checklist** 
- [] Variables are documented in the README.md
> [bitnami/solr] Fix typo in statefulset init container

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/kafka-provisioning.yaml
The `volumes:` section is wrongly indented so it appears as subobject of the container producing the following error when installing the chart with certain parameters:
```
... templates/kafka-provisioning.yaml: error validating "": error validating data: ValidationError(Job.spec.template.spec.containers[0]): unknown field "volumes" in io.k8s.api.core.v1.Container
```
With this PR `volumes:` is placed at the same level as `containers:`
- fixes #5882
**Checklist**
> [bitnami/kafka] Fix provisioning template

- bitnami/kafka/Chart.yaml
- bitnami/kafka/README.md
- bitnami/kafka/templates/kafka-provisioning.yaml
- bitnami/kafka/values.yaml
This PR adds support for custom command/args on provisioning job.
**Benefits**
- Flexibility
None
- fixes https://github.com/bitnami/charts/issues/5835
N/A
**Checklist**
> [bitnami/kafka] Add support for custom command/args on provisioning job

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/templates/grafana.yaml
We introduced a bug at https://github.com/bitnami/charts/pull/5869 since the error below appears when no pull secrets are indicated and `serviceAccount` is empty:
```
08:46:15  Error: Grafana.integreatly.org "t074611-grafana-grafana-operator-grafana" is invalid: spec.serviceAccount: Invalid value: "null": spec.serviceAccount in body must be of type object: "null"
```
**Benefits**
Fix bug
None
N/A
N/A
**Checklist**
> [bitnami/grafana-operator] Fix issue when serviceAccount field is empty

- bitnami/influxdb/Chart.yaml
- bitnami/influxdb/README.md
- bitnami/influxdb/templates/NOTES.txt
- bitnami/influxdb/templates/influxdb/service.yaml
- bitnami/influxdb/values.yaml
Adds `service.sessionAffinity` to the InfluxDb chart
**Benefits**
Adds session stickiness, fixing an issue caused by the Kubernetes service balancing an already connected session to a different pod where the connection doesn't exist.
None known.
- fixes #5866
```
> helm template bitnami/influxdb
...
apiVersion: v1
kind: Service
metadata:
name: influx-influxdb
labels:
app.kubernetes.io/name: influxdb
helm.sh/chart: influxdb-2.2.0
app.kubernetes.io/instance: influx
app.kubernetes.io/component: influxdb
spec:
type: ClusterIP
sessionAffinity: ClientIP
sessionAffinityConfig:
clientIP:
timeoutSeconds: 300
ports:
- port: 8086
targetPort: http
protocol: TCP …
```
> [bitnami/influxdb] Add sessionaffinity capability

- bitnami/wavefront-prometheus-storage-adapter/Chart.lock
- bitnami/wavefront-prometheus-storage-adapter/Chart.yaml
Bump the wavefront dependency. The major bump is because wavefront-collector is moved to scratch, but that container is not used in this chart.
**Benefits**
- fixes #
**Checklist** 
> [bitnami/wavefront-prometheus-storage-adapter] Bump wavefront dep

- bitnami/solr/Chart.yaml
- bitnami/solr/README.md
- bitnami/solr/templates/statefulset.yaml
- bitnami/solr/values.yaml
**Benefits**
Users will be able to configure the Solr podManagementPolicy.
None known.
- fixes #5912
**Checklist**
> [bitnami/solr] Add podManagementPolicy

- bitnami/harbor/Chart.yaml
- bitnami/harbor/templates/ingress/ingress.yaml
- bitnami/harbor/templates/ingress/secret.yaml
Forces the Notary Ingress TLS secret to be stored in a separate secret than the Harbor Ingress TLS secret. When they both use the same secret, you would have to use a wildcard cert for this to work. 
**Benefits**
Allows both Harbor and Notary Ingress endpoints to have their own secrets which allows them to present valid TLS certs to clients.
No known limitations
- fixes #5770 
**Checklist** 
> [bitnami/harbor] Use notary secret for notary ingress

- bitnami/redis-cluster/Chart.lock
- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/README.md
- bitnami/redis-cluster/values.yaml
Update the chart so it uses the new stable Redis version, `6.2`. Added entry to the `Upgrading` section and bumped chart's major version.
**Benefits**
**Checklist** 
> [bitnami/redis-cluster] Update from Redis 6.0 to 6.2 and bump major

- bitnami/grafana-operator/Chart.lock
- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/templates/rbac.yaml
- bitnami/grafana-operator/values.yaml
support for examples like this -> https://github.com/integr8ly/grafana-operator/blob/master/deploy/examples/dashboards/DashboardFromConfigMap.yaml
* Added support for dashboards from configmaps.
**Benefits**
* being able to reference a configmap inside a dashboard resource cluster wide.
**Checklist** 
> [bitnami/grafana-operator] Added support for configmaps in global rbac role.

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/templates/ingress.yaml
This change fixes a bug caused by an incorrect values reference from with a range operation. The `extraHosts` option for the Keycloak ingress is currently broken since it is trying to find `.Values.ingress.servicePort` from within the context of `.Values.ingress.extraHosts`. The solution is to use the global scope `$` at the beginnning of the reference.
**Benefits**
This change fixes broken functionality.
N/A
N/A
**Checklist** 
> [bitnami/keycloak] Fix extraHosts option for ingress

- bitnami/metallb/Chart.yaml
- bitnami/metallb/templates/networkpolicy.yaml
Modified metallb.fullname and metallb.matchLabels variables to use common.names.fullname and 
common.labels.matchLabels respectively.
**Benefits**
Users can enable NetworkPolicy without crashes.
- fixes #5945
**Checklist**
> [bitnami/metallb] Modify fullname and matchLabels variable in Network Policy

- bitnami/rabbitmq/Chart.lock
- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/README.md
- bitnami/rabbitmq/templates/NOTES.txt
- bitnami/rabbitmq/templates/secrets.yaml
- bitnami/rabbitmq/templates/statefulset.yaml
- bitnami/rabbitmq/values.yaml
- Improves the way password and load-definitions.
- Updates the RabbitMQ component.
This PR is based on #4374 by @msvticket. Thanks so much!
- fixes #4222
- might help with #4033 #4351 #3783
- closes #4374
**Checklist** 
> [bitnami/rabbitmq] Improve handling of load-definitions

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/redis-slave-statefulset.yaml
Fixes the indentation on volume mount for the Redis slave volume mount as added in:
https://github.com/bitnami/charts/pull/5897
**Benefits**
Allows for the correct setting of extra volume mounts on the Redis slave Statefulset
N/A
- fixes bug introduced by #5897
N/A
**Checklist** 
> [bitnami/redis] Fixing indentation on redis slave volume mount

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/README.md
- bitnami/zookeeper/templates/statefulset.yaml
Modifies the liveness/readiness probes to include two new test in case that the tls client is enabled. This change includes also two new variables to set up the key and cert pem paths.
**Benefits**
Users can activate the liveness and readiness probes with the tls client enabled without any crashes. Moreover, this change allows them to set up the paths of the key and cert files needed to execute properly the probes.
- fixes [#4811](https://github.com/bitnami/charts/issues/4811)
**Checklist**
> Zookeeper TLS liveness/readiness probes fail when using auto signed certs

- bitnami/metrics-server/Chart.yaml
- bitnami/metrics-server/templates/metrics-api-service.yaml
A Chart user has reported cosmetic inconsistency setting up the metadata.name. Now, the Chart is checking the common.capabilities.kubeVersion to set up different apiVersions but with metatada.name not. Therefore, this patch includes the logic to set up the metadata.name looking the common.capabilities.kubeVersion to choose the best option.
**Benefits**
Fix a cosmetic inconsistency
* fixes #5906 
**Checklist**
> [bitnami/metrics-server] Modify metadata.name checking common.capabilities.kubeVersion

- bitnami/airflow/Chart.yaml
- bitnami/airflow/README.md
- bitnami/airflow/templates/config/configmap.yaml
- bitnami/airflow/templates/worker/statefulset.yaml
- bitnami/airflow/values.yaml
Adds strict toleration and affinity settings for worker pods.
**Benefits**
It will enable the possibility to have strict configurations for worker pods, superseding the global settings.
- fixes #5923
**Checklist** 
> Airflow worker toleration

- bitnami/kafka/Chart.yaml
- bitnami/kafka/README.md
- bitnami/kafka/templates/scripts-configmap.yaml
- bitnami/kafka/templates/statefulset.yaml
- bitnami/kafka/values.yaml
Description of the change
HOST_IP environment variable is dependent from externalAccess.autoDiscovery.enabled This is not right. This is fix for that issue.
Benefits
Fix the issue
Possible drawbacks
Applicable issues
Additional information
Checklist
**Checklist**
> [bitnami/kafka] Usage of Host IPs for external service without autodiscovery

- bitnami/metrics-server/Chart.yaml
- bitnami/metrics-server/templates/serviceaccount.yaml
- bitnami/metrics-server/values.yaml
As mentioned by @mkilchhofer in https://github.com/bitnami/charts/pull/5673#discussion_r604695303.
The conditional would not allow setting `automountServiceAccountToken: false`
**Benefits**
Fixes isssue.
None known.
**Checklist**
> [bitnami/metric-server] Fix issue with automountServiceAccountToken

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/templates/deployment.yaml
This change gives us a support to set up the replicaCount in cases that deployment has a autoscaler enabled. This new implementation helps us to avoid problem during the upgrade.
During the upgrade, the wordpress Chart sets up always the replicaCount and if we do not specific the value by default will be 1. Setting up the value like this during the upgrade, if we have several pods running (because the autoscaler has ordered to create more than one pod), we are going to erase everything except one and then the autoscaler will order again the number of pods needed. 
**Benefits**
Solve unwanted behaviors during the upgrade. 
- fixes #5960
**Checklist**
> [bitnami/wordpress] Respect deployment's strategy in case replicaCount is not defined

- bitnami/thanos/Chart.yaml
- bitnami/thanos/README.md
- bitnami/thanos/templates/query-frontend/ingress.yaml
- bitnami/thanos/values.yaml
This PR adds a `tls` flag (default value: `false`) to the Thanos queryFrontend Ingress config section in order to be able to configure Cert-Manager issued certificates. Cert-Manager needs a TLS section inside the Ingress object but this was not possible until now since only the `.Values.queryFrontend.ingress.secrets` flag caused this section to be created.
The same kind of `tls` flag was already present in the Thanos bucketweb Ingress configuration which has the `.Values.bucketweb.ingress.tls` flag available (compare https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/bucketweb/ingress.yaml#L38 to https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/query-frontend/ingress.yaml#L38). So this PR also unifies the Thanos …
> [bitnami/thanos] Added tls flag for thanos queryFrontend

- bitnami/postgresql/Chart.yaml
- bitnami/postgresql/templates/configmap.yaml
- bitnami/postgresql/templates/extended-config-configmap.yaml
Currently the postgresql chart will fail if postgresqlConfiguration contains strings, since those strings are not contained 
in the configuration file.
```yaml
postgresql:
postgresqlConfiguration:
listenAddresses: '*'
```
-> results in:
listen_addresses: *
This can be fixed with this PR.
I've already tested this change on my cluster.
> [bitnami/postgresql] Fix postgresql.conf generation from values

- bitnami/kafka/Chart.yaml
- bitnami/kafka/README.md
- bitnami/kafka/templates/kafka-metrics-deployment.yaml
- bitnami/kafka/templates/serviceaccount.yaml
- bitnami/kafka/values.yaml
Signed-off-by: Ankit Mehta <ankit.mehta@appian.com>
The change adds serviceAccount already used for Kafka statefulset to Kafka metrics deployment as well.
In addition this change adds `automountServiceAccountToken` to the serviceAccount template. This field has a default value of `true` and that is set on the values.yaml file in this PR. This would allow someone to set it to `false` for their use case.
**Benefits**
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
- Can use serviceAccount for kafka exporter pods
- Can control automountServiceAccountToken for SA
Can't think of Any 😄 
- fixes #5980  …
> [bitnami/kafka] Add serviceAccount to Kafka metrics deployment and add automountServiceAccountToken to SA

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/README.md
- bitnami/zookeeper/templates/serviceaccount.yaml
- bitnami/zookeeper/values.yaml
Signed-off-by: Ankit Mehta <ankit.mehta@appian.com>
This change adds `automountServiceAccountToken` to the serviceAccount template. This field has a default value of true and that is set on the values.yaml file in this PR. This would allow someone to set it to `false` for their use case.
Similar change was done for kafka chart: https://github.com/bitnami/charts/pull/5988
**Benefits**
Allows one to control auto mounting of service account token (which allows pods to talk to the K8s api).
https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#use-the-default-service-account-to-access-the-api-server
https://kubernetes.io/docs/tasks/access-application-cluster/access-cluster/#accessing-the-api-from-a-pod
None …
> [bitnami/zookeepr] Add automountServiceAccountToken field to the serviceaccount

- bitnami/airflow/Chart.yaml
- bitnami/airflow/templates/_git_helpers.tpl
An init container can be used to clone repositories with custom dags/plugins. This init container uses emptyDir volumes to clone the repositories and share them with the main container.
On container restarts, the init container attempts to clone again the repos, even if they're already cloned. This PR changes this to skip that once the repos are already cloned.
**Benefits**
Reliability
None
- fixes https://github.com/bitnami/charts/issues/5995
**Checklist**
> [bitnami/airflow] Avoid cloning dags/plugins repositories on container restarts

- bitnami/etcd/Chart.yaml
- bitnami/etcd/templates/cronjob.yaml
- bitnami/etcd/templates/statefulset.yaml
- bitnami/etcd/values.yaml
We're not properly setting in the **etcd** container logic a way to detect where to find the snapshot file to start the etcd cluster from. This PR attempts to fix that.
**Benefits**
Users can start their etcd cluster from snapshots
None
- fixes https://github.com/bitnami/charts/issues/5989
**Checklist**
> Etcd init from snapshot

- bitnami/nats/Chart.yaml
- bitnami/nats/templates/client-svc.yaml
- bitnami/nats/templates/cluster-svc.yaml
- bitnami/nats/templates/headless-svc.yaml
- bitnami/nats/templates/ingress.yaml
- bitnami/nats/templates/metrics-svc.yaml
- bitnami/nats/templates/monitoring-svc.yaml
- bitnami/nats/templates/servicemonitor.yaml
Alter the port names of each service to make them work with Istio
Add tcp- in front of each port name
**Benefits**
Make automatic routing with Istio and its sidecar for mutual TLS work out of the box .
None that I know of.
- fixes #5999 
**Checklist** 
- [X ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
> [bitnami/nats] Add tcp- to the beginning of each services port name to make them compatible with Istio

- bitnami/etcd/Chart.yaml
- bitnami/etcd/templates/configmap.yaml
Removed the dash in `charts/bitnami/etcd/templates/configmap.yaml` which resulted in an error if `configuration` attribute in `values.yaml` is set.
See issue #6023
- fixes #6023
**Checklist** 
> [bitnami/etcd] Fix configmap template

- bitnami/elasticsearch/Chart.lock
- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/README.md
- bitnami/elasticsearch/values.yaml
Bumps major version of the chart due to major changes in the sub-charts and its components.
- Kibana container configuration logic was migrated to bash.
- Elasticsearch and Kibana container include X-Pack.
- Elasticsearch and Kibana components are now licensed under the Elastic License that is not currently accepted as an Open Source license by the Open Source Initiative (OSI).
**Checklist**
> [bitnami/elasticsearch] Bump major version

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/README.md
- bitnami/wordpress/templates/NOTES.txt
- bitnami/wordpress/templates/_helpers.tpl
- bitnami/wordpress/templates/config-secret.yaml
- bitnami/wordpress/templates/deployment.yaml
- bitnami/wordpress/templates/externaldb-secrets.yaml
- bitnami/wordpress/templates/hpa.yaml
- bitnami/wordpress/templates/ingress.yaml
- bitnami/wordpress/templates/metrics-svc.yaml
- bitnami/wordpress/templates/pdb.yaml
- bitnami/wordpress/templates/postinit-configmap.yaml
- bitnami/wordpress/templates/pvc.yaml
- bitnami/wordpress/templates/secrets.yaml
- bitnami/wordpress/templates/servicemonitor.yaml
- bitnami/wordpress/templates/svc.yaml
- bitnami/wordpress/templates/tls-secrets.yaml
- bitnami/wordpress/values.yaml
This PR adapts WordPress **values.yaml** to follow the format supported by [readmenator](https://github.com/bitnami-labs/readmenator) to automatically generate the READMEs' tables based on the metadata.
It also adds a couple of new parameters:
| Name                                   | Description                                                              | Value              |
| -------------------------------------- | ------------------------------------------------------------------------ | ------------------ |
| `wordpressConfiguration`               | The content for your custom wp-config.php file                           | `""`               |
| `existingWordPressConfigurationSecret` | The name of an …
> [bitnami/wordpress] Values to follow 'readmenator' format

- bitnami/apache/Chart.yaml
- bitnami/apache/templates/svc.yaml
Fix the case of empty service.annotations
```
annotations:
{}
commonAnnotations: ...
```
**Benefits**
- fixes #
**Checklist** 
> [bitnami/apache] fix service annotations

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/templates/_helpers.tpl
This change avoids crashes setting up metric.podAnnotions to null following the helm documentation:
https://helm.sh/docs/chart_template_guide/values_files/
To set up to null maps.
- fixes #6026
**Checklist**
> [bitnami/rabbitmq] Fix crash setting up metric.podAnnotions to null

- bitnami/dataplatform-bp1/Chart.lock
- bitnami/dataplatform-bp1/Chart.yaml
- bitnami/dataplatform-bp1/README.md
- bitnami/dataplatform-bp1/values.schema.json
As per the suggestions from Tanzu Observability team, wavefront should be replaced with Tanzu Observability in the documentation. and Provided link in the kubeapps form layout.
**Benefits**
Replacing Wavefront with Tanzu Observability as the name has changed.
NA
NA
**Checklist** 
> bitnami/dataplatform-bp1 changes to replace Wavefront with Tanzu Observability

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
Add the option to loading environment variables from files in setup.sh and setup-hidden.sh.
Using bitnami docker image for mongodb, you have the option to load environment variables using files 
( https://github.com/bitnami/bitnami-docker-mongodb/blob/master/4.4/debian-10/rootfs/opt/bitnami/scripts/mongodb-env.sh )
**Checklist** 
> [bitnami/mongodb] Add support to load environment variables from files

- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/templates/_helpers.tpl
This change fix the invalid image when enable volume permissions.
**Checklist** 
> [bitnami/elasticsearch] Fix volumePermissions image bug

- bitnami/etcd/Chart.lock
- bitnami/etcd/Chart.yaml
- bitnami/etcd/README.md
- bitnami/etcd/templates/_helpers.tpl
- bitnami/etcd/templates/serviceaccount.yaml
- bitnami/etcd/templates/statefulset.yaml
- bitnami/etcd/values.yaml
* Add support for service account specification
* Supports creation or using existing service account
* Default to the 'default' service account
* Update common dependency for new patch release 1.4.1 -> 1.4.2
* Increment chart version 6.1.5 -> 6.2.0
**Benefits**
* Improves security posture by allowing the association of etcd with a specific service account instead of the default which may have certain permissions associated with it by default that etcd doesn't need
N/A
N/A
N/A
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This …
> [bitnami/etcd] Service account specification

- bitnami/airflow/Chart.yaml
- bitnami/airflow/templates/_git_helpers.tpl
The clone-repositories init container had [[ ]] inside the is_mounted_dir_empty. That caused issues as reported by @echang0929 .
**Benefits**
- fixes https://github.com/bitnami/charts/issues/6068
**Checklist** 
> [bitnami/airflow] Fix incorrect clone-repositories container generation

- bitnami/etcd/Chart.yaml
- bitnami/etcd/templates/cronjob.yaml
The "imagePullSecrets" are missing for the **etcd** cronjob used to snapshot the keyspace.
**Benefits**
Users can use the **etcd** chart with images pulled from private repos.
None
N/A
N/A
**Checklist**
> [bitnami/etcd] Add image pull secrets to cronjob

- bitnami/memcached/Chart.yaml
- bitnami/memcached/README.md
- bitnami/memcached/templates/deployment.yaml
- bitnami/memcached/templates/statefulset.yaml
- bitnami/memcached/values.yaml
This change enhances the chart to support Topology Spread Constraints for assignment pods spread across your cluster among failure-domains such as regions, zones, nodes, and other user-defined topology domains. This can help to achieve high availability as well as efficient resource utilization.
**Benefits**
Users have an optional to use Topology Spread Constraints
None
Copied mostly from https://github.com/bitnami/charts/pull/5599
**Checklist** 
> [bitnami/memcached] Add topology constraints

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/templates/pgpool/service.yaml
Only render `commonAnnotations` if the key is set and not empty. This fixes an issue that would render an invalid manifest when only setting `service.annotations`.
- fixes #6064
**Checklist**
> [bitnami/postgresql-ha] Fix pgpool service annotations

- bitnami/wordpress/Chart.yaml
* HTTPS because 2021
* .org to point the OSS website home
**Benefits**
Better metadata
N/A
N/A
**Checklist** 
> [bitnami/wordpress] Fix upstream project link

- bitnami/nginx/Chart.yaml
- bitnami/nginx/values.yaml
Moves the `sysctls` field from ``containerSecurityContext` to `podSecurityContext` where it belongs.
If you look at the docs the field `sysctls`does not exist in the container but does in the pod security context.
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#podsecuritycontext-v1-core
https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#securitycontext-v1-core
**Benefits**
Fixes an incorrect helm chart.
N/A
N/A
N/A
**Checklist**
> [bitnami/nginx] Move sysctls to podSecurityContext

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/receive/hpa.yaml
Fixes the thanos/receive HPA which currently looks for a `Deployment` instead of a `StatefulSet` set resulting in only one pod when HPA is enabled.
**Benefits**
Thanos Recieve can now be scaled with an HPA properly
more pods = more money 💵 
No existing issue open, the component is fairly new so I may be the first to notice 🤓 
**Checklist**
> [bitnami/thanos] fixes thanos/receive HPA

- bitnami/logstash/Chart.lock
- bitnami/logstash/Chart.yaml
- bitnami/logstash/README.md
- bitnami/logstash/templates/sts.yaml
- bitnami/logstash/values.yaml
Added support to include `configmap / secrets` into environment for use as variables in the pipelines config.
Example: Ref #6111 for an example case.
**Benefits**
One can use Kubernetes secrets and substitute variables in the pipeline configs. 
Example: I may use username and password to authenticate with Elasticsearch within the VPC and provide the same as kubernetes secrets.
I don't think there are any known drawbacks. Do let me know if there's something.
- fixes #6111 
**Checklist** 
> [bitnami/logstash] Added support for kubernetes secrets in environment

- bitnami/nginx-ingress-controller/Chart.yaml
- bitnami/nginx-ingress-controller/templates/controller-daemonset.yaml
- bitnami/nginx-ingress-controller/templates/controller-deployment.yaml
- bitnami/nginx-ingress-controller/templates/default-backend-deployment.yaml
I am trying to deploy bitnami/nginx-ingress-controller on openshift platform and I saw that .Values.podSecurityContext.enabled parameter is omitted. I need disable podSecurityContext in order to prevent openshift problems.
You can run helm chart on OpenShift
> [bitnami/nginx-ingress-controller] - Fixed ignoring "enabled" parameter in .Values.podSecurityContext

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/configmap-scripts.yaml
You can configure the sentinel masterset with `sentinel.masterSet`. This value should be used everywhere. 
- fixes #6145
**Checklist**
> [bitnami/redis] fix hardcoded value for sentinel masterset

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/hidden/statefulset.yaml
Fix issue #5698 : avoid create duplicate env variable MONGODB_EXTRA_FLAGS for hidden nodes when tls.enabled= true and extraFlags is set.
**Benefits**
This allows to have correct values in MONGODB_EXTRA_FLAGS and fix chart upgrade removing some values randomly.
NA
- fixes #5698 
NA
**Checklist** 
> [bitnami/mongodb]Fix duplicate env variable MONGODB_EXTRA_FLAGS for hidden nodes

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/README.md
- bitnami/rabbitmq/values.yaml
The value `metrics.serviceMonitor.release` is no longer used.
**Benefits**
- fixes #6132
**Checklist** 
> [bitnami/rabbitma] delete label release

- bitnami/tomcat/Chart.yaml
- bitnami/tomcat/README.md
- bitnami/tomcat/templates/_pod.tpl
- bitnami/tomcat/templates/deployment.yaml
- bitnami/tomcat/templates/pvc.yaml
- bitnami/tomcat/templates/statefulset.yaml
- bitnami/tomcat/templates/svc-headless.yaml
- bitnami/tomcat/values.yaml
Add the possibility to choose statefulset instead of deployment.
```
persistence.enabled == true || persistence.type == "pvc" => deployment + pvc
persistence.enabled == true && persistence.type == "statefulset" && len(existingClaim) == 0 => statefulset + svc-headless
```
- fixes #
**Checklist** 
> [bitnami/tomcat] deployment, statefulset choice

- bitnami/nats/Chart.yaml
- bitnami/nats/templates/ingress.yaml
Fixed the monitoring ingress endpoint.
**Benefits**
The monitoring page will work properly with nginx ingress.
N/A
- fixes #6166
N/A
**Checklist** 
> [bitnami/nats] Fix monitoring ingress endpoint

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/hidden/statefulset.yaml
Hidden nodes in bitnami/mongodb chart uses its own headless services e.g- **cluster-name-hidden-headless**. Currently it is configured wrong in `MONGODB_ADVERTISED_HOSTNAME`, It is using `"$(MY_POD_NAME).$(K8S_SERVICE_NAME).$(MY_POD_NAMESPACE).svc.{{ .Values.clusterDomain }}"` which is pointing to the headless service for replicaset.
- Added a new env var `K8S_HIDDEN_NODE_SERVICE_NAME`
- Fixed `MONGODB_ADVERTISED_HOSTNAME` for hidden nodes
**Benefits**
Fixes the hidden deployment
N/A
NA
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeap …
> [bitnami/mongodb] fixed advertised hostname for hidden nodes

- bitnami/mysql/Chart.yaml
- bitnami/mysql/values.yaml
fixing plugin_dir option in my.cnf to point to the correct directory
The current plugin_dir option in my.cnf points in the mysql chart point to a path that does not exists in the docker image. This fix should correct that. Currently I'm using this chart with the following env var:
extraFlags: "--plugin-dir=/opt/bitnami/mysql/lib/plugin"
This a fix for a misconfiguration
NA
- fixes #
**Checklist** 
> [bitnami/mysql] fixing plugin_dir option in my.cnf

- bitnami/tomcat/Chart.yaml
- bitnami/tomcat/templates/_pod.tpl
This change solves this problem:
Error: YAML parse error on tomcat/templates/deployment.yaml: error converting YAML to JSON: yaml: line 30: did not find expected key
helm.go:81: [debug] error converting YAML to JSON: yaml: line 30: did not find expected key
**Benefits**
Fix a crash
- fixes #6134
**Checklist**
> [bitnami/tomcat] Fix incorrect identation using imagePullSecrets

- bitnami/nats/Chart.yaml
- bitnami/nats/README.md
- bitnami/nats/templates/configmap.yaml
- bitnami/nats/values.yaml
This change is a minor update of parameters for NATS chart. It is introducing a new parameter `auth.timeout`. This parameter is used in ConfigMap to control how long authentication of the nats client may hang before timeout. 
**Benefits**
Current ConfigMap contains the hardcoded value of 1 second.  With this PR I propose to make it a parameter but keep `1` second as a default value.
Hardcoded value in the current ConfigMap:
```yaml
authorization {
{{- if .Values.auth.user }}
user: {{ .Values.auth.user | quote }}
password: {{ $authPwd | quote }}
{{- else if .Values.auth.token }}
token: {{ .Values.auth.token | quote }}
{{- end }}
timeout:  1 
}
```
After the change:
```yaml
timeout: {{ int .Values.auth.timeout }}
```
New parameter:
```yaml
##
auth:
enabled: …
```
> [bitnami/nats] Adds auth.timeout value to manage client authentication timeout

- bitnami/redis/Chart.yaml
- bitnami/redis/README.md
- bitnami/redis/templates/master/statefulset.yaml
- bitnami/redis/templates/replicas/statefulset.yaml
- bitnami/redis/templates/scripts-configmap.yaml
- bitnami/redis/templates/sentinel/statefulset.yaml
- bitnami/redis/values.yaml
This improves on #5528 by checking and waiting until the failover is finished on both the redis and the sentinel container termination. This completely eliminates a momentary service interruption during rollouts that happens with just #5528 applied.
**Benefits**
This eliminates the few seconds of downtime that happen with v13.0.1 because the redis container terminates before the sentinel prestop hook finishes running (in k8s containers are being stopped concurrently)
I have also replaced a hard-coded masterSet config value in the prestop script with proper config reference. This problem was mentioned by @srueg in this comment: https://github.com/bitnami/charts/pull/5528#discussion_r611600890
This code can make pod deletes (and rollouts) slower by a few seconds. …
> [bitnami/redis] Improve sentinel prestop hook to prevent service interruption

- bitnami/solr/Chart.yaml
- bitnami/solr/README.md
- bitnami/solr/templates/ingress.yaml
- bitnami/solr/templates/tls-secrets.yaml
- bitnami/solr/values.yaml
Signed-off-by: mamiller <mamiller@rosettastone.com>
This allows you to specify the name of an existing TLS secret to use for the Ingress object instead of relying on cert generation to happen by cert-manager.
**Checklist** 
> [bitnami/solr] allow specifying an existing secret for the ingress objects

- bitnami/jupyterhub/Chart.yaml
- bitnami/jupyterhub/values.yaml
When using storage class, for example in IKS, I got the following error:
```
21:53:19          if self.check_token(KeyToken):
21:53:19        File "/opt/bitnami/miniconda/lib/python3.7/site-packages/yaml/scanner.py", line 116, in check_token
21:53:19          self.fetch_more_tokens()
21:53:19        File "/opt/bitnami/miniconda/lib/python3.7/site-packages/yaml/scanner.py", line 223, in fetch_more_tokens
21:53:19          return self.fetch_value()
21:53:19        File "/opt/bitnami/miniconda/lib/python3.7/site-packages/yaml/scanner.py", line 579, in fetch_value
21:53:19          self.get_mark())
21:53:19      yaml.scanner.ScannerError: mapping values are not allowed here
21:53:19        in "/etc/jupyterhub/secret/values.yaml", line 68, column 37
```
This is …
> [bitnami/jupyterhub] Fixes error when using storageclass

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/README.md
- bitnami/rabbitmq/templates/servicemonitor.yaml
- bitnami/rabbitmq/values.yaml
It's allow to specify `podTargetLabels` and `targetLabels` on ServiceMonitor to forward labels on prometheus
**Benefits**
more granularity on metrics
**Checklist** 
> [bitnami/rabbitmq]: allow to specify targetLabels on servicemonitor

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/NOTES.txt
- bitnami/kafka/templates/statefulset.yaml
When you use TLS as authentication protocol and disable host name verification, the chart installation complains with the error below:
```
Error: template: kafka/templates/NOTES.txt:110:11: executing "kafka/templates/NOTES.txt" at <eq $tlsEndpointIdentificationAlgorithm "">: error calling eq: incompatible types for comparison
```
You can reproduce it using these values:
```
auth:
clientProtocol: tls
interBrokerProtocol: tls
tls:
type: jks
existingSecret: kafka-certificates
password: password
endpointIdentificationAlgorithm: ""
tlsEndpointIdentificationAlgorithm: ""
```
This PR fixes this bug.
**Benefits**
Fixes TLS  authentication protocol when disabling host name verification.
None …
> [bitnami/kafka] Allow empty value for 'auth.tlsEndpointIdentificationAlgorithm'

- bitnami/common/Chart.yaml
- bitnami/common/templates/validations/_redis.tpl
Following the latest major of the Redis chart introduced in #6102, we need to update the bitnami/common's validation's helper before updating the charts using Redis as a subchart.
**Benefits**
- Updates common helper and implements backward compatibility to work with any Redis chart regardless of version.
- Unblocks #6079
**Checklist** 
> [bitnami/common] Update Redis validation's helper

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/templates/pgpool/deployment.yaml
Remove the requirement that LDAP be disabled to enable pgpool liveness/readiness/startup probes.
**Benefits**
Currently, to enable pgpool probes with LDAP also enabled, you have to dig into the deployment template and copy the probes to custom* versions in your values YAML. This requires reproducing the values from the deployment and hardcoding parts of it. This increases maintenance requirements for the user.
I'm not sure why the probes were disabled with LDAP originally as I can't find any explanation in the history. I made this a major version change since it has at least the potential to be breaking. If the configured user and password could not authenticate, I believe other configurations in this chart would fail as well. However, …
> [bitnami/postgresql-ha] remove ldap restriction on pgpool probes

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/replicaset/external-access-svc.yaml
If no externalAccess.service.nodePorts is set remove the nodePort: null value;
nodePort: null is useless and prevent argocd to sync. This is arguably a bug/issue with argocd but it's easy to correct on the chart.
**Checklist** 
> [bitnami/mongodb] remove nodePort: null

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/templates/deployment.yaml
**Benefits**
- fixes #6215
**Checklist** 
> [bitnami/wordpress] Fix AllowOverrideNone logic

- bitnami/kubeapps/Chart.lock
- bitnami/kubeapps/Chart.yaml
- bitnami/kubeapps/templates/_helpers.tpl
- bitnami/kubeapps/templates/kubeops-deployment.yaml
- bitnami/kubeapps/values.yaml
Signed-off-by: antgamdia agamez@vmware.com
i) A new param `isKubeappsCluster` is introduced in the values.yaml. This optional param will allow defining the cluster in which Kubeapps is being installed in case it cannot be automatically inferred. For instance, when every cluster uses an APIServiceURL we are not able to know which one is this cluster.
This param is enforced in both Kubeops and the chart template. Therefore, helm will throw an error if the chart does not define properly the cluster in which kubeapps in installed.
ii) Two params are introduced for passing namespaces in the header. The name of the header field and its value are defined by 2 environment variables.
iii) Upgrade the chart dependencies as part of the usual Kubeapps release process. …
> [bitnami/kubeapps] bump chart version to 6.1.1

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/templates/_helpers.tpl
- bitnami/postgresql-ha/templates/pgpool/deployment.yaml
Shorten the hostnames used by pgpool by omitting the namespace and cluster domain.
**Benefits**
It will be possible to use longer release names.
Short hostnames might not be supported by all DNS plugins. However, other charts use short hosts too. For example: e.g. [redis-cluster](https://github.com/bitnami/charts/blob/master/bitnami/redis-cluster/templates/redis-statefulset.yaml#L128).
- fixes #4923
**Checklist**
> [bitnami/postgresql-ha] Shortened pgpool backend hostnames

- bitnami/memcached/Chart.yaml
- bitnami/memcached/README.md
- bitnami/memcached/templates/servicemonitor.yaml
- bitnami/memcached/values.yaml
This PR adds the 'metricRelabelings' and 'relabelings' parameters to the ServiceMonitor resource
**Benefits**
Flexibility
None
N/A
**Checklist**
> [bitnami/memcached] Add 'metricRelabelings' and 'relabelings' parameters

- bitnami/mariadb/Chart.yaml
- bitnami/mariadb/templates/NOTES.txt
NOTES.txt post install command used old `release` label whereas templates use `app.kubernetes.io/instance`, as referred by current Helm best practices.
**Benefits**
Command indicated to the chart user after installation will show expected result, not a blank screen without indications for as long as the user is able to wait.
None came to mind.
Didn't think about looking at issues before, my bad :) Will do next time I promise.
**Checklist** 
- [ X] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
:warning: Keep in mind that if you want to …
> [charts/mariadb] Right release label in NOTES.

- bitnami/external-dns/Chart.yaml
- bitnami/external-dns/templates/_helpers.tpl
ExternalDNS service account name had missing {
**Benefits**
Value set in serviceAccountName should be set correctly
**Checklist**
> [bitnami/external-dns] Fix typo in service name template

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/README.md
- bitnami/wordpress/values.yaml
wordpress default value
tolerations: {} => []
**Benefits**
Fixed warning `coalesce.go:160: warning: skipped value for tolerations: Not a table.`
None
- fixes #6237 
**Checklist** 
> [bitnami/wordpress] Update values.yaml & README.md

- bitnami/kong/Chart.yaml
- bitnami/kong/README.md
- bitnami/kong/templates/service.yaml
- bitnami/kong/values.yaml
This PR adds support to setting clusterIP on the exposed service.
**Benefits**
You can specify your own cluster IP address as part of the Service creation.
As per Kubernetes documentation: The IP address that you choose must be a valid IPv4 or IPv6 address from within the service-cluster-ip-range CIDR range that is configured for the API server. If you try to create a Service with an invalid clusterIP address value, the API server will return a 422 HTTP status code to indicate that there's a problem.
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized …
> [bitnami/kong] Added service.clusterIP option

- bitnami/nginx/Chart.yaml
- bitnami/nginx/README.md
- bitnami/nginx/templates/deployment.yaml
- bitnami/nginx/values.yaml
This PR adds the settings `.Values.cloneStaticSiteFromGit.gitRepoSync.command` and `Values.cloneStaticSiteFromGit.gitClone.command`.
This is especially useful for users using a custom image who would like to run a custom command.
None known.
- fixes #6066
```yaml
> helm template bitnami/nginx --set cloneStaticSiteFromGit.enabled=true,cloneStaticSiteFromGit.repository=my_repo,cloneStaticSiteFromGit.branch=master
...
initContainers:
- name: git-clone-repository
image: docker.io/bitnami/git:2.31.1-debian-10-r31
imagePullPolicy: "IfNotPresent"
command:
- /bin/sh
args:
- -c
- echo 'Hello World'
volumeMounts:
- name: staticsite
mountPath: /app
containers:
- name: git-repo-syncer
image: …
```
> [bitnami/nginx] Add git custom commands

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/README.md
- bitnami/wordpress/templates/_helpers.tpl
- bitnami/wordpress/templates/deployment.yaml
- bitnami/wordpress/templates/externaldb-secrets.yaml
- bitnami/wordpress/templates/httpd-configmap.yaml
- bitnami/wordpress/templates/postinit-configmap.yaml
- bitnami/wordpress/values.yaml
This PR adds support for mounting a custom `httpd.conf` file to configure Apache using a ConfigMap (or directly passing it throw the **values.yaml**)
**Benefits**
Support for more customizations.
None
N/A
N/A
**Checklist**
> [bitnami/wordpress] Add support for custom httpd.conf file

- bitnami/airflow/Chart.yaml
- bitnami/airflow/templates/_git_helpers.tpl
This PR fixes a missing segment of the plugin path. Without the correct path, Airflow cannot find plugins at the default plugin location. 
**Benefits**
Correct plugin path location by git sync.
Previous workarounds to this bug might fail to work.
- fixes #5647 
**Checklist**
> [bitnami/airflow] Fixed Git Sync Plugin Path

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/hidden/statefulset.yaml
TLS certs have wrong entry for hidden node headless service.
```sh
my_hostname=$(hostname)
svc=$(echo -n "$my_hostname" | sed s/-[0-9]*$//)-hidden-headless
```
hostname is having value like -  dev03-mongodb-hidden-0. Above expression  results in `dev03-mongodb-hidden-hidden-headless` which is wrong.
**Benefits**
Fixes Hidden node in TLS enable mode
None
None
**Checklist** 
> [bitnami/mongodb]  Fixed hidden node headless service name in TLS

- bitnami/kong/Chart.yaml
- bitnami/kong/templates/ingress-controller-rbac.yaml
- Add namespace templating for ServiceAccount created by Kong helm chart
**Benefits**
- Avoid diff issues when using `helm template` 
- I can't think of any
**Checklist** 
> [bitnami/kong] Fix kong ServiceAccount missing namespace

- bitnami/kube-prometheus/Chart.yaml
- bitnami/kube-prometheus/README.md
- bitnami/kube-prometheus/templates/prometheus-operator/deployment.yaml
- bitnami/kube-prometheus/values.yaml
The old --config-reloader-{cpu,memory} cmdline options have been
deprecated in favour of --config-reloader-{cpu,memory}-{request,limit}[1]
which allows us to set diffrent values for requests and limits on the
config-reloader sidecar. This change first appeard in version v0.47.0
As such, lets migrate away from the previous variables and options and
define a new 'configReloaderResources' to define these values similar to
the well known 'resources: {}' one.
[1] https://github.com/prometheus-operator/prometheus-operator/commit/bcf61aacda782d6c8ffc79f55ea1def9cfd97933
**Benefits**
- Be able to set distinct values for config-reloader sidecar resources
- Users need to migrate manually to new variables
**Checklist**
> [bitnami/kube-prometheus] Use new cmdline options for config-reloader resources

- bitnami/mediawiki/Chart.yaml
- bitnami/mediawiki/templates/mediawiki-pvc.yaml
This prevents a new PVC from being created when the `persistence.existingClaim` is used.
If an existing claim is used, another PVC will be created. This PVC will either remain unused or be provisioned if a default provisioner acts on it. In either case it will not be used by this chart [due to the custom claim being set](https://github.com/bitnami/charts/blob/master/bitnami/mediawiki/templates/deployment.yaml#L197).
Remove excess PVC object. This was causing my provisioner to act on the PVC and provision storage that would never be used.
**Benefits**
Reduce cost/clutter of unused PVC object.
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in …
> [bitnami/mediawiki] Don't create a PVC when using existing claim

- bitnami/ghost/Chart.yaml
- bitnami/ghost/README.md
- bitnami/ghost/templates/deployment.yaml
- bitnami/ghost/values.yaml
The existing `persistence.path` variable is used when setting volume permissions but hardcoded for the Ghost container. This change allows chart consumers to optionally modify this value.
Further, the current value of `persistence.path`, `/bitnami`, has been corrected to `/bitnami/ghost` as used in the Ghost container.
**Benefits**
Additional flexibility for chart consumers.
N/A
N/A
N/A
**Checklist** 
> [bitnami/ghost] Extracted mountPath for Ghost volume and corrected default value

- bitnami/harbor/Chart.yaml
- bitnami/harbor/templates/registry/registry-cm.yaml
Signed-off-by: David Young <davidy@funkypenguin.co.nz>
1. The official helm chart deprecated the registry config's notification section [during the update to v2.0](https://github.com/goharbor/harbor-helm/commit/4d5f65b8be7aec9e5170542f86779aa0df4172b0#diff-e480417def682cdbdf80291f789c5a323119804d9d47460f256088c989500357)
2. This was an intentional change, since the [notification handler was moved to the API](https://github.com/goharbor/harbor/pull/11085), and is now managed by middleware
3. Since this configuration has not yet been removed from our (Bitnami) charts, error messages like this are being outputted by the registry pod:
```
time="2021-05-11T22:31:28.597548803Z" level=error msg="retryingsink: error writing events: …
```
> [bitnami/harbor] Remove deprecated notifications config from registry

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/replicaset/statefulset.yaml
- bitnami/mongodb/templates/standalone/dep-sts.yaml
This commit is an answer to this comment : https://github.com/bitnami/charts/pull/4937#issuecomment-784374955
The previous version of the readiness probe could be incompatible with older versions of mongodb as db.hello() command was introduced in 4.4.2
For version before 4.4.2, the readiness probe now uses db.isMaster() (which is now deprecated)
**Benefits**
Readiness probe should now work on any version, even oldest ones.
None
https://github.com/bitnami/charts/pull/4937#issuecomment-784374955
-
**Checklist**
> [bitnami/mongodb] Improve readiness probe compatibility 

- bitnami/common/Chart.yaml
- bitnami/common/README.md
- bitnami/common/templates/_images.tpl
Changes the `common.images.pullSecrets` function to render both current context pullSecrets and global imagePullSecrets as templates.
**Benefits**
The user can now specify templated strings as pull secrets. This enables a parent Chart to generate Secrets programmatically and pass the name of the secrets to all other subcharts that use bitnami/common chart.
Changes the signature of a function used by many charts within bitnami repository.
- fixes #6229
**Checklist**
> [bitnami/common] pull secrets rendering

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/values.yaml
Since #6309 was merged the test engine is failing due to permission issues creating the needed folders. This PR fixes the security context changed at that PR in order to avoid the read-only file system, letting the tests engine work properly.
**Benefits**
- fixes #
**Checklist**
> [bitnami/grafana-operator] Fix security context changed at #6309

- bitnami/prestashop/Chart.lock
- bitnami/prestashop/Chart.yaml
- bitnami/prestashop/values.yaml
This merge request changes the `livenessProbe`, `readinessProbe` and `startupProbe` paths from `/login` to `/`
**Benefits**
On installations in other languages, the login path changes to the translation of "login" (such as "connexion" in french). Therefor `/login` becomes a 404 pages and the probes can't validate a ready state. Changing the probe path to `/` ensure the chart supports the most languages
- fixes #6337
**Checklist**
> [bitnami/prestashop] Change probe path to comply to deployments in other languages

- bitnami/common/Chart.yaml
- bitnami/common/templates/_affinities.tpl
Label values _must_ be strings, but if they are not quoted then
boolean/numerical/etc values can be misinterpreted by kubernetes.
eg:
```
values:
- "true"
```
Ensure that values in `matchExpressions` for `nodeAffinity` rules are quoted as strings.
**Benefits**
Value strings that can be misinterpreted as non-string types, eg: `"true"`, will no longer be.
None
#6349 
Nada
**Checklist**
> [bitnami/common] Node affinity values must be quoted.

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/README.md
- bitnami/rabbitmq/templates/certs.yaml
- bitnami/rabbitmq/templates/configuration.yaml
- bitnami/rabbitmq/templates/ingress.yaml
- bitnami/rabbitmq/templates/networkpolicy.yaml
- bitnami/rabbitmq/templates/pdb.yaml
- bitnami/rabbitmq/templates/prometheusrule.yaml
- bitnami/rabbitmq/templates/role.yaml
- bitnami/rabbitmq/templates/rolebinding.yaml
- bitnami/rabbitmq/templates/secrets.yaml
- bitnami/rabbitmq/templates/serviceaccount.yaml
- bitnami/rabbitmq/templates/servicemonitor.yaml
- bitnami/rabbitmq/templates/statefulset.yaml
- bitnami/rabbitmq/templates/svc-headless.yaml
- bitnami/rabbitmq/templates/svc.yaml
- bitnami/rabbitmq/values.yaml
Add commonAnnotations to bitnami/rabbitmq values.yaml that applied to all deployed resources
**Benefits**
Can use bitnami/rabbitmq chart like dependency and use helm hooks to manage deploying order
**Checklist**
> [bitnami/rabbitmq] add commonAnnotations to values.yaml to apply it to all deployed resources

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/receive/ingress.yaml
Put /api/v1/receive at the first of rules.
**Benefits**
When using AWS ALB for ingress, if default rule "/*" has higher order, other rules will never be matched.
N/A
- N/A
**Checklist**
> [bitnami/thanos] Put /api/v1/receive at the first of rules (thanos-receive ingress)

- bitnami/kubeapps/Chart.yaml
- bitnami/kubeapps/templates/frontend/configmap.yaml
- bitnami/kubeapps/templates/frontend/service.yaml
- bitnami/kubeapps/templates/kubeops/deployment.yaml
See #6398 . 
**Benefits**
Can deploy again with pinniped support :)
None that I can see.
- fixes #6398 
I've verified the same change in our local dev chart to deploy kubeapps with pinniped (while investigating https://github.com/kubeapps/kubeapps/issues/2827 )
**Checklist**
> [bitnami/kubeapps] Switch pinnipedProxy refs to new containerPort.

- bitnami/airflow/Chart.yaml
- bitnami/airflow/templates/scheduler/deployment.yaml
- bitnami/airflow/templates/web/deployment.yaml
- bitnami/airflow/templates/worker/statefulset.yaml
Fix typo for custom readinessProbe from `customRedinessProbe` -> `customReadinessProbe`
**Benefits**
Bug fix
NA
NA
NA
**Checklist**
> [bitnami/airflow] fix customReadinessProbe typo

- bitnami/influxdb/Chart.yaml
- bitnami/influxdb/templates/influxdb/cronjob-backup.yaml
Fix wrong container image declaration for influxdb-backup-dummy-container
**Benefits**
Backup of InfluxDB will work fine even with private repositories
-
- fixes #6401
-
> [bitnami/influxdb] Fix Backup (influxdb-backup-dummy-container)

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/templates/NOTES.txt
Updated kubectl command to obtain admin password. The name of the secrets are common.names.fullname and env-vars need not be appended.
Updated the command in notes.txt to fetch admin password from secrets. The name of the secret is appended with env-vars which is not being created and the name of the secret is as same as the release name.
**Benefits**
Better readability and ease of use
**Checklist**
> [bitnami/keycloak] Keycloak updated notes.txt

- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/templates/NOTES.txt
We're not considering in the NOTES.txt that users could be using custom secrets with custom secret keys to manage the Redis credentials. This PR addresses this bug.
**Benefits**
Accurate Installation Notes.
None
- fixes https://github.com/bitnami/charts/issues/6408
None
**Checklist**
> [bitnami/redis-cluster] Fix installation notes when using custom secret with custom key

- bitnami/redis/Chart.lock
- bitnami/redis/Chart.yaml
- bitnami/redis/templates/configmap.yaml
- bitnami/redis/templates/scripts-configmap.yaml
- bitnami/redis/values.yaml
Fixed some issues within the bitnami/redis chart that were preventing it from working as-is on a dualstack (IPv4/IPv6) kubernetes installation.  Specifically, that nodes were failing to start due to improper ip detection.  After nodes properly started, sentinel was not communicating with other sentinel nodes until the bind directive was removed.
**Benefits**
bitnami/redis chart will work out of the box in a dualstack k8s installation
I'm not aware of any drawbacks
- fixes #6329 
**Checklist**
> [bitnami/redis] IPv4/IPv6 dualstack compatibility fixes

- bitnami/redis-cluster/Chart.lock
- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/templates/redis-statefulset.yaml
- bitnami/redis-cluster/templates/update-cluster.yaml
- bitnami/redis-cluster/values.yaml
Allow custom securityContext for pod and container context. 
**Benefits**
Completely allow non privileged containers via values.yaml. 
e.g. 
```yaml
podSecurityContext:
enabled: true
runAsNonRoot: true
fsGroup: 1001
containerSecurityContext:
enabled: true
runAsUser: 1001
allowPrivilegeEscalation: false
```
Increased complexity of the helm chart. 
**Checklist**
> [bitnami/redis-cluster] Redis cluster security context

- bitnami/cert-manager/Chart.yaml
- bitnami/cert-manager/templates/cainjector/deployment.yaml
- bitnami/cert-manager/templates/controller/deployment.yaml
- bitnami/cert-manager/templates/webhook/deployment.yaml
This commit fixes testing crash in some scenarios.
**Benefits**
Allow us to test the charts properly.
**Checklist**
> [bitnami/cert-manager] Set up static names for the webhook, cainjector containers

- bitnami/nginx/values.yaml
Fix default value (in value.yaml) of podSecurityContext.sysctls, it must be an array , not an object.
**Benefits**
- fixes #
**Checklist**
> [bitnami/nginx] fix podSecurityContext.sysctls default value

- bitnami/nginx-ingress-controller/Chart.yaml
- bitnami/nginx-ingress-controller/templates/NOTES.txt
Update the deprecated `apiVersion: extensions/v1beta1` with `apiVersion: networking.k8s.io/v1`.
Since `extensions/v1beta1` will be removed in **v1.22+**
**Benefits**
Provide a better message after the chart is installed.
Removal of the following deprecation warning 
`Warning: extensions/v1beta1 Ingress is deprecated in v1.14+, unavailable in v1.22+; use networking.k8s.io/v1 Ingress`
- fixes #
**Checklist** 
> [bitnami/nginx-ingress-controller] Update NOTES.txt

- bitnami/kube-prometheus/Chart.yaml
- bitnami/kube-prometheus/templates/prometheus-operator/deployment.yaml
Fix indentation of command line arguments for config reloader
Dedent arguments. Otherwise, if resources of config reloader are specified, the rendered manifest is:
```yaml
containers:
- name: prometheus-operator
image: 'docker.io/bitnami/prometheus-operator:0.47.1-debian-10-r0'
args:
- '--kubelet-service=kube-system/prometheus-kube-prometheus-kubelet'
- '--log-format=logfmt'
- '--log-level=info'
- '--localhost=127.0.0.1'
- >-
--prometheus-config-reloader=$(PROMETHEUS_CONFIG_RELOADER) -
--config-reloader-cpu-request=10m -
--config-reloader-memory-request=25Mi -
--config-reloader-cpu-limit=200m -
--config-reloader-memory-limit=25Mi
ports:
```
**Benefits**
It works!
None.
None.
None. …
> [bitnami/kube-prometheus] Fix indentation of command line arguments for config reloader

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/replicaset/statefulset.yaml
- bitnami/mongodb/templates/standalone/dep-sts.yaml
Fix checking for the version in readiness probes
**Benefits**
Avoid issues in internal CI/CD.
This is issue was produced by changes in PR6342
- fixes #
**Checklist**
> [bitnami/mongodb] Changes how the mongodb version is checked in readiness probes

- bitnami/nginx-ingress-controller/Chart.yaml
- bitnami/nginx-ingress-controller/templates/default-backend-deployment.yaml
We're using a macro (`"nginx-ingress-controller.annotations"`) that doesn't exist. Therefore, we can't set custom annotations for default backend pods. This PR addresses this issue using the `"common.tplvalues.render"` macro.
**Benefits**
Custom annotations for Default Backend work
None
- fixes https://github.com/bitnami/charts/issues/6439
**Checklist**
> NGINX Ingress Controller - Fix podAnnotations for default backend

- bitnami/kube-prometheus/Chart.yaml
- bitnami/kube-prometheus/values.yaml
No changes apart from the chart's version.
A fix was introduced in 50fa206e84e20b2e477c5ec1603efd5114bc2570, however the Bitnami bot released 7bdf67c3acbee13b9bb194687b7dc41479b4669b a few hours before and it seems that we'll have to wait for a new "update components versions" by the bot in order to get the fix from 50fa206e84e20b2e477c5ec1603efd5114bc2570 which is not the best because I would need the changes from 50fa206e84e20b2e477c5ec1603efd5114bc2570 ASAP.
**Benefits**
Release is done sooner.
None.
None.
If this PR does not make sense or if there is another way of triggering the new release, then feel free to close this PR.
**Checklist**
> [bitnami/kube-prometheus] Force new release

- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/templates/scripts-configmap.yaml
ReadinessProbe won't check cluster status when `cluster.externalAccess.enabled=true`.
Using externalAccess caused the cluster to get stuck because of the following situation:
```
The pod is not Ready because cluster is not formed <--> Cluster can't be formed because pods are not ready
```
This does not happen when using `cluster.externalAccess.enabled=false` as the cluster is formed using the headless service.
Redis nodes will receive traffic although the cluster might not be formed yet.
- fixes #6443
**Checklist**
> [bitnami/redis-cluster] Fix readinessProbe when externalAccess.enabled=true

- bitnami/kubeapps/Chart.yaml
- bitnami/kubeapps/templates/apprepository/apprepositories-secret.yaml
Currently, adding an `initialRepos` with `authorizationHeader` prevents the chart to be installed. It tries to retrieve `.Values.commonLabels` but, since it's under a `range` it's not in the scope.  
```console
Error: UPGRADE FAILED: template: kubeapps/templates/apprepository/apprepositories-secret.yaml:13:18: executing "kubeapps/templates/apprepository/apprepositories-secret.yaml" at <.Values.commonLabels>: nil pointer evaluating interface {}.commonLabels
```
This PR just adds `$` to use the global scope when necessary.
**Benefits**
Adding an `initialRepos` with `authorizationHeader` will work again:
```yaml
apprepository:
initialRepos:
- authorizationHeader: Basic <redacted>
name: myrepo
namespace: kubeapps
...
```
N/A
**Applicable …
>  [bitnami/kubeapps] Add missing $ to use the global scope

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/headless-svc.yaml
This PR fixes a hardcoded naming mismatch
**Benefits**
A working deployment
None
None
I ran into this issue when I tried to deploy it alongside the envoy rate limiting service and a istio service mesh with mTLS enforced. In the old version the sentinel port name of the pod did not match the port name of the service.
**Checklist**
> [bitnami/redis]: Fix hardcoded target port name in headless service

- bitnami/metallb/Chart.yaml
- bitnami/metallb/README.md
- bitnami/metallb/templates/controller/deployment.yaml
- bitnami/metallb/templates/speaker/daemonset.yaml
- bitnami/metallb/values.yaml
Adding priority class name attribute support for the MetalLB controller and speaker pods.
**Benefits**
Make the chart even more configurable. Allow user to specify custom priority class name for metallb pods.
None.
None.
None.
**Checklist**
> [bitnami/metallb] Add priorityClassName support.

- bitnami/external-dns/Chart.yaml
- bitnami/external-dns/templates/deployment.yaml
- bitnami/external-dns/values.yaml
Include a support to remove the livenessProbes and readinessProbes in case that the user doesn't want to use them.
- fixes #6471
**Checklist**
> [bitnami/external-dns] Include readinessProbe and livenessProbe just in case that there are defined

- bitnami/mariadb-galera/Chart.yaml
- bitnami/mariadb-galera/templates/statefulset.yaml
liveness probe keeps failing if I use vault secrets. Needs to be updates in a similar fashion as readiness probe.
Updating liveness probe to support vault secrets
**Benefits**
Liveness probe won't fail anymore
No drawback.
- fixes #
**Checklist** 
- ~Variables are documented in the README.md~
> [bitnami/mariadb-galera] Updating liveness probe to support vault secrets

- bitnami/thanos/Chart.yaml
- bitnami/thanos/values.yaml
Signed-off-by: fktkrt <fktkrt@gmail.com>
The current defaults seems to be off for Receive, as myself and others can experience permission denied errors, for example here: https://github.com/bitnami/charts/pull/5069.
```console
level=error ts=2021-02-07T13:11:32.087598081Z caller=main.go:130 err="configuration file is not parsable\ngithub.com/thanos-io/thanos/pkg/receive.init\n\t/app/pkg/receive/config.go:26\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5652\nruntime.doInit\n\t/usr/local/go/src/runtime/proc.go:5647\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:191\nruntime.goexit\n\t/usr/local/go/src/runtime/asm_amd64.s:1374\nfailed to parse configuration file: json: cannot unmarshal string into Go value of type …
```
> [bitnami/thanos] Fix securityContext for Receive

- bitnami/kafka/Chart.yaml
- bitnami/kafka/README.md
- bitnami/kafka/templates/statefulset.yaml
- bitnami/kafka/values.yaml
Add selector for Kafka data PVC and Kafka logs PVC, aiming to further filter the set of volumes. Only the volumes whose labels match the selector can be bound to the claim.
Inspired from this existing feature in [bitnami/postgres](https://github.com/bitnami/charts/blob/master/bitnami/postgresql) chart.
> <https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector>
**Benefits**
Ability to select an existing Persistent Volume using `matchLabels` or `matchExpressions`. 
- fixes https://github.com/bitnami/charts/issues/6506
**Checklist**
> [bitnami/kafka] Add selector to pvc

- bitnami/tomcat/Chart.yaml
- bitnami/tomcat/templates/_pod.tpl
Fix of indentations in tomcat chart
- fixes #6501
**Checklist** 
NOTE: I did not know if i should bump version..
> [bitnami/tomcat] initContainers and sidecars indent fix

- bitnami/dataplatform-bp2/Chart.yaml
- bitnami/dataplatform-bp2/README.md
- bitnami/dataplatform-bp2/values.yaml
The prefixes for the metrics emitted were changed to have them in sync with individual dashboards of Kafka Spark and Elastic Search on Tanzu Observability platform.
**Benefits**
Individual Dashboard on wavefront will be lit up and users can use those dashboards once TO platfroms have prometheus exporter dashboards for each tech stack.
- fixes #
**Checklist**
> bitnami/dataplatform-bp2 metric prefixes were updated to keep in sync with TO platfrom

- bitnami/kafka/Chart.yaml
- bitnami/kafka/README.md
- bitnami/kafka/templates/servicemonitor-jmx-metrics.yaml
- bitnami/kafka/templates/servicemonitor-metrics.yaml
- bitnami/kafka/values.yaml
**Which chart:**
`bitnami/kafka`
This change adds additional `relabelings` and` metricRelabelings` parameters to the `ServiceMonitor` resource for more flexible label customization.
**Checklist**
> [bitnami/kafka] Added params `relabelings` and `metricRelabelings` into ServiceMonitor resource

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/servicemonitor-jmx-metrics.yaml
- bitnami/kafka/templates/servicemonitor-metrics.yaml
Hotfix for PR  #6511
Fixed duplicate  for `reabelings` condition in service monitor templates.
**Checklist**
> [bitnami/kafka] Fixed duplicate for `reabelings` condition in service monitor templates

- bitnami/haproxy/Chart.lock
- bitnami/haproxy/Chart.yaml
- bitnami/haproxy/README.md
- bitnami/haproxy/templates/NOTES.txt
- bitnami/haproxy/templates/_helpers.tpl
- bitnami/haproxy/templates/configmap.yaml
- bitnami/haproxy/templates/deployment.yaml
- bitnami/haproxy/templates/extra-list.yaml
- bitnami/haproxy/templates/hpa.yaml
- bitnami/haproxy/templates/pdb.yaml
- bitnami/haproxy/templates/service-account.yaml
- bitnami/haproxy/templates/service.yaml
- bitnami/haproxy/values.yaml
This PR adds a HAProxy helm chart based on https://github.com/haproxytech/helm-charts/tree/main/haproxy. It features the following:
- Multiple replica support
- HPA
- PDBs
- Custom configuration
- Bitnami standards
In a future iteration, we should consider adding DaemonSet support. But for a first iteration, we will stick with a first version that is usable for several use cases that we had in support tickets.
*IMPORTANT TO NOTE*: The default configuration of this chart is just dummy, the user should specify its own configuration and define which ports wants to expose. This is similar to the bitnami/logstash chart.
**Benefits**
**Checklist**
> [bitnami/haproxy] Add chart

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/README.md
- bitnami/mongodb/templates/role.yaml
- bitnami/mongodb/values.yaml
This PR adds support for custom RBAC rules in a similar way we already do the same in the Redis Cluster chart.
**Benefits**
User can choose their custom RBAC rules
None
N/A
N/A
**Checklist**
> [bitnami/mongodb] Support for custom RBAC rules

- bitnami/minio/Chart.yaml
- bitnami/minio/README.md
- bitnami/minio/templates/distributed/statefulset.yaml
- bitnami/minio/templates/gateway/deployment.yaml
- bitnami/minio/templates/standalone/deployment.yaml
- bitnami/minio/values.yaml
Signed-off-by: Christian Kotzbauer christian.kotzbauer@gmail.com
Add "runAsNonRoot" config-option to the securityContext.
**Benefits**
It is possible to set "runAsNonRoot" to "true" now.
**Checklist**
> [bitnami/minio] Make runAsNonRoot configurable

- bitnami/jupyterhub/templates/NOTES.txt
This is a fix for templates/NOTES.txt incorrect reference in line 11.
**Benefits**
This change makes it possible to deploy the chart when proxy.ingress.enabled is set to true.
Not aware of any.
- fixes #6339 
**Checklist**
> [bitnami/jupyterhub] Fix issue with NOTES.txt when using proxy.ingress.enabled

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/README.md
- bitnami/zookeeper/templates/statefulset.yaml
- bitnami/zookeeper/values.yaml
Adds the ability to specify `customLivenessProbe` and `customReadinessProbe` to the ZooKeeper chart. This brings it in line with many other bitnami charts and the recommended default values.
**Benefits**
Beyond the benefit of bringing the ZooKeeper chart in line with the standard, users of ZooKeeper would benefit from setting the liveness and readiness probes to use the admin port instead of the client port as is recommended by Apache ZooKeeper.
Nothing about ZooKeeper in particular makes this feature inappropriate or dangerous for use.
None
The “four letter word” feature that backs the current liveness and readiness probes has been deprecated by Apache ZooKeeper …
> [bitnami/zookeeper] add customLivenessProbe and customReadinessProbe

- bitnami/mariadb/Chart.yaml
- bitnami/mariadb/README.md
- bitnami/mariadb/templates/primary/statefulset.yaml
- bitnami/mariadb/templates/secondary/statefulset.yaml
- bitnami/mariadb/values.yaml
Add revisionHistoryLimit support for secondary/primary.
**Benefits**
Anyone using this chart can set their own revisionHistoryLimit.
Nothing notable.
- fixes #
**Checklist**
> [bitnami/mariadb] add revisionHistoryLimit support for secondary/primary

- bitnami/cert-manager/Chart.yaml
- bitnami/cert-manager/templates/cainjector/serviceaccount.yaml
- bitnami/cert-manager/templates/controller/serviceaccount.yaml
- bitnami/cert-manager/templates/webhook/serviceaccount.yaml
Fixes documented parameters were not used in the final rendering
- fixes #6565 
**Checklist**
> bitnami/cert-manager fix: service account specific annotations not being used.

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/templates/deployment.yaml
This change fixes the functionality to mount custom htaccess files into the wordpress application using the `customHTAccessCM` value.
It changes the mountpoint to /opt/bitnami/apache/conf/vhosts/htaccess, where it is expected by the docker wordpress image (see https://github.com/bitnami/bitnami-docker-wordpress/blob/aa3e7c32881842fbdd91bc0aeddb42e16e471dbb/5/debian-10/rootfs/opt/bitnami/scripts/libapache.sh#L400 )
**Benefits**
- Custom htaccess functionality works.
- I did not test for incompatibilities with other htaccess related functionality, like the persistence feature `htaccessPersistenceEnabled`
- fixes #6553
**Checklist**
> [bitnami/wordpress] Fix custom htaccess configmap mount path

- bitnami/mariadb-galera/Chart.yaml
- bitnami/mariadb-galera/templates/statefulset.yaml
Modify the configmaps configuration path to use the new /bitnami/config support. All the files mounted in this folder will be copied inside /opt/bitnami/mariadb/conf/ folder. This change allow us to avoid the read only configmaps limitations.
**Benefits**
Avoid the read only configmaps limitations.
**Checklist**
> [bitnami/mariadb-galera] Modify configmaps path to use /bitnami/conf folder

- bitnami/mediawiki/Chart.yaml
- bitnami/mediawiki/README.md
- bitnami/mediawiki/templates/deployment.yaml
- bitnami/mediawiki/templates/metrics-svc.yaml
- bitnami/mediawiki/templates/servicemonitor.yaml
- bitnami/mediawiki/values.yaml
Add service monitor on mediawiki chart. 
This changes are inspired from wordpress chart.
It also fix the port used by apache exporter
**Benefits**
Allow to use service monitor on mediawiki chart
**Checklist**
> [bitnami/mediawiki] Add service monitor

- bitnami/discourse/Chart.yaml
- bitnami/discourse/templates/deployment.yaml
In version 4.0.0 we introduced major changes to the chart. However we missed a minor thing that caused Sidekiq to continue using old configuration that would break any generated URLs.
Before the Sidekiq container needed to wait for the Discourse container to be ready (listening on port 3000). However that logic was improved and now instead it is waiting for DB migrations to be completed, to consider the DB ready to start.
Note that Sidekiq is used for things such as generating URLs for attachments so if it uses the wrong URLs, wrong ones will be generated. Now, URLs from the [`templates/configmaps.yaml` template](https://github.com/bitnami/charts/blob/master/bitnami/discourse/templates/configmaps.yaml) will be used instead.
**Benefits**
Attachments show …
> [bitnami/discourse] Fix URLs for emojis and attachments

- bitnami/mysql/Chart.yaml
- bitnami/mysql/README.md
- bitnami/mysql/files/docker-entrypoint-initdb.d/README.md
We deprecated the possibility of adding custom init scripts by placing them in the `files/docker-entrypoint-initdb.d` directory. This possibility was very error-prone since users didn't realize that they need to previously fetch the chart or clone the charts repository.
However, we didn't remove the instructions to use it from the **README.md**, this PR does so.
**Benefits**
Accurate docs
None
- fixes https://github.com/bitnami/charts/issues/6485
N/A
**Checklist**
> [bitnami/mysql] Remove references to deprecated approach to mount custom scripts

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/README.md
- bitnami/zookeeper/templates/statefulset.yaml
- bitnami/zookeeper/values.yaml
Add selector for Zookeeper data PVC and Zookeeper dataLogDir PVC, aiming to further filter the set of volumes. Only the volumes whose labels match the selector can be bound to the claim.
Inspired from this existing feature in [bitnami/postgres](https://github.com/bitnami/charts/blob/master/bitnami/postgresql) chart.
> <https://kubernetes.io/docs/concepts/storage/persistent-volumes/#selector>
**Benefits**
Ability to select an existing Persistent Volume using `matchLabels` or `matchExpressions`. 
- fixes https://github.com/bitnami/charts/issues/6506
**Checklist**
> [bitnami/zookeeper] Add selector to pvc

- bitnami/kafka/Chart.yaml
- bitnami/kafka/README.md
- bitnami/kafka/templates/kafka-provisioning.yaml
- bitnami/kafka/values.yaml
Hi,
First of all, thank you for sharing and maintaining these charts !  
I propose this humble contribution to address a minor issue i ran into.  
If you have Istio in your cluster, the provisionning Job never ends due to the istio sidecar running forever.  
https://github.com/bitnami/charts/issues/5835#issuecomment-805704862 propose a way to keep the Pod in the Mesh but kill the proxy at the end of the Job.  
This PR adds optional Pod annotations to the provisioning Pods.  
It allows, for example, to completely disable Istio for the provisioning Job by passing the `sidecar.istio.io/inject: "false"` annotation.
**Benefits**
- Provides more control over the Kubernetes resources created by this chart.
- Allow a wider variety of use cases for Istio Mesh users. …
> [bitnami/kafka] adding a way to pass annotations to provisioning Pods

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/README.md
- bitnami/zookeeper/templates/svc.yaml
- bitnami/zookeeper/values.yaml
Allow to specify a nodePort in zookeeper service
**Benefits**
Allow the service to be of type NodePort with a chosen nodePort 
None
None
**Checklist**
> [bitnami/zookeeper] Allow to specify a nodePort in zookeeper service

- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/templates/poddisruptionbudget.yaml
Replace cluster creator job by cluster update job in pdb selector as the creator job was removed some versions ago. The initialization is now done directly inside the first pod of the statefulset.
**Benefits**
Less unused code is in the chart.
None I can think of.
None.
None.
**Checklist**
> [bitnami/redis-cluster] Replace cluster creator job by cluster update job in pdb selector

- bitnami/nginx/Chart.yaml
- bitnami/nginx/README.md
- bitnami/nginx/templates/deployment.yaml
- bitnami/nginx/values.yaml
Added new Value `$.Values.metrics.port`. If it's set a custom port can be configured which is the used by the exporter to scrape the status. The Default value is no longer hard coded to `8080` but takes as default the value of `$.Values.containerPorts.http`.
**Benefits**
When Changing the Port, the scraper currently no longer works, since the port is configured statically so you have to define the entire sidecar yourself. With this change the port value is considered and the possibility is given, to overwrite the port to any value.
Don't see any yet. 
Just did the pr with issue.
**Checklist**
> [bitnami/nginx] Custom Scrape port for Exporter

- bitnami/memcached/Chart.yaml
- bitnami/memcached/README.md
- bitnami/memcached/templates/_helpers.tpl
- bitnami/memcached/templates/deployment.yaml
- bitnami/memcached/templates/statefulset.yaml
- bitnami/memcached/values.yaml
This PR fixes the persistence setup since we were not passing the right flag to start Memcached, and when fixing it we found permissions issues:
```
failed to open file for mmap: No such file or directory
```
This PR also adds support to 2 common parameters: `initContainers` and `sidecars`
**Benefits**
The chart can be used with persistence.
None
- fixes https://github.com/bitnami/charts/issues/6647
N/A
**Checklist**
> [bitnami/memcached] Fix persistence + custom sidecars/init containers

- bitnami/airflow/Chart.yaml
- bitnami/airflow/templates/_helpers.tpl
Changed the `BITNAMI_DEBUG` variable to true value from 1.
**Benefits**
DEBUG messages start appearing one this is fixed
With 1 the container did not enter the debug mode and had the error 
```
airflow 09:12:03.10 INFO  ==> Waiting for PostgreSQL to be available at ctlfwmaster.ccdwyedutqre.ap-southeast-2.rds.amazonaws.com:5432...
airflow 09:12:03.13 DEBUG ==> Executing /opt/bitnami/airflow/venv/bin/airflow db init
/opt/bitnami/scripts/libos.sh: line 253: 1: command not found
```
> Fix debug value to true instead of 1

- bitnami/kubeapps/Chart.yaml
- bitnami/kubeapps/templates/kubeops/deployment.yaml
Values set at `kubeops.namespaceHeaderName` and `kubeops.namespaceHeaderPattern` cannot be passed to kubeops at initialization due to a typo.
**Benefits**
Ability to use the kubeops namespace whitelist feature implemented in https://github.com/kubeapps/kubeapps/pull/2671.
N/A.
N/A.
Mirror of https://github.com/kubeapps/kubeapps/pull/2981/files.
**Checklist**
> [bitnami/kubeapps] Fix typo in kubeops deployment for namespace header values

- bitnami/discourse/Chart.yaml
- bitnami/discourse/templates/deployment.yaml
Changes the health probes on the Discourse container from `/` to `/srv/status`.
**Benefits**
`/srv/status` is the dedicated endpoint for health checks on Discourse so should respond with `200 OK` when the server is up and running.
When `login_required` is enabled in Discourse settings the health probes start returning 302 as `/` is now being redirected to the login page. This creates a warning about the health probe in Kubernetes. Changing the health probe to `/srv/status` resolves this issue as the `/srv/status` endpoint is excluded from the login requirement.
- fixes #4927 
**Checklist**
> [bitnami/discourse] Fix health probes for Discourse container

- bitnami/redis/Chart.yaml
- bitnami/redis/README.md
- bitnami/redis/templates/serviceaccount.yaml
- bitnami/redis/values.yaml
* Add support for disabling automountServiceAccountToken
* Defaults to true
* Increment chart version 14.3.3 -> 14.4.0
Add support for disabling automountServiceAccountToken for the Redis ServiceAccount.
Also updated `pdb.create` in the README.md to reflect that its for creating the Pod Disruption Budget, NOT the ServiceAccount.
**Benefits**
Allows users to opt into disabling automountServiceAccountToken to keep the Redis pods from communicating with the Kubernetes API.
None, as automountServiceAccountToken will default to true, keeping the default behavior of giving pods access to the Kubernetes API.
N/A
N/A
**Checklist** 
- [X ] Chart version bumped in `Chart.yaml` according to …
> [bitnami/redis] Service account automountServiceAccountToken

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/templates/_helpers.tpl
fix ldap validation issue on bindpw. #6671
**Benefits**
It will take existingSecret into account as well, instead of just bindpw
none
- fixes #6671
N/A
**Checklist**
> [bitnami/postgresql-ha] fix ldap validation issue

- bitnami/nats/Chart.yaml
- bitnami/nats/templates/NOTES.txt
Fixes issue with instructions for the NATS client pod.
None known.
- fixes #6680
Without `GO111MODULE=off`, the `go get` command would download the nats.go package to `$GOPATH/pkg/mod` instead of `$GOPATH/src`:
```console
go: downloading github.com/nats-io/nats.go v1.11.0
CODE-OF-CONDUCT.md  context.go       go.mod       nats_test.go    timer_test.go
GOVERNANCE.md       dependencies.md  go.sum       netchan.go      util
LICENSE             enc.go           go_test.mod  norace_test.go  ws.go
MAINTAINERS.md      enc_test.go      go_test.sum  parser.go       ws_test.go
README.md           encoders         js.go        scripts
TODO.md             example_test.go  jsm.go       test
bench …
```
> [bitnami/nats] Update NATS client instructions in NOTES.txt

- bitnami/mongodb-sharded/Chart.yaml
- bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml
- bitnami/mongodb-sharded/templates/mongos/mongos-dep-sts.yaml
- bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml
- bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
Added support for the priorityClassName configuration that was already present in the value.yaml file, but not implemented in the templates.
**Benefits**
Deployed pods can be assigned a priority.  This is very important especially for database applications where eviction can cause major disruptions.
None known.
- fixes #6699 
**Checklist**
> [bitnami/mongodb-sharded] Enabled support for priorityClassName

- bitnami/nginx/Chart.yaml
- bitnami/nginx/templates/deployment.yaml
The chart does not mount the path `/opt/bitnami/nginx/conf/server_blocks`by default 
**Benefits**
- fixes #6693
**Checklist**
> [bitnami/nginx] server_blocks

- bitnami/wildfly/Chart.yaml
- bitnami/wildfly/templates/deployment.yaml
The management admin console was bound to 127.0.0.1 by default and it is needed to open it to be able to access from outside the pod.
**Benefits**
Makes the admin console accesible
- fixes #6716
**Checklist** 
- [] Variables are documented in the README.md
> [bitnami/wildfly]Fix management interface binding

- bitnami/owncloud/Chart.yaml
- bitnami/owncloud/templates/deployment.yaml
Fixes issue with Owncloud always using the Release fullname, ignoring `existingSecret`
- fixes #6719
**Checklist**
> [bitnami/owncloud] Fix issue with SecretName

- bitnami/mariadb/Chart.yaml
- bitnami/mariadb/README.md
- bitnami/mariadb/templates/primary/statefulset.yaml
- bitnami/mariadb/templates/secondary/statefulset.yaml
- bitnami/mariadb/values.yaml
There is a builtin startup check in Bitnami's MariaDB Docker image. This PR adds a way to control this check's options via MariaDB's chart values.
**Benefits**
This addition will allow the users to control startup wait time if they need to, in case their MariaDB installation takes too much time to start (e.g. it hosts a big database and/or installed on a slow storage).
These options could be accidentally set to incorrect values (say, 2 tries with 1 second wait time) and break startup on many installations.
- Fixes bitnami/bitnami-docker-mariadb#239
- Implements bitnami/bitnami-docker-mariadb#240
N/A
**Checklist**
> [bitnami/mariadb] Add options for image's builtin startup check

- bitnami/external-dns/Chart.yaml
- bitnami/external-dns/templates/deployment.yaml
Remove deprecated variables for Azure Private DNS as it now uses the same exact config as the Azure provider.
- fixes #6738 
Support for these variables was removed in #6657 
**Checklist**
> [bitnami/external-dns] Remove deprecated variables for Azure Private DNS

- bitnami/wavefront/Chart.yaml
- bitnami/wavefront/templates/collector-cluster-role.yaml
- bitnami/wavefront/values.yaml
Add `nodes/proxy` to role bindings. Upstream: 
https://github.com/wavefrontHQ/helm/commit/04da7cca365fa837635017c395a7a692a9420c51
https://github.com/wavefrontHQ/helm/commit/d6c5e8135aee025581d1625480dadad6b2e93212
**Checklist**
> [bitnami/wavefront] Add nodes/proxy to role bindings

- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/templates/coordinating-deploy.yaml
- bitnami/elasticsearch/templates/data-statefulset.yaml
- bitnami/elasticsearch/templates/ingest-deploy.yaml
- bitnami/elasticsearch/templates/master-statefulset.yaml
I stumpled over this while settings up security and therefore need to define a *customStartupProbe*
Changed all incorrect referneces where *livenessProbe* was mapped to  *customStartupProbe*
**Benefits**
Should work now as aspected
**Checklist** 
- [X ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
> [bitnami/elasticsearch] Fixed c&p errors in templates

- bitnami/solr/Chart.yaml
- bitnami/solr/templates/exporter-deployment.yaml
Fixes duplicate exporter probe properties
Demo of Issue in chart version 1.0.0:
```
cd bitnami/charts
helm template --set exporter.enabled=true --set authentication.enabled=false .
```
See duplicate keys in `livenessProbe` / `readinessProbe` in `solr-exporter` container.
**Benefits**
Fix duplicate properties
n/a
n/a
n/a
**Checklist**
> bitnami/solr: Fix duplicate solr exporter probe props

- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/README.md
- bitnami/elasticsearch/templates/coordinating-deploy.yaml
- bitnami/elasticsearch/templates/cronjob.yaml
- bitnami/elasticsearch/templates/data-statefulset.yaml
- bitnami/elasticsearch/templates/ingest-deploy.yaml
- bitnami/elasticsearch/templates/master-statefulset.yaml
- bitnami/elasticsearch/values.yaml
This PR adds support for adding custom init container and sidecar containers to Elasticsearch components.
**Benefits**
Flexibility
None
- fixes https://github.com/bitnami/charts/issues/6790
N/A
**Checklist**
> [bitnami/elasticsearch] Add suppor for custom sidecars and init containers

- bitnami/discourse/Chart.yaml
- bitnami/discourse/templates/pvc.yaml
- bitnami/ghost/Chart.yaml
- bitnami/ghost/templates/pvc.yaml
- bitnami/magento/Chart.yaml
- bitnami/magento/templates/pvc.yaml
- bitnami/mediawiki/Chart.yaml
- bitnami/mediawiki/templates/mediawiki-pvc.yaml
- bitnami/opencart/Chart.yaml
- bitnami/opencart/templates/pvc.yaml
- bitnami/owncloud/Chart.yaml
- bitnami/owncloud/templates/pvc.yaml
- bitnami/phabricator/Chart.yaml
- bitnami/phabricator/templates/pvc.yaml
- bitnami/suitecrm/Chart.yaml
- bitnami/suitecrm/templates/pvc.yaml
There are several apps that requires the external hostname (or IP) to be passed during the chart installation to configure the app properly.
Currently, we're not creating the **deployment** when we detect this happens (while installing other manifests such as the database ones), and show a warning in the **NOTES.txt** explaining the steps to follow to complete the installation. This is done to avoid users to face weird issues and `Crashloopbackoff` errors.
When you install the chart using `--wait` flag, it waits for every resource to be ready. While we're not creating the  **deployment** manifests as I mention before, we are creating the associated PVC manifests. These PVC(s) remain as "Pending" since the pods …
> [bitnami/*] Avoid creating PVC when unneeded

- bitnami/wordpress/Chart.lock
- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/README.md
- bitnami/wordpress/templates/ingress.yaml
- bitnami/wordpress/values.yaml
Reopens #5522
**Benefits**
Adds support for IngressClassName and updates common to version 1.7.0
None known.
- fixes #5514
**Checklist**
> [bitnami/wordpress] Add support for ingressClassName

- bitnami/nginx/Chart.yaml
- bitnami/nginx/templates/_helpers.tpl
Allow using templating in `staticSiteConfigmap` and `staticSitePVC`.
**Benefits**
If Nginx is a sub-chart of a chart, we can dynamically define the PVC to mount for Nginx to serve static content.
Nil
- fixes #
Currently, the chart already allows tpl for server block config map so this enhancement will add to that to make it fully functional as a sub chart.
**Checklist**
> [bitnami/nginx] Use tpl for staticSiteConfigmap and staticSitePVC

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/templates/svc-headless.yaml
Fix a broken a config for the headless service of zookeeper.
**Benefits**
Allows adding custom annotations to the headless service.
- fixes #
**Checklist**
> [bitnamti/zookeeper] Fix broken headless service annotations.

- bitnami/grafana/Chart.yaml
- bitnami/grafana/README.md
- bitnami/grafana/templates/deployment.yaml
- bitnami/grafana/values.yaml
The `podLabels` parameter is quite a common parameter that we usually add to our charts so users can define their custom labels for the pods to be deployed. This PR adds support for this parameter.
**Benefits**
Flexibility
None
- fixes https://github.com/bitnami/charts/issues/6842
N/A
**Checklist**
> [bitnami/grafana] Add support for custom pod labels

- bitnami/keycloak/Chart.lock
- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/README.md
- bitnami/keycloak/templates/ingress.yaml
- bitnami/keycloak/values.yaml
Adds support for ingressClassname for the Keycloak chart, as requested in https://github.com/bitnami/charts/issues/5514#issuecomment-872128727
**Benefits**
Additional feature.
None known.
**Checklist**
> [bitnami/keycloak] Add support for ingressClassName

- bitnami/nginx/Chart.yaml
- bitnami/nginx/templates/_helpers.tpl
Fix templating. Removing whitespace after yaml `key:` causes issues.
**Benefits**
- fixes #
**Checklist**
> [bitnami/nginx] Fix missing whitespace in template

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/master/statefulset.yaml
Specify explicitly the default replicas (1) for Redis master instead of leaving it implicit
**Benefits**
+ If we omit to specify the replicas it is defaulted to 1.
By omitting the value, an issue arise if an operator scale (down/up)
the replicaset and after try to re-apply the helm chart in order to
revert operations. In the case the replicas value is omitted
helm/kube will not scale back the replicaset to its original default
value.
+ This PR intends to paliate to the above issue. It just adds
replicas in the chart, so Helm/Kube will re-adjust/scale the
replicaset even if changed by an operator.
Replicaset will be re-scaled every time the chart is applied if not at the default value, but that's the desired behavior
**Checklist**
> [bitnami/redis] Specify master replicas to be 1

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/templates/tls-secret.yaml
Issue discovered installing a chart with a long name. The secret name of the secret auto generated is different than that name used to mount the secret. This error blocks the chart during the initialization. 
**Checklist**
> [bitnami/keycloak] Fix long name issue enabling autogenerated support

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/scripts-configmap.yaml
The IP detection logic for dualstack environments used two different awk scripts to detect ipv4 IP - one for sentinel (used mawk) and one for redis (used gnu awk in prior versions).  Current installation has mawk on both environments.  As the mawk version works on gnu awk, using it in both containers prevents further issues from occuring.
**Benefits**
IPv4 detection is not tied to specifc awk implementations.  Container changes will not impact configmap script functionality.
None
**Checklist**
> [bitnami/redis] Fix issue with IP detection when mawk is used

- bitnami/mongodb-sharded/Chart.lock
- bitnami/mongodb-sharded/Chart.yaml
- bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
- bitnami/mongodb-sharded/values.yaml
`MONGODB_MONGOS_HOST` variable was hardcoded to `common.names.fullname` but there is a template used to generate the service name based on the custom name specified in the values or the general fullname:
```
{{/*
Returns the proper Service name depending on if an explicit service name is set
in the values file. If the name is not explicitly set it will take the "common.names.fullname"
*/}}
{{- define "mongodb-sharded.serviceName" -}}
{{- if .Values.service.name -}}
{{ .Values.service.name }}
{{- else -}}
{{ include "common.names.fullname" .}}
{{- end -}}
{{- end -}}
```
This template is used everywhere except in the `MONGODB_MONGOS_HOST` env. variable, causing an issue when deploying the chart with a custom service name:
```console
$ kubectl get pods
NAME …
```
> [bitnami/mongodb-sharded] Fix issue when setting a custom service name

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/standalone/dep-sts.yaml
Specify explicitly the default replicas (1) for standalone mongo instead of leaving it implicit
P.s: Found the same issue than yesterday, PR for Redis master
**Benefits**
+ If we omit to specify the replicas it is defaulted to 1.
By omitting the value, an issue arise if an operator scale (down/up)
the replicaset and after try to re-apply the helm chart in order to
revert operations. In the case the replicas value is omitted
helm/kube will not scale back the replicaset to its original default
value.
+ This PR intends to paliate to the above issue. It just adds
replicas in the chart, so Helm/Kube will re-adjust/scale the
replicaset even if changed by an operator.
Replicaset will be re-scaled every time the chart is applied if not at the …
> [bitnami/mongodb] Specify standalone replicas to be 1

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/templates/statefulset.yaml
Adding common labels and annotations to PVC
**Benefits**
Able to locate the PVCs, for automatic deletion for example
**Checklist**
> bitnami/zookeeper - apply common labels and annotations to PVC

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/values.yaml
Currently `initContainers` is an empty map.
- "containers" suggests is should be a list
- `statefulset.yaml` has a single-entry list
- when adding an initContainer in the values.yaml, a render warning is issued:
" Merging destination map for chart 'rabbitmq'. Overwriting table item 'initContainers', with non table value: [map[...."
- Replace default value with empty list
**Benefits**
Removes the helm render error.
None 
None
**Checklist**
> [bitnami/rabbitmq] Fix default empty "initContainers" object

- .github/workflows/generate-chart-readme.yml
- bitnami/nginx-ingress-controller/Chart.yaml
- bitnami/nginx-ingress-controller/README.md
- bitnami/nginx-ingress-controller/values.yaml
- bitnami/node-exporter/Chart.yaml
- bitnami/node-exporter/README.md
- bitnami/node-exporter/values.yaml
- bitnami/node/Chart.yaml
- bitnami/node/README.md
- bitnami/node/values.yaml
Add metadata to `values.yaml` in order to be used by [readme-generator](https://github.com/bitnami-labs/readme-generator-for-helm) to automatically generate the "Parameters" section of the `README.md`.
General rules followed:
- If `values.yaml` doesn't have a description for a key in a comment → Use `README.md` description
- If `values.yaml` does have a description for a key in a comment but the `README.md` description provides more info → Use `README.md` description
- Else → Leave the `values.yaml` description
**Benefits**
Less manual work and consistency between `values.yaml` and `README.md`.
Commented keys are not picked by readme-generator so some had to be uncommented in order to appear in the README, however none of them …
> [bitnami/*] Adapt values.yaml of Nginx Ingress Controller, Node and Node Exporter charts

- bitnami/redis/Chart.yaml
- bitnami/redis/README.md
- bitnami/redis/values.yaml
Change default initialDelaySeconds from 5 to 20 for all probes. Although the logs end in a few seconds, Redis does take a while to init after that.
**Benefits**
1. Resolve Redis pods from getting killed on decent spec computers including i5 and i7 due to liveness probe unhealthy.
2. Resolve them from getting killed on Github actions using default values. Take a look at `Lint and Test Charts / test` log for commit aed05d3 (attached in additional info).
3. Mitigate chain reaction causing a cascading failure. If running on replica mode, Redis-1 will spin up since Redis-0 is ready, but Redis-0 is being killed due to the liveness probe unhealthy. Redis-1 will be killed as well and so on.
Nil
- fixes #
**Additional …
> [bitnami/redis] Fix: Redis initialDelaySeconds too short

- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/templates/cronjob.yaml
Currently the sidecars are placed on the wrong level (or under the wrong yaml property). 
**Benefits**
The sidecars specification is placed under the right section ("Containers:") and not under ("Spec:")
None known, since I fear it has never worked. 
https://github.com/bitnami/charts/issues/6956
**Checklist**
> [bitnami/elasticsearch] Curator sidecars are placed at the wrong level

- bitnami/discourse/Chart.yaml
- bitnami/discourse/templates/configmaps.yaml
This patch modifies the way that we are including the port inside the DISCOURSE_HOST in our chart. After an internal investigation, it seems that Discourse doesn't support to modify the default 80 or 443 ports:
https://meta.discourse.org/t/how-to-specify-a-different-port-not-80-during-installation/47859/10
This patch modifies the DISCOURSE_HOST included in our configmap to set up just the host without the port.
- fixes #6932
**Checklist**
> [bitnami/discourse] Avoid to include ports in DISCOURSE_HOST

- .github/workflows/generate-chart-readme.yml
- bitnami/common/values.yaml
- bitnami/tomcat/Chart.yaml
- bitnami/tomcat/README.md
- bitnami/tomcat/values.yaml
- bitnami/wavefront/Chart.yaml
- bitnami/wavefront/README.md
- bitnami/wavefront/values.yaml
- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/README.md
- bitnami/zookeeper/values.yaml
Add metadata to `values.yaml` in order to be used by [readme-generator](https://github.com/bitnami-labs/readme-generator-for-helm) to automatically generate the "Parameters" section of the `README.md`.
General rules followed:
- If `values.yaml` doesn't have a description for a key in a comment → Use `README.md` description
- If `values.yaml` does have a description for a key in a comment but the `README.md` description provides more info → Use `README.md` description
- Else → Leave the `values.yaml` description
**Benefits**
Less manual work and consistency between `values.yaml` and `README.md`.
Commented keys are not picked by readme-generator so some had to be uncommented in order to appear in the README, however none of them …
> [bitnami/*] Adapt values.yaml of common library, Tomcat, Wavefront and ZooKeeper charts

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/README.md
- bitnami/rabbitmq/templates/extra-list.yaml
- bitnami/rabbitmq/values.yaml
Add extraDeploy feature as in others bitnami charts.
**Benefits**
Allow users to create any extra k8s resources (such like configmap or secrets to use with extraVolume and extraVolumeMounts)
N/A
- fixes #6926
**Checklist**
> [bitnami/rabbitmq] add extraDeploy support (#6926)

- bitnami/discourse/Chart.yaml
- bitnami/discourse/templates/deployment.yaml
I fixed the indentation function used for sidecars container from ` indent` to `nindent`, because that was causing a `YAML parse error`.
To test it run the following command:
```
helm install --dry-run --debug discourse bitnami/discourse --set discourse.host=example.com --set "sidecars[0].name=example,sidecars[0].image=example:latest"
```
You should see the following error:
```
Error: YAML parse error on discourse/templates/deployment.yaml: error converting YAML to JSON: yaml: line 152: mapping values are not allowed in this context
helm.go:88: [debug] error converting YAML to JSON: yaml: line 152: mapping values are not allowed in this context
```
**Benefits**
This PR fixes the `YAML parse error` described above. …
> [bitnami/discourse] fixed indentation of sidecars containers on discourse

- bitnami/nginx/Chart.yaml
- bitnami/nginx/README.md
- bitnami/nginx/templates/deployment.yaml
- bitnami/nginx/values.yaml
It disables the automounting of the service account token in the pod. Nginx does not need this. This commit disables it by default, but leaves it configurable if anyone needs to use it.
**Benefits**
By disabling the automount, potential attackers cannot access the Kubernetes API on behalf/through the pod.
In the unlikely event that anyone is using some sidecar to access the Kubernetes API, relying on the mounted SA token, it will break with this commit.
If raising an issue is required or helpful, please tell me and I'd be glad to do so.
**Checklist**
> [bitnami/nginx]: disable automount of SA token

- bitnami/suitecrm/Chart.yaml
- bitnami/suitecrm/templates/secrets.yaml
Fixes a small typo in SuiteCRM `secrets.yaml` causing the SMTP password to be ignored.
None known.
- fixes #6999
**Checklist**
> [bitnami/suitecrm] Fix issue with SMTP password

- bitnami/mongodb-sharded/Chart.yaml
- bitnami/mongodb-sharded/templates/mongos/mongos-service-per-replica.yaml
This PR fixes an issue with the `$index` that keeps the value `1` after the first 2 iterations because of the way the precedence is done in Helm when using `merge`, causing things like : 
```yaml
metadata:
name: RELEASE-NAME-mongodb-sharded-3
labels: 
app.kubernetes.io/name: mongodb-sharded
annotations:
external-dns.alpha.kubernetes.io/hostname: mongo-1.test # The .index used here is wrong
```
**Benefits**
I thought it would better to create a copy of the object instead of mutating it throughout the loops, but using `mergeOverwrite` would work too 🤷
**Checklist**
> [bitnami/mongodb-sharded] Fix wrong index in servicePerReplica context

- bitnami/mediawiki/Chart.yaml
- bitnami/mediawiki/templates/NOTES.txt
The notes generated when using helm to install **bitnami/mediawiki** are incorrect as far as the MariaDB exported variables are concerned. This change will fix the problem with the definition of MARIADB_ROOT_PASSWORD and MARIADB_PASSWORD.
**Benefits**
Manual edits of the generated notes will no longer be required.
**Checklist**
> [bitnami/mediawiki] Corrected generated notes for MariaDB.

- bitnami/cert-manager/Chart.yaml
- bitnami/cert-manager/templates/controller/rbac.yaml
Add missing RBAC permissions to allow cert-manager do its leader election.
**Benefits**
- fixes leader election when cert-manager controller starts.
Cf. https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/templates/rbac.yaml
**Checklist**
> [bitnami/cert-manager] Fix leader election RBAC

- bitnami/metallb/Chart.yaml
- bitnami/metallb/templates/speaker/daemonset.yaml
It removes the duplicated tolerations key from the speaker daemonset manifests.
**Benefits**
- fixes #
**Checklist**
> [bitnami/metallb] Hotfix double tolerations in speaker daemonset.

- bitnami/kibana/Chart.yaml
- bitnami/kibana/templates/deployment.yaml
Currently, kibana healthcheck using `/app/kibana` which regularly lead to 503 or 429 (Too many requests).
So I suggest that change healthcheck endpoint to `/api/status` to avoid this issue.
> [kibana] change healthcheck endpoint to /api/status

- bitnami/redis/Chart.yaml
- bitnami/redis/README.md
- bitnami/redis/templates/master/statefulset.yaml
- bitnami/redis/templates/replicas/statefulset.yaml
- bitnami/redis/values.yaml
If `metrics.extraArgs.script` is defined, add an extra VolumeMount to the metrics sidecar containers to ensure they can see it.  The responsibility of providing the volume and script is on the chart.
This was not added to the sentinel sidecar, as that is apparently going away.
Fixes issue: https://github.com/bitnami/charts/issues/6792
> [bitnami/redis]: Add an extra VolumeMount to the metrics sidecar

- bitnami/jupyterhub/Chart.yaml
- bitnami/jupyterhub/README.md
- bitnami/jupyterhub/values.yaml
The default value was modified from:
```yaml
extraIngress: |
##
- ports:
- port: {{ .Values.proxy.containerPort.http }}
```
to
```yaml
extraIngress:
##
- ports:
- port: "{{ .Values.proxy.containerPort.http }}"
```
at #7024
Causing the following issue
```console
$ helm install my-jupyter --set hub.adminUser=user --set hub.password=jphubpassword .
Error: NetworkPolicy.extensions "t012909-jupyter-jupyterhub-proxy" is invalid: spec.ingress[0].ports[0].port: Invalid value: "8000": must contain at least one letter or number (a-z, 0-9)
```
that was produced because the port was assigned as a value containing the double quotes:
```console
$ helm template my-jupyter --set hub.adminUser=user --set hub.password=jphubpassword -s templates/proxy/networkpolicy.yaml . …
```
> [bitnami/jupyterhub] Fix default value for extraIngress/extraEgress

- bitnami/concourse/Chart.yaml
- bitnami/concourse/values.yaml
Fixes `nil` value.
**Checklist**
> [bitnami/concourse] Fix nil value

- bitnami/mongodb-sharded/Chart.lock
- bitnami/mongodb-sharded/Chart.yaml
- bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml
- bitnami/mongodb-sharded/values.yaml
When doing a `helm template -f my_values_file.yaml` I had the following issue : 
```
Error: template: mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml:268:28: executing "mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml" at <.Values.diagnosticMode.enabled>: can't evaluate field Values in type int
```
Looks like we may have missed the necessary `$` in front of the `Values` when adding the diagnostic mode (https://github.com/bitnami/charts/pull/7012)
**Benefits**
- Looks like no issue was opened 🤷 
**Checklist**
> [bitnami/mongodb-sharded] Fix helm error in arbiter statefulset

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/scripts-configmap.yaml
A variable was missing for setting the truststore location
**Benefits**
- fixes #
**Checklist**
> [bitnami/kafka] Fix missing environment variable for SSL

- bitnami/kafka/Chart.lock
- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/statefulset.yaml
- bitnami/kafka/values.yaml
We included in the Kafka image a new function (`kafka_configure_from_environment_variable`) that maps every env. variable with the "KAFKA_CFG" prefix to the configuration file. However, there are a couple of env. vars used by the container logic to configure TLS that have no associated property. We'll release a new container revision removing the `_CFG_` appendix to `KAFKA_CFG_TLS_TYPE` and `KAFKA_CFG_TLS_CLIENT_AUTH`.
**Benefits**
Correct configuration files
None
N/A
N/A
**Checklist**
> [bitnami/kafka] Adapt env. variables to new format

- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/templates/networkpolicy.yaml
The networkpolicy template messed up with the indentation and if/else blocks. This PR addresses that problem.
**Benefits**
Users can set custom policies so pods from other namespaces can connect Redis as described below:
- https://github.com/bitnami/charts/tree/master/bitnami/redis-cluster#networkpolicy
None
- fixes https://github.com/bitnami/charts/issues/7097
N/A
**Checklist**
> [bitnami/redis-cluster] Fix networkpolicy

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/_helpers.tpl
- bitnami/kafka/templates/kafka-metrics-deployment.yaml
The exporter needs now a new flag to work with SASL. This flag indicates the mechanism to use (scram or plain) and uses a slightly different format to the one used by Kafka itself.
More info at https://github.com/danielqsj/kafka_exporter#flags
**Benefits**
Users can use SASL and metrics simoultaneously.
None
- fixes https://github.com/bitnami/charts/issues/7065
N//A
**Checklist**
> [bitnami/kafka] Add missing flag to Kafka exporter to use SASL as authentication

- bitnami/postgresql-ha/README.md
On my journey exploring this repo I stumbled over a dead link. It seems, that the repo was renamed, this PR fix it with the correct and new one
**Benefits**
- fixes #
**Checklist**
> updated Link to new repo name

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/bucketweb/tls-secrets.yaml
- bitnami/thanos/templates/query-frontend/tls-secrets.yaml
- bitnami/thanos/templates/receive/tls-secrets.yaml
Updates the Values variable reference to global scope in order to not throw a nil pointer exception.
**Benefits**
Thanos:5.2.6 will install properly when ingress is enabled with several specific configurations.
- fixes #7106 
**Checklist** 
- [X ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
> [bitnami/thanos] Fix nil pointer exception when deploying Thanos with bucketweb ingress.

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/README.md
- bitnami/grafana-operator/templates/NOTES.txt
- bitnami/grafana-operator/templates/_helpers.tpl
- bitnami/grafana-operator/templates/deployment.yaml
- bitnami/grafana-operator/templates/grafana.yaml
- bitnami/grafana-operator/values.yaml
- bitnami/kafka/Chart.yaml
- bitnami/kafka/README.md
- bitnami/kafka/templates/_helpers.tpl
- bitnami/kafka/templates/kafka-provisioning.yaml
- bitnami/kafka/values.yaml
- bitnami/redmine/Chart.yaml
- bitnami/redmine/README.md
- bitnami/redmine/templates/NOTES.txt
- bitnami/redmine/templates/_helpers.tpl
- bitnami/redmine/templates/cronjob.yaml
- bitnami/redmine/values.yaml
- bitnami/solr/Chart.yaml
- bitnami/solr/README.md
- bitnami/solr/templates/NOTES.txt
- bitnami/solr/templates/_helpers.tpl
- bitnami/solr/templates/exporter-deployment.yaml
- bitnami/solr/values.yaml
In this version, the `image` block is defined once and is used in the different templates, while in the previous version, the `image` block was duplicated for every component
```yaml
image:
repository: bitnami/xxx
tag: A.B.C
```
VS
```yaml
foo:
image:
repository: bitnami/xxx
tag: A.B.C
...
bar:
image:
repository: bitnami/xxx
tag: A.B.C
```
The chart version was bumped in a major
**Checklist**
> [bitnami/several] Simplify image definition logic removing duplications

- bitnami/argo-cd/Chart.yaml
- bitnami/argo-cd/README.md
- bitnami/argo-cd/templates/NOTES.txt
- bitnami/argo-cd/templates/_helpers.tpl
- bitnami/argo-cd/templates/application-controller/deployment.yaml
- bitnami/argo-cd/templates/dex/deployment.yaml
- bitnami/argo-cd/templates/repo-server/deployment.yaml
- bitnami/argo-cd/templates/server/deployment.yaml
- bitnami/argo-cd/values.yaml
In this version, the `image` block is defined once and is used in the different templates, while in the previous version, the `image` block was duplicated for every component
```yaml
image:
repository: bitnami/argo-cd
tag: 2.0.5
```
VS
```yaml
controller:
image:
repository: bitnami/argo-cd
tag: 2.0.5
...
server:
image:
repository: bitnami/argo-cd
tag: 2.0.5
...
repoServer:
image:
repository: bitnami/argo-cd
tag: 2.0.5
```
The chart version was bumped in a major
**Checklist**
> [bitnami/argo-cd] Simplify image definition logic removing duplications

- bitnami/contour/Chart.lock
- bitnami/contour/Chart.yaml
- bitnami/contour/resources/extensionservices.yaml
- bitnami/contour/resources/httpproxies.yaml
- bitnami/contour/resources/tlscertificatedeligations.yaml
- bitnami/contour/values.yaml
Updates the Contour CRDs to match the recently release Contour 1.18
**Benefits**
Adds `ingressClassName` field
**Checklist**
> [bitnami/contour] Sync CRDs with contour release 1.18

- bitnami/kubeapps/Chart.yaml
- bitnami/kubeapps/crds/apprepository-crd.yaml
Upgraded the App Repository CRD from version v1beta1 to v1. v1beta1 is deprecated and is being removed in kubernetes 1.22+.
Updated the definition to comply with the new schema for V1 version.
Added a open API v3 schema.
Also added additional printer columns.
**Benefits**
Allows support for kubeapps in kubernetes 1.22+ 
This change breaks support for kubernetes 1.15.
The change is related to Kubeapps issue 2169 (https://github.com/kubeapps/kubeapps/issues/2169)
N/A
**Checklist**
> [bitnami/kubeapps] upgraded app repository CRD to v1 version

- bitnami/contour/Chart.yaml
- bitnami/contour/README.md
- bitnami/contour/templates/contour/deployment.yaml
- bitnami/contour/templates/contour/rbac.yaml
- bitnami/contour/values.yaml
Following patterns in other charts, sidecar pods and rbac customization
was added
**Benefits**
- Can add sidecar pods to the contour controller
- Can specify additional RBAC permissions for the contour service account
**Checklist**
> [bitnami/contour] Aidan/sidecar rbac options

- bitnami/common/Chart.yaml
- bitnami/common/README.md
- bitnami/common/templates/_capabilities.tpl
CronJobs reached general availability in Kubernetes 1.21, see the announcement [here](https://kubernetes.io/blog/2021/04/09/kubernetes-release-1.21-cronjob-ga/).
This change adds the `common.capabilities.cronjob.apiVersion` template to switch between `batch/v1beta1` and `batch/v1` for CronJobs if the Kubernetes version is 1.21+.
**Benefits**
Removes the following warning when attempting to deploy a CronJob of API version `batch/v1beta1` onto a Kubernetes cluster of 1.21+:
`batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
`
None that I can for-see.
**Checklist**
> [bitnami/common] Add cronjob apiVersion capability

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/templates/postinit-configmap.yaml
This change is to avoid error during wp-config.php permission change.
```
+ chmod -w bitnami/wordpress/wp-config.php
chmod: bitnami/wordpress/wp-config.php: new permissions are r--rw-r--, not r--r--r--
```
**Benefits**
It makes post-init script more stable.
None
**Checklist**
> [bitnami/wordpress]: fix flag for wp-config.php permission change in post-init script

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/templates/deployment.yaml
Set `APACHE_HTTPS_PORT_NUMBER` and `APACHE_HTTP_PORT_NUMBER` using the values of `containerPorts.http` and `containerPorts.https`.
**Benefits**
Users won't need to add `extraEnvVars` in addition to `containerPorts` to modify the WordPress ports.
None known. 
Maybe conflicts with users that were already setting `APACHE_*_PORT_NUMBER` or were setting a different `containerPorts` with other purposes.
- fixes #7130
**Checklist**
> [bitnami/wordpress] Set APACHE_HTTP_PORT_NUMBER

- bitnami/jenkins/Chart.yaml
- bitnami/jenkins/templates/ingress.yaml
when `ingress.tls` is `true`, TLS config for `ingress.hostname` should
be applied if either one of the following 3 conditions is met:
1. `certManager` is enabled
2. `selfSigned` is enabled
3. `hostname-tls` secret is configured separately.
Previously, condition 3 was not covered.
**Benefits**
Now it covers all the cases for tls config for `ingress.hostname`
N/A
- fixes #7143
N/A
**Checklist**
> [bitnami/jenkins] Fix the condition for ingress tls config

- template/CHART_NAME/templates/deployment.yaml
There should be a typo around `replicaCount` in the template.  The `%%MAIN_OBJECT_BLOCK%%` placeholder was missing in `template/CHART_NAME/templates/deployment.yaml` for some reason, though it's documented in `template/CHART_NAME/values.yaml`.
> Fix template replicaCount

- bitnami/mysql/Chart.yaml
- bitnami/mysql/README.md
- bitnami/mysql/values.yaml
We're enabling the startup probes by default in MySQL. However, we're still using huge values for `initialDelaySeconds` properties in the probes which doesn't make sense at all. Instead, we should a combination `failureThreshold * periodSeconds` long enough to cover the worse case startup time.
More info at:
- https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes
**Benefits**
The MySQL installation is ready much faster.
None
N/A
N/A
**Checklist**
> [bitnami/mysql] Improve default values for probes

- bitnami/haproxy/Chart.yaml
- bitnami/haproxy/templates/deployment.yaml
By adding an annotation including the checksum of the Configmap, we ensure that every time the configuration is updated by Helm the HA Proxy deployment will run a rolling update since this annotation will change.
**Benefits**
Pods are updated when the configuration changes.
None
Reported at https://github.com/bitnami/charts/issues/5424
None
**Checklist**
> [bitnami/haproxy] Add Configmap checksum annotation

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/README.md
- bitnami/zookeeper/templates/statefulset.yaml
- bitnami/zookeeper/values.yaml
Added preAllocSize and snapCount options to the chart. These correspond to environment variables ZOO_PRE_ALLOC_SIZE and ZOO_SNAPCOUNT. Default values are the same as those in the docker image.
**Benefits**
Allows users to specify preAllocSize and snapCount settings
None
None
N/A
**Checklist**
> [bitnami/zookeeper] Added preAllocSize and snapCount options

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/templates/ingress.yaml
If the fullname is longer than 20 characters, the keycloak.fullname (which is used in service.name) will be trimmed while "keycloak.fullname" is only trimmed at 63 characters. This will lead to a situation where the ingress references an non-existing service. Example:
`error: endpoints "a-very-long-release-name-keycloak" not found>)`
**Benefits**
- fixes #
**Checklist**
> [bitnami/keycloak] Fix service reference in ingress

- bitnami/odoo/Chart.yaml
- bitnami/odoo/templates/_helpers.tpl
- bitnami/odoo/templates/externaldb-secrets.yaml
Change external DB secret name because Odoo can't find it.
```
Warning  Failed   0s (x3 over 15s)   kubelet   Error: secret "my-release-externaldb" not found
------------
my-release-odoo-7cfd4fdc6b-vxr6f   0/1     CreateContainerConfigError   0          10m
```
Steps to reproduce the issue:
- Create a helm chart with an external database.
```
helm install my-release bitnami/odoo \
--set odooPassword=password \
--set postgresql.enabled=false \
--set externalDatabase.host=myexternalhost \
--set externalDatabase.user=myuser \
--set externalDatabase.password=mypassword
```
- Describe a pod from Odoo.
```
kubectl describe po my-release-odoo-7cfd4fdc6b-vxr6f
Events:
Type     Reason                  Age                From                     Message
----     ------ …
```
> [bitnami/odoo] Fix external database secret

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/query/deployment.yaml
- bitnami/thanos/templates/storegateway/service-sharded.yaml
This is a continued effort on #7049 the thanos query needs to read from the different sharded services 
**Benefits**
This will enable the thanos query to read on the service shardes
fixes #7049
**Checklist** 
- [] Variables are documented in the README.md
> [bitnami/thanos] Update thanos query to read sharded service

- bitnami/nginx-ingress-controller/Chart.yaml
- bitnami/nginx-ingress-controller/templates/controller-prometheusrules.yaml
This PR fixes the prometheusrule template by increasing `nindent` by 2.
**Benefits**
Template renders with correct indentation for rules array.
**Checklist**
> [bitnami/nginx-ingress-controller] Fix indentation for prometheusrule.

- bitnami/external-dns/Chart.yaml
- bitnami/external-dns/templates/configmap.yaml
- bitnami/external-dns/templates/pdb.yaml
- bitnami/external-dns/templates/secret.yaml
- bitnami/external-dns/templates/tls-secret.yaml
- bitnami/external-dns/values.yaml
Adds a metadata.namespace entry to a handful of namespace-scoped resources. These would work before when using `helm install -n <namespace>`, but when generating the manifest from `helm template -n <namespace>` those resources would be placed in default, instead.
**Benefits**
Allows users to generate correct manifests from Helm
If users relied on the bad behavior, it is now gone
- fixes #7210 
**Checklist**
> [bitnami/external-dns] Adds namespace entries to several templates

- bitnami/cert-manager/Chart.yaml
- bitnami/cert-manager/templates/cainjector/rbac.yaml
Add missing RBAC permissions to allow cert-manager **cainjector** do its leader election. Related to #7035 
CAinjector also required leases permissions in order to complete leader election.
**Benefits**
CF: https://github.com/jetstack/cert-manager/blob/master/deploy/charts/cert-manager/templates/rbac.yaml
**Checklist**
> [bitnami/cert-manager] Fix RBAC issue for cainjector leader election

- bitnami/etcd/Chart.yaml
- bitnami/etcd/templates/cronjob.yaml
- bitnami/etcd/templates/statefulset.yaml
Use existingSecret parameters on client/peer certificates as a template. This improve experience when bitnami/etcd is used as a sub-chart.
**Benefits**
Easier to handle when used as a sub-chart.
- fixes #7208
**Checklist**
> [bitnami/etcd] use existingSecret parameters as a template

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/scripts-configmap.yaml
Signed-off-by: alex <zhanweidu@163.com>
Adjust the order of sentinel starting logic. make sure the master is elected before node restarted.
**Benefits**
Redis is alway available when there are two node available at least.
- fixes #7181
**Checklist**
> [bitnami/redis] fix redis available issue after master node restarted

- bitnami/redmine/Chart.yaml
- bitnami/redmine/templates/NOTES.txt
- bitnami/redmine/templates/_helpers.tpl
- bitnami/redmine/templates/deployment.yaml
The current configuration assumes the database port is 3306 in case an external database is not configured so it breaks in case the embedded database selected is PostgreSQL. This makes the chart set the default port for MariaDB at 3306 and for PostgreSQL at 5432.
- fixes #7219
**Checklist**
> [bitnami/redmine] Fix port number setting for PostgreSQL database

- bitnami/mariadb-galera/Chart.yaml
- bitnami/mariadb-galera/templates/statefulset.yaml
Changes the mountPath for the Mariadb Galera custom configuration
None known.
- fixes #7198
**Checklist**
> [bitnami/mariadb-galera] Fix issue with my.cnf

- bitnami/kubernetes-event-exporter/Chart.yaml
- bitnami/kubernetes-event-exporter/templates/deployment.yaml
`extraEnvVars` variable is described in README/documentation but isn't supported in chart itself.
**Benefits**
We can inject ENV variables into containers from now on.
None.
**Checklist**
> [bitnami/kubernetes-event-exporter] Add extraEnvVars support

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/replicas/statefulset.yaml
- bitnami/redis/templates/scripts-configmap.yaml
The clustering was configured using the headless service (that will return the pod IPs) with the service IPs (which is not present in the containers). This was causing conflicts when changing the service port. This PR fixes this. 
**Benefits**
- fixes #
**Checklist**
> [bitnami/redis] Fix clustering when service port != container port

- template/CHART_NAME/templates/daemonset.yaml
- template/CHART_NAME/templates/deployment.yaml
- template/CHART_NAME/templates/statefulset.yaml
The base template is very much broken unless these below are fixed:
1. Fix logic about `diagnosticMode`
2. Remove non-existing `persistence` section (should have been ported from other charts while not used here – but why breaking the base template?)
3. Add missing quotes around `%%COMPONENT_NAME%%`
> Fix template logic

- bitnami/kubernetes-event-exporter/Chart.yaml
- bitnami/kubernetes-event-exporter/templates/deployment.yaml
A typo was made in #7238. Variable `extraEnvVars` was misspelled to `extraEnv`.
**Benefits**
Fix typo.
None.
**Checklist**
> [bitnami/kubernetes-event-exporter] Fix variable name to extraEnvVars

- bitnami/kube-state-metrics/Chart.yaml
- bitnami/kube-state-metrics/README.md
- bitnami/kube-state-metrics/values.yaml
When enabling kube state metrics service monitor it fails because of an incorrect type in the honorlabels section.
**Benefits**
- fixes #
**Checklist**
> [bitnami/kube-state-metrics] Change honorLabels type to boolean

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/templates/_helpers.tpl
In Keycloak chart, postgresql nameOverride and fullnameOverride support has been added to have a right value for `KEYCLOAK_DATABASE_HOST`
**Benefits**
postgresql nameOverride and fullnameOverride are supported.
- fixes #
**Checklist**
> bitnami/keycloak: handle postgresql nameOverride and fullnameOverride

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/templates/_helpers.tpl
Enable tpl in `auth.tls.existingSecret` value
**Benefits**
Tpl is useful for existingSecret. It's applied for others existing secrets but not for this one.
None ?
- fixes #
**Checklist**
> bitnami/rabbitmq: enable tpl for auth.tls.existingSecret

- bitnami/airflow/Chart.yaml
- bitnami/airflow/README.md
- bitnami/airflow/templates/metrics/deployment.yaml
- bitnami/airflow/values.yaml
Add Extra Environment Variables to the Airflow Metrics Deployment.
**Benefits**
Additional configuration of the deployment container.  This allows environment variables like `AIRFLOW_PROMETHEUS_POSTGRES_SSL_MODE` to be injected to the Airflow Metrics Deployment.
None foreseen.
- fixes #6820 
This does not include `.Values.extraEnvVars` like scheduler, web, and worker as those variables are not relevant to metrics.
This is a quick fix to get additional environment variables into the metrics deployment.  As my original conversation mentioned, ultimately, it would great to have a value (i.e. `externalDatabase.sslMode`) and helper (`airflow.database.sslMode`) that added the appropriate …
> [bitnami/airflow] Add Extra Environment Variables to Metrics Deployment

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/statefulset.yaml
Add app.kubernetes.io/component to matchLabels in podAntiAffinity section
**Benefits**
Avoids metrics pod (kafka exporter) to have same app.kubernetes.io/name and force k8s to schedule kafka-exporter on separate node.
None ?
fixes #
Additional information
**Checklist**
> [bitnami/kafka] Fix missing "component" "%COMPONENT_NAME%"

- bitnami/kibana/Chart.yaml
- bitnami/kibana/templates/deployment.yaml
This fixes a bug introduced at https://github.com/bitnami/charts/pull/7211/files. We included the `serviceAccountName` field under `spec.template.spec.containers[0].serviceAccountName` instead of `spec.template.spec.serviceAccountName`.
**Benefits**
Fixes the Kibana deployment specification.
None
N/A
N/A
**Checklist**
> [bitnami/kibana] Fix ServiceAcccount

- bitnami/nginx/Chart.yaml
- bitnami/nginx/README.md
- bitnami/nginx/templates/deployment.yaml
- bitnami/nginx/values.yaml
This chage adds a new bitnami/nginx chart value to toggle shareProcessNamespace for pods.
**Benefits**
This would benefit sidecars which would like to notify nginx configuration changes via signals. 
As this is a backwards compatible change, only downside is misuse of the value. That may cause security issues.
**Checklist**
> [bitnami/nginx] Added sidecarSingleProcessNamespace parameter

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/templates/rbac.yaml
For the operator to be able to scan all namespaces, it must have these rules.
Added more rules to RBAC ClusterRole.
**Benefits**
It will allow the operator to listen to all namespaces.
None.
None.
**Checklist**
> [bitnami/grafana-operator] Fix missing RBAC rules in case of cluster-wide installation

- bitnami/mariadb-galera/Chart.yaml
- bitnami/mariadb-galera/templates/statefulset.yaml
Fix the evaluation of `bootstrapFromNode` in the command of the statefulset.
**Benefits**
This fixes that a simple chart upgrade will keep (most probably) the node `0` in crash loop with the error `node not safe to bootstrap`.
- fixes #
**Checklist** 
> [bitnami/mariadb-galera] Fix bootstrapFromNode evaluation

- bitnami/contour/Chart.lock
- bitnami/contour/Chart.yaml
- bitnami/contour/README.md
- bitnami/contour/values.yaml
The new Contour version (https://github.com/projectcontour/contour/releases/tag/v1.18.0) support Envoy 1.19, see
> **Envoy Updated to 1.19.0**
> Contour 1.18.0 is compatible with Envoy 1.19.0. For more information, see the Contour compatibility matrix.
> Relevant PRs:
>  [#3887](https://github.com/projectcontour/contour/pull/3887) : update Envoy to 1.19.0
> [bitnami/contour] Bump envoy version bundled in contour Helm Chart

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/templates/statefulset.yaml
- bitnami/keycloak/values.yaml
It fixes a warning and enable tpl on existingSecret/existingSecretPerPassword secret names
**Benefits**
It enables tpl support in existingSecret and existingSecretPerPassword. It adds support. It also removes warning (cf commit)
None ?
**Checklist**
> bitnami/keycloak: tpl existingSecret/existingSecretPerPassword

- bitnami/redis/Chart.yaml
- bitnami/redis/README.md
- bitnami/redis/templates/scripts-configmap.yaml
- bitnami/redis/values.yaml
After upgrading to the latest Redis chart version from 12.0.1 we noticed that sentinel behaviour was broken.
Initially, we made another [PR](https://github.com/bitnami/charts/pull/7124) that tackled one specific issue we wanted to fix. However, we then realized that the current sentinel implementation is much more fragile than we thought it was.
In the current sentinel configuration there is an option to use `staticID: true` or not. This leads to two different behaviours to ensure the system's stability and resiliency.
Having different, functionally identical behaviours can introduce fragility. Specifically, supporting two incompatible configurations adds an additional burden to ensure that new bugs are not introduced to the other path.
- When **NOT** using …
> [bitnami/redis]: Enhance sentinel resiliency, harmonize sentinel behaviour by using staticID as default behaviour

- bitnami/etcd/Chart.yaml
- bitnami/etcd/README.md
- bitnami/etcd/templates/statefulset.yaml
- bitnami/etcd/values.yaml
This PR adds a new parameter **terminationGracePeriodSeconds** so this property can be easily customized.
**Benefits**
Flexibility
None
N/A
N/A
**Checklist**
> [bitnami/etcd] Add support for custom terminationGracePeriodSeconds

- bitnami/wildfly/Chart.yaml
- bitnami/wildfly/README.md
- bitnami/wildfly/ci/values-with-ingress-and-initcontainers.yaml
- bitnami/wildfly/templates/NOTES.txt
- bitnami/wildfly/templates/deployment.yaml
- bitnami/wildfly/templates/management-ingress.yaml
- bitnami/wildfly/templates/svc.yaml
- bitnami/wildfly/templates/tls-secrets.yaml
- bitnami/wildfly/values.yaml
This PR introduces new parameters to properly manage exposing the WildFly management console outside the cluster.
**Benefits**
Users can properly expose the management console when required.
None
- fixes https://github.com/bitnami/charts/issues/6911
You can test it using a **values.yaml** like the one below:
```yaml
exposeManagementConsole: true
ingress:
enabled: true
hostname: my.wildfly.hostname
mgmtIngress:
enabled: true
hostname: my.mgmt.hostname
service:
type: ClusterIP
```
**Checklist**
> [bitnami/wildfly] Add support for exposing WildFly Management console outside the cluster

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/scripts-configmap.yaml
After upgrading to 15.0.0 we realized there was an issue with sentinel. If the service is restarted within its running container, the sentinel config remained unchanged. The script is supposed to prune the known sentinels and replicas and regenerate them when fetching the available hosts on the network. This part of the script was not working as expected which caused this error:
```
>>> 'sentinel known-sentinel rt-collector-master 10.8.5.30 26379 ecac44470a643ce5d853d166ad8abc2135e4bdbf'
Duplicate runid for sentinel.
```
Our proposed solution is to override the existing configuration _(if it exists)_ with the original configuration at each bootup. This ensures all replicas start with the expected configuration file.
**Benefits**
- Fixes CrashBackLoop state if …
> [bitnami/redis]: hotfix, regenerate sentinel config at each boot-up

- bitnami/redis/Chart.yaml
- bitnami/redis/README.md
- bitnami/redis/templates/servicemonitor.yaml
- bitnami/redis/values.yaml
Allows relabeling labels for exported redis metrics via ServiceMonitor (before, only metricRelabelings was supported)
**Benefits**
Additional configuration options
None
- related #7330
None
**Checklist**
> [bitnami/redis] Add relabelings to ServiceMonitor

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/templates/secrets.yaml
Linebreak within secrets.yaml is not realized. Checking the rest of the file, it looks like the change will fix the linebreak, which breaks all helm deployments:
data:
admin-password: "xxxx"
management-password: "xxxxx"postgresql-password: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
> #7334 Missing line-break for external database

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/README.md
- bitnami/mongodb/templates/servicemonitor.yaml
- bitnami/mongodb/values.yaml
Allows relabeling labels for exported mongodb metrics
**Benefits**
More customization
None
- related #7342
**Checklist**
> [bitnami/mongodb] Add relabelings / metricRelabelings to ServiceMonitor

- bitnami/contour/Chart.yaml
- bitnami/contour/templates/envoy/daemonset.yaml
- bitnami/contour/templates/envoy/deployment.yaml
- bitnami/contour/values.yaml
From version 1.18.1, Contour requires an admin socket to be created under the default path of `/admin/admin.sock`. This PR implements a new volume that creates that path in both `shutdown-manager` and `envoy` containers. 
**Benefits**
Prepares the chart for the new Contour version 1.18.1
None
N/A
Contour does no longer expose the entire Envoy administration interface and instead, it does only show read-only options through it. This is in order to mitigate CVE-2021-32783. 
Envoy now listens on a Unix domain socket for such options.
https://github.com/projectcontour/contour/releases/tag/v1.18.1
**Checklist**
> [bitnami/contour] Add additional volume for admin sock

- bitnami/etcd/Chart.yaml
- bitnami/etcd/README.md
- bitnami/etcd/templates/svc.yaml
- bitnami/etcd/values.yaml
Add service.clusterIP parameter (taking example from aspnet-core chart)
**Benefits**
ETCD Service does not have the clusterIP parameter, it can be useful to set static IP or None.
**Checklist**
> [bitnami/etcd] add service.clusterIP parameter

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/replicas/hpa.yaml
- bitnami/redis/templates/sentinel/hpa.yaml
Fixes the HPA resource creation condition for sentinel and replicas.
- fixes #7360 
**Checklist**
> [bitnami/redis] Fix HPA condition for sentinel and replicas

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/README.md
- bitnami/mongodb/templates/arbiter/statefulset.yaml
- bitnami/mongodb/templates/hidden/statefulset.yaml
- bitnami/mongodb/templates/replicaset/statefulset.yaml
- bitnami/mongodb/templates/standalone/dep-sts.yaml
- bitnami/mongodb/values.yaml
Added support of runtime classes in mongodb chart
**Benefits**
Will be possible to specify runtime class on clusters that support multiple runtime classes (f.e. gVisor with FireCracker and runc)
- fixes #7361
**Checklist**
> [bitnami/mongodb] Add runtimeClassName support

- bitnami/contour/Chart.yaml
- bitnami/contour/templates/contour/deployment.yaml
Issue reported by an user. The ingressClass key now is generated checking the ingressClass in the top of the keys defined in values.yaml instead of contour.ingressClass (properly key definition path).
**Benefits**
Fix ingressClass definition in our templates.
- fixes #7372
**Checklist**
> [bitnami/contour] Fix ingressClass

- bitnami/etcd/Chart.yaml
- bitnami/etcd/README.md
- bitnami/etcd/templates/svc.yaml
- bitnami/etcd/values.yaml
* Adding .Values.service.enable bool set by default to true (service by default activated) on the ETCD Helm Chart
I added a conditional to the service creation, thanks to that, user is free to create or not the unnecessary service to the ETCD cluster
**Benefits**
Helpful if k8s cluster have mechanism who automatically create service with labeled resources or if administrator encounter errors with Gitops tools like flux (for example, I had an 'clusterIP immutable' when I tried to change values who concerned the STS object. HelmOperator was on error, impossible to modify the HelmRelease to fix that).
If user specify a un-boolean value (other than `true` & `false`)
**Checklist**
> [bitnami/etcd] Adding the possibility to disable service

- bitnami/elasticsearch/Chart.lock
- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/README.md
- bitnami/elasticsearch/values.yaml
A new major version of Kibana (8.X.X -> 9.X.X) was released a day ago (see https://github.com/bitnami/charts/pull/6487). This Elasticsearch chart bundled Kibana as a subchart, in order to bump the major version of the Kibana subchart we also need to bump the major version of Elasticsearch.
The Elasticsearch major version was also released yesterday (see https://github.com/bitnami/charts/pull/6486) but the subchart was not updated.
Both PRs (https://github.com/bitnami/charts/pull/6486 and https://github.com/bitnami/charts/pull/6487) are related, but since the Elasticsearch PR didn't incorporate the Kibana version bump, a new major version is required.
> [bitnami/elasticsearch] Bump Kibana major version

- bitnami/oauth2-proxy/Chart.yaml
- bitnami/oauth2-proxy/templates/deployment.yaml
Recreate pods when config is updated by adding configmap checksum to the pod annotations
**Benefits**
No need for manual restart when config is changed
None
**Checklist**
> [bitnami/oauth2-proxy] Recreate pods when config is updated

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/templates/networkpolicy.yaml
Our current NetworkPolicy doesn't allow internal communications between nodes. You can test it by simply installing the chart in a namespace (e.g. "dev") and testing the policies with [illuminatio](https://github.com/inovex/illuminatio):
```console
$ helm install zookeeper bitnami/zookeeper --set networkPolicy.enabled=true --set replicaCount=3 --namespace=dev
$ illuminatio run
...
FROM                                                                       TO                                                                         PORT    RESULT
dev:app.kubernetes.io/instance=zookeeper,app.kubernetes.io/name=zookeeper  dev:app.kubernetes.io/instance=zookeeper,app.kubernetes.io/name=zookeeper  3888    failure …
```
> [bitnami/zookeeper] Fix NetworkPolicy

- bitnami/external-dns/Chart.yaml
- bitnami/external-dns/templates/deployment.yaml
zoneType empty value allow creation domains in [both zones](https://github.com/kubernetes-sigs/external-dns/blob/master/provider/zone_type_filter.go#L42) at the same time. This change allow passing empty value as a zoneType filter. 
**Benefits**
This change enables to pass three available values to external-dns operator. 
n/a
n/a
**Checklist**
> [bitnami/external-dns] Allow empty value for zoneType filter

- bitnami/haproxy/Chart.yaml
- bitnami/haproxy/templates/pdb.yaml
According to https://kubernetes.io/docs/reference/using-api/deprecation-guide/ we can start using `policy/v1` in Kubernetes `1.21`.
Without this change you can observe such things in logs:
```
W0901 11:28:35.264440      91 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0901 11:28:35.269403      91 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
W0901 11:28:35.297605      91 warnings.go:70] policy/v1beta1 PodDisruptionBudget is deprecated in v1.21+, unavailable in v1.25+; use policy/v1 PodDisruptionBudget
```
**Checklist**
> [bitnami/haproxy] Update apiVersion of PDB to policy/v1 on 1.21+ cluster (via common.capabilities.policy.apiVersion)

- bitnami/redmine/Chart.yaml
- bitnami/redmine/templates/cronjob.yaml
mail-receiver-configmap.yaml reference $REDMINE_DATABASE_TYPE variable but this variable is never defined in cronjob.yaml
**Benefits**
- fixes #
**Checklist**
> [bitnami/redmine] Missing env var in cronjob.yaml

- bitnami/etcd/Chart.yaml
- bitnami/etcd/README.md
- bitnami/etcd/templates/podmonitor.yaml
- bitnami/etcd/values.yaml
PodMonitor are used by prometheus to discover endpoints to scrape and to pass scraping configuration (timeout, port ....).
Relabeling is a useful feature that allows promethues to manipulate labels on the generated metrics, these labels will be used later for filtering and alerting.
This PR add the relabelings field to the podmonitor created by the chart.
**Benefits**
- Custom labeling makes the metric more human friendly and easier to manipulate.
- Custom labeling can be used for backward compatibility with existing monitoring system.
N/A
- fixes #
**Checklist**
> [bitnami/etcd] add Prometheus podmonitor relabelings parameter

- bitnami/mariadb/Chart.yaml
- bitnami/mariadb/README.md
- bitnami/mariadb/templates/primary/statefulset.yaml
- bitnami/mariadb/templates/secondary/statefulset.yaml
- bitnami/mariadb/values.yaml
This adds support for specifying [topology spread constraints](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) to be sure Mariadb pods are spread reasonably in cluster by the topology key specified.
**Benefits**
user can spread pod evenly across cluster.
None.
None.
Before use, please read [topology spread constraints documentation](https://kubernetes.io/docs/concepts/workloads/pods/pod-topology-spread-constraints/) carefully. It is so important to label nodes with proper topologyKey, Otherwise pods will not be scheduled.
Examples
```
topologySpreadConstraints:
- maxSkew: 1
topologyKey: topology.kubernetes.io/zone
whenUnsatisfiable: DoNotSchedule
``` …
> [bitnami/mariadb] Added topology spread constraints to Mariadb chart.

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/crds/grafanadashboards.yaml
- bitnami/grafana-operator/crds/grafanadatasources.yaml
- bitnami/grafana-operator/crds/grafanas.yaml
The current version doesn't match the corresponding CRD in grafana-operator/grafana-operator v3.10.3
https://github.com/grafana-operator/grafana-operator/blob/v3.10.3/deploy/crds/Grafana.yaml
Update CRD grafanas.integreatly.org to match the corresponding upstream CRD
See https://github.com/grafana-operator/grafana-operator/blob/v3.10.3/deploy/crds/Grafana.yaml
**Benefits**
The current CRD is out of sync and needs the update. 
Not that I am aware of.
- it isn't possible to see `ingressClassName` in the outdated CRD.
**Checklist**
> [bitnami/grafana-operator] Update CRD grafanas.integreatly.org

- bitnami/thanos/Chart.yaml
- bitnami/thanos/README.md
- bitnami/thanos/templates/receive/distributor.yaml
- bitnami/thanos/templates/receive/service.yaml
- bitnami/thanos/values.yaml
This change enables users of this chart to leverage the new deployment model of Thanos Receiver implemented in [Thanos v0.22](https://github.com/thanos-io/thanos/releases/tag/v0.22.0) by adding a `recevier.mode` to the `values.yaml` and additional configurations for the `distributor` deployment. 
**Benefits**
See [this](https://github.com/thanos-io/thanos/blob/release-0.22/docs/proposals-accepted/202012-receive-split.md) for benefits of the receiver dual-mode implementation. 
Turning on the dual-mode implementation will reroute the receive service to point to the distributor. This means that there would be no service in front of the ingestor receive pods (i.e. the StatefulSet), although the headless service will still exist. This …
> [bitnami/thanos] Thanos receiver dualmode

- bitnami/kibana/Chart.yaml
- bitnami/kibana/templates/deployment.yaml
- bitnami/kibana/values.yaml
Fixes issue caused by
```
- name: KIBANA_SERVER_TLS_USE_PEM
value: {{ ternary "true" "false" (or .Values.tls.usePemCerts (include "kibana.createTlsSecret" .)) | quote }}
```
Error message:
```console
$ helm install --dry-run test bitnami/kibana/ --set elasticsearch.hosts[0]=YOUR_ES_HOST,elasticsearch.port=YOUR_ES_PORT,tls.usePemCerts=true
Error: template: kibana/templates/deployment.yaml:95:109: executing "kibana/templates/deployment.yaml" at <.>: wrong type for value; expected bool; got string
```
- fixes #7410 
None known.
**Checklist**
> [bitnami/kibana] Fix KIBANA_SERVER_TLS_USE_PEM

- bitnami/elasticsearch/Chart.lock
- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/templates/ingest-statefulset.yaml
- bitnami/elasticsearch/values.yaml
When the security and ingest node is enabled, an indent problem occurs in the volumes area for ingest-statefulset.yaml. This problem has been fixed.
<pre>
helm install elastic bitnami/elasticsearch --dry-run --debug --set security.enabled=true --set ingest.enabled=true --set security.tls.autoGenerated=true
Error: YAML parse error on elasticsearch/templates/ingest-statefulset.yaml: error converting YAML to JSON: yaml: line 147: did not find expected key
</pre>
There is no drawbacks
**Checklist**
> [bitnami/elasticsearch] Fixed indent problem on ingest statefulset

- bitnami/magento/Chart.yaml
- bitnami/magento/README.md
- bitnami/magento/templates/deployment.yaml
- bitnami/magento/values.yaml
Add a separate parameter `extraContainerPorts` to expose custom ports of the Magento container.
This is especially useful if a custom image is used.
Furthermore there's already an `extraContainerPorts` parameter for the Magento service, so this change completes the current configuration options.
**Benefits**
The chart doesn't has to be forked and customized but can be easily configured with the `extraContainerPorts` variable.
Unknown (probably none).
**Additional Information:**
This PR is based on the [`extraContainerPorts` PR](https://github.com/bitnami/charts/pull/7193) for [bitnami/wordpress]. 
**Checklist**
> Add "extraContainerPorts" parameter

- bitnami/airflow/Chart.yaml
- bitnami/airflow/templates/config/configmap.yaml
This PR allows setting custom resource limits and requests based on the `worker.resources.limits` and `worker.resources.requests` parameters for workers when using  the 'k8s-executor'.
**Benefits**
Flexibility
None
- fixes https://github.com/bitnami/charts/issues/7446
N/A
**Checklist**
> [bitnami/airflow] Worker resources to be customizable using 'k8s-executor'

- bitnami/oauth2-proxy/Chart.yaml
- bitnami/oauth2-proxy/templates/ingress.yaml
This adds quotes around the host to allow wildcard hosts. Currently trying to set a wildcard host results in an error:
`Error: YAML parse error on oauth2-proxy/templates/ingress.yaml: error converting YAML to JSON: yaml: line 15: did not find expected alphabetic or numeric character`
Currently this is possible for the extrahosts field.
**Benefits**
It adds quotes around the hostname.
Personally I don't see any
**Checklist** 
- [x ] Variables are documented in the README.md
- [x ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
> [bitnami/oauth2-proxy] add quotes around host to allow wildcard host

- bitnami/metrics-server/Chart.yaml
- bitnami/metrics-server/README.md
- bitnami/metrics-server/templates/auth-delegator-crb.yaml
- bitnami/metrics-server/templates/cluster-role.yaml
- bitnami/metrics-server/templates/deployment.yaml
- bitnami/metrics-server/templates/metrics-api-service.yaml
- bitnami/metrics-server/templates/metrics-server-crb.yaml
- bitnami/metrics-server/templates/pdb.yaml
- bitnami/metrics-server/templates/role-binding.yaml
- bitnami/metrics-server/templates/serviceaccount.yaml
- bitnami/metrics-server/templates/svc.yaml
- bitnami/metrics-server/values.yaml
Adds `commonLabels` and `commonAnnotations` to all components of the `metrics-server`
**Benefits**
In multi-tenant environments, provides filtering, ownership and auditing capabilities to distinguish `metrics-server` from other apps.
Leveraged the work done in https://github.com/bitnami/charts/pull/6864 to be consistent across charts.
**Checklist**
> [bitnami/metrics-server] Add commonLabels and commonAnnotations 

- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/templates/_helpers.tpl
- bitnami/elasticsearch/templates/coordinating-statefulset.yaml
- bitnami/elasticsearch/templates/data-statefulset.yaml
- bitnami/elasticsearch/templates/ingest-statefulset.yaml
- bitnami/elasticsearch/templates/master-statefulset.yaml
Hi guys,
I found bug with sysctl init container.
If node have greater value of some options, than this chart set, it will be overwritten, so I made this PR for fix this behavior.
**Checklist**
> [bitnami/elasticsearch] fix sysctl set options

- bitnami/dataplatform-bp2/Chart.lock
- bitnami/dataplatform-bp2/Chart.yaml
- bitnami/dataplatform-bp2/README.md
- bitnami/magento/Chart.lock
- bitnami/magento/Chart.yaml
- bitnami/magento/README.md
This PR updates Elasticsearch subchart for `bitnami/magento` and `bitnami/dataplatform-bp2`.
**Checklist**
> [bitnami/*] Bump Elasticsearch subchart dependency

- bitnami/external-dns/Chart.yaml
- bitnami/external-dns/templates/deployment.yaml
The property is called "secretName" rather than "name".
```
Message:     error validating data: ValidationError(Deployment.spec.template.spec.volumes[0].secret): unknown field "name" in io.k8s.api.core.v1.SecretVolumeSource
```
https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#secretvolumesource-v1-core
**Benefits**
- fixes #
**Checklist**
> [bitnami/external-dns] Fix transip SecretVolumeSource

- bitnami/minio/Chart.yaml
- bitnami/minio/templates/ingress.yaml
- bitnami/minio/templates/service.yaml
- bitnami/minio/templates/servicemonitor.yaml
Changes the ServiceMonitor target port to `minio-api` and renames the service port name to make it easier to differentiate from `minio-console`.
Additionally, fixes an issue with the ingress aiming to the MinIO API port, when it should be aiming for the MinIO console.
The ingress change will prioritize exposing the Web UI over the MinIO API.
Exposing the API via ingress would require additional configuration.
- fixes #7474
**Checklist**
> [bitnami/minio] Fix ServiceMonitor, rename service port and ingress

- bitnami/etcd/Chart.yaml
- bitnami/etcd/templates/NOTES.txt
In the etcd chart, the `kubectl exec -it ...` example shown in chart notes was missing the `--namespace` argument
**Benefits**
The chart notes will now work for users who do not deploy the etcd chart in their default namespace
**Checklist**
> [bitnami/etcd] fix kubectl exec example in chart notes

- bitnami/memcached/Chart.yaml
- bitnami/memcached/README.md
- bitnami/memcached/templates/statefulset.yaml
- bitnami/memcached/values.yaml
Chart doesn't allow configuration of liveness and readiness probe sections of the metrics container. This PR adds support to allow it.
**Benefits**
We've noticed quite often in our deployments where the readiness probe of the metrics container failed to report in time causing kubernetes to stop traffic to both memcached and metrics container.  Configuring timeoutSeconds & failureThreshold directly on the resource mitigated this problem for us.
Making these fields configurable allows the end user to tweak the probe behaviour
-
- fixes #
**Checklist**
> [bitnami/memcached] Make liveness and readiness probe configurable

- bitnami/memcached/Chart.yaml
- bitnami/memcached/templates/statefulset.yaml
statefulset template uses incorrect variable `{{- if .Values.livenessProbe.enabled }}`
This change fixes it
**Benefits**
Bugfix
NA
- fixes #
**Checklist**
> [bitnami/memcached] Correct probe template variable

- bitnami/common/README.md
Fix documentation bug/typo.
**Benefits**
No typo in documentation.
None
**Checklist**
> bitname/common: Fix typo in README

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
Rename the init container changing TLS permissions to `init-chmod-tls`.
**Benefits**
The `init-chmod-tls` init container can be used alongside the `init-chmod-data` init container.
- fixes #7522
**Checklist**
> [bitnami/postgresql-ha]  Rename of the tls init container - fixes #7522

- bitnami/drupal/Chart.lock
- bitnami/drupal/Chart.yaml
- bitnami/drupal/README.md
- bitnami/drupal/templates/ingress.yaml
- bitnami/drupal/values.yaml
Changes introduced at https://github.com/bitnami/charts/pull/7512 are not following our standard metadata format (`nil` value VS empty string):
```console
$ readme-generator -v ./values.yaml -m /tmp/metadata.json
Skipping check for hostAliases[0].ip
Skipping check for hostAliases[0].hostnames[0]
Skipping check for containerPorts.http
Skipping check for containerPorts.https
Skipping check for resources.requests.memory
Skipping check for resources.requests.cpu
Skipping check for service.nodePorts.http
Skipping check for service.nodePorts.https
Skipping check for metrics.podAnnotations.prometheus.io/scrape
Skipping check for metrics.podAnnotations.prometheus.io/port
INFO: Checking missing metadata...
INFO: Metadata is correct! …
```
> [bitnami/drupal] Fix ingressClassName default parameter and template

- bitnami/minio/Chart.lock
- bitnami/minio/Chart.yaml
- bitnami/minio/README.md
- bitnami/minio/templates/NOTES.txt
- bitnami/minio/templates/api-ingress.yaml
- bitnami/minio/templates/distributed/statefulset.yaml
- bitnami/minio/templates/gateway/deployment.yaml
- bitnami/minio/templates/standalone/deployment.yaml
- bitnami/minio/values.yaml
Adds a secondary ingress, that would allow users to expose the MinIO API in addition to the MinIO console.
Additionally, fixes a bug that configures MINIO_CONSOLE_PORT to match the value `containerPorts.console`.
None known.
- fixes #7495
**Checklist**
> [bitnami/minio] Add CONSOLE_PORT parameter and API ingress

- bitnami/solr/Chart.yaml
- bitnami/solr/templates/exporter-deployment.yaml
- bitnami/solr/templates/exporter-svc.yaml
- bitnami/solr/templates/statefulset.yaml
- bitnami/solr/templates/svc-headless.yaml
- bitnami/solr/templates/svc.yaml
Renaming `targetPort`  value.
**Benefits**
Provide a "painless" solution for Container Native Loadbalancing on GKE before [kubernetes/ingress-gce/pull/1462](https://github.com/kubernetes/ingress-gce/pull/1462) lands.
External references to old values. If this is a concern, one could still introduce a helm value defaulting to old values while allowing those affected to override using `http`.
n/a
**Checklist**
> [bitnami/solr] : Workaround/Fix for GCE Ingress

- githooks/pre-push/helm-lint
When running the `helm-lint` githook, we're currently updating every configured chart repository when we update the chart dependencies:
```console
Updating dependencies for bitnami/foo with helm dep update:
Hang tight while we grab the latest from your chart repositories...
...Successfully got an update from the "xxx" chart repository
...Successfully got an update from the "yyy" chart repository
...Successfully got an update from the "zzz" chart repository
...
...Successfully got an update from the "bitnami" chart repository
```
This changes ensure that only the "bitnami" chart repository is updated, saving time everytime the hook is executed.
**Benefits**
Speed
None …
> Reduce time needed to update chart dependencies

- bitnami/spring-cloud-dataflow/Chart.yaml
- bitnami/spring-cloud-dataflow/templates/server/configmap.yaml
Adding Spring Cloud Task closecontextEnabled as true in spring-cloud-data-flow server configmap.yaml
**Benefits**
Verified settings work on local minikube cluster for Composed Task parent Pod changing to Completed instead of Running, after all child Tasks finishes.
- fixes #https://github.com/bitnami/charts/issues/7539
**Checklist**
> [bitnami/spring-cloud-dataflow] 7539 - add spring cloud task closecontext enabled

- bitnami/minio/Chart.yaml
- bitnami/minio/templates/api-ingress.yaml
- bitnami/minio/values.yaml
When https://github.com/bitnami/charts/pull/7526 was merged, the `apiIngress` and `ingress` were set to the same name. This causes issues when both are enabled and a user tries to run an upgrade. Second issue it created was only one ingress can be added at a time.
**Benefits**
Let's the user create both ingresses simultaneously and does not cause issues during the upgrade
- fixes #7526
**Checklist**
> [bitnami/minio] fix: ingress name and port

- bitnami/dataplatform-bp2/Chart.lock
- bitnami/dataplatform-bp2/Chart.yaml
- bitnami/dataplatform-bp2/README.md
- bitnami/dataplatform-bp2/templates/_helpers.tpl
- bitnami/dataplatform-bp2/templates/emitter-deployment.yaml
- bitnami/dataplatform-bp2/templates/emitter-svc.yaml
- bitnami/dataplatform-bp2/templates/exporter-deployment.yaml
- bitnami/dataplatform-bp2/templates/exporter-svc.yaml
- bitnami/dataplatform-bp2/templates/role.yaml
- bitnami/dataplatform-bp2/templates/rolebinding.yaml
- bitnami/dataplatform-bp2/templates/serviceaccount.yaml
- bitnami/dataplatform-bp2/values.yaml
1. Add Deployment and Service for Data Platform Metrics Emitter and Prometheus Exporters to the chart (enabled by default)
2. Add ServiceAccount, RBAC creation by default for the data platform
**Benefits**
Prometheus exporter emits Health Metrics for the data platform
NA
- fixes #
**Checklist**
> bitnami/dataplatform-bp2 Add Data Platform Metrics Emitter and Prometheus Exporters

- bitnami/rabbitmq-cluster-operator/Chart.yaml
- bitnami/rabbitmq-cluster-operator/templates/extra-list.yaml
Add missing `extra-list.yaml` manifest required for `extraDeploy` feature to work properly.
**Benefits**
`extraDeploy` feature is available
None
N/A
N/A
**Checklist**
> [bitnami/rabbitmq-cluster-operator] Add missing extra-list.yaml

- bitnami/contour/Chart.yaml
- bitnami/contour/README.md
- bitnami/contour/templates/envoy/service.yaml
These changes enable the SSL termination on the AWS NLB side instead of using `nodePort` which brings security issues and didn't work for private Kubernetes clusters.
**Benefits**
Make easier to people change the value of `targetPort` from __https__ to **http** to enable SSL termination on AWS ELB.
None.
- fixes #
**Checklist**
> [bitnami/contour] - 7571 Add targetPort as values to aws nlb ssl termination

- bitnami/airflow/Chart.yaml
- bitnami/airflow/README.md
- bitnami/airflow/templates/NOTES.txt
- bitnami/airflow/templates/_helpers.tpl
- bitnami/airflow/templates/config/secret.yaml
- bitnami/airflow/values.yaml
This change use the new airflow containers which ask for a new value as parameter called auth.secretKey. It fix a problem fetching logs from worker nodes:
**Benefits**
It will allow to the user to watch logs in the UI like this:
There is not known drawbacks.
- fixes #7167
**Checklist**
> [bitnami/airflow] Fix cannot fetch logs in worker nodes

- README.md
This PR adds a badge in the main README pointing to the Bitnami organization in the ArtifactHub
> Add ArtifactHub badge to the main charts README

- bitnami/keycloak/Chart.yaml
- bitnami/keycloak/README.md
- bitnami/keycloak/templates/statefulset.yaml
- bitnami/keycloak/values.yaml
**Describe the scope of your change - i.e. what the change does.**
We saw that the startup time when using the Keycloak helm chart is very long, because already the configuration generation and testing takes up to a minute.
startupProbe is a new pod feature enabled by default since Kubernetes 1.18.x. It allows pods to be faster ready, because you can set initialDelaySeconds to 0 for livenessProbe and readinessProbe.
livenessProbe and readinessProbe will wait until the startupProbe has succeeded.
This change adds the new configuration options startupProbe (with sub keys) and customStartupProbe.
**Describe any known limitations with your change.**
startupProbe is not available ot not enabled by default before Kubernetes 1.18.x, that's why I've disabled it by default for this chart.
**Please …
> [bitnami/keycloak] Implement support for startupProbe for faster pod startups

- bitnami/grafana/Chart.yaml
- bitnami/grafana/README.md
- bitnami/grafana/templates/deployment.yaml
- bitnami/grafana/values.yaml
Add scheme option to readiness and liveness probes. Default value is HTTP. Optional value is HTTPS.
**Benefits**
Gives you the option to set the probe scheme to HTTPS if you configure grafana to use SSL/TLS.
None
- fixes #7611
**Checklist**
> bitnami/grafana - Configure scheme probe

- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/templates/svc-cluster-external-access.yaml
As it is possible to do at mongodb chart, the targetPod variable is usefull to create custom annotations and labels to specific pod, this simple change just add this possibility 
**Benefits**
Create labels and annotations to specific instance of redis
I can't see any drawbacks
An simple appplication is to use external-dns in to create an dns entry to specific instance, with annotation
```external-dns.alpha.kubernetes.io/hostname: "{{`{{ .targetPod }}`}}.example.com```
**Checklist**
> [bitnami/redis-cluster] possibility to use targetPod on labels and annotations at externalAccess

- bitnami/phabricator/Chart.yaml
- bitnami/phabricator/README.md
- bitnami/phabricator/templates/NOTES.txt
- bitnami/phabricator/values.yaml
Phabricator helm chart will be deprecated since the upstream project has been [discontinued](https://admin.phacility.com/phame/post/view/11/phacility_is_winding_down_operations/) and no new features. 
**Checklist**
> [stable/phabricator] Mark Phabricator chart as deprecated

- bitnami/common/Chart.yaml
- bitnami/common/README.md
- bitnami/common/templates/_capabilities.tpl
This PR adds a new capability helper for Network Policies: "common.capabilities.networkPolicy.apiVersion"
**Benefits**
Reuse logic that we currently duplicate in several charts, see:
```console
$ ag -l "networkPolicy.apiVersion" bitnami/**/templates/_helpers.tpl
bitnami/cassandra/templates/_helpers.tpl
bitnami/etcd/templates/_helpers.tpl
bitnami/influxdb/templates/_helpers.tpl
bitnami/metallb/templates/_helpers.tpl
bitnami/mysql/templates/_helpers.tpl
bitnami/nats/templates/_helpers.tpl
bitnami/postgresql-ha/templates/_helpers.tpl
bitnami/postgresql/templates/_helpers.tpl
bitnami/redis-cluster/templates/_helpers.tpl
bitnami/redis/templates/_helpers.tpl
``` 
None
N/A …
> [bitnami/common] Add new capability helper for Network Policies

- bitnami/kubeapps/Chart.yaml
- bitnami/kubeapps/values.schema.json
The current code (since https://github.com/bitnami/charts/pull/7656) is failing during the packaging:
```console
$ helm package .
Error: failed to save: Invalid JSON in values.schema.json
```
once fixed the JSON format everything works as expected:
```console
helm package .
Successfully packaged chart and saved it to: /home/bitnami/projects/charts/charts/bitnami/kubeapps/kubeapps-7.5.4.tgz
```
> [bitnami/kubeapps] Fix values.schema.json

- bitnami/contour/Chart.yaml
- bitnami/contour/README.md
- bitnami/contour/templates/envoy/daemonset.yaml
- bitnami/contour/templates/envoy/deployment.yaml
- bitnami/contour/values.yaml
Make envoy minReadySeconds configurable
**Benefits**
Let users override `minReadySeconds` value of envoy Deployment or DaemonSet.
None
None
None
**Checklist**
> [bitnami/contour] Make envoy minReadySeconds configurable

- bitnami/nginx-ingress-controller/Chart.lock
- bitnami/nginx-ingress-controller/Chart.yaml
- bitnami/nginx-ingress-controller/templates/clusterrole.yaml
- bitnami/nginx-ingress-controller/templates/role.yaml
- bitnami/nginx-ingress-controller/values.yaml
In #7485 the `extensions` apiGroup was removed from the role and clusterrules rules. They shouldn't have been removed as we are still supporting `apiGroup: extensions` in `podsecuritypolicy.yaml`
**Benefits**
Fixes removed support for old `apiGroups`.
None
**Checklist**
> [bitnami/nginx-ingress-controller] Revert 7485 apiGroup change

- bitnami/jenkins/Chart.lock
- bitnami/jenkins/Chart.yaml
- bitnami/jenkins/templates/servicemonitor.yaml
- bitnami/jenkins/values.yaml
fix issue #7686 - port name issue on service monitor.
**Benefits**
Prometheus is able to get jenkins metrics with `metrics.serviceMonitor.enabled=true`.
Can't think of any at this point of time.
- fixes #7686
**Checklist**
> [bitnami/jenkins] - fix(jenkins): svc monitor port name differences fixed

- bitnami/memcached/Chart.yaml
- bitnami/memcached/templates/pdb.yaml
Adds the namespace to the PDB resource in the memcached chart.
**Benefits**
The PDB resource is created with the helm release's namespace and doesn't have to be overridden at deploy time.
- fixes #7682
Bump chart version as a path release as the PDB would not work if it was placed in another namespace.
**Checklist**
> [bitnami/memcached] Fix namespace on PDB resource.

- bitnami/thanos/Chart.yaml
- bitnami/thanos/values.yaml
This PR changes the default deployment strategy of Thanos compactor Deployment from `RollingUpdate` to `Recreate`.
**Benefits**
The Thanos compactor Deployment contains two volume mounts by default (https://github.com/bitnami/charts/blob/master/bitnami/thanos/templates/compactor/deployment.yaml#L134). This makes the `RollingUpdate` strategy unsuitable as a new pod cannot be created as long as the old pod is running. The `RollingUpdate` strategy results in
```
Multi-Attach error for volume "pvc-0a8b96f5-249f-4708-8c7d-51c2538d647d" Volume is already used by pod(s) thanos-compactor-7d4dbdf4f9-kgt9j
```
errors. A `Recreate` deployment strategy, waits for the old pod to terminate before starting a new one, avoiding the attempt to mount the PVCs twice.
**Possible …
> bitnami/thanos: Switch deployment strategy to 'Recreate'

- bitnami/contour-operator/.helmignore
- bitnami/contour-operator/Chart.lock
- bitnami/contour-operator/Chart.yaml
- bitnami/contour-operator/README.md
- bitnami/contour-operator/crds/crd-backendpolicy.yaml
- bitnami/contour-operator/crds/crd-contour.yaml
- bitnami/contour-operator/crds/crd-contourconfiguration.yaml
- bitnami/contour-operator/crds/crd-contourdeployment.yaml
- bitnami/contour-operator/crds/crd-extensionservice.yaml
- bitnami/contour-operator/crds/crd-gateway.yaml
- bitnami/contour-operator/crds/crd-gatewayclass.yaml
- bitnami/contour-operator/crds/crd-httpproxy.yaml
- bitnami/contour-operator/crds/crd-httproute.yaml
- bitnami/contour-operator/crds/crd-tcproute.yaml
- bitnami/contour-operator/crds/crd-tlscertificatedelegation.yaml
- bitnami/contour-operator/crds/crd-tlsroute.yaml
- bitnami/contour-operator/crds/crd-udproute.yaml
- bitnami/contour-operator/templates/NOTES.txt
- bitnami/contour-operator/templates/_helpers.tpl
- bitnami/contour-operator/templates/clusterrole.yaml
- bitnami/contour-operator/templates/clusterrolebinding.yaml
- bitnami/contour-operator/templates/deployment.yaml
- bitnami/contour-operator/templates/extra-list.yaml
- bitnami/contour-operator/templates/metrics-service.yaml
- bitnami/contour-operator/templates/role.yaml
- bitnami/contour-operator/templates/rolebinding.yaml
- bitnami/contour-operator/templates/service-account.yaml
- bitnami/contour-operator/templates/servicemonitor.yaml
- bitnami/contour-operator/values.yaml
This PR adds a Contour Operator chart based on the example operator upstream: https://github.com/projectcontour/contour-operator/blob/main/examples/operator/operator.yaml
**Checklist**
> [bitnami/contour-operator] Add Contour Operator chart

- bitnami/minio/Chart.yaml
- bitnami/minio/templates/distributed/statefulset.yaml
- changes the `minio-console` port used by all the minio-pod probes to `minio-api`
**Benefits**
- startup is failing, and pods are going in `CrashLoop`, if probes keeps failing
- probes keep failing due to waiting for results from wrong port
- N/A
- fixes #https://github.com/bitnami/charts/issues/7657
**Checklist**
> [bitnami/minio] readinessProbe, startupProbe and LivenessProbe needs minio-api port

- bitnami/apache/Chart.yaml
- bitnami/apache/README.md
- bitnami/apache/templates/deployment.yaml
- bitnami/apache/templates/hpa.yaml
- bitnami/apache/templates/pdb.yaml
- bitnami/apache/values.yaml
Introduce `autoscaling` and `pdb` options in the values file to create `HorizontalPodAutoscaler` and `PodDisruptionBudget` objects
**Benefits**
Allows Apache deployment to scale dynamically and limit the number of concurrent disruptions.
**Checklist**
> [bitnami/apache] Add Autoscaling and Disruption Budget options

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/health-configmap.yaml
Add logic to the health-configmap to omit the auth lines for the sentinel liveness check if `.Values.auth.sentinel` is `false`
**Benefits**
If auth is enabled for redis, but disabled for the sentinels, the sentinel liveness probe will fail and the pods will be killed due to using a password when one is not required.  The error message encountered is: `AUTH failed: ERR AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?`  Removing the lines for password env and file allow the pods to successfully pass the liveness check on the sentinel containers.
If auth is disabled, but sentinel auth is left as enabled, these lines will appear in the script.  However, the current …
> [bitnami/redis] Ignore auth for sentinel liveness if auth is disabled

- bitnami/apache/Chart.yaml
- bitnami/apache/README.md
- bitnami/apache/values.yaml
- bitnami/fluentd/Chart.yaml
- bitnami/fluentd/values.yaml
As part of https://github.com/bitnami/charts/pull/7979 and https://github.com/bitnami/charts/pull/7990, some parameters were added to the _values.yaml_ and **manually** added to the _README.md_; when executing the `readme-generator` tool, some inconsistencies appeared. The goal of this PR is to fix those inconsistencies.
> [bitnami/apache, bitnami/fluentd] Fix metadata used to generate README table

- bitnami/nats/Chart.yaml
- bitnami/nats/templates/configmap.yaml
There was a bug introduced in PR #7791 which requires excessive configuration:
```yaml
auth:
enabled: true
user: ""
users: any-value-works
usersCredentials:
- username: anonymous
password: anonymous
```
The configuration node `auth.users` is unnecessary and confusing.
The configuration should just be:
```yaml
auth:
enabled: true
user: ""
usersCredentials:
- username: anonymous
password: anonymous
```
**Benefits**
Simplifies the configuration of authentication user map.
**Checklist**
> [bitnami/nats] Rename configuration node for authentication user map

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/README.md
- bitnami/zookeeper/templates/poddisruptionbudget.yaml
- bitnami/zookeeper/values.yaml
Change apiVersion if kubeversion is "<1.21-0"
**Benefits**
remove deprecation warning
- fixes #7862
**Checklist**
> [bitnami/zookeeper] change pdb apiVersion in function of kubeVersion

- bitnami/grafana/Chart.yaml
- bitnami/grafana/templates/servicemonitor.yaml
Modify helm chart references.
**Benefits**
Fixes a nil pointer reference when configuring a servicemonitor.
Not known
```
metrics:
enabled: true
serviceMonitor:
enabled: true
```
```
Error: UPGRADE FAILED: template: grafana/templates/servicemonitor.yaml:20:16: executing "grafana/templates/servicemonitor.yaml"
at <.Values.serviceMonitor.jobLabel>: nil pointer evaluating interface {}.jobLabel
```
**Checklist**
> [bitnami/grafana] Fix servicemonitor nil pointer

- bitnami/tomcat/README.md
It seems **tomcatUser** is not a valid parameter name according to the parameter table showed in this README file.
This commit replaces **tomcatUser** to **tomcatUsername**.
> Update readme to correct parameter name.

- bitnami/nginx-ingress-controller/Chart.yaml
- bitnami/nginx-ingress-controller/README.md
- bitnami/nginx-ingress-controller/templates/NOTES.txt
Add upgrade notes for 9.0.0 explaining the major changes introduced in https://github.com/bitnami/charts/pull/7867
Update Ingress example in `NOTES.txt` replacing deprecated annotation with `spec.IngressClassName`.
**Benefits**
Better user experience.
Worse user experience.
Related to https://github.com/bitnami/charts/issues/7817
**Checklist**
> [bitnami/nginx-ingress-controller] add upgrade notes for 9.0.0 and update example in NOTES.txt

- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/README.md
- bitnami/redis-cluster/values.yaml
The TLS Certificate generation uses .Values.clusterDomain
which is not defined thus in the generated certificate SAN
field you will values like: %!s(<nil>)
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
**Benefits**
TLS Certificate SANs will not contain entries like `%!s(<nil>)`
`N/A`
- fixes #8032
**Checklist**
> [bitnami/redis-cluster] fix missing clusterDomain variable

- bitnami/contour/Chart.yaml
- bitnami/contour/templates/_helpers.tpl
- bitnami/contour/templates/contour/deployment.yaml
- bitnami/contour/templates/default-backend/ingress.yaml
As @Legion2 mentioned in #8041, adding `--ingress-class-name` to controller argument breaks previous deployments, since it enables controller to filter Ingresses and HTTPProxies.
**Benefits**
Users can deploy contour as a default (implicit) cluster ingress controller.
None
- Fixes #8041
- Related to https://github.com/projectcontour/contour/issues/4134
Since there was a possible breaking change in #7668, I think it makes sense to applying this patch to `v5.x`.
Could anyone give an opinion? 🙇 
**Checklist**
> [bitnami/contour] Allow deploying without explicit IngressClass

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/hidden/statefulset.yaml
- bitnami/mongodb/templates/replicaset/statefulset.yaml
- bitnami/mongodb/templates/standalone/dep-sts.yaml
This PR fixes an issue reported by @mtimm and introduced by me at https://github.com/bitnami/charts/pull/7930.
There's a condition that's not taken into account the users & dbs set at `auth.usernames` and `auth.databases` to decide whether to set the `MONGODB_EXTRA_PASSWORDS` env. var or not.
**Benefits**
Users can add use `auth.usernames` and `auth.passwords` without requiring to set deprecated `auth.username` and `auth.database` parameters.
None
- fixes https://github.com/bitnami/charts/issues/8063
**Checklist**
> [bitnami/mongodb] Fix custom passwords

- bitnami/logstash/Chart.yaml
- bitnami/logstash/README.md
- bitnami/logstash/values.yaml
The metrics service is headless by default, which doesn't make much sense.
- fixes #8029 
**Checklist**
> [bitnami/logstash] Make metrics service non-headless

- bitnami/node/Chart.lock
- bitnami/node/Chart.yaml
- bitnami/node/templates/deployment.yaml
- bitnami/parse/Chart.lock
- bitnami/parse/Chart.yaml
- bitnami/parse/templates/server-deployment.yaml
#7930 changed MongoDB's password key from `mongodb-password` to `mongodb-passwords`. This PR updates the key in the charts that use it.
**Checklist**
> [bitnami/node] [bitnami/parse] Fix mongodb password key

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/replicaset/statefulset.yaml
This PR fixes a bug in the MongoDB Helm chart, where TLS doesn't work, when a user specified a value for `service.nameOverride` in the values file. When this property is set, the generated certificates are not working because, the certificate does not match the host name:
```
2021-11-10T08:18:39.984+0000 E  NETWORK  [Replication] The server certificate does not match the host name. Hostname: mongodb-rs-1.mongodb-rs.default.svc.cluster.local does not match SAN(s): mongodb-rs-headless, mongodb-rs-1, mongodb-rs-1.mongodb-rs-headless.default.svc.cluster.local, localhost, 127.0.0.1, CN: mongodb-rs-1
```
```yaml
service:
nameOverride: mongodb-rs
```
**Benefits**
This allows users to use TLS when `service.nameOverride` was set.
I think there …
> [bitnami/mongodb] Fix service name in TLS init container

- bitnami/thanos/Chart.yaml
- bitnami/thanos/README.md
- bitnami/thanos/templates/receive-distributor/serviceaccount.yaml
- bitnami/thanos/values.yaml
Adds the `receiveDistributor.enabled` field to the values and to the readme. 
It also fixes the deployment of the Receiver Distributor, as prior to this change, one would get this on a clean install where it is enabled.:
```
Error: UPGRADE FAILED: failed to create resource: ServiceAccount "thanos-receiveDistributor" is invalid: metadata.name: Invalid value: "thanos-receiveDistributor": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is 'a-z0-9?(\.a-z0-9?)*')
```
**Benefits**
Enabling the distributor works.
N/A
N/A
**Checklist**
> [bitnami/thanos] Fix Receiver Distributor

- bitnami/grafana/Chart.yaml
- bitnami/grafana/templates/deployment.yaml
Using the default [values.yaml](https://github.com/bitnami/charts/blob/master/bitnami/grafana/values.yaml) file with `extraVolumes` and `extraVolumeMounts` options enabled:
```
extraVolumes:
- name: my-volume
emptyDir: {}
##
extraVolumes: []
extraVolumeMounts:
- name: my-volume
mountPath: /opt/bitnami/grafana/my-stuff
```
Results in the following
```bash
$ helm install \
grafana 
--dry-run 
--namespace grafana\
--values values.yaml \
bitnami/grafana
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec.template.spec.containers[1]): unknown field "mountPath" in io.k8s.api.core.v1.Container
```
This change address the validation errors for the deployment …
> Grafana - fix indentation in deployment template for extraVolumeMounts

- bitnami/haproxy/Chart.yaml
- bitnami/haproxy/README.md
- bitnami/haproxy/templates/service.yaml
- bitnami/haproxy/values.yaml
Add service.labels input to the bitnami/haproxy chart to allow custom labels to be passed to the service.
**Benefits**
Currently the only way to accomplish a user specified label on the HAProxy service is to use `commonLabels` which also adds the label to all other Kubernetes resources created in the chart. This addition allows for a more intuitive solution.
- Adds more inputs to the chart
My use case is that I'm using a label selector in our external-dns controller to control which resources it creates records for. Creation is opt-in via a specific label. My current workaround for this haproxy chart is to use the commonLabels value to add the label to  each resource in the installation. …
> [bitnami/haproxy] Add service.labels input

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/NOTES.txt
- bitnami/redis/templates/scripts-configmap.yaml
Proposed fix for https://github.com/bitnami/charts/issues/7869.
Replace all instances of:
```bash
redis-cli -a <password>
```
With:
```bash
REDISCLI_AUTH=<password> redis-cli
```
This fixes cases of passwords being printed to the logs when logging commands, and also avoids `redis-cli` warning about the `-a` option.
**Benefits**
- No longer leaks password in logs.
- Avoids warnings from redis-cli by eliminating `-a`.
n/a
- fixes https://github.com/bitnami/charts/issues/7869
This is my first PR to this project, please let me know if there's anything missing!
**Checklist**
> bitnami/redis: Specify password via REDISCLI_AUTH to avoid leaking password via logs

- bitnami/mariadb-galera/Chart.yaml
- bitnami/mariadb-galera/templates/statefulset.yaml
This is a continuation of my other PR over at https://github.com/bitnami/bitnami-docker-mariadb-galera/pull/53. As such, this PR should only be merged after the other one got merged, because it will be useless (but in no way harmful!) on its own.
Please especially read my comment https://github.com/bitnami/bitnami-docker-mariadb-galera/pull/53#issuecomment-867910704. 
Many people may not know it, but when not using specifying a value for `galera.bootstrap.bootstrapFromNode`, the first node of the StatefulSet deployed by this chart bootstraps "implicitly". This happens because the container tries to... be smart. Let's leave it at that, because detailed explanations can be found at the linked PR. 
Unfortunately, sometimes the container is just not smart enough. …
> Explicitly only bootstrap the node specified by `galera.bootstrap.bootstrapFromNode`

- bitnami/minio/Chart.yaml
- bitnami/minio/templates/networkpolicy.yaml
- bitnami/minio/values.yaml
Currently if `networkPolicy.allowExternal` is `false` the `podSelector` added in the `from` clause allows connection from Pods having pre-defined labels, which is not always applicable/desiderable.
This PR adds the possibility for for additional `from` clauses in `NetworkPolicy` to add custom behavior.
**Benefits**
This PR adds the possibility for for additional `from` clauses in `NetworkPolicy` to add custom behavior.
- fixes #
**Checklist**
> [bitnami/minio] allow additional from clauses in NetworkPolicy

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/templates/svc-headless.yaml
Set publishNotReadyAddresses to true in headless service, according to https://www.rabbitmq.com/cluster-formation.html#peer-discovery-k8s: `On the headless service spec, field publishNotReadyAddresses must be set to true`.
Pods in the StatefulSet should have their addresses published even before they're ready, since they have to be able to talk to each other to join the cluster in order to become ready, otherwise split brain will occur when creating cluster.
Replaces https://github.com/bitnami/charts/pull/7438
**Benefits**
- fixes #
**Checklist**
> bitnami/rabbitmq: Set publishNotReadyAddresses to true in headless service.

- bitnami/mariadb/Chart.yaml
- bitnami/mariadb/README.md
- bitnami/mariadb/values.yaml
Changes the `values.yaml` (and the generated `README.md`) to use `existingConfigmap` key instead of `existingConfiguration` to specify a custom configuration map for MariaDB configuration.
**Benefits**
The existing MariaDB chart actually use the `existingConfigmap` key to check for and use a custom configuration map to deploy the database configuration. The `values.yaml` and `README.md` files were actually out-of-sync.
The semantic version has not been upgraded as it's more of a documentation fix and it should not have any impact on existing deployments.
As it is more of a documentation fix, there shouldn't be any impact on production. There may be some confusion though if one used the old key and expected it to work.
**Applicable …
> fix(mariadb): use proper configuration map

- bitnami/contour/Chart.yaml
- bitnami/contour/values.yaml
This fixes #8162. Port 8080 and 8443 are the same as Contour is using:
https://github.com/projectcontour/contour/pull/3393
https://github.com/projectcontour/contour/pull/4084
Envoy is already running as `runAsUser: 1001`, the default containerPorts 80/443 do not work anymore...
https://github.com/bitnami/charts/blob/84f366af1d4c4eb5e31b27ccec84076dc3ca9bf1/bitnami/contour/values.yaml#L584
See #8162 for a more detailed example. 
Changing the containerPorts to be > 1024 using the same values as Contour does. 
**Benefits**
Envoy ingress is accepting calls again. 
n/a
- fixes #8162
**Checklist**
> [bitnami/contour]fix:Changing envoy containerPorts for http & https to > 1024 range

- bitnami/discourse/README.md
- bitnami/dokuwiki/README.md
- bitnami/drupal/README.md
- bitnami/ghost/README.md
- bitnami/jasperreports/README.md
- bitnami/joomla/README.md
- bitnami/magento/README.md
- bitnami/mediawiki/README.md
- bitnami/metallb/README.md
- bitnami/moodle/README.md
- bitnami/node/README.md
- bitnami/odoo/README.md
- bitnami/opencart/README.md
- bitnami/orangehrm/README.md
- bitnami/osclass/README.md
- bitnami/owncloud/README.md
- bitnami/phpbb/README.md
- bitnami/phpmyadmin/README.md
- bitnami/prestashop/README.md
- bitnami/redmine/README.md
- bitnami/suitecrm/README.md
The Helm charts affected by this PR are marked as a community-supported solution. This means that the Bitnami team is not actively working on new features/improvements nor providing support through GitHub Issues for those Helm charts.
> [bitnami/several] Add 'community support' note to some Helm chart READMEs

- bitnami/spark/Chart.yaml
- bitnami/spark/README.md
"Submitting Applications to Kubernetes" uses a
k8s://https://<k8s-apiserver-host>:<k8s-apiserver-port>
for the --master arg, to submit jobs vis-a-vis the kube-apiserver.
Ref: https://spark.apache.org/docs/latest/running-on-kubernetes.html#submitting-applications-to-kubernetes
> [bitnami/spark] Update spark-submit example inline with Spark docs

- bitnami/etcd/Chart.yaml
- bitnami/etcd/templates/statefulset.yaml
We're using `.Values.service.*` parameters to set the the _ETCD_LISTEN_*_  environment variables. This is conceptually wrong since these parameters refer to the etcd service port instead of the container ports. We should use `.Values.containerPorts.*` parameters to customize container ports.
**Benefits**
Correct use of `.Values.service.*` and `.Values.containerPorts.*` parameters.
None
N/A
N/A
**Checklist**
> [bitnami/etcd] ETCD_LISTEN_* to use container ports instead of svc ports

- bitnami/etcd/Chart.yaml
- bitnami/etcd/templates/statefulset.yaml
- bitnami/etcd/templates/svc-headless.yaml
- bitnami/etcd/values.yaml
We recently adapted the chat so you can use a port different from 2379 as the "service port". However, this isn't working as expected since the headless svc should've been adapted to use the container port too (since this svc is used to generate unique FQDN to access specific etcd pods).
Also, the `ETCD_ADVERTISE_CLIENT_URLS` env. var has been adapted so it advertised both the URL to access etcd through the service and the URL to access etcd by addressing the pod's hostname directly.
**Benefits**
User can set a custom svc port
None
N/A
Follow up from https://github.com/bitnami/charts/pull/8180
**Checklist** 
- [x ] Title of the PR starts with …
> [bitnami/etcd] Fix etcd when using a custom svc port

- bitnami/redis/Chart.lock
- bitnami/redis/Chart.yaml
- bitnami/redis/README.md
- bitnami/redis/templates/master/statefulset.yaml
- bitnami/redis/templates/replicas/statefulset.yaml
- bitnami/redis/values.yaml
This PR allows users to provide a custom dataSource on the redis StatefulSets.
**Benefits**
The main reason people might want to set this is to be able to restore redis data from a [VolumeSnapshot](https://kubernetes.io/docs/concepts/storage/volume-snapshots/).
It's a pretty complex process to restore from backup. You have to delete the statefulset with cascade=false, then recreate it, then repeat to remove the dataSource line from the StatefulSet. So that may confuse users. But I figure they'll ignore this extra setting in the mountain of other settings :)
n/a
This code is already used in a few other charts like [sonarqube and wordpress](https://github.com/bitnami/charts/search?q=persiste …
> [bitnami/redis] Support custom dataSource to allow creating volumes from VolumeSnapshots

- bitnami/grafana/Chart.yaml
- bitnami/grafana/templates/configmap.yaml
- bitnami/grafana/templates/dashboard-provider.yaml
- bitnami/grafana/templates/deployment.yaml
- bitnami/grafana/templates/image-renderer-deployment.yaml
- bitnami/grafana/templates/image-renderer-service.yaml
- bitnami/grafana/templates/image-renderer-servicemonitor.yaml
- bitnami/grafana/templates/service.yaml
- bitnami/grafana/templates/serviceaccount.yaml
- bitnami/grafana/templates/servicemonitor.yaml
This PR adds`.Values.commonAnnotations` to more templates in the grafana chart. 
https://github.com/bitnami/charts/tree/master/bitnami/nginx-ingress-controller was used as a model
**Benefits**
Use case: adding an annotation like [reloader](https://github.com/stakater/Reloader) becomes possible with this change, where a deployment of grafana will restart the pods if there is a detected change in a defined configmap/secret. 
Similar to the nginx-ingress-controller chart above, it can add annotations to resources where they're not needed, but has no impact on the resource created. 
**Checklist**
> [bitnami/grafana] Add .Values.commonAnnotations to more templates

- bitnami/tomcat/Chart.yaml
- bitnami/tomcat/README.md
- bitnami/tomcat/templates/_helpers.tpl
- bitnami/tomcat/templates/networkpolicy.yaml
- bitnami/tomcat/values.yaml
Add networkpolicy support on tomcat chart. 
Networkpolicy control access to containerPort and containerExtraPorts, if metrics is enabled flow are not filtered and open from any source.
If the chart is deployed on a K8S cluster where default rule is deny all, we need to deployed a networkpolicy but it can be tedious. we want to have a chart allign with other ones to integrate a default netwokpolicy.
By default network policy is disable, but when it's enabled some change must be done to be work fine.
the good label and sometime the right namespaces selector must be added to each pod, want to reach the tomcat.
- fixes #
**Checklist**
> [bitnami/tomcat] Add networkpolicy support

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/README.md
- bitnami/grafana-operator/templates/grafana.yaml
- bitnami/grafana-operator/values.yaml
honor dashboardNamespaceSelector for multi namespace support
**Benefits**
possibility to enable or disable dashboard deployment from other namespaces
opt-in features
-
**Checklist**
> bitnami/grafana-operator add opt-in dashboardNamespaceSelector

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/templates/pdb.yaml
Use policy/v1 PodDisruptionBudget if available.
**Benefits**
Avoids warnings like `policy/v1beta1 PodDisruptionBudget is deprecated in Kubernetes v1.21+, unavailable in v1.25+`
- fixes #
**Checklist**
> [bitnami/rabbitmq] PodDisruptionBudget: support apiVersion policy/v1

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/README.md
- bitnami/mongodb/templates/arbiter/statefulset.yaml
- bitnami/mongodb/templates/hidden/statefulset.yaml
- bitnami/mongodb/templates/replicaset/statefulset.yaml
- bitnami/mongodb/templates/standalone/dep-sts.yaml
- bitnami/mongodb/values.yaml
This PR adds a new value to set the `--tlsMode` for MongoDB, which is currently hard coded to `requireTLS`.
**Benefits**
Currently it is not possible to set the `tlsMode` for MongoDB when TLS is enabled. When we want to set the `tlsMode` via `extraFlags` value, the following error is thrown by MongoDB: `Error parsing command line:  Multiple occurrences of option "--tlsMode"`
There shouldn't be any drawbacks, the default is still `requireTLS`.
- fixes #
**Checklist**
> [bitnami/mongodb] Add value for tlsMode

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/hidden/statefulset.yaml
- bitnami/mongodb/templates/replicaset/statefulset.yaml
- bitnami/mongodb/templates/standalone/dep-sts.yaml
This fixes a bug with the new tls mode value introduced in https://github.com/bitnami/charts/pull/8214, where the value wasn't rendered correctly.
**Benefits**
- fixes #
**Checklist**
> [bitnami/mongodb] Fix tls mode value

- bitnami/grafana-tempo/Chart.yaml
- bitnami/grafana-tempo/README.md
- bitnami/grafana-tempo/values.yaml
For consistency, the volume folder should be /bitnami/grafana-tempo instead of /bitnami/tempo-grafana. This will also fix the issue with the latest Grafana Tempo release. 
**Benefits**
- fixes #
**Checklist**
> [bitnami/grafana-tempo] Fix incorrect data folder

- bitnami/mariadb/Chart.yaml
- bitnami/mariadb/templates/secondary/statefulset.yaml
Fix env var not available on secondary because it was clearly a copy+paste error from implement startupProbe in primary.
**Checklist**
> [bitnami/mariadb] Fix typo in secondary startup probe

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/README.md
- bitnami/mongodb/templates/hidden/statefulset.yaml
- bitnami/mongodb/templates/replicaset/statefulset.yaml
- bitnami/mongodb/templates/standalone/dep-sts.yaml
- bitnami/mongodb/values.yaml
Adds `persistence.medium` and `hidden.persistence.medium` options.
**Benefits**
With the added medium option, it is now possible to set medium to `Memory`, as opposed to defaulting to local fs.
None come to mind, as this is completely optional and will keep the default if not set.
- closes #7382 
**Checklist**
> [bitnami/mongodb] Add medium option for non-persisted.

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/query/service.yaml
Fixes setting the GRPC nodeport in the Thanos Query service
**Benefits**
**Checklist**
> [bitnami/thanos] Fix thanos query grpc nodeport

- bitnami/thanos/README.md
The example minio configuration is no longer correct for the newest
chart version.
The `accessKey` and `secretKey` fields were removed and only and `auth`
dictionary is now available.
Deploying Thanos with the configuration in the Readme works again.
**Checklist**
> [bitnami/thanos] Update Thanos Readme for minio configuration.

- bitnami/influxdb/Chart.yaml
- bitnami/influxdb/templates/influxdb/deployment-standalone.yaml
- bitnami/influxdb/templates/influxdb/statefulset-high-availability.yaml
- bitnami/influxdb/values.yaml
The new CLI version shows an error when running `influx --host X.X.X.X ping`:
```
Incorrect Usage. flag provided but not defined: -host
```
But it works if you switch the order and the command is the 1st argument: `influx ping --host X.X.X.X`.
**Benefits**
Adapt the chart for the new CLI version.
None
N/A
N/A
**Checklist**
> [bitnami/influxdb] Fix probes

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/replicaset/statefulset.yaml
Add handling of `tls.extraDnsNames` paramater to "replicaset" cluster architecture. Currently `tls.extraDnsNames` works only in "standalone" mode, but it can be useful in "replicaset" as well. 
**Benefits**
`tls.extraDnsNames` will work in both "standalone" and "replicaset" modes.
Not know
N/A
N/A
**Checklist**
> [bitnami/mongodb] Support tls.extraDnsNames in "replicaset" architecture

- bitnami/rabbitmq-cluster-operator/Chart.yaml
- bitnami/rabbitmq-cluster-operator/templates/cluster-operator/servicemonitor.yaml
- bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/servicemonitor.yaml
Resource names in the same namespace have to be unique.
**Benefits**
It is possible to enable ServiceMonitors for both operators
None.
None.
I bumped the version to .3 because I also created https://github.com/bitnami/charts/pull/8261 for .2. Probably needs a rebase after the other is merged.
**Checklist**
> [bitnami/rabbitmq-cluster-operator] Make ServiceMonitor names unique

- bitnami/contour/Chart.yaml
- bitnami/contour/templates/certgen/job.yaml
Remove ttlSecondsAfterFinished from a `contour-certgen` Job. `"helm.sh/hook-delete-policy": hook-succeeded` is responsible for the Job deletion.
I was trying to deploy `bitnami/contour` chart with Argo CD but it was stuck almost every time with `waiting for completion of hook...`. I found out that job is launching and closing normally and creates secrets successfully. But for some reason Argo CD was not picking up on job completion (maybe issue is needed to be open as well there). 
I though that something was wrong with `helm.sh/hook-weight` and spent a lot of time there, but in the end I finally saw 
```
As an alternative to hook deletion policies, both Jobs and Argo Workflows support 
the ttlSecondsAfterFinished field in the spec, which let their respective …
```
> [bitnami/contour] Remove ttlSecondsAfterFinished from Job

- bitnami/rabbitmq-cluster-operator/Chart.yaml
- bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/metrics-service.yaml
- bitnami/rabbitmq-cluster-operator/values.yaml
With the addition of the messaging-topology-operator the path to the metrics
ports changed. This change was still missing in the values.yaml, causing a
"nil pointer evaluating interface" error when rendering the chart with enabled
metrics.
One of the metrics services was also still using the old path.
**Benefits**
The chart renders correctly when enabling metrics.
If the user uses a different name for the port instead of the default `http` or a `nodePort`, they will also have to adjust the annotation. They have to to that anyway though, as for example a hardcoded value would also need manual adjustment by the user.
None.
**Checklist**
> [bitnami/rabbitmq-cluster-operator] Fix reference to metrics ports in values.yaml and metrics service

- bitnami/argo-cd/Chart.yaml
- bitnami/argo-cd/templates/application-controller/deployment.yaml
- bitnami/argo-cd/templates/dex/deployment.yaml
- bitnami/argo-cd/templates/repo-server/deployment.yaml
- bitnami/argo-cd/templates/server/deployment.yaml
Modifies the chart to render readinessProbe properly if overridden in values.yaml
**Benefits**
Without this fix, chart fails to deploy if you attempt to override the readiness probes in argo-cd.
None that I can see.
- fixes #8284
None.
**Checklist**
> [bitnami/argo-cd] Properly renders overridden readiness probes in argo-cd

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/README.md
- bitnami/mongodb/templates/replicaset/statefulset.yaml
- bitnami/mongodb/values.yaml
This PR adds the ability to configure the `topologySpreadConstraints` for the MongoDB ReplicaSet deployed as `StatefulSet`.
**Benefits**
Is as so possible to spread the ReplicaSet pods among topology areas (e.g. nodes, zones, regions).
The implementation is pretty basic. It's alllowed to specify a `topologySpreadConstraints` value that must contain what is expected by the Pod API's `spec.topologySpreadConstraints` field.
NONE
NONE
**Checklist**
> bitnami/mongodb: enable to configure topology spread constraints

- bitnami/magento/Chart.yaml
- bitnami/magento/templates/NOTES.txt
Print `https` and corresponding `httpsPort` number when `magentoUseHttps` or `magentoUseSecureAdmin` are set to `true`.
**Benefits**
Prints correct values after installing the Helm chart.
Otherwise, user is mislead when using security to point to an incorrect protocol or port number.
N/A
- fixes #8279
**Checklist**
> [bitnami/magento] Correct protocol and port number with https

- bitnami/mysql/Chart.yaml
- bitnami/mysql/templates/primary/initialization-configmap.yaml
pass commonAnnotations variable to initialization-configmap
**Benefits**
enable configuring annotations to the initialization-configmap
use case: use mysql as subchart and install it during pre-install hook. to configure hook, annotations must be supplied to all mysql resources.
none
none
how to test:
1. add mysql as subchart
2. set values.yaml
```
mysql:
initdbScripts: <some mysql commands>
primary:
persistence:
annotations:
helm.sh/hook: pre-install
helm.sh/hook-weight: "-10"
commonAnnotations:
helm.sh/hook: pre-install
helm.sh/hook-weight: "-10"
```
3. helm install
before change: helm install failed with hook timeout; the mysql statefulset shows event error of mysql-init-scripts not …
> [bitnami/mysql] add commonAnnotations to initialization-configmap

- bitnami/ghost/Chart.yaml
- bitnami/ghost/templates/deployment.yaml
Patch health probes for Ghost chart when HTTPS is enabled
- fixes #8201 
**Checklist**
> [bitnami/ghost] Fix Health probes when HTTPS is enabled (#8201)

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/query/grpc-client-tls-secrets.yaml
- bitnami/thanos/templates/query/grpc-server-tls-secrets.yaml
- bitnami/thanos/templates/receive/grpc-server-tls-secrets.yaml
- bitnami/thanos/templates/storegateway/grpc-server-tls-secrets.yaml
Resolves #8322
**Benefits**
when set `grpc.server.tls.autoGenerated` components will start working again as intended.
- fixes #8322
**Checklist**
> [bitnami/thanos] Fix grpc.server.tls.autoGenerated doesn't work

- bitnami/airflow/Chart.yaml
- bitnami/airflow/templates/_git_helpers.tpl
Fix #8207 
In airflow chart, make the init container of airflow worker fails when it fails to clone dags or plugins repository
**Benefits**
Airflow worker will not be ready if it fails to loads dags or plugins. So it will not receive tasks that will automatically fails as dags or plugins are not loaded.
> [bitnami/airflow] fix airflow worker init container

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/receive/ingress.yaml
Fix remote port in thanos-receive ingress. It was renamed to 'remote' in https://github.com/bitnami/charts/pull/7875 .
**Benefits**
thanos remote write (`/api/v1/receive`) through ingress works fine after this fix
- fixes #
**Checklist**
> [bitnami/thanos] fix remote port in thanos-receive ingress

- bitnami/mongodb/values.yaml
I fixed the example of tls.extraDnsNames of the mongoDB chart as it led me in error.
**Benefits**
Before, using the example, the alt_names were looking like this (using kubectl describe pod)
```
[alt_names]
DNS.1 = $svc
DNS.2 = $my_hostname
DNS.3 = $my_hostname.$svc.$MY_POD_NAMESPACE.svc.cluster.local
DNS.4 = localhost
DNS.5 = 127.0.0.1
0 = map[DNS.6:mongo.domain.com]
EOL
```
With the corrected example :
```
[alt_names]
DNS.1 = $svc
DNS.2 = $my_hostname
DNS.3 = $my_hostname.$svc.$MY_POD_NAMESPACE.svc.cluster.local
DNS.4 = localhost
DNS.5 = 127.0.0.1
DNS.6 = mongo.domain.com
EOL
```
**Checklist** 
Edit:
**Impact**
This generates this warning now : 
`coalesce.go:202: warning: destination for extraDnsNames is a table. Ignoring non-table value []`
> [bitnami/mongodb] Fixed tls.extraDnsNames example

- bitnami/airflow/Chart.lock
- bitnami/airflow/Chart.yaml
- bitnami/airflow/templates/web/deployment.yaml
- bitnami/airflow/values.yaml
There are several env. vars values that aren't properly quoted resulting on "invalid syntax" errors when you try to enable LDAP.
**Benefits**
Users can properly define LDAP properties in the values.yaml without facing syntax errors.
None
- reported at https://github.com/bitnami/charts/issues/8345
N/A
**Checklist**
> [bitnami/airflow] Ensure LDAP related env. vars values are quoted

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/README.md
- bitnami/postgresql-ha/templates/networkpolicy-egress.yaml
- bitnami/postgresql-ha/templates/networkpolicy-ingress.yaml
- bitnami/postgresql-ha/values.yaml
Add network Egress policy rules as it's done in other bitnami charts (ex. MariaDB).
**Benefits**
The extension makes it possible to configurer Egress rules in the values with no need to patch the original chart.
No drawbacks known because by default these extra Egress rules are disabled.
None
**Checklist**
> [bitnami/postgresql-ha] Add network egress policy rules

- bitnami/mysql/Chart.yaml
- bitnami/mysql/README.md
- bitnami/mysql/values.yaml
I was change of name value to use own configmap for primary and secondary, because in K8s objects was used different
**Benefits**
Own configmap can be use.
**Checklist**
> [bitnami/mysql] Fix existingConfigmap typo in values

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/kafka-provisioning.yaml
Use resources for provisioning initContainer
**Benefits**
The chart can be installed in more strict environments (requiring explicit resources being set on all containers).
**Checklist**
> [bitnami/kafka] use resources for provisioning initContainer

- bitnami/mariadb-galera/Chart.yaml
- bitnami/mariadb-galera/templates/headless-svc.yaml
Improve peer discovering by publishing not-ready addresses in the headless service.
**Benefits**
Cluster stability
None
=  - fixes #8331
N/A
**Checklist**
> [bitnami/mariadb-galera] Improve peer discovering

- bitnami/grafana/Chart.yaml
- bitnami/grafana/templates/configmap.yaml
For grafana virtual environment `GF_RENDERING_SERVER_URL` I changed the address template from `.Values.imageRenderer.service.ports.grafana` to `.Values.imageRenderer.service.ports.imageRenderer`.
**Benefits**
The changes made will allow grafana to bind to Image Renderer service.
There will be no known limitations.
**Checklist**
> [bitnami/grafana] from grafana to imageRenderer in configmap

- bitnami/postgresql/Chart.yaml
- bitnami/postgresql/templates/initialization-configmap.yaml
- fixes #8366
Instead of using toYaml, use common.tplrender helper in order to have option to render chart variables into initDbScripts, like in mongoDb chart
**Benefits**
When implementing initDbScript, user has an option to render chart values if needed
**Checklist**
> bitnami/postgresql Render template values inside initDbScripts, resolves #8366

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/templates/networkpolicy-egress.yaml
This PR fixes a rendering bug introduced by the PR#8358.
**Benefits**
This PR fixes a bug when `networkPolicy.enabled` is set to `true` and `egressRules` is defined.
None.
- fixes #8371
**Checklist**
> [bitnami/postgresql-ha] Egress NP rendering issue 

- bitnami/rabbitmq/Chart.yaml
- bitnami/rabbitmq/templates/svc.yaml
Allow to set nodePort when type is LoadBalancer for all ports. Fixes issue: #8363
**Benefits**
Fixes issue: #8363
None that I know of.
- fixes #8363
**Checklist**
> [bitnami/RabbitMQ] Allow to set nodePort when type is LoadBalancer for all ports

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/templates/svc.yaml
currently it's iterated over all objects instead of array
Fix sourcerange array iteration in wordpress
**Benefits**
we can now use sourceranges
- fixes #
**Checklist**
> bitnami/wordpress fix source-ranges wrong iteration

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/README.md
- bitnami/postgresql-ha/values.yaml
The `pgpool.configuration` parameter expects a string instead of a map.
**Benefits**
README.md and default values are aligned with the expected format.
None
- fixes #8375
N/A
**Checklist**
> [bitnami/postgresql-ha] Fix default value for pgpool.configuration

- bitnami/zookeeper/Chart.yaml
- bitnami/zookeeper/templates/statefulset.yaml
Fixes a regression introduced by #8318, so that ZooKeeper can be installed.
**Benefits**
ZooKeeper can be installed without issues.
None
- #8318 
**Checklist**
> [bitnami/zookeeper] Fix securityContext reference after #8318 was merged

- bitnami/wavefront/Chart.yaml
- bitnami/wavefront/templates/proxy-deployment.yaml
Signed-off-by: Helen Shao <shaoh@vmware.com>
Just the wavefront `proxy-deployment.yaml` template file for `bitnami/wavefront`
**Benefits**
Address Log4j vulnerability https://community.pivotal.io/s/article/Workaround-instructions-to-address-CVE-2021-44228-in-Tanzu-Observability-Proxy?language=en_US
Just a workaround until a new proxy image is released
N/A
N/A
**Checklist**
> bitnami/wavefront Add Log4j workaround to proxy

- bitnami/influxdb/Chart.yaml
- bitnami/influxdb/templates/influxdb/statefulset-high-availability.yaml
Changed the ownership of /bitnami/influxdb path mounted in influxdb pod initialized in high-availability setup to prevent error relating to custom script initialization problem. 
**Benefits**
Providing user-defined initialization scripts no longer causes error in initialization of influxdb pods. 
When script is inserted using the `influxdb.initdbScripts` parameter, the deployed pod will run the scripts provided and attempted to touch a file `.user_scripts_initialized` to prevent rerun of the provided initialization scripts in the future. 
We are using microk8s on Centos 7. Thus the persistent volume mounted is on the filesystem of the machine. Initially this worked fine with kernel version 3.10.0-957.21.3.el7.x86_64. However it no …
> [bitnami/influxdb] Changed ownership of /bitnami/influxdb to prevent custom init script initialization error.

- bitnami/rabbitmq-cluster-operator/Chart.yaml
- bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/servicemonitor.yaml
Changes the port of the `ServiceMonitor` for the messaging topology operator to `http` which matches the port name in the matching service. `.spec.endpoints[].targetPort` would have be set to `http-metrics` if used, but `.spec.endpoints[].port` refers to the name of the port defined in the service.
Together with #8411 the messaging topology operator metrics were not scraped by the Prometheus operator.
**Checklist**
> [bitnami/rabbitmq-cluster-operator] ServiceMonitor port must be Service port name

- bitnami/rabbitmq-cluster-operator/Chart.yaml
- bitnami/rabbitmq-cluster-operator/templates/cluster-operator/servicemonitor.yaml
- bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/servicemonitor.yaml
Use the available name templates for consistent naming of the `ServiceMonitor` manifests.
**Benefits**
Depending on how the `nameOverride` and `fullnameOverride` are set or if the `rmqco.clusterOperator.fullname` and `rmqco.msgTopologyOperator.fullname` template are overridden in a parent chart, the naming of the `ServiceMonitor` manifests will now be consistent in all cases with all other manifests generated.
`ServiceMonitor` names will change on updating this chart as user, but it has no BC impact.
This is a follow-up to #8264, which introduced those names.
**Checklist**
> [bitnami/rabbitmq-cluster-operator] Consistent naming for ServiceMonitor

- bitnami/mariadb-galera/Chart.yaml
- bitnami/mariadb-galera/values.yaml
Change bind-address from values.yaml from `0.0.0.0` to `::`
**Benefits**
With this change service could listen on IPv6
No possible drawbacks
**Checklist**
> [bitnami/mariadb-galera] change mariadb-galera bind-adrs to enable IPv6

- bitnami/rabbitmq-cluster-operator/Chart.yaml
- bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/deployment.yaml
Use the correct component name for pod affinities on the `message-topology-operator` deployment.
**Benefits**
When deploying the operators in HA, the `message-topology-operator` will now spread over different nodes to each other instead of having and anti-affinity by default to the `rabbitmq-cluster-operator`.
This change will update the default pod anti-affinity of the `messaging-topology-operator` deployment. If anyone has adapted the affinities due to this bug, they can remove their changes.
If anyone is using the pod affinity preset to co-locate the `messaging-topology-operator` with the `rabbitmq-cluster-operator` pods, this will not be possible anymore. But IMHO it's not the intended case.
RFC: Should …
> [bitnami/rabbitmq-cluster-operator] Fix messaging-topology-operator pod affinities

- bitnami/rabbitmq/README.md
RabbitMQ has been multi-protocol since 2010 or so (when STOMP support was introduced).
The core team would strongly prefer to use this language as "AMQP" these days refers to more
than one protocol for historical reasons.
> bitnami/rabbitmq: README copywriting updates

- bitnami/grafana/Chart.yaml
- bitnami/grafana/README.md
- bitnami/grafana/templates/image-renderer-deployment.yaml
- bitnami/grafana/values.yaml
Add support for PodAntiAffinity for image-renderer
**Benefits**
Spread the containers over nodes instead a possible single one (if it's use `hard` option)
No possible knows limitations
**Checklist**
> [bitnami/grafana] add podAntiAffinity support for image-renderer

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/replicaset/statefulset.yaml
- bitnami/mongodb/values.yaml
Using MongoDB shell version v5.0.5 and MongoDB shell version v4.4.10, a warning is issued when you try to connect to a cluster using TLS autogenerated certs.
`{"t":{"$date":"2021-12-14T17:21:50.482Z"},"s":"W",  "c":"NETWORK",  "id":23237,   "ctx":"js","msg":"You have an IP Address in the DNS Name field on your certificate. This formulation is deprecated."}`
This is painfull when you use mongoshell for scripting as we can't disable this warning (even with `--quiet` option).
**Benefits**
Removing `127.0.0.1` in default generation `alt_names` seems to resolve this 'un-mutable' warning.
**Checklist**
> [bitnami/mongodb] Fix deprecated 'IP Address in the DNS Name field on certificate' when using tls

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/query/grpc-client-tls-secrets.yaml
- bitnami/thanos/templates/query/grpc-server-tls-secrets.yaml
- bitnami/thanos/templates/receive/grpc-server-tls-secrets.yaml
when it creates the certificate its missing a E in the secret
**Benefits**
- fixes #
**Checklist**
> [bitnami/thanos] fix auto Generated certificate 

- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/templates/coordinating-hpa.yaml
Coordinating pods are of type `StatefulSet` but the corresponding hpa has type `Deployment`. So setting `coordinating.autoscaling.enabled: true` causes pods to not be fully deployed.
**Benefits**
HPA will work for coordinating type es nodes
None
**Checklist** 
- [ X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
> [bitnami/elasticsearch] coordinating-hpa kind to StatefulSet

- bitnami/mariadb-galera/Chart.yaml
- bitnami/mariadb-galera/values.yaml
Reverts #8395, because it is failing in the internal CI/CD:
```
1) MariaDB remote authentication
Password authentication is required through 10.49.49.5:
Expected "Access denied for user 'root'@'10.49.49.5'" but got "'ERROR 2002 (HY000): Can't connect to server on '10.49.49.5' (115)'"
2) MariaDB remote authentication
Password authentication is required through 127.0.0.1:
Expected "Access denied for user 'root'@'127.0.0.1'" but got "'ERROR 2002 (HY000): Can't connect to server on '127.0.0.1' (115)'"
```
> [bitnami/mariadb-galera] Revert enabling of IPv6

- bitnami/ejbca/Chart.yaml
- bitnami/ejbca/templates/deployment.yaml
- bitnami/ejbca/values.yaml
This change needs to be applied due to the persistence refactorization. The volume is now mounted in `/bitnami/wildfly` instead of in `/bitnami/ejbca`. Also, since the container initialization logic and volumes content change, this is a major change of the chart, since the upgrade won't work.
**Benefits**
Applies the new persistence logic, which make the containers being able to restart and recreate without issues.
check: https://github.com/bitnami/bitnami-docker-ejbca/pull/12
- fixes 
**Checklist**
> [bitnami/ejbca] Major change. Adapt to image PR #12

- bitnami/grafana/Chart.yaml
- bitnami/grafana/README.md
- bitnami/grafana/templates/image-renderer-deployment.yaml
- bitnami/grafana/values.yaml
In order to use image-renderer configuration environment variables it's needed to use extraEnvVars to chart.
re. [Image Renderer Configuration](https://grafana.com/docs/grafana/latest/image-rendering/#configuration) 
For this I added extraEnvVars support
**Benefits**
Support for extraEnvVars for Grafana Image Renderer
No possible knows limitations
**Checklist**
> [bitnami/grafana] add extraEnvVars for image-renderer

- bitnami/argo-cd/Chart.yaml
- bitnami/argo-cd/templates/application-controller/deployment.yaml
- bitnami/argo-cd/templates/repo-server/deployment.yaml
- bitnami/argo-cd/templates/server/deployment.yaml
Enable using Redis with `redis.auth.enabled = false`.
**Benefits**
You can use `redis.auth.enabled = false`.
None.
- fixes #8273 
**Checklist**
> [bitnami/argo-cd] Disable passing redis password when there is none

- bitnami/airflow/README.md
There was a missing period in the documentation specifying the option for configuring the config map containing DAG files
> Fixed typo in README.md

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/README.md
- bitnami/postgresql-ha/templates/pgpool/deployment.yaml
- bitnami/postgresql-ha/values.yaml
Default to setting reserved_connections to 1 in pgpool.conf.
See [here](https://www.pgpool.net/docs/latest/en/html/runtime-config-connection.html#GUC-RESERVED-CONNECTIONS) for documentation on this property.
**Benefits**
When this property is set to 0 (as is default), pgpool blocks excess connections. This results in the readiness/liveness probes for pgpool failing with a timeout and no errors in the logs. When this property is set to 1, pgpool instead rejects the connection with an informative error message in the pod events, as well as the logs. This makes the problem much more obvious, as well as allows for log monitoring to scan for this message and alert if found.
As the name implies, one fewer connection is allowed, but users can …
> [bitnami/postgresql-ha] Default pgpool reserved_connections to 1

- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/templates/redis-statefulset.yaml
Adding the redis configmap file checksum to statefulset annotations.
**Benefits**
When updating chart with redis configmap changes the checksum of the configmap file will change and cause pods to be re-created and load new config.
- fixes #
**Checklist**
> [bitnami/redis-cluster] Add checksum to update pods when configmap is updated

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/poddisruptionbudget.yaml
- bitnami/kafka/templates/statefulset.yaml
- bitnami/kafka/values.yaml
There are 2 changes to the kafka chart:
- Ensure that the chart is Kubernetes 1.21+ compatible by making sure that the PodDisruptionBudget uses the `policy/v1` apiVersion if it is available.
- Can set a special `auto` value to the `volumePermissions.securityContext.runAsUser` to make it OpenShift compatible as that does not like the `0` (root) user.
**Benefits**
Compatibility with newer Kubernetes versions and OpenShift deployments
Fully backwards compatible so no drawbacks expected.>
N/A
N/A
**Checklist**
> [bitnami/kafka] Improved compatibility with Kubernetes 1.21+ and Openshift

- bitnami/mariadb-galera/Chart.yaml
- bitnami/mariadb-galera/templates/NOTES.txt
- bitnami/mariadb-galera/values.yaml
This PR includes password validations to ensure that every expected password is provided during chart upgrades so users avoid the [Credentials error known issue](https://docs.bitnami.com/general/how-to/troubleshoot-helm-chart-issues/#credential-errors-while-upgrading-chart-releases). 
**Benefits**
Reduce the % of making a bad use of the chart during upgrades.
None
- fixes #8256
N/A
**Checklist**
> [bitnami/mariadb-galera] Add password validations during upgrades

- bitnami/contour/Chart.yaml
- bitnami/contour/templates/contour/ingressclass.yaml
Even if `ingressClass.default` is set to false, the actual label will be applied and make the ingress be a default ingress. See #8450
Credits go all to @javsalgar !
> [bitnami/contour] Fix applying default ingress label even if not default #8450

- bitnami/redis/templates/NOTES.txt
The REDISCLI_AUTH variable settings in redis-client pod are `REDISCLI_AUTH="$REDIS_PASSWORD"`.
Thus, the `kubectl run` should set the env `REDIS_PASSWORD=$REDIS_PASSWORD` instead of `REDISCLI_AUTH=$REDIS_PASSWORD`.
**Checklist**
> * [bitnami/redis] Fix env variable name

- bitnami/spring-cloud-dataflow/Chart.yaml
- bitnami/spring-cloud-dataflow/README.md
- bitnami/spring-cloud-dataflow/templates/_helpers.tpl
- bitnami/spring-cloud-dataflow/templates/server/configmap.yaml
- bitnami/spring-cloud-dataflow/templates/skipper/configmap.yaml
- bitnami/spring-cloud-dataflow/values.yaml
Now we can define the environment variables for the Spring Cloud Deployer (`deployer.environmentVariables`) with a list of strings instead of a single string splitted by commas (this method is still allowed).
**Benefits**
- Clearer values.yml files
- Amend issues with multivalued environment variables
None
- fixes #7639
- https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#configuration-kubernetes-deployer
**Checklist**
> [bitnami/spring-cloud-dataflow] Allow multiple external kafka nodes

- bitnami/fluentd/Chart.yaml
- bitnami/fluentd/values.yaml
Fix the host label in prometheus metrics for fluentd.
**Benefits**
correct hostname in prometheus metrics
nothing
**Checklist**
> [bitnami/fluentd] fix host label in prometheus metrics

- bitnami/kibana/Chart.yaml
- bitnami/kibana/templates/deployment.yaml
The current liveness/readiness probe path is /login I have changed it to the official healthcheck in the kibana image which is /status
**Benefits**
/login does not work unless xpack is enabled, this obviously causes issues in many cases and it is obviously the better solution to use the proper healthcheck /status
None
- fixes #3058 
**Checklist**
> [bitnami/kibana] Change probe path

- bitnami/phpbb/Chart.yaml
- bitnami/phpbb/templates/deployment.yaml
The volume mount name is incorrect in the phpbb deployment template when using volumePermissions. It references a "data" mount instead of "phpbb-data". This causes the following error:
```
[...] is invalid: spec.template.spec.initContainers[0].volumeMounts[0].name: Not found: "data"
```
- Fixes #5401
**Checklist**
> [bitnami/phpbb] fix volumemount name for volumePermissions

- bitnami/mysql/Chart.yaml
- bitnami/mysql/templates/_helpers.tpl
- bitnami/mysql/templates/secrets.yaml
Look up existing secrets before generating random secrets, and use the existing ones if they exist.
Related to: 
- #8320
- #8495
- #8499
- #8486
- #8504
**Benefits**
- fixes #
**Checklist**
> [bitnami/mysql] lookup existing secrets

- bitnami/grafana/Chart.yaml
- bitnami/grafana/README.md
- bitnami/grafana/templates/image-renderer-prometheusrules.yaml
- bitnami/grafana/templates/prometheusrules.yaml
- bitnami/grafana/values.yaml
Add image-renderer-prometheusrule and prometheusrule files to enable support for PrometheusRules
**Benefits**
Write prometheus rules to alert the state of grafana and grafana-image-renderer services
No possible known drawbacks.
**Checklist**
> [bitnami/grafana] prometheusrules supp for grafana and image-renderer

- bitnami/mariadb/Chart.yaml
- bitnami/mariadb/README.md
- bitnami/mariadb/templates/prometheusrules.yaml
- bitnami/mariadb/values.yaml
Add support for PrometheusRules. Add prometheusrules.yaml file in templates directory.
**Benefits**
Create prometheusrules from chart for mariadb.
No known possible drawbacks.
**Checklist**
> [bitnami/mariadb] add support for PrometheusRules

- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/README.md
- bitnami/elasticsearch/templates/servicemonitor.yaml
- bitnami/elasticsearch/values.yaml
* Support to add custom labels for servicemonitor.
* Update README.md
**Benefits**
Prometheus could select service monitor by labels.
- fixes #8485 
**Checklist**
> [bitnami/elasticsearch]: support custom labels for servicemonitor.

- bitnami/contour/Chart.yaml
- bitnami/contour/README.md
- bitnami/contour/templates/envoy/deployment.yaml
- bitnami/contour/values.yaml
Added additional parameter to values.yaml which allows to configure sidecars for Envoy pods
**Benefits**
Run sidecars in Envoy pod
**Checklist**
> [bitnami/contour] Added ability to use sidecars in Envoy pods

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/README.md
- bitnami/grafana-operator/templates/grafana.yaml
- bitnami/grafana-operator/values.yaml
Add `grafana.ingress.pathType` value with default value of `ImplementationSpecific`
**Benefits**
Fixes an issue where this chart `Grafana` resource could not be provisioned with an `Ingress` due to missing the `pathType` parameter required by the `networking.k8s.io/v1` API.
- fixes #8531
- fixes #8540 
**Checklist**
> [bitnami/grafana-operator] add `grafana.ingress.pathType`

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/templates/standalone/dep-sts.yaml
Adds an active wait to prevent the exporter from initializing before MongoDB credentials have been set.
- fixes #7592
**Checklist**
> [bitnami/mongodb] Add metrics active wait

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/README.md
- bitnami/wordpress/templates/deployment.yaml
- bitnami/wordpress/values.yaml
Add startup probe config 
**Benefits**
- startup probes help to know when a container application has started and it will be good for deployments on wp helm chart.
**Checklist**
> [bitnami/wordpress] Add startup probe on wordpress helm chart

- bitnami/mysql/Chart.yaml
- bitnami/mysql/templates/_helpers.tpl
Leading newline character added to predefined `auth.password` and `auth.replicationPassword` by bitnami/mysql chart.
Introducing change: https://github.com/bitnami/charts/commit/7238fbe13877943f861c03229a72dad35c0d81b9
**Benefits**
Permit use of predefined `auth.password` and `auth.replicationPassword` parameters in bitnami/mysql chart.
n/a
- fixes #8504
Reproduced by predefined values for `auth.password` and `auth.replicationPassword` and visible in container logs with `image.debug: true`:
`helm install my-release bitnami/mysql --set auth.password=9fXymk61OT,auth.replicationPassword=E6dMqifzrh,auth.username=my_user,image.debug=true`
Log file:
```
mysql 01:31:24.36 DEBUG ==> Configuring …
```
> [bitnami/mysql] Prevent introduction of leading newline character in predefined password and replicationPassword

- bitnami/concourse/Chart.yaml
- bitnami/concourse/templates/web/deployment.yaml
- bitnami/elasticsearch/Chart.yaml
- bitnami/elasticsearch/templates/cronjob.yaml
- bitnami/etcd/Chart.yaml
- bitnami/etcd/templates/statefulset.yaml
- bitnami/jupyterhub/Chart.yaml
- bitnami/jupyterhub/templates/hub/deployment.yaml
- bitnami/minio/Chart.yaml
- bitnami/minio/templates/gateway/deployment.yaml
- bitnami/mongodb-sharded/Chart.yaml
- bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
- bitnami/mysql/Chart.yaml
- bitnami/mysql/templates/secrets.yaml
- bitnami/nginx/Chart.yaml
- bitnami/nginx/templates/deployment.yaml
- bitnami/nginx/templates/ldap-daemon-secrets.yaml
Replace all occurrences of `| quote}}` with `| quote }}` in order to solve some issues.
**Benefits**
Originally created to solve the issue described for MySQL at #8557 (probably introduced at #8504), but it can be also applied to all occurrences. For this specific issue:
- With `| quote}}`:
```yaml
data:   
mysql-root-password: {{ include "mysql.root.password" . | b64enc | quote}}
mysql-password: {{ include "mysql.password" . | b64enc | quote }}
```
```console
$ kubectl get secret --namespace mymysql7 mysql7 -o jsonpath="{.data.mysql-root-password}" | base64 --decode
myRootPassword%
$ kubectl get secret  mysql -o jsonpath="{.data.mysql-password}" | base64 --decode
myregularpassword%
```
- With `| quote }}`
```yaml
data:   
mysql-root-password: {{ include …
```
> [bitnami/several] Fix issue with quote when followed by }}

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/README.md
- bitnami/grafana-operator/values.yaml
After recent [changes](https://github.com/bitnami/charts/commit/d87dec202858e218f08470a8a28d5397426b6a6c) to the grafana-operator chart Values.grafana.persistence.accessModes is expected to be a list:
https://github.com/bitnami/charts/blob/master/bitnami/grafana-operator/templates/grafana.yaml#L33
Change Values.grafana.persistence.accessModes to be a list.
**Benefits**
Fixes: Error: UPGRADE FAILED: template: grafana-operator/templates/grafana.yaml:34:23: executing "grafana-operator/templates/grafana.yaml" at <.Values.grafana.persistence.accessModes>: range can't iterate over ReadWriteOnce
None
**Checklist**
> bitnami/grafana-operator fix default value for accessModes

- bitnami/minio/Chart.yaml
- bitnami/minio/templates/distributed/statefulset.yaml
With new version of Minio, it requires to have the API port in the discovery URLs passed to Minio nodes.
**Benefits**
Fix Minio not starting in distributed mode.
None
None
**Checklist**
> [bitnami/minio] Fix minio discovery

- bitnami/cert-manager/Chart.yaml
- bitnami/cert-manager/README.md
- bitnami/cert-manager/templates/controller/deployment.yaml
- bitnami/cert-manager/values.yaml
Add the `clusterResourceNamespace` parameter to set the namespace where ClusterIssuer resources live.
- fixes #8559 
**Checklist**
> [bitnami/cert-manager] Add clusterResourceNamespace value

- bitnami/solr/Chart.yaml
- bitnami/solr/README.md
- bitnami/solr/templates/NOTES.txt
- bitnami/solr/templates/statefulset.yaml
- bitnami/solr/values.yaml
Introduces a new `coreNames` property, replacing the existing `coreName`.
**Benefits**
Makes the chart compatible with Solr images at version `8.10.1-debian-10-r2` and up, due to bitnami/bitnami-docker-solr#37.
Due to `coreName` being replaced by `coreNames`, this is a breaking change.
Thus the version being bumped to the next minor.
Although I first wanted to implement a backward compatible solution (by keeping `coreName` around), in the end I thought it would be just as good to replace/rename it.
- fixes #8482
**Checklist**
> [bitnami/solr] Adapt to env variable change in Solr image

- bitnami/sonarqube/Chart.yaml
- bitnami/sonarqube/templates/_helpers.tpl
If external database is used the enviroment variables are quoted twice and sonarqube is not able to connect to db
**Benefits**
With this external db can be used
- fixes #8437
**Checklist**
> [bitnami/sonarqube] Removed extra quotes from externalDatabase variables

- bitnami/postgresql/Chart.yaml
- bitnami/postgresql/templates/svc-read-set.yaml
Fixes the following templating error when setting `replication.uniqueServices` to `true`:
```
Error: template: postgresql/templates/svc-read-set.yaml:18:16: executing "postgresql/templates/svc-read-set.yaml" at <.Values.commonLabels>: can't evaluate field Values in type int
```
**Checklist**
> [bitnami/postgresql]: fix unique services template render

- bitnami/etcd/Chart.yaml
- bitnami/etcd/README.md
- bitnami/etcd/templates/statefulset.yaml
- bitnami/etcd/values.yaml
This PR allows to override the `schedulerName` field of the etcd statefulset.
This overlaps with the proposed changes in #7926 but that PR has become stale and changes much more.
**Checklist**
> [bitnami/etcd] Allow to override schedulerName

- bitnami/spring-cloud-dataflow/Chart.yaml
- bitnami/spring-cloud-dataflow/README.md
- bitnami/spring-cloud-dataflow/templates/server/configmap.yaml
- bitnami/spring-cloud-dataflow/templates/skipper/configmap.yaml
- bitnami/spring-cloud-dataflow/values.yaml
Adding deployer imagePullSecrets property in skipper and SCDF server configmap
**Benefits**
Add imagePullSecrets to pod deployment of stream and tasks apps when using a private registry
- fixes #7902
**Checklist**
> [bitnami/spring-cloud-dataflow] Add deployer.imagePullSecrets property

- bitnami/nginx/Chart.yaml
- bitnami/nginx/templates/servicemonitor.yaml
#8551 resolved some issues with the ServiceMonitor definition in the Nginx chart, but didn't correct the if statements that controlled the rendering of the relabelling options
**Benefits**
Resolves issues using the chart with metrics enabled.
None
None
N/A
**Checklist**
> [bitnami/nginx] Fix ServiceMonitor relabling values

- bitnami/spark/Chart.yaml
- bitnami/spark/templates/statefulset-master.yaml
- bitnami/spark/templates/svc-master.yaml
**With current chart the https port is not exposed when ssl is enabled, because of this spark master webUI is not accessible, this change exposes the https port for master when ssl is enabled**
**Benefits**
We will be able to access master WebUI on https when ssl is enabled.
- fixes # https://github.com/bitnami/charts/issues/8417
**Checklist**
> bitnami/spark: updated svc-master and master statefulset  to expose https port when ssl is enabled.

- bitnami/contour/Chart.yaml
- bitnami/contour/templates/envoy/daemonset.yaml
added envoy sidecars not only for deployment mode, but also for daemonset
**Benefits**
Run sidecars in Envoy pod in daemonset mode
related to https://github.com/bitnami/charts/pull/8512
**Checklist**
> [bitnami/contour] Envoy sidecars in daemonset mode

- bitnami/cert-manager/Chart.yaml
- bitnami/cert-manager/README.md
- bitnami/cert-manager/templates/controller/deployment.yaml
- bitnami/cert-manager/values.yaml
Add dnsPolicy and dnsConfig settings to controller
**Benefits**
Optional DNS settings, useful if you have a public and private DNS zone for the same domain on Route 53.
None
None
None
**Checklist**
> [bitnami/cert-manager] Add dnsPolicy and dnsConfig settings to controller

- bitnami/phpmyadmin/Chart.yaml
- bitnami/phpmyadmin/README.md
- bitnami/phpmyadmin/templates/ingress.yaml
- bitnami/phpmyadmin/values.yaml
Adds support for `ingress.ingressClassName`
**Benefits**
Replaces a deprecated feature of using `kubernetes.io/ingress.class` annotation to determine ingress class.
None known.
**Checklist**
> [bitnami/phpmyadmin] Add support for ingressClassName

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/scripts-configmap.yaml
When starting the current Redis chart with Sentinel, one of the containers (the `redis` container) does not start. It gets killed by the liveliness probe:
```
Events:
Type     Reason                  Age                From                     Message
----     ------                  ----               ----                     -------
Warning  FailedScheduling        13m                default-scheduler        0/1 nodes are available: 1 pod has unbound immediate PersistentVolumeClaims.
Normal   Scheduled               13m                default-scheduler        Successfully assigned api-engine/engine-redis-node-0 to scw-x-x-x-pg-2fe6e7bd09064
Normal   SuccessfulAttachVolume  13m                attachdetach-controller  AttachVolume.Attach succeeded for volume …
```
> [bitnami/redis] add timeout to redis container for sentinel

- bitnami/rabbitmq-cluster-operator/Chart.yaml
- bitnami/rabbitmq-cluster-operator/templates/cluster-operator/clusterrole.yaml
- bitnami/rabbitmq-cluster-operator/templates/cluster-operator/clusterrolebinding.yaml
- bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/clusterrole.yaml
- bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/clusterrolebinding.yaml
Remove the namespace from non-namespaced cluster-scoped resources.
Most of the tooling ignores the namespace on cluster-scoped resources. But the [GitLab Kubernetes Agent](https://docs.gitlab.com/ee/user/clusters/agent/) where I use `helm template` to render the chart and use it within the GitOps workflow of the agent is very strict and fails with namespaces defined on cluster-scoped resources.
```
{"level":"error","time":"2021-12-14T13:39:32.245Z","msg":"Failed to decode GitOps objects","mod_name":"gitops","project_id":"<redacted>/manifests","agent_id":<redacted>,"error":"resource is cluster-scoped but has a non-empty namespace \"rabbitmq-operator\"","commit_id":"<redacted>"}
```
Meta issue: #8414
**Checklist**
> [bitnami/rabbitmq-cluster-operator] Remove namespace from cluster-scoped resources

- bitnami/airflow/Chart.yaml
- bitnami/airflow/templates/web/ingress.yaml
- bitnami/airflow/values.yaml
This PR adds support of ingressClassName for the airflow chart. This feature is required for k8s 1.18+ using more than one ingress controller.
**Benefits**
Supports the newest Kubernetes specification.
None
- fixes partially https://github.com/bitnami/charts/issues/7364
None
**Checklist**
> [bitnami/airflow] Add ingressClassName parameter

- bitnami/solr/Chart.yaml
- bitnami/solr/templates/ingress.yaml
Fixes indentation issue on last PR to support `ingress.ingressClassName`
**Benefits**
Users can now correctly replace the deprecated `kubernetes.io/ingress.class` annotation to determine ingress class.
None known.
- fixes error in https://github.com/bitnami/charts/pull/8601
**Checklist**
> [bitnami/solr] Fix indentation

- bitnami/phpmyadmin/Chart.yaml
- bitnami/phpmyadmin/templates/ingress.yaml
Fixes indentation issue on last PR to support `ingress.ingressClassName`
**Benefits**
Users can now correctly replace the deprecated `kubernetes.io/ingress.class` annotation to determine ingress class
None known.
- fixes error in https://github.com/bitnami/charts/pull/8600
**Checklist**
> [bitnami/phpmyadmin] Fix indentation

- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/templates/update-cluster.yaml
- bitnami/redis-cluster/values.yaml
This pull request addresses three issues:
1. Adds slot rebalancing to update-cluster.yaml (#3853, #7579, and other tickets)
2. Fixes the Redis port config name that is used in update-cluster.yaml (#8245) 
3. Adds missing TLS configs to update-cluster.yaml
**Checklist**
> [bitnami/redis-cluster] Scale out bugfixes

- bitnami/moodle/Chart.yaml
- bitnami/moodle/README.md
- bitnami/moodle/templates/ingress.yaml
- bitnami/moodle/values.yaml
Adds support for `ingress.ingressClassName`
**Benefits**
Replaces a deprecated feature of using `kubernetes.io/ingress.class` annotation to determine ingress class.
None known.
**Checklist**
> [bitnami/moodle] Add support for ingressClassName

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/templates/deployment.yaml
**Benefits**
Enable templating the wordpress startupProbe
Without this, the helm template, when startupProbe.enabled=true was : 
```
startupProbe:
httpGet:
httpHeaders: []
path: /wp-login.php
port: '{{ .Values.wordpressScheme }}'
scheme: '{{ .Values.wordpressScheme | upper }}'
```
**Checklist**
> [bitnami/wordpress] enable templating of startupProbe

- bitnami/tomcat/Chart.yaml
- bitnami/tomcat/templates/statefulset.yaml
This PR fixes the indentation in Tomcat's statefulset when setting a custom StorageClass.
**Benefits**
Users can set a custom StorageClass
None
- fixes #8664
N/A
**Checklist**
> [bitnami/tomcat] Fix storageclass indentation

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/README.md
- bitnami/grafana-operator/templates/grafana.yaml
- bitnami/grafana-operator/values.yaml
Allow configuration of `deployment.skipCreateAdminAccount` in `grafana.yaml`.
**Benefits**
Users of this chart can now configure this parameter.
None
- Fixes #8629
- Fixes #8661 
**Checklist**
> [bitnami/grafana-operator] Add deployment.skipCreateAdminAccount to grafana.yaml

- bitnami/spring-cloud-dataflow/Chart.yaml
- bitnami/spring-cloud-dataflow/README.md
**Description**
This removes the `$` (dollar prompt) from several copyable command examples in the `bitnami/spring-cloud-dataflow` README to allow the user to copy and used them directly without editing them to remove the `$`. This is part of an improvement effort on the Spring Cloud Dataflow Microsite to make these copyable commands easier to use. The coupling between the 2 repos is due to the fact that the microsite [includes the bitnami README](https://github.com/spring-io/dataflow.spring.io/blob/main/content/documentation/pages/1-installation/3-kubernetes/2-helm.md?plain=1#L42) via 
```
```
**Benefits**
Without this change, the microsite will have 4 (out of ~50) inconsistent command examples.
Since this only changes the `bitnami/spring-cloud-dataflow` README, it …
> [bitnami/spring-cloud-dataflow] Remove dollar prompt from command examples in README

- bitnami/nginx/Chart.yaml
- bitnami/nginx/templates/servicemonitor.yaml
This fixes an issue with ServiceMonitors. If  `.Values.metrics.serviceMonitor.enabled` is true and `.Values.metrics.serviceMonitor.additionalLabels` is the empty object, no valid YAML is produced.
> [bitnami/nginx] Fix issue with ServiceMonitors

- bitnami/rabbitmq-cluster-operator/Chart.yaml
- bitnami/rabbitmq-cluster-operator/templates/_helpers.tpl
- bitnami/rabbitmq-cluster-operator/templates/cluster-operator/deployment.yaml
- bitnami/rabbitmq-cluster-operator/values.yaml
This PR ensure the default image pull secrets information is passed to the operator using the `DEFAULT_IMAGE_PULL_SECRETS` environment variable. 
**Benefits**
None
N/A
Support for `DEFAULT_IMAGE_PULL_SECRETS` environment variable was recently added at https://github.com/rabbitmq/cluster-operator/pull/926
**Checklist**
> [bitnami/rabbitmq-cluster-operator] Specify default image pull secrets for the operator

- bitnami/redmine/Chart.yaml
- bitnami/redmine/README.md
- bitnami/redmine/values.yaml
Changed the default updateStrategy.rollingUpdate parameter from {} to null
**Benefits**
Allows setting updateStrategy type to `Recreate`.
None.
- Fixes #8539
**Checklist**
> [bitnami/redmine] Change default updateStrategy.rollingUpdate from {} to null

- bitnami/orangehrm/Chart.lock
- bitnami/orangehrm/Chart.yaml
- bitnami/orangehrm/README.md
- bitnami/orangehrm/templates/NOTES.txt
- bitnami/orangehrm/values.yaml
OrangeHRM helm chart will be deprecated since the upstream project only supports deprecated PHP versions.
**Checklist**
> [bitnami/orangehrm] Mark OrangeHRM chart as deprecated

- bitnami/grafana-operator/Chart.yaml
- bitnami/grafana-operator/templates/rbac.yaml
Added missing permissions.
**Benefits**
This won't happen:
```
2022-01-17T20:13:47.638Z    DEBUG    controller-runtime.manager.events    Warning    {"object": {"kind":"Grafana","namespace":"test-0","name":"release-grafana-operator-grafana","uid":"0f1af8f4-9bd7-4e37-89db-69fd98a15d62","apiVersion":"integreatly.org/v1alpha1","resourceVersion":"168620319"}, "reason": "ProcessingError", "message": "deployment not ready"}E0117 20:13:47.640482       1 event.go:264] Server rejected event '&v1.Event{TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, ObjectMeta:v1.ObjectMeta{Name:"release-grafana-operator-grafana.16cb2725e2b9218b", GenerateName:"", Namespace:"test-0", SelfLink:"", UID:"", ResourceVersion:"8303976", Generation:0, …
```
> [bitnami/grafana-operator] Add `patch events` permissions to grafana-operator ClusterRole

- bitnami/spring-cloud-dataflow/Chart.yaml
- bitnami/spring-cloud-dataflow/templates/prometheus-proxy/service.yaml
- bitnami/spring-cloud-dataflow/values.yaml
An error is thrown when enabling metrics, as reported in #8670:
```console
$ helm install scdf-test bitnami/spring-cloud-dataflow --set metrics.enabled=true --dry-run
Error: UPGRADE FAILED: template: spring-cloud-dataflow/templates/prometheus-proxy/service.yaml:17:6: executing "spring-cloud-dataflow/templates/prometheus-proxy/service.yaml" at <include "common.tplvalues.render" (dict "value" .Values.metrics.service.annotations "context" $)>: error calling include: template: spring-cloud-dataflow/charts/common/templates/_tplvalues.tpl:11:12: executing "common.tplvalues.render" at <tpl (.value | toYaml) .context>: error calling tpl: error during tpl function execution for "prometheus.io/path: /metrics/proxy\nprometheus.io/port: '{{ coalesce …
```
> [bitnami/spring-cloud-dataflow] Fix metrics

- bitnami/kube-state-metrics/Chart.yaml
- bitnami/kube-state-metrics/templates/deployment.yaml
- bitnami/kube-state-metrics/values.yaml
- Fix the condition to match the `namespaces` key in values.yaml
- Add the ability to have templated value in `namespaces` key (like `namespaces: "{{ .Release.Namespace }}"` to restrict scope to the NS where kube-state-metrics is deployed)
**Benefits**
- Regarding the ability o have templated value in `namespaces` key, it will avoid users to explicitly define the key to the namespace kube-state-metrics is currently deployed
None that I know of (so far)
None apparently
None
**Checklist**
> [bitnami/kube-state-metrics] .Values.namespaces: Fix condition and add rendering

- bitnami/redis/Chart.yaml
- bitnami/redis/templates/scripts-configmap.yaml
Reverts #8641, which causes Redis Sentinel to fail before starting.
**Checklist**
> [bitnami/redis] Revert PR 8641

- bitnami/tomcat/Chart.yaml
- bitnami/tomcat/templates/_pod.tpl
Removes duplicated `extraVolumes` in Tomcat's pod.
**Benefits**
Fixes bug.
None known.
- fixes #8681
- fixes #8690
**Checklist**
> [bitnami/tomcat] Fix extraVolumes parameter

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
This PR attempts to fix a permissions issue when users use extended configuration without enabling persistence.
**Benefits**
Users can extend the configuration without enabling persistence.
None
- fixes #6206
N/A
**Checklist**
> [bitnami/postgresql-ha] Fix extendend config without persistence

- bitnami/dokuwiki/Chart.yaml
- bitnami/dokuwiki/README.md
- bitnami/dokuwiki/templates/deployment.yaml
- bitnami/dokuwiki/templates/postinit-configmap.yaml
- bitnami/dokuwiki/values.yaml
Adds support for post-init scripts.
**Benefits**
Adds additional feature supported by other charts.
None known.
**Checklist**
> [bitnami/dokuwiki] Add support for customPostInitScripts

- bitnami/memcached/Chart.yaml
- bitnami/memcached/README.md
- bitnami/memcached/ci/values-production.yaml
- bitnami/memcached/ci/values-with-persistence-and-metrics.yaml
- bitnami/memcached/templates/NOTES.txt
- bitnami/memcached/templates/_helpers.tpl
- bitnami/memcached/templates/deployment.yaml
- bitnami/memcached/templates/metrics-svc.yaml
- bitnami/memcached/templates/pdb.yaml
- bitnami/memcached/templates/secrets.yaml
- bitnami/memcached/templates/service.yaml
- bitnami/memcached/templates/serviceaccount.yaml
- bitnami/memcached/templates/servicemonitor.yaml
- bitnami/memcached/templates/statefulset.yaml
- bitnami/memcached/values.yaml
This PR standardizes the `bitnami/memcached` chart to be in line with the rest of the catalog.
**Benefits**
Changes the values structure forcing a major bump, check the README.md for more information.
N/A
N/A
**Checklist**
> [bitnami/memcached] Chart standardized

- bitnami/grafana/Chart.yaml
- bitnami/grafana/values.yaml
**Update initContainers type to list**
Update `initContainers` type from map `{}` to list `[]`. This update matches the existing parameter documentation:
```yaml
```
**Benefits**
Grafana chart originally installed with `initContainers` can be patched/upgraded.
No obvious drawbacks.
Not aware of any.
This change is expected to resolve the error:
```
coalesce.go:199: warning: cannot overwrite table with non table for initContainers (map[])
```
**Checklist**
> [bitnami/grafana] Update initContainers type to list

- bitnami/grafana-tempo/Chart.lock
- bitnami/grafana-tempo/Chart.yaml
- bitnami/grafana-tempo/README.md
- bitnami/grafana-tempo/ci/values-with-init-container-and-metrics.yaml
- bitnami/grafana-tempo/templates/NOTES.txt
- bitnami/grafana-tempo/templates/_helpers.tpl
- bitnami/grafana-tempo/templates/compactor/deployment.yaml
- bitnami/grafana-tempo/templates/compactor/service.yaml
- bitnami/grafana-tempo/templates/compactor/servicemonitor.yaml
- bitnami/grafana-tempo/templates/distributor/deployment.yaml
- bitnami/grafana-tempo/templates/distributor/service.yaml
- bitnami/grafana-tempo/templates/distributor/servicemonitor.yaml
- bitnami/grafana-tempo/templates/gossip-ring-headless-service.yaml
- bitnami/grafana-tempo/templates/ingester/service.yaml
- bitnami/grafana-tempo/templates/ingester/servicemonitor.yaml
- bitnami/grafana-tempo/templates/ingester/statefulset.yaml
- bitnami/grafana-tempo/templates/querier/deployment.yaml
- bitnami/grafana-tempo/templates/querier/service.yaml
- bitnami/grafana-tempo/templates/querier/servicemonitor.yaml
- bitnami/grafana-tempo/templates/query-frontend/deployment.yaml
- bitnami/grafana-tempo/templates/query-frontend/headless-service.yaml
- bitnami/grafana-tempo/templates/query-frontend/service.yaml
- bitnami/grafana-tempo/templates/query-frontend/servicemonitor.yaml
- bitnami/grafana-tempo/templates/service-account.yaml
- bitnami/grafana-tempo/templates/vulture/deployment.yaml
- bitnami/grafana-tempo/templates/vulture/service.yaml
- bitnami/grafana-tempo/templates/vulture/servicemonitor.yaml
- bitnami/grafana-tempo/values.yaml
This PR standardizes the `bitnami/grafana-tempo` chart to be in line with the rest of the catalog.
**Benefits**
Changes the values structure forcing a major bump, check the README.md for more information.
N/A
Blocked by https://github.com/bitnami/charts/pull/8668 (major bump in dep)
**Checklist**
> [bitnami/grafana-tempo] Chart standardized

- bitnami/wordpress/Chart.lock
- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/README.md
- bitnami/wordpress/ci/ingress-wildcard-values.yaml
- bitnami/wordpress/ci/values-metrics-and-ingress.yaml
- bitnami/wordpress/templates/NOTES.txt
- bitnami/wordpress/templates/_helpers.tpl
- bitnami/wordpress/templates/deployment.yaml
- bitnami/wordpress/templates/hpa.yaml
- bitnami/wordpress/templates/ingress.yaml
- bitnami/wordpress/templates/metrics-svc.yaml
- bitnami/wordpress/templates/pdb.yaml
- bitnami/wordpress/templates/secrets.yaml
- bitnami/wordpress/templates/serviceaccount.yaml
- bitnami/wordpress/templates/servicemonitor.yaml
- bitnami/wordpress/templates/svc.yaml
- bitnami/wordpress/templates/tls-secrets.yaml
- bitnami/wordpress/values.yaml
This PR standardizes the `bitnami/wordpress` chart to be in line with the rest of the catalog.
**Benefits**
Changes the values structure forcing a major bump, check the README.md for more information.
N/A
Blocked by https://github.com/bitnami/charts/pull/8668 (major bump in dep)
**Checklist**
> [bitnami/wordpress] Chart standardized

- bitnami/wordpress/Chart.yaml
- bitnami/wordpress/README.md
- bitnami/wordpress/templates/_helpers.tpl
- bitnami/wordpress/values.yaml
Allow templating externalDatabase.existingSecret, for example `{{ .Release.Name }}-mysql`
**Benefits**
We do not need to pass the exact secret name anymore for each release.
**Checklist**
> [bitnami/wordpress] tpl externaldb secret

- bitnami/kafka/Chart.yaml
- bitnami/kafka/templates/networkpolicy-egress.yaml
Fix duplicate resource-names for networkpolicies within kafka-chart.
**Benefits**
Fixes the resource-name for [networkpolicy-egress.yaml](bitnami/kafka/templates/networkpolicy-egress.yaml) to prevent failing deployments due to duplicate names.
- fixes #8724 
**Checklist**
> [bitnami/kafka] fix resource-name for networkpolicy-egress.yaml

- bitnami/solr/Chart.yaml
- bitnami/solr/templates/_helpers.tpl
- bitnami/solr/templates/ingress.yaml
This PR adds a missing named template that's required for the ingress rule to be properly rendered.
**Benefits**
Ingress can be enabled again.
None
- fixes #8717
N/A
**Checklist**
> [bitnami/solr] Add missing named template

- bitnami/redis/Chart.yaml
- bitnami/redis/README.md
Fix README to indicate that standalone redis architecture does not deploy a replica set
**Checklist**
> [bitnami/redis] Fix redis standalone section README

- bitnami/argo-cd/Chart.yaml
- bitnami/argo-cd/templates/tls-certs-cm.yaml
Fix the condition for creating the TLS certs configmap.
- fixes #8567
**Checklist**
> [bitnami/argo-cd] Fix tls certs configmap

- bitnami/tomcat/Chart.yaml
- bitnami/tomcat/templates/_pod.tpl
Signed-off-by: Peter Kassak <48527944+cache-sk@users.noreply.github.com>
When containerExtraPorts is used, it ends in "error converting YAML to JSON: yaml: line XY: did not find expected key", because of wrong indent.
**Benefits**
Fixed indent, so containerExtraPorts can be used.
None?
Not reported so far.
**Checklist**
> [bitnami/tomcat] wrong indent for containerExtraPorts fix

- bitnami/minio/Chart.yaml
- bitnami/minio/templates/provisioning-job.yaml
The Minio Helm chart does have an entry for entering tolerations for running on nodes which have taints, however, this is not cascaded over to the Provisioning Job when it's enabled and hence the Job will be stuck in a pending state since it cant find a node to deploy to.
Updated the provisioning-job.yaml to respect the tolerations set in the values.yaml chart
**Benefits**
Provisioning jobs can be successfully deployed on nodes which have taints
N.A
- fixes  #8769
**Checklist**
- [ x ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ x ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [ x ] All commits signed off and in agreement of [Developer …
> [bitnami/minio] Minio provisioning job toleration support

- bitnami/airflow/Chart.yaml
- bitnami/airflow/templates/rbac/role.yaml
1. If a task goes orphan and is adopted by a new scheduler instance, then this change could patch the orphaned task instance rather than sending a SIGTERM.
**Benefits**
1. The Task will proceed further with its execution instead of receiving a SIGTERM and getting killed.
- fixes #8766 
**Checklist**
- [ X] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [ X] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)
> [bitnami/airflow] Add 'patch' verb to pod

- bitnami/rabbitmq-cluster-operator/Chart.yaml
- bitnami/rabbitmq-cluster-operator/templates/cluster-operator/servicemonitor.yaml
- bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/deployment.yaml
- bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/servicemonitor.yaml
Add `app.kubernetes.io/component` and `app.kubernetes.io/part-of` labels where they were missing and remove the `app.kubernetes.io/part-of` label from a few label selectors.
**Benefits**
Labels on all manifests are now consistent throughout the chart. The `app.kubernetes.io/part-of` label has no additional benefit or difference on label selectors, so I removed it to make them all consistent.
Due to the inconsistencies of labeling and label selectors, the messaging topology operator metrics service and service monitor didn't match and no metrics were scraped for it.
New PR in place of #8411, as I couldn't reopen it.
**Checklist**
> [bitnami/rabbitmq-cluster-operator] Use consistent labeling and label selectors

- .github/workflows/vib.yaml
Removes the internal VMware URL replacement variable. This is only useful for within VMware VPN users but there is no need to use it within Bitnami charts repository
Signed-off-by: Martin Perez <martinpe@vmware.com>
> Removed internal VMware replace URL from bitnami public charts

- bitnami/kube-prometheus/Chart.yaml
- bitnami/kube-prometheus/README.md
- bitnami/kube-prometheus/values.yaml
> [bitnami/kube-prometheus] Fix typo in kube-prometheus README.md

- bitnami/aspnet-core/Chart.yaml
- bitnami/aspnet-core/templates/health-ingress.yaml
This PR fixes aspnet-core health ingress which is currently hard coded to use the beta version of the ingress api which is no longer supported in latest version of k8
**Benefits**
None
- fixes #8739
**Checklist**
> [bitnami/aspnet-core] Detect ingress apiVersion

- bitnami/postgresql-ha/Chart.yaml
- bitnami/postgresql-ha/README.md
- bitnami/postgresql-ha/values.yaml
Add option to pgpool postgresql-ha chart to use an existing secret store for the Pgpool admin password.
**Benefits**
Possibility to use own secret store for Pgpool admin password.
- fixes #8093
**Checklist**
> [bitnami/postgresql-ha]: Add existingSecret to pgpool values

- bitnami/thanos/Chart.yaml
- bitnami/thanos/templates/receive-distributor/pdb.yaml
**Thanos receive-distributor PDB selector labels**
**Benefits**
The PDB for receive-distributor target the right pods instead of reciever pods.
None
**Checklist**
> [bitnami/thanos] fix receive-distributor pdb selector

- bitnami/aspnet-core/Chart.yaml
- bitnami/aspnet-core/README.md
- bitnami/aspnet-core/templates/health-ingress.yaml
- bitnami/aspnet-core/values.yaml
Add `IngressClass` as an option when defining ingress-health
**Benefits**
Make health-ingress options the same as ingress and allow consumer to use standard k8 fields.
- see #8739
**Checklist**
> [bitnami/aspnet-core] add ingressClassName option to health ingress

- bitnami/redis-cluster/Chart.lock
- bitnami/redis-cluster/Chart.yaml
- bitnami/redis-cluster/templates/configmap.yaml
- bitnami/redis-cluster/templates/headless-svc.yaml
- bitnami/redis-cluster/templates/metrics-prometheus.yaml
- bitnami/redis-cluster/templates/metrics-svc.yaml
- bitnami/redis-cluster/templates/networkpolicy.yaml
- bitnami/redis-cluster/templates/poddisruptionbudget.yaml
- bitnami/redis-cluster/templates/prometheusrule.yaml
- bitnami/redis-cluster/templates/psp.yaml
- bitnami/redis-cluster/templates/redis-role.yaml
- bitnami/redis-cluster/templates/redis-rolebinding.yaml
- bitnami/redis-cluster/templates/redis-serviceaccount.yaml
- bitnami/redis-cluster/templates/redis-statefulset.yaml
- bitnami/redis-cluster/templates/redis-svc.yaml
- bitnami/redis-cluster/templates/scripts-configmap.yaml
- bitnami/redis-cluster/templates/secret.yaml
- bitnami/redis-cluster/templates/svc-cluster-external-access.yaml
- bitnami/redis-cluster/templates/tls-secret.yaml
- bitnami/redis-cluster/templates/update-cluster.yaml
The scope of this work is to add namesapce into all the templates used to generate the yaml files required to deploy all the components of this chart, if enabled.
This pretty much replicate the work from the redis chart, with the adjustments required and all the parts dedicated to this chart completed.
We migrated from the redis chart (using sentinel) and we noticed that this one was missing the namespace in the metadata object. 
We added it, tested it and it is running in our dev environment for a while, so we believe that this is correctly done.
Also the tests and the template generated looks ok.
We have generated a template with a "test-ns" namespace and all the components enabled, not completely filled, except for the ones that were affected by the scope …
> [bitnami/redis-cluster] Add namespace in metadata

- bitnami/external-dns/Chart.yaml
- bitnami/external-dns/templates/deployment.yaml
Uses a generated secret resource if `azure.useManagedIdentity` is `true`
**Benefits**
Fixes #8822
None
- fixes #8822
**Checklist**
> [bitnami/external-dns] Fix deployment error on AKS with MSI. (refs bitnami#8822)

- .github/workflows/vib.yaml
**Renaming tkg target platform**
Replacing _tkg-1.3.0-aws_ with _tkg_
- fixes #8838
> Replacing tkg target platform name

- bitnami/mongodb/Chart.yaml
- bitnami/mongodb/ci/metrics-values.yaml
- bitnami/mongodb/templates/standalone/dep-sts.yaml
Fix the command for the exporter.
The command was using a `--test` flag that isn't supported anymore. This was added to the chart logic in order to try and make the exporter start after MongoDB is already live, to avoid connection issues. However, this is not needed since each call to the exporter endpoint will create a new connection to get the data.
**Checklist**
> [bitnami/mongodb] Fix exporter command

- .github/workflows/generate-chart-readme.yml
Only run the readme-generator workflow when the `values.yaml` of a chart is modified, ignoring the files under the `ci` directory.
**Checklist**
> Don't run readme-generator when a ci values.yaml file is modified

- bitnami/redis/Chart.yaml
- bitnami/redis/README.md
- bitnami/redis/templates/replicas/statefulset.yaml
- bitnami/redis/values.yaml
Support custom init metrics container command
**Benefits**
useful for custom metrics image usage
N/A
N/A
N/A
**Checklist**
> [bitnami/redis] Support custom init command for metrics container

- bitnami/common/Chart.yaml
- bitnami/common/templates/_secrets.tpl
The current **"common.secrets.passwords.manage"** is a helper to manage secret passwords for a given secret/key. It basically does two things:
- If the given secret exists (release upgrade), it reuses the secret password that was previously set in the existing secret for the given key.
- If the given secret doesn't exist (new release installation), it creates a random secret password if the corresponding parameter is not set.
- If the given secret doesn't exist (new release installation), it creates a secret password based on a parameter if that parameter is set.
This help work flawlessly but there's a scenario it doesn't take into account:
- what happens if the given secret exists but the given key does not? E.g. …
> [bitnami/common] Improve "common.secrets.passwords.manage" helper
