bitnami/charts

mongodb/manifests/mongodb-rc.yaml
=> mongo: fix liveness and readiness probes

apache/values.yaml, drupal/charts/mariadb/values.yaml, drupal/values.yaml, ghost/charts/mariadb/values.yaml, jenkins/values.yaml, joomla/charts/mariadb/values.yaml, joomla/values.yaml, mariadb-cluster/values.yaml, mariadb/values.yaml, mediawiki/charts/mariadb/values.yaml, mediawiki/values.yaml, memcached/values.yaml, mongodb/values.yaml, nginx/values.yaml, odoo/charts/postgresql/values.yaml, odoo/values.yaml, phabricator/charts/mariadb/values.yaml, phpbb/charts/mariadb/values.yaml, phpbb/values.yaml, postgresql/values.yaml, rabbitmq/values.yaml, redis/values.yaml, redmine/charts/mariadb/values.yaml, redmine/values.yaml, testlink/charts/mariadb/values.yaml, testlink/values.yaml, tomcat/values.yaml, wildfly/values.yaml, wordpress/charts/mariadb/values.yaml, wordpress/values.yaml
=> updates chart images to their latest versions

apache/values.yaml, drupal/values.yaml, ghost/values.yaml, jenkins/values.yaml, joomla/values.yaml, mariadb-cluster/values.yaml, mediawiki/values.yaml, odoo/charts/postgresql/values.yaml, odoo/values.yaml, phabricator/values.yaml, phpbb/values.yaml, postgresql/values.yaml, rabbitmq/values.yaml, redmine/values.yaml, testlink/values.yaml, tomcat/values.yaml, wildfly/values.yaml, wordpress/values.yaml
=> values: uncomment lines that set defualt values

drupal/README.md, drupal/charts/mariadb/README.md, drupal/charts/mariadb/templates/_helpers.tpl, drupal/charts/mariadb/templates/deployment.yaml, drupal/charts/mariadb/values.yaml, drupal/templates/NOTES.txt, drupal/templates/svc.yaml, drupal/values.yaml
=> Added NOTES.txt to Drupal

redmine/Chart.yaml, redmine/values.yaml
Still building the image in DockerHub.
=> Updated Redmine to 3.3.1

drupal/Chart.yaml, drupal/values.yaml
=> drupal 0.3.2

incubator/owncloud/Chart.yaml, incubator/owncloud/values.yaml
Correct password is _bitnami_, I don't know the reason why it was established to _bitnami1_
=> Update owncloud version to 9.1.2

incubator/mariadb-cluster/Chart.yaml, incubator/mariadb-cluster/README.md, incubator/mariadb-cluster/templates/NOTES.txt, incubator/mariadb-cluster/templates/_helpers.tpl, incubator/mariadb-cluster/templates/master-deployment.yaml, incubator/mariadb-cluster/templates/master-pvc.yaml, incubator/mariadb-cluster/templates/master-svc.yaml, incubator/mariadb-cluster/templates/secrets.yaml, incubator/mariadb-cluster/templates/slave-deployment.yaml, incubator/mariadb-cluster/templates/slave-svc.yaml, incubator/mariadb-cluster/values.yaml
- adds PVC support
- adds random password support
- fixes health probes
- adds post deployment notes
=> [incubator/mariadb-cluster] release 0.4.0

incubator/elasticsearch/.helmignore, incubator/elasticsearch/Chart.yaml, incubator/elasticsearch/README.md, incubator/elasticsearch/templates/NOTES.txt, incubator/elasticsearch/templates/_helpers.tpl, incubator/elasticsearch/templates/deployment.yaml, incubator/elasticsearch/templates/pvc.yaml, incubator/elasticsearch/templates/svc.yaml, incubator/elasticsearch/values.yaml
The chart deploys a single node elasticsearch deployment
=> [incubator/elasticsearch] adds elasticsearch chart

incubator/tomcat/Chart.yaml, incubator/tomcat/README.md, incubator/tomcat/templates/deployment.yaml, incubator/tomcat/values.yaml
=> rename chart param `allowRemoteManagement` to `tomcatAllowRemoteManagement`

incubator/elasticsearch/values.yaml
=> ielasticsearch: request more memory than the maximum heapSize

README.md
=> readme: instructions to add the incubator repo

functions/crypto/Chart.yaml, functions/crypto/README.md, functions/crypto/templates/function.yaml
If possible, let's merge to check that the entire pipeline works, then we can make the chart better
=> WIP of a function

stable/phabricator/Chart.yaml, stable/phabricator/README.md, stable/phabricator/templates/ingress.yaml, stable/phabricator/values.yaml
Applying https://github.com/kubernetes/charts/pull/3370 to phabricator bitnami/chart
=> [stable/phabricator] add ingress and support reverse proxy tls

stable/testlink/Chart.yaml, stable/testlink/templates/deployment.yaml, stable/testlink/values.yaml
PR to sync with https://github.com/kubernetes/charts/pull/3905
=> [stable/testlink] Fix default SMTP configuration

stable/prestashop/Chart.yaml, stable/prestashop/templates/deployment.yaml, stable/prestashop/values.yaml
PR to sync https://github.com/kubernetes/charts/pull/3997
=> Disable check the cookie IP address

incubator/apache/Chart.yaml, incubator/apache/templates/deployment.yaml, incubator/apache/values.yaml, incubator/elasticsearch/Chart.yaml, incubator/elasticsearch/templates/client-deploy.yaml, incubator/elasticsearch/templates/data-statefulset.yaml, incubator/elasticsearch/templates/master-deploy.yaml, incubator/elasticsearch/values.yaml, incubator/mariadb-cluster/Chart.yaml, incubator/mariadb-cluster/templates/master-deploy.yaml, incubator/mariadb-cluster/templates/slave-deploy.yaml, incubator/mariadb-cluster/values.yaml, incubator/nginx/Chart.yaml, incubator/nginx/templates/deployment.yaml, incubator/nginx/values.yaml
Standardize docker image property in values file for apache, nginx, elasticsearch and mariadb-cluster to enable automatic uploads.
=> Standardize docker image property in values file

library/bitnami-common/Chart.yaml, library/bitnami-common/README.md
Minor improvement in bitnami-common chart
=> Add example in bitnami-common chart

README.md, bitnami/apache/Chart.yaml, bitnami/apache/README.md, bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/README.md, bitnami/jenkins/Chart.yaml, bitnami/jenkins/README.md, bitnami/mariadb-cluster/Chart.yaml, bitnami/mariadb-cluster/README.md, bitnami/mean/Chart.yaml, bitnami/mean/README.md, bitnami/memcached/Chart.yaml, bitnami/memcached/README.md, bitnami/mysql/Chart.yaml, bitnami/mysql/README.md, bitnami/nginx/Chart.yaml, bitnami/nginx/README.md, bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/node/requirements.yaml, bitnami/postgresql/Chart.yaml, bitnami/postgresql/README.md, bitnami/tensorflow-inception/Chart.yaml, bitnami/tensorflow-inception/README.md, bitnami/tomcat/Chart.yaml, bitnami/tomcat/README.md, bitnami/tomcat/values.yaml, bitnami/wildfly/Chart.yaml, bitnami/wildfly/README.md
This PRs updates the documentation to be consistent with the latest changes in the repo (https://github.com/bitnami/charts/pull/648)
=> Documentation fixes

bitnami/tomcat/Chart.yaml, bitnami/tomcat/templates/deployment.yaml
Remove default values from deployment.yaml in templates as they are already in values.yaml
=> [bitnami/tomcat] - Remove default values for tomcat

bitnami/tensorflow-inception/Chart.yaml, bitnami/tensorflow-inception/templates/NOTES.txt, bitnami/tensorflow-inception/values.yaml
Update tensorflow-serving image and fix outdated path in documentation
=> [bitnami/tensorflow] update tensorflow-serving image version

bitnami/mysql/Chart.yaml, bitnami/mysql/templates/NOTES.txt, bitnami/mysql/templates/master-svc.yaml, bitnami/mysql/templates/slave-statefulset.yaml
That way other applications can use MySQL with or without replication without any change in its configuration.
=> MySQL standard service name. 

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/data-statefulset.yaml, bitnami/elasticsearch/templates/master-deploy.yaml, bitnami/elasticsearch/values-production.yaml
=> Fixing wron heapSize on data/master replicaSet/deployment & values-production.yaml indentation

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/cm.yaml
Fixes https://github.com/bitnami/charts/issues/687
=> Adding missing space between key & value on ConfigMap

bitnami/postgresql/Chart.yaml, bitnami/postgresql/values-production.yaml
svc type not correct in the values-production.yaml file
=> Fix svc type for values-production.yaml for PostgreSQL

bitnami/nginx/Chart.yaml, bitnami/nginx/README.md, bitnami/nginx/templates/deployment.yaml, bitnami/nginx/templates/svc.yaml, bitnami/nginx/values.yaml
- Only configure HTTP by default, disable HTTPS
- Do not persist data
- Modify default "vhosts" folder. From /bitnami/nginx/conf/vhosts to /opt/bitnami/nginx/conf/vhosts.
=> Do not use volume for Nginx. Do not ship default SSL certs

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/coordinating-deploy.yaml, bitnami/elasticsearch/templates/data-statefulset.yaml, bitnami/elasticsearch/templates/ingest-deploy.yaml, bitnami/elasticsearch/templates/master-deploy.yaml
The fsGroup was in the wrong placement. Any strict checking of kubectl will make it fail. This PR fixes it
=> Set proper fsGroup location

bitnami/jenkins/Chart.yaml, bitnami/jenkins/templates/deployment.yaml
Jenkins was migrated from Tomcat to Jetty, we need to implement a little modification in the probes
=> Change Jetty probes

bitnami/kubeapps/Chart.yaml, bitnami/kubeapps/README.md, bitnami/kubeapps/templates/tests/test-chartsvc.yaml, bitnami/kubeapps/templates/tests/test-dashboard.yaml, bitnami/kubeapps/templates/tests/test-tiller-proxy.yaml, bitnami/kubeapps/values.yaml
=> [bitnami/kubeapps] sync to 0.2.0

bitnami/kubeapps/Chart.yaml, bitnami/kubeapps/values.yaml
=> kubeapps: update chart to 0.3.1

bitnami/etcd/Chart.yaml, bitnami/etcd/templates/statefulset.yaml
Fixes https://github.com/bitnami/charts/issues/782
=> Allow running etcd on a non-default namespace

bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/node/templates/deployment.yaml
What this PR does / why we need it:
Add spec.selector.matchLabels without the chart label.
Which issue this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close that issue when PR gets merged): fixes https://github.com/helm/charts/issues/5657
Chart was not being upgradable
=> [bitnami/node] Fix chart not being upgradable

bitnami/etcd/Chart.yaml, bitnami/etcd/templates/statefulset.yaml
Fixes https://github.com/bitnami/charts/issues/791.
The main issue was loading the env-vars for the new cluster state after add a new node.
=> [bitnami/etcd] Fix scaling etcd nodes

bitnami/mysql/Chart.yaml, bitnami/mysql/templates/master-statefulset.yaml, bitnami/mysql/templates/slave-statefulset.yaml
This PR fixes an issue when upgrading with PVC templates. See https://github.com/helm/charts/issues/7803
=> [bitnami/mysql] Fix issue with pvc on upgrades

bitnami/consul/Chart.yaml, bitnami/consul/README.md, bitnami/consul/templates/ui-service.yaml, bitnami/consul/values-production.yaml, bitnami/consul/values.yaml
Fixes https://github.com/bitnami/charts/issues/868
=> [bitnami/consul] Add service annotations

bitnami/node/Chart.yaml, bitnami/node/README.md
Fix https://github.com/bitnami/charts/issues/898
=> Update Node with OSBA Mongodb instructions

bitnami/mean/Chart.yaml, bitnami/mean/README.md
Fix https://github.com/bitnami/charts/issues/898
=> Update MEAN with OSBA Mongodb instructions

bitnami/apache/Chart.yaml, bitnami/apache/README.md, bitnami/apache/templates/svc.yaml, bitnami/apache/values.yaml
=> [bitnami/apache] Add service.type to values.yaml

bitnami/jenkins/Chart.yaml, bitnami/jenkins/README.md, bitnami/jenkins/templates/NOTES.txt, bitnami/jenkins/templates/svc.yaml, bitnami/jenkins/values.yaml
=> [bitnami/jenkins] Add service.type to values.yaml

bitnami/nginx/Chart.yaml, bitnami/nginx/README.md, bitnami/nginx/templates/svc.yaml, bitnami/nginx/values.yaml
=> [bitnami/nginx] Add service.port in values.yaml

bitnami/tomcat/Chart.yaml, bitnami/tomcat/README.md, bitnami/tomcat/templates/NOTES.txt, bitnami/tomcat/templates/svc.yaml, bitnami/tomcat/values.yaml
=> [bitnami/tomcat] Add service.port to values.yaml

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/README.md, bitnami/nginx-ingress-controller/templates/NOTES.txt, bitnami/nginx-ingress-controller/templates/controller-metrics-service.yaml, bitnami/nginx-ingress-controller/templates/controller-stats-service.yaml, bitnami/nginx-ingress-controller/templates/default-backend-service.yaml, bitnami/nginx-ingress-controller/values.yaml
=> [bitnami/nginx-ingress-controller] Normalize port names

bitnami/wildfly/Chart.yaml, bitnami/wildfly/README.md, bitnami/wildfly/templates/NOTES.txt, bitnami/wildfly/templates/svc.yaml, bitnami/wildfly/values.yaml
=> [stable/wildfly] Add service.port to values.yaml

bitnami/tensorflow-inception/Chart.yaml, bitnami/tensorflow-inception/values.yaml
Update Tensorflow Serving to 1.12.0
=> Update Tensorflow Serving to 1.12.0

bitnami/apache/Chart.yaml, bitnami/cassandra/Chart.yaml, bitnami/consul/Chart.yaml, bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx/Chart.yaml, bitnami/tensorflow-inception/Chart.yaml
=> Change logos

bitnami/cassandra/Chart.yaml, bitnami/cassandra/README.md, bitnami/consul/Chart.yaml, bitnami/external-dns/Chart.yaml, bitnami/tensorflow-inception/Chart.yaml, library/bitnami-common/Chart.yaml
Fix some typos and inconsistencies in the charts metadata
=> Fix metadata in different Charts

bitnami/kafka/Chart.yaml, bitnami/kafka/requirements.lock
It propagates https://github.com/bitnami/charts/pull/981 to the kafka chart.
=> [bitnami/kafka] Update zookeeper dependency

bitnami/elasticsearch/Chart.yaml
Increase patch version. It should have been bumped at https://github.com/bitnami/charts/pull/985
=> [bitnami/elasticsearch] Increase patch version

bitnami/cassandra/Chart.yaml, bitnami/cassandra/README.md, bitnami/cassandra/files/conf/README.md, bitnami/cassandra/templates/NOTES.txt, bitnami/cassandra/templates/_helpers.tpl, bitnami/cassandra/templates/configuration-cm.yaml, bitnami/cassandra/templates/statefulset.yaml, bitnami/cassandra/values-production.yaml, bitnami/cassandra/values.yaml
=> [bitnami/cassandra] Allow adding custom configuration files

bitnami/tensorflow-resnet/Chart.yaml
Add icon and change URL
**Benefits**
Display the icon and the proper URL in https://hub.helm.sh/charts/bitnami/tensorflow-resnet
=> [bitnami/tensorflow-resnet] Add icon and change URL

bitnami/tensorflow-inception/Chart.yaml
Fix home URL and add a new source
=> [bitnami/tensorflow-inception] Fix home URL and add source

bitnami/cassandra/Chart.yaml, bitnami/cassandra/templates/service.yaml
Because of an incorrect setting of the go template, the loadBalancerIP line was rendered without indentation. This PR fixes it
**Benefits**
=> [bitnami/cassandra] Fix issue with LoadBalancerIP

bitnami/node/Chart.yaml, bitnami/node/templates/deployment.yaml
Check if the user exists before attempting to create it, as the command fails in this case.
=> [bitnami/node] Conditional bitnami user creation

bitnami/mean/Chart.yaml, bitnami/mean/requirements.lock, bitnami/mean/requirements.yaml, bitnami/node/Chart.yaml, bitnami/node/requirements.lock, bitnami/node/requirements.yaml
Signed-off-by: Carlos Rodriguez Hernandez <crhernandez@bitnami.com>
Update mongo as a dependency in Node and MEAN
=> Update mongo as a dependency in Node and MEAN

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/templates/statefulset.yaml
Fix typo in `statefulset.yaml`
Fixes #1067
=> Fix typo in statefulset.yaml

bitnami/apache/values.yaml
Fix small typo in values.yaml comments
=> [bitnami/apache] Fix typo in values.yaml comments

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/coordinating-deploy.yaml, bitnami/elasticsearch/templates/data-statefulset.yaml, bitnami/elasticsearch/templates/ingest-deploy.yaml, bitnami/elasticsearch/templates/master-deploy.yaml
Fix templates when there's no configmap
=> [bitnami/elasticsearch] Fix templates when there's no configmap

bitnami/consul/Chart.yaml, bitnami/consul/templates/statefulset.yaml
Fix following syntax error:
```
Error: parse error in "consul/templates/statefulset.yaml": template: consul/templates/statefulset.yaml:259: unexpected EOF
```
=> Fix syntax issue in consul chart

bitnami/jenkins/Chart.yaml, bitnami/jenkins/README.md, bitnami/jenkins/templates/ingress.yaml, bitnami/jenkins/values.yaml
=> [bitnami/jenkins] Add ingress rules

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/templates/default-backend-deployment.yaml
=> [bitnami/nginx-ingress-controller] Fix probes

bitnami/tensorflow-inception/README.md
Signed-off-by: Alejandro Moreno <amoreno@bitnami.com>
Add a deprecation notice to the README.
**Benefits**
Tell the users that this chart has been deprecated.
=> [bitnami/tensorflow-inception] Deprecate tensorflow-inception

bitnami/mean/Chart.yaml, bitnami/mean/README.md
Changed Mean's README.md and Chart.yaml to mark Mean as deprecated.
=> MEAN deprecation

bitnami/minio/Chart.yaml, bitnami/minio/templates/deployment-standalone.yaml, bitnami/minio/templates/statefulset.yaml
This PR fixes the **deployment** and **statefulset** definitions so they set the right labels to the associated pods.
=> [bitnami/minio] Fix Pod Metadata Labels

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/README.md, bitnami/zookeeper/templates/NOTES.txt, bitnami/zookeeper/templates/_helpers.tpl, bitnami/zookeeper/templates/configmap.yaml, bitnami/zookeeper/templates/metrics-deployment.yaml, bitnami/zookeeper/templates/metrics-svc.yaml, bitnami/zookeeper/templates/poddisruptionbudget.yaml, bitnami/zookeeper/templates/secrets.yaml, bitnami/zookeeper/templates/statefulset.yaml, bitnami/zookeeper/templates/svc-headless.yaml, bitnami/zookeeper/templates/svc.yaml, bitnami/zookeeper/values-production.yaml, bitnami/zookeeper/values.yaml
This PR ensures the official labels are supported.
On the other hand, it updates the README.md including the metrics exporter parameters.
=> [bitnami/zookeeper] Fix labels + document metrics in README.md

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kafka/requirements.lock, bitnami/kafka/requirements.yaml
This PR updates the Kafka chart dependency: Zookeeper
=> [bitnami/kafka] Update dependencies

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/NOTES.txt, bitnami/kafka/templates/configmap.yaml, bitnami/kafka/templates/jmx-configmap.yaml, bitnami/kafka/templates/kafka-exporter.yaml, bitnami/kafka/templates/secrets.yaml, bitnami/kafka/templates/statefulset.yaml, bitnami/kafka/templates/svc-headless.yaml, bitnami/kafka/templates/svc.yaml
Update labels to the official format.
This is a follow-up PR of #1173
That's the reason why a major version hasn't been bumped
=> [bitnami/kafka] Adapt kafka to new labels format

bitnami/airflow/Chart.yaml, bitnami/airflow/values.yaml
=> [bitnami/airflow] Remove testing value

bitnami/airflow/Chart.yaml, bitnami/airflow/requirements.lock, bitnami/airflow/requirements.yaml
Signed-off-by: juan131 juan@bitnami.com
This PR updates Airflow so it uses the latest major version of PostgreSQL as dependency.
=> [bitnami/airflow] Update Airflow dependencies

bitnami/minio/Chart.yaml, bitnami/minio/templates/statefulset.yaml
Change `.Values.persistence.podAnnotations` to `.Values.persistence.annotations`, as defined in both `values.yaml` and `values-production.yaml`.
**Benefits**
It will correctly use the annotations.
=> [bitnami/minio] Fix PVC annotations

bitnami/tomcat/Chart.yaml, bitnami/tomcat/values.yaml
Everything is ready in our internal pipeline in order to release using the new branch from now on
=> [bitnami/tomcat] Update chart to Tomcat 9.0

bitnami/mysql/Chart.yaml, bitnami/mysql/values-production.yaml, bitnami/mysql/values.yaml
Everything is ready in our internal pipeline in order to release using the new branch from now on
=> [bitnami/mysql] Update chart to MySQL 8.X

README.md, bitnami/pytorch/.helmignore, bitnami/pytorch/Chart.yaml, bitnami/pytorch/README.md, bitnami/pytorch/templates/NOTES.txt, bitnami/pytorch/templates/_helpers.tpl, bitnami/pytorch/templates/configmap.yaml, bitnami/pytorch/templates/deployment.yaml, bitnami/pytorch/templates/pvc.yaml, bitnami/pytorch/templates/service.yaml, bitnami/pytorch/templates/statefulset.yml, bitnami/pytorch/values-production.yaml, bitnami/pytorch/values.yaml
Add a new chart to our catalogue: PyTorch.
=> Add PyTorch chart

library/bitnami-common/Chart.yaml
Fix typo in chart description
**Benefits**
Chart description without typos :)
=> Fix typo in bitnami-common chart description

bitnami/minio/Chart.yaml, bitnami/minio/templates/deployment-standalone.yaml, bitnami/minio/templates/statefulset.yaml
This PR fixes the MinIO chart by ensuring all the environment variables are properly quoted.
=> [bitnami/minio] Fix MinIO

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/templates/metrics-deployment.yaml
If the IPs of the ZooKeeper pods change, the running metrics exporter
won't notice. With these health checks it will be automatically
restarted.
=> [bitnami/zookeeper] Configure probes for metrics exporter

bitnami/pytorch/Chart.yaml, bitnami/pytorch/README.md, bitnami/pytorch/templates/service.yaml, bitnami/pytorch/values-production.yaml, bitnami/pytorch/values.yaml
Export service.type to the values.yaml to be able to specify the type of service.
**Benefits**
More flexibility to configure the way to access pytorch
None
None
=> Add property to specify service type

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/README.md, bitnami/zookeeper/values-production.yaml, bitnami/zookeeper/values.yaml
Specify the way to specify serverUsers and serverPasswords properties.
None
https://github.com/bitnami/charts/issues/1192
=> Clarify zookeeper serverUsers and serverPasswords input format

bitnami/kafka/Chart.yaml, bitnami/kafka/values-production.yaml, bitnami/kafka/values.yaml
=> [bitnami/kafka] Fix values*.yaml syntax

bitnami/airflow/Chart.yaml, bitnami/airflow/README.md, bitnami/airflow/templates/NOTES.txt, bitnami/airflow/templates/_helpers.tpl, bitnami/airflow/templates/deployment-scheduler.yaml, bitnami/airflow/templates/deployment-web.yaml, bitnami/airflow/templates/statefulset-worker.yaml, bitnami/airflow/values-production.yaml, bitnami/airflow/values.yaml
This PR adds a sidecar container to update git repository periodically
**Benefits**
It ensures the DAGs are consistent amongst the nodes
None
=> [bitnami/airflow] Add sidecar container to update git repository periodically

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/values-production.yaml, bitnami/elasticsearch/values.yaml
=> [bitnami/kafka] update to 7.1.1

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md
Add that ZooKeeper persistency is separately configured
**Benefits**
=> Update Kafka readme regarding persistency

README.md, bitnami/mxnet/.helmignore, bitnami/mxnet/Chart.yaml, bitnami/mxnet/README.md, bitnami/mxnet/templates/NOTES.txt, bitnami/mxnet/templates/_helpers.tpl, bitnami/mxnet/templates/configmap.yaml, bitnami/mxnet/templates/deployment-pvc.yaml, bitnami/mxnet/templates/headless-svc.yaml, bitnami/mxnet/templates/scheduler-deployment.yaml, bitnami/mxnet/templates/scheduler-service.yaml, bitnami/mxnet/templates/server-statefulset.yml, bitnami/mxnet/templates/standalone-deployment.yaml, bitnami/mxnet/templates/worker-statefulset.yml, bitnami/mxnet/values-production.yaml, bitnami/mxnet/values.yaml
Signed-off-by: Javier Salmeron Garcia <javsalgar@Javiers-MacBook-Pro.local>
This PR adds the bitnami/mxnet chart. It has the following features
- Standalone vs Distributed mode (with server, worker and scheduler nodes)
- Custom applications using ConfigMaps or git repository.
- Sensitive data mount using secrets
- Custom sidecars and init containers
**Benefits**
=> [bitnami/mxnet] Release MXNet chart

.github/PULL_REQUEST_TEMPLATE.md
Add a checklist to the PR template
=> Add checklist to PULL_REQUEST_TEMPLATE.md

bitnami/cassandra/Chart.yaml, bitnami/cassandra/templates/statefulset.yaml
This PR adds the env var CASSANDRA_USER so we are able to modify the username
Test
```
I have no name!@my-release-cassandra-0:/$ cqlsh -u admin -p password
Warning: Cannot create directory at `/.cassandra`. Command history will not be saved.
Connected to cassandra at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.11.4 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
admin@cqlsh>
```
**Benefits**
https://github.com/bitnami/charts/issues/1248
=> [bitnami/cassandra] Fix dbUser.user not being used

README.md, bitnami/spark/.helmignore, bitnami/spark/Chart.yaml, bitnami/spark/README.md, bitnami/spark/templates/NOTES.txt, bitnami/spark/templates/_helpers.tpl, bitnami/spark/templates/headless-svc.yaml, bitnami/spark/templates/hpa-worker.yaml, bitnami/spark/templates/ingress.yaml, bitnami/spark/templates/secret.yaml, bitnami/spark/templates/statefulset-master.yaml, bitnami/spark/templates/statefulset-worker.yaml, bitnami/spark/templates/svc-master.yaml, bitnami/spark/values-production.yaml, bitnami/spark/values.yaml
Add Spark Chart
**Benefits**
A new Chart is added
=> [bitnami/spark] Add Spark Helm Chart

bitnami/spark/Chart.yaml, bitnami/spark/templates/_helpers.tpl, bitnami/spark/templates/statefulset-master.yaml, bitnami/spark/templates/statefulset-worker.yaml
Add template to set the image.
**Benefits**
=> [bitnami/spark] Add template for image on Spark Chart

.github/PULL_REQUEST_TEMPLATE.md
Add the word `fixes` to the template to avoid users forget about it when the PR closes an issue.
**Benefits**
implement the changes in both files
=> Add fixes to PR template

bitnami/spark/Chart.yaml, bitnami/spark/templates/statefulset-master.yaml, bitnami/spark/templates/statefulset-worker.yaml
Affinity didn't work as it was added in the wrong section.
**Benefits**
Affinity will work now.
None.
- Fixes https://github.com/bitnami/charts/issues/1300
=> [bitnami/spark] Fix affinity

bitnami/magento/Chart.yaml, bitnami/magento/requirements.lock, bitnami/magento/templates/_helpers.tpl, bitnami/magento/templates/apache-pvc.yaml, bitnami/magento/templates/deployment.yaml, bitnami/magento/templates/externaldb-secrets.yaml, bitnami/magento/templates/magento-pvc.yaml, bitnami/magento/templates/secrets.yaml, bitnami/magento/templates/svc.yaml
Add a template called `magento.chart` to set the Chart name on the `YAML` files.
**Benefits**
- fixes #
=> [bitnami/magento] Create template for magento chart name and version

bitnami/kafka/Chart.yaml, bitnami/kafka/requirements.lock, bitnami/kafka/requirements.yaml, bitnami/magento/Chart.yaml, bitnami/magento/requirements.lock, bitnami/magento/requirements.yaml, bitnami/node/Chart.yaml, bitnami/node/requirements.lock, bitnami/node/requirements.yaml
Update dependencies for Magento, Node and Kafka charts.
**Benefits**
- fixes #
=> Update dependencies for some bitnami charts

bitnami/minio/Chart.yaml, bitnami/minio/templates/networkpolicy.yaml, bitnami/minio/templates/statefulset.yaml
When deploying with the `values-production.yaml` the deployment was failing because the indentation of a section in the `networkpolicy.yaml` was not correct, this PR fix that problem.
**Benefits**
- fixes #1317 
=> [bitnami/minio ]Fix minio networkPolicy indentation

bitnami/tensorflow-resnet/Chart.yaml, bitnami/tensorflow-resnet/templates/deployment.yaml
This is for our automated testing pipeline to properly test this chart
**Benefits**
- fixes #
=> [bitnami/tensorflow-resnet] Change container name to tensorflow-serving

bitnami/magento/Chart.yaml, bitnami/magento/requirements.lock, bitnami/magento/requirements.yaml
Update dependencies for Magento chart
**Benefits**
Magento chart will benefit from the latest features added to the elasticseach chart.
- fixes #
**Checklist**
=> [bitnami/magento] Update dependencies

bitnami/minio/Chart.yaml, bitnami/minio/templates/tls-secrets.yaml, bitnami/nginx/Chart.yaml, bitnami/nginx/templates/tls-secrets.yaml
Fix incorrect scope when using range in tls-secrets.yaml
**Benefits**
https://github.com/bitnami/charts/issues/1320
- fixes #
=> [bitnami/minio, bitnami/nginx] Fix scope in tls

bitnami/pytorch/Chart.yaml, bitnami/pytorch/templates/deployment.yaml, bitnami/pytorch/templates/statefulset.yml
Previously, when `volumePermissions` was enabled, we were using a wrong path.
**Benefits**
- fixes #
=> [bitnami/pytorch] Fix persistence path

bitnami/harbor/Chart.yaml, bitnami/harbor/README.md, bitnami/harbor/requirements.yaml, bitnami/harbor/templates/_helpers.tpl, bitnami/harbor/templates/chartmuseum/chartmuseum-cm-envvars.yaml, bitnami/harbor/templates/chartmuseum/chartmuseum-cm.yaml, bitnami/harbor/templates/chartmuseum/chartmuseum-dpl.yaml, bitnami/harbor/templates/chartmuseum/chartmuseum-pvc.yaml, bitnami/harbor/templates/chartmuseum/chartmuseum-secret.yaml, bitnami/harbor/templates/chartmuseum/chartmuseum-svc.yaml, bitnami/harbor/values-production.yaml, bitnami/harbor/values.yaml
This PR adds the ChartMuseum component to the Harbor Helm Chart
**Benefits**
- fixes #
=> [bitnami/harbor] Add ChartMuseum component to Harbor Chart

bitnami/harbor/Chart.yaml
Fix the link to Harbor logo.
- none
- none
=> [bitnami/harbor] Fix Harbor logo link.

bitnami/etcd/Chart.yaml, bitnami/etcd/templates/cronjob.yaml
The change fixes a bug in the etcd-cluster-snapshotter pod and now the snapshotter will work when TLS is enabled with self signed certificates
**Benefits**
snapshotter will work when TLS is enabled with self signed certificates
- fixes #
#1359 
=> bitnami/etcd fix #1359

bitnami/harbor/Chart.yaml, bitnami/harbor/requirements.lock
Update Harbor dependencies (PostgreSQL and Redis)
**Checklist**
=> [bitnami/harbor] Update Harbor dependencies (PostgreSQL and Redis)

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/_helpers.tpl
=> [bitnami/harbor] Fix values path for coreImage on _helpers.tpl

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/_helpers.tpl, bitnami/harbor/values-production.yaml, bitnami/harbor/values.yaml
=> [bitnami/harbor] Not use redis password when usePassword is false

bitnami/cassandra/Chart.yaml, bitnami/cassandra/templates/networkpolicy.yaml
When network policies were enabled, the internal cluster communication would not work. This PR fixes that.
**Benefits**
- fixes #
=> [bitnami/cassandra] Fix networkpolicy

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/README.md, bitnami/nginx-ingress-controller/values-production.yaml, bitnami/nginx-ingress-controller/values.yaml
tcp and udp are duplicated in values.yaml
**Benefits**
- fixes #
=> [bitnami/nginx-ingress-controller] Remove duplicated values

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/README.md, bitnami/nginx-ingress-controller/templates/controller-deployment.yaml, bitnami/nginx-ingress-controller/values-production.yaml, bitnami/nginx-ingress-controller/values.yaml
We thought that the values were duplicated but actually we had to rename one
**Benefits**
- fixes #
=> [bitnami/nginx-ingress-controller] Revert removal of tcp and udp

.github/PULL_REQUEST_TEMPLATE.md
Comments the `[Place an '[X]' (no spaces) in all applicable fields. Please remove unrelated fields.]` message so that it doesn't show in the final PR.
**Benefits**
Clearer PRs.
=> Comment 'Place [X]...' instructions

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/statefulset.yaml, bitnami/kafka/values-production.yaml, bitnami/kafka/values.yaml
The environment variables for the Kafka container were fixed some time ago. However, they were left outdated in the chart. This PR fixes this issue.
**Benefits**
Environment variables set in `values.yaml` are not properly detected by Kafka.
- Fixes https://github.com/bitnami/bitnami-docker-kafka/issues/62
**Checklist**
=> [bitnami/kafka] Fix name of environment variables set in chart

bitnami/cassandra/Chart.yaml, bitnami/cassandra/README.md, bitnami/cassandra/values-production.yaml, bitnami/cassandra/values.yaml
Change from a node.js based container to a bash container. No major changes necessary when upgrading
**Benefits**
- fixes https://github.com/bitnami/bitnami-docker-cassandra/issues/56
**Checklist** 
=> [bitnami/cassandra] Use Cassandra bash container

bitnami/airflow/Chart.yaml, bitnami/airflow/requirements.lock, bitnami/harbor/Chart.yaml, bitnami/harbor/requirements.lock
Update PostgreSQL dependency to fix CVE
**Benefits**
- fixes #
**Checklist** 
=> Update postgresql dependency in Harbor and Airflow

bitnami/consul/Chart.yaml, bitnami/consul/README.md, bitnami/consul/values-production.yaml, bitnami/consul/values.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/consul] Change image to the bash based one

README.md, bitnami/kibana/.helmignore, bitnami/kibana/Chart.yaml, bitnami/kibana/README.md, bitnami/kibana/requirements.lock, bitnami/kibana/requirements.yaml, bitnami/kibana/templates/NOTES.txt, bitnami/kibana/templates/_helpers.tpl, bitnami/kibana/templates/configmap.yml, bitnami/kibana/templates/deployment.yaml, bitnami/kibana/templates/ingress.yaml, bitnami/kibana/templates/plugins-configmap.yml, bitnami/kibana/templates/pvc.yaml, bitnami/kibana/templates/saved-objects-configmap.yml, bitnami/kibana/templates/service.yaml, bitnami/kibana/templates/tests/test-connection.yaml, bitnami/kibana/values-production.yaml, bitnami/kibana/values.yaml
Add Kibana chart with the following features:
* Custom init and sidecars containers (we already have that in wordpress)
* Custom envs (in the form of direct value or secret)
* Custom configuration files
* Ingress
* Extra volume mounts and extra volumes
* Import saved data
* Plugin installation
* Use existing volume claims
* Add extra config maps mounts
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/kibana] Add Kibana chart

bitnami/kibana/Chart.yaml, bitnami/kibana/values-production.yaml, bitnami/kibana/values.yaml
The image version that was using is not compatible. This PR fixes it
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/kibana] Fix kibana image

bitnami/kibana/Chart.yaml, bitnami/kibana/README.md, bitnami/kibana/values-production.yaml, bitnami/kibana/values.yaml
This is done for improving the user experience for those testing with the bundled elasticsearch
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/kibana] Expose elasticsearch.sysctlImage.enabled

bitnami/tomcat/Chart.yaml, bitnami/tomcat/README.md, bitnami/tomcat/values.yaml
Update version due to container upgrading to bash
**Checklist**
=> [bitnami/tomcat] Update version due container moved to bash

bitnami/grafana/Chart.yaml, bitnami/grafana/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/grafana] Add LDAP documentation to README.md

bitnami/grafana/Chart.yaml, bitnami/grafana/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/grafana] Ldap docs

bitnami/grafana/Chart.yaml, bitnami/grafana/README.md
Add syntax highlighting to missing blocks.
**Checklist**
=> [bitnami/grafana] Add missing syntax highlighting to blocks

bitnami/etcd/Chart.yaml, bitnami/etcd/README.md
Removes a duplicated section in the README.
**Checklist**
=> [bitnami/etcd] Remove duplicated section

README.md, bitnami/influxdb/.helmignore, bitnami/influxdb/Chart.yaml, bitnami/influxdb/README.md, bitnami/influxdb/files/conf/README.md, bitnami/influxdb/files/docker-entrypoint-initdb.d/README.md, bitnami/influxdb/templates/NOTES.txt, bitnami/influxdb/templates/_helpers.tpl, bitnami/influxdb/templates/influxdb/configmap.yaml, bitnami/influxdb/templates/influxdb/initdb-scripts-configmap.yaml, bitnami/influxdb/templates/influxdb/metrics-svc.yaml, bitnami/influxdb/templates/influxdb/pvc.yaml, bitnami/influxdb/templates/influxdb/secrets.yaml, bitnami/influxdb/templates/influxdb/service-headless.yaml, bitnami/influxdb/templates/influxdb/service.yaml, bitnami/influxdb/templates/influxdb/standalone-dpl.yaml, bitnami/influxdb/templates/influxdb/statefulset.yaml, bitnami/influxdb/templates/ingress.yaml, bitnami/influxdb/templates/networkpolicy.yaml, bitnami/influxdb/templates/relay/configmap.yaml, bitnami/influxdb/templates/relay/deployment.yaml, bitnami/influxdb/templates/relay/service.yaml, bitnami/influxdb/values-production.yaml, bitnami/influxdb/values.yaml
This PR adds a new Helm chart to the catalog: InfluxDB
InfluxDB is an open source time-series database designed to handle large write and read loads in real-time.
This chart support two different architecture setups: **standalone** and **high-availability**. please put extra emphasis on this peculiarity.
=> Add new InfluxDB chart

bitnami/jenkins/Chart.yaml, bitnami/jenkins/README.md
Standardize README.md so it is readable by Marketplaces
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/jenkins] Standardize README.md

bitnami/tomcat/Chart.yaml, bitnami/tomcat/README.md, bitnami/tomcat/templates/ingress.yaml, bitnami/tomcat/values.yaml
Signed-off-by: Gonzalo Gomez <gonzalo@bitnami.com>
Update the Ingress configuration to be the same than for other charts
**Benefits**
- fixes #
**Checklist**
=> [bitnami/tomcat] Update Ingress configuration for Tomcat

bitnami/tensorflow-resnet/Chart.yaml, bitnami/tensorflow-resnet/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/tensorflow-resnet] Update prerequisites

bitnami/mxnet/Chart.yaml, bitnami/mxnet/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/mxnet] Update prerequisites

bitnami/pytorch/Chart.yaml, bitnami/pytorch/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/pytorch] Update prerequisites

bitnami/node/Chart.yaml, bitnami/node/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/node] Update prerequisites

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/nginx-ingress-controller] Update prerequisites

bitnami/nginx/Chart.yaml, bitnami/nginx/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/nginx] Update prerequisites

bitnami/mysql/Chart.yaml, bitnami/mysql/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/mysql] Update prerequisites

bitnami/memcached/Chart.yaml, bitnami/memcached/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/memcached] Update prerequisites

bitnami/kibana/Chart.yaml, bitnami/kibana/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/kibana] Update prerequisites

bitnami/harbor/Chart.yaml, bitnami/harbor/README.md, bitnami/harbor/values.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/harbor] Update prerequisites

bitnami/grafana/Chart.yaml, bitnami/grafana/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/grafana] Update prerequisites

bitnami/etcd/Chart.yaml, bitnami/etcd/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/etcd] Update prerequisites

bitnami/consul/Chart.yaml, bitnami/consul/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/consul] Update prerequisites

bitnami/cassandra/Chart.yaml, bitnami/cassandra/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/cassandra] Update pre-requisites

bitnami/apache/Chart.yaml, bitnami/apache/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/apache] Update prerequisites

bitnami/airflow/Chart.yaml, bitnami/airflow/values-production.yaml, bitnami/airflow/values.yaml
Fix wrong image tag 
**Checklist** 
=> [bitnami/airflow] Fix wrong image tag

bitnami/influxdb/Chart.yaml, bitnami/influxdb/README.md, bitnami/jenkins/Chart.yaml, bitnami/jenkins/README.md, bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kibana/Chart.yaml, bitnami/kibana/README.md, bitnami/magento/Chart.yaml, bitnami/magento/README.md, bitnami/mariadb-galera/Chart.yaml, bitnami/mariadb-galera/README.md, bitnami/memcached/Chart.yaml, bitnami/memcached/README.md, bitnami/metrics-server/Chart.yaml, bitnami/metrics-server/README.md, bitnami/minio/Chart.yaml, bitnami/minio/README.md, bitnami/mxnet/Chart.yaml, bitnami/mxnet/README.md, bitnami/mysql/Chart.yaml, bitnami/mysql/README.md
```
.
├── ## Parameters
│  └── (Table)
├── ## Configuration and installation details
│  ├── ### Rolling VS Immutable tags
│  ├── ### Production configuration and horizontal scaling
│  └── ### Forwarding the logs to another service
└── ## Persistence
```
Batch II: From InfluxDB to MySQL
=> Adapt README in charts (II)

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/README.md, bitnami/nginx/Chart.yaml, bitnami/nginx/README.md, bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/pytorch/Chart.yaml, bitnami/pytorch/README.md, bitnami/spark/Chart.yaml, bitnami/spark/README.md, bitnami/tensorflow-resnet/Chart.yaml, bitnami/tensorflow-resnet/README.md, bitnami/tomcat/Chart.yaml, bitnami/tomcat/README.md, bitnami/wildfly/Chart.yaml, bitnami/wildfly/README.md, bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/README.md
```
.
├── ## Parameters
│  └── (Table)
├── ## Configuration and installation details
│  ├── ### Rolling VS Immutable tags
│  ├── ### Production configuration and horizontal scaling
│  └── ### Forwarding the logs to another service
└── ## Persistence
```
Batch III: From Nginx to Zookeeper
=> Adapt README in charts (III)

bitnami/minio/Chart.yaml, bitnami/minio/values-production.yaml, bitnami/minio/values.yaml
The minio and minio client image tags were set to the same tag while they are not the same. This PR fixes the minio tag and updates the minio client one to the latest version.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/minio] Fix minio and update minio client image tags

bitnami/kibana/Chart.yaml, bitnami/kibana/templates/service.yaml
=> [bitnami/kibana] fix typo

bitnami/grafana/Chart.yaml, bitnami/grafana/README.md, bitnami/grafana/templates/service.yaml, bitnami/grafana/templates/servicemonitor.yaml, bitnami/grafana/values-production.yaml, bitnami/grafana/values.yaml
Adds Prometheus Operator ServiceMonitor support
=> [bitnami/grafana] adds servicemonitor support

bitnami/mysql/Chart.yaml, bitnami/mysql/values-production.yaml, bitnami/mysql/values.yaml
=> add `plugin_dir` configuration to the mysql configuration

bitnami/apache/Chart.yaml, bitnami/apache/values.schema.json
Signed-off-by: Andres Martinez Gotor <andres@bitnami.com>
The annotations for Kubeapps have changed a bit. This PR uses the latest annotations.
**Checklist** 
=> [bitnami/apache] Update values.schema.json to reflect latest format

bitnami/postgresql-ha/.helmignore, bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/README.md, bitnami/postgresql-ha/files/README.md, bitnami/postgresql-ha/files/conf.d/README.md, bitnami/postgresql-ha/files/docker-entrypoint-initdb.d/README.md, bitnami/postgresql-ha/templates/NOTES.txt, bitnami/postgresql-ha/templates/_helpers.tpl, bitnami/postgresql-ha/templates/ldap-secrets.yaml, bitnami/postgresql-ha/templates/networkpolicy.yaml, bitnami/postgresql-ha/templates/pgpool/deployment.yaml, bitnami/postgresql-ha/templates/pgpool/ingress.yaml, bitnami/postgresql-ha/templates/pgpool/pdb.yaml, bitnami/postgresql-ha/templates/pgpool/secrets.yaml, bitnami/postgresql-ha/templates/pgpool/service.yaml, bitnami/postgresql-ha/templates/postgresql/configmap.yaml, bitnami/postgresql-ha/templates/postgresql/extended-configmap.yaml, bitnami/postgresql-ha/templates/postgresql/initdb-scripts-configmap.yaml, bitnami/postgresql-ha/templates/postgresql/metrics-service.yaml, bitnami/postgresql-ha/templates/postgresql/pdb.yaml, bitnami/postgresql-ha/templates/postgresql/secrets.yaml, bitnami/postgresql-ha/templates/postgresql/service-headless.yaml, bitnami/postgresql-ha/templates/postgresql/service.yaml, bitnami/postgresql-ha/templates/postgresql/servicemonitor.yaml, bitnami/postgresql-ha/templates/postgresql/statefulset.yaml, bitnami/postgresql-ha/values-production.yaml, bitnami/postgresql-ha/values.yaml
This chart was already reviewed internally, I just copied the files from GitLab
**Checklist**
=> [bitnami/postgresql-ha] Add new chart: postgresql-ha

bitnami/apache/Chart.yaml, bitnami/apache/README.md, bitnami/apache/templates/_helpers.tpl, bitnami/apache/templates/configmap-vhosts.yaml, bitnami/apache/templates/configmap.yaml, bitnami/apache/templates/deployment.yaml, bitnami/apache/templates/ingress.yaml, bitnami/apache/templates/svc.yaml, bitnami/apache/values.yaml
=> [bitnami/apache] Lint chart

bitnami/cassandra/Chart.yaml, bitnami/cassandra/templates/_helpers.tpl, bitnami/cassandra/templates/cassandra-secret.yaml, bitnami/cassandra/templates/configuration-cm.yaml, bitnami/cassandra/templates/headless-svc.yaml, bitnami/cassandra/templates/initdb-configmap.yaml, bitnami/cassandra/templates/networkpolicy.yaml, bitnami/cassandra/templates/pdb.yaml, bitnami/cassandra/templates/service.yaml, bitnami/cassandra/templates/statefulset.yaml, bitnami/cassandra/values-production.yaml, bitnami/cassandra/values.yaml
=> [bitnami/cassandra] Lint chart

bitnami/harbor/Chart.yaml, bitnami/harbor/values-production.yaml, bitnami/harbor/values.yaml
**Benefits**
- fixes #1598
**Checklist** 
=> [bitnami/harbor] Fix image tag for Harbor portal

bitnami/influxdb/Chart.yaml
#1565 was merged without increasing the chart version. This PR increases it.
**Checklist**
=> [bitnami/influxdb] Increase version

bitnami/etcd/Chart.yaml, bitnami/etcd/templates/statefulset.yaml
fixed a typo in the update strategy of the etcd statefulset
=> [bitnami/etcd] fix updateStrategy in statefulset

bitnami/grafana/Chart.yaml, bitnami/grafana/README.md, bitnami/grafana/templates/NOTES.txt, bitnami/grafana/templates/_helpers.tpl, bitnami/grafana/templates/configmap.yaml, bitnami/grafana/templates/dashboard-provider.yaml, bitnami/grafana/templates/deployment.yaml, bitnami/grafana/templates/ingress.yaml, bitnami/grafana/templates/pvc.yaml, bitnami/grafana/templates/secret.yaml, bitnami/grafana/templates/service.yaml, bitnami/grafana/templates/servicemonitor.yaml, bitnami/grafana/values-production.yaml, bitnami/grafana/values.yaml
=> [bitnami/grafana] Lint chart

bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/aggregator-statefulset.yaml, bitnami/fluentd/templates/clusterrole.yaml, bitnami/fluentd/templates/clusterrolebinding.yaml, bitnami/fluentd/templates/forwarder-daemonset.yaml, bitnami/fluentd/templates/servicemonitor.yaml, bitnami/fluentd/templates/tls-certs.yaml, bitnami/fluentd/values-production.yaml, bitnami/fluentd/values.yaml
=> [bitnami/fluentd] Lint chart

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/_helpers.tpl, bitnami/influxdb/templates/influxdb/configmap.yaml, bitnami/influxdb/templates/influxdb/initdb-scripts-configmap.yaml, bitnami/influxdb/templates/influxdb/metrics-svc.yaml, bitnami/influxdb/templates/influxdb/pvc.yaml, bitnami/influxdb/templates/influxdb/secrets.yaml, bitnami/influxdb/templates/influxdb/service-headless.yaml, bitnami/influxdb/templates/influxdb/service.yaml, bitnami/influxdb/templates/influxdb/servicemonitor.yaml, bitnami/influxdb/templates/influxdb/standalone-dpl.yaml, bitnami/influxdb/templates/influxdb/statefulset.yaml, bitnami/influxdb/templates/ingress.yaml, bitnami/influxdb/templates/networkpolicy.yaml, bitnami/influxdb/templates/relay/configmap.yaml, bitnami/influxdb/templates/relay/deployment.yaml, bitnami/influxdb/templates/relay/service.yaml, bitnami/influxdb/values-production.yaml, bitnami/influxdb/values.yaml
=> [bitnami/influxdb] Lint chart

bitnami/jenkins/Chart.yaml, bitnami/jenkins/README.md, bitnami/jenkins/ci/values-with-metrics-and-ingress.yaml, bitnami/jenkins/templates/NOTES.txt, bitnami/jenkins/templates/_helpers.tpl, bitnami/jenkins/templates/deployment.yaml, bitnami/jenkins/templates/ingress.yaml, bitnami/jenkins/templates/pvc.yaml, bitnami/jenkins/templates/secrets.yaml, bitnami/jenkins/templates/svc.yaml, bitnami/jenkins/values.yaml
=> [bitnami/jenkins] Lint chart

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/NOTES.txt, bitnami/harbor/templates/_helpers.tpl, bitnami/harbor/templates/chartmuseum/chartmuseum-cm-envvars.yaml, bitnami/harbor/templates/core/core-cm-envvars.yaml, bitnami/harbor/templates/notary/notary-cm.yaml, bitnami/harbor/templates/registry/registry-cm.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/harbor] Add function to check the externalURL http prefix

bitnami/mariadb-galera/Chart.yaml, bitnami/mariadb-galera/ci/values-production-with-rbac.yaml, bitnami/mariadb-galera/templates/_helpers.tpl, bitnami/mariadb-galera/templates/configmap.yaml, bitnami/mariadb-galera/templates/headless-svc.yaml, bitnami/mariadb-galera/templates/initialization-configmap.yaml, bitnami/mariadb-galera/templates/metrics-svc.yaml, bitnami/mariadb-galera/templates/pdb.yaml, bitnami/mariadb-galera/templates/role.yaml, bitnami/mariadb-galera/templates/rolebinding.yaml, bitnami/mariadb-galera/templates/secrets.yaml, bitnami/mariadb-galera/templates/serviceaccount.yaml, bitnami/mariadb-galera/templates/servicemonitor.yaml, bitnami/mariadb-galera/templates/statefulset.yaml, bitnami/mariadb-galera/templates/svc.yaml, bitnami/mariadb-galera/templates/test-runner.yaml, bitnami/mariadb-galera/values-production.yaml, bitnami/mariadb-galera/values.yaml
=> [bitnami/mariadb-galera] Lint chart

bitnami/memcached/Chart.yaml, bitnami/memcached/README.md, bitnami/memcached/ci/values-production.yaml, bitnami/memcached/templates/NOTES.txt, bitnami/memcached/templates/_helpers.tpl, bitnami/memcached/templates/deployment.yaml, bitnami/memcached/templates/secrets.yaml, bitnami/memcached/templates/servicemonitor.yaml, bitnami/memcached/templates/svc-metrics.yaml, bitnami/memcached/templates/svc.yaml, bitnami/memcached/values-production.yaml, bitnami/memcached/values.yaml
=> [bitnami/memcached] Lint chart

bitnami/metrics-server/Chart.yaml, bitnami/metrics-server/README.md, bitnami/metrics-server/ci/values-with-rbac.yaml, bitnami/metrics-server/templates/_helpers.tpl, bitnami/metrics-server/templates/auth-delegator-crb.yaml, bitnami/metrics-server/templates/cluster-role.yaml, bitnami/metrics-server/templates/deployment.yaml, bitnami/metrics-server/templates/metrics-api-service.yaml, bitnami/metrics-server/templates/metrics-server-crb.yaml, bitnami/metrics-server/templates/role-binding.yaml, bitnami/metrics-server/templates/serviceaccount.yaml, bitnami/metrics-server/templates/svc.yaml, bitnami/metrics-server/values.yaml
=> [bitnami/metrics-server] Lint chart

bitnami/minio/Chart.yaml, bitnami/minio/README.md, bitnami/minio/ci/values-production.yaml, bitnami/minio/templates/NOTES.txt, bitnami/minio/templates/_helpers.tpl, bitnami/minio/templates/deployment-standalone.yaml, bitnami/minio/templates/ingress.yaml, bitnami/minio/templates/networkpolicy.yaml, bitnami/minio/templates/pvc-standalone.yaml, bitnami/minio/templates/secrets.yaml, bitnami/minio/templates/service.yaml, bitnami/minio/templates/statefulset.yaml, bitnami/minio/templates/svc-headless.yaml, bitnami/minio/templates/tls-secrets.yaml, bitnami/minio/values-production.yaml, bitnami/minio/values.yaml
=> [bitnami/minio] Lint chart

bitnami/nginx/Chart.yaml, bitnami/nginx/README.md, bitnami/nginx/ci/values-with-ingress-metrics-and-serverblock.yaml, bitnami/nginx/templates/NOTES.txt, bitnami/nginx/templates/_helpers.tpl, bitnami/nginx/templates/deployment.yaml, bitnami/nginx/templates/ingress.yaml, bitnami/nginx/templates/server-block-configmap.yaml, bitnami/nginx/templates/servicemonitor.yaml, bitnami/nginx/templates/svc.yaml, bitnami/nginx/templates/tls-secrets.yaml, bitnami/nginx/values.yaml
Change chart YAML(s) to make it follow our styling standards
**Checklist**
=> [bitnami/nginx] Lint chart + standardization

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/README.md, bitnami/nginx-ingress-controller/ci/values-production.yaml, bitnami/nginx-ingress-controller/templates/_helpers.tpl, bitnami/nginx-ingress-controller/templates/addheaders-configmap.yaml, bitnami/nginx-ingress-controller/templates/clusterrole.yaml, bitnami/nginx-ingress-controller/templates/clusterrolebinding.yaml, bitnami/nginx-ingress-controller/templates/controller-configmap.yaml, bitnami/nginx-ingress-controller/templates/controller-daemonset.yaml, bitnami/nginx-ingress-controller/templates/controller-deployment.yaml, bitnami/nginx-ingress-controller/templates/controller-hpa.yaml, bitnami/nginx-ingress-controller/templates/controller-metrics-service.yaml, bitnami/nginx-ingress-controller/templates/controller-poddisruptionbudget.yaml, bitnami/nginx-ingress-controller/templates/controller-prometheusrules.yaml, bitnami/nginx-ingress-controller/templates/controller-service.yaml, bitnami/nginx-ingress-controller/templates/controller-servicemonitor.yaml, bitnami/nginx-ingress-controller/templates/default-backend-deployment.yaml, bitnami/nginx-ingress-controller/templates/default-backend-poddisruptionbudget.yaml, bitnami/nginx-ingress-controller/templates/default-backend-service.yaml, bitnami/nginx-ingress-controller/templates/podsecuritypolicy.yaml, bitnami/nginx-ingress-controller/templates/proxyheaders-configmap.yaml, bitnami/nginx-ingress-controller/templates/role.yaml, bitnami/nginx-ingress-controller/templates/rolebinding.yaml, bitnami/nginx-ingress-controller/templates/serviceaccount.yaml, bitnami/nginx-ingress-controller/templates/tcp-configmap.yaml, bitnami/nginx-ingress-controller/templates/udp-configmap.yaml, bitnami/nginx-ingress-controller/values-production.yaml, bitnami/nginx-ingress-controller/values.yaml
Change chart YAML(s) to make it follow our styling standards
**Checklist**
=> [bitnami/nginx-ingress-controller] Lint chart + standardisation

bitnami/metrics-server/Chart.yaml, bitnami/metrics-server/README.md, bitnami/metrics-server/templates/deployment.yaml, bitnami/metrics-server/values.yaml
Add an option to specify custom resources for the container.
- fixes #1659
**Checklist**
=> [bitnami/metrics-server] Add customizable resources

bitnami/pytorch/Chart.yaml, bitnami/pytorch/ci/values-production.yaml, bitnami/pytorch/templates/_helpers.tpl, bitnami/pytorch/templates/configmap.yaml, bitnami/pytorch/templates/deployment.yaml, bitnami/pytorch/templates/headless-svc.yaml, bitnami/pytorch/templates/pvc.yaml, bitnami/pytorch/templates/service.yaml, bitnami/pytorch/templates/statefulset.yml, bitnami/pytorch/values-production.yaml, bitnami/pytorch/values.yaml
Change chart YAML(s) to make it follow our styling standards
**Checklist**
=> [bitnami/pytorch] Lint chart + standardisation

bitnami/spark/Chart.yaml, bitnami/spark/README.md, bitnami/spark/ci/values-with-ingress-and-autoscaling.yaml, bitnami/spark/templates/_helpers.tpl, bitnami/spark/templates/headless-svc.yaml, bitnami/spark/templates/hpa-worker.yaml, bitnami/spark/templates/ingress.yaml, bitnami/spark/templates/secret.yaml, bitnami/spark/templates/statefulset-master.yaml, bitnami/spark/templates/statefulset-worker.yaml, bitnami/spark/templates/svc-master.yaml, bitnami/spark/values-production.yaml, bitnami/spark/values.yaml
Change chart YAML(s) to make it follow our styling standards
**Checklist**
=> [bitnami/spark] Lint chart + standardisation

githooks/functions/libchartversion.sh, githooks/functions/libhelmlint.sh, githooks/functions/libkubeval.sh, githooks/functions/libyamllint.sh, githooks/pre-push/chart-version, githooks/pre-push/helm-lint, githooks/pre-push/kubeval, githooks/pre-push/yaml-lint
- yamllint allows us to have a standard on how we format our yaml files
- kubeval allows us to validate the standard values.yaml. helm templates only checks if the rendering is possible but does not perform any validation of the values themselves against the API.
NOTE: DO NOT MERGE UNTIL ALL THE CHARTS HAVE BEEN LINTED FIRST
**Benefits**
- fixes #
**Checklist** 
=> Add hooks for use with yamllint and kubeval

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
Signed-off-by: Javier J. Salmeron Garcia <jsalmeron@vmware.com>
The data nodes were not getting the proper resource values. This PR fixes that.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/mongodb-sharded] Fix incorrect resource allocation in data nodes

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/statefulset.yaml
Fixes a typo in the bitnami/kafka statefulset template. `containinig` -> `containing`.
**Benefits**
There will be less typos.
N/A
N/A
**Checklist** 
=> [bitnami/kafka] Update typo in kafka statefulset

bitnami/prometheus-operator/Chart.yaml, bitnami/prometheus-operator/templates/alertmanager/alertmanager.yaml
=> [bitnami/prometheus-operator] fix indentation of alertmanager `securityContext`

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/statefulset-worker.yaml
- fixes #1686
**Benefits**
- fixes #1686
None
- fixes #1686
**Checklist**
=> [bitnami/airflow] fix resource template in `statefulset-worker.yaml`

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/statefulset-worker.yaml
Fix nindent to be 12 when extraEnvVars is set
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/airflow]Update statefulset-worker.yaml

bitnami/node-exporter/Chart.yaml, bitnami/node-exporter/templates/_helpers.tpl, bitnami/node-exporter/templates/service.yaml
=> [bitnami/node-exporter] minor updates

bitnami/kube-state-metrics/Chart.yaml, bitnami/kube-state-metrics/values.yaml
=> [bitnami/kube-state-metrics] remove whitespaces

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/influxdb/standalone-dpl.yaml, bitnami/influxdb/templates/relay/deployment.yaml
Configures the update strategy for Deployments
**Checklist**
=> [bitnami/influxdb] configure update strategy for deployments

bitnami/prometheus-operator/Chart.yaml, bitnami/prometheus-operator/requirements.lock
Update chart dependencies
Ref: #1765 
Ref: #1766 
**Benefits**
Chart uses latest versions of dependencies.
**Checklist** 
=> [bitnami/prometheus-operator]: Update chart dependencies

githooks/functions/libyamllint.sh
Modify `helm template` command in the yamllint lib in order to support helm version 3 flags.
**Benefits**
We will be able to execute `yamllint` hooks using helm version 3.
N/A
N/A
I have added `2> /dev/null` in order to mitigate the output related with https://github.com/helm/helm/issues/7295 
**Checklist** 
=> [bitnami/*] use the proper flags depending on helm version

bitnami/airflow/Chart.yaml, bitnami/airflow/README.md, bitnami/airflow/templates/deployment-web.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/airflow]Add airflow.webserverConfigMap to allow override FAB config.

bitnami/kibana/Chart.yaml, bitnami/kibana/README.md, bitnami/kibana/templates/deployment.yaml, bitnami/kibana/templates/tests/test-connection.yaml, bitnami/kibana/values-production.yaml, bitnami/kibana/values.yaml
- Lint files
- Fix the indentation in the sidecars and initContainers
- Document how to add a sample ES container for testing purpose
**Checklist**
=> [bitnami/kibana] Lint, fix sidecar indentation and document ES sample container

bitnami/grafana/Chart.yaml, bitnami/grafana/README.md, bitnami/grafana/templates/_helpers.tpl, bitnami/grafana/templates/deployment.yaml, bitnami/grafana/values-production.yaml, bitnami/grafana/values.yaml
**Benefits**
- fixes https://github.com/bitnami/charts/issues/1783
**Checklist** 
=> [bitnami/grafana] Allow ini files to be passed as secrets

bitnami/kafka/Chart.yaml, bitnami/kafka/requirements.lock, bitnami/kafka/requirements.yaml
Update the dependency version (Zookeeper)
**Benefits**
Get the latest from dependencies
None
- resolves #1796
- resolves #1793
**Checklist** 
=> [bitnami/kafka] Fix dependency

bitnami/fluentd/Chart.yaml, bitnami/fluentd/values-production.yaml, bitnami/fluentd/values.yaml
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
Upgrade fluentd image
**Benefits**
latest patched image
N/A
N/A
**Checklist** 
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/bitnami/charts/1822)
=> [bitnami/fluentd] upgrade image

bitnami/minio/Chart.yaml
New major release
**Checklist**
=> [bitnami/minio] release 3.0.0

bitnami/prometheus-operator/Chart.yaml, bitnami/prometheus-operator/requirements.lock
=> [bitnami/prometheus-operator] update chart depencency versions

bitnami/kafka/Chart.yaml, bitnami/kafka/requirements.lock
bumping zookeeper dependency version
**Benefits**
Getting kafka dependency up to date
None
- fixes #
**Checklist** 
=> [bitnami/kafka] bumping zookeeper dependency version

bitnami/thanos/requirements.lock
=> Fix Thanos 'requirements.lock'

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/requirements.lock, bitnami/prometheus-operator/Chart.yaml, bitnami/prometheus-operator/requirements.lock, bitnami/thanos/requirements.lock
Fix **requirements.lock** on ES and Prometheus Operator
=> Fix Requirements

README.md
Update commands to Helm 3 (internal task created to update the GIF)
=> Convert README into Helm 3 friendly

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/README.md
=> [bitnami/elasticsearch] Fix typo in README.md

bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/aggregator-svc.yaml
Only create the Aggregator Service if enabled.
**Benefits**
Aggregator Service will only be created if the Aggregator is enabled.
**Checklist**
=> [bitnami/fluentd] don't create aggregator svc if not enabled

bitnami/kafka/Chart.yaml, bitnami/kafka/requirements.lock, bitnami/node/Chart.yaml, bitnami/node/requirements.lock, bitnami/thanos/Chart.yaml, bitnami/thanos/requirements.lock
Fixes the **requirements.lock** that are not synced with **requirements.yaml**
=> [bitnami/*] Fix requirements.lock

bitnami/harbor/Chart.yaml, bitnami/harbor/README.md, bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/README.md
Remove invalid `debian-9` references
=> [bitnami/harbor&postgresql-ha] Remove debian 9 references

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/deployment-scheduler.yaml, bitnami/airflow/templates/deployment-web.yaml
Fix an issue when node selector, toleration or affinity is enabled
**Benefits**
Fix.
None.
- fixes #
**Checklist** 
=> 🐛 [bitnami/airflow] - fixing node selector, toleration and affinity

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/NOTES.txt
Use service.port instead of service.nodePort from values.
**Benefits**
LB service type command from NOTES.txt is working.
None 
None 
- fixes #
**Checklist** 
=> [bitnami/mongodb-sharded] Fix port for service type LoadBalancer in NOTES.txt

bitnami/airflow/Chart.yaml, bitnami/airflow/requirements.lock, bitnami/airflow/requirements.yaml, bitnami/airflow/values-production.yaml, bitnami/airflow/values.yaml, bitnami/harbor/Chart.yaml, bitnami/harbor/requirements.lock, bitnami/harbor/values-production.yaml, bitnami/harbor/values.yaml
Update dependencies on Harbor and Airflow charts
**Checklist**
=> [bitnami/{airflow|harbor}] Update dependencies

bitnami/node/Chart.yaml, bitnami/node/requirements.lock, bitnami/node/requirements.yaml
Signed-off-by: Carlos Rodriguez Hernandez <crhernandez@bitnami.com>
Update repo
**Checklist**
=> [bitnami/node] Get mongodb dep from Bitnami repo

bitnami/magento/Chart.yaml, bitnami/magento/requirements.lock, bitnami/magento/requirements.yaml
Signed-off-by: Carlos Rodriguez Hernandez <crhernandez@bitnami.com>
Update ES as a dependency and change repository for mariadb
**Checklist**
=> [bitnami/magento] Update ES dependency in a major

bitnami/grafana/Chart.yaml, bitnami/grafana/values-production.yaml, bitnami/grafana/values.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/grafana] Fix typo in values.yaml

bitnami/fluentd/Chart.yaml, bitnami/fluentd/README.md, bitnami/mariadb-galera/Chart.yaml, bitnami/mariadb-galera/README.md, bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/README.md
Signed-off-by: Carlos Rodriguez Hernandez <crhernandez@bitnami.com>
Add a note in the README of those charts that needs to run containers as root.
=> [bitnami/several] Add note about necessary (by the moment) root containers

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/compactor/pvc.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/thanos] Fix pvc creation on compactor.enabled = false

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/ci/affinity-toleration-values.yaml, bitnami/rabbitmq/ci/default-values.yaml, bitnami/rabbitmq/ci/networkpolicy-values.yaml, bitnami/redis/Chart.yaml, bitnami/redis/ci/default-values.yaml, bitnami/redis/ci/dev-values.yaml, bitnami/redis/ci/extra-flags-values.yaml, bitnami/redis/ci/insecure-sentinel-values.yaml, bitnami/redis/ci/production-sentinel-values.yaml, bitnami/redis/ci/production-values.yaml, bitnami/redis/ci/redis-lib-values.yaml, bitnami/redis/ci/redisgraph-module-values.yaml
Revert part of the changes in https://github.com/bitnami/charts/pull/2017
=> [bitnami/redis & rabbit] Revert CI removal

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/values.yaml
Following my issue #2023 and the suggestions of @rafariossaa I updated the documentation to specify exactly the format necessary for those options to work.
=> [bitnami/rabbitmq] added instructions to use extra ports - closes #2023 

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kafka/requirements.lock, bitnami/kafka/values-production.yaml, bitnami/kafka/values.yaml
We need to update the major version as the last PR merged breaks the upgrade.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/kafka] Update major version

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/deployment-standalone.yaml, bitnami/mongodb/templates/statefulset-arbiter-rs.yaml, bitnami/mongodb/templates/svc-standalone.yaml, bitnami/mongodb/values-production.yaml, bitnami/mongodb/values.yaml
**Benefits**
- fixes #2073
**Checklist** 
=> [bitnami/mongodb] Fix svc name in arbitrer

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/templates/controller-service.yaml
Fix scoping variables in node port tcp and udp in controller-service.yaml 
**Benefits**
Template compile when using tcp and/or udp port 
None
None
**Checklist** 
=> [bitnami/nginx-ingress-controller] Fix variable scope in tcp and/or udp

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/serviceaccount.yaml
Adds the rabbitmq secret to it's service account.
**Benefits**
Allows to use this chart in a cluster where strict secret linking is require (see #1982 ).
**Checklist**
=> [bitnami/rabbitmq] Link secret in rabbitmq chart

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kafka/values-production.yaml, bitnami/kafka/values.yaml
This PR updates the README.md
**Checklist**
=> [bitnami/kafka] Update README.md

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/deployment-standalone.yaml, bitnami/mongodb/values-production.yaml, bitnami/mongodb/values.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/mongodb] Fix indentation error

bitnami/external-dns/Chart.yaml, bitnami/external-dns/templates/deployment.yaml, bitnami/external-dns/values-production.yaml, bitnami/external-dns/values.yaml
Signed-off-by: cw-sakamoto <sakamoto@chatwork.com>
- revert this 3d396f5d13a0b489078341325be30f9f8df97928
**Checklist** 
=> [bitnami/external-dns] Remove unnecessary lines

bitnami/external-dns/Chart.yaml, bitnami/external-dns/README.md, bitnami/external-dns/templates/clusterrole.yaml, bitnami/external-dns/templates/clusterrolebinding.yaml, bitnami/external-dns/templates/deployment.yaml, bitnami/external-dns/templates/service.yaml, bitnami/external-dns/templates/serviceaccount.yaml, bitnami/external-dns/values-production.yaml, bitnami/external-dns/values.yaml
This PR fixes an issue where the serviceAccount is not created when using a custom SA. It also fixes several issues related to `yamllint`.
None
- fixes https://github.com/bitnami/charts/issues/2147
**Checklist**version bumped in `Chart.yaml` according to [semver](http://semver.org/).
=> [bitnami/external-dns] Fix issue on SA

bitnami/grafana/Chart.yaml, bitnami/grafana/README.md, bitnami/grafana/templates/_helpers.tpl, bitnami/grafana/templates/deployment.yaml, bitnami/grafana/templates/serviceaccount.yml, bitnami/grafana/values-production.yaml, bitnami/grafana/values.yaml
Adds the `serviceAccount.name` and `serviceAccount.create` config options to the grafana chart.
**Benefits**
Allows to use the grafana chart in clusters enforcing secret linking. (See #1982 )
**Checklist**
=> [biitnami/grafana] Add serviceAccount.create and serviceAccount.name to grafana chart

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/secrets.yaml, bitnami/rabbitmq/values-production.yaml, bitnami/rabbitmq/values.yaml
Signed-off-by: André Bauer <monotek23@gmail.com>
fixes missing $ in .Release.Namespace of secrets.yaml
**Benefits**
fixes failing helm upgrade:
```
UPGRADE FAILED
Error: render error in "rabbitmq/templates/statefulset.yaml": template: rabbitmq/templates/statefulset.yaml:35:28: executing "rabbitmq/templates/statefulset.yaml" at <include (print $.Template.BasePath "/secrets.yaml") .>: error calling include: template: rabbitmq/templates/secrets.yaml:31:24: executing "rabbitmq/templates/secrets.yaml" at <.Release.Namespace>: nil pointer evaluating interface {}.Namespace
Error: UPGRADE FAILED: render error in "rabbitmq/templates/statefulset.yaml": template: rabbitmq/templates/statefulset.yaml:35:28: executing "rabbitmq/templates/statefulset.yaml" at <include …
```
=> [rabbitmq] fix missing $ in .Release.Namespace

bitnami/phpmyadmin/Chart.yaml, bitnami/phpmyadmin/requirements.lock, bitnami/phpmyadmin/requirements.yaml, bitnami/phpmyadmin/values.yaml
Changes to use the latest version of MariaDB in the phpMyAdmin chart
=> Update the phpMyAdmin requirements with the latest MariaDB

bitnami/external-dns/Chart.yaml, bitnami/external-dns/README.md, bitnami/external-dns/values-production.yaml, bitnami/external-dns/values.yaml
Minor fix of markdown formatting in the external-dns chart README.md
**Benefits**
- fixes #
**Checklist** 
=>  [bitnami/external-dns] Fix markdown errors in README.md

bitnami/odoo/Chart.yaml, bitnami/odoo/requirements.lock, bitnami/odoo/values.yaml
This PR should be included in the pipeline to update the tags before merging it, but I need to create it in order to bump the chart version in a major.
=> [bitnami/odoo] Move appVersion from 12 to 13

bitnami/external-dns/README.md
Fix typo.
**Benefits**
Good document.
Nothing.
Nothing.
Nothing.
**Checklist**
=> [bitnami/external-dns] Fix typo

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/influxdb/deployment-standalone.yaml, bitnami/influxdb/values-production.yaml, bitnami/influxdb/values.yaml
The init-container create a {data,meta,wal} directory is created instead of three directories when the variable "volumePermissions.enabled" set to true
**Benefits**
- fixes #2150
**Checklist** 
=> Indluxdb init container

bitnami/thanos/Chart.yaml, bitnami/thanos/README.md, bitnami/thanos/values-production.yaml, bitnami/thanos/values.yaml
I added to `values.yaml` missing annotations as stated in
[this issue](https://github.com/bitnami/charts/issues/2249)
=> [bitnami/thanos] Add missing podAnnotations

bitnami/common/Chart.yaml, bitnami/common/values.yaml
Add `values.yaml` since it is required by CI/CD tools and processes.
**Benefits**
We can run CI/CD.
N/A
N/A
N/A
**Checklist**
=> [bitnami/common] bitnami common add values yaml

bitnami/wordpress/Chart.yaml, bitnami/wordpress/templates/deployment.yaml, bitnami/wordpress/values-production.yaml, bitnami/wordpress/values.yaml
Add `-` to the command in metrics
**Benefits**
- fixes #2274
**Checklist** 
=> [bitnami/wordpress] Change in the command of apache-exporter

bitnami/apache/Chart.yaml, bitnami/apache/templates/deployment.yaml, bitnami/apache/values.yaml
Add - to the command the apache_exporter in metrics
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/apache] Change in the command of apache-exporter 

bitnami/dokuwiki/Chart.yaml, bitnami/dokuwiki/templates/deployment.yaml, bitnami/dokuwiki/values.yaml
Add - to the command the apache_exporter in metrics
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/dokuwiki] Change in the command of apache-exporter

bitnami/joomla/Chart.yaml, bitnami/joomla/requirements.lock, bitnami/joomla/templates/deployment.yaml, bitnami/joomla/values.yaml
Add `-` to the command the apache_exporter in metrics
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/joomla] Change in the command of apache-exporter

bitnami/drupal/Chart.yaml, bitnami/drupal/templates/deployment.yaml, bitnami/drupal/values.yaml
Add `-` to the command the apache_exporter in metrics
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/drupal] Change in the command of apache-exporter

bitnami/magento/Chart.yaml, bitnami/magento/requirements.lock, bitnami/magento/templates/deployment.yaml, bitnami/magento/values-production.yaml, bitnami/magento/values.yaml
Add `-` to the command the apache_exporter in metrics
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/magento] Change in the command of apache-exporter

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/redis-statefulset.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/redis-cluster] Fix indentation in storageClass

bitnami/grafana/Chart.yaml, bitnami/grafana/README.md, bitnami/grafana/templates/service.yaml, bitnami/grafana/values-production.yaml, bitnami/grafana/values.yaml
Add loadBalancerSourceRanges to grafana service.
**Benefits**
Increased security by allowing a whitelist of IP ranges.
N/A
N/A
N/A
**Checklist** 
=> [bitnami/grafana] Add loadBalancerSourceRanges to grafana service.

bitnami/memcached/Chart.yaml, bitnami/memcached/values-production.yaml, bitnami/memcached/values.yaml, bitnami/thanos/Chart.yaml, bitnami/thanos/values-production.yaml, bitnami/thanos/values.yaml
**Benefits**
This PR is necessary to fix an issue with the internal CI/CD.
- fixes #
**Checklist** 
=> [bitnami/thanos bitnami/memcached] Add global storageClass

bitnami/kong/Chart.yaml, bitnami/kong/README.md, bitnami/kong/requirements.lock, bitnami/kong/templates/_helpers.tpl, bitnami/kong/templates/migrate-job.yaml, bitnami/kong/values-production.yaml, bitnami/kong/values.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/kong] Make override migration image as optional

bitnami/kafka/Chart.yaml, bitnami/kafka/values-production.yaml, bitnami/kafka/values.yaml, bitnami/nginx/Chart.yaml, bitnami/nginx/values.yaml
Update tags of some images
**Checklist**
=> [bitnami/kafka & nginx] Manually update git and kubectl tags

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/NOTES.txt, bitnami/redis-cluster/values-production.yaml, bitnami/redis-cluster/values.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/redis-cluster] Fix typo in NOTES

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/metrics-prometheus.yaml, bitnami/redis-cluster/values-production.yaml, bitnami/redis-cluster/values.yaml
There is an indentation issue in the Prometheus ServiceMonitor template file. This PR fixes that.
**Benefits**
- fixes #2425
**Checklist** 
=> [bitnami/redis-cluster] Intentation fix for ServiceMonitor label selector

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/prometheusrule.yaml, bitnami/redis-cluster/values-production.yaml, bitnami/redis-cluster/values.yaml
Labels added to values.yml for PrometheusRule CRDs are not properly included, and there is a newline that is missing. This PR fixes that issue.
**Benefits**
- fixes #2426
**Checklist** 
=> [bitnami/redis-cluster] Fix PrometheusRule indentation

README.md
The documentation has been moved to another repository https://github.com/helm/helm-www (e.g. https://github.com/helm/helm-www/tree/master/content/en/docs) but I guess the better documentation is on the official documentation page without markdown meta informations.
The documentation of Helm has been moved to another repository.
**Benefits**
It works 🤪
❌
❌
- fixes #
New docs repository here: https://github.com/helm/helm-www
I guess it's better to navigate to the official documentation page instead of markdown because of md meta information formatting.
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps …
=> docs: update links to Helm quickstart & using helm

bitnami/kibana/Chart.yaml, bitnami/kibana/templates/deployment.yaml, bitnami/kibana/values-production.yaml, bitnami/kibana/values.yaml
Fix `extraVolumes` and `extraVolumeMounts` indentation.
Previously the following error appears when setting the above parameters
```
Error: YAML parse error on kibana/templates/deployment.yaml: error converting YAML to JSON: yaml: line 71: did not find expected key
```
in the same way, I was able to find the error by running `helm template ... --debug`
```yaml
volumeMounts:
- name: kibana-data
mountPath: /bitnami/kibana
- name: kibana-config
mountPath: /bitnami/kibana/conf
- name: plugins-init-scripts
mountPath: /docker-entrypoint-initdb.d/plugin-install
- mountPath: /usr/share/kibana/plugins/logtrail/logtrail.json
name: logtrailconfig
subPath: logtrail.json
volumes:
- name: kibana-data
persistentVolumeClaim:
claimName: kibana-svc
- name: kibana-config …
```
=> [bitnami/kibana] Fix extraVolumes

bitnami/kong/Chart.yaml, bitnami/kong/README.md, bitnami/kong/requirements.lock, bitnami/kong/templates/extra-list.yaml, bitnami/kong/values-production.yaml, bitnami/kong/values.yaml
Cover the case where the user may want to deploy KongPlugins, KongConsumers... or basically any other thing.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/kong] Allow deploying extra objects

bitnami/metallb/Chart.yaml, bitnami/metallb/templates/daemonset.yaml, bitnami/metallb/templates/deployment.yaml, bitnami/metallb/values.yaml
This change is necessary for our internal CI/CD
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/metallb] Change container names

bitnami/mariadb-galera/Chart.yaml, bitnami/mariadb-galera/templates/_helpers.tpl, bitnami/mariadb-galera/values-production.yaml, bitnami/mariadb-galera/values.yaml
The statefulset mounts the tls secret under `/bitnami/mariadb/certs/`
**Benefits**
Fix mariadb-galera TLS mount
none
none
none
**Checklist** 
=> [bitnami/chart] fix(mariadb-galera/tls): match sts and template cert path

bitnami/common/Chart.yaml
Align version and appVersion for `bitnami/common` chart since  this chart has not app to be deployed but has only `_helpers` and `templates`.
**Benefits**
CI/CD can understand it better.
N/A
N/A
N/A
**Checklist**
=> [bitnami/common] bump version number

bitnami/external-dns/Chart.yaml, bitnami/external-dns/templates/deployment.yaml, bitnami/external-dns/values-production.yaml, bitnami/external-dns/values.yaml
Fix issue with https://github.com/bitnami/charts/pull/2572
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/external-dns] Fix Email for Cloudflare

bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md, bitnami/wordpress/values-production.yaml, bitnami/wordpress/values.schema.json, bitnami/wordpress/values.yaml
The TLS parameter was missing from the values.yaml but it's actually used in the Ingress template.
**Checklist** 
=> [bitnami/wordpress] Add TLS parameter to values.yaml and schema

bitnami/cassandra/Chart.yaml, bitnami/cassandra/templates/headless-svc.yaml, bitnami/cassandra/values-production.yaml, bitnami/cassandra/values.yaml
This change add service annotation to cassandra headless service.  For cassandra service this annotation is already present.  
**Benefits**
Main benefit of this change is to have service annotation e.g for another services like external-dns
[external-dns](https://github.com/kubernetes-sigs/external-dns/blob/master/docs/tutorials/hostport.md)
fixes #2632 
**Checklist**
=> [bitnami/cassandra] add headless-svc annotation

bitnami/metallb/Chart.yaml, bitnami/metallb/values.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/metallb] Use a proper jobLabel for the serviceMonitor.

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/README.md, bitnami/redis-cluster/templates/redis-statefulset.yaml, bitnami/redis-cluster/values-production.yaml, bitnami/redis-cluster/values.yaml
The `.extraInitContainers` option does not work properly for some users, and the documentation about it is wrong.
**Benefits**
- fixes #2503
**Checklist** 
=> [bitnami/redis-cluster] Fix extraInitContainers option

bitnami/common/Chart.yaml, bitnami/common/values.yaml, bitnami/elasticsearch/values-production.yaml, bitnami/elasticsearch/values.yaml, bitnami/fluentd/values-production.yaml, bitnami/fluentd/values.yaml, bitnami/harbor/values.yaml, bitnami/influxdb/values-production.yaml, bitnami/influxdb/values.yaml, bitnami/logstash/values-production.yaml, bitnami/logstash/values.yaml, bitnami/metallb/values.yaml, bitnami/minio/values-production.yaml, bitnami/minio/values.yaml, bitnami/spark/values-production.yaml, bitnami/spark/values.yaml, bitnami/testlink/values.yaml, bitnami/zookeeper/values-production.yaml, bitnami/zookeeper/values.yaml
Remove trailing spaces and some minor improvements to make `helm lint` work:
```console
$ ct lint --all
✔︎ airflow => (version: "6.3.2", path: "bitnami/airflow")
✔︎ apache => (version: "7.3.16", path: "bitnami/apache")
✔︎ cassandra => (version: "5.4.2", path: "bitnami/cassandra")
✔︎ common => (version: "0.2.3", path: "bitnami/common") > Error waiting for process: exit status 1
✔︎ consul => (version: "7.0.15", path: "bitnami/consul")
✔︎ dokuwiki => (version: "6.0.17", path: "bitnami/dokuwiki")
✔︎ drupal => (version: "6.2.21", path: "bitnami/drupal")
✔︎ elasticsearch => (version: "12.3.1", path: "bitnami/elasticsearch")
✔︎ etcd => (version: "4.8.2", path: "bitnami/etcd")
✔︎ external-dns => (version: "3.1.0", path: "bitnami/external-dns")
✔︎ fluentd => (version: "1.2.0", path: …
```
=> [bitnami/several] Fix trailing spaces to make helm lint work on all of them

bitnami/common/Chart.yaml
=> [bitnami/common] Bump chart version

README.md
Update k8s cluster get started guides
=> Update k8s cluster get started guides

bitnami/common/Chart.yaml, bitnami/common/README.md, bitnami/common/templates/_capabilities.tpl
Signed-off-by: Marco Kilchhofer <marco.kilchhofer@bedag.ch>
Implement the template function for ingress apiVersion used in [wordpress](https://github.com/bitnami/charts/blob/11da0731a1816b798142e2589963ee350f5aa744/bitnami/wordpress/templates/_helpers.tpl#L183) in the common chart as other charts have the same need (eg. phpmyadmin).
**Benefits**
centralize code
--
--
See also PR of phpmyadmin: https://github.com/bitnami/charts/pull/2694
**Checklist** 
=> [bitnami/common]: add template function for ingress apiVersion

bitnami/grafana/Chart.yaml, bitnami/grafana/values-production.yaml, bitnami/grafana/values.yaml
Bump major version required due to new major version in the app
=> [bitnami/grafana] Bump major version required due to new major version in the app

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/README.md, bitnami/redis-cluster/templates/poddisruptionbudget.yaml, bitnami/redis-cluster/values-production.yaml, bitnami/redis-cluster/values.yaml
- Adds PodDisruptionBudget discussed #2741
**Benefits**
**Checklist** 
=> [bitnami/redis-cluster] Add PodDisruptionBudget

bitnami/harbor/Chart.yaml, bitnami/harbor/README.md, bitnami/harbor/requirements.lock, bitnami/harbor/templates/clair/clair-dpl.yaml, bitnami/harbor/templates/trivy/trivy-sts.yaml, bitnami/harbor/values-production.yaml, bitnami/harbor/values.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/harbor] Add missing imagePullSecrets

bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/forwarder-daemonset.yaml, bitnami/fluentd/values-production.yaml, bitnami/fluentd/values.yaml
Signed-off-by: Ivan Rizzante <ivan.rizzante@tech.sdb.it>
Fix a typo error in [forwarder daemonset](https://github.com/bitnami/charts/blob/6f290fea818adeeb6e6a8e64d03957608f5db2af/bitnami/fluentd/templates/forwarder-daemonset.yaml#L50)
**Benefits**
The typo will be fixed
- fixes #
**Checklist** 
=> [bitnami/fluentd] Fluentd daemon group var is incorrect

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kafka/values-production.yaml, bitnami/kafka/values.yaml
- fixed typo in "Upgrading" section of the readme
- fixed formatting in "Upgrading" section of the readme
**Checklist** 
=> [bitnami/kafka] docs: "Upgrading" typo & formatting

.github/ct-install.yaml
Skipping this verification as discourse does not seem to be passing the tests although
deploying (installation stage is presumably taking too much time)
Signed-off-by: joancafom <jcarmona@bitnami.com>
Skipping test stage on upcoming Discourse chart.
**Benefits**
Functional modifications will not generate a counterfeit output due to timeout on installations.
Easy-to-detect errors might not be recognized at first sight
- NA
**Checklist** 
=> [bitnami] Remove discourse from CT install tests

bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md, bitnami/wordpress/values-production.yaml, bitnami/wordpress/values.yaml
Taking care of the abandoned PR: https://github.com/bitnami/charts/pull/2459
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/wordpress] Fix docs to run as root

bitnami/spark/Chart.yaml, bitnami/spark/templates/NOTES.txt, bitnami/spark/values-production.yaml, bitnami/spark/values.yaml
Improve NOTES.txt to use the proper jar example
```console
$ helm install spark
...
2. Submit an application to the cluster:
To submit an application to the cluster the spark-submit script must be used. That script can be
obtained at https://github.com/apache/spark/tree/master/bin. Also you can use kubectl run.
export EXAMPLE_JAR=$(kubectl exec -ti --namespace default spark-worker-0 -- find examples/jars/ -name 'spark-example*\.jar' | tr -d '\r')
kubectl exec -ti --namespace default spark-worker-0 -- spark-submit --master spark://spark-master-svc:7077 \
--class org.apache.spark.examples.SparkPi \
$EXAMPLE_JAR 5
$ helm install spark2 . --set service.type=LoadBalancer
...
2. Submit an application to the cluster:
To submit an application to the cluster the …
```
=> [bitnami/spark] Improve NOTES.txt to use the proper jar example

bitnami/apache/values.schema.json, bitnami/drupal/values.schema.json, bitnami/ghost/values.schema.json, bitnami/jenkins/values.schema.json, bitnami/joomla/values.schema.json, bitnami/mariadb-galera/values.schema.json, bitnami/mariadb/values.schema.json, bitnami/mongodb/values.schema.json, bitnami/nginx/values.schema.json, bitnami/postgresql/values.schema.json, bitnami/rabbitmq/values.schema.json, bitnami/redis/values.schema.json, bitnami/redmine/values.schema.json, bitnami/wordpress/values.schema.json
With the latest update of Kubeapps, the format to hide elements in the form has changed:
- When `hidden` is an object, the keys are now `value` and `path`.
- All the paths are JSON paths, which means that instead of using `.` it should use `/`. For example: `mariadb.enabled` -> `mariadb/enabled`.
This PR updates all the existing JSON schemas to use the new format.
**Checklist** 
~~- [ ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).~~
~~- [ ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)~~
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized …
=> [multiple charts] Update hidden properties in the different JSON schemas

bitnami/prometheus-operator/Chart.yaml, bitnami/prometheus-operator/templates/alertmanager/alertmanager.yaml, bitnami/prometheus-operator/templates/prometheus/prometheus.yaml, bitnami/prometheus-operator/values-production.yaml, bitnami/prometheus-operator/values.yaml
This PR fixes the pod affinity for Prometheus and Alertmanager pods. The labels were not properly set when using affinity.
**Benefits**
- fixes #2784
**Checklist** 
=> [bitnami/prometheus-operator] Fix pod affinity

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/_helpers.tpl
When adding trivy to the no proxy list, it was causing issues. This PR fixes it.
=> [bitnami/harbor] Add trivy to no proxy list

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/README.md, bitnami/redis-cluster/requirements.lock, bitnami/redis-cluster/requirements.yaml, bitnami/redis-cluster/templates/NOTES.txt, bitnami/redis-cluster/templates/_helpers.tpl, bitnami/redis-cluster/templates/configmap.yaml, bitnami/redis-cluster/templates/extra-list.yaml, bitnami/redis-cluster/templates/headless-svc.yaml, bitnami/redis-cluster/templates/init-cluster.yaml, bitnami/redis-cluster/templates/metrics-prometheus.yaml, bitnami/redis-cluster/templates/metrics-svc.yaml, bitnami/redis-cluster/templates/networkpolicy.yaml, bitnami/redis-cluster/templates/poddisruptionbudget.yaml, bitnami/redis-cluster/templates/prometheusrule.yaml, bitnami/redis-cluster/templates/psp.yaml, bitnami/redis-cluster/templates/redis-role.yaml, bitnami/redis-cluster/templates/redis-rolebinding.yaml, bitnami/redis-cluster/templates/redis-serviceaccount.yaml, bitnami/redis-cluster/templates/redis-statefulset.yaml, bitnami/redis-cluster/templates/redis-svc.yaml, bitnami/redis-cluster/templates/scripts-configmap.yaml, bitnami/redis-cluster/templates/secret.yaml, bitnami/redis-cluster/templates/svc-cluster-external-access.yaml, bitnami/redis-cluster/templates/update-cluster.yaml, bitnami/redis-cluster/values-production.yaml, bitnami/redis-cluster/values.yaml
This PR adds several Bitnami charts good practices and standards. Most of them are about customization:
- Custom Liveness/Rediness probes
- Lifecycle hooks
- Add more customization to jobs (such as adding annotations, env vars, commands, initContainers)
- Extra deploy array
- Use the bitnami/common chart
**Benefits**
More standard and more flexible
Even though the upgrade was tested, we may find some corner cases.
- fixes https://github.com/bitnami/charts/issues/2890
**Checklist** 
=> [bitnami/redis-cluster] Refactor to add bitnami chart standard features

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/init-cluster.yaml, bitnami/redis-cluster/templates/update-cluster.yaml, bitnami/redis-cluster/values.yaml
Fix regression for not setting the security context to enabled
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/redis-cluster] Return enabled to podSecurityContext and containerSecurityContext

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/bucketweb/deployment.yaml
The command for the bucketweb changed, this PR fixes it
**Benefits**
- fixes #2922
**Checklist** 
=> [bitnami/thanos] Fix bucket command

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/replicaset/statefulset.yaml
Remove the use of `toYaml` for the metrics container `securityContext`.
This avoids rendering `enabled: true` to the output, which is not invalid:
```
error validating data: ValidationError(StatefulSet.spec.template.spec.containers[1].securityContext): unknown field “enabled” in io.k8s.api.core.v1.SecurityContext
```
**Benefits**
Fixes validation error
N\A
- fixes #
**Checklist** 
=> [bitnami/mongodb] fix up StatefulSet metrics securityContext

bitnami/redis/Chart.yaml, bitnami/redis/values-production.yaml, bitnami/redis/values.yaml
**Benefits**
Improved reading of the comments in the example values file
None
N/A
- fixes #
N/A
**Checklist** 
=> [bitnami/redis] fix copy/paste error in comment

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/README.md
- Fixes #2985
- Related: https://github.com/bitnami/bitnami-docker-rabbitmq/issues/126
**Checklist**
=> [bitnami/rabbitmq] Update plugins section in the README

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/deployment-scheduler.yaml
**Benefits**
- fixes wrong indentation of airflow.scheduler.extraVolumes
**Checklist** 
=> [bitnami/airflow] Fix wrong indentation of airflow.scheduler.extraVolumes

bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/templates/server/configmap.yaml
Remove triling spaces in the server/configmap.yml
**Benefits**
https://github.com/bitnami/charts/pull/2945
**Checklist** 
=> [bitnami/spring-cloud-dataflow] Remove trailing spaces

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml, bitnami/mongodb-sharded/templates/replicaset-entrypoint-configmap.yaml, bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml, bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
A small PR to fix mogodb-sharded chart, expected env VARS are not found because everything is pushed with PPRIMARY... instead of PRIMARY.
THX
=> fix PPRIMARY in ENV VARS

bitnami/contour/Chart.yaml, bitnami/metallb/Chart.yaml
The used icons were incorrect, this PR fixes that. Bump the chart to force a release.
https://github.com/bitnami/charts/issues/3032
**Checklist** 
=> [bitnami/contour, metallb] Fix incorrect icons

bitnami/contour/Chart.yaml, bitnami/metallb/Chart.yaml
=> [bitnami/metallb][bitnami/contour] Revert appVersion change

bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/values-production.yaml, bitnami/spring-cloud-dataflow/values.yaml
- fix the URL of the chart icon
- fix some yaml linter errors
**Benefits**
We can reach out the icon for this chart
N/A
N/A
N/A
**Checklist**
=> [bitnami/spring-cloud-dataflow] fix dataflow icon URL

.github/actions/category-checker/Dockerfile, .github/actions/category-checker/action.yaml, .github/actions/category-checker/category-checker.sh, .github/actions/category-checker/ct-check-category.yaml, .github/workflows/lint-test.yaml
This PR adds a GitHub action to test that the Helm Charts contains a valid category.
This PR completes https://github.com/bitnami/charts/pull/3075 but it is created separately to make the testing easier.
=> Add action to test charts categories

bitnami/logstash/Chart.yaml, bitnami/logstash/templates/ingress.yaml, bitnami/logstash/values-production.yaml
Updates Logstash ingress for Kubernetes 1.14+
Checks Kubernetes version and chooses between "extensions/v1beta1" and "networking.k8s.io/v1beta1"
None known.
apiVersion is limited to two versions.
- fixes #
**Checklist** 
=> [bitnami/logstash] Update logstash ingress for newer K8S versions

bitnami/phpmyadmin/Chart.yaml, bitnami/phpmyadmin/README.md, bitnami/phpmyadmin/requirements.lock, bitnami/phpmyadmin/templates/deployment.yaml, bitnami/phpmyadmin/values.yaml
Add the possibility to provide with extra environment variables.
**Benefits**
The end user can include as many env vars as needed, both declaring them explicitly in the `values.yaml` or indicating a ConfigMap from where to be loaded.
NA
- fixes #3078
**Checklist** 
=> [bitnami/phpmyadmin]Add extra environment variables

bitnami/drupal/Chart.yaml, bitnami/drupal/templates/_helpers.tpl, bitnami/drupal/templates/deployment.yaml, bitnami/drupal/templates/extra-list.yaml
Signed-off-by: Andrés Bono <andresbono@vmware.com>
**Checklist**
=> [bitnami/drupal] Fix matchLabels and extraDeploy

bitnami/ejbca/Chart.yaml, bitnami/ejbca/README.md, bitnami/ejbca/templates/deployment.yaml, bitnami/ejbca/values.yaml
Signed-off-by: joancafom <jcarmona@bitnami.com>
Allow end user to specify what ports the container will be using to listen to incoming connections.
**Benefits**
More control on what ports the pod is listening to.
- None
NA
**Checklist** 
=> [bitnami/ejbca] Customize EJBCA container port

bitnami/fluentd/Chart.yaml, bitnami/fluentd/README.md
Correct typo in Readme
**Benefits**
More accurate Readme
None
None
None
**Checklist** 
=> [bitnami/fluentd] fix typo in Readme

bitnami/kibana/Chart.yaml
=> [bitnami/kibana] Fix typo in categories

bitnami/mysql/Chart.yaml
=> [bitnami/mysql] Add missing category

bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md, bitnami/spring-cloud-dataflow/templates/_helpers.tpl, bitnami/spring-cloud-dataflow/templates/server/configmap.yaml, bitnami/spring-cloud-dataflow/templates/skipper/configmap.yaml, bitnami/spring-cloud-dataflow/values-production.yaml, bitnami/spring-cloud-dataflow/values.yaml
Added ability to configure volume mounts, volumes, and environment variables.
**Checklist**
=> [bitnami/spring-cloud-dataflow] Added ability to configure volumeMounts, volumes and environmentVariables.

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml, bitnami/mongodb-sharded/templates/mongos/mongos-deployment.yaml, bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml, bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
mongodb-sharded helm chart
Small fix for a bad cm name reference.
Thx
=> Fix bad cm name ref

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/NOTES.txt
Fixes pod name for the cp commands
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/kafka] Fix typo in NOTES.txt

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/influxdb/cronjob-backup.yaml
Signed-off-by: joancafom <jcarmona@bitnami.com>
Fix parameter capitalisation to actually match its correct form in `values.yml`.
**Benefits**
Annotations for the cronjob are correctly rendered.
None
NA
This PR implements changes requested in #3100 in order to be able to merge it. The original user closed the issue when asked to perform them, so I have implemented them myself.
**Checklist** 
=> [bitnami/influxdb] Fix podAnnotations in cronjob

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/redis-statefulset.yaml
An incorrect value was set, this PR fixes it. 
**Benefits**
- fixes https://github.com/bitnami/charts/issues/2890
**Checklist** 
=> [bitnami/redis-cluster] Fix podannotations

bitnami/drupal/Chart.yaml, bitnami/drupal/templates/deployment.yaml
Fixed a bad indent in drupal charts, see issue #3258 
**Benefits**
The possibility to use the `commonLabels` value
- fixes #3258
**Checklist** 
=> [bitnami/drupal] fix indent in drupal chart

bitnami/dokuwiki/Chart.yaml, bitnami/dokuwiki/templates/deployment.yaml
It is not possible to use commonLabels because the indent is wrongly set
**Benefits**
Fix commonLabels usage
None
- #3258
**Checklist** 
=> [bitnami/dokuwiki] Fix commonLables indent

bitnami/thanos/Chart.yaml, bitnami/thanos/README.md, bitnami/thanos/templates/bucketweb/deployment.yaml, bitnami/thanos/templates/compactor/deployment.yaml, bitnami/thanos/templates/querier/deployment.yaml, bitnami/thanos/templates/ruler/statefulset.yaml, bitnami/thanos/templates/storegateway/statefulset.yaml, bitnami/thanos/values-production.yaml, bitnami/thanos/values.yaml
**Benefits**
Allow users to specify multiflags (flags that can be specified multiple times) and make it more natural to specify boolean flags.
Not compatible with previous chart versions.
- fixes #3218
**Checklist** 
=> [bitnami/thanos] Improve the way boolean/multi flags are passed

bitnami/postgresql/README.md
Add upgrade notes for the major release in https://github.com/bitnami/charts/pull/3021
I am not bumping the chart version as those changes are going to be reflected in the README and we don't need to release a new version for that.
=> [bitnami/postgresql] Add upgrade notes for 9.X.X

bitnami/mediawiki/Chart.yaml, bitnami/mediawiki/templates/deployment.yaml
The current pod CPU usage is high because it's querying to `/api.php`, which loads lots of stuff. Instead, a query to `/api.php?action=query&meta=siteinfo&format=none` would result in a much simpler result that also consumes less CPU.
Without the change I've seen the CPU range from 50m-77m. With the change, from 6m-9m (!!). Right after the deployment, it was 40m.
**Benefits**
Less CPU consumption.
None
- fixes #3138
**Checklist** 
=> [bitnami/mediawiki] Reduce pod CPU usage by changing health check

bitnami/thanos/Chart.yaml
No change, version in my last PR -> https://github.com/bitnami/charts/pull/3323 got overwritten by a bot commit. Changing version with a minor release.
**Benefits**
Can use the correct helm chart.
**Checklist** 
=> [bitnami/thanos]During PR version got bumped by bot. 

bitnami/jenkins/Chart.yaml, bitnami/jenkins/templates/metrics-svc.yaml
**Benefits**
Work as it would be expected: Avoid metrics being enabled when disabled by the user
- Related issue (MongoDB): #3151
**Checklist** 
=> [bitnami/jenkins] Fix metrics-svc.yaml: Remove whitespace in filename and disable when metrics.enabled=false

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/metrics-svc.yaml
**Benefits**
Work as it would be expected: Avoid metrics being enabled when disabled by the user
None
- fixes #3151
**Checklist** 
=> [bitnami/mongodb] Not enable metrics-svc.yaml with metrics.enabled=false

bitnami/prometheus-operator/Chart.yaml, bitnami/prometheus-operator/crds/crd-probes.yaml, bitnami/prometheus-operator/templates/prometheus-operator/crd-probes.yaml
Signed-off-by: joancafom <jcarmona@bitnami.com>
Update probes CRD to apiVersion v1beta
**Benefits**
This new `probes` CRD matches the apiVersion of the other components.
Deployment of the chart can be achieved in K8s cluster with versions < 1.16
- fixes #
**Checklist** 
=> [bitnami/prometheus-operator] Change probes apiVersion to v1beta

bitnami/etcd/Chart.yaml, bitnami/etcd/values-production.yaml, bitnami/etcd/values.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/etcd] Fix typo in values file

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/ruler/statefulset.yaml
Remove if block for mountPath in Ruler, as it's not longer needed.
**Benefits**
No exceptions anymore with certain settings. Working deployment.
- fixes https://github.com/bitnami/charts/issues/3451
**Checklist** 
=> [bitnami/thanos]Fix mountPath for existingObjstoreSecretItems

bitnami/cassandra/Chart.yaml, bitnami/cassandra/templates/statefulset.yaml
CASSANDRA_ENDPOINT_SNITCH is already defined in line 111
Trivial change - remove duplicate definition of the same env var (already defined in line 111) 
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/cassandra]: Remove duplicate env var definition

bitnami/moodle/Chart.yaml, bitnami/moodle/requirements.lock, bitnami/moodle/templates/deployment.yaml
This PR allows the exporter to scrape metrics from the proper Apache port.
**Benefits**
- fixes #3484
**Checklist** 
=> [bitnami/moodle] Use correct port in apache exporter

bitnami/mongodb/README.md
=> [bitnami/mongodb] Add notes to upgrade to 9.0.0

bitnami/mongodb-sharded/README.md
=> [bitnami/mongodb-sharded] Add notes to upgrade to 2.0.0

bitnami/odoo/Chart.yaml, bitnami/odoo/templates/NOTES.txt
Fix misspelling in NOTES.txt
**Benefits**
Release information is displayed without errors now.
None
N/A
None
**Checklist**
⚠️ Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the kubeapps repository. This is only a synchronized mirror.
=> [bitnami/odoo] Fixed the spelling of 'running'

bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/node/requirements.lock, bitnami/node/requirements.yaml
Signed-off-by: Andrés Bono <andresbono@vmware.com>
**Checklist**
=> [bitnami/node] Update MongoDB dependency to latest major version

bitnami/parse/Chart.yaml, bitnami/parse/README.md, bitnami/parse/requirements.lock, bitnami/parse/requirements.yaml
Signed-off-by: Andrés Bono <andresbono@vmware.com>
**Checklist**
=> [bitnami/parse] Update MongoDB dependency to latest major version

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/NOTES.txt
Provides a copy and paste actions for the users. This will avoid typos when handling the helm install output.
**Benefits**
- Helps avoiding  #3499
**Checklist** 
- [-] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files
=> [bitnami/kafka] Improves NOTES.txt for users

bitnami/odoo/Chart.yaml, bitnami/odoo/templates/secrets.yaml
Make Odoo secret API request cleaner.
**Benefits**
Remove white lines in generated odoo secret yaml that make request smaller. 
**Checklist**
=> [bitnami odoo] Clean Odoo secret API request

bitnami/mongodb/Chart.yaml, bitnami/mongodb/values-production.yaml, bitnami/mongodb/values.yaml
Fix wrong descriptions due to copy-paste from other charts
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/mongodb] Fix values descriptions

bitnami/mariadb-galera/README.md, bitnami/nginx/README.md, bitnami/postgresql-ha/README.md, bitnami/rabbitmq/README.md
Add links to the Kubernetes documentation at docs.bitnami.com
**Benefits**
Have a section in the README file to redirect customers to  docs.bitnami.com
- fixes #
**Checklist** 
- [X ] Variables are documented in the README.md
=> Add links to docs.bitnami.com

bitnami/redis/values-production.yaml
Fixed a typo in a comment
**Benefits**
Correct spelling
None
None
**Checklist** 
=> Typo in comment fixed: namespacess -> namespaces

bitnami/prestashop/README.md
- Add a new troubleshooting section in Prestashop chart documentation
- Add an SSL section in troubleshooting to explain how to activate it manually in Prestashop.
**Benefits**
Clarify how to activate SSL in prestashop to avoid confusion with the chart configuration since it has to be done manually.
None
- fixes #3714
**Checklist** 
=> [bitnami/prestashop]: add a troubleshooting section in README

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/_helpers.tpl, bitnami/postgresql/templates/configmap.yaml, bitnami/postgresql/templates/extended-config-configmap.yaml, bitnami/postgresql/templates/initialization-configmap.yaml, bitnami/postgresql/templates/metrics-configmap.yaml, bitnami/postgresql/templates/metrics-svc.yaml, bitnami/postgresql/templates/networkpolicy.yaml, bitnami/postgresql/templates/podsecuritypolicy.yaml, bitnami/postgresql/templates/prometheusrule.yaml, bitnami/postgresql/templates/role.yaml, bitnami/postgresql/templates/rolebinding.yaml, bitnami/postgresql/templates/secrets.yaml, bitnami/postgresql/templates/serviceaccount.yaml, bitnami/postgresql/templates/servicemonitor.yaml, bitnami/postgresql/templates/statefulset-slaves.yaml, bitnami/postgresql/templates/statefulset.yaml, bitnami/postgresql/templates/svc-headless.yaml, bitnami/postgresql/templates/svc-read.yaml, bitnami/postgresql/templates/svc.yaml
Use the common functions instead of the `postgresql.tplValue` function
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/postgresql] Use common functions for tplValues

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/statefulset.yaml
Added labels for volumeClaimTemplates
**Benefits**
If we want to delete a pvc using a label release. 
for eg:
kubectl delete pvc -l release=xxx
- fixes #
**Checklist** 
=> [bitnami/postgresql] Added labels for volumeClaimTemplates

bitnami/redis/Chart.yaml, bitnami/redis/templates/pdb.yaml
The pod disruption budget template does not have field for namespace, and hence cannot be overridden.
**Benefits**
The change will allow users override pdb's namespace with helm commands as needed.
- fixes https://github.com/bitnami/charts/issues/3787
N.A.
**Checklist** 
=> [bitnami/redis] Add namespace in Pod Disruption Budget template

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/registry/registry-cm.yaml
This is necessary for the latest version of harbor-registryctl to work.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/harbor] Add missing parameter in harbor-registryctl ConfigMap

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/statefulset.yaml
#3768 causes any upgrades to fail because it changes an immutable field. Also, `common.labels.standard` should not be set, and we should be using `matchLabels`.
**Benefits**
Upgrades will start working again.
#3768 needs to be revisited.
- Related issue: #3801
**Checklist** 
=> [bitnami/postgresql] Revert #3768 due to being a breaking change

bitnami/mariadb/Chart.yaml, bitnami/mariadb/templates/master-statefulset.yaml, bitnami/mariadb/templates/slave-statefulset.yaml
**Benefits**
- fixes #3794
**Checklist** 
=> [bitnami/mariadb] Fix existingSecret

bitnami/dokuwiki/Chart.yaml, bitnami/dokuwiki/values.yaml
In none of our containers do we enable the volumePermissions init container by default, but in #3441 we added support for it and then also enabled it by default.
However it should not be needed for most scenarios, in fact some Kubernetes clusters would not even support it because it would start a container as a root user, against cluster policies.
Even the README shows `false` being the default value currently, meaning the current setting is wrong.
**Benefits**
* Consistency with other Bitnami charts, as we're never running the volumePermissions init container by default
* Default values would work on clusters with policies against running containers as a root user.
* Changing the default values that would result in a new behavior for …
=> [bitnami/dokuwiki] Do not run volumePermissions init container by default

bitnami/mongodb-sharded/Chart.yaml
Fixes https://github.com/bitnami/charts/issues/3695
=> bump chart version number

bitnami/nginx/Chart.yaml, bitnami/nginx/README.md, bitnami/nginx/templates/deployment.yaml, bitnami/nginx/values.yaml
Fixes usage of cloneStaticSiteFromGit which was failing due to a typo in one of the templates.
**Benefits**
It is now possible to use cloneStaticSiteFromGit
None
- fixes #3829
**Checklist** 
=> [bitnami/nginx] Fix usage of cloneStaticSiteFromGit

bitnami/node-exporter/Chart.yaml, bitnami/node-exporter/templates/service.yaml
Fix indentations for the service annotations
**Benefits**
- fixes #3815
**Checklist** 
=> [bitnami/node-exporter] Fix service annotations indentation

README.md
Add a note in the README about the Helm v2 deprecation
=> Helm v2 EOL notice in the main README

bitnami/tomcat/Chart.yaml, bitnami/tomcat/README.md, bitnami/tomcat/templates/deployment.yaml, bitnami/tomcat/values.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/tomcat] add replicas to tomcat  deployment

bitnami/prestashop/Chart.yaml, bitnami/prestashop/templates/deployment.yaml
This chart fails on a new install using external db as the secret name does not match in the pod to the secret. 
This chart and application can now be used with an external db
- fixes #
**Checklist** 
=> [bitnami/prestashop] fix usage of externalDb secret in pod

bitnami/ghost/Chart.yaml, bitnami/ghost/requirements.lock, bitnami/ghost/requirements.yaml
Revert to using version `0.7.x` of the chart `common` until the new major of `bitnami/mariadb` is released.
- fixes #3875
**Checklist** 
=> [bitnami/ghost] Fix common dependency

bitnami/mariadb/Chart.yaml, bitnami/mariadb/templates/secrets.yaml
- fixed typo rauth to auth
- fixed logical error which caused error "A MariaDB Replication Password is required!" when architecture=replication and auth.replicationPassword is empty.
**Benefits**
Fix problems.
Not known.
- fixes #3909 
**Checklist** 
=> [bitami/mariadb] fix replication password #3909

bitnami/mariadb-galera/README.md
Update README section about using initialization scripts
=> [bitnami/mariadb-galera] Update instructions about initialization scripts

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/replicaset/external-access-svc.yaml
**Benefits**
- fixes #3921
**Checklist** 
=> [bitnami/mongodb] Fix mongodb external access

bitnami/consul/templates/statefulset.yaml
Fix issue with duplicated env var (https://github.com/bitnami/charts/pull/3810/files) that prevented the publication of the chart
It does not require a major bump because it was never released.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/consul] Fix duplicated bootstrap expect

bitnami/moodle/Chart.yaml, bitnami/moodle/requirements.lock, bitnami/moodle/requirements.yaml
Revert to using version `0.7.x` of the `common` chart until the new major this chart with `bitnami/mariadb 8.0.0` is released.
**Benefits**
Moodle chart installs successfully
`common` subchart must be updated afterwards, manually
- fixes #
**Checklist** 
=> [bitnami/moodle] Fix common dependency

bitnami/nginx/README.md
The default value is an empty array not an empty map. empty map implied `<NAME>: <value>` rather than correct empty array implying standard kubernetes format.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/nginx] Minor readme fix

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/replicaset/external-access-svc.yaml
**Benefits**
- fixes #3956
**Checklist** 
=> [bitnami/mongodb] Fix typo in external access namespace

bitnami/owncloud/Chart.yaml, bitnami/owncloud/README.md, bitnami/owncloud/templates/_helpers.tpl, bitnami/owncloud/templates/deployment.yaml, bitnami/owncloud/values.yaml
Add extraEnvVars parameter
https://github.com/bitnami/bitnami-docker-owncloud/issues/64
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/owncloud] Add ExtraEnvVar parameter

bitnami/drupal/Chart.yaml, bitnami/drupal/README.md, bitnami/drupal/requirements.lock, bitnami/drupal/requirements.yaml, bitnami/drupal/templates/NOTES.txt, bitnami/drupal/templates/_helpers.tpl, bitnami/drupal/templates/deployment.yaml, bitnami/drupal/templates/externaldb-secrets.yaml, bitnami/drupal/templates/ingress.yaml, bitnami/drupal/templates/pv.yaml, bitnami/drupal/templates/pvc.yaml, bitnami/drupal/templates/secrets.yaml, bitnami/drupal/templates/svc.yaml, bitnami/drupal/templates/tls-secrets.yaml, bitnami/drupal/values.yaml
As part of #3869 we implemented some standarizations, but there are some things that were left out, i.e. init containers for volume permissions, injecting certificates, more customization options, etc.
**Benefits**
The chart is now more complete, with lots of new features for users
None
- fixes #
**Checklist** 
=> [bitnami/drupal] Implement additional standarizations

bitnami/kube-state-metrics/Chart.yaml, bitnami/kube-state-metrics/templates/service.yaml
Fixes the indentation issue when trying add additional service labels through the `service.labels` key:
```yaml
apiVersion: v1
kind: Service
metadata:
name: kube-state-metrics
namespace: kube-system
annotations:
prometheus.io/scrape: "true"
labels:
app.kubernetes.io/name: kube-state-metrics
helm.sh/chart: kube-state-metrics-0.5.3
app.kubernetes.io/instance: kube-state-metrics
app.kubernetes.io/version: "1.9.7"
app.kubernetes.io/managed-by: Helm    \nkubernetes.io/cluster-service: "true"
kubernetes.io/name: kube-state-metrics
spec:
type: ClusterIP
ports:
- name: http
port: 8080
targetPort: http
nodePort: null
selector:
app.kubernetes.io/name: kube-state-metrics
app.kubernetes.io/instance: kube-state-metrics
Error: YAML parse error on …
```
=> [bitnami/kube-state-metrics] Fix service label indentation issue

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/update-cluster.yaml
When upgrading and adding more nodes, the nodes will be added as master and slaves. Also it retries to add the node if it failed for some reason.
**Benefits**
- should fix #3743 
**Checklist** 
=> [bitnami/redis-cluster] Fix adding nodes with helm upgrade.

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/values-production.yaml, bitnami/redis-cluster/values.yaml, bitnami/redis/Chart.yaml, bitnami/redis/ci/production-sentinel-values.yaml, bitnami/redis/values-production.yaml, bitnami/redis/values.yaml
Fix example PrometheusRule
**Benefits**
People can use example PrometheusRule in `values.yaml` files without getting `invalid rule` error from admission webhook
Not everyone is familiar with PromQL to debug this syntax error
None
- fixes #
**Checklist** 
=> [bitnami/redis] Fix example PrometheusRule

bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md, bitnami/wordpress/templates/ingress.yaml, bitnami/wordpress/values-production.yaml, bitnami/wordpress/values.yaml
Make the default/main path configurable
This is useful if you are deploying with an Application Load Balancer ingress controller because it uses exact matches, so this value will need to be set to `/*`.
**Checklist**
=> [bitnami/wordpress] Make primary path configurable

bitnami/grafana/README.md
Fix typo in the README
- fixes #4046
=> [bitnami/grafana] Fix typo in README

bitnami/mariadb-galera/README.md, bitnami/mariadb/README.md, bitnami/mysql/README.md
Update initdbScripts documentation
=> [bitnami/mariadb/galera/mysql] Update initdbScripts documentation

bitnami/thanos/Chart.yaml, bitnami/thanos/README.md, bitnami/thanos/requirements.lock, bitnami/thanos/templates/_helpers.tpl, bitnami/thanos/templates/query-frontend/configmap.yaml, bitnami/thanos/templates/query-frontend/deployment.yaml, bitnami/thanos/templates/query-frontend/hpa.yaml, bitnami/thanos/templates/query-frontend/ingress.yaml, bitnami/thanos/templates/query-frontend/pdb.yaml, bitnami/thanos/templates/query-frontend/psp-clusterrole.yaml, bitnami/thanos/templates/query-frontend/psp-clusterrolebinding.yaml, bitnami/thanos/templates/query-frontend/psp.yaml, bitnami/thanos/templates/query-frontend/service.yaml, bitnami/thanos/templates/query-frontend/serviceaccount.yaml, bitnami/thanos/templates/query-frontend/servicemonitor.yaml, bitnami/thanos/templates/query-frontend/tls-secrets.yaml, bitnami/thanos/values-production.yaml, bitnami/thanos/values.yaml
Add ability to deploy [Thanos Query Frontend](https://thanos.io/v0.15/components/query-frontend/#query-frontend) component.
**Benefits**
Users can cache responses for query range.
Users can split query range queries.
Users can rate limit and retry range queries.
- fixes #3747 
**Checklist** 
=> [bitnami/thanos] Add Thanos Query Frontend

bitnami/odoo/Chart.yaml, bitnami/odoo/README.md, bitnami/odoo/requirements.lock, bitnami/odoo/requirements.yaml, bitnami/odoo/templates/NOTES.txt, bitnami/odoo/templates/_helpers.tpl, bitnami/odoo/templates/deployment.yaml, bitnami/odoo/templates/externaldb-secrets.yaml, bitnami/odoo/templates/ingress.yaml, bitnami/odoo/templates/pvc.yaml, bitnami/odoo/templates/secrets.yaml, bitnami/odoo/templates/svc.yaml, bitnami/odoo/templates/tls-secrets.yaml, bitnami/odoo/values.yaml
This PR updates PostgreSQL subchart to the new major version, which includes breaking changes. More info at #3021
As this requires a major bump in this chart, it has been adapted to follow some standardizations found in other Bitnami Charts. Please check _additional information_ or README for a detailed list of new standard features.
The most important change is in the labels, that are adapted to follow the Helm charts standard labels.
**Benefits**
Standardization, up-to-date subcomponents, 
Breaks backwards compatibility
NA
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps …
=> [bitnami/odoo] Odoo major

bitnami/redis/Chart.yaml, bitnami/redis/templates/configmap-scripts.yaml, bitnami/redis/templates/configmap.yaml, bitnami/redis/templates/headless-svc.yaml, bitnami/redis/templates/health-configmap.yaml, bitnami/redis/templates/metrics-prometheus.yaml, bitnami/redis/templates/metrics-svc.yaml, bitnami/redis/templates/networkpolicy.yaml, bitnami/redis/templates/pdb.yaml, bitnami/redis/templates/prometheusrule.yaml, bitnami/redis/templates/psp.yaml, bitnami/redis/templates/redis-master-statefulset.yaml, bitnami/redis/templates/redis-master-svc.yaml, bitnami/redis/templates/redis-node-statefulset.yaml, bitnami/redis/templates/redis-role.yaml, bitnami/redis/templates/redis-rolebinding.yaml, bitnami/redis/templates/redis-serviceaccount.yaml, bitnami/redis/templates/redis-slave-statefulset.yaml, bitnami/redis/templates/redis-slave-svc.yaml, bitnami/redis/templates/redis-with-sentinel-svc.yaml, bitnami/redis/templates/secret.yaml
This change makes the solution to work in numeric namespaces
**Benefits**
- fixes https://github.com/bitnami/charts/issues/3856
**Checklist** 
=> [bitnami/redis] Add quote to namespace

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/_helpers.tpl, bitnami/influxdb/templates/ingress.yaml
**Benefits**
- fixes #4098 
**Checklist** 
=> [bitnami/influxdb] Set proper ingress apiVersion

bitnami/airflow/README.md
https://github.com/bitnami/charts/issues/3920#issuecomment-705388139
=> [bitnami/airflow]: add documentation on python package installation into airflow containers

bitnami/moodle/README.md
Update Moodle title
**Checklist** 
- [not needed] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
=> [bitnami/moodle] Update moodle title

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/secrets.yaml
The logic to create the Postgres password is on the _helpers.tpl so it is not necessary at the secret
**Benefits**
- fixes #4120
**Checklist** 
=> [bitnami/postgresql] Fix secret logic for passwords

bitnami/mariadb/Chart.yaml, bitnami/mariadb/templates/primary/statefulset.yaml, bitnami/mariadb/templates/secondary/statefulset.yaml
This pull requests introduces the `commonLabels` into the spec of pods in `primary` and `secondary` statefulsets. Most of the other resources already use `commonLabels`, however the pods under sts did not, which causes policy violations in environments using OPA (gatekeeper).
**Benefits**
This PR applies the labels in `commonLabels` on pods deployed by `primary` and `secondary` statefulsets, just as it is the case for all other resources deployed in this chart. It makes it possible to deploy this chart in environments enforcing policies through OpenPolicy Agent (a.k.a. gatekeeper), like required labels.
No known drawbacks.
- fixes #4175
**Checklist**
=> [bitnami/mariadb] Add commonLabels to pods spec

bitnami/mongodb/README.md
Fix error in README renderization
**Benefits**
- fixes https://github.com/bitnami/charts/pull/3959
**Checklist** 
=> [bitnami/mongodb] Fix README.md issue

CONTRIBUTING.md
There is a typo in `CONTRIBUTING.md` with the link to the new directory `template`.
**Checklist** 
=> Fix CONTRIBUTING.md link

bitnami/mariadb/Chart.yaml, bitnami/mariadb/values-production.yaml, bitnami/mariadb/values.yaml
Remove old references to master and slave
**Benefits**
- fixes #4180
**Checklist** 
=> [bitnami/mariadb] Fix master and slave references

bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md, bitnami/keycloak/ci/values-ha.yaml, bitnami/keycloak/ci/values-hpa-pdb.yaml, bitnami/keycloak/ci/values-metrics-and-ingress.yaml, bitnami/keycloak/requirements.lock, bitnami/keycloak/requirements.yaml, bitnami/keycloak/templates/NOTES.txt, bitnami/keycloak/templates/_helpers.tpl, bitnami/keycloak/templates/clusterrole.yaml, bitnami/keycloak/templates/clusterrolebinding.yaml, bitnami/keycloak/templates/configmap-env-vars.yaml, bitnami/keycloak/templates/configmap.yaml, bitnami/keycloak/templates/extra-list.yaml, bitnami/keycloak/templates/headless-service.yaml, bitnami/keycloak/templates/hpa.yaml, bitnami/keycloak/templates/ingress.yaml, bitnami/keycloak/templates/init-scripts-configmap.yaml, bitnami/keycloak/templates/metrics-service.yaml, bitnami/keycloak/templates/networkpolicy.yaml, bitnami/keycloak/templates/pdb.yaml, bitnami/keycloak/templates/role.yaml, bitnami/keycloak/templates/rolebinding.yaml, bitnami/keycloak/templates/secret-env-vars.yaml, bitnami/keycloak/templates/service.yaml, bitnami/keycloak/templates/serviceaccount.yaml, bitnami/keycloak/templates/servicemonitor.yaml, bitnami/keycloak/templates/statefulset.yaml, bitnami/keycloak/templates/tls-secret.yaml, bitnami/keycloak/values.yaml
This PR adds a new chart to the catalog: Keycloak
Keycloak is a high performance Java-based identity and access management solution. It lets developers add an authentication layer to their applications with minimum effort.
Please read carefully the README.md and provide feedback about anything you think that doesn't make sense.
=> Add new chart: Keycloak

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/log4j-configmap.yaml
This will allow to use variables in the log4j configuration
log4j: |-
log4j.rootLogger={{ default "INFO" .Values.logLevel }}, stdout, kafkaAppender
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/kafka]Use template for log4j configuration

bitnami/wordpress/values.yaml
Fix file path for file to mount in comment
=> Fix typo in file path

bitnami/wordpress/values-production.yaml
Fix file path for the file to mount in comment
Forgot in last PR
=> [bitnami/wordpress] Fix typo in file path

bitnami/odoo/README.md
The newest major version of the chart includes a new major of the application itself. Given that the DB schemas are changed, the notice only contains a link to the official documentation upgrade process.
**Checklist** 
=> [bitnami/odoo] Add upgrade notice

bitnami/kong/Chart.yaml, bitnami/kong/templates/deployment.yaml
There is an indentation error on `deployment.yaml`, causing an `Error: YAML parse error` when using `.Values.extraVolumes`.
**Benefits**
Solves the issue
None
- fixes #4356
**Checklist** 
=> [bitnami/kong] Fix indentation problem

bitnami/opencart/Chart.yaml, bitnami/opencart/values.yaml
**Description** 
Wrong position of the sessionAffinity variable in the values.yaml.
**Benefits**
Bug will be fixed
=> [bitnami/opencart] fixed sessionAffinity

bitnami/kiam/Chart.lock, bitnami/kiam/Chart.yaml, bitnami/kiam/requirements.lock
Update dependencies and remove old requirements.lock file
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/kiam] Fix KIAM package

bitnami/postgresql/Chart.yaml, bitnami/postgresql/values.yaml
Fix typo in `values.yaml` introduced in version `10.0.0`.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/postgresql] Fix typo in values.yaml

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/NOTES.txt
Add validation to show an error when upgrading if you are not setting the old keycloack admin password.
**Benefits**
Avoid users confusions
- fixes #4411
**Checklist** 
=> [bitnami/keycloack] Add validation for Keycloack admin password

bitnami/logstash/Chart.yaml, bitnami/logstash/README.md, bitnami/logstash/templates/sts.yaml, bitnami/logstash/values-production.yaml, bitnami/logstash/values.yaml
Allows users to use the [multiple pipelines](https://www.elastic.co/guide/en/logstash/master/multiple-pipelines.html) feature.
The scenario described in the README is also the proper way to test the changes.
It's a new feature, no drawback
- fixes #4464
Changes in the container are already released in the `-r7` revision, see https://github.com/bitnami/bitnami-docker-logstash/commit/99d500a1205f41050ca88385611ab33cd2ad457b
**Checklist**
=> [bitnami/logstash] Allows to use multiple pipelines

bitnami/airflow/README.md, bitnami/discourse/README.md, bitnami/harbor/README.md, bitnami/keycloak/README.md, bitnami/kong/README.md, bitnami/odoo/README.md, bitnami/postgresql/README.md
Added instructions for upgrading to the latest major reusing the PVC.
- fixes #4468
**Checklist** 
=> [bitnami/*] Add upgrade details to README

bitnami/node/Chart.lock, bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/node/requirements.lock, bitnami/node/requirements.yaml, bitnami/node/templates/NOTES.txt, bitnami/node/templates/_helpers.tpl, bitnami/node/templates/deployment.yaml, bitnami/node/templates/extra-list.yaml, bitnami/node/templates/ingress.yaml, bitnami/node/templates/mongodb-binding.yaml, bitnami/node/templates/pvc.yaml, bitnami/node/templates/svc.yaml, bitnami/node/values.yaml
=> Revert "[bitnami/node] Major version. apiVersion: v2, standardizations and subchart bump"

bitnami/mongodb/Chart.lock, bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/NOTES.txt
Continuation of https://github.com/bitnami/charts/pull/4497, we should wait for the common release before merging this PR. Once released the new common, we should run `helm dep update` and check that the new version is included in the Chart.lock
=> [bitnami/mongodb] Use common validations

bitnami/node/Chart.lock, bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/node/requirements.lock, bitnami/node/requirements.yaml, bitnami/node/templates/NOTES.txt, bitnami/node/templates/_helpers.tpl, bitnami/node/templates/deployment.yaml, bitnami/node/templates/extra-list.yaml, bitnami/node/templates/ingress.yaml, bitnami/node/templates/mongodb-binding.yaml, bitnami/node/templates/pvc.yaml, bitnami/node/templates/svc.yaml, bitnami/node/values.yaml
Continuation of the changes implemented in https://github.com/bitnami/charts/pull/4322 that were merged by mistake and immediately reverted in https://github.com/bitnami/charts/pull/4503
=> [bitnami/node] Major version. apiVersion: v2, standardizations and subchart bump

bitnami/nats/Chart.lock, bitnami/nats/Chart.yaml, bitnami/nats/README.md, bitnami/nats/templates/NOTES.txt, bitnami/nats/templates/_helpers.tpl, bitnami/nats/templates/client-svc.yaml, bitnami/nats/templates/cluster-svc.yaml, bitnami/nats/templates/configmap.yaml, bitnami/nats/templates/deployment.yaml, bitnami/nats/templates/extra-list.yaml, bitnami/nats/templates/headless-svc.yaml, bitnami/nats/templates/ingress.yaml, bitnami/nats/templates/metrics-svc.yaml, bitnami/nats/templates/monitoring-svc.yaml, bitnami/nats/templates/networkpolicy.yaml, bitnami/nats/templates/poddisruptionbudget.yaml, bitnami/nats/templates/servicemonitor.yaml, bitnami/nats/templates/statefulset.yaml, bitnami/nats/templates/tls-secret.yaml, bitnami/nats/values-production.yaml, bitnami/nats/values.yaml
This PR refactors the whole chart to follow Helm chart best practices. This includes several breaking changes, so please review it carefully, putting special emphasis to the "Upgrading" section describing all of them.
**Benefits**
- Reduces technical debt.
It breaks backwards compatibility.
None
-
**Checklist**
=> [bitnami/nats] New major version

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/redis-statefulset.yaml
Remove dead code in statefulset template.
**Benefits**
Cleaner code.
None.
None.
**Checklist** 
=> [bitnami/redis-cluster] Remove dead code in statefulset template

bitnami/consul/Chart.yaml, bitnami/consul/templates/servicemonitor.yaml
Modify servicemonitor endpoint port name. https://github.com/bitnami/charts/issues/4513
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/consul] Update servicemonitor.yaml

bitnami/grafana/Chart.yaml, bitnami/grafana/templates/deployment.yaml
…aml file
Sets `GF_SMTP_ENABLED` environment variable along the other `SMTP` variables when `stmp.enabled` is set in `values.yaml`.
**Benefits**
Enables SMTP
- fixes #4561
**Checklist** 
- [-] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files
=> [bitnami/grafana] Set environment variable GF_SMTP_ENABLED when enabled in the values.yaml

bitnami/jenkins/Chart.lock, bitnami/jenkins/Chart.yaml, bitnami/jenkins/README.md, bitnami/jenkins/ci/values-with-metrics-and-ingress.yaml, bitnami/jenkins/templates/NOTES.txt, bitnami/jenkins/templates/_helpers.tpl, bitnami/jenkins/templates/deployment.yaml, bitnami/jenkins/templates/extra-list.yaml, bitnami/jenkins/templates/ingress.yaml, bitnami/jenkins/templates/metrics-svc.yaml, bitnami/jenkins/templates/pvc.yaml, bitnami/jenkins/templates/secrets.yaml, bitnami/jenkins/templates/servicemonitor.yaml, bitnami/jenkins/templates/svc.yaml, bitnami/jenkins/templates/tls-secret.yaml, bitnami/jenkins/values.yaml
This PR refactors the whole chart to follow Helm chart best practices. This includes several breaking changes, so please review it carefully, putting special emphasis to the "Upgrading" section describing all of them.
**Benefits**
- Reduces technical debt.
It breaks backwards compatibility.
None
-
**Checklist**
=> [bitnami/jenkins] New major version

bitnami/kubernetes-event-exporter/Chart.yaml, bitnami/kubernetes-event-exporter/README.md, bitnami/kubernetes-event-exporter/templates/deployment.yaml, bitnami/kubernetes-event-exporter/values.yaml
add priorityClassName
**Benefits**
priorityClass support
NA
NA
**Checklist** 
=> [bitnami/kubernetes-event-exporter] add priorityClassName to kubernetes-event-exporter

bitnami/grafana/Chart.yaml, bitnami/grafana/templates/deployment.yaml
Fixes missing quotes in `GF_SMTP_ENABLED`
**Benefits**
- fixes #4565, #4561 
**Checklist** 
- [-] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files
=> [bitnami/grafana] Fixes typo in smtp enabled

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md
Update README
**Benefits**
Go to the right docs instead of some random site
No known
- fixes #
**Checklist** 
=> [bitnami/kafka] Fix Kafka website url

bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md, bitnami/keycloak/templates/statefulset.yaml, bitnami/keycloak/values.yaml
Allow adding extra parameters to the default keycloak container startup command (standalone.sh)
**Benefits**
- fixes https://github.com/bitnami/charts/issues/4548
**Checklist** 
=> [bitnami/keycloak] Add extra startup args support

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/trivy/trivy-cm-envvars.yaml, bitnami/harbor/values-production.yaml, bitnami/harbor/values.yaml
This PR adds proxy capabilities to Trivy
**Benefits**
- fixes https://github.com/bitnami/charts/issues/4608
**Checklist** 
=> [bitnami/harbor] Add trivy to proxy

bitnami/spark/values.yaml
Add empty list in annotations introduced by #4605
**Checklist** 
- [ n/a] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ n/a] Variables are documented in the README.md
=> [bitnami/spark] Add empty list for annotations

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/statefulset.yaml
fixed command name in preStop in statefulset,yaml: rabbitmq to rabbitmqctl
**Benefits**
Avoid of error message rabbitmq: command not found on pod stop
**Checklist** 
=> [bitnami/rabbitmq] Fix rabbitmqctl command name in preStop action

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/replicaset/external-access-svc.yaml
To allow accessing the current targetPod in the annotations
We register a new variable with the current index of pod for annotations
**Benefits**
servcie annotations can now retrieve the targetPod for example for a DNS
`external-dns.alpha.kubernetes.io/hostname: '{{ .targetPod }}.example.com'`
- fixes #https://github.com/bitnami/charts/issues/4639
**Checklist** 
=> [bitnami/mongodb] Register targetPod in global context

bitnami/mariadb/README.md
Single word typo fix "MongoDB" to "MariaDB" in the README.md.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/mariadb] docs - fix typo in README.md

bitnami/kafka/Chart.lock, bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kafka/templates/statefulset.yaml, bitnami/kafka/values-production.yaml, bitnami/kafka/values.yaml
This PR allows specifying extra init containers.
**Benefits**
Allows to add extra init containers
- fixes #4651
**Checklist** 
=> [bitnami/kafka] Add extra initContainers parameter

bitnami/wordpress/README.md
Minor update to docs - readme - broken URL (404)
**Benefits**
Link in readme to MariaDB chart now works
N/A
N/A
N/A
=> Fix out of date MariaDB chart URL

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml, bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml, bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
**Benefits**
- fixes #4684
**Checklist** 
=> [bitnami/mongodb-sharded] fix for #4684

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/statefulset.yaml
**Benefits**
- fixes #4678
**Checklist** 
=> [bitnami/keycloak] Fix entrypoint usage with auth.tls.enabled

bitnami/osclass/Chart.lock, bitnami/osclass/Chart.yaml, bitnami/osclass/README.md, bitnami/osclass/ci/values-with-host-and-ingress.yaml, bitnami/osclass/templates/NOTES.txt, bitnami/osclass/templates/_helpers.tpl, bitnami/osclass/templates/deployment.yaml, bitnami/osclass/templates/externaldb-secrets.yaml, bitnami/osclass/templates/extra-list.yaml, bitnami/osclass/templates/ingress.yaml, bitnami/osclass/templates/metrics-svc.yaml, bitnami/osclass/templates/osclass-pvc.yaml, bitnami/osclass/templates/secrets.yaml, bitnami/osclass/templates/svc.yaml, bitnami/osclass/templates/tls-secrets.yaml, bitnami/osclass/values.yaml
This PR refactors the whole chart to follow Helm chart best practices. This includes several breaking changes, so please review it carefully, putting special emphasis to the "Upgrading" section describing all of them.
**Benefits**
- Reduces technical debt.
It breaks backwards compatibility.
None
-
**Checklist**
=> [bitnami/osclass] New major version

bitnami/logstash/Chart.yaml, bitnami/logstash/README.md, bitnami/logstash/files/conf/README.md, bitnami/logstash/templates/configuration-cm.yaml, bitnami/logstash/templates/extra-list.yaml, bitnami/logstash/templates/sts.yaml, bitnami/logstash/values-production.yaml, bitnami/logstash/values.yaml
Remove files/conf support as it was causing issues in certain Kubernetes solutions due to the README.md file.
**Checklist** 
=> [bitnami/logstash] Remove files/conf support

bitnami/kong/Chart.yaml, bitnami/kong/crds/custom-resource-definitions.yaml, bitnami/kong/values-production.yaml, bitnami/kong/values.yaml
This PR updates CRDs according to the latest changes introduced in Kong Ingress Controller
None
None
**Checklist**
=> [bitnami/kong] Update CRDs

bitnami/ejbca/Chart.yaml, bitnami/ejbca/templates/ingress.yaml
Without the added parameter, the SSL redirection was not working as expected.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/ejbca] Fix ingress issue with SSL redirection

bitnami/jasperreports/Chart.lock, bitnami/jasperreports/Chart.yaml, bitnami/jasperreports/README.md, bitnami/jasperreports/ci/values-with-ingress.yaml, bitnami/jasperreports/templates/NOTES.txt, bitnami/jasperreports/templates/_helpers.tpl, bitnami/jasperreports/templates/deployment.yaml, bitnami/jasperreports/templates/externaldb-secrets.yaml, bitnami/jasperreports/templates/extra-list.yaml, bitnami/jasperreports/templates/ingress.yaml, bitnami/jasperreports/templates/pvc.yaml, bitnami/jasperreports/templates/secrets.yaml, bitnami/jasperreports/templates/svc.yaml, bitnami/jasperreports/templates/tls-secrets.yaml, bitnami/jasperreports/values.yaml
This PR refactors the whole chart to follow Helm chart best practices.
This includes several breaking changes, so please review it carefully, putting special emphasis to the "Upgrading" section describing all of them.
**Benefits**
- Reduces technical debt.
It breaks backwards compatibility.
None
-
**Checklist**
=> [bitnami/jasperreports] New major version

template/CHART_NAME/templates/daemonset.yaml, template/CHART_NAME/templates/deployment.yaml, template/CHART_NAME/templates/service.yaml, template/CHART_NAME/templates/statefulset.yaml, template/CHART_NAME/values.yaml
This PR performs minor corrections in template example.
=> Minor corrections in template

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/ingress.yaml
In case of `high-availability` architecture, the existing ingress rules do not work with ALB ingress controller. The reason being, `/` has higher priority over `/write` Furthermore, except `/write` which should go to the relay, all other requests should go to the InfluxDB directly.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/influxdb] Re-order ingress rules to be compatible with ALB ingress controller

bitnami/kube-state-metrics/Chart.yaml, bitnami/kube-state-metrics/templates/deployment.yaml
Uses tolerations from .Values.tolerations
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/kube-state-metrics] Fix tolerations in deployment

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/README.md
There was a small indentation error in the README for setting up an emptyDir.
**Benefits**
When copy-pasting the suggested code, it will work without issues.
**Checklist** 
=> [bitnami/postgresql-ha] docs: fixed indentation error in README

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/relay/deployment.yaml
Fixes the command name for the relay image.
**Benefits**
- fixes #4765
**Checklist** 
- [-] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files
=> [bitnami/influxdb] Fixes relay command influxdb

bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/node/templates/svc.yaml, bitnami/node/values.yaml
Added "loadBalancerSourceRanges" to LoadBalancer service type as it's been implemented in other charts.
**Benefits**
You will now be ale to constrain source IPs to the installed application. Additionally, the charts service is more consistent with services of existing charts.
- fixes #
**Checklist** 
=> [bitnami/node] Added "loadBalancerSourceRanges" to LoadBalancer service type

bitnami/wordpress/Chart.lock, bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md, bitnami/wordpress/templates/ingress.yaml, bitnami/wordpress/values-production.yaml, bitnami/wordpress/values.yaml
**Benefits**
n/a
**Checklist** 
=> [bitnami/wordpress] Make Ingress rules compatible with Kubernetes 1.20

bitnami/minio/README.md
Per the MinIO team request, we need to add the trademark to the MinIO description.
**Benefits**
- nothing
**Checklist** 
=> Add trademarkt to the MinIO readme file

bitnami/minio/README.md
Add disclaimer to the MinIO Chart readme
**Benefits**
- nothing
**Checklist** 
=> Add disclaimer to the MinIO readme

bitnami/kiam/README.md
This solution can be deployed in any K8s cluster see https://github.com/uswitch/kiam/issues/244 but it is mainly intended to be deployed in AWS.
**Checklist** 
- [n/a] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [n/a] Variables are documented in the README.md
- [n/a] If the chart contains a `values-production.yaml` apart from `values.yaml`, ensure that you implement the changes in both files
=> [bitnami/kiam] Improve note for the chart requirements in AWS

bitnami/suitecrm/Chart.yaml, bitnami/suitecrm/templates/deployment.yaml
When deploying bitnami/suitecrm the pod complains about missing smtp password and port.
**Benefits**
With this fix suitecrm will deploy correctly when using smtp settings.
None.
- fixes #
**Checklist** 
=> [bitnami/suitecrm] Fix for smtpPassword and SUITECRM_SMTP_PORT

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/templates/_helpers.tpl, bitnami/postgresql-ha/templates/postgresql/statefulset.yaml
**Benefits**
- fixes #4655
**Checklist** 
=> [bitnami/postgresql-ha] Fix password when using existingSecret

bitnami/mariadb/Chart.yaml, bitnami/mariadb/README.md, bitnami/mariadb/values-production.yaml, bitnami/mariadb/values.yaml
Change references of `pdb.create` to `pdb.enabled`, as the documentation and examples state `pdb.create` but the template file actually uses `pdb.enabled`.
**Benefits**
Ensures documentation and templates are in sync, to prevent further confusion.
None, as far as I can tell, as `create` was not implemented.
- fixes #4931
**Checklist** 
=> [bitnami/mariadb] Fix PDB option documentation for MariaDB chart. Fixes #4931

bitnami/kube-state-metrics/Chart.yaml, bitnami/kube-state-metrics/templates/deployment.yaml
Change podLabels `indent` to `nindent` in the `deployment.yaml` to fix the error "mapping values are not allowed in this context" when trying to use the podLabels param.
**Benefits**
You will be able to use the podLabels param to set custom podLabels.
n/a
- fixes #
**Checklist** 
=> [bitnami/kube-state-metrics] Fix podLabels mapping values are not allowed in this context error

bitnami/mysql/README.md
Updated docs to include `priorityClassName`.
**Checklist** 
=> [bitnami/mysql] Update README.md to document priorityClassName

bitnami/ejbca/Chart.lock, bitnami/ejbca/Chart.yaml, bitnami/ejbca/README.md, bitnami/ejbca/templates/NOTES.txt, bitnami/ejbca/templates/_helpers.tpl, bitnami/ejbca/templates/deployment.yaml, bitnami/ejbca/templates/ingress.yaml, bitnami/ejbca/templates/pvc.yaml, bitnami/ejbca/templates/secrets.yaml, bitnami/ejbca/templates/svc.yaml, bitnami/ejbca/values.yaml
NOTE: bumping WordPress as there was a bug in the latest common library
**Benefits**
n/a
**Checklist**
=> [bitnami/ejbca] Make Ingress compatible with k8s 1.20

bitnami/ghost/Chart.lock, bitnami/ghost/Chart.yaml, bitnami/ghost/README.md, bitnami/ghost/templates/ingress.yaml, bitnami/ghost/values.yaml
NOTE: bumping WordPress as there was a bug in the latest common library
**Benefits**
n/a
**Checklist**
=> [bitnami/ghost] Major change: Adapt ingress

bitnami/logstash/Chart.lock, bitnami/logstash/Chart.yaml, bitnami/logstash/README.md, bitnami/logstash/templates/NOTES.txt, bitnami/logstash/templates/ingress.yaml, bitnami/logstash/values-production.yaml, bitnami/logstash/values.yaml
**Benefits**
n/a
**Checklist**
=> [bitnami/logstash] Major change: Adapt ingress

bitnami/odoo/Chart.yaml, bitnami/odoo/README.md, bitnami/odoo/templates/ingress.yaml, bitnami/odoo/values.yaml
**Benefits**
n/a
**Checklist**
=> [bitnami/odoo] Major change: Adapt ingress

bitnami/phpbb/Chart.lock, bitnami/phpbb/Chart.yaml, bitnami/phpbb/README.md, bitnami/phpbb/templates/ingress.yaml, bitnami/phpbb/values.yaml
**Benefits**
n/a
**Checklist**
=> [bitnami/phpbb] Major change: adapt ingress

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/scheduler/deployment.yaml, bitnami/airflow/templates/web/deployment.yaml, bitnami/airflow/templates/worker/statefulset.yaml
Fix broken support for priorityClassName
**Benefits**
Bug fix.
NA
priorityClassName variable was being picked from global scope instead of component scope.
**Checklist**
=> [bitnami/airflow] fix priorityClassName for all components

bitnami/drupal/Chart.lock, bitnami/drupal/Chart.yaml, bitnami/drupal/README.md, bitnami/drupal/templates/ingress.yaml, bitnami/drupal/values.yaml
**Benefits**
n/a
**Checklist**
=> [bitnami/drupal] Major change: Update ingress

bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md, bitnami/mongodb/templates/serviceaccount.yaml, bitnami/mongodb/values-production.yaml, bitnami/mongodb/values.yaml
Adds `serviceAccount.annotations` to the chart.
**Benefits**
- fixes #4958
**Checklist** 
=> [bitnami/mongodb] Add serviceAccount annotations

bitnami/moodle/Chart.lock, bitnami/moodle/Chart.yaml, bitnami/moodle/README.md, bitnami/moodle/templates/ingress.yaml, bitnami/moodle/values.yaml
**Benefits**
n/a
**Checklist**
=> [bitnami/moodle] Major change: adapt ingress

bitnami/node/Chart.lock, bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/node/templates/ingress.yaml, bitnami/node/values.yaml
**Benefits**
n/a
**Checklist**
=> [bitnami/node] Major change: Adapt ingress

bitnami/prestashop/Chart.lock, bitnami/prestashop/Chart.yaml, bitnami/prestashop/README.md, bitnami/prestashop/templates/ingress.yaml, bitnami/prestashop/values.yaml
**Benefits**
n/a
**Checklist**
=> [bitnami/prestashop] Major change: adapt ingress

bitnami/minio/README.md
This PR simply updates the title of the README of MinIO to match with the last legal request.
=> Update MinIO title

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/README.md
Fixed documentation for this chart as the 
grafana-plugin-init container is now as well the grafana container.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/grafana-operator] Update documentation for Plugin Init Container.

.github/workflows/lint-test.yaml
Update the version of the chart-testing action for it to use a newer Helm version and fix the `function "lookup" not defined` error.
Change tested on forked repository where I did a minor change to every chart's `Chart.yaml` for the lint to execute in the whole catalog https://github.com/FraPazGal/charts/pull/2.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/*] Bump version of chart-testing action

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/templates/prometheus/additionalScrapeJobs.yaml
Last PR to add inline scrape jobs config introduced a bug when enabled. The data in the secret ends up as a string instead of a map because the space between the key and the value is removed. 
**Benefits**
Fixes a bug
None
- fixes #
**Checklist** 
=> [bitnami/kube-prometheus] Bug fix. Remove whitespace chomping in new secret

.github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, bitnami/elasticsearch/README.md, githooks/functions/libyamllint.sh
**Description**
Remove values-production.yaml references, see #5095
=> Remove values-production references in lint, templates, contributing guidelines, etc

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md
In addition to https://github.com/bitnami/charts/pull/4783
=> [bitnami/kafka] Add provisioning values to readme

.gitmodules
This PR includes the submodule https://github.com/bitnami/charts-docs/. This includes all the Kubernetes documentation we use in docs.bitnami.com. 
**Benefits**
Documentation accessible to our users so it can be easily modified.
Need to manually update the submodule at the moment.
- fixes #
**Checklist** 
=> [bitnami/*] Add docs submodule

bitnami/metallb/Chart.lock, bitnami/metallb/Chart.yaml, bitnami/metallb/templates/speaker/secret.yaml, bitnami/metallb/values.yaml
#4831 removed the hook annotations, which broke upgrade compatibility. Hooks will be removed in a future major when `lookup` is stablished as the default behaviour for password management.
**Benefits**
**Checklist** 
=> [bitnami/metallb] Fix hooks for speaker secret

bitnami/redis-cluster/Chart.lock, bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/values.yaml
This change includes the following changes:
- Bump the images to use the ones obtained after the merging of https://github.com/bitnami/bitnami-docker-redis-cluster/pull/20. The referenced PR fixes the cluster creation issues when using Istio sidecars.
- Adds an example about how to configure the job annotaions for Istio.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/redis-cluster] Fix Istio issues

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/statefulset-readreplicas.yaml, bitnami/postgresql/templates/statefulset.yaml
There is a missing character in the parameter `postgresqlTcpKeepalivesCount` in both the statefulsets.
**Benefits**
- fixes #5166
**Checklist** 
=> [bitnami/postgresql] Fix value KeepalivesCount typo

bitnami/kubewatch/Chart.yaml, bitnami/kubewatch/templates/deployment.yaml
This PR adds a missing section in the deployment YAML. It was in the values.yaml but it was not being used.
There is no need to add it in the README.md and the values.yaml because it was already there.
**Benefits**
- fixes https://github.com/bitnami/charts/issues/5155
**Checklist** 
=> [bitnami/kubewatch] Fix missing tolerations

bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md, bitnami/spring-cloud-dataflow/values.yaml
The README.md file was updated with missing values, namely `metrics.resources.limits`, `metrics.resources.requests`. Also `values.yaml` was updated with empty objects.
**Benefits**
Documentation.
_n/a_
- fixes #
**Checklist** 
=> [bitnami/spring-cloud-dataflow] Add metrics resources to README.md

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/README.md, bitnami/nginx-ingress-controller/templates/clusterrole.yaml, bitnami/nginx-ingress-controller/templates/controller-daemonset.yaml, bitnami/nginx-ingress-controller/templates/controller-deployment.yaml, bitnami/nginx-ingress-controller/templates/default-backend-deployment.yaml, bitnami/nginx-ingress-controller/values.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/nginx-ingress-controller] Add hostAlias and Lint

bitnami/metallb/Chart.yaml, bitnami/metallb/README.md, bitnami/metallb/templates/controller/deployment.yaml, bitnami/metallb/templates/controller/rbac.yaml, bitnami/metallb/templates/rbac.yaml, bitnami/metallb/templates/speaker/daemonset.yaml, bitnami/metallb/templates/speaker/rbac.yaml, bitnami/metallb/values.yaml
**Benefits**
None known 
**Checklist** 
=> [bitnami/metallb] Add hostAlias and lint

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/scripts-configmap.yaml
Change the signal of the liveness and readiness check.
**Benefits**
- fixes #5328
**Checklist** 
=> [bitnami/redis-cluster] Fix zombie processes in probes

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/values.yaml
Removed invalid character from values.yaml causing certain parsers to fail.
Changes non-latin7 character from invalid character
**Benefits**
- fixes #5326
**Checklist** 
=> [bitnami/kube-prometheus] Removed invalid character from values.yaml

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/NOTES.txt
- Add check for `auth.admin.token when` upgrade
**Benefits**
- We can upgrade safely
N/A
N/A
N/A
**Checklist**
=> [bitnami/influxdb] fix: add check for auth.admin.token when upgrade

bitnami/grafana-operator/README.md, bitnami/grafana/README.md
Add a section in both readmes explaining the differences between the bitnami/grafana and bitnami/grafana-operator charts.
**Benefits**
Users will properly understand the difference between the two.
- fixes #
**Checklist** 
=> [bitnami/grafana, grafana-operator] Add documentation explaining differences between operator and chart

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/values.yaml
Add comment for ALB ingress controllers in `ingress.path`.
- fixes #4346
**Checklist**
=> [bitnami/rabbitmq] Add comment in ingress.path value

bitnami/metallb/Chart.yaml, bitnami/metallb/templates/speaker/secret.yaml
=> [bitnami/metallb] revert: fix: remove unnecessary hooks

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/metrics-deploy.yaml
Adds `int` to fix comparison issues
**Benefits**
- fixes #5390
**Checklist** 
=> [bitnami/elasticsearch] Fixes elasticsearch metrics error

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/bucketweb/ingress.yaml, bitnami/thanos/templates/query-frontend/ingress.yaml, bitnami/thanos/templates/query/ingress-grpc.yaml, bitnami/thanos/templates/query/ingress.yaml, bitnami/thanos/templates/receive/ingress.yaml
Added `{{ include "common.capabilities.ingress.apiVersion" . }}` instead of hardcoded `extensions/v1beta1`
**Benefits**
The Ingresses of this chart will work in more cluster / work at all.
Hopefully none. Because it is keeping track off in the `bitnami/common` chart.
- fixes #5404 
**Checklist** 
=> [bitnami/thanos] Update ingress.yaml on all components to fix bad ingress behavior.

bitnami/moodle/README.md
Update README to fix issue https://github.com/bitnami/charts/issues/5422 that cause confusion when create Ingress annotation. 
Update README file
**Benefits**
To avoid confusion when create values.yaml.
- fixes #5422
**Checklist** 
=> [bitnami/moodle] Update README.md

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kafka/templates/kafka-metrics-deployment.yaml, bitnami/kafka/templates/log4j-configmap.yaml, bitnami/kafka/templates/statefulset.yaml
This PR fixes some incorrect references in the chart. When we transitioned to the common library, we forgot to fix some references.
**Benefits**
- fixes https://github.com/bitnami/charts/issues/5452
**Checklist** 
=> [bitnami/kafka] Fix incorrect helpers

bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md, bitnami/mongodb/templates/replicaset/statefulset.yaml, bitnami/mongodb/templates/standalone/dep-sts.yaml, bitnami/mongodb/values.yaml
Allow configuring the container port. This required to check the mongodb_exporter parameter 
**Benefits**
- fixes https://github.com/bitnami/charts/issues/5469
**Checklist** 
=> [bitnami/mongodb] Add metrics.containerPort

bitnami/mysql/Chart.yaml, bitnami/mysql/templates/NOTES.txt
remove unnecessary bracket at NOTES.txt
**Benefits**
it will be correct while doing copy-paste on ROOT_PASSWORD command
- fixes #
**Checklist** 
=> [bitnami/mysql] remove unnecessary bracket at NOTES.txt

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/_helpers.tpl
Simple bug fix to the volumePermissions helper in the thanos chart
=> Fix permissions image in thanos

bitnami/mariadb/Chart.yaml, bitnami/mariadb/README.md, bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md
Condensed information and linked to chart documentation on docs.bitnami.com
**Benefits**
Shorter, easier-to-read file
Focus on key information with links to related resources
- fixes #
**Checklist** 
=> [bitnami/wordpress] Improved WordPress and MariaDB READMEs

bitnami/thanos/Chart.yaml, bitnami/thanos/README.md, bitnami/thanos/templates/receive/statefulset.yaml, bitnami/thanos/templates/ruler/statefulset.yaml, bitnami/thanos/values.yaml
It adds support to configurable replica label.
It can already be configured, but only on the query component, this would allow to extend this configuration to the ruler and the receiver.
**Benefits**
Allows for more flexible deduplication labels, instead of forcing every component to use `replica` as the deduplication label
- fixes #
**Checklist** 
=> [bitnami/thanos] Add support to configurable replica label

bitnami/minio/Chart.yaml, bitnami/minio/templates/extra-list.yaml
…minio/templates/ history.
**Benefits**
- fixes #
**Checklist** 
=> Wire documented extraDeploy option in minio chart

bitnami/dataplatform-bp1/Chart.yaml, bitnami/dataplatform-bp1/templates/NOTES.txt, bitnami/dataplatform-bp1/templates/_helpers.tpl
Fix the name in the Chart.yaml that is creating a tarball with the wrong name and the services names in the NOTES.txt.
Not bumping the version on purpose since it has never been released.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/dataplatform-bp1] Fix chart name at Chart.yaml and service names at NOTES.txt

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/query/deployment.yaml
On thanos query component you cannot have duplicated entries, otherwise you get the error:
```
level=error ts=2021-02-16T10:36:17.72044512Z caller=main.go:130 err="Address dnssrv+_grpc._tcp.thanos-receive.monitoring.svc.cluster.local is duplicated for --store flag.\nmain.re
gisterQuery.func1\n\t/app/cmd/thanos/query.go:137\nmain.main\n\t/app/cmd/thanos/main.go:128\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/usr/local/go
/src/runtime/asm_amd64.s:1374\npreparing query command failed\nmain.main\n\t/app/cmd/thanos/main.go:130\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:204\nruntime.goexit\n\t/
usr/local/go/src/runtime/asm_amd64.s:1374
```
The current implementation is not handling the absence of receive component headless …
=> [bitnami/thanos] Fix query receive service discovery

bitnami/metallb/README.md
`livenessProbe.successThreshold` is limited to 1 and cannot be a different value, or an error will be thrown (i.e. see #5537).
References: https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#configure-probes
> `successThreshold`: Minimum consecutive successes for the probe to be considered successful after having failed. Defaults to 1. Must be 1 for liveness and startup Probes. Minimum value is 1.
**Benefits**
- fixes #
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only …
=> [bitnami/metallb] Fix successThreshold reference in README

bitnami/mongodb/Chart.yaml, bitnami/mongodb/values.yaml
Fixed a comment in the `values.yaml` where `rabbitmq.fullname` instead of `mongodb.fullname` was specified, whereas in the `README.md` it was `mongodb.fullname`.
**Benefits**
`README.md` and `values.yaml` are consistent
- fixes #
**Checklist** 
=> [bitname/mongodb] fixed comment in values.yaml

bitnami/memcached/Chart.yaml, bitnami/memcached/README.md, bitnami/memcached/templates/deployment.yaml, bitnami/memcached/templates/extra-list.yaml, bitnami/memcached/templates/secrets.yaml, bitnami/memcached/templates/service.yaml, bitnami/memcached/templates/servicemonitor.yaml, bitnami/memcached/templates/statefulset.yaml, bitnami/memcached/templates/svc-metrics.yaml, bitnami/memcached/values.yaml
This PR add some common parameters missing in this chart such as:
- commonLabels
- commonAnnotations
- extraDeploy
**Benefits**
Flexibility
None
- fixes https://github.com/bitnami/charts/issues/5640
**Checklist**
=> [bitnami/memcached] Add some missing common parameters

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/config/configmap.yaml
**Benefits**
- fixes #4983
**Checklist** 
=> [bitnami/airflow] Add missing parameters to the worker template

.github/workflows/checklist.yml, CHECKLIST.yml
Enable GH Action to show a checklist for reviewers and contributors (it's a first version, I hope we will add more items to the checklist in the future).
Example:
PS: Wording is different in the screenshot, it was just a test
=> Add revision checklist GH action

bitnami/thanos/Chart.yaml, bitnami/thanos/README.md, bitnami/thanos/templates/bucketweb/deployment.yaml, bitnami/thanos/templates/compactor/deployment.yaml, bitnami/thanos/templates/query-frontend/deployment.yaml, bitnami/thanos/templates/query/deployment.yaml, bitnami/thanos/templates/receive/statefulset.yaml, bitnami/thanos/templates/ruler/statefulset.yaml, bitnami/thanos/templates/storegateway/statefulset.yaml, bitnami/thanos/values.yaml
Adds PodLabels to thanos pods.
None known
- fixes #5695
Manual test setting `query.podLabels`:
```yml
#helm template bitnami/thanos
---
apiVersion: apps/v1
kind: Deployment
metadata:
name: RELEASE-NAME-thanos-query
labels:
app.kubernetes.io/name: thanos
helm.sh/chart: thanos-3.12.0
app.kubernetes.io/instance: RELEASE-NAME
app.kubernetes.io/component: query
spec:
replicas: 1
strategy:
type: RollingUpdate
selector:
matchLabels:
app.kubernetes.io/name: thanos
app.kubernetes.io/instance: RELEASE-NAME
app.kubernetes.io/component: query
template:
metadata:
labels:
app.kubernetes.io/name: thanos
helm.sh/chart: thanos-3.12.0
app.kubernetes.io/instance: …
```
=> [bitnami/thanos] Add PodLabels

bitnami/memcached/Chart.yaml, bitnami/memcached/README.md, bitnami/memcached/templates/deployment.yaml, bitnami/memcached/templates/statefulset.yaml, bitnami/memcached/values.yaml
Add podLabels
**Benefits**
- fixes #5716
**Checklist** 
=> [bitnami/memcached] Add podLabels

bitnami/thanos/Chart.yaml, bitnami/thanos/README.md, bitnami/thanos/templates/bucketweb/deployment.yaml, bitnami/thanos/templates/compactor/deployment.yaml, bitnami/thanos/templates/query-frontend/deployment.yaml, bitnami/thanos/templates/query/deployment.yaml, bitnami/thanos/templates/receive/statefulset.yaml, bitnami/thanos/templates/ruler/statefulset.yaml, bitnami/thanos/templates/storegateway/statefulset.yaml, bitnami/thanos/values.yaml
Current Thanos chart does not allow users to set log format: the default `logfmt` format is implicitly used by Thanos.
This Pull Request introduce a set of Helm values to do so in each Thanos component: using `logfmt` as default to prevent any change in behaviour for users that don't want to change this format.
**Benefits**
This change allows users to set a different format for Thanos logs: especially JSON format comes to mind.
No drawback identified.
No issue currently opened related to this change.
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps …
=> [bitnami/thanos] introduce logFormat in Thanos components

bitnami/redis/values.yaml
Typo
I don't bump the version because this fix is not really important.
=> [bitnami/redis]: typo

bitnami/mariadb-galera/Chart.yaml, bitnami/mariadb-galera/templates/NOTES.txt
Fixed _NOTE.txt_ which prints to CLI.
**Benefits**
Fixing the namespace scope of the rootUser password secret. 
**Checklist**
=> [bitnami/mariadb-galera] Fixed namespace for secret

bitnami/minio/Chart.yaml, bitnami/minio/README.md
Change name of MinIO in Chart.yaml description
**Checklist** 
=> [bitnami/minio] Update minio name

bitnami/external-dns/Chart.yaml, bitnami/external-dns/templates/deployment.yaml
When using Alibaba cloud, if there is no 'alibaba-cloud-config-file' option, it will use 'alibaba-cloud-config-file=/etc/kubernetes/alibaba-cloud.json' . If IAM authentication is used, the service cannot be started
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/external-dns]fix: update alibaba config

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/configmap.yaml
This PR fixes a rendering issue in the keycloak/templates/configmap.yaml as also discussed in #5074.
**BUG**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: test-keycloak-configurationnamespace: default
labels:
app.kubernetes.io/name: keycloak
helm.sh/chart: keycloak-2.4.0
app.kubernetes.io/instance: test
app.kubernetes.io/component: keycloak
data:
standalone-ha.xml: |-
<?xml version='1.0' encoding='UTF-8'?>
```
**SOLUTION**
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
name: test-keycloak-configuration
namespace: default
labels:
app.kubernetes.io/name: keycloak
helm.sh/chart: keycloak-2.4.0
app.kubernetes.io/instance: test
app.kubernetes.io/component: keycloak
data: …
```
=> [bitnami/keycloak] Fix config map template bug

bitnami/wavefront/Chart.yaml, bitnami/wavefront/README.md, bitnami/wavefront/templates/collector-daemonset.yaml, bitnami/wavefront/templates/collector-deployment.yaml
As part of the process of moving the wavefront image to be scratch this PR adds the needed changes to find the executable inside the scratch container. We are bumping the minor version in order to not use just a patch for this change.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/wavefront] Move collector image to scratch

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md
Fixes https://github.com/bitnami/bitnami-docker-kafka/issues/150
=> [bitnami/kafka] Fix typo in Kafka connect example

bitnami/mongodb/Chart.yaml, bitnami/mongodb/values.yaml
This bumps the version of the image used by the chart to include the latest changes in the image.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/mongodb] Bumps mongodb image version used by the chart

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/core/core-cm-envvars.yaml, bitnami/harbor/templates/core/core-dpl.yaml
Implements https://github.com/goharbor/harbor-helm/commit/685108220c8efab3f2748e16528480282f662e8f into the `bitnami/harbor` chart.
**Benefits**
`uaaSecretName` works.
None.
- fixes #5894
**Checklist** 
=> [bitnami/harbor] Fix usage of uaaSecretName option

bitnami/metrics-server/Chart.yaml, bitnami/metrics-server/templates/metrics-api-service.yaml
Changes de api version for `apiregistration.k8s.io` depending on the kubernetes version.
**Benefits**
- fixes #5906
**Checklist** 
=> [bitnami/metrics-server] Use different api version depending on the kubernetes version

bitnami/redmine/Chart.yaml, bitnami/redmine/README.md
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/redmine] Add info on how to run redmine with multiple replicas to Readme

bitnami/redis/Chart.yaml, bitnami/redis/values.yaml
Fix issue described in #5954 about the default value used for the `priorityClassName`.
- fixes #5954
**Checklist**
=> [bitnami/redis] Fix priorityClassName

bitnami/metrics-server/Chart.yaml, bitnami/metrics-server/templates/metrics-api-service.yaml
Revert PR #5968
**Benefits**
- fixes #5906 
**Checklist** 
=> [bitnami/chart] Revert PR 5968

bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md
Compressed README, added links to Bitnami docs website
**Benefits**
- fixes #
This PR should not be merged until https://github.com/bitnami/charts-docs/pull/16/ is approved and those changes deployed and live.
**Checklist** 
- [ x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [x ] Title of the PR starts with chart name (e.g. `[bitnami/chart]`)
=> [bitnami/mongodb] Improved README

bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md, bitnami/mongodb/templates/replicaset/statefulset.yaml, bitnami/mongodb/templates/standalone/dep-sts.yaml, bitnami/mongodb/values.yaml
Add a startupProbe, so that a slow starting container gets enough time to initialize without getting killed.
**Benefits**
Slow starting containers are often killed by the readiness and liveness probes before they've gotten a chance to fully initialize. Startup probes mitigate that.
Available only from Kubernetes 1.16 onwards
- fixes #4979 
**Checklist** 
=> [bitnami/mongodb] Add startup probe

bitnami/redmine/Chart.yaml, bitnami/redmine/templates/cronjob.yaml
=> [bitnami/redmine] fix indent in cronjob.yml

bitnami/apache/Chart.yaml, bitnami/apache/README.md, bitnami/apache/templates/configmap-vhosts.yaml, bitnami/apache/templates/configmap.yaml, bitnami/apache/templates/deployment.yaml, bitnami/apache/templates/ingress.yaml, bitnami/apache/templates/svc.yaml, bitnami/apache/values.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/apache] port commonLabels, commonAnnotations & podLabels from other charts

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/_helpers.tpl
Fixes a bug with https://github.com/bitnami/charts/pull/5844.
**Benefits**
Bugfix
- fixes #5844 
**Checklist** 
=> [bitnami/keycloak] Fix error on missing credentials

bitnami/memcached/Chart.yaml, bitnami/memcached/README.md, bitnami/memcached/templates/serviceaccount.yaml, bitnami/memcached/values.yaml
* Adds value to specify whether the service account token should be auto
mounted to pods
* Increments chart version from 5.8.1 to 5.9.0
**Benefits**
* Improves security posture
N/A
N/A
N/A
**Checklist** 
=> [bitnami/memcached] SA automount token values

bitnami/airflow/Chart.yaml, bitnami/airflow/README.md, bitnami/airflow/values.yaml
The name of that setting is wrong in README and comment in `values.yaml`.
Fix it to reflect reality.
**Checklist**
=> [bitnami/airflow] Fix comment and README to reflect LocalExecutor config: Local Executor -> LocalExecutor

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/config/configmap.yaml
Fix the workers when using Kubernetes executor.
**Benefits**
- fixes https://github.com/bitnami/bitnami-docker-airflow/issues/75
**Checklist** 
=> [bitnami/airflow] Fix worker

bitnami/dataplatform-bp2/Chart.yaml, bitnami/dataplatform-bp2/values.yaml, bitnami/wavefront-adapter-for-istio/Chart.yaml, bitnami/wavefront-adapter-for-istio/values.yaml, bitnami/wavefront-prometheus-storage-adapter/Chart.yaml, bitnami/wavefront-prometheus-storage-adapter/values.yaml, bitnami/wordpress/Chart.yaml, bitnami/wordpress/values.yaml
Standardise `values.yaml` that uses readmenator to the format supported by our internal automations
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/*] Fix values.yaml for internal automations

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/_git_helpers.tpl
We encountered this error:
```
$ kubectl get pod
airflow-postgresql-0                      1/1     Running            0          32h
airflow-redis-master-0                    1/1     Running            0          32h
airflow-scheduler-6c4bd6775c-7c7m4        2/2     Running            4          32h
airflow-web-67cf848d67-zmkh6              2/2     Running            42         32h
airflow-worker-0                          1/2     CrashLoopBackOff   328        29h
airflow-worker-1                          2/2     Running            28         29h
```
The log shows:
```
$ kubectl logs  -f airflow-worker-0 -c sync-repositories
From https://github.com/username/repo
* branch            master     -> FETCH_HEAD
Already up to date.
fatal: unable to access …
```
=> [bitnami/chart] Avoid crash when clone/sync git repository

bitnami/redis-cluster/README.md
**Benefits**
- fixes #
**Checklist** 
=> fix wording

bitnami/postgresql-ha/Chart.yaml
Increases the version for #6073
**Checklist**
=> [bitnami/postgresql-ha] Increase version for #6073

bitnami/tomcat/Chart.yaml, bitnami/tomcat/README.md, bitnami/tomcat/templates/deployment.yaml, bitnami/tomcat/values.yaml
**Benefits**
- Add the possibility to define extra ports listened by tomcat
- fixes #
**Checklist** 
=> [bitnami/tomcat] add containerExtraPorts

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/README.md
Migrated examples to docs.bitnami.com and added links.
**Benefits**
Reduced length of README.
- fixes #
This PR should not be merged until https://github.com/bitnami/charts-docs/pull/26 is approved and those changes live on docs.bitnami.com, to ensure added links work correctly.
**Checklist** 
=> [bitnami/rabbitmq] Improved RabbitMQ README

bitnami/phpbb/Chart.yaml, bitnami/phpbb/templates/deployment.yaml
Signed-off-by: André Bauer <monotek23@gmail.com>
* fixes init container usage (wrong var name core.initContainers instead of initContainers was used)
**Benefits**
- fixes #
**Checklist** 
=> [phpbb] fix initcontainer usage

bitnami/cassandra/Chart.yaml, bitnami/cassandra/README.md, bitnami/etcd/Chart.yaml, bitnami/etcd/README.md, bitnami/mariadb/Chart.yaml, bitnami/mariadb/README.md, bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md, bitnami/mysql/Chart.yaml, bitnami/mysql/README.md, bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md
Updates links to docs.bitnami.com
**Benefits**
Avoids broken links
- fixes #
This PR should not be merged until bitnami/charts-docs#25 is approved and those changes live on docs.bitnami.com
**Checklist** 
=> Updated links to common sections in multiple READMEs

bitnami/odoo/Chart.yaml, bitnami/odoo/templates/deployment.yaml
field "extraEnvVars" in values file doesn't match deployment's
**Benefits**
fix bugs
- fixes #
**Checklist** 
=> [bitnami/odoo] fix odoo bug

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/metrics/deployment.yaml
Make Airflow Exporter respect the tolerations settings. Currently it is declared in values but it was not implemented in the deployment template for airflow exporter. They are also present in the docs, but not used -.-
**Benefits**
Airflow Exporter respect the tolerations settings and end users can use it in their setups. 
None.
- fixes #
**Checklist** 
=> [bitnami/airflow] Fix tolerations for Airflow Exporter

bitnami/memcached/Chart.yaml, bitnami/memcached/templates/statefulset.yaml
* Service account was only being set for the deployment, but this should
also be set for the statefulset as well
* Increment chart version from 5.10.0 to 5.10.1
**Benefits**
* Allows service account funcitonality to apply towards statefulsets as well
N/A
N/A
N/A
**Checklist** 
=> [bitnami/memcached] Use SA for statefulset pods

bitnami/keycloak/README.md
3 block of code had escapes that prevented them from rendering as code blocks
**Benefits**
Easier to read the readme
The escapes could have been there for a reason I cannot see.
- fixes #
**Checklist** 
=> [bitnami/keycloak] Update README.md

bitnami/mediawiki/Chart.yaml, bitnami/mediawiki/templates/extra-list.yaml
Include extra-list.yaml to the templates to render the `extraDeploy` value
- fixes #6139
**Checklist**
=> Include extra-list.yaml to render extraDeploy values

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/README.md
Compresses the README information by providing links to more information on docs.bitnami.com
**Benefits**
- fixes #
This PR should not be merged until https://github.com/bitnami/charts-docs/pull/30 is approved and merged AND the corresponding changes are live on docs.bitnami.com
**Checklist** 
=> [bitnami/zookeeper] Updated Zookeeper README

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/values.yaml
Change the location of documentation of Istio 
**Benefits**
- fixes #6151
**Checklist** 
=> [bitnami/redis-cluster] the istio annotation goes in podAnnotations

bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md
Fixes broken link in README
**Benefits**
- fixes #6162 
**Checklist** 
=> [bitnami/wordpress] Fixed broken link

bitnami/wildfly/Chart.yaml, bitnami/wildfly/README.md, bitnami/wildfly/templates/deployment.yaml, bitnami/wildfly/templates/ingress.yaml, bitnami/wildfly/templates/pvc.yaml, bitnami/wildfly/templates/secrets.yaml, bitnami/wildfly/templates/svc.yaml, bitnami/wildfly/templates/tls-secrets.yaml, bitnami/wildfly/values.yaml
This PR bumps the major version due to imminent changes in the WildFly container image.
The values.yaml metadata has been also adapated to follow the format supported by [readmenator](https://github.com/bitnami-labs/readmenator) to automatically generate the READMEs' tables based on the metadata.
**Benefits**
- Standardization
- Remove tech debt
None
None
**Checklist**
=> [bitnami/wildfly] New major version

bitnami/minio/Chart.yaml, bitnami/minio/templates/gateway/deployment.yaml
**Benefits**
- fixes #https://github.com/bitnami/charts/issues/6188
**Checklist** 
=> [bitnami/minio] Fix syntax error in template

bitnami/tomcat/Chart.yaml, bitnami/tomcat/README.md, bitnami/tomcat/templates/_pod.tpl, bitnami/tomcat/templates/statefulset.yaml, bitnami/tomcat/values.yaml
**Benefits**
- fixes #6134 
**Checklist** 
=> [bitnami/tomcat] fix indent & improve volume claim in sts

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/templates/hub/service-account.yaml, bitnami/jupyterhub/templates/singleuser/service-account.yaml
Removes imagePullSecrets that are not compatible with TKG and IKS.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/jupyterhub] Removes imagePullSecrets

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/templates/image-puller/daemonset.yaml
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/jupyterhub] Fix for TKG

bitnami/wordpress/Chart.yaml, bitnami/wordpress/values.yaml
**Benefits**
- fixes #6215
**Checklist** 
=> [bitnami/wordpress] Fix wrong comment

bitnami/kafka/README.md
SASL Parameters updated in the readme file
**Checklist**
=> [bitnami/kafka] SASL parameters updated

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/update-cluster.yaml
This PR improves the resiliency of the script by recalculating the IP in every loop. This would avoid infinite loops when a node crashes.
**Benefits**
- fixes https://github.com/bitnami/charts/issues/3743
**Checklist** 
=> [bitnami/redis-cluster] Improve resiliency of the update script

bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md, bitnami/kiam/Chart.yaml, bitnami/kiam/README.md, bitnami/kubewatch/Chart.yaml, bitnami/kubewatch/README.md, bitnami/mariadb/Chart.yaml, bitnami/mariadb/README.md, bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md, bitnami/mysql/Chart.yaml, bitnami/mysql/README.md, bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/README.md, bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/README.md, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md
Fix typos in several README files.
**Benefits**
**Checklist** 
=> Fix typos in several README files

bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md, bitnami/mongodb/templates/hidden/statefulset.yaml, bitnami/mongodb/templates/replicaset/statefulset.yaml, bitnami/mongodb/values.yaml
This PR adds dataSource to mongodb volumeClaimTemplates. Supports both replicaset nodes and hidden nodes.
**Benefits**
- fixes https://github.com/bitnami/charts/issues/6092
**Checklist** 
=> [bitnami/mongodb] Add dataSource

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/values.yaml
This is a small change to set commonLabels and commonAnnotations to be tables.
**Benefits**
Changing `commonLabels:` to `commonLabels: {}` allows the base values file to be extended with a table. The issue is described here: https://github.com/helm/helm/issues/8283
none known
none known
This is already correct in https://github.com/bitnami/charts/blob/master/bitnami/redis/values.yaml#L35, not sure why redis-cluster is set differently
**Checklist** 
=> [bitnami/redis-cluster] change parameters to tables

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/ingress.yaml
Fixing the issue https://github.com/bitnami/charts/issues/6299
=> [bitnami/keycloak] Update ingress.yaml to support optional hostname

bitnami/external-dns/Chart.yaml, bitnami/external-dns/README.md, bitnami/external-dns/templates/crd.yaml
Update CRD API version
**Benefits**
- fixes #4723
**Checklist** 
=> [bitnami/external-dns] Update CRDs api version

template/CHART_NAME/templates/clusterrolebinding.yaml, template/CHART_NAME/templates/configmap.yaml, template/CHART_NAME/templates/daemonset.yaml, template/CHART_NAME/templates/deployment.yaml, template/CHART_NAME/templates/secret.yaml, template/CHART_NAME/templates/service-account.yaml, template/CHART_NAME/templates/service.yaml, template/CHART_NAME/templates/statefulset.yaml, template/CHART_NAME/values.yaml
This PR adapts the template so it follow the new format for values.yaml compatible with readmenator.
**Benefits**
Remove tech debt.
None
None
It also ensure every manifest defines the namespaces.
**Checklist** 
N/A
=> Template - Adapt values to new format

bitnami/mariadb-galera/Chart.yaml, bitnami/mariadb-galera/templates/statefulset.yaml
…he configmap
I bumped the minor version since even if the parameters have not changed the behaviour of the upgrade will change.
This PR allows upgrading the pods after modifying the config map.
**Benefits**
- fixes #3671
**Checklist** 
=> [bitnami/mariadb-galera] Add checksum to update pods when the configmap is updated

bitnami/kube-prometheus/Chart.lock, bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/README.md, bitnami/wavefront/Chart.lock, bitnami/wavefront/Chart.yaml, bitnami/wavefront/README.md
The `kube-state-metrics` chart was updated to a new major in #6231. This PR updates the charts that use it as subchart, `kube-prometheus` and `wavefront`, to use the new `kube-state-metrics` major. This means bumping these two charts to a new major as well.
**Benefits**
- fixes #
**Checklist** 
=> [bitnami/*] Update kube-state-metrics used as subchart to newest major

bitnami/dataplatform-bp1/Chart.yaml, bitnami/dataplatform-bp1/README.md, bitnami/dataplatform-bp1/values.yaml, bitnami/dataplatform-bp2/Chart.yaml, bitnami/dataplatform-bp2/README.md, bitnami/dataplatform-bp2/values.yaml
The pod affinity and anti affinity rules were updated for bitnami/dataplatform-bp1 , bitnami/dataplatform-bp2 charts because when we have two deployments from both the blueprints on the same cluster the affinity rules would conflict each other, as two blueprints have some pods in common. To overcome this extra set of affinity rules were added on the release name for both the blueprints.  
**Benefits**
Two blueprints can be added on the same cluster and namespace without conflicts if provided with the sufficient resources.
- fixes #
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps …
=> bitnami/dataplatform-bp1 and bitnami/dataplatform-bp2 charts updated with extra set of affinity rules.

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/README.md
Compressed and migrated information from the README
**Benefits**
Smaller and more compact README
- fixes #
This PR should not be merged until https://github.com/bitnami/charts-docs/pull/32 is landed and the corresponding links live on docs.bitnami.com
**Checklist** 
=> [bitnami/jupyterhub] Updated README

bitnami/external-dns/values.yaml
Updates documentation in values.yaml file to accurately reflect all 3 valid policy values.
**Benefits**
Documentation is more accurate.
Is version bump required for this change?
**Checklist**
=> [bitnami/external-dns] values.yaml docs missing policy

bitnami/osclass/Chart.lock, bitnami/osclass/Chart.yaml, bitnami/osclass/README.md, bitnami/osclass/templates/NOTES.txt, bitnami/osclass/templates/_helpers.tpl, bitnami/osclass/templates/deployment.yaml, bitnami/osclass/templates/externaldb-secrets.yaml, bitnami/osclass/templates/hpa.yaml, bitnami/osclass/templates/ingress.yaml, bitnami/osclass/templates/metrics-svc.yaml, bitnami/osclass/templates/osclass-pvc.yaml, bitnami/osclass/templates/pdb.yaml, bitnami/osclass/templates/secrets.yaml, bitnami/osclass/templates/servicemonitor.yaml, bitnami/osclass/templates/svc.yaml, bitnami/osclass/templates/tls-secrets.yaml, bitnami/osclass/values.yaml
This PR bumps Osclass major version since its dependency since the container was moved to root and bash. It also includes several standardizations from other charts.
**Benefits**
**Benefits**
Issues when upgrading 
- fixes #
**Checklist**
=> [bitnami/osclass] MAJOR: Move the container to non-root and bash

bitnami/redis/README.md
Shorten the sections that are already migrated to the BDS and add links to the chart documentation in docs.bitnami.com
**Benefits**
Make the README file shorter and redirect users to a single point for documentation
Some sections have new content and need migration:
- Enable metrics
-  Cluster topologies
See https://phabricator.nami.run/T40074
Check https://docs.bitnami.com/kubernetes/infrastructure/redis/
**Checklist** 
:warning: Keep in mind that if you want to make changes to the kubeapps chart, please implement them in the [kubeapps repository](https://github.com/kubeapps/kubeapps/tree/master/chart/kubeapps). This is only a synchronized …
=> Update README to refer chart documentation

bitnami/wavefront/Chart.yaml, bitnami/wavefront/README.md, bitnami/wavefront/templates/proxy-deployment.yaml, bitnami/wavefront/values.yaml
Updates Wavefront chart adding upstream features.
- https://github.com/wavefrontHQ/helm/commit/a6d792ce7fd1ddef6e446ce39931e82fc46a433e
- https://github.com/wavefrontHQ/helm/commit/17f1b95dfbabb52d2a29b47e528226e564e864bc
- https://github.com/wavefrontHQ/helm/commit/dbed3541015c24ae12704ef37754a2fbd8c16d1b
None known.
**Checklist**
=> [bitnami/wavefront] Update chart with upstream commits

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/templates/_helpers.tpl, bitnami/jupyterhub/values.yaml
Fix the storageClass setting, which was incorrectly set to storageClassName.
**Benefits**
- fixes https://github.com/bitnami/charts/pull/6205#issuecomment-842607060
**Checklist**
=> [bitnami/jupyterhub] Fix singleuser storage class

bitnami/dataplatform-bp1/Chart.lock, bitnami/dataplatform-bp1/Chart.yaml, bitnami/dataplatform-bp1/README.md, bitnami/dataplatform-bp2/Chart.lock, bitnami/dataplatform-bp2/Chart.yaml, bitnami/dataplatform-bp2/README.md, bitnami/kube-prometheus/README.md, bitnami/wavefront-adapter-for-istio/Chart.lock, bitnami/wavefront-adapter-for-istio/Chart.yaml, bitnami/wavefront-adapter-for-istio/README.md, bitnami/wavefront-prometheus-storage-adapter/Chart.lock, bitnami/wavefront-prometheus-storage-adapter/Chart.yaml, bitnami/wavefront-prometheus-storage-adapter/README.md, bitnami/wavefront/README.md
The `wavefront` chart was updated to a new major in #6324. This PR updates the charts that use it as subchart to use the new `wavefront` major. This means bumping the following 4 charts to a new major as well:
- dataplatform-bp1
- dataplatform-bp2
- wavefront-adapter-for-istio
- wavefront-prometheus-storage-adapter
Updated the READMEs of `kube-prometheus` and `wavefront` to fix a typo.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/*] Update wavefront used as subchart to newest major

bitnami/kafka/Chart.yaml, bitnami/kafka/values.yaml, bitnami/mongodb/Chart.yaml, bitnami/mongodb/values.yaml, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/values.yaml
Updates kubectl container's version used in several of bitnami/charts to version `1.19` given the upcoming kubectl deprecation of branches `1.16-18` per [it's deprecation notice](https://github.com/bitnami/bitnami-docker-kubectl#branch-deprecation-notice).
**Benefits**
- fixes #
**Checklist**
=> [bitnami/*] Update Kubectl container version

bitnami/common/Chart.yaml, bitnami/common/templates/_ingress.tpl
When using helmfile types other than int endup in backend config , 
```
backend:
-               serviceName: event-listener
-               servicePort: app
+               service:
+                 name: app
+                 port:
+                   number: 63032
+             # 63032
+             # float64
```
**Benefits**
- fixes #
**Checklist**
=> [bitnami/common] Update _ingress.tpl

bitnami/minio/Chart.yaml, bitnami/minio/templates/NOTES.txt
Do not throw an error upgrading when a gateway is set for missing keys
**Benefits**
- fixes #6456
**Checklist**
=> [bitnami/minio] Fix passwords checks

bitnami/redis/README.md, template/CHART_NAME/README.md
Update old references to the new repo name
**Benefits**
- fixes #
=> Update templates for readme generator

bitnami/dataplatform-bp1/Chart.yaml, bitnami/dataplatform-bp1/README.md, bitnami/dataplatform-bp1/values.yaml
…al techs stacks
The prefixes for the metrics emitted were changed to have them in sync with individual dashboards of Kafka Spark and Solr on Tanzu Observability platform. 
**Benefits**
Individual Dashboard on wavefront will be lit up and users can use those dashboards once TO platfroms have prometheus exporter dashboards for each tech stack.
- fixes #
**Checklist**
=> bitnami/dataplatform-bp1  metric prefixes were updated to keep in sync with TO platfrom

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/ruler/statefulset.yaml
When a previously created configmap for the rules, it's difficult to debug with just one (huge) rule file.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/thanos] use multiple rules files

bitnami/mysql/Chart.yaml, bitnami/mysql/README.md, bitnami/mysql/templates/primary/statefulset.yaml, bitnami/mysql/templates/secondary/statefulset.yaml, bitnami/mysql/values.yaml
Signed-off-by: Youssef El Houti <youssef.elhouti@gmail.com>
**Benefits**
- fixes #6444
**Checklist**
=> [bitnami/mysql] add startupProb

bitnami/discourse/Chart.lock, bitnami/discourse/Chart.yaml, bitnami/discourse/README.md, bitnami/discourse/templates/configmaps.yaml, bitnami/discourse/templates/deployment.yaml, bitnami/discourse/values.yaml
Update chart to be compatible with new refactored Bitnami Discourse container image
**Benefits**
Users can enjoy an improved container image :)
Upgrades are not guaranteed to work
- fixes #
**Checklist**
=> [bitnami/discourse] MAJOR: Discourse image refactor

bitnami/redis/Chart.yaml, bitnami/redis/templates/master/statefulset.yaml, bitnami/redis/templates/replicas/statefulset.yaml, bitnami/redis/templates/sentinel/statefulset.yaml
Start using `.Values.tls.certificatesSecret` as a template.
**Benefits**
- fixes #6583
**Checklist**
=> [bitnami/redis] use `.Values.tls.certificatesSecret` as a template

bitnami/solr/Chart.yaml, bitnami/solr/README.md
Reduced examples, added links to docs.bitnami.com, made titles consistent
**Benefits**
- fixes #
**Checklist**
=> [bitnami/solr] Updated Solr README

bitnami/discourse/Chart.yaml, bitnami/discourse/templates/configmaps.yaml
External DB usage does not work since of chart version 4.0.0 if the external user is not created before deploying. With this change, the logic will try and create the user if it doesn't exist already.
**Benefits**
External DB support is working
None
- fixes #6606
**Checklist**
=> [bitnami/discourse] Fix external DB support

bitnami/mysql/Chart.yaml, bitnami/mysql/templates/primary/svc-headless.yaml, bitnami/mysql/templates/secondary/svc-headless.yaml
Remove the service-specific primary and seconday annotations from the
headless Service resources used by the StatefulSets. This retains the
common annotations.
This allows for use of things like external-dns on the primary and
secondary Service resources. Fixes #6576
Signed-off-by: Chris Gianelloni <cgianelloni@applause.com>
**Benefits**
- fixes #
**Checklist**
=> [bitnami/mysql] Remove annotations from headless services

bitnami/spark/Chart.yaml, bitnami/spark/README.md
Compressed content, added links to docs.bitnami.com, performed copy edit on text
**Benefits**
- fixes #
This PR should not be merged until https://github.com/bitnami/charts-docs/pull/45/ is merged and the links active on docs.bitnami.com
**Checklist**
=> [bitnami/spark] Updated Spark README

bitnami/redmine/Chart.yaml, bitnami/redmine/templates/mail-receiver-configmap.yaml
Fix mail protocol
Fix error `Unsupported mail receive protocol. Exiting` if POP3 configured.
**Benefits**
Mail receiver cron works with pop3
- fixes #
**Checklist**
=> [bitnami/redmine] Update mail-receiver-configmap.yaml

bitnami/dataplatform-bp2/Chart.lock, bitnami/dataplatform-bp2/Chart.yaml
Update dependencies with `helm repo update && helm dep update`
Related to #6653
=> [bitnami/dataplatform-bp2] Update dependencies

bitnami/common/Chart.yaml, bitnami/common/README.md, bitnami/common/templates/_capabilities.tpl
Fixes #6648 .
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
**Checklist**
=> bitnami/common: add version detection for policy api

bitnami/prestashop/Chart.yaml, bitnami/prestashop/templates/pv.yaml, bitnami/prestashop/templates/pvc.yaml
In platforms like TKG, helm install --wait does not work because of this
```
agent@ip-10-10-89-22:~/workspace/Releases/chart-package/prestashop/1.7/debian-10/86$ helm install test12 charts/bitnami/prestashop --debug --wait
WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: kubeconfig-tkg
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: kubeconfig-tkg
install.go:172: [debug] Original chart version: ""
install.go:189: [debug] CHART PATH: /home/agent/workspace/Releases/chart-package/prestashop/1.7/debian-10/86/charts/bitnami/prestashop
client.go:109: [debug] creating 8 resource(s)
wait.go:53: [debug] beginning wait for 8 resources with timeout of 5m0s
wait.go:216: [debug] …
```
=> [bitnami/prestashop] Fix issue with --wait

bitnami/thanos/Chart.yaml, bitnami/thanos/README.md
Fix typo on receive component parameter documentation for `bitnami/thanos` chart README
**Benefits**
Correct documentation
None
None
None
**Checklist**
=> [bitnami/thanos] fix typo on receive component parameter documentation

bitnami/magento/Chart.lock, bitnami/magento/Chart.yaml
Update the chart dependencies.
**Benefits**
Use latest available features
None
N/A
N/A
**Checklist**
=> [bitnami/magento] Update deps

bitnami/mongodb/Chart.yaml, bitnami/mongodb/values.yaml
**Benefits**
- fixes #
**Checklist**
=> [bitnami/mongodb] Indentation fix to extraDeploy section when un-commenting

bitnami/dataplatform-bp1/Chart.lock, bitnami/dataplatform-bp1/Chart.yaml, bitnami/dataplatform-bp1/README.md, bitnami/kafka/Chart.lock, bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/solr/Chart.lock, bitnami/solr/Chart.yaml, bitnami/solr/README.md
Update charts including Zookeeper as a dependency.
The following charts have been updated with a major version:
- Kafka
- Solr
- Data Platform Blueprint 1 with Kafka-Spark-Solr
**Checklist**
=> [bitnami/*] Update zookeeper deps

bitnami/thanos/Chart.lock, bitnami/thanos/Chart.yaml, bitnami/thanos/README.md
Update Thanos' MinIO dependency to its latest major.
**Checklist**
=> [bitnami/thanos] Update Thanos' MinIO dependency to its latest major

bitnami/minio/README.md
This prerequisite is only needed in gateway mode
=> [bitnami/minio] Update prerequisites

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/influxdb/deployment-standalone.yaml
Add `commonLabels` to the pod spec.
- fixes #6750
**Checklist**
=> [bitnami/influxdb] Add commonLabels to pod spec

bitnami/jenkins/Chart.yaml, bitnami/jenkins/README.md
Modified README, updated links
**Benefits**
- fixes #
**Checklist**
=> [bitnami/jenkins] Updated README

bitnami/wavefront/Chart.yaml, bitnami/wavefront/README.md
Updated README, added links to docs.bitnami.com
**Benefits**
- fixes #
This PR should not be merged until https://github.com/bitnami/charts-docs/pull/47 is landed to avoid broken links.
**Checklist**
=> [bitnami/wavefront] Updated README

bitnami/common/Chart.yaml, bitnami/common/README.md, bitnami/common/templates/_ingress.tpl
=> [bitnami/common] Add supportIngressClassname

template/CHART_NAME/README.md, template/CHART_NAME/templates/ingress.yaml, template/CHART_NAME/templates/tls-secret.yaml, template/CHART_NAME/values.yaml
This PR adds the skeleton for the ingress and TLS secrets manifests to the chart template.
**Benefits**
Updated template
None
None
N/A
**Checklist** 
N/A
=> Template: Add ingress resources

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/influxdb/cronjob-backup.yaml
Fix indentation problems in the cronjob template
- fixes #6802
**Checklist**
=> [bitnami/influxdb] Fix indentation problems generating backup cronjob

bitnami/redis/Chart.yaml, bitnami/redis/values.schema.json
Simple add enum `Redis architecture` to `values.schema.json`.
**Benefits**
User can choose `Redis architecture` from list
- fixes #
**Checklist**
=> values.schema: add enum to json file

bitnami/mysql/Chart.yaml, bitnami/mysql/values.schema.json
add values.schema.json for mysql chart
**Benefits**
user can choose parameters base from values.schema.json
- fixes #
**Checklist**
=> bitnami/mysql: add values.schema.json check

bitnami/minio/README.md
PR to update the disclaimer information. Requested by the MinIO team.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/minio] Update Disclaimer of the MinIO chart

.github/workflows/lint-test.yaml
Upgrade `kind-action` and `chart-testing-action` to their latest versions. This should fix the issues we are having with the `test` job.
=> Upgrade action versions

bitnami/mongodb/Chart.lock, bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/replicaset/external-access-svc.yaml
Fixed issue with `commonLabels` when external access is enabled
**Benefits**
None
- fixes #6857
**Checklist**
=> [bitnami/mongodb] fixed commonLabels for external access

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/web/deployment.yaml
Fix ldap with tls
**Benefits**
- fixes #6082
**Checklist**
=> [bitnami/airflow] fix values of AIRFLOW_LDAP_USE_TLS

bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md
Compressed README and moved information to docs.bitnami.com
**Benefits**
- fixes #
Do not merge this until https://github.com/bitnami/charts-docs/pull/52 is merged and public.
**Checklist**
=> [bitnami/keycloak] Improved README

bitnami/dokuwiki/Chart.yaml, bitnami/dokuwiki/README.md, bitnami/dokuwiki/templates/deployment.yaml, bitnami/dokuwiki/templates/dokuwiki-pvc.yaml, bitnami/dokuwiki/values.yaml
Adds support for `persistence.existingClaim`.
**Benefits**
Adds additional feature supported by other charts.
None known.
- fixes #6891
**Checklist**
=> [bitnami/dokuwiki] Add support for persistence.existingClaim

bitnami/kubeapps/README.md
Update Kubeapps chart to be aligned with the information available in Kubeapps repo
**Benefits**
Up to date information for Kubeapps chart
N/A
N/A
N/A
**Checklist**
=> [bitnami/kubeapps] Update Kubeapps overview

bitnami/kiam/Chart.yaml, bitnami/kiam/README.md
Updated README with links to docs.bitnami.com, performed general copy edit
**Benefits**
- fixes #
**Checklist**
=> [bitnami/kiam] Updated README

bitnami/grafana/Chart.yaml, bitnami/grafana/README.md, bitnami/grafana/templates/image-renderer-deployment.yaml, bitnami/grafana/values.yaml
Adds resources section to image renderer.
**Benefits**
- fixes #6923
**Checklist**
=> [bitnami/grafana] add missing resources on image renderer

bitnami/dataplatform-bp1/Chart.lock, bitnami/dataplatform-bp1/Chart.yaml, bitnami/dataplatform-bp1/README.md, bitnami/dataplatform-bp2/Chart.lock, bitnami/dataplatform-bp2/Chart.yaml, bitnami/dataplatform-bp2/README.md, bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md
Update subchart dependecies for Data Platform Blueprint 1, 2 and Spring Cloud Data Flow.
**Checklist**
=> [bitnami/*] Update subchart dependencies

bitnami/node-exporter/Chart.yaml, bitnami/node-exporter/README.md
Updated README
**Benefits**
- fixes #
**Checklist** 
- [X Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
=> [bitnami/node-exporter] Updated README

bitnami/oauth2-proxy/Chart.lock, bitnami/oauth2-proxy/README.md, bitnami/oauth2-proxy/templates/NOTES.txt, bitnami/oauth2-proxy/templates/deployment.yaml, bitnami/oauth2-proxy/values.yaml
Add diagnostic mode to the chart 
**Benefits**
- fixes #
**Checklist**
=> [bitnami/oauth2-proxy] Add diagnostic mode

bitnami/argo-cd/values.yaml
**Benefits**
- fixes #
**Checklist**
=> [bitnami/argo-cd] Fix configmap

bitnami/nginx/Chart.yaml, bitnami/nginx/values.yaml
Unset `pdb.maxUnavailable` in default `values.yaml`.
**Benefits**
Resolves conflict introduced in https://github.com/bitnami/charts/commit/97543ce59612ccd6da1f68bee37693e32d9f47d6:
```hcl
│ Error: cannot patch "[REDACTED]" with kind PodDisruptionBudget: PodDisruptionBudget.policy "[REDACTED]" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc00f5be560), Selector:(*v1.LabelSelector)(0xc00f5be580), MaxUnavailable:(*intstr.IntOrString)(0xc00f5be5c0)}: minAvailable and maxUnavailable cannot be both set
```
N/A
N/A
Reproducible with Terraform `v1.0.2` Helm provider `2.2.0`.
**Checklist**
=> [bitnami/nginx] unset pdb.maxUnavailable in default values

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/core/core-cm.yaml
**Indent for common annotations for harbor helm**
**Benefits**
common annotations in helm harbor was broken due to incorrect indent (probably typo)
Now it's possibly to add annotations to all Harbor resources
No
**Checklist**
=> [bitnami/harbor]: indent for annotations

bitnami/redis/README.md
Edited README, per suggestion [here](https://github.com/bitnami/charts/issues/6996). Clarified wording around enabling sentinel, as it is disabled by default.
**Benefits**
Better understanding of the options that come with Redis Helm Chart by default
Hopefully none, since this is a documentation change.
https://github.com/bitnami/charts/issues/6996
- fixes #
**Checklist**
=> [bitnami/redis] Edited README to clarify option of enabling Redis Sentinel with Redis Helm Chart

bitnami/airflow/Chart.yaml, bitnami/airflow/README.md, bitnami/airflow/templates/web/poddisruptionbudget.yaml, bitnami/airflow/templates/worker/poddisruptionbudget.yaml, bitnami/airflow/values.yaml
Removes `nil` values from `bitnami/airflow/values.yaml`.
**Checklist**
=> [bitnami/airflow] Remove nil values

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/replicaset/svc.yaml
When I trying to install the chart in the `replicaset` mode with external pod access through ClusterIP, I get an error message:
```
Error: template: mongodb/templates/replicaset/svc.yaml:18:18: executing "mongodb/templates/replicaset/svc.yaml" at <.Values.commonLabels>: can't evaluate field Values in type int
helm.go:88: [debug] template: mongodb/templates/replicaset/svc.yaml:18:18: executing "mongodb/templates/replicaset/svc.yaml" at <.Values.commonLabels>: can't evaluate field Values in type int
```
In the 'replicaset/svc.yaml' template I was replace variables likes '.Value.commonLabes' to '$root.Value.commonLabes'
**Benefits**
- fixes #6980 
**Checklist**
=> [bitnami/mongodb] Fix a bug that fails install chart in the `replicaset` mode

bitnami/tomcat/Chart.yaml, bitnami/tomcat/README.md
Updated README
**Benefits**
- fixes #
**Checklist**
=> [bitnami/tomcat] README changes

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/README.md
Updated README, migrated examples to docs.bitnami.com
**Benefits**
- fixes #
This PR should only be merged after https://github.com/bitnami/charts-docs/pull/60 is merged and the changes live on docs.bitnami.com
**Checklist**
=> [bitnami/kube-prometheus] Updated README

bitnami/logstash/Chart.yaml, bitnami/logstash/README.md
Updated README and added links to docs.bitnami.com
**Benefits**
- fixes #
This should not be merged until https://github.com/bitnami/charts-docs/pull/57 is merged and the URLs shown are valid on docs.bitnami.com
**Checklist**
=> [bitnami/logstash] Updated README

bitnami/redis/Chart.yaml, bitnami/redis/values.yaml
Small fix in values.yaml
**Benefits**
- fixes #7043
**Checklist**
=> [bitnami/redis] fix typo in values.yaml

bitnami/oauth2-proxy/Chart.lock, bitnami/oauth2-proxy/Chart.yaml, bitnami/oauth2-proxy/templates/_helpers.tpl, bitnami/oauth2-proxy/templates/deployment.yaml, bitnami/oauth2-proxy/templates/secret-authenticated-emails-file.yaml
**Benefits**
- fixes #7068
**Checklist**
=> [bitnami/oauth2-proxy] Fix authenticated emails configurations

bitnami/rabbitmq/README.md
Fix broken link in README
- fixes #7078
=> [bitnami/rabbitmq] Fix wrong link in README

bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md, bitnami/keycloak/templates/ingress.yaml, bitnami/keycloak/values.yaml
Hi,
This for keycloak.
Add existingSecret for ingress TLS configuration.
=> [bitnami/keycloak] Add existingSecret for ingress TLS

bitnami/wordpress/Chart.lock, bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md, bitnami/wordpress/values.yaml
This PR bumps the major version due to the upcoming release of the Bitnami WordPress 5.8 docker image.
**Benefits**
Up-to-date components
None
N/A
N/A
**Checklist**
=> [bitnami/wordpress] New major version

bitnami/dataplatform-bp1/Chart.lock, bitnami/dataplatform-bp1/Chart.yaml, bitnami/dataplatform-bp1/README.md, bitnami/dataplatform-bp2/Chart.lock, bitnami/dataplatform-bp2/Chart.yaml, bitnami/dataplatform-bp2/README.md, bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md
Use the latest version in subcharts
=> [bitnami/several] Use the latest major version in subcharts

bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md, bitnami/mongodb/values.yaml
**Benefits**
- fixes https://github.com/bitnami/charts/issues/6981
**Checklist**
=> [bitnami/mongodb] Clarify externalAccess parameter

bitnami/haproxy/Chart.yaml, bitnami/haproxy/README.md
Updated README with links to docs.bitnami.com
**Benefits**
- fixes #
This shouldn't be merged until https://github.com/bitnami/charts-docs/pull/63 is merged and the transferred example  live on docs.bitnami.com
**Checklist**
=> [bitnami/haproxy] Updated README

bitnami/nats/Chart.yaml, bitnami/nats/README.md
Updated README
**Benefits**
- fixes #
**Checklist**
=> [bitnami/nats] Updated README

bitnami/ejbca/Chart.yaml, bitnami/ejbca/README.md
Updated README
**Benefits**
- fixes #
This should not be landed until https://github.com/bitnami/charts-docs/pull/62 and https://github.com/bitnami/charts-docs/pull/61 are merged and the changes live on docs.bitnami.com
**Checklist**
=> [bitnami/ejbca] Updated README

bitnami/apache/Chart.yaml, bitnami/apache/README.md, bitnami/apache/templates/ingress.yaml, bitnami/apache/values.yaml
This PR modifies bitnami/apache adding compatibility for ingressClassName.
https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/
**Benefits**
Adds compatibility for ingressClassName preserving backward compatibility.
None
None
**Checklist**
=> [bitnami/apache] add support for IngressClassName

template/CHART_NAME/templates/deployment.yaml, template/CHART_NAME/values.yaml
Similar to #7166, there were some obvious typos in the templates.
=> Fix template image section

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/application-controller/deployment.yaml
Fix application-controller repo-server configuration problem
**Benefits**
None
- fixes #7173 
**Checklist**
=> [bitnami/argo-cd] Fix application-controller repo-server

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/application-controller/deployment.yaml, bitnami/argo-cd/templates/dex/deployment.yaml, bitnami/argo-cd/templates/repo-server/deployment.yaml, bitnami/argo-cd/templates/server/deployment.yaml
Fix extraArgs nindent
**Benefits**
None
- fixes #
**Checklist**
=> [bitnami/argo-cd] Fix extraArgs nindent

bitnami/kong/Chart.lock, bitnami/kong/Chart.yaml, bitnami/kong/README.md, bitnami/kong/values.yaml
Updates the Cassandra subchart to its new major `4.0.0`, bumping the Kong chart to a new major.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/kong] Update Cassandra subchart to newest major

bitnami/cert-manager/Chart.yaml
Revert manual `appVersion` update in #7224
**Checklist**
=> [bitnami/cert-manager] Revert appVersion update

bitnami/kibana/Chart.lock, bitnami/kibana/Chart.yaml, bitnami/kibana/templates/_helpers.tpl, bitnami/kibana/templates/deployment.yaml, bitnami/kibana/templates/serviceaccount.yaml, bitnami/kibana/values.yaml
Add service account to Kibana 
**Benefits**
- fixes #7059
This continues working of https://github.com/bitnami/charts/pull/7060
**Checklist**
=> [bitnami/kibana] add serviceaccout

bitnami/kube-prometheus/Chart.lock, bitnami/kube-prometheus/Chart.yaml
This adds the fix https://github.com/bitnami/charts/pull/7258
**Benefits**
- fixes #
**Checklist**
=> [bitnami/kube-prometheus] Bump kube-state-metrics

bitnami/ejbca/Chart.yaml, bitnami/ejbca/README.md, bitnami/mysql/Chart.yaml, bitnami/mysql/README.md, bitnami/nginx/Chart.yaml, bitnami/nginx/README.md, bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/odoo/Chart.yaml, bitnami/odoo/README.md, bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/README.md, bitnami/postgresql/Chart.yaml, bitnami/postgresql/README.md, bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/README.md, bitnami/redis/Chart.yaml, bitnami/redis/README.md, bitnami/solr/Chart.yaml, bitnami/solr/README.md, bitnami/tomcat/Chart.yaml, bitnami/tomcat/README.md, bitnami/wavefront/Chart.yaml, bitnami/wavefront/README.md
Updated and made the README section for `image.tag` more consistent
**Benefits**
- fixes #
This should not land until https://github.com/bitnami/charts-docs/pull/64 is merged and the changes in that PR go live on docs.bitnami.com
**Checklist**
=> [multiple] Updated image.tag section

bitnami/wavefront-hpa-adapter/Chart.yaml, bitnami/wavefront-hpa-adapter/README.md
Updated README
**Benefits**
- fixes #
This should only be merged after https://github.com/bitnami/charts-docs/pull/66 is landed.
**Checklist**
=> [bitnami/wavefront-hpa-adapter] Updated README

bitnami/wavefront-adapter-for-istio/Chart.yaml, bitnami/wavefront-adapter-for-istio/README.md
Updated README and migrated examples to docs.bitnami.com
**Benefits**
- fixes #
This should only be landed after https://github.com/bitnami/charts-docs/pull/65 lands and the pages are live on docs.bitnami.com
**Checklist**
=> [bitnami/wavefront-adapter-for-istio] Updated README

bitnami/wavefront-prometheus-storage-adapter/Chart.yaml, bitnami/wavefront-prometheus-storage-adapter/README.md
Updated README, migrated examples to docs.bitnami.com
**Benefits**
This should be landed only after https://github.com/bitnami/charts-docs/pull/67 is merged and the changes live on docs.bitnami.com
**Checklist**
=> [bitnami/wavefront-prometheus-storage-adapter] Updated README

bitnami/cert-manager/Chart.yaml, bitnami/cert-manager/templates/cainjector/rbac.yaml
=> fix: #7298: missing rbac permissions

bitnami/rabbitmq-cluster-operator/.helmignore, bitnami/rabbitmq-cluster-operator/Chart.lock, bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/README.md, bitnami/rabbitmq-cluster-operator/templates/NOTES.txt, bitnami/rabbitmq-cluster-operator/templates/_helpers.tpl, bitnami/rabbitmq-cluster-operator/templates/clusterrole.yaml, bitnami/rabbitmq-cluster-operator/templates/clusterrolebinding.yaml, bitnami/rabbitmq-cluster-operator/templates/crd-rabbitmq-cluster.yaml, bitnami/rabbitmq-cluster-operator/templates/deployment.yaml, bitnami/rabbitmq-cluster-operator/templates/metrics-service.yaml, bitnami/rabbitmq-cluster-operator/templates/role.yaml, bitnami/rabbitmq-cluster-operator/templates/rolebinding.yaml, bitnami/rabbitmq-cluster-operator/templates/service-account.yaml, bitnami/rabbitmq-cluster-operator/templates/servicemonitor.yaml, bitnami/rabbitmq-cluster-operator/values.yaml
This PR adds a new chart: rabbitmq-cluster-operator. It is an operator similar to what we offer in our grafana-operator chart. It is configured to deploy the Bitnami RabbitMQ chart by default. Because of this, we need to templatize the CRDs and therefore they cannot be put in the `crds/` folder. 
**Benefits**
- fixes #
**Checklist**
=> [bitnami/rabbitmq-cluster-operator] Add chart

bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/README.md, bitnami/rabbitmq-cluster-operator/values.yaml
**Benefits**
- fixes #
**Checklist**
=> [bitnami/rabbitmq-cluster-operator] Fix metadata

bitnami/dataplatform-bp1/Chart.yaml, bitnami/dataplatform-bp1/README.md
README file is Updated in bitnami/dataplatform-bp1  to configure the wavefront to the existing setup.
**Benefits**
If you want to use an existing Wavefront deployment, we can edit the Wavefront Collector ConfigMap and add the blueprint configuration snippet under Prometheus sources.
- fixes #
**Checklist**
=> bitnami/dataplatform-bp1 README file is updated with Wavefront configuration for existing setup.

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/standalone/pvc.yaml
**Benefits**
- fixes #7351
**Checklist**
=> [bitnami/mongodb] Add persistence annotations to PVC

bitnami/wildfly/Chart.yaml, bitnami/wildfly/README.md
Modified README
**Benefits**
- fixes #
**Checklist**
=> [bitnami/wildfly] Updated README

bitnami/dataplatform-bp1/README.md
README file is Updated in bitnami/dataplatform-bp1 to configure the wavefront to the existing setup.
**Benefits**
If you want to use an existing Wavefront deployment, we can edit the Wavefront Collector ConfigMap and add the blueprint configuration snippet under discovery plugins
- fixes #
**Checklist**
=> bitnami/dataplatform-bp1 README file is updated with Wavefront configuration for existing setup

bitnami/redis/Chart.yaml, bitnami/redis/templates/replicas/statefulset.yaml
If autoscaling is enabled do not set StatefulSet.replicas
**Benefits**
Currently Helm shows as OutOfSync when autoscaling is turned on, when there is actually no change to apply
I think there is no drawback
- fixes #
**Checklist**
=> [bitnami/redis] Do not set StatefulSet.replicas if autoscaling is enabled

bitnami/drupal/Chart.yaml, bitnami/drupal/templates/deployment.yaml
Drupal App ExistingSecret is always named of the common Name.
Now you can use any existing Secret with the values drupal-password and smtp-password with it.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/drupal] Fix Variable for existing Secret of Drupal app

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/standalone/dep-sts.yaml
This PR allows the standalone deployment to be upgraded by default. The old RollingUpdate did not allow the new pod to start running due to the `mongodb.lock` file was already created by the already running pod.
**Benefits**
- fixes #7405
**Checklist**
=> [bitnami/mongodb] Use Recreate as strategy type for standalone deployments

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/query-frontend/ingress.yaml
**Benefits**
- fixes https://github.com/bitnami/charts/issues/7280
**Checklist**
=> [bitnami/thanos] Fix incorrect ingress name

bitnami/external-dns/Chart.yaml, bitnami/external-dns/README.md, bitnami/external-dns/values.yaml
Fix a typo in the parameters section from the _values.yaml_ and regenerate the _README.md_ table
- fixes #7453
=> [bitnami/external-dns] Fix typo in parameters section

bitnami/thanos/Chart.lock, bitnami/thanos/Chart.yaml, bitnami/thanos/README.md
This PR updates MinIO subchart.
**Checklist**
=> [bitnami/thanos] Update subcharts

bitnami/common/Chart.yaml, bitnami/common/templates/_names.tpl
**Benefits**
- fixes #7457
**Checklist**
=> [bitnami/common] Add new dependency fullname template

bitnami/mysql/Chart.yaml, bitnami/mysql/templates/NOTES.txt
Fix the instructions to connect to the database
**Benefits**
- fixes #7383
**Checklist**
=> [bitnami/mysql] Fix Mysql root password in NOTES.txt

bitnami/airflow/Chart.lock, bitnami/airflow/Chart.yaml, bitnami/airflow/README.md, bitnami/argo-cd/Chart.lock, bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/README.md, bitnami/discourse/Chart.lock, bitnami/discourse/Chart.yaml, bitnami/discourse/README.md, bitnami/harbor/Chart.lock, bitnami/harbor/Chart.yaml, bitnami/harbor/README.md, bitnami/oauth2-proxy/Chart.lock, bitnami/oauth2-proxy/Chart.yaml, bitnami/oauth2-proxy/README.md, bitnami/redis/Chart.yaml, bitnami/redis/README.md
Updates the redis dependency in several charts. Also adds a comment about redis chart v15 in its REAMDE.
**Benefits**
Dependencies updated.
- fixes #
**Checklist** 
- [-] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
=> [bitnami/ several charts] Redis dependency upgrade

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/README.md
Compressed README, migrated content to docs.bitnami.com
**Benefits**
Smaller and more concise README as extra information moves to docs site
- fixes #
This should not be merged until https://github.com/bitnami/charts-docs/pull/68 is landed and the changes live on docs.bitnami.com
**Checklist**
=> [bitnami/grafana-operator] Updated README

bitnami/mariadb/Chart.yaml, bitnami/mariadb/README.md, bitnami/mariadb/templates/primary/svc.yaml, bitnami/mariadb/templates/secondary/svc.yaml, bitnami/mariadb/values.yaml
PR adds an option to configure externalTrafficPolicy to service type LoadBalancer in mysql chart to preserve Client IP. Additionally, while running MariaDB on Azure AKS cluster with an internal LoadBalancer and default externalTrafficPolicy: Cluster, mysql instance gets health probes from AKS LoadBalancer and drops them as aborted connections, this fills up error logs and reserves unnecessary connections in mysql. Setting externalTrafficPolicy: Local eliminates this issue.
**Benefits**
- externalTrafficPolicy is configurable to preserve ClientIP
- avoid issues with internal load balancers on AKS clusters
not known
no
no
**Checklist**
=> [bitnami/mariadb] add `externalTrafficPolicy` to service type `LoadBalancer`

bitnami/kubernetes-event-exporter/Chart.yaml, bitnami/kubernetes-event-exporter/README.md
Added more information about parameters to README
**Benefits**
Additional information for users
None
None
None 
**Checklist**
=> [bitnami/kubernetes-event-exporter] Updated README

bitnami/drupal/Chart.lock, bitnami/drupal/Chart.yaml, bitnami/drupal/README.md, bitnami/drupal/templates/ingress.yaml, bitnami/drupal/values.yaml
Adds support for IngressClassName
**Benefits**
Adds support for IngressClassName
Nothing known
**Checklist**
=> [bitnami/drupal] Add support for ingressClassName

bitnami/kibana/Chart.yaml, bitnami/kibana/README.md
Updated README and migrated some examples to docs.bitnami.com
**Benefits**
Smaller more compact README
This should only be merged after https://github.com/bitnami/charts-docs/pull/71 is merged and the changes live on docs.bitnami.com
**Checklist**
=> [bitnami/kibana] Updated README

bitnami/metrics-server/Chart.yaml, bitnami/metrics-server/README.md
Updated and improved README
**Benefits**
- fixes #
**Checklist**
=> [bitnami/metrics-server] Updated README

bitnami/kube-state-metrics/Chart.yaml, bitnami/kube-state-metrics/README.md
Updated README
**Benefits**
- fixes #
**Checklist**
=> [bitnami/kube-state-metrics] Updated README

bitnami/thanos/Chart.yaml, bitnami/thanos/README.md
Fixed broken links
**Benefits**
- fixes #
**Checklist**
=> [bitnami/thanos] Fixed broken links in Thanos README

bitnami/common/Chart.yaml, bitnami/common/README.md
fix `Storage` from readme of the common chart 
**Benefits**
- fixes #
**Checklist**
=> fix readme for common chart

bitnami/dataplatform-bp2/Chart.lock, bitnami/dataplatform-bp2/Chart.yaml, bitnami/dataplatform-bp2/values.yaml
Fix incorrect metadata generation.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/dataplatform-bp2] Fix annotations

bitnami/minio/Chart.lock, bitnami/minio/Chart.yaml, bitnami/minio/templates/gateway/deployment.yaml
Add in the args the flag --console-address 
**Benefits**
- fixes #7591
**Checklist**
=> [bitnami/minio] gateway console port

bitnami/minio/Chart.yaml, bitnami/minio/templates/gateway/deployment.yaml
**Benefits**
Add missing ':' in the command of args
- fixes #7591
**Checklist**
=> [bitnami/minio] fix args in gateway

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/arbiter/configmap.yaml, bitnami/mongodb/templates/arbiter/headless-svc.yaml, bitnami/mongodb/templates/arbiter/pdb.yaml, bitnami/mongodb/templates/arbiter/statefulset.yaml
Add `commonAnnotations` on Arbiter resources
**Benefits**
Arbiter resources can inherit global annotations from values `commonAnnotations`
- fixes #
**Checklist**
=> [bitnami/mongodb] Add commonAnnotations on arbiter

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/README.md, bitnami/elasticsearch/templates/coordinating-statefulset.yaml, bitnami/elasticsearch/templates/cronjob.yaml, bitnami/elasticsearch/templates/data-statefulset.yaml, bitnami/elasticsearch/templates/ingest-statefulset.yaml, bitnami/elasticsearch/templates/master-statefulset.yaml, bitnami/elasticsearch/templates/metrics-deploy.yaml, bitnami/elasticsearch/values.yaml
**Benefits**
- Enables you to set a podTopologyConstraint per set of resources within the elasticsearch chart
- fixes: #7600
- relates to: https://github.com/bitnami/charts/pull/7598
**Checklist**
=> [bitnami/elasticsearch] Configure topology spread constraints

bitnami/tensorflow-resnet/Chart.yaml, bitnami/tensorflow-resnet/README.md
Updated README and linked to docs.bitnami.com
**Benefits**
- fixes #
**Checklist**
=> [bitnami/tensorflow-resnet] Updated README

bitnami/mongodb-sharded/Chart.yaml, bitnami/rabbitmq-cluster-operator/Chart.yaml
Fix Chart.yaml format due to some errors detected with
```console
$ yq r --tojson Chart.yaml | jq . | yq r --prettyPrint - > Chart.yaml.new && mv Chart.yaml.new Chart.yam
```
=> [bitnami/rabbitmq-cluster-operator & mongodb-sharded] Fix Chart.yaml format

bitnami/discourse/README.md
Add disclaimer and registered icon to the Bitnami Discourse Chart solution
**Benefits**
- fixes #
**Checklist**
=> [bitnami/discourse] Add registered icon and trademark information to the Discourse's README

bitnami/spark/Chart.yaml, bitnami/spark/README.md, bitnami/spark/templates/_helpers.tpl, bitnami/spark/templates/serviceaccount.yaml, bitnami/spark/templates/statefulset-master.yaml, bitnami/spark/templates/statefulset-worker.yaml, bitnami/spark/values.yaml
Signed-off-by: Ahmet Kaftan <ahmet.kaftan@cloudnesil.com>
Adds ServiceAccount to Spark Worker and Master pods.
**Benefits**
- fixes #7991 
**Checklist**
=> [bitnami/spark] Add ServiceAccount to Spark Worker and Master.

bitnami/contour-operator/Chart.yaml, bitnami/keycloak/Chart.yaml
Fix minor format issues in Chart.yaml
=> [bitnami/contour-operator, bitnami/keycloak] Fix Chart.yaml format

bitnami/oauth2-proxy/Chart.yaml, bitnami/oauth2-proxy/README.md, bitnami/oauth2-proxy/templates/deployment.yaml, bitnami/oauth2-proxy/values.yaml
Add the `google-group` parameter
**Benefits**
Fixes #7944 
- fixes #7944
**Checklist**
=> [bitnami/oauth2-proxy] Support for google-group parameter

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/repo-server/repository-credentials-secret.yaml
=> [bitnami/argo-cd] Fix typo on repository-credentials-secret

bitnami/etcd/Chart.yaml, bitnami/etcd/README.md, bitnami/etcd/templates/cronjob.yaml, bitnami/etcd/values.yaml
add nodeSelector & tolerations on disasterRecovery cronJob
**Benefits**
- fixes  #7769
**Checklist**
=> [bitnami/etcd] add etcd nodeselector & toleration on disasterRecovery

CONTRIBUTING.md
Add info about readme-generator tool in the contributing guidelines.
**Benefits**
Reduce the issues in the PRs regarding linter errors.
- fixes #
**Checklist** 
- [-] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [-] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
=> Add info about README generator in CONTRIBUTING

CONTRIBUTING.md
**Benefits**
- fixes #
**Checklist**
=> Fix contributing readme tool url

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/templates/alertmanager/service.yaml, bitnami/kube-prometheus/templates/prometheus/service.yaml, bitnami/kube-prometheus/templates/prometheus/thanos-service.yaml
Updates he services created by the `kube-prometheus` charts with the correct selector labels. The `app` label is no longer used as of: https://github.com/prometheus-operator/prometheus-operator/commit/27abc70fbd35a27d2270273c06b14d1a86d1afd8
**Benefits**
Services will work again :D
None known.
- #8095 
See: https://github.com/prometheus-operator/prometheus-operator/commit/27abc70fbd35a27d2270273c06b14d1a86d1afd8
**Checklist**
=> [bitnami/kube-prometheus] fix: update service selectors

bitnami/postgresql-ha/Chart.lock, bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/README.md, bitnami/postgresql-ha/values.yaml
**Benefits**
- fixes #
**Checklist**
=> [bitnami/postgresql-ha] Bump to 8.0.0

bitnami/influxdb/Chart.yaml, bitnami/influxdb/README.md, bitnami/influxdb/templates/influxdb/deployment-standalone.yaml, bitnami/influxdb/templates/influxdb/statefulset-high-availability.yaml, bitnami/influxdb/templates/podsecuritypolicy.yaml, bitnami/influxdb/templates/role.yaml, bitnami/influxdb/templates/rolebinding.yaml, bitnami/influxdb/templates/serviceaccount.yaml, bitnami/influxdb/values.yaml
I have added PSP when volume permissions are enabled in a hardened cluster. Without it, my deployment fails as runAsUser=0 is not allowed.
**Benefits**
- fixes #
Depends on https://github.com/bitnami/bitnami-docker-influxdb/issues/8
**Checklist**
=> [bitnami/influxdb] Added PSP for volume permissions in hardened cluster

bitnami/elasticsearch/Chart.lock, bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/ingest-statefulset.yaml
Fix for PR https://github.com/bitnami/charts/pull/7847
**Benefits**
- fixes #8132
**Checklist**
=> [bitnami/elasticsearch] fix ingest-statefulset

bitnami/minio/Chart.yaml, bitnami/minio/README.md, bitnami/minio/templates/gateway/deployment.yaml, bitnami/minio/values.yaml
Adds support for custom server endpoint for Azure Blob Storage MinIO gateway
**Benefits**
Allows users to use non-standard Azure Blob endpoint for MinIO gateway
- fixes #8161
**Checklist**
=> [bitnami/minio] Support custom endpoint for minio azure gateway

bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md, bitnami/spring-cloud-dataflow/values.yaml
Add documentation for parameter **commonLabels** in values.yaml and README.md
**Benefits**
The chart will be easier to be configured.
no
no
**Checklist**
=> [bitnami/spring-cloud-dataflow] Add undocumented parameter in values.yaml

bitnami/contour/Chart.yaml, bitnami/contour/README.md, bitnami/contour/templates/_helpers.tpl, bitnami/contour/values.yaml
- Change default config in `values.yaml` to not specify a `ingressClass.name`. 
- Changed helper function `isIngressClassNameDefined` to only return `true` if `ingressClass.name` has explicitly configured.
These changes ensure that using the default config `contour server` will be started without the `--ingress-class-name` flag and therefore Contour will reconcile `httpproxy` instances which do not explicitly specify an `ingressClassName` under `spec`.
**Benefits**
FIx for #8174 
Contour installed with the Helm chart uses the same config / behaves the same as Contour installed via the other methods described on the Contour website. E.g. config examples from the Contour documentation work without changes...
- fixes …
=> [bitnami/contour]: fix for #8174

bitnami/apache/Chart.yaml, bitnami/apache/templates/deployment.yaml
Currently, the init container is able to pull the repository but when performing the `mv` the `.git` is lost. This PR makes it to move the full folder, including hidden directories.
**Benefits**
- fixes #8190
**Checklist**
=> [bitnami/apache] Allow to move hidden directories

bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/node/templates/_helpers.tpl, bitnami/node/templates/deployment.yaml, bitnami/node/templates/serviceaccount.yaml, bitnami/node/values.yaml
Adds service account to the deployment
**Benefits**
- fixes #8213
**Checklist**
=> [bitnami/node] Adds service account

bitnami/external-dns/README.md
https://github.com/kubernetes-sigs/external-dns/issues/2168#issuecomment-947841020
**Benefits**
- fixes #
**Checklist**
=> state correct version

bitnami/common/Chart.yaml, bitnami/common/templates/validations/_cassandra.tpl, bitnami/common/templates/validations/_mariadb.tpl, bitnami/common/templates/validations/_mongodb.tpl, bitnami/common/templates/validations/_postgresql.tpl, bitnami/common/templates/validations/_redis.tpl
Applying the "quote" function to an empty string causes the string "" to become """", causing issues in certain password checks in the common library. This PR adds an extra check to avoid this situation.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/common] fix: :bug: Add extra check for "\"\"" values in existing secrets

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/secrets.yaml
fix error in secrets template. Chart throw error with extraSecrets in .Values
**Benefits**
error fixed
none
- fixes #
**Checklist**
=> [bitnami/rabbitmq] fix error with scope of .Values in secrets template

bitnami/external-dns/Chart.yaml, bitnami/external-dns/values.yaml
This will hopefully fix the crashed CI pipeline introduced in #7659
https://github.com/bitnami/charts/runs/4483384859?check_suite_focus=true
**Benefits**
- fixes #
**Checklist**
=> [bitnami/external-dns] Fix duplicated variable in values.yaml

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/templates/networkpolicy-egress.yaml
This PR add the egress rules to the pods "pgpool".
**Benefits**
The egress rules should be applied to both the "postgresql" and "pgpool" pods.
This PR adds apply the egress rules also to the "pgpool" pods.
None known.
None
**Checklist**
=> [bitnami/postgresql-ha] Add egress rules for pgpool pods

bitnami/kubeapps/Chart.yaml, bitnami/kubeapps/values.yaml
**Benefits**
Fix pending change from  #8297 
- fixes #
**Checklist**
=> [bitnami/kubeapps] Fix kubeapps parameter

CONTRIBUTING.md
Update _CONTRIBUTING.md_ adding a note about Helm charts additions to the catalog
=> Update CONTRIBUTING.md adding a note about chart additions

bitnami/wavefront/Chart.yaml, bitnami/wavefront/templates/proxy-deployment.yaml
Removed by the upstream project at https://github.com/wavefrontHQ/helm/pull/142
=> [bitnami/wavefront] Remove Java args

bitnami/redis/Chart.yaml, bitnami/redis/README.md, bitnami/redis/values.yaml
Fixes the description and default value of `spreadConstraints` as it was reported to be incorrect.
**Benefits**
The default value has the expected format.
None
- fixes #8304
**Checklist**
=> [bitnami/redis] Fix spreadConstraints description and default value

bitnami/memcached/Chart.yaml, bitnami/memcached/templates/hpa.yaml
Minor change that makes prevents this chart from always being out of sync when deployed using ArgoCD. 
More info here: https://github.com/bitnami/charts/issues/8390#issuecomment-993336875
**Benefits**
Chart can be used with ArgoCD
None. 
https://github.com/bitnami/charts/issues/8390#issuecomment-993336875
**Checklist**
=> [bitnami/memcached] Update to prevent argocd from always  reporting out of sync

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kafka/templates/networkpolicy-egress.yaml, bitnami/kafka/templates/networkpolicy-ingress.yaml, bitnami/kafka/values.yaml
Signed-off-by: Davide Madrisan <davide.madrisan@gmail.com>
This PR add the possibility to define custom Egress rules.
**Benefits**
This feature is required in strict kubernetes environments where by default the Egress traffic is denied.
This PR is backward compatible because in the default values the Egress custom rules are disabled.
The `.Values.networkPolicy.egressRules.denyConnectionsToExternal` is not implemented in this PR because I found it very complex for this chart. There are several components (kafka, zookeeper, metrics, jmx metrics) all of that must be configured in a default Egress rule.
None
None 
**Checklist**
=> [bitnami/kafka] Add egress custom rules

bitnami/redis/Chart.yaml, bitnami/redis/templates/scripts-configmap.yaml
@sagar-infinitus-ai pointed out an error in the current chart. Make sure that sentinels can start.
Also it adds a timeout to the master search command.
**Benefits**
Redis sentinel can start
If the master is not available for the duration of the startup we can end up with a multi master situation.
- fixes https://github.com/bitnami/charts/issues/8451
**Checklist**
=> [bitnami/redis] redis sentinel startup

bitnami/joomla/Chart.yaml, bitnami/joomla/README.md, bitnami/joomla/values.yaml
**Benefits**
Use Joomla 4.x in the chart.
- fixes #
**Checklist**
=> [bitnami/joomla] feat!: :boom: Bump to Joomla 4

bitnami/redis/Chart.yaml, bitnami/redis/templates/NOTES.txt
Now there is no need to verify whether the password is empty, because after #8486 password will auto reload  through lookup existing secret.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/redis] remove password empty validation

bitnami/kong/Chart.lock, bitnami/kong/Chart.yaml, bitnami/kong/README.md, bitnami/kong/templates/_helpers.tpl, bitnami/kong/templates/migrate-job.yaml, bitnami/kong/values.yaml
Bump the Cassandra chart. We also detected that kong-ingress-controller is not compatible with Cassandra, so we added a validation to avoid this deployment.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/kong] feat!: :boom: Bump cassandra chart to 9.x.

bitnami/cassandra/Chart.yaml, bitnami/cassandra/templates/NOTES.txt
Now there is no need to verify whether the password is empty, because after #8495 password will auto reload through lookup existing secret.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/cassandra] remove password empty validation

bitnami/tensorflow-resnet/Chart.yaml, bitnami/tensorflow-resnet/README.md, bitnami/tensorflow-resnet/templates/deployment.yaml, bitnami/tensorflow-resnet/values.yaml
Signed-off-by: Jose Antonio Carmona <jcarmona@vmware.com>
- Update TensorFlow ResNet to the new minor, version `2.7.0`
- Update the pretrained model to a more recent one, which uses the new signature.
**Benefits**
Up-to-date components
Older models may need to adapt their signature to the newer one. As an alternative, users may still be able to specify older versions of the `bitnami-docker-tensorflow-resnet` image.
NA
https://github.com/tensorflow/serving/issues/1947
**Checklist**
=> [bitnami/tensorflow-resnet] Update TF ResNet version

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/NOTES.txt
Now there is no need to verify whether the password is empty, because after #8320 password will auto reload through lookup existing secret.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/postgresql] remove empty password validation

bitnami/thanos/Chart.yaml, bitnami/thanos/README.md
typo
**Benefits**
- fixes #
**Checklist**
=> bitnami/thanos chart: readme typo

bitnami/aspnet-core/Chart.yaml, bitnami/aspnet-core/README.md, bitnami/aspnet-core/values.yaml
**Benefits**
- fixes #
**Checklist**
=> [bitnami/aspnet] Bump ASP.NET to version 6

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/README.md, bitnami/grafana-operator/values.yaml
Upgraded the images to the latest bitnami images
**Benefits**
A bug was solved https://github.com/bitnami/bitnami-docker-grafana/pull/23
No drawbacks.
**Checklist**
=> [bitnami/grafana-operator] Release 2.1.1 updating components versions

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/hidden/external-access-svc.yaml
Fixes commonLabels for hidden nodes externak service
**Benefits**
- fixes installation for cluster with hidden nodes and external access
NA
**Checklist**
=> [bitnami/mongodb] Fixed commonlabel issues for hidden node external service

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/README.md, bitnami/redis-cluster/templates/metrics-svc.yaml, bitnami/redis-cluster/values.yaml
added metrics.service.clusterIP
**Checklist**
=> [bitnami/redis-cluster] Add metrics.service.clusterIP

bitnami/etcd/Chart.yaml, bitnami/etcd/values.yaml
Fix values metadata for parameter introduced at https://github.com/bitnami/charts/pull/8595
=> [bitnami/etcd] Fix values metadata

bitnami/postgresql/Chart.yaml, bitnami/postgresql/values.yaml
Fix typo
**Benefits**
Correct comments in postgres values
**Checklist**
=> [bitnami/postgresql]: Fix typo

CONTRIBUTING.md
Add DCO to the CONTRIBUTING file
=> Add DCO to the CONTRIBUTING file

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/templates/alertmanager/pdb.yaml, bitnami/kube-prometheus/templates/prometheus/pdb.yaml
Adapt the labels to the new version
**Benefits**
- fixes #6500 
**Checklist**
=> [bitnami/kube-prometheus] Update labels

bitnami/apache/Chart.yaml, bitnami/apache/README.md, bitnami/apache/templates/NOTES.txt, bitnami/apache/templates/deployment.yaml, bitnami/apache/templates/ingress.yaml, bitnami/apache/templates/svc.yaml, bitnami/apache/values.yaml
This PR standardizes the bitnami/apache chart to be in line with the rest of the catalog.
**Checklist**
=> [bitnami/apache] Chart standardized

bitnami/phpmyadmin/Chart.lock, bitnami/phpmyadmin/Chart.yaml, bitnami/phpmyadmin/README.md, bitnami/phpmyadmin/templates/NOTES.txt, bitnami/phpmyadmin/templates/deployment.yaml, bitnami/phpmyadmin/templates/ingress.yaml, bitnami/phpmyadmin/templates/metrics-svc.yaml, bitnami/phpmyadmin/templates/service.yaml, bitnami/phpmyadmin/templates/servicemonitor.yaml, bitnami/phpmyadmin/values.yaml
This PR standardizes the bitnami/phpmyadmin chart to be in line with the rest of the catalog.
**Checklist**
=> [bitnami/phpmyadmin] Chart standardized

bitnami/moodle/Chart.lock, bitnami/moodle/Chart.yaml, bitnami/moodle/README.md, bitnami/moodle/templates/NOTES.txt, bitnami/moodle/templates/deployment.yaml, bitnami/moodle/templates/ingress.yaml, bitnami/moodle/templates/metrics-svc.yaml, bitnami/moodle/templates/pvc.yaml, bitnami/moodle/templates/svc.yaml, bitnami/moodle/values.yaml
This PR standardizes the bitnami/moodle chart to be in line with the rest of the catalog.
**Checklist**
=> [bitnami/moodle] Chart standardized

.github/PULL_REQUEST_TEMPLATE.md
Added checkbox reminding people to check they've signed off their commits.
=> [meta] Add DCO to PR template

bitnami/haproxy/Chart.yaml, bitnami/haproxy/README.md, bitnami/haproxy/templates/deployment.yaml, bitnami/haproxy/templates/service-account.yaml, bitnami/haproxy/templates/service.yaml, bitnami/haproxy/values.yaml
This PR standardizes the bitnami/haproxy chart to be in line with the rest of the catalog.
**Checklist**
=> [bitnami/haproxy] Chart standardized

bitnami/thanos/Chart.lock, bitnami/thanos/Chart.yaml, bitnami/thanos/README.md
Signed-off-by: Francisco de Paz <fdepaz@vmware.com>
Updated `Chart.yaml` to use the latest MinIO chart major, `10.X`.
**Checklist**
=> [bitnami/thanos] Update MinIO subchart to newest major version

bitnami/cassandra/Chart.yaml, bitnami/cassandra/README.md
Amend TLS documentation for Apache Cassandra Bitnami chart. It was using deprecated parameters
**Checklist**
[https://github.com/bitnami-labs/readme-generator-for-helm]
=> [bitnami/cassandra] Amend cassandra TLS documentation

bitnami/cert-manager/Chart.yaml, bitnami/cert-manager/README.md, bitnami/cert-manager/templates/cainjector/deployment.yaml, bitnami/cert-manager/templates/cainjector/serviceaccount.yaml, bitnami/cert-manager/templates/controller/deployment.yaml, bitnami/cert-manager/templates/controller/serviceaccount.yaml, bitnami/cert-manager/templates/controller/servicemonitor.yaml, bitnami/cert-manager/templates/webhook/deployment.yaml, bitnami/cert-manager/templates/webhook/serviceaccount.yaml, bitnami/cert-manager/values.yaml
This PR standardizes the bitnami/cert-manager chart to be in line with the rest of the catalog.
**Checklist**
=> [bitnami/cert-manager] Chart standardized

bitnami/etcd/Chart.yaml, bitnami/etcd/README.md, bitnami/etcd/templates/NOTES.txt, bitnami/etcd/templates/_helpers.tpl, bitnami/etcd/templates/configmap.yaml, bitnami/etcd/templates/cronjob.yaml, bitnami/etcd/templates/pdb.yaml, bitnami/etcd/templates/secrets.yaml, bitnami/etcd/templates/serviceaccount.yaml, bitnami/etcd/templates/snapshot-pvc.yaml, bitnami/etcd/templates/statefulset.yaml, bitnami/etcd/templates/svc-headless.yaml, bitnami/etcd/templates/svc.yaml, bitnami/etcd/values.yaml
This PR standardizes the bitnami/etcd chart to be in line with the rest of the catalog.
**Checklist**
=> [bitnami/etcd] Chart standardized

bitnami/ghost/Chart.lock, bitnami/ghost/Chart.yaml, bitnami/ghost/README.md
Updates the MariaDB subchart to its version 10.x.x.
**Checklist**
=> [bitnami/ghost] Bump MariaDB chart

bitnami/grafana-tempo/Chart.yaml, bitnami/grafana-tempo/templates/compactor/deployment.yaml, bitnami/grafana-tempo/templates/distributor/deployment.yaml, bitnami/grafana-tempo/templates/ingester/statefulset.yaml, bitnami/grafana-tempo/templates/querier/deployment.yaml, bitnami/grafana-tempo/templates/query-frontend/deployment.yaml, bitnami/grafana-tempo/templates/vulture/deployment.yaml
Grafana-tempo config checksum annotation was added to all the deployments template metadata.
**Benefits**
Pods will restart if config changes.
- fixes #8707
**Checklist**
=> [bitnami/grafana-tempo] Add checksum annotations

bitnami/joomla/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/joomla] Fix non utf-8 character

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
Fixes missing closing bracket for hidden node script.
**Benefits**
Fixes hidden node deployment.
NA
NA
**Checklist**
=> [bitnami/mongodb] Fixed closing bracket for hidden node scripts

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/README.md, bitnami/rabbitmq/templates/svc.yaml, bitnami/rabbitmq/values.yaml
Signed-off-by: Fabio Castagnino <fabio.castagnino@outlook.it>
Added two option to disable (or enable) epmd and/or dist port on Service.
**Benefits**
Improve security not exposing unwanted ports.
Reduce cost on Cloud Load Balancer.
- fixes #
**Checklist**
=> [bitnami/rabbitmq] Added option to disable epmd and dist port on service

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/README.md, bitnami/elasticsearch/templates/data-svc.yaml, bitnami/elasticsearch/values.yaml
**Benefits**
Makes the data-svc annotations a configuration option. All other services appear to have this ability but the data one doesn't (I need the ability to annotate the service to appease `linkerd check --proxy` warnings as port `9300` is an opaque port on the pods but not for things coming in via the service.
Fixes the lack of annotation ability on the data-svc
- fixes #
I'm using linkerd as my service-mesh of choice, and it uses annotations on pods / services to configure it. I need to mark the port `9300` as opaque on the data and master svcs but I can't actually annotate the data svc at all
**Checklist**
=> [bitnami/elasticsearch] Add annotations to data-svc

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/templates/proxy/ingress.yaml
Fix misplaced Ingress class in template file
**Benefits**
IngressClassName is usable
- fixes #8757 
**Checklist**
=> [bitnami/jupyterhub] Fix misplaced Ingress class in template file

bitnami/metrics-server/Chart.lock, bitnami/metrics-server/Chart.yaml, bitnami/metrics-server/README.md, bitnami/metrics-server/templates/cluster-role.yaml, bitnami/metrics-server/values.yaml
Signed-off-by: Francisco de Paz <fdepaz@vmware.com>
Updated cluster-role resource definition following the changes made by upstream in their new minor, `0.6.0`. 
New version upstream's changelog: https://github.com/kubernetes-sigs/metrics-server/releases/tag/v0.6.0
**Checklist**
=> [bitnami/metrics-server] Update cluster-role resource per new version

bitnami/testlink/Chart.yaml, bitnami/testlink/templates/deployment.yaml
If the metrics sidecar is not enabled and the pod is still annotated Prometheus will report the target as down even though it shouldn't be scraped.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/testlink] fix: skip metrics annotation if disabled

bitnami/nginx-intel/README.md
Fix ® character.
**Checklist**
=> [bitnami/nginx-intel] Fix registered symbol

.github/workflows/vib.yaml, .vib/vib-pipeline.json, .vib/vib-platform-verify.json, .vib/wordpress/cypress/cypress.json, .vib/wordpress/cypress/cypress/fixtures/helloworld.json, .vib/wordpress/cypress/cypress/fixtures/user.json, .vib/wordpress/cypress/cypress/integration/admin_spec.js, .vib/wordpress/cypress/cypress/integration/helloworld_spec.js, .vib/wordpress/cypress/cypress/integration/login_spec.js, .vib/wordpress/cypress/cypress/plugins/index.js, .vib/wordpress/cypress/cypress/support/commands.js, .vib/wordpress/cypress/cypress/support/index.js, .vib/wordpress/cypress/package-lock.json, .vib/wordpress/cypress/package.json, .vib/wordpress/goss/goss-wait.yaml, .vib/wordpress/goss/goss.yaml, .vib/wordpress/jmeter/wordpress.jmx
Adds support for VMware Image Builder. 
For PoC purposes only.
=> Initial commit for VMware Image Builder support PoC
