bitnami/redis/Chart.lock, bitnami/redis/Chart.yaml, bitnami/redis/templates/health-configmap.yaml, bitnami/redis/templates/scripts-configmap.yaml
This PR fixes some errors when enabling sentinel + TLS
**Benefits**
- fixes https://github.com/bitnami/charts/issues/7392
- fixes https://github.com/bitnami/charts/issues/7283
- fixes https://github.com/bitnami/charts/issues/8325
- related https://github.com/bitnami/charts/pull/7428
**Checklist**
=> [bitnami/redis] Fix Redis Sentinel TLS issues

.github/workflows/vib.yaml
Signed-off-by: Martin Perez <martinpe@vmware.com>
Turns VIB on in master branch for Wordpress product. PR to Wordpress will go through several automated verifications: linting, trivy and, multi-cluster k8s verification.
This new flow is driven by the vib.yaml GitHub workflow.
**Benefits**
Showcases our new product, VMware Image Builder for ISV package distribution and verification.
None. 
- fixes #
=> Turns VIB on in master branch for wordpress product

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/README.md, bitnami/mongodb-sharded/values.yaml, bitnami/mongodb/Chart.lock, bitnami/mongodb/Chart.yaml, bitnami/mongodb/README.md, bitnami/mongodb/values.yaml
mongodb-exporter version was updated
**Checklist**
=> [bitnami/mongodb*] New major version using 0.30.X for the exporter

bitnami/cassandra/README.md, bitnami/cert-manager/README.md, bitnami/geode/README.md, bitnami/ghost/README.md, bitnami/kafka/README.md, bitnami/keycloak/README.md, bitnami/kong/README.md, bitnami/kube-prometheus/README.md, bitnami/kubewatch/README.md, bitnami/mariadb-galera/README.md, bitnami/memcached/README.md, bitnami/metrics-server/README.md, bitnami/mongodb-sharded/README.md, bitnami/mongodb/README.md, bitnami/moodle/README.md, bitnami/nginx-ingress-controller/README.md, bitnami/nginx-intel/README.md, bitnami/nginx/README.md, bitnami/phpmyadmin/README.md, bitnami/prestashop/README.md, bitnami/tomcat/README.md, bitnami/wildfly/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/*] Fix non-utf8 characters

bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md, bitnami/spring-cloud-dataflow/templates/server/configmap.yaml, bitnami/spring-cloud-dataflow/templates/skipper/configmap.yaml, bitnami/spring-cloud-dataflow/values.yaml
Added `deployer.secretRefs` to spring-cloud-dataflow chart (https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_secret_references)
**Benefits**
Having the possibility to add secrets to the deployed apps.
None (that I can think of)
- fixes #8837
**Checklist**
=> [bitnami/spring-cloud-dataflow] enable deployer secretRefs

bitnami/spark/Chart.yaml, bitnami/spark/README.md
Closes #8121.
Closes #5997.
Signed-off-by: Brad Solomon <81818815+brsolomon-deloitte@users.noreply.github.com>
=> [bitnami/spark] Document configuring Spark Master as reverse proxy

bitnami/keycloak/Chart.yaml, bitnami/nginx-intel/Chart.yaml, bitnami/nginx/Chart.yaml, bitnami/rabbitmq-cluster-operator/Chart.yaml
Prettify Chart.yaml file across charts by running
```bash
for d in *; do
cd $d
if [ -f "Chart.yaml" ]; then
yq r --tojson Chart.yaml | jq . | yq r --prettyPrint - > Chart.yaml.new && mv Chart.yaml.new Chart.yaml
fi
cd ..
done
```
=> [bitnami/several] Prettify Chart.yaml

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/kafka-provisioning.yaml
When using Kafka with provisioning job, the job itself is left behind after destoying the release.
**Benefits**
Kafka provisioning job and pods are cleaned-up after destroying a release.
None
- unclean destroy - the provisioning job is left behind
**Checklist**
=> [bitnami/kafka] Provisioning hook lifecycle

bitnami/pytorch/Chart.yaml, bitnami/pytorch/values.yaml
The Chart installation was prone to fail due to a problem with the `readinessProbe` timeout, which may take slightly more time than the allowed one.
**Benefits**
Improve chart stability
None
NA
**Checklist**
=> [bitnami/pytorch] Increase timeout for the Pytorch readinessProbe

bitnami/nginx-intel/README.md, bitnami/wordpress-intel/README.md
Adapt README for Intel solutions
=> [bitnami/*-intel] Adapt README

bitnami/nginx-intel/README.md, bitnami/wordpress-intel/README.md
=> [bitnami/*-intel] Fix typos in README

bitnami/haproxy/Chart.yaml, bitnami/haproxy/ci/ct-values.yaml
By default, the chart has LoadBalancer enabled as service type. This causes conflicts with the Github action testing environment. This PR adds a ct-values.yaml file setting the Service to ClusterIP by default.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/haproxy] test: :white_check_mark: Add testing values.

.github/ct-install.yaml, bitnami/harbor/Chart.yaml, bitnami/harbor/ci/ct-values.yaml
This PR re-enables the Harbor tests in the GH action. We need to add a ct-values.yaml so the service is ClusterIP.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/harbor] test: :white_check_mark: Add ct-values.yaml

.github/ct-install.yaml, bitnami/discourse/Chart.yaml, bitnami/discourse/ci/ct-values.yaml
This PR re-enables the Discourse tests in the GH action. We need to add a ct-values.yaml so the service is ClusterIP.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/discourse] test: :white_check_mark: Add ct-values.yaml

bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/crds/crd-rabbitmq-cluster.yaml, bitnami/rabbitmq-cluster-operator/crds/crds-messaging-topology-operator.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/clusterrole.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/validating-webhook-configuration.yaml
CRDs updated from the upstream projects: https://github.com/rabbitmq/cluster-operator/releases https://github.com/rabbitmq/messaging-topology-operator/releases
**Benefits**
- fixes #
**Checklist**
=> [bitnami/rabbitmq-cluster-operator] feat: :wrench: Update CRDs

bitnami/moodle/Chart.yaml, bitnami/moodle/README.md, bitnami/moodle/templates/_helpers.tpl, bitnami/moodle/templates/deployment.yaml, bitnami/moodle/values.yaml
In PR [#bitnami/bitnami-docker-moodle](https://github.com/bitnami/bitnami-docker-moodle/pull/197) the option was added that Postgresql data beacons can be used. For this purpose the option `externalDatabase.type` was added to select whether it is a `mariadb `or `postgresql `database.  
**Benefits**
The Moodle chart underlines the choice between external Mariadb or Postgresql.
**Checklist**
=> [bitnami/moodle] add support for moodle database type

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/values.yaml
Signed-off-by: fahad-rauf <fahad.abdulrauf@gmail.com>
Update the default configuration in values.yaml to use the "singleuser.podLabels"
**Benefits**
It will fix the bug
- fixes #8954 
**Checklist**
=> [bitnami/jupyterhub] Update label configuration

.github/workflows/vib-redis.yaml, .vib/redis/vib-pipeline.json, bitnami/redis/README.md
Signed-off-by: Aleksandra Lukic <alukic@vmware.com>
This is just a test of the Redis workflow. I'm triggering it by making a change in the Redis README.md
=> [bitnami/redis] Fixing the Redis VIB workflow

bitnami/jenkins/Chart.yaml, bitnami/jenkins/README.md, bitnami/jenkins/templates/deployment.yaml, bitnami/jenkins/values.schema.json, bitnami/jenkins/values.yaml
Add values for Jenkins Helm chart to be able to specify service account
**Benefits**
User are able to input service account for Jenkins' pod
- fixes #6983
**Checklist**
=> [bitnami/jenkins] feat: allow config service account

.github/workflows/vib-early-feedback.yaml
**Benefits**
- fixes #
**Checklist**
=> test(all): :ambulance: Fix incorrect chart changes detection

bitnami/mariadb/Chart.yaml, bitnami/mariadb/templates/servicemonitor.yaml
Signed-off-by: bbaudelet <bbaudelet@gmail.com>
Fix typo on serviceMonitor,by add missing { on relabelings.
**Benefits**
relabeling on serviceMonitor can be use.
- fixes #
**Checklist**
=> [bitnami/mariadb] Fix typo on serviceMonitor

bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/forwarder-psp.yaml, bitnami/fluentd/templates/ingress.yaml
These changes fix the correct names to use in Fluentd chart templates.
Fix : 
- `.Values.ingress.ingressClassNam` to `.Values.aggregator.ingress.ingressClassName `
- `.Values.forwarder.securityContext` to `.Values.forwarder.podSecurityContext`
**Benefits**
The errors below are corrected: 
Error naming for ingress.ingressClassName : 
`stderr: Error: UPGRADE FAILED: template: fluentd/templates/ingress.yaml:24:20: executing "fluentd/templates/ingress.yaml" at <.Values.ingress.ingressClassName>: nil pointer evaluating interface {}.ingressClassName`
Error naming for securityContext.* :  
`stderr: Error: UPGRADE FAILED: template: fluentd/templates/forwarder-psp.yaml:36:26: executing "fluentd/templates/forwarder-psp.yaml" at …
=> [bitnami/fluentd] fix naming errors in template file

bitnami/grafana/Chart.yaml, bitnami/grafana/README.md, bitnami/grafana/values.yaml
PR for issue https://github.com/bitnami/charts/issues/9007
**Checklist**
=> [bitnami/grafana] Patch for issue 9007

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/_helpers.tpl, bitnami/airflow/templates/scheduler/deployment.yaml, bitnami/airflow/templates/web/deployment.yaml, bitnami/airflow/templates/worker/statefulset.yaml
Fix for issue reported in #8986 
Not identified
- fixes #8986 
**Checklist**
=> [bitnami/airflow] Fix template errors when using existing configmap for dags

.github/workflows/vib-early-feedback.yaml
Currently, for changes that don't apply to charts, the Early Feedback github action is not run. However, this action is a mandatory requirement for merging, so PRs like https://github.com/bitnami/charts/pull/9059 are blocked because of not changing any chart.
The action already skips the test when no charts are changed, so it is safe to remove `path` section of the action.
Tested with these two PRs https://github.com/javsalgar/charts-1/pull/11 https://github.com/javsalgar/charts-1/pull/12
**Benefits**
- fixes #
**Checklist**
=> [bitnami/*]: test: :children_crossing: Make "Early Feedback" run in all PRs

bitnami/contour/Chart.yaml, bitnami/contour/templates/contour/rbac.yaml
This creates resources necessary for Contour to pick a leader via the
new mechanism planned for 1.21.1.
**Benefits**
Users will be able to use Contour's new leader election mechanism.
* Fixes #8975.
**Checklist**
=> [bitnami/contour] Support namespace-scoped leader election

bitnami/kubernetes-event-exporter/Chart.yaml, bitnami/kubernetes-event-exporter/templates/NOTES.txt
Display additional information in the NOTES.txt when the chart is deployed.
**Checklist**
=> [bitnami/kubernetes-event-exporter] Update NOTES.txt

.github/workflows/vib-early-feedback.yaml
The action is returning jq parse errors because of a sed that escapes backslashes, which are already escaped in the returned curl output. This double escaping is causing parse errors.
```
parse error: Invalid numeric literal at line 1, column 1615
```
The changes were added in this PR:  https://github.com/bitnami/charts/pull/9069
**Benefits**
- fixes this PR https://github.com/bitnami/charts/pull/9163
**Checklist**
=> [bitnami/*] test: :ambulance: Fix incorrect jq parsing

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/NOTES.txt
Some users may be accessing the container for debugging. This is done using `kubectl exec -ti <pod> /bin/bash`. This command overrides the container entrypoint and may cause an error like this when executing `psql` without specifying the user:
```
psql: local user with ID 1001 does not exist
```
This PR improves the container NOTES.txt file.
**Benefits**
n/a
- fixes #
**Checklist**
=> [bitnami/postgresql] docs: :memo: Add note about using the container entrypoint

.github/workflows/generate-chart-readme.yml
**Benefits**
- fixes #
**Checklist**
=> Update readme generator commit id

.github/workflows/vib-early-feedback.yaml, .github/workflows/vib-redis.yaml, .github/workflows/vib.yaml
Signed-off-by: Martin Perez <martinpe@vmware.com>
Start using the VIB action from the official repo
=> Move us to use the action from the official repo

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/README.md
Right now, we don't have automated support for scaling down (at least not until the chart uses Redis 7, which has hostname support). This PR improves the instructions for scaling down a cluster.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/redis-cluster] docs: :memo: Improve instructions for scaling down.

bitnami/discourse/Chart.yaml, bitnami/discourse/templates/pvc.yaml, bitnami/jenkins/Chart.yaml
The indent in the pvc.yaml file for the storage class was incorrect. This PR fixes it. 
**Benefits**
Correct use of PVC
n/a
- fixes #
**Checklist**
=> [bitnami/discourse]: fix: :bug: Fix incorrect indent in PVC

bitnami/moodle/Chart.yaml, bitnami/moodle/templates/_helpers.tpl
Signed-off-by: Shih-Ting Huang <huangstm@gmail.com>
The format specifier for externalDatabase.type was incorrect.
**Benefits**
Generate correct value for the externalDatabase.type parameter (MOODLE_DATABASE_TYPE)
n/a
- fixes #
**Checklist**
=> [bitnami/moodle] Fix format specifier of externalDatabase.type

.github/workflows/vib-early-feedback.yaml
The bitnami/common chart is a library, non-installable chart. Therefore the checks with VMware ImageBuilder fail. The action should skip this chart.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/*] test: :white_check_mark: Skip Early Feedback test in bitnami/common

bitnami/minio/Chart.yaml, bitnami/minio/templates/gateway/hpa.yaml
Due to https://github.com/kubernetes/kubernetes/issues/74099 the HPA reorders resource specs in a certain manner (memory, then cpu)
This causes Out of sync diffs when using GitOps tools like ArgoCD
**Benefits**
One less Out of Sync resource when using ArgoCD or a similar GitOps tool
https://github.com/kubernetes/kubernetes/issues/74099
**Checklist**
=> [bitnami/minio] Reorder MinIO Gateway HPA resource list to smooth out GitOps diffs

bitnami/sonarqube/Chart.lock, bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/README.md, bitnami/sonarqube/templates/_helpers.tpl, bitnami/sonarqube/templates/deployment.yaml, bitnami/sonarqube/templates/externaldb-secret.yaml, bitnami/sonarqube/values.yaml
BREAKING CHANGE. This PR bumps the PostgreSQL subchart. This will imply a change in the PostgreSQL version.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/sonarqube]: feat!: :arrow_up: Bump PostgreSQL subchart

bitnami/contour/Chart.yaml, bitnami/contour/README.md, bitnami/contour/templates/envoy/service.yaml, bitnami/contour/values.yaml
**Benefits**
- fixes #9289 
**Checklist**
=> [bitnami/contour] Support dual stack of contour ingress

bitnami/ghost/Chart.yaml, bitnami/ghost/README.md, bitnami/ghost/templates/deployment.yaml, bitnami/ghost/values.schema.json, bitnami/ghost/values.yaml
Capacity in Helm Chart of Ghost to use SSL in Database
It's related to this PR:
https://github.com/bitnami/bitnami-docker-ghost/pull/121
**Benefits**
Use SSL in database
**Checklist**
=> bitnami/ghost add database SSL support 

CONTRIBUTING.md
Signed-off-by: alukic <alukic@vmware.com>
Using a markdown functionality of an automatically numbered list instead of a hardcoded one. 
**Benefits**
The numbered lists are not hardcoded anymore. 
**Checklist**
=> [bitnami/*] Fixed the ordered list

bitnami/discourse/Chart.lock, bitnami/discourse/Chart.yaml, bitnami/discourse/values.yaml
Signed-off-by: Marcos Bjoerkelund <marcos@bitnami.com>
Discourse 2.8.x plugins are not compatible with 2.7.x. Since those are persisted, upgrades won't work. As a consequence we are increasing the chart major.
Related PR (docs) for upgrade notes: https://github.com/bitnami/charts-docs/pull/98
**Benefits**
Users can deploy Discourse 2.8.x.
The new major require additional steps to upgrade.
None
**Checklist**
=> [bitnami/discourse] MAJOR: Update to 2.8.x

bitnami/jenkins/Chart.yaml, bitnami/jenkins/templates/metrics-svc.yaml
fix issue in metrics service port value
**Benefits**
no workaround is required
`templates/metrics-svc.yaml` is using `.Values.metrics.service.ports.http` while `metrics.service.port` is provided in `values.yaml` and README.md
**Checklist**
=> [bitnami/jenkins] fix: jenkins metrics service invalid value

bitnami/minio/Chart.yaml, bitnami/minio/README.md, bitnami/minio/values.yaml
Signed-off-by: Gonzalo Gomez Gracia <gonzalog@vmware.com>
**Checklist**
=> [bitnami/minio] Remove compatibility with MINIO_ACCESS_KEY and MINIO_SECRET_KEY

bitnami/geode/Chart.lock, bitnami/geode/Chart.yaml, bitnami/geode/templates/server/statefulset.yaml
Change liveness and readiness probes to avoid errors in the logs
**Benefits**
- fixes #9175
**Checklist**
=> [bitnami/geode] Change liveness and readiness probe

bitnami/mariadb/Chart.yaml, bitnami/mariadb/templates/_helpers.tpl, bitnami/mariadb/templates/secrets.yaml, bitnami/mariadb/values.yaml
Don't overwrite already generated secret values on mariadb chart upgrade
**Benefits**
MariaDB doesn't break on chart upgrade.
None.
- fixes #7403 
- fixes https://github.com/bitnami/bitnami-docker-mariadb/issues/225#issuecomment-880124912
**Checklist**
=> [bitnami/mariadb] Don't overwrite existing secrets

bitnami/contour/Chart.lock, bitnami/contour/Chart.yaml, bitnami/contour/resources/contourconfiguration.yaml, bitnami/contour/resources/contourdeployments.yaml, bitnami/contour/resources/extensionservices.yaml, bitnami/contour/resources/httpproxies.yaml, bitnami/contour/resources/tlscertificatedeligations.yaml, bitnami/contour/values.yaml
Although it shows a lot of changes, it doesn't matter, it's just a few indents. I just synced it over from the contour code repository. Subsequent changes synced this way should be easier to review.
**Benefits**
- fixes #9308 
**Checklist**
=> [bitnami/contour] Sync CRDs with contour release 1.20.1

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/scripts-configmap.yaml
Fix issue with #9279.
Thanks, @kvendingoldo for reporting this.
**Checklist**
=> [bitnami/redis-cluster] Fix 9279

bitnami/redis/Chart.yaml, bitnami/redis/templates/health-configmap.yaml
=> [bitnami/redis] Fix 9279

bitnami/thanos/Chart.yaml, bitnami/thanos/README.md, bitnami/thanos/values.yaml
**Benefits**
Add readOnlyRootOnlyFilesystem by default. [Ref](https://kubesec.io/basics/containers-securitycontext-readonlyrootfilesystem-true/)
- fixes #
**Checklist**
=> Read only root file system thanos

bitnami/influxdb/Chart.yaml, bitnami/influxdb/README.md, bitnami/influxdb/templates/NOTES.txt, bitnami/influxdb/templates/ingress.yaml, bitnami/influxdb/values.yaml
Signed-off-by: Christian Lumper <ch.lumper@gmail.com>
Add support for template directives at hostname of ingress/tls configuration.
**Benefits**
Allows to use values for generation of hostname which is especially handy if chart is used within umbrella chart.
e.g.
```yaml
ingress:
enabled: true
tls: true
hostname: '{{ .Values.global.domain }}'
```
- fixes #
**Checklist**
=> [bitnami/influxdb] ingress/tls hostname template support

bitnami/odoo/Chart.yaml, bitnami/odoo/README.md, bitnami/odoo/templates/pvc.yaml, bitnami/odoo/values.yaml
Signed-off-by: Mostafa Hussein <mostafa.hussein91@gmail.com>
This PR adds the ability to maintain the status of a PVC using `persistence.resourcePolicy` parameter
**Benefits**
If you are using a storage class with a `Retain` relcaim policy, the PV will inherit the same policy, in such case you might need to keep the PVC in case you removed a release and you wanted to deploy it again so you don't have to manually update the PV to mark it as available again.
**Checklist**
=> [bitnami/odoo] add the ability to set resourcePolicy value for PVC

bitnami/mysql/README.md
**Benefits**
README tidy, delete unnecessary blank
- fixes #
**Checklist**
=> [bitnami/mysql] document tidy, delete unnecessary blank

bitnami/ghost/Chart.lock, bitnami/ghost/Chart.yaml, bitnami/ghost/README.md, bitnami/ghost/templates/deployment.yaml, bitnami/ghost/values.yaml
Capacity in Helm Chart of Ghost to use SSL/TLS in mail provider for secure connection
It's related to this PR:
https://github.com/bitnami/bitnami-docker-ghost/commit/4f75a4555e75165ee0eb766f1772c899214ff088
**Benefits**
Use SSL/TLS when you send emails
**Checklist**
=> bitnami/ghost add smtp SSL/TSL support

bitnami/redis/README.md
clean unnecessary blank and fix typo
**Benefits**
- fixes #
**Checklist**
=> [bitnami/redis] README tidy, fix typo

bitnami/odoo/Chart.lock, bitnami/odoo/Chart.yaml, bitnami/odoo/README.md, bitnami/odoo/templates/NOTES.txt, bitnami/odoo/templates/_helpers.tpl, bitnami/odoo/templates/deployment.yaml, bitnami/odoo/templates/ingress.yaml, bitnami/odoo/templates/pvc.yaml, bitnami/odoo/templates/secrets.yaml, bitnami/odoo/templates/serviceaccount.yaml, bitnami/odoo/templates/svc.yaml, bitnami/odoo/values.yaml
This PR standardizes the `bitnami/odoo` chart to be in line with the rest of the catalog.
**Benefits**
None. No major bump is required since breaking changes were added support for deprecated values using `coalesce`.
N/A
N/A
**Checklist**
=> [bitnami/odoo] Chart standardized

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/crds/application.yaml, bitnami/argo-cd/crds/applicationset.yaml, bitnami/argo-cd/crds/project.yaml
Updates ArgoCD CRDs and adds newly added (v2.3) ApplicationSet.
- fixes #9389
**Checklist**
=> [bitnami/argo-cd] Update CRDs + Add ApplicationSet CRD

bitnami/redis/Chart.yaml, bitnami/redis/README.md, bitnami/redis/templates/master/application.yaml, bitnami/redis/values.yaml
Signed-off-by: Mihir Kumar Singh <singhmihirkumar@gmail.com>
Added sizeLimit option for `emptyDir` volumes.
**Benefits**
It will allow us to add size limit on emptyDir Vol
None.
- fixes #
**Checklist**
=> [bitnami/redis] Add sizeLimit option for emptyDir volumes.

bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md, bitnami/keycloak/values.yaml
Signed-off-by: Lester Guerzon <lester@pidnull.io>
Hi! This MR is to correct some spelling mistakes in the Keycloak chart.
**Benefits**
Correct spelling mistakes.
None.
None.
**Checklist**
=> [bitnami/keycloak]: fix spelling mistakes in values.yml

bitnami/redis/Chart.yaml, bitnami/redis/values.yaml
Signed-off-by: Rafael Rios Saavedra <rafael.rios.saavedra@gmail.com>
Relocate comment in values.yaml
**Benefits**
- fixes #
**Checklist**
- [-] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
=> [bitnami/redis] Relocate comment in values

bitnami/redis/Chart.yaml, bitnami/redis/templates/master/application.yaml
Signed-off-by: Mihir Kumar Singh <singhmihirkumar@gmail.com>
This is related to change in the PR https://github.com/bitnami/charts/pull/9418 , there was a syntax issue while adding new key to the dict `emptyDir` due which now it was failing with an error `did not find expected , or }`. This PR is to fix that issue.
**Benefits**
Bug fix
None
- fixes #
**Checklist**
=> [Bitnami/Redis] Bug fix for emptyDir Dict

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/primary/statefulset.yaml, bitnami/postgresql/values.yaml
... to be able to use numeric initdb.password
Fixes #9445
Signed-off-by: Alexander Evseev <aevseev@gmail.com>
=> [bitnami/postgresql] Quote POSTGRESQL_INITSCRIPTS_PASSWORD

bitnami/argo-workflows/Chart.lock, bitnami/argo-workflows/Chart.yaml, bitnami/argo-workflows/README.md, bitnami/argo-workflows/values.yaml
**Benefits**
Add readOnlyRootOnlyFilesystem by default. [Ref](https://kubesec.io/basics/containers-securitycontext-readonlyrootfilesystem-true/)
- fixes #
**Checklist**
=> [bitnami/argo-workflows] Set rootOnlyrootFileSystem by default

bitnami/contour-operator/Chart.lock, bitnami/contour-operator/Chart.yaml, bitnami/contour-operator/README.md, bitnami/contour-operator/values.yaml
**Benefits**
- fixes #
**Checklist**
=> [bitnami/contour-operator] Set readOnlyRootFileSystem by default

bitnami/wavefront-hpa-adapter/Chart.lock, bitnami/wavefront-hpa-adapter/Chart.yaml, bitnami/wavefront-hpa-adapter/README.md, bitnami/wavefront-hpa-adapter/templates/custom-metrics-apiserver-deployment.yaml, bitnami/wavefront-hpa-adapter/values.yaml
**Benefits**
- fixes #
**Checklist**
=> [bitnami/wavefront-hpa-adapter] Set readOnlyRootFileSystem by default

bitnami/harbor/Chart.yaml
Bump chart version after https://github.com/bitnami/charts/pull/9436
=> [bitnami/harbor] Bump chart version

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/README.md
clean unnecessary blank and fix typo
**Benefits**
- fixes #
**Checklist**
=> [bitnami/redis-cluster] fix typo

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/README.md, bitnami/grafana-operator/values.yaml
Signed-off-by: Baptiste Roux <baptiste.roux@skale-5.com>
Fixes the example in `values.yaml` for the `dashboardNamespaceSelector` param.
**Benefits**
- fixes #9456
**Checklist**
=> [bitnami/grafana-operator] Correct dashboardNamespaceSelector expected type. Fixes #9456.

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/README.md
fix some typos
**Benefits**
- fixes #
**Checklist**
=> [bitnami/postgresql-ha] document clean, fix typos

bitnami/spark/Chart.lock, bitnami/spark/Chart.yaml, bitnami/spark/templates/statefulset-master.yaml, bitnami/spark/templates/statefulset-worker.yaml, bitnami/spark/values.yaml
Moving the mounted configuration approach to /bitnami/spark, just like we do with other applications. This allows users to mount their own configuration files, no matter how many.
**Benefits**
- fixes https://github.com/bitnami/charts/issues/9505
**Checklist**
=> [bitnami/spark] fix: :bug: Move mounted configuration to /bitnami/spark

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/jobservice/jobservice-dpl.yaml
**Benefits**
- fixes #
**Checklist**
=> [bitnami/harbor] `jobservice.replicaCount` is now taken into account

bitnami/solr/Chart.lock, bitnami/solr/Chart.yaml, bitnami/solr/README.md, bitnami/solr/values.yaml
Update zookeeper dependency to use version 3.8
**Checklist**
=> [bitnami/solr] Update zookeeper version for solr

bitnami/dataplatform-bp1/Chart.lock, bitnami/dataplatform-bp1/Chart.yaml, bitnami/dataplatform-bp1/README.md, bitnami/dataplatform-bp1/values.yaml
Update zookeeper dependency to use version 3.8
**Checklist**
=> [bitnami/dataplatform-bp1] Update zookeeper version

README.md, bitnami/keycloak/Chart.lock, bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/service.yaml, bitnami/keycloak/values.yaml
Fix loadBalancerSourceRanges evaluation bug
**Benefits**
- fixes #
**Checklist**
=> [bitnami/keycloak] :bug: Fix loadBalancerSourceRanges evaluation bug

bitnami/redis/Chart.yaml, bitnami/redis/README.md, bitnami/redis/values.yaml
Fixed a typo in redis helm chart values description of the `Egress` part in `NetworkPolicy`
**Benefits**
Fixing typos for better documentation
- fixes #
**Checklist**
=> [bitnami/redis]: fixing typo in `egress` part of `NetworkPolicy` (from `ingress`)

.github/workflows/generate-chart-readme.yml
Updating the Github Action "generate-chart-readme.yml" so it properly updates the README.md with a commit from bitnami-bot. The action will execute readme-generator-for-helm and push the changes. This will only occur if the values.yaml file is changed.
In order to do so, we need to use the Personal Access Token of the bitnami-bot account so the workflows get re-triggered after the automated commit. 
We also removed Github Actions that were not certified by Github.
Tests:
- Action not triggered: https://github.com/javsalgar/charts/pull/1
- Action triggered and updated (1 chart): https://github.com/javsalgar/charts/pull/5
- Action triggered and failed (incorrect metadata): …
=> [bitnami/*]: chore: :hammer: Change the Update README metadata action to update the README.md

bitnami/etcd/Chart.yaml, bitnami/etcd/README.md, bitnami/etcd/values.yaml
According to the [upstream etcd developers](https://github.com/etcd-io/etcd/tree/main/CHANGELOG#production-recommendation), version 3.5 is discouraged to use in production due to a data corruption issue. This PR changes the etcd default version to 3.4.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/etcd] fix!: :arrow_down: Downgrade default etcd version to 3.4.

template/CHART_NAME/templates/daemonset.yaml, template/CHART_NAME/templates/deployment.yaml, template/CHART_NAME/templates/hpa.yaml, template/CHART_NAME/templates/ingress.yaml, template/CHART_NAME/templates/pdb.yaml, template/CHART_NAME/templates/pvc.yaml, template/CHART_NAME/templates/role.yaml, template/CHART_NAME/templates/service-account.yaml, template/CHART_NAME/templates/service.yaml, template/CHART_NAME/templates/servicemonitor.yaml, template/CHART_NAME/templates/statefulset.yaml, template/CHART_NAME/values.yaml
**Benefits**
- fixes #
**Checklist**
=> Update template to the latest standardisations

bitnami/jenkins/README.md
Update README.md of Jenkins
**Checklist**
=> [bitnami/jenkins] Update jenkins README.md

.github/workflows/sync-chart-index.yaml
This new workflow will sync the bitnami/index.yaml file located in the index branch to an S3 bucket configured in the repository secrets. As currently we are under testing, we added the `--dryrun` flag to ensure that the job works as expected.
For syncing with S3 we used the S3 sync action: https://github.com/marketplace/actions/s3-sync
**Benefits**
- fixes #
**Checklist**
=> [bitnami/*] feat: :tada: Add workflow for syncing index.yaml to S3

bitnami/contour-operator/Chart.yaml, bitnami/contour-operator/README.md
Fix Chart.yaml quotes and README as a continuation of #9658
=> [bitnami/contour-operator] Fix Chart.yaml quotes and README

bitnami/minio/Chart.yaml, bitnami/minio/templates/_helpers.tpl
Signed-off-by: Loh, Yun-Fong <yunloh@hotmail.com>
=> [bitnami/minio]: Allow existingSecret to be a template.

bitnami/mysql/Chart.yaml, bitnami/mysql/templates/NOTES.txt
Signed-off-by: Yi Siqi <yisq@me.com>
Now there is no need to verify whether the password is empty, because after #8504 password will auto reload through lookup existing secret.
**Benefits**
- fixes #
Similar to #8534
**Checklist**
=> [bitnami/mysql] remove empty password validation

bitnami/nginx-ingress-controller/Chart.yaml
Since the ingress controller version `1.0.0` only Kubernertes >= 1.22 is supported. See supported versions [here](https://github.com/kubernetes/ingress-nginx#support-versions-table).
**Benefits**
- fixes #7264
**Checklist**
=> [bitnami/nginx-ingress-controller] Add kubeVersion to Chart.yaml

bitnami/rabbitmq-cluster-operator/Chart.yaml
Ref: https://github.com/bitnami/charts/pull/9717
**Checklist**
=> [bitnami/rabbitmq-cluster-operator] Update kubeVersion regex to work with GKE

bitnami/contour-operator/Chart.yaml
Ref: https://github.com/bitnami/charts/pull/9717
**Checklist**
=> [bitnami/contour-operator] Update kubeVersion regex to work with GKE

bitnami/postgresql/Chart.yaml, bitnami/postgresql/README.md, bitnami/postgresql/templates/primary/configmap.yaml, bitnami/postgresql/templates/primary/extended-configmap.yaml, bitnami/postgresql/templates/primary/initialization-configmap.yaml, bitnami/postgresql/templates/primary/metrics-configmap.yaml, bitnami/postgresql/templates/primary/metrics-svc.yaml, bitnami/postgresql/templates/primary/networkpolicy.yaml, bitnami/postgresql/templates/primary/prometheusrule.yaml, bitnami/postgresql/templates/primary/servicemonitor.yaml, bitnami/postgresql/templates/primary/statefulset.yaml, bitnami/postgresql/templates/primary/svc-headless.yaml, bitnami/postgresql/templates/primary/svc.yaml, bitnami/postgresql/templates/psp.yaml, bitnami/postgresql/templates/read/networkpolicy.yaml, bitnami/postgresql/templates/read/statefulset.yaml, bitnami/postgresql/templates/read/svc-headless.yaml, bitnami/postgresql/templates/read/svc.yaml, bitnami/postgresql/templates/role.yaml, bitnami/postgresql/templates/rolebinding.yaml, bitnami/postgresql/templates/secrets.yaml, bitnami/postgresql/templates/serviceaccount.yaml, bitnami/postgresql/templates/tls-secrets.yaml, bitnami/postgresql/values.yaml
Signed-off-by: Dennis Urban <dennis.urban@flipapp.de>
This change make numeric only namespaces possible. The Problem is at the moment, that the chart dont quote the Namespaces, so numeric Namespaces are detected as Integer and not String.
```
Error: unable to build kubernetes objects from release manifest: unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.namespace of type string
helm.go:84: [debug] unable to decode "": json: cannot unmarshal number into Go struct field ObjectMeta.metadata.namespace of type string
````
Its the same problem describes here for the redis chart: https://github.com/bitnami/charts/pull/4094
**Benefits**
You can use numeric only namespaces, e.g. 1234
**Applicable …
=> [bitnami/postgresql] Add quote to namespace

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/storegateway/ingress-grpc.yaml
**Benefits**
- fixes #
**Checklist**
=> [bitnami/thanos] Use correct helpers for ingress-grpc.yaml

bitnami/kube-state-metrics/Chart.yaml, bitnami/kube-state-metrics/templates/service.yaml
Add a default annotation `prometheus.io/port` based on the Service port.
**Benefits**
VictoriaMetrics agent will discover the Prometheus Scrape if this annotation is added.
N/A
- relates to VictoriaMetrics/VictoriaMetrics#2417
**Checklist**
=> [bitnami/kube-state-metrics] Add Service annotation prometheus.io/port

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/tls-secret.yaml
Signed-off-by: lc-guy <aptyget@gmail.com>
**Checklist**
=> [bitnami/keycloak] Fix nil pointer evaluating interface {}.tls

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/templates/prometheus/tls-secrets.yaml
**Benefits**
- Fixes #9696 
**Checklist**
=> [bitnami/kube-prometheus] Fix indentation in tls secrets template

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/config/configmap.yaml, bitnami/airflow/templates/scheduler/deployment.yaml, bitnami/airflow/templates/web/deployment.yaml, bitnami/airflow/templates/worker/statefulset.yaml
[bitnami/airflow] condition to accept extraEnvVarsCM added in the chart templates
Signed-off-by: Vedant Pareek <dunefro@gmail.com>
Adding the extraEnvVarsCM  in the if condition to accept the configmap at a global level
**Benefits**
Create a single configmap that  you wish to attach to all the pods in the charts
- fixes #9716 
**Checklist**
=> [bitnami/airflow] condition to accept extraEnvVarsCM added in the chart templates

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/README.md, bitnami/argo-cd/crds/application.yaml
Signed-off-by: Raymonder Jin <rayjingithub@gmail.com>
**Benefits**
- fixes #
**Checklist**
=> [bitnami/argo-cd] document clean, fix typos

bitnami/grafana-tempo/Chart.yaml, bitnami/grafana-tempo/README.md, bitnami/grafana-tempo/values.yaml
This PR adds the parameter tempo.search.enabled to enable the Tempo search feature (defaults to disabled)
**Benefits**
The official grafana/tempo chart already has this parameter (https://github.com/grafana/helm-charts/blob/e59bc2b3393b252b3f2673c42d0a6f0dd72d57c1/charts/tempo-distributed/values.yaml#L369)
Tempo search is still an experimental feature (https://grafana.com/docs/tempo/latest/getting-started/tempo-in-grafana/#tempo-search)
**Checklist**
=> [bitnami/grafana-tempo] Add a parameter to enable Tempo search

bitnami/node-exporter/Chart.yaml, bitnami/node-exporter/templates/daemonset.yaml, bitnami/node-exporter/templates/psp-clusterrolebinding.yaml, bitnami/node-exporter/templates/service.yaml, bitnami/node-exporter/templates/serviceaccount.yaml, bitnami/node-exporter/templates/servicemonitor.yaml
Signed-off-by: Dennis Urban <mail@dpunkturban.io>
Without quoting the namespace, it is not possible to run node-exporter in numeric only namespaces.
**Benefits**
You can run the chart in numeric only-namespaces (e.g. 1234)
- fixes #
**Checklist**
=> [bitnami/node-exporter] quote namespace

bitnami/minio/Chart.yaml, bitnami/minio/templates/distributed/statefulset.yaml, bitnami/minio/templates/provisioning-configmap.yaml, bitnami/minio/templates/provisioning-job.yaml, bitnami/minio/templates/tls-secrets.yaml, bitnami/minio/values.yaml
Some places need the namespace unquoted to build a fully quallified url
- regression of #9734
**Benefits**
Chart works again
none
- fixes #
**Checklist**
=> [bitnami/minio]: unquote required namespaces

bitnami/logstash/Chart.yaml, bitnami/logstash/README.md
No longer supported by logstash chart. logstash chart 2.0.0
dropped files/conf support, so remove it from readme.
Signed-off-by: Brad Solomon <81818815+brsolomon-deloitte@users.noreply.github.com>
**Benefits**
- fixes #
**Checklist**
=> [bitnami/logstash] Remove mention of files/ in readme

bitnami/external-dns/Chart.yaml, bitnami/external-dns/templates/_helpers.tpl
This PR removes unnecssary azure validations, as some parameters didn't need to be set.
**Benefits**
- fixes https://github.com/bitnami/charts/issues/9572
**Checklist**
=> [bitnami/external-dns]: fix: :bug: Remove unnecessary Azure validation

bitnami/mariadb/Chart.yaml, bitnami/mariadb/README.md, bitnami/mariadb/values.yaml
BREAKING CHANGE. This PR bump the MariaDB version to 10.6. No issues are expected during upgrade.
**Benefits**
- fixes #
**Checklist**
=> [bitnami/mariadb]: feat!: :arrow_up: bump MariaDB version to 10.6

bitnami/mediawiki/Chart.lock, bitnami/mediawiki/Chart.yaml, bitnami/mediawiki/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/mediawiki] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/prestashop/Chart.lock, bitnami/prestashop/Chart.yaml, bitnami/prestashop/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/prestashop] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/wordpress-intel/Chart.lock, bitnami/wordpress-intel/Chart.yaml, bitnami/wordpress-intel/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/wordpress-intel] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/redmine/Chart.lock, bitnami/redmine/Chart.yaml
**Benefits**
- fixes #
**Checklist**
=> [bitnami/redmine] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/moodle/Chart.lock, bitnami/moodle/Chart.yaml, bitnami/moodle/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/moodle] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/joomla/Chart.lock, bitnami/joomla/Chart.yaml, bitnami/joomla/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/joomla] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/wordpress/Chart.lock, bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/wordpress] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/phpmyadmin/Chart.lock, bitnami/phpmyadmin/Chart.yaml, bitnami/phpmyadmin/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/phpmyadmin] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/phpbb/Chart.lock, bitnami/phpbb/Chart.yaml, bitnami/phpbb/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/phpbb] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/ghost/Chart.lock, bitnami/ghost/Chart.yaml, bitnami/ghost/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/ghost] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/suitecrm/Chart.lock, bitnami/suitecrm/Chart.yaml, bitnami/suitecrm/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/suitecrm] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/spring-cloud-dataflow] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/owncloud/Chart.lock, bitnami/owncloud/Chart.yaml, bitnami/owncloud/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/owncloud] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/osclass/Chart.lock, bitnami/osclass/Chart.yaml, bitnami/osclass/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/osclass] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/opencart/Chart.lock, bitnami/opencart/Chart.yaml, bitnami/opencart/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/opencart] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/jasperreports/Chart.lock, bitnami/jasperreports/Chart.yaml, bitnami/jasperreports/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/jasperreports] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/drupal/Chart.lock, bitnami/drupal/Chart.yaml, bitnami/drupal/README.md
**Benefits**
- fixes #
**Checklist**
=> [bitnami/drupal] feat!: :arrow_up: Bump MariaDB version to 10.6

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/README.md, bitnami/redis-cluster/templates/svc-cluster-external-access.yaml, bitnami/redis-cluster/values.yaml
Signed-off-by: Cedric Hnyda <cedric.hnyda@itera.io>
Add loadBalancerSourceRanges when exposing redis-cluster externally. 
**Benefits**
- fixes #
**Checklist**
=> [bitnami/redis-cluster]: loadBalancerSourceRanges for external access

.github/workflows/vib-verify-extra-redis.yaml, .github/workflows/vib-verify-extra-thanos.yaml, .github/workflows/vib-verify.yaml
Use a secret to define the `target-platform` instead of hardcoding the value.
**Benefits**
The `target-platform` can be modified dynamically, without having to explicitly alter the workflow file every time.
None
NA
NA
**Checklist**
=> [bitnami/*] Easily update target-platforms

bitnami/contour/Chart.yaml, bitnami/contour/README.md, bitnami/contour/templates/contour/deployment.yaml, bitnami/contour/values.yaml
Signed-off-by: yy <yang.yang@daocloud.io>
Add contour root-namespaces option
**Benefits**
Restrict contour to searching these namespaces for root ingress routes.
**Checklist**
=> [bitnami/contour] Add contour root-namespaces option

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/templates/statefulset.yaml
During first start `volume-permissions` container creates directory for data, but not changes owner ot this dir. It only tries to find files in this dir and change owner. It do nothing because no files at first start. So, zookeeper fails to start because can't create files in data dir (`/bitnami/zookeeper`).
**Benefits**
Added chmod for data directory next step after creating.
- fixes #9690
**Checklist**
=> [bitnami/zookeeper] Add chown for data dir, not only children (#9690)

bitnami/argo-workflows/Chart.yaml, bitnami/argo-workflows/templates/controller/servicemonitor.yaml
[bitnami/argo-workflows] fix argo-workflows ServiceMonitor port name error
**Benefits**
Getting argo-workflows and Grafana to work
- fixes #
https://user-images.githubusercontent.com/8380489/164976382-3c3f5231-9add-42d8-874e-24bbc01288ca.png
**Checklist**
=> [bitnami/argo-workflows] fix argo-workflows ServiceMonitor port name error

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/README.md, bitnami/grafana-operator/templates/grafana.yaml, bitnami/grafana-operator/values.yaml
Signed-off-by: Ronan LE BRUN ronan.lebrun@gmail.com
Change allows for the ingress host to be optional, i.e. not being set, if set empty
**Benefits**
Make ingress compatible with other scenarios where hosts are not relevant (e.g. content accessed directly via IP) 
None
- fixes #
**Checklist**
=> [bitnami/grafana-operator] Make ingress host optional

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/_helpers.tpl
Signed-off-by: Rafael Rios Saavedra <rafael.rios.saavedra@gmail.com>
Fix the issue #9885. 
The name of the postgresql host is wrong when using `postgresql.architecture=replication`
**Benefits**
- fixes #9885 
**Checklist**
- [-] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
=> [bitnami/keycloak] Fix postgresql replication usage issue

.github/PULL_REQUEST_TEMPLATE.md
Applied correct markdown to the PR template.
**Benefits**
Better use of the tools.
- fixes #
**Checklist**
=> Applied correct markdown

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/NOTES.txt, bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml, bitnami/mongodb-sharded/templates/mongos/mongos-dep-sts.yaml, bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
Replace `mongo` with `mongosh`
**Benefits**
- fixes #
**Checklist**
=> [bitnami/mongodb-sharded] chore: :wastebasket: Remove reference to mongo command

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/NOTES.txt, bitnami/mongodb/templates/hidden/statefulset.yaml, bitnami/mongodb/templates/replicaset/scripts-configmap.yaml, bitnami/mongodb/templates/replicaset/statefulset.yaml, bitnami/mongodb/templates/standalone/dep-sts.yaml
Making use of `mongosh` instead of `mongo`. The output parsing has been adapted too
**Benefits**
- fixes #
**Checklist**
=> [bitnami/mongodb] feat: :wastebasket: Remove mongo references

bitnami/metallb/Chart.yaml, bitnami/metallb/templates/speaker/daemonset.yaml
Add a missing "context" argument to a `common.tplvalues.render` template call.
**Benefits**
The template is rendered correctly.
None
- fixes #9913
NA
**Checklist**
=> [bitnami/metallb] missing "context"

.vib/kibana/cypress/cypress.json, .vib/kibana/cypress/cypress/integration/kibana_spec.js, .vib/kibana/cypress/cypress/support/commands.js, .vib/kibana/vib-verify.json
Signed-off-by: alukic <alukic@vmware.com>
There was a major Kibana release which forces the CSP which is a problem for Cypress tests. We need to disable CSP so that the tests will run without issues.
Also, there are small changes in the UI which the tests need to adapt to. 
This is tested on the fork with the [following executions.](https://github.com/superaleks/charts/runs/6206267985?check_suite_focus=true)
=> [bitnami/kibana] Fix Kibana tests that started failing due to a major release

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/templates/postgresql/metrics-service.yaml
update metrics to match with servicemonitor selector
update metrics service to match with the serviceMonitor selector
add metrics postgresql metrics on prometheus
- fixes #9937
=> [bitnami/postgresql-ha] update metrics to match with servicemonitor

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/templates/_helpers.tpl
Fix wrong indentation of global labels in alertmanager
- fixes #9886
=> [bitnami/kube-prometheus] Fix alertmanaer global labels indentation

.vib/redis/replicas/goss/goss-master/goss.yaml, .vib/redis/replicas/goss/goss-replica/goss.yaml, .vib/redis/sentinel/goss/goss.yaml, .vib/redis/standalone/goss/goss.yaml, bitnami/redis/Chart.yaml
Signed-off-by: Rafael Rios Saavedra <rafael.rios.saavedra@gmail.com>
Fix redis sentinel testing
- fixes #
- [-] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [-] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
=> [bitnami/redis] Fix redis sentinel testing

bitnami/sonarqube/README.md
The README.md contained a typo, that prevents install.
Corrected misspelling of the bitnami/sonarqube chart name in the `helm install` command.
Was:
```
$ helm install my-release bitnami/sonarqubes
```
should be
```
$ helm install my-release bitnami/sonarqube
```
More people will be able to install sonarqube with less frustration.
None that I can think of, unless your attempting to limit the number of installs with this typo.
https://github.com/bitnami/charts/issues/9972
Running the type command resulted in:
```
Error: failed to download "bitnami/sonarqubes" (hint: running helm repo update may help)
```
Debugged using:
```
helm install --dry-run --debug my-release bitnami/sonarqubes
```
That produced a little more useful information:
```
Error: chart "sonarqubes" matching  not found in …
```
=> [bitnami/sonarqube] chart install had a misspelling in the README

bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/node/templates/deployment.yaml, bitnami/node/values.yaml
Add `startupProbe` to `bitnami/node`.
- fixes #9976
=> [bitnami/node] add startup probe

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/templates/prometheus-operator/clusterrole.yaml
Added new resource `prometheuses/status` to cluster role for prometheus-operator 
- fixes #9988
=> [bitnami/kube-prometheus] Added cluster role for prometheus-operator prometheuses/status

bitnami/jenkins/Chart.yaml, bitnami/jenkins/templates/deployment.yaml
- Modified the deployment.yaml template of the bitnami/jenkins chart: now it renders the value set under "sidecars" in the deployment.yaml and adds additional containers. 
- Bumped the jenkins chart version to 10.0.7
A possibility to add additional containers to the Jenkins Pod. 
none
- fixes #10020
=> [bitnami/jenkins] Render sidecars in the deployment.yaml template

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md
=> [bitnami/spring-cloud-dataflow] Update RabbitMQ subchart

bitnami/kubeapps/Chart.yaml, bitnami/kubeapps/README.md, bitnami/kubeapps/values.yaml
Signed-off-by: Michael Nelson <minelson@vmware.com>
In the change at:
https://github.com/bitnami/charts/pull/9441/files#diff-0f1b69af1b7c9c48d9d4f43c74fd880405aec305533aa650e1c26d7a2d20c300R1976-R1988
the values of the Kubeapps chart switched to reference the non-postgres
user rather than the postgres user which Kubeapps currently uses
I believe Kubeapps could switch to the normal (unprivileged) user (see https://github.com/vmware-tanzu/kubeapps/issues/4643), but currently it is using the postgres user throughout, so this change just restores our values.yaml to reflect that after @jorgemoralespou noticed that our README now mentions the non-priv'd user password rather than setting the postgres password.
Better documentation.
- reference #
=> [bitnami/kubeapps] Values references postgresPassword used by Kubeapps.

bitnami/redis/Chart.yaml, bitnami/redis/templates/master/pvc.yaml
Signed-off-by: Rafael Rios Saavedra <rafael.rios.saavedra@gmail.com>
fixes #10036
- fixes #10036 
- [-] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
=> [bitnami/redis] Fix PersistentVolumeClaim storage class indentation

template/CHART_NAME/templates/NOTES.txt, template/CHART_NAME/templates/clusterrolebinding.yaml, template/CHART_NAME/templates/configmap.yaml, template/CHART_NAME/templates/daemonset.yaml, template/CHART_NAME/templates/deployment.yaml, template/CHART_NAME/templates/ingress.yaml, template/CHART_NAME/templates/secret.yaml, template/CHART_NAME/templates/service.yaml, template/CHART_NAME/templates/statefulset.yaml, template/CHART_NAME/templates/tls-secret.yaml, template/CHART_NAME/values.yaml
Include in the scaffolding template the following changes:
* Ensure `namespace` is quoted
* Add `ingress.extraRules`
* Add `service.annotations`, `service.nodePorts` and `service.clusterIP`
* Don't set number of `replicas` if `autoscaling` is enabled
Ensure templates are up to date for new assets
=> [template] Update template with latest standardisation changes

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/secrets.yaml
It's a typo of a missing `$` reference in the `secrets` template.
Without this fix the template simply not renders:
```
executing \"rabbitmq/templates/secrets.yaml\" at <.Values.commonLabels>: nil pointer evaluating interface {}.commonLabels
```
- fixes #
=> [bitnami/rabbitmq] Fixed missing `$` in secrets

.vib/redis-cluster/goss/goss.yaml, .vib/redis-cluster/vib-verify.json
Adds Goss tests to the `bitnami/redis-cluster` chart.
**Benefits**
Ensuring higher quality of the Helm chart.
**Test results** - PASS
[Please see them in the history here](https://github.com/FraPazGal/charts/pull/8)
**Checklist**
=> [bitnami/redis-cluster] Add goss tests

bitnami/opencart/Chart.yaml, bitnami/opencart/README.md, bitnami/opencart/templates/deployment.yaml, bitnami/opencart/templates/externaldb-secrets.yaml, bitnami/opencart/templates/ingress.yaml, bitnami/opencart/templates/networkpolicy-backend-ingress.yaml, bitnami/opencart/templates/networkpolicy-egress.yaml, bitnami/opencart/templates/networkpolicy-ingress.yaml, bitnami/opencart/templates/pv.yaml, bitnami/opencart/templates/pvc.yaml, bitnami/opencart/templates/secrets.yaml, bitnami/opencart/templates/svc.yaml, bitnami/opencart/templates/tls-secrets.yaml, bitnami/opencart/values.yaml
=> [bitnami/opencart] Add missing namespace metadata

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/curator/cronjob.yaml, bitnami/elasticsearch/templates/metrics/deployment.yaml
I got the following errors:
```
$ helm template bitnami/elasticsearch --set curator.enabled=true
Error: YAML parse error on elasticsearch/templates/curator/cronjob.yaml: error converting YAML to JSON: yaml: line 53: did not find expected '-' indicator
Use --debug flag to render out invalid YAML
```
```
$ helm install test bitnami/elasticsearch --set metrics.enabled=true -n test --dry-run
Error: INSTALLATION FAILED: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec): unknown field "replicaCount" in io.k8s.api.apps.v1.DeploymentSpec
```
I corrected the bad identification.
I deleted the unnecessary character (]).
Fixed a bug in the metrics template. (replicas instead of replicaCount)
Fixes bugs in the …
=> [bitnami/elasticsearch] Curator cronjob and metrics deployment bugfixes

bitnami/common/Chart.yaml, bitnami/common/README.md, bitnami/common/templates/_capabilities.tpl
Signed-off-by: Miguel A. Cabrera Minagorri <devgorri@gmail.com>
Add function to calculate HPA API version.
- fixes #
=> [bitnami/common] Add common function for HPA api version

bitnami/fluentd/Chart.lock, bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/aggregator-hpa.yaml
=> [bitnami/fluentd] Use the new helper for HPA API version

bitnami/magento/Chart.lock, bitnami/magento/Chart.yaml, bitnami/magento/templates/hpa.yaml
=> [bitnami/magento] Use the new helper for HPA API version

bitnami/aspnet-core/Chart.lock, bitnami/aspnet-core/Chart.yaml, bitnami/aspnet-core/templates/hpa.yaml
=> [bitnami/aspnet-core] Use the new helper for HPA API version

bitnami/spark/Chart.lock, bitnami/spark/Chart.yaml, bitnami/spark/templates/hpa-worker.yaml
=> [bitnami/spark] Use the new helper for HPA API version

bitnami/nginx-intel/Chart.lock, bitnami/nginx-intel/Chart.yaml, bitnami/nginx-intel/templates/hpa.yaml
=> [bitnami/nginx-intel] Use the new helper for HPA API version

bitnami/osclass/Chart.lock, bitnami/osclass/Chart.yaml, bitnami/osclass/templates/hpa.yaml
=> [bitnami/osclass] Use the new helper for HPA API version

bitnami/nginx/Chart.lock, bitnami/nginx/Chart.yaml, bitnami/nginx/templates/hpa.yaml
=> [bitnami/nginx] Use the new helper for HPA API version

bitnami/kong/Chart.lock, bitnami/kong/Chart.yaml, bitnami/kong/README.md, bitnami/kong/templates/hpa.yaml, bitnami/kong/values.yaml
Signed-off-by: Miguel A. Cabrera Minagorri <devgorri@gmail.com>
- fixes #
=> [bitnami/kong] Use the new helper for HPA API version

bitnami/elasticsearch/Chart.lock, bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/coordinating/hpa.yaml, bitnami/elasticsearch/templates/data/hpa.yaml, bitnami/elasticsearch/templates/ingest/hpa.yaml, bitnami/elasticsearch/templates/master/hpa.yaml
=> [bitnami/elasticsearch] Use the new helper for HPA API version

bitnami/apache/Chart.lock, bitnami/apache/Chart.yaml, bitnami/apache/templates/hpa.yaml
=> [bitnami/apache] Use the new helper for HPA API version

bitnami/wordpress/Chart.lock, bitnami/wordpress/Chart.yaml, bitnami/wordpress/templates/hpa.yaml
=> [bitnami/wordpress] Use the new helper for HPA API version

.vib/jenkins/cypress/cypress.json, .vib/jenkins/cypress/cypress/fixtures/credentials.json, .vib/jenkins/cypress/cypress/fixtures/items.json, .vib/jenkins/cypress/cypress/fixtures/users.json, .vib/jenkins/cypress/cypress/integration/jenkins_spec.js, .vib/jenkins/cypress/cypress/integration/utils.js, .vib/jenkins/cypress/cypress/support/commands.js, .vib/jenkins/cypress/cypress/support/index.js, .vib/jenkins/goss/goss.yaml, .vib/jenkins/vib-publish.json, .vib/jenkins/vib-verify.json
Increasing the test coverage of the Jenkins Helm Chart by adding Cypress and Goss tests. 
Ensuring higher quality of the Helm charts
**Test results** - [PASS](https://github.com/joancafom/charts/pull/46)
=> [bitnami/jenkins] Add Jenkins Helm Chart tests

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/secrets.yaml
The merge call removed is not needed
Simplify code and avoid collateral errors.
=> [bitnami/mongodb] remove unnecessary merge call

bitnami/common/Chart.yaml, bitnami/common/templates/_capabilities.tpl
=> [bitnami/common] Differentiate between autoscaling v1beta1 and v1beta2

bitnami/wordpress/Chart.lock, bitnami/wordpress/Chart.yaml, bitnami/wordpress/templates/hpa.yaml
Signed-off-by: Miguel A. Cabrera Minagorri <devgorri@gmail.com>
- fixes #
=> [bitnami/wordpress] Fix HPA API version template usage

bitnami/argo-cd/Chart.lock, bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/repo-server/hpa.yaml, bitnami/argo-cd/templates/server/hpa.yaml
=> [bitnami/argo-cd] Use the new helper for HPA API version

bitnami/redis/Chart.lock, bitnami/redis/Chart.yaml, bitnami/redis/templates/replicas/hpa.yaml, bitnami/redis/templates/sentinel/hpa.yaml
=> [bitnami/redis] Use the new helper for HPA API version

bitnami/concourse/Chart.lock, bitnami/concourse/Chart.yaml, bitnami/concourse/templates/worker/horizontalpodautoscaler.yaml
=> [bitnami/concourse] Use the new helper for HPA API version

bitnami/memcached/Chart.yaml, bitnami/memcached/templates/hpa.yaml
=> [bitnami/memcached] Use the new helper for HPA API version

bitnami/nginx-ingress-controller/Chart.lock, bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/templates/controller-hpa.yaml
=> [bitnami/nginx-ingress-controller] Use the new helper for HPA API version

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/hpa.yaml
=> [bitnami/keycloak] Use the new helper for HPA API version

bitnami/odoo/Chart.lock, bitnami/odoo/Chart.yaml, bitnami/odoo/templates/hpa.yaml
=> [bitnami/odoo] Use the new helper for HPA API version

bitnami/minio/Chart.yaml, bitnami/minio/templates/gateway/hpa.yaml
Use the new helper in `common` and adapt HPA to be compatible with `autoscaling/v2`
Up-to-date components.
None, it is backwards compatible.
NA
NA
=> [bitnami/minio] Use the new helper for HPA API version

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md
Use latest major version of Kafka chart.
- fixes #
=> Update kafka dependency for spring-cloud-dataflow

.vib/wordpress-intel/vib-publish.json, .vib/wordpress-intel/vib-verify.json
Changes tested at https://github.com/FraPazGal/charts/pull/11
=> [bitnami/wp-intel] Add health-check to VIB pipelines

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/templates/hub/deployment.yaml
Fix indent in jupyter-hub hub extra annotations(possible ^c ^v issue).
- fixes #
=>  [bitnami/jupyterhub] Fix indent in annotations of hub deployment

bitnami/kiam/Chart.yaml, bitnami/kiam/README.md, bitnami/kiam/templates/agent/agent-service.yaml, bitnami/kiam/templates/server/server-service.yaml, bitnami/kiam/values.yaml
=> [bitnami/kiam] Add missing service parameter

bitnami/tomcat/Chart.yaml, bitnami/tomcat/README.md, bitnami/tomcat/templates/NOTES.txt, bitnami/tomcat/templates/_helpers.tpl, bitnami/tomcat/templates/podmonitor.yaml, bitnami/tomcat/templates/svc.yaml, bitnami/tomcat/values.yaml
=> [bitnami/tomcat] Add missing service parameter

bitnami/aspnet-core/Chart.yaml, bitnami/aspnet-core/README.md, bitnami/aspnet-core/templates/NOTES.txt, bitnami/aspnet-core/templates/svc.yaml, bitnami/aspnet-core/values.yaml
=> [bitnami/aspnet-core] Add missing service parameter

bitnami/dokuwiki/Chart.yaml, bitnami/dokuwiki/README.md, bitnami/dokuwiki/templates/NOTES.txt, bitnami/dokuwiki/templates/deployment.yaml, bitnami/dokuwiki/templates/svc.yaml, bitnami/dokuwiki/values.yaml
=> [bitnami/dokuwiki] Add missing service parameter

bitnami/logstash/Chart.yaml, bitnami/logstash/README.md, bitnami/logstash/values.yaml
Adds values implemented but missing in `values.yaml`
**Checklist**
=> [bitnami/logstash] Add missing values

bitnami/nats/Chart.yaml, bitnami/nats/README.md, bitnami/nats/templates/metrics-svc.yaml, bitnami/nats/templates/service.yaml, bitnami/nats/values.yaml
=> [bitnami/nats] Add missing service parameter

bitnami/redis/Chart.yaml, bitnami/redis/README.md, bitnami/redis/templates/master/service.yaml, bitnami/redis/templates/metrics-svc.yaml, bitnami/redis/templates/replicas/service.yaml, bitnami/redis/templates/sentinel/service.yaml, bitnami/redis/templates/sentinel/statefulset.yaml, bitnami/redis/values.yaml
=> [bitnami/redis] Add missing service parameter

bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/README.md, bitnami/sonarqube/templates/service.yaml, bitnami/sonarqube/values.yaml
=> [bitnami/sonarqube] Add missing service parameter

bitnami/wordpress-intel/Chart.yaml, bitnami/wordpress-intel/README.md, bitnami/wordpress-intel/templates/svc.yaml, bitnami/wordpress-intel/values.yaml
=> [bitnami/wordpress-intel] Add missing service parameter

bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md, bitnami/wordpress/templates/svc.yaml, bitnami/wordpress/values.yaml
=> [bitnami/wordpress] Add missing service parameter

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/README.md, bitnami/zookeeper/templates/NOTES.txt, bitnami/zookeeper/templates/svc.yaml, bitnami/zookeeper/values.yaml
=> [bitnami/zookeeper] Add missing service parameter

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/README.md, bitnami/redis-cluster/templates/redis-svc.yaml, bitnami/redis-cluster/values.yaml
=> [bitnami/redis-cluster] Add missing service parameter

bitnami/concourse/Chart.yaml, bitnami/concourse/README.md, bitnami/concourse/templates/web/gateway-service.yaml, bitnami/concourse/templates/web/service.yaml, bitnami/concourse/values.yaml
=> [bitnami/concourse] Add missing service parameter

bitnami/discourse/Chart.yaml, bitnami/discourse/README.md, bitnami/discourse/templates/service.yaml, bitnami/discourse/values.yaml
=> [bitnami/discourse] Add missing service parameter

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/README.md, bitnami/rabbitmq/values.yaml
BREAKING CHANGE.
This PR updates the default RabbitMQ branch to use 3.10.x, now that version is available. 
- fixes #
=> [bitnami/rabbitmq] feat!: :arrow_up: Bump default image to 3.10.x

bitnami/airflow/Chart.lock, bitnami/airflow/Chart.yaml, bitnami/airflow/templates/worker/horizontalpodautoscaler.yaml
=> [bitnami/airflow] Use the new helper for HPA API version

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/README.md, bitnami/jupyterhub/templates/hub/service.yaml, bitnami/jupyterhub/templates/hub/servicemonitor.yaml, bitnami/jupyterhub/templates/proxy/service-api.yaml, bitnami/jupyterhub/templates/proxy/service-metrics.yaml, bitnami/jupyterhub/templates/proxy/service-public.yaml, bitnami/jupyterhub/templates/proxy/servicemonitor.yaml, bitnami/jupyterhub/values.yaml
=> [bitnami/jupyterhub] Add missing service parameter

bitnami/grafana-tempo/Chart.yaml, bitnami/grafana-tempo/README.md, bitnami/grafana-tempo/templates/compactor/service.yaml, bitnami/grafana-tempo/templates/distributor/service.yaml, bitnami/grafana-tempo/templates/ingester/service.yaml, bitnami/grafana-tempo/templates/querier/service.yaml, bitnami/grafana-tempo/templates/query-frontend/service.yaml, bitnami/grafana-tempo/templates/vulture/service.yaml, bitnami/grafana-tempo/values.yaml
=> [bitnami/grafana-tempo] Add missing service parameter

.vib/solr/cypress/cypress/integration/solr_spec.js
Fix VIB tests for Solr 9 due to this change ([source](https://solr.apache.org/guide/solr/9_0/upgrade-notes/major-changes-in-solr-9.html)):
```
QueryResponse.getExplainMap() type has changed from Map<String, String> to Map<String, Object> in order to support structured explanations.
```
Cypress tests are fixed.
None
- fixes #
Graph ID: 6c779a7c-c3cd-4967-a336-184b80de737f
=> [bitnami/solr] Fix Cypress integration tests for Solr 9

bitnami/haproxy-intel/Chart.yaml
=> [bitnami/haproxy-intel] Fix Chart.yaml format

bitnami/sealed-secrets/Chart.yaml
=> [bitnami/sealed-secrets] Fix Chart.yaml format

bitnami/wavefront/Chart.lock, bitnami/wavefront/Chart.yaml, bitnami/wavefront/README.md
Updates bitnami/wavefront subchart dependency.
**Checklist**
=> [bitnami/wavefront] Update subchart dependency

bitnami/kube-prometheus/Chart.lock, bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/README.md
Updates bitnami/kube-prometheus subchart dependency.
**Checklist**
=> [bitnami/kube-prometheus] Update subchart dependency

bitnami/tomcat/Chart.yaml, bitnami/tomcat/README.md, bitnami/tomcat/values.yaml
=> [bitnami/tomcat] fix data type

bitnami/wavefront-adapter-for-istio/Chart.lock, bitnami/wavefront-adapter-for-istio/Chart.yaml, bitnami/wavefront-adapter-for-istio/README.md
Updates bitnami/wavefront-adapter-for-istio subchart dependency.
**Checklist**
=> [bitnami/wavefront-adapter-for-istio] Update subcharts deps

bitnami/kafka/Chart.yaml, bitnami/kafka/README.md
=> [bitnami/kafka] Fix link in README

.vib/mongodb/goss/goss.yaml, .vib/mongodb/vib-publish.json, .vib/mongodb/vib-verify.json
Increasing the test coverage of the Postgres Helm Chart by adding Goss tests. 
**Benefits**
Ensuring higher quality of the Helm charts.
**Test results**
:gear: - [PASS](https://github.com/joancafom/charts/pull/49)
=> [bitnami/mongodb] Add MongoDB Helm Chart tests

.vib/nginx-intel/vib-publish.json, .vib/node-exporter/vib-publish.json
Sync `vib-verify.json` and `vib-publish.json` information to ensure the same parameters and steps are used in the two phases.
Consistent verification and publishing pipelines for VMware Image Builder.
None
NA
The inconsistencies were introduced in:
- nginx-intel: https://github.com/bitnami/charts/pull/10180
- node-exporter: https://github.com/bitnami/charts/pull/10250
=> [bitnami/*] Ensure vib-publish and vib-verify pipelines are synced

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/secrets.yaml
Fixing prepend the namespace that was broken from refactoring the chart. 
- fixes #10290
=> [bitnami/rabbitmq] fix: extraSecretsPrependReleaseName

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/templates/controller-hpa.yaml
Remove version condition to set the `apiVersion` in the `HorizontalPodAutoscaler`. That logic was moved to the `common.capabilities.hpa.apiVersion` helper
- fixes #10532
=> [bitnami/nginx-ingress-controller] Remove version condition in HPA

bitnami/node/Chart.yaml, bitnami/node/README.md, bitnami/node/values.yaml
Fixes the default value for `tolerations` and `topologySpreadConstraints`.
None.
None
=> [bitnami/node] Fix tolerations and topologySpreadConstraints default values

bitnami/solr/Chart.yaml, bitnami/solr/README.md, bitnami/solr/templates/metrics-deployment.yaml, bitnami/solr/values.yaml
This PR removes the hardcoding of the solr-exporter path so the chart can be used with different Solr major versions.
- fixes https://github.com/bitnami/charts/issues/10504
=> [bitnami/solr] fix: :bug: Do not hardcode solr-exporter path

bitnami/grafana-loki/Chart.yaml, bitnami/grafana-loki/README.md, bitnami/grafana-loki/templates/NOTES.txt, bitnami/grafana-loki/templates/promtail/clusterrole.yaml, bitnami/grafana-loki/templates/promtail/clusterrolebinding.yaml, bitnami/grafana-loki/templates/promtail/daemonset.yaml, bitnami/grafana-loki/templates/promtail/secret.yaml, bitnami/grafana-loki/templates/promtail/service-account.yaml, bitnami/grafana-loki/templates/promtail/service.yaml, bitnami/grafana-loki/templates/promtail/servicemonitor.yaml, bitnami/grafana-loki/values.yaml
Availability for enable or disable promtail daemonset deployment
- fixes #
=> [bitnami/grafana-loki] promtail deploy

bitnami/grafana-tempo/Chart.yaml, bitnami/grafana-tempo/README.md, bitnami/grafana-tempo/templates/_helpers.tpl, bitnami/grafana-tempo/templates/metrics-generator/deployment.yaml, bitnami/grafana-tempo/templates/metrics-generator/service.yaml, bitnami/grafana-tempo/templates/metrics-generator/servicemonitor.yaml, bitnami/grafana-tempo/values.yaml
Signed-off-by: Artem Belov <artem.belov@pm.bet>
New service metrics-generator was added
Metrics-generator deployment can collect metrics from your spans
- fixes #
=> [bitnami/grafana-tempo] Add metrics-generator service

bitnami/etcd/Chart.yaml, bitnami/etcd/README.md, bitnami/etcd/templates/statefulset.yaml, bitnami/etcd/values.yaml
Signed-off-by: Michael Sidorov <mixity@yandex.ru>
Added runtimeClass value
Possibility to specify runtime classes, which is extremely useful for environments with multiple runtime classes enabled
Application might not be compatible with some certain runtime classes
- fixes #10682
=> [bitnami/etcd] add runtime class support

bitnami/cert-manager/Chart.yaml, bitnami/cert-manager/README.md, bitnami/cert-manager/templates/cainjector/deployment.yaml, bitnami/cert-manager/templates/controller/deployment.yaml, bitnami/cert-manager/templates/webhook/deployment.yaml, bitnami/cert-manager/values.yaml
Signed-off-by: Michael Sidorov <mixity@yandex.ru>
Added runtimeClass value
Possibility to specify runtime classes, which is extremely useful for environments with multiple runtime classes enabled
Application might not be compatible with some certain runtime classes
- fixes #10682
=> [bitnami/cert-manager] add runtime class support

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/README.md, bitnami/argo-cd/templates/application-controller/deployment.yaml, bitnami/argo-cd/templates/dex/deployment.yaml, bitnami/argo-cd/templates/repo-server/deployment.yaml, bitnami/argo-cd/templates/server/deployment.yaml, bitnami/argo-cd/values.yaml
Signed-off-by: Michael Sidorov <mixity@yandex.ru>
Added runtimeClass value
Possibility to specify runtime classes, which is extremely useful for environments with multiple runtime classes enabled
Application might not be compatible with some certain runtime classes
- fixes #10682
=> [bitnami/argo-cd] add runtime class support

bitnami/argo-workflows/Chart.yaml, bitnami/argo-workflows/README.md, bitnami/argo-workflows/values.yaml
=> [bitnami/argo-workflows] fix: :bug: Use proper type for sidecars and init containers

bitnami/pinniped/Chart.yaml, bitnami/pinniped/README.md, bitnami/pinniped/values.yaml
=> [bitnami/pinniped] fix: :bug: Use proper type for sidecars and init containers

bitnami/pytorch/Chart.yaml, bitnami/pytorch/README.md, bitnami/pytorch/values.yaml
=> [bitnami/pytorch] fix: :bug: Use proper type for sidecars and init containers

bitnami/sealed-secrets/Chart.yaml, bitnami/sealed-secrets/values.yaml
=> [bitnami/sealed-secrets] fix: :bug: Use proper type for sidecars and init containers

bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/README.md, bitnami/sonarqube/values.yaml
=> [bitnami/sonarqube] fix: :bug: Use proper type for sidecars and init containers

bitnami/solr/Chart.lock, bitnami/solr/Chart.yaml, bitnami/solr/README.md
Updates the Zookeeper subchart to its latest version 10.0.0.
=> [bitnami/solr] Update Zookeeper major

bitnami/contour/Chart.yaml, bitnami/contour/README.md
fix the mismatch between README.md and values.yaml in the contour chart
- fixes #
=> [bitnami/contour] fix the mismatch between README.md and values.yaml

README.md
This change is about explaining to the users the limitations of the Bitnami Charts index limitations and alternatives where they can find a full index.
Provide a better explanation about Bitnami Charts repository.
=> [bitnami/*] Note about truncated and full index branches.

bitnami/pinniped/Chart.yaml
=> [bitnami/pinniped] Change maintainers

.github/workflows/archive-full-index.yaml
Fix problem during Bitnami bot authentication when checking out the `archive-full-index` branch.
=> [bitnami/Index] Fix bot authentication

bitnami/dokuwiki/Chart.yaml, bitnami/dokuwiki/README.md, bitnami/dokuwiki/values.yaml, bitnami/odoo/Chart.yaml, bitnami/odoo/README.md, bitnami/odoo/values.yaml, bitnami/wordpress-intel/Chart.yaml, bitnami/wordpress-intel/README.md, bitnami/wordpress-intel/values.yaml, bitnami/wordpress/values.yaml, template/CHART_NAME/values.yaml
Remove mentions to Debian 10 Buster since it was replaced by Debian 11 Bullseye
=> [bitnami/*] Remove debian-10 mentions 

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/curator/configmap.yaml
=> [bitnami/elasticsearch] Add templating to curator config action file

bitnami/kube-prometheus/Chart.lock, bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/crds/crd-alertmanager-config.yaml, bitnami/kube-prometheus/crds/crd-alertmanager.yaml, bitnami/kube-prometheus/crds/crd-podmonitor.yaml, bitnami/kube-prometheus/crds/crd-probes.yaml, bitnami/kube-prometheus/crds/crd-prometheus.yaml, bitnami/kube-prometheus/crds/crd-prometheusrules.yaml, bitnami/kube-prometheus/crds/crd-servicemonitor.yaml, bitnami/kube-prometheus/crds/crd-thanosrulers.yaml, bitnami/kube-prometheus/values.yaml
Update-prometheus-operator-CRDs to version 0.57.0
Fixes #10860
=> [bitnami/kube-prometheus] Update prometheus operator CRDs

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/common-scripts-cm.yaml
Fix a bug in the MongoDB version check condition which
caused versions 5.[0-3].[0-1] to be evaluated incorrectly,
and to use the deprecated db.isMaster() functionality.
Signed-off-by: Sheldon Roddick <sheldon.roddick@hotmail.com>
- fixes #
=> [bitnami/mongodb] Readiness Probe bug fix

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/README.md, bitnami/rabbitmq/templates/statefulset.yaml
This PR reverts statefulset changes merged in #10042 
PR #10042 changes the name of rabbitmq nodes and could wipe existing data.
=> [bitnami/rabbitmq] Reverts "Use short DNS names for clustering" 

bitnami/cert-manager/Chart.yaml, bitnami/cert-manager/README.md, bitnami/cert-manager/templates/cainjector/deployment.yaml, bitnami/cert-manager/templates/controller/deployment.yaml, bitnami/cert-manager/templates/webhook/deployment.yaml, bitnami/cert-manager/values.yaml
- adds support for extra arguments
- fixes #8569
=> [bitnami/cert-manager] add extraArgs support

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/cd-pipeline.yaml, .github/workflows/ci-pipeline.yaml
We should not force a version bump when we are performing changes in just markdown files. This PR will add an improvement in our CI/CD costs.
- fixes #
=> [bitnami/*] ci: :construction_worker: Skip ci-pipeline workflow if the changes are only in markdown files

bitnami/argo-cd/README.md
Applied trailing whitespace remover.
- fixes #
=> [bitnami/argo-cd] docs: :memo: Remove unnecessary whitespace

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/_helpers.tpl, bitnami/airflow/templates/config/configmap.yaml, bitnami/airflow/templates/scheduler/deployment.yaml
(according https://helm.sh/docs/chart_template_guide/function_list/#contains)
- fixes #
=> [bitnami/airflow] update contains args order

.vib/consul/vib-publish.json
Use the correct path to GOSS tests for consul.
- GOSS tests can be executed
- Publish action does not fail
None.
NA
NA
=> [bitnami/consul] Fix GOSS publishing pipeline

bitnami/magento/Chart.lock, bitnami/magento/Chart.yaml, bitnami/magento/README.md
Updates the Elasticsearch subchart to its latest version
=> [bitnami/magento] Major version: Update Elasticsearch subchart

bitnami/wavefront/Chart.yaml
This PR just updates the logo URL as we were using an outdated one.
This asset will have the proper logo.
N/A
N/A
N/A
=> [bitnami/wavefront] Fix icon URL

bitnami/argo-workflows/Chart.yaml
This PR just updates the logo URL as we were using an outdated one.
This asset will have the proper logo.
N/A
N/A
N/A
=> [bitnami/argo-workflows] Fix icon URL

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/templates/svc-headless.yaml
…nd not set the configuration of  service.annotations,the configuration of service.headless.annitations  is inoperative
Signed-off-by: wanggy <717338097@qq.com>
I replace  `{{- if or .Values.commonAnnotations .Values.service.annotations }}` with `{{- if or .Values.commonAnnotations .Values.service.headless.annotations }} `  in svc-headless.yaml.
N/A
N/A
N/A
- fixes #
N/A
=> [bitnami/zookeeper] fix - service.headless.annitations  is inoperative when i  do not set the configuration of service.annotations

bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/certificate.yaml
Signed-off-by: Eugen Fohlenweider <eugen.fohlenweider@hotmail.com>
This will add an CommonName to the self-signed certificate in the rabbitmq-cluster-operator chart when using cert-manager by adding the value `useCertManager: true`.
When cert-manager is creating the certificate it will also log an event saying `Certificate will be issued with an empty Issuer DN, which contravenes RFC 5280 and could break some strict clients`.
When helm is generating those certificates on it's own it will also add the fullname of the messaging-topology-operator as CN.
There are no.
- fixes #
=> [bitnami/rabbitmq-cluster-operator] add commonName to the rabbitmq-operator certificate

bitnami/fluentd/Chart.yaml
=> [bitnami/fluentd] Prettify and unify Chart.yaml

bitnami/grafana-loki/Chart.yaml
=> [bitnami/grafana-loki] Prettify and unify Chart.yaml

bitnami/oauth2-proxy/Chart.yaml
=> [bitnami/oauth2-proxy] Prettify and unify Chart.yaml

bitnami/metallb/Chart.yaml
=> [bitnami/metallb] Prettify and unify Chart.yaml

bitnami/kubeapps/Chart.yaml
=> [bitnami/kubeapps] Prettify and unify Chart.yaml

bitnami/phpmyadmin/Chart.yaml
Prettify the _Chart.yaml_ file following the same order and structure used in all that appear in this repository.
=> [bitnami/phpmyadmin] Prettify and unify Chart.yaml

bitnami/grafana-loki/Chart.yaml
This PR bumps `bitnami/grafana-loki` to fix the issue of https://github.com/bitnami/charts/commit/91c55a24369d2bf9dd951f8dc02ec896a043f89e, where GitHub incorrectly checked the changes from https://github.com/bitnami/charts/pull/11126 with `master` branch. Even if the PR says a bump to the `Chart.yaml` version is made, when the changes are merged the bump is not performed. This is because that same bump was performed in a previous PR (https://github.com/bitnami/charts/pull/11219).
The latest chart changes are published.
=> [bitnami/grafana-loki] Bump chart version

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/secrets.yaml
Signed-off-by: wanggy <717338097@qq.com>
elasticsearch/templates/secret.yaml
- fixes #
the key of truststore-password  and keystore-password is reversed
=> [bitnami/elasticsearch] fix elasticsearch tls secret

bitnami/keycloak/README.md
Several users are trying to use our keycloak chart with non PostgreSQL database. Only PostgreSQL is supported for external database configuration at the moment and the documentation should mention it.
Document current limitation.
None detected
- fixes #11209
=> [bitnami/keycloak] Update documentation about external database configuration

.github/workflows/.env
Signed-off-by: Marcos Bjoerkelund <marcosbd@vmware.com>
- fixes #
=> Add marcosbc to support assignation

bitnami/mariadb/Chart.yaml, bitnami/mariadb/README.md, bitnami/mariadb/templates/_helpers.tpl, bitnami/mariadb/values.yaml
Same https://github.com/bitnami/charts/pull/11167 but for mariadb
=> [bitnami/mariadb] Allow custom name of database role

.github/workflows/cd-pipeline.yaml
Followup of https://github.com/bitnami/charts/pull/11328
=> [bitnami/dataplatform-bp2] Add dataplatform-bp2 to cd-pipeline.yaml

.github/workflows/triage.yml
Simplify condition for triage workflow
- fixes #
=> [bitnami/*] Simplify condition for triage workflow

.vib/jenkins/cypress/cypress/integration/jenkins_spec.js, bitnami/jenkins/Chart.lock, bitnami/jenkins/Chart.yaml, bitnami/jenkins/README.md, bitnami/jenkins/values.yaml
Update test for the new version of Jenkins.
- fixes #
=> [bitnami/jenkins] Update new version of Jenkins 2.346.2

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/configmap.yaml
Sync `redis-default.conf` file with [upstream file](https://download.redis.io/redis-stable/redis.conf).
Our configuration for redis-cluster is in sync with upstream.
Not expected.
=> [bitnami/redis-cluster] Update redis-default config

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/receive/statefulset.yaml
This change is to conditionally set objstore arg and OBJSTORE_CONFIG for Thanos receive 
If Thanos receive was deployed without object store config setting the objstore arg and OBJSTORE_CONFIG will lead to an error 
Allow Thanos receive to run without object store config
I tested this change on Thanos receive only and it's only affecting Thanos receive
- fixes #11272
=> [bitnami/thanos] Conditionally Set objstore arg and OBJSTORE_CONFIG for Thanos receive

.vib/consul/cypress/cypress/integration/consul_spec.js, .vib/consul/goss/goss.yaml, .vib/consul/goss/vars.yaml, .vib/consul/vib-publish.json, .vib/consul/vib-verify.json
=> [bitnami/consul] Revisit Goss/Cypress tests 

.vib/mariadb/goss/goss.yaml, .vib/mariadb/goss/vars.yaml, .vib/mariadb/vib-publish.json, .vib/mariadb/vib-verify.json
=> [bitnami/mariadb] Revisit GOSS tests

.vib/discourse/cypress/cypress/fixtures/user-settings.json, .vib/discourse/cypress/cypress/fixtures/users.json, .vib/discourse/cypress/cypress/integration/discourse_spec.js, .vib/discourse/cypress/cypress/support/commands.js, .vib/discourse/goss/goss.yaml, .vib/discourse/goss/vars.yaml, .vib/discourse/vib-publish.json, .vib/discourse/vib-verify.json
=> [bitnami/discourse] Revisit Goss/Cypress tests

bitnami/contour-operator/Chart.lock, bitnami/contour-operator/Chart.yaml, bitnami/contour-operator/README.md, bitnami/contour-operator/templates/auth-proxy-clusterrole.yaml, bitnami/contour-operator/templates/auth-proxy-clusterrolebinding.yaml, bitnami/contour-operator/templates/clusterrole.yaml, bitnami/contour-operator/templates/metrics-clusterrole.yaml, bitnami/contour-operator/templates/metrics-clusterrolebinding.yaml, bitnami/contour-operator/values.yaml
This PR adds missing RBAC objects taken from the new upstream 1.22.0 version.
- fixes #
=> [bitnami/contour] feat!: :arrow_up: Bump to 1.22.0

.vib/elasticsearch/cypress/cypress/integration/elasticsearch_spec.js, .vib/elasticsearch/goss/goss.yaml, .vib/elasticsearch/goss/vars.yaml, .vib/elasticsearch/vib-publish.json, .vib/elasticsearch/vib-verify.json
=> [bitnami/elasticsearch] Revisit Goss/Cypress tests

.vib/joomla/cypress/cypress/fixtures/users.json, .vib/joomla/cypress/cypress/integration/joomla_spec.js, .vib/joomla/goss/goss.yaml, .vib/joomla/goss/vars.yaml, .vib/joomla/vib-publish.json, .vib/joomla/vib-verify.json
=> [bitnami/joomla] Revisit Goss/Cypress tests

bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/templates/deployment.yaml
Runs sysctl container as a privileged user
=> [bitnami/sonarqube] Sonarqube pipeline fails using sysctl on a non-root container

bitnami/parse/Chart.lock, bitnami/parse/Chart.yaml, bitnami/parse/README.md
=> [bitnami/parse] Update MongoDB subchart for parse

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/scripts-configmap.yaml
In https://github.com/bitnami/charts/pull/11569 a typo was introduced. This PR corrects the used path for the logs used by the `setup.sh` script.
- fixes #11569
=> [bitnami/kafka] Fix typo introduced in #11569

bitnami/schema-registry/Chart.yaml
I've noticed a typo in the icon URL, so it was targeting a non-existent file. Also, the chart didn't have a category (which could be ok, but I wasn't sure). This PR simply to point to the proper icon URL and add a category for the `schema-registry` chart
N/A
N/A
N/A
=> [bitnami/schema-registry] Fix logo and category

.vib/zookeeper/goss/goss.yaml, .vib/zookeeper/goss/vars.yaml, .vib/zookeeper/vib-publish.json, .vib/zookeeper/vib-verify.json, bitnami/zookeeper/Chart.yaml
Adding the tests for the Zookeeper Helm chart.
When someone makes a change in the Helm Chart, they will be able to check if their change has broken the Helm chart by running these automated tests.
=> [bitnami/zookeeper] Add Zookeeper Helm Chart tests

bitnami/redmine/Chart.yaml, bitnami/redmine/templates/deployment.yaml
Signed-off-by: Morgan Christiansson <git@mog.se>
Fix error
```
YAML parse error on redmine/templates/deployment.yaml: error converting YAML to JSON: yaml: line 61: did not find expected node content
```
=> [bitnami/redmine] Fix helm syntax error

bitnami/contour/README.md
Signed-off-by: Wilson Wu <iwilsonwu@gmail.com>
Update the README file as same as the latest version of values.yaml
No confuse getting information from README file
=> [bitnami/contour] Sync 9.0.2 Values to README

.vib/schema-registry/cypress/cypress.json, .vib/schema-registry/cypress/cypress/fixtures/config.json, .vib/schema-registry/cypress/cypress/fixtures/schema.json, .vib/schema-registry/cypress/cypress/integration/schema_registry_spec.js, .vib/schema-registry/goss/goss.yaml, .vib/schema-registry/goss/vars.yaml, .vib/schema-registry/vib-publish.json, .vib/schema-registry/vib-verify.json
Adds Goss and Cypress tests for the Schema Registry chart.
Tests have been executed in this PR in my fork: https://github.com/migruiz4/charts/pull/1
=> [bitnami/schema-registry] Add Goss/Cypress tests

.github/workflows/srp-report.yml
Add new scheduled workflow to build and submit the Secure Release Pipeline report.
None
None
=> Add new workflow for SRP report

bitnami/contour/README.md
Signed-off-by: Wilson Wu <iwilsonwu@gmail.com>
Sync release 9.0.3 values to README
Make document good.
=> [bitnami/contour] Sync release 9.0.3 values to README

bitnami/postgresql/Chart.yaml, bitnami/postgresql/README.md, bitnami/postgresql/templates/_helpers.tpl, bitnami/postgresql/values.yaml
Same https://github.com/bitnami/charts/pull/11167 but for postgresql
=> [bitnami/postgresql] Allow custom role name for postgresql

.vib/keycloak/cypress/cypress/fixtures/admins.json, .vib/keycloak/cypress/cypress/fixtures/identity-providers.json, .vib/keycloak/cypress/cypress/fixtures/smtps.json, .vib/keycloak/cypress/cypress/integration/keycloak_spec.js, .vib/keycloak/cypress/cypress/support/commands.js, .vib/keycloak/goss/goss.yaml, .vib/keycloak/goss/vars.yaml, .vib/keycloak/vib-publish.json, .vib/keycloak/vib-verify.json
=> [bitnami/keycloak] Revisit Goss/Cypress tests

.vib/magento/cypress/cypress/integration/magento_spec.js, .vib/magento/cypress/cypress/support/commands.js, .vib/magento/cypress/cypress/support/utils.js, .vib/magento/goss/goss.yaml
=> [bitnami/magento] Revisit tests

bitnami/logstash/Chart.yaml, bitnami/logstash/templates/headless-svc.yaml
adjust the naming style for `headless-svc` to  make it not pass the length limit
- fixes #
=> [bitnami/logstash] Adjust the naming style for resource/headless-svc

bitnami/redis/Chart.yaml, bitnami/redis/templates/scripts-configmap.yaml
Sentinel parameters order matter in v7. This PR is to fix it.
Fix issue: #11565
- fixes #11565
=> [bitnami/redis] Fix sentinel start command parameters order

.github/workflows/cd-pipeline.yaml
Add Bitnami Joomla Helm Chart to the list of assets published using VMware Image Builder.
Increased pool of assets completely handled by VMware Image Builder.
None
NA
We have already implemented GOSS & Cypress tests for this asset, see [.vib/joomla](https://github.com/bitnami/charts/tree/master/.vib/joomla)
=> [bitnami/joomla] Publish using VIB

bitnami/elasticsearch/Chart.yaml
Version 19.1.10 was released with changes described in #11738. In the PR #11632 we used the same version, so the release 19.1.10 has no the changes from #11632
Force a new release with the changes from #11632
None
=> [bitnami/elasticsearch] Release 19.1.11

bitnami/common/Chart.yaml, bitnami/common/templates/_images.tpl
Revert changes from #11797 due to the issue introduced described at #11828
- Fixes #11828
=> Revert changes from #11797

bitnami/common/Chart.yaml, bitnami/common/templates/_images.tpl
Same changes as https://github.com/bitnami/charts/pull/11797 but bumping the chart version in a major after the issue reported at https://github.com/bitnami/charts/issues/11828
=> [bitnami/common] MAJOR: Add support for image digest apart from tag

bitnami/nginx/Chart.yaml, bitnami/nginx/templates/ingress.yaml
If set `ingress.hostname` to wildcard, e.g. ***.example.com** error occurs `YAML parse error on nginx/templates/ingress.yaml: error converting YAML to JSON: yaml: line 17: did not find expected alphabetic or numeric character`. Add quotes for hostname in ingress for using wildcard
Wildcard usage
None
None
=> [bitnami/nginx] quote hostname on ingress

bitnami/nats/Chart.yaml, bitnami/nats/templates/NOTES.txt, bitnami/nats/templates/headless-svc.yaml, bitnami/nats/templates/ingress.yaml, bitnami/nats/templates/metrics-svc.yaml, bitnami/nats/templates/servicemonitor.yaml, bitnami/nats/templates/statefulset.yaml, bitnami/nats/templates/tls-secret.yaml
Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)
- fixes #
=> [bitnami/nats] Adjust the naming style for resources

.vib/pinniped/vib-publish.json, .vib/pinniped/vib-verify.json
VIB's deployment fails in it's deployment because one of the exposed endpoints, the service going by `pinniped-concierge-impersonation-proxy-load-balancer`, does not return a valid response. Changed the `concierge.credentialIssuerConfig` value used in the VIB pipelines to deploy a `ClusterIP` service instead of a `LoadBalancer` one.
This error appeared when the value of `VIB_ENV_TARGET_PLATFORM` in GH was changed from TKG to GKE. Given TKG limitations, the impersonation-proxy was not been deployed, which made the deployment succeed.
VIB pipelines for `bintami/pinniped` succeed and related PRs are unblocked.
None
Tested in https://github.com/FraPazGal/charts/pull/79
=> [bitnami/pinniped] Fix VIB health-check

bitnami/grafana/Chart.yaml, bitnami/grafana/templates/service.yaml
Signed-off-by: lynchmaniac <lynchmaniac@gmail.com>
This PR is to fix https://github.com/bitnami/charts/issues/11791
commonAnnotations is now appears in service
- fixes #11791
=> [bitnami/grafana] Fix - missing commonAnnotations in service

bitnami/haproxy/Chart.yaml, bitnami/haproxy/templates/_helpers.tpl
drop `-foo` suffix  from the default serviceaccount name
consistency with the other charts
serviceaccount name change
- fixes #
=> [bitnami/haproxy] drop -foo suffix from default serviceaccount name

bitnami/redmine/Chart.lock, bitnami/redmine/Chart.yaml
=> [bitnami/redmine] Update Chart.lock

bitnami/parse/Chart.lock, bitnami/parse/Chart.yaml
=> [bitnami/parse] Update Chart.lock

bitnami/node/Chart.lock, bitnami/node/Chart.yaml
=> [bitnami/node] Update Chart.lock

bitnami/kafka/Chart.lock, bitnami/kafka/Chart.yaml
=> [bitnami/kafka] Update Chart.lock

bitnami/phpbb/Chart.lock, bitnami/phpbb/Chart.yaml
=> [bitnami/phpbb] Update Chart.lock

bitnami/joomla/Chart.lock, bitnami/joomla/Chart.yaml
=> [bitnami/joomla] Update Chart.lock

bitnami/haproxy-intel/Chart.lock, bitnami/haproxy-intel/Chart.yaml
=> [bitnami/haproxy-intel] Update Chart.lock

bitnami/ejbca/Chart.lock, bitnami/ejbca/Chart.yaml
=> [bitnami/ejbca] Update Chart.lock

bitnami/argo-workflows/Chart.lock, bitnami/argo-workflows/Chart.yaml
=> [bitnami/argo-workflows] Update Chart.lock

bitnami/elasticsearch/Chart.lock, bitnami/elasticsearch/Chart.yaml
=> [bitnami/elasticsearch] Update Chart.lock

bitnami/grafana-loki/Chart.lock, bitnami/grafana-loki/Chart.yaml
=> [bitnami/grafana-loki] Update Chart.lock

bitnami/argo-cd/Chart.lock, bitnami/argo-cd/Chart.yaml
=> [bitnami/argo-cd] Update Chart.lock

bitnami/etcd/Chart.lock, bitnami/etcd/Chart.yaml
=> [bitnami/etcd] Update Chart.lock

bitnami/solr/Chart.lock, bitnami/solr/Chart.yaml
=> [bitnami/solr] Update Chart.lock

bitnami/sonarqube/Chart.lock, bitnami/sonarqube/Chart.yaml
=> [bitnami/sonarqube] Update Chart.lock

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml
=> [bitnami/spring-cloud-dataflow] Update Chart.lock

bitnami/thanos/Chart.lock, bitnami/thanos/Chart.yaml
=> [bitnami/thanos] Update Chart.lock

bitnami/kube-prometheus/Chart.lock, bitnami/kube-prometheus/Chart.yaml
=> [bitnami/kube-prometheus] Update Chart.lock

bitnami/schema-registry/Chart.lock, bitnami/schema-registry/Chart.yaml
=> [bitnami/schema-registry] Update Chart.lock

bitnami/wavefront/Chart.lock, bitnami/wavefront/Chart.yaml
=> [bitnami/wavefront] Update Chart.lock

bitnami/magento/Chart.lock, bitnami/magento/Chart.yaml
=> [bitnami/magento] Update Chart.lock

bitnami/kong/Chart.lock, bitnami/kong/Chart.yaml
=> [bitnami/kong] Update Chart.lock

bitnami/etcd/Chart.lock, bitnami/etcd/Chart.yaml
This PR bumps the bitnami/common version to the next major. There are no expected changes since the subchart contains the same changes
=> [bitnami/etcd] Bump bitnami/common major version

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/compactor/ingress.yaml
Signed-off-by: Jens Heremans <jensheremans@gmail.com>
Fixed conditional around Thanos compactor ingressclassname. It referenced a bucketweb value instead of the appropriate compactor value.
ingressClassName will be defined as expected
None
None
=> [bitnami/thanos] Fix thanos compactor ingressclassname conditional

bitnami/rabbitmq-cluster-operator/README.md
Adds instructions on how to update the CRDs in the chart, as helm upgrade does not have support for CRD upgrade
- fixes #
=> [bitnami/rabbitmq-cluster-operator] docs: :memo: Add CRD upgrade instructions

.github/workflows/cd-pipeline.yaml, .vib/memcached/goss/goss.yaml, .vib/memcached/goss/vars.yaml, .vib/memcached/vib-publish.json, .vib/memcached/vib-verify.json
The main objective of this PR is to publish our Bitnami Memcached Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
Tested in https://github.com/FraPazGal/charts/pull/77
=> [bitnami/memcached] Add Helm Chart tests

bitnami/pinniped/Chart.lock, bitnami/pinniped/Chart.yaml
=> [bitnami/pinniped] Update Chart.lock

bitnami/postgresql-ha/Chart.lock, bitnami/postgresql-ha/Chart.yaml
=> [bitnami/postgresql-ha] Update Chart.lock

bitnami/postgresql/Chart.lock, bitnami/postgresql/Chart.yaml
=> [bitnami/postgresql] Update Chart.lock

bitnami/pytorch/Chart.lock, bitnami/pytorch/Chart.yaml
=> [bitnami/pytorch] Update Chart.lock

bitnami/rabbitmq/Chart.lock, bitnami/rabbitmq/Chart.yaml
=> [bitnami/rabbitmq] Update Chart.lock

bitnami/redis/Chart.lock, bitnami/redis/Chart.yaml
=> [bitnami/redis] Update Chart.lock

bitnami/sealed-secrets/Chart.lock, bitnami/sealed-secrets/Chart.yaml
=> [bitnami/sealed-secrets] Update Chart.lock

bitnami/spark/Chart.lock, bitnami/spark/Chart.yaml
=> [bitnami/spark] Update Chart.lock

bitnami/tomcat/Chart.lock, bitnami/tomcat/Chart.yaml
=> [bitnami/tomcat] Update Chart.lock

bitnami/wildfly/Chart.lock, bitnami/wildfly/Chart.yaml
=> [bitnami/wildfly] Update Chart.lock

bitnami/zookeeper/Chart.lock, bitnami/zookeeper/Chart.yaml
=> [bitnami/zookeeper] Update Chart.lock

bitnami/grafana/Chart.lock, bitnami/grafana/Chart.yaml
=> [bitnami/grafana] Update Chart.lock

bitnami/grafana-operator/Chart.lock, bitnami/grafana-operator/Chart.yaml
=> [bitnami/grafana-operator] Update Chart.lock

bitnami/influxdb/Chart.lock, bitnami/influxdb/Chart.yaml
=> [bitnami/influxdb] Update Chart.lock

bitnami/jenkins/Chart.lock, bitnami/jenkins/Chart.yaml
=> [bitnami/jenkins] Update Chart.lock

bitnami/kiam/Chart.lock, bitnami/kiam/Chart.yaml
=> [bitnami/kiam] Update Chart.lock

bitnami/kibana/Chart.lock, bitnami/kibana/Chart.yaml
=> [bitnami/kibana] Update Chart.lock

bitnami/logstash/Chart.lock, bitnami/logstash/Chart.yaml
=> [bitnami/logstash] Update Chart.lock

bitnami/metallb/Chart.lock, bitnami/metallb/Chart.yaml
=> [bitnami/metallb] Update Chart.lock

bitnami/metrics-server/Chart.lock, bitnami/metrics-server/Chart.yaml
=> [bitnami/metrics-server] Update Chart.lock

bitnami/minio/Chart.lock, bitnami/minio/Chart.yaml
=> [bitnami/minio] Update Chart.lock

bitnami/mongodb/Chart.lock, bitnami/mongodb/Chart.yaml
=> [bitnami/mongodb] Update Chart.lock

bitnami/mxnet/Chart.lock, bitnami/mxnet/Chart.yaml
=> [bitnami/mxnet] Update Chart.lock

bitnami/mysql/Chart.lock, bitnami/mysql/Chart.yaml
=> [bitnami/mysql] Update Chart.lock

bitnami/apache/Chart.lock, bitnami/apache/Chart.yaml
=> [bitnami/apache] Update Chart.lock

bitnami/aspnet-core/Chart.lock, bitnami/aspnet-core/Chart.yaml
=> [bitnami/aspnet-core] Update Chart.lock

bitnami/cert-manager/Chart.lock, bitnami/cert-manager/Chart.yaml
=> [bitnami/cert-manager] Update Chart.lock

bitnami/consul/Chart.lock, bitnami/consul/Chart.yaml
=> [bitnami/consul] Update Chart.lock

bitnami/contour/Chart.lock, bitnami/contour/Chart.yaml
=> [bitnami/contour] Update Chart.lock

bitnami/dokuwiki/Chart.lock, bitnami/dokuwiki/Chart.yaml
=> [bitnami/dokuwiki] Update Chart.lock

bitnami/contour-operator/Chart.lock, bitnami/contour-operator/Chart.yaml
=> [bitnami/contour-operator] Update Chart.lock

bitnami/drupal/Chart.lock, bitnami/drupal/Chart.yaml
=> [bitnami/drupal] Update Chart.lock

bitnami/jasperreports/Chart.lock, bitnami/jasperreports/Chart.yaml
=> [bitnami/jasperreports] Update Chart.lock

bitnami/matomo/Chart.lock, bitnami/matomo/Chart.yaml
=> [bitnami/matomo] Update Chart.lock

bitnami/mediawiki/Chart.lock, bitnami/mediawiki/Chart.yaml
=> [bitnami/mediawiki] Update Chart.lock

bitnami/moodle/Chart.lock, bitnami/moodle/Chart.yaml
=> [bitnami/moodle] Update Chart.lock

bitnami/opencart/Chart.lock, bitnami/opencart/Chart.yaml
=> [bitnami/opencart] Update Chart.lock

bitnami/osclass/Chart.lock, bitnami/osclass/Chart.yaml
=> [bitnami/osclass] Update Chart.lock

bitnami/owncloud/Chart.lock, bitnami/owncloud/Chart.yaml
=> [bitnami/owncloud] Update Chart.lock

bitnami/phpmyadmin/Chart.lock, bitnami/phpmyadmin/Chart.yaml
=> [bitnami/phpmyadmin] Update Chart.lock

bitnami/prestashop/Chart.lock, bitnami/prestashop/Chart.yaml
=> [bitnami/prestashop] Update Chart.lock

bitnami/suitecrm/Chart.lock, bitnami/suitecrm/Chart.yaml
=> [bitnami/suitecrm] Update Chart.lock

bitnami/grafana-tempo/Chart.lock, bitnami/grafana-tempo/Chart.yaml
=> [bitnami/grafana-tempo] Update Chart.lock

bitnami/wordpress-intel/Chart.lock, bitnami/wordpress-intel/Chart.yaml
=> [bitnami/wordpress-intel] Update Chart.lock

bitnami/airflow/Chart.lock, bitnami/airflow/Chart.yaml
=> [bitnami/airflow] Update Chart.lock

bitnami/harbor/Chart.lock, bitnami/harbor/Chart.yaml
=> [bitnami/harbor] Update Chart.lock

bitnami/keycloak/Chart.lock, bitnami/keycloak/Chart.yaml
=> [bitnami/keycloak] Update Chart.lock

bitnami/kubeapps/Chart.lock, bitnami/kubeapps/Chart.yaml
=> [bitnami/kubeapps] Update Chart.lock

bitnami/odoo/Chart.lock, bitnami/odoo/Chart.yaml
=> [bitnami/odoo] Update Chart.lock

bitnami/ghost/Chart.lock, bitnami/ghost/Chart.yaml
=> [bitnami/ghost] Update Chart.lock

bitnami/minio/README.md, bitnami/minio/values.yaml
Signed-off-by: Burt Holzman <burt@fnal.gov>
Minor documentation fix to clarify ingress vs. apiIngress
- [X ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [X ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [X ] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)
=> [bitnami/minio]: Clarify ingress/apiIngress helm values for MinIO chart

.github/workflows/cd-pipeline.yaml, .vib/nginx-intel/cypress/cypress.json, .vib/nginx-intel/cypress/cypress/integration/nginx-intel_spec.js, .vib/nginx-intel/goss/goss.yaml, .vib/nginx-intel/goss/vars.yaml, .vib/nginx-intel/vib-publish.json, .vib/nginx-intel/vib-verify.json
The main objective of this PR is to publish our Bitnami NGINX-Intel Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
Tested in https://github.com/joancafom/charts/pull/72
=> [bitnami/nginx-intel] Add tests and publish using VIB

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/storegateway/hpa-sharded.yaml, bitnami/thanos/templates/storegateway/hpa.yaml, bitnami/thanos/templates/storegateway/pdb-sharded.yaml, bitnami/thanos/templates/storegateway/pdb.yaml, bitnami/thanos/templates/storegateway/service-sharded.yaml, bitnami/thanos/templates/storegateway/statefulset-sharded.yaml
Fixes an issue with the storegateway HPA/PDB not being well generated in case of a sharded configuration.
The functionality will be fixed.
People that missed this issue and upgrade to the latest version with sharding enabled will see storegateway start scaling. 
- fixes #11305
=> [bitnami/thanos] feat: create sharded hpa and pdb for storegateway

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/_helpers.tpl
Changes the conditional that controls if the ingest StatefulSet should be deployed to include both `ingest.enabled` & the number of replicas configured. The previous behavior was to require setting `ingest.replicaCount` to 0 even if `ingest.enabled` was set to `false`.
The unnecessary ingest StatefulSet is not deployed when ingest nodes are not enabled.
- fixes #12181 
To test: `helm install es ./bitnami/elasticsearch --dry-run | grep ingest/statefulset` should return nothing, as the default `values.yaml` has `ingest.enabled = false` and the StatefulSet should not be deployed
=> [bitnami/elasticsearch] Fix ingest StatefulSet deployed when `.Values.ingest.enabled=false`

bitnami/apache/Chart.yaml, bitnami/apache/templates/_helpers.tpl, bitnami/apache/templates/configmap-vhosts.yaml, bitnami/apache/templates/configmap.yaml, bitnami/apache/templates/ingress.yaml, bitnami/apache/templates/metrics-svc.yaml, bitnami/apache/templates/tls-secrets.yaml
=> [bitnami/apache] Adjust the naming style for resources

bitnami/aspnet-core/Chart.yaml, bitnami/aspnet-core/templates/health-ingress.yaml, bitnami/aspnet-core/templates/ingress.yaml, bitnami/aspnet-core/templates/tls-secret.yaml
=> [bitnami/aspnet-core] Adjust the naming style for resources

.github/workflows/ci-pipeline.yaml
This CI pipeline refactor aims to simplify the existing workflow complexity by simplifying the logic involved and replacing raw API calls with the use of actions as done for the rest of the workflows. Some of the key changes are:
- The CI will only run once for new automated PRs. It was previously triaging the PR and then launching another CI to run VIB Verify.
- Auto-merge enabling and labeling has been moved to the `auto-pr-review` job so they are only added once we are sure the PR will be merged automatically.
- Improved comment used when an automated PR failed.
- Automated PRs to be reviewed by an agent will now appear on the Support board.
Less CIs executions and a clearer code.
Testing PRs created in a fork:
- …
=> [bitnami/*] Reduce CI complexity and improve UX for automated PRs

.vib/nginx/cypress/cypress.json, .vib/nginx/cypress/cypress/integration/nginx_spec.js, .vib/nginx/goss/goss.yaml, .vib/nginx/goss/vars.yaml, .vib/nginx/vib-publish.json, .vib/nginx/vib-verify.json
=> [bitnami/nginx] Revisit nginx tests

.github/workflows/clossing-issues.yml, .github/workflows/comments.yml, .github/workflows/move-closed-issues.yml, .github/workflows/moving-cards.yml, .github/workflows/triage.yml
Use github token (user github-actions) to label the issues and PRs in the support workflows.
CI/CD workflows are listening for any label change in the PRs. This change should reduce the number of events triggered due to movements in the support dashboard.
=> [bitnami/*]Use github token to reduce the number of labeled events 

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/README.md, bitnami/jupyterhub/values.yaml
Change type for `singleuser.extraEnvVars` from `list` to `dict`. We usually have an extraEnvVars array to add additional environment variables to the containers but in this case we use singleuser.extraEnvVars to set the [Jupyter singleuser.extraEnv](https://zero-to-jupyterhub.readthedocs.io/en/latest/resources/reference.html#singleuser-extraenv), so our extraEnvVars shouldn't be a list.
Avoids warnings like:
```
coalesce.go:223: warning: destination for jupyterhub.singleuser.extraEnvVars is a table. Ignoring non-table value ([])
coalesce.go:223: warning: destination for jupyterhub.singleuser.extraEnvVars is a table. Ignoring non-table value ([])
```
It shouldn't have any drawbacks, this value is rendered with a template.
- fixes #11806
=> [bitnami/jupyterhub] Change type singleuser.extraEnvVars type

bitnami/redis/Chart.yaml, bitnami/redis/templates/prometheusrule.yaml
Use common templating function instead of helm one to be consistent with other bitnami charts (postgresql, tomcat, ...) and prevent errors while rendering values like:
```
rules: 
{{ tpl ($.Values.metrics.prometheusRule.standaloneRules | toYaml) . }}
{{- if eq $.Values.architecture "replication" }}
{{ tpl ($.Values.metrics.prometheusRule.replicationRules | toYaml) . }}
{{- end }}
```
Be able to use templates inside metrics rules value
No drawback identified 
No applicable issue
Tested locally to prevent any regression
=> [bitnami/redis] Use consistent prometheusrules templating

bitnami/common/Chart.yaml, bitnami/common/templates/_capabilities.tpl
Signed-off-by: David J. M. Karlsen <david@davidkarlsen.com>
Fixes #12274
Make it work
Not tested
- fixes #12274
=> [bitnami/common] fix context for HPA util

bitnami/consul/Chart.yaml, bitnami/consul/templates/NOTES.txt, bitnami/consul/templates/_helpers.tpl, bitnami/consul/templates/configmap.yaml, bitnami/consul/templates/consul-headless-service.yaml, bitnami/consul/templates/gossip-secret.yaml, bitnami/consul/templates/ingress.yaml, bitnami/consul/templates/metrics-svc.yaml, bitnami/consul/templates/service.yaml, bitnami/consul/templates/servicemonitor.yaml, bitnami/consul/templates/statefulset.yaml, bitnami/consul/templates/tls-secrets.yaml, bitnami/consul/values.yaml
Adjust the naming style for resources` name to make them not pass the length limit
- fixes #
=> [bitnami/consul] Adjust the naming style for resources

bitnami/kafka/Chart.lock, bitnami/kafka/Chart.yaml, bitnami/kafka/README.md, bitnami/kafka/templates/prometheusrule.yaml, bitnami/kafka/values.yaml
Signed-off-by: Cyril Jouve <jv.cyril@gmail.com>
implement prometheusrule for kafka
define prometheusrule for kafka from helm values.
- fixes #
updated bitnami/common
=> [bitnami/kafka] implement prometheusrule

bitnami/etcd/Chart.yaml, bitnami/etcd/README.md, bitnami/etcd/values.yaml
Signed-off-by: vinokuma <vinod.kumar@radisys.com>
In this PR, we have added one parameter allowPrivilegeEscalation: false to values.yaml in consul to disallow privilege escalation
a child process should not be able to get more privileges than its parent process, e.g. via set uid bit. This should be fixed by adding securityContext to the deployment yaml of the pod
- fixes #
=> [bitnami/etcd] Disallowing privilege escalation for etcd

.github/workflows/cd-pipeline.yaml, .vib/parse/cypress/cypress.json, .vib/parse/cypress/cypress/fixtures/high_score_stats.json, .vib/parse/cypress/cypress/integration/parse_spec.js, .vib/parse/cypress/cypress/support/utils.js, .vib/parse/goss/dashboard/goss.yaml, .vib/parse/goss/dashboard/vars.yaml, .vib/parse/goss/server/goss.yaml, .vib/parse/goss/server/vars.yaml, .vib/parse/vib-publish.json, .vib/parse/vib-verify.json
The main objective of this PR is to publish our Bitnami Parse Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
Tested in https://github.com/joancafom/charts/pull/77
=> [bitnami/parse] Add tests and publish using VIB

bitnami/redis/Chart.yaml, bitnami/redis/templates/scripts-configmap.yaml, bitnami/redis/templates/sentinel/statefulset.yaml
Fix Sentinel + SSL configuration.
- fixes #10826
=> [bitnami/redis] Fix Sentinel + SSL

bitnami/etcd/Chart.yaml, bitnami/etcd/templates/cronjob.yaml
=> [bitnami/etcd] Fix API Version for CronJob of etcd

.github/workflows/cd-pipeline.yaml, .vib/logstash/cypress/cypress.json, .vib/logstash/cypress/cypress/integration/logstash_spec.js, .vib/logstash/goss/goss.yaml, .vib/logstash/goss/vars.yaml, .vib/logstash/vib-publish.json, .vib/logstash/vib-verify.json
The main objective of this PR is to publish our Bitnami MongoDB Sharded Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
Tested in https://github.com/FraPazGal/charts/pull/109
=> [bitnami/logstash] Add tests and publishing using VIB

bitnami/grafana-loki/Chart.yaml, bitnami/grafana-loki/templates/gateway/ingress.yaml
This change corrects the service name reference used in Loki's gateway ingress.
Previously it was 
```yaml
backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" .) "servicePort" "http" "context" $)  | nindent 14 }}
metadata:
name: {{ template "grafana-loki.gateway.fullname" . }}
```
now it's
```yaml
backend: {{- include "common.ingress.backend" (dict "serviceName" (include "grafana-loki.gateway.fullname" .) "servicePort" "http" "context" $)  | nindent 14 }}
metadata:
name: {{ template "grafana-loki.gateway.fullname" . }}
```
This makes the gateway ingress usable upon Helm install
NIL
=> [bitnami/grafana-loki] Fix Loki gateway service name reference in gateway ingress

.github/workflows/ci-pipeline.yml
Fix dependency in `ci-workflow.yml`
https://github.com/bitnami/charts/actions/runs/3106265107
Follow up #12622
=> [bitnami/*] Fix dependency in ci-workflow.yml

.github/workflows/ci-pipeline.yml
Change condition for vib-verify job to execute the job if the PR has been labeled and the latest change comes from bitnami-bot. Concurrency control added to avoid concurrent CI executions over the same PR.
- fixes #
Follow up #12655
=> [bitnami/*] Allow verification in automated PRs

template/CHART_NAME/Chart.yaml, template/CHART_NAME/values.yaml
=> [bitnami/template] chore: :wrench: Add references to latest common chart

bitnami/clickhouse/Chart.lock, bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/README.md, bitnami/clickhouse/values.yaml
This PR adds support for the latest common chart and therefore to the digest section in the images.
- fixes #
=> [bitnami/clickhouse] feat: :sparkles: Add support for image digest

.github/workflows/cd-pipeline.yml
This adds OsClass Cypress and Goss tests to the continuous development pipeline for VIB
=> [bitnami/osclass] Add Osclass to cd pipeline

.github/workflows/cd-pipeline.yml, .vib/pytorch/goss/goss.yaml, .vib/pytorch/goss/vars.yaml, .vib/pytorch/vib-publish.json, .vib/pytorch/vib-verify.json
The main objective of this PR is to publish our Bitnami Pytorch Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
NA
=> [bitnami/pytorch] Add tests and publishing using VIB

.github/workflows/cd-pipeline.yml
Follow up of https://github.com/bitnami/charts/pull/12632
=> [bitnami/geode] Add geode to CD Pipeline

bitnami/argo-workflows/Chart.yaml, bitnami/argo-workflows/crds/argoproj.io_workflowartifactgctasks.yaml
Add '[workflowartifactgctasks](https://github.com/argoproj/argo-workflows/blob/master/manifests/quick-start-postgres.yaml)' role to add permission to the controller to list the workflows. 
- fixes #
=> [bitnami/argo-workflows] add workflowartifactgctasks

bitnami/clickhouse/README.md, template/CHART_NAME/README.md
This directive is required in order to sync the internal metadata (such as the description), otherwise, our internal tooling will fail:
```
07:18:42  java.lang.Error: Unable to match pattern \<\!\-\-\- app-name: (.*) \-\-\>
07:18:42  	at com.bitnami.dynpipeline.utils.ChartSyncer.getCapturingGroupFromRegexp(ChartSyncer.groovy:281)
07:18:42  	at com.bitnami.dynpipeline.utils.ChartSyncer.syncReadmeInfo(ChartSyncer.groovy:247)
```
=> [bitnami/clickhouse] Add app-name to the README

.vib/grafana/cypress/cypress.json, .vib/grafana/cypress/cypress/fixtures/apikeys.json, .vib/grafana/cypress/cypress/fixtures/dashboards.json, .vib/grafana/cypress/cypress/fixtures/datasources.json, .vib/grafana/cypress/cypress/fixtures/panels.json, .vib/grafana/cypress/cypress/fixtures/smtps.json, .vib/grafana/cypress/cypress/fixtures/users.json, .vib/grafana/cypress/cypress/integration/grafana_spec.js, .vib/grafana/cypress/cypress/support/commands.js, .vib/grafana/cypress/cypress/support/utils.js, .vib/grafana/goss/goss.yaml, .vib/grafana/goss/vars.yaml, .vib/grafana/vib-publish.json, .vib/grafana/vib-verify.json
=> [bitnami/grafana] Review tests

.vib/rabbitmq/cypress/cypress.json, .vib/rabbitmq/cypress/cypress/fixtures/admins.json, .vib/rabbitmq/cypress/cypress/fixtures/messages.json, .vib/rabbitmq/cypress/cypress/fixtures/queues.json, .vib/rabbitmq/cypress/cypress/integration/rabbitmq_spec.js, .vib/rabbitmq/cypress/cypress/support/commands.js, .vib/rabbitmq/goss/goss.yaml, .vib/rabbitmq/goss/vars.yaml, .vib/rabbitmq/vib-publish.json, .vib/rabbitmq/vib-verify.json
=> [bitnami/rabbitmq] Revisit tests

.github/workflows/cd-pipeline.yml, .vib/node-exporter/cypress/cypress.json, .vib/node-exporter/cypress/cypress/integration/node_exporter_spec.js, .vib/node-exporter/goss/goss.yaml, .vib/node-exporter/goss/vars.yaml, .vib/node-exporter/vib-publish.json, .vib/node-exporter/vib-verify.json, bitnami/node-exporter/Chart.yaml, bitnami/node-exporter/templates/psp-clusterrole.yaml, bitnami/node-exporter/templates/psp-clusterrolebinding.yaml, bitnami/node-exporter/templates/psp.yaml
The main objective of this PR is to publish our Bitnami Node Exporter Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
Tested in https://github.com/FraPazGal/charts/pull/115
=> [bitnami/node-exporter] Add tests and publishing using VIB

.github/workflows/cd-pipeline.yml, .vib/postgresql-ha/goss/pgpool/goss.yaml, .vib/postgresql-ha/goss/pgpool/vars.yaml, .vib/postgresql-ha/goss/repmgr/goss.yaml, .vib/postgresql-ha/goss/repmgr/vars.yaml, .vib/postgresql-ha/vib-publish.json, .vib/postgresql-ha/vib-verify.json
The main objective of this PR is to publish our Bitnami PostgreSQL HA Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
Tested in https://github.com/FraPazGal/charts/pull/114
=> [bitnami/postgresql-ha] Add tests and publishing using VIB

.github/workflows/cd-pipeline.yml, .vib/ejbca/cypress/cypress.json, .vib/ejbca/cypress/cypress/fixtures/certs.json, .vib/ejbca/cypress/cypress/integration/ejbca_spec.js, .vib/ejbca/cypress/cypress/plugins/index.js, .vib/ejbca/cypress/cypress/support/commands.js, .vib/ejbca/cypress/cypress/support/index.js, .vib/ejbca/goss/goss.yaml, .vib/ejbca/goss/vars.yaml, .vib/ejbca/vib-publish.json, .vib/ejbca/vib-verify.json
The main objective of this PR is to publish our Bitnami EJBCA Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
Tested in https://github.com/joancafom/charts/pull/85
=> [bitnami/ejbca] Add ejbca tests

bitnami/thanos/Chart.lock, bitnami/thanos/Chart.yaml
Upgrade dependencies, mainly to include the changes about #12372
- fixes #12747
=> [bitnami/thanos] Upgrade dependencies

bitnami/discourse/Chart.yaml, bitnami/discourse/templates/networkpolicy-backend-ingress.yaml, bitnami/discourse/templates/networkpolicy-egress.yaml, bitnami/discourse/templates/networkpolicy-ingress.yaml, bitnami/discourse/templates/secrets-database.yaml, bitnami/discourse/templates/secrets-discourse.yaml, bitnami/discourse/templates/secrets-redis.yaml, bitnami/discourse/templates/tls-secrets.yaml
=> [bitnami/discourse] Adjust the naming style for resources 

bitnami/cassandra/Chart.yaml, bitnami/cassandra/README.md, bitnami/cassandra/templates/statefulset.yaml, bitnami/cassandra/values.yaml
Expose ports of the cassandra-containers as k8s hostPort.
=> [bitnami/cassandra] add hostPort-support

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/templates/clusterrole.yaml, bitnami/nginx-ingress-controller/templates/role.yaml
This PR updates the chart to use the latest RBAC rules from https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/templates/
Fixes https://github.com/bitnami/charts/issues/12028
=> [bitnami/nginx-ingress-controller] fix: :bug: Update RBAC rules from upstream project

bitnami/ejbca/Chart.yaml, bitnami/ejbca/templates/externaldb-secrets.yaml, bitnami/ejbca/templates/networkpolicy-backend-ingress.yaml, bitnami/ejbca/templates/networkpolicy-egress.yaml, bitnami/ejbca/templates/networkpolicy-ingress.yaml
=> [bitnami/ejbca] Adjust the naming style for resources

bitnami/kubernetes-event-exporter/Chart.yaml, bitnami/kubernetes-event-exporter/README.md
Modified reference links to kubernetes-event-exporter upstream
Reference links to kubernetes upstream -event-exporter are up to date
=> [bitnami/kubernetes-event-exporter] Modified README for kubernetes-event-exporter

.vib/minio/cypress/cypress.json, .vib/minio/cypress/cypress/fixtures/buckets.json, .vib/minio/cypress/cypress/fixtures/example.json, .vib/minio/cypress/cypress/fixtures/testdata.json, .vib/minio/cypress/cypress/integration/minio_spec.js, .vib/minio/cypress/cypress/support/commands.js, .vib/minio/goss/goss.yaml, .vib/minio/goss/vars.yaml, .vib/minio/vib-publish.json, .vib/minio/vib-verify.json
=> [bitnami/minio] Revisit tests

bitnami/contour-operator/Chart.yaml, bitnami/contour-operator/templates/auth-proxy-clusterrole.yaml, bitnami/contour-operator/templates/auth-proxy-clusterrolebinding.yaml, bitnami/contour-operator/templates/contour-editor-role.yaml, bitnami/contour-operator/templates/contour-viewer-role.yaml, bitnami/contour-operator/templates/leader-election-role.yaml, bitnami/contour-operator/templates/leader-election-rolebinding.yaml, bitnami/contour-operator/templates/metrics-clusterrole.yaml, bitnami/contour-operator/templates/metrics-clusterrolebinding.yaml, bitnami/contour-operator/templates/metrics-service.yaml
Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)
- fixes #
=> [bitnami/contour-operator] Adjust the naming style for resources

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/crds/grafanadashboards.integreatly.org.yaml, bitnami/grafana-operator/crds/grafanadatasources.integreatly.org.yaml, bitnami/grafana-operator/crds/grafanafolders.integreatly.org.yaml, bitnami/grafana-operator/crds/grafanas.integreatly.org.yaml, bitnami/grafana-operator/templates/rbac.yaml
Fixes #12875 
Fixes helm-chart and operator
- fixes #12875 
Should consider automating this
=> Fix 12875/update grafana crds

bitnami/kafka/README.md
Include upgrade notes after updating the Kafka version
https://github.com/bitnami/charts/pull/12892
- fixes #
=> [bitnami/kafka] Upgrade README after releasing version 19.0.0

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md
Bump bitnami/kafka chart version to include changes from https://github.com/bitnami/charts/pull/12892
- fixes #
=> [bitnami/spring-cloud-dataflow] Update dependencies

bitnami/schema-registry/Chart.lock, bitnami/schema-registry/Chart.yaml, bitnami/schema-registry/README.md
Bump bitnami/kafka chart version to include changes from https://github.com/bitnami/charts/pull/12892
- fixes #
=> [bitnami/schema-registry] Update dependencies

bitnami/pinniped/Chart.lock, bitnami/pinniped/Chart.yaml, bitnami/pinniped/README.md, bitnami/pinniped/crds/concierge-crds.yaml, bitnami/pinniped/crds/supervisor.crds.yaml, bitnami/pinniped/templates/_helpers.tpl, bitnami/pinniped/templates/supervisor/apiservice-clientsecret.yaml, bitnami/pinniped/templates/supervisor/rbac.yaml, bitnami/pinniped/values.yaml
This is the plan for this PR
Goal: upgrade pinniped helm charts to support version `v0.20.0` of pinniped
The basic upgrade PR https://github.com/bitnami/charts/pull/12718 opened by the bot did not have all of the necessary changes to successfully deploy version `v0.20.0` of pinniped. This PR is intended to fill in those gaps to successfully deploy pinniped version `v0.20.0`
This PR makes the latest release `v0.20.0` of pinniped deployable using bitnami helm charts.
None.
- fixes #
=> bitnami/pinniped release 0.3.3

bitnami/pinniped/Chart.yaml, bitnami/pinniped/crds/supervisor.crds.yaml
Signed-off-by: Ashish Amarnath <ashisham@vmware.com>
Edit the label on CRDs for pinniped-supervisor
- fixes #
=> [bitnami/pinniped] fix pinniped-supervisor CRD labels

bitnami/etcd/Chart.yaml, bitnami/etcd/templates/_helpers.tpl, bitnami/etcd/templates/configmap.yaml, bitnami/etcd/templates/cronjob.yaml, bitnami/etcd/templates/snapshot-pvc.yaml, bitnami/etcd/templates/statefulset.yaml, bitnami/etcd/templates/svc-headless.yaml, bitnami/etcd/templates/token-secrets.yaml
=> [bitnami/etcd] Adjust the naming style for resources

bitnami/sealed-secrets/Chart.yaml, bitnami/sealed-secrets/templates/clusterrole.yaml
Sealed secrets is able to recreate secrets, if they get deleted or changed.
- fixes #
=> [bitnami/sealed-secrets] Add missing roles

bitnami/kong/Chart.yaml, bitnami/kong/crds/custom-resource-definitions.yaml
This PR updates the CRDs to match the upstream ones
- fixes #12971
=> [bitnami/kong] Sync upstream CRDs

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
Fix scope in .Values.common.podLabels due to missing "$" in the data StatefulSet.
Bug fix to successfully deploy the data StatefulSet using specified common pod labels.
None
None
None
=> [bitnami/mongodb-sharded] Fix missing $ in data StatefulSet

.github/workflows/cd-pipeline.yml, CONTRIBUTING.md, README.md, TESTING.md, bitnami/spring-cloud-dataflow/README.md, template/CHART_NAME/README.md, template/CHART_NAME/values.yaml
Change default branch in links.
Keep documentation up to date and avoid unnecessary redirections.
None
Follow up: #12943
=> [bitnami/*] Update links with new default branch

bitnami/grafana-loki/README.md
This changes adds a description on the limitation of the chart, specifically on the topic of local filesystem persistence.
Other users will be made aware of the limitation.
NIL
Fixes #12916
=> [bitnami/grafana-loki] Update README to include persistence limitation

bitnami/geode/Chart.yaml, bitnami/geode/templates/service-account.yaml
Creates the `serviceAccount` object conditionally 
- fixes #
- [-] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
=> [bitnami/geode] Only create service Account if needed

.github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline-extra-thanos.yml, .github/workflows/ci-pipeline.yml
Revert changes from #13011 since it didn't help
=> Revert retry-count increment from #13011

bitnami/fluentd/Chart.yaml, bitnami/fluentd/values.yaml
The kubernetes block in the default config file is removed if no `serviceAccount` is used.
Prevent deploying error from appearing if no SA is used.
```
#<Thread:0x00007fb0689f9a00 run> terminated with exception (report_on_exception is true):
/opt/bitnami/fluentd/gems/fluent-plugin-kubernetes_metadata_filter-3.1.0/lib/fluent/plugin/kubernetes_metadata_watch_pods.rb:120:in `rescue in start_pod_watch': start_pod_watch: Exception encountered setting up pod watch from Kubernetes API v1 endpoint https://10.96.0.1:443/api: pods is forbidden: User "system:serviceaccount:default:default" cannot list resource "pods" in API group "" at the cluster scope ({"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"pods is forbidden: User \\"system:serviceaccount:default:default\\" …
```
=> [bitnami/fluentd] Chage default config file if not ServiceAccount is provided

.github/workflows/generate-chart-readme.yml
Use [readme-generator-for-helm npm package](https://www.npmjs.com/package/@bitnami/readme-generator-for-helm) instead of cloning and building the project.
Use directly the binary instead of building the [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm) project.
None
Here we have an execution example https://github.com/fmulero/charts/pull/8
=> [bitnami/*] Use readme-generator npm package in generate-readme workflow

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/ingress.yaml
remove deprecated param.
- fixes https://github.com/bitnami/charts/issues/12854
=> [bitnami/influxdb]remove deprecated param

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/dex/deployment.yaml, bitnami/argo-cd/templates/repo-server/deployment.yaml, bitnami/argo-cd/templates/server/deployment.yaml
These changes fix the usage of the volumePermissions.enabled parameter
The deployment succeeds when enabling volumePermissions.enabled
None
- fixes [12785](https://github.com/bitnami/charts/issues/12785)
=> [bitnami/argo-cd] Fix volume-permissions initContainer definitions

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/README.md, bitnami/jupyterhub/values.yaml
Fix envvars render error
- fixes #
=> [bitnami/jupyterhub] Fix envvars render error

bitnami/grafana-loki/Chart.yaml, bitnami/grafana-loki/templates/ingester/statefulset.yaml, bitnami/grafana-loki/templates/query-frontend/deployment.yaml, bitnami/grafana-loki/templates/query-scheduler/deployment.yaml
Fix loki config volume hardcode.
Changes to .Values.loki.dataDir will be used in ingester and query-scheduler and query-frontend.
- fixes #
=> [bitnami/grafana-loki] Fix loki config volume hardcode

bitnami/prestashop/Chart.yaml, bitnami/prestashop/README.md, bitnami/prestashop/values.yaml
Add resources example for metrics exporter container.
Users can easily configure resources for the metrics export container.
- fixes #
=> [bitnami/prestashop] Add resources example for metrics exporter container

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml
Fix render topologySpreadConstraints.
- fixes #
=> [bitnami/mongodb-sharded] Fix render topologySpreadConstraints

bitnami/metallb/Chart.yaml, bitnami/metallb/templates/controller/deployment.yaml, bitnami/metallb/templates/controller/psp.yaml, bitnami/metallb/templates/controller/rbac.yaml, bitnami/metallb/templates/controller/service.yaml, bitnami/metallb/templates/controller/servicemonitor.yaml, bitnami/metallb/templates/networkpolicy.yaml, bitnami/metallb/templates/rbac.yaml, bitnami/metallb/templates/speaker/daemonset.yaml, bitnami/metallb/templates/speaker/psp.yaml, bitnami/metallb/templates/speaker/rbac.yaml, bitnami/metallb/templates/speaker/service.yaml, bitnami/metallb/templates/speaker/servicemonitor.yaml
adjust the naming style for resources to make them not pass the length.
- fixes #
=> [bitnami/metallb] Adjust the naming style for resources to make them not pass the length

bitnami/minio/Chart.yaml, bitnami/minio/templates/distributed/statefulset.yaml, bitnami/minio/templates/standalone/deployment.yaml
Adds `commonLabels` to standalone MinIO `deployment.spec.template.spec.metadata` in the style of existing Bitnami charts.
=> [bitnami/minio] add commonLabels to template.metadata

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/rolebinding.yaml
Fixes the rolebinding creation when not service account is provided.
In this case, it defaults to service account `default` and the rolebinding should be created.
- fixes #
=> [bitnami/rabbitmq] Fix rolebinding creation

bitnami/spark/Chart.yaml, bitnami/spark/templates/tls-secrets.yaml
Fix render namespace for spark
- fixes #
=> [bitnami/spark] Fix render namespace for spark

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
Fix render topologySpreadConstraints for shard data statefulset.
Fix render topologySpreadConstraints for shard data statefulset so that can be install successfully.
- fixes #
=> [bitnami/mongodb-sharded] Fix render topologySpreadConstraints for shard data statefulset

bitnami/memcached/Chart.yaml, bitnami/memcached/README.md, bitnami/memcached/templates/_helpers.tpl, bitnami/memcached/templates/deployment.yaml, bitnami/memcached/templates/secrets.yaml, bitnami/memcached/templates/statefulset.yaml, bitnami/memcached/values.yaml
Allow existing secret to be used for Authentication.
Fixes: https://github.com/bitnami/charts/issues/12836
- fixes https://github.com/bitnami/charts/issues/12836
=> [bitnami/memcached]Allow existing secret to be used for Authentication

bitnami/metallb/Chart.yaml, bitnami/metallb/templates/_helpers.tpl
Fixes the name for the service accounts.
- fixes #
=> [bitnami/metallb] Fix serviceaccount names

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/README.md, bitnami/zookeeper/values.yaml
Add securityContext.runAsUser=0
```
$ helm template zookeeper bitnami/zookeeper --set volumePermissions.enabled=true
...
initContainers:
- name: volume-permissions
image: docker.io/bitnami/bitnami-shell:11-debian-11-r35
imagePullPolicy: "IfNotPresent"
command:
- /bin/bash
args:
- -ec
- |
mkdir -p /bitnami/zookeeper
chown -R 1001:1001 /bitnami/zookeeper
find /bitnami/zookeeper -mindepth 1 -maxdepth 1 -not -name ".snapshot" -not -name "lost+found" | xargs -r chown -R 1001:1001
+         securityContext:
+           runAsUser: 0
resources:
limits: {}
requests: {}
volumeMounts:
- name: data
mountPath: /bitnami/zookeeper
...
```
- fixes #
=> [bitnami/zookeeper] Fix volume permission

bitnami/schema-registry/Chart.yaml, bitnami/schema-registry/templates/hpa.yaml
Fix apiversion hardcode for hpa.
- fixes #
=> [bitnami/schema-registry] Fix apiversion hardcode for hpa

bitnami/grafana-loki/Chart.yaml, bitnami/grafana-loki/templates/gateway/ingress.yaml
Signed-off-by: cleverhu <shouping.hu@daocloud.io>
Fix ingress ingest for grafana-loki.
- fixes #
=> [bitnami/grafana-loki] Fix ingress ingest

bitnami/node-exporter/Chart.yaml, bitnami/node-exporter/templates/service.yaml, bitnami/node-exporter/templates/serviceaccount.yaml, bitnami/node-exporter/templates/servicemonitor.yaml
=> [bitnami/node-exporter] Optimize annos check

bitnami/tomcat/Chart.yaml, bitnami/tomcat/templates/_pod.tpl
Optimize extraPodSpec style for pod tpl
Optimize extraPodSpec style for pod tpl so that the style looks like consistent.
- fixes #
=> [bitnami/tomcat] Optimize extraPodSpec style for pod tpl

bitnami/matomo/Chart.yaml, bitnami/matomo/templates/deployment.yaml, bitnami/matomo/templates/svc.yaml
=> [bitnami/matomo] Optimize annos check

bitnami/haproxy/Chart.yaml, bitnami/haproxy/templates/ingress.yaml, bitnami/haproxy/templates/service.yaml
Optimize annos check for ingress and service.
- fixes #
=> [bitnami/haproxy] Optimize annos check

bitnami/spark/Chart.yaml, bitnami/spark/templates/serviceaccount.yaml, bitnami/spark/templates/svc-master.yaml
=> [bitnami/spark] Optimize annos check

bitnami/metrics-server/Chart.yaml, bitnami/metrics-server/templates/auth-delegator-crb.yaml, bitnami/metrics-server/templates/metrics-server-crb.yaml, bitnami/metrics-server/templates/role-binding.yaml
Fix the service account name for the role/clusterrole bindings.
- fixes #
=> [bitnami/metrics-server] Fix rolebings service account name

bitnami/postgresql-ha/Chart.yaml, bitnami/postgresql-ha/templates/pgpool/service.yaml, bitnami/postgresql-ha/templates/postgresql/metrics-service.yaml, bitnami/postgresql-ha/templates/postgresql/service.yaml, bitnami/postgresql-ha/templates/postgresql/servicemonitor.yaml
Signed-off-by: cleverhu <shouping.hu@daocloud.io>
- fixes #
=> [bitnami/postgresql-ha] Optimize annos check

bitnami/elasticsearch/Chart.yaml, bitnami/elasticsearch/templates/ingest/ingress.yaml
Fix ingress backend for ingest.
Fix ingress ingest.
- fixes #
=> [bitnami/elasticsearch] Fix ingress ingest

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml
This updates the dependencies so this charts benefits from the service account fix in rabbitmq chart.
- fixes #
=> [bitnami/spring-cloud-dataflow] Update subchart dependencies

bitnami/apache/Chart.yaml, bitnami/apache/templates/ingress.yaml
=> [bitnami/apache] Optimize annos check

bitnami/redmine/Chart.yaml, bitnami/redmine/templates/cronjob.yaml
Fix apiversion hardcode for cronjob.
- fixes #
=> [bitnami/redmine] Fix apiversion hardcode for cronjob

bitnami/argo-workflows/README.md
Signed-off-by: Mauro Franchini <mawmaw@duck.com>
Fix typo
Decrease confusion in the documentation
None
- 
- fixes #
-
=> Fix typo in README.md

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/registry/registry-cm.yaml, bitnami/harbor/templates/registry/registry-dpl.yaml, bitnami/harbor/templates/registry/registry-secret.yaml
Allow to the GCP storage without specifying a key, which is required to use [Workload Identity](https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity).
Allows to use Workload Identity.
- fixes #
=> [bitnami/harbor] : gcp storage without key

bitnami/pinniped/Chart.yaml, bitnami/pinniped/templates/_helpers.tpl, bitnami/pinniped/templates/concierge/token-secret.yaml
Fixes service account name in the secret and also avoid collision in the API server object name.
- fixes #
=> [bitnami/pinniped] Fix serviceaccount and apiserver object name

bitnami/postgresql-ha/README.md, bitnami/postgresql/README.md
Update upgrading information of recently updated charts
- fixes #
=> [bitnami/*] Update upgrading notes of PostgreSQL and PostgreSQL HA

bitnami/jupyterhub/Chart.lock, bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/README.md
=> [bitnami/jupyterhub] Update dependencies

bitnami/redmine/Chart.lock, bitnami/redmine/Chart.yaml, bitnami/redmine/README.md
=> [bitnami/redmine] Update dependencies

bitnami/airflow/Chart.lock, bitnami/airflow/Chart.yaml, bitnami/airflow/README.md
=> [bitnami/airflow] Update dependencies

bitnami/odoo/Chart.lock, bitnami/odoo/Chart.yaml, bitnami/odoo/README.md
=> [bitnami/odoo] Update dependencies

bitnami/concourse/Chart.lock, bitnami/concourse/Chart.yaml, bitnami/concourse/README.md
=> [bitnami/concourse] Update dependencies

bitnami/discourse/Chart.lock, bitnami/discourse/Chart.yaml, bitnami/discourse/README.md
=> [bitnami/discourse] Update dependencies

bitnami/sonarqube/Chart.lock, bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/README.md
=> [bitnami/sonarqube] Update dependencies

bitnami/kubeapps/Chart.lock, bitnami/kubeapps/Chart.yaml, bitnami/kubeapps/README.md
=> [bitnami/kubeapps] Update dependencies

bitnami/kong/Chart.lock, bitnami/kong/Chart.yaml, bitnami/kong/README.md
=> [bitnami/kong] Update dependencies

bitnami/argo-workflows/Chart.lock, bitnami/argo-workflows/Chart.yaml, bitnami/argo-workflows/README.md
=> [bitnami/argo-workflows] Update dependencies

bitnami/keycloak/Chart.lock, bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md
=> [bitnami/keycloak] Update dependencies

bitnami/harbor/Chart.lock, bitnami/harbor/Chart.yaml, bitnami/harbor/README.md
=> [bitnami/harbor] Update dependencies

bitnami/contour/Chart.yaml, bitnami/contour/templates/envoy/deployment.yaml
change apiversion hardcode for deployment
- fixes #
=> [bitnami/contour]change apiversion hardcode for deployment

bitnami/airflow/Chart.yaml, bitnami/airflow/templates/worker/horizontalpodautoscaler.yaml
[bitnami/airflow] change apiversion hardcode for airflow
- fixes #
=> [bitnami/airflow] change apiversion hardcode for airflow

bitnami/nginx/Chart.yaml, bitnami/nginx/templates/ingress.yaml
Signed-off-by: Boris Girsch <girsch@ventx.de>
`host` is optional for an ingress rule, so it must be possible to create ingress rules even if `ingress.hostname` is empty
allows to create an ingress rule without the `host`
- fixes #
=> [bitnami/nginx] ingress rule with no "host"

bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/_helpers.tpl, bitnami/fluentd/templates/aggregator-configmap.yaml, bitnami/fluentd/templates/aggregator-hpa.yaml, bitnami/fluentd/templates/aggregator-init-configmap.yaml, bitnami/fluentd/templates/aggregator-statefulset.yaml, bitnami/fluentd/templates/aggregator-svc-headless.yaml, bitnami/fluentd/templates/aggregator-svc.yaml, bitnami/fluentd/templates/forwarder-clusterrole.yaml, bitnami/fluentd/templates/forwarder-configmap.yaml, bitnami/fluentd/templates/forwarder-init-configmap.yaml, bitnami/fluentd/templates/forwarder-psp.yaml, bitnami/fluentd/templates/forwarder-svc.yaml, bitnami/fluentd/templates/ingress.yaml, bitnami/fluentd/templates/metrics-svc.yaml, bitnami/fluentd/templates/tls-certs.yaml, bitnami/fluentd/values.yaml
=> [bitnami/fluentd] Adjust the naming style for resources 

bitnami/contour/Chart.yaml, bitnami/contour/README.md, bitnami/contour/templates/contour/service.yaml, bitnami/contour/templates/envoy/service.yaml, bitnami/contour/values.yaml
This PR adds `loadBalancerClass` field to the `bitnami/contour` chart.
The `loadBalancerClass` enables to use a load balancer implementation other than the cloud provider default.
For example, when using MetalLB.
=> [bitnami/contour] Add loadBalancerClass options

.vib/redis/vib-publish.json, .vib/redis/vib-verify.json, bitnami/redis/Chart.yaml, bitnami/redis/templates/scripts-configmap.yaml
The master node stops the client write requests during the prestop hook to avoid data loss
Write requests are stopped to avoid data loss
None from the tests I performed
- fixes https://github.com/bitnami/charts/issues/12598
=> [bitnami/redis] Fix data loss when executing failover

bitnami/ejbca/Chart.yaml, bitnami/ejbca/templates/deployment.yaml
[bitnami/ejbca] fix apiversion hardcode for deployment
- fixes #
=> [bitnami/ejbca] fix apiversion hardcode for deployment

bitnami/jasperreports/Chart.yaml, bitnami/jasperreports/templates/_helpers.tpl, bitnami/jasperreports/templates/externaldb-secrets.yaml, bitnami/jasperreports/templates/networkpolicy-backend-ingress.yaml, bitnami/jasperreports/templates/networkpolicy-egress.yaml, bitnami/jasperreports/templates/networkpolicy-ingress.yaml, bitnami/jasperreports/templates/tls-secrets.yaml
=> [bitnami/jasperreports] Adjust the naming style for resources

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/rolebinding.yaml
The rolebinding creation should not depend on the service account creation.
- fixes #
=> [bitnami/kafka] Always create rolebindings 

bitnami/geode/README.md
Add bitnami/geode chart deprecation notice.
=> [bitnami/geode] Add chart deprecation notice

bitnami/kafka/Chart.yaml
Force changes in https://github.com/bitnami/charts/pull/13403/commits/6344ca13c0432b66a8056ccda044bf12dd3bdd30 to be published.
The asset is up-to-date in our helm index.
- fixes #
GitHub did mistakingly allow to merge the PR without the bump.
=> [bitnami/kafka] Force new version publishing

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml, bitnami/mongodb-sharded/templates/mongos/mongos-dep-sts.yaml, bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml, bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml
Same as #10445, but for mongodb-sharded. It's currently only exporting few metrics, this will make it export all.
=> [bitnami/mongodb-sharded] Enable all collectors in mongodb_exporter

CONTRIBUTING.md
=> Reference `main` instead of `master` in CONTRIBUTING.md

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/templates/grafana.yaml, bitnami/grafana-operator/templates/rbac.yaml
=> [bitnami/grafana-operator] Adjust the naming style for resources

bitnami/metallb/Chart.yaml
Set a minimum kubeVersion in Chart.yaml
When I install metallb by chart, the output:
```
$ helm install metallb -nkube-system ./ --dry-run
Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: [ValidationError(CustomResourceDefinition.spec.versions[0]): unknown field "deprecated" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion, ValidationError(CustomResourceDefinition.spec.versions[0]): unknown field "deprecationWarning" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion, ValidationError(CustomResourceDefinition.spec.versions[1]): unknown field "deprecated" in io.k8s.apiextensions-apiserver.pkg.apis.apiextensions.v1.CustomResourceDefinitionVersion, …
```
=> [bitnami/metallb] kube version support

.github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline-extra-thanos.yml, .github/workflows/ci-pipeline.yml
This version should include changes from the following PRs:
* https://github.com/vmware-labs/vmware-image-builder-action/pull/100
* https://github.com/vmware-labs/vmware-image-builder-action/pull/101
* https://github.com/vmware-labs/vmware-image-builder-action/pull/102
=> Use 0.4.10 as pinned version for vib action

bitnami/owncloud/Chart.yaml, bitnami/owncloud/templates/_helpers.tpl, bitnami/owncloud/templates/deployment.yaml, bitnami/owncloud/templates/externaldb-secrets.yaml, bitnami/owncloud/templates/ingress.yaml, bitnami/owncloud/templates/metrics-svc.yaml, bitnami/owncloud/templates/networkpolicy-backend-ingress.yaml, bitnami/owncloud/templates/networkpolicy-egress.yaml, bitnami/owncloud/templates/networkpolicy-ingress.yaml, bitnami/owncloud/templates/pv.yaml, bitnami/owncloud/templates/pvc.yaml, bitnami/owncloud/templates/tls-secrets.yaml, bitnami/owncloud/values.yaml
Signed-off-by: Gang Liu [gang.liu@daocloud.io](mailto:gang.liu@daocloud.io)
- fixes #
=> [bitnami/owncloud] Adjust the naming style for resources 

bitnami/osclass/Chart.yaml, bitnami/osclass/templates/_helpers.tpl, bitnami/osclass/templates/deployment.yaml, bitnami/osclass/templates/externaldb-secrets.yaml, bitnami/osclass/templates/ingress.yaml, bitnami/osclass/templates/metrics-svc.yaml, bitnami/osclass/templates/networkpolicy-backend-ingress.yaml, bitnami/osclass/templates/networkpolicy-egress.yaml, bitnami/osclass/templates/networkpolicy-ingress.yaml, bitnami/osclass/templates/osclass-pvc.yaml, bitnami/osclass/templates/tls-secrets.yaml, bitnami/osclass/values.yaml
=> [bitnami/osclass] Adjust the naming style for resources

bitnami/wildfly/Chart.yaml, bitnami/wildfly/templates/ingress.yaml, bitnami/wildfly/templates/management-ingress.yaml, bitnami/wildfly/templates/tls-secrets.yaml, bitnami/wildfly/values.yaml
=> [bitnami/wildfly] Adjust the naming style for resources

bitnami/redis/Chart.yaml, bitnami/redis/templates/sentinel/statefulset.yaml
Signed-off-by: Bejenaru Remus <remus@bejenaru.com>
- fixes #
=> [bitnami/redis] Fix suport for persistent volume claim for sentinel

bitnami/mongodb-sharded/Chart.yaml, bitnami/mongodb-sharded/templates/_helpers.tpl, bitnami/mongodb-sharded/templates/shard/shard-data-poddisruptionbudget.yaml, bitnami/mongodb-sharded/templates/shard/shard-data-podmonitor.yaml
Corrected a few typos: missing space, missing $
Added improved logic for creating PodMonitors that select the correct Pods
Enabling PodMonitors works as expected, PDB is created without error, and now correctly uses the ServiceAccount name specified in the "common" section of the values file
- fixes #
=> [bitnami/mongodb-sharded]Fixed a few errors in the templates that support monitoring, PDB, etc

bitnami/sealed-secrets/Chart.yaml, bitnami/sealed-secrets/README.md, bitnami/sealed-secrets/templates/service.yaml, bitnami/sealed-secrets/templates/servicemonitor.yaml, bitnami/sealed-secrets/values.yaml
Parametrize the name of the service port and serviceMonitor port
- fixes #13513
=> bitnami/sealed-secrets Fix using serviceMonitor in sealed secrets

bitnami/cassandra/Chart.yaml, bitnami/cassandra/templates/statefulset.yaml
[bitnami/cassandra] fix hardcord for statefulset
=> [bitnami/cassandra] fix hardcord for statefulset

bitnami/fluentd/Chart.yaml, bitnami/fluentd/templates/aggregator-hpa.yaml, bitnami/fluentd/templates/aggregator-statefulset.yaml
[bitnami/fluentd] fix apiversion hardcode for statefulset
=> [bitnami/fluentd] fix apiversion hardcode for statefulset

bitnami/consul/Chart.yaml, bitnami/consul/templates/statefulset.yaml
[bitnami/consul] fix apiversion hardcode for statefulset
=> [bitnami/consul] fix apiversion hardcode for statefulset

bitnami/spark/Chart.yaml, bitnami/spark/templates/hpa-worker.yaml, bitnami/spark/templates/statefulset-master.yaml, bitnami/spark/templates/statefulset-worker.yaml
[bitnami/spark] fix apiversion hardcode for statefulset
=> [bitnami/spark] fix apiversion hardcode for statefulset

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/receive/statefulset.yaml, bitnami/thanos/templates/storegateway/hpa-sharded.yaml, bitnami/thanos/templates/storegateway/hpa.yaml
[bitnami/thanos] fix apiversion hardcode for statefulset
=> [bitnami/thanos] fix apiversion hardcode for statefulset

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/trivy/trivy-sts.yaml
[bitnami/harbor]fix apiversion hardcode for statefulset
=> [bitnami/harbor]fix apiversion hardcode for statefulset

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/statefulset.yaml
[bitnami/rabbitmq]fix apiversion hardcode for statefulset
=> [bitnami/rabbitmq]fix apiversion hardcode for statefulset

.github/workflows/cd-pipeline.yml, .github/workflows/ci-pipeline-extra-thanos.yml, .github/workflows/ci-pipeline.yml
Use main instead of a pinned version for VIB action
=> Use main instead of a pinned version for VIB action

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/templates/hub/networkpolicy.yaml, bitnami/jupyterhub/templates/proxy/networkpolicy.yaml, bitnami/jupyterhub/templates/singleuser/networkpolicy.yaml
[bitnami/jupyterhub] fix apiversion hardcode for NetworkPolicy
=> [bitnami/jupyterhub] fix apiversion hardcode for NetworkPolicy

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/networkpolicy.yaml
[bitnami/rabbitmq] fix apiversion hardcode for NetworkPolicy
=> [bitnami/rabbitmq] fix apiversion hardcode for NetworkPolicy

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/application-controller/clusterrolebinding.yaml
[binami/argo-cd] fix apiversion hardcode ClusterRoleBinding
=> [binami/argo-cd] fix apiversion hardcode ClusterRoleBinding

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/networkpolicy.yaml
[bitnami/keycloak] fix apiversion hardcode for NetworkPolicy
=> [bitnami/keycloak] fix apiversion hardcode for NetworkPolicy

bitnami/thanos/Chart.yaml, bitnami/thanos/templates/alert-rule/store_gateway.yml
Fix 2 syntax errors in the new thanos-store rules
By default the helm chart will be installable
N/A
This fixes the following errors that are encountered if this rule is enabled in the chart:
```
The  "prometheusrules" is invalid:
* : group "thanos-store", rule 1, "ThanosStoreGrpcErrorRate": annotation "description": template: __alert_ThanosStoreGrpcErrorRate:1: unterminated raw quoted string
* : group "thanos-store", rule 2, "ThanosStoreSeriesGateLatencyHigh": annotation "description": template: __alert_ThanosStoreSeriesGateLatencyHigh:1: unexpected "}" in operand
```
=> [bitnami/thanos] Fixed invalid go tmpl syntax in 2 thanos-store prometheus rules

bitnami/argo-workflows/Chart.yaml, bitnami/argo-workflows/templates/controller/clusterrolebinding.yaml, bitnami/argo-workflows/templates/server/clusterrolebinding.yaml
[bitnami/argo-workflows] fix apiversion hardcode ClusterRoleBinding
=> [bitnami/argo-workflows] fix apiversion hardcode ClusterRoleBinding

bitnami/minio/Chart.yaml, bitnami/minio/templates/networkpolicy.yaml
[bitnami/minio] fix apiversion hardcode for NetworkPolicy
=> [bitnami/minio] fix apiversion hardcode for NetworkPolicy

bitnami/pinniped/Chart.yaml, bitnami/pinniped/templates/concierge/rbac.yaml, bitnami/pinniped/templates/supervisor/rbac.yaml
[bitnami/pinniped] fix apiversion hardcode ClusterRoleBinding
=> [bitnami/pinniped] fix apiversion hardcode ClusterRoleBinding

bitnami/phpmyadmin/Chart.yaml, bitnami/phpmyadmin/templates/deployment.yaml
[bitnami/phpmyadmin]fix apiversion hardcode for deployment
=> [bitnami/phpmyadmin]fix apiversion hardcode for deployment

bitnami/argo-cd/Chart.yaml, bitnami/argo-cd/templates/argocd-secret.yaml
In case `config.secret.annotations` are set, the wrong annotations are rendered into the release.
Bugfix
None
None
=> [bitnami/argo-cd] Use correct secret annotations in argocd-secret

bitnami/grafana/Chart.yaml, bitnami/grafana/templates/deployment.yaml, bitnami/grafana/templates/image-renderer-deployment.yaml
[bitnami/grafana] fix apiversion hardcode for deployment
=> [bitnami/grafana] fix apiversion hardcode for deployment

bitnami/kubernetes-event-exporter/Chart.yaml, bitnami/kubernetes-event-exporter/templates/rbac-leader-election.yaml
[bitnami/kubernetes-event-exporter]fix apiversion hardcode for Role
=> [bitnami/kubernetes-event-exporter]fix apiversion hardcode for Role

bitnami/grafana-loki/Chart.yaml, bitnami/grafana-loki/templates/promtail/daemonset.yaml
[bitnami/grafana-loki] fix apiversion hardcode for deployment
=> [bitnami/grafana-loki] fix apiversion hardcode for deployment

bitnami/schema-registry/Chart.lock, bitnami/schema-registry/Chart.yaml
Sort dependencies in reverse order
=> [bitnami/schema-registry] Reverse sort of dependencies in Chart.yaml

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/notary/notary-server.yaml, bitnami/harbor/templates/notary/notary-signer.yaml
[bitnami/harbor] fix apiversion hardcode for deployment
=> [bitnami/harbor] fix apiversion hardcode for deployment

bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/README.md, bitnami/sonarqube/templates/NOTES.txt, bitnami/sonarqube/templates/_helpers.tpl, bitnami/sonarqube/values.yaml
Add trademark notes and update disclaimer in this chart
=> [bitnami/sonarqube] Add trademark information to SonarQube

.github/workflows/cd-pipeline.yml
Add Bitnami Kiam Helm Chart to the list of assets published using VMware Image Builder.
Increased pool of assets completely handled by VMware Image Builder.
None
NA
None.
=> [bitnami/kiam] Publish kiam using VIB

bitnami/cassandra/Chart.yaml, bitnami/cassandra/values.yaml
Fixes the cassandra port in metrics configuration
- fixes #13668
=> [bitnami/cassandra] Fix cassandra port in metrics config

bitnami/redis/Chart.yaml, bitnami/redis/templates/master/application.yaml, bitnami/redis/templates/replicas/statefulset.yaml, bitnami/redis/templates/sentinel/statefulset.yaml
Adds version check for the parameter introduced in #13596
Makes the char compatible with older (<1.25) k8s versions
- improves #13596
=> [bitnami/redis] Add version checking to minReadySeconds parameter

.vib/solr/cypress/cypress.env.json, .vib/solr/cypress/cypress.json, .vib/solr/cypress/cypress/integration/solr_spec.js, .vib/solr/cypress/cypress/support/commands.js, .vib/solr/cypress/cypress/support/utils.js, .vib/solr/goss/goss.yaml, .vib/solr/goss/vars.yaml, .vib/solr/vib-publish.json, .vib/solr/vib-verify.json
=> [bitnami/solr] Revisit tests

bitnami/zookeeper/Chart.yaml, bitnami/zookeeper/README.md, bitnami/zookeeper/templates/statefulset.yaml, bitnami/zookeeper/values.yaml
New PR following https://github.com/bitnami/charts/pull/8272
Cf. https://github.com/bitnami/charts/pull/8272#issuecomment-1324830168
=> [bitnami/zookeeper] replace commonAnnotations & commonLabels with persistence.annotations & persistence.labels in volumeClaimTemplates

bitnami/zookeeper/README.md
Add upgrading notes to version 11.0.0
Document changes in version 11.0.0 and let users know how to upgrade from previous version.
- related to #13662
=> [bitnami/zookeeper] Add upgrading notes

bitnami/kafka/Chart.lock, bitnami/kafka/Chart.yaml, bitnami/kafka/README.md
This major version updates the Zookeeper subchart to its newest major.
- Related to #13662
=> [bitnami/kafka] Zookeeper chart update

bitnami/clickhouse/Chart.lock, bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/README.md
This major version updates the Zookeeper subchart to its newest major.
- Related to #13662
=> [bitnami/clickhouse] Zookeeper chart update

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md
This major version updates the Kafka subchart to its newest major.
- Related to #13839
=> [bitnami/spring-cloud-dataflow] Kafka subchart update

.vib/ejbca/goss/goss.yaml
This fixes the Goss test. The ejbca batch command needs to be executed in the ejbca folder as it uses relative paths.
=> [bitnami/ejbca] Fix EJBCA Goss test

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/README.md, bitnami/clickhouse/templates/_helpers.tpl, bitnami/clickhouse/templates/scripts-configmap.yaml, bitnami/clickhouse/templates/service-external-access.yaml, bitnami/clickhouse/templates/service-headless.yaml, bitnami/clickhouse/templates/service.yaml, bitnami/clickhouse/templates/statefulset.yaml, bitnami/clickhouse/values.yaml
Clickhouse chart support clickhouse keeper.
But still use zookeeper as defalut.
- fixes #13654
=> [bitnami/clickhouse]: support clickhouse keeper

bitnami/common/Chart.yaml, bitnami/common/templates/_names.tpl, bitnami/common/templates/_secrets.tpl, bitnami/common/templates/_utils.tpl
resolve namespace using common.names.namespace in a consistent manner
allow .Values.namespaceOverride to work consistently
- fixes #
fallback to using .Release.Namespace is namespaceOverride is not defined, so backward compatible
=> [bitnami/common] resolve namespace using common.names.namespace macro

.vib/redmine/cypress/cypress.json, .vib/redmine/cypress/cypress/fixtures/settings.json, .vib/redmine/cypress/cypress/fixtures/smtps.json, .vib/redmine/cypress/cypress/fixtures/users.json, .vib/redmine/cypress/cypress/integration/redmine_spec.js, .vib/redmine/cypress/cypress/support/commands.js, .vib/redmine/goss/goss.yaml, .vib/redmine/goss/vars.yaml, .vib/redmine/vib-publish.json, .vib/redmine/vib-verify.json
=> [bitnami/redmine] Revisit tests

.vib/redis-cluster/goss/goss.yaml, .vib/redis-cluster/goss/vars.yaml, .vib/redis-cluster/vib-publish.json, .vib/redis-cluster/vib-verify.json
=> [bitnami/redis-cluster] Revisit tests

.github/workflows/ci-pipeline.yml
Merge directly the PR instead of enabling the auto-merge.
In certain occasions the auto-merge process for bitnami-bot PRs may fail without notifying the team due to changes in base branch. Also retries were included to avoid temporary issues.
[Execution example](https://github.com/fmulero/charts/actions/runs/3678415149/jobs/6221908123)
=> [bitnami/*] Merge automated PRs instead of enabling auto-merge

bitnami/nginx/Chart.yaml, bitnami/nginx/templates/deployment.yaml
I noticed the hidden files were not copied correctly when executing the git-clone-repository container and that prevented the git-repo-syncer to work properly, it didn't find the .git folder and failed. 
Pod is deployed correctly
- fixes https://github.com/bitnami/charts/issues/13579
=> [bitnami/nginx] Copy hidden files when configuring the cloneStaticSiteFromGit parameter

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/_helpers.tpl
Support enabling sentinel for the local redis and running the registry in a configuration like:
```yaml
redis:
enabled: true
architecture: replication
sentinel:
enabled: true
replica:
replicaCount: 3
```
Increase availability of the registry with the build-in redis.
Duplicated logic between this chart and the main redis chart.
- fixes #
=> [bitnami/harbor]: support enabling redis sentinel

bitnami/keycloak/Chart.yaml, bitnami/keycloak/README.md, bitnami/keycloak/templates/configmap-env-vars.yaml, bitnami/keycloak/values.yaml
Adding a log level value to be used as an environment variables (KC_LOG_LEVEL)
Signed-off-by: Martin Charette <iam@cinq.com>
Updating to use the latest version of the container available from bitnami (20.0.1)
Adding a value to use the KC_LOG_LEVEL environment variable to allow different log level.
Avoid using an extraEnvVar and uses the logging value section already present.
- fixes #
=> [bitnami/keycloak] Updating to use your latest container version (20.0.1)and adding KC_LOG_LEVEL

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/README.md, bitnami/clickhouse/values.yaml
Signed-off-by: lusson <lusson@foxmail.com>
add change notes in readme and values.yaml to use Kubernetes 1.8
Install clickhouse is failed when i use Kubernetes 1.8
no
- fixes #13855
=> [bitnami/clickhouse] add change notes to use Kubernetes 1.8

bitnami/owncloud/Chart.yaml, bitnami/owncloud/README.md, bitnami/owncloud/templates/NOTES.txt
=> [bitnami/owncloud] Deprecate Owncloud chart

bitnami/metrics-server/Chart.yaml, bitnami/metrics-server/templates/svc.yaml
Signed-off-by: Amit Ben Ami <benami.amit1@gmail.com>
=> [bitnami/metrics-server] removing empty `annotations` on `Servier` if no values exist for it

bitnami/memcached/Chart.yaml, bitnami/memcached/values.yaml
=> Fix misleading comment "arguments" => "args"

bitnami/kubeapps/Chart.yaml, bitnami/kubeapps/README.md, bitnami/kubeapps/templates/apprepository/deployment.yaml, bitnami/kubeapps/templates/kubeappsapis/deployment.yaml, bitnami/kubeapps/values.yaml
Signed-off-by: Gallardot <tttick@163.com>
- fixes #
=> [bitnami/kubeapps] Custom postgres user name

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/crds/grafanas.integreatly.org.yaml
Signed-off-by: Roberto Montero <roberto.montero@commercetools.com>
Added initContainers to Grafana pods spec.
- fixes #
Bug related: https://github.com/bitnami/charts/issues/14180
- [ *] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [* ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [* ] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ *] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/main/CONTRIBUTING.md#sign-your-work)
=> [bitnami/grafana.operator] Added initContainers to Grafana pods spec.

bitnami/postgresql/Chart.yaml
=> [bitnami/postgresql] update chart version for conflict

.vib/sealed-secrets/vib-publish.json
=> [bitnami/sealed-secrets] update vib-publish

bitnami/ghost/Chart.yaml
=> [bitnami/ghost] Bump version chart to force new publish

bitnami/pinniped/Chart.yaml
=> [bitnami/pinniped] Bump version chart to force new publish

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/values.yaml
Signed-off-by: Sachin Rakshe <srakshe@synamedia.com>
The port used by the Rabbitmq prometheus-plugin can be configured using the `prometheus.tcp.port` key.
This key is hardcoded to a value of 9419 in the _values.yaml_. In order to set this port to a custom value would require one to override the entire 'configuration' key from _values.yaml_. Instead, the value for this key can be derived from `{{ .Values.containerPorts.metrics }}`.
The metrics port in Service is configurable through port: `{{ .Values.service.ports.metrics }}`
The metrics port in StatefulSet is configurable through `containerPort`: `{{ .Values.containerPorts.metrics }}` 
The change is to make the value for `prometheus.tcp.port` key follow the `{{ .Values.containerPorts.metrics }}`.
This allows setting a custom port value …
=> [bitnami/rabbitmq] Fixes 14212 - Rabbitmq metrics port configuration follows containerPorts.metrics value

bitnami/haproxy-intel/Chart.yaml, bitnami/haproxy-intel/README.md, bitnami/haproxy-intel/templates/NOTES.txt
Deprecate the bitnami/haproxy-intel Helm chart
=> [bitnami/haproxy-intel] Deprecate Helm chart

bitnami/nginx-intel/Chart.yaml, bitnami/nginx-intel/README.md, bitnami/nginx-intel/templates/NOTES.txt
Deprecate the bitnami/nginx-intel Helm chart
=> [bitnami/nginx-intel] Deprecate Helm chart

bitnami/jaeger/Chart.lock, bitnami/jaeger/Chart.yaml, bitnami/jaeger/README.md
Update Jaeger's dependencies. In particular, update Cassandra to 10.x
https://github.com/bitnami/charts/pull/14076
Update dependencies to the latest version
None
Cassandra was recently updated to 10.x
=> [bitnami/jaeger] Update dependencies

bitnami/owncloud/Chart.yaml
Add deprecation notice to Owncloud chart.yml
=> [bitnami/owncloud] Add deprecation message for Owncloud chart

bitnami/harbor/Chart.yaml
Fix harbor version to apply uncommitted changes of #13374.
=> [bitnami/harbor] Fix harbor version to apply uncommitted changes

.github/workflows/comments.yml, .github/workflows/pr-reviews.yml
Creates a new workflow to move cards properly in the support dashboard attending to PR reviews and repository changes.
Cards will be properly moved according to our support workflow.
These PRs will not moved when the review was submitted
- #14217
- #14163
=> [bitnami/charts] Add workflow to move issue cards based on PR reviews

.github/workflows/pr-reviews.yml
Remove listener for `pull_request_review` event. We cannot change the card column from `pull_request_review`, because this event is triggered in the [context of the pull request](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request_review) and the workflow doesn't have permissions to run that operation.
Follow-up #14333
- https://github.com/bitnami/charts/actions/runs/3913098493/jobs/6688638524
=> [bitnami/charts] Add workflow to move issue cards based on PR changes

bitnami/thanos/Chart.lock, bitnami/thanos/Chart.yaml, bitnami/thanos/README.md
Update MinIO subchart to major version 2023.
=> [bitnami/thanos] Update MinIO subchart

bitnami/mastodon/Chart.lock, bitnami/mastodon/Chart.yaml, bitnami/mastodon/README.md
Update MinIO subchart to major version 2023.
=> [bitnami/mastodon] Update MinIO subchart

.github/workflows/archiving-cards.yml, .github/workflows/comments.yml, .github/workflows/delete-solved-cards.yml, .github/workflows/move-closed-issues.yml, .github/workflows/pr-reviews.yml, .github/workflows/triage.yml
This PR include several changes:
* New workflow to delete archived cards or "solved" cards without changes in the last week.
* Avoid concurrency in the workflows in charge of moving the cards for a particular issue.
* Remove cards for automated PRs once the PR is merged.
* Avoid undesired card movements for PRs under triage.
Fix card movements errors.
With these changes we are trying to fix error like these:
- https://github.com/bitnami/containers/actions/runs/3940500911
- https://github.com/bitnami/containers/actions/runs/3939228827
- https://github.com/bitnami/containers/actions/runs/3883202822
=> [bitnami/charts] Fix workflow issues with existing cards

bitnami/metrics-server/Chart.yaml, bitnami/metrics-server/templates/cluster-role.yaml
Remove namespace on cluster-scoped resource `clusterRole`
Signed-off-by: xeivieni <clement.mondion@gmail.com>
In order to address this issue https://github.com/bitnami/charts/issues/8434 for metrics-server we remove the namespace for cluter-scoped resources (here, the clusterRole)
Prevents errors on strict systems such as gitlab agent
Cannot see drawbacks at the time
- fixes #8434
=> [bitnami/metrics-server] fix: remove namespace

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/exporter/exporter-dpl.yaml
Fix issue https://github.com/bitnami/charts/issues/14379
- fixes  https://github.com/bitnami/charts/issues/14379
=> bitnami/harbor Fix extraEnvVarsSecret on exporter

bitnami/contour/Chart.yaml, bitnami/contour/README.md, bitnami/contour/templates/envoy/service.yaml, bitnami/contour/values.yaml
There are often situations where you want to replace the contour yaml you are writing with bitnami's helm chart.
In this case, if the name of the LoadBalancer Service is changed, the NLB must be re-created.
In other words, the service must be suspended.
NLB cannot be easily re-created in many cases due to use cases such as Private Link.
In such cases, we would like to be able to switch to bitnami's helm chart.
Allows users to fix the name of the LoadBalancer Service as they wish.
None
- fixes #
=> [bitnami/contour] Added option to override envoy service name

bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/README.md, bitnami/sonarqube/values.yaml
1) **READMDE.md** file  I have changed the README.md of the sonarqube chart inside the PostgreSQL section to update all the attributes by placing primary after the PostgreSQL. For example, it looks like this when you want to set the existing claim attribute  --> `--set postgresql.primary.persistence.existingClaim=sonar-pv-claim` instead of `postgresql.persistence. existing claim =sonar-pv-claim`.
As if you typed in the set parameter `postgresql.persistence.existingClaim` without accessing the primary attribute it will always create a new PV claim even though you have specified an existing one.
This section of code inside the PostgreSQL chart is updated but the documentation of it inside sonarqube is not updated
2) **values.yaml** file Added the primary section to include all the …
=> [bitnami/sonarqube] Modify README

.vib/external-dns/cypress/cypress.json, .vib/external-dns/cypress/cypress/integration/external_dns_spec.js, .vib/external-dns/goss/goss.yaml, .vib/external-dns/goss/vars.yaml, .vib/external-dns/vib-publish.json, .vib/external-dns/vib-verify.json
=> [bitnami/external-dns] Revisit tests

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/NOTES.txt
Signed-off-by: Carlos Rodríguez Hernández <carlosrh@vmware.com>
Add a warning in the installation notes about the common/well-known issue of reinstalling the Helm chart after `helm delete`
=> [bitnami/postgresql] Add note about password issue when reinstalling helm chart

.vib/fluentd/goss/goss.yaml
Tests were failing due to these checks depend on the configuration of the underlying platform
Test will become more stable
None
- [N/A] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [N/A] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
=> [bitnami/fluentd] Remove unnecessary checks during the tests that depend on the underlying platform

.vib/kube-prometheus/cypress/cypress/integration/kube_prometheus_spec.js
=> [bitnami/kube-prometheus] Fix kube-prometheus tests

TESTING.md
Update the testing information to include the most up-to-date information related to the testing policy applied in the repository.
Documentation is up-to-date.
None
NA
NA
=> [bitnami/*] Update testing documentation

bitnami/kubernetes-event-exporter/Chart.yaml, bitnami/kubernetes-event-exporter/templates/rbac-leader-election.yaml
This change grants access to the leases in the coordinator API for the leader-election code
fixes a regression
not that I'm aware of
- fixes #14687 
I based the RBAC changes off of other projects that use the leader-election API such as cert-manager
=> [bitnami/kubernetes-event-exporter] grant access to coordinator API for leader election

bitnami/kubernetes-event-exporter/Chart.yaml, bitnami/kubernetes-event-exporter/README.md, bitnami/kubernetes-event-exporter/templates/deployment.yaml, bitnami/kubernetes-event-exporter/templates/metrics-service.yaml, bitnami/kubernetes-event-exporter/templates/prometheusrule.yaml, bitnami/kubernetes-event-exporter/templates/servicemonitor.yaml, bitnami/kubernetes-event-exporter/values.yaml
Signed-off-by: Maxime Leroy <19607336+maxime1907@users.noreply.github.com>
Add metrics support on port 2112
Expose these metrics:
- events_sent (The total number of events sent)
- events_discarded (The total number of events discarded because of being older than the maxEventAgeSeconds specified)
- watch_errors (The total number of errors received from the informer)
- send_event_errors (The total number of send event errors)
None
=> [bitnami/kubernetes-event-exporter]: metrics support

template/CHART_NAME/templates/daemonset.yaml, template/CHART_NAME/templates/deployment.yaml, template/CHART_NAME/templates/statefulset.yaml
Add commonLabels to pod labels in deployment, statefulset and daemonset templates.
Add labels via setting only one value instead of needing to set a value for each separately.
Several PRs has been approved and merged with similar changes. Template should reflect these changes
- https://github.com/bitnami/charts/pull/14244
- https://github.com/bitnami/charts/pull/13501
- https://github.com/bitnami/charts/pull/12962
=> [template] Add commonLabels to pod templates

bitnami/grafana-operator/Chart.yaml, bitnami/grafana-operator/crds/grafanadashboards.integreatly.org.yaml, bitnami/grafana-operator/crds/grafanadatasources.integreatly.org.yaml, bitnami/grafana-operator/crds/grafanafolders.integreatly.org.yaml, bitnami/grafana-operator/crds/grafananotificationchannels.integreatly.org.yaml, bitnami/grafana-operator/crds/grafanas.integreatly.org.yaml
updates `grafana-operator` crds to [`v4.9.0`](https://github.com/grafana-operator/grafana-operator/tree/v4.9.0/config/crd)
=> [bitnami/grafana-operator] updates crds to 4.9.0

bitnami/postgresql/Chart.yaml, bitnami/postgresql/README.md, bitnami/postgresql/templates/secrets.yaml, bitnami/postgresql/values.yaml
THIS FEATURE IS EXPERIMENTAL
This PR adds a `serviceBindings.enabled` flag that, apart from the regular secret, it will create extra ones to be integrated with the [ServiceBindings](https://servicebinding.io/). In order to not make it very breaking, the flag is disabled by default and also it will not replace the existing secrets. 
It will create two extra secrets: one for the Postgres user and one for the custom user. It can be simply integrated with a ServiceBinding object out of the box. 
- fixes #
=> [bitnami/postgresql] feat: :sparkles: Add ServiceBinding-compatible secrets

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/templates/prometheus-operator/clusterrole.yaml
Signed-off-by: Jack Yang [qwedd296@gmail.com](mailto:qwedd296@gmail.com)
Add `- alertmanagers/status` to `rules.resources` in `charts/bitnami/kube-prometheus/templates/prometheus-operator/clusterrole.yaml` 
prometheus-operator ClusterRole has the permission to alertmanagers/status 
- fixes #14889
=> [bitnami/kube-prometheus] Add permission to the alertmanagers/status resource

bitnami/argo-workflows/Chart.yaml, bitnami/argo-workflows/README.md, bitnami/argo-workflows/values.yaml
We are not using latest so it's not necessary to use "Always" as pull policy.
Less pulls
None
=> [bitnami/argo-workflows] Update pullPolicy to not to always pull the images

bitnami/argo-workflows/Chart.yaml
Force changes in https://github.com/bitnami/charts/commit/089a7db7069ddfa69b68f7dff67b5e7e2acec338 to be published.
- related to https://github.com/bitnami/charts/pull/14907
Pull was not merged correctly
=> [bitnami/argo-workflows] Force new version publishing

.github/workflows/generate-chart-readme.yml
Use latest version of readme-generator
readme-output will be aligned with current markdown lint rules.
- fixes https://github.com/bitnami/charts/pull/14920#discussion_r1109524815
https://github.com/bitnami-labs/readme-generator-for-helm/releases/tag/2.5.0
=> [Support] Update readme-generator

bitnami/wildfly/Chart.yaml, bitnami/wildfly/templates/deployment.yaml
Added priorityClassName prop
Users can change priority classes for wildfly
=> [bitnami/wildfly] added priorityClassName prop

bitnami/harbor/Chart.lock, bitnami/harbor/Chart.yaml, bitnami/harbor/templates/nginx/configmap-http.yaml, bitnami/harbor/templates/nginx/configmap-https.yaml
Show devcenter-api-2.0
- fixes #14137
=> [bitnami/harbor] DevCenter API Page

.vib/grafana-tempo/cypress/cypress.json, .vib/grafana-tempo/cypress/cypress/integration/grafana_tempo_spec.js, .vib/grafana-tempo/vib-publish.json, .vib/grafana-tempo/vib-verify.json, bitnami/grafana-tempo/Chart.yaml, bitnami/grafana-tempo/README.md, bitnami/grafana-tempo/templates/metrics-generator/deployment.yaml, bitnami/grafana-tempo/templates/metrics-generator/service.yaml, bitnami/grafana-tempo/templates/metrics-generator/servicemonitor.yaml, bitnami/grafana-tempo/test.yaml, bitnami/grafana-tempo/values.yaml
Update tempo.yaml for grafana-tempo 2
=> [bitnami/grafana-tempo] Update grafana-tempo-2

bitnami/kube-prometheus/Chart.yaml, bitnami/kube-prometheus/values.yaml
Change description for prometheus.ingress in values.yaml
Benefits
- [ X Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
=> [bitnami/kube-prometheus] fix typo in values.yaml

bitnami/metallb/Chart.yaml, bitnami/metallb/templates/controller/rbac.yaml, bitnami/metallb/templates/speaker/rbac.yaml
- fixes #https://github.com/bitnami/charts/issues/15095
Related to #15096
=> [bitnami/metallb] fix failed-to-list-namespaces issue

bitnami/kafka/Chart.yaml
bump kafka chart to 21.x
- fixes #15160
=> [bitnami/kafka] bump to 21.x

bitnami/metallb/Chart.yaml, bitnami/metallb/templates/networkpolicy.yaml, bitnami/metallb/values.yaml
- fixes #15094
Related to #15097
=> [bitnami/metallb] fix failed-to-call-webhook issue

bitnami/tomcat/Chart.yaml, bitnami/tomcat/templates/prometheusrule.yaml
* fix prometheusRule.additionalLabels conditionnal (`with` -> `if`)
* normalise template to be like other charts
- fixes #
- [] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
=> [bitnami/tomcat] promrule additional labels

bitnami/mongodb/Chart.yaml, bitnami/mongodb/values.yaml
=> [bitnami/mongodb]  fixing doc comment

bitnami/kubernetes-event-exporter/Chart.yaml, bitnami/kubernetes-event-exporter/templates/deployment.yaml
This change resolves an issue with the service selector for the metrics in the Kubernetes Event Exporter chart. The service was trying to match the label `app.kubernetes.io/component: kubernetes-event-exporter`, but this was not present on the pod. I have updated the pod spec to include that label and the metrics now work without any patching.
Metrics are functioning without patches.
N/A
- fixes #
=> [bitnami/kubernetes-event-exporter] Resolve issue with servicemonitor selector

bitnami/harbor/Chart.yaml, bitnami/harbor/templates/core/core-cm-envvars.yaml
Add github-ghcr as allowed proxy cache type.
It is supported since https://github.com/goharbor/harbor/pull/16834
Be able to create a proxy cache project with Github GHCR type.
=> bitnami/harbor: Add github-ghcr as allowed proxy cache type

.vib/whereabouts/goss/goss.yaml, .vib/whereabouts/goss/vars.yaml, .vib/whereabouts/vib-publish.json, .vib/whereabouts/vib-verify.json, bitnami/mariadb/values.yaml, bitnami/whereabouts/.helmignore, bitnami/whereabouts/Chart.lock, bitnami/whereabouts/Chart.yaml, bitnami/whereabouts/README.md, bitnami/whereabouts/crds/whereabouts.cni.cncf.io_ippools.yaml, bitnami/whereabouts/crds/whereabouts.cni.cncf.io_overlappingrangeipreservations.yaml, bitnami/whereabouts/templates/NOTES.txt, bitnami/whereabouts/templates/_helpers.tpl, bitnami/whereabouts/templates/clusterrole.yaml, bitnami/whereabouts/templates/clusterrolebinding.yaml, bitnami/whereabouts/templates/daemonset.yaml, bitnami/whereabouts/templates/extra-list.yaml, bitnami/whereabouts/templates/service-account.yaml, bitnami/whereabouts/values.yaml
This PR adds a helm chart for Whereabouts. It is based on the upstream [installation instructions](https://github.com/k8snetworkplumbingwg/whereabouts/blob/master/doc/crds/daemonset-install.yaml). As this updates the CNI configuration, it needs to be root and privileged.
New product in our catalog
n/a
- fixes #
=> [bitnami/whereabouts] feat: :tada: Add chart

bitnami/harbor/Chart.yaml
https://github.com/bitnami/charts/pull/15337 already bumped to 16.4.3
Be able to use the fix  https://github.com/bitnami/charts/pull/15336 in a chart.
=> [bitnami/harbor] bump patch version

.markdownlint.json
Disable rule [MD047](https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md#md047---files-should-end-with-a-single-newline-character) in the markdown linter.
This rule can be ignored. Several editors and our automations remove the latest line in the README.md files.
None
- fixes https://github.com/bitnami/charts/actions/runs/4356225484
=> [bitnami/charts] Disable makdownlint rule MD047

.github/workflows/cd-pipeline.yml, bitnami/whereabouts/Chart.yaml
=> [bitnami/whereabouts] chore: :construction_worker: Enable CD Pipeline

.vib/whereabouts/vib-publish.json, bitnami/whereabouts/Chart.yaml
Add missing fields in `vib-publish.json` pipeline definition.
The asset is published.
None.
NA
NA
=> [bitnami/whereabouts] Fix VIB publish pipeline

bitnami/cassandra/Chart.yaml, bitnami/cassandra/templates/statefulset.yaml
In our Production Environment we had to limit every emptyDir Volume. And the certs-shared emptyDir is the only one without sizeLimit. In this PR i hardcoded the Limit to 1Gi I think this should be enough for two certificate files ;-) 
- fixes #
=> [bitnami/cassandra] set sizeLimit only for certs-shared emptyDir

bitnami/contour/Chart.yaml, bitnami/contour/resources/contourconfiguration.yaml, bitnami/contour/resources/contourdeployments.yaml, bitnami/contour/resources/extensionservices.yaml, bitnami/contour/resources/httpproxies.yaml, bitnami/contour/resources/tlscertificatedeligations.yaml, bitnami/contour/templates/envoy/daemonset.yaml, bitnami/contour/templates/envoy/deployment.yaml
Updates the CRDs from the upstream project to match the appVersion of the chart. Also removes the liveness probe from the envoy shutdown-manager as this was removed in the 1.24 release too.
- fixes #15354
=> [bitnami/contour] Sync upstream CRD and templates

bitnami/external-dns/Chart.yaml, bitnami/external-dns/templates/_helpers.tpl, bitnami/external-dns/templates/dep-ds.yaml
Fix the image.digest 
- fixes #15318
=> [bitnami/external-dns] fix image.digest

bitnami/grafana-tempo/Chart.yaml, bitnami/grafana-tempo/README.md, bitnami/grafana-tempo/templates/query-frontend/headless-service.yaml, bitnami/grafana-tempo/values.yaml
=> [bitnami/grafana-tempo] Add support for service.headless.annotations

bitnami/mastodon/Chart.yaml, bitnami/mastodon/templates/pvc.yaml
The name of the PVC is generated with the wrong function. It must be "mastodon.pvc", instead "mastodon.sidekiq.fullname" is used.
- fixes #
=> [bitnami/mastodon]fix: use mastodon.pvc to generate name for PersistentVolumeClaim

bitnami/memcached/Chart.yaml, bitnami/memcached/templates/statefulset.yaml
The containerSecurityContext configuration is missing from the StatefulSet template, which I believe is in error. Such configuration is required for restrictive PSS compliance.
Add securityContext to memcached metrics container in STS too. It already exists in the Deployment.
Such configuration is required e.g. for restrictive PSS compliance.
- fixes #15449
=> [bitnami/memcached] Add securityContext to memcached metrics in STS

.github/workflows/markdown-linter.yml, .markdownlintignore, README.md, template/README.md
Ignore linter errors in `LICENSE.md` and `.github/PULL_REQUEST_TEMPLATE.md`  files.
Avoid false positives.
None
Same approach applied to VMs and containers repositories
=> [bitnami/charts] Add ignored files to markdown linter

.github/workflows/cd-pipeline.yml, .vib/multus-cni/goss/goss.yaml, .vib/multus-cni/goss/vars.yaml, .vib/multus-cni/vib-publish.json, .vib/multus-cni/vib-verify.json, bitnami/multus-cni/.helmignore, bitnami/multus-cni/Chart.lock, bitnami/multus-cni/Chart.yaml, bitnami/multus-cni/README.md, bitnami/multus-cni/crds/network-attachment-definitions.yaml, bitnami/multus-cni/templates/NOTES.txt, bitnami/multus-cni/templates/_helpers.tpl, bitnami/multus-cni/templates/clusterrole.yaml, bitnami/multus-cni/templates/clusterrolebinding.yaml, bitnami/multus-cni/templates/daemonset.yaml, bitnami/multus-cni/templates/extra-list.yaml, bitnami/multus-cni/templates/service-account.yaml, bitnami/multus-cni/values.yaml
This PR adds a helm chart for Multus-CNI. It is based on the upstream [installation instructions](https://github.com/k8snetworkplumbingwg/multus-cni/blob/v3.9.3/deployments/multus-daemonset-thick-plugin.yml) for branch 3.x. As this updates the CNI configuration, it needs to be root and privileged.
New product in our catalog
n/a
- fixes #
=> [bitnami/multus-cni] feat: :tada: Add chart

bitnami/mastodon/Chart.yaml, bitnami/mastodon/templates/init-job/init-job.yaml, bitnami/mastodon/templates/sidekiq/deployment.yaml, bitnami/mastodon/templates/streaming/deployment.yaml, bitnami/mastodon/templates/web/deployment.yaml
If S3/Minio is not enabled and a PVC is used, the deployments and initjob are not rendered.
- fixes #
=> [bitnami/mastodon] render deployments when a pvc is used

bitnami/kafka/README.md
Add upgrading notes to version 21.0.0.
None
- Related to #14943
=> [bitnami/kafka] Add upgrading notes to version 21.0.0

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/templates/service.yaml
Fixes the rendering of CIDR block list for loadBalancerSourceRanges in the Kubernetes service.
Supplying a list of CIDR blocks in .Values.service.loadBalancerSourceRanges will render correctly in the final manifest.
There should be no negative effects from this change.
- fixes #15477
=> [bitnami/clickhouse] Fix rendering of CIDR block list for loadBalancerSourceRanges

bitnami/supabase/Chart.yaml, bitnami/supabase/templates/NOTES.txt
Updates the parameters for kubectl commands in NOTES.txt
The commands that NOTES.txt returns to the user don't run.
- fixes #
=> [bitnami/supabase] Fix kubectl commands in notes.txt

bitnami/harbor/Chart.lock, bitnami/harbor/Chart.yaml, bitnami/harbor/templates/nginx/configmap-http.yaml, bitnami/harbor/templates/nginx/configmap-https.yaml, bitnami/harbor/templates/portal/portal-cm.yaml
Fix the page devcenter-api-2.0 with ingress
- fixes #14137
=> [bitnami/harbor] DevCenter API 2.0 fix ingress

.vib/contour-operator/ginkgo/contour_operator_test.go
This PR is a follow-up of https://github.com/bitnami/charts/pull/15138 to avoid executing Ginkgo tests for `bintami/contour-operator` when using private images. This is needed due to the asset itself not supporting the use of private registries for the CRDs objects it uses.
Internal testing using private registries won't fail
None
Tested in fork: https://github.com/FraPazGal/charts/pull/150
=> [bitnami/contour-operator] Skip Ginkgo execution when using private registries

bitnami/rabbitmq-cluster-operator/README.md
Running `helm install my-release my-repo/rabbitmq-cluster-operators` gives the following error:
```
Error: INSTALLATION FAILED: chart "rabbitmq-cluster-operators" matching  not found in bitnami index. (try 'helm repo update'): no chart name found
```
Simple fix by removing the trailing `s` .
- fixes #
=> Fix Error: INSTALLATION FAILED: chart "rabbitmq-cluster-operators" 

.github/workflows/ci-pipeline.yml
Revert changes done over `ci-pipeline.yml` workflow in PR https://github.com/bitnami/charts/pull/15742
- https://github.com/bitnami/charts/actions/runs/4533469406?pr=15750
=> Revert temporary changes in ci-pipeline.yaml

bitnami/rabbitmq-cluster-operator/Chart.yaml, bitnami/rabbitmq-cluster-operator/crds/crd-rabbitmq-cluster.yaml
Upgrade CRD definition with changes from version [v2.1.0](https://github.com/rabbitmq/cluster-operator/releases/tag/v2.1.0)
Keep CRDs up to date.
- Related to #15725
=> [bitnami/rabbitmq-cluster-operator] Update CRDs

bitnami/nginx-ingress-controller/Chart.yaml, bitnami/nginx-ingress-controller/templates/controller-daemonset.yaml
Add dnsConfig to nginx-ingress-controller daemonset template to be able to modify resolv.conf.
Flexibility. This is an option that this project should support. It's already supported by the deployment object.
- fixes #
=> [bitnami/nginx-ingress-controller] add dnsConfig option to the daemonset

bitnami/cassandra/Chart.yaml, bitnami/cassandra/templates/statefulset.yaml
If the init-certs get restarted by K8s it will give you following prompt: 
```
Importing keystore /tmp/keystore.p12 to
/opt/bitnami/cassandra/certs/keystore...
keytool error: java.lang.NullPointerException
Existing entry alias 1 exists, overwrite?
```
Disable Prompt at keystore import
- fixes #
=> [bitnami/cassandra] Disable Prompt at keystoreimport (init-certs)

bitnami/supabase/README.md
Fix typo by change MongoDB to PostgreSQL.
Prevent people from being misinformed.
None
None
None
=> [bitnami/supabase] Fix typo: Replace MongoDB with PostgreSQL

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/statefulset.yaml
Applies same fix from #15816 to rabbitmq chart.
- fixes same issue as described in bitnami/charts#15526 for rabbitmq
Only impact is a rolling restart of the deployment due to the helm chart version change.
=> [bitnami/rabbitmq] Add missing version, kind to volumeClaimTemplates

bitnami/clickhouse/Chart.yaml, bitnami/clickhouse/templates/servicemonitor.yaml, bitnami/clickhouse/templates/statefulset.yaml
Fix of `lables` for `persistentVolume` and makes it consistent with whole repo for `servicemonitor`.
Bug is fixed and added more consistency in repo.
Template after fix is not broken anymore:
```
volumeClaimTemplates:
- metadata:
name: data
annotations:
labels:
app.kubernetes.io/name: clickhouse
helm.sh/chart: clickhouse-3.1.5
app.kubernetes.io/instance: release-name
app.kubernetes.io/component: clickhouse
test: test_label
app: clickhouse
env: uat
```
Cannot see any.
- fixes #15978
=> [bitnami/clickhouse] Clickhouse chart fix labels for persistent volumes

bitnami/redis/README.md
Add notes about RDB compatibility to README explaining how to mitigate disruptions in rolling updates caused by upgrades to Redis with forward incompatible RDBs.
In upcoming Redis 7.2 we have a new RDB format.
Smoother rolling update when RDB format changed.
None afaik
=> [bitnami/redis] Add notes about RDB compatibility in upgrades

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/_helpers.tpl
Added templating for `externalDatabase.host`
In our case we are using SQL Server running inside kubernetes for development.
And we want to use, for example `{{ .Release.Name }}-mssql.{{ .Release.Namespace }}.svc.cluster.local` as an stable endpoint.
=> [bitnami/keycloak] Added templating for `externalDatabase.host`

bitnami/spring-cloud-dataflow/README.md
Fix typo in README.md
The correct example
None
None
=> [bitnami/spring-cloud-dataflow] Fix typo in README.md

.github/workflows/ci-pipeline.yml
Upgrade `peter-evans/create-or-update-comment` action to its [latest version](https://github.com/peter-evans/create-or-update-comment/releases/tag/v3.0.0)
Keep us up to date and avoid `set-output` warnings.
Warning example here:
- https://github.com/bitnami/containers/actions/runs/4659030590/jobs/8256679021#step:4:15
=> [bitnami/charts] Upgrade comments action

.vib/flink/vib-publish.json
=> [bitnami/flink] Fix vib "helm-publish" action

bitnami/elasticsearch/README.md
Add upgrading notes for version 19.6.0 to the README.md
- related to: #15987
=> [bitnami/elasticsearch] Add upgrading notes for version 19.6.0 to the README.md

bitnami/apache/Chart.yaml, bitnami/apache/README.md, bitnami/apache/templates/deployment.yaml, bitnami/apache/values.yaml
This PR allows setting the deployment's revisionHistoryLimit to another value than the implicit default value of 10 for the Bitnami Apache chart.
Users of can set the deployment's revisionHistoryLimit to another value than the implicit default value of 10 :smile: 
None.
None.
None.
=> [bitnami/apache] Allow setting deployment's revisionHistoryLimit

bitnami/redis/Chart.yaml, bitnami/redis/README.md, bitnami/redis/values.yaml
=> [bitnami/redis] upgrade redis-exporter

bitnami/nginx/Chart.yaml, bitnami/nginx/README.md, bitnami/nginx/values.schema.json, bitnami/nginx/values.yaml
This is an old check that is no longer needed in the chart (this the only solution with this check). The pdb configuration allows you use integers or strings (percentages) to configure it.
Allows you configure maxUnavailable to 0% if needed
None
- fixes https://github.com/bitnami/charts/issues/15747
The issue above contains all the information
=> [bitnami/nginx] Allow using percentages when configuring the pdb

bitnami/spark/Chart.yaml, bitnami/spark/templates/statefulset-master.yaml, bitnami/spark/templates/statefulset-worker.yaml
Update the config path as appears in https://github.com/bitnami/containers/tree/main/bitnami/spark#mount-a-custom-configuration-file
- fixes #14468
=> [bitnami/spark] Update config path

bitnami/kube-prometheus/Chart.lock, bitnami/kube-prometheus/Chart.yaml
Updating dep kube-state-metrics from 3.3.5 to 3.4.0
When kube-state-metrics is installed via kube-prometheus, the kube-state-metrics can be scraped with #16087
- fixes #16086
=> [bitnami/kube-prometheus] Updating dep kube-state-metrics from 3.3.5 to 3.4.0

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/secrets.yaml
=> [bitnami/postgresql] Use username as key in the Service Binding secret

bitnami/mariadb/Chart.yaml, bitnami/mariadb/templates/secrets.yaml
=> [bitnami/mariadb] Use username as key in the Service Binding secret

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/secrets.yaml
=> [bitnami/mongodb] Use username as key in the Service Binding secret

bitnami/kafka/Chart.yaml, bitnami/kafka/templates/jaas-secret.yaml
=> [bitnami/kafka] Use username as key in the Service Binding secret

bitnami/mysql/Chart.yaml, bitnami/mysql/templates/secrets.yaml
=> [bitnami/mysql] Use username as key in the Service Binding secret

bitnami/spark/Chart.yaml, bitnami/spark/templates/statefulset-master.yaml, bitnami/spark/templates/statefulset-worker.yaml
- fixes #14468
The confirmation of the container is necessary to initialize the environment variable SPARK_CONF_FILE
=> [bitnami/spark] Revert change existingConfigmap

bitnami/fluent-bit/Chart.lock, bitnami/fluent-bit/Chart.yaml, bitnami/fluent-bit/README.md
Replace charts repo with oci registry links
=> [bitnami/fluent-bit] Add Fluent Bit OCI links

bitnami/rabbitmq-cluster-operator/README.md
=> [bitnami/rabbitmq-cluster-operator] Typo fix

bitnami/fluent-bit/Chart.yaml, bitnami/fluent-bit/templates/deployment.yaml
Includes imagePullSecrets helper on deployment (missing till now). 
- fixes #
=> [bitnami/fluent-bit] Include imagePullSecrets on deployment

.vib/grafana/goss/goss.yaml
Change the test temporarily until this will be fixed in https://github.com/grafana/grafana/issues/68213
When this will be fixed this test should be added again:
```
grafana-cli-data-migration:
exec: cd /opt/bitnami/grafana && grafana-cli admin data-migration encrypt-datasource-passwords
exit-status: 0
stdout:
- /datasources.*already encrypted/
```
- fixes #
=> [bitnami/grafana] Change the test temporaly

bitnami/external-dns/Chart.yaml, bitnami/external-dns/values.yaml
Fix a commented example, make it use the corresponding template variable
Uncommenting the example is now working out of the box.
=> [bitnami/external-dns] Fix securityContext example

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/NOTES.txt
When we launch keycloak chart and `tls.enabled = false` we should not print:
```bash
kubectl port-forward --namespace keycloak svc/keycloak ${HTTP_SERVICE_PORT}:${HTTP_SERVICE_PORT} ${HTTPS_SERVICE_PORT}:${HTTPS_SERVICE_PORT} &
```
but
```bash
kubectl port-forward --namespace keycloak svc/keycloak ${HTTP_SERVICE_PORT}:${HTTP_SERVICE_PORT} &
```
So the message would look like:
```
...
To access Keycloak from outside the cluster execute the following commands:
1. Get the Keycloak URL by running these commands:
export HTTP_SERVICE_PORT=$(kubectl get --namespace keycloak -o jsonpath="{.spec.ports[?(@.name=='http')].port}" services keycloak)
kubectl port-forward --namespace keycloak svc/keycloak ${HTTP_SERVICE_PORT}:${HTTP_SERVICE_PORT} &
echo "http://127.0.0.1:${HTTP_SERVICE_PORT}/"
2. Access …
```
=> [bitnami/keycloak] Fix keycloak notes message when not using tls

bitnami/fluent-bit/Chart.yaml, bitnami/fluent-bit/values.yaml
Removes default systemd input in order to support VAC distros (no systemd)
- fixes #
=> [bitnami/fluent-bit] Remove default systemd input

bitnami/supabase/Chart.yaml, bitnami/supabase/templates/studio/ingress.yaml
=> [bitnami/supabase] Fix ingress name

bitnami/contour-operator/Chart.yaml, bitnami/contour-operator/README.md, bitnami/contour-operator/templates/NOTES.txt
Deprecation of the chart Contour Operator
=> [bitnami/contour-operator] deprecate

bitnami/postgresql/Chart.yaml
Update the version of the chart 
- fixes #
=> [bitnami/postgresql] Bump the version

bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md, bitnami/wordpress/values.yaml
/kind bug
This PR fix the error related to directory permissions
Linked with https://github.com/bitnami/charts/issues/16332
=> [bitnami/wordpress] Fix NFS permission

bitnami/fluent-bit/README.md
Fix the issue reported at https://github.com/bitnami/charts/pull/16352#issuecomment-1551995527
=> [bitnami/fluent-bit] Update README.md

bitnami/contour/Chart.yaml, bitnami/contour/README.md, bitnami/contour/templates/envoy/daemonset.yaml, bitnami/contour/templates/envoy/deployment.yaml, bitnami/contour/values.yaml
Support deploy multiple contours (hostnetwork:true) with different ingresscalsses on the same node .
you can now change the following parameters in valuse.yaml  :
- metric port
- readinessProbe port
- livenessProbe port
- startupProbe port
- Add extra args to shutdown manager
- shutdown port
Deploy multiple contours(envoy) with `hostnetwork:true` on the same node by proxy chart, like this
```yaml
apiVersion: v2
name: contour-ingress-controller
description: A Helm chart for Kubernetes
type: application
version: 1.24.4
sources:
- https://artifacthub.io/packages/helm/bitnami/contour
dependencies:
- name: contour
version: 11.3.1
repository: https://charts.bitnami.com/bitnami
alias: public
- name: contour
version: 11.3.1
repository: https://charts.bitnami.com/bitnami
alias: private
- name: …
```
=> [bitnami/contour] add feature to deploy multi envoy by proxy chart

bitnami/contour/Chart.yaml, bitnami/contour/resources/contourconfiguration.yaml, bitnami/contour/resources/contourdeployments.yaml, bitnami/contour/resources/extensionservices.yaml, bitnami/contour/resources/httpproxies.yaml, bitnami/contour/resources/tlscertificatedeligations.yaml
Updates the CRDs from the upstream project to match the appVersion of the chart.
The update bot has updated the chart for the latest minor release in #16627, but the CRDs were not updated as part of that change.
Ensures the functionality described in the latest release works as expected
N/A
- fixes #
=> [bitnami/contour] Sync CRDs with upstream

bitnami/mongodb/Chart.yaml, bitnami/mongodb/templates/replicaset/statefulset.yaml
Adds missing apiVersion and kind fields to volumeClaimTemplates.
Was also implemented in charts such as Cassandra and RabbitMQ.
=> [bitnami/mongodb] Add apiVersion and kind in volumeClaimTemplates

bitnami/grafana/Chart.yaml, bitnami/grafana/templates/datasources-secret.yaml, bitnami/grafana/templates/deployment.yaml
Apply `common.tplvalues.render` funtion to following Grafana values:
- `datasources.secretDefinition`
- `dashboardsConfigMaps.configMapName`
Enables to specify a variable like `{{ .Release.Name }}` for the value of that variable so that it can be replaced on install. 
- fixes #16891
=> [bitnami/grafana] Apply template to more variables

bitnami/keycloak/Chart.yaml, bitnami/keycloak/templates/statefulset.yaml
This reverts changes from #16013, and fixes #16256
- fixes #16256
=> [bitnami/keycloak] Revert "Drop unnecessary secret moint in Keycloak container (#16013)"

.github/workflows/assign-asset-label.yml, .github/workflows/comments.yml, .github/workflows/generate-chart-readme.yml, .github/workflows/moving-cards.yml, .github/workflows/pr-reviews.yml, .github/workflows/sync-teams.yml, .github/workflows/triage.yml
Review and improve workflow permissions
Reduce the privileges of the GitHub token and use `pull_request` instead of `pull_request_target` to reduce secrets exposure. 
https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
=> [bitnami/charts] review and improve workflow permissions

.github/workflows/generate-chart-readme.yml
Fix error introduced in #16908
Use right ref.
- Relates to  #16908
=> [bitnami/charts] Fix generate-chart-readme

bitnami/rabbitmq/Chart.yaml, bitnami/rabbitmq/templates/statefulset.yaml
This change reverts changes added in #16916 and enables again #16082 since `curl` has been re-added to support the installation of custom plugins.
Recover previous changes to reduce CPU usage.
N/A
N/A
N/A
=> Re add curl validation

bitnami/metallb/Chart.yaml, bitnami/metallb/templates/controller/rbac.yaml
The clusterrole in the bitnami chart does not match some of the rbac rules from the upstream sources. This change adds a missing rule for listing nodes in the cluster as per the
[upstream](https://github.com/metallb/metallb/blob/e708fc9010afb80c379bdfadd5d543931164ca5e/config/rbac/role.yaml#L17-L22) configuration
This should fix errors like this:
```
BGPAdvertisement/kube-system/default dry-run failed, reason: Forbidden: admission webhook "bgpadvertisementvalidationwebhook.metallb.io" denied the request: nodes is forbidden: User "system:serviceaccount:kube-system:metallb-controller" cannot list resource "nodes" in API group "" at the cluster scope
```
Allows helm chart upgrades to succeed
Helm chart fails to upgrade
- fixes #
=> [bitnami/metallb] Add missing rule to controller role

.vib/spring-cloud-dataflow/cypress/cypress/integration/spring_cloud_dataflow_spec.js, bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml
This major version updates the RabbitMQ subchart.
- Related #17064
=> [bitnami/spring-cloud-dataflow] Bump rabbitmq dependency

bitnami/mysql/Chart.yaml
Bump version to fix CD pipeline
=> [bitnami/mysql] Bump version

bitnami/argo-cd/Chart.lock, bitnami/argo-cd/Chart.yaml
Update subcharts (redis)
Deliver the latest version
=> [bitnami/argo-cd] Update subcharts (redis)

bitnami/discourse/README.md, bitnami/dokuwiki/README.md, bitnami/drupal/README.md, bitnami/ghost/README.md, bitnami/jasperreports/README.md, bitnami/joomla/README.md, bitnami/magento/README.md, bitnami/mediawiki/README.md, bitnami/metallb/README.md, bitnami/moodle/README.md, bitnami/odoo/README.md, bitnami/opencart/README.md, bitnami/osclass/README.md, bitnami/phpbb/README.md, bitnami/phpmyadmin/README.md, bitnami/prestashop/README.md, bitnami/redmine/README.md, bitnami/suitecrm/README.md
From now on there won't be distinction between solutions and the support provided will be the same for all assets
=> [bitnami/several] Remove 'Community supported solution' section from READMEs

bitnami/oauth2-proxy/Chart.yaml, bitnami/oauth2-proxy/templates/_helpers.tpl
Fix typo in helpers' function name
=> [bitnami/oauth2-proxy] Fix typo in helpers' function name

bitnami/supabase/Chart.yaml, bitnami/supabase/templates/jwt-init-job.yaml
=> [bitnami/supabase] Existing jwt secret is overwritten, although it should not be.

bitnami/apisix/Chart.lock, bitnami/apisix/Chart.yaml, bitnami/apisix/README.md
Upgrade ETCD to its latest version.
Keep chart up to date.
PR #17001 contains the changes in the etcd chart.
=> [bitnami/apisix] Upgrade etcd dependency

bitnami/jupyterhub/Chart.yaml, bitnami/jupyterhub/README.md, bitnami/jupyterhub/templates/_helpers.tpl, bitnami/jupyterhub/templates/proxy/deployment.yaml, bitnami/jupyterhub/templates/proxy/service-account.yaml, bitnami/jupyterhub/values.yaml
Add serviceaccount settings to proxy deployment
Allow disabling or use of custom serviceaccount
- fixes #17255
=> [bitnami/jupyterhub] Add jupyterhub proxy serviceAccount settings

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/redis-statefulset.yaml
This commit contains the fix for https://github.com/bitnami/charts/issues/17098
- fixes #
=> [bitnami/redis-cluster] Issue #17098 - add commonLabels to the Pods

bitnami/nginx/Chart.yaml, bitnami/nginx/README.md, bitnami/nginx/templates/deployment.yaml, bitnami/nginx/values.yaml
This PR allows setting the deployment's `revisionHistoryLimit` to another value than the implicit default value of 10 for the Bitnami nginx chart.
Users of can set the deployment's `revisionHistoryLimit` to another value than the implicit default value of 10.
None.
None.
=> [bitnami/nginx] Allow setting deployment's revisionHistoryLimit

.vib/pinniped/ginkgo/pinniped_test.go, .vib/pinniped/ginkgo/scripts/pinniped-auth.sh
Update the version of pinniped cli in the test
=> [bitnami/pinniped] Update cli version and increase the timeouts

bitnami/apisix/Chart.yaml, bitnami/apisix/values.yaml
Add the plugins list to the dashboard default config
The Apisix dashboard plugin page will display the plugins correctly.
- fixes #17193
=> [bitnami/apisix] Add the plugins list to the dashboard default config

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml
=> [bitnami/spring-cloud-dataflow] Update Kafka version

bitnami/supabase/Chart.yaml, bitnami/supabase/templates/auth/service.yaml, bitnami/supabase/templates/meta/service.yaml, bitnami/supabase/templates/realtime/service.yaml, bitnami/supabase/templates/rest/service.yaml, bitnami/supabase/templates/storage/service.yaml, bitnami/supabase/templates/studio/service.yaml
=> [bitnami/supabase] Remove duplicated targetPort in service templates

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/primary/statefulset.yaml
Fix typo setting postgresPassword installing with `--set auth.postgresPassword=<password>` only.
Fix chart usage.
Not expected.
- fixes #17472
=> [bitnami/postgresql] Fix postgres password if customUser is empty

bitnami/redis/Chart.yaml, bitnami/redis/templates/master/application.yaml, bitnami/redis/templates/replicas/statefulset.yaml
Applies same fix from https://github.com/bitnami/charts/pull/15943 to redis chart
- fixes same issue described in https://github.com/bitnami/charts/pull/15816
- fixes same issue described in https://github.com/bitnami/charts/issues/15526
=> [bitnami/redis] Add missing apiVersion and kind to redis volumeClaimTemplates

.github/workflows/license-headers.yml
Run license header check only on modified files. Please note that current configuration distinguish between templates and regular yaml files.
Users won't be warned about errors in license header coming from main branch.
None identifed
- #17524
Several tests performed in a forked repository:
- https://github.com/fmulero/charts/pull/31
- https://github.com/fmulero/charts/pull/30
=> [bitnami/charts] Run license check on modified files

bitnami/sonarqube/Chart.yaml, bitnami/sonarqube/templates/service.yaml
Correctly set annotations on the Sonarqube service when service.annotations is set in the helm values.
Custom annotations can be set on the service.
None
- fixes #17566
=> [bitnami/sonarqube] Include service.annotations in template

bitnami/milvus/Chart.yaml, bitnami/milvus/templates/init-job.yaml
Depending on the system, a cat HERE-DOCUMENT command may create a temporary file in /tmp. This PR ensures that /tmp is writable so the file can be created
- fixes #
=> [bitnami/milvus] fix: :bug: Add emptyDir to init job /tmp

bitnami/airflow/Chart.yaml, bitnami/airflow/README.md, bitnami/airflow/values.yaml
Updates the `git` container image version that includes a fix for #17543
Fixes #17543 issue.
- fixes #17543
=> [bitnami/airflow] Updates the git container version

bitnami/pinniped/Chart.yaml, bitnami/pinniped/templates/concierge/credential-issuer.yaml
Only deploy CredentialIssuer when concierge is enabled.
Prevent creating useless resources.
None that I'm aware of.
=> [bitnami/pinniped] fix: deploy credentialissuer only for concierge

bitnami/etcd/Chart.yaml, bitnami/etcd/README.md, bitnami/etcd/templates/statefulset.yaml, bitnami/etcd/values.yaml
This PR adds a new value extraVolumeClaimTemplate that would allow users to define custom extraVolumeClaimTemplate for the etcd statefulset.
New feature.
None known.
None known.
=> [bitnami/etcd] Add feature extraVolumeClaimTemplate

bitnami/postgresql/Chart.yaml, bitnami/postgresql/templates/_helpers.tpl, bitnami/postgresql/templates/primary/statefulset.yaml, bitnami/postgresql/templates/secrets.yaml
The password of postgres appear in file o in a secret
- fixes #
=> [bitnami/postgresl] Remove the password in text of the statefulset

bitnami/redis-cluster/Chart.yaml, bitnami/redis-cluster/templates/NOTES.txt
=> [bitnami/redis-cluster] Get the external IP from -svc suffixed services

bitnami/cert-manager/Chart.yaml, bitnami/cert-manager/templates/NOTES.txt
Trying https://github.com/bitnami/charts/pull/17371 again with the version bump, sorry for the delay!
Fixed a typo in NOTES.txt after installing the `cert-manager` chart.
`In other to begin using certificates` => `In order to begin using certificates`
Clearer documentation.
A tiny fix. It might be worth batching up into a larger doc and NOTES updates.
N/A
I grep'd for other instances of this typo and couldn't find any.
- [ X ] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files. (In this case it was the NOTES.txt file and the version was updated.)
- [ X ] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/re …
=> [bitnami/cert-manager] Fix NOTES.txt typo

.vib/mastodon/cypress/cypress.json, .vib/mastodon/cypress/cypress/integration/mastodon_spec.js, bitnami/mastodon/Chart.yaml
I have detected our Cypress tests for `bitnami/mastodon` do not support retryability. This PR fixes that.
Cypress tests comply with our testing best practices.
None
N/A
N/A
=> [bitnami/mastodon] Make Cypress tests retriable

bitnami/minio/Chart.yaml, bitnami/minio/README.md, bitnami/minio/templates/servicemonitor.yaml, bitnami/minio/values.yaml
Add TLS support for the metrics endpoint in the ServiceMonitor 
There will be healthy targets in prometheus in case TLS in enabled for minio
- fixes https://github.com/bitnami/charts/issues/17708
=> [bitnami/minio] Add TLS scheme support to ServiceMonitor

bitnami/external-dns/Chart.yaml
Revert missing comment and indentation from https://github.com/bitnami/charts/pull/17989/files
- fixes #
=> [bitnami/external-dns] Revert pr 17989

.vib/kong/cypress/cypress/fixtures/services.json, .vib/kong/cypress/cypress/integration/kong_spec.js, bitnami/kong/Chart.yaml
Some tests do not work in air-gapped environments.
We are modifying the tests to make them work in all environments. This way we can verify that the solution works as expected. If the solution doesn't work in that environment, the tests will not be changed and support for that env will be removed.
- fixes #
=> [bitnami/kong] Adapt Kong tests to Air-gapped environments

bitnami/influxdb/Chart.yaml, bitnami/influxdb/templates/NOTES.txt
Add missing namespace flag to one of the port forward commands
Port forward command will find the service
N/A
N/A
=> [bitnami/influxdb] include namespace in port forward command

bitnami/minio/Chart.yaml, bitnami/minio/templates/servicemonitor.yaml
Provide the fix for the Service Monitor template spec in TLS configuration and relabelings
There will be no failure
- fixes https://github.com/bitnami/charts/issues/18057
=> [bitnami/minio] fix tlsConfig and indentation in ServiceMonitor

bitnami/mariadb-galera/README.md, bitnami/mariadb/README.md
Updating README of MariaDB and MariaDB Galera after updating them to MariaDB 11.0
- fixes #
=> [bitnami/*] Update MariaDB and MariaDB Galera READMEs after the latest update

bitnami/drupal/Chart.lock, bitnami/drupal/Chart.yaml, bitnami/drupal/README.md
=> [bitnami/drupal] Update MariaDB chart to 13.0

bitnami/ejbca/Chart.lock, bitnami/ejbca/Chart.yaml, bitnami/ejbca/README.md
=> [bitnami/ejbca] Update MariaDB chart to 13.0

bitnami/jasperreports/Chart.lock, bitnami/jasperreports/Chart.yaml, bitnami/jasperreports/README.md
=> [bitnami/jasperreports] Update MariaDB chart to 13.0

bitnami/joomla/Chart.lock, bitnami/joomla/Chart.yaml, bitnami/joomla/README.md
=> [bitnami/joomla] Update MariaDB chart to 13.0

bitnami/matomo/Chart.lock, bitnami/matomo/Chart.yaml, bitnami/matomo/README.md
=> [bitnami/matomo] Update MariaDB chart to 13.0

bitnami/mediawiki/Chart.lock, bitnami/mediawiki/Chart.yaml, bitnami/mediawiki/README.md
=> [bitnami/mediawiki] Update MariaDB chart to 13.0

bitnami/moodle/Chart.lock, bitnami/moodle/Chart.yaml, bitnami/moodle/README.md
=> [bitnami/moodle] Update MariaDB chart to 13.0

bitnami/osclass/Chart.lock, bitnami/osclass/Chart.yaml, bitnami/osclass/README.md
=> [bitnami/osclass] Update MariaDB chart to 13.0

bitnami/phpbb/Chart.lock, bitnami/phpbb/Chart.yaml, bitnami/phpbb/README.md
=> [bitnami/phpbb] Update MariaDB chart to 13.0

bitnami/prestashop/Chart.lock, bitnami/prestashop/Chart.yaml, bitnami/prestashop/README.md
=> [bitnami/prestashop] Update MariaDB chart to 13.0

bitnami/redmine/Chart.lock, bitnami/redmine/Chart.yaml, bitnami/redmine/README.md
=> [bitnami/redmine] Update MariaDB chart to 13.0

bitnami/wordpress/Chart.lock, bitnami/wordpress/Chart.yaml, bitnami/wordpress/README.md
=> [bitnami/wordpress] Update MariaDB chart to 13.0

bitnami/opencart/Chart.lock, bitnami/opencart/Chart.yaml, bitnami/opencart/README.md
=> [bitnami/opencart] Update MariaDB chart to 13.0

bitnami/spring-cloud-dataflow/Chart.lock, bitnami/spring-cloud-dataflow/Chart.yaml, bitnami/spring-cloud-dataflow/README.md, bitnami/spring-cloud-dataflow/values.yaml
Updates Kafka subchart after its new major #17507
=> [bitnami/spring-cloud-dataflow] Update Kafka subchart 24.0.0
