bitnami/node/Chart.yaml
bitnami/node/README.md
bitnami/node/templates/deployment.yaml
bitnami/node/values.yaml

This pull request adds a Node parameter to overwrite the default install command (`npm install`) with a custom one.
**Benefits**
There are deloy scenarios, in which `npm install` is not desired upon initialization - for example, when a complete and tested "fixed package", including node_modules, is put together through CI workflows and saved in a "distribution"-repository. In those cases, it is desired to prevent npm from changing node_modules, package.json or package-lock.json by accident. I thought it would be better to give the option to overwrite the install-command instead of just making it optional.
This feature should be non-breaking, since the default option is the same as the hard-coded command before the change. In case …

[bitnami/node] Added possibility to overwrite npm install-command

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/ci/extended-config.yaml
bitnami/postgresql/templates/_helpers.tpl

This PR fixes a bug introduced in the "postgresql.primary.extendedConfigmapName" at #8827. It also improves the githooks coverage to ensure we don't include break this functionality anymore.
**Benefits**
Users can actually use the `primary. extendedConfiguration` parameter.
None
- fixes #8884
N/A
**Checklist**

[bitnami/postgresql] Fix "postgresql.primary.extendedConfigmapName" named template

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/primary/statefulset.yaml

The secret key to obtain the password from is different depending on whether a custom user was set or not. Therefore, we need to take this into account.
**Benefits**
Users can enable metrics correctly.
None
- fixes #8896
Bug introduced by me at https://github.com/bitnami/charts/pull/8827
**Checklist**

[bitnami/postgresql] Fix PostgreSLQ password in metrics container

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/statefulset.yaml

This change allows a user to add arbiter.extraVars and to enable TLS without duplicating MONGODB_EXTRA_FLAGS environment variable. Details are given in the linked issue.
**Benefits**
Fix a bug.
None.
- fixes #8872
None.
**Checklist**

[bitnami/mongodb] fix duplicated arbiter MONGODB_EXTRA_FLAGS env var

---

bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/deployment.yaml

It would be great to be able to add annotations for the main deployment.
Our use case is that we automatically inspect all components running in the cluster to give advice about best practices etc. To ignore some rules per object we need to be able to set annotations.
There is already a property called commonAnnotations, but it is not applied to the deployment
**Checklist**
- [ x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [ x] Variables are documented in the values.yaml and added to the README.md using (readme-generator-for-helm)[https://github.com/bitnami-labs/readme-generator-for-helm]
- [x ] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
- [ x] All commits signed off and in agreement of …

[bitnami/external-dns]fix: add commonAnnotations to deployment

---

bitnami/haproxy/Chart.yaml
bitnami/haproxy/templates/service.yaml

Fixes issue with haproxy's service not working when LoadBalancer `service.type` is used, caused by a duplicated `loadBalancerSourceRanges` entry.
**Checklist**

[bitnami/haproxy] Fix service duplicated 'loadBalancerSourceRanges'

---

.github/ct-lint.yaml
.github/workflows/lint-test.yaml

It shouldn't be required to increment the chart version to update README.md(s) or equivalent files.
**Benefits**
N/A
None
N/A
N/A
**Checklist**

Avoid running chart version increment validation when it's not required

---

bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/templates/master/application.yaml
bitnami/redis/templates/master/pvc.yaml
bitnami/redis/values.schema.json
bitnami/redis/values.yaml

Allow user to change `Kind` type on Redis Master from default `StatefulSet` to `Deployment`.
**Benefits**
This can be useful for people who want a single Pod with no persistent storage, as per current behaviour, if the node where StatefulSet is running goes down, Redis won't start until the node is recovered.
None, user is able to switch between options.
- fixes #6386
**Checklist**

[bitnami/redis] Allow to change Workload as StatefulSet or Deployment

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/templates/statefulset.yaml
bitnami/rabbitmq/values.yaml

Signed-off-by: Fabio Castagnino <fabio.castagnino@outlook.it>
add support for custom mountPath and subpath
**Benefits**
mountPath: useful when using custom RabbitMQ images
subPath: useful in dev environments and one PV for multiple services
- fixes #
**Checklist**

[bitnami/rabbitmq] Add support for custom mountPath and subpath

---

bitnami/airflow/Chart.yaml
bitnami/airflow/templates/config/configmap.yaml
bitnami/airflow/templates/scheduler/deployment.yaml
bitnami/airflow/templates/worker/statefulset.yaml

This PRs fixes references to deprecated parameters at https://github.com/bitnami/charts/pull/8909
**Benefits**
User can use custom ports.
None
N/A
N/A
**Checklist**

[bitnami/airflow] Fix for custom service port

---

bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/templates/secret-google.yaml

Fix the condition for google secret creation
- fixes #8850
**Checklist**

[bitnami/oauth2-proxy] Google is secret always created

---

bitnami/concourse/Chart.yaml
bitnami/concourse/ci/global-values.yaml
bitnami/concourse/templates/_helpers.tpl
bitnami/concourse/templates/web/deployment.yaml
bitnami/concourse/templates/worker/deployment.yaml

The chart isn't taken into account the `global.postgresql.auth` values, this PR address this.
**Benefits**
The chart is consistent with its dependency's values.
None
N/A
N/A
**Checklist**

[bitnami/concourse] Add support to PostgreSQL globals

---

bitnami/tomcat/Chart.yaml
bitnami/tomcat/templates/_helpers.tpl
bitnami/tomcat/templates/_pod.tpl

Signed-off-by: Peter Kassak <48527944+cache-sk@users.noreply.github.com>
After previous pull with metrics fixes i have noticed, that exporter is reporting only scrape error. It was caused by removing CATALINA_OPTS enviroment variable in pull #7707, so tomcat.catalinaOpts was unused at all and tomcat was not started with JMX enabled.
So this pull is restoring this eviroment variable and adding little tweak to tomcat.catalinaOpts to not add metrics.jmx.catalinaOpts if only catalinaOpts is used.
**Benefits**
Exporter is now exporting again! :)
None?
None reported.
None.
**Checklist**

[bitnami/tomcat] Another monitoring fixes

---

bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md
bitnami/spring-cloud-dataflow/templates/server/configmap.yaml
bitnami/spring-cloud-dataflow/values.yaml

Signed-off-by: CEDDM <52827991+CEDDM@users.noreply.github.com>
Change values.yml and server/configmap.yml
**Benefits**
Allow common application properties configuration in SCDF server configmap
fixes #8955 
**Checklist**

[bitnami/spring-cloud-dataflow] Add common application properties configuration

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/_helpers.tpl

The referenced init-scripts ConfigMap name isn't correct when using "replication" architecture. This PR address this bug.
**Benefits**
Users can actually consume custom init scripts.
None
- fixes #8997
N/A
**Checklist**

[bitnami/postgresql] Fix init scripts cm reference

---

bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/templates/grafana.yaml

First time doing a PR to this project - hopefully I did it right?
Adds a nodeSelector parameter to the grafana CRD
**Benefits**
Unlocks the possibility to contain grafana-deployment pods in certain nodepools.
N/A
- fixes #8987 (https://github.com/bitnami/charts/issues/8987)
**Checklist**

[bitnami/grafana-operator] Include nodeSelector parameter

---

bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/README.md
bitnami/postgresql-ha/templates/pgpool/service.yaml
bitnami/postgresql-ha/templates/postgresql/service-headless.yaml
bitnami/postgresql-ha/templates/postgresql/service.yaml
bitnami/postgresql-ha/values.yaml

This change makes the name of service port customizable. 
**Benefits**
Other workload might need port name following certain pattern to interpret port traffic and this change enables those use cases.
- issue #8999 
**Checklist**

[bitnami/postgresql-ha] Add Service port name in Traffic Exposure parameters and bring README.md up to date

---

bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/svc-cluster-external-access.yaml

As reported at https://github.com/bitnami/charts/issues/8917#issuecomment-1039677569, this PR https://github.com/bitnami/charts/pull/8821 introduced a bug when using `externalAccess.enabled=true`.
The issue was caused because of the `.Release.namespace` being used inside a `range` loop.
**Benefits**
Fixes issue with manifest when using `externalAccess`.
None known
**Checklist**

[bitnami/redis-cluster] Fix namespace issue with externalAccess

---

bitnami/contour/Chart.yaml
bitnami/contour/templates/contour/rbac.yaml

This change adds support for [Kubernetes Gateway API v1alpha2](https://gateway-api.sigs.k8s.io/v1alpha2/references/spec/). This API version migrates to a new API group (`gateway.networking.k8s.io`), and from `BackendPolicy` to `ReferencePolicy`.
**Benefits**
Users of this chart will be able to use the new version of the Gateway API, as supported by Contour v1.20.0.
The resource name change coupled with how we phrase this rule means that we support both resource name for both API groups. I'd be happy to change this to be more explicit, this just seemed cleaner and more concise.
**Checklist**

[bitnami/contour] Support Gateway API v1alpha2 resources and API groups

---

bitnami/kafka/Chart.yaml
bitnami/kafka/templates/kafka-metrics-deployment.yaml
bitnami/kafka/templates/scripts-configmap.yaml

remove quotes from kafka_exporter deployment
**Benefits**
working exporter
none
- fixes #9041
Pls merge PR #9038 first 
**Checklist**

[btinami/kafka] Fixes kafka_exporter with TLS

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/_helpers.tpl
bitnami/postgresql/templates/primary/statefulset.yaml
bitnami/postgresql/templates/read/statefulset.yaml

It shouldn't be necessary to run a "root" container to adapt volume permissions to enable TLS. This PR address that.
**Benefits**
TLS without using a "root" container.
None
- fixes #8990
N/A
**Checklist**

[bitnami/postgresql] Allow enabling TLS without volume-permissions

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/primary/statefulset.yaml

Signed-off-by: Jan Lauber <jan.lauber@protonmail.ch>
It fixes a render bug for the statefulset init-chmod-data container.
**Benefits**
The resources for the mentioned init container will be prober set.
People who set the init container resources in the values file on `.Values.resources` (which is not documented so it's a bug) have to set the `.Values.primary.resources` values.
- fixes #9052
**Checklist**

[bitnami/postgresql] fix init-chmod-data resources value rendering

---

.github/workflows/vib-early-feedback.yaml

Currently, the Github action was obtaining the list of files by executing
```
git diff origin/master HEAD
```
However, this was causing issues with branches that had commits behind master, as the list of changed files was included changes done by other commits. This PR changes the action so it uses the Github API to obtain the list of changed files.
We considered other options like jitterbit/get-changed-files but this does not support pull_request_target actions. We also checked `git merge-base` but it was unable to find the fork-point as soon as the branch had commits behind master.
It was tested successfully in this PR: https://github.com/javsalgar/charts-1/pull/10. In it, we can see commits …

[bitnami/*] test: :children_crossing: Improve "Early Feedback" list of changed files

---

bitnami/mariadb-galera/Chart.yaml
bitnami/mariadb-galera/templates/pdb.yaml

**Benefits**
None
- fixes #7488
N/A
**Checklist**

[bitnami/mariadb-galera] Do not hardcode PDB apiVersion

---

bitnami/osclass/Chart.yaml
bitnami/osclass/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/osclass] Do not hardcode PDB apiVersion

---

bitnami/redmine/Chart.yaml
bitnami/redmine/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/redmine] Do not hardcode PDB apiVersion

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/bucketweb/pdb.yaml
bitnami/thanos/templates/query-frontend/pdb.yaml
bitnami/thanos/templates/query/pdb.yaml
bitnami/thanos/templates/receive-distributor/pdb.yaml
bitnami/thanos/templates/receive/pdb.yaml
bitnami/thanos/templates/ruler/pdb.yaml
bitnami/thanos/templates/storegateway/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/thanos] Do not hardcode PDB apiVersion

---

bitnami/airflow/Chart.yaml
bitnami/airflow/templates/scheduler/poddisruptionbudget.yaml
bitnami/airflow/templates/web/poddisruptionbudget.yaml
bitnami/airflow/templates/worker/poddisruptionbudget.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/airflow] Do not hardcode PDB apiVersion

---

bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/templates/controller/pdb.yaml
bitnami/argo-workflows/templates/server/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/argo-workflows] Do not hardcode PDB apiVersion

---

bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/aspnet-core] Do not hardcode PDB apiVersion

---

bitnami/etcd/Chart.yaml
bitnami/etcd/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/etcd] Do not hardcode PDB apiVersion

---

bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/external-dns] Do not hardcode PDB apiVersion

---

bitnami/consul/Chart.yaml
bitnami/consul/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/consul] Do not hardcode PDB apiVersion

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/cassandra] Do not hardcode PDB apiVersion

---

bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/templates/hub/pdb.yaml
bitnami/jupyterhub/templates/proxy/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/jupyterhub] Do not hardcode PDB apiVersion

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/keycloak] Do not hardcode PDB apiVersion

---

bitnami/contour/Chart.yaml
bitnami/contour/templates/default-backend/poddisruptionbudget.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/contour] Do not hardcode PDB apiVersion

---

bitnami/kong/Chart.yaml
bitnami/kong/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/kong] Do not hardcode PDB apiVersion

---

bitnami/mariadb/Chart.yaml
bitnami/mariadb/templates/primary/pdb.yaml
bitnami/mariadb/templates/secondary/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/mariadb] Do not hardcode PDB apiVersion

---

bitnami/logstash/Chart.yaml
bitnami/logstash/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/logstash] Do not hardcode PDB apiVersion

---

bitnami/metrics-server/Chart.yaml
bitnami/metrics-server/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/metrics-server] Do not hardcode PDB apiVersion

---

bitnami/minio/Chart.yaml
bitnami/minio/templates/distributed/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/minio] Do not hardcode PDB apiVersion

---

bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/config-server/config-server-poddisruptionbudget.yaml
bitnami/mongodb-sharded/templates/mongos/mongos-poddisruptionbudget.yaml
bitnami/mongodb-sharded/templates/shard/shard-data-poddisruptionbudget.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/mongodb-sharded] Do not hardcode PDB apiVersion

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/pdb.yaml
bitnami/mongodb/templates/hidden/pdb.yaml
bitnami/mongodb/templates/replicaset/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/mongodb] Do not hardcode PDB apiVersion

---

bitnami/mysql/Chart.yaml
bitnami/mysql/templates/primary/pdb.yaml
bitnami/mysql/templates/secondary/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/mysql] Do not hardcode PDB apiVersion

---

bitnami/nats/Chart.yaml
bitnami/nats/templates/poddisruptionbudget.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/nats] Do not hardcode PDB apiVersion

---

bitnami/nginx-ingress-controller/Chart.yaml
bitnami/nginx-ingress-controller/templates/controller-poddisruptionbudget.yaml
bitnami/nginx-ingress-controller/templates/default-backend-poddisruptionbudget.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/nginx-ingress-controller] Do not hardcode PDB apiVersion

---

bitnami/nginx-intel/Chart.yaml
bitnami/nginx-intel/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/nginx-intel] Do not hardcode PDB apiVersion

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/nginx] Do not hardcode PDB apiVersion

---

bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/oauth2-proxy] Do not hardcode PDB apiVersion

---

bitnami/odoo/Chart.yaml
bitnami/odoo/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/odoo] Do not hardcode PDB apiVersion

---

bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/poddisruptionbudget.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/redis-cluster] Do not hardcode PDB apiVersion

---

bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/templates/pgpool/pdb.yaml
bitnami/postgresql-ha/templates/postgresql/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/postgresql-ha] Do not hardcode PDB apiVersion

---

bitnami/wordpress-intel/Chart.yaml
bitnami/wordpress-intel/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/wordpress-intel] Do not hardcode PDB apiVersion

---

bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/templates/prometheus-proxy/pdb.yaml
bitnami/spring-cloud-dataflow/templates/server/pdb.yaml
bitnami/spring-cloud-dataflow/templates/skipper/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/spring-cloud-dataflow] Do not hardcode PDB apiVersion

---

bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/crds/crd-alertmanager-config.yaml
bitnami/kube-prometheus/templates/alertmanager/pdb.yaml
bitnami/kube-prometheus/templates/prometheus/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/kube-prometheus] Do not hardcode PDB apiVersion

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/pdb.yaml

**Benefits**
None
N/A
N/A
**Checklist**

[bitnami/wordpress] Do not hardcode PDB apiVersion

---

bitnami/parse/Chart.lock
bitnami/parse/Chart.yaml
bitnami/parse/README.md

In this version, the mongodb-exporter bundled as part of the bitnami/mongodb dependency was updated to a new version which, even it is not a major change, can contain breaking changes (from `0.11.X` to `0.30.X`).
Please visit the release notes from the upstream project at https://github.com/percona/mongodb_exporter/releases

[bitnami/parse] Bump bundled MongoDB subchart

---

bitnami/node/Chart.lock
bitnami/node/Chart.yaml
bitnami/node/README.md

In this version, the mongodb-exporter bundled as part of the bitnami/mongodb dependency was updated to a new version which, even it is not a major change, can contain breaking changes (from `0.11.X` to `0.30.X`).
Please visit the release notes from the upstream project at https://github.com/percona/mongodb_exporter/releases

[bitnami/node] Bump bundled MongoDB subchart

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/deployment.yaml

Replaces the `find | xargs` logic with `chown -R`, as `xargs` would fail with error `missing operand after` if `find` didn't find any coincidence`.
There are other alternatives that are discussed here: https://unix.stackexchange.com/questions/491948/chown-missing-operand-after-rootusers
Such as using `find -exec` or adding `xargs` flag `-r` to not fail if no args are provided, but I decided to keep it simple and go for the `chown -R` as we do in other charts.
- fixes #9074
**Checklist**

[bitnami/wordpress] Add flag -r to xargs to avoid failure on empty input

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/README.md
bitnami/postgresql/templates/primary/statefulset.yaml
bitnami/postgresql/templates/read/statefulset.yaml
bitnami/postgresql/values.yaml

Signed-off-by: Hayden James <hayden.james@gmail.com>
This adds the "hostNetwork" option to the StatefulSets used for the PostgreSQL chart in order to enable/disable that feature.  This allows you to enable host networking for the PostgreSQL pod, instead of only forcing the user to user a network bridge.
**Checklist**

[bitnami/postgresql] Add hostNetwork option for PostgreSQL StatefulSets

---

bitnami/contour-operator/Chart.yaml

This trivial PR just fixes a wrong icon in the `contour-operator` chart as the current one yields a 404.
**Benefits**
This asset will have an icon again.
N/A
N/A
N/A
**Checklist**

[bitnami/contour-operator] Fix contour-operator icon

---

bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml
bitnami/discourse/README.md
bitnami/discourse/ci/global-values.yaml
bitnami/discourse/ci/ingress.yaml
bitnami/discourse/templates/NOTES.txt
bitnami/discourse/templates/_helpers.tpl
bitnami/discourse/templates/configmaps.yaml
bitnami/discourse/templates/deployment.yaml
bitnami/discourse/templates/ingress.yaml
bitnami/discourse/templates/networkpolicy-backend-ingress.yaml
bitnami/discourse/templates/networkpolicy-egress.yaml
bitnami/discourse/templates/networkpolicy-ingress.yaml
bitnami/discourse/templates/pvc.yaml
bitnami/discourse/templates/secrets-database.yaml
bitnami/discourse/templates/secrets-discourse.yaml
bitnami/discourse/templates/secrets-redis.yaml
bitnami/discourse/templates/service.yaml
bitnami/discourse/templates/serviceaccount.yaml
bitnami/discourse/templates/tls-secrets.yaml
bitnami/discourse/values.yaml

This PR standardizes the `bitnami/discourse` chart to be in line with the rest of the catalog.
**Benefits**
Changes the values structure forcing a major bump, check the README.md for more information.
N/A
Triggered after https://github.com/bitnami/charts/pull/8827 (major bump in PostgreSQL)
**Checklist**

[bitnami/discourse] Chart standardization

---

bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/README.md
bitnami/kubeapps/templates/NOTES.txt
bitnami/kubeapps/templates/_helpers.tpl
bitnami/kubeapps/templates/kubeappsapis/deployment.yaml
bitnami/kubeapps/templates/kubeappsapis/rbac_fluxv2.yaml
bitnami/kubeapps/values.yaml

This change contains the changes landed in our Kubeapps chart at https://github.com/kubeapps/kubeapps/pull/4265 , but without the update to the plugin paths for now.
Adding Antonio and Rafa as reviewers just to ensure we're on the same page about landing this change now.
**Benefits**
It gives us a better UX for choosing which packaging system to use with Kubeapps, by allowing the user to choose just the packaging system, while the chart then calculates the required plugins. It also allows the chart to conditionally enable/disable chart dependencies based on the chosen packaging.
Backwards compatible as setting the `kubeappsapis.enabledPlugins` will override (see paste below)
I understand the readme-generator-for-helm check failure is …

bitnami/kubeapps Improved handling of packaging options for Kubeapps

---

.github/PULL_REQUEST_TEMPLATE.md

I've noticed the link for the readme-generator project wasn't being rendered due to a simple markdown typo. This PR is to address this trivial bug.
**Benefits**
Subsequent PRs will have the proper syntax.
N/A
N/A
N/A
**Checklist**

Fix PR template link

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/README.md
bitnami/postgresql/templates/primary/statefulset.yaml
bitnami/postgresql/templates/read/statefulset.yaml
bitnami/postgresql/values.yaml

Signed-off-by: Hayden James <hayden.james@gmail.com>
This adds the "hostIPC" option to the StatefulSets used for the PostgreSQL chart in order to enable/disable that feature.  This allows you to enable host IPC (inter-process communication) for the PostgreSQL pod, instead of only forcing the user to use an IPC namespace.
**Checklist**

[bitnami/postgresql] Add hostIPC option for PostgreSQL StatefulSets

---

bitnami/mariadb-galera/Chart.yaml
bitnami/mariadb-galera/templates/statefulset.yaml
bitnami/mariadb-galera/values.yaml

Currently, there is a race condition when using init scripts in mariadb-galera:
- Node 0 may be executing init scripts operations
- Node 1 gets started because the readiness probe of node 0 passes
- Node 0 shuts down and then cannot start because of this error
```
It may not be safe to bootstrap the cluster from this node. It was not the last one to leave the cluster and may not contain all the updates.
```
In order to fix this, the readiness probe willl check that the init scripts have been executed prior to marking the node as ready.
**Benefits**
Avoid race condition
n/a
- fixes https://github.com/bitnami/charts/issues/1395 …

[bitnami/mariadb-galera] fix: :bug: Avoid race condition when using init scripts

---

bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml
bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml

Replace "configMapRef" with "secretRef" when configuring extra variables, so that it correctly points to a secret instead of a config map.
**Benefits**
The configuration is working correctly now
-
- fixes #
**Checklist**

[bitnami/mongodb-sharded] Replace "configMapRef" with "secretRef" when configuring extra variables

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/scripts-configmap.yaml

This change removes a timeout when trying to retrieve the information on who is the Master from Sentinel
**Benefits**
Currently, if the command times out it is been treated as if there was no Master elected. If there's no master elected, the pod calling this command assumes the Master role, which means sometimes multiple pods could call themselves "master" as explained on https://github.com/bitnami/charts/issues/8851
If this command takes too long to return the startup could freeze, but this probably indicates a network problem or an issue with Sentinel
- fixes #8851 
**Checklist**

[bitnami/redis] Removing timeout on Sentinel command

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/receive/statefulset.yaml

Add volumePermission initContainer for Thanos Receive `statefulset.yaml`
**Benefits**
Fix the issue with k8s securityContext in some Cloud Providers. 
No drawbacks as my understanding, just copy the configs from other component.
**Checklist**

[bitnami/Thanos] Add volumePermission initContainer for receive.statefulset

---

.github/workflows/generate-chart-readme.yml

The readme-generator command `--metadata` was renamed as `--schema`. The readme generator commit-id was recently updated here: https://github.com/bitnami/charts/pull/9181 but the command wasn't, leading to this error:

Update readme-generator command in github-actions

---

bitnami/grafana-tempo/Chart.yaml
bitnami/grafana-tempo/values.yaml

Increase initialDelaySeconds parameter for Grafana Tempo Compactor to wait for the cluster to be ready. There is a new version of the solution and it takes more time to be fully deployed
This PR increases the initialDelaySeconds parameter for Grafana Tempo Compactor to wait for the cluster to be ready. Grafana Tempo 1.3.x seems to take more time to be deployed.
**Benefits**
Grafana-Tempo 1.3.1 will be properly deployed
Solution will take some more seconds to be fully deployed
- fixes #
**Checklist**
- [NA] Variables are documented in the values.yaml and added to the README.md using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)

[bitnami/grafana-tempo] Increase initialDelaySeconds parameter for Grafana Tempo Compactor

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/scripts-configmap.yaml

Signed-off-by: Jose Galvez <jose.galvez@appian.com>
This change removes a second timeout when trying to retrieve the information on who is the Master from Sentinel that was missed under #9169 
**Benefits**
Currently, if the command times out it is been treated as if there was no Master elected. If there's no master elected, the pod calling this command assumes the Master role, which means sometimes multiple pods could call themselves "master" as explained on https://github.com/bitnami/charts/issues/8851
If this command takes too long to return the startup could freeze, but this probably indicates a network problem or an issue with Sentinel
- fixes #8851 
**Checklist**

[bitnami/redis] Removing second timeout on Sentinel command

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/ingress.yaml

Fix incorrect port in ingress definition. If we enabled security, `https` is set as name for most of the exposed ports but ingress is using always http. The porpouse of the change is use the same logic in the ingress definition.
Not identified
- fixes #9159
**Checklist**

[bitnami/elasticsearch] Fix named port in ingress

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/values.yaml

I noticed the wordpress metrics were not being scrapped by prometheus and it turned out the port annotation wasn't being set.
**Checklist**

[bitnami/wordpress] corrected metrics annotation

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/metrics-deploy.yaml

Always use the correct elasticsearch port for the exporter.
**Benefits**
With this change, the exporter is able to scrape the elasticsearch cluster regardless of the nodes configuration.
None.
- fixes #https://github.com/bitnami/charts/issues/9182
Remove the usage of parameter chart and use a hardcoded value.
**Checklist**

[bitnami/elasticsearch] fix use the correct elasticsearch port for exporter.

---

bitnami/nginx/Chart.yaml
bitnami/nginx/README.md
bitnami/nginx/templates/deployment.yaml
bitnami/nginx/values.yaml

Signed-off-by: Hayden James <hayden.james@gmail.com>
This adds the "hostIPC" option to the Deployment used for the NGINX chart in order to enable/disable that feature.  This allows you to enable host IPC (inter-process communication) for the NGINX pods, instead of only forcing the user to use an IPC namespace.
**Checklist**

[bitnami/nginx] Add hostIPC option for NGINX Deployment

---

bitnami/wordpress/Chart.lock
bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/deployment.yaml
bitnami/wordpress/values.yaml

Signed-off-by: Michiel Hobbelman <michiel@hobbelman.net>
The use of `-mindepth 0` instead of `-mindepth 1` makes sure  the chown command  affects  not only the sub-directories but also the parent-directory /bitnami/wordpress/ . This is necessary to prevent ```
cp: cannot create regular file '/bitnami/wordpress/wp-config.php': Permission denied``` in the case of  an existing empty  PVC being provided via  helm install option  `persistence.existingClaim`.
As discussed in #9074 
**Benefits**
- fixes #9074 
**Checklist**

[bitnami/wordpress] Let the chown command  affect parent-directory /bitnami/wordpress

---

bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/README.md
bitnami/argo-cd/templates/repo-server/metrics-svc.yaml
bitnami/argo-cd/values.yaml

This PR fixes a typo in the metrics service.
**Benefits**
Users can enable metrics (`--set repoServer.metrics.enabled=true`).
None
- fixes #9241
N/A
**Checklist**

[bitnami/argo-cd] Fix svc wrong indentation

---

bitnami/common/Chart.yaml
bitnami/common/templates/_secrets.tpl

Add documentation about the order in which the common.secrets.passwords.manage function returns a secret password.
**Checklist**

[bitnami/common] Improve documentation for the common.secrets.passwords.manage function

---

bitnami/contour/Chart.yaml
bitnami/contour/README.md
bitnami/contour/templates/certgen/job.yaml
bitnami/contour/values.yaml

This PR adds a way to change the lifetime (in days) of the TLS cert generated by contour certgen for communication b/w contour and envoy services.
**Benefits**
Allows to extend the lifetime of the generated certificated and hence reduce the need to refresh the certificate.
- fixes #9224 
**Checklist**
- Running `readme-generator-for-helm` was generating too many unrelated changes, so skipped for this PR, can take it up as a separate one.
- README updated manually for now

[bitnami/contour] Add support for changing lifetime for tls certificate generated by contour certgen

---

bitnami/haproxy/Chart.lock
bitnami/haproxy/Chart.yaml
bitnami/haproxy/templates/service.yaml

- Add `loadBalancerIP` spec to the HAProxy service.
**Benefits**
- Ensure it's possible to set an IP address over the HAProxy load balancer if the option is enabled on your cloud provider.
- None
- fixes https://github.com/bitnami/charts/issues/9285
None
**Checklist**

[bitnami/haproxy] Add loadBalancerIP to Service

---

bitnami/grafana-tempo/Chart.lock
bitnami/grafana-tempo/Chart.yaml

It seems there is an issue when working with OCI registries and the definition order of the subcharts.
While the issue is solved in the Helm CLI, we are reordering the dependencies.
The upstream issue is to be created.

[bitnami/grafana-tempo] Reorder subcharts

---

bitnami/dataplatform-bp1/Chart.lock
bitnami/dataplatform-bp1/Chart.yaml
bitnami/dataplatform-bp1/README.md
bitnami/dataplatform-bp2/Chart.lock
bitnami/dataplatform-bp2/Chart.yaml
bitnami/dataplatform-bp2/README.md

This PR bumps the Kafka subchart version to its latest major.
**Benefits**
Use latest chart features
None. Upgrading from previous versions is a possibility.
N/A
N/A
**Checklist**

[bitnami/dataplatform-*] Bump Kafka subchart

---

bitnami/dataplatform-bp1/Chart.lock
bitnami/dataplatform-bp1/Chart.yaml
bitnami/dataplatform-bp1/README.md
bitnami/dataplatform-bp2/Chart.lock
bitnami/dataplatform-bp2/Chart.yaml
bitnami/dataplatform-bp2/README.md

This PR bumps the Kafka, Solr & Zookeeper subcharts version to their latest major.
**Benefits**
Use latest chart features
None. Upgrading from previous versions is a possibility.
N/A
N/A
**Checklist**

[bitnami/dataplatform-*] Bump Kafka, Solr & Zookeeper subcharts

---

bitnami/logstash/Chart.lock
bitnami/logstash/Chart.yaml
bitnami/logstash/templates/_helpers.tpl
bitnami/logstash/templates/serviceaccount.yaml
bitnami/logstash/values.yaml

…y integration
Signed-off-by: Luiz Ferreira <luiz.ferreira@idwall.co>
This config enables the logstash chart to integrate with workload identity of GCP, useful when you need to use a cloud permission on your config, like, buckets, pubsub, etc..
**Benefits**
This change implements a cleaner config of permissions when installing on a GKE cluster, with that you don't need to create a JSON Key for the logstash service acount with the cloud permission and put it inside the pod, you can config that easily using workload identity(https://cloud.google.com/kubernetes-engine/docs/how-to/workload-identity)
This is a simply configuration, doesn't affect anything related to how things work right now.
- fixes #
**Additional …

[bitnami/logstash] Adding service account config for workload identity integration

---

bitnami/kafka/Chart.yaml
bitnami/kafka/values.yaml

Fix typo mentioning Redis instead of Kafka in a comment from the _values.yaml_
- fixes #8888
**Checklist**

[bitnami/kafka] Fix typo in comment

---

.vib/wordpress/cypress/cypress/integration/utils.js
.vib/wordpress/cypress/cypress/integration/wordpress_spec.js
.vib/wordpress/cypress/cypress/support/commands.js

Added a dynamic data generator function, used to create a title of the post. Improved some of the locators to avoid flakiness and use a smarter locator strategy. 
**Test results**
Executed successfully 3 different times in a row, total 9 executions. Results of the last one: 
- [GKE](https://cp.production.k.bromelia.bitnami.net/v1/execution-graphs/457a76fb-8eb3-42b9-831c-6f582e62d32b/report) - PASS
- [AKS](https://cp.production.k.bromelia.bitnami.net/v1/execution-graphs/f89dcb60-c8cb-4dfe-8e9d-568d1e8aa655/report) - PASS
- [TKG](https://cp.production.k.bromelia.bitnami.net/v1/execution-graphs/217fa52e-9a39-4364-8f6c-9cd8713367de/report) - PASS
**Benefits**
Less flaky tests that can be run many times in a row and don't generate duplicate data. 
**Possible …

[bitnami/wordpress] WordPress test update to follow Test Strategy

---

bitnami/apache/Chart.lock
bitnami/apache/Chart.yaml
bitnami/apache/README.md
bitnami/apache/templates/prometheusrules.yaml
bitnami/apache/templates/servicemonitor.yaml
bitnami/apache/values.yaml

Currently the deployment with the proper values for metrics is failing, see
- prometheusRule
```console
$ helm template bitnami/apache --set metrics.enabled=true --set metrics.prometheusRule.enabled=true --debug -s templates/prometheusrules.yaml
---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
name: RELEASE-NAME-apache
namespace: default
labels:
app.kubernetes.io/name: apache
helm.sh/chart: apache-9.0.6
app.kubernetes.io/instance: RELEASE-NAME
app.kubernetes.io/component: metrics
{}
spec:
groups:
- name: RELEASE-NAME-apache
rules:
[]
Error: YAML parse error on apache/templates/prometheusrules.yaml: error converting YAML to JSON: yaml: line 11: did not find expected key
helm.go:88: [debug] error …
```

[bitnami/apache] Fix issue rendering metrics.*.additionalLabels

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/values.yaml

Remove unused 'database-password' key commented example
in values.yaml.
Closes #9274.

[bitnami/keycloak] Remove unused 'database-password' key

---

bitnami/jenkins/Chart.yaml
bitnami/jenkins/templates/servicemonitor.yaml
bitnami/jenkins/values.yaml

extends #9305 by fixing the rendered annotation "prometheus.io/port:" for the metrics service.
Fixes identation of label in servicemonitor.yaml which breaks the deployment.
**Benefits**
With metrics enabled the Helm chart will deploy with default values.yaml.
Deploys with metrics.servicemonitor.enabled: true
- extends #9305 
**Checklist**

[bitnami/jenkins] fix: jenkins metrics service and servicemonitor

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/networkpolicy-egress.yaml
bitnami/postgresql/templates/primary/networkpolicy.yaml
bitnami/postgresql/templates/read/networkpolicy.yaml

add namespace definition in the network policies
**Benefits**
mostly make the k8s linters happy
none I'm aware of
**Checklist**

[bitnami/postgresql] add namespace definition in network policies

---

bitnami/kong/Chart.lock
bitnami/kong/Chart.yaml
bitnami/kong/README.md
bitnami/kong/ci/values-ingress.yaml
bitnami/kong/ci/values-metrics-hpa-pdb.yaml
bitnami/kong/templates/NOTES.txt
bitnami/kong/templates/_helpers.tpl
bitnami/kong/templates/dep-ds.yaml
bitnami/kong/templates/external-database-secret.yaml
bitnami/kong/templates/hpa.yaml
bitnami/kong/templates/ingress-controller-rbac.yaml
bitnami/kong/templates/ingress-controller-serviceaccount.yaml
bitnami/kong/templates/ingress.yaml
bitnami/kong/templates/kong-prometheus-role.yaml
bitnami/kong/templates/kong-prometheus-rolebinding.yaml
bitnami/kong/templates/kong-script-configmap.yaml
bitnami/kong/templates/metrics-exporter-configmap.yaml
bitnami/kong/templates/metrics-script-configmap.yaml
bitnami/kong/templates/metrics-service.yaml
bitnami/kong/templates/migrate-job.yaml
bitnami/kong/templates/pdb.yaml
bitnami/kong/templates/service.yaml
bitnami/kong/templates/servicemonitor.yaml
bitnami/kong/templates/tls-secrets.yaml
bitnami/kong/values.yaml

This PR standardizes the `bitnami/kong` chart to be in line with the rest of the catalog.
**Benefits**
None. No major bump is required since breaking changes were added support for deprecated values using `coalesce`.
N/A
N/A
**Checklist**

[bitnami/kong] Chart standardized

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/values.yaml

Sets the recommended default for `automountServiceAccountToken` as recommended by the Kuberenets documentation.
**Benefits**
no issues with bootstrapping a keycloak cluster
none
- fixes #9372
**Checklist**

bitnami/keycloak: sets default to true for automountServiceAccountToken (#9372)

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/_helpers.tpl

Using the following `values.yaml`:
```yaml
postgresql:
enabled: false
externalDatabase:
host: "postgres"
port: 5432
user: keycloak
database: keycloak
password: "something-here"
existingSecret: ""
existingSecretPasswordKey: ""
```
Keycloak SecretRef will end up being empty:
```yaml
- name: KEYCLOAK_DATABASE_PASSWORD
valueFrom:
secretKeyRef:
name:
key: password
```
This PR fixes the issue:
```yaml
- name: KEYCLOAK_DATABASE_PASSWORD
valueFrom:
secretKeyRef:
name: keycloak
key: password
```
- fixes #9381
**Checklist**

[bitnami/keycloak] Fix externalDB issue when using 'externalDatabatase.password'

---

bitnami/mongodb/Chart.lock
bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
bitnami/mongodb/values.yaml

Currently, when a MongoDB node crashes, it will make use of the existing persistence to re-join a replica set. However, if the PVC is lost (or persistence is disabled), the node will try recreating the replica set from scratch. For covering this use case, we improved the initialization configmap with the following:
- Check if there's persistence
-  In case there's persistence, continue with the default logic
- In case there's no persistence, try querying the replicaset for an existing master
- In case the primary is the same restarting node, configure as master.
- In case the primary is another node, configure as replica of this new primary.
This should mitigate the case of MongoDB as caches and …

[bitnami/mongodb] feat: :sparkles: Check replicaset status when persistence is not detected

---

bitnami/fluentd/Chart.yaml
bitnami/fluentd/templates/aggregator-statefulset.yaml

Fixes the aggregator statefulset rendering when adding annotations.
Given a values files wich contains the following content
```yaml
aggregator:
annotations:
configmap.reloader.stakater.com/reload: fluentd-forwarder
secret.reloader.stakater.com/reload: fluentd-forwarder-certificate
```
I faced an error
```text
Error: YAML parse error on fluentd/templates/aggregator-statefulset.yaml: error converting YAML to JSON: yaml: line 15: did not find expected key
helm.go:88: [debug] error converting YAML to JSON: yaml: line 15: did not find expected key
YAML parse error on fluentd/templates/aggregator-statefulset.yaml
helm.sh/helm/v3/pkg/releaseutil.(*manifestFile).sort
helm.sh/helm/v3/pkg/releaseutil/manifest_sorter.go:146
helm.sh/helm/v3/pkg/releaseutil.SortManifests …
```

[bitnami/fluentd] fix aggregator statefulset annotations

---

bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/README.md
bitnami/redis-cluster/templates/redis-statefulset.yaml
bitnami/redis-cluster/values.yaml

Allow setting `hostNetwork: true` for pods of the redis statefulset. 
**Checklist**

[bitnami/redis-cluster] Add possibility to set `hostNetwork: true` for redis pods

---

bitnami/airflow/Chart.yaml
bitnami/airflow/templates/scheduler/service-headless.yaml

Fix a typo in the port parameter used in the `scheduler/service-headless.yaml`
- Fixes #9220

[bitnami/airflow] Fix typo in container port

---

bitnami/kibana/Chart.yaml
bitnami/kibana/templates/NOTES.txt

Signed-off-by: alukic <alukic@vmware.com>
Updated the URL in the user guide since I noticed it was pointing to an old resource. 
**Benefits**
Improved user experience. 
I don't see any.
**Checklist**

[bitnami/kibana] Updated the auth URL for Elasticsearch

---

bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/templates/scripts-configmap.yaml
bitnami/redis/values.yaml

This change ensures that fresh deployments and existing deployments continue to function with redis sentinel mode. Previously a timeout existed which caused `redis-cli` get-master to timeout after 5 seconds but this caused a few issues. This PR addresses a problem introduced by removing this timeout, as probes never successfully triggered meaning the kubelet constantly restarted the pod before it managed to get up and running.
**Benefits**
Timeout is configurable for those who wish to reduce it, and startupProbes are enabled to ensure liveness/readiness aren't too eager to kill the pod when it hasn't had the opportunity to come up
None that I can see, as this is setting the timeout to the default for the `redis-cli` to 220 whilst also …

[bitnami/redis] fix sentinel deployment

---

bitnami/wavefront-prometheus-storage-adapter/Chart.yaml
bitnami/wavefront-prometheus-storage-adapter/templates/_helpers.tpl

The wavefront proxy helper was not taking into account the wavefront string. causing the chart to fail because of incorrect service endpoints.
**Benefits**
- fixes #
**Checklist**

[bitnami/wavefront-prometheus-storage-adapter] fix: :bug: Change wavefront-proxy helper to take into account the "wavefront" string

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/hpa.yaml

To circumvent issues https://github.com/kubernetes/kubernetes/issues/74099 causes with GitOps and using this chart. 
Same issue like [here](https://github.com/bitnami/charts/pull/7849).
Switched resource order in HPA.
**Benefits**
Bypasses issue https://github.com/kubernetes/kubernetes/issues/74099 that can cause problems when using GitOps like ArgoCD. As the impact is minimal I believe this is the optimal solution for this problem.
**Checklist**

[bitnami/nginx] Switch metric list order in nginx

---

bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/templates/health-ingress.yaml

[bitnami/aspnet-core] Fix context for include inside range extraHosts

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/ingress.yaml

[bitnami/elasticsearch] Fix context for include inside range extraHosts

---

bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/server/ingress-grcp.yaml
bitnami/argo-cd/templates/server/ingress.yaml

[bitnami/argo-cd] Fix context for include inside range extraHosts

---

bitnami/harbor/README.md

Escape a pipe that broke the markdown table.
**Benefits**
Markdown renders correctly.
None.
None, I think.
I'd recommend using `markdownlint` to identify issues with your README files. :)
**Checklist**

[bitnami/harbor] Escape a pipe that broke the markdown table

---

bitnami/harbor/Chart.yaml
bitnami/harbor/templates/ingress/core-ingress.yaml
bitnami/harbor/templates/ingress/notary-ingress.yaml

[bitnami/harbor] Fix context for include inside range extraHosts

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/deployment.yaml

When autoscaling is enabled, key `.spec.replicas` in `deployment.yaml` manifest is still generated, which causing problem when using GitOps like ArgoCD.
When `.Values.autoscaling.enabled=true` field `.spec.replicas` in `deployment.yaml` is not generated.
**Benefits**
When autoscaling is disabled (by default), replicas field is generated. When autoscaling is enabled, replicas field is not generated.
**Checklist**

[bitnami/nginx] Disable replicas when autoscaling enabled

---

bitnami/rabbitmq-cluster-operator/Chart.lock
bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/README.md
bitnami/rabbitmq-cluster-operator/values.yaml

**Benefits**
- fixes #
**Checklist**

[bitnami/rabbitmq-cluster-operator] Set readOnlyRootFileSystem by default

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/query/deployment.yaml
bitnami/thanos/values.yaml

Description of the change
To update thanos-query deployment to look for serverName instead of servername in the values.
#9332
Benefits
ServerName can be passed for query in Thanos when using mtls and you want to validate the server name using SNI.
Possible drawbacks
NA
Applicable issues
#9332
Additional information
None
Checklist
[x] Chart version bumped in Chart.yaml according to semver.
[x] Variables are documented in the values.yaml and added to the README.md using readme-generator-for-helm
[x] Title of the PR starts with chart name (e.g. [bitnami/<name_of_the_chart>])
[x] All commits signed off and in agreement of Developer Certificate of Origin (DCO)

[bitnami/thanos] - updated version and fixed typo servername to serverName in deployment.yml

---

bitnami/nats/Chart.yaml
bitnami/nats/templates/ingress.yaml

[bitnami/nats] Fix context for include inside range extraHosts

---

template/CHART_NAME/templates/NOTES.txt
template/CHART_NAME/templates/clusterrolebinding.yaml
template/CHART_NAME/templates/configmap.yaml
template/CHART_NAME/templates/daemonset.yaml
template/CHART_NAME/templates/deployment.yaml
template/CHART_NAME/templates/ingress.yaml
template/CHART_NAME/templates/secret.yaml
template/CHART_NAME/templates/service-account.yaml
template/CHART_NAME/templates/service.yaml
template/CHART_NAME/templates/statefulset.yaml
template/CHART_NAME/templates/tls-secret.yaml
template/CHART_NAME/values.yaml

Implements use of the computed namespace name from `common.names.namespace`
**Benefits**
Future charts will support `namespaceOverride` out of the box 
none
[bitnami/common > README > Names](https://github.com/bitnami/charts/tree/master/bitnami/common#names)

[chart template] Make use of computed namespace name from common library

---

bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/values.yaml

Eliminate Helm warning if user defines topology spread
constraints for master: cannot overwrite table with non
table for redis.master.topologySpreadConstraints (map[])
Same is applicable to redis.replica.topologySpreadConstraints
(map[]) warning
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
**Benefits**
Warning will disappear
N/A
- fixes #9493
N/A
**Checklist**

[bitnami/redis] fix topology spread constraints templating

---

bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/README.md
bitnami/kubeapps/templates/_helpers.tpl

I noticed when testing the latest chart change in my dev environment that it was broken, with pods connecting to postgres erroring with:
```
Warning  Failed     2s (x6 over 53s)  kubelet            Error: secret "kubeapps-postgresql" not found
```
Turns out it there were two renames which we missed:
1. `existingSecret` -> `auth.existingSecret`. This required a change to the `_helpers.tpl` to fix the chart. 
2. `additionalFlags` -> `extraFlags` for the auth proxy. This wasn't a chart change (other than docs), but did break my dev env (and will do so for anyone using OIDC for authentication with Kubeapps), so worth including in the upgrade notes.
I also added a note about the changed `postgres-password` key, since anyone upgrading will need to update the key on …

[bitnami/kubeapps] Fix kubeapps existing secret

---

bitnami/kubewatch/Chart.lock
bitnami/kubewatch/Chart.yaml
bitnami/kubewatch/README.md
bitnami/kubewatch/templates/NOTES.txt
bitnami/kubewatch/values.yaml

Kubewatch Helm chart will be deprecated since the upstream project has been [discontinued](https://github.com/bitnami-labs/kubewatch#warning-kubewatch-is-no-longer-actively-maintained-by-vmware) and no new features. 
**Checklist**

[bitnami/kubewatch] Mark Kubewatch chart as deprecated

---

bitnami/testlink/Chart.lock
bitnami/testlink/Chart.yaml
bitnami/testlink/README.md
bitnami/testlink/templates/NOTES.txt
bitnami/testlink/values.yaml

TestLink helm chart will be deprecated since the upstream project is no longer maintained and has no new features.
**Checklist**

[bitnami/testlink] Deprecate TestLink chart

---

bitnami/testlink/Chart.yaml
bitnami/testlink/README.md
bitnami/testlink/templates/NOTES.txt

TestLink helm chart will be deprecated since the upstream project is no longer maintained and no new features are expected.
Undo some automatic changes from https://github.com/bitnami/charts/pull/9535
**Checklist**

[bitnami/testlink] Add deprecation messages to the TestLink chart

---

bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/README.md
bitnami/kube-prometheus/templates/prometheus/prometheus.yaml
bitnami/kube-prometheus/values.yaml

Signed-off-by: Marian Soltys <41568766+maso7@users.noreply.github.com>
Add startup probe config
**Benefits**
- Option to change default values of the startup probe provided by operator.
- None
**Checklist**

[bitnami/kube-prometheus] Support startup probe in prometheus

---

bitnami/solr/Chart.yaml
bitnami/solr/templates/scripts-configmap.yaml

The `init-certs.sh` script perferes the keystore/truststore provided by the user.
**Benefits**
The [cert-manager](https://cert-manager.io/) can generate `keystore.p12` and `truststore.p12` for the user. These are generated to the same secret (together with `ca.crt`, `tls.crt` and `tls.key`). This helm-chart should prefere these files over generating some files on it's own.
- related to #9506
**Checklist**

[bitnami/solr] init-certs.sh prefers user provided keystore/truststore

---

bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/mongos/mongos-service.yaml

Currently, [bitnami/mongodb-sharded] provide externalIPs field, however this field is not correctly supported. This MR add extenralIPs into service.
#9522 
**Checklist**

[bitnami/mongodb-sharded] Add externalIP in mongos service

---

bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/crds/crd-rabbitmq-cluster.yaml
bitnami/rabbitmq-cluster-operator/crds/crds-messaging-topology-operator.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/validating-webhook-configuration.yaml
bitnami/rabbitmq-cluster-operator/values.yaml

Sync CRDs with https://github.com/rabbitmq/cluster-operator/tree/main/config/crd and https://github.com/rabbitmq/messaging-topology-operator/tree/main/config/crd
- fixes #9513
**Checklist**

[bitnami/rabbitmq-operator] Sync CRDs

---

bitnami/kafka/Chart.lock
bitnami/kafka/Chart.yaml
bitnami/kafka/README.md
bitnami/kafka/values.yaml

Update zookeeper dependency to use version 3.8
**Checklist**

[bitnami/kakfa] Update zookeeper version for kafka

---

bitnami/kubeapps/Chart.lock
bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/README.md
bitnami/kubeapps/templates/frontend/service.yaml
bitnami/kubeapps/values.yaml

Fixes an issue where Helm chart will fail if LoadBalancer service type is used with empty nodePort
**Checklist**

[bitnami/kubeapps] Fix service issue with NodePorts

---

bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/templates/server/configmap.yaml

Added `entryPointStyle` to the server config so tasks will use the configured `entryPointStyle`
**Benefits**
`entryPointStyle` can be changed from the default for tasks if required. 
None
None
This will allow the user to configure a global entry point as documented https://docs.spring.io/spring-cloud-dataflow/docs/current/reference/htmlsingle/#_entry_point_style
**Checklist**

[bitnami/spring-cloud-dataflow] Add missing entryPointStyle so that entrypoint may be configured for tasks

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/_helpers.tpl

The hosts provided through environment variables to the elasticsearch pods do not reflect the real ones. If the data node or the coordinating node is not configured in the chart, the hosts variable is not correctly updated.
**Benefits**
Prevent to expose unknown DNS.
None
Resolve #9527 
None
**Checklist**

[bitnami/elasticsearch] update the hosts depending of the cluster configuration.

---

bitnami/kafka/Chart.yaml
bitnami/kafka/README.md
bitnami/kafka/templates/kafka-provisioning.yaml
bitnami/kafka/values.yaml

Add the possibility to provision the kafka topics in parallel.
**Benefits**
Reduce the provisioning time.
None.
Resolve #9479
**Checklist**

[bitnami/kafka] Add the possibility to provision kafka topics in parallel

---

bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/templates/secret.yaml
bitnami/redis/values.yaml

These changes should allow annotations to be added to the redis secret only.
My use case is that I want to use [kubernetes reflector](https://github.com/emberstack/kubernetes-reflector#:~:text=Reflector%20is%20a%20Kubernetes%20addon,the%20same%20or%20other%20namespaces.) to reflect the `redis` secret on an other kubernetes namespace. 
I tried to use `commonAnnotations` to add the reflector annotations to the secret, it works the secret is well reflected but redis nodes are failing because of `commonAnnotations`. 
It's how I would use it:
```
secretAnnotations:
reflector.v1.k8s.emberstack.com/reflection-auto-enabled: "true"
reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: …
```

[bitnami/redis] Add possibility to set annotations for secret only

---

bitnami/airflow/Chart.yaml
bitnami/airflow/README.md
bitnami/airflow/templates/config/configmap.yaml
bitnami/airflow/templates/scheduler/deployment.yaml
bitnami/airflow/templates/web/deployment.yaml
bitnami/airflow/templates/worker/statefulset.yaml
bitnami/airflow/values.yaml

Add values `extraEnvVars`, `extraEnvVarsCM`, `extraEnvVarsSecret`, `sidecars`, `initContainers`, `extraVolumeMounts` and `extraVolumes`, that applies the same name values but for all airflow pods.
These values, with the exception of `extraVolumes` and `extraVolumeMounts`, were accidentally removed during the standardisation: #8909
- fixes #9579.
**Checklist**

[bitnami/airflow] Add common values for all pods

---

bitnami/nginx-ingress-controller/Chart.yaml
bitnami/nginx-ingress-controller/templates/controller-hpa.yaml

Added kubernetes version to euse the autoscalling v2 instead of v2beta.
**Checklist**

[bitnami/nginx-ingress-controller] Validation for autoscalling

---

bitnami/mysql/Chart.yaml
bitnami/mysql/templates/_helpers.tpl

This enables templating values in `auth.existingSecret`.
**Benefits**
This is useful when using the `mysql` chart as sub-chart.
Similar to https://github.com/bitnami/charts/pull/9594
**Checklist**

[bitnami/mysql] Support templating in auth.existingSecret

---

bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/shard/shard-data-poddisruptionbudget.yaml

Signed-off-by: Vinay Pulim <v@pulim.com>
Fixes a typo in shard-data-poddisruptionbudget.yaml that results in the following helm error after adding `shardsvr.pdb.enabled=true`:
```
Error: template: mongodb-sharded/templates/shard/shard-data-poddisruptionbudget.yaml:5:15: executing "mongodb-sharded/templates/shard/shard-data-poddisruptionbudget.yaml" at <include "common.capabilities.policy.apiVersion" .>: error calling include: template: mongodb-sharded/charts/common/templates/_capabilities.tpl:22:32: executing "common.capabilities.policy.apiVersion" at <include "common.capabilities.kubeVersion" .>: error calling include: template: mongodb-sharded/charts/common/templates/_capabilities.tpl:7:14: executing "common.capabilities.kubeVersion" at <.Values.global>: …
```

[bitnami/mongodb-sharded] Fix typo in shard-data-poddisruptionbudget

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/role.yaml

Added missing single quote in postgresql RBAC Role manifest. Installation of the chart worked, but kubernetes wouldn't recognize the association to the PSP.
**Benefits**
Chart works out of the box for people installing with `rbac.create: true` and `psp.create: true`
none
**Checklist**

[bitnami/postgresql] Add missing quote in postgresql RBAC Role manifest

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/templates/secrets.yaml
bitnami/rabbitmq/templates/statefulset.yaml
bitnami/rabbitmq/values.yaml

Up until now, the load definitions and the RabbitMQ credentials were incompatible. In the latest revision of the container we will allow setting both elements. If the "users" section inside the loadDefinitions file is set, then the credentials will be ignored.
**Benefits**
- fixes https://github.com/bitnami/charts/issues/5976
**Checklist**

[bitnami/rabbitmq] Allow both definitions and setting credentials

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/metrics-deploy.yaml

With the current combination of defaults it will be impossible for the metrics pod to connect unless at least one of these settings has been altered.

[bitnami/elasticsearch] Make metrics work again in non-TLS clusters

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/sentinel/statefulset.yaml

This volume is either an emptyDir if persistence is disabled or an pvc
if persistence is enabled.
Signed-off-by: Anselm Eberhardt <aeberhardt@dg-i.net>
This PR always includes the `sentinel-data` volume if sentinel is deployed.
**Benefits**
Redis with Sentinel enabled can be deployed again without enabling persistence.
None
- fixes #9603
**Checklist**

[bitnami/redis] Always include sentinel-data volume

---

bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/crds/argoproj.io_workflowtaskresults.yaml

Add a missing CRD. [Source](https://github.com/argoproj/argo-workflows/blob/662a7295b2e263f001b94820ebde483fcf7f038d/manifests/base/crds/full/argoproj.io_workflowtaskresults.yaml).
-  #9588 
**Checklist**

[bitnami/argo-workflows] Add missing crd

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/_helpers.tpl

Dear Bitnami-Team,
we are using the Cassandra-Helm chart with autogenerated Certificates.
However, after every update, we encounter the following Error with the `init-certs`-Container
```
unable to load private key
140359890613568:error:0909006C:PEM routines:get_name:no start line:../crypto/pem/pem_lib.c:745:Expecting: ANY PRIVATE KEY
stream closed
```
The reason can be found in the `cassandra-crt`-Secret
The Key-Section is empty.
The Reason is a typo here:
https://github.com/bitnami/charts/blob/master/bitnami/cassandra/templates/_helpers.tpl#L238
please also see
https://github.com/bitnami/charts/issues/9687
* fix the typo in `templates/_helpers.tpl`
Signed-off-by: Espe0n <christoph.andre89@gmx.de>
Fix of a Typo in `templates/_helpers.tpl`
```
{{- $key = (get …
```

[bitnami/cassandra] Fix typo in Certificate Handling

---

bitnami/etcd/Chart.yaml
bitnami/etcd/templates/statefulset.yaml
bitnami/etcd/values.yaml

The current method of calculating peers was incorrect because `getent hosts` could return something different from the headless service, such as the regular service, causing cluster ID mismatches.
This approach relies on the StatefulSet name in order to calculate the etcd peers.
**Benefits**
- fixes https://github.com/bitnami/charts/issues/5771
**Checklist**

[bitnami/etcd]: fix: :bug: Use StatefulSet to calculate peers

---

bitnami/nginx-ingress-controller/Chart.yaml

The used regex by `kubeVersion` in `Chart.yaml` [doesn't work for GKE clusters](https://github.com/helm/helm/issues/3810#issuecomment-379877753), as they use a non-semver versioning:
```
$ helm install nginx-ingress-controller .
Error: chart requires kubeVersion: >= 1.19 which is incompatible with Kubernetes v1.21.6-gke.1503
```
This is solved by modifying the used regex a bit. This change has been tested in GKE and TKG clusters:
```
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16+", GitVersion:"v1.16.13-dispatcher", GitCommit:"fd22db44e150011eccc8729db223945384460143", GitTreeState:"clean", BuildDate:"2020-07-24T07:27:52Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", …
```

[bitnami/nginx-ingress-controller] Update kubeVersion regex to work with GKE

---

bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/templates/kubeappsapis/configmap.yaml

Signed-off-by: Michael Nelson <minelson@vmware.com>
Adds the missing namespace to the kubeapps-apis configmap. This doesn't affect a normal helm install, but if you render the templates first then try to apply the templates, the configmap will end up in the default (or current) namespace. See https://github.com/vmware-tanzu/kubeapps/issues/4571
**Benefits**
People who helm template && apply will succeed :)
- fixes https://github.com/vmware-tanzu/kubeapps/issues/4571
**Checklist**

[bitnami/kubeapps] Add missing namespace to kubeappsapis configmap.

---

bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/templates/rbac.yaml

Add missing RBAC resource for OpenShift routes with custom hostnames (routes/custom-host)
Addresses this issue #9731
In this commit https://github.com/bitnami/charts/commit/d87dec202858e218f08470a8a28d5397426b6a6c?diff=split#r70792073 the resource "routes/custom-host" has been removed from the RBAC configuration.
We assume this is a mistake, the official grafana-operator RBAC configuration contains this resource https://github.com/grafana-operator/grafana-operator/blob/v4.2.0/config/rbac/role.yaml#L154
**Benefits**
Allows the grafana-operator to manage OpenShift routes with custom hostnames again
- fixes  #9731
We were uncertain whether this PR
**Checklist**

[bitnami/grafana-operator] Add missing RBAC resource for OpenShift routes

---

bitnami/grafana-tempo/Chart.yaml
bitnami/grafana-tempo/templates/query-frontend/headless-service.yaml

In `bitnami/grafana-tempo` Helm chart, copy/paste extraPorts customization from query-frontend service manifest to query-frontend headless service manifest.
**Benefits**
This configuration is mandatory in order to fix an error raised by Tempo Querier. This error can be reproduced with chart version 1.0.18, seen in Querier Deployment logs: msg="failed DNS SRV record lookup" err="lookup _grpclb._tcp.tempo-query-frontend-headless on 10.X.0.X:53: no such host".
The fix for this error is to add this lines in the chart values:
```yaml
queryFrontend:
service:
extraPorts:
- name: grpclb
port: 9096
targetPort: grpc
protocol: TCP
```
None.
None reported.
None.
**Checklist**

bitnami/grafana-tempo Add extraPorts value to query-frontend headless service

---

bitnami/spark/Chart.yaml
bitnami/spark/README.md
bitnami/spark/values.yaml

Signed-off-by: Gonzalo Gomez Gracia <gonzalog@vmware.com>
Update the 'submit an application' section by adding the `spark.kubernetes.driverEnv.SPARK_MASTER_URL` config parameter for the new driver pod to properly find the spark master service.
**Benefits**
Example works.
Not expected.
- Related to [bitnami-docker-spark/issues/56](https://github.com/bitnami/bitnami-docker-spark/issues/56)
**Checklist**

[bitnami/spark] Provide environment variables to driver command

---

bitnami/airflow/Chart.yaml
bitnami/airflow/templates/config/configmap.yaml
bitnami/airflow/templates/scheduler/deployment.yaml
bitnami/airflow/templates/web/deployment.yaml
bitnami/airflow/templates/worker/statefulset.yaml

web, scheduler, worker, configmap
Signed-off-by: Addison Jones <addison.jones@gocaribou.com>
Version 12.1.7 of the Airflow chart corrected the .Values.extraEnvVarsCM inclusion on worker, web, scheduler, and configmaps, but the .Values.extraEnvVarsSecret will still not be included even if the value is set. This PR adds the .Values.extraEnvVarsSecret to the conditional sections as intended.
**Benefits**
Creates the intended behavior of adding a secret to all pods within the environment
N/A
- fixes #9716 
**Checklist**

[bitnami/airflow] fix: Add expected .Values.extraEnvVarsSecret behavior

---

bitnami/nginx-intel/README.md
bitnami/nginx/README.md

Update the note for the major version bump adding more info about the deprecation of the container that has coincided in time with a security bug in the same component

[bitnami/nginx bitnami/nginx-intel] Clarify nginx-ldap-auth-daemon deprecation

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/storegateway/statefulset-sharded.yaml

Ever since https://github.com/bitnami/charts/commit/ebc73d5903e68e731ae3a3a651ccd9bc8cec8a1f it is no longer possible to install thanos with a sharded storegateway. The following error is printed:
```
│ Error: template: thanos/templates/storegateway/statefulset-sharded.yaml:62:46: executing "thanos/templates/storegateway/statefulset-sharded.yaml" at <.Values.storegateway.automountServiceAccountToken>: can't evaluate field Values in type int
```
**Benefits**
This PR should make the chart installable again.
N/A
N/A
N/A
**Checklist**

[bitnami/thanos] fix(thanos-storegateway): error in accessed value

---

bitnami/common/Chart.yaml
bitnami/common/README.md

Signed-off-by: Chart Updater <krzysztof.wiatrzyk@comarch.com>
Fix affinities identifier in README.md for common chart
**Benefits**
User will not be misguided by chart's documentation on how to include affinities.
- fixes #9807 
**Checklist**

[bitnami/common] Fix affinities identifier in README.md for common chart

---

bitnami/airflow/Chart.yaml
bitnami/airflow/README.md
bitnami/airflow/templates/config/configmap.yaml
bitnami/airflow/templates/scheduler/deployment.yaml
bitnami/airflow/templates/web/deployment.yaml
bitnami/airflow/templates/worker/statefulset.yaml
bitnami/airflow/values.yaml

Background: The `extraEnvVarsSecret` is a useful feature that allows for a single secret to be loaded into pods as an environment variable using the `envFrom:` capability of the pod spec. 
A use case I encountered was the need to securely add environment variables to our pods using the [External Secrets](https://github.com/external-secrets/kubernetes-external-secrets) custom resource definition, but without loading everything into a single secret. This posed a potential issue with multiple developers modifying the same secret with the chance of overwriting the values. 
The result was the `extraEnvVarsSecrets` list that can be set at the global, scheduler, web, and worker level. Each secret can be loaded by providing the name of the secret just as one would do …

[bitnami/airflow] feat: Airflow extraEnvVarsSecrets list

---

.vib/postgresql-ha/vib-verify.json

Modifies runtime_params used by the `bitnami/postgresql-ha` VIB action after https://github.com/bitnami/charts/pull/9777 changes that weren't updated in https://github.com/bitnami/charts/pull/9780.
**Checklist**

[bitnami/postgresql-ha] Update vib action runtime_params

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/sentinel/statefulset.yaml

I updated the health check command to use the correct variable. I think it was a copy mistake and was left the same from the livenessProbe.
**Benefits**
The readinessProbe timeout will also be used in the script.
I do not see any drawbacks in this code fix.
N/A
**Checklist**

[bitnami/Redis] Fixed invalid variable used for readinessProbe when using sentinels

---

bitnami/rabbitmq-cluster-operator/Chart.lock
bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/README.md
bitnami/rabbitmq-cluster-operator/templates/NOTES.txt
bitnami/rabbitmq-cluster-operator/templates/cluster-operator/clusterrolebinding.yaml
bitnami/rabbitmq-cluster-operator/templates/cluster-operator/deployment.yaml
bitnami/rabbitmq-cluster-operator/templates/cluster-operator/metrics-service.yaml
bitnami/rabbitmq-cluster-operator/templates/cluster-operator/role.yaml
bitnami/rabbitmq-cluster-operator/templates/cluster-operator/rolebinding.yaml
bitnami/rabbitmq-cluster-operator/templates/cluster-operator/service-account.yaml
bitnami/rabbitmq-cluster-operator/templates/cluster-operator/servicemonitor.yaml
bitnami/rabbitmq-cluster-operator/templates/issuer.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/certificate.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/clusterrolebinding.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/deployment.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/metrics-service.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/role.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/rolebinding.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/service-account.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/servicemonitor.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/validating-webhook-configuration.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/webhook-service.yaml
bitnami/rabbitmq-cluster-operator/values.yaml

This PR standardizes the bitnami/rabbitmq-cluster-operator chart to be in line with the rest of the catalog.
**Checklist**

[bitnami/rabbitmq-cluster-operator] Chart standardised

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/ingress.yaml

Signed-off-by: Hans Erik Heggem <hans.erik.heggem@gmail.com>
Fixed ingress bug with the extraHosts option.
Setting extraHosts results in this helm template error:
```bash
Error: template: rabbitmq/templates/ingress.yaml:44:135: executing "rabbitmq/templates/ingress.yaml" at <.Values.service.managerPortName>: nil pointer evaluating interface {}.service
```
The bug was simply caused by not using a '$' sign in a 'range' loop to fetch a value.
**Benefits**
Makes it possible to use the extraHosts option.
Should not cause any drawbacks.
**Checklist**

bitnami/rabbitmq - Fixed ingress bug with extraHosts in RabbitMQ chart.

---

bitnami/elasticsearch/README.md

just a readme doc invalid yaml format fix.
**Checklist**

fix(es): wrong yaml format in README

---

bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/templates/_helpers.tpl

hello i woud like to contribute at fixing a small error, the error happens when existing secret is not provided and plain password are used in the chart the secret named is generated correctly but is being called with wrong name caused by this error , the variable affected is  SONARQUBE_DATABASE_PASSWORD in the deployment.yaml for sonarqube
https://github.com/bitnami/charts/blob/master/bitnami/sonarqube/templates/deployment.yaml
```- name: SONARQUBE_DATABASE_PASSWORD
valueFrom:
secretKeyRef:
name: {{ include "sonarqube.database.secretName" . }}
key: password
```
**Benefits**
Secret  for sonarqube database password will be called correctly when user doesnt set existing secret 
NONE
NONE
it can help deploying the chart …

[bitnami/sonarqube] wrong secret name called in deployment

---

bitnami/kafka/Chart.lock
bitnami/kafka/Chart.yaml
bitnami/kafka/templates/statefulset.yaml

During first start `volume-permissions` container creates directory for data, but not changes owner ot this dir. It only tries to find files in this dir and change owner. It do nothing because no files at first start. So, kafka fails to start because can't create files in data dir (`/bitnami/kafka`).
**Benefits**
Added chmod for data directory next step after creating.
- fixes #9690
**Checklist**

[bitnami/kafka] Add chown for data dir, not only children (#9690)

---

bitnami/mysql/Chart.yaml
bitnami/mysql/templates/NOTES.txt

The pod described in NOTES.txt to be run as a client was missing the import of `MYSQL_ROOT_PASSWORD`, which led to `mysql` asking for credentials when following the installation instructions.
**Benefits**
The `mysql-client` ephemeral pod has now access to the `MYSQL_ROOT_PASSWORD` environment variable and does not ask for the password.
None
- relates to #9746
None
**Checklist**

[bitnami/mysql] Fix missing environment variable in NOTES

---

.github/workflows/vib-verify-extra-redis.yaml
.github/workflows/vib-verify-extra-thanos.yaml
.github/workflows/vib-verify.yaml

This PR introduces minor updates to the existing `vib-verify` GitHub workflow:
- Do not fail by default when a PR is created.
- Rename some jobs/steps so they all use the infinitive form.
- New PR contributors won't misunderstand the lack of the `verify` tag with a failed verification run.
None on the contributor's side, but we should ensure the `verify` tag is added to PRs.
NA
NA

[bitnami/*] Update "vib-verify" workflow

---

.vib/wordpress/vib-publish.json

This PR adds the VIB publish pipeline definition for WordPress. Together with https://github.com/bitnami/charts/pull/9939, it will  enable the verification and publishing of the WordPress chart (first chart) using VIB (VMware Image Builder)
Easy integration with VIB to verify and publish Bitnami WordPress chart.
None
NA
None

[bitnami/wordpress] Add VIB wordpress publish pipeline

---

bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/templates/master/service.yaml
bitnami/redis/templates/replicas/service.yaml
bitnami/redis/values.yaml

Signed-off-by: Eduardo Semprebon <eduardobr@gmail.com>
Add support for Service Internal Traffic Policy to master and replicas:
https://kubernetes.io/docs/concepts/services-networking/service-traffic-policy/
Alpha in K8s v1.21, beta from v1.22 on:
https://kubernetes.io/docs/reference/command-line-tools-reference/feature-gates/
**Benefits**
Allow restricting internal traffic of master and/or replicas pods to node.
None
N/A
**Checklist**

[bitnami/redis] Add internalTrafficPolicy support on master and replicas

---

bitnami/kong/Chart.yaml
bitnami/kong/templates/kong-prometheus-rolebinding.yaml

Adding missing {{ }} 
The current code result in invalid YAML when using serviceMonitor 
None

[bitnami/kong] fix kong missing templating indicator

---

bitnami/nginx/Chart.yaml
bitnami/nginx/README.md
bitnami/nginx/templates/ingress.yaml
bitnami/nginx/values.yaml

This PR adds support of ingressClassName for the nginx chart. This feature is required for k8s 1.18+ using more than one ingress controller.
Supports the newest Kubernetes specification.
None
- fixes partially https://github.com/bitnami/charts/issues/7364
- follows work done on consul chart thanks to work done on PR https://github.com/bitnami/charts/pull/9842

[bitnami/nginx] Add ingressClassName parameter to nginx chart

---

bitnami/argo-cd/Chart.lock
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/application-controller/metrics-svc.yaml
bitnami/argo-cd/templates/application-controller/servicemonitor.yaml
bitnami/argo-cd/templates/repo-server/metrics-svc.yaml
bitnami/argo-cd/templates/repo-server/servicemonitor.yaml
bitnami/argo-cd/templates/server/metrics-svc.yaml
bitnami/argo-cd/templates/server/servicemonitor.yaml
bitnami/argo-cd/values.yaml

Signed-off-by: juan131 <juan.ariza.1311993@gmail.com>
This PR fixes the integration of Argo CD metrics with Prometheus Operator via Servicemonitor.
**Benefits**
Integration with Prometheus Operator works.
None
Currently, both the `argo-cd-XXX` and `argo-cd-XXX-metrics` services (where XXX is one of the ArgoCD components: `app-controller`, `server` or `repo-server`) have the same labels, see:
```console
$ kubectl get svc -n argocd -l app.kubernetes.io/component=controller,app.kubernetes.io/instance=argo-cd,app.kubernetes.io/name=argo-cd
NAME                             TYPE        CLUSTER-IP     EXTERNAL-IP   PORT(S)    AGE
argo-cd-app-controller           ClusterIP   10.3.243.63    <none>        8082/TCP   15h …
```

[bitnami/argo-cd] Fix Prometheus Operator integration

---

bitnami/etcd/Chart.yaml
bitnami/etcd/README.md
bitnami/etcd/values.yaml

Without PDBs, every time a cluster is updated, since Kubernetes is not aware of how to handle the application without PDB, it may cause a majority failure. 
According to [the etcd docs on Majority Failure](https://etcd.io/docs/v3.5/op-guide/failures/#majority-failure):
> When the majority members of the cluster fail, the etcd cluster fails and cannot accept more writes.
>
>The etcd cluster can only recover from a majority failure once the majority of members become available. If a majority of members cannot come back online, then the operator must start disaster recovery to recover the cluster.
This means that manual intervention is needed.
**Benefits**
Enabling this by default instructs the Kubernetes cluster and operators that at least 51% must remain …

[bitnami/etcd] PodDisruptionBudget should be enabled by default

---

bitnami/memcached/Chart.yaml
bitnami/memcached/templates/statefulset.yaml

fix missing volumesPermissions parameters use in memcached statefulset
Signed-off-by: greg-azi <gregoire.pheline@swedbank.se>
In statefulset :
- volume-permissions container will be conditioned by value volumePermissions.enabled
- volume-permissions container securityContext.runAsUser value will be taken from value volumePermissions.containerSecurityContext.runAsUser 
Increase parameterization 
Allow disabling volume-permissions container
Allow customized user from volume-permissions container
No known drawbacks
/
/

[bitnami/memcached] fix missing volumesPermissions parameters use in memcached statefulset

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/svc.yaml

Fixes typo in service template.
- fixes #9979

[bitnami/rabbitmq] Fix metrics service port value

---

bitnami/kafka/Chart.yaml
bitnami/kafka/README.md
bitnami/kafka/templates/statefulset.yaml
bitnami/kafka/values.yaml

Append zookeeperChrootPath when externalZookeeper.servers are used.
When using an external zookeeper, it's typically because we share it with other applications using zookeeper, so it's 
important to use a root path where kafka keeps its data. 
There is a documented zookeeperChrootPath value, but it was ignored when using external zookeepers.
- fixes #9989

[bitnami/kafka] Append zookeeperChrootPath when using external zookeeper.

---

bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/README.md
bitnami/argo-cd/values.yaml

Changes the `runAsUser` parameter to 65534 for the repoServer, fixing a problem with SSH based repos not being able to add applications and throwing a `No user exists for uid 1001` error. This is caused due to user 1001 not existing on the repoServer pod. By changing the userID to a user that does exist on the pod, the issue no longer occurs.
Also updates the containerSecurityContext on the controller, repo, server and dex deploys to be in line with Argo CD's own defaults as can be seen [here](https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml).
Fixes the `No user exists for uid 1001` error when tried to add applications from SSH based private repos
None
- fixes https://github.com/argoproj/argo-cd/issues/2890
None

[bitnami/argo-cd] Fix SSH repo bug: No user exists for uid 1001

---

bitnami/kafka/Chart.yaml
bitnami/kafka/templates/servicemonitor-jmx-metrics.yaml

Change the JMX service monitor selector to target services labeled as `metrics` instead of `kafka`. Makes the JMX service monitor consistent with the [exporter service monitor](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/servicemonitor-metrics.yaml#L31). The label is already correctly set on the [JMX service](https://github.com/bitnami/charts/blob/master/bitnami/kafka/templates/jmx-metrics-svc.yaml#L8).
JMX service monitor points to the correct service. This will allow prometheus to properly retrieve JMX metrics.
- fixes #9936

[bitnami/kafka] Fix label selector in jmx service monitor

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/README.md
bitnami/mongodb/templates/hidden/statefulset.yaml
bitnami/mongodb/templates/replicaset/statefulset.yaml
bitnami/mongodb/templates/standalone/dep-sts.yaml
bitnami/mongodb/values.yaml

Allow using custom command and args to override the default one in the metrics container as we already support it in the regular MongoDB container.
Users can easily customize the command and/or arg used when deploying the metrics container by using the `metrics.command` and `metrics.args` parameters.
- fixes #10026

[bitnami/mongodb] Allow custom command and args in the metrics container

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/sentinel/statefulset.yaml

As described at https://github.com/bitnami/charts/issues/10027, the `lifecycle` is duplicated in the sentinel template. It works fine if the user doesn't provide a custom `lifecycle` since the one set in the file is going to be taken into account; but if the user sets a custom one both are defined at the same time.
With those changes, by default the one defined in the template is going to be used unless the user sets its own `lifecycle`
Users will be able to set a custom `lifecycle` overriding the default one.
- fixes #10027

[bitnami/redis] Fix issue with duplicated lifecycles

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/values.yaml

Use `kubernetes.default` instead of `kubernetes.default.svc.{{ clusterDomain }}`
for peer discovery configuration in rabbitmq
- Simpler chart
- More robust if there is some quirks in the DNS configuration (we recently
encounted a problem with a custom clusterDomain where the DNS response for
`kubernetes.default.svc.{{ clusterDomain }}` was not the same as
`kubernetes.default` )
If `kubernetes.default` does not work but `kubernetes.default.svc.{{
clusterDomain }}` does, rabbitmq will be broken. It's pretty unlikely since the
latter rely on the former.
```
bitnami/wavefront/templates/collector-config.yaml:49:        url: https://kubernetes.default.svc
bitnami/wavefront/templates/collector-config.yaml:93:        - url: https://kubernetes.default.svc.cluster.local:443/metrics …
```

[bitnami/rabbitmq] Use short dns name for the Kubernetes api

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/statefulset.yaml

Adds the flag '-r' to `xargs` to not fail on empty args.
- fixes #10045

[bitnami/rabbitmq] Add '-r' to volumePermissions to not fail on empty xargs

---

bitnami/nginx-ingress-controller/Chart.yaml
bitnami/nginx-ingress-controller/templates/controller-hpa.yaml
bitnami/nginx-ingress-controller/templates/default-backend-poddisruptionbudget.yaml

* Solve the issue 10059: Unable to deploy HorizontalPodAutoscaler on cluster >= 1.23.0.. The format of the HPA resource v2 was not correct.
* Solve the issue 10060: Error in PodDisruptionBudget. Missing tabulation for included match labels.
- fixes #10059
- fixes #10060
Signed-off-by: Renaud Demarneffe <renaud.demarneffe@gmail.com>

[bitnami/nginx-ingress-controller] Solve issues 10059 (HPA/v2) and 10060 (PDB)

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/hidden/external-access-svc.yaml
bitnami/mongodb/templates/replicaset/external-access-svc.yaml

Remove unnecessary logic around `externalAccess.service.nodePorts`and `externalAccess.hidden.service.nodePorts`. We will use a simple list as mentioned in the original readme file.
- fixes #10000

[bitnami/mongodb] Remove unnecessary logic around externalAccess.service.nodePorts

---

.github/workflows/generate-chart-readme.yml

Signed-off-by: Alejandro Ruiz <alejandroruiz@vmware.com>
The automation for automatically updating the README files is producing a new commit, which retriggers again the complete CI. This PR uses [this functionality](https://github.blog/changelog/2021-02-08-github-actions-skip-pull-request-and-push-workflows-with-skip-ci/) to prevent that.
Expensive verify actions are only executed once.
A wrong README generation wouldn't be caught by the verify actions, but this is not being checked AFAIK.

[bitnami/*] chore 🔨: Prevent automated README updates from triggering the CI

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/standalone/dep-sts.yaml

Fixes issue with MongoDB metrics exporter when using standalone deployment
- fixes #10072

[bitnami/mongodb] Fix metrics containerPort when using standalone

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/sentinel/statefulset.yaml

Add metrics.extraEnvVars, metrics.extraVolumes and metrics.extraVolumeMounts
to Sentinel StatefulSet
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
Users can customize metrics side car in case of Sentinel
N/A
- fixes #10082

[bitnami/redis] fix missing metrics customization to Sentinel

---

bitnami/airflow/Chart.yaml
bitnami/airflow/templates/scheduler/deployment.yaml
bitnami/airflow/templates/web/deployment.yaml
bitnami/airflow/templates/worker/statefulset.yaml

The `terminationGracePeriodSeconds` Pod configuration from the values.yaml file 
is not making its way into the Deployment and StatefulSet templates for the web,
scheduler, and worker pods.
This change implements this expected feature.
This PR adds the behavior expected from the current configuration items in the chart.
N/A
N/A
N/A

[bitnami/airflow] fix: Implement intended behavior for terminationGracePeriodSeconds

---

bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/cluster-configs.yaml

[bitnami/argo-cd] Add missing namespace metadata

---

bitnami/apache/Chart.yaml
bitnami/apache/templates/configmap-vhosts.yaml
bitnami/apache/templates/configmap.yaml
bitnami/apache/templates/deployment.yaml
bitnami/apache/templates/ingress.yaml

**Checklist**
gh pr create --title "[bitnami/airflow] Add missing namespace metadata" --body-file ./pr-body.md

[bitnami/apache] Add missing namespace metadata

---

bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/README.md
bitnami/mediawiki/templates/NOTES.txt
bitnami/mediawiki/templates/_helpers.tpl
bitnami/mediawiki/templates/deployment.yaml
bitnami/mediawiki/templates/secrets.yaml
bitnami/mediawiki/values.yaml

Support existing Secret parameter for mediawiki password.
- Add parameter: mediawikiSecret to point to existing admin Secret
- Add some validation of mutual exclusivity
- Add helper functions
- Bump chart version
Allow passing an existing `Secret` rather than hardcoding and passing the password directly.

[bitnami/mediawiki] support existing Secret parameter for mediawiki admin

---

bitnami/concourse/Chart.yaml
bitnami/concourse/templates/config/secret-external-db.yaml
bitnami/concourse/templates/web/gateway-service.yaml
bitnami/concourse/templates/web/podsecuritypolicy.yaml
bitnami/concourse/templates/web/role.yaml
bitnami/concourse/templates/web/service.yaml
bitnami/concourse/templates/worker/horizontalpodautoscaler.yaml
bitnami/concourse/templates/worker/poddisruptionbudget.yaml
bitnami/concourse/templates/worker/podsecuritypolicy.yaml
bitnami/concourse/templates/worker/role.yaml

[bitnami/concourse] Add missing namespace metadata

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/server-block-configmap.yaml

Fixes `Error: YAML parse error on nginx/templates/server-block-configmap.yaml: error converting YAML to JSON: yaml: line 12: mapping values are not allowed in this context`when deploying nginx helm chart with server block enabled

[bitnami/nginx] fixed tpl error in server-block configmap

---

bitnami/owncloud/Chart.yaml
bitnami/owncloud/templates/deployment.yaml
bitnami/owncloud/templates/externaldb-secrets.yaml
bitnami/owncloud/templates/ingress.yaml
bitnami/owncloud/templates/metrics-svc.yaml
bitnami/owncloud/templates/networkpolicy-backend-ingress.yaml
bitnami/owncloud/templates/networkpolicy-egress.yaml
bitnami/owncloud/templates/networkpolicy-ingress.yaml
bitnami/owncloud/templates/pv.yaml
bitnami/owncloud/templates/pvc.yaml
bitnami/owncloud/templates/secrets.yaml
bitnami/owncloud/templates/svc.yaml
bitnami/owncloud/templates/tls-secrets.yaml

[bitnami/owncloud] Add missing namespace metadata

---

bitnami/node-exporter/Chart.yaml
bitnami/node-exporter/templates/psp-clusterrole.yaml
bitnami/node-exporter/templates/psp-clusterrolebinding.yaml
bitnami/node-exporter/templates/psp.yaml

[bitnami/node-exporter] Add missing namespace metadata

---

bitnami/nginx-intel/Chart.yaml
bitnami/nginx-intel/README.md
bitnami/nginx-intel/templates/deployment.yaml
bitnami/nginx-intel/templates/health-ingress.yaml
bitnami/nginx-intel/templates/hpa.yaml
bitnami/nginx-intel/templates/ingress.yaml
bitnami/nginx-intel/templates/pdb.yaml
bitnami/nginx-intel/templates/server-block-configmap.yaml
bitnami/nginx-intel/templates/serviceaccount.yaml
bitnami/nginx-intel/templates/servicemonitor.yaml
bitnami/nginx-intel/templates/svc.yaml
bitnami/nginx-intel/templates/tls-secrets.yaml
bitnami/nginx-intel/values.yaml

[bitnami/nginx-intel] Add missing namespace metadata

---

bitnami/mxnet/Chart.yaml
bitnami/mxnet/templates/pvc.yaml

[bitnami/mxnet] Add missing namespace metadata

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/configmap.yaml
bitnami/mongodb/templates/arbiter/headless-svc.yaml
bitnami/mongodb/templates/arbiter/pdb.yaml
bitnami/mongodb/templates/arbiter/statefulset.yaml
bitnami/mongodb/templates/common-scripts-cm.yaml
bitnami/mongodb/templates/configmap.yaml
bitnami/mongodb/templates/hidden/configmap.yaml
bitnami/mongodb/templates/hidden/headless-svc.yaml
bitnami/mongodb/templates/hidden/pdb.yaml
bitnami/mongodb/templates/hidden/statefulset.yaml
bitnami/mongodb/templates/initialization-configmap.yaml
bitnami/mongodb/templates/metrics-svc.yaml
bitnami/mongodb/templates/psp.yaml
bitnami/mongodb/templates/replicaset/headless-svc.yaml
bitnami/mongodb/templates/replicaset/pdb.yaml
bitnami/mongodb/templates/replicaset/scripts-configmap.yaml
bitnami/mongodb/templates/replicaset/statefulset.yaml
bitnami/mongodb/templates/role.yaml
bitnami/mongodb/templates/rolebinding.yaml
bitnami/mongodb/templates/serviceaccount.yaml
bitnami/mongodb/templates/standalone/dep-sts.yaml
bitnami/mongodb/templates/standalone/pvc.yaml
bitnami/mongodb/templates/standalone/svc.yaml

[bitnami/mongodb] Add missing namespace metadata

---

bitnami/drupal/Chart.yaml
bitnami/drupal/README.md
bitnami/drupal/templates/NOTES.txt
bitnami/drupal/templates/deployment.yaml
bitnami/drupal/templates/externaldb-secrets.yaml
bitnami/drupal/templates/ingress.yaml
bitnami/drupal/templates/networkpolicy-backend-ingress.yaml
bitnami/drupal/templates/networkpolicy-egress.yaml
bitnami/drupal/templates/networkpolicy-ingress.yaml
bitnami/drupal/templates/pv.yaml
bitnami/drupal/templates/pvc.yaml
bitnami/drupal/templates/secrets.yaml
bitnami/drupal/templates/svc.yaml
bitnami/drupal/templates/tls-secrets.yaml
bitnami/drupal/values.yaml

[bitnami/drupal] Add missing namespace metadata

---

bitnami/mariadb/Chart.yaml
bitnami/mariadb/templates/networkpolicy-egress.yaml
bitnami/mariadb/templates/primary/networkpolicy-ingress.yaml
bitnami/mariadb/templates/primary/statefulset.yaml
bitnami/mariadb/templates/prometheusrules.yaml
bitnami/mariadb/templates/secondary/networkpolicy-ingress.yaml

[bitnami/mariadb] Add missing namespace metadata

---

bitnami/kubernetes-event-exporter/Chart.yaml
bitnami/kubernetes-event-exporter/templates/configmap.yaml
bitnami/kubernetes-event-exporter/templates/deployment.yaml
bitnami/kubernetes-event-exporter/templates/rbac-leader-election.yaml
bitnami/kubernetes-event-exporter/templates/rbac.yaml
bitnami/kubernetes-event-exporter/templates/serviceaccount.yaml

[bitnami/kubernetes-event-exporter] Add missing namespace metadata

---

bitnami/jasperreports/Chart.yaml
bitnami/jasperreports/templates/deployment.yaml
bitnami/jasperreports/templates/externaldb-secrets.yaml
bitnami/jasperreports/templates/ingress.yaml
bitnami/jasperreports/templates/networkpolicy-backend-ingress.yaml
bitnami/jasperreports/templates/networkpolicy-egress.yaml
bitnami/jasperreports/templates/networkpolicy-ingress.yaml
bitnami/jasperreports/templates/pvc.yaml
bitnami/jasperreports/templates/secrets.yaml
bitnami/jasperreports/templates/tls-secrets.yaml

[bitnami/jasperreports] Add missing namespace metadata

---

bitnami/kiam/Chart.yaml
bitnami/kiam/templates/agent/agent-daemonset.yaml
bitnami/kiam/templates/agent/agent-psp-clusterrole.yaml
bitnami/kiam/templates/agent/agent-psp-clusterrolebinding.yaml
bitnami/kiam/templates/agent/agent-psp.yaml
bitnami/kiam/templates/agent/agent-secret.yaml
bitnami/kiam/templates/agent/agent-service-account.yaml
bitnami/kiam/templates/agent/agent-service.yaml
bitnami/kiam/templates/server/server-daemonset.yaml
bitnami/kiam/templates/server/server-deployment.yaml
bitnami/kiam/templates/server/server-psp-clusterrole.yaml
bitnami/kiam/templates/server/server-psp-clusterrolebinding.yaml
bitnami/kiam/templates/server/server-psp.yaml
bitnami/kiam/templates/server/server-read-clusterrole.yaml
bitnami/kiam/templates/server/server-read-clusterrolebinding.yaml
bitnami/kiam/templates/server/server-secret.yaml
bitnami/kiam/templates/server/server-service-account.yaml
bitnami/kiam/templates/server/server-service.yaml
bitnami/kiam/templates/server/server-write-clusterrole.yaml
bitnami/kiam/templates/server/server-write-clusterrolebinding.yaml

[bitnami/kiam] Add missing namespace metadata

---

bitnami/kube-state-metrics/Chart.yaml
bitnami/kube-state-metrics/templates/clusterrole.yaml
bitnami/kube-state-metrics/templates/clusterrolebinding.yaml
bitnami/kube-state-metrics/templates/deployment.yaml
bitnami/kube-state-metrics/templates/psp-clusterrole.yaml
bitnami/kube-state-metrics/templates/psp-clusterrolebinding.yaml
bitnami/kube-state-metrics/templates/psp.yaml
bitnami/kube-state-metrics/templates/service.yaml
bitnami/kube-state-metrics/templates/serviceaccount.yaml
bitnami/kube-state-metrics/templates/servicemonitor.yaml

[bitnami/kube-state-metrics] Add missing namespace metadata

---

bitnami/contour-operator/Chart.yaml
bitnami/contour-operator/templates/service-account.yaml
bitnami/contour-operator/templates/servicemonitor.yaml

[bitnami/contour-operator] Add missing namespace metadata

---

bitnami/redmine/Chart.yaml
bitnami/redmine/templates/externaldb-secret.yaml
bitnami/redmine/templates/networkpolicy-backend-ingress.yaml
bitnami/redmine/templates/networkpolicy-egress.yaml
bitnami/redmine/templates/networkpolicy-ingress.yaml

[bitnami/redmine] Add missing namespace metadata

---

bitnami/moodle/Chart.yaml
bitnami/moodle/templates/deployment.yaml
bitnami/moodle/templates/externaldb-secrets.yaml
bitnami/moodle/templates/ingress.yaml
bitnami/moodle/templates/networkpolicy-backend-ingress.yaml
bitnami/moodle/templates/networkpolicy-egress.yaml
bitnami/moodle/templates/networkpolicy-ingress.yaml
bitnami/moodle/templates/pv.yaml
bitnami/moodle/templates/pvc.yaml
bitnami/moodle/templates/secrets.yaml
bitnami/moodle/templates/tls-secrets.yaml

[bitnami/moodle] Add missing namespace metadata

---

bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/README.md
bitnami/argo-cd/templates/application-controller/deployment.yaml
bitnami/argo-cd/templates/repo-server/deployment.yaml
bitnami/argo-cd/templates/server/deployment.yaml
bitnami/argo-cd/values.yaml

Signed-off-by: juan131 <juan.ariza.1311993@gmail.com>
This PR modifies the Argo CD - related components' deployments to ensure the default's container entrypoint is executed. This entrypoint is essential to setup the _nss_wrapper_ configuration.
**Benefits**
User/group is properly configured in the container so the Repository Server can clone repositories without facing permissions issues.
None
Check problem described at https://github.com/bitnami/bitnami-docker-argo-cd/pull/2
NA
**Checklist**

[bitnami/argo-cd] Ensure default's container entrypoint is executed

---

bitnami/phpmyadmin/Chart.yaml
bitnami/phpmyadmin/templates/certs.yaml
bitnami/phpmyadmin/templates/deployment.yaml
bitnami/phpmyadmin/templates/ingress.yaml
bitnami/phpmyadmin/templates/metrics-svc.yaml
bitnami/phpmyadmin/templates/networkpolicy-backend-ingress.yaml
bitnami/phpmyadmin/templates/networkpolicy-egress.yaml
bitnami/phpmyadmin/templates/networkpolicy-ingress.yaml
bitnami/phpmyadmin/templates/servicemonitor.yaml
bitnami/phpmyadmin/templates/tls-secrets.yaml

[bitnami/phpmyadmin] Add missing namespace metadata

---

bitnami/dataplatform-bp1/Chart.yaml
bitnami/dataplatform-bp1/templates/configmap.yaml
bitnami/dataplatform-bp1/templates/role.yaml
bitnami/dataplatform-bp1/templates/rolebinding.yaml
bitnami/dataplatform-bp1/templates/serviceaccount.yaml

[bitnami/dataplatform-bp1] Add missing namespace metadata

---

bitnami/dataplatform-bp2/Chart.yaml
bitnami/dataplatform-bp2/templates/configmap.yaml
bitnami/dataplatform-bp2/templates/role.yaml
bitnami/dataplatform-bp2/templates/rolebinding.yaml
bitnami/dataplatform-bp2/templates/serviceaccount.yaml

[bitnami/dataplatform-bp2] Add missing namespace metadata

---

bitnami/ghost/Chart.yaml
bitnami/ghost/templates/networkpolicy-backend-ingress.yaml
bitnami/ghost/templates/networkpolicy-egress.yaml
bitnami/ghost/templates/networkpolicy-ingress.yaml

[bitnami/ghost] Add missing namespace metadata

---

bitnami/prestashop/Chart.yaml
bitnami/prestashop/README.md
bitnami/prestashop/templates/deployment.yaml
bitnami/prestashop/templates/externaldb-secrets.yaml
bitnami/prestashop/templates/ingress.yaml
bitnami/prestashop/templates/networkpolicy-backend-ingress.yaml
bitnami/prestashop/templates/networkpolicy-egress.yaml
bitnami/prestashop/templates/networkpolicy-ingress.yaml
bitnami/prestashop/templates/pv.yaml
bitnami/prestashop/templates/pvc.yaml
bitnami/prestashop/templates/secrets.yaml
bitnami/prestashop/templates/svc.yaml
bitnami/prestashop/templates/tls-secrets.yaml
bitnami/prestashop/values.yaml

[bitnami/prestashop] Add missing namespace metadata

---

bitnami/osclass/Chart.yaml
bitnami/osclass/templates/deployment.yaml
bitnami/osclass/templates/externaldb-secrets.yaml
bitnami/osclass/templates/ingress.yaml
bitnami/osclass/templates/metrics-svc.yaml
bitnami/osclass/templates/networkpolicy-backend-ingress.yaml
bitnami/osclass/templates/networkpolicy-egress.yaml
bitnami/osclass/templates/networkpolicy-ingress.yaml
bitnami/osclass/templates/osclass-pvc.yaml
bitnami/osclass/templates/secrets.yaml
bitnami/osclass/templates/servicemonitor.yaml
bitnami/osclass/templates/svc.yaml
bitnami/osclass/templates/tls-secrets.yaml

[bitnami/osclass] Add missing namespace metadata

---

bitnami/wordpress-intel/Chart.yaml
bitnami/wordpress-intel/templates/networkpolicy-backend-ingress.yaml
bitnami/wordpress-intel/templates/networkpolicy-egress.yaml
bitnami/wordpress-intel/templates/networkpolicy-ingress.yaml
bitnami/wordpress-intel/templates/servicemonitor.yaml

[bitnami/wordpress-intel] Add missing namespace metadata

---

bitnami/spark/Chart.yaml
bitnami/spark/templates/NOTES.txt
bitnami/spark/templates/hpa-worker.yaml
bitnami/spark/templates/podmonitor.yaml
bitnami/spark/templates/tls-secrets.yaml

[bitnami/spark] Add missing namespace metadata

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/master/pvc.yaml
bitnami/redis/templates/prometheusrule.yaml
bitnami/redis/templates/servicemonitor.yaml
bitnami/redis/templates/tls-secret.yaml

[bitnami/redis] Add missing namespace metadata

---

bitnami/phpbb/Chart.yaml
bitnami/phpbb/README.md
bitnami/phpbb/templates/NOTES.txt
bitnami/phpbb/templates/deployment.yaml
bitnami/phpbb/templates/externaldb-secrets.yaml
bitnami/phpbb/templates/ingress.yaml
bitnami/phpbb/templates/networkpolicy-backend-ingress.yaml
bitnami/phpbb/templates/networkpolicy-egress.yaml
bitnami/phpbb/templates/networkpolicy-ingress.yaml
bitnami/phpbb/templates/phpbb-pvc.yaml
bitnami/phpbb/templates/secrets.yaml
bitnami/phpbb/templates/svc.yaml
bitnami/phpbb/templates/tls-secrets.yaml
bitnami/phpbb/values.yaml

[bitnami/phpbb] Add missing namespace metadata

---

bitnami/fluentd/Chart.yaml
bitnami/fluentd/templates/aggregator-configmap.yaml
bitnami/fluentd/templates/aggregator-hpa.yaml
bitnami/fluentd/templates/aggregator-statefulset.yaml
bitnami/fluentd/templates/aggregator-svc-headless.yaml
bitnami/fluentd/templates/aggregator-svc.yaml
bitnami/fluentd/templates/forwarder-clusterrole.yaml
bitnami/fluentd/templates/forwarder-clusterrolebinding.yaml
bitnami/fluentd/templates/forwarder-configmap.yaml
bitnami/fluentd/templates/forwarder-daemonset.yaml
bitnami/fluentd/templates/forwarder-psp.yaml
bitnami/fluentd/templates/forwarder-svc.yaml
bitnami/fluentd/templates/ingress.yaml
bitnami/fluentd/templates/metrics-svc.yaml
bitnami/fluentd/templates/serviceaccount.yaml
bitnami/fluentd/templates/servicemonitor.yaml
bitnami/fluentd/templates/tls-certs.yaml

[bitnami/fluentd] Add missing namespace metadata

---

bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/clusterrole.yaml
bitnami/external-dns/templates/clusterrolebinding.yaml
bitnami/external-dns/templates/configmap.yaml
bitnami/external-dns/templates/deployment.yaml
bitnami/external-dns/templates/pdb.yaml
bitnami/external-dns/templates/psp-clusterrole.yaml
bitnami/external-dns/templates/psp-clusterrolebinding.yaml
bitnami/external-dns/templates/psp.yaml
bitnami/external-dns/templates/rolebindings.yaml
bitnami/external-dns/templates/secret.yaml
bitnami/external-dns/templates/service.yaml
bitnami/external-dns/templates/serviceaccount.yaml
bitnami/external-dns/templates/servicemonitor.yaml
bitnami/external-dns/templates/tls-secret.yaml

[bitnami/external-dns] Add missing namespace metadata

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/curator/rolebinding.yaml
bitnami/elasticsearch/templates/metrics/servicemonitor.yaml

[bitnami/elasticsearch] Add missing namespace metadata

---

bitnami/ejbca/Chart.yaml
bitnami/ejbca/README.md
bitnami/ejbca/templates/NOTES.txt
bitnami/ejbca/templates/deployment.yaml
bitnami/ejbca/templates/externaldb-secrets.yaml
bitnami/ejbca/templates/ingress.yaml
bitnami/ejbca/templates/networkpolicy-backend-ingress.yaml
bitnami/ejbca/templates/networkpolicy-egress.yaml
bitnami/ejbca/templates/networkpolicy-ingress.yaml
bitnami/ejbca/templates/pvc.yaml
bitnami/ejbca/templates/secrets.yaml
bitnami/ejbca/templates/svc.yaml
bitnami/ejbca/values.yaml

[bitnami/ejbca] Add missing namespace metadata

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/cassandra-secret.yaml
bitnami/cassandra/templates/headless-svc.yaml
bitnami/cassandra/templates/networkpolicy.yaml
bitnami/cassandra/templates/pdb.yaml
bitnami/cassandra/templates/service.yaml
bitnami/cassandra/templates/serviceaccount.yaml
bitnami/cassandra/templates/servicemonitor.yaml
bitnami/cassandra/templates/statefulset.yaml
bitnami/cassandra/templates/tls-secret.yaml

[bitnami/cassandra] Add missing namespace metadata

---

bitnami/airflow/Chart.yaml
bitnami/airflow/templates/config/configmap.yaml
bitnami/airflow/templates/config/secret-external-db.yaml
bitnami/airflow/templates/config/secret-external-redis.yaml
bitnami/airflow/templates/config/secret-ldap.yaml
bitnami/airflow/templates/config/secret.yaml
bitnami/airflow/templates/metrics/deployment.yaml
bitnami/airflow/templates/metrics/service.yaml
bitnami/airflow/templates/metrics/servicemonitor.yaml
bitnami/airflow/templates/rbac/role.yaml
bitnami/airflow/templates/rbac/rolebinding.yaml
bitnami/airflow/templates/rbac/serviceaccount.yaml
bitnami/airflow/templates/scheduler/deployment.yaml
bitnami/airflow/templates/scheduler/poddisruptionbudget.yaml
bitnami/airflow/templates/scheduler/service-headless.yaml
bitnami/airflow/templates/web/deployment.yaml
bitnami/airflow/templates/web/poddisruptionbudget.yaml
bitnami/airflow/templates/web/service.yaml
bitnami/airflow/templates/worker/horizontalpodautoscaler.yaml
bitnami/airflow/templates/worker/poddisruptionbudget.yaml
bitnami/airflow/templates/worker/service-headless.yaml
bitnami/airflow/templates/worker/statefulset.yaml

[bitnami/airflow] Add missing namespace metadata

---

bitnami/consul/Chart.yaml
bitnami/consul/templates/configmap.yaml
bitnami/consul/templates/consul-headless-service.yaml
bitnami/consul/templates/gossip-secret.yaml
bitnami/consul/templates/ingress.yaml
bitnami/consul/templates/metrics-svc.yaml
bitnami/consul/templates/pdb.yaml
bitnami/consul/templates/service.yaml
bitnami/consul/templates/servicemonitor.yaml
bitnami/consul/templates/statefulset.yaml
bitnami/consul/templates/tls-secrets.yaml

[bitnami/consul] Add missing namespace metadata

---

bitnami/magento/Chart.yaml
bitnami/magento/templates/NOTES.txt
bitnami/magento/templates/deployment.yaml
bitnami/magento/templates/externaldb-secrets.yaml
bitnami/magento/templates/hpa.yaml
bitnami/magento/templates/ingress.yaml
bitnami/magento/templates/metrics-svc.yaml
bitnami/magento/templates/networkpolicy-backend-ingress.yaml
bitnami/magento/templates/networkpolicy-egress.yaml
bitnami/magento/templates/networkpolicy-ingress.yaml
bitnami/magento/templates/pv.yaml
bitnami/magento/templates/pvc.yaml
bitnami/magento/templates/secrets.yaml
bitnami/magento/templates/svc.yaml
bitnami/magento/templates/tls-secrets.yaml

[bitnami/magento] Add missing namespace metadata

---

.vib/logstash/vib-verify.json
bitnami/logstash/Chart.yaml
bitnami/logstash/templates/configuration-cm.yaml
bitnami/logstash/templates/headless-svc.yaml
bitnami/logstash/templates/ingress.yaml
bitnami/logstash/templates/metrics-svc.yaml
bitnami/logstash/templates/pdb.yaml
bitnami/logstash/templates/serviceaccount.yaml
bitnami/logstash/templates/servicemonitor.yaml
bitnami/logstash/templates/sts.yaml
bitnami/logstash/templates/svc.yaml
bitnami/logstash/templates/tls-secret.yaml

[bitnami/logstash] Add missing namespace metadata

---

bitnami/kubeapps/Chart.yaml
bitnami/solr/Chart.yaml

Use the same icon used in the rest of the Helm charts, following the unified format:
```
https://bitnami.com/assets/stacks/ASSET/img/ASSET-stack-220x234.png
```

[bitnami/kubeapps & solr] Unify icon in Chart.yaml

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/httpd-configmap.yaml
bitnami/wordpress/templates/networkpolicy-backend-ingress.yaml
bitnami/wordpress/templates/networkpolicy-egress.yaml
bitnami/wordpress/templates/networkpolicy-ingress.yaml
bitnami/wordpress/templates/serviceaccount.yaml
bitnami/wordpress/templates/servicemonitor.yaml

[bitnami/wordpress] Add missing namespace metadata

---

.vib/mediawiki/cypress/cypress/integration/mediawiki_spec.js
bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/templates/deployment.yaml
bitnami/mediawiki/templates/externaldb-secrets.yaml
bitnami/mediawiki/templates/ingress.yaml
bitnami/mediawiki/templates/mediawiki-pvc.yaml
bitnami/mediawiki/templates/networkpolicy-backend-ingress.yaml
bitnami/mediawiki/templates/networkpolicy-egress.yaml
bitnami/mediawiki/templates/networkpolicy-ingress.yaml
bitnami/mediawiki/templates/secrets.yaml
bitnami/mediawiki/templates/servicemonitor.yaml
bitnami/mediawiki/templates/tls-secrets.yaml

[bitnami/mediawiki] Add missing namespace metadata

---

bitnami/dokuwiki/Chart.yaml
bitnami/dokuwiki/README.md
bitnami/dokuwiki/templates/NOTES.txt
bitnami/dokuwiki/templates/deployment.yaml
bitnami/dokuwiki/templates/dokuwiki-pvc.yaml
bitnami/dokuwiki/templates/ingress.yaml
bitnami/dokuwiki/templates/postinit-configmap.yaml
bitnami/dokuwiki/templates/secrets.yaml
bitnami/dokuwiki/templates/svc.yaml
bitnami/dokuwiki/templates/tls-secrets.yaml
bitnami/dokuwiki/values.yaml

[bitnami/dokuwiki] Add missing namespace metadata

---

bitnami/kibana/Chart.yaml
bitnami/kibana/templates/NOTES.txt
bitnami/kibana/templates/configmap.yaml
bitnami/kibana/templates/servicemonitor.yaml
bitnami/kibana/templates/tls-secret.yaml

[bitnami/kibana] Add missing namespace metadata

---

bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/crds/grafanadashboards.integreatly.org.yaml
bitnami/grafana-operator/crds/grafanadatasources.integreatly.org.yaml
bitnami/grafana-operator/crds/grafananotificationchannels.integreatly.org.yaml
bitnami/grafana-operator/crds/grafanas.integreatly.org.yaml
bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/crds/crd-alertmanager-config.yaml
bitnami/kube-prometheus/crds/crd-alertmanager.yaml
bitnami/kube-prometheus/crds/crd-podmonitor.yaml
bitnami/kube-prometheus/crds/crd-probes.yaml
bitnami/kube-prometheus/crds/crd-prometheus.yaml
bitnami/kube-prometheus/crds/crd-prometheusrules.yaml
bitnami/kube-prometheus/crds/crd-servicemonitor.yaml
bitnami/kube-prometheus/crds/crd-thanosrulers.yaml

Signed-off-by: juan131 <juan.ariza.1311993@gmail.com>
The Grafana Operator and kube-prometheus charts' CRDs start with 3 dashes that are not necessary since these are only required as a separator when N directives are included in a single YAML file (which is not the case). Indeed, if you render the templates including the CRDs (e.g. running  `helm template kube-prometheus bitnami/kube-prometheus --include-crds > foo.yaml` and inspect the output, you'll find blocks such as the one below:
```
---
---
```
This is interpreted as an empty directive which doesn't make sense.
Charts compatible with `helm template --include-crds ...`.
None
N/A
N/A

[bitnami/{grafana-operator|kube-prometheus}] CRDs should not include unnecessary dashes

---

bitnami/argo-workflows/Chart.lock
bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/README.md
bitnami/argo-workflows/values.yaml

Bumps the MySQL subchart to its latest major 9.0.0.
Documentation PR:  https://github.com/bitnami/charts-docs/pull/108

[bitnami/argo-workflows] Bump mysql subchart version

---

bitnami/contour/Chart.lock
bitnami/contour/Chart.yaml
bitnami/contour/templates/envoy/hpa.yaml

Use the new helper in `common` and adapt HPA to be compatible with `autoscaling/v2`
Up-to-date components.
None, it is backwards compatible.
NA
NA

[bitnami/contour] Use the new helper for HPA API version

---

bitnami/thanos/Chart.lock
bitnami/thanos/Chart.yaml
bitnami/thanos/templates/bucketweb/hpa.yaml
bitnami/thanos/templates/query-frontend/hpa.yaml
bitnami/thanos/templates/query/hpa.yaml
bitnami/thanos/templates/receive-distributor/hpa.yaml
bitnami/thanos/templates/receive/hpa.yaml
bitnami/thanos/templates/ruler/hpa.yaml
bitnami/thanos/templates/storegateway/hpa.yaml

Use the new helper in `common` and adapt HPA to be compatible with `autoscaling/v2`
Up-to-date components.
None, it is backwards compatible.
NA
NA

[bitnami/thanos] Use the new helper for HPA API version

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/sentinel/statefulset.yaml

Metrics related extra volume mounts are placed under redis
container instead of metrics container
Metrics related extra volume mounts shall go under metrics
container
Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>
Users can define extra volume mounts for metrics container
N/A
- fixes #10188
It is fix for the regression introduced in https://github.com/bitnami/charts/pull/10085

[bitnami/redis] fix wrongly placed metrics extra volume mounts

---

bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/README.md
bitnami/kubeapps/values.yaml

Signed-off-by: Michael Nelson <minelson@vmware.com>
This change restores the Kubeapps configuration for Postgresql to disable persistence. Kubeapps uses postgres as a cache only, so persistence is not necessary. We've recently had a number of users having postgres auth issues due to the persistence (latest in https://github.com/vmware-tanzu/kubeapps/issues/4689), but what we didn't realise is that this is another setting which had accidentally changed when upgrading postgres from 10->11. As you can see in the diff here, we still had intended to disable persistence, but it's still using the location of that knob for the postgres 10 chart (postgresql.persistence.enabled) rather than the 11 location (postgresql.primary.persistence.enabled).
No auth issues when upgrading kubeapps with the …

[bitnami/kubeapps] Restore PG persistence disabling in Kubeapps chart.

---

.github/workflows/generate-chart-readme.yml

This functionality is not available for workflows of type: `pull_request_target`.
Signed-off-by: Alejandro Ruiz <alejandroruiz@vmware.com>

[bitnami/*] revert: skipping the CI automated README comments

---

bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml

Missing "$" causes error on deploying arbiters.
Fix arbiter statefulset, due to missing `$`
Able to deploy arbiters
None
- fixes #10062 
None
- [ X] Variables are documented in the values.yaml and added to the `README.md` using [readme-generator-for-helm](https://github.com/bitnami-labs/readme-generator-for-helm)
- [ X] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title

[bitnami/mongodb-sharded] Fix bug in arbiter statefulset

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/secrets.yaml
bitnami/mongodb/values.yaml

Use a deepCopy of the context with custom Values in `common.secrets.passwords.manage` call. Some context information (from .Release object) is required by `common.secrets.passwords.manage` helper
Not reported. 
`bitnami/parse` or `bitnami/node` charts couldn't be upgraded if they used version 12.1.8 of this chart

[bitnami/mongodb] Use deepCopy in "common.secrets.passwords.manage" call 

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/keycloak-config-cli-job.yaml

Signed-off-by: Aaron Miller <millrfz@amazon.com>
Updates the environment variable to support keycloak-config-cli versions 5.0.0 and greater.
Without this change keycloak-config-cli fails to run
not aware of any
- fixes #10320

[bitnami/keycloak] Update ENV for keycloak-config-cli v5.0.0+

---

bitnami/dataplatform-bp1/Chart.yaml
bitnami/dataplatform-bp1/README.md
bitnami/dataplatform-bp1/templates/NOTES.txt
bitnami/dataplatform-bp2/Chart.yaml
bitnami/dataplatform-bp2/README.md
bitnami/dataplatform-bp2/templates/NOTES.txt

The Dataplatform BPs Helm charts will be deprecated

[bitnami/dataplatform-bp1/2] Deprecate Dataplatform BPs Helm charts

---

bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/README.md
bitnami/argo-workflows/templates/controller/service-account.yaml
bitnami/argo-workflows/templates/controller/workflow-serviceaccount.yaml
bitnami/argo-workflows/templates/server/service-account.yaml
bitnami/argo-workflows/values.yaml

This PR adds serviceAccount.* parameters that were missing them.

[bitnami/argo-workflows] Add missing serviceAccount.* parameters

---

bitnami/mysql/Chart.yaml
bitnami/mysql/templates/secrets.yaml

Fix SQL authentication (master/slave) due to improper `replicationPassword` value parsing
Slave can authenticate with Master after chart applied.
In helm template, mysql chart v9.0.4, after apply, decoded secret will be:
```
mysql-password: vwzcwef
mysql-replication-password: '"asf3efwf"'
mysql-root-password: fwef23
```
The issue is in the _quote_ in mysql-replication-password.
N/A
- fixes #10366
N/A

[bitnami/mysql] Fix mysql slave auth after applying helm

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/scripts-configmap.yaml

[bitnami/redis]  Don't use sentinel auth in sentinel prestop hook when sentinel auth is disabled.
Allow to use sentinel failover as prestop hook when auth is disabled on sentinel but enabled on redis.
- fixes #10314

[bitnami/redis] Fix #10314: don't use sentinel auth in sentinel prestop hook when sentinel auth is disabled

---

.vib/minio/cypress/cypress/integration/minio_spec.js

These changes adapt Cypress tests to the latest version of MinIO. One of our steps in a test case was in conflict with an upstream issue, so I temporarily commented it out.
MinIO is correctly verified again.
We may need to recall uncommenting the faulty step once the upstream issue is resolved.
NA
Link to upstream issue: https://github.com/minio/console/issues/2031
Successful proof of execution: https://github.com/joancafom/charts/pull/47

[bitnami/minio] Fix minio Cypress tests

---

.vib/mediawiki/vib-publish.json
.vib/mediawiki/vib-verify.json

Adds missing `health-check` action to the `bitnami/mediawiki` VIB pipelines. 
Change tested at https://github.com/FraPazGal/charts/pull/10.

[bitnami/mediawiki] Add health-check to VIB pipelines

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/templates/configmap-env-vars.yaml
bitnami/keycloak/values.yaml

This PR adds support for configuring keycloak distributed caching in kubernetes
Reference: https://www.keycloak.org/server/caching
Users can configure keycloak distributed cache using transport stack as kubernetes and cache as infinity span.
relates_to: https://github.com/bitnami/bitnami-docker-keycloak/pull/65

[bitnami/keycloak] Add support for distributed caching in kubernetes

---

bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/deployment.yaml

Two args were previously rendering as a single line. For example:
```
--aws-zone-type=private
--aws-batch-change-size=1000 - --aws-zones-cache-duration=1h
```
After this fix, the args render correctly. For example:
```
--aws-zone-type=private
--aws-batch-change-size=1000
--aws-zones-cache-duration=1h
```
This is a bug fix.
None
None
This bug was introduced in https://github.com/bitnami/charts/pull/10007

[bitnami/external-dns] Fix YAML syntax

---

bitnami/memcached/Chart.yaml
bitnami/memcached/README.md
bitnami/memcached/templates/deployment.yaml
bitnami/memcached/templates/service.yaml
bitnami/memcached/templates/statefulset.yaml
bitnami/memcached/values.yaml

Add support for terminationGracePeriodSeconds and service.sessionAffinityConfig

[bitnami/memcached] Add support for terminationGracePeriod and service.sessionAffinityConfig

---

.vib/airflow/cypress/cypress/integration/airflow_spec.js

These changes adapt Cypress tests to the latest version of Airflow. It replaces the interaction with the UI by direct navigation to the desired DAG.
Airflow is correctly verified again.
None
NA
Successful proof of execution: https://github.com/joancafom/charts/pull/48

[bitnami/airflow] Fix airflow Cypress tests

---

bitnami/thanos/Chart.yaml
bitnami/thanos/README.md
bitnami/thanos/templates/_helpers.tpl
bitnami/thanos/templates/bucketweb/serviceaccount.yaml
bitnami/thanos/templates/compactor/serviceaccount.yaml
bitnami/thanos/templates/query-frontend/serviceaccount.yaml
bitnami/thanos/templates/query/serviceaccount.yaml
bitnami/thanos/templates/receive-distributor/serviceaccount.yaml
bitnami/thanos/templates/receive/serviceaccount.yaml
bitnami/thanos/templates/ruler/serviceaccount.yaml
bitnami/thanos/templates/serviceaccount.yaml
bitnami/thanos/templates/storegateway/serviceaccount.yaml
bitnami/thanos/values.yaml

Implements the values `serviceAccount.create` and `serviceAccount.name` in a backward-compatible way

[bitnami/thanos] Implement ServiceAccount.create and ServiceAccount.name with BWC

---

.github/workflows/vib-publish.yaml
.vib/haproxy-intel/vib-publish.json
.vib/haproxy-intel/vib-verify.json
bitnami/haproxy-intel/Chart.lock
bitnami/haproxy-intel/Chart.yaml
bitnami/haproxy-intel/README.md
bitnami/haproxy-intel/ci/ct-values.yaml
bitnami/haproxy-intel/templates/NOTES.txt
bitnami/haproxy-intel/values.yaml

Add an umbrella chart for the HAProxy chart that uses an Intel optimized image instead for HAProxy.
**Benefits**
- New chart added to the catalog.
- Umbrella approach makes it easier to maintain.
**Checklist**

[bitnami/haproxy-intel] Add bitnami/haproxy-intel umbrella chart

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/replicaset/statefulset.yaml
bitnami/mongodb/templates/standalone/dep-sts.yaml

Fixes mdb exporter not showing other metrics except mongodb_up
As per https://github.com/percona/mongodb_exporter/blob/main/REFERENCE.md , we need to pass --collect-all argument to enable all available collectors. Also it closes(resolves) https://github.com/bitnami/charts/issues/10440 https://github.com/bitnami/charts/issues/10379 https://github.com/bitnami/charts/issues/10294
Additionally enabled compatible mode as suggested here https://github.com/percona/mongodb_exporter/issues/472

[bitnami/mongodb] enabled mdb all collectors

---

bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/service.yaml
bitnami/external-dns/values.yaml

`type: {{ .Values.service.type }}` is duplicated within the same service manifest:
* https://github.com/bitnami/charts/blob/master/bitnami/external-dns/templates/service.yaml#L15
* https://github.com/bitnami/charts/blob/master/bitnami/external-dns/templates/service.yaml#L49
This produce some issues when rendering the k8s manifests:
```
yaml: unmarshal errors:
line 25: mapping key "type" already defined at line 15
```
k8s manifests are properly rendered
None
- fixes #10468

[bitnami/external-dns] Fix duplicated service type

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/replicaset/scripts-configmap.yaml

Fixes typo that was preventing MONGODB_INITIAL_PRIMARY_HOST from being set correctly.
There are two scenarios where this typo causes issues:
1. When externalAccess.enabled is set and externalAccess.service.type is set to NodePort the secondary/replica would attempt to connect to {kubernetes cluster domain}:{nodeport} instead of {hostname/ip}:{nodeport}
2. If the primary host in the replicaset has changed from the default, the secondary will fail to join
- I believe this fixes #8594 (stale)
- fixes #10458

  [bitnami/mongodb] Replicaset environment variable typo

---

bitnami/kube-state-metrics/Chart.yaml
bitnami/kube-state-metrics/templates/servicemonitor.yaml

Updates bitnami/kube-prometheus subchart dependency.
**Checklist**

[bitnami/kube-state-metrics] Fix servicemonitor namespace

---

bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/templates/NOTES.txt

Replace base64 --decode with base64 -d
The `base64` tool used for decoding the secretes in our Helm charts support `-d` and `--decode` in some versions/distros but only `-d` in others (such as Alpine).
In order to make our charts as much compatible as possible with different distros and distro versions, we should replace the currently used `--decode` flag with `-d` since it is more extended across platforms:
```console
$ docker run -it docker.io/bitnami/minideb base64 --help
Usage: base64 [OPTION]... [FILE]
Base64 encode or decode FILE, or standard input, to standard output.
With no FILE, or when FILE is -, read standard input.
Mandatory arguments to long options are mandatory for short options too.
-d, --decode          decode data
-i, --ignore-garbage  when decoding, ignore non-alphabet …
```

[bitnami/grafana-loki] Replace base64 --decode with base64 -d

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md
bitnami/wordpress/templates/NOTES.txt

Replace base64 --decode with base64 -d
The `base64` tool used for decoding the secretes in our Helm charts support `-d` and `--decode` in some versions/distros but only `-d` in others (such as Alpine).
In order to make our charts as much compatible as possible with different distros and distro versions, we should replace the currently used `--decode` flag with `-d` since it is more extended across platforms:
```console
$ docker run -it docker.io/bitnami/minideb base64 --help
Usage: base64 [OPTION]... [FILE]
Base64 encode or decode FILE, or standard input, to standard output.
With no FILE, or when FILE is -, read standard input.
Mandatory arguments to long options are mandatory for short options too.
-d, --decode          decode data
-i, --ignore-garbage  when decoding, ignore non-alphabet …
```

[bitnami/wordpress] Replace base64 --decode with base64 -d

---

bitnami/common/Chart.yaml
bitnami/common/README.md
bitnami/common/templates/_utils.tpl

fixes #10486
change --decode flag to -d to solve a compatibility issue with alpine linux (--decode flag not available on alpine)
another example of this issue on another product: https://github.com/promptworks/aws-secrets/issues/14

[bitnami/common] use -d flag for base64

---

bitnami/wavefront-prometheus-storage-adapter/Chart.lock
bitnami/wavefront-prometheus-storage-adapter/Chart.yaml
bitnami/wavefront-prometheus-storage-adapter/README.md

Updates bitnami/wavefront-prometheus-storage-adapter subchart dependency.
**Checklist**

[bitnami/wavefront-prometheus-storage-adapter] Update subcharts deps

---

bitnami/haproxy-intel/Chart.yaml

The `containers@bitnami.com` mail is going to be sunset and it was not used for providing support. The proper place to reach out to the Helm charts maintainers and receive support is through this repository.
According to the [official Helm specification](https://helm.sh/docs/topics/charts/#the-chartyaml-file), the `maintainers` object can contain the following config:
```yaml
maintainers: # (optional)
- name: The maintainers name (required for each maintainer)
email: The maintainers email (optional for each maintainer)
url: A URL for the maintainer (optional for each maintainer)
```

[bitnami/haproxy-intel] Replace maintainers email by url

---

bitnami/wordpress/Chart.yaml

The `containers@bitnami.com` mail is going to be sunset and it was not used for providing support. The proper place to reach out to the Helm charts maintainers and receive support is through this repository.
According to the [official Helm specification](https://helm.sh/docs/topics/charts/#the-chartyaml-file), the `maintainers` object can contain the following config:
```yaml
maintainers: # (optional)
- name: The maintainers name (required for each maintainer)
email: The maintainers email (optional for each maintainer)
url: A URL for the maintainer (optional for each maintainer)
```

[bitnami/wordpress] Replace maintainers email by url

---

bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/README.md
bitnami/kubeapps/templates/apprepository/apprepositories.yaml
bitnami/kubeapps/values.yaml

Signed-off-by: Michael Nelson <minelson@vmware.com>
Updates the values, specifically the `apprepository.syncJobPodTemplate.spec` to support `tolerations`.
Users did not have an easy way to specify the tolerations for a sync job pod, though we did support the `nodeSelector`. This small change updates to support `tolerations` as well.
See https://github.com/vmware-tanzu/kubeapps/issues/4574
- fixes https://github.com/vmware-tanzu/kubeapps/issues/4574
Before this change, a sync job pod is created with the following tolerations:
```
tolerations:
- effect: NoExecute
key: node.kubernetes.io/not-ready
operator: Exists
tolerationSeconds: 300
- effect: NoExecute
key: node.kubernetes.io/unreachable
operator: Exists
tolerationSeconds: 300
```
After this change, when the values are updated as per the …

[bitnami/kubeapps] Update chart to support specifying sync tolerations via values.

---

bitnami/grafana-loki/Chart.lock
bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/templates/promtail/clusterrole.yaml
bitnami/grafana-loki/templates/promtail/clusterrolebinding.yaml

The cluster-wide resources in this chart get their name from the `common.names.fullname` function, which only takes into account the deployment name. As such, when installing the same chart with the same deploy name but different namespaces, you get installation errors of the following type"
```
Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "grafana-loki-promtail" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "test": current value is "default"
```
To solve this, we'll use the new `common.names.fullname.namespace` function added in …

[bitnami/grafana-loki] Modify naming of cluster-wide resources

---

bitnami/mysql/Chart.yaml
bitnami/mysql/values.yaml

Fix mysql-secondary configuration
Without this, mysql secondary instances cannot be connected with the
following error message:
Access denied for user 'root'@'localhost' (using password: YES)

[bitnami/mysql] fix mysql-secondary configuration

---

bitnami/redis-cluster/README.md

Amend the scale down documentation to warn the user about removing several nodes at the same time. That process could remove a master node and its slaves at the same time causing a data loss.
- References #9966

[bitnami/redis-cluster] Improve scale down documentation

---

bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/templates/alertmanager/secrets.yaml
bitnami/kube-prometheus/templates/prometheus/additionalPrometheusRules.yaml

Revert `templates/alertmanager/secrets.yaml` and `templates/prometheus/additionalPrometheusRules.yaml` (<7.0.0)
Prometheus rules and AlertManager configurations contain many go templates.
This PR allows to reuse the configurations as before without having to escape each line
This PR also patches the values file which currently contains non-functional examples
- fixes #10496

[bitnami/kube-prometheus] Patch additionalPrometheusRules and alertmanager.templateFiles

---

.vib/minio/cypress/cypress/integration/minio_spec.js

In https://github.com/bitnami/charts/pull/10382, one of our Cypress tests detected a faulty feature in a new version of MinIO. As action, we decided to report it and disable the check for the moment.
A [new version of MinIO](https://github.com/minio/minio/releases/tag/RELEASE.2022-06-03T01-40-53Z) addressing the bug has been released, so the test should be enabled back again. Additionally, it seems that the DOM element that shows error has changed, so this PR also updates its selector accordingly.
- The Cypress test suite for MinIO is completely enabled again.
- Tests work with the latest version of the asset.
None
- relates to https://github.com/bitnami/charts/pull/10382
- Successful proof of execution: https://github.com/joancafom/charts/pull/50
- MinIO Console (UI) release addressing …

[bitnami/minio] Enable back & fix minio test

---

.github/workflows/vib-verify-extra-redis.yaml
.github/workflows/vib-verify-extra-thanos.yaml

When using an extra VIB verify pipeline to test some specific features/configuration of a Helm chart, the name used is simply _VIB_, the same name used by the generic VIB pipeline.
Currently, there are 3 VIB actions (the generic one and the other two with the extra tests for Redis and Thanos); but in the future, when this number grows, it won't be easy to navigate over the [actions view](https://github.com/bitnami/charts/actions).
There is a descriptive name to be shown in the [actions view](https://github.com/bitnami/charts/actions) instead of the current

Use descriptive name for extra VIB verify workflows

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/ingress.yaml

The service name of the ingress was set to "restApi" which is an invalid value for Kubernetes. It should have been "tcp-rest-api".
Fixes #10460
Signed-off-by: Tonny Miousse <tonny.miousse@telus.com>

[bitnami/elasticsearch] Fix ingress service name

---

.github/workflows/vib-publish.yaml

Add MongoDB, Kibana, and SolR to the list of assets published using VMware Image Builder.
Increased pool of assets completely handled by VMware Image Builder.
None
NA
NA

[bitnami/*] Use VIB to publish mongodb, kibana and solr

---

bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/README.md
bitnami/spring-cloud-dataflow/values.yaml

[bitnami/spring-cloud-dataflow] Fix tolerations default values

---

bitnami/jenkins/Chart.yaml
bitnami/jenkins/README.md
bitnami/jenkins/values.yaml

[bitnami/jenkins] Fix tolerations default values

---

bitnami/nginx/Chart.yaml
bitnami/nginx/README.md
bitnami/nginx/values.yaml

[bitnami/nginx] Fix tolerations default values

---

bitnami/nginx-intel/Chart.yaml
bitnami/nginx-intel/README.md
bitnami/nginx-intel/values.yaml

[bitnami/nginx-intel] Fix tolerations default values

---

bitnami/concourse/Chart.yaml
bitnami/concourse/README.md
bitnami/concourse/values.yaml

[bitnami/concourse] Fix topologySpreadConstraints default values

---

bitnami/spark/Chart.yaml
bitnami/spark/README.md
bitnami/spark/values.yaml

[bitnami/spark] Fix topologySpreadConstraints default values

---

bitnami/wildfly/Chart.yaml
bitnami/wildfly/README.md
bitnami/wildfly/values.yaml

[bitnami/wildfly] Fix tolerations default values

---

bitnami/memcached/Chart.yaml
bitnami/memcached/README.md
bitnami/memcached/values.yaml

[bitnami/memcached] Fix topologySpreadConstraints default values

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md
bitnami/wordpress/values.yaml

[bitnami/wordpress] Fix topologySpreadConstraints default values

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/values.yaml

[bitnami/keycloak] Fix topologySpreadConstraints default values

---

bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/README.md
bitnami/jupyterhub/values.yaml

[bitnami/jupyterhub] Fix topologySpreadConstraints default values

---

bitnami/sealed-secrets/Chart.yaml
bitnami/sealed-secrets/README.md
bitnami/sealed-secrets/values.yaml

[bitnami/sealed-secrets] Fix topologySpreadConstraints default values

---

bitnami/pytorch/Chart.yaml
bitnami/pytorch/README.md
bitnami/pytorch/values.yaml

[bitnami/pytorch] Fix topologySpreadConstraints default values

---

bitnami/wavefront-adapter-for-istio/Chart.yaml
bitnami/wavefront-adapter-for-istio/README.md
bitnami/wavefront-adapter-for-istio/values.yaml

[bitnami/wavefront-adapter-for-istio] Fix topologySpreadConstraints default values

---

bitnami/zookeeper/Chart.yaml
bitnami/zookeeper/README.md
bitnami/zookeeper/values.yaml

[bitnami/zookeeper] Fix topologySpreadConstraints default values

---

bitnami/grafana-tempo/Chart.yaml
bitnami/grafana-tempo/README.md
bitnami/grafana-tempo/values.yaml

[bitnami/grafana-tempo] Fix topologySpreadConstraints default values

---

bitnami/ghost/Chart.yaml
bitnami/ghost/README.md
bitnami/ghost/values.yaml

[bitnami/ghost] Fix tolerations default values

---

template/CHART_NAME/values.yaml

[template] Fix topologySpreadConstraints default values

---

bitnami/postgresql-ha/README.md

This is a very minor change in the upgrade notes of the documentation of postgresql-ha. The release notes use `POSTGRES_PASSWORD` to export the password (https://github.com/bitnami/charts/blob/master/bitnami/postgresql-ha/templates/NOTES.txt#L41). This variable name is matching the documentation (instead `POSTGRESQL_PASSWORD`) from now on.
I did only change the general upgrade documentation and not those for previous major upgrades.
No different variable names for the same thing.
None.

[bitnami/postgresql-ha] Updated README no match release notes variable names

---

.vib/airflow/vib-verify.json
bitnami/airflow/Chart.yaml
bitnami/airflow/README.md
bitnami/airflow/values.yaml

[bitnami/airflow] Fix topologySpreadConstraints default values

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/README.md
bitnami/cassandra/templates/statefulset.yaml
bitnami/cassandra/values.yaml

Cassandra commit log mount fixed 
- Cassandra commit log mount fixed ( if commitStorageClass is replaced with commitLogMountPath)
- a few lines are added to the readme
- comment added on default values 
Before there was unclear behavior when PVCs for commit log were created, but not mounted until you not define the particular `--set persistence.commitStorageClass=gp3 `. The preferred behavior is to use the default storage class. I suggest creating and mounting PVC by a single parameter `--set persistence.commitLogMountPath=/bitnami/cassandra/commitlog`. Some documentation was improved to make it easy to start.
The issue looks like this:
```
helm upgrade --install cassandra bitnami/cassandra --version 9.1.11 \
--set replicaCount=3 \
--set persistence.size=100Gi \
--set …
```

[bitnami/cassandra] Cassandra commit log mount fixed

---

bitnami/kafka/Chart.yaml
bitnami/kafka/templates/jmx-configmap.yaml
bitnami/kafka/templates/kafka-metrics-deployment.yaml
bitnami/kafka/templates/kafka-metrics-serviceaccount.yaml
bitnami/kafka/templates/kafka-metrics-svc.yaml
bitnami/kafka/templates/servicemonitor-jmx-metrics.yaml
bitnami/kafka/templates/servicemonitor-metrics.yaml

change the app.kubernetes.io/component for kafka-exporter to differenciate it from jmx-exporter
separate service & servicemonitor for kafka-exporter & jmx-exporter
- fixes #10470

[bitnami/kafka] component labels for jmx & kafka exporter

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/statefulset.yaml

Cassandra: Drain node before stop when persistence enabled memtable and restart node correctly
Signed-off-by: Sergey Matvienko <smatvienko@thingsboard.io>
Cassandra will stop correctly using `nodetool drain` for persistence-enabled configuration.
https://kubernetes.io/docs/tutorials/stateful-application/cassandra/#using-a-statefulset-to-create-a-cassandra-ring
https://docs.datastax.com/en/cassandra-oss/3.0/cassandra/tools/toolsDrain.html
Correct lifecycle with no surprise when you make a rolling restart like
```
kubectl rollout restart statefulset cassandra
```
- fixes #

[bitnami/cassandra] Cassandra: Drain node before stop when persistence enabled

---

bitnami/airflow/Chart.yaml
bitnami/airflow/templates/config/configmap.yaml

Signed-off-by: Tung Le Thanh <nothing5lose@gmail.com>
For Resolve: https://github.com/bitnami/charts/issues/10720
worker podTemplate's configmap should be rendered using common.tplvalues.render.
Now it's not functional correct (template literal value rendered)
N/A
- fixes #10720
N/A

[bitnami/airflow] worker podTemplate's configmap rendered using common.tplvalues.render

---

.github/workflows/generate-chart-readme.yml
.github/workflows/vib-publish.yaml
template/CHART_NAME/Chart.yaml

This PR replaces the maintainer/committer email in GH workflows and chart scaffolding in order to use a corporative VMware account replacing the old Bitnami one

Replace maintainer/committer email in GH workflows and chart scaffolding

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/configmap-env-vars.yaml

Despite setting value `cache.enabled: false`, Keycloak will attempt to use **ISPN** JGroups, which in turn causes the Keycloak instance to go cluster-wide looking for other Keycloak instances.
This enforces to set `KEYCLOAK_CACHE_TYPE: "local"` if cache is disabled.
Infinispan and JGroups won't create a multicast address, other Keycloak instances won't attempt to "join the standalone Keycloak"
N/A
N/A
Testing with values file:
```yaml
auth:
adminUser: admin
adminPassword: somepassword
postgresql:
enabled: true
primary:
persistence:
enabled: true
size: 2Gi
ingress:
enabled: true
certManager: true
tls: true
hostname: myhostname.local
ingressClassName: nginx
annotations:
cert-manager.io/cluster-issuer: letsencrypt
nginx.ingress.kubernetes.io/proxy-read-timeout: "3600" …
```

[bitnami/keycloak] Set cache type "local" if cache is disabled

---

bitnami/kube-state-metrics/Chart.yaml
bitnami/kube-state-metrics/templates/clusterrole.yaml
bitnami/kube-state-metrics/templates/clusterrolebinding.yaml
bitnami/kube-state-metrics/templates/psp-clusterrole.yaml
bitnami/kube-state-metrics/templates/psp-clusterrolebinding.yaml
bitnami/kube-state-metrics/templates/psp.yaml

The cluster-wide resources in this chart get their name from the `common.names.fullname` function, which only takes into account the deployment name. As such, when installing the same chart with the same deploy name but different namespaces, you get installation errors of the following type"
```
Error: rendered manifests contain a resource that already exists. Unable to continue with install: PodSecurityPolicy "alpha-kube-state-metrics" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-namespace" must equal "gamma": current value is "default"
```
To solve this, we'll use the new `common.names.fullname.namespace` function added in #10462.
Solves a chart design issue and allows for the …

[bitnami/kube-state-metrics] Modify naming of cluster-wide resources

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/bucketweb/deployment.yaml
bitnami/thanos/templates/compactor/deployment.yaml
bitnami/thanos/templates/query-frontend/deployment.yaml
bitnami/thanos/templates/query/deployment.yaml
bitnami/thanos/templates/receive-distributor/deployment.yaml
bitnami/thanos/templates/receive/statefulset.yaml
bitnami/thanos/templates/ruler/statefulset.yaml
bitnami/thanos/templates/storegateway/statefulset.yaml

Fixes https://github.com/bitnami/charts/issues/10778

[bitnami/thanos] Fix customStartupProbe for thanos receive statefulset

---

bitnami/airflow/Chart.yaml
bitnami/airflow/README.md
bitnami/airflow/templates/_helpers.tpl
bitnami/airflow/templates/config/configmap.yaml
bitnami/airflow/templates/config/secret-external-redis.yaml
bitnami/airflow/templates/scheduler/deployment.yaml
bitnami/airflow/templates/scheduler/service-headless.yaml
bitnami/airflow/values.yaml

Adds support for the new `LocalKubernetesExecutor`. Fixes https://github.com/bitnami/charts/issues/10659
Can now select if a task runs in the scheduler, or in a kubernetes pod
- fixes #

[bitnami/airflow] Allows for LocalKubernetesExecutor to be used, as added in Airflow 2.3 (#10659)

---

bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/templates/_helpers.tpl

Set the define postgresql-ha.postgresqlPasswordProvided correct, if postgresql.postgresPassword instead of global.postgresql.postgresPassword is used and the values global or global.postgresql exists.
The following configuration will work as expected and create a password for the postgresql user:
```
helm install --namespace test postgresql bitnami/postgresql-ha \
--set postgresql.postgresPassword=supersecret \
--set postgresql.password=secret \
--set postgresql.username=test \
--set postgresql.database=test
```
Because with the current chart trying to login as postgres user with the postgres user password supersecret on one of the postgresql pods with the command `kubectl exec -it -n test postgresql-postgresql-ha-postgresql-0 -- psql -U postgres` fails with the error message: `FATAL: …

[bitnami/postgresql-ha] Fix postgres user password configuration

---

.github/workflows/archive-full-index.yaml

This change is a new branch that will not be merged with master. The purpose is to hold file called bitnami/index.yaml which will be the home for the archive of Bitnami Charts full index. The index is built once per day.
The workflow downloads the last 6-months index from charts.bitnami.com and merges it with the last full index available, removes the duplicates and checks that there is not dups remaining or any missing release.
We can offer a full index for everybody so the can use it to access every chart version, not only version from the last six months.
This work is part of the efforts to reduce the impact of cutting off the official Bitnami Charts index to 6-months.
- [N/A] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/).
- [N/A] Variables are …

[bitnami/index] Archive full index automation

---

bitnami/solr/Chart.yaml
bitnami/solr/templates/statefulset.yaml

…less ressource hungry ones
Signed-off-by: Robert Mühlbauer <robert.muehlbauer@youplant.com>
changes liveness and readiness probes if solr runs in cloud mode.
Uses solr's implicit request handlers, as described here: https://solr.apache.org/guide/solr/latest/configuration-guide/implicit-requesthandlers.html
solves issue described in #10502 and therefore consume less cpu/memory for probing
- fixes #10502

[bitnami/solr]change liveness and readiness probes for solr cloud to

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/_helpers.tpl

Signed-off-by: Adrian Axelsson <adrian.axelsson@hotmail.se>
When deploying the current version of the postgresql chart with replication, without specifying an existing secret, postgresql.replicationPasswordKey will not default to "replication-password". 
This change fixes the if/else logic
The chart can be installed successfully with architecture=replication without having to specify an existing secret
- fixes #

[bitnami/postgresql] fix postgresql.replicationPasswordKey secret key logic

---

.github/workflows/archive-full-index.yaml

Due to Github workflow limitations it is not possible to run a workflow in the branch `archive-full-index` when the `push` event occurs in the `index` branch. So we decided to move the `archive-full-index` workflow to the `index` branch. See the previous [PR](https://github.com/bitnami/charts/pull/10830).
Fix the [current archive-full-index](https://github.com/bitnami/charts/pull/10830) workflow.
(https://github.com/bitnami-labs/readme-generator-for-helm)

[bitnami/index] New workflow for Bitnami Charts full index.

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/replicas/statefulset.yaml

Signed-off-by: AJ Romito <ajromito@gmail.com>
Issue introduced in #10047
When installing redis master as a deployment, with count = 1, the endpoint/url of the service is changed and cannot support the current value in the template.  
Conditional expanded to set REDIS_MASTER_HOST to the regular service endpoint when master.kind = Deployment.
Allows redis replicas to come online and make connection to master.
- fixes #10621 
Deployment kind for master helps us maintain redis uptime in eks, as non-graceful shutdown can occur and causes issues with statefulset.  We prefer data loss over extended downtime.
ToDo: Add support for replica of kind deployment to further support quick recovery

[bitnami/redis] Fix for REDIS_MASTER_HOST

---

bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/mongos/mongos-dep-sts.yaml
bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml
bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml

- Fixed call to common render values instead of incorrect mongodb-sharded tplValue
- Fixed extraEnvVarsSecret call to be secretRef instead of configMapRef
- Bumped to newer version
- extraEnvVarsSecret for mongos maps as secrets instead of previous configmap (pod fails to start)
- extraEnvVarsSecret and extraEnvVarsCM have correct calls to include template values, which can pull configuration correctly. Users can set extraEnvVarsSecret and extraEnvVarsCM without error
- fixes #10856
- fixes #10847

[bitnami/mongodb-sharded] Fixed calls for render values and extraEnvVarsSecret calls

---

bitnami/keycloak/Chart.yaml

Bump chart version to fix https://github.com/bitnami/charts/commit/5e62b53282f56ca55420e96b39f6a7935d449c2a, which was incorrectly merged without a bump.
Correct asset versioning.
None
- relates to https://github.com/bitnami/charts/pull/10876
NA

[bitnami/keycloak] Bump chart version accordingly

---

.github/workflows/ci-pipeline-extra-redis.yaml
.github/workflows/ci-pipeline-extra-thanos.yaml
.github/workflows/ci-pipeline.yaml

Today our internal tools created 30 automated PRs in the span of ~45 min. Given the high number of action runs triggered, the GitHub's service that manages actions couldn't process so many of them simultaneously and queued them. Unfortunately, some of them were queued incorrectly. In [this example](https://github.com/bitnami/charts/actions?query=branch%3Aautomated%2Fairflow-12.5.11), the run triggered by labeling the PR was executed after the execution of the run triggered by opening the PR.
As seen above, this caused instances where the execution order was mixed and thus some of the actions that should have skipped the `VIB Verify` job executed it. This would normally cause only a PR to have double approval but because the VIB service was at …

Improve trigger restrictions for the CI/VIB Verify job

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/templates/statefulset.yaml
bitnami/rabbitmq/values.yaml

Allow customize the securityContext in the RabbitMQ Helm chart for the volumePermission container.
Be able to run on OpenShift
Do not known. The default behavior remain the same.
- fixes #9984
- fixes #8932

[bitnami/rabbitmq] Allow to customize securityContext in volumePermission container

---

.github/workflows/ci-pipeline.yaml

In https://github.com/bitnami/charts/pull/10982, we introduced a new set of logic conditions to prevent `VIB Verify` to be double-triggered. Nevertheless, it seems that the ordering of the logic is not correct and some PRs are now failing due to that:
https://github.com/bitnami/charts/pull/10991
https://github.com/bitnami/charts/pull/10988
https://github.com/bitnami/charts/blob/bec65c1eb1e7c647299f32f11951e4911ca87d6c/.github/workflows/ci-pipeline.yaml#L95-L99
Looking at the logic, we are missing some parentheses between the last two conditions. This opens the possibility for some PRs to skip the first two preconditions (previous step is OK & the event action is not open).
This PR fixes this logic, adding the correct parentheses in place to ensure preconditions are met.
Correct triggering …

[bitnami/*] Fix incorrect triggering of VIB

---

bitnami/mysql/Chart.yaml
bitnami/mysql/templates/secondary/statefulset.yaml

Initscripts were being executed only in the primary node.
This PR fixes the issue by running init scripts in both primary and secondary nodes.
Allow users to run init scripts in secondary nodes.
Users who are already using init scripts, may need to add additional logic if they want their scripts to be executed only in the primary node:
```bash
if [[ "$DB_REPLICATION_MODE" != "slave" ]]; then
echo "Running init script on a primary"
fi
```
- fixes #10984

[bitnami/mysql] Run initscripts on secondary nodes

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/read/metrics-configmap.yaml
bitnami/postgresql/templates/read/metrics-svc.yaml
bitnami/postgresql/templates/read/servicemonitor.yaml

Signed-off-by: Aurélien Pasteau <aurelien.pasteau@illuin.tech>
This change adds the condition that the replication architecture must be enabled to create the following templates in the postgresql chart:
* read/metrics-configmap.yaml
* read/metrics-svc.yaml
* read/servicemonitor.yaml
It also changes the selectors in the read/servicemonitor.yaml and the labels in read/metrics-svc.yaml to scrape the metrics from the correct pod.
This PR solves 2 different bugs:
1. When standalone architecture is enabled, the read servicemonitor is created (which is not normal) and exports metrics from the primary pod.
2. When replication architecture is enabled, the read servicemonitor is created (so far all good) but it exports the metrics from the primary pod instead of the replication pod
- fixes #

[bitnami/postgresql] Fix postgresql read servicemonitor scraping metrics on primary pod

---

.vib/phpmyadmin/cypress/cypress/integration/phpmyadmin_spec.js

This PR adapts tests to the new version of PhpMyAdmin, which includes some minor changes in the UI:
- A floating menu that covers some actionable elements (hence, use `force: true`)
- Renaming of some buttons (`Go` -> `Create`)
Working, up-to-date tests.
None
NA
This PR will unblock https://github.com/bitnami/charts/pull/10946
Associated Graph ID used to test: ff12a94e-39d6-45fd-871d-43d2441defc6

[bitnami/phpmyadmin] Fix PhpMyAdmin cypress tests

---

.github/workflows/sync-labels.yml

Adding a scheduled daily job to synchronize labels from the bitnami/containers repository.
Ensuring the repositories have the same labels
If in the bitnami/containers a label is created without thinking in a common way, it maybe will not make sense here.
Now running in the [bitnami/vms](https://github.com/bitnami/vms) repository getting the labels from this repository and working as expected.

Creating a scheduled job to sync labels from bitnami/containers

---

bitnami/nginx/Chart.yaml
bitnami/nginx/README.md
bitnami/nginx/templates/deployment.yaml
bitnami/nginx/values.yaml

Adds `extraContainerPorts`, addresses #10998. Adheres to the convention across other Bitnami charts.
Allows custom container ports to be added.
N/A
N/A
N/A

[bitnami/nginx] Add custom container ports

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/_helpers.tpl

This change removes the validation check for receiver to have object store config
Users will be able to run Thanos receiver without object strore config as Thanos can store data locally
- Nothing I am aware of.
- fixes #10995 
-

 [bitnami/thanos]: Allow receiver to run without object store config

---

bitnami/wavefront-adapter-for-istio/Chart.yaml

Signed-off-by: michield <michield@vmware.com>
Marking Wavefront Adapter for Istio as deprecated

Mark Wavefront Adapter for Istio as deprecated

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/templates/statefulset.yaml

Allow not set RABBITMQ_LOGS env to set custom logging. When RABBITMQ_LOGS is set log parameters in rabbitmq.conf are ignored.
The [official documentation says](https://www.rabbitmq.com/logging.html#log-file-location):
> The environment variable takes precedence over the configuration file. When in doubt, consider overriding log file location via the config file. As a consequence of the environment variable precedence, if the environment variable is set, the configuration key `log.file` will not have any effect.
Allow set `log.*` parameters in `extraConfiguration` value.
I don't think so.
I have been testing `log.` parameters. When the env `RABBITMQ_LOGS` exists seems like rabbit doesn't read log config. So using the following config:
```yaml
extraConfiguration: |
log.default.level = …
```

[bitnami/rabbitmq] Allow set custom logging

---

bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/templates/argocd-secret.yaml

do not change autogenerated admin password during upgrade.
- fixes #10974

[bitnami/argo-cd] Persistent autogenerated admin password on upgrade

---

.vib/redis/replicas/goss/goss-replica/goss.yaml

In #10655 `slave-read-only yes` was removed because that configuration was removed in 2.6 and the new `replica-read-only` is `yes` by default
Keep tests aligned with latest redis version
#10655

[bitnami/redis] Remove 'slave-read-only yes' test for replicas

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/statefulset.yaml

Use REST APIs for liveness/readiness probes, instead of spawning
expensive erlang processes.
Negligible CPU usage.
* Might be less accurate
- fixes #11116

[bitnami/rabbitmq] Fix high CPU usage while idle

---

bitnami/matomo/Chart.yaml

This PR just changes the case in the `category` field, as the rest of the chart capitalizes the first letter. So, `analytics` becomes `Analytics`.
For case-sensitive consumers (like Kubeapps)  this field will be processed properly
N/A
N/A
N/A

[bitnami/matomo] Fix category case

---

bitnami/external-dns/Chart.yaml
bitnami/external-dns/templates/psp-clusterrole.yaml

Fixes an issue with the psp-clusterrole template caused by a double dash `-`
- fixes #11079

[bitnami/external-dns] Fix issue with psp-cluster-role

---

bitnami/drupal/Chart.yaml
bitnami/drupal/README.md
bitnami/drupal/templates/_helpers.tpl
bitnami/drupal/templates/deployment.yaml
bitnami/drupal/templates/serviceaccount.yaml
bitnami/drupal/values.schema.json
bitnami/drupal/values.yaml

This PR adds a configurable ServiceAccount to Drupal
It is Best Practice to use ServiceAccounts per Namespace/Deploment for security reasons
No drawbacks because a default ServiceAccount will be used as fallback

[bitnami/drupal] Add ServiceAccount

---

bitnami/airflow/Chart.lock
bitnami/airflow/Chart.yaml
bitnami/airflow/README.md

[bitnami/airflow] Update Redis subchart

---

bitnami/argo-cd/Chart.lock
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/README.md

Upgrading notes will be moved to charts-docs: bitnami/charts-docs#120

[bitnami/argo-cd] Update Redis subchart

---

bitnami/kubeapps/Chart.lock
bitnami/kubeapps/Chart.yaml

[bitnami/kubeapps] Update Redis subchart

---

bitnami/harbor/Chart.lock
bitnami/harbor/Chart.yaml

[bitnami/harbor] Update Redis subchart

---

bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml

[bitnami/discourse] Update Redis subchart

---

bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/secrets.yaml

Use the `common.secrets.passwords.manage` helper to prevent app secrets from being regenerated during an upgrade process.
- Passwords are reused during the upgrade process
- New pods can join the cluster without issues
None
- fixes #10771 
NA

[bitnami/mongodb-sharded] Use common helper to manage app secrets

---

bitnami/oauth2-proxy/Chart.lock
bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md

This PR updates the `bitnami/redis` subchart to its latest version `17.0.1`, which upgrades Redis from its version 6.2 to version 7.0.
Upgrading notes are moved to the chart documentation: https://github.com/bitnami/charts-docs/pull/121

[bitnami/oauth2-proxy] Update Redis subchart

---

.github/workflows/cd-pipeline.yaml
.github/workflows/ci-pipeline-extra-redis.yaml
.github/workflows/ci-pipeline-extra-thanos.yaml
.github/workflows/ci-pipeline.yaml

The team has discovered an issue affecting the creation of some TKG clusters. Temporarily change the default target-platform to avoid pipelines from failing.
Additionally, and as agreed in the past, deprecate the use of GitHub secrets for to set the main and alternative target-platforms.
High-availability: VIB pipelines are not affected by transient errors related to the default platform.
None
NA
NA

[bitnami/*] Temporarily change VIB target-platform

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/query/deployment.yaml

- Describe the scope of your change - i.e. what the change does.
- Describe any known limitations with your change.
- Please run any tests or examples that can exercise your modified code.
Replaced `--store=` with `--endpoint=`
Users will not have to worry when the "deprecation" happens.
Older versions (before adding `--endpoint` flag might not work
fixes:
```
--store=<store> ...        Deprecation Warning - This flag is deprecated
and replaced with `endpoint`. Addresses of
statically configured store API servers
(repeatable). The scheme may be prefixed with
'dns+' or 'dnssrv+' to detect store API servers
through respective DNS lookups.
--store-strict=<staticstore> ...
Deprecation Warning - This flag is deprecated
and replaced with `endpoint-strict`. Addresses
of only statically …
```

[bitnami/thanos] fix Deprecation Warning of thanos

---

bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/README.md
bitnami/redis-cluster/templates/redis-statefulset.yaml
bitnami/redis-cluster/values.yaml

Signed-off-by: Muhammad Hamza Zaib <hamzazaib3202@gmail.com>
This pull request adds the ability to specify container security context for the metrics container. Even though the change introduced does not break anything, it is still disabled by default i.e the default behavior is to not set container security context for the metrics container.
It will be possible to set the container security context for the metrics container. If a cluster doesn't allow privilege escalation then it is not possible to deploy redis with metrics currently.
None that I am aware of
N/A

[bitnami/redis-cluster] Allow specifying metrics container security context

---

bitnami/minio/Chart.yaml
bitnami/minio/README.md
bitnami/minio/templates/_helpers.tpl

Signed-off-by: kyue1005 <kyue1005@gmail.com>
Remove empty values check for s3 creds when using IRSA
Allow empty s3 creds when using IRSA for accessing s3 in EKS
No drawbacks.
N/A
N/A

[bitnami/minio] allow empty s3 creds when using iam role for sa

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/templates/servicemonitor.yaml
bitnami/keycloak/values.yaml

This change will allow the scrape path to be configurable, as `/metrics` will only work, if `httpRelativePath` is set to `/`
Monitoring will work if `httpRelativePath` set to a non-default value.
- fixes #
```
keycloak@keycloak-2:/$ curl -s http://localhost:8080/metrics; echo
<html><body><h1>Resource not found</h1></body></html>
keycloak@keycloak-2:/$ curl -s http://localhost:8080/auth/metrics | head -n1; echo
```

[bitnami/keycloak] make metrics scrape target configurable

---

bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/templates/prometheus-proxy/deployment.yaml
bitnami/spring-cloud-dataflow/templates/prometheus-proxy/service.yaml
bitnami/spring-cloud-dataflow/templates/server/configmap.yaml
bitnami/spring-cloud-dataflow/templates/server/deployment.yaml
bitnami/spring-cloud-dataflow/templates/server/ingress.yaml
bitnami/spring-cloud-dataflow/templates/server/service.yaml
bitnami/spring-cloud-dataflow/templates/skipper/configmap.yaml
bitnami/spring-cloud-dataflow/templates/skipper/deployment.yaml
bitnami/spring-cloud-dataflow/templates/skipper/service.yaml

Signed-off-by: umer <umer.anwar@nuance.com>
Use common `common.tplvalues.render` function instead of just `toYaml`.
Allows the usage of templates instead of just outputting the yaml. Also aligns the chart where this function is being used [(example)](https://github.com/bitnami/charts/blob/master/bitnami/spring-cloud-dataflow/templates/server/deployment.yaml#L13).
This will allow us to evaluate custom logic and pass it on to the chart as values.
For example:
If we define the following variable:
```yaml
{{- define "common.volumeMount.myVolumeMount" }}
- name: my-volume-mount
mountPath: {{ .Values.myVolumeMount.containerVolumeMountPath | default "/mnt/foo" }}
readOnly: true
{{- end }} 
```
Then we want to be able to use it in the spring-cloud-dataflow chart:
```yaml
extraVolumeMounts: '{{ …
```

[bitnami/spring-cloud-dataflow] use common tpl function instead of toYaml

---

.github/ISSUE_TEMPLATE/bug_report.yml
.github/ISSUE_TEMPLATE/feature_request.yml
.github/workflows/.env
.github/workflows/clossing-issues.yml
.github/workflows/comments.yml
.github/workflows/move-closed-issues.yml
.github/workflows/moving-cards.yml
.github/workflows/sync-labels.yml
.github/workflows/triage.yml

Adding GH workflows in order to use GH board.
Using GH board to manage the issues and PRs support.
When an issue is commented and closed at the same time, depending on how GH performs the actions (order) the issue will appear on the _Solved_ column or in the _Triage_ one (as reopened). That's something out of our control and happens sometimes.
All the issues and PRs will be sent to the Support board.

Adding workflows for the support by using the GH board

---

.github/workflows/cd-pipeline.yaml
.github/workflows/ci-pipeline-extra-redis.yaml
.github/workflows/ci-pipeline-extra-thanos.yaml
.github/workflows/ci-pipeline.yaml

Add the `[CI/CD]` prefix to the GH actions name.
In the [Actions view](https://github.com/bitnami/charts/actions) it would be easy to identify what actions are related to a specific purpose.
In the same way, since actions are alphabetically ordered, all the actions with the same prefix will appear together. This is the approach used for the different actions related to support, see
Related to https://github.com/bitnami/charts/pull/11271

Add [CI/CD] prefix to the GH actions name

---

.github/workflows/archive-full-index.yaml
.github/workflows/sync-chart-index.yaml

Add the `[Index]` prefix to the GH actions name.
In the [Actions view](https://github.com/bitnami/charts/actions) it would be easy to identify what actions are related to a specific purpose.
In the same way, since actions are alphabetically ordered, all the actions with the same prefix will appear together. This is the approach used for the different actions related to support, see
Related to https://github.com/bitnami/charts/pull/11270

Add [Index] prefix to the GH actions name

---

.github/workflows/triage.yml

Avoid assigning reviewers for the bitnami-bot PRs. Replicate changes from https://github.com/bitnami/containers/pull/263
Automated PRs will not have reviewers by default.
If _bitnami-bot_ opens a non-automated PR, will not have a reviewer assigned.

Avoid assigning reviewers for the bitnami-bot PRs

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/health-ingress.yaml
bitnami/nginx/templates/ingress.yaml

Signed-off-by: Ferdinand Hübner <mail@ferdi.codes>
Commit f48790b465021af15620f08d40fec2d065535e14 (PR #10048) breaks support for externally provided TLS certificates that are specified through the `ingress.secrets` and `healthIngress.secrets` parameters. This change fixes the TLS block rendering for configurations of the chart that supply TLS certificates externally. 
TLS certificats can be provided externally again.
N/A
N/A
N/A

[bitnami/nginx] Fix TLS setup for externally provided TLS certificates

---

.github/workflows/ci-pipeline.yaml

Disable CI in closed PRs. Also on 'labeled' events we take care only about 'verify' label
Don't run CI on unexpected events. For example automated [PRs are failing](https://github.com/bitnami/charts/pulls?q=is%3Apr+is%3Aclosed+is%3Amerged+author%3Abitnami-bot) after closing it

[bitnami/*] Disable CI in closed PRs

---

.github/workflows/comments.yml
.github/workflows/move-closed-issues.yml
.github/workflows/moving-cards.yml
.github/workflows/triage.yml

Ignoring automated PR (Release activity) from the support flow.
Ensuring the support flow only handles the support and not any flow related to the Release one.
None detected

[bitnami/*] Ignoring automated PR (Release activity) from the support flow. 

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/scripts-configmap.yaml

Fixes #11294
Signed-off-by: Kendi Paet <kendi@tavex.eu>
Add timeout to redis-cli in start-sentinel.sh, because since Redis version 7.0 redis-cli doesn't seem to have timeout and redis-cli will run forever until container gets retarted by Kubernetes. This will fix it by adding timeout, so the script won't wait indefinetly, so Sentinel can actually start when master is not yet created or available.

[bitnami/redis] Add timeout to redis-cli in start-sentinel.sh

---

bitnami/dataplatform-bp2/Chart.yaml

A new version bump is needed, followup of https://github.com/bitnami/charts/pull/11328 and https://github.com/bitnami/charts/pull/11331

[bitnami/dataplatform-bp2] Bump chart version in Chart.yaml

---

.github/workflows/comments.yml
.github/workflows/move-closed-issues.yml
.github/workflows/moving-cards.yml
.github/workflows/triage.yml

When in the PR #11308 we avoided adding the bitnami-bot PRs action to the support flow, there was a regression that impacted on the issues (are not added into triage). This fixes it.
Issues will be in the support flow as they should.
None detected.

Fixing regression when an issue is created by non bitnami-bot

---

.github/workflows/comments.yml

Fixing the race condition only to exclude bitnami-bot ON auto-merge PRs
When an user comment on a non release PR/issue the cards are properly moved.
None detected.

[bitnami/*]  Fixing the race condition only to exclude bitnami-bot ON auto-merge PRs

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/statefulset.yaml

This make **volume-permissions** initContainer able to run without error if value `volumePermissions.containerSecurityContext.runAsUser=auto`
OpenShift users will be able to run this initContainer with an arbitrary user id.
Not known. the default behaviour remain the same. It just fix the use case of the "auto" user id.
- fixes #9984
- fixes #8932

[bitnami/rabbitmq] Fix volume-permissions initContainer if runAsUser is auto

---

.github/workflows/ci-pipeline.yaml

Until now, the initial triage for automated PRs of labeling and enabling auto-merge was performed internally. That is, the same pipeline that created the PR performed the triage. With this PR, we'll leave only the PR creation logic internally and have all the PR lifecycle logic in GH instead of having it divided.
Besides that logic migration, we are also adding the disable of auto-merge when an automated PR fails to run VIB Verify. This is to avoid a specific corner case where an automated PR could be merged without executing the whole CI.
We improve transparency and avoid having part of the PR management logic internally. 
Users with opened PRs may require a rebase from `master` branch.
This PR is a copy of …

[bitnami/*] Migrate logic for automated PRs to GitHub's CI

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/replicas/hpa.yaml
bitnami/redis/templates/sentinel/hpa.yaml

Minor change that prevents the bitnami/redis helm chart to produce OutOfSync applications when deployed with ArgoCD
Chart can be used with or without ArgoCD
None
- fixes #11312
It is a known limitation of ArgoCD and Kubernetes as stated in ArgoCD's documentation: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing
- [ x] Chart version bumped in `Chart.yaml` according to [semver](http://semver.org/). This is *not necessary* when the changes only affect README.md files.
- [ x] Title of the pull request follows this pattern [bitnami/<name_of_the_chart>] Descriptive title
- [ x] All commits signed off and in agreement of [Developer Certificate of Origin (DCO)](https://github.com/bitnami/charts/blob/master/CONTRIBUTING.md#sign-your-work)

[bitnami/redis] Fix OutOfSync HPAs with ArgoCD

---

.github/workflows/cd-pipeline.yaml

This PR makes our CD pipeline more resilient against concurrency failures. It decouples the _VIB Publish_ step from the _Update Index_ one, introducing retry-ability for the latter as well.
* The _Update Index_ step, which can be affected by concurrency errors, is now retried before marking the job as _failed_.
* The _Update Index_ step can be independently retried from the _VIB Publish_ one.
* Less human intervention in failed, automatic releases.
None
NA
NA

[bitnami/*] Make cd-pipeline retryable

---

.github/workflows/ci-pipeline.yaml

We need to use the `BITNAMI_BOT_TOKEN` to enable the auto-merge feature for automated PRs, as the user that enables it is the one that appears as the one that merges the PR:
- Before https://github.com/bitnami/charts/pull/11307: https://github.com/bitnami/charts/pull/11342
- After  https://github.com/bitnami/charts/pull/11307: https://github.com/bitnami/charts/pull/11374
The user `github-actions` can't be the one that merges the PR's because tasks performed by `GITHUB_TOKEN` [won't trigger new actions.](https://docs.github.com/en/actions/using-workflows/triggering-a-workflow#triggering-a-workflow-from-a-workflow) It seems GH understands the merged commit is pushed to `master` by `GITHUB_TOKEN` and thus is not triggering the `CD Pipeline` …

[bitnami/*] Use bitnami-bot to manage auto-merge in automated PRs

---

.github/workflows/cd-pipeline.yaml
.vib/schema-registry/vib-publish.json
.vib/schema-registry/vib-verify.json
bitnami/schema-registry/.helmignore
bitnami/schema-registry/Chart.lock
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/templates/NOTES.txt
bitnami/schema-registry/templates/_helpers.tpl
bitnami/schema-registry/templates/configmap.yaml
bitnami/schema-registry/templates/external-kafka-secrets.yaml
bitnami/schema-registry/templates/extra-list.yaml
bitnami/schema-registry/templates/headless-service.yaml
bitnami/schema-registry/templates/hpa.yaml
bitnami/schema-registry/templates/ingress.yaml
bitnami/schema-registry/templates/log4j-configmap.yaml
bitnami/schema-registry/templates/pdb.yaml
bitnami/schema-registry/templates/service.yaml
bitnami/schema-registry/templates/serviceaccount.yaml
bitnami/schema-registry/templates/statefulset.yaml
bitnami/schema-registry/templates/tls-secret.yaml
bitnami/schema-registry/values.yaml

This PR moves the schema-registry chart to the bitnami/charts repository.
The following changes have been added:
- Bumped major version 4.x.x, updating Kafka subchart from version 12 to 18.
- Kafka and Zookeeper subchart values updated.
- Adds VIB files
- Adds `.helmignore`

[bitnami/schema-registry] Add schema-registry chart

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/hidden/statefulset.yaml
bitnami/mongodb/templates/replicaset/statefulset.yaml
bitnami/mongodb/templates/standalone/dep-sts.yaml

In mongodb-exporter 0.33 the http handler was changed to listen only in route `/metrics`, so any request to `/` will return a 404 code.
In this change we change the path for liveness and readiness probes in metrics containers.
None detected
- fixes #11213 
These are the changes in [mongodb-exporter 0.33](https://github.com/percona/mongodb_exporter/compare/v0.32.3...v0.33.0#diff-c722ac09a12b0798d4b56729c7f9c7236651f195ea1d3ee985db75543d5ce219R328)

[bitnami/mongodb] Change endpoint for metrics liveness and readiness probes

---

.github/workflows/cd-pipeline.yaml
.vib/fluentd/goss/goss.yaml
.vib/fluentd/vib-publish.json
.vib/fluentd/vib-verify.json
bitnami/fluentd/Chart.yaml
bitnami/fluentd/templates/forwarder-clusterrole.yaml
bitnami/fluentd/templates/forwarder-clusterrolebinding.yaml
bitnami/fluentd/templates/forwarder-psp.yaml

The main objective of this PR is to publish our Bitnami Fluentd Helm Chart using VMware Image Builder. In order to do that, several changes are included:
- Adapting the chart to use `common.names.fullname.namespace`, which allows deploying several releases under the same K8s cluster but in different namespaces.
**Benefits**
**Test results**
Tested in https://github.com/joancafom/charts/pull/60

[bitnami/fluentd] Add GOSS tests and publish using VIB

---

.github/workflows/.env
.github/workflows/sync-teams.yml

The request done to the GH API didn't add the per_page parameters and only 30 members were retrieved.
The workflow is executed once a day, that's why I run it locally and fix it for today.
All the Bitnami members are properly set.
None detected

[bitnami/*] Ensuring all developers are properly added to bitnami-team

---

bitnami/mariadb/Chart.yaml
bitnami/mariadb/templates/primary/statefulset.yaml
bitnami/mariadb/templates/secondary/statefulset.yaml

Signed-off-by: Stollin, Thomas <thomas.stollin@interhyp.de>
This change fixes a templating error caused by adding extraVolumeMounts to the mariadb metrics container when customPasswordFiles are used. This combination of configurations results in a missing ```volumeMounts``` key for the metrics container and dangling list entries. 
The problem was introduced with https://github.com/bitnami/charts/pull/11142. 
- fixes #

[bitnami/mariadb] fix missing volumeMounts key for metrics container

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/templates/configmap-env-vars.yaml
bitnami/keycloak/templates/networkpolicy.yaml
bitnami/keycloak/templates/secrets.yaml
bitnami/keycloak/templates/statefulset.yaml
bitnami/keycloak/values.yaml

Since Keycloak 17, there isn't any listener bound to port 9990, and the management password passed to the image isn't used. This PR removes all references to these obsoleted features.
See #11129
- Closes #11129

[bitnami/keycloak] remove Wildfly management port and secret key

---

.github/workflows/moving-cards.yml
.github/workflows/triage.yml

Bumping the action version after being merged my contribution and being released a [new version](https://github.com/pozil/auto-assign-issue/releases/tag/v1.9.0) of the action.
PRs will be assigned, so in the board will be shown the assignees.
None

[bitnami/*] Bumping the action version to assign PRs

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/bucketweb/deployment.yaml
bitnami/thanos/templates/compactor/deployment.yaml
bitnami/thanos/templates/receive/statefulset.yaml
bitnami/thanos/templates/ruler/statefulset.yaml
bitnami/thanos/templates/storegateway/statefulset-sharded.yaml
bitnami/thanos/templates/storegateway/statefulset.yaml

Signed-off-by: Diego Cavichiolli Carbone <dccarbone.app@gmail.com>
Fixing a typo in Thanos chart k8s annotation. It's not critical and does not affect the way the app works.
Making the variable name correct.
No limitations.
- fixes #11457

[bitnami/thanos] - Fix typo in k8s annotation

---

bitnami/rabbitmq/README.md

This adds documentation on a previously undocumented breaking change in the RabbitMQ chart version 7.0.0 - if persistence is enabled, the structure of the persistent volumes is changed under the default values - previously the RabbitMQ data was stored under `mnesia/` in the persistent volume but now it is stored at the root of the peristent volume and the previous `config/` and `schema/` directories are no longer used.  If using persistence it is desirable to know about this change and address it appropriately.
Anyone upgrading from a chart version below 7.0.0 to a newer one (7.0.0 or above) can read these notes and know to address this before they accidentally loose data currently in their RabitMQ cluster.
- Specific, bulletproof instructions for addressing this are not provided.  A link …

[bitnami/rabbitmq] Document persistent volume layout change in 7.0.0

---

bitnami/airflow/Chart.yaml
bitnami/airflow/templates/_git_helpers.tpl

Modified the behaviour of the volumes of dags and plugins so that git has the necessary permissions to be able to correctly access the content of the volumes.
Git won't have permission issues when accessing volumes.

[bitnami/airflow] Git permission error in Airflow Helm chart

---

.vib/airflow/cypress/cypress/support/commands.js
.vib/discourse/cypress/cypress/support/commands.js
.vib/dokuwiki/cypress/cypress/support/commands.js
.vib/ghost/cypress/cypress/support/commands.js
.vib/grafana/cypress/cypress/support/commands.js
.vib/harbor/cypress/cypress/support/commands.js
.vib/jenkins/cypress/cypress/support/commands.js
.vib/joomla/cypress/cypress/support/commands.js
.vib/keycloak/cypress/cypress/support/commands.js
.vib/magento/cypress/cypress/support/commands.js
.vib/matomo/cypress/cypress/support/commands.js
.vib/mediawiki/cypress/cypress/support/commands.js
.vib/minio/cypress/cypress/support/commands.js
.vib/odoo/cypress/cypress/support/commands.js
.vib/opencart/cypress/cypress/support/commands.js
.vib/owncloud/cypress/cypress/support/commands.js
.vib/phpmyadmin/cypress/cypress/support/commands.js
.vib/prestashop/cypress/cypress/support/commands.js
.vib/rabbitmq/cypress/cypress/support/commands.js
.vib/redmine/cypress/cypress/support/commands.js
.vib/solr/cypress/cypress/support/commands.js
.vib/spring-cloud-dataflow/cypress/cypress/support/commands.js
.vib/suitecrm/cypress/cypress/support/commands.js
.vib/thanos/bucketweb/cypress/cypress/support/commands.js
.vib/thanos/queryfrontend/cypress/cypress/support/commands.js
.vib/wordpress/cypress/cypress/support/commands.js

This PR unifies the delays used in Cypress for specific types of commands (click/type/etc) to a single duration across the catalog. Besides using the same interval for every asset, it also unifies the different delays (COMMAND_DELAY, TYPE_DELAY, etc.) into a single `COMMAND_DELAY` const. This further reduced the involved logic.
This duration is equal to the largest time interval used by any of our tested assets, which means the majority of our tests now have bigger command delays. Even though this will translate into a (slightly) slower test execution, we are gaining in test stability and readability.
Having said that, given the current effort to reduce the number of strictly necessary tests, the added delayed time will be negligible.
Better …

[bitnami/*] Unify Cypress' command delays

---

bitnami/etcd/Chart.yaml
bitnami/etcd/templates/cronjob.yaml

This put a new indentation level o cronjob's command when disasterRecovery and diagnosticMode are enabled and fixes #11636;
- fixes #11636

[binami/etcd] Fix command for cronjob when diagnostic and disaster recovery are enabled

---

bitnami/zookeeper/Chart.yaml
bitnami/zookeeper/templates/secrets.yaml

There was copy/paste error - the quorum password value was tried to be taken from client-auth secret.
Signed-off-by: Maciej Próchniak <mpr@touk.pl>
The user no longer gets:
` PASSWORDS ERROR: The secret "zookeeper-client-auth" does not contain the key "quorum-learner-password"` 
error after each helm upgrade.

[bitnami/zookeeper] Fix quorum secret generation

---

bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/templates/deployment.yaml

Fixes issue with MediaWiki HTTPS container port.
This issue was causing a block in our CI/CD pipeline, see #11619

[bitnami/mediawiki] Fix HTTPS container port

---

bitnami/wildfly/Chart.yaml
bitnami/wildfly/README.md
bitnami/wildfly/templates/deployment.yaml
bitnami/wildfly/values.yaml

This change enables the user to add a serviceAccount to the deployment
It is possible to connect your deployment to a k8s ServiceAccount object
- none
- none

[bitnami/wildfly]: add serviceAccountName property

---

bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/templates/external-kafka-secrets.yaml

```
"msg": "Failure when executing Helm command. Exited 1.\nstdout: \nstderr: Error: Failed to render chart: exit status 1: Error: template: schema-registry/templates/external-kafka-secrets.yaml:19:81: executing \"schema-registry/templates/external-kafka-secrets.yaml\" at <include \"commons.fullname\" .>: error calling include: template: no template \"commons.fullname\" associated with template
```
Wrong template name "commons.fullname" in external-kafka-secrets.yaml
Signed-off-by: Osmani Sánchez <osmanisanchez@gmail.com>

[bitnami/schema-registry] Wrong template name "commons.fullname"

---

bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md
bitnami/oauth2-proxy/templates/deployment.yaml
bitnami/oauth2-proxy/values.yaml

Signed-off-by: Alexander Evseev <a.evseev@bringo.com>
Add DNS parameters (dnsPolicy and dnsConfig) to the oauth2 deployment
Allows to configure DNS for ex. to avoid issues with ndots

[bitnami/oauth2-proxy] Add DNS parameters to the oauth2 deployment

---

bitnami/kubeapps/Chart.yaml

In a recent PR we added the `kubeVersion` constraint in the chart. However, some clouds are using suffixes to identify their k8s version. For instance, 1.21.1-gke. In semver, this is technically a prerelease, so it is less than 1.21.1, for instance. Adding ' -0` makes the trick. This PR is just updating this constraint to allow prereleases and therefore supporting k8s cluster version using suffixes.
The chart will work again in clouds using k8s version names with suffixes.
N/A
N/A
N/A

[bitnami/kubeapps] Allow prereleases in `kubeVersion`

---

bitnami/kubernetes-event-exporter/Chart.yaml
bitnami/kubernetes-event-exporter/README.md

The repo used in the past containing the source code (https://github.com/opsgenie/kubernetes-event-exporter) is not being maintained. At this moment, the source code can be found at https://github.com/resmoio/kubernetes-event-exporter.
We updated the URL in our internal track, test & release pipeline to reflect this change. In this PR, we are updating the README and some chart metadata.
- Fixes #11412

[bitnami/kubernetes-event-exporter] Replace upstream repo

---

bitnami/redis/README.md

Adds Redis Upgrading notes for version 17.x.x
- fixes #11657

[bitnami/redis] Add 17.x.x upgrading notes

---

bitnami/schema-registry/Chart.yaml

Bump the version of the schema-registry chart to 4.0.5 so that #11431 can make it into a build. The chart version had been bumped to 4.0.4 by both #11431 and #11664 in parallel, but the latter went in first. Git didn't see it as a conflict, but [the build for the former PR failed](https://github.com/bitnami/charts/actions/runs/2838925682) since 4.0.4 had already been built.
Produces a build of the schema-registry chart that supports the use of an external Kafka.
None known
Fixes #11630
None

[bitnami/schema-registry] Bump version to 4.0.5

---

bitnami/nginx-ingress-controller/Chart.yaml
bitnami/nginx-ingress-controller/templates/role.yaml

https://github.com/bitnami/charts/pull/11454 introduced changes for nginx ingress 1.3.x but hardcoded values that are actually configurable within the chart. this fixes that
You can specify your own electionID again, without the chart breaking

[bitnami/nginx-ingress-controller] fix name of electionID in RBAC

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/master/statefulset.yaml

Signed-off-by: wanggy <717338097@qq.com>
`Values.master.extraEnvVarsCM` and `Values.extraEnvVarsSecret` is repeat effective for master statefulset envFrom 
`Values.extraEnvVarsCM` and `Values.master.extraEnvVarsSecret` is not effective for master statefulset envFrom
replace one of `Values.master.extraEnvVarsCM` with `Values.extraEnvVarsCM` on master statefulset
replace one of `Values.extraEnvVarsSecret`  with `Values.master.extraEnvVarsSecret` on master statefulset
`Values.extraEnvVarsCM` and `Values.master.extraEnvVarsSecret`  effect for master statefulset
none
none

[bitnami/elasticsearch]fix master statefulset envFrom

---

bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/templates/alertmanager/secrets.yaml

non consistent nindent on alertmanager secret on kube-prometheus chart
labels were indented to 4 spaces
commonlabels were indented to 10 spaces
this is causing error in helm templating : 
```
helm.go:88: [debug] error converting YAML to JSON: yaml: line 12: mapping values are not allowed in this context
YAML parse error on kube-prometheus/templates/alertmanager/secrets.yaml
```
=> commonLabels are unusable in this chart
CommonLabels will be usable in kube-prometheus chart
None
NA
NA

[bitnami/kube-prometheus] Fix - non consistent nindent on alertmanager secret

---

bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/README.md
bitnami/kubeapps/values.yaml

Some time ago we disabled the persistence of the cached data for the PostgreSQL database, meaning no PVC are created by default. This simply implies that cached repos in Kubeapps will get erased when deleting kubeapps.
However, this behavior wasn't replicated for the Flux plugin, which uses Redis. This PR is to disable by default the creation of PVCs for the Flux cache.
No persistent cache by default + allowing users to enable this functionality if they want via chart.
N/A
N/A
Squeezing some fixes in the usage of the Redis trademark.
Requiring @gfichtenholt's before merging.

[bitnami/kubeapps] Disable redis persistence by default

---

bitnami/zookeeper/Chart.yaml
bitnami/zookeeper/templates/statefulset.yaml

quorum auth value not set properly.
Signed-off-by: sachintandon-nexla <93154405+sachintandon-nexla@users.noreply.github.com>
statefulset quorum auth value not set properly
The change was made back on :
https://github.com/bitnami/charts/commit/e4b159ae75f534bf3e951085bd8e2385a26053ca#diff-0ba4ee4bc548e5cbcbb20a833af41af7a75c8fcdd77e63cb7f8a4db2f7007c38

[bitnami/zookeeper] Statefulset quorum auth value not set properly

---

bitnami/common/Chart.yaml
bitnami/common/templates/_images.tpl

This PR adds support for image digest apart from the existing image tag. Changes in the different Helm charts will look like this one in bitnami/etcd: https://github.com/bitnami/charts/pull/11798
```yaml
##
image:    
```
```console
```
In the same way, when the `image.digest` is empty (default value), this …

[bitnami/common] Add support for image digest apart from tag

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/README.md
bitnami/elasticsearch/templates/tls-secret.yaml

Minor fix in the generated Elasticsearch TLS certs, specifically one of the alternative DNS names.
Before this change, the name would be generated like this: `DNS:elasticsearch.%!s(MISSING).svc.%!s(MISSING)`.
Those fixed alt names are now usable.
Can't think of any.
I haven't created an issue for this, since it is a very simple fix. If preferred I can also file GitHub issue and link it here.
One additional (super minor) fix in the README.

[bitnami/elasticsearch] Fix alt names in generated TLS certs

---

bitnami/etcd/Chart.lock
bitnami/etcd/Chart.yaml
bitnami/etcd/README.md
bitnami/etcd/values.yaml

From now on it will be possible to set an `image.digest` instead of `image.tag` to pull the container image. Please note it is needed to release a bitnami/common version with those changes (see https://github.com/bitnami/charts/pull/11797).
```yaml
##
image:    
```
```console
``` …

[bitnami/etcd] Add support for image digest apart from tag

---

.vib/mysql/goss/goss.yaml
.vib/mysql/goss/vars.yaml
.vib/mysql/vib-publish.json
.vib/mysql/vib-verify.json

[bitnami/mysql] Revisit tests

---

bitnami/minio/Chart.yaml
bitnami/minio/templates/provisioning-job.yaml

Apply the resource limits to minio's init-container.

[bitnami/minio] Apply the resource limits to minio's init-container

---

bitnami/nats/Chart.yaml
bitnami/nats/templates/networkpolicy.yaml

Signed-off-by: rui.guo <rui.guo@bytedance.com>
Fix cluster port in nats networkpolicy resource
Fixes https://github.com/bitnami/charts/issues/11749

[bitnami/nats] fix networkpolicy

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/ingest/statefulset.yaml

Signed-off-by: wanggy <717338097@qq.com>
Values.ingest.extraEnvVarsCM and Values.extraEnvVarsSecret is repeat effective for ingest statefulset envFrom
Values.extraEnvVarsCM and Values.ingest.extraEnvVarsSecret is not effective for ingest statefulset envFrom
replace one of Values.ingest.extraEnvVarsCM with Values.extraEnvVarsCM on ingest statefulset
replace one of Values.extraEnvVarsSecret with Values.ingest.extraEnvVarsSecret on ingest statefulset
Values.extraEnvVarsCM and Values.ingest.extraEnvVarsSecret effect for ingest statefulset

fix elasticsearch ingest envFrom

---

bitnami/sealed-secrets/Chart.lock
bitnami/sealed-secrets/Chart.yaml
bitnami/sealed-secrets/README.md
bitnami/sealed-secrets/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/sealed-secrets] Add support for image digest apart from tag

---

bitnami/tensorflow-resnet/Chart.lock
bitnami/tensorflow-resnet/Chart.yaml
bitnami/tensorflow-resnet/README.md
bitnami/tensorflow-resnet/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/tensorflow-resnet] Add support for image digest apart from tag

---

bitnami/sonarqube/Chart.lock
bitnami/sonarqube/Chart.yaml
bitnami/sonarqube/README.md
bitnami/sonarqube/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/sonarqube] Add support for image digest apart from tag

---

bitnami/wavefront-hpa-adapter/Chart.lock
bitnami/wavefront-hpa-adapter/Chart.yaml
bitnami/wavefront-hpa-adapter/README.md
bitnami/wavefront-hpa-adapter/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/wavefront-hpa-adapter] Add support for image digest apart from tag

---

bitnami/spark/Chart.lock
bitnami/spark/Chart.yaml
bitnami/spark/README.md
bitnami/spark/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/spark] Add support for image digest apart from tag

---

bitnami/wildfly/Chart.lock
bitnami/wildfly/Chart.yaml
bitnami/wildfly/README.md
bitnami/wildfly/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/wildfly] Add support for image digest apart from tag

---

bitnami/thanos/Chart.lock
bitnami/thanos/Chart.yaml
bitnami/thanos/README.md
bitnami/thanos/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/thanos] Add support for image digest apart from tag

---

bitnami/phpbb/Chart.lock
bitnami/phpbb/Chart.yaml
bitnami/phpbb/README.md
bitnami/phpbb/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/phpbb] Add support for image digest apart from tag

---

bitnami/pinniped/Chart.lock
bitnami/pinniped/Chart.yaml
bitnami/pinniped/README.md
bitnami/pinniped/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/pinniped] Add support for image digest apart from tag

---

bitnami/redmine/Chart.lock
bitnami/redmine/Chart.yaml
bitnami/redmine/README.md
bitnami/redmine/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/redmine] Add support for image digest apart from tag

---

bitnami/nats/Chart.lock
bitnami/nats/Chart.yaml
bitnami/nats/README.md
bitnami/nats/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/nats] Add support for image digest apart from tag

---

bitnami/memcached/Chart.lock
bitnami/memcached/Chart.yaml
bitnami/memcached/README.md
bitnami/memcached/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/memcached] Add support for image digest apart from tag

---

bitnami/haproxy/Chart.lock
bitnami/haproxy/Chart.yaml
bitnami/haproxy/README.md
bitnami/haproxy/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/haproxy] Add support for image digest apart from tag

---

bitnami/haproxy-intel/Chart.lock
bitnami/haproxy-intel/Chart.yaml
bitnami/haproxy-intel/README.md
bitnami/haproxy-intel/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/haproxy-intel] Add support for image digest apart from tag

---

bitnami/joomla/Chart.lock
bitnami/joomla/Chart.yaml
bitnami/joomla/README.md
bitnami/joomla/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/joomla] Add support for image digest apart from tag

---

bitnami/ejbca/Chart.lock
bitnami/ejbca/Chart.yaml
bitnami/ejbca/README.md
bitnami/ejbca/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/ejbca] Add support for image digest apart from tag

---

bitnami/cert-manager/Chart.lock
bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/README.md
bitnami/cert-manager/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/cert-manager] Add support for image digest apart from tag

---

bitnami/grafana-loki/Chart.lock
bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/README.md
bitnami/grafana-loki/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/grafana-loki] Add support for image digest apart from tag

---

bitnami/redis/Chart.lock
bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/redis] Add support for image digest apart from tag

---

bitnami/kiam/Chart.lock
bitnami/kiam/Chart.yaml
bitnami/kiam/README.md
bitnami/kiam/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/kiam] Add support for image digest apart from tag

---

bitnami/nginx-ingress-controller/Chart.lock
bitnami/nginx-ingress-controller/Chart.yaml
bitnami/nginx-ingress-controller/README.md
bitnami/nginx-ingress-controller/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/nginx-ingress-controller] Add support for image digest apart from tag

---

bitnami/nginx-intel/Chart.lock
bitnami/nginx-intel/Chart.yaml
bitnami/nginx-intel/README.md
bitnami/nginx-intel/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/nginx-intel] Add support for image digest apart from tag

---

bitnami/kubernetes-event-exporter/Chart.lock
bitnami/kubernetes-event-exporter/Chart.yaml
bitnami/kubernetes-event-exporter/README.md
bitnami/kubernetes-event-exporter/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/kubernetes-event-exporter] Add support for image digest apart from tag

---

bitnami/nginx/Chart.lock
bitnami/nginx/Chart.yaml
bitnami/nginx/README.md
bitnami/nginx/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/nginx] Add support for image digest apart from tag

---

bitnami/mongodb/Chart.lock
bitnami/mongodb/Chart.yaml
bitnami/mongodb/README.md
bitnami/mongodb/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/mongodb] Add support for image digest apart from tag

---

bitnami/grafana/Chart.lock
bitnami/grafana/Chart.yaml
bitnami/grafana/README.md
bitnami/grafana/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/grafana] Add support for image digest apart from tag

---

bitnami/jenkins/Chart.lock
bitnami/jenkins/Chart.yaml
bitnami/jenkins/README.md
bitnami/jenkins/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/jenkins] Add support for image digest apart from tag

---

bitnami/dokuwiki/Chart.lock
bitnami/dokuwiki/Chart.yaml
bitnami/dokuwiki/README.md
bitnami/dokuwiki/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/dokuwiki] Add support for image digest apart from tag

---

bitnami/mariadb/Chart.lock
bitnami/mariadb/Chart.yaml
bitnami/mariadb/README.md
bitnami/mariadb/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/mariadb] Add support for image digest apart from tag

---

bitnami/cassandra/Chart.lock
bitnami/cassandra/Chart.yaml
bitnami/cassandra/README.md
bitnami/cassandra/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/cassandra] Add support for image digest apart from tag

---

bitnami/kafka/Chart.lock
bitnami/kafka/Chart.yaml
bitnami/kafka/README.md
bitnami/kafka/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/kafka] Add support for image digest apart from tag

---

bitnami/minio/Chart.lock
bitnami/minio/Chart.yaml
bitnami/minio/README.md
bitnami/minio/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/minio] Add support for image digest apart from tag

---

bitnami/mysql/Chart.lock
bitnami/mysql/Chart.yaml
bitnami/mysql/README.md
bitnami/mysql/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/mysql] Add support for image digest apart from tag

---

bitnami/rabbitmq/Chart.lock
bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/README.md
bitnami/rabbitmq/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/rabbitmq] Add support for image digest apart from tag

---

bitnami/zookeeper/Chart.lock
bitnami/zookeeper/Chart.yaml
bitnami/zookeeper/README.md
bitnami/zookeeper/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/zookeeper] Add support for image digest apart from tag

---

bitnami/redis-cluster/Chart.lock
bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/README.md
bitnami/redis-cluster/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/redis-cluster] Add support for image digest apart from tag

---

bitnami/argo-cd/Chart.lock
bitnami/argo-cd/Chart.yaml
bitnami/argo-cd/README.md
bitnami/argo-cd/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/argo-cd] Add support for image digest apart from tag

---

bitnami/wordpress/Chart.lock
bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md
bitnami/wordpress/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/wordpress] Add support for image digest apart from tag

---

bitnami/concourse/Chart.lock
bitnami/concourse/Chart.yaml
bitnami/concourse/README.md
bitnami/concourse/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/concourse] Add support for image digest apart from tag

---

bitnami/airflow/Chart.lock
bitnami/airflow/Chart.yaml
bitnami/airflow/README.md
bitnami/airflow/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/airflow] Add support for image digest apart from tag

---

bitnami/ghost/Chart.lock
bitnami/ghost/Chart.yaml
bitnami/ghost/README.md
bitnami/ghost/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/ghost] Add support for image digest apart from tag

---

bitnami/schema-registry/Chart.lock
bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/README.md
bitnami/schema-registry/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/schema-registry] Add support for image digest apart from tag

---

bitnami/wordpress-intel/Chart.lock
bitnami/wordpress-intel/Chart.yaml
bitnami/wordpress-intel/README.md
bitnami/wordpress-intel/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/wordpress-intel] Add support for image digest apart from tag

---

bitnami/oauth2-proxy/Chart.lock
bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md
bitnami/oauth2-proxy/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/oauth2-proxy] Add support for image digest apart from tag

---

bitnami/opencart/Chart.lock
bitnami/opencart/Chart.yaml
bitnami/opencart/README.md
bitnami/opencart/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/opencart] Add support for image digest apart from tag

---

bitnami/osclass/Chart.lock
bitnami/osclass/Chart.yaml
bitnami/osclass/README.md
bitnami/osclass/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/osclass] Add support for image digest apart from tag

---

bitnami/owncloud/Chart.lock
bitnami/owncloud/Chart.yaml
bitnami/owncloud/README.md
bitnami/owncloud/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/owncloud] Add support for image digest apart from tag

---

bitnami/matomo/Chart.lock
bitnami/matomo/Chart.yaml
bitnami/matomo/README.md
bitnami/matomo/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/matomo] Add support for image digest apart from tag

---

bitnami/mediawiki/Chart.lock
bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/README.md
bitnami/mediawiki/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/mediawiki] Add support for image digest apart from tag

---

bitnami/mxnet/Chart.lock
bitnami/mxnet/Chart.yaml
bitnami/mxnet/README.md
bitnami/mxnet/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/mxnet] Add support for image digest apart from tag

---

bitnami/keycloak/Chart.lock
bitnami/keycloak/Chart.yaml
bitnami/keycloak/README.md
bitnami/keycloak/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/keycloak] Add support for image digest apart from tag

---

bitnami/kong/Chart.lock
bitnami/kong/Chart.yaml
bitnami/kong/README.md
bitnami/kong/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/kong] Add support for image digest apart from tag

---

bitnami/kubeapps/Chart.lock
bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/README.md
bitnami/kubeapps/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/kubeapps] Add support for image digest apart from tag

---

bitnami/jupyterhub/Chart.lock
bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/README.md
bitnami/jupyterhub/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/jupyterhub] Add support for image digest apart from tag

---

bitnami/aspnet-core/Chart.lock
bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/README.md
bitnami/aspnet-core/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/aspnet-core] Add support for image digest apart from tag

---

bitnami/drupal/Chart.lock
bitnami/drupal/Chart.yaml
bitnami/drupal/README.md
bitnami/drupal/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/drupal] Add support for image digest apart from tag

---

bitnami/contour/Chart.lock
bitnami/contour/Chart.yaml
bitnami/contour/README.md
bitnami/contour/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/contour] Add support for image digest apart from tag

---

bitnami/apache/Chart.lock
bitnami/apache/Chart.yaml
bitnami/apache/README.md
bitnami/apache/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/apache] Add support for image digest apart from tag

---

bitnami/suitecrm/Chart.lock
bitnami/suitecrm/Chart.yaml
bitnami/suitecrm/README.md
bitnami/suitecrm/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/suitecrm] Add support for image digest apart from tag

---

bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml
bitnami/discourse/README.md
bitnami/discourse/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/discourse] Add support for image digest apart from tag

---

bitnami/jasperreports/Chart.lock
bitnami/jasperreports/Chart.yaml
bitnami/jasperreports/README.md
bitnami/jasperreports/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/jasperreports] Add support for image digest apart from tag

---

bitnami/grafana-tempo/Chart.lock
bitnami/grafana-tempo/Chart.yaml
bitnami/grafana-tempo/README.md
bitnami/grafana-tempo/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/grafana-tempo] Add support for image digest apart from tag

---

bitnami/odoo/Chart.lock
bitnami/odoo/Chart.yaml
bitnami/odoo/README.md
bitnami/odoo/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/odoo] Add support for image digest apart from tag

---

bitnami/prestashop/Chart.lock
bitnami/prestashop/Chart.yaml
bitnami/prestashop/README.md
bitnami/prestashop/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/prestashop] Add support for image digest apart from tag

---

bitnami/magento/Chart.lock
bitnami/magento/Chart.yaml
bitnami/magento/README.md
bitnami/magento/values.yaml

```yaml
##
image:    
```
```console
``` …

[bitnami/magento] Add support for image digest apart from tag

---

.github/workflows/comments.yml
.github/workflows/move-closed-issues.yml
.github/workflows/stale.yml
.github/workflows/triage.yml

Changes related to the stale bot and its behaviour. The action was being raised by using the _GITHUB_TOKEN_ than doesn't raise any event. After changing into the _BITNAMI_BOT_TOKEN_, will raise events as usual and removing the if condition in the `move-closed-issues.yml`, the issue will be moved directly into the solved column **without removing the stale label** to know was moved there because of the stale bot.
On the other hand, adding the possibility to assign internal PRs to the support team without doing triage (it's not needed).
Finally, adding the step to remove the _stale_ label when a comment is done to ensure the stale bot doesn't archive it as happened in https://github.com/bitnami/charts/issues/11404.
* Ensuring closed issues by the stale bot are properly moved into the Solved …

[bitnami/*] Fixing stale behaviour and assignation to internal contributions

---

.github/workflows/cd-pipeline.yaml
.vib/influxdb/cypress/cypress.json
.vib/influxdb/cypress/cypress/fixtures/buckets.json
.vib/influxdb/cypress/cypress/fixtures/dashboards/health_tracker.json
.vib/influxdb/cypress/cypress/fixtures/sample_data/glucose_levels.txt
.vib/influxdb/cypress/cypress/integration/influxdb_spec.js
.vib/influxdb/cypress/cypress/support/commands.js
.vib/influxdb/cypress/cypress/support/index.js
.vib/influxdb/cypress/cypress/support/utils.js
.vib/influxdb/goss/goss.yaml
.vib/influxdb/goss/vars.yaml
.vib/influxdb/vib-publish.json
.vib/influxdb/vib-verify.json

The main objective of this PR is to publish our Bitnami InfluxDB Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
Tested in https://github.com/joancafom/charts/pull/69

[bitnami/influxdb] Add tests and publish using VIB

---

bitnami/common/Chart.yaml
bitnami/common/templates/_images.tpl

```console
$ cat values.yaml
image:
repository: bitnami/rabbitmq
tag: 3.10.7-debian-11-r4
digest: ""
$ helm template . | grep 'image:'
image: docker.io/bitnami/rabbitmq:3.10.7-debian-11-r4
```
```console
$ cat values.yaml
image:
repository: bitnami/rabbitmq
tag: 3.10.7-debian-11-r4
digest: "sha256:aaa"
$ helm template . | grep 'image:'
image: docker.io/bitnami/rabbitmq@sha256:aaa
```
```console
$ cat values.yaml
image:
repository: bitnami/rabbitmq
tag: 3.10.7-debian-11-r4
$ helm template . | grep 'image:'
image: docker.io/bitnami/rabbitmq@<nil>
```
```console
$ cat values.yaml
image:
repository: bitnami/rabbitmq
tag: 3.10.7-debian-11-r4
digest: ""
$ helm template . | grep 'image:'
image: …
```

[bitnami/common] Digest/Tag new approach backward compatible

---

bitnami/nats/Chart.lock
bitnami/nats/Chart.yaml

[bitnami/nats] Update Chart.lock

---

bitnami/nginx-ingress-controller/Chart.lock
bitnami/nginx-ingress-controller/Chart.yaml

[bitnami/nginx-ingress-controller] Update Chart.lock

---

bitnami/nginx-intel/Chart.lock
bitnami/nginx-intel/Chart.yaml

[bitnami/nginx-intel] Update Chart.lock

---

bitnami/nginx/Chart.lock
bitnami/nginx/Chart.yaml

[bitnami/nginx] Update Chart.lock

---

bitnami/node-exporter/Chart.lock
bitnami/node-exporter/Chart.yaml

[bitnami/node-exporter] Update Chart.lock

---

bitnami/rabbitmq-cluster-operator/Chart.lock
bitnami/rabbitmq-cluster-operator/Chart.yaml

[bitnami/rabbitmq-cluster-operator] Update Chart.lock

---

bitnami/redis-cluster/Chart.lock
bitnami/redis-cluster/Chart.yaml

[bitnami/redis-cluster] Update Chart.lock

---

bitnami/tensorflow-resnet/Chart.lock
bitnami/tensorflow-resnet/Chart.yaml

[bitnami/tensorflow-resnet] Update Chart.lock

---

bitnami/wavefront-hpa-adapter/Chart.lock
bitnami/wavefront-hpa-adapter/Chart.yaml

[bitnami/wavefront-hpa-adapter] Update Chart.lock

---

bitnami/haproxy/Chart.lock
bitnami/haproxy/Chart.yaml

[bitnami/haproxy] Update Chart.lock

---

bitnami/geode/Chart.lock
bitnami/geode/Chart.yaml

[bitnami/geode] Update Chart.lock

---

bitnami/kube-state-metrics/Chart.lock
bitnami/kube-state-metrics/Chart.yaml

[bitnami/kube-state-metrics] Update Chart.lock

---

bitnami/kubernetes-event-exporter/Chart.lock
bitnami/kubernetes-event-exporter/Chart.yaml

[bitnami/kubernetes-event-exporter] Update Chart.lock

---

bitnami/mariadb-galera/Chart.lock
bitnami/mariadb-galera/Chart.yaml

[bitnami/mariadb-galera] Update Chart.lock

---

bitnami/mariadb/Chart.lock
bitnami/mariadb/Chart.yaml

[bitnami/mariadb] Update Chart.lock

---

bitnami/memcached/Chart.lock
bitnami/memcached/Chart.yaml

[bitnami/memcached] Update Chart.lock

---

bitnami/mongodb-sharded/Chart.lock
bitnami/mongodb-sharded/Chart.yaml

[bitnami/mongodb-sharded] Update Chart.lock

---

bitnami/cassandra/Chart.lock
bitnami/cassandra/Chart.yaml

[bitnami/cassandra] Update Chart.lock

---

bitnami/external-dns/Chart.lock
bitnami/external-dns/Chart.yaml

[bitnami/external-dns] Update Chart.lock

---

bitnami/grafana-loki/Chart.lock
bitnami/grafana-loki/Chart.yaml

[bitnami/grafana-loki] Update Chart.lock

---

bitnami/wordpress/Chart.lock
bitnami/wordpress/Chart.yaml

[bitnami/wordpress] Update Chart.lock

---

bitnami/concourse/Chart.lock
bitnami/concourse/Chart.yaml

[bitnami/concourse] Update Chart.lock

---

bitnami/discourse/Chart.lock
bitnami/discourse/Chart.yaml

[bitnami/discourse] Update Chart.lock

---

bitnami/haproxy-intel/Chart.lock
bitnami/haproxy-intel/Chart.yaml

[bitnami/haproxy-intel] Update Chart.lock

---

bitnami/jupyterhub/Chart.lock
bitnami/jupyterhub/Chart.yaml

[bitnami/jupyterhub] Update Chart.lock

---

bitnami/kafka/Chart.lock
bitnami/kafka/Chart.yaml

[bitnami/kafka] Update Chart.lock

---

bitnami/oauth2-proxy/Chart.lock
bitnami/oauth2-proxy/Chart.yaml

[bitnami/oauth2-proxy] Update Chart.lock

---

bitnami/spring-cloud-dataflow/Chart.lock
bitnami/spring-cloud-dataflow/Chart.yaml

[bitnami/spring-cloud-dataflow] Update Chart.lock

---

bitnami/wavefront-prometheus-storage-adapter/Chart.lock
bitnami/wavefront-prometheus-storage-adapter/Chart.yaml

[bitnami/wavefront-prometheus-storage-adapter] Update Chart.lock

---

.vib/memcached/vib-publish.json
.vib/memcached/vib-verify.json

Change memcached tests default container port from 11211 to 11212
Tested in https://github.com/migruiz4/charts/pull/3

[bitnami/memcached] Change memcached containerPort in tests

---

bitnami/argo-workflows/Chart.yaml

#11975 Follow up.
After merging the changes from #11994 into #11975, the changes were finally merge into master accidentally without  a version bump.
Force a new release (2.4.2) with the changes from #11975
None

[bitnami/argo-workflows] #11975 Follow up

---

bitnami/apache/Chart.yaml
bitnami/apache/templates/deployment.yaml

This change fixes the Chart's containerPort values configuration in the values.yaml.
The Goss and Cypress tests are being added in this [PR](https://github.com/bitnami/charts/pull/11801)

[bitnami/apache] Allow the charts containerPorts to be configured

---

.github/workflows/cd-pipeline.yaml
.vib/haproxy/cypress/cypress.json
.vib/haproxy/cypress/cypress/integration/haproxy_spec.js
.vib/haproxy/goss/goss.yaml
.vib/haproxy/goss/vars.yaml
.vib/haproxy/vib-publish.json
.vib/haproxy/vib-verify.json

The main objective of this PR is to publish our Bitnami HAProxy Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
Tested in https://github.com/joancafom/charts/pull/71

[bitnami/haproxy] Add tests and publish using VIB

---

.github/workflows/cd-pipeline.yaml
.vib/etcd/goss/goss.yaml
.vib/etcd/goss/vars.yaml
.vib/etcd/vib-publish.json
.vib/etcd/vib-verify.json

The main objective of this PR is to publish our Bitnami Cassandra Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
Tested in https://github.com/FraPazGal/charts/pull/83

[bitnami/etcd] Add Helm Chart tests

---

.vib/apache/vib-publish.json
.vib/apache/vib-verify.json

This will change the runtime_parameters for the Apache chart VIB test to use non default values
Successful test run: https://github.com/mdhont/charts/runs/8022860972

Change containerPorts runtime_parameters for Apache tests

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/common-scripts-cm.yaml

Instead of just checking the presence of the 'true' value anywhere in the probes command result, after this fix the 'true' value must to be at the end.
Even if the connection contains parameters with 'true' value, the probe will failed when not primary/secondary are UP.
None
- fixes #11607
You can verify with a mongodb with tls enabled:
**Before**:
```bash
$ mongosh  $TLS_OPTIONS --port $MONGODB_PORT_NUMBER --eval 'db.hello().isWritablePrimary || db.hello().secondary' | grep "true"
Connecting to:          mongodb://127.0.0.1:27017/?directConnection=true&serverSelectionTimeoutMS=2000&tls=true&tlsCertificateKeyFile=%2Fcerts%2Fmongodb.pem&tlsCAFile=%2Fcerts%2Fmongodb-ca-cert&appName=mongosh+1.5.1
true
```
=> when the status is 'false' the grep -q exit with 0 due to the first line match …

[bitnami/mongodb] Fix probes when url connection contains 'true'

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/scripts-configmap.yaml

fix: prevents incorrect master host to be written to sentinel.conf
This should prevent that a wrong monitor config for redis master host is written to sentinel.conf, but instead fail to start with incorrect configuration.
So happened in many cases described by #9296. This error occurred when `get_sentinel_master_info` could not get a correct tuple of redis master host and port and thus the variables `REDIS_MASTER_HOST` and `REDIS_MASTER_PORT_NUMBER` did not have correct values.
The `start-sentinel.sh` script is exited with non-zero code when this error occurs. This may lead to `CrashLoopBackOff` states.
- fixes #9296
- fixes #11081
- possibly fixes #7283 and others

[bitnami/redis] prevents incorrect master host to be written to sentinel.conf

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/statefulset.yaml

In RabbitMQ helm chart fix init script provisioning via configmap or secret
Bug  (#12161) fixed
n/a
- fixes #12161 
n/a

[bitnami/rabbitmq] Fixing init scripts via configmap/secret (#12161)

---

bitnami/oauth2-proxy/Chart.yaml
bitnami/oauth2-proxy/README.md
bitnami/oauth2-proxy/values.yaml

This PR fixes the Oauth2 Proxy default values for Pod Disruption Budget since both `pdb.minAvailable` & `pdb.maxUnavailable` are set.
Users that enable Pod Disruption Budget creation won't find the error below:
```
The PodDisruptionBudget "oauth2-proxy" is invalid: spec: Invalid value: policy.PodDisruptionBudgetSpec{MinAvailable:(*intstr.IntOrString)(0xc01ef241a0), Selector:(*v1.LabelSelector)(0xc01ef241c0), MaxUnavailable:(*intstr.IntOrString)(0xc01ef24180)}: minAvailable and maxUnavailable cannot be both set
```
None
N/A
N/A

[bitnami/oauth2-proxy] Fix PDB default values

---

bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/templates/prometheus/prometheus.yaml

Fix two errors while trying to create `Prometheus` resource using default values in kuberneres 1.19.
Kubernetes 1.19 supported 
None expected.

[bitnami/kube-prometheus] Fix Prometheus' storage annotations and initContainers for kubernetes 1.19

---

bitnami/nginx/README.md

Signed-off-by: ncouse
There is a typo in the README for the `nginx` chart.
The capitalisation for `staticSiteConfigmap` in one case is incorrect.
Fix reference to `staticSiteConfigmap` in README.md
Someone else, like me, doesn't waste time using the wrong key value :)

[bitnami/nginx] Fix reference to staticSiteConfigmap in README.md

---

bitnami/nginx-intel/README.md

Copied from https://github.com/bitnami/charts/pull/12212
There is a typo in the README for the `nginx-intel` chart.
The capitalization for `staticSiteConfigmap` in one case is incorrect.
Fix reference to `staticSiteConfigmap` in README.md

[bitnami/nginx-intel] Fix reference to staticSiteConfigmap in README.md

---

bitnami/pinniped/Chart.yaml
bitnami/pinniped/README.md
bitnami/pinniped/templates/concierge/deployment.yaml
bitnami/pinniped/values.yaml

This PR enables deployment of Pinniped on setups requiring host network mode e.g. An EKS cluster using a custom CNI plugin like Cilium in overlay network mode.
* Without `hostNetwork: true` Pinniped will not be able to talk to the EKS control plane with a custom CNI in overlay network mode.
* `dnsPolicy: "ClusterFirstWithHostNet"` might be needed if the cluster relies on a in-cluster DNS service that is not reachable by the nodes directly.
* It will be easier to configure the `aggregatedAPIServerPort` and `impersonationProxyServerPort` in the concierge `configMap` if needed without having to replicate the whole config file in Helm values.
If you somehow hacked the changes yourself they might clash with the Helm Chart although the custom implementation will most likely overwrite this …

[bitnami/pinniped] add support for hostNetwork

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/README.md
bitnami/cassandra/templates/statefulset.yaml
bitnami/cassandra/values.yaml

Signed-off-by: Jan Mederer <jan@mederer.it>
The Metrics Container can now mount a Volume like the cassandra container.
So you can configure the config.yaml of the metrics container with a ConfigMaps for example. 
And also some old stuff is remove the ENVs from the metrics Container. Those were not used by the default Bitnami Image.
You can use the Bitnami Metrics Container with hostNetwork: true

[bitnami/cassandra] metrics Container - extraVolumeMounts option added

---

bitnami/etcd/Chart.yaml
bitnami/etcd/templates/_helpers.tpl
bitnami/etcd/templates/snapshot-pvc.yaml

Signed-off-by: Jayson Reis <santosdosreis@gmail.com>
If you have enabled disaster recovery, pvcs are created with nfs but, if you run an upgrade to try and restore from a specific file, the template removes the pvc definition, and it gets garbage collected by helm thus making the previously attached pvc invalid.
You can use helm upgrade to start from a snapshot
I cannot foresee one
- maybe helps #11697

[bitnami/etcd] Fix pvc deletion when trying to restore from snapshot

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/README.md
bitnami/wordpress/values.yaml

This PR makes the WordPress container compatible with the Kubernetes 1.25 `restricted` Pod Security Standard.
https://kubernetes.io/docs/concepts/security/pod-security-standards/
- fixes #

[bitnami/wordpress] feat: :sparkles: Make WordPress container run in restricted Pod Security Standard

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/NOTES.txt
bitnami/rabbitmq/templates/validation.yaml

It will allow failing early with a human readable errors like
```bash
$ helm template --set memoryHighWatermark.enabled=true .
Error: execution error at (rabbitmq/templates/statefulset.yaml:35:28):
VALUES VALIDATION:
rabbitmq: memoryHighWatermark
You enabled configuring memory high watermark using a relative limit. However,
no memory limits were defined at POD level. Define your POD limits as shown below:
$ helm install release-name bitnami/rabbitmq \
--set memoryHighWatermark.enabled=true \
--set memoryHighWatermark.type="relative" \
--set memoryHighWatermark.value="0.4" \
--set resources.limits.memory="2Gi"
Altenatively, user an absolute value for the memory memory high watermark :
$ helm install release-name bitnami/rabbitmq \
--set memoryHighWatermark.enabled=true \
--set …
```

[bitnami/rabbitmq] Improve error handling message when memoryHighWatermark.enabled=true

---

bitnami/grafana-operator/Chart.yaml
bitnami/grafana-operator/crds/grafanadashboards.integreatly.org.yaml
bitnami/grafana-operator/crds/grafanadatasources.integreatly.org.yaml
bitnami/grafana-operator/crds/grafananotificationchannels.integreatly.org.yaml
bitnami/grafana-operator/crds/grafanas.integreatly.org.yaml

Signed-off-by: Jamie van Brunschot <jamievbrunschot@gmail.com>
As with the latest version bump the CRDs were not updated to the latest (4.6.0) version.

[bitnami/grafana-operator] update crds to 4.6.0

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/prometheusrule.yaml

Signed-off-by: Max Nitze <max.nitze@gmx.de>
When using multiple groups in the PrometheusRule, that was introduced in #12268, the top level key `groups` was added multiple times to the resource.
_Bugfix, see description._
no limitations known

[bitnami/keycloak] Do not duplicate groups key in PrometheusRule

---

bitnami/rabbitmq/Chart.yaml
bitnami/rabbitmq/templates/statefulset.yaml

Without this change, in order to use a custom probe, the user has to specify the probe parameters, and also must specify for the original

[bitnami/rabbitmq] Use custom probes if given

---

bitnami/rabbitmq/Chart.yaml

The Helm chart version was bumped to the same number (`1.3.3`) in two different PRs:
- https://github.com/bitnami/charts/pull/12227
- https://github.com/bitnami/charts/pull/12303
Once merged, GitHub doesn't detect any conflict so the commit from the second one doesn't contain the chart version bump, see https://github.com/bitnami/charts/commit/99e9d0c93ea11c2d70d90f1fb2f50860dfd70d0c
The aim of this PR is to bump the chart version in a new patch (`1.3.4`) so there is a new chart released including changes from both PRs

[bitnami/rabbitmq] Bump chart version

---

bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/templates/tls-secrets.yaml

This change detects (using the bitnami common chart) the
cert-manager annotation(s) to prevent creation of the self-signed cert
and helps users follow the deprecation guidelines of using their own
annotations instead of relying on `ingress.certManager`.
The deprecated behavior is retained if `ingress.certManager` is
specified.
`ingress.certManager` is deprecated, yet ~~required to use cert-manager~~
needed to prevent creation of an unused self-signed certificate.
When `ingress.certManager` used it prevents creation of an unused self
signed certificate and places an optional annotation
`kubernetes.io/tls-acme: "true"` on the ingress.
While users may need this annotation for their setup, it is not required
for cert-manager to function (I didn't need it in my setup).
None, this is backward …

[bitnami/mediawiki] Don't generate certificates if cert-manager annotation is found

---

bitnami/common/Chart.yaml
bitnami/common/templates/_capabilities.tpl

This PR reverts the changes implemented at #12282 because it causes some issues described at:
- Fixes https://github.com/bitnami/charts/issues/12309
- Fixes https://github.com/bitnami/charts/issues/12338

[bitnami/common] Revert changes in HPA context from #12282

---

bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/templates/alertmanager/ingress.yaml
bitnami/kube-prometheus/templates/alertmanager/pdb.yaml
bitnami/kube-prometheus/templates/alertmanager/psp-clusterrole.yaml
bitnami/kube-prometheus/templates/alertmanager/psp-clusterrolebinding.yaml
bitnami/kube-prometheus/templates/alertmanager/psp.yaml
bitnami/kube-prometheus/templates/alertmanager/secrets.yaml
bitnami/kube-prometheus/templates/alertmanager/service.yaml

Signed-off-by: Julian Muders <julian.muders@deliveryhero.com>
Some `nindent` values in the alertmanager component of kube-prometheus had wrong values, breaking the use of `commonLabels` & `commonAnnotations`. This PR fixes these values.
`commonLabels` and `commonAnnotations` will work as expected and not fail to template.
None, bugfix.
None

[bitnami/kube-prometheus] update nindent values for alertmanager

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/README.md
bitnami/cassandra/templates/statefulset.yaml
bitnami/cassandra/values.yaml

ReadinessProbes Timeouts for Metrics Container are now configurable
On Cassandras with a huge amount of Keyspace the metrics container needs a lot of time and gets often killed by OOM.
No more unnecessary restarts.
- fixes #

[bitnami/cassandra] ReadinessProbes Timeouts for Metrics Container are now configurable

---

bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/validating-webhook-configuration.yaml

While the webhook port of the message topology operator was already changeable, the validation webhook was hardcoded to use 443 so any change would result in a failure.
Allow to change the webhook port and keep the webhook configuration in-sync.
None.
- fixes #

[bitnami/rabbitmq-cluster-operator] allow to change webhook port

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/statefulset.yaml

MongoDB chart in `architecture=replicaset` doesn't work properly in ipv6 clusters, because `mongodb-arbiter` don't start in ipv6 [mode](https://github.com/bitnami/charts/issues/12411). So there is commit that added that ability.
Added variable `MONGODB_ENABLE_IPV6` in arbiter statefulset, similar to data node 
https://github.com/bitnami/charts/blob/master/bitnami/mongodb/templates/replicaset/statefulset.yaml#L284
MongoDB will be able to work in `architecture=replicaset` in ipv6 clusters
\-
- fixes [12411](https://github.com/bitnami/charts/issues/12411)
Install chart with changes:
```bash
helm3 install my-mongo ./ --set "architecture=replicaset,image.pullPolicy=Always,enableIPv6=true" -n mongo-test
```
```bash
k get all -n mongo-test
```
```bash
NAME                             READY …
```

[bitnami/mongodb] Added variable for ipv6 in mongodb arbiter statefulset

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/receive-distributor/deployment.yaml

Fix `nodeAffinityPreset` rendering for Thanos Receive Distributor Deployment manifest. It uses `.Values.receiveDistributor.values` instead of `.Values.receiveDistributor.nodeAffinityPreset.values`
It fixes the issue with `nodeAffinity` rendering for Thanos Receive Distributor Deployment manifest.
None
None
None
Signed-off-by: Dmytro Horkhover <gd.mail.89@gmail.com>

[bitnami/thanos] Fix receive-distributor nodeAffinityPreset

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/README.md
bitnami/elasticsearch/templates/_helpers.tpl
bitnami/elasticsearch/templates/coordinating/statefulset.yaml
bitnami/elasticsearch/templates/coordinating/svc-headless.yaml
bitnami/elasticsearch/templates/data/statefulset.yaml
bitnami/elasticsearch/templates/data/svc-headless.yaml
bitnami/elasticsearch/templates/ingest/statefulset.yaml
bitnami/elasticsearch/templates/ingest/svc-headless.yaml
bitnami/elasticsearch/templates/master/statefulset.yaml
bitnami/elasticsearch/templates/master/svc-headless.yaml
bitnami/elasticsearch/templates/tls-secret.yaml
bitnami/elasticsearch/values.yaml

Since chart version 18.0.0 the naming of the node services changed **from**: 
```{{ include "elasticsearch.coordinating.fullname" . }}```  
**to:** 
```{{ printf "%s-hl" (include "elasticsearch.coordinating.fullname" .) | trunc 63 | trimSuffix "-" }}```
If one has a cluster running with the latest 17.x.x chart he will not be able to perform a rolling cluster upgrade to chart version >=18.0.0. This is because of kubernetes does not allow to change the servicename in a statefulset once set. Adressed in this issue #11505
This change intruduces the value ```servicenameOverride``` for each node section (**coordinating**, **data**, **master**, **ingest**) which could be used to override the *-hl* suffix.
You can run a rolling cluster upgrade  to elasticserach version >= 8 without any problems …

[bitnami/elasticsearch] Configurable servicenames

---

bitnami/mysql/Chart.yaml
bitnami/mysql/values.yaml

Changed `bind-address` to * in helm values in primary/secondary.configuration
This allow us to run mysql in both ipv4 and ipv6 modes by default.
\-
- fixes [12442](https://github.com/bitnami/charts/issues/12442)
I've tested changes in both EKS ipv4 and ipv6 clusters, it works well.

[bitnami/mysql]  change default bind-address to * in mysql configuration (for enabling ipv6)

---

.github/workflows/cd-pipeline.yaml
.vib/mariadb-galera/goss/goss.yaml
.vib/mariadb-galera/goss/vars.yaml
.vib/mariadb-galera/vib-publish.json
.vib/mariadb-galera/vib-verify.json

The main objective of this PR is to publish our Bitnami MariaDB-Galera Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
Tested in https://github.com/joancafom/charts/pull/78

[bitnami/mariadb-galera] Add tests and publishing using VIB

---

bitnami/thanos/Chart.yaml
bitnami/thanos/templates/bucketweb/deployment.yaml
bitnami/thanos/templates/compactor/deployment.yaml
bitnami/thanos/templates/query-frontend/deployment.yaml
bitnami/thanos/templates/query/deployment.yaml
bitnami/thanos/templates/receive-distributor/deployment.yaml
bitnami/thanos/templates/receive/statefulset.yaml
bitnami/thanos/templates/ruler/statefulset.yaml
bitnami/thanos/templates/storegateway/statefulset-sharded.yaml
bitnami/thanos/templates/storegateway/statefulset.yaml

[bitnami/thanos] Use custom probes if given

---

bitnami/wordpress/Chart.yaml
bitnami/wordpress/templates/deployment.yaml

[bitnami/wordpress] Use custom probes if given

---

bitnami/tomcat/Chart.yaml
bitnami/tomcat/templates/_pod.tpl

[bitnami/tomcat] Use custom probes if given

---

bitnami/schema-registry/Chart.yaml
bitnami/schema-registry/templates/statefulset.yaml

[bitnami/schema-registry] Use custom probes if given

---

bitnami/spring-cloud-dataflow/Chart.yaml
bitnami/spring-cloud-dataflow/templates/server/deployment.yaml
bitnami/spring-cloud-dataflow/templates/skipper/deployment.yaml

[bitnami/spring-cloud-dataflow] Use custom probes if given

---

bitnami/redis-cluster/Chart.yaml
bitnami/redis-cluster/templates/redis-statefulset.yaml

Without this change, in order to use a custom probe, the user has to specify the probe parameters, and also must specify for the original probe "enabled: false".
Issue: #12354
Signed-off-by: Orgad Shaneh <orgad.shaneh@audiocodes.com>

[bitnami/redis-cluster] Use custom probes if given

---

template/CHART_NAME/templates/daemonset.yaml
template/CHART_NAME/templates/deployment.yaml
template/CHART_NAME/templates/statefulset.yaml

Without this change, in order to use a custom probe, the user has to specify the probe parameters, and also must specify for the original probe "enabled: false".
Issue: #12354
Signed-off-by: Orgad Shaneh <orgad.shaneh@audiocodes.com>

[template] Use custom probes if given

---

bitnami/osclass/Chart.yaml
bitnami/osclass/templates/deployment.yaml

[bitnami/osclass] Use custom probes if given

---

bitnami/node/Chart.yaml
bitnami/node/templates/deployment.yaml

[bitnami/node] Use custom probes if given

---

bitnami/logstash/Chart.yaml
bitnami/logstash/templates/sts.yaml

[bitnami/logstash] Use custom probes if given

---

bitnami/jupyterhub/Chart.yaml
bitnami/jupyterhub/templates/hub/deployment.yaml
bitnami/jupyterhub/templates/proxy/deployment.yaml

[bitnami/jupyterhub] Use custom probes if given

---

bitnami/nginx-ingress-controller/Chart.yaml
bitnami/nginx-ingress-controller/templates/controller-daemonset.yaml
bitnami/nginx-ingress-controller/templates/controller-deployment.yaml
bitnami/nginx-ingress-controller/templates/default-backend-deployment.yaml

[bitnami/nginx-ingress-controller] Use custom probes if given

---

bitnami/nats/Chart.yaml
bitnami/nats/templates/deployment.yaml
bitnami/nats/templates/statefulset.yaml

[bitnami/nats] Use custom probes if given

---

bitnami/elasticsearch/Chart.yaml
bitnami/elasticsearch/templates/coordinating/statefulset.yaml
bitnami/elasticsearch/templates/data/statefulset.yaml
bitnami/elasticsearch/templates/ingest/statefulset.yaml
bitnami/elasticsearch/templates/master/statefulset.yaml
bitnami/elasticsearch/templates/metrics/deployment.yaml

[bitnami/elasticsearch] Use custom probes if given

---

bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/deployment.yaml

[bitnami/influxdb] Use custom probes if given

---

bitnami/mongodb/Chart.yaml
bitnami/mongodb/templates/arbiter/statefulset.yaml
bitnami/mongodb/templates/hidden/statefulset.yaml
bitnami/mongodb/templates/replicaset/statefulset.yaml
bitnami/mongodb/templates/standalone/dep-sts.yaml

[bitnami/mongodb] Use custom probes if given

---

bitnami/jenkins/Chart.yaml
bitnami/jenkins/templates/deployment.yaml

[bitnami/jenkins] Use custom probes if given

---

bitnami/kube-prometheus/Chart.yaml
bitnami/kube-prometheus/templates/blackbox-exporter/deployment.yaml
bitnami/kube-prometheus/templates/prometheus-operator/deployment.yaml

[bitnami/kube-prometheus] Use custom probes if given

---

bitnami/magento/Chart.yaml
bitnami/magento/templates/deployment.yaml

[bitnami/magento] Use custom probes if given

---

bitnami/mysql/Chart.yaml
bitnami/mysql/templates/primary/statefulset.yaml
bitnami/mysql/templates/secondary/statefulset.yaml

[bitnami/mysql] Use custom probes if given

---

bitnami/mongodb-sharded/Chart.yaml
bitnami/mongodb-sharded/templates/config-server/config-server-statefulset.yaml
bitnami/mongodb-sharded/templates/mongos/mongos-dep-sts.yaml
bitnami/mongodb-sharded/templates/shard/shard-arbiter-statefulset.yaml
bitnami/mongodb-sharded/templates/shard/shard-data-statefulset.yaml

[bitnami/mongodb-sharded] Use custom probes if given

---

bitnami/owncloud/Chart.yaml
bitnami/owncloud/templates/deployment.yaml

[bitnami/owncloud] Use custom probes if given

---

bitnami/rabbitmq-cluster-operator/Chart.yaml
bitnami/rabbitmq-cluster-operator/templates/cluster-operator/deployment.yaml
bitnami/rabbitmq-cluster-operator/templates/messaging-topology-operator/deployment.yaml

[bitnami/rabbitmq-cluster-operator] Use custom probes if given

---

bitnami/sealed-secrets/Chart.yaml
bitnami/sealed-secrets/templates/deployment.yaml

[bitnami/sealed-secrets] Use custom probes if given

---

bitnami/odoo/Chart.yaml
bitnami/odoo/templates/deployment.yaml

[bitnami/odoo] Use custom probes if given

---

bitnami/parse/Chart.yaml
bitnami/parse/templates/dashboard-deployment.yaml
bitnami/parse/templates/server-deployment.yaml

[bitnami/parse] Use custom probes if given

---

bitnami/tensorflow-resnet/Chart.yaml
bitnami/tensorflow-resnet/templates/deployment.yaml

[bitnami/tensorflow-resnet] Use custom probes if given

---

bitnami/wavefront-hpa-adapter/Chart.yaml
bitnami/wavefront-hpa-adapter/templates/custom-metrics-apiserver-deployment.yaml

[bitnami/wavefront-hpa-adapter] Use custom probes if given

---

bitnami/postgresql-ha/Chart.yaml
bitnami/postgresql-ha/templates/pgpool/deployment.yaml
bitnami/postgresql-ha/templates/postgresql/statefulset.yaml

[bitnami/postgresql-ha] Use custom probes if given

---

bitnami/wildfly/Chart.yaml
bitnami/wildfly/templates/deployment.yaml

[bitnami/wildfly] Use custom probes if given

---

bitnami/haproxy/Chart.yaml
bitnami/haproxy/templates/deployment.yaml

[bitnami/haproxy] Use custom probes if given

---

bitnami/redis/Chart.yaml
bitnami/redis/templates/master/application.yaml
bitnami/redis/templates/replicas/statefulset.yaml
bitnami/redis/templates/sentinel/statefulset.yaml

[bitnami/redis] Use custom probes if given

---

bitnami/spark/Chart.yaml
bitnami/spark/templates/statefulset-master.yaml
bitnami/spark/templates/statefulset-worker.yaml

[bitnami/spark] Use custom probes if given

---

bitnami/wordpress-intel/Chart.yaml
bitnami/wordpress-intel/templates/deployment.yaml

[bitnami/wordpress-intel] Use custom probes if given

---

bitnami/mediawiki/Chart.yaml
bitnami/mediawiki/templates/deployment.yaml

[bitnami/mediawiki] Use custom probes if given

---

bitnami/moodle/Chart.yaml
bitnami/moodle/templates/deployment.yaml

[bitnami/moodle] Use custom probes if given

---

bitnami/nginx/Chart.yaml
bitnami/nginx/templates/deployment.yaml

[bitnami/nginx] Use custom probes if given

---

bitnami/nginx-intel/Chart.yaml
bitnami/nginx-intel/templates/deployment.yaml

[bitnami/nginx-intel] Use custom probes if given

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/statefulset.yaml

[bitnami/keycloak] Use custom probes if given

---

bitnami/kiam/Chart.yaml
bitnami/kiam/templates/agent/agent-daemonset.yaml
bitnami/kiam/templates/server/server-daemonset.yaml
bitnami/kiam/templates/server/server-deployment.yaml

[bitnami/kiam] Use custom probes if given

---

bitnami/minio/Chart.yaml
bitnami/minio/templates/distributed/statefulset.yaml
bitnami/minio/templates/gateway/deployment.yaml
bitnami/minio/templates/standalone/deployment.yaml

[bitnami/minio] Use custom probes if given

---

bitnami/wavefront/Chart.yaml
bitnami/wavefront/templates/proxy-deployment.yaml

[bitnami/wavefront] Use custom probes if given

---

bitnami/drupal/Chart.yaml
bitnami/drupal/templates/deployment.yaml

[bitnami/drupal] Use custom probes if given

---

bitnami/argo-workflows/Chart.yaml
bitnami/argo-workflows/templates/controller/deployment.yaml
bitnami/argo-workflows/templates/server/deployment.yaml

[bitnami/argo-workflows] Use custom probes if given

---

bitnami/discourse/Chart.yaml
bitnami/discourse/templates/deployment.yaml

[bitnami/discourse] Use custom probes if given

---

bitnami/kafka/Chart.yaml
bitnami/kafka/templates/statefulset.yaml

[bitnami/kafka] Use custom probes if given

---

bitnami/kibana/Chart.yaml
bitnami/kibana/templates/deployment.yaml

[bitnami/kibana] Use custom probes if given

---

bitnami/joomla/Chart.yaml
bitnami/joomla/templates/deployment.yaml

[bitnami/joomla] Use custom probes if given

---

bitnami/harbor/Chart.yaml
bitnami/harbor/templates/chartmuseum/chartmuseum-dpl.yaml
bitnami/harbor/templates/core/core-dpl.yaml
bitnami/harbor/templates/exporter/exporter-dpl.yaml
bitnami/harbor/templates/jobservice/jobservice-dpl.yaml
bitnami/harbor/templates/nginx/deployment.yaml
bitnami/harbor/templates/notary/notary-server.yaml
bitnami/harbor/templates/notary/notary-signer.yaml
bitnami/harbor/templates/portal/portal-dpl.yaml
bitnami/harbor/templates/registry/registry-dpl.yaml
bitnami/harbor/templates/trivy/trivy-sts.yaml

[bitnami/harbor] Use custom probes if given

---

bitnami/fluentd/Chart.yaml
bitnami/fluentd/templates/aggregator-statefulset.yaml
bitnami/fluentd/templates/forwarder-daemonset.yaml

[bitnami/fluentd] Use custom probes if given

---

bitnami/kubeapps/Chart.yaml
bitnami/kubeapps/templates/dashboard/deployment.yaml
bitnami/kubeapps/templates/frontend/deployment.yaml
bitnami/kubeapps/templates/kubeappsapis/deployment.yaml
bitnami/kubeapps/templates/kubeops/deployment.yaml

[bitnami/kubeapps] Use custom probes if given

---

bitnami/matomo/Chart.yaml
bitnami/matomo/templates/deployment.yaml

[bitnami/matomo] Use custom probes if given

---

bitnami/apache/Chart.yaml
bitnami/apache/templates/deployment.yaml

[bitnami/apache] Use custom probes if given

---

bitnami/concourse/Chart.yaml
bitnami/concourse/templates/web/deployment.yaml
bitnami/concourse/templates/worker/deployment.yaml
bitnami/concourse/templates/worker/statefulset.yaml

[bitnami/concourse] Use custom probes if given

---

bitnami/airflow/Chart.yaml
bitnami/airflow/templates/config/configmap.yaml
bitnami/airflow/templates/web/deployment.yaml
bitnami/airflow/templates/worker/statefulset.yaml

[bitnami/airflow] Use custom probes if given

---

bitnami/aspnet-core/Chart.yaml
bitnami/aspnet-core/templates/deployment.yaml

[bitnami/aspnet-core] Use custom probes if given

---

bitnami/metallb/Chart.yaml
bitnami/metallb/templates/controller/deployment.yaml
bitnami/metallb/templates/speaker/daemonset.yaml

[bitnami/metallb] Use custom probes if given

---

bitnami/opencart/Chart.yaml
bitnami/opencart/templates/deployment.yaml

[bitnami/opencart] Use custom probes if given

---

bitnami/memcached/Chart.yaml
bitnami/memcached/templates/deployment.yaml
bitnami/memcached/templates/statefulset.yaml

[bitnami/memcached] Use custom probes if given

---

bitnami/geode/Chart.yaml
bitnami/geode/templates/locator/statefulset.yaml
bitnami/geode/templates/server/statefulset.yaml

[bitnami/geode] Use custom probes if given

---

bitnami/ejbca/Chart.yaml
bitnami/ejbca/templates/deployment.yaml

[bitnami/ejbca] Use custom probes if given

---

bitnami/cassandra/Chart.yaml
bitnami/cassandra/templates/statefulset.yaml

[bitnami/cassandra] Use custom probes if given

---

.vib/ghost/cypress/cypress/integration/ghost_spec.js

The changes introduced in https://github.com/bitnami/charts/pull/12478 are not enough for the tests to pass consistently.
Although the tests passed in the PR, during most executions the tests are failing because the Ghost post creation fails to wait for the 'Draft - Saved' status twice.
The timeout deadline is probably being exceeded because the post contains an image and the server size is not big enough to complete the test in under 60seconds. 
For reference, the 'create-page' test takes about 27 seconds and does not include an image.
Unlike the 'create-page' test, the 'create-post' test won't fail if a wait for 'Draft saved' status is not performed, therefore this PR removes them.
I initially added the wait to be consistent with the …

[bitnami/ghost] cypress: Remove 'wait for save' during post creation test

---

bitnami/ghost/Chart.yaml
bitnami/ghost/templates/deployment.yaml

[bitnami/ghost] Use custom probes if given

---

bitnami/zookeeper/Chart.yaml
bitnami/zookeeper/templates/statefulset.yaml

[bitnami/zookeeper] Use custom probes if given

---

bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/templates/webhook/deployment.yaml

[bitnami/cert-manager] Use custom probes if given

---

bitnami/etcd/Chart.yaml
bitnami/etcd/templates/statefulset.yaml

[bitnami/etcd] Use custom probes if given

---

bitnami/pinniped/Chart.yaml
bitnami/pinniped/templates/concierge/deployment.yaml
bitnami/pinniped/templates/supervisor/deployment.yaml

[bitnami/pinniped] Use custom probes if given

---

bitnami/kong/Chart.yaml
bitnami/kong/templates/dep-ds.yaml

[bitnami/kong] Use custom probes if given

---

bitnami/kube-state-metrics/Chart.yaml
bitnami/kube-state-metrics/templates/deployment.yaml

[bitnami/kube-state-metrics] Use custom probes if given

---

bitnami/node-exporter/Chart.yaml
bitnami/node-exporter/templates/daemonset.yaml

[bitnami/node-exporter] Use custom probes if given

---

bitnami/prestashop/Chart.yaml
bitnami/prestashop/templates/deployment.yaml

[bitnami/prestashop] Use custom probes if given

---

bitnami/wavefront-prometheus-storage-adapter/Chart.yaml
bitnami/wavefront-prometheus-storage-adapter/templates/deployment.yaml

[bitnami/wavefront-prometheus-storage-adapter] Use custom probes if given

---

bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/templates/ruler/statefulset.yaml

Previously, the the deployment of the ruler statefulset was determined by `.Values.indexGateway.enabled` and not `.Values.ruler.enabled` (this is the correct one).
This PR fixes that
```
{{- if .Values.indexGateway.enabled }}
{{- if .Values.ruler.enabled }}
```
Ruler statefulset is not deployed when indexGateway is enabled but ruler is not

[bitnami/grafana-loki] Deploy ruler statefulset if ruler.enabled is true

---

bitnami/redis/Chart.yaml
bitnami/redis/README.md
bitnami/redis/templates/servicemonitor.yaml
bitnami/redis/values.yaml

This exposes `metrics.serviceMonitor.podTargetLabels` to allow setting which labels from the pod get added to the metrics that the servicemonitor exports.
This is what we need for https://gitlab.com/gitlab-com/gl-infra/k8s-workloads/tanka-deployments/-/merge_requests/519
This allows configuring the servicemonitor with podTargetLabels, as documented here: https://docs.openshift.com/container-platform/4.10/rest_api/monitoring_apis/servicemonitor-monitoring-coreos-com-v1.html
n/a
n/a
n/a

[bitnami/redis] Make podTargetLabels configurable on servicemonitor

---

bitnami/influxdb/Chart.yaml
bitnami/influxdb/templates/deployment.yaml

This change improves volume permissions container behavior and adds feature of changing permission to `/bitnami/influxdb`.
Just adding one more chmod and not touching other code
No
Not opened an issue, providing PR instead of issue opening :)
Generally it fixes the bug with initial starting influxdb even with volume permissions container enabled. Reproduced it on EKS with EBS CSI driver storage class.
```
influxdb 13:05:31.76 
influxdb 13:05:31.76 Welcome to the Bitnami influxdb container
influxdb 13:05:31.77 Subscribe to project updates by watching https://github.com/bitnami/bitnami-docker-influxdb
influxdb 13:05:31.77 Submit issues and feature requests at https://github.com/bitnami/bitnami-docker-influxdb/issues
influxdb 13:05:31.77 
influxdb 13:05:31.77 INFO  ==> ** Starting InfluxDB …
```

[bitnami/influxdb] Add chown for data dir, not only children

---

bitnami/cert-manager/Chart.yaml
bitnami/cert-manager/templates/webhook/mutating-webhook.yaml
bitnami/cert-manager/templates/webhook/validating-webhook.yaml

Signed-off-by: Benoit Pourre <benoit.pourre@gmail.com>
Add missing mutating and validateing webooks to cert-manager.
These hooks exist in the official cert-manager Helm chart, but not in Bitnami's.
Without these webhooks, any external plugin for cert-manager will fail to approve its certificates.
Be able to use external plugins for cert-manager.
None
- fixes #12235
NA

[bitnami/cert-manager] Add missing webhooks to fix external plugin issues

---

.github/workflows/assign-labels.yml

* Human friendly name for `assign-label` job in assign-label workflow
It avoids a manual assignment during triage
None
Follow up: #12683

[bitnami/charts] Human friendly name for assign-label job

---

bitnami/keycloak/Chart.yaml
bitnami/keycloak/templates/servicemonitor.yaml

Fix reference cycle in ServiceMonitor template. In #12268 a change was introduced, that merges single endpoints for a service monitor with default values. The default values are part of a parent key of the endpoints, which creates a reference cycle. This cycle is only a problem in `helm upgrade/install`, not in `helm template`.
_Bugfix, see description._
no limitations known
- fixes #12316

[bitnami/keycloak] Break reference cycle in ServiceMonitor template

---

bitnami/grafana-tempo/Chart.yaml
bitnami/grafana-tempo/templates/compactor/deployment.yaml
bitnami/grafana-tempo/templates/distributor/deployment.yaml
bitnami/grafana-tempo/templates/ingester/statefulset.yaml
bitnami/grafana-tempo/templates/metrics-generator/deployment.yaml
bitnami/grafana-tempo/templates/querier/deployment.yaml
bitnami/grafana-tempo/templates/query-frontend/deployment.yaml
bitnami/grafana-tempo/templates/vulture/deployment.yaml

[bitnami/grafana-tempo] Use custom probes if given

---

bitnami/postgresql/Chart.yaml
bitnami/postgresql/templates/primary/statefulset.yaml
bitnami/postgresql/templates/read/statefulset.yaml

[bitnami/postgresql] Use custom probes if given

---

bitnami/contour/Chart.yaml
bitnami/contour/templates/envoy/servicemonitor.yaml

Signed-off-by: Paul Nicholson <brenix@gmail.com>
Includes the values of the `metrics.serviceMonitor.labels` as part of the envoy servicemonitor.
Currently, these labels are only rendered as part of the contour servicemonitor. Given the structure of the values, a user would expect the labels to be applied to any of the servicemonitors created.
Allows configuring labels across all servicemonitors, not just for Contour. For our use case, this allows us to label both servicemonitors so that they can be discovered by our prometheus.
Some users may want more control over individual servicemonitors. For example scraping contour from one prometheus, while envoy on another.

[bitnami/contour] Include labels in envoy servicemonitor

---

.github/workflows/cd-pipeline.yml

Add Thanos to the list of assets published using VMware Image Builder.
Increased pool of assets completely handled by VMware Image Builder.
None
NA
NA

[bitnami/thanos] Use VIB to publish Thanos

---

.github/workflows/assign-asset-label.yml

Rename `[Support] Assign asset label` worflow file and fix regular expression.
In some automated PRs the workflow is not assigning the label:
* #12734
* #12731
Follow up: #12683

[bitnami/*] Rename Assign Asset Label workflow file and remove unnecessary '/'

---

bitnami/nginx-intel/Chart.yaml

Force changes in https://github.com/bitnami/charts/commit/2c1af791d03ec80827585e09f2b2e25c2509d794 to be published.
The asset is up-to-date in our helm index.
None
Related to https://github.com/bitnami/charts/pull/12748
We have been experiencing intermittent failures in our publishing pipelines, which made the index to miss some updates from charts.

[bitnami/nginx-intel] Force new version publishing

---

bitnami/concourse/Chart.yaml

Force changes in https://github.com/bitnami/charts/commit/876854198ad92bcb60b4524c2660e4ba803a2733 to be published.
The asset is up-to-date in our helm index.
None
Related to https://github.com/bitnami/charts/pull/12748
We have been experiencing intermittent failures in our publishing pipelines, which made the index to miss some updates from charts.

[bitnami/concourse] Force new version publishing

---

.github/workflows/cd-pipeline.yml
.vib/grafana-operator/cypress/cypress.json
.vib/grafana-operator/cypress/cypress/fixtures/dashboards.json
.vib/grafana-operator/cypress/cypress/fixtures/datasources.json
.vib/grafana-operator/cypress/cypress/fixtures/test-dashboard.json
.vib/grafana-operator/cypress/cypress/integration/grafana_operator_spec.js
.vib/grafana-operator/cypress/cypress/support/commands.js
.vib/grafana-operator/cypress/cypress/support/index.js
.vib/grafana-operator/cypress/cypress/support/utils.js
.vib/grafana-operator/goss/goss.yaml
.vib/grafana-operator/goss/vars.yaml
.vib/grafana-operator/vib-publish.json
.vib/grafana-operator/vib-verify.json

The main objective of this PR is to publish our Bitnami Grafana Operator Helm Chart using VMware Image Builder. In order to do that, several changes are included:
NA
Tested in https://github.com/FraPazGal/charts/pull/117

[bitnami/grafana-operator] Add tests and publishing using VIB

---

bitnami/mongodb-sharded/Chart.yaml

Force changes in https://github.com/bitnami/charts/commit/7e73521cbb6fd948a018f983125f5154157ed3c0 to be published.
The asset is up-to-date in our helm index.
None
Related to https://github.com/bitnami/charts/pull/12748
We have been experiencing intermittent failures in our publishing pipelines, which made the index to miss some updates from charts.

[bitnami/mongodb-sharded] Force new version publishing

---

bitnami/suitecrm/Chart.yaml
bitnami/suitecrm/templates/deployment.yaml

[bitnami/suitecrm] Use custom probes if given

---

bitnami/grafana-loki/Chart.yaml
bitnami/grafana-loki/templates/compactor/deployment.yaml
bitnami/grafana-loki/templates/distributor/deployment.yaml
bitnami/grafana-loki/templates/gateway/deployment.yaml
bitnami/grafana-loki/templates/index-gateway/statefulset.yaml
bitnami/grafana-loki/templates/ingester/statefulset.yaml
bitnami/grafana-loki/templates/promtail/daemonset.yaml
bitnami/grafana-loki/templates/querier/statefulset.yaml
bitnami/grafana-loki/templates/query-frontend/deployment.yaml
bitnami/grafana-loki/templates/query-scheduler/deployment.yaml
bitnami/grafana-loki/templates/ruler/statefulset.yaml
bitnami/grafana-loki/templates/table-manager/deployment.yaml

[bitnami/grafana-loki] Use custom probes if given

---

bitnami/consul/Chart.yaml
bitnami/consul/templates/statefulset.yaml

[bitnami/consul] Use custom probes if given
